### ISSUE TITLE
Opencensus tracer using Zipkin exporter to send spans to jaeger throws error

### ISSUE THREAD

**Issue by mohit-a21** [envoyproxy/envoy#10024]
**Bug Template**

*Title*: *Opencensus tracer using Zipkin exporter to send spans to jaeger throws error*

*Description*:
> When using Opencensus tracer for tracing, if Zipkin exporter is configured to send spans to a jaeger backend following error is thrown:
`Unable to process request body: wrong ipv4`
On further investigation, it seems local endpoint information of Zipkin spans has issues.
There process ipv4 is being set as ::1 (loopback ipv6). 

 The issue seems to be here:
```
if (oc_config.zipkin_exporter_enabled()) {
    ::opencensus::exporters::trace::ZipkinExporterOptions opts(oc_config.zipkin_url());
    opts.service_name = local_info_.clusterName();
    ::opencensus::exporters::trace::ZipkinExporter::Register(opts);
  }
```
Here, since opts doesn't have `af_type` set to either ` kIpv4` or `kIpv6`, it goes into this weird state. 

*Repro steps*:
> Following is the config file used to run envoy:
```
static_resources:
  listeners:
  - name: listener_ingress
    traffic_direction: inbound
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 15006
    listener_filters:
      - name: "envoy.listener.http_inspector"
        typed_config: {}
      - name: "envoy.listener.original_dst"
        typed_config: {}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          preserve_external_request_id: true
          server_header_transformation: PASS_THROUGH
          tracing: {}
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/echo"
                route:
                  cluster: service_echo
              - match:
                  prefix: "/"
                route:
                  cluster: service_test
          http_filters:
            - name: envoy.router
              config:
                suppress_envoy_headers: true
  clusters:
  - name: passthrough
    type: ORIGINAL_DST
    connect_timeout: 10s
    lb_policy: ORIGINAL_DST_LB
  - name: service_test
    connect_timeout: 25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_echo
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 8080
tracing:
  http:
    name: envoy.tracers.opencensus
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v2.OpenCensusConfig
      trace_config:
        max_number_of_attributes: 500
      zipkin_exporter_enabled: true
      zipkin_url: http://127.0.0.1:9411/api/v2/spans
      incoming_trace_context:
      - trace_context
      - grpc_trace_bin
      outgoing_trace_context:
      - trace_context
      - grpc_trace_bin
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 15009
```
Is there a way to define the address family option for the process?
