### ISSUE TITLE
Enable dynamic configuration for "xds-grpc" cluster

### ISSUE THREAD

**Issue by seflerZ** [envoyproxy/envoy#10059]
*Description*:
In Envoy with Istio scenario, the back end xDS server Pilot is configured through "envoy_bootstrap_v2.json" like this:
```yaml
{
        "name": "xds-grpc",
        "type": "STATIC",
        "dns_lookup_family": "V4_ONLY",
        "connect_timeout": "{{ .connect_timeout }}",
        "lb_policy": "RANDOM",
        ...
        "hosts": {{ .pilot_grpc_address_group }},
        ...
}
```
However, this is a static address and can't not be changed any longer. If we want to migrate the Pilot address, the Envoy has to reboot to reload the new Pilot address. I'm wandering if there is any way to dynamically change this address. Maybe by enabling configure file watching and reloading is a good practice.

**Comment by seflerZ** [comment]
We've decided to use pilot-agent to deploy other Envoy and hot swap the network traffic. Still, I hope to enable dynamic reloading because it's much simpler and easier.

**Comment by mattklein123** [comment]
Is there any reason you can't use DNS? This is generally how we would recommend solving this problem.

**Comment by seflerZ** [comment]
> Is there any reason you can't use DNS? This is generally how we would recommend solving this problem.

1. The DNS change got a TTL and usually a long latency and may be cached by operating system.
2. The DNS doesn't have any mechanism to notify the Envoy to switch the IP
3. Since the Envoy xDS ADS gRPC is usually a keep-alive connection. There is no way to disconnect and reconnect except restart Envoy.
4. DNS doesn't got a healthy check, so it's less effective when establishing connection.
5. If you got a very large Pilot cluster (such as 500+) list, it will be hard to maintenance.

Thanks for helping.

**Comment by mattklein123** [comment]
Yes those are reasonable points. I can imagine a few different ways of solving this:
1) Using filesystem EDS for this case, and fixing the init order so that filesystem EDS is a special case which comes before non-filesystem EDS.
2) Some new type of cluster in which the hosts are read from the filesystem and/or updatable via admin endpoint (or possibly some variant of static cluster which allows this).

Full design proposals welcome. Please do not implement any code before design proposal approval. Thank you!

**Comment by bcba25** [comment]
@seflerZ Hi! Am I right to say that this configuration will not work for gRPC currently ? I've been trying to make xds configuration for my envoy and consul but end up with no solution.
```
- name: app_service
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      type: EDS
      eds_cluster_config:
        eds_config:
          api_config_source:
            #api_type: GRPC
            #cluster_names: [xds_cluster]
            api_type: GRPC
            grpc_services:
              envoy_grpc:
                cluster_name: xds_cluster
    - name: xds_cluster
      connect_timeout: 0.25s
      type: STATIC #STATIC
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8053 }}]
```
