### ISSUE TITLE
router_check_tool can't see response_headers_to_add

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#10072]
*Title*: response_headers_to_add not available to router check tool 

*Description*:
I was trying to verify a direct response route by checking the content-type and content-length headers, but these headers aren't present during validation.

```
- input:
    authority: www.foo.com
    method: GET
    path: /robots.txt
    ssl: true
  test_name: /robots.txt
  validate:
    cluster_name: ''
    host_rewrite: ''
    path_redirect: https://www.foo.com/robots.txt
    path_rewrite: ''
    virtual_cluster_name: ''
    virtual_host_name: ''
    header_fields:
     - key: 'content-length'
       value: '27'
     - key: 'content-type'
       value: 'text/plain'
```
