### ISSUE TITLE
Forward to Host header

### ISSUE THREAD

**Issue by xpepermint** [envoyproxy/envoy#10075]
This is a question. I'd like someone to help me write a configuration that would forward requests to hosts based on `Host` header (reverse proxy). We could test this from localhost with this command:

```
$ curl -H 'Host: target.com' http://localhost:5000
```

Here is my setup:

* I use Docker for Mac (local development setup).
* I deployed two echo http servers `echo1` and `echo2` (returns just Hello world 1/2).
* I also created a custom network where containers can communicate with each other and I attached `echo1` and `echo2` to the new network.
```
$ docker network create proxytest
$ docker network connect proxytest echo1
$ docker network connect proxytest echo2
$ docker exec -it echo1 /bin/sh -c 'curl http://echo2:8080'
$ docker exec -it echo2 /bin/sh -c 'curl http://echo1:8080'
```

Now I need to deploy an envoy that would be exposed to localhost at some port (e.g. 5000) and would route traffic to these two echo servers based on `Host` header. The configuration must not be static so Envoy should dynamically route based on request's `Host:` header. The effect would be the same as in K8S setup where this already works.

```
$ curl -H 'Host: echo1' http://localhost:5000
$ curl -H 'Host: echo2' http://localhost:5000
```

What I currently have is this configuration:

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 5000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: dynamic_forward_proxy_cluster
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.router
  clusters:
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
```

I deployed this to Docker and connected it with my custom network. The `curl` command works for public domains (e.g. google.com), but for local names throws `no healthy upstream` (e.g. echo1).

Thanks for all the hints.
