### ISSUE TITLE
Forward HTTPS without SSL termination

### ISSUE THREAD

**Issue by alexEnsimag** [envoyproxy/envoy#10080]
Hi,

I am trying to configure Envoy to forward HTTPS traffic without doing SSL termination. Is it something possible?

Scenario:
```
export HTTPS_PROXY=http://<envoy-ip>:8080 
curl -v https://mydomain.com 
```
Currently, Envoy returns a Bad Request when curl performs HTTP CONNECT.
Is it not supported yet: https://github.com/envoyproxy/envoy/issues/1451 ?
Or not supported at all: https://github.com/envoyproxy/envoy/issues/8213 ?
Is it doable using the TCP proxy?

Here is my configuration:
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_https
              access_log:
                - name: envoy.file_access_log
                  config:
                    path: /dev/stdout
              route_config:
                name: myroute
                virtual_hosts:
                - name: myhost
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: mycluster
              http_filters:
              - name: envoy.router
  clusters:
    - name: mycluster
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: mycluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: mydomain.com
                      port_value: 443
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

```

Thanks!
