### ISSUE TITLE
GRPC Web Error Handling

### ISSUE THREAD

**Issue by codebreach** [envoyproxy/envoy#10128]
*Title*: GRPC Web served with `http_filters: [{name: envoy.grpc_web}]` results in CORS issues when non returning success

*Description*:
Issue as seen in Chrome:
```
Access to fetch at 'https://REDACTED/SERVICE_NAME/METHOD_NAME' from origin 'https://REDACTED' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
This GRPC API is returning a non success response. For success response it continues to work as expected.
Sample non success response when hitting GRPC Directly:
```
connecting to localhost:50076
Received trailing metadata from server:
REDACTED
Rpc failed with status code 13, error message: Upstream Error: File contains corrupted data.
```

Response Headers (success):
```
accept-encoding: identity,gzip
access-control-allow-origin: https://REDACTED_FE_URL
access-control-expose-headers: grpc-status,grpc-message
content-type: application/grpc-web+proto
date: Fri, 21 Feb 2020 08:53:13 GMT
grpc-accept-encoding: identity,deflate,gzip
server: nginx/1.17.7
status: 200
strict-transport-security: max-age=15724800; includeSubDomains
x-envoy-upstream-service-time: 22289
```
Response Headers (failure):
```
content-length: 559
content-type: text/html
date: Fri, 21 Feb 2020 08:53:21 GMT
server: nginx/1.17.7
status: 502
strict-transport-security: max-age=15724800; includeSubDomains
```
envoy config:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 51051 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: grpc-backend-services
                  max_grpc_timeout: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: grpc-status,grpc-message,grpc-status-details-bin,grpc-status-details-text
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: grpc-backend-services
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: UPSTREAM_HOST #CONFIGURE
        port_value: UPSTREAM_PORT #CONFIGURE

```
