### ISSUE TITLE
With different routes on the same router you don't get the methods

### ISSUE THREAD

**Issue by EdwinBetanc0urt** [envoyproxy/envoy#10146]
When using different routes to redirect to the clusters, it generates the following message Method not found: access-route/access.AccessService/GetMenuAndChild. Code: 12.

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: {
      address: 0.0.0.0,
      port_value: 9902
    }

static_resources:
  listeners:
  - name: local_listener
    address:
      socket_address: {
        address: 0.0.0.0,
        # port of this proxy route
        port_value: 8989
      }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route_access
            virtual_hosts:
            - name: local_access_service
              domains: ["*"]
              routes:
              - match: {
                  prefix: "/access-route"
                }
                route: {
                  cluster: access_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/dictionary-route"
                }
                route: {
                  cluster: dictionary_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/businessdata-route"
                }
                route: {
                  cluster: business_data_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/enrollment-route"
                }
                route: {
                  cluster: enrollment_cluster,
                  max_grpc_timeout: 0s
                }
              cors:
                allow_origin_string_match:
                  - safe_regex:
                      google_re2: {}
                      regex: \*
                # This directive holds the list of HTTP request methods. If the
                # requests are more than one then the request are separated by commas.
                allow_methods: GET, PUT, DELETE, POST, PATCH, OPTIONS
                # is a response-type header that is used to indicate the HTTP headers.
                allow_headers: authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                # It specifies how many maximum seconds can the result be cached. Note: If -1 is present then caching is disabled.
                max_age: "1728000"
                # Is a response header that is used to expose the headers that have been mentioned in it.
                expose_headers: custom-header-1,grpc-status,grpc-message,x-envoy-upstream-service-time
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router

  clusters:
  - name: access_cluster
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: access_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # replace the 'localhost' address with your access host address
                address: localhost
                # it is the default port, unless the server port is changed it is recommended not to change
                # https://github.com/erpcya/adempiere-gRPC-Server/blob/master/src/main/java/org/spin/grpc/util/AccessServer.java#L128
                port_value: 50050

  - name: dictionary_cluster
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: dictionary_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # replace the 'localhost' address with your dictionary host address
                address: localhost
                # it is the default port, unless the server port is changed it is recommended not to change
                # https://github.com/erpcya/adempiere-gRPC-Server/blob/master/src/main/java/org/spin/grpc/util/DictionaryServer.java#L128
                port_value: 50051

  - name: business_data_cluster
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: business_data_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # replace the 'localhost' address with your business data host address
                address: localhost
                # it is the default port, unless the server port is changed it is recommended not to change
                # https://github.com/erpcya/adempiere-gRPC-Server/blob/master/src/main/java/org/spin/grpc/util/BusinessDataServer.java#L128
                port_value: 50052

  - name: enrollment_cluster
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: enrollment_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # replace the 'localhost' address with your enrollment host address
                address: localhost
                # it is the default port, unless the server port is changed it is recommended not to change
                # https://github.com/erpcya/adempiere-gRPC-Server/blob/master/src/main/java/org/spin/grpc/util/EnrollmentServer.java#L127
                port_value: 50047
```

however using only one router for each route works well, this is not the most appropriate
https://github.com/erpcya/gRPC-Envoy-Proxy/blob/master/envoy.yaml

**Comment by zuercher** [comment]
I think the "Method not found error" is coming from your GRPC server, not Envoy. The normal format for GRPC paths is `/service/Method` so I'd expect your GRPC upstreams to want `/access.AccessService/GetMenuAndChild`. Perhaps you need to use `prefix_rewrite` to strip `/access-route` from the start of your path?

**Comment by EdwinBetanc0urt** [comment]
Thank you @zuercher, it worked correctly as you indicated with `prefix_rewrite` as follows:
```yaml

              routes:
              - match: {
                  prefix: "/access-route/"
                  # prefix: "/access"
                }
                route: {
                  prefix_rewrite: "/",
                  cluster: access_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/dictionary-route/"
                }
                route: {
                  prefix_rewrite: "/",
                  cluster: dictionary_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/businessdata-route/"
                }
                route: {
                  prefix_rewrite: "/",
                  cluster: business_data_cluster,
                  max_grpc_timeout: 0s
                }
              - match: {
                  prefix: "/enrollment-route/"
                }
                route: {
                  prefix_rewrite: "/",
                  cluster: enrollment_cluster,
                  max_grpc_timeout: 0s
                }
```
