### ISSUE TITLE
Ext Authz (gRPC): Plugin denies when failure_mode_allow set to true and Auth Server responses 5xx

### ISSUE THREAD

**Issue by kikogolk** [envoyproxy/envoy#10158]
*Title*: *Ext Authz (gRPC): Plugin denies when failure_mode_allow set to true and Auth Server responses 5xx*

*Description*:
Hi!

Envoy version: **v1.13.0**

Not sure if this is an issue or just I misunderstood the meaning of the "**failure_mode_allow**" parameter in the HTTP External Authorization plugin (using grpc_service).

From following link:
https://www.envoyproxy.io/docs/envoy/v1.13.0/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2-extauthz

> failure_mode_allow
> 
>     (bool) Changes filter’s behaviour on errors:
> 
>         1. When set to true, the filter will accept client request even if the communication with the authorization service has failed, or if the authorization service has returned a HTTP 5xx error.
> 
>         2. When set to false, ext-authz will reject client requests and return a Forbidden response if the communication with the authorization service has failed, or if the authorization service has returned a HTTP 5xx error.

When failure_mode_allow is set to true, I am afraid the request is denied even when the External Authz server returns HTTP 5xx error. However it is working as stated in the description when the connection fails or timeout (i.e request is accepted and passed to router plugin). Checking the code, it seems the "http_service" is routing  the request (as described in the documentation) but not happening the same in "grpc_service".

This is the Envoy's filter configuration I am using:

```
      - filters:
        - name: envoy.http_connection_manager
          config:
            codec_type: auto
            stat_prefix: ingress_http
            access_log:
              - name: envoy.file_access_log
                config:
                  path: /dev/null
            rds:
               route_config_name: local_route
               config_source:
                  path: /etc/envoy/rds.yaml
            http_filters:
              - name: envoy.ext_authz
                config:
                  grpc_service:
                    envoy_grpc:
                      cluster_name: ext-authz
                    timeout: 3s
                  clear_route_cache: true
                  status_on_error:
                    code: InternalServerError
                  with_request_body:
                    max_request_bytes: 2048
                    allow_partial_message: true
                  failure_mode_allow: true
              - name: envoy.router
```

When sending a request that Auth Server denies:

```
$ curl -v localhost:8000/service/1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /service/1 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< date: Fri, 14 Feb 2020 15:46:55 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

When Auth Server query fails due to timeout (upstream answers correctly):

```
$ curl -v localhost:8000/service/1
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /service/1 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html; charset=utf-8
< content-length: 93
< server: envoy
< date: Fri, 14 Feb 2020 15:51:17 GMT
< x-envoy-upstream-service-time: 1
< 
Hello from behind Envoy GET (service 1)! hostname: d3ac953e9781 resolvedhostname: 172.23.0.5
* Connection #0 to host localhost left intact
```

I was checking this already closed issue: https://github.com/envoyproxy/envoy/issues/4124 . Not sure then if it is an documentation issue or I am misunderstanding the proper behavior.

Thanks a lot!
