### ISSUE TITLE
Ratelimiting or Circuit breaking based on L7 rules

### ISSUE THREAD

**Issue by kprakasam** [envoyproxy/envoy#10207]
*Title*: *Ratelimiting or Circuit breaking based on L7 rules*

*Description*:
Envoy currently allows only one circuit breaker per upstream cluster and a global rate limiter service, this is very constraining when dealing with DDOS attacks when there is only one upstream cluster (If you want to understand the specific use case we can discuss offline). We are wondering if we can create a filter that can configure one or more localized rate limiter/circuit-breaker (https://github.com/Netflix/concurrency-limits)  associated with an arbitrary L7 rule and when the breaker is trigger allow arbitrary action to be takes (ex: Serve a static page, cached version of page, etc.). I would like to hear the community's thoughts on this approach.

Sample Filter Configuration
```
  rate-limiters:
    ingressRoute: mweb-1-80
    www.acme.com :
    - name: view-item
      match:
        - header: { name: "path", regex_match: "/itm/.*" }
      circuit-breakers:
         - windowed:
        ...
       - fixed: 
        ...
      action:
          drop: true
   - name: default
     circuit-breakers:
       - gradient2:
        ...
       - aimd
        ...
     action:
       monitor: true
```
