### ISSUE TITLE
Explicitly test for header presence/absence in router_check_tool

### ISSUE THREAD

**Issue by kb000** [envoyproxy/envoy#10229]
*Title*: Router check tool could check for absence or presence of a header, regardless of header value.

*Description*:
router_check_tool can verify HTTP header values, but not explicitly test for http header absence.  There's a workaround to test for empty value string, which is nearly but not quite the same thing. 
Adding `present: true/false` to the `request_header_fields` and `response_header_fields` would allow for testing for value-agnostic presence of a header, and for explicit absence of a header.

```
validate:
  response_header_fields:
    - key: content-length
      present: true
```

```
validate:
  response_header_fields:
    - key: x-ride-corp-internal
      present: false
```
