### ISSUE TITLE
Unable to parse budget_percent literal in yaml config

### ISSUE THREAD

**Issue by mmatusiak-atlassian** [envoyproxy/envoy#10277]
I'm trying to use circuit breakers with a retry budget. The relevant config is:

```
circuit_breakers:
  thresholds:
    - priority: "DEFAULT"
      max_requests: 0xffffffff
      max_pending_requests: 0xffffffff
      max_retries: 0xffffffff
      retry_budget:
        budget_percent: 25.0
        min_retry_concurrency: 10
```

Trouble is the yaml parser won't accept this value:

```
Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[2].circuit_breakers.thresholds[0].retry_budget.budget_percent):
 invalid value "25.0" for type type.googleapis.com/envoy.type.Percent)
```

I've unsuccessfully tried to write this literal in the following ways:

- 25
- "25"
- 25.0
- "25.0"
- 0.25
- "25%"

I'm using envoy version: envoyproxy/envoy-alpine:v1.13.0

**Comment by mattklein123** [comment]
cc @tonya11en. It would be good to get a doc update once we figure this out. Thank you!

**Comment by rohaldbUni** [comment]
I'm facing the same issue with the healthy_panic_threshold field, which is also a percent type

**Comment by tonya11en** [comment]
@mmatusiak-atlassian this will work:
```
    circuit_breakers:
      thresholds:
        - priority: "DEFAULT"
          max_requests: 0xffffffff
          max_pending_requests: 0xffffffff
          max_retries: 0xffffffff
          retry_budget:
            budget_percent:
              value: 25.0
            min_retry_concurrency: 10
```

Sorry for the confusion in the docs. Percent protos store their values in the `value` field:
```
// Identifies a percentage, in the range [0.0, 100.0].
message Percent {
  double value = 1 [(validate.rules).double = {lte: 100.0 gte: 0.0}];
}
```

I think it's relevant for @rohaldbUni as well.
