### ISSUE TITLE
 Http2 performance issue with firefox

### ISSUE THREAD

**Issue by jsenon** [envoyproxy/envoy#10315]
*Title*: * Http2 performance issue*

*Description*:

When we upload files with Firefox it took 7 times more than in Chrome browser (7s compared to 1s).
We are using H2 protocol.
**When we change the setting network.buffer.cache.size in about:config, our upload time is reduced to 1 second.**

IMO the network size is part of flow control implemented in http2 (https://developers.google.com/web/fundamentals/performance/http2#flow_control)

In server side we have set following value:
(https://httpwg.org/specs/rfc7540.html#rfc.section.6.9.2)

Initial Flow-Control Window Size: 104857500
Connection-level flow-control window: 104857500

Actual results:

When we upload files with Firefox it took 7 times more than in Chrome browser (7s compared to 1s).

Expected results:

Same upload time compared to chrome.

[optional *Relevant Links*:]

*Repro steps*:
Try to upload a file with firefox with http2

*Admin and Stats Output*:
 /stats: https://gist.github.com/jsenon/8552f40cafa0a25bc9e12b126b27b652

/server_info:

```
{
 "version": "4cd27af28f54d6da1a487aa756256eb5393fff7d/1.12.0/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 4,
  "config_path": "/etc/istio/proxy/envoy-rev0.json",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "warning",
  "component_log_level": "misc:error",
  "log_format": "[Envoy (Epoch 0)] [%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "service_cluster": "istio-ingressgateway",
  "service_node": "router~10.10.129.155~istio-ingressgateway-85f6c47d95-gsqrs.istio-system~istio-system.svc.cluster.local",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "file_flush_interval": "10s",
  "drain_time": "45s",
  "parent_shutdown_time": "60s"
 },
 "uptime_current_epoch": "411585s",
 "uptime_all_epochs": "411585s"
}
```

pcap link https://send.firefox.com/download/004e0e9f4ea9ca91/#ad9EdZ0Ijt18Dw5e7-6P3g

*Config*:

Flow: Client <-> AWS Classical LB <-> Istio/Envoy ingress gateway <-> upstreamsvc uploader

Configured with Istio, and add following envoy filter:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-control
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager"
          http2_protocol_options:
            initial_stream_window_size: 524288000
            initial_connection_window_size: 524288000
```
