### ISSUE TITLE
Question: Malformed IP Address for listener with address "localhost"

### ISSUE THREAD

**Issue by sumukhs** [envoyproxy/envoy#10346]
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: localhost
          port_value: 19888
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
```

For the above config, I see this error when bootstrapping envoy:

[critical][main] [source/server/server.cc:91] error initializing configuration - malformed IP address: localhost

What is the reason we cannot specify the listen address to be localhost?
