### ISSUE TITLE
ADS API request for v2 type URL in v3 API endpoints

### ISSUE THREAD

**Issue by winguse** [envoyproxy/envoy#10375]
I am working on upgrade our ads service to use API v3 and I find Envoy is requesting  v2 type url on v3 endpoints.

## reproduce

envoy version: v1.13.1

envoy config:
```yaml
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
  id: node-id
  cluster: test
  locality:
    region: us-west-1
    zone: us-west-1b
    sub_zone: sub-zone

dynamic_resources:
  ads_config:
    transport_api_version: V3
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: ads_cluster
  lds_config:
    ads: {}
  cds_config:
    ads: {}

static_resources:
  clusters:
  - name: ads_cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ads_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal # change this if you're not macOS
                    port_value: 9902
```

docker-compose.yaml:
```yaml
version: '3'
services:
  envoy:
    command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml # --log-level debug
    image: envoyproxy/envoy:v1.13.1
    volumes:
      - ./config:/etc/envoy/
      - ./log:/var/log/envoy/
    ports:
    - "9901:9901"
```

To see the request in a simple way:

```
$ nc -l 9902
PRI * HTTP/2.0

... hide useless input ...

envoy.statsdenvoy.stats_sinks"(type.googleapis.com/envoy.api.v2.Cluster%
```

the package capture by Wireshark:

![image](https://user-images.githubusercontent.com/1443504/76609820-f166ef00-6552-11ea-95d3-1f9b543c0b6f.png)

# relevent source code 

https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L746-L753

it's always getting `v2` type url.

https://github.com/envoyproxy/envoy/blob/master/source/common/config/resources.h#L16

I think this will be problem on LDS / EDS / RDS as well.
