### ISSUE TITLE
Question: Allow IP for requests

### ISSUE THREAD

**Issue by vzemtsov** [envoyproxy/envoy#10386]
How i can set allow IP list for request (in route_config)?

Like "allow" settings in nginx.

**Comment by mattklein123** [comment]
This is not currently supported. See https://github.com/envoyproxy/envoy/issues/7918. There are hacky ways of doing this like having the IP tagging filter add a header, and then routing on that.

**Comment by mirwide** [comment]
RBAC filter let limit by source CIDR, for example:
```yaml
            - name: envoy.filters.http.rbac 
              config: 
                rules: 
                  action: ALLOW
                  policies:
                    "local-allow-rules":
                      permissions:
                      - any: true
                      principals:
                      - source_ip: 
                          address_prefix: 192.168.0.0
                          prefix_len: 24
```
or per route:
```yaml
                  per_filter_config:
                    envoy.filters.http.rbac:
                      rbac:
                        rules: 
                          action: ALLOW
                          policies:
                            "localhost-alow-rules":
                              permissions:
                              - any: true
                              principals:
                              - source_ip: 
                                  address_prefix: 192.168.0.0
                                  prefix_len: 24
```
