### ISSUE TITLE
Question: http_health_check configuration

### ISSUE THREAD

**Issue by charlesxu2000** [envoyproxy/envoy#10393]
*Title*: *Endpoint request does not response with 503 with upstream health check failed*

*Description*:
I have a simple API server, there two endpoints /hello and /healthcheck. Envoy has only one upstream host, and I configured http_health_check as below. I can see from health check log that it gets the active health check failure event. I can also see the health flags for the cluster in failed_active_hc when I use the admin /clusters API. I also configured the panic mode to 0.
But after reaching unhealthy threshold, I curl the endpoint /hello, Envoy still routes the request to upstream webserver and not response with 503. (I wait long enough after the drain timeout and still not response with 503)

Another data point (maybe unrelated). I have the http health_check filter configured. I send /healthcheck/fail to the admin endpoint, I confirm with /ready and the server is in DRAIN state. But my service endpoint /hello still return the 200 (even after the drain timeout).

By looking the documentation, seems in both cases, Envoy should response with 503 after upstream cluster healthcheck failed, or we mark the server unhealthy with /healthcheck/fail, But it never happen to me.  Could you tell me what is wrong in my configuration?

===== Snap of Healthcheck log =====
`{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"testcluster","health_check_failure_event":{"failure_type":"ACTIVE","first_check":false},"timestamp":"2020-03-15T04:06:15.351Z"}
`
hc response=503 health_flags=/failed_active_hc

The Admin /clusters returns the correct status
```
curl -v  http://localhost:9000/clusters
testcluster::127.0.0.1:8080::health_flags::healthy
testcluster::127.0.0.1:8080::health_flags::/failed_active_hc
```

===== Snap of Envoy Configuration ====
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: test_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: testcluster

    http_filters:
          - name: envoy.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.health_check.v2.HealthCheck
              pass_through_mode: true
              headers:
                - name: ":path"
                  exact_match: "/healthcheck"
          - name: envoy.router
            typed_config: {}

  clusters:
  - name: testcluster
    connect_timeout: 1s
    type: strict_dns
    dns_lookup_family: V4_ONLY
    lb_policy: ring_hash
    load_assignment:
      cluster_name: testcluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
    common_lb_config:
      healthy_panic_threshold:
        value: 0
    health_checks:
      - timeout: 1s
        interval: 2s
        unhealthy_threshold: 3
        healthy_threshold: 1
        always_log_health_check_failures: true
        event_log_path: /tmp/health-check.log
        http_health_check:
          path: /healthcheck
    http_protocol_options: {}
```

I make the webserver /healthcheck return 503 for each health check call.
