### ISSUE TITLE
Envoy should be able to describe (Wasm) ABIs it supports

### ISSUE THREAD

**Issue by yskopets** [envoyproxy/envoy#10395]
*Title*: Envoy should be able to describe (Wasm) ABIs it supports

*Context*:
* consider a use case of a marketplace with Wasm extensions for Envoy
* from a user perspective, it's important to know whether a given extension is supported by a particular Envoy distribution he is using right now
* the assumption is that an answer like "use Envoy vX.Y.Z+" is not good enough (a user might be using either a 3rd party Envoy distro, or a nightly build of upstream Envoy, etc)
 
*Proposal*:
* Add to Envoy the ability to describe (Wasm) ABIs it supports
* The initial focus is on the offline scenario where it is a user, or a marketplace, or a vendor, who needs to know this info
* The online scenario, where it is a Control Plane who needs to know this info, is currently out of scope

*Example use cases*:
* a user runs `envoy --list-abis` to get the precise list of (Wasm) ABIs this particular Envoy distro supports, e.g.
  ```yaml
  envoy:
    version:
     ... 
    abis:
      v1:
        host:
          http_client:
            proxy_http_call:   SUPPORTED
          grpc_client:
            proxy_grpc_call:   SUPPORTED
            proxy_grpc_stream: SUPPORTED
            proxy_grpc_send:   SUPPORTED
          tcp_client:
            ...
          udp_client:
            ...
        ...
        extension:
          http_client:
            proxy_on_http_call_response:           SUPPORTED
          grpc_client:
            proxy_on_grpc_create_initial_metadata: SUPPORTED
            proxy_on_grpc_receive:                 DEPRECATED
          tcp_client:
            ...
          udp_client:
            ...
        ...
  ```
* a user then comes to a marketplace site, provides info from above and gets back the exact info on what extensions (and their versions) are applicable to him
* a marketplace runs `envoy --list-abis` on popular Envoy distributions (e.g. upstream, `getenvoy`, `istio`, `solo`, etc) to provide compatibility info in advance
* vendors of closed source Envoy distributions run `envoy --list-abis` on their own binaries and submit this info to a marketplace in order to be present in the compatibility matrix for each extension in the catalog

**Comment by Shikugawa** [comment]
I think it is easy to implement this with a dynamic approach by fetching symbols with `wasm_vm_->registerCallback` and any other functionality to provide ABI support.

**Comment by mattklein123** [comment]
Agreed. This is similar also for Envoy expressing what extensions it supports. cc @jpeach

**Comment by yskopets** [comment]
Here is the re-worked schema that is meant to meet the following requirements:
* it should support not only `proxy-wasm` but also Envoy-specific ABIs (see 2 examples below)
* it should have the same form both for `proxy-wasm` and Envoy-specific ABIs (unlike in the original proposal)
* it should be simple (given that the entire Wasm support in Envoy is new and might evolve significantly)

```yaml
'@type': type.googleapis.com/envoy.data.abi.v3alpha.ABI
apis:
- name: proxy-wasm:0.1.0 # reference name 
  description: Wasm for Proxies (github.com/proxy-wasm/spec)

  api: proxy-wasm # name of the API without a version component
  version:
    semantic:
      major: 0
      minor: 1
      patch: 0

  # API provided by host.
  host:
    # Module through which host API will be exposed to the extension.
    module: env

    functions: # use Wasm terms
    - name: proxy_log
      status: IMPLEMENTED # by default

    - name: proxy_configuration
      status: DEPRECATED # to flag the extensions that are still using this function

    - name: proxy_get_buffer

    - name: proxy_open_grpc_stream

  # API expected from the extension.
  extension:
    functions: # use Wasm terms
    - name: proxy_abi_version_0_1_0
      expectation: MANDATORY # Envoy will reject those extensions that are not exposing this function

    - name: proxy_on_memory_allocate
      expectation: MANDATORY

    - name: proxy_on_vm_start
      expectation: OPTIONAL # by default

    - name: proxy_on_new_connection
    
- name: envoy.extensions.tracers.v1alpha0 # reference name 
  description: Wasm ABI for tracing providers

  api: envoy.extensions.tracers # name of the API without a version component
  version:
    grpc:
      major: v1
      stability: alpha0

  host: {} # API implemented only by the extension

  extension:
    functions:
    - name: envoy_extensions_tracers_v1alpha0_tracer_create # functions exposed by the extension must have fully qualified names
      expectation: MANDATORY

    - name: envoy_extensions_tracers_v1alpha0_tracer_destroy
      expectation: MANDATORY

    - name: envoy_extensions_tracers_v1alpha0_span_start
      expectation: MANDATORY

    - name: envoy_extensions_tracers_v1alpha0_span_set_operation

    - name: envoy_extensions_tracers_v1alpha0_span_set_tag

    - name: envoy_extensions_tracers_v1alpha0_span_finish
      expectation: MANDATORY

- name: envoy.sdk.udp.client.v1alpha0 # reference name 
  description: Wasm ABI for Envoys-specific APIs, such as UDP client

  api: envoy.sdk.udp.client # name of the API without a version component
  version:
    grpc:
      major: v1
      stability: alpha0

  host:
    # Module through which host API will be exposed to the extension.
    module: envoy.sdk.udp.client.v1alpha0

    functions:
    - name: create_client
      status: NOT_IMPLEMENTED # explicitly indicate that this API is not implemented yet

    - name: destroy_client
      status: NOT_IMPLEMENTED

    - name: send_message
      status: NOT_IMPLEMENTED

  extension: {} # API implemented only by the host
```
