### ISSUE TITLE
Is it possible to set separate filters for static and dynamic routes?

### ISSUE THREAD

**Issue by ksanghavi** [envoyproxy/envoy#10401]
We are introducing an xDS server that will set dynamic routes and cluster details to Envoy. However we want to keep existing static routes in place and may be move them to xDS server in the future. Is there a way to achieve that? 
I tried add multiple http connection managers, but Envoy doesn't seem to route to the second one. Thanks for your help! 

```
  listeners:
    - name: gateway-listener-8080
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
          protocol: TCP
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - domains:
                        - '*'
                      name: backend
                      routes:
                        - match:
                            prefix: /staticbackend
                          route:
                            prefix_rewrite: /
                            cluster: cluster_http___static_backend
            - name: envoy.http_connection_manager                            
              config:
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.router
                rds:
                  route_config_name: routes-listener-8080
                  config_source:
                    ads: {}


  dynamic_resources:
    ads_config:
      api_type: GRPC
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
    cds_config:
      ads: {}                    

```
