### ISSUE TITLE
SNI in the FAQ doesn't work

### ISSUE THREAD

**Issue by chintan-mishra** [envoyproxy/envoy#10425]
*Title*: *SNI config in the FAQ doesn't work*

*Description*:
I am trying to route HTTPS traffic to a container on my network. I have a very simple configuration that has two listeners and one cluster. The listener for HTTP traffic reroutes everything to HTTPS. The listener for HTTPS connects with the upstream container. While connecting with the website using `curl -v https://rebhu.com` I get the following error:
`* ALPN, server did not agree to a protocol`

In order to check if this is a cluster configuration error, I redirected the HTTP traffic to the cluster. After this, I was able to access my cluster over HTTP. **Please suggest correct SNI configuration.**

*Relevant Links*:
[SNI config FAQ](https://www.envoyproxy.io/docs/envoy/v1.13.0/faq/configuration/sni)

*Config*:
<details>
<summary>Configuration used for this setup</summary>

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: https_redirect_route
            virtual_hosts:
            - name: https_redirect_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.router
            config: {}

  - name: listener_https
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: "envoy.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names: ["rebhu.com", "www.rebhu.com"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: 
                filename: "/letsencrypt/fullchain.pem"
              private_key:
                filename: "/letsencrypt/privkey.pem"
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_https_rebhu_com
          route_config:
            name: rebhu_com_ghost_route
            virtual_hosts:
            - name: rebhu_com_ghost_service
              domains: ["rebhu.com", "www.rebhu.com"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_rebhu_com_ghost

  clusters:
  - name: service_rebhu_com_ghost
    connect_timeout: 0.25s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_rebhu_com_ghost
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: rebhu-com-ghost
                port_value: 2368
```

</details>

**Comment by mattklein123** [comment]
cc @PiotrSikora @ggreenway

**Comment by chintan-mishra** [comment]
Thank you @mattklein123 for referencing people here.

I figured that this was an uncommon issue particularly related to the LetsEncrypt TLS certificate in use. I was supplying `fullchain.pem` file in the `certificate_chain` option within the config. It combines server certificate and any additional intermediate certificate in the `fullchain.pem` file. The server certificate is available within the same directory as `cert.pem`. Using this file solved the issue and I can access my website.

```yaml
          common_tls_context:
            tls_certificates:
            - certificate_chain: 
                # Modified this filename
                filename: "/letsencrypt/cert.pem"
              private_key:
                filename: "/letsencrypt/privkey.pem"
```

Here are some more details: https://certbot.eff.org/docs/using.html#where-are-my-certificates
