### ISSUE TITLE
Accessing meta data such as method, uri (path + query) from Lua API

### ISSUE THREAD

**Issue by tzuryby** [envoyproxy/envoy#10435]
I am trying to figure out how can I access basic information such as request path and method from lua.
By looking through the docs, I could not see any option for this.

I was thinking of two possible options:

1. Using [metadata](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#metadata-object-api)
2. A prior filter that will feed this infomation to the headers

As for option no. 1, the question would be how can I can I set a dynamic entry, with variable such as those available for access log.

The following example **_does not work_**, it is just for concept demonstration

```
metadata:
  filter_metadata:
    envoy.filters.http.lua:
      path: "%REQ(:PATH)%"
      method: "%REQ(:METHOD)%"
      method2: "%METHOD%"
```

for option no. 2 _or any other idea_, I would love to get an example how to get it done.

docs:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html
