### ISSUE TITLE
Example on Envoy-xray integration

### ISSUE THREAD

**Issue by BhagathSeelam** [envoyproxy/envoy#10442]
Can someone provide configuration example on Envoy with Aws xray?

Thanks

**Comment by mattklein123** [comment]
cc @marcomagdy would be nice to get a doc update on this if needed.

**Comment by marcomagdy** [comment]
```yaml
tracing:
  http:
    name: envoy.tracers.xray
    config:
      sampling_rule_manifest:
        filename: /tmp/rules.json
      daemon_endpoint:
        protocol: UDP
        address: 127.0.0.1
        port_value: 2000
```
For more information on the contents of the rule.json file see the [x-ray documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-configuration.html#xray-sdk-go-configuration-sampling)

I'll update the documentation in Envoy with a complete example as soon as I can.
Let me know if you still have questions.

**Comment by marcomagdy** [comment]
There is no more configuration needed.
I don't have visibility into the rules you are supplying to the tracer (/xray_daemon/rules.json).

You either have a low sampling rate that's why you are not seeing anything sent to the daemon. You need to send more requests. Or the rules you set are not matching any of the requests you are making.

**Comment by BhagathSeelam** [comment]
@marcomagdy 
 
I am allowing all paths with *

here is my rules.json file 

{
  "version": 2,
  "rules": [
    {
      "priority":1,
      "description": "Envoy XRay Sampling rules",
      "service_name": "*",
      "http_method": "*",
      "url_path": "*",
      "fixed_target": 100,
      "rate": 1
    }
  ],
  "default": {
    "fixed_target": 1,
    "rate": 0.1
  }
}

**Comment by marcomagdy** [comment]
Verify two things:
1. You have `tracing: {}` in the connection manager settings (see below)
2. Use the (non-deprecated) `typed_config` in the tracer (my bad for suggesting those earlier).

```yaml
static_resources:
   listeners:
   - name: listener_0
     address:
       socket_address: { address: 0.0.0.0, port_value: 10000 }
     filter_chains:
     - filters:
       - name: envoy.http_connection_manager
         typed_config:
           "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
           stat_prefix: ingress_http
           tracing: {}  # <---- this MUST exist for the tracer to work
           codec_type: AUTO
           route_config:
```
Use the non-deprecated configuration:
```yaml
tracing:
  http:
    name: envoy.tracers.xray
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.XRayConfig
      segment_name: "Envoy" # You must set this until v1.14 
      daemon_endpoint:
        protocol: UDP
        address: 127.0.0.1
        port_value: 2000
      sampling_rule_manifest:
        filename: /xray_daemon/rules.json

```
