### ISSUE TITLE
Feature Request: Mirror trafic to MongoDB

### ISSUE THREAD

**Issue by chaspy** [envoyproxy/envoy#10652]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

**Issue Template**

*Title*: *One line description*

Feature Request: Mirror trafic to MongoDB

*Description*:
>Describe the issue. Please be detailed. If a feature request, please
describe the desired behavior, what scenario it enables and how it
would be used.

I'm using Envoy to proxy to MongoDB from an application.

```
      - name: mongo_proxy
        address:
          socket_address: { address: 0.0.0.0, port_value: 27000 }
        filter_chains:
        - filters:
          - name: envoy.mongo_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.mongo_proxy.v2.MongoProxy
              stat_prefix: mongo_proxy
          - name: envoy.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
              stat_prefix: mongo_tcp_proxy
              cluster: mongo_proxy
```

I'd like to mirror traffic like HTTP route configuration.
i.e:  https://blog.markvincze.com/shadow-mirroring-with-envoy/amp/

So I need upstream envoy filter for tcp.
Could you help us?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Asked in envoy Slack: https://envoyproxy.slack.com/archives/C78M4KW76/p1585924570317300 Thanks @SecurityInsanity
