### ISSUE TITLE
max_concurrent_streams and max_requests_per_connections not working as expected

### ISSUE THREAD

**Issue by freesnowCL** [envoyproxy/envoy#10675]
I tried to set the max_concurrent_streams to 1 and max_requests_per_connections to 10 in my configurations:
```
...
     - name: grpc-demo
        connect_timeout: 0.5s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        max_requests_per_connection: 10
        http2_protocol_options:
          max_concurrent_streams: 1
        load_assignment:
...
```
And used ghz to test the settings by sending 50 requests with 1 connections and 1 concurrent stream:
`ghz --skipTLS --call demo.grpc.api.v1.Demo/SayHello -c 1 -n 50 --connections 1 $url:443`

I expect 40 requests to be rejected, but the actual result is no request is rejected.

I also tried using ghz to send 50 requests with 1 connections and 10 concurrent streams:
`ghz --skipTLS --call demo.grpc.api.v1.Demo/SayHello -c 10 -n 50 --connections 1 $url:443`

Again, all 50 requests are returned successfully.

**Comment by snowp** [comment]
`max_concurrent_streams: 1` instructs Envoy to create a new connection for every stream instead of reusing the connection, it won't fail until Envoy is unable to create more connections. You probably want to be using circuit breakers (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking) to configure these limits.

**Comment by freesnowCL** [comment]
Thanks for the reply. Does that mean the max_concurrent_streams and max_requests_per_connection only limits the traffic from the envoy proxy to the application but not the traffic to the envoy proxy? 

I tried setting up the circuit breaker and the result is still the same:
```
...
        max_requests_per_connection: 10
        circuit_breakers:
          thresholds:
            max_connection_pools: 1
        http2_protocol_options:
          max_concurrent_streams: 1
...
```

But when I sent requests with the following command, all requests are returned successfully again:
`ghz --skipTLS --call demo.grpc.api.v1.Demo/SayHello -c 10 -n 50 --connections 1 $url:443`

I then tried using different circuit breaker settings, but the results are still not the expected results:

All requests returned successfully:
```
...
        max_requests_per_connection: 10
        circuit_breakers:
          thresholds:
            max_connections: 1
        http2_protocol_options:
          max_concurrent_streams: 1
...
```

All requests returned successfully:
```
...
        max_requests_per_connection: 10
        circuit_breakers:
          thresholds:
            max_connections: 1
            max_connection_pools: 1
        http2_protocol_options:
          max_concurrent_streams: 1
...
```

Sometimes all requests returned successfully and sometimes all requests failed:
```
...
        max_requests_per_connection: 10
        circuit_breakers:
          thresholds:
            max_pending_requests: 1  
        http2_protocol_options:
          max_concurrent_streams: 1
...
```

The only time when the result is as expected (49 requests failed) is when I use the max_requests setting:
```
...
        max_requests_per_connection: 10
        circuit_breakers:
          thresholds:
            max_requests: 1
        http2_protocol_options:
          max_concurrent_streams: 1
...
```

When I set `max_requests: 100`, `max_requests_per_connection: 10`, `max_concurrent_streams: 1` and send 50 requests several times, there would be 2 different results:

- All 50 requests passed successfully
- All 50 requests failed
