### ISSUE TITLE
Fault Injection: unable to set header_abort

### ISSUE THREAD

**Issue by freesnowCL** [envoyproxy/envoy#10677]
I followed the instruction in the [fault injection page](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/fault_filter) and added the section to the http_filters in my config:
```
...
              http_filters:
              - name: envoy.fault
                config:
                  max_active_faults: 10
                  abort:
                    header_abort: {}
                    percentage:
                      numerator: 100
                      denominator: HUNDRED
                  delay:
                    header_delay: {}  # x-envoy-fault-delay-request: [ms]
                    percentage:
                      numerator: 100
                      denominator: HUNDRED
                  response_rate_limit:
                    header_limit: {} # x-envoy-fault-throughput-response: [KB/s]
                    percentage:
                      numerator: 100
                      denominator: HUNDRED
              - name: envoy.router
                config: {}
...
```

But when I restart envoy, the following error comes up:
```
[2020-04-07 09:44:33.494][1][critical][main] [source/server/server.cc:94] error initializing configuration '/etc/envoy/envoy.yaml': Protobuf message (type envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager reason INVALID_ARGUMENT:(abort) header_abort: Cannot find field.) has unknown fields
```

If I changed 'header_abort' to 'http_status', envoy can be restarted successfully:
```
...
              http_filters:
              - name: envoy.fault
                config:
                  max_active_faults: 10
                  abort:
                    http_status: 504
                    percentage:
                      numerator: 100
                      denominator: HUNDRED
...
```

Did I set the config for header_abort incorrectly?
