### ISSUE TITLE
Canary/Active Cluster Retry on 404

### ISSUE THREAD

**Issue by bringking** [envoyproxy/envoy#10683]
**WARNING: If you want to report crashes, leaking of sensitive information,
and/or other security issues, please consider
[reporting them using appropriate channels](https://github.com/envoyproxy/envoy#reporting-security-vulnerabilities).**

*Title*: Retry request on another cluster in weighted cluster

*Description*:
We are in the process of setting up Envoy to use as a Load Balancer for an application that serves a mix of HTML pages and static files. We are setting up a weighted cluster for Canary deploys, so that we can send fractional traffic to the Canary. However, since the servers serve static files, this creates a problem. There are some cases in which a request may be routed based on weight to the active cluster, but the file doesn't exist on that cluster. In this case we want to retry the request against the canary. I have setup the retry policy, but that only seems to retry against the _same_ cluster, not the other cluster. Is this a configuration issue, or a limitation of envoy?

Here is our virtual host config - 

```yaml
            virtual_hosts:
              - name: "site"
                domains: ["*"]
                retry_policy:
                  retry_host_predicate:
                    - name: envoy.retry_host_predicates.previous_hosts
                  host_selection_retry_max_attempts: 3
                  retry_on: "retriable-status-codes"
                  retriable_status_codes: [404]
                routes:
                  - match:
                      prefix: "/"
                      headers:
                        - name: "cookie"
                          safe_regex_match: { google_re2: {}, regex: ".*?(srv\\=canary).*?" }
                    route: { cluster: canary }
                  - match:
                      prefix: "/"
                      headers:
                        - name: "cookie"
                          safe_regex_match: { google_re2: {}, regex: ".*?(srv\\=active).*?" }
                    route: { cluster: active }
                  - match: { prefix: "/" }
                    route:
                      weighted_clusters:
                        clusters:
                          - name: active
                            weight: 95
                            response_headers_to_add:
                              - header: { key: Set-Cookie, value: "srv=active; HttpOnly; SameSite=Lax; Path=/;" }
                          - name: canary
                            weight: 5
                            response_headers_to_add:
                              - header: { key: Set-Cookie, value: "srv=canary; HttpOnly; SameSite=Lax; Path=/;" }

          http_filters:
          - name: envoy.router
```

[optional *Relevant Links*:]=
Trying to use the documentation here - 
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#arch-overview-http-retry-plugins
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-msg-route-retrypolicy

**Comment by mattklein123** [comment]
cc @snowp @zuercher. I know this comes up occasionally and we should probably have a FAQ or some guidance on this. I think this can probably be done either with the subset LB (using metadata) or possibly the aggregate cluster but I'm not sure and will defer to them.

**Comment by alkalinecoffee** [comment]
Also wanted to chime in that we're facing a similar situation.

This was surprising to find as the default behavior of retrying against a potentially bad cluster seems to be a bad idea.  If the original request had a 50/50 chance of going to a bad cluster, the retries should be subject to the same weighting rule, or at least have an option to force the retry against all clusters or a specific subset of clusters.

**Comment by snowp** [comment]
Currently the only way to retry between clusters is to use the aggregate cluster - none of the routing/retry mechanism are able to target more than one cluster for a given route, so the only way to hit more than one is to aggregate multiple with the cluster. 

The weighted cluster route is a fairly simple dice roll between the listed clusters, with the random value only computed once (so that filters can clear the route cache without the result changing). 

I think you could get the behavior you describe by using aggregate clusters to dictate the retry preferences:

Assuming you want to hit cluster A and B, define aggregate cluster AB and aggregate cluster BA (which orders A and B in opposite orders). Then do a weighted cluster route between AB and BA, with the `previous_priorities` retry plugin enabled. That way retries should walk down the list of priorities, hitting the other cluster after the first failure. 

I'm not sure if we want to try to make `weighted_cluster` more flexible by itself or if we think that adding more docs around these kind of retry setups would be sufficient.

**Comment by bringking** [comment]
Okay, I think I am understanding. However, I can see in the docs here for Aggregate Clusters that the retry priorities won't work? https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster#example


here is a larger snippet of the config. I feel like this is close to what you are describing, however it's not working.

```yml
         route_config:
            name: ${STACK_NAME}
            virtual_hosts:
              - name: ${STACK_NAME}
                domains: ["*"]
                routes:
                  - match:
                      prefix: "/"
                      headers:
                        - name: "cookie"
                          safe_regex_match: { google_re2: {}, regex: ".*?(_wm_${STACK_NAME}_srv\\=canary).*?" }
                    route: 
                      cluster: canary
                      metadata_match:
                        filter_metadata:
                          "envoy.lb":
                            "stage": "canary"
                  - match:
                      prefix: "/"
                      headers:
                        - name: "cookie"
                          safe_regex_match: { google_re2: {}, regex: ".*?(_wm_${STACK_NAME}_srv\\=active).*?" }
                    route: 
                      cluster: active
                      metadata_match:
                        filter_metadata:
                          "envoy.lb":
                            "stage": "active"
                  - match: { prefix: "/" }
                    route:
                      retry_policy:
                        retry_priority:
                          name: envoy.retry_priorities.previous_priorities
                          typed_config:
                            "@type": type.googleapis.com/envoy.config.retry.previous_priorities.PreviousPrioritiesConfig
                            update_frequency: 2
                        retry_on: retriable-status-codes
                        retriable_status_codes:
                          - 404
                      weighted_clusters:
                        clusters:
                          - name: active_then_canary
                            weight: ${ACTIVE_WEIGHT}
                            response_headers_to_add:
                              - header: { key: Set-Cookie, value: "srv=active; HttpOnly; SameSite=Lax; Path=/;" }
                          - name: canary_then_active
                            weight: ${CANARY_WEIGHT}
                            response_headers_to_add:
                              - header: { key: Set-Cookie, value: "srv=canary; HttpOnly; SameSite=Lax; Path=/;" }

          http_filters:
          - name: envoy.router
  clusters:
    - name: canary_then_active
      connect_timeout: 0.25s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.aggregate
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.aggregate.v2alpha.ClusterConfig
          clusters:
            # cluster primary, secondary and tertiary should be defined outside.
            - canary
            - active
    - name: active_then_canary
      connect_timeout: 0.25s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.aggregate
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.aggregate.v2alpha.ClusterConfig
          clusters:
            # cluster primary, secondary and tertiary should be defined outside.
            - active
            - canary
    - name: active
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: active
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${ACTIVE_UPSTREAM}
                      port_value: ${ACTIVE_UPSTREAM_PORT}
    - name: canary
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: canary
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${CANARY_UPSTREAM}
                      port_value: ${CANARY_UPSTREAM_PORT}
                metadata:
                  filter_metadata:
                    "envoy.lb":
                      "canary": true
```

any help would be appreciated.
