### ISSUE TITLE
Help needed to return `x-b3-traceid` in response header using Jaeger tracing

### ISSUE THREAD

**Issue by deveshbajpai19** [envoyproxy/envoy#10692]
*Title*: *Help needed to return `x-b3-traceid` in response header using Jaeger tracing*

*Description*:
I'm using the a simple Envoy service mesh as mentioned in tutorials here: [https://github.com/yokawasa/envoy-proxy-demos/tree/master/jaeger-tracing]
The essential tracing configs are: 
  
```
... 
 filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          tracing:
            operation_name: egress
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              ...
              response_headers_to_add:
              - header:
                  key: x-b3-traceid
                  value: "%REQ(x-b3-traceid)%"

          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  ...
  - name: jaeger
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: jaeger
        port_value: 9411
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: jaeger
      collector_endpoint: "/api/v1/spans"
      shared_span_context: false
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      tracing:
        global_enabled: 100
```

As I add the response_headers_to_add config in my front envoy with 'REQ' format, I get the error: 
```
[2020-04-08 07:03:19.405][6][critical][main] [source/server/server.cc:95] error initializing configuration '/etc/front-envoy.yaml': field 'REQ(x-b3-traceid)' not supported as custom header
[2020-04-08 07:03:19.406][6][info][main] [source/server/server.cc:594] exiting
```

I also referred this issue: [https://github.com/envoyproxy/envoy/issues/9243]
but that seems to work in Zipkin tracing. 

I also tried keeping the header x-ot-span-context in the trace headers' propagation as discussed in this issue: [https://github.com/envoyproxy/envoy/issues/1364] but the issue persists. 

Is this a bug or there is an error in my envoy tracing configurations?
