### ISSUE TITLE
server.hot_restart_generation does not include tags defined in stats_config.stats_tags

### ISSUE THREAD

**Issue by argos83** [envoyproxy/envoy#10719]
*Title*: *gauge server.hot_restart_generation is not tagged*

*Description*:

I've been trying out the new 1.14.1 release, and happened to notice that there's this new `server.hot_restart_generation` metric, which is the only metric (in our setup) that doesn't get the tags defined in `stats_config.tags`.

```
stats_config:
  stats_tags:
    - tag_name: foo
      fixed_value: bar

stats_sinks:
  - name: "envoy.dog_statsd"
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v2.DogStatsdSink
      address:
        socket_address:
          protocol: "UDP"
          address: "x.x.x.x"
          port_value: 8125
```

Maybe this is working as designed, but I though it could be a bug. E.g. we tag our metrics by service id and environment (among other things), and in our infrastructure a metric without these tags provides no value since we can't tell where it comes from.

I thought of filtering it out via the `stats_matcher` config but I got second thoughts from the warning in the docs:

```
Excluding stats may affect Envoy’s behavior in undocumented ways. See issue #8771 for more information. If any unexpected behavior changes are observed, please open a new issue immediately.
```
