### ISSUE TITLE
Mirror policy can't be disabled with value of zero

### ISSUE THREAD

**Issue by alkalinecoffee** [envoyproxy/envoy#10712]
*Description*:
We are unable to disable mirroring by using a numerator value of zero.  It's expected that this would effectively disable the mirroring policy, but instead zero appears to be treated the same as configuring 100%.  Configuring the value to any other `1-100` number will mirror the appropriate amount of traffic.

The documentation (https://www.envoyproxy.io/docs/envoy/latest/api-v2/type/percent.proto#type-fractionalpercent) shows that the default `numerator` value is zero, but omitting this value also has the same result of all traffic being mirrored.

*Config*:

```
virtual_hosts:
- name: envoy_backend_service
  domains: ["*"]
  routes:
  - match:
      prefix: "/"
    route:
      cluster: envoy-backend-green
      request_mirror_policies:
        - cluster: envoy-backend-yellow
          runtime_fraction:
            default_value:
              numerator: 0
              denominator: HUNDRED
```

*Logs*:

> TBD
