### ISSUE TITLE
Dynamic Forward Proxy with auto_host_rewrite_header for HTTPS traffic

### ISSUE THREAD

**Issue by mabukhovsky** [envoyproxy/envoy#10756]
Hi guys, thanks to @dio help we have Envoy dynamic forward proxy that is validating requests via ext_authz and rewriting host and port based on header information (**auto_host_rewrite_header**).

It works fine for HTTP requests coming to Envoy, however it doesn't if we do HTTPS requests. I was trying to include port 443 in auto_host_rewrite_header and in a debugger at upstream host side I can see that still HTTP request was made from Envoy.

If dynamic forward proxy is accepting only HTTP requests due to internal constraints, may be there's a way to introduce a protocol header (like **auto_protocol_rewrite_header**) so when actual routing happens, we can specify that it should actually go to HTTPS, not HTTP we used to connect to Envoy.
Please let me know if you work or plan to do something similar in the nearest future, or there's any other workaround how to configure Envoy forward HTTPS requests.

My Envoy configuration:

```
admin:
  access_log_path: %WD_HOME%/logs/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: %ADMIN_PORT% }

static_resources:
  listeners:
    - name: exposed_admin_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: %EXPOSED_ADMIN_PORT% }```
filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                          per_filter_config:
                            envoy.filters.http.dynamic_forward_proxy:
                              auto_host_rewrite_header: "X-Host-Port"
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                http_filters:
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: xds_cluster
                        timeout: 5s
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                  - name: envoy.router
  clusters:
    - name: xds_cluster
      connect_timeout: 5s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
          common_tls_context:
            alpn_protocols: [
              "h2"
            ]
      dns_refresh_rate:
        seconds: 3600
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: %HOST%
                      port_value: %PORT%

    - name: dynamic_forward_proxy_cluster
      connect_timeout: 5s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
   - name: exposed_admin
      connect_timeout: 0.250s
      type: STATIC
      hosts:
        - socket_address: { address: 127.0.0.1, port_value: %ADMIN_PORT% }
```

**Comment by mabukhovsky** [comment]
Hi @mattklein123 , I would appreciate if someone from your team could give me advice. Thanks :)

**Comment by mattklein123** [comment]
Whether upstream uses TLS or not is determined by the configuration of the upstream cluster (basically whether it has a TLS transport socket or not). There may be a way of doing this using a transport socket matcher without code changes, or possibly somehow routing to do different clusters depending on the x-forwarded-proto or something like that. cc @lizan who might have some ideas.

**Comment by lizan** [comment]
Yes I think you can setup two clusters and two route entries, one with TLS and one without TLS, the two route matches the specific header to decide whether it goes to TLS cluster or plaintext cluster.

**Comment by mabukhovsky** [comment]
@lizan Thank you for a quick response and good suggestion. Is it possible to combine the approach you're offering with dynamic forward proxy in order hostname and port to be taken from the header (see **auto_host_rewrite_header** in my config) so we don't have to push cluster and route to Envoy config for every endpoint (unique domain name/port)? If we would end up with dynamic forward proxy cluster + 2 more clusters (TLS, non TLS) that are capable of forwarding HTTP / HTTPS requests to a host/port that is specified in auto_host_rewrite_header, that would be ideal (static) configuration that we are looking for.

**Comment by mabukhovsky** [comment]
@lizan I would appreciate your help as this issue is a blocker for a team. Thanks!

**Comment by lizan** [comment]
@mabukhovsky Here's what I meant:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: http
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: "X-Host-Port"
                    suffix_match: ":443"
                route:
                  cluster: dynamic_forward_proxy_cluster_tls
                per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    auto_host_rewrite_header: "X-Host-Port"
              - match:
                  prefix: "/"
                route:
                  cluster: dynamic_forward_proxy_cluster
                per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    auto_host_rewrite_header: "X-Host-Port"
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.filters.http.router
  clusters:
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
  - name: dynamic_forward_proxy_cluster_tls
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca: {filename: /etc/ssl/certs/ca-certificates.crt}
```

Basically it set two route:
- one matches if `X-Host-Port` ends with `:443` and send it to `dynamic_forward_proxy_cluster_tls`
- another one matches everything else and send it to `dynamic_forward_proxy_cluster`.

Is this what you meant?

**Comment by mabukhovsky** [comment]
Hi @lizan , thank you for providing the config, I'm grateful for your time and efforts. I'm facing the following issue:
```
$ curl --header "X-Sage-Host-Port: www.yahoo.com" https://www.google.com
curl: (56) Received HTTP code 403 from proxy after CONNECT
```
This is a [known issue](https://github.com/envoyproxy/envoy/issues/10160#issuecomment-591432025) I was asking about some time ago.

@mattklein123 mentioned that @alyssawilk is working on adding CONNECT support to upstreams, I see it is not merged yet: https://github.com/envoyproxy/envoy/pull/10623/files @alyssawilk Please let me know if your commit will enable CONNECT for both HTTP and HTTPS?

**Comment by lizan** [comment]
@mabukhovsky the downstream client have to connect to Envoy in plaintext. so if you do
`curl --header "X-Host-Port: www.yahoo.com" http://127.0.0.1:10000` Envoy connects to www.yahoo.com in plaintext.
`curl --header "X-Host-Port: www.yahoo.com:443" http://127.0.0.1:10000` then Envoy connects to www.yahoo.com in TLS.

**Comment by moderation** [comment]
I've been testing and struggling with the dynamic forward proxy and the new SNI dynamic forward proxy over the last couple of days. The examples in the documentation don't work out of the gate. For those interested a v3 API version of @lizan's example above is below:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 127.0.0.1
      protocol: TCP
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        protocol: TCP
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: http
              domains:
              - '*'
              routes:
              - match:
                  prefix: /
                  headers:
                  - name: X-Host-Port
                    suffix_match: :443
                route:
                  cluster: dynamic_forward_proxy_cluster_tls
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                    host_rewrite_header: X-Host-Port
              - match:
                  prefix: /
                route:
                  cluster: dynamic_forward_proxy_cluster
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                    host_rewrite_header: X-Host-Port
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.filters.http.router
  clusters:
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
  - name: dynamic_forward_proxy_cluster_tls
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
```
