### ISSUE TITLE
Outlier detection cannot eject unhealthy hosts

### ISSUE THREAD

**Issue by freesnowCL** [envoyproxy/envoy#10770]
I used the httpbin docker image to test the health check and outlier detection feature of envoy in a k8s cluster:
```
...
      clusters:
      - name: httpbin
        outlier_detection:
          consecutive_5xx: 3
          interval: 1s
          base_ejection_time: 60s
          max_ejection_percent: 100   # eject all hosts
...
```

I expected the host to be ejected after I pass 3 consecutive `/status/500` requests to it:
```
curl http://$envoyUrl/httpbin/status/500

HTTP/1.1 500 Internal Server Error
server: envoy
date: Tue, 14 Apr 2020 09:48:20 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 0
```

I also checked the cluster statistics using admin API:
```
...
httpbin::10.100.122.245:80::health_flags::/failed_outlier_check
...
```

But when I pass a `status/200/` request to it, it returned HTTP 200:
```
curl http://$envoyUrl/httpbin/status/200

HTTP/1.1 200 OK
server: envoy
date: Tue, 14 Apr 2020 09:48:25 GMT
content-type: text/html; charset=utf-8
access-control-allow-origin: *
access-control-allow-credentials: true
content-length: 0
x-envoy-upstream-service-time: 1
```

I also tried for 2 httpbin pods and over 10 consecutive 500 requests, but the hosts did not get ejected.
