### ISSUE TITLE
Cannot use TLS with TCP Proxy

### ISSUE THREAD

**Issue by suvl** [envoyproxy/envoy#10874]
*Title*: *Unable to create a TLS listener with TCP Proxy alone*

*Description*:
I'm trying to create a TLS termination proxy for RSyslog but I'm being unable to make envoy perform the TLS part of the proxying.

Here's my config:
```yaml
static_resources:
  listeners:
  - name: rsyslog-filter
    address:
      socket_address: { address: 0.0.0.0, port_value: 6514 }
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names: ["syslog.example.com"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: "/certs/tls.crt" }
              private_key: { filename: "/certs/tls.key" }
      filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
          stat_prefix: ingress_tcp
          cluster: rsyslog_server
          max_connect_attempts: 3
          access_log:
          - name: rsyslog.access_log
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
  clusters:
  - name: rsyslog-server
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 514
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

Envoy is being launched as a container in a pod and it is now proxying from the 6514 port to the 514 port where there's another container listening. Connections do flow, but the TLS part is not working despite my efforts. I've tried for version 1.14.1 and for `envoy-dev:latest`.
