### ISSUE TITLE
Envoy segfault using Redis Proxy

### ISSUE THREAD

**Issue by aviramha** [envoyproxy/envoy#10873]
I encounter a determinstic crash in my workload each time the app tries to connect to it (for Redis)
Using this image as sidecar for the app:
envoyproxy/envoy-alpine:v1.13.1

Log:
```
[2020-04-21 11:15:06.953][24][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x75b5886fd3eb
4/21/2020 2:15:06 PM [2020-04-21 11:15:06.953][24][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
4/21/2020 2:15:06 PM [2020-04-21 11:15:06.953][24][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: b67c14052c49890a7e3afe614d50979c346c024b/1.13.1/Clean/RELEASE/BoringSSL
4/21/2020 2:15:06 PM [2020-04-21 11:15:06.953][24][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #0: [0x7fc80c284420]
4/21/2020 2:15:06 PM [2020-04-21 11:15:06.953][24][critical][backtrace] [bazel-out/k8-opt/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:77] #1: [0x996d36dc1961aae5]
4/21/2020 2:15:07 PM Segmentation fault (core dumped)

```
Example configuration:
```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          downstream_auth_password:
            inline_string: local
          settings:
            op_timeout: 1s
            enable_command_stats: True
          prefix_routes:
            routes:
              - prefix: "first_prefix_"
                cluster: "reg"
                request_mirror_policy:
                  cluster: "lp"
                  exclude_read_commands: True
              - prefix: "second_prefix_"
                cluster: "reg"
                request_mirror_policy:
                  cluster: "lp"
                  exclude_read_commands: True
            catch_all_route:
              cluster: "reg"
  clusters:
  - name: lp
    connect_timeout: 6s
    type: strict_dns
    load_assignment:
      cluster_name: redis_lp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redishost2
                port_value: 19382
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "censored"}
  - name: reg
    connect_timeout: 6s
    type: strict_dns
    load_assignment:
      cluster_name: redis
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redishost
                port_value: 19191
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "censored"}
```
