### ISSUE TITLE
TLS HealthCheck for non-TLS endpoints

### ISSUE THREAD

**Issue by bvandewalle** [envoyproxy/envoy#10888]
We are using Envoy as a Layer 4 load balancer (based on SNI). Envoy doesn't terminate TLS.
However, we would like to perform HealthChecks over TLS, and there seems to be no way to enable healthChecks over TLS.

I would have expected that enabling the `tls_option` under the `health_checks` config would result in a TLS enabled healthcheck as described here: 

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#core-healthcheck-tlsoptions

However I can see the healthcheck request being issued as `HTTP`, not `HTTPS`.
I also dumped the config and confirmed that the `tls_option` got correctly configured.

Am I misusing this `tls_option` parameter or is this by design?

**Listener config:**
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.Listener
  name: https_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  listener_filters:
  - name: "envoy.listener.tls_inspector"
    config: {}
  filter_chains:
  - filter_chain_match:
      transport_protocol: tls
      server_names:
        - demoapp.com
    filters:
    - name: envoy.tcp_proxy
      config:
        access_log:
          - name: envoy.file_access_log
            config:
              path: /var/log/envoy/envoy_tcp.log
        stat_prefix: prod_west
        cluster: demoapp_cluster
```

**Cluster config:**

```
resources:
- "@type": "type.googleapis.com/envoy.api.v2.Cluster"
  name: demoapp_cluster
  connect_timeout: 1s
  type: strict_dns
  lb_policy: MAGLEV
  health_checks:
    tls_options: 
      alpn_protocols:
    timeout: 4s
    interval: 4s
    unhealthy_threshold: 2
    healthy_threshold: 2
    http_health_check:
      host: demoapp.com
      path: "/"
      expected_statuses:
        start: 200
        end: 399
    event_log_path: /dev/stdout
  load_assignment:
    cluster_name: demoapp_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: endpoint1
              port_value: 443
      - endpoint:
          address:
            socket_address:
              address: endpoint2
              port_value: 443
```
