### ISSUE TITLE
Headers values/variables in path

### ISSUE THREAD

**Issue by featureed** [envoyproxy/envoy#10956]
Hi.

Is it possible to use request headers' values or envoy internal variables (like in access log) in redirect action?

For example, like this:
```
domains:
- host1.com
- hosttest.com
- someotherhost.com
routes:
  match:
    prefix: "/"
  redirect:
    host_redirect: "host2.com"
    prefix_rewrite: "/referer/%REQ(:AUTHORITY)%/"
```

Found few issues here about the same problem, but all of them were unanswered.

In nginx this can be easily done using $host or $http_host variables. Is there some workaround for that in envoy?
