### ISSUE TITLE
Question: envoy timeout exception configuration allowed?

### ISSUE THREAD

**Issue by sp-manuel-jurado** [envoyproxy/envoy#10986]
Hello, is it possible to overwrite the headers of the envoy [route timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-field-route-routeaction-timeout) exception so that the grpc_http1_reverse_bridge can understand them?

When a route timeout happens, we receive this exception:
```
RpcError Code: 2 Message: Status (StatusCode = Unknown, Detail = "envoy reverse bridge: upstream responded with unsupported content-type application/grpc, status code 200")
```

When they are exceptions handled by our upstream (http1.1 and It doesn't understand gRPC semantics), we have no problem because we generate the http1.1 response with status code 500 and the following headers:

```
Content-Type: 'application/grpc+proto'
Content-Length: 0
grpc-status: n
grpc-message: 'message'
grpc-status-details: {}
```

Note: this is the configuration

```
static_resources:
  listeners:
    ...
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        ...
              - match:
                  prefix: "/"
                route:
                  host_rewrite: x
                  cluster: backend
                  timeout: 2.00s
          http_filters:
            - name: envoy.filters.http.grpc_http1_reverse_bridge
              config:
                content_type: application/grpc+proto
                withhold_grpc_frames: true
            - name: envoy.router
      use_proxy_proto: true
      ...
  clusters:
  - name: backend
    connect_timeout: 1.00s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: xxx
          port_value: 80
    ....
```

Thanks in advance.
