### ISSUE TITLE
cluster filter optimization

### ISSUE THREAD

**Issue by zengyuxing007** [envoyproxy/envoy#10991]
At present, envoy supports custom filters under cluster semantics,

``` yaml
  clusters:   # Outgoing connections
  - name: ernie
    filters:
    - name: envoy.filters.network.amqp_client
      config: { bridge: { named_relay: ernie } } 
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 15672 }}] 
    type: static
    connect_timeout: 0.25s          
```

 but the upstream messages obtained by each cluster filter are raw original messages;

Like "http + json <=> envoy <=> grpc server" or
"Http <=> envoy <=> amqp server"
 These series of requirements depends on the parsed message from the downstream http_connection_manager, and it is necessary to construct an upstream request based on the http header and body

Currently implemented, every cluster filter onData interface receives raw original message,
Need to do http parser parsing again,

``` cpp

void ConnectionImpl::write(Buffer::Instance& data, bool end_stream, bool through_filter_chain) {
  ASSERT(!end_stream || enable_half_close_);

  if (write_end_stream_) {
    // It is an API violation to write more data after writing end_stream, but a duplicate
    // end_stream with no data is harmless. This catches misuse of the API that could result in data
    // being lost.
    ASSERT(data.length() == 0 && end_stream);

    return;
  }

  if (through_filter_chain) {
    // NOTE: This is kind of a hack, but currently we don't support restart/continue on the write
    //       path, so we just pass around the buffer passed to us in this function. If we ever
    //       support buffer/restart/continue on the write path this needs to get more complicated.
    current_write_buffer_ = &data;
    current_write_end_stream_ = end_stream;
    FilterStatus status = filter_manager_.onWrite();
    current_write_buffer_ = nullptr;

    if (FilterStatus::StopIteration == status) {
      return;
    }   
  }

  write_end_stream_ = end_stream;
  if (data.length() > 0 || end_stream) {
    ENVOY_CONN_LOG(trace, "writing {} bytes, end_stream {}", *this, data.length(), end_stream);
    // TODO(mattklein123): All data currently gets moved from the source buffer to the write buffer.
    // This can lead to inefficient behavior if writing a bunch of small chunks. In this case, it
    // would likely be more efficient to copy data below a certain size. VERY IMPORTANT: If this is
    // ever changed, read the comment in SslSocket::doWrite() VERY carefully. That code assumes that
    N    source/common/network/connection_impl.cc             
```

It is recommended to optimize the process here！
