### ISSUE TITLE
Invalid Access-Control-Allow-Origin header with custom URI scheme

### ISSUE THREAD

**Issue by alienvspredator** [envoyproxy/envoy#11039]
Description:

The origin is in the custom scheme "package: //". When I make an xhr request, I get the following error:

```log
"Access to XMLHttpRequest at 'http://10.211.55.2:8811/test' from origin 'package://' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'package://' that is not equal to the supplied origin.", source: package://gui/test.html (0)
```

This is due to an invalid Access-Control-Allow-Origin header value.

My envoy config for processing preflight requests looks like this:

```yaml
cors:
  allow_origin_string_match:
    - prefix: "*"
  allow_methods: GET, PUT, DELETE, POST, OPTIONS
  allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
  max_age: "1728000"
  expose_headers: grpc-status,grpc-message
```

Envoy log:

```log
[2020-05-02T05:11:54.714Z] "OPTIONS /test HTTP/1.1" 200 - 0 0 0 - "-" "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "002d44a4-a2f8-4f85-a3d8-efd063790ff4" "10.211.55.2:8811" "-"
```
