### ISSUE TITLE
Support 404 NotFound with gRPC-JSON transcoder when an unknown url comes in

### ISSUE THREAD

**Issue by longkai** [envoyproxy/envoy#11042]
Currently, if.an unknown or mistyped HTTP request url comes in envoy, it will return something like below(will not delivery to upstream gRPC services):

```http
HTTP/1.1 503 Service Unavailable
content-length: 85
content-type: text/plain
date: Mon, 04 May 2020 13:47:45 GMT
server: istio-envoy
x-envoy-upstream-service-time: 86

upstream connect error or disconnect/reset before headers. reset reason: remote reset
```

It is a client error. Often in HTTP services, returning a 404 is rational.

It would be great envoy provides this feature.

**Comment by qiwzhang** [comment]
It makes sense.  It is a legitimate request. Just to be careful, some people will add grpc_transcoder filter for both grpc and http backends.  So this feature should be guarded by a filter config as:

No_match_url_action:
*  skip_transcoding_and_forward;   //current behaviors
*  reject_with_404;

**Comment by longkai** [comment]
Thanks for the advice.

With wireshark, I found envoy did forward the not found request to the upstream but it won't logged in the interceptor. 

I am interested implementing this feature but I am not familiar with C++, so it may takes sometime.

**Comment by lych77** [comment]
After some exploration I've found the 503's are originated from the upstream gRPC server, as it sees an malformed request bypassed by Envoy (specifically, lacking the `content-type` header), it resets the stream with the error code `INTERNAL_ERROR`, and that consequently causes Envoy to generate a 503 response. If you try manually adding a `content-type: application/grpc` header field to your original HTTP request, you may see a more reasonable reply. see <https://github.com/grpc/grpc-go/issues/3819>, I was using a [grpc-go](https://github.com/grpc/grpc-go) server and don't know what kind of gRPC server you are using, but the behaviors might be alike.

And this can be workarounded by the following approach (I did it by an Istio EnvoyFilter and bare Envoys can be configured alike):

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gr-transcoder
spec:
  workloadSelector:
    labels:
      app: gr
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          portNumber: 9527
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.grpc_json_transcoder
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
            proto_descriptor: /etc/envoy/demo.desc
            services: [demo.Demo]
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          portNumber: 9527
          vhost:
            name: inbound|http|9527
      patch:
        operation: MERGE
        value:
          match:
            headers:
              - name: content-type
                prefix_match: application/grpc        # according to the gRPC spec there may be a suffix to the value, so prefix_match is used here

```

This restricts the route to requests having a valid `content-type` header, i.e. the ones really transcoded by the filter, and the bypassed ones without this field will trigger 404's. If more specific actions are needed, this configuration can be extended easily.
