### ISSUE TITLE
RBAC settings question

### ISSUE THREAD

**Issue by freesnowCL** [envoyproxy/envoy#11063]
I wanted to set up the RBAC filter but somehow it doesn't work:

```
...
            http_filters:
            - name: envoy.filters.http.rbac
              config:
                action: ALLOW
                policies:
                  "admin-user":
                    permissions:
                      - any: true
                    principals:
                      - header: { name: "test", exact_match: "111" }
                  "general-user":
                    permissions:
                      - not_rule:
                        - path: { prefix: "/demo.grpc.api.v1.Demo/" }
                    principals:
                      - any: true
...
```

I expected only requests with header `test: 111` can access the service with prefix `/demo.grpc.api.v1.Demo/`, but it turns out all requests can still access the service

Could you let me know where I got it wrong?
