### ISSUE TITLE
Envoy Tracing for Zipkin and Jaeger is not working for 1.13.1

### ISSUE THREAD

**Issue by mike1808** [envoyproxy/envoy#11076]
Hi. I'm trying to test requests tracing feature for Envoy. I followed the [Jaeger tracing docs for 1.13.1](https://www.envoyproxy.io/docs/envoy/v1.13.1/start/sandboxes/jaeger_tracing) and put an appropriate tag for Docker images in the sandbox to use 1.13.1. And after starting all containers and sending few requests Jaeger UI doesn't show anything. I also tried to use jaeger-query API:

```
curl http://localhost:16686/api/traces?service=front-proxy
```

And it also returns an empty result. I tried to perform tcpdump inside the Envoy container and I didn't find any packets sent to jaeger-collector. 

However, tracing works in the latest published version (1.15) where `tracing` configuration was moved to HttpConnectionManager config. 

Repro steps:
1. Checkout to `release/v1.13`
1. Modify [examples/front-proxy/Dockerfile-frontenvoy](https://github.com/envoyproxy/envoy/blob/release/v1.13/examples/front-proxy/Dockerfile-frontenvoy) and [examples/front-proxy/Dockerfile-service](https://github.com/envoyproxy/envoy/blob/release/v1.13/examples/front-proxy/Dockerfile-service) base image tag to the one used in 1.13. I used `bb7ceff4c3c5bd4555dff28b6e56d27f2f8be0a7`
1. Go to the example folder: `cd examples/jaeger-tracing`
1. Start containers: `docker-compose up --build -d`
1. Perform requests `curl -v localhost:8000/trace/1`
1. Check Jaeger UI: `curl http://localhost:16686/api/traces?service=front-proxy`
1. The results will be empty.

If you do the same on `master` or `release/v.1.15` the results from Jaeger will contain traces.

**Comment by dio** [comment]
@mike1808 I think you need to add a `tracing` entry as in this commit: https://github.com/envoyproxy/envoy/commit/7ab9307a678e27b50df06c20108dee3911b947ac

The relevant part:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    traffic_direction: OUTBOUND
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          generate_request_id: true
          tracing: {}
          codec_type: auto
          stat_prefix: ingress_http
          ...
```

Yes, this is needed also for `envoyproxy/envoy:v1.13.1` image.
