### ISSUE TITLE
http2_protocol_options.stream_error_on_invalid_http_messaging with reverse bridge

### ISSUE THREAD

**Issue by sp-manuel-jurado** [envoyproxy/envoy#11099]
Hi,

I'm configuring envoy (v1.12.2) as level two proxy (sidecar) within reverse bridge filter enabled only, and using an ingress controller envoy based as level one proxy.

I've read [this article](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/level_two) and I checked using http2_protocol_options.stream_error_on_invalid_http_messaging=true, but I continue getting this error (only for grpc errors; for grpc succesful responses works correctly):
```
{
  "error": "14 UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection termination"
}
```

If I do the calls directly to the service (which contains the sidecar), both cases (grpc errors and grpc successful responses) work correctly, and there is no connection termination.

Is it possible that this config does not apply to the reverse bridge?
Would there be any workaround?

This is the filter config (the upstream doesn't understand grpc semantics):
```
- name: envoy.filters.http.grpc_http1_reverse_bridge
   config:
     content_type: application/grpc+proto
     withhold_grpc_frames: true
```

This is the http connection manager config:
```
 - name: envoy.http_connection_manager
    config:
      http2_protocol_options:
        stream_error_on_invalid_http_messaging: true
```

Thank you in advance.

**Comment by alyssawilk** [comment]
FWIW what stream_error_on_invalid_http_messaging controls is if there's an HTTP/2 level issue if the stream is closed or if the full connection is closed.  It shouldn't change the validation which is being performed, or look at the gRPC layer at all, it just controls how thoroughly HTTP/2 non-compliant traffic is rejected.

**Comment by sp-manuel-jurado** [comment]
Hi @alyssawilk ,
thanks for the quick reply.

This is a correct grpc-response (with grpc error) returned by the L2 proxy.
You can see the header "grpc-status-details":
```
Response trailers received:
access-control-allow-origin:
cache-control: no-cache, private
content-length: 5
content-type: application/grpc
date: Thu, 07 May 2020 18:41:50 GMT
grpc-status-details: {"code":2,"message":"Invalid argument type","details":{}}
server: envoy
x-envoy-upstream-healthchecked-cluster:
x-envoy-upstream-service-time: 23
Sent 1 request and received 0 responses
ERROR:
  Code: Unknown
  Message: Invalid argument type
```

This L2 proxy doesn't have any cluster/upstream that understand grpc (only http1.1), so this response is transformed by the http filter grpc-http1-reverse-bridge.

Guessing that grpc is a protocol over http2 and reading:
```
stream_error_on_invalid_http_messaging:
(bool) Allows invalid HTTP messaging and headers. When this option is disabled (default), then the whole HTTP/2 connection is terminated upon receiving invalid HEADERS frame. However, when this option is enabled, only the offending stream is terminated.
```

I suspect that envoy L1 detects "grpc-status-details" as an invalid header and close de connection, even if stream_error_on_invalid_http_messaging is set to true (due to reverse bridge casuistry). But I'm not 100% sure, maybe is another issue.

This is the L1 proxy response:
```
Request metadata to send:
(empty)

Response headers received:
(empty)

Response trailers received:
content-type: application/grpc
date: Thu, 07 May 2020 18:44:50 GMT
server: envoy
Sent 1 request and received 0 responses
ERROR:
  Code: Unavailable
  Message: upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

I've checked using L1 ingress controller non envoy based and works as expected.

Note:
grpc_http1_reverse_bridge_filter:
This is a filter that enables converting an incoming gRPC request into a HTTP/1.1 request to allow a server that does not understand HTTP/2 or gRPC semantics to handle the request.

**Comment by sp-manuel-jurado** [comment]
This is the level 2 envoy configuration in case it was useful:

```
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              http2_protocol_options:
                stream_error_on_invalid_http_messaging: true
              stream_idle_timeout: 40.00s
              use_remote_address: false
              access_log:
              - name: envoy.file_access_log
                config:
                  path: /dev/stdout
              stat_prefix: ingress_http_reverse
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      host_rewrite: service-http11
                      cluster: backend
              http_filters:
                - name: envoy.filters.http.grpc_http1_reverse_bridge
                  config:
                    content_type: application/grpc+proto
                    withhold_grpc_frames: true
                - name: envoy.health_check
                  config:
                    pass_through_mode: true
                - name: envoy.router
                  config: {}
          use_proxy_proto: false
      clusters:
      - name: backend
        connect_timeout: 5.00s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        http_protocol_options: {}
        hosts:
          - socket_address:
              address: service-http11
              port_value: 80
```
