### ISSUE TITLE
Support SPDY

### ISSUE THREAD

**Issue by weixiao-huang** [envoyproxy/envoy#11190]
In [envoy's documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/what_is_envoy), it shows that it does not support SPDY. However, we usually want to use it in kubernetes' projects.
In `kubectl exec` command, it widely uses SPDY to connect with kube-apiserver. So is there some plan to support SPDY?

**Comment by moderation** [comment]
HTTP/3 is the successor to SPDY and is still in the draft phase - https://tools.ietf.org/html/draft-ietf-quic-http. Work is being done in Envoy to support HTTP/3 but this is not yet enabled in the builds. I expect that once HTTP/3 is finalized support in Envoy will happen at some point.

**Comment by mattklein123** [comment]
SPDY is the precursor to HTTP/2 and is no longer supported, we won't implement it in Envoy. See https://github.com/kubernetes/kubernetes/issues/7452.

**Comment by weixiao-huang** [comment]
Now we find that kube-apiserver only proxies requests from kubectl exec. The real SPDY request is resolved in kubelet. However, we find that kubelet also supports websocket for receiving exec operation. So we use websocket to interact with kube-apiserver so that it can proxy it to kubelet's websocket api. There is a very simple example for using websocket to implement exec: https://github.com/kairen/websocket-exec. And this is another discussion for this: https://github.com/kubernetes/kubernetes/issues/89163. So we can use websocket to implement this function. Thanks for your answer.

**Comment by mikedanese** [comment]
Late comment: envoy "supports" spdy enough to front kube-apiserver. Use a route config that looks like:

```
route_config:
  name: frontproxy
  virtual_hosts:
  - domains:
    - "*"
    name: apiserver
    routes:
    - match:
        headers:
        - name: Upgrade
        - exact_match: Upgrade
          name: Connection
        prefix: "/"
      route:
        cluster: apiserver_upgrade
        timeout: 2592000s
        upgrade_configs:
        - upgrade_type: spdy/3.1
        - upgrade_type: websocket
    - match:
        prefix: "/"
      route:
        cluster: apiserver
        timeout: 2592000s
```

Then enable h2 on `apiserver` cluster. Disable h2 on `apiserver_upgrade`.

Fuller config (that worked a year ago but might need some fiddling): https://gist.github.com/mikedanese/7f1812a328ac43f88d9c49fee7670bce
