### ISSUE TITLE
"No TLS certificates found for server context" for common_tls_context with valid CRT file

### ISSUE THREAD

**Issue by mabukhovsky** [envoyproxy/envoy#11198]
Hi guys, I have a listener with filters that forward requests to one of 2 dynamic_foward_proxy clusters (one for HTTPS, one for HTTP) traffic based on request header values. I would like this listener to be accessible only via https request and included corresponding filter_chain and common_tls_context pointing to a valid CRT file. However I'm still getting "No TLS certificates found for server context" issue and Envoy is shutting down automatically. Please advise if any changes in config are needed to fix the issue. P.S: provided config it works fine without common_tls_context but only for HTTP requests.

### Config
```
admin:
  access_log_path: %WD_HOME%/logs/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: %ADMIN_PORT% }
static_resources:
  listeners:
    - name: exposed_admin_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: %EXPOSED_ADMIN_PORT% }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                access_log:
                  - name: envoy.file_access_log
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
                      path: %WD_HOME%/logs/exposed_admin_access.log
                route_config:
                  name: envoy_admin
                  virtual_hosts:
                    - name: envoy_admin
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/app_info/metrics" }
                          route: { cluster: exposed_admin, prefix_rewrite: "/stats/prometheus" }
                http_filters:
    - name: listener_1
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10324
      filter_chains:

# UPDATE: filter chain match to make listener accessible only via https requests

        - filter_chain_match: { source_type: ANY }
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                validation_context:
                  trusted_ca: {filename: /etc/ssl/certs/ca-bundle.crt}

        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                            headers:
                              - name: "X-Proto"
                                exact_match: "https"
                          route:
                            cluster: dynamic_forward_proxy_cluster_tls
                          per_filter_config:
                            envoy.filters.http.dynamic_forward_proxy:
                              auto_host_rewrite_header: "X-Host-Port"
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                          per_filter_config:
                            envoy.filters.http.dynamic_forward_proxy:
                              auto_host_rewrite_header: "X-Host-Port"
                http_filters:
                  - name: envoy.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: xds_cluster
                        timeout: 5s
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                  - name: envoy.filters.http.router
  clusters:
    - name: xds_cluster
      connect_timeout: 5s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
          common_tls_context:
            alpn_protocols: [
              "h2"
            ]
      dns_refresh_rate:
        seconds: 3600
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: %XDS_HOST%
                      port_value: %XDS_PORT%

    - name: dynamic_forward_proxy_cluster
      connect_timeout: 5s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
    - name: dynamic_forward_proxy_cluster_tls
      connect_timeout: 5s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trusted_ca: {filename: /etc/ssl/certs/ca-bundle.crt}
    - name: exposed_admin
      connect_timeout: 0.250s
      type: STATIC
      hosts:
        - socket_address: { address: 127.0.0.1, port_value: %ADMIN_PORT% }
node:
  id: %NODE_ID%
  cluster: %NODE_CLUSTER%
  metadata:
    instance: %NODE_INSTANCE%
    host: %NODE_HOST%
    port: %NODE_PORT%
    admin_port: %ADMIN_PORT%
```

### Logs

```
proxy_1        | [2020-05-14 18:04:10.577][1][debug][config] [source/server/filter_chain_manager_impl.cc:214] new fc_contexts has 1 filter chains, including 1 newly built
proxy_1        | [2020-05-14 18:04:10.578][1][debug][config] [source/server/listener_impl.cc:80] Create listen socket for listener exposed_admin_listener on address 0.0.0.0:10328
proxy_1        | [2020-05-14 18:04:10.578][1][debug][config] [source/server/listener_impl.cc:70] Set listener exposed_admin_listener socket factory local address to 0.0.0.0:10328
proxy_1        | [2020-05-14 18:04:10.578][1][debug][config] [source/server/listener_impl.cc:508] add active listener: name=exposed_admin_listener, hash=17057273911243491833, address=0.0.0.0:10328
proxy_1        | [2020-05-14 18:04:10.578][1][debug][config] [source/server/configuration_impl.cc:81] listener #1:
proxy_1        | [2020-05-14 18:04:10.578][1][debug][config] [source/server/listener_manager_impl.cc:386] begin add/update listener: name=listener_1 hash=332932127160212014
proxy_1        | [2020-05-14 18:04:10.581][1][critical][main] [source/server/server.cc:95] error initializing configuration '/usr/local/envoy/envoy.yaml': No TLS certificates found for server context
proxy_1        | [2020-05-14 18:04:10.581][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:35] Joining completionThread
proxy_1        | [2020-05-14 18:04:10.582][63][debug][grpc] [source/common/grpc/google_async_client_impl.cc:68] completionThread exiting
proxy_1        | [2020-05-14 18:04:10.582][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:37] Joined completionThread
proxy_1        | [2020-05-14 18:04:10.582][1][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:942] shutting down thread local cluster manager
proxy_1        | [2020-05-14 18:04:10.584][1][info][main] [source/server/server.cc:606] exiting
proxy_1        | No TLS certificates found for server context
proxy_1 exited with code 1
rabbitmq_1     | Last login: Thu May 14 16:38:50 2020 from 8.18.220.189
```

**Comment by lizan** [comment]
For server context you need `tls_certificate` (not a validation context), which doesn't exist in your config.

**Comment by mabukhovsky** [comment]
@lizan Thanks for quick response. Per your clue I've modified dynamic_forward_proxy_cluster_tls config to include tls_certificate. Now server starts successfully.
```
    - name: dynamic_forward_proxy_cluster_tls
      connect_timeout: 5s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.cluster.dynamic_forward_proxy.v2alpha.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
              certificate_chain: { "filename": "/etc/envoy/envoy.crt" }
              private_key: { "filename": "/etc/envoy/envoy.key" }
```
When I'm trying to make HTTPS connection to the server (https://envoy-proxy:10324/) I'm hitting the following issue.
```
proxy_1        | [2020-05-15 04:30:14.232][67][trace][connection] [source/common/network/connection_impl.cc:493] [C0] socket event: 2
proxy_1        | [2020-05-15 04:30:14.232][67][trace][connection] [source/common/network/connection_impl.cc:581] [C0] write ready
proxy_1        | [2020-05-15 04:30:14.250][67][trace][connection] [source/common/network/connection_impl.cc:493] [C0] socket event: 3
proxy_1        | [2020-05-15 04:30:14.250][67][trace][connection] [source/common/network/connection_impl.cc:581] [C0] write ready
proxy_1        | [2020-05-15 04:30:14.250][67][trace][connection] [source/common/network/connection_impl.cc:531] [C0] read ready
proxy_1        | [2020-05-15 04:30:14.250][67][trace][connection] [source/common/network/raw_buffer_socket.cc:25] [C0] read returns: 204
proxy_1        | [2020-05-15 04:30:14.250][67][trace][connection] [source/common/network/raw_buffer_socket.cc:39] [C0] read error: Resource temporarily unavailable
proxy_1        | [2020-05-15 04:30:14.251][67][trace][http] [source/common/http/http1/codec_impl.cc:470] [C0] parsing 204 bytes
proxy_1        | [2020-05-15 04:30:14.251][67][trace][connection] [source/common/network/connection_impl.cc:429] [C0] writing 66 bytes, end_stream false
proxy_1        | [2020-05-15 04:30:14.251][67][debug][http] [source/common/http/conn_manager_impl.cc:283] [C0] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
proxy_1        | [2020-05-15 04:30:14.251][67][debug][connection] [source/common/network/connection_impl.cc:109] [C0] closing data_to_write=66 type=2
proxy_1        | [2020-05-15 04:30:14.251][67][debug][connection] [source/common/network/connection_impl_base.cc:30] [C0] setting delayed close timer with timeout 1000 ms
proxy_1        | [2020-05-15 04:30:14.252][67][trace][connection] [source/common/network/connection_impl.cc:493] [C0] socket event: 2
proxy_1        | [2020-05-15 04:30:14.252][67][trace][connection] [source/common/network/connection_impl.cc:581] [C0] write ready
proxy_1        | [2020-05-15 04:30:14.252][67][trace][connection] [source/common/network/raw_buffer_socket.cc:68] [C0] write returns: 66
proxy_1        | [2020-05-15 04:30:14.252][67][debug][connection] [source/common/network/connection_impl.cc:622] [C0] write flush complete
proxy_1        | [2020-05-15 04:30:14.257][67][trace][connection] [source/common/network/connection_impl.cc:493] [C0] socket event: 6
proxy_1        | [2020-05-15 04:30:14.257][67][debug][connection] [source/common/network/connection_impl.cc:514] [C0] remote early close
proxy_1        | [2020-05-15 04:30:14.257][67][debug][connection] [source/common/network/connection_impl.cc:200] [C0] closing socket: 0
```
