### ISSUE TITLE
Envoy exit with code 1 on docker run with no extra information [Please help]

### ISSUE THREAD

**Issue by huynhthanhbinh** [envoyproxy/envoy#11230]
I current run envoy with docker in my project, start it up with docker compose.
But as soon as it start, it exit with code 1, with no more information.

Here is my envoy.yaml:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: saigonparking_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: saigonparking_gateway
                            max_grpc_timeout: 0s
                      cors:
                        enabled: true
                        allow_origin:
                          - "*"
                        allow_methods: GET, POST, PUT, DELETE, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.router
  clusters:
    - name: saigonparking_gateway
      connect_timeout: 0.5s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts: [{ socket_address: { address: gateway, port_value: 9080 }}]
```

Here is my Dockerfile:

```
FROM envoyproxy/envoy:v1.11.0
USER root
COPY envoy.yaml /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
Here in my docker-compose

```
 proxy:
    image: ${DOCKER_HUB_ID}/proxy:v1.0
    networks:
      - saigonparking-gateway
    environment:
      TZ: ${TIMEZONE}
    ports:
      - "${PROXY_HTTP_PORT}:${PROXY_HTTP_PORT}"
      #- "${PROXY_HTTP_SSL_PORT}:${PROXY_HTTP_SSL_PORT}"
      - "127.0.0.1:${PROXY_ADMIN_PORT}:${PROXY_ADMIN_PORT}"
```

Here is log from console:

```
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:238] initializing epoch 0 (hot restart version=11.104)
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:240] statically linked extensions:
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:242]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:245]   filters.http: envoy.buffer,envoy.cors,envoy.csrf,envoy.ext_authz,envoy.fault,envoy.filters.http.dynamic_forward_proxy,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.original_src,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:248]   filters.listener: envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:251]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:253]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:255]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.tracers.opencensus,envoy.zipkin
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:258]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:261]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.tap,raw_buffer,tls
proxy_1              | [2020-05-17 11:27:57.844][6][info][main] [source/server/server.cc:267] buffer implementation: old (libevent)
proxy_1              | [2020-05-17 11:27:57.852][6][warning][misc] [source/common/protobuf/utility.cc:199] Using deprecated option 'envoy.api.v2.Cluster.hosts' from file cds.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details.

proxy_1              | [2020-05-17 11:27:57.855][6][info][main] [source/server/server.cc:322] admin address: 0.0.0.0:9901
proxy_1              | [2020-05-17 11:27:57.857][6][info][main] [source/server/server.cc:432] runtime: layers:
proxy_1              |   - name: base
proxy_1              |     static_layer:
proxy_1              |       {}
proxy_1              |   - name: admin
proxy_1              |     admin_layer:
proxy_1              |       {}
proxy_1              | [2020-05-17 11:27:57.857][6][warning][runtime] [source/common/runtime/runtime_impl.cc:497] Skipping unsupported runtime layer: name: "base"
proxy_1              | static_layer {
proxy_1              | }
proxy_1              | 
proxy_1              | [2020-05-17 11:27:57.857][6][info][config] [source/server/configuration_impl.cc:61] loading 0 static secret(s)
proxy_1              | [2020-05-17 11:27:57.857][6][info][config] [source/server/configuration_impl.cc:67] loading 1 cluster(s)
proxy_1              | [2020-05-17 11:27:57.859][6][info][config] [source/server/configuration_impl.cc:71] loading 1 listener(s)
proxy_1              | [2020-05-17 11:27:57.860][6][critical][main] [source/server/server.cc:93] error initializing configuration '/etc/envoy/envoy.yaml': Proto constraint validation failed (Using deprecated option 'envoy.api.v2.route.CorsPolicy.enabled' from file route.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): allow_origin: "*"
proxy_1              | allow_methods: "GET, POST, PUT, DELETE, OPTIONS"
proxy_1              | allow_headers: "keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization"
proxy_1              | expose_headers: "custom-header-1,grpc-status,grpc-message"
proxy_1              | max_age: "1728000"
proxy_1              | enabled {
proxy_1              |   value: true
proxy_1              | }
proxy_1              | 
proxy_1              | [2020-05-17 11:27:57.861][6][info][main] [source/server/server.cc:560] exiting
proxy_1              | Proto constraint validation failed (Using deprecated option 'envoy.api.v2.route.CorsPolicy.enabled' from file route.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.): allow_origin: "*"
proxy_1              | allow_methods: "GET, POST, PUT, DELETE, OPTIONS"
proxy_1              | allow_headers: "keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization"
proxy_1              | expose_headers: "custom-header-1,grpc-status,grpc-message"
proxy_1              | max_age: "1728000"
proxy_1              | enabled {
proxy_1              |   value: true
proxy_1              | }
proxy_1 exited with code 1

```

I don't know how to deal with it, I've tried to downgrade envoy 1,2,3 recent versions, but it no change.
I am looking forward to hearing from you ! Thank you very much ! Binh !
