### ISSUE TITLE
HTTP/1.1 503 Service Unavailable

### ISSUE THREAD

**Issue by Rahul7794** [envoyproxy/envoy#11257]
I am running envoy proxy with Grpc services. Here is my dockerfile which runs application through envoy proxy.

```
FROM golang:1.14.2-alpine3.11 as build-stage

# required by go get
RUN apk add --update --no-cache alpine-sdk bash python ca-certificates \
      libressl \
      tar \
      git openssh openssl yajl-dev zlib-dev cyrus-sasl-dev openssl-dev coreutils

WORKDIR /app

ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

COPY . /app

ARG COMMIT
ARG BUILD_DATE

RUN GOOS=linux go build -a -ldflags "-s -w -X github.com/xxx/xxx/version.GitCommit=${COMMIT} -X github.com/xxx/xxx/version.BuildDate=${BUILD_DATE}" -o service

FROM envoyproxy/envoy-alpine-dev:latest

COPY --from=build-stage /app/service /usr/local/bin/service

RUN chmod +x /usr/local/bin/group-code-service

COPY start-envoy.sh /start-envoy.sh
COPY envoy.yml /etc/envoy.yaml
COPY .certs/envoy.crt /etc/envoy.crt
COPY .certs/envoy.key /etc/envoy.key

RUN chmod +x /start-envoy.sh


EXPOSE 443

ENTRYPOINT ["/start-envoy.sh"]
```

here is my envoy.yml file

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_service
                http_filters:
                  - name: envoy.router
                    config: {}
          tls_context:
            common_tls_context:
              tls_certificates:
                - certificate_chain:
                    filename: "/etc/envoy.crt"
                  private_key:
                    filename: "/etc/envoy.key"
  clusters:
    - name: local_service
      connect_timeout: 0.5s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: localhost
            port_value: 8083
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
```

When I hit the server with 8083 port I am returning success code but somehow when I am hitting with 443 port which exposes envoy its throws 

```
bash-5.0# curl -I --insecure https://localhost/
HTTP/1.1 503 Service Unavailable
content-length: 95
content-type: text/plain
date: Tue, 19 May 2020 05:05:20 GMT
server: envoy

```

Any help is configuring envoy to TLS will be much appreciated.

**Comment by dio** [comment]
Hey, @Rahul7794!

I think you need to let the "cluster" to talk to your service using HTTP2 (since it is gRPC?). You can enable it by inserting default `[`http2_protocol_options`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-http2-protocol-options)` entry to the cluster.

Applying to your config:

```yaml
  clusters:
    - name: local_service
      connect_timeout: 0.5s
      type: strict_dns
      lb_policy: round-robin

      # This is where you insert it.
      http2_protocol_options: {}

      hosts:
        - socket_address:
            address: localhost
            port_value: 8083
```
