### ISSUE TITLE
How to log/get Retry mode Failure details (HTTP Response code, Response Time, etc..) ?

### ISSUE THREAD

**Issue by GaneshKumarKannan** [envoyproxy/envoy#11297]
Hi,
I am using envoy v1.12.1 - load_assignment with two endpoints as below,

```
- route:
                      cluster: cluster1
                      auto_host_rewrite: true
                      prefix_rewrite: "this/is/new"
                      retry_policy:
                        retry_on: "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes"
                        num_retries: 3

                        retriable_status_codes: ["401", "404", "500", "502", "503", "504"]
                        per_try_timeout: "5s"

                        retry_priority:
                          name: envoy.retry_priorities.previous_priorities
                          config:
                            update_frequency: 2

                    match:
                      prefix: "this/is/old"

clusters:
      - name:  cluster1
        connect_timeout: 10s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: cluster1
          endpoints:
          - priority: 1
            lb_endpoints:

            - endpoint:
                address:
                  socket_address: { address: "e1.com", port_value: 443 }				
          - priority: 0
            lb_endpoints:

            - endpoint:
                address:
                  socket_address: { address: "e2.com", port_value: 443}
```

As per my understanding, When priority 0 endpoint fails, it will try to hit priority 1 endpoint. 

In Such cases, Is it possible to get/log priority 0 endpoint hit failure reasons? As of now we can get logs of priority 1 endpoint hit alone by default.
