### ISSUE TITLE
RetryPolicy supports retry_on "no healthy upstream" in LB subsets

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#11307]
RetryPolicy currently supports various [retry condition](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#config-http-filters-router-x-envoy-retry-on) at route level.

Envoy also supports [load balancer subsets](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets) for a given cluster. However, when the RetryPolicy is NOT triggered when:
1) fallback_policy: NO_FALLBACK, and
2) lb_endpoints doesn't have any [lb_endpoint](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/endpoint/endpoint_components.proto#endpoint-lbendpoint) that matches the "envoy.lb" filter_metadata, or there is endpoint of the lb_endpoint is not healthy.

Our use case is to select a filter to pick a specific endpoint by setting the "envoy.lb" filter_metadata in the dynamicMetadata in [SteramInfo](https://github.com/envoyproxy/envoy/blob/74290ef76a76fbbf50f072dc33438791f93f68c7/include/envoy/stream_info/stream_info.h). We also use EDS to update the endpoints information. There can be a race between filter setting the filter_metadata vs EDS update being consumed by Envoy, which results in "no healthy upstream" error.

We assume the EDS will be available "soon". The simple solution to solve the race is to set up a RetryPolicy to retry on "no healthy upstream" error. 

Example Envoy config (EDS is not configure, but it shows the idea):
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 9090
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: upstream
                  timeout: 300s
                  retry_policy:
                    retry_on: 5xx,reset,connect-failure,refused-stream
                    num_retries: 1000
                    per_try_timeout: 1s
          http_filters:
          - name: envoy.router

  clusters:
  - name: upstream
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: LEAST_REQUEST
    lb_subset_config:
      fallback_policy: NO_FALLBACK
      subset_selectors:
        - keys:
          - target
    load_assignment:
      cluster_name: upstream
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
          metadata:
            filter_metadata:
              envoy.lb:
                target: "target_1"
    health_checks:
      - no_traffic_interval: 1s
        timeout: 1s
        healthy_threshold: 1
        tcp_health_check: {}
        interval: 30s
        unhealthy_interval: 30s
        unhealthy_threshold: 1
```
