### ISSUE TITLE
backwards compatibility issue with PR #11125 (Move access_log_format out of FileAccessLogger to be shared)

### ISSUE THREAD

**Issue by yuval-k** [envoyproxy/envoy#11371]
We updated envoy to recent master, and noticed one of e2e tests was failing. specifically, the semantics of using an empty string for file access log format has changed. It used to mean to output the default log format; after that change it outputs nothing.

To reproduce, use this config:

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          access_log:
          - name: "envoy.access_loggers.file"
            typed_config:
              "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog"
              path: /dev/stdout
              format: ""
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: namespace.local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: 
                  cluster: somecluster
          http_filters:
          - name: envoy.router
  clusters:
  - name: somecluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: somecluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8082
``` 

PR #11125 was merged to master in commit 00238028d51dd7e2a866e721a678dbc5cdbec996.
this outputs nothing:
```
docker run --rm -v $(pwd):$(pwd):ro -w $(pwd) -p 10000:10000 envoyproxy/envoy-alpine-dev:00238028d51dd7e2a866e721a678dbc5cdbec996 -c ./file-acess-log.yaml -l critical --file-flush-interval-msec 1
```

The commit before it, outputs access logs:
```
docker run --rm -v $(pwd):$(pwd):ro -w $(pwd) -p 10000:10000 envoyproxy/envoy-alpine-dev:853ecaa2f1e7364c1db49dad6a91bfcb3bcc4d61 -c ./file-acess-log.yaml -l critical --file-flush-interval-msec 1
```

(to trigger access logs, just `curl localhost:10000`; no need for a live upstream)
