### ISSUE TITLE
HCM request_header_to_add.append not working

### ISSUE THREAD

**Issue by dominicqi** [envoyproxy/envoy#11378]
Description:

I use the  [header append](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-headervalueoption).
but it not append to existing values. Will add a new header

Repro steps:

envoy config add header in `VirtualHost` ,then request envoy with a same name header .
` curl -H 'theader:12312' host:18000` 
Test with  envoy docker  image   `envoyproxy/envoy-dev:f13ea5b3ee906c4510d68f286a0f65b8b961d7b5`

Config:

```
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
#                http2_protocol_options: {}
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: service
                      domains:
                        - "*"
                      request_headers_to_add:
                        - header:
                            key: theader
                            value: append
                          append: true

```

Logs:

```
[2020-05-31 15:18:41.991][40][debug][http] [source/common/http/conn_manager_impl.cc:807] [C3][S15333841434755356732] request headers complete (end_stream=true):
':authority', '172.20.224.242:18000'
':path', '/'
':method', 'GET'
'user-agent', 'curl/7.29.0'
'accept', '*/*'
'theader', '12312'

[2020-05-31 15:18:41.991][40][debug][http] [source/common/http/conn_manager_impl.cc:1373] [C3][S15333841434755356732] request end stream
[2020-05-31 15:18:41.991][40][debug][router] [source/common/router/router.cc:441] [C3][S15333841434755356732] cluster 'oap6' match for URL '/'
[2020-05-31 15:18:41.991][40][debug][router] [source/common/router/router.cc:597] [C3][S15333841434755356732] router decoding headers:
':authority', '172.20.224.242:18000'
':path', '/'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.29.0'
'accept', '*/*'
'theader', '12312'
'x-forwarded-proto', 'http'
'x-request-id', 'cd03bf74-be50-4bce-ae66-027ef1d544a2'
'x-envoy-expected-rq-timeout-ms', '15000'
'theader', 'append'

```
