### ISSUE TITLE
Jaeger Native Tracing is broken after migration from 1.12.3 to 1.14.1

### ISSUE THREAD

**Issue by vadim-egt** [envoyproxy/envoy#11382]
In version 1.12.3 tracing worked. and we see messages 
```
[source/server/configuration_impl.cc:97] loading tracing configuration
[source/server/configuration_impl.cc:106]   loading tracing driver: envoy.dynamic.ot
```
 In version 1.14.1 we see message , but connection is absent. 
```
[2020-06-01 15:36:31.756][12727][info][config] [external/envoy/source/server/configuration_impl.cc:103] loading tracing configuration
[2020-06-01 15:36:31.756][12727][info][config] [external/envoy/source/server/configuration_impl.cc:114]   validating default server-wide tracing driver: envoy.tracers.dynamic_ot
```
In  migration we used you examples:
https://github.com/envoyproxy/envoy/blob/release/v1.14/examples/jaeger-native-tracing/front-envoy-jaeger.yaml

Please see our config:
```
static_resources:
  listeners:
  - name: web_grpc_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    traffic_direction: OUTBOUND
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          generate_request_id: true
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: grpc_proxy
              domains: ["*"]
              response_headers_to_remove: ["grpc-message"]
              routes:
              - match: { prefix: "/IPService" }
                route:
                  cluster: ip_service
                  max_grpc_timeout: 600s
                  prefix_rewrite: "/IPService"
          http_filters:
          - name: envoy.filters.http.ext_authz
            config:
                grpc_service:
                    envoy_grpc:
                        cluster_name: ext_auth
                    timeout: 30s
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.router
            typed_config: {}
          use_remote_address: true
  clusters:
  - name: ext_auth
    connect_timeout: 2s
    type: static
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 9000 }}]
    common_http_protocol_options: { idle_timeout: 60s }
    circuit_breakers:
        thresholds:
            max_pending_requests: 1024
            max_connections: 16384
            max_requests: 16384
  - name: ip_service
    connect_timeout: 5s
    type: strict_dns
    http2_protocol_options: {}
    common_http_protocol_options: { idle_timeout: 60s }
    lb_policy: round_robin
    max_requests_per_connection: 500
    hosts: [{ socket_address: { address: "ip-service-sv.rmt.svc.cluster.local", port_value: 9090 }}]
    upstream_connection_options:
        tcp_keepalive:
            keepalive_probes: 2
            keepalive_time: 10
            keepalive_interval: 10
    circuit_breakers:
        thresholds:
            max_pending_requests: 1024
            max_connections: 2048
            max_requests: 2048
tracing:
  http:
    name: envoy.tracers.dynamic_ot
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig
      library: /usr/local/lib/libjaegertracing_plugin.so
      config:
        service_name: retail-gw
        sampler:
          type: const
          param: 1
        reporter:
          localAgentHostPort: 127.0.0.1:6831
        headers:
          jaegerDebugHeader: jaeger-debug-id
          jaegerBaggageHeader: jaeger-baggage
          traceBaggageHeaderPrefix: uberctx-
        baggage_restrictions:
          denyBaggageOnInitializationFailure: false
          hostPort: ""
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 8000 }
```
