### ISSUE TITLE
Aggregate cluster properties override those of the "child" clusters

### ISSUE THREAD

**Issue by dcarney-stripe** [envoyproxy/envoy#11431]
*Title*: *Aggregate cluster properties override those of the "child" clusters*

*Description*:
We’re using Envoy 1.13.0.1 with an aggregate cluster, and multiple “child” clusters.

Our aggregate cluster has a basic config, similar to the example given in the current docs [0].

```
name: aggregate_cluster
connect_timeout: 0.25s
lb_policy: CLUSTER_PROVIDED
cluster_type:
  name: envoy.clusters.aggregate
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
    clusters:
    - primary
    - secondary
    - tertiary
```

Each of our “child” clusters (`primary`, `secondary`, `tertiary` in this example) is configured to use HTTP/2, by specifying the following, as per the cluster configuration docs [1]:

```
"http2_protocol_options": {
  "stream_error_on_invalid_http_messaging": true
},
```

We’ve used this cluster configuration in many other Envoy applications to great effect, so we were surprised to find that when used as part of an aggregate cluster, the connections were all using HTTP/1.1!  We verified this by not only looking at access logs for the Envoy upstream, but also by looking at the metrics for:
- `envoy.cluster.upstream_cx_http1_total`
- `envoy.cluster.upstream_cx_http2_total`

It appears that some of the configuration properties on the aggregate cluster override those in the “child” clusters, even though the docs make no mention of this.  In this specific case, the child clusters were behaving as if the lack of `http2_protocol_options` on the aggregate cluster was overriding its own configuration.

We were able to add the `http2_protocol_options` configuration to the aggregate cluster, and see that our traffic did begin to use H/2.

In other words, we changed our aggregate cluster configuration to be:

```
name: aggregate_cluster
connect_timeout: 0.25s
lb_policy: CLUSTER_PROVIDED
http2_protocol_options: 
  stream_error_on_invalid_http_messaging: true
cluster_type:
  name: envoy.clusters.aggregate
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
    clusters:
    - primary
    - secondary
    - tertiary
```

Which caused our traffic to be sent via H/2 as expected.

We know empirically that not all of a cluster’s top-level configuration properties are being overridden by the aggregate cluster in this manner, since we see that our configurations for things like:
- `upstream_bind_config`
- `transport_socket`
- `health_checks`

are being used by the child clusters as expected.

This seems like a bug to us, since the aggregate cluster docs specifically mention that it is intended to be used “...for failover between clusters with different configuration”.

If this is not a bug and is in fact the intended behavior of the aggregate cluster, I think the docs should spell out which cluster configuration properties are overridden/inherited with those of the aggregate cluster.

*Relevant Links*:
[0] https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/aggregate_cluster#example
[1] https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/cluster.proto

Thanks!
