### ISSUE TITLE
Strange information in doc

### ISSUE THREAD

**Issue by hakuno** [envoyproxy/envoy#11445]
Hey all,

The doc has a section called [Is there a way to disable circuit breaking?](https://www.envoyproxy.io/docs/envoy/latest/faq/load_balancing/disable_circuit_breaking)

There explains it should be

```
circuit_breakers:
  thresholds:
    priority: HIGH
    max_connections: 1000000000
    max_pending_requests: 1000000000
    max_requests: 1000000000
    max_retries: 1000000000
```

But I have some questions:

- Why `HIGH` instead of `DEFAULT`? Since the router uses `DEFAULT` for default.

- The `thresholds` field expects a list. But it shows no list. Is there right?

Thanks in advance,
Seiji

**EDIT**

Pull Request https://github.com/envoyproxy/envoy/pull/11451
