### ISSUE TITLE
Fault injection: active faults not decremented properly after request finishes

### ISSUE THREAD

**Issue by AngelaNing97** [envoyproxy/envoy#11504]
Description:
When using fault injection filters with max_active_faults set, we noticed that we couldn’t inject delays after some iterations. The Admin stats showed that active_faults was larger than the specified max_active_faults, which would stop further fault injection. We expected active_faults to decrement when a request finishes, which was not observed.

Repro steps:
1. Configure a fault filter on the egress listener with max_active_faults specified. (In our case, we had multiple fault filters configured each matching a different upstream cluster)
2.  Mock egress traffic and close connection after each request. (we are curling over http/1.1)
3. Observe that active_faults does not decrement accordingly

Admin and Stats Output:
http.egress.fault.aborts_injected: 80
http.egress.fault.active_faults: 61
http.egress.fault.delays_injected: 37
http.egress.fault.faults_overflow: 28
http.egress.fault.response_rl_injected: 0
http.egress.downstream_rq_active: 0
http.egress.downstream_cx_active: 0

Config:
```
      {
              "name": "envoy.filters.http.fault",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.config.filter.http.fault.v2.HTTPFault",
               "delay": {
                "fixed_delay": "3s",
                "percentage": {
                 "numerator": 9000,
                 "denominator": "TEN_THOUSAND"
                }
               },
               "abort": {
                "http_status": 555,
                "percentage": {
                 "numerator": 5000,
                 "denominator": "TEN_THOUSAND"
                }
               },
               "upstream_cluster": "XXX",
               "max_active_faults": 50
              }
             }
```

**Comment by snowp** [comment]
Do you see this issue when only configuring a single fault filter? I'm not sure if the multiple fault filter situation is well tested so I my initial suspicion is that something odd is at play there.

**Comment by jzhn** [comment]
I can reproduce this issue with official envoy docker image 1.14.2.

Unlike original poster of the issue, I only have a single fault filter, and the `envoy_http_fault_active_faults` gauge is increased by 1 whenever a request is aborted by the fault filter.

 ```
http_filters:
    - name: envoy.filters.http.fault
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
        max_active_faults: 100
        abort:
            http_status: 503
            percentage:
                numerator: 25
                denominator: HUNDRED
        delay:
            fixed_delay: 1s
            percentage:
                numerator: 0
                denominator: HUNDRED
    - name: envoy.filters.http.router
```

With above, a clean new container will have 
```
# TYPE envoy_http_fault_active_faults gauge
envoy_http_fault_active_faults{envoy_http_conn_manager_prefix="ingress_http"} 0
```

When the first `fault filter abort` occurs, the gauge becomes
```
# TYPE envoy_http_fault_active_faults gauge
envoy_http_fault_active_faults{envoy_http_conn_manager_prefix="ingress_http"} 1
```

And it becomes 2 and so on when more aborts happen.

**Comment by tonya11en** [comment]
I actually just got done taking a look at this with some colleagues. It's trivial to reproduce. I added the following fault filter config:
```
          http_filters:
          - name: envoy.fault
            typed_config:
              "@type": "type.googleapis.com/envoy.config.filter.http.fault.v2.HTTPFault"
              max_active_faults: 100
              abort:
                header_abort: {}
                percentage:
                  numerator: 100
```

Then simply just curled through the Envoy with the following:
```
curl -i -H "x-envoy-fault-abort-request: 503" -H "x-envoy-fault-abort-request-percentage: 100" <envoy IP/port>
```

The `active_faults` stat never decrements. It appears the filter's `onDestroy()` function is being called before the active faults are incremented, so it does not perform a decrement. We fixed it with the following:
```
diff --git a/source/extensions/filters/http/fault/fault_filter.cc b/source/extensions/filters/http/fault/fault_filter.cc
index ad40112619e2..29c84c6b159a 100644
--- a/source/extensions/filters/http/fault/fault_filter.cc
+++ b/source/extensions/filters/http/fault/fault_filter.cc
@@ -431,9 +431,9 @@ void FaultFilter::postDelayInjection(const Http::RequestHeaderMap& request_heade
 void FaultFilter::abortWithStatus(Http::Code http_status_code,
                                   absl::optional<Grpc::Status::GrpcStatus> grpc_status) {
   decoder_callbacks_->streamInfo().setResponseFlag(StreamInfo::ResponseFlag::FaultInjected);
+  recordAbortsInjectedStats();
   decoder_callbacks_->sendLocalReply(http_status_code, "fault filter abort", nullptr, grpc_status,
                                      RcDetails::get().FaultAbort);
-  recordAbortsInjectedStats();
 }

 bool FaultFilter::matchesTargetUpstreamCluster() {
```

Someone will submit.a patch that has an integration test reproducing the issue today/tomorrow.
