### ISSUE TITLE
envoy  rate limit not work  when use_remote_address is true and have no x-forwarded-for  header

### ISSUE THREAD

**Issue by du2016** [envoyproxy/envoy#11515]
envoy config

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
              rate_limits:
              - actions:
                  - {generic_key: {"descriptor_value": "apis"}}
                stage: 0
          http_filters:
          - name: envoy.rate_limit
            config:
              stage: 0
              domain: "ratelimiter"
              request_type: external
              failure_mode_deny: true
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: rate_limit_service
          - name: envoy.router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
  - name: rate_limit_service
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address:  127.0.0.1
        port_value: 8081
```

test as this,rate limit server not recive any request
```
curl http://127.0.0.1:10000/index.html
```

test as this,rate limit server can recive request,and rate limit working right

```
curl  -H 'x-forwarded-for: 192.168.1.1' http://127.0.0.1:10000/index.html
```

why envoy ratelimit working with `use_remote_address` must have `x-forwarded-for` header
