### ISSUE TITLE
Getting permission denied on latest dev image for access logs

### ISSUE THREAD

**Issue by instigardo** [envoyproxy/envoy#11551]
```
- filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: envoy_egress
          upgrade_configs:
          - upgrade_type: "CONNECT"          
          access_log:
            name: envoy.file_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout

```
When the envoy-dev container is started it gives out following error, can someone help out here.
```
proxy_1        | [2020-06-11 06:29:12.117][6][critical][main] [source/server/server.cc:100] error initializing configuration '/etc/envoy/envoy.yaml': unable to open file '/dev/stdout': Permission denied
proxy_1        | [2020-06-11 06:29:12.130][6][info][main] [source/server/server.cc:685] exiting
proxy_1        | unable to open file '/dev/stdout': Permission denied
```

Image: envoyproxy/envoy-dev:92e608f066b017d664d8fa161cfc735f0c6b41e7

**Comment by dio** [comment]
This is related to the change introduced in #11323. I think you can either let the `envoy` user have access to `/dev/stdout` or set `ENVOY_UID=0` when running the container.

**Comment by instigardo** [comment]
Great! thanks @dio

**Comment by phlax** [comment]
@dio i can PR to fix this in the container/image, can you reopen this ticket, otherwise i can open a new ticket

**Comment by AkhilRaja** [comment]
I get this error when I deploy the container image to Google Cloud Run. Local container runs, but on cloud run it throws
`chown: changing ownership of '/dev/stdout': Operation not permitted`

Any leads on this please ?

**Comment by phlax** [comment]
@AkhilRaja which version of envoy are you using ?

**Comment by AkhilRaja** [comment]
@phlax I am running on envoy-dev:latest

**Comment by phlax** [comment]
strange - this issue should have been resolved in #15115

in the latest containers the code to `chown` if the user isnt root - if the user is root then it should be able to `chown`

**Comment by AkhilRaja** [comment]
Ive been breaking my head over this for a while now. It runs fine in my local docker build, but when I deploy the container to cloud run this happens. Is there a way I could connect with you and show you whats happening  ? 
@phlax  I would really appreciate that. Thanks again

**Comment by phlax** [comment]
you can ping me on the envoy slack channel if you wish - preferably tomorrow and earlier in the utc day

**Comment by pablote** [comment]
> Ive been breaking my head over this for a while now. It runs fine in my local docker build, but when I deploy the container to cloud run this happens. Is there a way I could connect with you and show you whats happening ?
> @phlax I would really appreciate that. Thanks again

I'm running into this same issue trying to run Envoy on Cloud Run. Did you got it working?

**Comment by paymog** [comment]
I'm also running into this issue on cloud build. I've tried version 1.16.0, 1.17.0 and 1.19.0 without success.

**Comment by percenuage** [comment]
For those who already have the issue with Cloud Run, I've found the origin : Docker Entrypoint. You can check the file -> [docker-entrypoint.sh](https://github.com/envoyproxy/envoy/blob/main/ci/docker-entrypoint.sh). 
I just override the entrypoint like that :
```Dockerfile
FROM envoyproxy/envoy-alpine:v1.21.0

COPY envoy/envoy.yaml /etc/envoy/envoy.yaml
COPY envoy/entrypoint.sh .

ENTRYPOINT ["/entrypoint.sh"]

CMD ["envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "trace"]
```
(I'm using my own entrypoint for another use)

**Comment by hamza-maqsood** [comment]
has anybody fixed this issue?

**Comment by phlax** [comment]
the best solution i think is to use the distroless image - which is permissionless anyway

the solutions posted above are not really solutions imho - they are just disabling the dropping of permissions - which is not in most cases desirable i think

**Comment by pablocompagni-contractorvp** [comment]
Setting ENVOY_UID as an env var as suggested previously worked for me

<img width="677" alt="image" src="https://user-images.githubusercontent.com/82176706/160833297-14bcd071-8f1a-47ff-a77b-30685075ca2f.png">

**Comment by phlax** [comment]
> Setting ENVOY_UID as an env var as suggested previously worked for me

setting it to `0` is also the equivalent of saying - run as root (ie the same as overriding the entrypoint and preventing permissions being dropped)

this is probably not going to make the container that much less secure - but its not generally a good idea for production

a much better solution is to use the distroless image (note: alpine image has been deprecated for some time and is no longer supported)

**Comment by hamza-maqsood** [comment]
I tried using the distroless image now

here's my dockerfile
FROM envoyproxy/envoy-distroless:v1.20-latest
COPY envoy-stag.yml /etc/envoy/envoy.yml
RUN apk --no-cache add ca-certificates
ENTRYPOINT /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace

but when I run it through github actions and try deploying to google run, I get the following error:
OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

**Comment by phlax** [comment]
it also doesnt have apk - so that recipe wont work

i think you will need a multi-stage recipe and to use `COPY --from` to get the certs

see here https://stackoverflow.com/questions/52636213/docker-distroless-image-how-to-add-customize-certificate-to-trust-store for discussion

**Comment by fordneild** [comment]
My issue was that I needed to start the container as root, as well as run the envoy process as root. This involved adding
```yml
  envoy:
    container_name: envoy
...
    environment:
      - ENVOY_UID=0
      - ENVOY_GID=0
    user: root
```
