### ISSUE TITLE
Support tunneling TCP over HTTP/2 behind HTTP proxy

### ISSUE THREAD

**Issue by irozzo-1A** [envoyproxy/envoy#11569]
Description:

#1451 enables the usage of envoy to tunnel raw TCP over HTTP/2. I would like to use this feature in a scenario in which the tunnel should pass through an HTTP proxy (supporting HTTP/1.x CONNECT). This would mean that I would need "double tunneling", something like:

```
client--[raw TCP]-->L2 Envoy--[TCP tunneled over HTTP/2 tunneled over HTTP/1.1]-->HTTP Proxy-->[TCP tunneled over HTTP/2]-->L1 Envoy--[raw TCP]-->server
```

I know HTTP/1.x connect are not supported yet (i.e. #11308), but I would like to have an early feedback about the possibility of supporting this.

**Comment by mattklein123** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
Why would you need double tunneling?   Could you simply have the middle proxy forward the connect on untouched?  Envoy at least supports incoming CONNECT being sent as outbound CONNECT, at which point you could just encapsulate your TCP in a CONNECT request at the front proxy, forward it through the middle one, and terminate the CONNECT at the last one in line.

**Comment by irozzo-1A** [comment]
Thx @alyssawilk for your reply. This setup would be needed in environments where we don't have the hands on the middle HTTP proxy, that could be anything e.g. Squid, Bluecoat proxies, Fortigates, etc. The advantage is that it would be transparent to the middle HTTP proxy and wouldn't require any specific configuration on it.
I agree that having full control on the environment would make it easier.

**Comment by lambdai** [comment]
I am adding pluggable backend to tcp proxy, so potentially you could have additional control on terminating raw TCP at L2 Envoy.

I feel the double tunnel is extremely complex. I see your point but it's likely be supported by your own extension using the pluggable framework.

My PR on the pluggable tcp proxy backend will be create today. Now I am examples how it could be used and the compatibility with the current tcp proxy.

**Comment by irozzo-1A** [comment]
Thx @lambdai for your reply! I will take a look to the TCP pluggable backend.

In the meantime I was thinking about a possible workaround (probably less clean than the option you proposed). The idea is to use two stages and a Unix domain socket between them.
* First stage is composed by a listener binding to a TCP socket with a TCP proxy filter taking care of the inner tunnel addressed to the L1 Envoy with a UDS upstream.
* Second stage is listening to the UDS and is also using a TCP proxy filter to take care of the outer tunnel terminated by the middle HTTP proxy.

Configuration of the L2 Envoy should look like the snippet below (apart that HTTP/1.x CONNECT should be used in he second stage).  WDYT?

```yaml
static_resources:
listeners:
- name: stage_one_listener
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 8443
  filter_chains:
  - filters:
    - name: tcp
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        stat_prefix: tcp_stats
        cluster: "uds_cluster"
        tunneling_config:
          hostname: dest-server.example.com
- name: stage_two_listener
  address:
    pipe:
      path: "/tmp/envoy.sock"
  filter_chains:
  - filters:
    - name: tcp
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        stat_prefix: tcp_stats
        cluster: "l2_envoy_cluster"
        tunneling_config:
          hostname: l2-envoy.example.com
clusters:
  - name: uds_cluster
    type: STATIC
    connect_timeout: 5s
    http2_protocol_options:
      {}
    load_assignment:
      cluster_name: uds_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: "/var/run/envoy.sock"
  - name: l2_envoy_cluster
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    http2_protocol_options:
      {}
    load_assignment:
      cluster_name: l2_envoy_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: http-proxy.foo
                    port_value: 8443
```
