### ISSUE TITLE
Unable to connect TLS with envoy

### ISSUE THREAD

**Issue by kumaranshu72** [envoyproxy/envoy#11582]
I have a GRPC Web client and a GRPC Server and I am using envoy proxy from the conversion of HTTP 1.1 to HTTP2.

My server creation Logic uses TLS. The code is as follows:

```go
    var opts []grpc.ServerOption
    creds, err := credentials.NewServerTLSFromFile("cert/server.crt", "cert/server.key")
    if err != nil {
        log.Fatalf("Failed to generate credentials %v", err)
    }
    opts = []grpc.ServerOption{grpc.Creds(creds)}
    server := grpc.NewServer(opts...)
```

I am calling the From my react client as follows:

```js
const client = new LiveClient('http://localhost:8080')
const request = new GetLiveRequest()
request.setApi(1)
request.setTrackkey(trackKey)

// on success response
const stream = client.getLive(request, {})
stream.on('data', response => {
  console.log(response);
}
```

The envoy.yaml is as follows:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: greeter_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
      tls_context:
        common_tls_context:
          alpn_protocols: "h2"
          tls_certificates:
            - certificate_chain:
                filename: "/etc/server.crt"
              private_key:
                filename: "/etc/server.key"
  clusters:
  - name: greeter_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: app, port_value: 3000 }}]
```
The Dockerfile for envoy is as follows:

```Dockerfile
FROM envoyproxy/envoy:36f39c746eb7d03b762099b206403935b11972d8
COPY ./envoy.yaml /etc/envoy/envoy.yaml

ADD ./cert/server.crt /etc/server.crt
ADD ./cert/server.key /etc/server.key
ADD ./cert/server.csr /etc/server.csr

WORKDIR /etc/envoy
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
I am getting the following error when:

`{code: 2, message: "Http response at 400 or 500 level"}`
But when I remove the SSL authentication from backend server. It is working fine. I have also created a grpc client and TLS is working fine with it. I am unable to find what is going wrong in my envoy configuration for TLS.

On further investigation in am getting following in envoy logs. `TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`

The TLS certificates are working fine if I use it with envoy by directly using a GRPC client.

**Comment by htuch** [comment]
You probably want to set an upstream TLS context if your server is using TLS.

**Comment by kumaranshu72** [comment]
@htuch can you help in setting an upstream TLS context?

**Comment by dio** [comment]
@kumaranshu72 Could you provide the envoy version? 

Looking at your config it seems like it is `<= v1.12.1`. (since it still uses the deprecated `tls_context`)

To add upstream TLS context, you can refer to this doc: https://www.envoyproxy.io/docs/envoy/v1.12.1/api-v2/api/v2/cds.proto.html#envoy-api-field-cluster-tls-context.

```
  clusters:
  - name: greeter_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: app, port_value: 3000 }}]
    tls_context: {}
```

You can add more options to `tls_context` as defined in here: https://www.envoyproxy.io/docs/envoy/v1.12.1/api-v2/api/v2/auth/cert.proto#envoy-api-msg-auth-upstreamtlscontext

As a note, `tls_context` is deprecated, please use `transport_socket` instead.

For v2,

```
https://github.com/envoyproxy/envoy/blob/5139aef7e699ee7fe0afe029604c689711ed177a/configs/google_com_proxy.v2.yaml#L51-L55
```

And for v3: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto.html#extensions-transport-sockets-tls-v3-upstreamtlscontext.

Good luck! 🙂

**Comment by reliveyy** [comment]
Hi, there

I'm new to envoy. I noticed that there are two `tls_context` sections in envoy.yaml.

The first one (in **listeners**):

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 9090 }
    filter_chains:
      - name: envoy.http_connection_manager
        # ...
            tls_context:
        common_tls_context:
          alpn_protocols: "h2"
          tls_certificates:
            - certificate_chain: { filename: "/root/.xud/tls.cert" }
              private_key: { filename: "/root/.xud/tls.key" }
```

The second one (in **clusters**):

```yaml
static_resources:
  listeners:
  # ...
  clusters:
  - name: xud_service
    # ...
    hosts: [{ socket_address: { address: xud, port_value: 28885 }}]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        # "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
            - certificate_chain: { filename: "/root/.xud/tls.cert" }
              private_key: { filename: "/root/.xud/tls.key" }
```

**Question 1**

Does these two `tls_context`s act like the the graph drawn below?

```
outer <------------> envoy <-------------------> backend service
        listeners            clusters
        tls_context          transport_socket
                             UpstreamTlsContext
```

**Question 2**
I configured transport_socket for clusters (no tls_context in listeners) but I got the error in grpc-web client

```
{code: 14, message: "upstream connect error or disconnect/reset before headers. reset reason: connection failure", metadata: {…}}
```

There is TLS handshake error inside envoy in the meanwhile

```
[2020-06-29 19:20:22.118][23][debug][pool] [source/common/http/conn_pool_base.cc:265] [C1] client disconnected, failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

When I configured tls_context in listeners I got the error in grpc-web client

```
{code: 2, message: "Http response at 400 or 500 level"}
```

There is TLS handshake error inside envoy too

```
[2020-06-29 00:37:00.250][19][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:226] [C0] TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST
```
