### ISSUE TITLE
Envoy occasional 504s but the upstream response 200

### ISSUE THREAD

**Issue by columbus9963** [envoyproxy/envoy#11587]
## Description
I'm using envoy 1.10.0 as my front edge and nginx as the backend, h2 downstream and http1.1 upstream. I notice that the 504 requests appear batchly over weeks while the nginx upstream response 200. using elk for access log collecting.
* a sample access log with same request id
![image](https://user-images.githubusercontent.com/57693768/84609807-f38e7000-aeea-11ea-90f5-4d4561a6c783.png)
* envoy trace log
![image](https://user-images.githubusercontent.com/57693768/84611606-f42a0500-aef0-11ea-8f30-4f7cbdf1aba3.png)
![image](https://user-images.githubusercontent.com/57693768/84611695-2e93a200-aef1-11ea-99fa-810b699f1eef.png)
![image](https://user-images.githubusercontent.com/57693768/84611724-3e12eb00-aef1-11ea-8716-58b792008aac.png)
* from the envoy trace log, the upstream nginx response header was recieved, read error raised so that envoy not fetch the request boby? Is that related to the 504 UT response for downstream clients?
* `Readdisable` was also appeared in the error connection trace log, is this related to [issue 6190](https://github.com/envoyproxy/envoy/issues/6190)?
![image](https://user-images.githubusercontent.com/57693768/84612482-597ef580-aef3-11ea-9ca9-029716860aa7.png)
* envoy config
```
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: "envoy.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filter_chain_match: {}
      tls_context:
        common_tls_context:
          alpn_protocols: ["h2,http/1.1"]
          tls_params: {}
          tls_certificates:
            - certificate_chain:
                filename: "/etc/ssl/cert_file.crt"
              private_key:
                filename: "/etc/ssl/cert_file.key"
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_https
          access_log:
          - config:
                format: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%-_-%REQ(remote_user?remote_user):20%-_-%START_TIME%-_-%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%-_-%RESPONSE_CODE%-_-%BYTES_SENT%-_-%REQ(REFERER?:AUTHORITY)%-_-%REQ(USER-AGENT)%-_-%REQ(X-FORWARDED-FOR)%-_-%UPSTREAM_HOST%-_-%RESPONSE_CODE%-_-%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%-_-%DURATION%-_-%RESPONSE_FLAGS%-_-%REQ(X-REQUEST-ID)%\n"
                path: /var/log/envoy/envoy-access.log
            name: envoy.file_access_log
          codec_type: AUTO
          http2_protocol_options: { allow_connect: True }
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                    prefix: "/"
                route:
                    cluster: cluster_nginx
                    timeout: 120s
                    retry_policy:
                        retry_on: 5xx
                        num_retries: 3
          http_filters:
          - name: envoy.router
  clusters:
  - name: cluster_nginx
    connect_timeout: 120s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 192.168.1.206
        port_value: 80
```
* upstream nginx config
```
user www-data;
worker_processes 4;
pid /run/nginx.pid;
worker_rlimit_nofile 102400;

events {
        use epoll;
        worker_connections  204800;
        multi_accept on;
}

http {
        tcp_nopush                      on;
        tcp_nodelay             on;

        types_hash_max_size 2048;
        charset                         utf-8;
            sendfile                    on;
            client_header_buffer_size   64k;
            large_client_header_buffers 4 128k;
            client_body_buffer_size     256m;
            client_body_temp_path               /tmp;
            client_max_body_size                50m;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

                log_format main '$remote_addr-_-$remote_user-_-$time_local-_-$request-_-$status-_-$body_bytes_sent-_-'
                                '$http_referer-_-$http_user_agent-_-$http_x_forwarded_for-_-$upstream_addr-_-$upstream_status-_-'
                                '$upstream_response_time-_-$request_time-_-$nameInCookie';

        gzip on;
        gzip_disable "msie6";

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        keepalive_timeout  60s;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```
@alyssawilk @mattklein123 @lizan @JonathanO 
Any thoughts?
