### ISSUE TITLE
Traffic forwarded to unhealthy hosts

### ISSUE THREAD

**Issue by prakhag-1** [envoyproxy/envoy#11673]
My setup (config below) uses multiple endpoints in a cluster. When health check for hosts in one of the endpoints fail, I see that the traffic is still forwarded to its underlying hosts.

Config:
```
route:
     cluster: backend-service
      retry_policy:
           retry_on: 5xx
            num_retries: 2
            per_try_timeout: 5s
            retry_host_predicate:
             - name: envoy.retry_host_predicates.omit_host_metadata
                 typed_config:
                     "@type": type.googleapis.com/envoy.config.retry.omit_host_metadata.v2.OmitHostMetadataConfig
                     metadata_match:
                           filter_metadata:
                               "envoy.lb":
                                     "type" : "pvm"
clusters:
 - name: backend-service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
        cluster_name: backend-service
         endpoints:
          - lb_endpoints:
             - endpoint:
                   address:
                       socket_address:
                           address: web-pvm
                           port_value: 8080
                    metadata:
                         filter_metadata:
                            "envoy.lb":
                            "type": "pvm"
          - lb_endpoints:
             - endpoint:
                    address:
                       socket_address:
                           address: web-std
                           port_value: 8080
   health_checks:
    - timeout: 1s
       interval: 2s
       interval_jitter: 10s
       unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check:
         path: "/health"
```

Logs from application:

[web-pvm-59fb685cfc-98rxt] Health status: **pass** at: 2020-06-20 05:27:47.445
[web-pvm-59fb685cfc-4pk69] Health status: **pass** at: 2020-06-20 05:27:48.682
[web-std-79688dd94d-ls5vw] Health status: **pass** at: 2020-06-20 05:27:48.731
[web-pvm-59fb685cfc-t4gc7] Health status: **pass** at: 2020-06-20 05:27:49.304
...
<All underlying hosts get requests based on lb policy>
...
[web-pvm-59fb685cfc-t4gc7] Health status: **false** at: 2020-06-20 05:28:11.302
[web-pvm-59fb685cfc-t4gc7] Received request at: 2020-06-20 05:28:14.275
[web-pvm-59fb685cfc-t4gc7] Received request at: 2020-06-20 05:28:14.309
...
[web-pvm-59fb685cfc-4pk69] Health status: **false** at: 2020-06-20 05:28:08.776
[web-pvm-59fb685cfc-4pk69] Received request at: 2020-06-20 05:28:08.825
[web-pvm-59fb685cfc-4pk69] Received request at: 2020-06-20 05:28:08.834
...
[web-std-79688dd94d-ls5vw] Health status: **true** at: 2020-06-20 05:28:16.729
[web-std-79688dd94d-ls5vw] Received request at: 2020-06-20 05:28:16.781
[web-std-79688dd94d-ls5vw] Received request at: 2020-06-20 05:28:16.789
...
