### ISSUE TITLE
Generate 504 status when max_stream_duration is reached by no response headers is sent

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#11706]
Hi, I came across that when [max_stream_duration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-max-stream-duration) is reached, upstream client doesn't get any HTTP status.

While when route [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-timeout) is reached, a 504 status is generated.

Could we generate the similar status for max_stream_duration when response header is never sent?

**Comment by Shikugawa** [comment]
@wlhee It is curious. Would you mind to tell me detail situations? It should return 408 status when upstream max_stream_duration is reached.

**Comment by wlhee** [comment]
Sure.

I configured the max_stream_duration in the listener config:

    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          stream_idle_timeout: 0s
          common_http_protocol_options:
            max_stream_duration: 3s

I have a simple setup like:

curl -> H1 -> Envoy (port 8081) -> H1 -> upstream (port 8080)

The upstream has a simple sleep handler, so I did:
curl -i --raw localhost:8081/sleep?duration=20s
curl: (52) Empty reply from server

**Comment by Shikugawa** [comment]
@wlhee This is resolved by https://github.com/envoyproxy/envoy/pull/12228.

**Comment by wlhee** [comment]
Thanks, I confirmed with the new change. Is "downstream duration timeout" an expected timeout? It looks like it's "upstream" instead?

curl -i localhost:8081/sleep?duration=10s

HTTP/1.1 408 Request Timeout
content-length: 27
content-type: text/plain
date: Tue, 18 Aug 2020 23:42:40 GMT
server: envoy
downstream duration timeout

**Comment by Shikugawa** [comment]
> Thanks, I confirmed with the new change. Is "downstream duration timeout" an expected timeout? It looks like it's "upstream" instead?
> 
> curl -i localhost:8081/sleep?duration=10s
> 
> HTTP/1.1 408 Request Timeout
> content-length: 27
> content-type: text/plain
> date: Tue, 18 Aug 2020 23:42:40 GMT
> server: envoy
> downstream duration timeout

It seems that your `max_stream_duration` is configured as downstream protocol options. If you'd like to attach this on upstream connection, you should configure like,

```
clusters:
  - name: upstream
     connect_timeout: 0.250s
     type: static
     http_protocol_options:
       max_stream_duration: 3s
     load_assignment:
       cluster_name: upstream_cluster
       endpoints:
         lb_endpoints:
           - endpoint:
                address:
                  socket_address:
                    address: 
                      port_value: 50001
```
