### ISSUE TITLE
ext_authz: unable to configure balacing within grpc cluster

### ISSUE THREAD

**Issue by TuvaevAndrey** [envoyproxy/envoy#11821]
_Description_:
I'm using envoy:v1.12.3 with [ext_authz](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#config-http-filters-ext-authzhttps://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#config-http-filters-ext-authz) filter. I want to configure load balancing subsets within my grpc cluster. In accordance with doc I configured my cluster with subset selector and marked my endpoint nodes with additional meta.

Cluster config:
```yaml
     "cluster": {
      "name": "ext_authz_grpc",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {}
       }
      },
      "lb_subset_config": {
       "fallback_policy": "DEFAULT_SUBSET",
       "default_subset": {
        "subset": "default"
       },
       "subset_selectors": [
        {
         "keys": [
          "subset"
         ]
        }
       ]
      }
    }
```
Endpoints:

```yaml
cluster_name: "ext_authz_grpc"
endpoints {
  lb_endpoints {
    endpoint {
      address {
        socket_address {
          address: "10.42.109.114"
          port_value: 8889
        }
      }
    }
    metadata {
      filter_metadata {
        key: "envoy.lb"
        value {
          fields {
            key: "subset"
            value {
              string_value: "default"
            }
          }
        }
      }
    }
  }
  lb_endpoints {
    endpoint {
      address {
        socket_address {
          address: "10.42.101.47"
          port_value: 8889
        }
      }
    }
    metadata {
      filter_metadata {
        key: "envoy.lb"
        value {
          fields {
            key: "subset"
            value {
              string_value: "custom_subset"
            }
          }
        }
      }
    }
  }
}
```

All I need is to add "subset" key to meta and provide correct value("custom_subset") during my http request. 
I used another envoy http filter "envoy.filters.http.header_to_metadata".

My filter chain:
```yaml
filter_chains:
          - filters:
              - name: envoy.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                  add_user_agent: true
                  generate_request_id: true
                  tracing:
                    operation_name: INGRESS
                    request_headers_for_tags: 
                      - X-Real-IP
                    - name: envoy.filters.http.header_to_metadata
                      typed_config:
                        "@type": type.googleapis.com/envoy.config.filter.http.header_to_metadata.v2.Config
                        request_rules:
                          - header: subset
                            on_header_present:
                              metadata_namespace: envoy.lb
                              key: subset
                              type: STRING
                    - name: envoy.ext_authz
                      typed_config:
                        "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
                        grpc_service:
                          timeout: 1s
                          envoy_grpc:
                            cluster_name: ext_authz_grpc
                        metadata_context_namespaces:
                        - envoy.lb
                        status_on_error:
                          code: GatewayTimeout
                    - name: envoy.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.config.filter.http.router.v2.Router
                        start_child_span: true
```
But after passing header "subset":"custom_subset" envoy still routes me to default subset, ignoring host with predefined meta. I suppose that ext_authz doesn't receive my meta information from metaspace _envoy.lb_.
I also tried to pass meta within _envoy.lua_ filter. But the result was the same.
```yaml
request_handle:streamInfo():dynamicMetadata():set("envoy.lb", "subset", "custom_subset")
````
It is worth mentioning that I already tested loadbalancing subsets with http clusters and it was fine.
