### ISSUE TITLE
Envoy cors OPTIONS call 404

### ISSUE THREAD

**Issue by JacobSMoller** [envoyproxy/envoy#11881]
Description: 
Using the envoy.cors http filter i get 404 when doing options calls. I have read https://github.com/envoyproxy/envoy/issues/6608 and https://github.com/envoyproxy/envoy/issues/7833

My config is a bit different to theirs, but as far I read their solutions i have fixed what they had problems with.(eg. having the cors filter as the first filter and removing the grpc: {} from my routes.

My config looks as follows. 

```yaml
apiVersion: v1
data:
  config.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 443
        listener_filters:
        - name: "envoy.listener.tls_inspector"
          typed_config: {}
        filter_chains:
        - filter_chain_match: {}
          tls_context:
            common_tls_context:
              alpn_protocols: h2
              tls_certificates:
              - certificate_chain:
                  filename: "/etc/cert-self-signed/tls.crt"
                private_key:
                  filename: "/etc/cert-self-signed/tls.key"
          filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  json_format:
                    protocol: "%PROTOCOL%"
                    duration: "%DURATION%"
                    request_method: "%REQ(:METHOD)%"
                    request_authority: "%REQ(:AUTHORITY)%"
                    request_path: "%REQ(PATH)%"
                    request_scheme: "%REQ(:SCHEME)%"
                    request_id: "%REQ(X-REQUEST-ID)%"
                    request_auth: "%REQ(AUTHORIZATION):15%"
                    request_contenttype: "%REQ(CONTENT-TYPE)%"
                    user: "%REQ(VML-USERNAME)%"
                    route: "%ROUTE_NAME%"
                    cloud_trace: "%REQ(X-CLOUD-TRACE-CONTEXT)%"
                    start_time: "%START_TIME%"
                    protocol: "%PROTOCOL%"
                    bytes_send: "%BYTES_SENT%"
                    response_code: "%RESPONSE_CODE%"
                    response_code_details: "%RESPONSE_CODE_DETAILS%"
                    response_duration: "%RESPONSE_DURATION%"
                    response_flags: "%RESPONSE_FLAGS%"
                    response_tx_duration : "%RESPONSE_TX_DURATION%"
                    grpc_status: "%TRAILER(GRPC-MESSAGE?GRPC-STATUS)%"
                    upstream_host: "%UPSTREAM_HOST%"
                    upstream_cluster: "%UPSTREAM_CLUSTER%"
                    upstream_local_adress: "%UPSTREAM_LOCAL_ADDRESS%"
                    upstream_transport_failure_reason: "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
                    downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                    downstream_remote_address_without_port: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                    downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
                    downstream_local_address_without_port: "%DOWNSTREAM_LOCAL_ADDRESS_WITHOUT_PORT%"
                  path: "/dev/stdout"
              use_remote_address: true
              xff_num_trusted_hops: 2
              codec_type: auto
              stat_prefix: ingress_http
              rds:
                route_config_name: local_route
                config_source:
                  path: /etc/envoy/rds.yaml
              http_filters:
              - name: envoy.cors
              - name: envoy.grpc_web
              - name: envoy.buffer
                config:
                  max_request_bytes: 10485760
              - name: envoy.grpc_json_transcoder
                config:
                  proto_descriptor: "/etc/grpc/descriptor.bin"
                  services:
                    - "asgt.jester.v1.Jester"
                    - "asgt.dataservice.v1.DataService"
                  print_options:
                    always_print_primitive_fields: false
                    always_print_enums_as_ints: false
                    preserve_proto_field_names: false
              - name: envoy.ext_authz
                config:
                  grpc_service:
                    envoy_grpc:
                      cluster_name: ext-authz
                    timeout: 2s
                  failure_mode_allow: false
                  status_on_error:
                    code: 503
              - name: envoy.rate_limit
                config:
                  domain: asgt
                  timeout: 0.1s
                  rate_limited_as_resource_exhausted: true
                  rate_limit_service:
                    grpc_service:
                      envoy_grpc:
                        cluster_name: rate-limit
              - name: envoy.router
                config: {}
      clusters:
      - name: xds-grpc
        connect_timeout: 10s
        type: strict_dns
        hosts:
        - socket_address:
            address: istio-pilot.istio-system.svc.cluster.local
            port_value: 15010
        circuit_breakers:
          thresholds:
            - max_connections: 100000
              max_pending_requests: 100000
              max_requests: 100000
            - priority: HIGH
              max_connections: 100000
              max_pending_requests: 100000
              max_requests: 100000
        http2_protocol_options: {}
        dns_refresh_rate: 300s
        dns_lookup_family: V4_ONLY
        upstream_connection_options:
          tcp_keepalive:
            keepalive_time: 300
      - name: zipkin
        connect_timeout: 1s
        type: strict_dns
        hosts:
        - socket_address:
            address: zipkin.istio-system.svc.cluster.local
            port_value: 9411
        dns_refresh_rate: 300s
        dns_lookup_family: V4_ONLY
      - name: rate-limit
        connect_timeout: 0.25s
        lb_policy: round_robin
        http2_protocol_options: {}
        type: EDS
        eds_cluster_config:
          eds_config:
            ads: {}
          service_name: "outbound|50051||envoy-services.ssn.svc.cluster.local"
      - name: ext-authz
        connect_timeout: 0.25s
        lb_policy: round_robin
        http2_protocol_options: {}
        type: EDS
        eds_cluster_config:
          eds_config:
            ads: {}
          service_name: "outbound|50051||envoy-services.ssn.svc.cluster.local"

    dynamic_resources:
      cds_config:
        ads: {}
      ads_config:
        api_type: GRPC
        grpc_services:
        - envoy_grpc:
            cluster_name: xds-grpc

    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: zipkin
          collector_endpoint: "/api/v1/spans"
          collector_endpoint_version: "HTTP_JSON"
          shared_span_context: false
          trace_id_128bit: true

    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
  rds.yaml: |
    version_info: "0"
    resources:
    - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      name: local_route
      virtual_hosts:
      - name: health
        domains:
        - "10.*"
        routes:
        - match:
            path: "/healthz/ready"
          direct_response:
            status: 200
            body:
              inline_string: "ready..."
        - match:
            path: "/"
          direct_response:
            status: 200
            body:
              inline_string: "ready..."
      - name: api
        domains:
        - "*"
        retry_policy:
          retry_on: "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,reset,gateway-error"
          host_selection_retry_max_attempts: 8
          retry_host_predicate:
          - name: "envoy.retry_host_predicates.previous_hosts"
          num_retries: 8
        cors:
          allowOrigin:
            - "*"
          allowMethods: POST,GET,OPTIONS,PUT,DELETE
          allowHeaders: authorization,grpc-timeout,content-type,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
          maxAge: 1728s
          exposeHeaders: authorization,custom-header-1,grpc-status,grpc-message
          allowCredentials: true
        routes:
        - match:
            prefix: "/"
            headers:
              - name: ":scheme"
                exact_match: "http"
          redirect:
            scheme_redirect: https
        - match:
            prefix: "/asgt.dataservice"
          route:
            cluster: "outbound|50051||meta-data.asgt.svc.cluster.local"
        - match:
            prefix: "/"
          direct_response:
            status: 404
            body:
              inline_string: |
                not found
kind: ConfigMap
metadata:
  name: envoy-edgeproxy
  namespace: asgt
  annotations:
    moniker.spinnaker.io/application: envoy-edgeproxy
  labels:
    app: envoy-edgeproxy
```

Doing a regular GET request to for example.

https://foor.bar/v1/bank/test:info works as expected but doing an OPTIONS call results in a 404 response. 
Debug log for the GET call looks
```
[envoy-edgeproxy-5ff54c956b-424pq] ':method', 'GET' 
[envoy-edgeproxy-5ff54c956b-424pq] ':scheme', 'https' 
[envoy-edgeproxy-5ff54c956b-424pq] ':authority', 'foo.bar' 
[envoy-edgeproxy-5ff54c956b-424pq] ':path', '/v1/bank/test:info' 
[envoy-edgeproxy-5ff54c956b-424pq] 'user-agent', 'python-requests/2.19.1' 
[envoy-edgeproxy-5ff54c956b-424pq] 'accept-encoding', 'gzip, deflate' 
[envoy-edgeproxy-5ff54c956b-424pq] 'accept', '*/*' 
[envoy-edgeproxy-5ff54c956b-424pq] 'authorization', 'Bearer ***' 
[envoy-edgeproxy-5ff54c956b-424pq] 'x-cloud-trace-context', 'a08579b45bde503cc2cf9e5d78e732d2/1163129912725668252' 
[envoy-edgeproxy-5ff54c956b-424pq] 'via', '1.1 google' 
[envoy-edgeproxy-5ff54c956b-424pq] 'x-forwarded-for', 'ip0, ip1' 
[envoy-edgeproxy-5ff54c956b-424pq] 'x-forwarded-proto', 'https' 
```

And then more logging as it goes through ext.authz service and finally is send to the GRPC backend on 
```
[envoy-edgeproxy-5ff54c956b-424pq] ':path', '/asgt.dataservice.v1.DataService/GetInfo' 
```
for an OPTIONS call through curl looking like this:
```curl
curl -i -XOPTIONS \
  -H'Access-Control-Request-Method: GET' \
  -H'Access-Control-Request-Headers: authorization, content-type' \
  -H'Origin: https://localhost:123' \
  -H'Authorization: Bearer TdxwCcBdpDuuzm43M3qHHB58Qff2DtgP' \
https://api.snbx.asgt.visma.ai/v1/bank/3573c37a77bb4472a4830cdf6455878a-test:info
```

The debug logs looks as follows
```
[envoy-edgeproxy-5ff54c956b-424pq] ':method', 'OPTIONS'
[envoy-edgeproxy-5ff54c956b-424pq] ':scheme', 'https'
[envoy-edgeproxy-5ff54c956b-424pq] ':authority', 'foo.bar'
[envoy-edgeproxy-5ff54c956b-424pq] ':path', '/v1/bank/test:info'
[envoy-edgeproxy-5ff54c956b-424pq] 'user-agent', 'curl/7.64.1'
[envoy-edgeproxy-5ff54c956b-424pq] 'accept', '*/*'
[envoy-edgeproxy-5ff54c956b-424pq] 'access-control-request-method', 'GET'
[envoy-edgeproxy-5ff54c956b-424pq] 'access-control-request-headers', 'authorization, content-type'
[envoy-edgeproxy-5ff54c956b-424pq] 'origin', 'https://localhost:123'
[envoy-edgeproxy-5ff54c956b-424pq] 'x-cloud-trace-context', 'a8060358fa9db05d479794a91c751c2a/15248226103828336334'
[envoy-edgeproxy-5ff54c956b-424pq] 'via', '1.1 google'
[envoy-edgeproxy-5ff54c956b-424pq] 'x-forwarded-for', 'ip0, ip1'
[envoy-edgeproxy-5ff54c956b-424pq] 'x-forwarded-proto', 'https'
[envoy-edgeproxy-5ff54c956b-424pq] 

[envoy-edgeproxy-5ff54c956b-424pq] ':status', '404'
[envoy-edgeproxy-5ff54c956b-424pq] 'content-length', '385'
[envoy-edgeproxy-5ff54c956b-424pq] 'content-type', 'text/plain'
[envoy-edgeproxy-5ff54c956b-424pq] 'date', 'Fri, 03 Jul 2020 11:00:49 GMT'
[envoy-edgeproxy-5ff54c956b-424pq] 'server', 'envoy'
[envoy-edgeproxy-5ff54c956b-424pq]
```

**Comment by yuval-k** [comment]
I believe allowOrigin is deprecated in v3;
try this instead:
```
allow_origin_string_match:
- safe_regex:
    google_re2: {}
    regex: .*
```
(didn't test this, but should work according to https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-corspolicy)

**Comment by lizan** [comment]
It seems the request matched your last route entry:
```
        - match:
            prefix: "/"
          direct_response:
            status: 404
            body:
              inline_string: |
                not found
```

It is possible that the request didn't match your proto descriptor for transcoding. What's your proto definition?
