### ISSUE TITLE
[question & help] Mysql network decoding seems to be incomplete?

### ISSUE THREAD

**Issue by zonghaishang** [envoyproxy/envoy#11880]
Title:  Mysql network decoding seems to be incomplete?

Description:

When I read envoy decoding mysql protocol, it seems to only support the latest version of mysql, taking the Handshake message as an example：

Official documents need to support HandshakeV10 and HandshakeV9 versions：
https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse

At present, the envoy source code only parses the Handshake V10 version of the message，and the following protocol part is not parsed (`Protocol::HandshakeResponse320` also does not seem to be decoded):

```
Protocol::HandshakeV10
Initial Handshake Packet - protocol version 10

Payload
....
string[10]     reserved (all [00])
  if capabilities & CLIENT_SECURE_CONNECTION {
string[$len]   auth-plugin-data-part-2 ($len=MAX(13, length of auth-plugin-data - 8))
  if capabilities & CLIENT_PLUGIN_AUTH {
string[NUL]    auth-plugin name
  }
```
decode Handshake V10 source code: 
https://github.com/envoyproxy/envoy/blob/093e2ffe046313242144d0431f1bb5cf18d82544/source/extensions/filters/network/mysql_proxy/mysql_codec_clogin.cc#L47

questions:
1. Does it currently only support some mysql capabilities? Is there a function limit report?
2. As it seems that `HandshakeV9` is not decoded, will it be supported in the future? Maybe my understanding is incorrect.

tips: from google translation.

Any extra documentation required to understand the issue.

**Comment by zonghaishang** [comment]
@venilnoronha please take a look, thanks.

**Comment by zonghaishang** [comment]
```
➜  envoy git:(local_develop) ✗ bazel-bin/source/exe/envoy-static --version
bazel-bin/source/exe/envoy-static  version: d92237726127c9d2486c539a42a9ff64a89349ab/1.12.0-dev/Modified/DEBUG/BoringSSL
```

```
➜  ~ mysql -u root -P 15000 -h 127.0.0.1 -p
Enter password:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

envoy start config: 
```
static_resources:
  listeners:
  - name: mysql_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 15000
    filter_chains:
    - filters:
      - name: envoy.filters.network.mysql_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProxy
          stat_prefix: egress_mysql
      - name: envoy.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
          stat_prefix: mysql_tcp
          cluster: mysql_cluster

  clusters:
  - name: mysql_cluster
    connect_timeout: 1s
    type: strict_dns
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mysql
                port_value: 3306

# admin:
#   access_log_path: "/dev/null"
#   address:
#     socket_address:
#       address: 0.0.0.0
#       port_value: 8001

```
