### ISSUE TITLE
Troubleshooting: upstream connection remote resets

### ISSUE THREAD

**Issue by jay-manday** [envoyproxy/envoy#11890]
Hi there,

I'm new to envoy and i've been having a surprising amount of difficulty integrating it with a project that i'm working on. I'm using grpc-web and envoy to connect to a grpc service supporting my app and this error keeps coming up, I've gone through the ringer while trying to debug this and would love some assistance.

`upstream connect error or disconnect/reset before headers. reset reason: remote reset`

It seems that envoy cannot bind/route to my grpc server for some unclear reason. 
I'm running `envoyproxy/envoy-alpine:v1.14.2` and here is my yaml:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:   
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: ephemeris
                  max_grpc_timeout: 15s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: ephemeris
    connect_timeout: 15s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: 0.0.0.0, port_value: 5000 }}]
```

Note in the host address for my cluster on the final line i've tried the following to the same results described:
- `127.0.0.1`
- `<my-ip-addr>`
- `host.docker.internal`

Currently i'm testing the envoy proxy in the container and my grpc server running on localhost, though i've tried this configuration with both containers running, and the `ephemeris` host address set to the docker net ipv4 address i've assigned to the container with the same results.

Additional context: this project is not using kubernetes, i'm using consul (irrelevant for this issue) and will be deploying with ECS.

Here are the logs for an attempted connection to a status endpoint via envoy:
https://gist.github.com/jay-manday/430ce905285a4cfda69544889c3b00d2

As well as the upstream status via the envoy admin endpoint

```
ephemeris::default_priority::max_connections::1024
ephemeris::default_priority::max_pending_requests::1024
ephemeris::default_priority::max_requests::1024
ephemeris::default_priority::max_retries::3
ephemeris::high_priority::max_connections::1024
ephemeris::high_priority::max_pending_requests::1024
ephemeris::high_priority::max_requests::1024
ephemeris::high_priority::max_retries::3
ephemeris::added_via_api::false
ephemeris::0.0.0.0:5000::cx_active::0
ephemeris::0.0.0.0:5000::cx_connect_fail::14
ephemeris::0.0.0.0:5000::cx_total::14
ephemeris::0.0.0.0:5000::rq_active::0
ephemeris::0.0.0.0:5000::rq_error::14
ephemeris::0.0.0.0:5000::rq_success::0
ephemeris::0.0.0.0:5000::rq_timeout::0
ephemeris::0.0.0.0:5000::rq_total::0
ephemeris::0.0.0.0:5000::hostname::0.0.0.0
ephemeris::0.0.0.0:5000::health_flags::healthy
ephemeris::0.0.0.0:5000::weight::1
ephemeris::0.0.0.0:5000::region::
ephemeris::0.0.0.0:5000::zone::
ephemeris::0.0.0.0:5000::sub_zone::
ephemeris::0.0.0.0:5000::canary::false
ephemeris::0.0.0.0:5000::priority::0
ephemeris::0.0.0.0:5000::success_rate::-1.0
ephemeris::0.0.0.0:5000::local_origin_success_rate::-1.0
```

Any help troubleshooting this issue would be extremely appreciated!!

**Comment by dio** [comment]
I think the problem is you can't connect from the container to the host. Can you reach your service (i.e. running on `host` from a process inside your container?) from inside the container?

Where are you running it (Ubuntu? Mac?)? If you're on Mac, are you using "Docker Desktop" (and what version)?

If you're on Linux, e.g. Ubuntu, use host networking (it is easier).
If you're on Mac use "host.docker.internal".

**Comment by jay-manday** [comment]
Hey @dio 

Thanks so much for looking into this, i really appreciate it!

Sure thing, heres what im running:

```
MacOS 10.15.3
Docker Desktop:  2.3.0.3
Docker Engine: 19.03.8

and my container is using:
envoyproxy/envoy-alpine:v1.14.2
```

I did manage to  work out getting get some minor success with changing my cluster config to the following earlier today to the following:

```
  clusters:
  - name: ephemeris
    connect_timeout: 25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: host.docker.internal
                    port_value: 5000
```

So with this change I'm able to invoke the upstream grpc services via `grpcurl` through the envoy proxy which is great, though, grpc-web on the frontend is still unable to reach it and the browser console logs shows the following:

```
Access to XMLHttpRequest at 'localhost:8000/proto.EphemerisService/ListEphemeris' from origin 'http://localhost:3000' 
has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
```

Which is strange because my cors configuration is identical to the grpc-web hello world
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/helloworld/envoy.yaml

Additionally this cors error could explain why my requests to that simple status endpoint were failing as well.

And re: host networking, totally, im using something like this to define my network in docker-compose:

```
version: '3.7'

networks:
  examplenet:
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16

  envoy.rtr:
    container_name: envoy.rt
    build:
      context: ..
      dockerfile: packages/gateway/docker/local.Dockerfile
    env_file:
      - ../environment/docker/.env
    ports:
      - 8000:8000
      - 8001:8001
    networks:
      examplenet:
        ipv4_address: 172.28.1.2
     
  eph.svc:
    container_name: ephemeris.svc
    build:
      context: ..
      dockerfile: packages/ephemeris/docker/local.Dockerfile
    env_file:
      - ../environment/docker/.env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      examplenet:
        ipv4_address: 172.28.2.3

```

With this configuration i'm able to invoke the upstream services through the gateway, both thru docker-compose config and via only running the envoy proxy by itself, though all http1/ browser based rest traffic  is blocked for some reason. Additionally `curl localhost:8000:/status` to the proxy fails as well (even though i can verify that the service is working by curling it directly)

anyways thanks again so so much for taking the time to review and assist, I really appreciate it.
