### ISSUE TITLE
envoy (docker-compose) not hitting local springboot/grpc on bridge

### ISSUE THREAD

**Issue by drumcircle** [envoyproxy/envoy#12021]
SpringBoot grpc service is verified working on port 6565 using BloomRpc

When connecting through Envoy, the socket connection appears blocked:

```
font-envoy_1  | [2020-07-10 06:22:40.427][14][debug][client] [source/common/http/codec_client.cc:35] [C5] connecting
**font-envoy_1  | [2020-07-10 06:22:40.427][14][debug][connection] [source/common/network/connection_impl.cc:753] [C5] connecting to 127.0.0.1:6565**
font-envoy_1  | [2020-07-10 06:22:40.427][14][debug][connection] [source/common/network/connection_impl.cc:769] [C5] connection in progress
font-envoy_1  | [2020-07-10 06:22:40.427][14][debug][http2] [source/common/http/http2/codec_impl.cc:1063] [C5] updating connection-level initial window size to 268435456
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/conn_manager_impl.cc:1093] [C0][S14720151499271966158] decode headers called: filter=0x5562ddcea600 status=1
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/http1/codec_impl.cc:733] [C0] message complete
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/http1/codec_impl.cc:943] [C0] body size=21
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddcea000 status=0
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddceb2c0 status=0
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][router] [source/common/router/upstream_request.cc:196] [C0][S14720151499271966158] buffering 21 bytes
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddcea600 status=3
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][connection] [source/common/network/connection_impl.cc:315] [C0] readDisable: disable=true disable_count=0 state=0 buffer_length=346
font-envoy_1  | [2020-07-10 06:22:40.427][14][debug][http] [source/common/http/conn_manager_impl.cc:1377] [C0][S14720151499271966158] request end stream
font-envoy_1  | [2020-07-10 06:22:40.427][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddcea000 status=0
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddceb2c0 status=0
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][router] [source/common/router/upstream_request.cc:196] [C0][S14720151499271966158] buffering 0 bytes
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][http] [source/common/http/conn_manager_impl.cc:1225] [C0][S14720151499271966158] decode data called: filter=0x5562ddcea600 status=3
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][http] [source/common/http/http1/codec_impl.cc:570] [C0] parsed 346 bytes
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][connection] [source/common/network/connection_impl.cc:506] [C5] socket event: 3
font-envoy_1  | [2020-07-10 06:22:40.428][14][trace][connection] [source/common/network/connection_impl.cc:607] [C5] write ready
**font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][connection] [source/common/network/connection_impl.cc:625] [C5] delayed connection error: 111**
font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][connection] [source/common/network/connection_impl.cc:208] [C5] closing socket: 0
font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][client] [source/common/http/codec_client.cc:92] [C5] disconnect. resetting 0 pending requests
font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][pool] [source/common/conn_pool/conn_pool_base.cc:255] [C5] client disconnected, failure reason: 
font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][router] [source/common/router/router.cc:1022] [C0][S14720151499271966158] upstream reset: reset reason connection failure
font-envoy_1  | [2020-07-10 06:22:40.428][14][debug][http] [source/common/http/conn_manager_impl.cc:1520] [C0][S14720151499271966158] Sending local reply with details upstream_reset_before_response_started{connection failure}

```
The result in the client (grpc-web or postman, same result) is this:

```
font-envoy_1  | ':status', '200'
font-envoy_1  | 'content-type', 'application/grpc-web+proto'
font-envoy_1  | 'grpc-status', '14'
font-envoy_1  | 'grpc-message', 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'
font-envoy_1  | 'date', 'Fri, 10 Jul 2020 06:22:39 GMT'
font-envoy_1  | 'server', 'envoy'
```
I'm using `type: static` for my cluster load balancing.

envoy.yaml
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 9902 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: echo_service
                            max_grpc_timeout: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: echo_service
      connect_timeout: 0.25s
      type: static
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 6565


```

docker-compose.yml

```
version: '3.7'
services:
  font-envoy:
    image: envoy:v1
    env_file: ./docker-compose.env
    networks:
      - test
    build:
      context: .
      dockerfile: Dockerfile.envoy
    ports:
      - 9902:9902
      - 9901:9901
networks:
  test:
    driver: bridge
```

Dockerfile.envoy

```
FROM envoyproxy/envoy:v1.15.0
RUN mkdir -p /var/log/envoy/
RUN touch /var/log/envoy/admin_access.log
COPY envoy.yaml /etc/envoy/envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "-l", "trace", "--service-cluster", "cluster0", "--service-node", "node0"]
```

Many thanks in advance.

**Comment by drumcircle** [comment]
It seems that when calling the localhost from the docker container, 127.0.0.1 does not point to the host, it's an address in the docker container.

A runtime hostname, **docker.for.mac.localhost* (it's a thing not a place-holder), provides easy access to the localhost.  This change does require type: `logical_dns` vs `static`.

Updated `clusters:` section of the envoy.yaml

```
 clusters:
    - name: echo_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: docker.for.mac.localhost
                      port_value: 6565
```
