### ISSUE TITLE
Upstream connections destroyed

### ISSUE THREAD

**Issue by supasteev0** [envoyproxy/envoy#12022]
Hi, 

I have been experiencing an issue with destroyed upstream connections for a long time now, producing 503 errors and higher response times.
After digging both Envoy, application and Kubernetes nodes system logs, and trying to tweak some Kernel net settings for quite a while, I could find any explanation to this issue.

Envoy 1.14.1 is deployed with hostPort , 3 replicas, in an EKS 1.16 cluster behind an ALB.
Upstream cluster is a headless service (Real Time Bidding fasthttp go application) with 6 pods running.
There is an average of 650 Keep Alive connections opened from clients (service providers) sending approximately 4000 requests/second.

Below is an example of Envoy dashboard for this upstream service: 

![envoy-github](https://user-images.githubusercontent.com/8753896/87125953-a99b6e80-c28b-11ea-8f61-f44c23009638.png)

Here is example of cluster stats showing destroyed connections: 

```
cluster.rtbd-prod-v2.upstream_cx_active: 289
cluster.rtbd-prod-v2.upstream_cx_close_notify: 5
cluster.rtbd-prod-v2.upstream_cx_connect_attempts_exceeded: 0
cluster.rtbd-prod-v2.upstream_cx_connect_fail: 2
cluster.rtbd-prod-v2.upstream_cx_connect_timeout: 2
cluster.rtbd-prod-v2.upstream_cx_destroy: 239737
cluster.rtbd-prod-v2.upstream_cx_destroy_local: 238275
cluster.rtbd-prod-v2.upstream_cx_destroy_local_with_active_rq: 237866
cluster.rtbd-prod-v2.upstream_cx_destroy_remote: 1462
cluster.rtbd-prod-v2.upstream_cx_destroy_remote_with_active_rq: 74
cluster.rtbd-prod-v2.upstream_cx_destroy_with_active_rq: 237940
cluster.rtbd-prod-v2.upstream_cx_http1_total: 240026
```

Both Envoy and the application deployment have the following sysctls configured: 
```
securityContext:
        sysctls:
          - name: net.core.somaxconn
            value: "100000"
          - name: net.ipv4.tcp_max_syn_backlog
            value: "100000"
          - name: net.ipv4.ip_local_port_range
            value: "1025 65535"
```

Example Envoy configuration: 
```
static_resources:
  listeners:
  - address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    socket_options:
      - name: 9
        level: 1
        int_value: 1
        state: STATE_LISTENING
      - name: 4
        level: 6
        int_value: 60
        state: STATE_LISTENING
      - name: 5
        level: 6
        int_value: 60
        state: STATE_LISTENING
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: entrypoint
              domains: ["*"]
              routes:
              - match: { prefix: "/myprefix" }
                route:
                  cluster: second-cluster
              - match: { prefix: "/" }
                route:
                  cluster: first-cluster
                  request_mirror_policies:
                  - cluster: staging-cluster
                    runtime_fraction:
                      default_value:
                        numerator: 100
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                function envoy_on_response(response_handle)
                  if response_handle:headers():get("Connection") then
                    if response_handle:headers():get("Connection") == "close" then
                      response_handle:logInfo("====================> Received Connection closed : removing header")
                      response_handle:headers():remove("Connection")
                    end
                  end
                end
          - name: envoy.filters.http.router
            typed_config: {}
  clusters:
    - name: staging-cluster
      type: STRICT_DNS
      connect_timeout: 1s
      hosts: [{ socket_address: { address: my-staging-cluster.com, port_value: 80 }}]
      upstream_connection_options:
        tcp_keepalive: {}
      circuit_breakers:
        thresholds:
          - priority: DEFAULT
            max_connections: 1000000000
            max_pending_requests: 1000000000
            max_requests: 1000000000
            max_retries: 1000000000
          - priority: HIGH
            max_connections: 1000000000
            max_pending_requests: 1000000000
            max_requests: 1000000000
            max_retries: 1000000000
    - name: first-cluster
      type: STRICT_DNS
      connect_timeout: 1s
      hosts: [{ socket_address: { address: first-cluster.svc.cluster.local, port_value: 5000 }}]
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 1
          keepalive_time: 5
          keepalive_interval: 60
      circuit_breakers:
        thresholds:
          - priority: DEFAULT
            max_connections: 1000000000
            max_pending_requests: 1000000000
            max_requests: 1000000000
            max_retries: 1000000000
          - priority: HIGH
            max_connections: 1000000000
            max_pending_requests: 1000000000
            max_requests: 1000000000
            max_retries: 1000000000
    - name: second-cluster
      type: LOGICAL_DNS
      connect_timeout: 1s
      hosts: [{ socket_address: { address: second-cluster.svc.cluster.local, port_value: 5000 }}]

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
```

I have to point out the fact that none of the issue appears with the same trafic load when routing traffic directly to the application.
I have also tried to disable mirroring and scale up application pods without getting any satisfying results.

Would you have any advice on how to solve this issue ?
