### ISSUE TITLE
Using envoy with multiple grpc endpoints

### ISSUE THREAD

**Issue by c10b10** [envoyproxy/envoy#12074]
Is it possible to tweak the `envoy.yaml` file to make it proxy multiple gRPC endpoints? If so, how?

**Comment by qiwzhang** [comment]
It is possible.  You can create a route config to route the request by service name.  Create a RouteMatch based in path prefix which is the gRPC service name,  each service will route to different gRPC backend defined in different clusters.

**Comment by c10b10** [comment]
@qiwzhang Can you point me to some example code / documentation on this topic?

**Comment by povesteam** [comment]
The gRPC services are on TCP layer, not HTTP, therefore it is not possible to differentiate multiple endpoints by path.

Instead, header-based separation is possible, using route configs like this:

```yml
        # ...
        - match:
            prefix: "/"
            headers:
              - name: x-service
                exact_match: my-awesome-service
        # ...
```

Please share if you find a way to differentiate gRPC by path. Thank you!

**Comment by kundansingh86** [comment]
> It is possible.  You can create a route config to route the request by service name.  Create a RouteMatch based in path prefix which is the gRPC service name,  each service will route to different gRPC backend defined in different clusters.

Can you please share an example?

**Comment by fr33kvanderwand** [comment]
> The gRPC services are on TCP layer, not HTTP, therefore it is not possible to differentiate multiple endpoints by path.
> 
> Instead, header-based separation is possible, using route configs like this:
> 
> ```yaml
>         # ...
>         - match:
>             prefix: "/"
>             headers:
>               - name: x-service
>                 exact_match: my-awesome-service
>         # ...
> ```
> 
@povesteam thanks, but can you please provide a bit more detailed example?

**Comment by povesteam** [comment]
Meanwhile we changed our approach, because envoy was overly complex to configure (from my point of view as a developer; maybe an experienced devops would have done better).
Now gRPC calls are only made server-to-server, without any proxy. So we ditched envoy, at least for now.
I don't have an example anymore, @fr33kvanderwand. Sorry about that.

**Comment by fr33kvanderwand** [comment]
Thanks for the reply, @povesteam  :D
I, for now, after reading a lot of envoy documentation, ended up with something like that:
```yaml
# ...
virtual_hosts:
- name gRPC-web-proxy
  domains: ["*"]
  routes:
  - name: my-super-service
    match:
      prefix: "/"
      headers:
        - name: my-service-header
          exact_match: "super-service"
    route:
      cluster: super_service
      cors: /* ... */
  - name: my-second-service
    match:
      prefix: "/"
      headers:
        - name: my-service-header
          exact_match: "second-service"
    route:
      cluster: second_service
      cors: /* ... */
  - name: fallback
    match:
      prefix: "/"
    route:
      cluster: super_service
      cors: /* ... */
#...
clusters:
- name: super_service
  # ...
  load_assignment:
    cluster_name: super_service
    endpoints:
    - lb_endpoints:
      - endpoint
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 1234
  transport_socket: /* ... */
- name: second_service
  # ...
  load_assignment:
    cluster_name: second_service
    endpoints:
    - lb_endpoints:
      - endpoint
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 4321
  transport_socket: /* ... */
```
but I'm sure it could be done better, like define CORS for all route, define one transport_socket for all cluster, and so on...
