### ISSUE TITLE
Upgrade from v1.12.3 to v1.14.4 leads to more CPU usage without traffic

### ISSUE THREAD

**Issue by fxposter** [envoyproxy/envoy#12080]
*Description*:
While trying to upgrade to latest version of envoy, we faced the problem (maybe) - envoy started to consume 1.5x more cpu (from 7-9% cpu to 12-20%) when there are no traffic to this particular envoy instance. Also, cpu usage graph now have way more spikes than it had before(previously it looked like a flat line - now it is full of spikes).

We have our own control plane and our bootstrap config looks like this:

```
node:
  cluster: private-cluster

admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

stats_flush_interval: 120s

dynamic_resources:
  lds_config: {ads: {}}
  cds_config: {ads: {}}
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: xds_cluster

static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: RANDOM
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
        keepalive_interval: 10
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: private-address
                port_value: 8080
```

we have quite a lot of routes/clusters/clusterLoadAssignments there which change quite often, though in this particular case number of changes is not that big - change every 20-300 seconds, but they are still present. Full config dump after initialization is about 6mb.

Doing CPU profiling gives me something like this:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/109216/87476875-ce973500-c62f-11ea-8600-2d1d8b2eaabb.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/109216/87476931-e79fe600-c62f-11ea-8c64-c1d7db0c689a.png">

We don't use envoy's healthchecking/rate limiting/etc - I am not sure whether their appearance in cpu profile says anything, but it bothers me a bit. Also, "__ZNSt3__1L20__throw_length_errorEPKc" looks strange.

Full profile of 10 minutes of time is here: [envoy.1.14.prof.zip](https://github.com/envoyproxy/envoy/files/4921514/envoy.1.14.prof.zip)
