### ISSUE TITLE
websocket with dynamic forward proxy

### ISSUE THREAD

**Issue by codeyq** [envoyproxy/envoy#12188]
I have an envoy running as a dynamic reverse proxy where the `Host` header is the upstream target. Everything is working perfectly so far except for websocket connections. I am not seeing any websocket traffic in the access log. This is the configuration I am using. Did I miss anything? Thanks!
```yaml
            - "name": "envoy.filters.network.http_connection_manager"
              "typed_config":
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
                "http_filters":
                - "name": "envoy.filters.http.dynamic_forward_proxy"
                  "typed_config":
                    "@type": "type.googleapis.com/envoy.config.filter.http.dynamic_forward_proxy.v2alpha.FilterConfig"
                    "dns_cache_config":
                      "dns_lookup_family": "V4_ONLY"
                      "name": "dynamic_forward_proxy_cache_config"
                "upgrade_configs":
                - "upgrade_type": "websocket"
```
