### ISSUE TITLE
mongo proxy: limited access logs

### ISSUE THREAD

**Issue by witalisoft** [envoyproxy/envoy#12272]
*Title*: *mongo proxy limited access logs*

*Description*:
I've configure envoy that acts as mongodb proxy with access logs support, but there is only a little subset of command being logged with one session.

*Repro steps*:
reuse config with:
```
# envoy --version
envoy  version: 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/Clean/RELEASE/BoringSSL
```

*Config*:
```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
static_resources:
  listeners:
  - name: mongodb00
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 27000
    filter_chains:
    - filters:
      - name: envoy.filters.network.mongo_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.mongo_proxy.v2.MongoProxy
          stat_prefix: mongo_proxy00
          access_log: /tmp/mongo_stats00.log
          emit_dynamic_metadata: true
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
          stat_prefix: ingress_tcp00
          cluster: mongo00
  clusters:
  - name: mongo00
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: mongo00
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                 socket_address:
                    address: mongo.dns.name
                    port_value: 27017
```

*Logs*:
application connect to mongo, list database, insert data, query data and disconnected, logs only contains:
```
{"time": "2020-07-24T10:21:56.150Z", "message": {"opcode": "OP_QUERY", "id": 1, "response_to": 0, "flags": "0x4", "collection": "admin.$cmd", "skip": 0, "return": -1, "query": {"isMaster": 1, "compression": {}, "client": {"driver": {"name": "mongo-go-driver", "version": "v1.4.0+prerelease"}, "os": {"type": "darwin", "architecture": "amd64"}, "platform": "go1.14"}}, "fields": {}}, "upstream_host": "mongo.dns.name:27017"}
{"time": "2020-07-24T10:21:56.178Z", "message": {"opcode": "OP_REPLY", "id": 33838692, "response_to": 1, "flags": "0x8", "cursor": "0", "from": 0, "returned": 1, "documents": 1}, "upstream_host": "mongo.dns.name:27017"}
{"time": "2020-07-24T10:21:56.320Z", "message": {"opcode": "OP_QUERY", "id": 2, "response_to": 0, "flags": "0x4", "collection": "admin.$cmd", "skip": 0, "return": -1, "query": {"isMaster": 1, "saslSupportedMechs": "admin.admin", "speculativeAuthenticate": {"saslStart": 1, "mechanism": "SCRAM-SHA-256", "payload": "n,,n=admin,r=payload", "db": "admin", "options": {"skipEmptyExchange": true}}, "compression": {}, "client": {"driver": {"name": "mongo-go-driver", "version": "v1.4.0+prerelease"}, "os": {"type": "darwin", "architecture": "amd64"}, "platform": "go1.14"}}, "fields": {}}, "upstream_host": "mongo.dns.name:27017"}
{"time": "2020-07-24T10:21:56.373Z", "message": {"opcode": "OP_REPLY", "id": 33838752, "response_to": 2, "flags": "0x8", "cursor": "0", "from": 0, "returned": 1, "documents": 1}, "upstream_host": "mongo.dns.name:27017"}
```
