### ISSUE TITLE
Access log log_format.text_format field is not printing logs

### ISSUE THREAD

**Issue by hinawatts** [envoyproxy/envoy#12348]
I am trying to enable v3 access logs for my application, where I am using text_format option. Logs are not getting printed if I use text_format, however if I use json_format, i can see the logs. Below is the snippet I used for enabling access logs - 
```yaml
filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                access_log:
                  name: envoy.access_loggers.http_grpc
                  typed_config:
                    '@type': >-
                      type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    log_format:
                      text_format: "plain_text - %REQ(:path)% - %RESPONSE_CODE%"
                    path: "/dev/stdout"
     ```
Please suggest how can i enable access logs using text option.

**Comment by jleskovar-tyro** [comment]
Hi, did you find a solution to this issue @hinawatts ?

**Comment by hinawatts** [comment]
Hi @jleskovar-tyro, no I didn't find a solution to this. I have switched to json_format type.

**Comment by dio** [comment]
@hinawatts @hinawatts 

Example of access log config for a `v3` `HttpConnectionManager` is as follows:

```yaml
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
            name: "envoy.access_loggers.http_file"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
              path: "/dev/stdout"
              log_format:
                text_format: "path=%REQ(:path)%\n"
```

And for `v2`:

```yaml
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          access_log:
            name: "envoy.access_loggers.http_file"
            typed_config:
              "@type": "type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog"
              path: "/dev/stdout"
              format: "path=%REQ(:path)%\n"
```

Note that logs printing is buffered, so there will be a delay (for envoy to print a log corresponding log line) if you test it with a single request.
