### ISSUE TITLE
bypass_cors_preflight=true flag is still applying authentication filter to preflight calls and returning 401

### ISSUE THREAD

**Issue by manogarsubramaniyam** [envoyproxy/envoy#12375]
Here's the definition of envoy proxy. Can someone help me on this?

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/dev/stdout"
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.jwt_authn
                    typed_config: 
                      "@type": type.googleapis.com/envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication
                      providers:
                        jwt_provider_oauth:
                          issuer: https://sso-ext.devops.quickplay.com/auth/realms/sbox
                          forward: true
                          remote_jwks:
                            http_uri:
                              uri: https://sso-ext.devops.quickplay.com/auth/realms/sbox/protocol/openid-connect/certs
                              cluster: oauth_cluster
                              timeout: 5s
                            cache_duration:
                              seconds: 300
                      rules:
                      - match:
                          path: /healthz
                      - match:
                          prefix: /
                        requires:
                          provider_name: jwt_provider_oauth
                      bypass_cors_preflight: true
                  - name: envoy.filters.http.ext_authz
                    config:
                      with_request_body:
                        max_request_bytes: 819200
                        allow_partial_message: true
                      failure_mode_allow: false
                      grpc_service:
                        google_grpc:
                          target_uri: 127.0.0.1:9191
                          stat_prefix: ext_authz
                        timeout: 0.5s
                  - name: envoy.filters.http.router
                    typed_config: {}
  clusters:
    - name: service
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: oauth_cluster
      connect_timeout: 10s
      type: LOGICAL_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: oauth_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: sso-ext.devops.quickplay.com
                  port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: sso-ext.devops.quickplay.com
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
