### ISSUE TITLE
Address changing localities results in corrupted EDS

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#12392]
When an address is switched to a different locality, it appears something goes wrong in the update, resulting in the EDS update not being applied correctly.

Initial EDS:
```yaml
  endpoints:
  - locality:
      region: primary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.10.10.10
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
  - locality:
      region: secondary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 20.20.20.20
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 1
```

Later send:
```yaml
  endpoints:
  - locality:
      region: primary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 20.20.20.20
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 20
  - locality:
      region: secondary
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 30.30.30.30
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 80
```

Resulting EDS (from config_dump, but I originally found this in a real cluster and verified traffic was incorrect as well, proving its not just a config_dump bug)
```yaml
- locality:
    region: secondary
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 20.20.20.20
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  - endpoint:
      address:
        socket_address:
          address: 30.30.30.30
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 80
```

Here you can see the `20.20.20.20` address ends up in the wrong locality.

This is not limited to just having the endpoints simply not move localities either:

<details>

Input 1:
```yaml
  endpoints:
  - locality:
      region: region
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.10.10.10
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
  - locality:
      region: notregion
      zone: notzone
      subZone: notsubzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.93.137
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 2
  - locality:
      region: nearregion
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.220.97
            portValue: 80
      loadBalancingWeight: 1
    loadBalancingWeight: 1
    priority: 1
```

Input 2:
```yaml
  endpoints:
  - locality:
      region: region
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.93.137
            portValue: 80
      load_balancing_weight: 1
    load_balancing_weight: 20
  - locality:
      region: notregion
      zone: notzone
      subZone: notsubzone
    load_balancing_weight: 1
  - locality:
      region: nearregion
      zone: zone
      subZone: subzone
    lbEndpoints:
    - endpoint:
        address:
          socketAddress:
            address: 10.103.220.97
            portValue: 80
      load_balancing_weight: 1
    load_balancing_weight: 80
```

Result:
```yaml
- locality:
    region: nearregion
    zone: zone
    sub_zone: subzone
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 10.103.220.97
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 80
- locality:
    region: notregion
    zone: notzone
    sub_zone: notsubzone
  lb_endpoints:
  - endpoint:
      address:
        socket_address:
          address: 10.103.93.137
          port_value: 80
      health_check_config: {}
    health_status: HEALTHY
    load_balancing_weight: 1
  load_balancing_weight: 1
```

You can see here notregion gets load_balancing_weight=1 when its expected to be `20`

</details>

Reproduce: 
[repro.tar.gz](https://github.com/envoyproxy/envoy/files/5004122/repro.tar.gz)

```
ln -sf eds1.yaml eds.yaml
envoy -c envoy-eds.yaml
ln -sf eds2.yaml eds.yaml
```
