### ISSUE TITLE
[Document clarification] tracing sampling range

### ISSUE THREAD

**Issue by christine-gong** [envoyproxy/envoy#12548]
### Description
https://www.envoyproxy.io/docs/envoy/v1.14.3/configuration/http/http_conn_man/runtime#config-http-conn-man-runtime-global-enabled says
```This runtime control is specified in the range 0-10000 and defaults to 10000. Thus, trace sampling can be specified in 0.01% increments.```
does this apply to random_sampling only?
since both v2 and v3 apis say the all sampling types are percent (float range in [0.0 - 100.0].
But when I specify the sampling rate as 0.1 in the envoy config like 
```
               tracing:
                      client_sampling:
                        value: 100.0
                      random_sampling:
                        value: 100.0
                      overall_sampling:
                        value: 0.1
```
there is no traces collected at all. Works when i bump the overall_sampling value to `1.0`
Does envoy allow sampling rate lower than 1%? or thats only for random sampling?
Thanks!
