### ISSUE TITLE
Reverse-proxy with Envoy - Enable internal-redirects

### ISSUE THREAD

**Issue by Jaskaranbir** [envoyproxy/envoy#12559]
I am trying to redirect all traffic going to a K8s pod to Envoy, with a later goal to perform some operations on that traffic (such as monitoring etc.). For this, I have added an IPTable rule to redirect traffic from network-interface to Envoy's address/port. Until here, it seems to work fine (I can see the requests coming into Envoy). Also, I am _not_ using Istio, just Envoy.

However, I get 302 in grpc-responses which the service isnt designed to handle, so I must redirect internally within the proxy. Basically, the equivalent of `-L` in curl. In fact, if I make request with `curl -L ....`, it works as intended.

In docs, I saw the internal-redirect-policy: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#internal-redirects
But unable to get it working, it seems to always detect it as invalid option. Here's a sample snippet:

```yaml
              - filters:
                - name: "envoy.http_connection_manager"
                  config:
                    stat_prefix: "ingress"
                    codec_type: "AUTO"
                    use_remote_address: true
                    route_config:
                      name: "xyz"
                      virtual_hosts:
                      ...
                      internal_redirect_policy:
                        max_internal_redirects: 5
                        allow_cross_scheme_redirect: true
```

I couldnt find an example which used `internal_redirect_policy`, so a config-example would really help.
