### ISSUE TITLE
`SpecificPerFilterConfig` should support semantic names

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#12575]
Filter names no longer encode filter types, so the name `envoy.filters.http.ext_authz` is not strictly required.
note: `myco.ext_authz` in the example.

```yaml
  - name: myco.ext_authz
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      http_service:
          server_uri:
            cluster: ext-authz
```

However,  route specific config name is hardcoded in the filter code, which forces the route config to continue using `envoy.filters.http.ext_authz` compatibility name.
```
    routes:
    - match: { prefix: "/static" }
      route: { cluster: some_service }
      typed_per_filter_config:
        envoy.filters.http.ext_authz:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
          disabled: true
```
https://github.com/envoyproxy/envoy/blob/67c5b435fd4723198091a658d913823b586b3854/source/extensions/filters/http/ext_authz/ext_authz.cc#L308

When a filter of the same type is instantiated in several different configs, this does not work.

Options
1. Pass in the `name` to the filter, this may already be the case. The filter should use that name instead of hardcoded value like the one above.
```c++
Http::Utility::resolveMostSpecificPerFilterConfig<FilterConfigPerRoute>(
          getFilterSemanticName(), route);
```
instead of 
```c++
      Http::Utility::resolveMostSpecificPerFilterConfig<FilterConfigPerRoute>(
          HttpFilterNames::get().ExtAuthorization, route);
```
2. Use thread context to figure this out?

@dio @kyessenov
