### ISSUE TITLE
ext_authz: Support filter naming and per-filter statistics

### ISSUE THREAD

**Issue by danielmittelman** [envoyproxy/envoy#12666]
*Title*: Support filter naming and per-filter statistics

*Description*:
My HTTP filter chain contains multiple instances of `ext_authz`, each fulfilling a completely different task.

My real-life use case:
```yaml
http_filters:
  # Filter #1 - WAF sidecar
  - name: envoy.filters.http.ext_authz
    config: {...}

  # Filter #2 - request authorization service
  - name: envoy.filters.http.ext_authz
    config: {...}
```

In this case, I can access relevant statistics about the External Authorization executions in general, but I cannot distinguish between the two external services, and most importantly I cannot measure the allow/deny rates of each of the filters.

My suggestion is to have the option of **naming each of the filters**, and having that name **added as a dimension** to the statistics produced by the filter, for example:

```yaml
http_filters:
  # Filter #1 - WAF sidecar
  - name: envoy.filters.http.ext_authz
    config:
      filter_stat_name: waf
      ...

  # Filter #2 - request authorization service
  - name: envoy.filters.http.ext_authz
    config:
      filter_stat_name: authorizer
      ...
```
