### ISSUE TITLE
Stats filtering inclusion list is not working for server level metrics

### ISSUE THREAD

**Issue by shyamradhakrishnan** [envoyproxy/envoy#12675]
We have the following configuration in envoy

```yml
    stats_config:
      stats_matcher:
        inclusion_list:
          patterns:
          - suffix: upstream_cx_total
          - exact: envoy_server_state
```
In this case, the metrics with suffix upstream_cx_total is emitted properly, but the metric envoy_server_state is never emitted. Please check if this a bug, we have a large config and metrics is slowing envoy down, hence wanted to include only the required metrics which is a combination of cluster and server level metrics.
