### ISSUE TITLE
Question: remote JWT can't GET token by URI with 'jwt is missing' error

### ISSUE THREAD

**Issue by luyisa** [envoyproxy/envoy#12723]
I want to use remote JWT for remote identity server, with exposed jwks URI

My config in envoy.yaml
```
 http_filters:
            - name: envoy.filters.http.jwt_authn
              typed_config: 
                "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                providers:
                  provider1:
                    issuer: "https://<host>/oidc/endpoint/default"
                    remote_jwks:
                      http_uri:
                        uri: "https://<host>/v1.0/endpoint/default/jwks"
                        cluster: security-authz
                        timeout: 5s
                      cache_duration:
                        seconds: 300
                rules:
                - match: {path: "/hosts"}
                  requires: 
                    provider_name: provider1

- name: security-authz
      connect_timeout: 3s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: security-authz
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: <host>
                  port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: <host>
          common_tls_context: 
            validation_context:
              trusted_ca:
                filename: /etc/ssl/certs/ca-cert.crt
```

Debug info in my container:
```
[2020-08-19 02:56:05.016][23][debug][http] [source/common/http/conn_manager_impl.cc:808] [C0][S7658054839179206635] request headers complete (end_stream=true):
':authority', '127.0.0.1:10000'
':path', '/hosts'
':method', 'GET'
'connection', 'keep-alive'
'cache-control', 'max-age=0'
'upgrade-insecure-requests', '1'
'user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36'
'accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9'
'sec-fetch-site', 'none'
'sec-fetch-mode', 'navigate'
'sec-fetch-user', '?1'
'sec-fetch-dest', 'document'
'accept-encoding', 'gzip, deflate, br'
'accept-language', 'en-US,en;q=0.9'
```
I can't see Any Authorization: Bearer <token> in my request, so I assume no GET for jwks URI... any thing wrong with my settings or not support?

Note: The remote JWT server is using OpenID connect 1.0
