### ISSUE TITLE
Envoy Round-Robin TCP Proxying is not balancing cluster hosts

### ISSUE THREAD

**Issue by hnasr** [envoyproxy/envoy#12882]
Trying out Envoy for the first time, built a quick TCP Proxy with this config, and it appears that Envoy is not truly balancing new connections evenly.

I have 3 services running on my mac on port 1111, 2222 and 3333 that simply returns their port number, this way I know which service I am hitting. I put an Envoy TCP proxy behind those 3 hosts but notice when I curl envoy frontend (which is establishing a new TCP connection every time, envoy sometimes hits the same host multiple time despite lb policy being round-robin. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3898305/91620023-a6476980-e943-11ea-8858-4c73c33748fa.gif)

My envoy config, anything looks wrong? 

thanks! awesome doc by the way 

```yaml
static_resources:
    listeners:
    - name: tcp_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8082
      filter_chains:
      - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
            stat_prefix: tcp_proxy
            cluster: backend_cluster
  
    clusters:
    - name: backend_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: backend_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: husseinmac
                  port_value: 1111
          - endpoint:
              address:
                socket_address:
                  address: husseinmac
                  port_value: 2222
          - endpoint:
              address:
                socket_address:
                  address: husseinmac
                  port_value: 3333                  

```
