### ISSUE TITLE
How is RegexMatchAndSubstitute used within a RouteMatch?

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#12910]
Hi folks

Hopefully this is an easy one.

Say I have a RouteMatch as follows

```yaml
match:
  safe_regex:
    pattern: '^/hello'
    substitution: '/'
```

Envoy reports the following

> INVALID_ARGUMENT:(route_config.virtual_hosts[0].routes[0].match.safe_regex) substitution: Cannot find field.

What is the actual syntax for this? I can't find any examples

**Comment by cetanu** [comment]
Found some examples in the tests:

```yaml
  - match:
      prefix: "/newforreg1_endpoint"
    route:
      regex_rewrite:
        pattern:
          google_re2: {}
          regex: "^/new(.*?)_endpoint(.*)$"
        substitution: /\1_rewritten_endpoint\2
      cluster: www2
  - match:
      prefix: "/newforreg2_endpoint"
    route:
      regex_rewrite:
        pattern:
          google_re2: {}
          regex: "e"
        substitution: "X"
      cluster: www2
```
