### ISSUE TITLE
Envoy to pass hits_addend to RateLimitService

### ISSUE THREAD

**Issue by wwillsey** [envoyproxy/envoy#12969]
## Description
The [RLS v3 api](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto) describes the RateLimitService as able to injest a hits_addend field to determine number of tokens to use for the rate limiting request. 
Envoy should provide a method for extracting a value from a request header (or some other method) to populate this method on a _per request_ basis. If hits_addend is only static, then it is effectively the same as modifying the ratelimit. 

### Use case
In the [HTTP Rate Limit Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter#config-http-filters-rate-limit) allow for a configuration of a request header containing an integer hits_addend value to send with the rate limit request, allowing for greater configurability of rate limiting capabilities.

**Comment by wwillsey** [comment]
Hey @mattklein123, I've created this issue to follow up on https://github.com/envoyproxy/ratelimit/issues/167. Please let me know if you think any more details would be helpful. 

Thanks!

**Comment by mattklein123** [comment]
Yeah this makes sense to me. Marking help wanted.

**Comment by medalliaerlich** [comment]
any news regarding this?

**Comment by sc0ttbeardsley** [comment]
Pinterest is interested in this also. cc @fishcakez @JuniorHsu

**Comment by lizzzcai** [comment]
Hi, any news regarding this? We would like to use it to limit the token/minutes for the LLM use case, as they are usually limited by `tokens-per-minutes` rather than requests/secs.

**Comment by PeterL328** [comment]
Related work.
I updated the ratelimit client to support the hits_addend field (https://github.com/envoyproxy/envoy/pull/28939). Some extra work would be required so users can configure ratelimit sidecar to send hits_addend

**Comment by PeterL328** [comment]
@lizzzcai In case you are using the OpenAI API, I think they limit on request token + response token. So further work would be required so the response token can be sent to the ratelimit sidecar.

**Comment by lizzzcai** [comment]
Hi @PeterL328 , thanks for your update, I will follow your other PR for the progress. 
> In case you are using the OpenAI API, I think they limit on request token + response token.

For our case, we are using Azure OpenAI. However, I think the limit is not on the `response` token at least for Azure OpenAI.  For our case we are using `prompt text token` + `max_tokens`(max number of token will be responded) in the `request`.

Reference: [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/quota?tabs=rest#understanding-rate-limits)

> As each request is received, Azure OpenAI computes an estimated max processed-token count that includes the following:
> 
> Prompt text and count
> The max_tokens parameter setting
> The best_of parameter setting
> 
> As requests come into the deployment endpoint, the estimated max-processed-token count is added to a running token count of all requests that is reset each minute. If at any time during that minute, the TPM rate limit value is reached, then further requests will receive a 429 response code until the counter resets.

**Comment by PeterL328** [comment]
Hi @lizzzcai,
We use OpenAI API and also Azure OpenAI. I believe both will report back the total token consumed (request + response token) in the response body. 

Yea you can use the max token on the response but it will not be accurate if that is what you need if you plan to track it.

**Comment by EItanya** [comment]
I have opened #34184 as a potential solution to setting `hits_addend` in an unobtrusive way.

**Comment by OS-ramamurtisubramanian** [comment]
Hi @EItanya, I'm trying to use the hits addend with istio. Can you please provide me an example of how to configure this as an EnvoyFilter?

I was trying to use the [set filter state](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/set_filter_state) filter to set the `envoy.ratelimit.hits_addend` filter state, but It was not working. 

I get the following error.

Error adding/updating listener(s) virtualInbound: 'envoy.ratelimit.hits_addend' does not have an object factory.

**Comment by zirain** [comment]
please use master branch

**Comment by OS-ramamurtisubramanian** [comment]
Hi @zirain , I managed to build and use the piot and proxyv2 images of istio from master branch.

I am tryting to create the following EnvoyFilter objects.

`apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-global-ratelimit
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      app: httpbin
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: productpage-ratelimit
            failure_mode_deny: true
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||ratelimit.istio-system.svc.cluster.local
                  authority: ratelimit.istio-system.svc.cluster.local
              transport_api_version: V3
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-set-ratelimit-filter-state
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      app: httpbin
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.ratelimit"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.set.hits.addend
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
            on_request_headers:
            - object_key: envoy.ratelimit.hits_addend
              format_string:
                text_format_source:
                  inline_string: "%REQ(:HITS)%"
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
spec:
  workloadSelector:
    labels:
      app: httpbin
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
              - request_headers:
                  header_name: "x-rate-limit-please"
                  descriptor_key: "ratelimitheader"
                  skip_if_absent: true
              - request_headers:
                  header_name: ":path"
                  descriptor_key: "PATH"`
                  
 Is this the correct way to set the envoy.ratelimit.hits_addend filter state from a request header called hits, before the rate limit filter?

**Comment by zirain** [comment]
be careful of inserting a filter based on something that is created by another envoyfilter.

**Comment by gcalmettes** [comment]
Seeing the same problem than the one described by @OS-ramamurtisubramanian on the `v1.31.1`, when trying to use the `envoy.filters.http.set_filter_state` filter to set the [`envoy.ratelimit.hits_addend`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto#envoy-v3-api-field-service-ratelimit-v3-ratelimitrequest-hits-addend) state key.

```
          - name: envoy.filters.http.set_filter_state
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
              on_request_headers:
              - object_key: envoy.ratelimit.hits_addend
                format_string:
                  text_format_source:
                    inline_string: "0"

```

Error log is:
```
[main] [source/server/server.cc:412] error initializing config '  /etc/envoy/envoy.yaml': 'envoy.ratelimit.hits_addend' does not have an object factory 
```

**Comment by zirain** [comment]
> Seeing the same problem than the one described by @OS-ramamurtisubramanian on the latest `v1.31.2`, when trying to use the `envoy.filters.http.set_filter_state` filter to set the [`envoy.ratelimit.hits_addend`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/ratelimit/v3/rls.proto#envoy-v3-api-field-service-ratelimit-v3-ratelimitrequest-hits-addend) state key.
> 
> ```
>           - name: envoy.filters.http.set_filter_state
>             typed_config:
>               "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
>               on_request_headers:
>               - object_key: envoy.ratelimit.hits_addend
>                 format_string:
>                   text_format_source:
>                     inline_string: "0"
> ```
> 
> Error log is:
> 
> ```
> [main] [source/server/server.cc:412] error initializing config '  /etc/envoy/envoy.yaml': 'envoy.ratelimit.hits_addend' does not have an object factory 
> ```
> 
> Is there another configuration to add ?

I cannot recall, but can you give a try with main branch?

**Comment by gcalmettes** [comment]
@zirain I just tried using a freshly built envoy binary from the `main` branch.

```
> ./envoy --version          

./envoy  version: 51e253405a2be7f94df8c0ba78bd884dc79bb8a5/1.32.0-dev/Modified/DEBUG/BoringSSL
```

Configuration tested:

```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.set_filter_state
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
              on_request_headers:
              - object_key: envoy.ratelimit.hits_addend
                format_string:
                  text_format_source:
                    inline_string: "0"
          - name: envoy.filters.http.ratelimit
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: rpm
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              failure_mode_deny: false
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit
                transport_api_version: V3
              rate_limited_as_resource_exhausted: true
              request_type: external
              stage: 0
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
  - name: ratelimit
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: ratelimit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5001
```

same error:

```
[2024-10-09 18:14:52.204][619209][info][main] [source/server/server.cc:871] runtime: {}
[2024-10-09 18:14:52.206][619209][info][admin] [source/server/admin/admin.cc:65] admin address: 127.0.0.1:9901
[2024-10-09 18:14:52.209][619209][info][config] [source/server/configuration_impl.cc:168] loading tracing configuration
[2024-10-09 18:14:52.209][619209][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2024-10-09 18:14:52.209][619209][info][config] [source/server/configuration_impl.cc:130] loading 2 cluster(s)
[2024-10-09 18:14:52.231][619209][info][config] [source/server/configuration_impl.cc:138] loading 1 listener(s)
[2024-10-09 18:14:52.241][619209][info][config] [source/server/configuration_impl.cc:168] loading tracing configuration
[2024-10-09 18:14:52.241][619209][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2024-10-09 18:14:52.241][619209][info][config] [source/server/configuration_impl.cc:130] loading 2 cluster(s)
[2024-10-09 18:14:52.258][619209][info][config] [source/server/configuration_impl.cc:138] loading 1 listener(s)
[2024-10-09 18:14:52.266][619209][critical][main] [source/server/server.cc:412] error initializing config '  envoy-basic.yaml': 'envoy.ratelimit.hits_addend' does not have an object factory
[2024-10-09 18:14:52.268][619209][info][main] [source/server/server.cc:1042] exiting
'envoy.ratelimit.hits_addend' does not have an object factory
```

**Comment by zirain** [comment]
I'm not sure how you build it, I cannot reproduce it on my machine.

```
bazel build envoy
cp bazel-bin/source/exe/envoy-static /usr/local/bin/envoy-dev
envoy-dev -c envoy.yaml
```

**Comment by gcalmettes** [comment]
@zirain , sorry, I must have missed something in my first build (I was using the docker script provided). Trying with you command indeed works. Thank you !
It's very useful to set a different hitsAddend value per filter for different domains when multiple ratelimit filters are chained.

**Comment by brightbyte** [comment]
I am also interested in this for use with the Wikipedia API. Some of our endpoints can be very expensive depending on the request parameters, and it would be useful to account for that in rate limiting.

Envoyproxy accepts hits_addend in the rate limit configuration, and the RLS protocol also suppotrs it, but I can't get envoy to actually use the information from the config and send it to the rate limit service.

I just started evaluating envoy for this use case, and I'm not familiar with all the details yet. I naively tried this:
```
static_resources:
  listeners:
    - name: https_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: mediawiki_cluster
                      rate_limits:
                        - actions:
                            - request_headers:
                                # just a dummy for testing
                                header_name: host
                                descriptor_key: host
                          hits_addend:
                            # this should work, right?
                            number: 2
                          stage: 0
```

But it's not working - I can see the request going into the rate limiting service, but it is missing the optional hits_addend field. 

I saw the comment mentioning Set-Filter-State above, but it is not clear to me how that works, can you point me to an example?

**Comment by gcalmettes** [comment]
@brightbyte I can provide you with a minimal config example. However depending on what you want to achieve, the config might look very different. Are the `hits_addend` dynamic in your case (e.g.: you want to inject a hits_addend 2 only based on some criteria ?), or do you want always the `hits_addend` 2 ?

basically, the `set_filter_state` allow you to override the "basic" hits_addend sent with all the ratelimit requests (default = 1), but that's not necessarily what you want. If you want to specify a specific `hits_addend` (e.g.: only for a specific route, based on a path or header for example), you'll need a `typed_per_filter_config` in your route config to override the `hits_addend` for this specific route.

**Comment by gcalmettes** [comment]
@brightbyte here is a complete example with the following behavior:
- path `/route-1` hit:
    - no ratelimiting  (e.g.: `curl -v http://localhost:8888/route-1`)
    - if `foo` header is present in request (e.g.: `curl -v http://localhost:8888/route-1 -H "foo: anything"`):
        - ratelimiting at 10 req/min
    - if `foo` header is present in request and value is `bar` (e.g.: `curl -v http://localhost:8888/route-1 -H "foo: bar"`)
       - the value of the hits addend is set to `5` (so effective ratelimiting is 2 req/min)

Le me know if your use case involves a different scenario.

<details>
<summary><code>docker-compose.yaml</code></summary>

```yaml
services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      - ratelimit-network
    volumes:
      - ./rls-config:/data/ratelimit/config
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

  envoy-proxy:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - "8888"
    ports:
      - "8888:8888"


  mock-service:
    image: envoyproxy/envoy-dev:latest
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node mock"
      - "--service-cluster mock"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level info"
    volumes:
      - ./mock-service.yaml:/etc/envoy/envoy.yaml
    networks:
      - ratelimit-network
    expose:
      - "9999"
    ports:
      - "9999:9999"

networks:
  ratelimit-network:
```

</details>

<details>
<summary><code>envoy.yaml</code></summary>

```yaml
static_resources:
  clusters:
  - name: ratelimit
    type: STRICT_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    protocol_selection: USE_CONFIGURED_PROTOCOL
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ratelimit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ratelimit
                port_value: 8081
  - name: mediawiki_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: mediawiki_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mock-service
                port_value: 9999
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8888
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress
          http_filters:
          - name: envoy.filters.http.ratelimit.mediawiki
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: rl
              request_type: external
              stage: 0
              rate_limited_as_resource_exhausted: true
              failure_mode_deny: false
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit
                transport_api_version: V3
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: route
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
              - name: route-with-specific-header-foo-value-bar
                match:
                  prefix: /route-1
                  headers:
                  - name: "foo"
                    string_match:
                      exact: bar
                typed_per_filter_config:
                  envoy.filters.http.ratelimit.mediawiki: # should match name use as the name of filter in filter chain
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimitPerRoute
                    rate_limits:
                    - hits_addend:
                        number: 5
                      actions:
                      - request_headers:
                          header_name: foo
                          descriptor_key: foo
                route:
                  cluster: mediawiki_cluster
                  rate_limits:
                    - actions:
                        - request_headers:
                            header_name: "foo"
                            descriptor_key: "foo"
              - name: route-with-specific-header-foo-value-any
                match:
                  prefix: /route-1
                  headers:
                  - name: "foo"
                    present_match: true
                route:
                  cluster: mediawiki_cluster
                  rate_limits:
                    - actions:
                        - request_headers:
                            header_name: "foo"
                            descriptor_key: "foo"
              - name: route-without-specific-header
                match:
                  prefix: /route-1
                route:
                  cluster: mediawiki_cluster
```

</details>

<details>
<summary><code>mock-service.yaml</code> (config for a mocked serviced)</summary>

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9999
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress
          route_config:
            name: ingress
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
                - match:
                    prefix: "/"
                  direct_response:
                    status: "200"
                    body:
                      inline_string: "Hello World"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

</details>

<details>
<summary>ratelimiting config: <code>example.yaml</code> (to be placed in `rls-config` folder</summary>

```yaml
---
domain: rl
descriptors:
  - key: foo
    rate_limit:
      unit: minute
      requests_per_unit: 10
```

</details>

**Comment by brightbyte** [comment]
@gcalmettes Thank you for the quick reply!

Here's my scenario: I want to be able to be able to assign different up-front costs to different routes, and I want to track the actual cost of the response (not route specific) based on the time spend in the backend. In my test setup I have a "fixed" hits_addend on the request and a "dynamic" hits_addend on the response (but neither of them works):

```
                      rate_limits:
                        # production example: https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/charts/api-gateway/templates/_api_gateway_routes.tpl#29
                        - actions:
                            - request_headers:
                                header_name: host
                                descriptor_key: host
                          hits_addend:
                            number: 2
                          stage: 0
                        - actions:
                            - request_headers:
                                header_name: host
                                descriptor_key: host
                          apply_on_stream_done: true
                          hits_addend:
                            format: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                          stage: 0
```

For testing I'm using per-host limits. In production they will be per-user (based on a JWT).

The "format" bit struck me as strange, but that's what the documentation seems to suggest...

EDIT: I notice that you are using envoyproxy/envoy-dev:latest. Do you know if this works in 1.33 or 1.34 as well?

**Comment by gcalmettes** [comment]
yes, `v1.33+` should work, as the ability to define dynamic hits_addend was added with [this PR](https://github.com/envoyproxy/envoy/pull/37548). (we are using 1.33 on our end in production, leveraging this feature).

I'll prepare a small config matching your specs as an example

**Comment by gcalmettes** [comment]
@brightbyte see the conf below. I sent a full example (including the docker compose with a new mock service to simulate slow response time) on your mediawiki email

```
static_resources:
  clusters:
  - name: ratelimit
    type: STRICT_DNS
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    protocol_selection: USE_CONFIGURED_PROTOCOL
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ratelimit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ratelimit
                port_value: 8081
  - name: mediawiki_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: mediawiki_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mock-service
                port_value: 80
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8888
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress
          http_filters:
          - name: envoy.filters.http.ratelimit.mediawiki_req
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: rl
              request_type: both
              stage: 0
              failure_mode_deny: false
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit
                transport_api_version: V3
          - name: envoy.filters.http.ratelimit.mediawiki_resp
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: rl
              request_type: both
              failure_mode_deny: false
              stage: 0
              enable_x_ratelimit_headers: DRAFT_VERSION_03
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit
                transport_api_version: V3
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: route
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
              - name: route-with-path-route-1
                match:
                  prefix: /sleep
                  headers:
                  - name: "host"
                    present_match: true
                typed_per_filter_config:
                  # ON REQUEST FLOW, FIXED HITS ADDEND
                  envoy.filters.http.ratelimit.mediawiki_req: # should match name use as the name of filter in filter chain
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimitPerRoute
                    rate_limits:
                    - hits_addend:
                        number: 5
                      actions:
                      - request_headers:
                          header_name: host
                          descriptor_key: host
                  # ON RESPONSE FLOW, DYNAMIC HITS ADDEND
                  envoy.filters.http.ratelimit.mediawiki_resp: # should match name use as the name of filter in filter chain
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimitPerRoute
                    rate_limits:
                    - hits_addend:
                        # format: "%RESP(x-envoy-upstream-service-time)%"
                        format: "%DURATION%"
                      apply_on_stream_done: true
                      actions:
                      - request_headers:
                          header_name: host
                          descriptor_key: host
                route:
                  cluster: mediawiki_cluster
                  rate_limits:
                  - actions:
                    - request_headers:
                        header_name: host
                        descriptor_key: host

```
