### ISSUE TITLE
Envoy server (v3 api) as Front-Edge proxy with http and https both

### ISSUE THREAD

**Issue by 2dev2** [envoyproxy/envoy#12965]
*We are running Envoy server [v1.15 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL](https://www.envoyproxy.io/docs/envoy/v1.15.0/version_history/current) on vm which serve the traffic for http and https both as Front Edge Proxy. We have two listener one for http and one for https.

1.We are able to get all the route for application and stats ```http://api.example.com/stats/prometheus``` for envoy working on non-tls port for http listener.

2.For https listener we have provided the path of letsencrypt self-signed certificated and configured according the [envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/sni#faq-how-to-setup-sni)
 Front Edge Proxy [example  in Envoy repo](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/front-envoy.yaml) uses the [v2 connection manger](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/front-envoy.yaml#L41), that why not able to configure it..

please find the config for same..
```yml
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          http_protocol_options:
            accept_http_10: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_envoy_admin_service
              domains:
              - "*"
              routes:
              - match:
                  path: "/stats/prometheus"
                route:
                  cluster: envoy_admin_service
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
                  timeout: 15s
          http_filters:
          - name: envoy.filters.http.router
  - name: listener_https
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names:
        - api.example.com
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: "/etc/letsencrypt/live/api.example.com/fullchain.pem"
              private_key:
                filename: "/etc/letsencrypt/live/api.example.com/privkey.pem"
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          use_remote_address: true
          http2_protocol_options:
            max_concurrent_streams: 100
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/var/log/envoy/access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - api.example.com
              routes:
              - match:
                  path: "/stats/prometheus"
                route:
                  cluster: envoy_admin_service
              - match:
                  path: "/"
                route:
                  cluster: local_service
      http_filters:
      - name: some.customer.filter
      - name: envoy.filters.http.router
  clusters:
  - name: envoy_admin_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy_admin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9901
  - name: local_service
    connect_timeout: 15s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8081
```
If https request comes, it should do the downstream TLS termination and forward non-tls request to desired upstream cluster. 
We have reached out to [stackoverflow](https://stackoverflow.com/questions/63712716/envoy-server-v3-api-with-http-and-https-both) also.
Please help us to figure it out what we are missing for HTTPS configuration
