### ISSUE TITLE
 envoy_on_request: respond() cannot be called if headers have been continued

### ISSUE THREAD

**Issue by linxuyalun** [envoyproxy/envoy#12985]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *respond() cannot be called if headers have been continued*

*Description*:
>Describe the issue.
I am configuring EnvoyFilter in istio, what I wanna do is:
1. get the method and body of the request
2. copy them and paste them into httpCall
3. DO SOMETHING
But when I apply this file, I always get ` script log: [string "function envoy_on_request(request_handle)..."]:36: respond() cannot be called if headers have been continued` error and have no idea how to resolve it.

Here is my yaml file:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-lua
spec:
  workloadSelector:
    labels:
      app: httpbin-callee
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
           function envoy_on_request(request_handle)
             -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
             local requestMethod = request_handle:headers():get(":method")
             local requestPath = request_handle:headers():get(":path")
             local requestAuthorization = request_handle:headers():get("authorization")
             local index = 0
             for chunk in request_handle:bodyChunks() do
               local len = chunk:length()
               result = chunk:getBytes(index, len)
               index = index + len

               request_handle:logDebug(result)

               -- Make an HTTP call.
               headers, body = request_handle:httpCall(
               "auth-server",
               {
                [":method"] = requestMethod,
                [":path"] = requestPath,
                [":authority"] = "httpbin-auth.default.svc.cluster.local",
                ["authorization"] = requestAuthorization
               },
               result,
               5000)
            end
             print("-result--")
             print(result)
             print("---Get all headers---")
             originhead = request_handle:headers()
             for key, value in pairs(originhead) do
               print('\t', key, value)
             end
             print("-x-header status---")
             print(headers[":status"])
             if (headers[":status"] ~= "200")
             then
               request_handle:respond(
                 {
                  [":status"] = "403",
                  ["content-type"] = "application/json;charset=UTF-8"
                 },
                 result)
             end
           end
  # The second patch adds the cluster that is referenced by the lua code
  # cds match is omitted as a new cluster is being added
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value: # cluster specification
        name: "auth-server"
        type: STRICT_DNS
        connect_timeout: 5s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            protocol: TCP
            address: "httpbin-auth.default.svc.cluster.local"
            port_value: 80
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by linxuyalun** [comment]
I also try another method(handle:body()) to get the content of body, which configure file is:
```yaml
inlineCode: |
           function envoy_on_request(request_handle)
             -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
             local requestMethod = request_handle:headers():get(":method")
             local requestPath = request_handle:headers():get(":path")
             local requestAuthorization = request_handle:headers():get("authorization")
             local requestBody = request_handle:body()
             local requestBodyString = tostring(requestBody)
             local headers, body = request_handle:httpCall(
              "auth-server",
              {
               [":method"] = requestMethod,
               [":path"] = requestPath,
               [":authority"] = "httpbin-auth.default.svc.cluster.local",
               ["authorization"] = requestAuthorization
              },
             requestBodyString,
             5000)
             print("--Get all headers---")
             originhead = request_handle:headers()
             for key, value in pairs(originhead) do
               print('\t', key, value)
             end
             print(headers[":status"])
             if (headers[":status"] ~= "200")
             then
               request_handle:respond(
                 {
                  [":status"] = "403",
                  ["content-type"] = "application/json;charset=UTF-8"
                 },
                 requestBodyString)
             end
           end
```
However, the body content is a userdata like `userdata: 0x41c8c448` and I can't get the real data.

**Comment by snowp** [comment]
@dio Mind taking a look?

**Comment by linxuyalun** [comment]
Hi, I solved the problem, I use the buffer:getBytes() and finally figure it out.

Here is my configuration:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-lua
spec:
  workloadSelector:
    labels:
      app: httpbin-callee
  configPatches:
    # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 80
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.config.filter.http.lua.v2.Lua"
         inlineCode: |
           function envoy_on_request(request_handle)
             -- Make an HTTP call to an upstream host with the following headers, body, and timeout.
             local requestMethod = request_handle:headers():get(":method")
             local requestPath = request_handle:headers():get(":path")
             local requestAuthorization = request_handle:headers():get("authorization")
             local requestBodyBuffer = request_handle:body()
             local requestBodyData = requestBodyBuffer:getBytes(0, requestBodyBuffer:length())
             headers, body = request_handle:httpCall(
             "auth-server",
             {
              [":method"] = requestMethod,
              [":path"] = requestPath,
              [":authority"] = "httpbin-auth.default.svc.cluster.local",
              ["authorization"] = requestAuthorization
             },
             requestBodyData,
             5000)

```
