### ISSUE TITLE
Using healthchecks to determine down upstream hosts

### ISSUE THREAD

**Issue by aqua777** [envoyproxy/envoy#12997]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Using healthchecks to determine down upstream hosts*

*Description*:

I am currently researching possibility of using Envoy as a gateway proxy for the environment consisting of multiple services. Each service would have distinct URL prefix and will be served by corresponding pool of service nodes. 
I started looking into Envoy's documentation and I also followed some of the scenarios on Try Envoy page: https://www.envoyproxy.io/try/
In particular I was interested in checking how Envoy handles detection of available service nodes using health checks: https://www.envoyproxy.io/try/detecting-service-health-with-healthchecks. I went through this scenario step by step, started Envoy and two test service nodes, was able to send several successful requests through Envoy, then triggered one of service nodes to pretend to be unhealthy, send some more requests and observed how initial request returned with errors and how some time later the unhealthy node was removed from pool of nodes. All worked as described in scenario.

I tried to replay this scenario on my own dev machine. Here is my configuration file:
```
admin:
    access_log_path: /tmp/admin_access.log
    address:
      socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
    listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            codec_type: auto
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: backend
                domains:
                  - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: targetCluster
            http_filters:
            - name: envoy.router
    clusters:
    - name: targetCluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      hosts: [
        { socket_address: { address: 172.18.0.3, port_value: 80 }},
        { socket_address: { address: 172.18.0.4, port_value: 80 }},
        { socket_address: { address: 172.18.0.5, port_value: 80 }},
        { socket_address: { address: 172.18.0.6, port_value: 80 }},
      ]
      health_checks:
        - timeout: 1s
          interval: 1s
          interval_jitter: 1s
          unhealthy_threshold: 1
          healthy_threshold: 1
          http_health_check:
            path: "/health"
```
It is slightly modified version of config file from the scenario mentioned above, with 4 service nodes instead of 2 and with enabled Admin interface. I also modified health checks times and set all thresholds to 1 and all time values to 1s.
Next I started Envoy proxy and one test node:
```
$ docker run -d --name envoy -p 8080:8080 -p 9901:9901 -v /Users/i512296/Samples/Envoy:/etc/envoy -e loglevel=debug envoyproxy/envoy:v1.14-latest
5f1a7c1f765ea87caf6e407ddd1770fe86041320b55460695631e7f742bca347

$ docker run -d katacoda/docker-http-server:healthy
03166c245fcb23fe4cecfec64abaf82a3bb09127ecc8a1a67b7a37a74083c3df

$ docker ps -a
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                       NAMES
03166c245fcb        katacoda/docker-http-server:healthy   "/app"                   2 minutes ago       Up 2 minutes        80/tcp                                                      quirky_gagarin
5f1a7c1f765e        envoyproxy/envoy:v1.14-latest         "/docker-entrypoint.…"   2 minutes ago       Up 2 minutes        0.0.0.0:8080->8080/tcp, 0.0.0.0:9901->9901/tcp, 10000/tcp   envoy
```
Then I stared endless loop of requests which produced this output:
```
$ while true; do curl http://localhost:8080/; echo; sleep 1; done
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
<h1>A healthy request was processed by host: 03166c245fcb</h1>

upstream connect error or disconnect/reset before headers. reset reason: connection failure
<h1>A healthy request was processed by host: 03166c245fcb</h1>

upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
<h1>A healthy request was processed by host: 03166c245fcb</h1>

upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
<h1>A healthy request was processed by host: 03166c245fcb</h1>

upstream connect error or disconnect/reset before headers. reset reason: connection failure
upstream connect error or disconnect/reset before headers. reset reason: connection failure
...
```

It appears to me that Envoy is sending requests to the nodes which aren't available, haven't been started yet. So I used Admin interface to check for cluster's health:
```
$ curl -s localhost:9901/clusters | grep health
targetCluster::172.18.0.3:80::health_flags::healthy
targetCluster::172.18.0.4:80::health_flags::/failed_active_hc
targetCluster::172.18.0.5:80::health_flags::/failed_active_hc
targetCluster::172.18.0.6:80::health_flags::/failed_active_hc
```
It looks like Envoy knows that only one service node is healthy and other 3 failed their health checks but it keeps forwarding requests to those unavailable nodes anyway. I left my request loop running for considerable time and those connection failure errors never disappeared.

When I started another node it still didn't help and I still could see connection failure errors. Situation improved when I started third service node, then connection failure disappeared. However if I terminate those two nodes which I started before and leave only one node running then the situation returns and I can see connection failure errors again.

Did I make some configuration mistakes here or am I missing something?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
