### ISSUE TITLE
No regexp for UDP prometheus stats

### ISSUE THREAD

**Issue by bartebor** [envoyproxy/envoy#13021]
*Title*: There is no default regexp to extract UDP statistics

*Description*:
Envoy emits prometheus statistics like this:
```
# TYPE envoy_udp_custom_14553_udp_downstream_sess_rx_bytes counter
envoy_udp_custom_14553_udp_downstream_sess_rx_bytes{} 0
```
while it should extract stat prefix and store it in a label:
```
# TYPE envoy_udp_downstream_sess_rx_bytes counter
envoy_udp_downstream_sess_rx_bytes{envoy_udp_prefix="custom-14553-udp"} 0
```
It works as expected for TCP listeners.

As a workaround one can supply custom regex:
```
stats_config:
  stats_tags:
    - regex: "^udp\\.((.*?)\\.)\\w+?$"
      tag_name: envoy.udp.prefix
```
but it would be better to add this to `well_known_names.cc`, just like for TCP.
