### ISSUE TITLE
how to configuration RDS with Independent file ？

### ISSUE THREAD

**Issue by kasini3000** [envoyproxy/envoy#13049]
*Title*: *how to configuration RDS with file？*

*Description*:

i use file base dynamic configuration with LDS
```
{
    "version_info": "0",
    "resources": [
        {
            "@type": "type.googleapis.com/envoy.api.v2.Listener",
            "name": "listener_0",
            "address": {
                "socket_address": {
                    "address": "0.0.0.0",
                    "port_value": 10000
                }
            },
            "filter_chains": [
                {
                    "filters": [
                        {
                            "name": "envoy.http_connection_manager",
                            "config": {
                                "stat_prefix": "ingress_http",
                                "codec_type": "AUTO",
                                "route_config": {
                                    "name": "local_route",
                                    "virtual_hosts": [
                                        {
                                            "name": "local_service",
                                            "domains": [
                                                "*"
                                            ],
                                            "routes": [
                                                {
                                                    "match": {
                                                        "prefix": "/"
                                                    },
                                                    "route": {
                                                        "cluster": "targetCluster"
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                "http_filters": [
                                    {
                                        "name": "envoy.router"
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
} 
```
# how to configuration RDS with Independent file ？
Looks like there is no “path“ attribute in the route_config?
i mean:
```
"route_config":
  path: "/etc/envoy/rds1.json"

```

Can you give an example?

#  ------------
## https://www.envoyproxy.io/docs/envoy/v1.14.4/configuration/overview/extension

```
name: front-http-proxy
typed_config:
  "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
  stat_prefix: ingress_http
  codec_type: AUTO
  rds:
    route_config_name: local_route
    config_source:
      api_config_source:
        api_type: GRPC
        grpc_services:
          envoy_grpc:
            cluster_name: xds_cluster
  http_filters:
  - name: front-router
    typed_config:
      "@type": type.googleapis.com/envoy.config.filter.http.router.v2.Router
      dynamic_stats: true
```

**Comment by htuch** [comment]
The path should be placed in the `config_source`, e.g.
```
  rds:
    route_config_name: local_route
    config_source:
      path: /some/rds.json
```
