### ISSUE TITLE
send request to another upstream after retries

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#13119]
*Title*: *send request to another upstream after retries*

*Description*:
I have a listener at port 8080 and I have the following retry policy 
```
                     retry_policy:
                        retry_on: 5xx,retriable-4xx,connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,reset,gateway-error,retriable-status-codes
                        num_retries: 2
                        per_try_timeout: 6s
                        retry_back_off:
                          base_interval: "2s"
                          max_interval: "5s"
```

is there a way that after all retries if still getting an error, send the error output of the request to another upstream cluster which has an API that concentrates all errors?
