### ISSUE TITLE
clang_tidy failure gcc/clang

### ISSUE THREAD

**Issue by asraa** [envoyproxy/envoy#13162]
clang_tidy is using GCC instead of clang 10 and is running into CI failures

https://dev.azure.com/cncf/envoy/_build/results?buildId=51547&view=logs&j=3bf5ec37-bb6f-5fb6-2cf1-5134dc6106d6&t=41d571fe-3811-578d-07de-68468f467dae

```
  DiagnosticName: clang-diagnostic-error
  Notes:
  - FileOffset: 12459
    FilePath: /usr/lib/gcc/x86_64-linux-gnu/9/include/xmmintrin.h
    Message: '''__builtin_ia32_cmpnleps'' declared here'
    Replacements: []
- DiagnosticMessage:
    FileOffset: 19280
    FilePath: /usr/lib/gcc/x86_64-linux-gnu/9/include/xmmintrin.h
    Message: use of undeclared identifier '__builtin_ia32_cvtsi2ss'; did you mean
      '__builtin_ia32_cvtsd2ss'?

```
