### ISSUE TITLE
Lots of 503 Errors after adding retries

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#13170]
Hi, we have been using Envoy for a while now and have always seen a small amount of 503s occurring with the **UF** flag. We could not figure out the root cause of these errors so we decided to mitigate them by adding route level retries on the "connect-failure" condition (Envoy will attempt a retry if a request is failed because of a connection failure to the upstream server (connect timeout, etc.). (Included in 5xx)).

After one load test it seemed like the retries had done their job as we saw much less errors reported. However, after our latest test we saw an increase in overall 503s and some flags we had not seen before: 

UF, **URX**: The request was rejected because the upstream retry limit (HTTP) or maximum connect attempts (TCP) was reached.
**LR**: Connection local reset in addition to 503 response code.
UF, **UO**: Upstream overflow (circuit breaking) in addition to 503 response code.
**UC**: Upstream connection termination in addition to 503 response code.

The UF, URX I understand as it means even after retries, the request did not succeed and we got those errors. The others however we did not expect and I'm not sure why they are popping up now. I can't seem to find much more information about these flags anywhere so I am not sure how they are related to the addition of retries.

So basically does anyone have ideas on why these errors might be occurring, after the addition of retries? 

Part of our Envoy config below:
```
static_resources:
  listeners:
  - name: xxx
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    traffic_direction: INBOUND
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: xxx
          server_name: "xxx"
          server_header_transformation: OVERWRITE
          access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: "xxx"
                format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\"
                  %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
                  %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(USER-AGENT)%\"
                  \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
          request_timeout: 300s
          route_config:
            name: xxx
            virtual_hosts:
            - name: xxx
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  timeout: 0s
                  idle_timeout: 300s
                  cluster: xxx
                  retry_policy:
                    retry_on: connect-failure
                    num_retries: 3
                decorator:
                  operation: xxx
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config: 
              "@type": type.googleapis.com/envoy.config.filter.http.jwt_authn.v2alpha.JwtAuthentication
              providers:
                xxx:
                  issuer: "xxx"
                  remote_jwks:
                    http_uri:
                      uri: "xxx"
                      cluster: jwks_cluster
                      timeout: 5s
                    cache_duration:
                      seconds: 2592000 # 30 days
                  forward: true
                  forward_payload_header: x-jwt-payload
                  payload_in_metadata: "jwt_payload"
                  from_headers:
                    - name: authorization
                      value_prefix: "Bearer "
              rules:
                - match:
                    prefix: /
                  requires:
                    requires_any:
                      requirements:
                        - provider_name: xxx
                        - allow_missing_or_failed: {}
          - name: envoy.filters.http.ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              stage: 0
              domain: xxx
              failure_mode_deny: false
              timeout: 0.25s
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: rate_limit_service
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              suppress_envoy_headers: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: [ "h2,http/1.1" ]
            tls_certificates:
              - certificate_chain: { filename: "xxx" }
                private_key: { filename: "xxx" }
            validation_context:
              trusted_ca: { filename: "xxx" }
  clusters:
  - name: xxx
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: xxx
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost.ssl
                port_value: 8443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca: { filename: "xxx" }
```
