### ISSUE TITLE
Question: how to use multiple TLS certificates (ECDSA/RSA) in conjunction with SDS?

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#13226]
I have a transport socket that uses SDS to retrieve it's TLS certificate

If I return 2 TLS certificates in the SDS response (one being ECDSA, the other being RSA) envoy fails to load the config with the error: 
> secrets rejected: Unexpected SDS secrets length: 2

**Example**

```javascript
{
   "version_info": "42",
   "resources":[
      {
         "name":"RSA certificate",
         "tls_certificate":{
            "certificate_chain":{
               "inline_string":"foo"
            },
            "private_key":{
               "inline_string":"bar"
            }
         }
      },
      { // <-- not allowed
         "name":"ECDSA certificate",
         "tls_certificate":{
            "certificate_chain":{
               "inline_string":"foo"
            },
            "private_key":{
               "inline_string":"bar"
            }
         }
      }
   ]
}
```

Alternatively, if I specify a second item in `tls_certificate_sds_secret_configs`, envoy responds with a similar error

**Example**

```yaml
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
            common_tls_context:
              tls_certificate_sds_secret_configs:
                - name: "ECDSA certificate"
                  sds_config:
                    api_config_source:
                      api_type: REST
                      cluster_names: [xds]
                      refresh_delay: 900s
                      request_timeout: 30s
                - name: "RSA certificate"  # <-- not allowed
                  sds_config:
                    api_config_source:
                      api_type: REST
                      cluster_names: [xds]
                      refresh_delay: 900s
                      request_timeout: 30s
              tls_params: ...
              alpn_protocols: h2,http/1.1
```

Is there a way to do this with SDS, or do I need to inline the certs in the listener configuration instead?

**Relevant documentation**

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#arch-overview-ssl-cert-select
