### ISSUE TITLE
no_traffic_edge_interval

### ISSUE THREAD

**Issue by Chuongv** [envoyproxy/envoy#13246]
# Feature request for no_traffic_edge_interval

## Description:

We have a setup where we have two envoys pointing to the same cluster. At the moment we have traffic routing to only one of the envoy instances. What is problematic is that we have `no_traffic_interval` set to 100ms. Which is great when we only have one envoy instance, since when a cluster is first up, we want to check to ensure it is healthy before any requests goes upstream. But when we only have traffic going to one envoy instance, the other envoy will be spamming the cluster every 100ms thinking that there has been no traffic.

We could increase the `no_traffic_interval` to something reasonable like 1 second to reduce the spam, however if once there is traffic coming over, from what I understand, envoy will hold onto the request before letting it go upstream which leads to slower latency?

## Proposed solution

Add a `no_traffic_edge_interval` that specifies the interval to run the health check after a cluster is marked healthy during the `no_traffic_interval` stage

**Comment by yanavlasov** [comment]
I'm unsure why you think that longer `no_traffic_interval` would cause initial requests to be delayed. The first host check is sent immediately when a cluster is loaded. Yes, the requests may be queued until health check response comes back and cluster fully warms up, but this time is not affected by the `no_traffic_interval`. In fact the `no_traffic_interval` is used specifically to reduce the spam from Envoy's that have not yet seen any traffic, so making it shorter than the `interval` is not using it right.

@snowp in case I'm not right on some points.

**Comment by Chuongv** [comment]
So my thinking is this.


1. Envoy starts Up
2. Envoy sends HC to Cluster
3. HC fails since the cluster is not up yet
4. Envoy will wait no_traffic_interval to HC
5. Cluster starts up
6. Request comes into Envoy but since the last HC has failed, we don't send the request and will have to wait for the `no_traffic_interval` to complete before running the next HC

Let me see if I can repro to make sure my understanding is correct.

**Comment by Chuongv** [comment]
> I'm unsure why you think that longer no_traffic_interval would cause initial requests to be delayed. 
Actually sorry that is an implementation filter on our end.

However I expected that without our filter, Envoy would either fail the request immediately or send a HC before sending off the first request if the cluster is marked unhealthy.

So perhaps i am misunderstanding the purpose of health checks. 

Here is what happens.

1. Envoy Starts up
2. Envoy sends HC to cluster and fails

```
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8081}},"cluster_name":"worker_endpoint","health_check_failure_event":{"failure_type":"NETWORK","first_check":true},"timestamp":"2020-09-24T17:36:26.896Z"}
```
3. Envoy will wait `no_traffic_interval` to do the next HC
4. The cluster starts up
5. I curl envoy and receive a 200

I expect in step #5 that we fail the request.

Current config that I am using

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: {
        address: 127.0.0.1,
        port_value: 8080
      }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          stream_idle_timeout: 3600s
          http_protocol_options:
            enable_trailers: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: worker_endpoint
                  timeout: 300s
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: worker_endpoint
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: worker_endpoint
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8081
    health_checks:
      - no_traffic_interval: 100s
        timeout: 60s
        healthy_threshold: 1
        tcp_health_check: {}  # empty payload indicates envoy will perform "connect only" TCP health checking.
        interval: 86400s
        unhealthy_interval: 86400s
        unhealthy_threshold: 1
        always_log_health_check_failures: true
        event_log_path: "/tmp/envoy_hc.txt"
```
