### ISSUE TITLE
Fix sampling for child spans when using opencensus trace provider

### ISSUE THREAD

**Issue by RashmiRam** [envoyproxy/envoy#13267]
*Title*: Fix sampling for child spans when using Opencensus trace provider via https://github.com/envoyproxy/envoy/blob/v1.15.0/api/envoy/config/trace/v3/opencensus.proto

*Description*:
Opencensus trace provider honors envoy's trace sampling decision. But, there is an pending issue at their end https://github.com/census-instrumentation/opencensus-cpp/issues/294 where the child span will always be sampled even if the parent span is not sampled. This leads to lots of orphan child spans which results in confusion.

When parent span is not sampled, child span will fall back either to the sampler present in [startSpanOptions](https://github.com/census-instrumentation/opencensus-cpp/blob/v0.4.0/opencensus/trace/internal/span.cc#L118) sent along while calling startSpan method OR to the default sampler configured at Opencensus [traceOptions](https://github.com/census-instrumentation/opencensus-cpp/blob/v0.4.0/opencensus/trace/internal/trace_config_impl.cc#L30)

 IMO, there are 2 ways to solve this.

1. Opencensus provides a way to configure the default sampler in traceOptions which envoy can expose in their config 
2. While creating a child span at envoy side, we can send the startSpanOptions with the sampler set accordingly as parent span's tracing decision.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by RashmiRam** [comment]
Among the mentioned solutions, the 1st one where we can configure the traceOptions of Opencensus through envoy is already existing. 

trace_config mentioned in this proto https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/opencensus.proto can be configured like below to avoid orphan child spans showing up in UI

``` yaml
<<elided>>
tracing:
  provider:
    name : envoy.tracers.opencensus
      typed_config:
        "@type": type.googleapis.com/envoy.config.trace.v3.OpenCensusConfig
        trace_config:
          constant_sampler:
            decision: ALWAYS_OFF #See issue: https://github.com/census-instrumentation/opencensus-cpp/issues/294
<<elided>>
```
We can close this issue if the above is an accepted solution.
