### ISSUE TITLE
How not to route to just discovered host?

### ISSUE THREAD

**Issue by alkapov** [envoyproxy/envoy#13319]
Hi. I have an envoy proxy with service (ssss). So, when the ssss opens a socket on port 85 it can't handle incoming requests (they gonna be failed on timeout), because it needs some time to initialize after forks. That's why I've tried to add the health checks, but they don't work. At the moment when the socket is opened, envoy route requests to the ssss, and after ~100ms (2 pings failed pings) it starts return 503 as needed.

What's the problem? v1.14.4 Here is the config

```yaml
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: "::"
      ipv4_compat: true
      port_value: 9901
static_resources:
  listeners:
    - name: "ssss_proxy"
      address:
        socket_address:
          address: "::"
          ipv4_compat: true
          port_value: 84
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: ssss
                            retry_policy:
                              num_retries: 0
                http_filters:
                  - name: envoy.filters.http.health_check
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                      pass_through_mode: false
                      cluster_min_healthy_percentages:
                        ssss:
                          value: 100
                      headers:
                        - name: ":path"
                          exact_match: "/ping"
                  - name: envoy.router
  clusters:
    - name: ssss
      connect_timeout: 0.05s
      type: LOGICAL_DNS
      dns_lookup_family: AUTO
      lb_policy: ROUND_ROBIN
      common_lb_config:
        ignore_new_hosts_until_first_hc: true
      close_connections_on_host_health_failure: true
      hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 85
      health_checks:
        - timeout: 0.04s
          interval: 0.05s 
          unhealthy_threshold: 2
          healthy_threshold: 20
          no_traffic_interval: 0.04s
          http_health_check:
            path: "/ping"
```
