### ISSUE TITLE
[Question] connection termination

### ISSUE THREAD

**Issue by hakuno** [envoyproxy/envoy#13377]
Greetings!

My settings are based on Failover setup.

I've two nodes behind the proxy. The primary node (in active mode) and secondary one (in passive mode).

```
  clusters:
  - name: intranet
    connect_timeout: 5s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.aggregate
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
        clusters:
          - active
          - passive
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 500000
          max_requests: 500000
        - priority: HIGH
          max_connections: 500000
          max_requests: 500000
```

with

```
  - name: XYZ
    connect_timeout: 5s
    per_connection_buffer_limit_bytes: 32768
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: XYZ
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: XYZ
                port_value: 808
            health_check_config:
              port_value: 80
    health_checks:
      timeout: 5s
      unhealthy_threshold: 1
      healthy_threshold: 2
      interval: 15s
      http_health_check: { path: "/", expected_statuses: { start: 200, end: 304 } }
```

The upstream nodes are IIS web servers.

The problem is: sometimes I got unknown problems. I don't know why it returns:

`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Yes. I found there's some downstream member down in order of seconds.

My listener has

```
          common_http_protocol_options:
            idle_timeout: 3600s
          stream_idle_timeout: 0s
          request_timeout: 0s
```

cluster

```
connect_timeout: 5s
```

and their healthcheck

```
timeout: 5s
```

What's the problem?

My timeout is too short?

The primary upstream node has been DOWN for sure?

I need to understand how to overcome this

`upstream connect error or disconnect/reset before headers. reset reason: connection termination`

Thanks in advance!

---

BTW what's the difference between `"eject_unhealthy_event":{"failure_type":"NETWORK"}` and `"eject_unhealthy_event":{"failure_type":"ACTIVE"}` ?
