### ISSUE TITLE
Ability to set service cluster via ENV

### ISSUE THREAD

**Issue by roboslone** [envoyproxy/envoy#13441]
*Description*:
It would be useful to be able to set service cluster via ENV, not via CLI option.
I'm using pre-built Docker image and my global Dockerfile looks something like this:
```
FROM envoyproxy/envoy-alpine:v1.15.2

COPY envoy.yaml /etc/envoy/envoy.yaml
```

This image is used as sidecar for multiple services. Each service should have it's own name and in Kubernetes it would be achieved easily if Envoy supported service cluster setting via env variable.

For example, deployment description would look like this:
```
kind: Deployment
...
    containers:
    - name: my-app
       ...
    - name: envoy-sidecar
       env:
       - { name: ENVOY_SERVICE_CLUSTER, value: envoy_my_app }
```

This would also make stats collection easier for the same reasons.
