### ISSUE TITLE
question: How to get client IP and custom headers in Lua filter

### ISSUE THREAD

**Issue by nic-chen** [envoyproxy/envoy#13457]
I am developing a framework that support Apache APISIX plugins run directly in Envoy Lua filter without modify Envoy. #13307

But in the process, I found that some header values, such as client IP and custom headers, cannot be get in Lua filter.

I think client IP and custom headers should be very commonly used. 

I might misreading/misunderstanding, but I don't know how to get them, please remind me, thank you !

**Comment by dio** [comment]
> I found that some header values, such as client IP and custom headers, cannot be get in Lua filter.

Sorry, do you mean you have this information available on headers but it is not there when you tried to access it?

FWIW, I think the information is available here: https://github.com/envoyproxy/envoy/blob/319a9a647f19036d831a75f68350c90e98bfc365/include/envoy/stream_info/stream_info.h#L474-L479 However, yes currently we have the [StreamInfo](https://github.com/envoyproxy/envoy/blob/319a9a647f19036d831a75f68350c90e98bfc365/source/extensions/filters/http/lua/wrappers.h#L181) wrapper but not all information is accessible from Lua script.

**Comment by nic-chen** [comment]
> Sorry, do you mean you have this information available on headers but it was not there when you tried to access it?

I reconfirmed that the custom headers are available by `handle:headers()`, sorry about that.

> However, yes currently we have the [StreamInfo](https://github.com/envoyproxy/envoy/blob/319a9a647f19036d831a75f68350c90e98bfc365/source/extensions/filters/http/lua/wrappers.h#L181) wrapper but not all information is accessible from Lua script.

It seems that only `protocol`, `dynamicMetadata` and `downstreamSslConnection` are exposed.
Would We export `downstreamRemoteAddress` to Lua filter ?  😃

**Comment by dio** [comment]
@nic-chen sure. I think this is a good exercise for a new contributor. Do you want to try? I can try to help with providing guidance and review. Here is a complete (well missing docs) patch to expose downstream local address: https://github.com/envoyproxy/envoy/compare/master...dio:lua-streaminfo-addresss?expand=1.

**Comment by nic-chen** [comment]
> @nic-chen sure. I think this is a good exercise for a new contributor. Do you want to try? I can try to help with providing guidance and review. Here is a complete (well, it's still missing docs) patch to expose downstream local address: https://github.com/envoyproxy/envoy/compare/master...dio:lua-streaminfo-addresss?expand=1.

Wow, so nice you are!

I have always used JAVA, PHP, GO, Lua, JavaScript to work, and have never used C++.

But I would like to try it out and learn, hoping to contribute more in the future.

**Comment by nic-chen** [comment]
> @nic-chen sure. I think this is a good exercise for a new contributor. Do you want to try? I can try to help with providing guidance and review. Here is a complete (well, it's still missing docs) patch to expose downstream local address: https://github.com/envoyproxy/envoy/compare/master...dio:lua-streaminfo-addresss?expand=1, you can then add more getters to StreamInfoWrapper as you wish 🙂.

Do you mind if I push directly to your repo? Or should I submit the code on my repo? Then create a pr.
Thanks !

**Comment by dio** [comment]
@nic-chen I think I prefer for you to work on your own repo. Please note that the patch that I have exposes downstream local address, which probably not what you want. You can of course expose more, since the pattern will be the same (the remote ones: `downstreamRemoteAddress()`, `downstreamDirectRemoteAddress()`, etc). 

Have you successfully built envoy on your local? Please let me know if you have any issues.

You can follow the official docs https://github.com/envoyproxy/envoy/blob/8a1d44422ba9ffa303c89b109b57e8889655b53a/bazel/README.md#building-envoy-with-bazel on building it, or the short one here (if you're on Linux (Debian-based) and want to use clang): https://gist.github.com/dio/9a7c826a2dbf004a81112db0d167d209.

**Comment by nic-chen** [comment]
@dio 
OK. Thanks so much.

I will try to build and make some test.

It may take some time. There should be issues in this process that need your help, if so, I will ping you here. : )

**Comment by nic-chen** [comment]
@dio 

I works on macOS, so took some time to build..

I think i could submit a pr today or tomorrow.

**Comment by Blitss** [comment]
In case anyone is looking for a solution on how to populate `x-real-ip` header with real client IP address, here's the complete solution which works for me with GKE load balancer.

First, patch the load balancer:
`kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'`

Then apply the envoy filter:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: set-remote-address-and-hops
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: ANY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            use_remote_address: true
            xff_num_trusted_hops: 1
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-x-real-ip-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inlineCode: |
              function envoy_on_request(request_handle)
                request_handle:headers():replace("x-real-ip", request_handle:headers():get("x-envoy-external-address"))
              end
```
I tried to use `downstreamDirectRemoteAddress` instead of `x-envoy-external-address` but that doesn't work in case client passes malformed `x-forwarded-for` header.
