### ISSUE TITLE
why Envoy striped out cookie with name "SERVER" from response?

### ISSUE THREAD

**Issue by xudesheng** [envoyproxy/envoy#13459]
I'm trying to use Envoy as edge proxy and replace Haproxy. My backend service specifically needs a cookie value with name:SERVER. However, it seems like Envoy automatically stripped out this cookie.

With **Haproxy**, when user accesses url: /Application, the response would set cookie with name "SERVER" at path: /
![image](https://user-images.githubusercontent.com/8742037/95548720-ad967400-09d3-11eb-8a49-b6c355cf18a8.png)

With **Envoy**, to same URL, "set cookie" was removed but a new header was added.
![image](https://user-images.githubusercontent.com/8742037/95548738-b7b87280-09d3-11eb-91a3-1f156426d968.png)

With **Haproxy**, next step, url /Application would move to (302) /Application/HOME, service will set new cookie with name "JSESSIONID" at path /Application
![image](https://user-images.githubusercontent.com/8742037/95548797-d6b70480-09d3-11eb-9cc9-8129a1e4bac5.png)

With Envoy, next step, it seems like cookie with "JSESSIONID" is acceptable but cookie with name "SERVER" was missed still.
![image](https://user-images.githubusercontent.com/8742037/95548941-2b5a7f80-09d4-11eb-89d3-8e9445220d6b.png)

```
overload_manager:
    refresh_interval: 0.25s
    resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      typed_config:
        "@type": type.googleapis.com/envoy.config.resource_monitor.fixed_heap.v2alpha.FixedHeapConfig
        max_heap_size_bytes: 2147483648 # 2 GiB
    actions:
    - name: "envoy.overload_actions.shrink_heap"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.95
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.98

static_resources:
    listeners:
    - address:
        socket_address:
            address: 0.0.0.0
            port_value: 8080
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: auto
            use_remote_address: true
            xff_num_trusted_hops: 2
            common_http_protocol_options:
                idle_timeout: 3600s # 1 hour
                headers_with_underscores_action: REJECT_REQUEST
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: application9
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/Application/WS"
                  route:
                    cluster: wsserver
                    hash_policy:
                      - cookie: {name: SERVER}
                    upgrade_configs:
                      upgrade_type: websocket
                      enabled: true
                - match:
                    prefix: "/Application"
                  route:
                    cluster: application
                    hash_policy:
                      - cookie: {name: SERVER}
            http_filters:
            - name: envoy.filters.http.router
              typed_config: {}

    
    clusters:
    - name: application
      connect_timeout: 15s
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      type: static
      lb_policy: round_robin
      health_checks:
        - timeout: 15s
          interval: 30s
          http_health_check:
            path: "/Application/readytogo"
          unhealthy_threshold: 1
          healthy_threshold: 1
      load_assignment:
        cluster_name: application
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 10.100.0.18
                  port_value: 8080
          - endpoint:
              address:
                socket_address:
                  address: 10.100.0.19
                  port_value: 8080
    - name: wsserver
      connect_timeout: 15s
      type: static
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      lb_policy: round_robin
      health_checks:
        - timeout: 15s
          interval: 30s
          http_health_check:
            path: "/"
          unhealthy_threshold: 1
          healthy_threshold: 1
      load_assignment:
        cluster_name: wsserver
        endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.100.0.20
                    port_value: 8080
            - endpoint:
                address:
                  socket_address:
                    address: 10.100.0.21
                    port_value: 8080

layered_runtime:
    layers:
        - name: static_layer_0
          static_layer:
            envoy:
                resource_limits:
                    listener:
                        example_listener_name:
                            connection_limit: 10000
            overload:
                global_downstream_max_connections: 50000
```
