### ISSUE TITLE
How to add cookie to response if a cookie is missed in request?

### ISSUE THREAD

**Issue by xudesheng** [envoyproxy/envoy#13466]
*Title*: *How to add cookie to response if a cookie is missed in request?*

*Description*:
> I need a cookie with name "SERVER" to present in each request header and the value of this "SERVER" key would be either IP:port of upstream machine or Hostname of upstream machine.

I try to follow examples in [Envoy Header-To-Metadata Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter) and here is my envoy.yaml
```
      - match:
                  prefix: "/Application"
                route:
                  cluster: application
                  hash_policy:
                    - cookie: {name: SERVER}
                typed_per_filter_config:
                  envoy.filters.http.header_to_metadata:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
                    request_rules:
                      - cookie: SERVER
                        on_header_missing:
                          key: SERVER
                          value: "%UPSTREAM_REMOTE_ADDRESS%"
```
but envoy complains: **Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(request_rules[0]) cookie: Cannot find field.) has unknown fields**
