### ISSUE TITLE
What is host_selection_retry_max_attempts on retry_policy?

### ISSUE THREAD

**Issue by Brunomachadob** [envoyproxy/envoy#13465]
**Description:**
I have been studying the docs here to enable retries for some routes I have, but I'm still trying to understand how all these concepts works as a whole.

Not sure if this is lack of knowledge on this matter, missing documentation or not-so-clear documentation.

When it comes to `host_selection_retry_max_attempts` and `envoy.retry_host_predicates.previous_hosts` based on this piece of [retry-plugin-configuration](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#retry-plugin-configuration) doc, what is `host`?

If we go to this [service_discovery#strict-dns](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#strict-dns) doc, they say a `host` is each IP being returned by the DNS query to that cluster. 

But the cluster has an array of hosts, so in the end we have a matrix of `cluster hosts x IPs` possible hosts?

My specific use case here is:
```yaml
...

#route
- match:
    path: /api/retry/test
route:
    cluster: myservice
    auto_host_rewrite: true
retry_policy:
    retry_on: gateway-error
    num_retries: 2
    host_selection_retry_max_attempts: 1
    retry_host_predicate:
        - name: envoy.retry_host_predicates.previous_hosts

...

# cluster
  - name: myservice
    connect_timeout: 1s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: myservice.service.consul
        port_value: 443
    tls_context:
      sni: myservice.service.consul

...
```

We can see the only `host` I have is pointing to consul that will return multiple IPs.

So the question is: When I use `host_selection_retry_max_attempts` and `envoy.retry_host_predicates.previous_hosts`, will the retry mechanism loop over the hosts of the cluster or the "hosts"/ips returned by the DNS query of my single cluster host?

With the configuration above, will I be able to retry the request on a different IP after the last one returned an error?

**What do I want to achieve:**
Specially during rolling deploys `myservice` goes down and up again with different ips, it could be that either consul or envoy did not updated their IP cache, and this leads to connection errors during usage.

I was hoping that this single retry change will improve resilience a bit without too much effort, by retrying the route again with the next ip (it could be based on current ip cache, it is not strictly needed to DNS query again)

Maybe you can help me understand that, and if we agree the doc could be improved, I could work on it.

Thanks!
