### ISSUE TITLE
Oauth proxy extensisons fails on boot with INVALID_ARGUMENT errors

### ISSUE THREAD

**Issue by krubot** [envoyproxy/envoy#13488]
*Title*: *Oauth proxy extensions fails on boot*

*Description*:

Current attempted config for envoy version 1.16 using the oauth extension type looks to be failing with INVALID_ARGUMENT as a critical error. My attempt to build envoy here was by following the docs as laid out here:

https://www.envoyproxy.io/docs/envoy/v1.16.0/configuration/http/http_filters/oauth2_filter.html?highlight=oauth

*Repro steps*:

This was build using envoy proxy container version 1.16 and envoy configurations here:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_proxy
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: api
          http_filters:
          - name: auth
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
              config:
                token_endpoint:
                  cluster: auth
                  uri: authorization-server.com/token
                  timeout: 3s
              authorization_endpoint: https://authorization-server.com/authorize
              redirect_uri: "https://www.oauth.com/playground/oidc.html"
              redirect_path_matcher:
                path:
                  exact: /callback
              signout_path:
                path:
                  exact: /signout
              credentials:
                client_id: <client-secret>
          - name: envoy.router
  clusters:
  - name: auth
    connect_timeout: 5s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address: { socket_address: { address: www.oauth.com, port_value: 443 }}
    tls_context: { sni: www.oauth.com }
  - name: api
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: api
                port_value: 8000
```

It was booted using a docker-compose file with the following config:

```yaml
version: '3'

services:
  api:
    image: alpine
    container_name: api
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "nc -l -p 8000"
    ports:
      - 8000:8000
  proxy:
    image: envoyproxy/envoy:v1.16.0
    container_name: proxy
    restart: unless-stopped
    ports:
      - 10000:10000
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
```

*Admin and Stats Output*:

Since the container failed to boot I have no admin stats to show.

*Config*:

Envoy config has already been added above.

*Logs*:

The following container logs were seen from docker compose output:

```
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:305] initializing epoch 0 (base id=0, hot restart version=11.104)
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:307] statically linked extensions:
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.retry_host_predicates: envoy.retry_host_predicates.omit_canary_hosts, envoy.retry_host_predicates.omit_host_metadata, envoy.retry_host_predicates.previous_hosts
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.thrift_proxy.protocols: auto, binary, binary/non-strict, compact, twitter
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.internal_redirect_predicates: envoy.internal_redirect_predicates.allow_listed_routes, envoy.internal_redirect_predicates.previous_routes, envoy.internal_redirect_predicates.safe_cross_scheme
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.resource_monitors: envoy.resource_monitors.fixed_heap, envoy.resource_monitors.injected_resource
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.clusters: envoy.cluster.eds, envoy.cluster.logical_dns, envoy.cluster.original_dst, envoy.cluster.static, envoy.cluster.strict_dns, envoy.clusters.aggregate, envoy.clusters.dynamic_forward_proxy, envoy.clusters.redis
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.dubbo_proxy.filters: envoy.filters.dubbo.router
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.quic_client_codec: quiche
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.tracers: envoy.dynamic.ot, envoy.lightstep, envoy.tracers.datadog, envoy.tracers.dynamic_ot, envoy.tracers.lightstep, envoy.tracers.opencensus, envoy.tracers.xray, envoy.tracers.zipkin, envoy.zipkin
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.thrift_proxy.filters: envoy.filters.thrift.rate_limit, envoy.filters.thrift.router
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.stats_sinks: envoy.dog_statsd, envoy.metrics_service, envoy.stat_sinks.dog_statsd, envoy.stat_sinks.hystrix, envoy.stat_sinks.metrics_service, envoy.stat_sinks.statsd, envoy.statsd
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.udp_listeners: quiche_quic_listener, raw_udp_listener
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.filters.listener: envoy.filters.listener.http_inspector, envoy.filters.listener.original_dst, envoy.filters.listener.original_src, envoy.filters.listener.proxy_protocol, envoy.filters.listener.tls_inspector, envoy.listener.http_inspector, envoy.listener.original_dst, envoy.listener.original_src, envoy.listener.proxy_protocol, envoy.listener.tls_inspector
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.access_loggers: envoy.access_loggers.file, envoy.access_loggers.http_grpc, envoy.access_loggers.tcp_grpc, envoy.file_access_log, envoy.http_grpc_access_log, envoy.tcp_grpc_access_log
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.filters.http: envoy.buffer, envoy.cors, envoy.csrf, envoy.ext_authz, envoy.fault, envoy.filters.http.adaptive_concurrency, envoy.filters.http.admission_control, envoy.filters.http.aws_lambda, envoy.filters.http.aws_request_signing, envoy.filters.http.buffer, envoy.filters.http.cache, envoy.filters.http.cdn_loop, envoy.filters.http.compressor, envoy.filters.http.cors, envoy.filters.http.csrf, envoy.filters.http.decompressor, envoy.filters.http.dynamic_forward_proxy, envoy.filters.http.dynamo, envoy.filters.http.ext_authz, envoy.filters.http.fault, envoy.filters.http.grpc_http1_bridge, envoy.filters.http.grpc_http1_reverse_bridge, envoy.filters.http.grpc_json_transcoder, envoy.filters.http.grpc_stats, envoy.filters.http.grpc_web, envoy.filters.http.gzip, envoy.filters.http.header_to_metadata, envoy.filters.http.health_check, envoy.filters.http.ip_tagging, envoy.filters.http.jwt_authn, envoy.filters.http.local_ratelimit, envoy.filters.http.lua, envoy.filters.http.oauth, envoy.filters.http.on_demand, envoy.filters.http.original_src, envoy.filters.http.ratelimit, envoy.filters.http.rbac, envoy.filters.http.router, envoy.filters.http.squash, envoy.filters.http.tap, envoy.grpc_http1_bridge, envoy.grpc_json_transcoder, envoy.grpc_web, envoy.gzip, envoy.health_check, envoy.http_dynamo_filter, envoy.ip_tagging, envoy.local_rate_limit, envoy.lua, envoy.rate_limit, envoy.router, envoy.squash
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.quic_server_codec: quiche
proxy    | [2020-10-09 16:07:19.029][7][info][main] [source/server/server.cc:309]   envoy.udp_packet_writers: udp_default_writer, udp_gso_batch_writer
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.http.cache: envoy.extensions.http.cache.simple
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.upstreams: envoy.filters.connection_pools.http.generic, envoy.filters.connection_pools.http.http, envoy.filters.connection_pools.http.tcp
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.dubbo_proxy.protocols: dubbo
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.transport_sockets.upstream: envoy.transport_sockets.alts, envoy.transport_sockets.quic, envoy.transport_sockets.raw_buffer, envoy.transport_sockets.tap, envoy.transport_sockets.tls, envoy.transport_sockets.upstream_proxy_protocol, raw_buffer, tls
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.compression.compressor: envoy.compression.gzip.compressor
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.retry_priorities: envoy.retry_priorities.previous_priorities
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.bootstrap: envoy.extensions.network.socket_interface.default_socket_interface
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.guarddog_actions: envoy.watchdog.abort_action, envoy.watchdog.profile_action
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.resolvers: envoy.ip
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.dubbo_proxy.serializers: dubbo.hessian2
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.compression.decompressor: envoy.compression.gzip.decompressor
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.filters.udp_listener: envoy.filters.udp.dns_filter, envoy.filters.udp_listener.udp_proxy
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.dubbo_proxy.route_matchers: default
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.thrift_proxy.transports: auto, framed, header, unframed
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.health_checkers: envoy.health_checkers.redis
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.filters.network: envoy.client_ssl_auth, envoy.echo, envoy.ext_authz, envoy.filters.network.client_ssl_auth, envoy.filters.network.direct_response, envoy.filters.network.dubbo_proxy, envoy.filters.network.echo, envoy.filters.network.ext_authz, envoy.filters.network.http_connection_manager, envoy.filters.network.kafka_broker, envoy.filters.network.local_ratelimit, envoy.filters.network.mongo_proxy, envoy.filters.network.mysql_proxy, envoy.filters.network.postgres_proxy, envoy.filters.network.ratelimit, envoy.filters.network.rbac, envoy.filters.network.redis_proxy, envoy.filters.network.rocketmq_proxy, envoy.filters.network.sni_cluster, envoy.filters.network.sni_dynamic_forward_proxy, envoy.filters.network.tcp_proxy, envoy.filters.network.thrift_proxy, envoy.filters.network.zookeeper_proxy, envoy.http_connection_manager, envoy.mongo_proxy, envoy.ratelimit, envoy.redis_proxy, envoy.tcp_proxy
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.grpc_credentials: envoy.grpc_credentials.aws_iam, envoy.grpc_credentials.default, envoy.grpc_credentials.file_based_metadata
proxy    | [2020-10-09 16:07:19.030][7][info][main] [source/server/server.cc:309]   envoy.transport_sockets.downstream: envoy.transport_sockets.alts, envoy.transport_sockets.quic, envoy.transport_sockets.raw_buffer, envoy.transport_sockets.tap, envoy.transport_sockets.tls, raw_buffer, tls
proxy    | [2020-10-09 16:07:19.042][7][critical][main] [source/server/server.cc:102] error initializing configuration '/etc/envoy/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:redirect_path_matcher: Cannot find field.) has unknown fields
proxy    | [2020-10-09 16:07:19.042][7][info][main] [source/server/server.cc:731] exiting
proxy    | Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:redirect_path_matcher: Cannot find field.) has unknown fields
```

*Call Stack*:

Again envoy is failing to boot so its unlikely I'll be able to get a call stack here too.

**Comment by dio** [comment]
These fields below are part of [`config`](https://github.com/envoyproxy/envoy/blob/5760b8a709e98c08fcd209ef7e3e84699b4b6ba7/api/envoy/extensions/filters/http/oauth2/v3alpha/oauth.proto#L48). Seems like you need to fix the indentations?

```yaml
              authorization_endpoint: https://authorization-server.com/authorize
              redirect_uri: "https://www.oauth.com/playground/oidc.html"
              redirect_path_matcher:
                path:
                  exact: /callback
              signout_path:
                path:
                  exact: /signout
              credentials:
                client_id: <client-secret>
```
