### ISSUE TITLE
Original Src Filter Causes "upstream connect error or disconnect/reset before headers. reset reason: local reset"

### ISSUE THREAD

**Issue by eltalkarim** [envoyproxy/envoy#13510]
*Title*: 
Adding Original Src Filter Causes "upstream connect error or disconnect/reset before headers. reset reason: local reset"

*Description*:
Once I added this to the listener at port 80 no connection could be made on that port. 

```        
      listener_filters:
        - name: envoy.filters.listener.original_src
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.original_src.v3.OriginalSrc
            mark: 123
```

*Admin and Stats Output*:

listeners:
```
listener_0::0.0.0.0:80
```

Server info:
```{
 "version": "50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "use_dynamic_base_id": false,
  "base_id_path": "",
  "concurrency": 6,
  "config_path": "/etc/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "ignore_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] [%g:%#] %v",
  "log_format_escaped": false,
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "drain_strategy": "Gradual",
  "mode": "Serve",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "disabled_extensions": [],
  "bootstrap_version": 0,
  "hidden_envoy_deprecated_max_stats": "0",
  "hidden_envoy_deprecated_max_obj_name_len": "0",
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "uptime_current_epoch": "878s",
 "uptime_all_epochs": "878s"
}
```

*Config*:
>Include the config used to configure Envoy.

```        
      listener_filters:
        - name: envoy.filters.listener.original_src
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.original_src.v3.OriginalSrc
            mark: 123
```
Based on this https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_src_filter
