### ISSUE TITLE
Redis TTL expiry doesn't work when mirroring

### ISSUE THREAD

**Issue by aviramha** [envoyproxy/envoy#13625]
*Title*: Redis TTL expiry doesn't work when mirroring

*Description*:
When sending a pipeline of adding 1 entry to a list and setting expiry on it, the list is created on both redises, but expire isn't set on the main (not mirrored) redis.
I tried reproducing it, when running two redises local it worked great, when one was remote it didn't. The remote redis is RedisLab's SSD.

*Repro steps*:
Script used to reproduce (pip3 install aioredis)
```py
import aioredis
import uuid
KEY_FORMAT = "mes_test"

async def main():
    envoy_redis = await aioredis.create_redis_pool(('127.0.0.1', 6666), password='local')
    first_redis = await aioredis.create_redis_pool(('127.0.0.1', 6379), password='a')
    second_redis = await aioredis.create_redis_pool(('remote_redis', remote_port), password='???')
    keys = [KEY_FORMAT + uuid.uuid4().hex for i in range(100)]
    tasks = [push(envoy_redis, key) for key in keys]
    await asyncio.wait(tasks)
    first_redis_tasks = [get_ttl(first_redis, key) for key in keys]
    second_redis_tasks = [get_ttl(second_redis, key) for key in keys]
    first_done, _ = await asyncio.wait(first_redis_tasks)
    second_done, _ = await asyncio.wait(second_redis_tasks)
    for i, task in enumerate(first_done):
        value = task.result()
        if value < 0:
            print(f"first redis {keys[i]} failed with value {value}")

    for i, task in enumerate(second_done):
        value = task.result()
        if value < 0:
            print(f"second redis {keys[i]} failed with value {value}")

    envoy_redis.close()
    await envoy_redis.wait_closed()
    first_redis.close()
    await first_redis.wait_closed()
    second_redis.close()
    await second_redis.wait_closed()

async def get_ttl(redis: aioredis.Redis, key: str) -> float:
    return await redis.ttl(key)

async def push(redis: aioredis.Redis, key: str):
    pipeline = redis.pipeline()
    pipeline.rpush(key, b"lol")
    pipeline.expire(key, 300)
    await pipeline.execute()

if __name__ == '__main__':
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
Output will be second redis `mes_test`... failed with value -1 if it's reproducing.

Dockerfile of Envoy
```docker
FROM envoyproxy/envoy:v1.16.0
COPY envoy.yaml /etc/envoy/envoy.yaml
```

YAML file:
```yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 8001
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          downstream_auth_password:
            inline_string: local
          settings:
            op_timeout: 5s
          prefix_routes:
            routes:
              - prefix: "mes_"
                cluster: "ssd"
                request_mirror_policy:
                  cluster: "standard"
                  exclude_read_commands: True
            catch_all_route:
              cluster: "standard"
  clusters:
  - name: ssd
    connect_timeout: 6s
    type: strict_dns
    load_assignment:
      cluster_name: redis_ssd
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: remote_redis
                port_value: remote_port
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "remote_password"}
  - name: standard
    connect_timeout: 6s
    type: strict_dns
    load_assignment:
      cluster_name: redis_standard
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.docker.internal
                port_value: 6379
    typed_extension_protocol_options:
        envoy.redis_proxy:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProtocolOptions
          auth_password: {inline_string: "a"}
```
