### ISSUE TITLE
Upstream request statistics by path

### ISSUE THREAD

**Issue by Brunomachadob** [envoyproxy/envoy#13673]
*Description*:
Continuing the discussion on https://github.com/envoyproxy/envoy/issues/1585, it would be nice to have path tags on the `envoy.upstream_rq` for example.

In my opinion it should not be the actual path of the current request, as this could expose sensitive information and also make a lot of unnecessary dimensions on the metric.

But rather, having it based on the [RouteMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routematch), specifically on `prefix`, `path` and `safe_regex`.

At the end does not really matter the full path being used at the moment, but rather which Envoy route was used, and the RouteMatcher would provide us a static and safe tag to be used.

*Another approach*:

Maybe another thing that could be done is by attaching a tag statically to a route and make that as a tag?
Maybe this exists somehow and I'm not aware? Like adding a tag from the route metadata for example...

**Comment by mattklein123** [comment]
I think it would be fine to opt-in to extra stats based on route name (probably). This is what we have discussed in the past. I think there are other issues already tracking this.

**Comment by carlos-fau-etermax** [comment]
We have a complex mesh with frontend services for specific products and backend services for multi-product functionality.

The involved product code is part of the URL like: "/products/XYZ/some-service/...". Currently we get metrics by "path spec", so we have a metric for the generic "/products/{productCode}/some-service/..." which provides us no clue on the product targeted in the call.

If we can "extract" the _productCode_ ("XYZ") along the "path spec" ("/products/{productCode}/some-service/...") we can generate very useful metrics.

Perhaps a filter that allow to stract metrics labels can be a way to go.

**Comment by grzegorz-mirek** [comment]
@carlos-fau-etermax, how do you actually get metrics by "path spec"?

**Comment by carlos-fau-etermax** [comment]
@grzegorz-mirek currently we use Traefik as an Ingress Controller and we have configured all the valid "path", so traefik report metrics per each "frontend" (each path).
The problems are:

1. we are using an Ingress for Service to Service communication (I do not recommend this practice) to get metrics for requests from one service to another (in new services we configured a Prometheus filter to expose those metrics but this solution was not spread because it requires to modified all services)
2. Most of the configured paths have the structure: `/games/{gameId}/...` and due that we cannot get metrics per **gameId**

**Comment by Brunomachadob** [comment]
Hello @mattklein123 I'm afraid I couldn't find another issue that relates to this one.
I believe your comment about going with a route name tag would be already be a great improvement.

Would you mind re-opening it? Or should we open another one?

**Comment by gabrielgiussi** [comment]
@Brunomachadob 
I asked for a similar thing recently since I didn't see this ticket and matt provided me two alternatives: virtual_clusters and stat_prefix, both work in a similar way and provide the same stats but they are configured at different places (I don't know in which cases one is better than the other).
https://github.com/envoyproxy/envoy/issues/23642

**Comment by Brunomachadob** [comment]
Hey @gabrielgiussi, thanks for the heads up.

Yeah, I actually use the `virtual_clusters` for a couple of use cases on smaller proxies, but I was avoiding adding it to our main API Gateway with hundreds of routes and thousands of requests per second.

Specially due to how you need to match the path again on the `virtual_cluster` and the note on "not recommend adding for every route".

As far as I understood, this `stat_prefix` of the route, works on top of the `virtual_cluster`, right? So I guess we would still have the same problems with it. I'll follow the other issue as well to understand it better, lets see how it goes.

Thanks!

**Comment by mjallday** [comment]
In case someone is looking for a practical example of how to do this (since it took me a couple of hours to figure out). 

```yaml
                route_config:
                  name: name-of-route-config
                  virtual_hosts:
                    # name used when emitting stats, not imp for routing itself
                    - name: name-of-vhost
                      domains:
                        - "*"
                      routes:
                        - name: /foo
                          stat_prefix: /foo
                          match:
                            prefix: /foo
                          route:
                            cluster: my-cluster
                        - name: /anything/{else}
                          stat_prefix: /anything/{else}
                          match:
                            path_template: /anything/{else}
                          route:
                            cluster: my-cluster
                        - name: default
                          stat_prefix: default
                          match:
                            prefix: /
                          route:
                            cluster: my-cluster
```

This works well for us and is generating per route statistics via `envoy_vhost_route_upstream_rq_total` prometheus metric using the `envoy_route` dimension.
