### ISSUE TITLE
Adding authorization token to Rate Limit requests

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#13680]
Hi, we have adopted the Rate Limiting Service with Envoy and we have added token validation logic to the Rate Limiting Service. 
Now we are trying to configure Envoy to get an OAuth2.0 token using Client Credentials, and then send that along in the call credentials for the Rate Limiting request.

I see in the documentation below that google_grpc supports the addition of call credentials:
(https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc#grpc-services) (https://www.envoyproxy.io/docs/envoy/v1.15.0/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice-googlegrpc-callcredentials) 

Would the access_token option work for our use case, or is it only for accessing Google Services? I don't see any examples so I am not sure what the best way to fetch the token would be, and how the token is getting sent.

If not that, is our only option to write a custom plugin and use the from_plugin setting? And if so, are there any examples of using a custom plugin?

**Comment by sunjayBhatia** [comment]
See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc#arch-overview-grpc-services for some more documentation on use cases of the Envoy gRPC vs Google gRPC services

**Comment by jaegchoi** [comment]
> See https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc#arch-overview-grpc-services for some more documentation on use cases of the Envoy gRPC vs Google gRPC clients
> 
> I believe the Google gRPC client provides the generic advanced feature from gRPC for OAuth2 integration and it is not only for use with Google services, I believe the warning `Only use these credentials when connecting to a Google endpoint. Using these credentials to connect to any other service may result in this service being able to impersonate your client for requests to Google services.` is meant to warn against Google specific issued tokens

Thanks, but I believe that is the same link that I included in the original post.

As to your second point, that's encouraging, I wonder if you or anyone else has an example on doing this. 
My Rate Limit Filter config is as below and when I include the call_credentials section the request seems to fail to reach the rate limiting service.
In my envoy log the one message I see that might be relevant is this:
`[2020-10-22 18:35:04.236][75][debug][grpc] [source/common/grpc/google_async_client_impl.cc:209] notifyRemoteClose 13`

```
- name: envoy.filters.http.ratelimit
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
    stage: 0
    domain: xxx
    failure_mode_deny: false
    timeout: 0.25s
    rate_limit_service:
      grpc_service:
        google_grpc:
          target_uri: xxx
          stat_prefix: rate_limit_service
          call_credentials:
            access_token: xxx
```
