### ISSUE TITLE
 Remote JWKS doesn't seem to cache public key despite cache_duration being configured in jwt_auth filter

### ISSUE THREAD

**Issue by kkatrio** [envoyproxy/envoy#13708]
*Title*: Remote JWKS doesn't seem to cache public key despite cache_duration being configured in jwt_auth filter

*Description*:
When using the jwt authentication filter to validate successfully a request by fetching the public key from a remote location, the key doesn't seem to be cached. If the same request is sent within the cache duration that is specified in the configuration, envoy tries to fetch it again from the remote location instead of looking into some local cache. Is this behavior expected or is there some configuration missing?

Here is the configuration:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: some_stat_prefix
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: provinceB
          http_filters:
          - name: envoy.filters.http.jwt_authn
            config:
              providers:
                provider1:
                  issuer: name.oftheissuer.com
                  remote_jwks:
                    http_uri:
                      uri: http://100.100.100.100:8080/public_key.txt
                      cluster: auth-server
                      timeout: 0.25s
                    cache_duration:
                      seconds: 5000
              rules:
              - match:
                  prefix: /my/api/v1/endpoint
                requires:
                  provider_name: provider1
          - name: envoy.router

 clusters:
  - name: auth-server
    connect_timeout: 0.25s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: auth-server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.100.100.100
                port_value: 8080
   ...
```
Also:
Logs of two subsequent requests:
In the first, the key is fetched and the token is validated successfully. The response is successful as expected:

> [2020-10-22 10:10:19.190][2039][debug][filter] [source/extensions/filters/http/common/jwks_fetcher.cc:71] onSuccess: fetch pubkey [uri = http://100.100.100.100:8080/public_key.txt]: success
> [2020-10-22 10:10:19.190][2039][debug][filter] [source/extensions/filters/http/common/jwks_fetcher.cc:77] onSuccess: fetch pubkey [uri = http://100.100.100.100:8080/public_key.txt]: succeeded
> [2020-10-22 10:10:19.190][2039][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:276] provider1: JWT token verification completed with: OK
> 
> 
> [2020-10-22 10:10:19.194][2039][debug][http] [source/common/http/conn_manager_impl.cc:1435] [C0][S14644052848363385753] encoding headers via codec (end_stream=false):
> ':status', '201'
> 'x-origin', 'something-2-6c65ddd4c7-lxfv8'
> 'content-type', 'application/json; charset=utf-8'
> 'x-envoy-upstream-service-time', '2'
> 'date', 'Thu, 22 Oct 2020 10:10:19 GMT'
> 'server', 'envoy'
> 
> [2020-10-22 10:10:19.194][2039][debug][client] [source/common/http/codec_client.cc:109] [C2] response complete

At this point, I remove manually the key from the remote server. Then I try the same request again, within the `cache duration`. However it tries to fetch it again straight away, and of course, it fails:

> [2020-10-22 10:10:47.008][2050][debug][conn_handler] [source/server/connection_handler_impl.cc:459] [C3] new connection
> [2020-10-22 10:10:47.008][2050][debug][http] [source/common/http/conn_manager_impl.cc:225] [C3] new stream
> [2020-10-22 10:10:47.008][2050][debug][http] [source/common/http/conn_manager_impl.cc:837] [C3][S5451393403416711153] request headers complete (end_stream=false):
> ':authority', '100.100.100.100:32383'
> ':method', 'POST'
> 'user-agent', 'curl/7.29.0'
> 'accept', '*/*'
> 'authorization', 'Bearer ababababa.cdcdcdcdcdcd.efefefef...'
> 'content-type', 'application/json'
> 'content-length', '97'
> 
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:127] Called Filter : setDecoderFilterCallbacks
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:49] Called Filter : decodeHeaders
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/matcher.cc:70] Prefix requirement '/nchf-convergedcharging/v1/chargingdata' matched.
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/extractor.cc:190] extract authorizationBearer
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:127] provider1: JWT authentication starts (allow_failed=false), tokens size=1
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:138] provider1: startVerify: tokens size 1
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:149] provider1: Verifying JWT token of issuer some.issuer....
> [2020-10-22 10:10:47.008][2050][debug][filter] [source/extensions/filters/http/common/jwks_fetcher.cc:55] **fetch pubkey** from [uri = http://100.100.100.100:8080/public_key.txt]: start
> [2020-10-22 10:10:47.008][2050][debug][router] [source/common/router/router.cc:429] [C0][S12433958812326943344] cluster 'auth-server' match for URL '/public_key.txt'
> [2020-10-22 10:10:47.008][2050][debug][router] [source/common/router/router.cc:586] [C0][S12433958812326943344] router decoding headers:
> ':path', '/public_key.txt'
> ':authority', '100.100.100.100:8080'
> ':method', 'GET'
> ':scheme', 'http'
> 'x-envoy-internal', 'true'
> 'x-envoy-expected-rq-timeout-ms', '250'
> 
> [2020-10-22 10:10:47.008][2050][debug][pool] [source/common/http/conn_pool_base.cc:71] queueing stream due to no available connections
> [2020-10-22 10:10:47.008][2050][debug][pool] [source/common/conn_pool/conn_pool_base.cc:104] creating a new connection
> [2020-10-22 10:10:47.008][2050][debug][client] [source/common/http/codec_client.cc:39] [C4] connecting
> [2020-10-22 10:10:47.008][2050][debug][connection] [source/common/network/connection_impl.cc:755] [C4] connecting to 100.100.100.100:8080
> [2020-10-22 10:10:47.008][2050][debug][connection] [source/common/network/connection_impl.cc:771] [C4] connection in progress
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:76] Called Filter : decodeHeaders Stop
> [2020-10-22 10:10:47.008][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:111] Called Filter : decodeData
> [2020-10-22 10:10:47.009][2050][debug][http] [source/common/http/filter_manager.cc:721] [C3][S5451393403416711153] request end stream
> [2020-10-22 10:10:47.009][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:111] Called Filter : decodeData
> [2020-10-22 10:10:47.017][2050][debug][connection] [source/common/network/connection_impl.cc:611] [C4] connected
> [2020-10-22 10:10:47.017][2050][debug][client] [source/common/http/codec_client.cc:77] [C4] connected
> [2020-10-22 10:10:47.017][2050][debug][pool] [source/common/conn_pool/conn_pool_base.cc:205] [C4] attaching to next stream
> [2020-10-22 10:10:47.017][2050][debug][pool] [source/common/conn_pool/conn_pool_base.cc:126] [C4] creating stream
> [2020-10-22 10:10:47.017][2050][debug][router] [source/common/router/upstream_request.cc:357] [C0][S12433958812326943344] pool ready
> [2020-10-22 10:10:47.018][2050][debug][router] [source/common/router/router.cc:1178] [C0][S12433958812326943344] upstream headers complete: end_stream=false
> [2020-10-22 10:10:47.019][2050][debug][http] [source/common/http/async_client_impl.cc:100] async http request response headers (end_stream=false):
> ':status', '404'
> 'content-type', 'text/plain; charset=utf-8'
> 'x-content-type-options', 'nosniff'
> 'date', 'Thu, 22 Oct 2020 10:10:47 GMT'
> 'content-length', '19'
> 'x-envoy-upstream-service-time', '9'
> 
> [2020-10-22 10:10:47.019][2050][debug][client] [source/common/http/codec_client.cc:109] [C4] response complete
> [2020-10-22 10:10:47.019][2050][debug][filter] [source/extensions/filters/http/common/jwks_fetcher.cc:89] onSuccess: fetch pubkey [uri = http://100.100.100.100:8080/public_key.txt]: **response status code 404**
> [2020-10-22 10:10:47.019][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:276] provider1: JWT token verification completed with: **Jwks remote fetch is failed**
> [2020-10-22 10:10:47.019][2050][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:87] Called Filter : check complete Jwks remote fetch is failed

What am I missing? I haven't seen anything in the documentation suggesting that some other cache mechanism must be deployed or that something else must be configured.
