### ISSUE TITLE
How to only allow specific domains for https request in envoy forward proxy?

### ISSUE THREAD

**Issue by chengdol** [envoyproxy/envoy#13704]
*Title*:  How to only allow specific domains for https request in envoy forward proxy?

*Description*:
I configure envoy as a forward proxy for https request, from my test log in this case the `domains` list in virtual_hosts has to be `*`, otherwise envoy cannot find upstream cluster and return 404, for example:
```
....
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
            ## ---------------------
              domains:
                - "*"
            ##----------------------
              routes:
                - match:
                    connect_matcher:
                      {}
                  route:
                    cluster: cluster_0
                    upgrade_configs:
                      - upgrade_type: CONNECT
          http_filters:
          - name: envoy.filters.http.router
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
            - upgrade_type: CONNECT
....
```
But I only want to allow specific domains to go through the connection, and other domains should get rejected.

I want to know does envoy support this when upgrading to `CONNECT`? Can anyone please advise how to achieve this?
