### ISSUE TITLE
proposal:  Implement `uri blocker` by Lua filter

### ISSUE THREAD

**Issue by nic-chen** [envoyproxy/envoy#13791]
## Background

We are developing a Lua framework that support Apache APISIX plugins run directly in Envoy Lua filter without modify Envoy. #13307

## Goals

Implementing the `uri blocker` plugin running on envoy.

Through uri blocking rules configuration, intercept invalid uri requests

## Implementation

1. Configure block rules and rejected code through `metadata`

2. Check whether the accessed uri matches the block rules (regular expression or string match), if it does not match, let it go, and if it matches, it will directly return rejected code

### filter
```yaml
name: envoy.filters.http.lua.uri-blocker
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
  source_codes:
    apisix_init.lua:
      filename: /apisix/init.lua
```

### config
```yaml
metadata:
  filter_metadata:
    envoy.filters.http.lua.uri-blocker:
      plugins: 
      - name: uri-blocker
        conf:
          ret_code: 302
          block_rules: 
          - root.exe
          - root.m+
```

Envoy community, what do you think of the proposal?

Any suggestion or feedback is welcome, thanks !

**Comment by membphis** [comment]
How to enable the plugin `uri-blocker` in routes? Can you provide an example?

**Comment by nic-chen** [comment]
@membphis 

It should be:


### source codes
```
name: envoy.filters.http.lua
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
  source_codes:
    apisix_init.lua:
      filename: /apisix/init.lua 
```



### per_filter_config
```
              routes:
              - match:
                  prefix: "/hello"
                route:
                  cluster: web_service
                per_filter_config:
                  envoy.filters.http.lua:
                    name: apisix_init.lua

```


### config
```
metadata:
  filter_metadata:
    envoy.filters.http.lua:
      plugins: 
      - name: uri-blocker
        conf:
          ret_code: 302
          block_rules: 
          - root.exe
          - root.m+
```

When it's done, I will write a real usable example here.

**Comment by membphis** [comment]
> envoy.filters.http.lua

Is it possible to use a name that is easier to understand? eg: `http.lua.plugins.test_uri_blocker`

**Comment by dio** [comment]
@nic-chen sorry, do we need to introduce changes inside Envoy for supporting this?

**Comment by nic-chen** [comment]
@dio 

Thanks for reply.

I think not. But after start development, there may be issues that require your help.

And, do you have some suggestions for this?  : )

**Comment by moonming** [comment]
nic-chen if you don’t need to modify the envoy code, I think it’s a good solution.
@dio what do you think？

**Comment by dio** [comment]
I think I have no objection on this. Probably creating an example sandbox will be useful for others.

**Comment by nic-chen** [comment]
@moonming  sure, that's what we are working on.

@dio  Thanks for suggestion. I will post an example that can be run quickly when it's done.

**Comment by nic-chen** [comment]
I have been quite busy during this period of time, will continue this work today, hope it coming soon.  : )

**Comment by nic-chen** [comment]
Here is a full example config:

```yaml
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/foo"
                route:
                  cluster: web_service
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    name: entry.lua
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua:
                      plugins: 
                      - name: uri-blocker
                        conf:
                          ret_code: 302
                          block_rules: 
                          - root.exe
                          - root.m+
              - match:
                  prefix: "/bar"
                route:
                  cluster: web_service
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    name: entry.lua
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua:
                      plugins: 
                      - name: redirect
                        conf:
                          ret_code: 301
                          uri: "/redirected/path"
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              source_codes:
                entry.lua:
                  filename: /apisix/entry.lua
          - name: envoy.router
            typed_config: {}

  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 80
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

```

What do you think ? Just make sure I'm on the right way. Thanks!


@dio @membphis @moonming
