### ISSUE TITLE
CORS and gRPC-JSON transcoder are not working correctly. OPTIONS returns 404 Not found

### ISSUE THREAD

**Issue by MilosSlavic** [envoyproxy/envoy#13878]
Hi,

I am using envoy as a front proxy. I have multiple grpc services behind the proxy.
My goal is to support REST API functionality for these grpc services.
I succeeded in configuring envoy for this use case, it works when I use Postman.
My web app needs to communicate with envoy with CORS enabled, so I followed the documentation, other issues on github and some example configurations. At the end of the day I was not able to make it work.

In hosts file I have set:
127.0.0.1 web-app.company.localdev
127.0.0.1 api-gateway.company.localdev

Web app is vue.js app running with npm run serve on local machine. 
Api gateway is running with docker compose (envoy and grpc services). Envoy is accepting connections on port 10000, admin port is 10001.

I get this in chrome: 
Access to XMLHttpRequest at 'http://api-gateway.company.localdev:10000/api/OrganizationUnit/Client/node' from origin 'http://web-app.company.localdev:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Fount this in log:
>[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Host value=api-gateway.company.localdev:10000
[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Connection value=keep-alive
[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Accept value=application/json
[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=User-Agent value=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Origin value=http://web-app.company.localdev:8080
[2020-11-03 09:43:56.304][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Referer value=http://web-app.company.localdev:8080/
[2020-11-03 09:43:56.305][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Accept-Encoding value=gzip, deflate
[2020-11-03 09:43:56.305][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:632] [C0] onHeadersCompleteBase
[2020-11-03 09:43:56.305][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C0] completed header: key=Accept-Language value=en-US,en;q=0.9
[2020-11-03 09:43:56.305][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:874] [C0] Server: onHeadersComplete size=8
[2020-11-03 09:43:56.305][19][trace][http] [source/common/http/http1/codec_impl_legacy.cc:745] [C0] message complete
[2020-11-03 09:43:56.305][19][trace][connection] [source/common/network/connection_impl.cc:310] [C0] readDisable: disable=true disable_count=0 state=0 buffer_length=427
[2020-11-03 09:43:56.306][19][debug][http] [source/common/http/conn_manager_impl.cc:837] [C0][S6662860450372106877] request headers complete (end_stream=true):
':authority', 'api-gateway.company.localdev:10000'
':path', '/api/OrganizationUnit/Client/node'
':method', 'GET'
'connection', 'keep-alive'
'accept', 'application/json'
'user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36'
'origin', 'http://web-app.company.localdev:8080'
'referer', 'http://web-app.company.localdev:8080/'
'accept-encoding', 'gzip, deflate'
'accept-language', 'en-US,en;q=0.9'

>[2020-11-03 09:43:56.306][19][debug][http] [source/common/http/filter_manager.cc:721] [C0][S6662860450372106877] request end stream
[2020-11-03 09:43:56.307][19][trace][http] [source/common/http/filter_manager.cc:463] [C0][S6662860450372106877] decode headers called: filter=0x35d7ff496f60 status=0
[2020-11-03 09:43:56.307][19][trace][http] [source/common/http/filter_manager.cc:463] [C0][S6662860450372106877] decode headers called: filter=0x35d7ff437140 status=0
[2020-11-03 09:43:56.318][19][trace][http] [source/common/http/filter_manager.cc:463] [C0][S6662860450372106877] decode headers called: filter=0x35d7ff483c20 status=0
[2020-11-03 09:43:56.318][19][debug][router] [source/common/router/router.cc:364] [C0][S6662860450372106877] no cluster match for URL '/OrganizationUnit.ClientGrpcService/GetNodesWithCount'
[2020-11-03 09:43:56.318][19][debug][http] [source/common/http/filter_manager.cc:805] [C0][S6662860450372106877] Sending local reply with details route_not_found
[2020-11-03 09:43:56.319][19][trace][http] [source/common/http/filter_manager.cc:966] [C0][S6662860450372106877] encode headers called: filter=0x35d7ff5efa40 status=0
[2020-11-03 09:43:56.319][19][trace][http] [source/common/http/filter_manager.cc:966] [C0][S6662860450372106877] encode headers called: filter=0x35d7ffaf2e60 status=0
[2020-11-03 09:43:56.319][19][trace][http] [source/common/http/filter_manager.cc:966] [C0][S6662860450372106877] encode headers called: filter=0x35d7ffaf3130 status=0
[2020-11-03 09:43:56.319][19][debug][http] [source/common/http/conn_manager_impl.cc:1435] [C0][S6662860450372106877] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Tue, 03 Nov 2020 09:43:56 GMT'
'server', 'envoy'

>[2020-11-03 09:43:56.319][19][trace][connection] [source/common/network/connection_impl.cc:422] [C0] writing 97 bytes, end_stream false

This is my yaml config:
```yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001

cluster_manager:
  outlier_detection:
    event_log_path: "/dev/stdout"

static_resources:
  listeners:
    - name: api_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: grpc_json
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*.company.localdev"]
                    routes:
                      - match: { prefix: "/OrganizationUnit.CarePlaceGrpcService/", grpc: {} }
                        route: { cluster: "organization_unit_grpc", timeout: 120s }
                    cors:
                      allow_origin_string_match:
                        - safe_regex:
                            google_re2: {}
                            regex: .*\.company\.localdev
                      allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
                      allow_headers: content-type,origin,authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                      expose_headers: grpc-status,grpc-message,x-envoy-upstream-service-time
                      allow_credentials: true
              http_filters:
                - name: envoy.filters.http.cors
                - name: envoy.filters.http.grpc_web
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/descriptor/descriptor.pb"
                    ignore_unknown_query_parameters: true
                    services:
                      - "OrganizationUnit.CarePlaceGrpcService"
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: true
                      preserve_proto_field_names: true
                - name: envoy.filters.http.router

  clusters:
    - name: organization_unit_grpc
      connect_timeout: 1s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: organization_unit_grpc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: organizationunit.api
                      port_value: 90
```

**Comment by qiwzhang** [comment]
You can try to set this `match_incoming_request_route` [flag](https://github.com/envoyproxy/envoy/blob/master/api/envoy/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto#L77) 

Envoy may be using the http  json content type before the transcoding to match the route.  But your route has `grpc {}`,  I am not sure what it means, it may want to match grpc content type. 

Or you can just remove `grpc {}` in your route match, it should work.

**Comment by MilosSlavic** [comment]
Hi.

Probably there is some issue with preflight request when not using / but instead using routes that consist of /PackageName.Service/.
The only thing that worked for me was adding the "fake" route:
- match: { prefix: "/", headers: [ { name: ":method", exact_match: "OPTIONS" } ] }
  route: { cluster: "organization_unit_grpc", timeout: 120s }

I tried to use direct_response and it didn't work, there is some difference in logic between direct_response and route.
This configuration is working with 1.16, maybe those things are fixed in 1.17.

Config:
```yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001

cluster_manager:
  outlier_detection:
    event_log_path: "/dev/stdout"

static_resources:
  listeners:
    - name: api_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: grpc_json
              codec_type: AUTO
              access_log:
                - name: envoy.access_loggers.file
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["api-gateway.company.localdev:10000"]
                    routes:
                      - match: { prefix: "/", headers: [ { name: ":method", exact_match: "OPTIONS" } ] }
                      # fake cluster route ... some issue in envoy.
                        route: { cluster: "organization_unit_grpc", timeout: 120s }
                      - match: { prefix: "/OrganizationUnit.ClientGrpcService/", grpc: {} }
                        route: { cluster: "organization_unit_grpc", timeout: 120s }
                    cors:
                      allow_origin_string_match:
                        - exact: http://web-app.company.localdev:8080
                        - exact: http://web-app.company.localdev:8080/
                        - exact: web-app.company.localdev
                      allow_methods: GET, PUT, DELETE, POST, PATCH, OPTIONS
                      allow_headers: content-type,origin,referer,authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                      expose_headers: grpc-status,grpc-message,x-envoy-upstream-service-time
              http_filters:
                - name: envoy.filters.http.cors
                - name: envoy.filters.http.grpc_web
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/descriptor/guide.pb"
                    ignore_unknown_query_parameters: true
                    services:
                      - "OrganizationUnit.ClientGrpcService"
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: true
                      preserve_proto_field_names: true
                - name: envoy.filters.http.router

  clusters:
    - name: organization_unit_grpc
      connect_timeout: 1s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: organization_unit_grpc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: organizationunit.api
                      port_value: 90
```
