### ISSUE TITLE
how to use `typed_per_filter_config`.

### ISSUE THREAD

**Issue by JaredTan95** [envoyproxy/envoy#13899]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
how to use `typed_per_filter_config`.

*Description*:
>Describe the issue.

I tried `typed_per_filter_config` on `virtual_hosts---> routes`  as follows:

```yml
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                upgrade_configs:
                  upgrade_type: websocket
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: service_google
                          typed_per_filter_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
```

but, when I starting the envoy, there occurs some errors :

```bash
Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].routes[0].typed_per_filter_config[1].value): invalid value "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute" for type type.googleapis.com/google.protobuf.Any): 
```

and I also referred the official document: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-luaperroute

but it still doesn't work. 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by JaredTan95** [comment]
This is resolved in the following way:

```yml
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle)
                                    request_handle:logInfo("Hello World.")
                                  end
```
