### ISSUE TITLE
Problems with logrotate

### ISSUE THREAD

**Issue by dantodor** [envoyproxy/envoy#13962]
I am trying to configure log rotation for access logs. 
Here are relevant parts of the config:

Envoy yaml:
```
access_log:
            name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/var/log/envoy/envoy.log"
              json_format:
                  starttime: "%START_TIME%"
                  rduration: "%DURATION%"
                  responsecode: "%RESPONSE_CODE%"
                  bytesr: "%BYTES_RECEIVED%"
                  bytess: "%BYTES_SENT%"
                  rcaller: "%REQ(X-FORWARDED-FOR)%"
                  routename: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
```

logrotate.d conf file:
```
/var/log/envoy/envoy.log
{
    missingok
    daily
    create 0644 root root
    rotate 50
    size=100M
    dateext
    dateformat -%d%m%Y
    sharedscripts
    postrotate
	/bin/kill -USR1 `pgrep envoy` 2> /dev/null || true
    endscript
}
```

Running logrotate by hand:

```reading config file /etc/logrotate.d/envoy
Allocating hash table for state file, size 15360 B

Handling 1 logs

rotating pattern: /var/log/envoy/envoy.log
 104857600 bytes (50 rotations)
empty log files are rotated, old logs are removed
considering log /var/log/envoy/envoy.log
  log needs rotating
rotating log /var/log/envoy/envoy.log, log->rotateCount is 50
Converted ' -%d%m%Y' -> '-%d%m%Y'
dateext suffix '-10112020'
glob pattern '-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
glob finding old rotated logs failed
renaming /var/log/envoy/envoy.log to /var/log/envoy/envoy.log-10112020
creating new /var/log/envoy/envoy.log mode = 0644 uid = 0 gid = 0
running postrotate script
running script with arg /var/log/envoy/envoy.log
: "
	/bin/kill -USR1 `pgrep envoy` 2> /dev/null || true
"`
```

Yet, envoy.log is still in place and growing ... Any idea what I'm doing wrong ?
Thank you!
