### ISSUE TITLE
TLS session resumption does not seem to happening with TLSv 1.2

### ISSUE THREAD

**Issue by sanathpholla** [envoyproxy/envoy#13980]
*Title*: *TLS session resumption does not seem to happening with TLSv 1.2*

*Description*:

Envoy was deployed as apt package on Linux ubuntu based system.
Was trying to disable the TLS session reuse for HTTPS listener and even when the disable_stateless_session_resumption of tls_context is set to True and the TLS version used is TLSv1.2, the TLS session ID is being reused for the connections made after initial connection establishment.
I have confirmed this behaviour both by seeing the traffic capture at envoy proxy machine and also by verifying the same by using openssl command(link: https://serverfault.com/a/566361/557378)

*Repro steps*:
* Send multiple requests by using wrk tool(1req per connection) from client machine to envoy proxy.
`wrk -t 1 -c 5 -d 2s -H 'Connection: Close' https://10.160.90.73:444`

*Config*:
Have the below envoy yaml config which was used which is pretty basic.
```
static_resources:
  listeners:
  - name: listener_https
    address:
      socket_address:
        address: 10.160.90.73
        port_value: 444
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: http1
          stat_prefix: envoy_https
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: backend_cluster }
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
      tls_context:
        disable_stateless_session_resumption: True
        common_tls_context:
          tls_params:
            tls_minimum_protocol_version: TLSv1_2
            tls_maximum_protocol_version: TLSv1_2
            cipher_suites: "[ECDHE-RSA-AES128-GCM-SHA256]"
          tls_certificates:
            - certificate_chain:
                filename: #path to cert
              private_key:
                filename: # path to private key
  clusters:
  - name: backend_cluster
    type: STATIC
    max_requests_per_connection: 100000
    connect_timeout: 1.00s
    lb_policy: round_robin
    load_assignment:
      cluster_name: backend_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.23.101
                port_value: 1024 # HTTP port
           # Similarly 9 more HTTP endpoints are present
admin:
  access_log_path: "/var/log/envoy.access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
By reading the API doc, I don't think it is a config issue.

*Stats output*:
From the stats output, ssl reuse counter seems to be incrementing.
```
root@envoy-proxy:~/envoy_configs# curl -X GET localhost:8001/stats|grep ssl
http.admin.downstream_cx_ssl_active: 0
http.admin.downstream_cx_ssl_total: 0
http.perf_envoy_https.downstream_cx_ssl_active: 0
http.perf_envoy_https.downstream_cx_ssl_total: 6229
listener.10.160.90.73_444.server_ssl_socket_factory.downstream_context_secrets_not_ready: 0
listener.10.160.90.73_444.server_ssl_socket_factory.ssl_context_update_by_sds: 0
listener.10.160.90.73_444.server_ssl_socket_factory.upstream_context_secrets_not_ready: 0
listener.10.160.90.73_444.ssl.ciphers.ECDHE-RSA-AES128-GCM-SHA256: 6225
listener.10.160.90.73_444.ssl.connection_error: 0
listener.10.160.90.73_444.ssl.curves.P-256: 6225
listener.10.160.90.73_444.ssl.fail_verify_cert_hash: 0
listener.10.160.90.73_444.ssl.fail_verify_error: 0
listener.10.160.90.73_444.ssl.fail_verify_no_cert: 0
listener.10.160.90.73_444.ssl.fail_verify_san: 0
listener.10.160.90.73_444.ssl.handshake: 6225
listener.10.160.90.73_444.ssl.no_certificate: 6225
listener.10.160.90.73_444.ssl.ocsp_staple_failed: 0
listener.10.160.90.73_444.ssl.ocsp_staple_omitted: 0
listener.10.160.90.73_444.ssl.ocsp_staple_requests: 0
listener.10.160.90.73_444.ssl.ocsp_staple_responses: 0
listener.10.160.90.73_444.ssl.session_reused: 6211
listener.10.160.90.73_444.ssl.versions.TLSv1.2: 6225
```
