### ISSUE TITLE
SDS warming stuck after SDS server outage (and recovery)

### ISSUE THREAD

**Issue by mpuncel** [envoyproxy/envoy#14000]
*Title*: *SDS warming stuck without retrying*

*Description*:
After an outage of our SDS server and subsequent recovery, we found an Envoy instance that seemed to be permanently stuck on warming secrets.

Info logs look like this (repeated forever):
```
[2020-11-12 18:41:47.798][25][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:100] StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:100] StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:100] StreamAggregatedResources gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
```

Turning the log level to `debug` after the fact doesn't yield anything interesting, it's as if no SDS is being attempted at all.

This shows up in our config_dump:

```
 {
   "@type": "type.googleapis.com/envoy.admin.v3.SecretsConfigDump",
   "dynamic_warming_secrets": [
    {
     "name": "spiffe://staging.ski.squarecloudservices.com/alok-test-app",
     "version_info": "uninitialized",
     "last_updated": "2020-11-12T16:53:21.005Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "spiffe://staging.ski.squarecloudservices.com/alok-test-app"
     }
    },
    {
     "name": "spiffe://production.squareup.com",
     "version_info": "uninitialized",
     "last_updated": "2020-11-12T16:53:21.005Z",
     "secret": {
      "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret",
      "name": "spiffe://production.squareup.com"
     }
    }
   ]
  }
```

*Repro steps*:

Envoy version: 4797e7a4fdaf5d2cf1475fe940b883f88782305c

This occurred after starting Envoy while the SDS server is down, and brought back up. I'm not sure how reliably this reproduces.

*Config*:

(I only included the SDS related bits)

```
static_resources:
  clusters:
  - name: spire-agent
    connect_timeout: 5s
    type: STATIC
    http2_protocol_options: {}
    upstream_connection_options:
      tcp_keepalive:
        keepalive_probes: 2
        keepalive_time: 30
        keepalive_interval: 30
    load_assignment:
      cluster_name: spire-agent
      endpoints:
        lb_endpoints:
        - endpoint:
            address:
              pipe:
                path: /run/spire/sockets/agent.sock

  - name: envoy-control-xds--staging-serving
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: RANDOM
    load_assignment:
      cluster_name: envoy-control-xds--staging-serving
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address: { address: <snip>, port_value: 32336 }
    http2_protocol_options: {}
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        common_tls_context:
          tls_certificate_sds_secret_configs:
            name: spiffe://staging.ski.squarecloudservices.com/alok-test-app
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services: { envoy_grpc: { cluster_name: spire-agent}}
          combined_validation_context:
            default_validation_context:
              verify_subject_alt_name: envoy-control.global.square
            validation_context_sds_secret_config:
              name: spiffe://production.squareup.com
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services: { envoy_grpc: { cluster_name: spire-agent}}
          alpn_protocols: h2
```

*Stats*
```
cluster.spire-agent.upstream_cx_active: 1
cluster.spire-agent.upstream_cx_http2_total: 1
cluster.spire-agent.upstream_rq_200: 2
cluster.spire-agent.upstream_rq_2xx: 2
cluster.spire-agent.upstream_rq_active: 2
cluster.spire-agent.http2.streams_active: 2
cluster.spire-agent.upstream_rq_completed: 2
cluster.spire-agent.upstream_rq_pending_total: 2
cluster.spire-agent.upstream_rq_total: 2
cluster.spire-agent.upstream_cx_rx_bytes_buffered: 17
cluster.spire-agent.upstream_cx_rx_bytes_total: 311
cluster.spire-agent.upstream_cx_total: 1
cluster.spire-agent.upstream_cx_tx_bytes_buffered: 0
cluster.spire-agent.upstream_cx_tx_bytes_total: 23085
cluster.envoy-control-xds--staging-serving.client_ssl_socket_factory.ssl_context_update_by_sds: 0
cluster.envoy-control-xds--staging-serving.client_ssl_socket_factory.upstream_context_secrets_not_ready: 459
```
