### ISSUE TITLE
Dynamically overriding rate limit with data from headers and dynamic metadata

### ISSUE THREAD

**Issue by RafalJachimczyk** [envoyproxy/envoy#14013]
**Title**: Dynamically overriding rate limit with headers and dynamic metadata

**Description**:

Hello! 

Apologies in advance if this is something trivial. We are spiking use of Envoy to replace our in-house api-management solution. 

We're trying to make use of `ExtAuthz` filter for api key validation and `ratelimit` filter for limiting. The `ratelimit` should make use of information returned by our `ExtAuthz` filter in headers to set different rate limits per api key. The ratelimit makes use of `https://github.com/envoyproxy/ratelimit` as the `rate_limit_service`

At first stage of our spike we achieved a global rate limiting, where each api key got their own quota tracked. This was a good starting point. But this meant that all api keys get the same rate limit (e.g. all got 10 requests per minute as an example)

The next step was to make use of the quota information retrieved from the key validation API. Our use case allows different clients represented by api keys to have different quotas. 

It was to our delight to find that we can make use of ratelimit override functionality (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter#rate-limit-override). So we tried to set it up.
We understand the ratelimit filter can't make use of override data in headers, but it can get it from dynamic metadata. 

**The simplest way I can describe what we try to do is this**: 
- A client makes a request to an API with an api key attached in a header.
- The request reaches envoy
- External auth filter `type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz` configured to make a call to our "sidecar" application, where the api key is extracted from headers and passed down to our Key Validation API
- The Key Validation API responds with status of the api key (success or failure). On success is attaches information about quota information - quota (Integer) and time unit (enum containing MINUTE, HOUR, DAY etc)
- We grab the information from headers using `header_to_metadata` filter
- Then this metadata is passed onto ratelimit override.
- Ratelimit service makes retrieves the override
- Ratelimit filter makes decision to let the request through or not
- The request reaches backend (or not)
- Response is sent back (either 429 code or another response code from backend)

Unfortunately the rate limits are not overridden at the service level and we still get the global rate limit which was set in the `https://github.com/envoyproxy/ratelimit` service. So all api keys (clients) get the same rate. 

We have added a simple `lua` filter to confirm the dynamic metadata is attached, and in fact it is. But the Rate Limit Override does not seem to kick in. Reading through the docs it looks like Rate Limit Override expects the metadata to come in as a struct containing `requests_per_unit` and `unit` fields - I'm thinking the problem with our config is around this - i.e. we're just setting primitive values on dynamic metadata and not struct. 

Is our scenario possible to achieve with rate limit override?  Any help would be appreciated 😌

We were also thinking of having another external filter which could read the quota headers already attached and make the call to ratelimit service for us, but we would obviously want to avoid this as it requires more code and therefore maintenance in future. 

Below is our config:

```
static_resources:

  listeners:
  - name: listener_ingress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              http_service:
                authorization_request:
                  allowed_headers:
                    patterns:
                    - exact: "x-api-key"               
                server_uri:
                  uri: 127.0.0.1:3000
                  cluster: ext-authz
                  timeout: 1s                               
              # Default is 200ms; override if your server needs e.g. warmup time.
              include_peer_certificate: true
          - name: envoy.filters.http.header_to_metadata
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
              request_rules:
                - header: product-quota
                  on_header_present:
                    # metadata_namespace: envoy.lb
                    key: rate.requests_per_unit
                    type: STRING
                  on_header_missing:
                    # metadata_namespace: envoy.lb
                    key: rate.requests_per_unit
                    value: '10'
                    type: STRING
                  remove: false                                   
                - header: product-quota-time-unit
                  on_header_present:
                    key: rate.unit
                    type: STRING
                  on_header_missing:
                    # metadata_namespace: envoy.lb
                    key: rate.unit
                    value: 'MINUTE'
                    type: STRING
                  remove: false                      

          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                -- Called on the request path.
                function envoy_on_request(request_handle)
                  local requests_per_unit = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.header_to_metadata")["rate.requests_per_unit"]
                  local unit = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.header_to_metadata")["rate.unit"]
                  request_handle:logInfo("requests_per_unit value: " .. requests_per_unit)
                  request_handle:logInfo("unit value: " .. unit)
                end
                             
          - name: envoy.filters.http.ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: apis 
              stage: 0         
              request_type: external
              failure_mode_deny: true
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit              
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  safe_regex: 
                    google_re2: {}
                    regex: "^/(.*)$"
                route:
                  regex_rewrite: 
                    pattern: 
                      google_re2: {}
                      regex: "^/httpbin(.*)$"
                    substitution: \1                
                  host_rewrite_literal: httpbin.org
                  cluster: egress-httpbin
              rate_limits:
                - stage: 0
                  actions:
                    - header_value_match:
                        descriptor_value: api-key-limit
                        headers:
                          - name: ":path"
                            prefix_match: "/"
                    - request_headers:
                        header_name: "X-Api-Key"
                        descriptor_key: api-key              
                  limit:
                    dynamic_metadata:
                      metadata_key:
                        key: envoy.filters.http.ratelimit
                        path:
                          - key: rate
          
          access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: "/dev/stdout"
```

Thanks !
