### ISSUE TITLE
Probable memory leak with JWT authentication with fetched public JWKS

### ISSUE THREAD

**Issue by gontard** [envoyproxy/envoy#14026]
*Title*: *Probable memory leak with JWT authentication with fetched public JWKS*

*Description*:
We have recently setup [JWT authentication](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto) and since we have observed that the allocated memory (`memory_allocated`) was increasing _lineary_. The growth is slow, ~5Mb per day, but still.
May be there is a leak in the JWKS cache?
Feel free to ask more details to help you to spot the bug.

*Config*:
Here is an extract of the config:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                cognito:
                  issuer: https://cognito-idp.eu-west-1.amazonaws.com/xxxxxxxxxxxxxxxxxxxxx
                  audiences:
                  - xxxxxxxxxxxxxxxxxxxxx
                  remote_jwks:
                    http_uri:
                      uri: https://cognito-idp.eu-west-1.amazonaws.com/xxxxxxxxxxxxxxxxxxxxx/.well-known/jwks.json
                      cluster: cognito-cluster
                      timeout: 5s
                    cache_duration: 600s
              rules:
              - match:
                    prefix: /api
                requires:
                  requires_any:
                    requirements:
                      - provider_name: cognito
                      - allow_missing: {}
          - name: envoy.filters.http.router
  clusters:
  - name: cognito-cluster
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cognito-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: cognito-idp.eu-west-1.amazonaws.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: cognito-idp.eu-west-1.amazonaws.com
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt

```

<img width="1414" alt="Capture d’écran 2020-11-16 à 10 29 33" src="https://user-images.githubusercontent.com/1221664/99235853-af373100-27f6-11eb-84ce-57172567547f.png">

**Comment by qiwzhang** [comment]
I just double checked Jwks cache code, it is using unique_ptr,  it is difficult to have memory leak.   Could you help to do following tests:
* turn on/off jwt_authn filter to make sure the leak is from that filter.
* use inline_jwks, instead of remote jwks
* remove `allow_missing` to see if its implementation may have leak.  Its implementation just changed recently, make sure to get the latest Envoy.

Thanks

**Comment by gontard** [comment]
@qiwzhang thanks a lot for your help.
I do not have a lot of time for the moment but i will give you more details in the next weeks.

**Comment by bjaglin** [comment]
I am working with @gontard and ran an initial test before following the list above.

I spawned an instance of envoy with a different remote jwks `cache_duration` behind the same load balancer as existing production instances (thus the difference of offset and the different axis to better compare) and observed no difference in the amount of leak per hour.

![cacheduration](https://user-images.githubusercontent.com/349077/99637327-f9155680-2a44-11eb-87ef-e880997fbe55.png)

**Comment by qiwzhang** [comment]
Thanks @bjaglin. Your test result implies that the leak is not from Jwks fetching and cache.

Could you help to run two tests with different qps? one QPS is the double of another one to see if the leak is the same

Thanks

**Comment by qiwzhang** [comment]
Hi @bjaglin Any update on your test?

BTW,  we have load tests with this filter.  Our tests did not show any memory leak.   Could you try to disable jwt_authn filter to make sure the leak is from this filter?

**Comment by ssimard24** [comment]
Any movement on this topic? Using Envoy 1.3, we have just released a change to use multiple providers for JWT and we are also seeing constant memory leak:

apiVersion: v1
kind: ConfigMap
metadata:
  name: presence-envoy-config
  namespace: __DEPLOY_KUBERNETES_NAMESPACE__
data:
  envoy.yaml: |
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9001
    static_resources:
      listeners:
      - name: listener0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9090
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/null"
                  json_format:
                    v: "1"
                    ts: "%START_TIME%"
                    appName: "__DEPLOY_KUBERNETES_APPNAME__"
                    clientID: "%DYNAMIC_METADATA(envoy.filters.http.jwt_authn:jwt-payload:client_id)%"
                    userID: "%DYNAMIC_METADATA(envoy.filters.http.jwt_authn:jwt-payload:sub)%"
                    req: "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    reqResult: "%RESPONSE_CODE%"
                    message: "soc log"
                    srcIP: "%REQ(X-FORWARDED-FOR)%"
                    msg: "envoy jwt validation"
                    status_details: "%RESPONSE_CODE_DETAILS%"
                    duration: "%DURATION%"
                    soc: "true"
                    sev: "low"

              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: __DEPLOY_KUBERNETES_APPNAME__
              http_filters:
              - name: envoy.cors
              - name: envoy.filters.http.jwt_authn
                ##reference: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/jwt_authn/v2alpha/config.proto#envoy-api-msg-config-filter-http-jwt-authn-v2alpha-jwtprovider
                config:
                  providers:
                    cc-idm:
                      forward: true
                      issuer: https://__IDM_ISSUER__:__IDM_PORT__
                      payload_in_metadata: jwt-payload
                      remote_jwks:
                        http_uri:
                          uri: __ENVOY_JWKS_URI__
                          cluster: idm-cluster
                          ## timeout required since envoy v1.13
                          timeout:
                            seconds: 3
                        cache_duration:
                          seconds: 86400 #24 hours
                    cc-master-idm:
                      forward: true
                      issuer: https://__MASTER_IDM_TOKEN_ISSUER__:__IDM_PORT__
                      payload_in_metadata: jwt-payload
                      remote_jwks:
                        http_uri:
                          uri: https://__PI_IDM_JWKS_URI__
                          cluster: pi-idm-cluster
                          ## timeout required since envoy v1.13
                          timeout:
                            seconds: 3                          
                        cache_duration:
                          seconds: 300 #5 minutes                          
                    cc-pi-idm:
                      forward: true
                      issuer: https://__PI_IDM_TOKEN_ISSUER__:__IDM_PORT__
                      payload_in_metadata: jwt-payload
                      remote_jwks:
                        http_uri:
                          uri: https://__PI_IDM_JWKS_URI__
                          cluster: pi-idm-cluster
                          ## timeout required since envoy v1.13
                          timeout:
                            seconds: 3                          
                        cache_duration:
                          seconds: 300 #5 minutes 
                  rules:
                    - match:
                        prefix: "/probes/readiness"
                    - match:
                        prefix: "/probes/liveness"
                    - match:
                        prefix: /
                      requires:
                        requires_any:
                          requirements:
                            - provider_name: cc-pi-idm
                            - provider_name: cc-master-idm
                            - provider_name: cc-idm 
              - name: envoy.lua
                config:
                  inline_code: |
                    function envoy_on_request(request_handle)
                      if not pcall(validate_request_scope_claim, request_handle) then
                        request_handle:respond({[":status"] = "500", ['content-type'] = "application/json"}, '{"code": 500, "message": "Internal Server Error"}')
                      end
                    end

                    function validate_request_scope_claim(request_handle)
                      local path = request_handle:headers():get(":path")

                      if path == "/probes/readiness" or path == "/probes/liveness" then
                        return
                      end

                      local payload = request_handle:streamInfo():dynamicMetadata():get("envoy.filters.http.jwt_authn")["jwt-payload"]

                      if payload == nil or payload["scope"] == nil or table.getn(payload["scope"]) == 0 then
                          request_handle:respond({[":status"] = "403", ["content-type"] = "application/json"}, '{"code": 403, "message": "No `scope` claim[s] in JWT payload"}')
                          return
                      end

                      local method = request_handle:headers():get(":method")

                      local found = false
                      if "POST" == method or "GET" == method or "PUT" == method or "DELETE" == method then
                          for key,value in pairs(payload["scope"]) do
                              if value == "cc911_pres" or value == "cc911_call_ev" then
                                  found = true
                                  break
                              end
                          end
                      else
                          request_handle:respond({[":status"] = "405", ['content-type'] = "application/json"}, '{"code": 405, "message": "Go away!"}')
                          return
                      end

                      if not found then
                          request_handle:respond({[":status"] = "403", ['content-type'] = "application/json"}, '{"code": 403, "message": "JWT scope claim[s] unauthorized"}')
                      end
                    end
              - name: envoy.router
      clusters:
      - name: __DEPLOY_KUBERNETES_APPNAME__
        connect_timeout: 0.25s
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 8080
      - name: idm-cluster
        connect_timeout: 5.00s
        dns_lookup_family: V4_ONLY
        dns_refresh_rate: 30.00s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: __IDM_ISSUER__
            port_value: __IDM_PORT__
        tls_context:
          sni: __IDM_ISSUER__
        type: LOGICAL_DNS
      - name: pi-idm-cluster
        connect_timeout: 5s
        dns_lookup_family: V4_ONLY
        dns_refresh_rate: 30.00s
        lb_policy: ROUND_ROBIN
        hosts:
        - socket_address:
            address: __PI_IDM_CLUSTER__
            port_value: __IDM_PORT__
        tls_context:
          sni: __PI_IDM_CLUSTER__
        type: LOGICAL_DNS

**Comment by qiwzhang** [comment]
This is a lot of memory leak, from 15MB to 800MB in two days.  What is your traffic qps?  

Could you ping point the cause:
1) remove lua filter, but keep jwt filter, or even remove both filters.
2) if indeed it is jwt,  then just keep one provider.   

Thanks

**Comment by bjaglin** [comment]
@qiwzhang sorry for the lack of updates.

1. It's very hard for us to try with different QPS unfortunately as we don't have a true staging environment, and the envoy instances are behind a load balancer we don't control (AWS ELB).
1. I have been able to reproduce the problem on Envoy 1.16.1.
1. Disabling the `jwt_authn` filter does make the problem disappear.
1. Our use-case requires `allow_missing` so I can't try without it.

Next step would be to try `inline_jwks` I guess, I'll see if I have time to look at that over the next 2 weeks.

**Comment by qiwzhang** [comment]
@bjaglin, @ssimard24 both your envoy config are using static listener,  are they your real envoy config?  My question is: do you use xDS to load dynamic listeners?  One area my memory leak test did not cover is using xDS dynamic listeners and filter chain with jwt_authn filter_config is constantly replaced due to xDS update.   are you using xDS?

Another area is: signature algorithm. I only tested RS256.   What is your jwt signature algorithm?

**Comment by ssimard24** [comment]
We have just reverted back to single providers and do not have memory leak anymore. The problem is definitely related to multiple providers for us. Our context was 3 providers. Only one was expected to work at any point in tome as the others were for backward/forward compatibility.

**Comment by qiwzhang** [comment]
Thanks @ssimard24 
Are your 3 providers using the same algorithm?  You just need to paste the JWT to jwt.io, its header will show the algorithm type.

**Comment by bjaglin** [comment]
> your envoy config are using static listener, are they your real envoy config? My question is: do you use xDS to load dynamic listeners?

Our config is fully static, no xDS involved.

> Another area is: signature algorithm. I only tested RS256. What is your jwt signature algorithm?

That could have been a good lead, but we use RS256 as well (https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html).

**Comment by bjaglin** [comment]
@qiwzhang I finally got the chance to try `local_jwks`. Unfortunately, the leak is still visible, so I guess the problem is in the filter itself.
```diff
-                  remote_jwks:
-                    http_uri:
-                      # https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json.
-                      uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_soDjURThj/.well-known/jwks.json
-                      cluster: cognito-cluster
-                      timeout: 5s
-                    cache_duration: 600s
+                  local_jwks:
+                    filename: /etc/envoy/jwks.json
```
```json
{
  "keys": [
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "n79wlqvqfXNK8uqRyHFby9RhKF310mdvLBbwCQO5j/U=",
      "kty": "RSA",
      "n": "wMHVQ5-rtYyVZHdC1N_6ZZWFZuYmlSm1HTJZeXvt_ZciXExQrMD1yjjFHm2u4D3MDevR_m-5kjYL7cUCKT49MCk5rwlLxNTEzFl-l2VMTFIg61ZdRydBfgoatCw83jwj8g2nlMuoUf6fm1RZDQfrYu4pNlR73h8TjcHrc7zFwyWy43_DqiPtwObSps71NA5nnmZOXTzz1RIjHoN2g-XP9MtwCO_uzODCTqY-8y7N5Ni7fnzU6t4DTV6MGVlXSv5OEwb8R5xO_RfFxgv4-KDGy79j3M9n8E4M84PSmotOBvGedAtLHD2dW9HJiUs7CVuS0Km-z5smf2I4_1ZnOZ0qVw",
      "use": "sig"
    },
    {
      "alg": "RS256",
      "e": "AQAB",
      "kid": "m82Mt01iAjG+WoM0UfGR9M/uRZ9EO0EV6Cx5bXkttqI=",
      "kty": "RSA",
      "n": "o4x7M1je1jqwbWJIl-n40y26IcYOmLJXDPB5jiZliq9wtQVXDAfr4AAO0LxLLEUdk6ypWqDvPzImFIMfeshTbSh4OJqioBDYWvWFPWhMvesvVQv70aoBF12yxbMCSOsZ9tnMkDLKHZPQ5G7b4Ss62l9pOmAUrJDZyxlL8e_sf6VMs0Rrz2-R1yE--zpZRKc34cVr91RqALT95rQqAkNRfpjgAwikIBMun9YMTN1EyjUHR9LxVIQnryWjKaaOaIlzx6CbECCLa0lIQJIQJNsWnJX49tx_XrDNe0hSbUD7bkjUQ1QOW-LYaYA-hWIgUp56docyG533SSY0a01skFrVtQ",
      "use": "sig"
    }
  ]
}
```

**Comment by qiwzhang** [comment]
Thanks.  @bjaglin 

We do have integration test with RS256.  Our CI and ASAN and TSAN tests, they did not find any memory leak. 
So I really don't know how to proceed from here.

**Comment by bjaglin** [comment]
Can it be related to the JWT payload header forwarding? I just realized the extract posted by my colleague when opening does not contain all the options we use, nor the other filters.
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
                format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %TRAILER(GRPC-STATUS)% %TRAILER(TEADS-DOMAIN)% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\" \"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\"\n"
          route_config:
            virtual_hosts:
            - name: all
              domains:
              - "*"
              routes:
              - match:
                  prefix: /
                route:
                  cluster: grpc-cluster
                  timeout: 60s
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                cognito:
                  issuer: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_soDjURThj
                  audiences:
                  - xxxxxxxxxxxxxxxxxxxxx
                  forward: true
                  forward_payload_header: jwt-payload
                  remote_jwks:
                    http_uri:
                      uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_soDjURThj/.well-known/jwks.json
                      cluster: cognito-cluster
                      timeout: 5s
                    cache_duration: 600s
              rules:
              - match:
                    prefix: /teads.api
                requires:
                  requires_any:
                    requirements:
                      - provider_name: cognito
                      - allow_missing: {}
          - name: envoy.filters.http.grpc_stats
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
              stats_for_all_methods: true
              enable_upstream_stats: true
          - name: envoy.filters.http.router
 ```

I will run another test without forwarding.
