### ISSUE TITLE
envoy as a layer 2 proxy with downstream from HAproxy

### ISSUE THREAD

**Issue by bettafish15** [envoyproxy/envoy#14032]
I have a HAproxy to route http2 grpc to server. But because grpc-web needs envoy so i configured envoy as a small reverse proxy with docker in server . HAproxy will reverse https connection to envoy which envoy will tls terminate it. But it got errors following:
```
envoy_1  | [2020-11-16 04:01:22.744][25][debug][conn_handler] [source/server/connection_handler_impl.cc:459] [C213] new connection
envoy_1  | [2020-11-16 04:01:22.747][25][debug][connection] [source/common/network/connection_impl.cc:579] [C213] remote close
envoy_1  | [2020-11-16 04:01:22.747][25][debug][connection] [source/common/network/connection_impl.cc:202] [C213] closing socket: 0
envoy_1  | [2020-11-16 04:01:22.747][25][debug][misc] [source/common/network/io_socket_error_impl.cc:30] Unknown error code 104 details Connection reset by peer
envoy_1  | [2020-11-16 04:01:22.747][25][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:288] [C213] SSL shutdown: rc=-1
envoy_1  | [2020-11-16 04:01:22.747][25][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C213]
envoy_1  | [2020-11-16 04:01:22.747][25][debug][conn_handler] [source/server/connection_handler_impl.cc:152] [C213] adding to cleanup list

```
My envoy yml config:
```yml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 10003 }

static_resources:
  listeners:
  - name: listener_0
    address: { socket_address: { address: 0.0.0.0, port_value: 80 } }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: some_service
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router   
          stream_error_on_invalid_http_message: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: [ "h2,http/1.1" ]
            tls_certificates:
              - certificate_chain: { filename: "/etc/crt.pem" }
                private_key: { filename: "/etc/key.pem" }
            validation_context:
              trusted_ca:
                filename: /etc/ca-cert.pem
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 10000
```
any ideas what happened?
