### ISSUE TITLE
Lua: in Lua filter, should require one of `inline_code` and `source_codes` , but not just require `inline_code`

### ISSUE THREAD

**Issue by nic-chen** [envoyproxy/envoy#14030]
Hi, Community

For reusing codes, I am used to writing the code in a file and referencing it through `source_codes`:

```yaml
          http_filters:
          -name: entry.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              source_codes:
                entry.lua:
                  filename: /apisix/entry.lua
```
But it cause an error

```sh
 Proto constraint validation failed (LuaValidationError.InlineCode: ["value length must be at least " '\x01' " runes"]): source_codes {
   key: "entry.lua"
   value {
     filename: "/apisix/entry.lua"
   }
 }
```

To avoid this error, I had to add an empty function in `inline_code`

```yaml
          http_filters:
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                end
              source_codes:
                entry.lua:
                  filename: /apisix/entry.lua
```

So, I think it should require one of `inline_code` and `source_codes` , but not just require `inline_code`.

What do you think? Thanks.
