### ISSUE TITLE
Invalid value Invalid type URL on TLS implementation

### ISSUE THREAD

**Issue by cre8ivejp** [envoyproxy/envoy#14033]
Hi

I am trying to migrate my envoy settings from API V2 to V3.
I have followed the example on this [page](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#example-configuration) to set the TLS, but I am getting this `invalid value Invalid type URL` error.

I am no sure what exactly is wrong. If I remove the TLS settings from the cluster settings, the same error shows in the listener's filter_chains.filter `envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager`.

Any help would be appreciated.

### Error
`
error initializing configuration '/usr/local/conf/config.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[0].transport_socket.typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext for type Any): {"static_resources":{"listeners":[{"filter_chains":[{"transport_socket":{"typed_config":{"common_tls_context":{"tls_certificates":[{"private_key":{"filename":"/usr/local/certs/test/tls.key"},"certificate_chain":{"filename":"/usr/local/certs/test/tls.crt"}}],"alpn_protocols":["h2"]},"@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext","require_client_certificate":true},"name":"envoy.transport_sockets.tls"},"filters":[{"typed_config":{"route_config":{"virtual_hosts":[{"cors":{"allow_credentials":true,"allow_methods":"POST","allow_origin_string_match":[{"prefix":"*"}],"allow_headers":"content-type, x-grpc-web, authorization"},"routes":[{"route":{"retry_policy":{"num_retries":3,"retry_on":"5xx"},"cluster":"web","timeout":"15s"},"match":{"prefix":"/"}}],"name":"web-gateway","domains":["*"]}]},"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","access_log":{"typed_config":{"path":"/dev/stdout","@type":"type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"},"name":"envoy.access_loggers.file"},"stat_prefix":"ingress_http","common_http_protocol_options":{"idle_timeout":"620s"},"http_filters":[{"name":"envoy.filters.http.cors"},{"name":"envoy.filters.http.grpc_web"},{"name":"envoy.filters.http.router"}],"codec_type":"auto"},"name":"envoy.filters.network.http_connection_manager"}]}],"name":"ingress","address":{"socket_address":{"port_value":443,"address":"0.0.0.0"}}}],"clusters":[{"transport_socket":{"typed_config":{"common_tls_context":{"tls_certificates":[{"private_key":{"filename":"/usr/local/certs/service/tls.key"},"certificate_chain":{"filename":"/usr/local/certs/service/tls.crt"}}],"alpn_protocols":["h2"]},"@type":"type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"},"name":"envoy.transport_sockets.tls"},"load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":443,"address":"web.default.svc.cluster.local"}}}}]}],"cluster_name":"web"},"http2_protocol_options":{},"health_checks":[{"unhealthy_threshold":2,"timeout":"1s","http_health_check":{"path":"/health"},"interval":"10s","interval_jitter":"1s","no_traffic_interval":"2s","healthy_threshold":1}],"type":"strict_dns","name":"web","connect_timeout":"5s","ignore_health_on_host_removal":true,"lb_policy":"round_robin"}]},"admin":{"address":{"socket_address":{"port_value":8001,"address":"0.0.0.0"}},"access_log_path":"/dev/stdout"}}
`

### Settings

```yaml
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  clusters:
    - name: web
      http2_protocol_options: {}
      connect_timeout: 5s
      ignore_health_on_host_removal: true
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: web
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: web.default.svc.cluster.local
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            alpn_protocols: ["h2"]
            tls_certificates:
              - certificate_chain:
                  filename: /usr/local/certs/service/tls.crt
                private_key:
                  filename: /usr/local/certs/service/tls.key
      health_checks:
        - http_health_check:
            path: /health
          timeout: 1s
          interval: 10s
          interval_jitter: 1s
          no_traffic_interval: 2s
          healthy_threshold: 1
          unhealthy_threshold: 2
  listeners:
    - name: ingress
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  name: envoy.access_loggers.file
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
                codec_type: auto
                common_http_protocol_options:
                  idle_timeout: 620s
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.router
                route_config:
                  virtual_hosts:
                    - name: web-gateway
                      domains:
                        - "*"
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_headers: "content-type, x-grpc-web, authorization"
                        allow_methods: "POST"
                        allow_credentials: true
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: web
                            timeout: 15s
                            retry_policy:
                              retry_on: 5xx
                              num_retries: 3
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              require_client_certificate: true
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /usr/local/certs/test/tls.crt
                    private_key:
                      filename: /usr/local/certs/test/tls.key
```
