### ISSUE TITLE
oauth2 filter: Allow multiple grant_types

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#14088]
I'm currently using keycloak as my oauth2 provider, in my current keycloak I'm using different mechanisms to authenticate and one of them is with client_credentials

Currently at this file https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/oauth2/oauth_client.cc, grant_type is hardcoded with authorization_code, which works fine, but will be nice to use multiple grant types like client_credentials or a custome one

Keycloak web page as reference https://www.keycloak.org/docs/latest/authorization_services/

Maybe we can add some logic to first try the authorization_code, if it fails retry with the next grant_type, we can define the list of grant_types like this
```

 - name: envoy.filters.http.oauth2
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
                    config:
                      token_endpoint:
                        cluster: oauth
                        uri: https://sso-dev.ohl.com/auth/realms/sso/protocol/openid-connect/token
                        timeout: 3s
                        grant_types: "authorization_code,client_credentials"
```
