### ISSUE TITLE
Decompressor Http filter does not decompress complete response

### ISSUE THREAD

**Issue by bharath-12345** [envoyproxy/envoy#14104]
*Title*: *Decompressor Http filter does not decompress complete response on envoy 1.15.1-dev*

*Description*:
**What is happening:**
The Envoy decompressor does not completely decompress the gzipped response. We have noticed that for gzipped responses with a size larger than the chunk_size specified in the gzip decompressor, we get back the decompressed response with a size nearly equal to chunk_size.  eg: Only 8192 bytes is returned from a response of which actual size is 10000 bytes. This happens whenever the Accept-Encoding header is set to gzip and the decompressor filter is enabled in the HTTP filter chain.

I have also tried using a buffer filter before the decompressor filter to buffer the output. But that does not seem to be working as expected. It is giving the same results.

**What is Expected**
I expect the decompression to be seamless i.e it should return the complete response and not just the number of bytes similar to the zlib buffer size.

*Repro steps*:
We can reproduce the bug by applying the decompressor filter (with response decompression) to an outbound listener and send an HTTP request which has a large response.

*Admin and Stats Output*:
Below are the response sizes when the gzip decompressor is applied.

Without any Accept-encoding headers. It returns the complete response. 
```
curl "<url>" > abc.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94214    0 94214    0     0  3680k      0 --:--:-- --:--:-- --:--:-- 3680k
```
With Accept-Encoding headers and with the decompressor filter applied with chunk size of 65536
```
root@<svc>:<dir># curl -H "Accept-Encoding: gzip" "<url>" > abc.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 65549    0 65549    0     0  1207k      0 --:--:-- --:--:-- --:--:-- 1207k
```

*Config*:
I have configured envoy using istio Envoy Filters. Here is the decompressor envoy filter
apiVersion: networking.istio.io/v1alpha3
```
kind: EnvoyFilter
metadata:
  name: istio-gunzip-sidecar-outbound
  namespace: service A
spec:
  workloadSelector:
    labels:
      app: service A
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: 'envoy.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.decompressor
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
            decompressor_library:
              name: small
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip"
                chunk_size: 65536

            request_direction_config:
              common_config:
                enabled:
                  default_value: false
                  runtime_key: request_decompressor_enabled
```
Here is the buffer envoy filter used
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: buffer-filter
  namespace: service A
spec:
  workloadSelector:
    labels:
      app: service A
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
              subFilter:
                name: 'istio.metadata_exchange'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
            max_request_bytes: 4096
```

The filter chain in envoy after these are applied looks like this:
```
"httpFilters": [
                             { 
                                    "name": "envoy.filters.http.buffer",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer",
                                        "maxRequestBytes": 4096
                                    }
                                },
                                {
                                    "name": "istio.metadata_exchange",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                                        "typeUrl": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                                        "value": {
                                            "config": {
                                                "configuration": {
                                                    "@type": "type.googleapis.com/google.protobuf.StringValue",
                                                    "value": "{}\n"
                                                },
                                                "vm_config": {
                                                    "code": {
                                                        "local": {
                                                            "inline_string": "envoy.wasm.metadata_exchange"
                                                        }
                                                    },
                                                    "runtime": "envoy.wasm.runtime.null"
                                                }
                                            }
                                        }
                                    }
                                },
                                {
                                    "name": "istio.alpn",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig",
                                        "alpnOverride": [
                                            {
                                                "alpnOverride": [
                                                    "istio-http/1.0",
                                                    "istio"
                                                ]
                                            },
                                            {
                                                "upstreamProtocol": "HTTP11",
                                                "alpnOverride": [
                                                    "istio-http/1.1",
                                                    "istio"
                                                ]
                                            },
                                            {
                                                "upstreamProtocol": "HTTP2",
                                                "alpnOverride": [
                                                    "istio-h2",
                                                    "istio"
                                                ]
                                            }
                                        ]
                                    }
                                },
                                {
                                    "name": "envoy.filters.http.cors",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"
                                    }
                                },
                                {
                                    "name": "envoy.filters.http.fault",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault"
                                    }
                                },
                                {
                                    "name": "istio.stats",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
                                        "typeUrl": "type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm",
                                        "value": {
                                            "config": {
                                                "configuration": {
                                                    "@type": "type.googleapis.com/google.protobuf.StringValue",
                                                    "value": "{\n  \"debug\": \"false\",\n  \"stat_prefix\": \"istio\"\n}\n"
                                                },
                                                "root_id": "stats_outbound",
                                                "vm_config": {
                                                    "code": {
                                                        "local": {
                                                            "inline_string": "envoy.wasm.stats"
                                                        }
                                                    },
                                                    "runtime": "envoy.wasm.runtime.null",
                                                    "vm_id": "stats_outbound"
                                                }
                                            }
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.filters.http.decompressor",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor",
                                        "decompressorLibrary": {
                                            "name": "small",
                                            "typedConfig": {
                                                "@type": "type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip",
                                                "chunkSize": 65536
                                            }
                                        },
                                        "requestDirectionConfig": {
                                            "commonConfig": {
                                                "enabled": {
                                                    "defaultValue": false,
                                                    "runtimeKey": "request_decompressor_enabled"
                                                }
                                            }
                                        }
                                    }
                                },
                                {
                                    "name": "envoy.filters.http.router",
                                    "typedConfig": {
                                        "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                                    }
                                }
                            ]
```

The complete envoy proxy_config file is attached below
[envoy_proxy_config.txt](https://github.com/envoyproxy/envoy/files/5569388/envoy_proxy_config.txt)

*Logs*:
>Include the access logs and the Envoy logs.

We disable logs in our clusters due to the high volume logging of envoy.

*Call Stack*:
No call stack. Non crashing bug
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/master/bazel#stack-trace-symbol-resolution).
