### ISSUE TITLE
Health status in EDS with active health check 

### ISSUE THREAD

**Issue by Kagamia-MS** [envoyproxy/envoy#14137]
version: 1.15.0

I'm trying to update dynamic endpoints with EDS, but the behavior in practice is inconsistent with the docs. Here's my questions:

1> What's the relationship between [active health check](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#core-healthcheck) and [LBEndpoint.heath_status](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto.html#config-endpoint-v3-lbendpoint), when will the health_status take effect?

I can explicitly set the health_status for each endpoint, but seems never take effect when active health check is configured. What's the initial health flag of an endpoint for the first time added/EDS push the same endpoint? I expected it should be unknown or healthy (reference: [Enum config.core.v3.HealthStatus](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#enum-config-core-v3-healthstatus)) after being added until the first time active health check returns, but I always get unhealthy while health_status is set to 1.

Since I don't find any document says that the two things are conflicted.

2> When starting a health check,  before the health check finished, whether the upstream node is still in load balance list and can still receive new traffic?

Just need a clarification, in my practice envoy will not temporary remove the endpoint from load balance list and it will follow the previous health flag until active health check complete.

cluster setting: 
```
- name: upstream_cluster
  connect_timeout: 2s
  type: EDS
  lb_policy: RANDOM
  upstream_connection_options:
    tcp_keepalive: {}
  common_lb_config:
    healthy_panic_threshold:
      value: 0       # disable panic
  health_checks:
  - timeout: 2s
    interval: 5s
    initial_jitter: 10s
    unhealthy_threshold: 1
    healthy_threshold: 1
    http_health_check: 
      path: "/ready"
    event_log_path: "/dev/stdout"
  eds_cluster_config:
    service_name: upstream_endpoint
    eds_config:
      ads: {}
```
