### ISSUE TITLE
aws_request_signing and aws_lambda not working for Lambda invocations having request body

### ISSUE THREAD

**Issue by sagital** [envoyproxy/envoy#14148]
*Title*:  Lambda and AWS Signature not working 

*Description*:
If I use the `envoy.filters.http.aws_lambda` filter to call a remote lambda using POST and a JSON body, AWS responds with 
`"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."` 

*Repro steps*:

`curl -X POST -H "Content-Type:application/json" localhost:10000/link-token-development -d '{"userId": 1 }'`

*Config*:
```
          http_filters:
          - name: envoy.filters.http.aws_lambda
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.aws_lambda.v3.Config
              arn: "arn:aws:lambda:eu-central-1:****:function:link-token-development"
              payload_passthrough: true


          - name: envoy.filters.http.router

          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: lambda_egress_gateway


  clusters:
  - name: lambda_egress_gateway
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    metadata:
      filter_metadata:
        com.amazonaws.lambda:
          egress_gateway: true
    load_assignment:
      cluster_name: lambda_egress_gateway
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address:  lambda.eu-central-1.amazonaws.com
                port_value: 443


    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: "*.amazonaws.com"


```

*Logs*:
```
[2020-11-23 18:45:26.033][466009][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:837] [C0][S877836865243054260] request headers complete (end_stream=false):
':authority', 'localhost:10000'
':path', '/2015-03-31/functions/link-token-development/invocations'
':method', 'POST'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'content-type', 'application/json'
'content-length', '14'
[2020-11-23 18:45:26.033][466009][debug][aws] [external/envoy/source/extensions/common/aws/credentials_provider_impl.cc:41] Getting AWS credentials from the environment
[2020-11-23 18:45:26.033][466009][debug][aws] [external/envoy/source/extensions/common/aws/credentials_provider_impl.cc:54] Found following AWS credentials in the environment: AWS_ACCESS_KEY_ID=*****, AWS_SECRET_ACCESS_KEY=*****, AWS_SESSION_TOKEN=
[2020-11-23 18:45:26.033][466009][debug][http] [external/envoy/source/extensions/common/aws/signer_impl.cc:65] Canonical request:
POST
/2015-03-31/functions/link-token-development/invocations

accept:*/*
content-length:14
content-type:application/json
user-agent:curl/7.64.1
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20201123T164500Z
x-request-id:4c4e50be-0072-4f50-b115-cf191282a412


accept;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-request-id
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[2020-11-23 18:45:26.033][466009][debug][http] [external/envoy/source/extensions/common/aws/signer_impl.cc:69] String to sign:
AWS4-HMAC-SHA256
20201123T164500Z
20201123/eu-central-1/lambda/aws4_request
bbc8982765b591a9d1749da2fac14bf7a11b2239adad02cca9eecb0179770bf9

...


[2020-11-23 18:45:26.189][466009][debug][http] [external/envoy/source/common/http/conn_manager_impl.cc:1435] [C0][S877836865243054260] encoding headers via codec (end_stream=false):
':status', '403'
'date', 'Mon, 23 Nov 2020 16:45:26 GMT'
'content-type', 'application/json'
'content-length', '192'
'x-amzn-requestid', 'c7ffecc3-d26c-42fd-93fa-9d66924c672f'
'x-amzn-errortype', 'InvalidSignatureException'
'x-envoy-upstream-service-time', '154'
'server', 'envoy'


```
