### ISSUE TITLE
Could suppport variables mode for `via` directive and like logformat.

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#14142]
Could suppport variables mode for `via` directive and like logformat. forexample：

```
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          via: %HOSTNAME%

```
