### ISSUE TITLE
 envoy.filters.http.aws_lambda payload_passthrough false not working

### ISSUE THREAD

**Issue by sagital** [envoyproxy/envoy#14149]
*Title*: *payload_passthrough* parameter is not changing the request

*Description*:
Setting the `payload_passthrough` parameter to `true` or `false` doesn't change the request. As I understood, setting it to false should convert the request to a JSON payload 
```{
    "rawPath": "/path/to/resource",
    "method": "GET|POST|HEAD|...",
    "headers": {"header-key": "header-value", ... },
    "queryStringParameters": {"key": "value", ...},
    "body": "...",
    "isBase64Encoded": true|false
}
```

*Repro steps*:
 ```curl -X POST -H "Content-Type:application/json" localhost:10000/2015-03-31/functions/link-token-development/invocations -d '{"userId": 1 }'```

*Config*:
```
          http_filters:
          - name: envoy.filters.http.aws_request_signing
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
              service_name: lambda
              region: eu-central-1
              host_rewrite: lambda.eu-central-1.amazonaws.com

          - name: envoy.filters.http.aws_lambda
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.aws_lambda.v3.Config
              arn: "arn:aws:lambda:eu-central-1:111111111:function:link-token-development"
              payload_passthrough: false
```

**Comment by sagital** [comment]
Closing this, looks like I was missing a configuration option: 

```
metadata:
  filter_metadata:
    com.amazonaws.lambda:
      egress_gateway: true
```
