### ISSUE TITLE
Error using certificate rotation support for certificates in static resources.

### ISSUE THREAD

**Issue by aejeet** [envoyproxy/envoy#14151]
**Description** 

**Envoy version: 1.15.2**

I am trying to make envoy pickup the renewed certs automatically. My envoy config looks like following

Relevant portions of envoy config
```
transport_socket:
   name: envoy.transport_sockets.tls
   typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
      common_tls_context:
      tls_certificate_sds_secret_configs:
         sds_config:
            path: /envoy/envoy-sds.yaml
      validation_context: {}
      alpn_protocols:
      - h2
      - http/1.1
```

Contents of envoy-sds.yaml
```
resources:
- "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
  tls_certificate:
    certificate_chain:
      filename: "/secrets/tls.crt"
    private_key:
      filename: "/secrets/tls.key"
```

This works as expected but sometimes envoy fails to start with following error
```
unable to add filesystem watch for file /envoy/envoy-sds.yaml: No space left on device
failed to watch file 
```

This goes away restarting the erring pods. 
Has others encountered similar issue ? If so how to fix this ?

Any pointers will be very helpful
