### ISSUE TITLE
How about add HeaderMatch for http local ratelimit?

### ISSUE THREAD

**Issue by ydh926** [envoyproxy/envoy#14161]
*Title*: *HeaderMatch for http local ratelimit*

*Description*:

For example, limit a special user's request, we may need HeaderMatch in limit config , like this:
```yaml
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 1
                tokens_per_fill: 1
                fill_interval: 600s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              match:
                  name: x-user
                  exact_match: Bill
                  invert_match: false
```
