### ISSUE TITLE
Using Local reply modification

### ISSUE THREAD

**Issue by karthequian** [envoyproxy/envoy#14203]
How do you use the Local Reply Modification feature?

I was reading about the local reply modification feature: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/local_reply.html?highlight=mapper and was looking to add the mapper to change the HTTP Response text that would be returned in a fault scenario.

```
mappers:
- filter:
    status_code_filter:
      comparison:
        op: EQ
        value:
          default_value: 400
          runtime_key: key_b
  headers_to_add:
    - header:
        key: "foo"
        value: "bar"
      append: false
  status_code: 401
  body:
    inline_string: "not allowed"
```

However, I'm not sure where to add this in the envoy config. I've tried adding this to the top level of `envoy.filters.network.http_connection_manager`, but I don't think it's the right spot for it, and wasn't sure how to add it to the `http_filters` section.

I keep getting the following error:
```
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0].filters[0]) mappers: Cannot find field.) has unknown fields
```

Any help would be appreciated, and I can go back to update the docs to make it clearer if needed!

**Comment by mk46** [comment]
@karthequian I think you're adding it to the wrong place. HCM has local_reply_config and config should be added like below.
```
filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
          local_reply_config:
            mappers:
            - filter:
                status_code_filter:
                  comparison:
                   op: EQ
                   value:
                     default_value: 400
                     runtime_key: key_b
              headers_to_add:
                - header:
                    key: "foo"
                    value: "bar"
                  append: false
              status_code: 401
              body:
                inline_string: "not allowed"
    
```

**Comment by karthequian** [comment]
Thank you so much @mk46! Really useful to see the whole config. Will try it today and close this issue!

**Comment by mk46** [comment]
Hi @karthequian, LMK if you still facing any issue with configuration otherwise we should close this.

**Comment by karthequian** [comment]
This can be closed. Thanks @mk46

**Comment by elvizlai** [comment]
Looks like this feature not woking?
```
        - filter_chain_match:
            server_names: ["api.example.com"]
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                alpn_protocols:
                  - "h2,http/1.1"
                tls_certificates:
                  - certificate_chain:
                      filename: "/etc/envoy/cert/api.example.com.crt"
                    private_key:
                      filename: "/etc/envoy/cert/api.example.com.key"
              require_client_certificate: true
          filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_https_api
                use_remote_address: true
                preserve_external_request_id: true
                always_set_request_id_in_response: true
                http2_protocol_options:
                  max_concurrent_streams: 100
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: api
                      domains: ["api.example.com"]
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,x-api-env,token
                        expose_headers: authorization,grpc-status,grpc-message,token
                        max_age: "1728000"
                        allow_credentials: true
                      routes:
                        - match: { prefix: "/xxx/" }
                          route:
                            { cluster: server-xxx, timeout: { seconds: 60 } }
                        - match: { prefix: "/" }
                          direct_response:
                            status: 200
                            body:
                              inline_string: "hello, this is api server"
                http_filters:
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
                local_reply_config:
                  mappers:
                    - filter:
                        status_code_filter:
                          comparison:
                            value:
                              default_value: 500
                              runtime_key: "%RESPONSE_CODE%"
                      status_code: 400
```

What I want is when visit https://api.example.com/xxx/yyy with status 500 return convert to status 400
