### ISSUE TITLE
Envoy failing requests toward rate limit service

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#14232]
We are in process of setting up rate limit service for our edge Envoys and so far looks like Envoy is failing to send requests to rate limit service:
```
ratelimit::10.173.11.194:8081::cx_active::4
ratelimit::10.173.11.194:8081::cx_connect_fail::0
ratelimit::10.173.11.194:8081::cx_total::4
ratelimit::10.173.11.194:8081::rq_active::0
ratelimit::10.173.11.194:8081::rq_error::7
ratelimit::10.173.11.194:8081::rq_success::0
ratelimit::10.173.11.194:8081::rq_timeout::0
ratelimit::10.173.11.194:8081::rq_total::7
ratelimit::10.173.11.194:8081::hostname::
ratelimit::10.173.11.194:8081::health_flags::healthy
ratelimit::10.173.11.194:8081::weight::1
ratelimit::10.173.11.194:8081::region::
ratelimit::10.173.11.194:8081::zone::
ratelimit::10.173.11.194:8081::sub_zone::
ratelimit::10.173.11.194:8081::canary::false
ratelimit::10.173.11.194:8081::priority::0
ratelimit::10.173.11.194:8081::success_rate::-1.0
ratelimit::10.173.11.194:8081::local_origin_success_rate::-1.0
```

Rate limit service config:
```
domain: messaging
descriptors:
  - key: foo
    rate_limit:
      unit: minute
      requests_per_unit: 3
  - key: foo
    rate_limit:
      unit: day
      requests_per_unit: 10
```

Envoy rate limit cluster config:
```
  - name: ratelimit
    connect_timeout: 5s
    type: STATIC
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ratelimit
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: x.x.x.x
                    port_value: 8081 
```

Envoy filter chain config:
```
      filters:
      - name: "envoy.http_connection_manager"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          upgrade_configs:
          - upgrade_type: "websocket"
            enabled: true
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536
            initial_connection_window_size: 1048576 # 1 MiB
            allow_connect: true
          tracing:
            overall_sampling:
              value: 1
            provider:
              name: envoy.tracers.opencensus
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.OpenCensusConfig
                zipkin_exporter_enabled: true
                zipkin_url: http://tracing-${SPOTIFY_DOMAIN}:80/api/v2/spans
                incoming_trace_context: [ CLOUD_TRACE_CONTEXT, GRPC_TRACE_BIN ]
                outgoing_trace_context: [ CLOUD_TRACE_CONTEXT, GRPC_TRACE_BIN ]
          common_http_protocol_options:
            idle_timeout: 600s
          drain_timeout: 5s # Should be longer than lb healthchecker's unhealthy threshold
          http_filters:
          - name: envoy.filters.http.ratelimit
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit"
              domain: "messaging"
              failure_mode_deny: true
              timeout: 3s
              stage: 0
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: ratelimit 
...
```
Per vhost/route config:
```
      {
        "name": "secret-domain-virtualhost",
        "domains": [
         "secret-domain.com"
        ],
        "routes": [
         {
          "match": {
           "path": "/v1/200",
           "case_sensitive": false
          },
          "route": {
           "cluster": "noop-http",
           "timeout": "300s",
           "retry_policy": {
            "retry_on": "5xx",
            "num_retries": 0
           },
           "rate_limits": [
            {
             "actions": [
              {
               "request_headers": {
                "header_name": "foo",
                "descriptor_key": "foo"
               }
              }
             ]
            }
           ]
          },
```
Error in rate limit service log:
```
DEBU[0091] caught error during call
```
Testing with following command and getting 500 as response.
```
curl -k -H "Host: secret-domain.com" -H "foo: jjdjdls" --resolve "secret-domain.com:8443:1x.x.x.x" https://secret-domain.com:8443/v1/200 -v
```
Rate limiter, Envoy, redis, control plane and ext authz are all running on same host if it matters.
