### ISSUE TITLE
Error running the example from Documentations

### ISSUE THREAD

**Issue by neonelect** [envoyproxy/envoy#14272]
*Title*: *Error parsing envoy config from documentation*

*Description*:
I'm trying to run the EDS example from https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples

Envoy gives me an error:

> Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[1].typed_extension_protocol_options[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.upstreams.http.v3.HttpProtocolOptions for type Any)

my config is just copy-paste from the exmples:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 127.0.0.1, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: some_service }
                http_filters:
                  - name: envoy.filters.http.router
  clusters:
    - name: some_service
      connect_timeout: 0.25s
      lb_policy: ROUND_ROBIN
      type: EDS
      eds_cluster_config:
        eds_config:
          api_config_source:
            api_type: GRPC
            grpc_services:
              - envoy_grpc:
                  cluster_name: xds_cluster
    - name: xds_cluster
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              connection_keepalive:
                interval: 30s
                timeout: 5s
      upstream_connection_options:
        # configure a TCP keep-alive to detect and reconnect to the admin
        # server in the event of a TCP socket half open connection
        tcp_keepalive: {}
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 55332
```

I've only changed the port at the end

**Comment by phlax** [comment]
@neonelect i think the problem  is that there is incorrect indentation on `load_assignment`

it should be a child of `upstream_connection_options`

could you test and confirm that fixes the issue ?

if it does - feel free to PR  - or i can

**Comment by phlax** [comment]
im wondering why it isnt picked up by config tests

**Comment by phlax** [comment]
Testing locally - i also see this error 

the problem seems to be with
```
"@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
```

Checking the docs there are quite a few occurrences of this and they seem to fail with the same problem

**Comment by phlax** [comment]
Im also  checking configs in the `/configs` dir that use `HttpProtocolOptions` and they are also failing locally

**Comment by phlax** [comment]
seems related to changes here https://github.com/envoyproxy/envoy/commit/7554d61bccf136638bdfb383c10d049dc8bd3790

**Comment by phlax** [comment]
@neonelect pull the latest docker image and it should work

**Comment by neonelect** [comment]
Ok checking

**Comment by neonelect** [comment]
Now:

type.googleapis.com/envoy.api.v2.ClusterLoadAssignment: node 'id' and 'cluster' are required.

**Comment by phlax** [comment]
you need to either:

- add to envoy start command
- add to config

**Comment by phlax** [comment]
see here https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem#node

**Comment by neonelect** [comment]
Works :) Thanks!!

**Comment by Kurounin** [comment]
I'm now getting the same error `Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[0].typed_extension_protocol_options[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.upstreams.http.v3.HttpProtocolOptions for type Any):` using the https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples#dynamic configuration:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster

static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options:
            # Configure an HTTP/2 keep-alive to detect connection issues and reconnect
            # to the admin server if the connection is no longer responsive.
            connection_keepalive:
              interval: 30s
              timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5678
```
