### ISSUE TITLE
Failed to load incomplete certificate from

### ISSUE THREAD

**Issue by qingyunha** [envoyproxy/envoy#14354]
*Title*: *Failed to load incomplete certificate from*

*Repro steps*:
>  openssl req -x509 -newkey rsa -keyout serverkey.pem -out servercert.pem -days 365

*Config*:
```yaml
static_resources:
  listeners:
  - name: listener_0
    address: { socket_address: { address: 0.0.0.0, port_value: 10000 } }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: default
              domains: "*"
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: some_service
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain: { filename: "certs/servercert.pem" }
                private_key: { filename: "certs/serverkey.pem" }
                password: {inline_string: "12345" }
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 12345
```

*Logs*:
```
[2020-12-10 05:50:54.013][9848][info][config] [source/server/configuration_impl.cc:80] loading 1 listener(s)
[2020-12-10 05:50:54.015][9848][critical][main] [source/server/server.cc:107] error initializing configuration 'envoy-demo-https.yaml': Failed to load incomplete cert
ificate from certs/servercert.pem, certs/serverkey.pem
[2020-12-10 05:50:54.016][9848][info][main] [source/server/server.cc:770] exiting
Failed to load incomplete certificate from certs/servercert.pem, certs/serverkey.pem
```
