### ISSUE TITLE
Envoy throughput limit when used as gRPC load balancer

### ISSUE THREAD

**Issue by kpitik** [envoyproxy/envoy#14422]
*Title*: *Envoy throughput limit when used as gRPC load balancer*

*Description*:
I am trying to use Envoy as load balancer for simple gRPC echo server. 
I am using docker-compose to create several instances of gRPC service and then put Envoy proxy 
in from of them. I use [ghz](https://github.com/bojand/ghz) to measure the RPS.
When I check CPU usage of each gRPC service using _docker stats_ load seems to be 
distributed equally among all gRPC services, however RPS stays the same no matter how many instances 
of gRPC services I create, shouldn't RPS rise linearly with number of gRPC service instances?

gRPC service I am using is a simple echo server that just returns request message, [here](https://github.com/Dauren2495/grpc-echo) is code.

[optional *Relevant Links*:]

**envoy.yaml**
```
static_resources:
  listeners:
  - name: listener_samir
    address:
      socket_address: { address: 0.0.0.0, port_value: 10620 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/pb.Echo/Echo" }
                route: 
                  cluster: echo_service
              cors:
                allow_origin_string_match:
                  - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive, authorization, user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                expose_headers: grpc-hostname, grpc-status,grpc-message
          http_filters:
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: echo_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: echo
                port_value: 5555

```
**docker-compose.yaml**
```
version: '3'
services: 
  envoy: 
    image: envoyproxy/envoy:v1.16-latest
    ports: 
      - 10620:10620
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
  echo:
    image:dauren2495/grpc-echo:no-auth
```
