### ISSUE TITLE
aws_lambda_filter: signature exception because of missing Host header

### ISSUE THREAD

**Issue by cip123** [envoyproxy/envoy#14435]
*Title*: *aws_lambda_filter: signature exception because of missing Host header*

*Description*:
When sending a request to Envoy proxy which is configured to use the `aws_lambda_filter`,

    curl -v  http://localhost:9500/lambda -d '{}'

 I get:

`{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}`

However, the request passes through if I explicitly pass in the Host header:

    curl -v -H "Host: localhost" http://localhost:9500/lambda -d '{}

*Config*:
```
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout

                route_config:
                  name: local_routes
                  virtual_hosts:
                    - name: local_services
                      domains: ["*"]
                      routes:
                      - match:
                          prefix: "/lambda"
                        route:
                          cluster: lambda_egress_gateway

                http_filters:
                  - name: envoy.filters.http.aws_lambda
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_lambda.v3.Config
                      arn: "arn:aws:lambda:us-east-1:*:function:lambda-sync-test"

                  - name: envoy.filters.http.router

  clusters:
    - name: lambda_egress_gateway
      connect_timeout: 2s
      type: LOGICAL_DNS

      metadata:
        filter_metadata:
          # Required to enable the Lambda proxying
          com.amazonaws.lambda:
            egress_gateway: true

      load_assignment:
        cluster_name: lambda_egress_gateway
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: lambda.us-east-1.amazonaws.com
                      port_value: 443
```

*Logs*:
```
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.675Z][27][debug][http] [source/extensions/common/aws/signer_impl.cc:65] Canonical request:
lambdaintegrationproxy_1  | POST
lambdaintegrationproxy_1  | /2015-03-31/functions/lambda-sync-test/invocations
lambdaintegrationproxy_1  |
lambdaintegrationproxy_1  | accept:*/*
lambdaintegrationproxy_1  | content-length:313
lambdaintegrationproxy_1  | content-type:application/json
lambdaintegrationproxy_1  | host:localhost:9500
lambdaintegrationproxy_1  | user-agent:curl/7.64.1
lambdaintegrationproxy_1  | x-amz-content-sha256:936614fabd15529e2a7fbd95a3f9338fc996affca63eaf3949ef776e919518b3
lambdaintegrationproxy_1  | x-amz-date:20201216T092800Z
lambdaintegrationproxy_1  | x-amz-invocation-type:RequestResponse
lambdaintegrationproxy_1  | x-request-id:67821493-9a11-44d9-95aa-a6e286c17602
lambdaintegrationproxy_1  |
lambdaintegrationproxy_1  | accept;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id
lambdaintegrationproxy_1  | 936614fabd15529e2a7fbd95a3f9338fc996affca63eaf3949ef776e919518b3
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.675Z][27][debug][http] [source/extensions/common/aws/signer_impl.cc:69] String to sign:
lambdaintegrationproxy_1  | AWS4-HMAC-SHA256
lambdaintegrationproxy_1  | 20201216T092800Z
lambdaintegrationproxy_1  | 20201216/us-east-1/lambda/aws4_request
lambdaintegrationproxy_1  | c7e23d5b392e79dcd4954ecfe497daa0d2b77683d402cf077af52dfdecf38db7
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.675Z][27][debug][http] [source/extensions/common/aws/signer_impl.cc:76] Signing request with: AWS4-HMAC-SHA256 Credential=*/20201216/us-east-1/lambda/aws4_request, SignedHeaders=accept;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id, Signature=b6b5c645834a023b083077c8a7b71b7c13de1f054e98b1117b3f36e0a6f0628e
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.676Z][27][trace][http] [source/common/http/filter_manager.cc:594] [C2][S10929273255513552519] decode data called: filter=0x2dd6bfa86360 status=0
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.676Z][27][trace][http] [source/common/http/filter_manager.cc:54] [C2][S10929273255513552519] continuing filter chain: filter=0x2dd6bfa86360
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.676Z][27][debug][router] [source/common/router/router.cc:429] [C2][S10929273255513552519] cluster 'lambda_egress_gateway' match for URL '/2015-03-31/functions/lambda-sync-test/invocations'
lambdaintegrationproxy_1  | [2020-12-16T09:28:56.676Z][27][debug][router] [source/common/router/router.cc:586] [C2][S10929273255513552519] router decoding headers:
lambdaintegrationproxy_1  | ':authority', 'localhost:9500'
lambdaintegrationproxy_1  | ':path', '/2015-03-31/functions/lambda-sync-test/invocations'
lambdaintegrationproxy_1  | ':method', 'POST'
lambdaintegrationproxy_1  | ':scheme', 'https'
lambdaintegrationproxy_1  | 'user-agent', 'curl/7.64.1'
lambdaintegrationproxy_1  | 'accept', '*/*'
lambdaintegrationproxy_1  | 'content-length', '313'
lambdaintegrationproxy_1  | 'content-type', 'application/json'
lambdaintegrationproxy_1  | 'x-forwarded-proto', 'http'
lambdaintegrationproxy_1  | 'x-request-id', '67821493-9a11-44d9-95aa-a6e286c17602'
lambdaintegrationproxy_1  | 'x-amz-invocation-type', 'RequestResponse'
lambdaintegrationproxy_1  | 'x-amz-content-sha256', '936614fabd15529e2a7fbd95a3f9338fc996affca63eaf3949ef776e919518b3'
lambdaintegrationproxy_1  | 'x-amz-date', '20201216T092800Z'
lambdaintegrationproxy_1  | 'authorization', 'AWS4-HMAC-SHA256 Credential=*/20201216/us-east-1/lambda/aws4_request, SignedHeaders=accept;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id, Signature=b6b5c645834a023b083077c8a7b71b7c13de1f054e98b1117b3f36e0a6f0628e'
lambdaintegrationproxy_1  | 'x-envoy-expected-rq-timeout-ms', '15000'
.
.
.
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=Date value=Wed, 16 Dec 2020 09:28:56 GMT
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=Content-Type value=application/json
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=Content-Length value=192
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=Connection value=keep-alive
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=x-amzn-RequestId value=1b21704b-b3c4-46e3-8fd1-50f450459c34
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:632] [C3] onHeadersCompleteBase
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:470] [C3] completed header: key=x-amzn-ErrorType value=InvalidSignatureException
lambdaintegrationproxy_1  | [2020-12-16T09:28:57.055Z][27][trace][http] [source/common/http/http1/codec_impl_legacy.cc:1117] [C3] status_code 403
lambdaintegrationproxy_1  | ':status', '403'
lambdaintegrationproxy_1  | 'date', 'Wed, 16 Dec 2020 09:28:56 GMT'
lambdaintegrationproxy_1  | 'content-type', 'application/json'
lambdaintegrationproxy_1  | 'content-length', '192'
lambdaintegrationproxy_1  | 'x-amzn-requestid', '1b21704b-b3c4-46e3-8fd1-50f450459c34'
lambdaintegrationproxy_1  | 'x-amzn-errortype', 'InvalidSignatureException'
lambdaintegrationproxy_1  | 'x-envoy-upstream-service-time', '378'
lambdaintegrationproxy_1  | 'server', 'envoy'

```
