### ISSUE TITLE
 The subset_selectors of cluster subsets could add a `case_sensitive` switch to select host that match subsets metadata?

### ISSUE THREAD

**Issue by wangfakang** [envoyproxy/envoy#14438]
The [subset_selectors](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster-lbsubsetconfig-lbsubsetselector) of cluster subsets could add a case sensitive switch to select host that match subsets metadata? forexample：
```
    lb_subset_config:
      fallback_policy: ANY_ENDPOINT
      subset_selectors:
      case_sensitive: false
      - keys:
        - idc
        fallback_policy: ANY_ENDPOINT
    load_assignment:
      cluster_name: xx
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 1.1.1.1
                port_value: 8019
          metadata:
            filter_metadata:
              envoy.lb:
                idc: 'xx'
        - endpoint:
            address:
              socket_address:
                address: 1.1.1.1
                port_value: 8020
          metadata:
            filter_metadata:
              envoy.lb:
                idc: 'XX'
```
if request lb metadata is `xx`, then we could get `1.1.1.1:8019` or `1.1.1.1:8020` when case_sensitive is false.
