### ISSUE TITLE
%UPSTREAM_CLUSTER% in logs is empty in case of no_healthy_upstream

### ISSUE THREAD

**Issue by fxposter** [envoyproxy/envoy#14466]
*Title*: %UPSTREAM_CLUSTER% in logs becomes "-" when there are no healthy upstreams for the matching cluster.

*Description*:
Envoy should return proper %UPSTREAM_CLUSTER%, even if there were no requests made for that cluster.

*Config*:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.file_access_log
            config:
              path: /dev/stdout
              json_format:
                upstream_cluster: "%UPSTREAM_CLUSTER%"
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: my_service
          http_filters:
          - name: envoy.router
  clusters:
  - name: my_service
    connect_timeout: 1s
    type: static
    load_assignment:
      cluster_name: "my_service"
      endpoints:
      - lb_endpoints: []
```
*Logs*:
```
{"upstream_cluster":"-"}
 ```
