### ISSUE TITLE
1.16 can't disable timeout

### ISSUE THREAD

**Issue by hakuno** [envoyproxy/envoy#14477]
Hey there, how are you?

Today I had to make a downgrade version.

The 1.16 is unable to shut down the timeout properly.

The configuration is below. I tried many ways to make the timeout be disabled. But no success in the end.

```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
#common_http_protocol_options:
#  idle_timeout: 3600s # 1 hour
#  headers_with_underscores_action: REJECT_REQUEST
          stream_idle_timeout: 0s
          request_timeout: 0s
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "" }
                route: { cluster: servicex }
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: servicex
    connect_timeout: 10s
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    type: STATIC
    lb_policy: LEAST_REQUEST
    http_protocol_options: {}
    load_assignment:
      cluster_name: servicex
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: XXX
                port_value: 80
        - endpoint:
            address:
              socket_address:
                address: XXX
                port_value: 80
    health_checks:
      timeout: 10s
      unhealthy_threshold: 2
      healthy_threshold: 2
      interval: 30s
      http_health_check: { path: "/", expected_statuses: { start: 200, end: 404 } }
      event_log_path: "/var/log/service.log"
      always_log_health_check_failures: true
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 100000000
          max_requests: 100000000
        - priority: HIGH
          max_connections: 100000000
          max_requests: 100000000
```
