### ISSUE TITLE
Envoy responds with `route_not_found` even if there is a valid route

### ISSUE THREAD

**Issue by koustubh25** [envoyproxy/envoy#14490]
*Title*: *Envoy responds with `route_not_found` even if there is a valid route*

*Description*:

I have the following envoy configuration

```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          common_http_protocol_options:
            idle_timeout: 300s
          use_remote_address: false
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/token"
                  query_parameters:
                    - name: requested_token_type
                      string_match: 
                          exact: mytokentype
                  headers:
                  - name: ":method"
                    exact_match: "POST"
                  tls_context:
                    presented: false
                    validated: true
                route:
                  host_rewrite_literal: myendpoint
                  prefix_rewrite: /token
                  cluster: frig_internal_sit
          http_filters:
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              certificate_chain:
                filename: /etc/ssl/listener/cert.pem
              private_key:
                filename: /etc/ssl/listener/key.pem
            validation_context:
              trusted_ca:
                filename: /etc/ssl/cluster/cabundle.pem
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_3

  clusters:
  - name: frig_internal_sit
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    common_http_protocol_options:
      idle_timeout: 300s
    load_assignment:
      cluster_name: frig_internal_sit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: myendpoint
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: myendpoint
        common_tls_context:
          tls_certificates:
            certificate_chain:
              filename: /etc/ssl/listener/cert.pem
            private_key:
              filename: /etc/ssl/listener/key.pem
          validation_context:
            trusted_ca:
              filename: /etc/ssl/cluster/cabundle.pem
          tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_3
        allow_renegotiation: false
```

There is only one-way tls for both upstream (envoy verifies upstream endpoint) and downstream clusters (envoy verifies downstream endpoint) 

I use the curl command to query it like this

```
curl -k -i --location --request POST 'https://localhost/token?requested_token_type=mytokentype \
--header 'x-request-id: cfbd178b-4997-44c4-afdc-f9158d7fb933' \
--header 'Authorization: Bearer tokendata' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'x-correlation-id: cfbd178b-4997-44c4-afdc-f9158d7fb955' \
--data-urlencode 'client_id=myclient' \
--data-urlencode 'client_secret=mypassword' \
--data-urlencode 'scope=myscope' \
--data-urlencode 'ocvId=2345' \
--data-urlencode 'personaType=mypersona' \
--cacert ca.pem \
--cert mtls_cert.pem \
--key mtls_key.pem \
--pass mycertpass \
--tlsv1.2 --tls-max 1.2
```

However, I get a 404 response with the following in the logs

```
relation-id value=cfbd178b-4997-44c4-afdc-f9158d7fb955
T1221 06:32:28.411 23 envoy] [23][http][source/common/http/http1/codec_impl.cc:642] [C0] onHeadersCompleteBase
T1221 06:32:28.411 23 envoy] [23][http][source/common/http/http1/codec_impl.cc:478] [C0] completed header: key=Content-Length value=105
T1221 06:32:28.411 23 envoy] [23][http][source/common/http/http1/codec_impl.cc:862] [C0] Server: onHeadersComplete size=8
D1221 06:32:28.411 23 envoy] [23][http][source/common/http/conn_manager_impl.cc:808] [C0][S370773444708327794] request headers complete (end_stream=false):
':authority', 'localhost'
':path', '/token?requested_token_type=mytokentype'
':method', 'POST'
'user-agent', 'curl/7.69.1'
'accept', '*/*'
'x-request-id', 'cfbd178b-4997-44c4-afdc-f9158d7fb933'
'authorization', 'Bearer tokendata'
'content-type', 'application/x-www-form-urlencoded'
'x-correlation-id', 'cfbd178b-4997-44c4-afdc-f9158d7fb955'
'content-length', '105'

D1221 06:32:28.411 23 envoy] [23][router][source/common/router/router.cc:361] [C0][S370773444708327794] no cluster match for URL '/token?requested_token_type=StaffJWT'
D1221 06:32:28.411 23 envoy] [23][http][source/common/http/conn_manager_impl.cc:1520] [C0][S370773444708327794] Sending local reply with details route_not_found
D1221 06:32:28.411 23 envoy] [23][http][source/common/http/conn_manager_impl.cc:1777] [C0][S370773444708327794] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Mon, 21 Dec 2020 06:32:28 GMT'
'server', 'envoy'
'connection', 'close'

T1221 06:32:28.411 23 envoy] [23][connection][source/common/network/connection_impl.cc:427] [C0] writing 116 bytes, end_stream false
D1221 06:32:28.411 23 envoy] [23][http][source/common/http/conn_manager_impl.cc:207] [C0][S370773444708327794] doEndStream() resetting stream
D1221 06:32:28.411 23 envoy] [23][http][source/common/http/conn_manager_impl.cc:2007] [C0][S370773444708327794] stream reset
```

Not quite sure, why the route for `/token` is not getting matched.
Using Envoy version 1.15.0
