### ISSUE TITLE
RBACPerRoute configuration not working!

### ISSUE THREAD

**Issue by sefaphlvn** [envoyproxy/envoy#14523]
*Per route RBAC configuration not working.*

*Description*:
>Everything looks ok envoy is running but RBAC doesn't work. Here is the configuration.

```
direct_response:
  body:
    inline_string: Hello world
  status: '200'
match:
  case_sensitive: false
  prefix: "/test"
typed_per_filter_config:
  envoy.filters.http.rbac:
    "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
    rbac:
      rules:
        action: DENY
        policies:
          general-rules:
            permissions:
            - any: true
            principals:
            - any: true
```

Is there something i missed?

*Resolution:*
This is should be in http filter
```
name: envoy.filters.network.rbac
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
```

**Comment by alexandru-ersenie** [comment]
Hey, 
i am facing a similar problem and i cannot get the end of it.

So this is my config right now. My expectation is that all requests on /products will be dropped, unless they are GET requests.

But this doesn't work, and i have tried pretty much everything. It is also funny that i do not get any stats regarding RBAC. It is almost as it would ccompletely ignore my rbac config


Would you please take a look at my config file, maybe i am missing on something.

Thx a lot!



```resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        route_config:
          name: local_route
          virtual_hosts:
          - name: all
            domains:
            - "*"
            routes:
            - name: myroute
              match:
                prefix: "/client"
              route:
                #host_rewrite_literal: www.envoyproxy.io
                cluster: targetCluster              
            - name: products
              match:
                prefix: "/products"
              direct_response:
                status: 403
                body:
                  inline_string: "denied\n"
              typed_per_filter_config:
                envoy.filters.http.rbac:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
                  rbac:
                    rules:
                      action: ALLOW
                      policies:
                        "policy1":
                          permissions:
                          - and_rules:
                              rules:
                              - header: { name: ":method", exact_match: "GET" }
                              - url_path:
                                  path: { prefix: "/products" }
                          principals:
                          - any: true
        http_filters:
        - name: envoy.filters.http.router
        access_log:
        - name: envoy.access_loggers.file
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: /var/log/envoy/envoy-access.log
            json_format:
              timestamp: "%START_TIME(%Y/%m/%dT%H:%M:%S%z)%"
              method: "%REQ(:METHOD)%"
              path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
              protocol: "%PROTOCOL%"
              response: "%RESPONSE_CODE%"
              response_flags: "%RESPONSE_FLAGS%"
              bytes_rcv: "%BYTES_RECEIVED%"
              bytes_snt: "%BYTES_SENT%"
              duration: "%DURATION%"
              ups_svc_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
              x-fwd_for: "%REQ(X-FORWARDED-FOR)%"
              user_agent: "%REQ(USER-AGENT)%"
              req_id: "%REQ(X-REQUEST-ID)%"
              req_authority: "%REQ(:AUTHORITY)%"
              upstream: "%UPSTREAM_HOST%"
              details: "%RESPONSE_CODE_DETAILS%"
              route: "%ROUTE_NAME%"
              source: "%DOWNSTREAM_REMOTE_ADDRESS%"
              orig_source: "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS%"
    transport_socket:
     name: envoy.transport_sockets.tls
     typed_config:
       "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
       common_tls_context:
         tls_certificates:
           certificate_chain:
              filename: /etc/httpd/ssl/wildcard.mydom.com.crt
           private_key:
              filename: /etc/httpd/ssl/wildcard.mydom.com.key```

**Comment by LironEr** [comment]
I faced the same problem, but managed to solve it by adding RBAC filter to http_filters, then overriding it per route

```yaml
filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              upgrade_configs:
                - upgrade_type: websocket
              codec_type: AUTO
              server_header_transformation: PASS_THROUGH
              http_filters:
                - name: envoy.filters.http.rbac
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                    rules:
                      action: DENY
                      policies:
                        'per-route-rule':
                          permissions:
                            - any: true
                          principals:
                            - any: true
```


per route:
```yaml
- name: cluster
  domains:
    - 'xxxxxxxxxxx'
  routes:
    - match:
        prefix: '/'
      route:
        cluster: some_cluster
  typed_per_filter_config:
    # enforce JWT token
    envoy.filters.http.jwt_authn:
      '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
      requirement_name: 'default_req'
    envoy.filters.http.rbac:
      '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
      rbac:
        rules:
          action: ALLOW
          policies:
            'allow-user':
              permissions:
                - any: true
              principals:
                - metadata:
                    filter: envoy.filters.http.jwt_authn
                    path:
                      - key: payload
                      - key: sub
                    value:
                      string_match:
                        exact: 'xxxxxxxxx'
```
