### ISSUE TITLE
Error when using envoy.extensions.upstreams.http.v3.HttpProtocolOptions

### ISSUE THREAD

**Issue by Kurounin** [envoyproxy/envoy#14545]
*Title*: *Error when using envoy.extensions.upstreams.http.v3.HttpProtocolOptions*

*Description*:
I'm getting the error `Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[0].typed_extension_protocol_options[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.upstreams.http.v3.HttpProtocolOptions for type Any)` using the latest envoyproxy/envoy:v1.16-latest and https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples#dynamic configuration
I mentioned the error on https://github.com/envoyproxy/envoy/issues/14272, but that issue is closed.

*Repro steps*:
Start envoy proxy docker image with the config from https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples#dynamic

*Config*:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster

static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options:
            # Configure an HTTP/2 keep-alive to detect connection issues and reconnect
            # to the admin server if the connection is no longer responsive.
            connection_keepalive:
              interval: 30s
              timeout: 5s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5678
```
