### ISSUE TITLE
Any way to retry on mirrored traffic?

### ISSUE THREAD

**Issue by tydurd** [envoyproxy/envoy#14548]
Hi team,
I'm leveraging request_mirror_policy to mirror traffic to a logging service.
Occasionally (~0,0005% of total requests) I got a 503 (due to upstream_cx_destroy_remote_with_active_rq) from the logging service, therefore losing the request. I think retrying the failed request will be much, much easier than debug and solve the underlying issue (if 0,0005% of errors could be considered an issue).
Is there any way to implement retry on shadow traffic? Envoy version is 1.12.2
Thanks in advance for your support.

**Comment by mattklein123** [comment]
This is not possible today. As a total hack, you could forward the mirrored traffic back to the current Envoy and then get full functionality to do whatever you want.

**Comment by tydurd** [comment]
Thanks @mattklein123 for the heads-up.
By forwarding the mirrored traffic back to current envoy, how do I avoid traffic to hit again the same upstream?

```yml 
  virtual_hosts:
  - name: demohost
	domains:
	- "*"
	routes:
	- match:
	    prefix: "/" 
	  route:
	    cluster: localcluster
	    retry_policy:
	      retry_on: "5xx"
	      num_retries: 3
	    timeout: 60s
	    request_mirror_policy:
	      cluster: webappmirror
```
Say **_webappmirror_** cluster is the current envoy, how do avoid requests being sent again to **_localcluster_** as well?
