### ISSUE TITLE
Is Envoy supposed to run outside a Docker container?

### ISSUE THREAD

**Issue by virtumonde** [envoyproxy/envoy#14559]
Hi! I would like to know if Envoy is supposed to run outside of a Docker container (for prototyping purposes). I have this config where I am upgrading incoming connections to HTTPV2 so that they would be compatible with gRPC. The web client is accessing envoy on 8080 and is redirected to a gRPC server on 50051. Does it look ok? I am using macOS 10.15.6. Unfortunately this doesn't work at all as the client is not able to connect to the server.

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: echo_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 50051
```

**Comment by dio** [comment]
Sorry, if you run the gRPC server on your local (`localhost:50051`), I think the address should be "localhost" (instead of "0.0.0.0"), since you're setting the `type: LOGICAL_DNS`. You can set it as 127.0.0.1, but you need to use `type: STATIC`.

```yaml
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 50051
```

**Comment by virtumonde** [comment]
@dio, let me check if it works with ```localhost```.

**Comment by virtumonde** [comment]
Wow it's working! Thank you, @dio! I guess it was not working for me previously because I was changing all addresses to ```localhost``` instead of only the endpoint ones. Can you inform me why it is the case? I am not very familiar with Envoy.

**Comment by dio** [comment]
> because I was changing all addresses to localhost instead of only the endpoint

Ah sorry for not being clear. (I'm obviously simplifying things here) Envoy receives (connection) request through the listener, that listener needs to listen to a certain address (this needs to be resolvable, and static IP is supported) and port. Then envoy proxies this out through the cluster, then to the selected upstream endpoint.

(downstream) request -> envoy listener (ip:port) -> filters -> cluster -> (upstream) endpoint (ip:port).

A complete life-of-a-request is presented here: https://www.envoyproxy.io/docs/envoy/latest/intro/life_of_a_request.

**Comment by jizezhang** [comment]
Hello, I am facing the same issue even though I use `localhost` in my yaml file. My grpc server is running on localhost:8084, which I have confirmed. and below is my envoy yaml file. However I am still not able to connect to the server from client. The error I am getting is
```
[2023-11-04 09:42:52.727][2460878][debug][connection] [source/common/network/connection_impl.cc:1009] [Tags: "ConnectionId":"1"] connecting to [::1]:8084
[2023-11-04 09:42:52.727][2460878][debug][connection] [source/common/network/connection_impl.cc:1028] [Tags: "ConnectionId":"1"] connection in progress
[2023-11-04 09:42:52.727][2460878][trace][pool] [source/common/conn_pool/conn_pool_base.cc:131] not creating a new connection, shouldCreateNewConnection returned false.
```
and below is my envoy yaml:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8083
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/recommerce.aftermarketplace.lotting.LottingService/" }
                          route:
                            cluster: lotting_service
                            timeout: 0s
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: lotting_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: lotting_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 8084
```
Any insights on this? Thanks a lot!
