### ISSUE TITLE
Curl works but envoy as ingress-controller not in a kubernetes cluster

### ISSUE THREAD

**Issue by hatzhang** [envoyproxy/envoy#14555]
We are trying envoy with [contour ](https://projectcontour.io/)as kubernetes' ingress controller in a [Kind ](https://kind.sigs.k8s.io/docs/user/ingress/#contour)provisioned local cluster.
Inside envoy‘s container, we can curl auth-service:5000 with a 200, but when access through the ingress, curl  localhost/auth, it will end with a 404. 
Totally new to envoy, not even know how to begin to resolve this issue, please help！
The log inside envoy is like this:
>[2021-01-04T10:31:22.593Z] "GET /auth HTTP/1.1" 404 - 0 0 19 18 "10.244.0.30" "curl/7.64.0" "4f7e876a-aec1-45ba-a0c6-9b9cad5b41c2" "localhost" "10.244.0.35:5000"

Our service and pods are like the following.

```
$ kubectl get svc
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
contour-ingres         ClusterIP      10.96.45.228    <none>        8001/TCP                     128m
contour-ingres-envoy   LoadBalancer   10.96.80.87     <pending>     80:31369/TCP,443:32664/TCP   128m
auth-service   ClusterIP      10.96.20.105    <none>        5000/TCP                     17m
$ kubectl get pods -o wide
NAME                                      READY   STATUS    RESTARTS   AGE     IP            NODE                    NOMINATED NODE   READINESS GATES
bar-app                                   1/1     Running   0          144m    10.244.0.25   ingress-control-plane   <none>           <none>
contour-ingres-contour-6f989674f4-f7dd8   1/1     Running   0          116m    10.244.0.27   ingress-control-plane   <none>           <none>
contour-ingres-contour-6f989674f4-pvx96   1/1     Running   0          116m    10.244.0.28   ingress-control-plane   <none>           <none>
contour-ingres-envoy-8586x                2/2     Running   0          113m    10.244.0.30   ingress-control-plane   <none>           <none>
auth-deployment-785b9994d-xnrmc   1/1     Running   0          6m23s   10.244.0.35   ingress-control-plane   <none>           <none>
```
Ingress config:

```yaml
   http:
      paths:
      - backend:
          serviceName: auth-service
          servicePort: 5000
        path: /auth
        pathType: ImplementationSpecific"
```

**Comment by dio** [comment]
Seems like Envoy is responding, however, you need to provide "host" to the ingress CRD and the "Host" header to the request (for example, let's name the host: "auth-service.local"), something like:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth
  namespace: default
spec:
  rules:
  - host: auth-service.local
    http:
      paths:
      - backend:
          serviceName: auth-service
          servicePort: 5000
...
```

And then the request:

```
$ curl -H "Host: auth-service.local" localhost/auth
```

(This is under the assumption that you have setup the kind cluster correctly, which I think you have since envoy is responding to your request).
