### ISSUE TITLE
How to set more  gRPC-JSON transcoder in envoy.yaml

### ISSUE THREAD

**Issue by Demon520-coder** [envoyproxy/envoy#14602]
In my project,We want to one port proxy two gRPC services. So I create two grpc_json_transcoder in http_filter. But when I call 
the "https://192.168.5.103:8843/book.BookStore/GetBooksByAuthor?author=zzl",it responsed 404. Here is my envoy.yaml file.
```yaml
admin:
  access_log_path: /tmp/admin_access_9902.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9902 }

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: { address: 0.0.0.0, port_value: 5856 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: local_service
              domains:
              - ["*"]
              routes:
              - match: { prefix: "/" }                 
                route: { cluster: mvc, timeout: { seconds: 60 } }                  
          http_filters:
          - name: envoy.router
            config: {}
      
  - name: listener2
    address:
      socket_address: { address: 0.0.0.0, port_value: 8843 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/greet.Greeter" }
                route: { cluster: grpc, timeout: { seconds: 60 } }
              - match: { prefix: "/" }
                route: { cluster: mvc_https, timeout: { seconds: 60 } }
              - match: { prefix: "/book.BookStore" }
                route: { cluster: grpc_book, timeout: { seconds: 60 } }
          http_filters:
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/greet.pb"
              services: ["greet.Greeter"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
              auto_mapping: true

          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/book.pb"
              services: ["book.BookStore"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
              auto_mapping: true    
          - name: envoy.filters.http.router
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/envoy/certs/server_103.crt"
              private_key:
                filename: "/etc/envoy/certs/server_103.key"                

  clusters:
  - name: grpc
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}   
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
    load_assignment:
      cluster_name: grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.17.0.2
                port_value: 50053
            
                
  - name: mvc
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
    load_assignment:
      cluster_name: mvc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.17.0.3
                port_value: 50054


  - name: mvc_https
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    hosts:
    - socket_address:
       address: 172.17.0.4
       port_value: 50055
    transport_socket: 
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext  
   
   

  - name: grpc_book
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}   
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
    load_assignment:
      cluster_name: grpc_book
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.6.120
                port_value: 50057
```
Here is my book.BookStore proto file:
```proto
syntax = "proto3";

option csharp_namespace = "GrpcApp";

package book;

// The greeting service definition.
service BookStore {
  // Sends a greeting
  rpc GetBooksByAuthor (BookInputDto) returns (BooksOutputDto);
  rpc GetList (EmptyRequest) returns (BooksOutputDto);
  rpc AddBook (BookInfoDto) returns (OperResult);
}

// The request message containing the user's name.
message BookInputDto { 
  string author = 1;
}

message EmptyRequest{

}

message OperResult{
	string message=1;
	int32 code=2;
}

// The response message containing the greetings.
message BookInfoDto {
  string name = 1;
  string author = 2;
  double price = 3;
  bool enabled = 4;
  string ISBN= 5;
}

message BooksOutputDto{
	string message=1;
	repeated BookInfoDto bookList=2;
}
```
Is anyone can help me? Thank you very much!!!
