### ISSUE TITLE
Configure path header for envoy ratelimiting

### ISSUE THREAD

**Issue by minbaev** [envoyproxy/envoy#14618]
I'm trying to use envoy ratelimiting functionality and need to ratelimit based on the entire url in my request, e.g. https://myenvoy.com/path/to/smth

Here is a part of my envoy.yaml
```
routes:
                - match: { prefix: "/" }
                  route: 
                    cluster: backend
                    rate_limits:
                      - stage: 0
                        actions:
                          - {request_headers: {header_name: ":path", descriptor_key: "path"}}
```
When I run 
```
curl -k https://myenvoy.com/path/to/smth
```

The above configuration creates descriptor value **/path/to/smth** whereas I would like to have descriptor of value **https://myenvoy.com/path/to/smth**

Is it possible to configure that with envoy?

Thank you 

PS: I looked at these header values and tried to use some, but it didn't help
https://github.com/envoyproxy/envoy/blob/master/source/common/http/headers.h
