### ISSUE TITLE
double-proxy with mtls and route by domain name

### ISSUE THREAD

**Issue by luxurine** [envoyproxy/envoy#14626]
*Title*: *double-proxy with mtls and route by domain name*

*Description*:
These are two envoy proxy for different cluster to proxy raw tcp svc, like redis and mysql.
frontend envoy will have two port  listening (16379, 13306), acting as virturl svc for redis and mysql.
backend envoy will have only one port 10001 listening, acting as general proxy, and use tls domain name to indicate which svc to route to. The route map just like follow:
![image](https://user-images.githubusercontent.com/8802090/104145080-b0549b00-5400-11eb-9e24-091203642bfe.png)

frontend-envoy.yaml
```yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 7000
static_resources:
  listeners:
  - name: mysql_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 13306
    filter_chains:
    - filters:
      - name: envoy.filters.network.mysql_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
          stat_prefix: egress_mysql
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: mysql_tcp
          cluster: mysql_cluster
  - name: redis_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 16379
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: redis_tcp
          cluster: redis_cluster
  clusters:
  - name: mysql_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: proxy-mysql-backend.example.com
                port_value: 10001
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
            certificate_chain:
              filename: certs/proxy-mysql-frontend.example.com.crt
            private_key:
              filename: certs/example.com.key
          validation_context:
            # match_subject_alt_names:
            # - exact: proxy-mysql-backend.example.com
            trusted_ca:
              filename: certs/ca.crt
  - name: redis_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: proxy-redis-backend.example.com
                port_value: 10001
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
            certificate_chain:
              filename: certs/proxy-redis-frontend.example.com.crt
            private_key:
              filename: certs/example.com.key
          validation_context:
            # match_subject_alt_names:
            # - exact: proxy-redis-backend.example.com
            trusted_ca:
              filename: certs/ca.crt
```

backend-envoy.yaml
```yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 7001
static_resources:
  listeners:
  - name: postgres_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10001
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        transport_protocol: tls
        server_names:
          - proxy-mysql-backend.example.com
      filters:
      - name: envoy.filters.network.mysql_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
          stat_prefix: egress_mysql
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: mysql_tcp
          cluster: mysql_cluster
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificates:
              certificate_chain:
                filename: certs/proxy-mysql-backend.example.com.crt
              private_key:
                filename: certs/example.com.key
            validation_context:
              # match_subject_alt_names:
              # - exact: proxy-mysql-frontend.example.com
              trusted_ca:
                filename: certs/ca.crt
    - filter_chain_match:
        transport_protocol: tls
        server_names:
          - proxy-redis-backend.example.com
      filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: redis_tcp
          cluster: redis_cluster
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            tls_certificates:
              certificate_chain:
                filename: certs/proxy-redis-backend.example.com.crt
              private_key:
                filename: certs/example.com.key
            validation_context:
              # match_subject_alt_names:
              # - exact: proxy-redis-frontend.example.com
              trusted_ca:
                filename: certs/ca.crt
  clusters:
  - name: mysql_cluster
    connect_timeout: 1s
    type: STATIC
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3306
  - name: redis_cluster
    connect_timeout: 1s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6379
```

/etc/hosts
```text
127.0.0.1 proxy-redis-backend.example.com
127.0.0.1 proxy-mysql-backend.example.com
```

Then I try to connect frontend-envoy port 16379, but got this.
```text
redis-cli -h proxy-redis-backend.example.com -p 16379
proxy-redis-backend.example.com:16379> set foo bar
Error: Connection reset by peer
```

Do I misunderstand something or this way is  just not supported.

[*Relevant Links*:]
- https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/double-proxy
- https://github.com/envoyproxy/envoy/issues/5939
- https://github.com/budanm/Envoy-With-2way-SSL
