### ISSUE TITLE
[lua filter] response body can be REST while request body can not

### ISSUE THREAD

**Issue by ikingye** [envoyproxy/envoy#14627]
*Title*: *response body can be REST while request body can not*

*Description*:

## Original

```shell
curl -vd '{"foo":"FFEE"}' \
-H "Content-Type:application/json" \
http://localhost:8000/     
```

```                               
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.70.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 604
< etag: W/"25c-TE/ybmgiBBD9gg185WvVXUS15q4"
< date: Mon, 11 Jan 2021 07:52:26 GMT
< x-envoy-upstream-service-time: 3
< response-body-size: 604
< server: envoy
< 
{
  "path": "/",
  "headers": {
    "host": "localhost:8000",
    "user-agent": "curl/7.70.0",
    "accept": "*/*",
    "content-type": "application/json",
    "content-length": "14",
    "x-forwarded-proto": "http",
    "x-request-id": "db83d7df-d57c-4efb-a971-6828c2e2d515",
    "foo": "bar",
    "x-envoy-expected-rq-timeout-ms": "15000"
  },
  "method": "POST",
  "body": "{\"foo\":\"FFEE\"}",
  "fresh": false,
  "hostname": "localhost",
  "ip": "::ffff:172.19.0.2",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "b7c3569c682c"
  }
* Connection #0 to host localhost left intact
}
```

## Can change response body

I can set response body with 
```lua
local content_length = response_handle:body():setBytes("abcde")
response_handle:headers():replace("content-length", content_length)
```

```shell
curl -vd '{"foo":"FFEE"}' \                  
-H "Content-Type:application/json" \
http://localhost:8000/
```

the result is:
```
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.70.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< etag: W/"280-4A1MrWEjTZ2Nva1X6K8pFpfkzNk"
< date: Mon, 11 Jan 2021 07:40:41 GMT
< x-envoy-upstream-service-time: 25
< response-body-size: 640
< content-length: 5
< server: envoy
< 
* Connection #0 to host localhost left intact
abcde
```

## Can NOT change request body

```lua
local content_length = request_handle:body().setBytes("12345")
request_handle:headers():replace("content-length", content_length)
```

```shell
curl -vd '{"foo":"FFEE"}' \                  
-H "Content-Type:application/json" \
http://localhost:8000/
```

```
*   Trying ::1:8000...
* Connected to localhost (::1) port 8000 (#0)
> POST / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.70.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-powered-by: Express
< content-type: application/json; charset=utf-8
< content-length: 604
< etag: W/"25c-ymlKz2t2m6DPNCSaB5FM/qkCa40"
< date: Mon, 11 Jan 2021 07:55:46 GMT
< x-envoy-upstream-service-time: 18
< response-body-size: 604
< server: envoy
< 
{
  "path": "/",
  "headers": {
    "host": "localhost:8000",
    "user-agent": "curl/7.70.0",
    "accept": "*/*",
    "content-type": "application/json",
    "content-length": "14",
    "x-forwarded-proto": "http",
    "x-request-id": "30fee4c7-f902-46ba-a93b-ebf66c7eff20",
    "foo": "bar",
    "x-envoy-expected-rq-timeout-ms": "15000"
  },
  "method": "POST",
  "body": "{\"foo\":\"FFEE\"}",       <-- This should be 12345
  "fresh": false,
  "hostname": "localhost",
  "ip": "::ffff:172.19.0.3",
  "ips": [],
  "protocol": "http",
  "query": {},
  "subdomains": [],
  "xhr": false,
  "os": {
    "hostname": "e6a873c3e73e"
  }
* Connection #0 to host localhost left intact
}
```

## envoy.yaml

```yaml
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                local mylibrary = require("lib.mylibrary")

                function envoy_on_request(request_handle)
                  request_handle:headers():add("foo", mylibrary.foobar())
                  local content_length = request_handle:body().setBytes("12345")
                  request_handle:headers():replace("content-length", content_length)
                end
                function envoy_on_response(response_handle)
                  body_size = response_handle:body():length()
                  response_handle:headers():add("response-body-size", tostring(body_size))
                  -- local content_length = response_handle:body():setBytes("abcde")
                  -- response_handle:headers():replace("content-length", content_length)
                end
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: strict_dns # static
    lb_policy: round_robin
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 80
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

```
