### ISSUE TITLE
Envoy responds with a 404, when using tlscontextmatchoptions

### ISSUE THREAD

**Issue by koustubh25** [envoyproxy/envoy#14659]
*Title*: *TLS client certificate validation on a per route basis*

*Description*:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#envoy-api-msg-route-routematch-tlscontextmatchoptions
When using the `presented` and `validated` flag for verifying client certificate, envoy responds with a 404, while when I use  `require_client_certificate: true` in `DownstreamTlsContext`, envoy responds correctly.
Expected: Envoy should not respond with 404 even when using the `presented` and `validated` flag for verifying client certificate.

*Repro steps*:

```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          common_http_protocol_options:
            idle_timeout: 300s
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/token"
                  headers:
                  - name: ":method"
                    exact_match: "POST"
                  tls_context:
                    presented: true
                    validated: true
                route:
                  host_rewrite_literal: myupstream
                  prefix_rewrite: /token
                  cluster: frig_internal_sit
          http_filters:
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              certificate_chain:
                filename: /etc/ssl/listener/cert.pem
              private_key:
                filename: /etc/ssl/listener/key.pem
            validation_context:
              trusted_ca:
                filename: /etc/ssl/cluster/cabundle.pem
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_3

  clusters:
  - name: frig_internal_sit
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    common_http_protocol_options:
      idle_timeout: 300s
    load_assignment:
      cluster_name: frig_internal_sit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: myupstream
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: myupstream
        common_tls_context:
          tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_3
        allow_renegotiation: false
```

When I make a `POST` request on the `/token` endpoint. I get this error

```
[2021-01-11 23:37:28.647][14][debug][http] [source/common/http/conn_manager_impl.cc:837] [C1222][S6477541132398669624] request headers complete (end_stream=false):
':authority', '10.161.0.2:443'
':path', '/token?requested_token_type=StaffJWT'
':method', 'POST'
'authorization', 'Bearer mytoken'
'x-request-id', 'f7812c40-5465-11eb-b166-02c6e9998a2c'
'x-correlation-id', 'f7812c40-5465-11eb-b166-02c6e9998a2c'
'user-agent', 'AHC/1.0'
'connection', 'keep-alive'
'accept', '*/*'
'content-type', 'application/x-www-form-urlencoded'
'content-length', '105'

[2021-01-11 23:37:28.650][14][debug][router] [source/common/router/router.cc:364] [C1222][S6477541132398669624] no cluster match for URL '/token?requested_token_type=StaffJWT'
[2021-01-11 23:37:28.650][14][debug][http] [source/common/http/filter_manager.cc:805] [C1222][S6477541132398669624] Sending local reply with details route_not_found
[2021-01-11 23:37:28.650][14][debug][http] [source/common/http/conn_manager_impl.cc:1435] [C1222][S6477541132398669624] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Mon, 11 Jan 2021 23:37:28 GMT'
'server', 'envoy'
'connection', 'close'

[2021-01-11 23:37:28.650][14][debug][http] [source/common/http/conn_manager_impl.cc:176] [C1222][S6477541132398669624] doEndStream() resetting stream
```
If I remove this section

```
tls_context:
    presented: true
    validated: true
```
and use 
`require_client_certificate: true` in `DownstreamTlsContext`, it seems to work correctly and responds with a 200.

update:

The above works ok, when testing locally, however I see a 404 when the request comes over a VPN network.
