### ISSUE TITLE
Ingress Proxy for Docker Compose Services

### ISSUE THREAD

**Issue by loganstellway** [envoyproxy/envoy#14657]
## Question
Do all linked Docker services need to be built from the `envoyproxy/envoy` base images to facilitate a connection?

I see in the [front-proxy example](https://github.com/envoyproxy/envoy/tree/master/examples/front-proxy) that the linked [Flask services](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/docker-compose.yaml#L16-L18) are built on top of the Envoy image ([Dockerfile reference](https://github.com/envoyproxy/envoy/blob/master/examples/front-proxy/Dockerfile-service)). 

Is it possible to redirect traffic to other Docker services that are not based on Envoy (and do not include a running Envoy agent process)? 

Below is the context for my setup. 
Please let me know if any other information would be helpful. 

## Context

Currently, the response I get is:
>upstream connect error or disconnect/reset before headers. reset reason: connection termination

**`docker-compose.yml`**:

```
version: "3"
services:
    envoy:
        image: envoyproxy/envoy-alpine:v1.16.2
        networks:
            - envoy_mesh
        ports:
            - "9901:9901"
            - "10000:10000"
        volumes:
            - ./envoy/etc/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    nginx:
        image: nginx:alpine
        networks:
            - envoy_mesh
        ports:
            - "8080:80"
networks:
    envoy_mesh: {}
```

**`envoy.yaml`**:

```
admin:
    access_log_path: /tmp/admin_access.log
    address:
        socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 9901
static_resources:
    listeners:
        - address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 10000
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          codec_type: auto
                          stat_prefix: ingress_http
                          route_config:
                              name: local_route
                              virtual_hosts:
                                  - name: local_services
                                    domains:
                                        - "*"
                                    routes:
                                        - match:
                                              prefix: "/nginx"
                                          route:
                                              cluster: nginx
                          http_filters:
                              - name: envoy.filters.http.router
    clusters:
        - name: nginx
          connect_timeout: 30s
          dns_lookup_family: V4_ONLY
          type: LOGICAL_DNS
          lb_policy: round_robin
          http2_protocol_options: {}
          load_assignment:
              cluster_name: nginx
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: nginx
                                      port_value: 80
```
