### ISSUE TITLE
could  not got sw8 value in access log config.

### ISSUE THREAD

**Issue by JaredTan95** [envoyproxy/envoy#14795]
*Title*: *how to get sw8 value in access log config.*

*Description*:
I'm referring [Access logging](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log)  to record envoy access log as following configs:

```yaml
static_resources:
  listeners:
    - name: listener_1
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                generate_request_id: true
                upgrade_configs:
                  upgrade_type: websocket
                tracing:
                  provider:
                    name: envoy.tracers.skywalking
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig
                      grpc_service:
                        envoy_grpc:
                          cluster_name: dmp-skywalking-oap
                        timeout: 0.250s
                      client_config:
                        service_name: envoy
                        instance_name: envoy
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/tmp/envoy_access.log"
                      log_format:
                        omit_empty_values: true
                        content_type: "application/json; charset=UTF-8"
                        json_format:
                          id: "%REQ(X-REQUEST-ID)%"
                          sw_trace_id: "%REQ(SW8)%" 👈👈👈👈👈👈👈
```

But, I got nothing value.🤔
How to use it? Thanks...

**Comment by yanavlasov** [comment]
The %REQ% operator prints value of a HTTP request header. Do you have "SW8" header in the request?
See doc https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by JaredTan95** [comment]
I used `envoy.config.trace.v3.SkyWalkingConfig`, So, the skywalking tracer provider will generate the `sw8` header in the request during the processing.

**Comment by yanavlasov** [comment]
I see. Enabling debug or trace level logs may help determine what is happening. @wbpcode @dio @lizan for any more comments.

**Comment by wbpcode** [comment]
Do you set `start_child_span` in the route filter? It is necessary for skywalking tracer because only the exit span in envoy will inject context into the request header. @JaredTan95 
Please check https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/skywalking.proto

**Comment by Shikugawa** [comment]
@JaredTan95 It works successfully with this configuration on `v1.17.1-dev`, maybe `v1.17.0` also work. This configuration is based on `example/skywalking-tracing` one. Please rewrite it following with your use case.

```
- name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing:
            provider:
              name: envoy.tracers.skywalking
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig
                grpc_service:
                  envoy_grpc:
                    cluster_name: skywalking
                  timeout: 0.250s
                client_config:
                  service_name: service1-envoy
                  instance_name: service1-envoy-1
          access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: "/tmp/envoy_access.log"
                log_format:
                  omit_empty_values: true
                  content_type: "application/json; charset=UTF-8"
                  json_format:
                    id: "%REQ(X-REQUEST-ID)%"
                    sw_trace_id: "%REQ(SW8)%"
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: service1_route
            virtual_hosts:
            - name: service1
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
                decorator:
                  operation: checkAvailability
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              start_child_span: true
```
