### ISSUE TITLE
Extend network filters through WASM

### ISSUE THREAD

**Issue by liuqi-sun** [envoyproxy/envoy#14826]
How do I extend network filters through WASM.How is YAML configured.

**Comment by yanavlasov** [comment]
I believe you can only create HTTP filters with WASM. See https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/wasm_filter#config-http-filters-wasm

@PiotrSikora for any future plans to support WASM network filters as well.

**Comment by PiotrSikora** [comment]
Network filters are already supported:
https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/wasm_filter.html

**Comment by liuqi-sun** [comment]
> Network filters are already supported:
> https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/wasm_filter.html

I saw the document before I asked the question，but I don't know how to use it in envoy.yaml.
Now I have tried it successfully and found that there is an error in the document.
The 'config' field is multiple, and the 'name' field is missing the '- character.
The following configuration is in effect:
static_resources:
  listeners:
  - name: mysql_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
#      - name: envoy.filters.network.mysql_proxy
#        typed_config:
#          "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
#          stat_prefix: egress_mysql
#      - name: envoy.filters.network.redis_proxy
#        typed_config:
#          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
#          stat_prefix: egress_redis
#          settings:
#            op_timeout: 5s
#          prefix_routes:
#            catch_all_route:
#              cluster: redis_cluster
      - name: envoy.filters.network.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
#          config:
          config:
             name: "my_plugin"
             root_id: "my_root_id"
             vm_config:
               runtime: "envoy.wasm.runtime.v8"
               code:
                 local:
                   filename: "/lib/wasm_example.wasm"
               allow_precompiled: true
      - name: envoy.filters.network.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
          config:
            name: "my_plugin"
            root_id: "my_root_id"
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              code:
                local:
                  filename: "/lib/envoy_filter_http_wasm_example.wasm"
              allow_precompiled: true
      - name: envoy.filters.network.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
          config:
            name: "my_plugin"
            root_id: "my_root_id"
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              code:
                local:
                  filename: "/lib/test_cpp_network_filter.wasm"
              allow_precompiled: true
#      - name: envoy.filters.network.redis_proxy
#        typed_config:
#          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
#          stat_prefix: egress_redis
#          settings:
#            op_timeout: 5s
#          prefix_routes:
#            catch_all_route:
#              cluster: redis_cluster
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: redis_tcp
          cluster: redis_cluster

  clusters:
  - name: mysql_cluster
    connect_timeout: 1s
    type: strict_dns
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mysql
                port_value: 3306
  - name: redis_cluster
    connect_timeout: 1s
    type: strict_dns # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.73.87.58
                port_value: 6379

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

**Comment by gzeronet** [comment]
I just test network.echo with my sample here, it works by telnet:

```
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
      - filters:
        - name: envoy.filters.network.wasm
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
            config:
              name: "my_plugin"
              vm_config:
                runtime: "envoy.wasm.runtime.v8"
                code:
                  local:
                    filename: "/etc/myenvoyfilter.wasm"
                allow_precompiled: true
        - name: envoy.filters.network.echo
```
