### ISSUE TITLE
response_headers_to_add of LocalRateLimit does not take effect on outbound routes

### ISSUE THREAD

**Issue by hania-elayoubi** [envoyproxy/envoy#14831]
*Title*: *response_headers_to_add of LocalRateLimit does not take effect on outbound routes*

*Description*:

I'm on Istio 1.8.2 using Envoy 1.16.1

I am able to configure the [HTTP LocalRateLimit filter](https://www.envoyproxy.io/docs/envoy/v1.16.1/configuration/http/http_filters/local_rate_limit_filter.html?highlight=local%20rate%20limit) following the example in the Istio tests here:
1. enabling envoy local rate limit: https://github.com/istio/istio/blob/master/tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit.yaml
2. enabling local rate limit on a route: https://github.com/istio/istio/blob/master/tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit_per_route.yaml

... and I set: 
```
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
```

When I try to set up the local rate limit filter for an **inbound** route, I do see the rate limit response code 429 and also the `x-local-rate-limit` response header when the rate limit is in effect.

However, if I try to set the local rate limit filter for an **outbound** route, I do see the rate limit response code 429 when the tokens run out, but I do **not** get the response header `x-local-rate-limit`.

If this is a limitation of how this HTTP filter is applied, could you please describe at a high level in Envoy terms what I would need to do to achieve this on top of the examples from Istio above?

**Comment by hugree** [comment]
@hania-elayoubi how were you able to apply the rate limit option on outbound routes? 

the only working local rate limit config I have is for this setup:
```yaml
 - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8080"
            route:
              action: ANY
```

when I true to use outbound or any other route from Istio config i.e. `my-service.svc.cluster.local:8080` the rate limit listeners are not being propagated to Envoy and it stops working.

**Comment by hania-elayoubi** [comment]
> @hania-elayoubi how were you able to apply the rate limit option on outbound routes?
> 
> the only working local rate limit config I have is for this setup:
> 
> ```yaml
>  - applyTo: HTTP_ROUTE
>       match:
>         context: SIDECAR_INBOUND
>         routeConfiguration:
>           vhost:
>             name: "inbound|http|8080"
>             route:
>               action: ANY
> ```
> 
> when I true to use outbound or any other route from Istio config i.e. `my-service.svc.cluster.local:8080` the rate limit listeners are not being propagated to Envoy and it stops working.

@hugree  I learned this the hard way :)  The syntax of
```
inbound|http|8080
```
is for **inbound** traffic at port 8080.

For **outbound**, look up the vhost name like this:

```
istioctl proxy-config route -o json $POD_NAME.$NAMESPACE
```

(That is $PODNAME DOT $NAMESPACE )

You will see all the virtualHosts and routes for your sidecar.

For example, for the following **outbound** virtual host from my pod to **prometheus**

```
    {
        "name": "9090",
        "virtualHosts": [
            {
                "name": "prometheus.istio-system.svc.cluster.local:9090",
                "domains": [
                    "prometheus.istio-system.svc.cluster.local",
                    "prometheus.istio-system.svc.cluster.local:9090",
                    "prometheus.istio-system",
                    "prometheus.istio-system:9090",
                    "prometheus.istio-system.svc.cluster",
                    "prometheus.istio-system.svc.cluster:9090",
                    "prometheus.istio-system.svc",
                    "prometheus.istio-system.svc:9090",
                    "172.20.115.197",
                    "172.20.115.197:9090"
                ],
                "routes": [
                    {
                        "name": "default",
                        "match": {
                            "prefix": "/"
                        },
                        "route": {
                            "cluster": "outbound|9090||prometheus.istio-system.svc.cluster.local",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            },
                            "maxStreamDuration": {
                                "maxStreamDuration": "0s"
                            }
                        },
                        "decorator": {
                            "operation": "prometheus.istio-system.svc.cluster.local:9090/*"
                        }
                    }
                ],
```

I would configure it this way for **outbound**

```
 - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          vhost:
            name: "prometheus.istio-system.svc.cluster.local:9090"
            route:
              action: ANY
```

Could you try that?

**Comment by hugree** [comment]
@hania-elayoubi thanks for the response. I've already tried that
```json
"name": "payment-service.devops.svc.cluster.local:8080",
                "domains": [
                    "payment-service.devops.svc.cluster.local",
                    "payment-service.devops.svc.cluster.local:8080",
                    "payment-service",
                    "payment-service:8080",
                    "payment-service.devops.svc.cluster",
                    "payment-service.devops.svc.cluster:8080",
                    "payment-service.devops.svc",
                    "payment-service.devops.svc:8080",
                    "payment-service.devops",
                    "payment-service.devops:8080",
                    "10.0.220.162",
                    "10.0.220.162:8080"
                ],
```
this is my service. Even if I stick to inbound which is pretty much my goal here this works:
```yaml
- applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "inbound|http|8080"
            route:
              action: ANY
```
but this doesn't
```yaml
- applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "payment-service.devops.svc.cluster.local:8080"
            route:
              action: ANY
```

I think my setup is correct but for some reason only the "inbound|http|8080" route works but not the one I need. 

In general I'm trying to exclude my prometheus endpoint in this service from being throttled. So close yet still so far ;)

**Comment by hania-elayoubi** [comment]
@hugree so you want to apply this http filter between this pod and payment-service

May I suggest `context: SIDECAR_OUTBOUND` or even `context: ANY` ? I am pretty sure `SIDECAR_INBOUND` won't work for outbound traffic between pod and payment-service.

1. Also, which Envoy are you applying this to? istio-ingressgateway or the sidecar in your namespace? 
2. What do you have for `spec.workloadSelector` in `EnvoyFilter`?

**Comment by hugree** [comment]
My workload selector is based on the app (pod) I'm applying the config to. I think I want to use inbound because it's for the incoming traffic. I'm applying it to the sidecar.

This is my whole config 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-payment-service
  namespace: devops
spec:
  workloadSelector:
    labels:
      app: payment-service
  configPatches:
    - applyTo: HTTP_FILTER
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: "payment-service.devops.svc.cluster.local:8080"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      header_name: "Api-Key"
                      descriptor_key: apikey

          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 10
                  tokens_per_fill: 10
                  fill_interval: 60s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
                descriptors:
                  # each descriptor limit MUST be a multiple of the
                  # default limit, otherwise, sidecar fails to inject
                  # or config fails to update on existing sidecar
                  - entries:
                      - key: apikey
                        value: "APIKEY1"
                    token_bucket:
                      max_tokens: 2
                      tokens_per_fill: 2
                      fill_interval: 60s
                  - entries:
                      - key: apikey
                        value: "APIKEY2"
                    token_bucket:
                      max_tokens: 4
                      tokens_per_fill: 4
                      fill_interval: 60s
```
