### ISSUE TITLE
How do I config the load balance in envoy?

### ISSUE THREAD

**Issue by Demon520-coder** [envoyproxy/envoy#14848]
I have some trobules in config load balance. When I follow the [https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto](url) link, it shows me wrong: 
```yaml
[2021-01-28 08:15:18.005][1][critical][main] [source/server/server.cc:109] error initializing configuration '/etc/envoy/envoy.yaml': LOGICAL_DNS clusters must have a single locality_lb_endpoint and a single lb_endpoint
[2021-01-28 08:15:18.005][1][info][main] [source/server/server.cc:782] exiting
LOGICAL_DNS clusters must have a single locality_lb_endpoint and a single lb_endpoint
```
Here is my envoy.yaml about clusters. Can someone help me? Thank you very much.
```yaml
 clusters:
  - name: grpc_01
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}        
    load_assignment:
      cluster_name: grpc_01
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.102
                port_value: 7001
            health_check_config:
              port_value: 7001
          health_status: HEALTHY    
        - endpoint:
            address:
              socket_address:
                address: 192.168.50.125
                port_value: 7001
            health_check_config:
              port_value: 7001
          health_status: HEALTHY  
    
    health_checks:
      - timeout: 2s
        interval: 120s
        unhealthy_threshold: 3
        healthy_threshold: 1
        grpc_health_check:
          service_name: "GrpcHealthService"
        event_log_path: "/etc/logs/health_check/check"
        always_log_health_check_failures: true
                          
  - name: grpc_03
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}    
    load_assignment:
      cluster_name: grpc_03
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.102
                port_value: 7003   
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext            

  - name: mvc_01
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY    
    load_assignment:
      cluster_name: mvc_01
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.102
                port_value: 7004                 

  - name: api_01
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY    
    load_assignment:
      cluster_name: api_01
      endpoints:   
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.102
                port_value: 7008
            health_check_config:
              port_value: 7008
          health_status: HEALTHY
     
        - endpoint:
            address:
              socket_address:
                address: 192.168.50.125
                port_value: 7008
            health_check_config:
              port_value: 7008
          health_status: HEALTHY

    health_checks:
      - timeout: 2s
        interval: 120s    
        unhealthy_threshold: 3
        healthy_threshold: 1
        http_health_check:          
          path: "/healthy"
        event_log_path: "/etc/logs/health_check/check"
        always_log_health_check_failures: true
                
  - name: vue_01
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY    
    load_assignment:
      cluster_name: vue_01
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.102
                port_value: 7006
            health_check_config:
              port_value: 7006
          health_status: HEALTHY
     
        - endpoint:
            address:
              socket_address:
                address: 192.168.50.125
                port_value: 7006
            health_check_config:
              port_value: 7006
          health_status: HEALTHY  
    health_checks:
      - timeout: 2s
        interval: 120s      
        unhealthy_threshold: 3   
        healthy_threshold: 1
        http_health_check:          
          path: "/healthy"
        event_log_path: "/etc/logs/health_check/check"
        always_log_health_check_failures: true  

  - name: auth_app
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY    
    load_assignment:
      cluster_name: auth_app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: fgms-idsrv.fgms.dev.com
                port_value: 5095           
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext                          

```
