### ISSUE TITLE
How to enable TLS passthrough via envoy config file

### ISSUE THREAD

**Issue by r-aravind1997** [envoyproxy/envoy#14852]
I want the envoy to just delegate https calls to underlying downstream server to handle. In other words, TLS handshake must not happen at the edge where the envoy is, instead of https headers should be passed to the underlying server that is being proxied by the envoy. I found the way to declare tls context is like this:
```
transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: "certs/servercert.pem" }
              private_key: { filename: "certs/serverkey.pem" }
``` 
I just want the envoy proxy to accept https call at proxy port and TLS/SSL handshake to happen at underlying server.
So a call to https://host1.com:9001/some/path should be proxied to https://host1.com:8443/some/path and TLS handshake should be taken care by server running on port 8443. How to achieve that through config.
My usecase of TLS passthrough is exactly same as TLS passthough in contour.io k8s config: https://projectcontour.io/docs/main/config/tls-termination/#:~:text=TLS%20Session%20Passthrough&text=passthrough%3A%20true%20indicates%20that%20once,of%20completing%20the%20TLS%20handshake.
