### ISSUE TITLE
formatting metrics

### ISSUE THREAD

**Issue by Alexander1000** [envoyproxy/envoy#14863]
*Title*: formatting metrics

*Description*:
Let me show you what me want: 
```
stats_config:
  stats_tags:
  - tag_name: ver
    fixed_value: 'v123'
  - tag_name: cluster
    fixed_value: 'alpha'
  use_all_default_tags: false
  metric_format: "{prefix}.{name}:{value}|{type}{tags}" # - this is default work now
  tag_format:
    start: "|#"
    assign: ":"
    separator: ","
stats_sinks:
- name: envoy.stat_sinks.statsd
  typed_config:
    '@type': type.googleapis.com/envoy.config.metrics.v2.StatsdSink
    address:
      socket_address:
        protocol: UDP
        address: '127.0.0.1'
        port_value: 8126
    prefix: some.metric.prefix
```
This will allow you to customize different ways of sending metrics.
For examples:
```
some.metric.name:1|ms|#ver:v1234,cluster:alpha
```
or with configure (metric_format: "{prefix}.{name}{tags}:{value}|{type}" and tag_format: start: ";", assign: "=", separator: ";")
```
some.metric.name;ver=v1234;cluster=alpha:1|ms
```
