### ISSUE TITLE
Allow envoy to set 'authority' header's value to the endpoint's hostname for clusters with type: STRICT_DNS and lb_policy: MAGLEV/RING_HASH 

### ISSUE THREAD

**Issue by denisanfimov** [envoyproxy/envoy#14873]
*Title*: Currently requests coming to endpoints of cluster with type=STRICT_DNS and lb_policy=MAGLEV have 'authority' header equal to the name of the cluster ('dcs-cluster' as in the example below) and not to the hostname of the endpoint.

*Description*: 
In my configuration:
```
  clusters:
    - name: dcs-cluster
      type: STRICT_DNS
      lb_policy: MAGLEV
      common_lb_config:
        consistent_hashing_lb_config:
          use_hostname_for_hashing: true
      load_assignment:
        cluster_name: dcs-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: dc1
                      port_value: 8080
                  hostname: dc1 # ignored for STRICT_DNS
                  health_check_config:
                    hostname: dc1 # only applies to health requests
              - endpoint:
                  address:
                    socket_address:
                      address: dc2
                      port_value: 8080
                  hostname: dc2 # ignored for STRICT_DNS
                  health_check_config:
                    hostname: dc2 # only applies to health requests
```

I would like the 'authority' header in the requests sent to dc1 endpoint was equal to 'dc1' (not 'dcs-cluster') - the hostname of the endpoint. So in case I want to route these requests back to the envoy, I could distinguish from which endpoint the request is coming from (based on the 'authority' header) to perform additional routing.

Envoy already allows to specify hostname for the endpoint, but it is ignored if cluster's type = STRICT_DNS/LOGICAL_DNS although it allows to specify hostname for endpoint's health_check_config.

I need this because I use hostnames dc1, dc2 in the endpoints as aliases and they point to different hostnames on different envoy servers. I need those aliases so the Maglev balancing with property 'use_hostname_for_hashing'=true would work identically on all our envoy servers.

**Comment by mattklein123** [comment]
I've been looking for a related issue to this, but I can't find it, so maybe I'm not remembering correctly. Doesn't auto_host_rewrite do what you want?

**Comment by denisanfimov** [comment]
@mattklein123 auto_host_rewrite=true on route allows to use hostname from 
'endpoint.address.socket_address.address' 
but ignores the value form
'endpoint.hostname'
I would like envoy to 
1) resolve IP address from 'endpoint.address.socket_address.address' via custom dns_resolve.
My custom dns_resolver actually resolves CNAME records not for dc1 (alias) but for real FQDN (rewritten in custom dns_resolver. I use coredns with rewrite plugin) 
2) use real FQDN from 'endpoint.hostname' to insert in 'authority' header in the requests to the upstream.

so if my config is like this:
```
              - endpoint:
                  address:
                    socket_address:
                      address: dc1
                      port_value: 8080
                  hostname: real-gw1.fqdn
                  health_check_config:
                    hostname: real-gw1.fqdn
```
health requests will contain 'authority' header = real-gw1.fqdn
other requests will contain 'authority' header = dc1
