### ISSUE TITLE
Didn't find a registered implementation for name: 'envoy.filters.udp_listener.udp_proxy

### ISSUE THREAD

**Issue by davidkornel** [envoyproxy/envoy#14925]
I'm a newcomer to envoy. I'm trying to make a dynamic conf setup from filesystem. I've got a few questions about it. First of all, what is the difference between listener_filters and filter_chains, seems the same at first, but there's gotta be something I miss. 

As in the title, you can see I'm having some problems. My cds config file works perfectly, but my lds config is wrong somehow.
An example from my lds.yaml:
```
    resources:
    - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
      name: rtp-a-listener-ingress
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9000
      filter_chains:
      - filters:
          name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            cluster: rtp-a-cluster-ingress
```

After dumping my configuration I got this error: 
```
{
name: "rtp-a-listener-ingress",
error_state: {
failed_configuration: {
@type: "type.googleapis.com/envoy.config.listener.v3.Listener",
name: "rtp-a-listener-ingress",
address: {
socket_address: {
address: "0.0.0.0",
port_value: 9000
}
},
filter_chains: [
{
filters: [
{
name: "envoy.filters.udp_listener.udp_proxy",
typed_config: {
@type: "type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig",
stat_prefix: "service",
cluster: "rtp-a-cluster-ingress"
}}]}]},
last_update_attempt: "2021-02-03T13:39:33.678Z",
details: "Didn't find a registered implementation for name: 'envoy.filters.udp_listener.udp_proxy'"
}},
```

I tried to find what's wrong with it but I can't figure it out. As a basic static_listener [`envoy.filters.udp_listere.udp_proxy`](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/udp_proxy) works fine, but as a dynamic_listener it doesn't.

Thanks.
