### ISSUE TITLE
When there is no healthy host in cluster, Envoy continue route traffic to unhealthy host in cluster

### ISSUE THREAD

**Issue by charlesxu2000** [envoyproxy/envoy#14968]
*Title*: *When there is no healthy host in cluster, Envoy continue route traffic to unhealthy host in cluster*

*Description*:

Envoy version: 1.17.0.
Have static route with two upstream services within a cluster. Cluster using round robin lb_policy. Have cluster health check configured on service endpint "/healthcheck".

If two services are all healthy, Ingress http traffic is round robin routed to both services.
If one service is unhealthy, Ingress http traffic is only routed to healthy service.
If both services are unhealthy, Ingress http traffic is round robin routed to both unhealthy services. (Suppose to return 503)

*Repro steps*:
1) Start two simple upstream services. Each service has two endpoints, one /healthcheck, one /demo.
2) Start Envoy with the following configuration:
3) Send http request to Envoy:
`curl -v http://localhost:8000/demo`
4) Monitor the response from the upstream services.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:

/clusters, /routes, /server_info
[stats.txt](https://github.com/envoyproxy/envoy/files/5936191/stats.txt)
[cluster.txt](https://github.com/envoyproxy/envoy/files/5936193/cluster.txt)
[server_info.txt](https://github.com/envoyproxy/envoy/files/5936194/server_info.txt)

. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: "::"
        port_value: 8000
        ipv4_compat: true
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          server_name: demo
          use_remote_address: true
          access_log:
            name: envoy.file_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: envoy-access.log
          route_config:
            name: ingress_route_config
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: testcluster
                  timeout: 0s
                  idle_timeout: 0s
          http_filters:
          - name: envoy.filters.http.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
              pass_through_mode: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: testcluster
    connect_timeout: 1s
    type: strict_dns
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    health_checks:
      timeout: 1s
      interval: 1s
      unhealthy_threshold: 1
      healthy_threshold: 1
      http_health_check:
        host: 127.0.0.1
        path: /healthcheck
      event_log_path: envoy-healthcheck.log
      always_log_health_check_failures: true
    load_assignment:
      cluster_name: testcluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 8080
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: 8081
admin:
  access_log_path: envoy-admin.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
```

*Logs*:
Attached the stats, cluster and server_info log.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
