### ISSUE TITLE
http status 444 not working as excepted

### ISSUE THREAD

**Issue by elvizlai** [envoyproxy/envoy#14974]
*Description*:
For nginx or other http server

444 No Response
A 444 No Response error indicates that the server has closed the connection with no returned information from a client request.

when we want deny ip visit, we using nginx.conf
```
server {
    listen      80 default;
    server_name _;
    return 444;
}

server {
    listen 80;
    server_name example.com
    location / {
    }
}
```

when we visit and the response looks fine enough:
```
curl -v $HIDDEN_IP_ADDRESS

*   Trying $HIDDEN_IP_ADDRESS...
* TCP_NODELAY set
* Connected to $HIDDEN_IP_ADDRESS ($HIDDEN_IP_ADDRESS) port 80 (#0)
> GET / HTTP/1.1
> Host: $HIDDEN_IP_ADDRESS
> User-Agent: curl/7.64.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

so we want similar feature in envoy as configured:
```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8888 }
      listener_filters:
        - name: "envoy.filters.listener.http_inspector"
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                access_log: &log_config
                  - name: envoy.file_access_log
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/dev/stdout"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        [
                          "example.com",
                        ]
                      require_tls: ALL
                    - name: default_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          direct_response:
                            status: 444
                http_filters:
                  - name: envoy.filters.http.router
```

Visiting `example.com` should response 301(this works fine), when using `direct ip` visiting, it should working as nginx response, but got:
```
*   Trying $HIDDEN_IP_ADDRESS...
* TCP_NODELAY set
* Connected to $HIDDEN_IP_ADDRESS ($HIDDEN_IP_ADDRESS) port 8888 (#0)
> GET / HTTP/1.1
> Host: $HIDDEN_IP_ADDRESS
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 444 Unknown
< date: Sun, 07 Feb 2021 05:28:27 GMT
< content-length: 0
<
* Connection #0 to host $HIDDEN_IP_ADDRESS left intact
* Closing connection 0
```
So, am i envoy conf right or can envoy has same feature as nginx?
