### ISSUE TITLE
Direct response/Redirect with ext_authz

### ISSUE THREAD

**Issue by artificial-aidan** [envoyproxy/envoy#14984]
*Title*: Unable to run ext_authz filter with direct response and redirect.

*Description*:
From how I read #8436 I should be able to set up a direct response and have it handled by the authorization filter. But when I set it up as follows no call is made to the ext_authz filter, and it just responds as specified

```
- name: envoy.filters.network.http_connection_manager
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
    codec_type: auto
    stat_prefix: ingress_http
    route_config:
      name: local_route
      virtual_hosts:
        - name: local_service
          domains: ["*"]
          typed_per_filter_config:
            envoy.filters.http.ext_authz:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
              check_settings:
                context_extensions:
                  virtual_host: local_service
          routes:
            - match: { path: "/auth-check" }
              direct_response:
                status: 200
            - match: { prefix: "/old-path" }
              redirect:
                path_redirect: "/new-path"
            - match: { prefix: "/" }
              route:
                cluster: upstream
    http_filters:
      - name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            envoy_grpc:
              cluster_name: ext_authz-grpc-service
            timeout: 0.250s
          failure_mode_allow: false
          transport_api_version: V3
```
