### ISSUE TITLE
Unable to implement local rate limiting using envoy local rate limit filter

### ISSUE THREAD

**Issue by r-aravind1997** [envoyproxy/envoy#14992]
I'm trying to use local rate filter for a http service, and it doesn't seem to work. I created a small playground setup to understand local rate limiting. Envoy version I'm using is 1.17.0
**BACKGROUND** : I started a simple HTTP server on port 9003 running in background.
`
python -m SimpleHTTPServer 9003
`
**AIM**:  Create a envoy proxy at port 10000 that proxies service at 9003 and does local rate limiting
**CONFIG FILE** : 
```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001

static_resources:
  listeners:
    - name: local-rate-limit-listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name:  envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: stats
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: admin_backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            timeout: 3600s
                            cluster: local-rate-limit-cluster
                          typed_per_filter_config:
                            envoy.filters.http.local_ratelimit:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                              stat_prefix: local-rate-limit
                              token_bucket:
                                max_tokens: 10
                                tokens_per_fill: 10
                                fill_interval: 200s
                              filter_enabled:
                                runtime_key: local_rate_limit_enabled
                                default_value:
                                  numerator: 100
                                  denominator: HUNDRED
                              filter_enforced:
                                runtime_key: local_rate_limit_enforced
                                default_value:
                                  numerator: 100
                                  denominator: HUNDRED
                              response_headers_to_add:
                                - append: false
                                  header:
                                    key: x-local-rate-limit
                                    value: 'true'
                http_filters:
                  - name: envoy.filters.http.router
  clusters:
    - name: local-rate-limit-cluster
      type: STRICT_DNS
      connect_timeout: 30s
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: local-rate-limit-cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9003

```
Ref config:  https://www.envoyproxy.io/docs/envoy/v1.17.0/configuration/http/http_filters/local_rate_limit_filter#config-http-filters-local-rate-limit 
But when tested with load test using wrk : https://github.com/wg/wrk 
` ./wrk  -c 500 -t 500 -d 3m http://localhost:10000/ `
All the requests seem to pass with 200, the once failed are also with 503, which I guess it is due to the default circuit breaker configs of envoy(1024) connections, not because of rate limits: https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/config/cluster/v3/circuit_breaker.proto 
I'm not sure what is that wiring I'm missing. We need our service to perform rate limiting and this play ground setup isn't helping that. I'm not sure how this https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-field-extensions-filters-http-local-ratelimit-v3-localratelimit-token-bucket works. Our use case is to have explicit 429 error codes when we are overloaded with more rate request, please point to what Am I missing here?

**Comment by antoniovicente** [comment]
cc @rgs1 @mattklein123 @junr03

**Comment by mattklein123** [comment]
Your filter list only contains the router filter. You need to load the rate limit filter.

**Comment by andye2004** [comment]
The docs on this are pretty sketchy IMHO. The filter is named `envoy.filters.http.local_ratelimit` and is described as a "local" rate limiter but in the section describing the configuration and in the examples it talks about 'global' rate limiting. This led me to be looking at the actual global rate limiter, implemented through an external rate limiting service., not for very long but still frustrating.

In the local rate limiting sections of the docs, when mention of 'global' is made they really mean 'listener'. To have route (or virtual host) level rate limiting, you MUST first define a rate limiter at the listener level. The rate limiter at the listener level can be 'disabled' all this means is that it shouldn't have a `token_bucket` defined. Then in the route/virtual host rate limiting section you define the bucket etc for that particular route / virtual host. Of course it is possible to have listener level rate limiting by specifying all necessary fields then further refine that on a per route / virtual host basis.

An example of how to configure 'listener' level rate limiting is below:-

```yaml
filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: api_port
        rds:
          route_config_name: api_routes
          config_source:
            resource_api_version: V3
            path: config/rds/api-routes.yaml

        http_filters:
          - name: envoy.filters.http.local_ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter

          - name: envoy.filters.http.router
```

Extract from rds routes file showing route specific rate limiting:-

```yaml
resources:
  - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: api_routes
    virtual_hosts:
      - name: api_all_domains
        domains: ["*"]
        routes:
          - match: { path: /route1 }
            route: { cluster: route1 }

          - match: { prefix: /route2 }
            route: { cluster: route2 }
            typed_per_filter_config:
              envoy.filters.http.local_ratelimit:
                "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                stat_prefix: route2_rate_limit
                token_bucket:
                  max_tokens: 1
                  tokens_per_fill: 1
                  fill_interval: 100s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
```

Hopefully this can help others understand what's going a little better than is obvious from the docs.
