### ISSUE TITLE
HTTP3: no access logs generated

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#15035]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
I have access logs configured, but they do not show up.

*Repro steps*:
```yaml
accessLog:
- filter:
    responseFlagFilter:
      flags:
      - NR
  name: envoy.access_loggers.file
  typedConfig:
    '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
    logFormat:
      textFormat: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
        %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS%
        "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
        %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
        "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER%
        %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS%
        %REQUESTED_SERVER_NAME% %ROUTE_NAME%

        '
    path: /dev/stdout
address:
  socketAddress:
    address: 0.0.0.0
    portValue: 4433
    protocol: UDP
filterChains:
- filters:
  - name: envoy.filters.network.http_connection_manager
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      accessLog:
      - name: envoy.access_loggers.file
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          logFormat:
            textFormat: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
              %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS%
              %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
              %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%
              "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%"
              "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS%
              %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%

              '
          path: /dev/stdout
      codecType: HTTP3
      forwardClientCertDetails: SANITIZE_SET
      httpFilters:
      - name: envoy.filters.http.cors
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
      - name: envoy.filters.http.fault
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
      - name: envoy.filters.http.router
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      httpProtocolOptions: {}
      normalizePath: true
      rds:
        configSource:
          ads: {}
          resourceApiVersion: V3
        routeConfigName: http3.4433.http3.echo.default
      serverName: istio-envoy
      setCurrentClientCertDetails:
        cert: true
        dns: true
        subject: true
        uri: true
      statPrefix: outbound_0.0.0.0_4433_udp
      streamIdleTimeout: 0s
      upgradeConfigs:
      - upgradeType: websocket
      useRemoteAddress: true
  transportSocket:
    name: envoy.transport_sockets.quic
    typedConfig:
      '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
      downstreamTlsContext:
        commonTlsContext:
          tlsCertificates:
          - certificateChain:
              inlineString: '...'
            privateKey:
              inlineString: '[redacted]'
name: 0.0.0.0_4433_udp
reusePort: true
trafficDirection: OUTBOUND
udpListenerConfig:
  udpListenerName: quiche_quic_listener
```
