### ISSUE TITLE
Problem [Bug?] Redis authentication

### ISSUE THREAD

**Issue by p53** [envoyproxy/envoy#15045]
*Title*: *Redis authentication*

*Description*:
i am trying to setup authentication to redis, have problems with it so i am not sure if am doing it correctly

What i had and it was partially working (sometimes getting errors) was:

(app->envoy redis proxy filter)=downstream ----> (envoy tcp filter->redis with auth in redis.conf)=upstream

redis version: 6.0.8-alpine3.12
envoy 1.15 setup on downstream with:

```
    - name: redis_cluster
      connect_timeout: 30s
      type: STRICT_DNS
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: RING_HASH
      health_checks:
        timeout: 10s
        interval: 30s
        tcp_health_check: {}
        always_log_health_check_failures: true
        event_log_path: "/dev/stdout"
        unhealthy_threshold: 3
        healthy_threshold: 3
      typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
          auth_username:
            inline_string: someuser
          auth_password:
            inline_string: somepass
 ```
 
 on upstream side:
 
 envoy tcp filter targeting redis instance which has user/password in redis.conf
 
 with envoy 1.17 this ceased to work and i am getting “NOAUTH Authentication required.”
 
i tried all this combinations, none of them worked:

(app->envoy1.17 redis proxy filter)=downstream ----> (envoy tcp filter->redis with auth in redis.conf)=upstream
(app->envoy1.17 redis proxy filter)=downstream ----> (envoy1.17 redis proxy filter with downstream auth->redis without auth in redis.conf)=upstream
(app->envoy1.15 redis proxy filter)=downstream ----> (envoy1.17 redis proxy filter with downstream auth->redis without auth in redis.conf)=upstream
(app->envoy1.15 redis proxy filter)=downstream ----> (envoy1.15 redis proxy filter with downstream auth->redis without auth in redis.conf)=upstream

configuration which i use for upstream envoy with redis proxy with downstream creds is:

```
      filter_chains:
      - transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_certificates:
                certificate_chain:
                  filename: "/etc/ssl/certs/redis_cert.pem"
                private_key:
                  filename: "/etc/ssl/certs/redis_privkey.pem"
        filters:
        - name: envoy.redis_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
            stat_prefix: to_redis
            prefix_routes:
              catch_all_route:
                cluster: redis
            settings:
              op_timeout: 5s
              enable_redirection: true
              enable_command_stats: true
            downstream_auth_username:
              inline_string: someuser
            downstream_auth_password:
              inline_string: somepass
```
