### ISSUE TITLE
Content-Length: 0 is auto-inserted in HTTP requests with empty body

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#15049]
*Title*: *Content-Length: 0 is auto-inserted in HTTP requests with empty body*

*Description*:
Envoy auto-inserts Content-Length: 0 into HTTP requests with empty body, such HTTP GET and Websocket Upgrade. It would cause some servers to misbehave.

https://github.com/envoyproxy/envoy/issues/5554 is a similar problem but for responses.

*Repro steps*:
1. Run a simple HTTP server listening on port 8080. It has a "/headers" handler that prints all request headers.

2. Run a Envoy with simple configuration that listens on port 7777:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: {
        address: 127.0.0.1,
        port_value: 7777
      }                                                                                                                                    
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: upstream
                  timeout: 300s
          http_filters:
            - name: envoy.filters.http.router

  clusters:
  - name: upstream
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: upstream
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
```

3. Output:

curl localhost:8080/headers
{
  "Accept":["*/*"],
  "User-Agent":["curl/7.74.0"]
}

curl localhost:7777/headers
{
  "Accept":["*/*"],
  "Content-Length":["0"],
  "User-Agent":["curl/7.74.0"],
   "X-Envoy-Expected-Rq-Timeout-Ms":["300000"],
  "X-Forwarded-Proto":["http"],"X-Request-Id":["f06070ac-8523-444c-93f5-ee1c3ee789ea"]
}
