### ISSUE TITLE
envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig not recognized

### ISSUE THREAD

**Issue by KU348-code** [envoyproxy/envoy#15070]
Envoy is running in CentOS 8.3. Envoy version is as follows.

envoy  version: 5c801b25cae04f06bf48248c90e87d623d7a6283/1.17.0/clean-getenvoy-28ef262-envoy/RELEASE/BoringSSL

Envoy configuration file is validated with the following command.

envoy --mode validate -c envoy.yaml

The contents of envoy.yaml is as follows.

```
overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
  - name: envoy.resource_monitors.fixed_heap
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
      max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
  - name: envoy.overload_actions.shrink_heap
    triggers:
    - name: envoy.resource_monitors.fixed_heap
      threshold:
        value: 0.95
  - name: envoy.overload_actions.stop_accepting_requests
    triggers:
    - name: envoy.resource_monitors.fixed_heap
      threshold:
        value: 0.98

static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          http2_protocol_options:
            max_concurrent_streams: 100
          request_timeout: 300s
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_envoyproxy_io

  clusters:
    - name: service_envoyproxy_io
      connect_timeout: 30s
      type: STATIC
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              max_concurrent_streams: 100
      load_assignment:
        cluster_name: service_envoyproxy_io
        endpoints:
        - lb_endpoints:
          - endpoint:
              address: 
                socket_address:
                  address: 127.0.0.1
                  port_value: 20000
```

The output of running the above envoy validation command is as follows.

[2021-02-17 14:46:48.700][1357][critical][main] [external/envoy/source/server/config_validation/server.cc:60] error initializing configuration 'envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(overload_manager.resource_monitors[0].typed_config): invalid value Invalid type URL, **unknown type: envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig for type Any**): {"static_resources":{"clusters":[{"type":"STATIC","load_assignment":{"cluster_name":"service_envoyproxy_io","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":48879,"address":"127.0.0.1"}}}}]}]},"name":"service_envoyproxy_io","typed_extension_protocol_options":{"envoy.extensions.upstreams.http.v3.HttpProtocolOptions":{"explicit_http_config":{"http2_protocol_options":{"max_concurrent_streams":100}},"@type":"type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"}},"connect_timeout":"30s"}],"listeners":[{"address":{"socket_address":{"address":"0.0.0.0","port_value":48813}},"name":"listener_0","filter_chains":[{"filters":[{"typed_config":{"route_config":{"name":"local_route","virtual_hosts":[{"name":"local_service","routes":[{"route":{"cluster":"service_envoyproxy_io"},"match":{"prefix":"/"}}],"domains":["*"]}]},"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","http_filters":[{"name":"envoy.filters.http.router"}],"access_log":[{"typed_config":{"path":"/dev/stdout","@type":"type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"},"name":"envoy.access_loggers.file"}],"stat_prefix":"ingress_http","use_remote_address":true,"http2_protocol_options":{"max_concurrent_streams":100},"request_timeout":"300s"},"name":"envoy.filters.network.http_connection_manager"}]}]}]},"overload_manager":{"actions":[{"triggers":[{"threshold":{"value":"0.95"},"name":"envoy.resource_monitors.fixed_heap"}],"name":"envoy.overload_actions.shrink_heap"},{"triggers":[{"name":"envoy.resource_monitors.fixed_heap","threshold":{"value":"0.98"}}],"name":"envoy.overload_actions.stop_accepting_requests"}],"resource_monitors":[{"typed_config":{"max_heap_size_bytes":"2147483648","@type":"type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig"},"name":"envoy.resource_monitors.fixed_heap"}],"refresh_interval":"0.25s"}}

Removing the entire overload_manager block found in config file envoy.yaml works fine though.

Please advice!
