### ISSUE TITLE
The stat init_fetch_timeout does not correctly increment when the timeout is reached 

### ISSUE THREAD

**Issue by kuroneko25** [envoyproxy/envoy#15085]
*Description*:
When `init_fetch_timeout` is reached (default of 15s) envoy gives up the xDS init process and proceeds to the next phase in initialization but does not increment the `init_fetch_timeout` counter.

*Repro steps*:
Define a xDS cluster that points to localhost:some_port
```
  - name: xds
    type: static
    hosts:
    - socket_address:
        address: 127.0.0.1  # netcat listen on this address
        port_value: 50000
    connect_timeout: 1s
    http2_protocol_options: {}  
```

Run `nc -l 50000` and start envoy. You will see envoy connecting to the port and sending xDS requests. After about 15s envoy becomes `LIVE`.
```
$ curl localhost:8001/ready
LIVE
```

However the stat is never incremented
```
$ curl -s localhost:8001/stats | grep init_fetch_timeout
cluster_manager.cds.init_fetch_timeout: 0
listener_manager.lds.init_fetch_timeout: 0
```
