### ISSUE TITLE
sni_cluster: case-insensitive comparing with sni and cluster name

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#15123]
*Title*: *sni_cluster: case-insensitive comparing with sni and cluster name*

*Description*:
This is separated from the issue #6199 and PR discussion https://github.com/envoyproxy/envoy/pull/14793#issuecomment-774572561

When using sni_cluster filter, the sni_cluster will choose the cluster based on SNI value. From the RFC definition https://tools.ietf.org/html/rfc6066#page-6 the hostname is case-insensitive in SNI. But the current behavior when matching the SNI value with cluster name is case-sensitive.

*Repro steps*:
start up envoy with following configuration:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: my_listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 13333
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config: {}
    filter_chains:
      - filters:
        - name: envoy.filters.network.sni_cluster
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: ingress_tcp
            cluster: foo.example.com
  clusters:
  - name: foo.example.com
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    protocol_selection: USE_DOWNSTREAM_PROTOCOL
    load_assignment:
      cluster_name: foo.example.com
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 33333
  - name: bar.example.com
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    protocol_selection: USE_DOWNSTREAM_PROTOCOL
    load_assignment:
      cluster_name: bar.example.com
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 33334
```
Request to `bar.example.com` successful.

But a request to `BAR.example.com` failed.

As the discussion in PR https://github.com/envoyproxy/envoy/pull/14793#issuecomment-774572561, we can't change the cluster name to case-insensitive directly, since it breaks the API.

So the available option is introducing explicit API change.

There are two options:
1. As @htuch 's suggestion, allowing the prefix for the cluster name, example:  `name: dns:bar.example.com`, then we store the cluster name with `dns` prefix as lower case inside envoy, and compare with lowercase SNI value. 
2. introduce another config option explicitly, example: "case-insensitive-name: true", the default value is `false`. When the value is true, the cluster name will be store as lower-case inside envoy, and compare with lowercase SNI value.
