### ISSUE TITLE
route_config.virtual_hosts.domains can't route the Fully-Qualified Domain Names

### ISSUE THREAD

**Issue by sunnoy** [envoyproxy/envoy#15206]
*Title*: *route_config.virtual_hosts.domains can't route the Fully-Qualified Domain Names*

*Description*:
>Describe the the desired behavior, what scenario it enables and how it
would be used.

the domains is 
```yaml
        route_config:
          name: "nginx"
          virtual_hosts:
          - name: nginx
            domains:
            - "www.baidu.com"
```

req is : 
the host is `www.baidu.com.`

```bash
curl --location --request GET 'xxx:xxx' \
--header 'Host: www.baidu.com.'
```

i get the access log : 
```bash
[2021-02-26T03:03:37.987Z] "GET / HTTP/1.1" 404 NR 0 0 0 - "-" "PostmanRuntime/7.26.8" "053a4ee8-00e0-435a-b6a0-bd2abbb9d1d4" "www.baidu.com." "-"
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
