### ISSUE TITLE
[Question] Problems switching from 1.16 to 1.17 - v2 to v3 static configuration

### ISSUE THREAD

**Issue by masbaehr** [envoyproxy/envoy#15207]
Hi, after several attempts of trying i gave up and cant figure out how to make this configuration work with latest envoy version 1.17.
Could you please help? 

Note: Working with 1.16 (though some warning about v2), but not working with 1.17

I understand that i have to switch to 

extensions.filters.network.http_connection_manager.v3.HttpConnectionManager

But this does not seem the only change necessary

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              cors: 
                allow_origin_string_match:
                  - prefix: "*"
                allow_headers: "content-type, authorization, origin, referer, user-agent, x-grpc-web, x-user-agent"
                allow_methods: "POST,OPTIONS"
              routes:
              - match: { path: "/status" }
                direct_response: { status: 200, body: {inline_string: "OK"} }
              - match:
                  prefix: "/rest/myinternalservice"
                route:
                  prefix_rewrite: "/"
                  cluster: myinternalservice
          http_filters:
          - name: envoy.cors
          - name: envoy.router
            config: {}   
      tls_context:
        common_tls_context:
          alpn_protocols: "h2"
          tls_certificates:
            - certificate_chain:
                filename: "/etc/letsencrypt/live/DOMAIN/fullchain.pem"
              private_key:
                filename: "/etc/letsencrypt/live/DOMAIN/privkey.pem"
  clusters:
  - name: myinternalservice
    connect_timeout: 1.0s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: myinternalservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.167.178.22
                port_value: 9600
```

**Comment by phlax** [comment]
@masbaehr 

can you try:

```

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              cors:
                allow_origin_string_match:
                  - prefix: "*"
                allow_headers: "content-type, authorization, origin, referer, user-agent, x-grpc-web, x-user-agent"
                allow_methods: "POST,OPTIONS"
              routes:
              - match: { path: "/status" }
                direct_response: { status: 200, body: {inline_string: "OK"} }
              - match:
                  prefix: "/rest/myinternalservice"
                route:
                  prefix_rewrite: "/"
                  cluster: myinternalservice
          http_filters:
          - name: envoy.cors
          - name: envoy.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: "h2"
            tls_certificates:
              - certificate_chain:
                  filename: "/etc/letsencrypt/live/DOMAIN/fullchain.pem"
                private_key:
                  filename: "/etc/letsencrypt/live/DOMAIN/privkey.pem"
  clusters:
  - name: myinternalservice
    connect_timeout: 1.0s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: myinternalservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend
                port_value: 9600

```
