### ISSUE TITLE
Dynamic HTTP tunnel

### ISSUE THREAD

**Issue by baojr** [envoyproxy/envoy#15285]
*Title*: *Dynamic HTTP tunnel*

*Description*:
I'm working on migrating a deployment of [squid proxy](http://www.squid-cache.org/) that we use as a forward proxy. In addition to HTTP requests on ports 80 and 443, we also need to support tunneling arbitrary TCP connections, such as SSH on port 22. The dynamic forward proxy setup [described in the docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_proxy) does not work for us, since the upstream clusters it creates only have HTTP endpoints. I was able to get a proof of concept working using the `original_dst` listener filter, but that requires me to do the DNS resolution myself and pass in the endpoint in a header. Ideally I'd be able to use the dynamic forward proxy HTTP filter and read from its DNS cache to create endpoints. That way, we get the behavior of pausing requests if a hostname is not in the DNS cache, but we also have the flexibility of tunneling TCP connections to arbitrary ports.

```
# Here's an example of proxying to a different port.
# I want envoy to perform the DNS resolution based on the hostname
# instead of passing in the original destination header manually.
curl --proxytunnel --proxy http://localhost:1080 http://www.asnt.org:8080/Test.html -H "x-envoy-original-dst-host: 64.132.177.13:8080"
```

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1080
    listener_filters:
      - name: envoy.filters.listener.original_dst
        typed_config: {}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
                - match:
                    connect_matcher:
                      {}
                  route:
                    cluster: dynamic_service
                    upgrade_configs:
                      - upgrade_type: CONNECT
                        connect_config:
                          {}
          http_filters:
          - name: envoy.filters.http.router
          http_protocol_options: {}
          upgrade_configs:
            - upgrade_type: CONNECT
  clusters:
    # I can't use envoy.clusters.dynamic_forward_proxy here, because that
    # only works for HTTP upstreams. Here, I want to tunnel TCP connections.
    - name: dynamic_service
      connect_timeout: 0.25s
      type: ORIGINAL_DST
      lb_policy: ORIGINAL_DST_LB
      original_dst_lb_config:
        use_http_header: true
```

**Comment by alyssawilk** [comment]
Sorry, I haven't played with this configuration myself but have you tried just using the dyanmic forward proxy?  It only works with HTTP insofar as it expects to be created by an HTTP session but the way Envoy's connect support works is it masquerades as HTTP up to the point it's serialized out to the wire so while I haven't tried it I would (possibly optimistically =P) expect it to work.

**Comment by baojr** [comment]
I gave it another shot just now and seem to have gotten it working. I ended up needing to add a route with a `connect_matcher` pointing to the dynamic forward proxy cluster to make it work both with and without using `HTTP CONNECT`. It seems that curl will always send a `CONNECT` request if the provided URL is not port 80, which is what my problem was before, since the [config example here](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter) would only match requests with the typical HTTP methods.

Thanks for confirming, Alyssa!

---

Below is the relevant config in case it helps anyone else. I also recommend turning on HTTP/1.0 support if you have existing clients that use that. We use netcat to set up an HTTP tunnel for SSH connections, for example, which apparently uses HTTP/1.0 with `ssh -o ProxyCommand="nc --proxy localhost:1080 --proxy-type http %h %p" $server`.

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              # Support tunneling using HTTP CONNECT
              # This route is what I had to add to get it working for my case.
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: dynamic_forward_proxy_cluster
                  upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config:
                        {}
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
              # Support tunneling without using HTTP CONNECT
              - match:
                  prefix: "/"
                route:
                  cluster: dynamic_forward_proxy_cluster
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
```

```bash
# Any port or protocol should work now! 
curl --proxy http://localhost:1080 http://www.asnt.org:8080/Test.html
```
