### ISSUE TITLE
Globally limiting maximum concurrent h/2 requests per endpoint

### ISSUE THREAD

**Issue by puilp0502** [envoyproxy/envoy#15287]
*Title*: *Globally limiting maximum concurrent h/2 requests per endpoint*

*Description*:
Hi,

I’m trying to limit the concurrent streams forwarded to the upstream endpoints, such that each endpoint sees at most N requests at any given time. (Upstream is a cluster of python grpc servers.)

Since `http2_protocol_option` supports manually specifying `max_concurrent_streams`, I tried combining the option with the circuit breaker's max_connections configuration.

So far, I've come up with the following configuration:
```yaml
  clusters:
    - name: processor_cluster
      connect_timeout: 0.25s
      circuit_breakers:
        thresholds:
        - max_pending_requests: 16384
          max_connections: 1
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:  # Forces HTTP/2 on upstream connection
              max_outbound_frames: 160000
              max_outbound_control_frames: 16000
              max_concurrent_streams: 4
      eds_cluster_config:
        eds_config:
          path: /<some-path>/edsconf.json
          resource_api_version: "V3"
        service_name: localservices
      lb_policy: ROUND_ROBIN
      type: EDS
```
This configuration works well when there are only one downstream connection. That is, `upstream_rq_active` is capped at `max_concurrent_streams` * `NUM_OF_ENDPOINTS`.   
However, when there are more than one downstream connection, `upstream_rq_active` peaks at `downstream_cx_active` * `max_concurrent_streams` * `NUM_OF_ENDPOINTS`, which clearly means that there are more than `MAX_CONCURRENT_STREAMS` active per endpoint.

One thing I noticed at this point was that there are actually more than one connection established to the endpoint, as seen by `upstream_cx_active`. Thus, I also tried limiting connection pool creation by specifying `max_connection_pools` in the circuit breaker configuration, but the subsequent requests made by other clients fails with `no healthy upstream` error in this case. This is also not desirable as we cannot determine the total number of clients that will be active before deployment.

Question:
> Is it possible to limit the maximum concurrent requests for each endpoint across multiple downstream connection?

Thanks.

**Comment by lambdai** [comment]
You may mislead by the max_concurrent_streams. It's not protecting the endpoint. It's protecting the connection to that endpoint. IIRC max_concurrent_streams is max_concurrent_streams **per upstream connection** and that endpoint can have multiple connections from this Envoy.

Could you look into circuit  breaker?
There are `max_connections` and `max_requests`. yet no concrete setting for per endpoint but that probably the right direction

**Comment by puilp0502** [comment]
@lambdai Thank you for the answer!

Although not satisfactory, limiting the maximum connections via `max_connections` combined with `--max-concurrency 1` option seems to do the trick:
```yaml
  clusters:
    - name: processor_cluster
      connect_timeout: 0.25s
      circuit_breakers:
        thresholds:
        - max_pending_requests: 16384
          max_connections: 1  # This, combined with --concurrency 1 does the trick
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:  # Forces HTTP/2 on upstream connection
              max_outbound_frames: 160000
              max_outbound_control_frames: 16000
              max_concurrent_streams: 4
      eds_cluster_config:
        eds_config:
          path: /etc/apx/eds.conf
          resource_api_version: "V3"
        service_name: localservices
      lb_policy: ROUND_ROBIN
      type: EDS
```
