### ISSUE TITLE
GRPC: problem with connections when GRPC server is unavailable

### ISSUE THREAD

**Issue by Green7** [envoyproxy/envoy#15309]
How do I set a timeout for the situation when Envoy is unable to connect to the GRPC server?

Now I have idle_timeout set to 0 because I don't want to close the GRPC streams if there is no data transferred. 
But it looks like idle_timeout is also used when a connection to the server cannot be established. 

So: if idle_timeout is 0, GRPC server is unavailable and I make a request, I will never get an error message.
From the level of the js client, the request continues indefinitely ! 

I checked to be sure and with the server unavailable and idle_timeout set to for example 5s, I get an error after 5 seconds.

How to solve it ?

**Comment by alyssawilk** [comment]
Generally the TCP connect_timeout (https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts) handles the issue where a server is not reachable.  Even with stream level timeouts off, if Envoy can't connect it should send an error back downstream.

**Comment by alyssawilk** [comment]
Hm, if the backend/upstream is unavailable that should work.  Can you drop your whole config in, and I can try to reproduce?

**Comment by Green7** [comment]
@alyssawilk Of course. The whole config:
```
 admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: grpcserver
                  idle_timeout: 0s
                  max_stream_duration:
                    grpc_timeout_header_max: 5s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: auth,lng,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: grpcserver
    connect_timeout: 0.25s
    type: static
    http2_protocol_options: {}
    lb_policy: round_robin
    # win/mac hosts: Use address: host.docker.internal instead of address: localhost in the line below
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.1.1.1
                    port_value: 12345

```
