### ISSUE TITLE
XDS over Google gRPC does not try to resolve DNS on connection close

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [envoyproxy/envoy#15380]
*Title*: *XDS over Google gRPC does not try to resolve DNS on connection reset*

*Description*:
When Envoy connects via XDS using Google gRPC (not Envoy gRPC) it seems that DNS name is only resolved once.
Let's say I've got 2 instances of the control plane behind a DNS name. Envoy connects to instance 1., then this instance is down, the result is that Envoy cannot reconnect to the second instance. It tries to connect to the first instance over and over (I checked with Wireshark that it tries to send SYN segments only to 1. instance).

This problem does not occur with Envoy gRPC with `STATIC_DNS` cluster.

We are using Google gRPC because we leverage `type.googleapis.com/envoy.config.grpc_credential.v3.FileBasedMetadataConfig` to provide channel credential.
We could switch to Envoy gRPC and use `initial_metadata`, but the problem is that auth credential will be then visible in `/config_dump` (I see no option to redact this)

*Repro steps*:
1. Run 2 instances of XDS server
2. Put them in /etc/hosts under DNS name `xds`
3. Configure Envoy to connect to `xds` using Google gRPC
4. Kill instance to which Envoy has connected
5. See that Envoy does not ever reconnect to other instance

I also tried to set some of `channelArgs`
```
  grpc_services:
  - googleGrpc:
      channelArgs:
        args:
          grpc.client_idle_timeout_ms:
            intValue: 1000
          grpc.max_connection_idle_ms:
            intValue: 1000
          grpc.max_connection_age_ms:
            intValue: 1000
          grpc.dns_min_time_between_resolutions_ms:
            intValue: 1000
```
but it did not solve a problem.

Is this expected behavior?

I dig a bit into a code
https://github.com/envoyproxy/envoy/blob/main/source/common/grpc/google_async_client_impl.cc#L92
could this be a problem that `GoogleAsyncClientImpl` builds a `grpc::Channel` once and maybe once Channel resolve a DNS into an IP, it tries to use it for the whole lifecycle of the client?

*Config*:
Simplified example of bootstrap config
```
admin:
  accessLogPath: /dev/null
  address:
    socketAddress:
      address: 127.0.0.1
      portValue: 30001
dynamicResources:
  adsConfig:
    apiType: GRPC
    grpcServices:
    - googleGrpc:
        statPrefix: ads
        targetUri: xds:5678
    transportApiVersion: V3
  cdsConfig:
    ads: {}
    resourceApiVersion: V3
  ldsConfig:
    ads: {}
    resourceApiVersion: V3
node:
  cluster: backend
  id: default.backend-01
```

*Logs*:
Some of the logs when problem occurs [logs.txt](https://github.com/envoyproxy/envoy/files/6109084/logs.txt)
