### ISSUE TITLE
serviceName not being sent to jaeger

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#15408]
I was using envoy version 1.17 and I just upgraded it to 1.18, its installed in a redhat vm

when using 1.17 and sending spans using this approach https://github.com/envoyproxy/envoy/tree/main/examples/jaeger-tracing, I was able to see the spans in jaeger

but now after upgrading it I cannot see them because they are being sent without the service name

this is the way I'm running envoy
`/usr/bin/envoy -c /etc/envoy/apple.yaml --service-cluster front-proxy --log-path /var/log/envoy.log -l debug`

This is my current configuration
```
                tracing:
                  provider:
                    name: envoy.tracers.zipkin
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                      collector_cluster: jaeger
                      collector_endpoint: "/api/v2/spans"
                      collector_hostname: "jaeger-collector-zipkin.xxx.com"
                      shared_span_context: false
                      collector_endpoint_version: HTTP_JSON
```
