### ISSUE TITLE
How can I download a .zip file over a http to grpc transcoded endpoint?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#15480]
I have the endpoint defined as below in my .proto file. The grpc endpoint returns a .zip file. It works OK over a grpc channel, but I'm having issues downloading it over the REST endpoint.

I use envoy to do the http transcoding.

My problem right now, on the REST endpoint, is that the download response header is always set to application/json instead of application/zip so my zip download is not properly handled by the browser.

Any idea how I can instruct envoy to set the proper headers during transcoding, so that the REST download will properly work ?

```
// Download build
  //
  // Download build
  rpc DownloadBuild(DownloadBuildRequest) returns (stream DownloadResponse) {
    option (google.api.http) = {
      get : "/v4/projects/{projectId}/types/{buildType}/builds/{buildVersion}/.download"
    };
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
      description: "Download build.";
      summary: "Download build.";
      tags: "Builds";
      responses: {
        key: "200"
        value: {
          description: "Download build";
        }
      }
      responses: {
        key: "401"
        value: {
          description: "Request could not be authorized";
        }
      }
      responses: {
        key: "404"
        value: {
          description: "Build not found";
        }
      }
      responses: {
        key: "500"
        value: {
          description: "Internal server error";
        }
      }
    };
  }
```

My Envoy config file looks like this:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: mix-api-listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 51051 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/v4/swagger-resources"}
                route: { prefix_rewrite: "/swagger-resources", cluster: swagger-backend-services, timeout: { seconds: 1500 } }
              - match: { prefix: "/v4/v2/api-docs"}
                route: { prefix_rewrite: "/v2/api-docs", cluster: swagger-backend-services, timeout: { seconds: 1500 } }
              - match: { prefix: "/v4/swagger-ui"}
                route: { prefix_rewrite: "/swagger-ui", cluster: swagger-backend-services, timeout: { seconds: 1500 } }
              - match: { prefix: "/", grpc: {} }
                route: { cluster: grpc-backend-services, timeout: { seconds: 120 } }
          http_filters:
          - name: envoy.grpc_json_transcoder
            config:
              proto_descriptor: "/data/mix-api.pb"
              services: ["mix.api.MixAPI"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
          - name: envoy.router

  clusters:
  - name: grpc-backend-services
    connect_timeout: 150s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: ${GRPC_HOST}
        port_value: 9090
  - name: swagger-backend-services
    connect_timeout: 150s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    hosts:
    - socket_address:
        address: ${GRPC_HOST}
        port_value: 8080

```

 I found this: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sending-arbitrary-content which seems to partially work, in the sense that I'm still not sure how to set the filename header
