### ISSUE TITLE
Support referencing http_filter name that is not the default type name in `per_filter_config` or `type_per_filter_config`

### ISSUE THREAD

**Issue by kev1n11** [envoyproxy/envoy#15504]
## Problem
We have 2 types of HTTP traffic, with different auth request headers. We would like to apply `ext_authz` filter with different values of `failure_mode_allow` based on the header.

## Attempts
Within a `http_connection_manager`, I've attempted the following:
1.  different filters of the _same_ type, _same_ name --> allowed 🟢, but obviously, I cant disable just one of them 🔴 
2. different filters of the _same_ type, _different_ name --> allowed 🟢 but when I try to reference that name in a `typed_per_filter_config` I get 🔴 
```
Didn't find a registered implementation for name: 'envoy.filters.http.ext_authz.failure_mode_allow'
```

Reading https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpfilter, it seems at least there was an intention for name to be different to the type if the type is specified.

```
name
(string, REQUIRED) The name of the filter configuration. The name is used as a fallback to select an extension if the type of the configuration proto is not sufficient. It also serves as a resource name in ExtensionConfigDS.
```

## Related Issues
From a bit of a search, possibly https://github.com/envoyproxy/envoy/issues/8659 or https://github.com/envoyproxy/envoy/issues/10164 but this seems a little bit more specific, potentially a bug? 

Happy for this to be merged to another issue if you see fit.

**Comment by kev1n11** [comment]
Config snippets
```
filter_chains:
  - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          http_filters:
            - name: envoy.filters.http.ext_authz.failure_mode_allow
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
```

and this is what results in an error
```
- match:
    prefix: "/"
  typed_per_filter_config:
    envoy.filters.http.ext_authz.failure_mode_allow:
      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
      disabled: true
```
