### ISSUE TITLE
I want to act as a proxy for rocketmq, is there any example configuration for reference

### ISSUE THREAD

**Issue by goudai** [envoyproxy/envoy#15514]
I want to act as a proxy for rocketmq, is there any example configuration for reference。

**Comment by phlax** [comment]
checking the docs i dont see any https://www.envoyproxy.io/docs/envoy/latest/search.html?q=rocket&check_keywords=yes&area=default

it would be great to add an example or even better a sandbox demonstrating how it works

**Comment by goudai** [comment]
Can you have a RedisClister example similar to the following, can you tell me how to configure RocketMQ proxy
```yaml
static_resources:
  listeners:
    - name: redis_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 6379
      filter_chains:
        filters:
          - name: redis
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
              stat_prefix: redis_stats
              prefix_routes:
                catch_all_route:
                  cluster: redis_cluster
              settings:
                op_timeout: 5s
                enable_redirection: true
  clusters:
    - name: redis_cluster
      lb_policy: CLUSTER_PROVIDED
      connect_timeout: 1s
      upstream_connection_options:
        tcp_keepalive:
          keepalive_time: 60
          keepalive_probes: 1
          keepalive_interval: 5
      load_assignment:
        cluster_name: redis_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: redis-cluster
                      port_value: 6379
      cluster_type:
        name: envoy.clusters.redis
        typed_config:
          "@type": type.googleapis.com/google.protobuf.Struct
          value:
            cluster_refresh_rate: 60s
            cluster_refresh_timeout: 4s
            redirect_refresh_interval: 10s
            redirect_refresh_threshold: 1
```
