### ISSUE TITLE
Retries Tracing Question

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#15522]
I'm running envoy with jaeger native tracing

is it possible to get the number of retries of a request and store it in jaeger with a tag?

This is my current retry mechanism
```
                      retry_policy:
                        retry_on: 5xx,retriable-4xx,connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,reset,gateway-error,retriable-status-codes
                        num_retries: 3
                        per_try_timeout: 6s
                        retry_back_off:
                          base_interval: "2s"
                          max_interval: "5s"
                        retriable_status_codes:
                          - 500
                          - 403
```

and I would like to see in jaeger UI how many times we retry with a tag or something
