### ISSUE TITLE
Various configs use http2_protocol_options deprecated field

### ISSUE THREAD

**Issue by davinci26** [envoyproxy/envoy#15559]
Various configs use (see `front-envoy-*.yaml` and others):

` http2_protocol_options: {}` which is deprecated instead of 
```
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
```

**Comment by davinci26** [comment]
I identified the following configs:

```
examples/cache/front-envoy.yaml
examples/cors/backend/front-envoy.yaml
examples/cors/frontend/front-envoy.yaml
examples/csrf/crosssite/front-envoy.yaml
examples/csrf/samesite/front-envoy.yaml
 examples/dynamic-config-cp/envoy.yaml
 examples/dynamic-config-fs/configs/cds.yaml
examples/ext_authz/config/grpc-service/v3.yaml
examples/ext_authz/config/opa-service/v3.yaml
examples/front-proxy/front-envoy.yaml
examples/grpc-bridge/server/envoy-proxy.yaml
examples/jaeger-native-tracing/front-envoy-jaeger.yaml
examples/jaeger-native-tracing/service1-envoy-jaeger.yaml
examples/jaeger-tracing/front-envoy-jaeger.yaml
examples/jaeger-tracing/service1-envoy-jaeger.yaml
examples/load-reporting-service/service-envoy-w-lrs.yaml
examples/skywalking-tracing/front-envoy-skywalking.yaml
examples/skywalking-tracing/service1-envoy-skywalking.yaml
examples/zipkin-tracing/front-envoy-zipkin.yaml
examples/zipkin-tracing/service1-envoy-zipkin.yaml
 ```

**Comment by phlax** [comment]
@davinci26 what is the default ?

im wondering if we can just remove them - the newer way seems complicated to just set an empty `{}`

**Comment by mattklein123** [comment]
cc @alyssawilk ^. How did this pass CI in the first place? I thought we force fixing all deprecated configs?

**Comment by alyssawilk** [comment]
setting http2 protocol options in the cluster config is deprecated
https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/cluster/v3/cluster.proto#L798
but setting http2 protocol options in the *http* config is not.
https://github.com/envoyproxy/envoy/blob/main/api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto#L69

If you take a look at the config you pasted it's using the new way of doing things

    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:

**Comment by davinci26** [comment]
I probably got confused somewhere when I was reading the `examples\cors\frontend\front-envoy.yaml`

```
  clusters:
  - name: frontend_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: frontend_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: frontendservice
                port_value: 8000
```
