### ISSUE TITLE
redis proxy: auth not work when using file monitor cds

### ISSUE THREAD

**Issue by qinggniq** [envoyproxy/envoy#15659]
*Title*: *redis proxy: auth not work when using cds*

*Description*:
>What issue is being seen? Describe what should be happening instead of
When I using cds to dynamic config my cluster config, auth is failed. 

*Repro steps*:
- run `docker-compose up --build -d` at examples/redis/ dir with below config.
I put the configs into my [branch](https://github.com/qinggniq/envoy/blob/redis-env/examples/redis/docker-compose.yaml)
*Config*:
>Include the config used to configure Envoy.
- envoy-dynamic.yaml
```yaml
node:
  id: id_1
  cluster: test

dynamic_resources:
  cds_config:
    path: "/etc/cds.yaml"

static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis
          prefix_routes: 
            catch_all_route:
              cluster: redis_cluster
          settings:
            op_timeout: 5s
          downstream_auth_password:
            inline_string: "123"
  
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
- cds.yaml
```yaml
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: redis_cluster
  connect_timeout: 1s
  type: STRICT_DNS # static
  lb_policy: MAGLEV
  typed_extension_protocol_options:
    envoy.filters.network.redis_proxy:
      "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
      auth_password:
        inline_string: "123"
  load_assignment:
    cluster_name: redis_cluster
    endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6379
```
*Logs*:
>Include the access logs and the Envoy logs.
```shell
$ redis-cli -h localhost -p 1999
localhost:1999> auth 123
OK
localhost:1999> set x y
(error) NOAUTH Authentication required.
```
