### ISSUE TITLE
Redis extension accepts only slots with IPv4

### ISSUE THREAD

**Issue by amirkhonov** [envoyproxy/envoy#15704]
*Title*: *Redis extension accepts only slots with IPv4*

*Description*:
I'm using this config to define Elasticache as a cluster in Envoy instance:
```yaml
name: redis_cluster
    connect_timeout: 3s
    cluster_type:
      name: envoy.clusters.redis
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: elasticache_clustercfg_host
                port_value: 6379
```
As per https://github.com/envoyproxy/envoy/blob/c04a75efe9d601ebcb9650f274b5adde60181f1c/source/extensions/clusters/redis/redis_cluster.cc#L228 it is not allowed to receive DNS hostnames in the Elasticache response with CLUSTER SLOTS.

I'm receiving an error from Envoy:
`[1][debug][upstream] [source/extensions/clusters/redis/redis_cluster.cc:225] Invalid ip address in CLUSTER SLOTS response: malformed IP address: elasticache_clustercfg_host`

AWS Elasticache returns list of primary and slave instances hostnames in the response. 

How to resolve this problem without changing the source code? Thank you!
