### ISSUE TITLE
How to strip host port for HTTP CONNECT

### ISSUE THREAD

**Issue by grzegorz-mirek** [envoyproxy/envoy#15771]
*Description*:

I have configured dynamic forward proxy that terminates HTTP/1.1 CONNECT and I have the following flow:

```
HTTP client ---HTTP-CONNECT---> Envoy ---HTTPS---> destination
```

The HTTP client (Micronaut app) uses HTTP CONNECT even for **plain HTTP** requests (as opposed to most HTTP clients that use [extended HTTP](https://docs.mitmproxy.org/stable/concepts-howmitmproxyworks/#explicit-http) request that includes a schema and host specification). It means that something like that is sent to Envoy:

```
 CONNECT www.google.com:80
```

 When the request reaches Envoy, I use CONNECT  matcher:

```
- match:
    connect_matcher:
      {}
  route:
    cluster: dynamic_forward_proxy_cluster
    upgrade_configs:
      - upgrade_type: CONNECT
        connect_config:
          {}
```

and:

```
http_filters:
- name: envoy.filters.http.router
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
http_protocol_options: {}
upgrade_configs:
  - upgrade_type: CONNECT
```

and forward the request to dynamic forward proxy cluster:

```
- name: dynamic_forward_proxy_cluster
  connect_timeout: 1s
  lb_policy: CLUSTER_PROVIDED
  cluster_type:
    name: envoy.clusters.dynamic_forward_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
      dns_cache_config:
        name: dynamic_forward_proxy_cache_config
        dns_lookup_family: V4_ONLY
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      common_tls_context:
        validation_context:
          trusted_ca: { filename: /etc/ssl/certs/ca-certificates.crt }
```

The cluster has TLS context configured - and as a result, I end up with the request to `https://www.google.com:80`:

```
 router decoding headers:
':authority', 'www.google.com:80'
':method', 'CONNECT'  // not sure about this one though - there is no CONNECT in Wireshark, so I assume that CONNECT is terminated correctly 
':scheme', 'https'
'x-forwarded-proto', 'http'
'x-request-id', '4394422c-fe2f-4741-a8c3-e46e8f6aa0f6'
'x-envoy-expected-rq-timeout-ms', '15000'
```

which leads to:

```
[external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:215] [C4] TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

I believe the culprit is the `:80` port that is forwarded from the listener to the dynamic forward cluster and then the cluster uses port 80 to establish TLS. If I explicitly specify `http://www.google.com:443` in Micronaut client, everything works well.

There is [strip_any_host_port](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-strip-any-host-port) switch, but it explicitly states: 

> The port would be removed only if request method is not CONNECT.

My questions are:
1) Why is there an exception in `strip_any_host_port` for CONNECT?
2) Is there other way to strip the host port in my scenario?
