### ISSUE TITLE
[Question] How properly set up front proxy for both web and grpc services

### ISSUE THREAD

**Issue by BatanGaming** [envoyproxy/envoy#15834]
*Description*:
I'm trying to set up front proxy which will redirect to one of "stands". Each stand consists of own proxy, some web services and one grpc service for mobile client. But when I try to connect to the grpc service through front proxy it fails with 
`"- - HTTP/2" 0 DPE 0 0 0 - "-" "-" "-" "-" "-"`. So what I did wrong?

Here's what I want to achieve (stand's proxy works fine):
![](https://i.imgur.com/nCombyz.png)

Front proxy's configuration:
```
static_resources:
  listeners:
  - name: backend_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          route_config:
            name: backend_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                    prefix: "/stand1/"
                route:
                    prefix_rewrite: "/"
                    cluster: gateway1
              - match:
                    prefix: "/stand1"
                route:
                    prefix_rewrite: "/"
                    cluster: gateway1
                    
              - match:
                    prefix: "/stand2/"
                route:
                    prefix_rewrite: "/"
                    cluster: gateway2
              - match:
                    prefix: "/stand2"
                route:
                    prefix_rewrite: "/"
                    cluster: gateway2

          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}

                  
  clusters:
  - name: gateway1
    connect_timeout: 30s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    load_assignment:
      cluster_name: gateway1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: gateway1
                port_value: 80

  - name: gateway2
    connect_timeout: 30s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    load_assignment:
      cluster_name: gateway2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: gateway2
                port_value: 80
```
