### ISSUE TITLE
JWT Authentication failed to fetch remote jwks after updating docker

### ISSUE THREAD

**Issue by BatanGaming** [envoyproxy/envoy#15854]
Envoy version: 1.17

I've just updated `Docker Desktop` to RC3 version for apple silicon and now I get error `Jwks remote fetch is failed`. Before it was working well, still maybe there are some issues with my config. Any ideas?

Config:
```
static_resources:
  listeners:
  - name: backend_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing:
            provider:
              name: envoy.tracers.zipkin
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                collector_cluster: jaeger
                collector_endpoint: "/api/v2/spans"
                shared_span_context: false
                collector_endpoint_version: HTTP_JSON
          stat_prefix: ingress_http
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          route_config:
            name: backend_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              # Order is important
              - match:
                  prefix: "/api"
                route:
                  cluster: web_cluster
              
              - match:
                  prefix: "/"
                route:
                  cluster: web_cluster

          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                cognito_provider:
                  issuer: "https://cognito-idp.<region>.amazonaws.com/<user-pool-id>"
                  forward_payload_header: x-jwt-payload
                  remote_jwks:
                    http_uri:
                      uri: https://cognito-idp.<region>.amazonaws.com/<user-pool-id>/.well-known/jwks.json
                      cluster: cognito_jwks_cluster
                      timeout: 5s
                    cache_duration:
                      seconds: 600
              rules:
              # Order is important
              - match:
                  prefix: /api
                requires: { provider_name: cognito_provider }
          - name: envoy.filters.http.router
            typed_config: {}

                  
  clusters:
  - name: web_cluster
    connect_timeout: 30s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: web_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web
                port_value: 80

  - name: cognito_jwks_cluster
    connect_timeout: 5s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cognito_jwks_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: cognito-idp.<region>.amazonaws.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      
  - name: jaeger
    connect_timeout: 2s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: jaeger
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: jaeger
                port_value: 9411

```
