### ISSUE TITLE
Connecting with IP when the listener is configured with SNI

### ISSUE THREAD

**Issue by VigneshSP94** [envoyproxy/envoy#15869]
We are PoC-ing envoy to use it as our load balancer, we are trying to utilize the SNI feature and it works perfectky fine.

But when we try to connect to IP of the listener that is configured with SNI, we get `no matching filter chain found` and the request fails.

We use curl with option `-k` to do this.

Below is the minimal configuration to do this

```
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: demo-https
  address:
    socket_address:
      address: 100.x.x.x
      port_value: 443
  listener_filters:
  - name: "envoy.filters.listener.tls_inspector"
    typed_config: {}
  filter_chains:
          #- use_proxy_proto: true
  - filter_chain_match:
      server_names: ["*.example.net", "example.net"]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        cluster: demo-https-cluster
        common_tls_context:
          tls_certificates:
          - certificate_chain: { filename: "/etc/certs/asterisk.example.net.chain" }
            private_key: { filename: "/etc/certs/asterisk.example.net.key" }
    filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: http
        cluster: demo-https-cluster
        rds:
          route_config_name: demo-rds
          config_source:
            path: "/etc/envoy/rds/demo-rds.yaml"
        access_log:
        - name: log
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: "/var/log/envoy.log"
            typed_json_format: *json_Format
        http_filters:
        - name: envoy.router
          config: {}
```
My questions are : 

1. Will connecting with IP work if SNI is enabled and specified?
2. If it does not support, any suggestions to use multiple certificates like haproxy supports?

Thank you !
