### ISSUE TITLE
Envoy proxy http to https redirect with dynamoDB (aws request signing)

### ISSUE THREAD

**Issue by dragonbone81** [envoyproxy/envoy#15861]
The basic flow that I want to achieve is:
- application sends dynamoDB request to envoy
- envoy intercepts this request and transforms the body with a lua filter
- envoy sends this request to a dynamoDB endpoint

I have achieved the first two steps. However I'm stuck on getting the request to the dynamoDB endpoint. In my application I set the dynamoDB endpoint as http://envoy:8888 (the host/port envoy is running on in my docker image). 

My enovy yaml file:
```
static_resources:
  listeners:
    - address:
        socket_address:
          protocol: "TCP"
          address: 0.0.0.0
          port_value: 8888
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamo-service
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        require("envoy_lua.envoy")
                  - name: envoy.filters.http.router
  clusters:
    - name: dynamo-service
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: dynamo-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: dynamodb.us-west-2.amazonaws.com
                      port_value: 443
```
Using this configuration I get the error message back: The plain HTTP request was sent to HTTPS port.
This makes sense to me I think but not sure how to fix this.

 In the routes section I have also tried using redirect without any luck, I just get a 301 response back
```
redirect:
    https_redirect: true
    host_redirect: dynamodb.us-west-2.amazonaws.com
```
I have also tried adding a transport_socket section to the cluster with no luck still:
```
transport_socket:
        name: envoy.transport_sockets.tls
        typedConfig:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

Trying to see what the solution to this is, or if it's even possible. Thanks!

**Comment by dragonbone81** [comment]
Figured out using this will transform the http request
```
transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

However the signing filter is not working correctly and giving an exception: The security token included in the request is invalid
```
- name: envoy.filters.http.aws_request_signing
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
      service_name: dynamodb
      region: us-west-2
      host_rewrite: dynamodb.us-west-2.amazonaws.com
```
