### ISSUE TITLE
Global Rate limit not taking effect: Istio 1.9.x

### ISSUE THREAD

**Issue by V3K3R** [envoyproxy/envoy#15915]
*Title*: *Global Rate limit not taking effect: Istio 1.9.x*

*Description*:
After applying a global rate limit on a host, the rate limits seem to be added to the host config, but not taking any effects.
```
            {
                "name": "api.omitted_domain.com:80",
                "domains": [
                    "api.omitted_domain.com",
                    "api.omitted_domain.com:*"
                ],
                "routes": [
                    {
                        "match": {
                            "prefix": "/bvs/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|80||bvs-leadapp-api.bvs.svc.cluster.local",
                            "prefixRewrite": "/",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            }
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/bvs/virtual-service/bvs-vs"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "bvs-leadapp-api.bvs.svc.cluster.local:80/bvs/*"
                        },
                        "requestHeadersToAdd": [
                            {
                                "header": {
                                    "key": "x-auth-realm",
                                    "value": "bvs"
                                },
                                "append": true
                            },
                            {
                                "header": {
                                    "key": "x-auth-type",
                                    "value": "token"
                                },
                                "append": true
                            }
                        ]
                    },
                    {
                        "match": {
                            "prefix": "/nginx/",
                            "caseSensitive": true
                        },
                        "route": {
                            "cluster": "outbound|80||nginx-poc.bvs.svc.cluster.local",
                            "prefixRewrite": "/",
                            "timeout": "0s",
                            "retryPolicy": {
                                "retryOn": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
                                "numRetries": 2,
                                "retryHostPredicate": [
                                    {
                                        "name": "envoy.retry_host_predicates.previous_hosts"
                                    }
                                ],
                                "hostSelectionRetryMaxAttempts": "5",
                                "retriableStatusCodes": [
                                    503
                                ]
                            }
                        },
                        "metadata": {
                            "filterMetadata": {
                                "istio": {
                                    "config": "/apis/networking.istio.io/v1alpha3/namespaces/bvs/virtual-service/nginx-vs"
                                }
                            }
                        },
                        "decorator": {
                            "operation": "nginx-poc.bvs.svc.cluster.local:80/nginx/*"
                        }
                    }
                ],
                "requireTls": "ALL",
                "rateLimits": [
                    {
                        "actions": [
                            {
                                "requestHeaders": {
                                    "headerName": ":path",
                                    "descriptorKey": "PATH"
                                }
                            }
                        ]
                    }
                ],
                "includeRequestAttemptCount": true
            },
```
Rate limit and Redis service Config:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: rate-limit
data:
  config.yaml: |
    domain: echo-ratelimit
    descriptors:
      - key: PATH
        value: "/nginx"
        rate_limit:
          unit: minute
          requests_per_unit: 1
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rate-limit
  labels:
    app: redis
spec:
  ports:
  - name: redis
    port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: rate-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: Always
        name: redis
        ports:
        - name: redis
          containerPort: 6379
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  namespace: rate-limit
  labels:
    app: ratelimit
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc-port
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: http-debug
    port: 6070
    targetPort: 6070
    protocol: TCP
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
  namespace: rate-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
      - image: envoyproxy/ratelimit:6f5de117 # 2021/01/08
        imagePullPolicy: Always
        name: ratelimit
        command: ["/bin/ratelimit"]
        env:
        - name: LOG_LEVEL
          value: debug
        - name: REDIS_SOCKET_TYPE
          value: tcp
        - name: REDIS_URL
          value: redis:6379
        - name: USE_STATSD
          value: "false"
        - name: RUNTIME_ROOT
          value: /data
        - name: RUNTIME_SUBDIRECTORY
          value: ratelimit
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 6070
        volumeMounts:
        - name: config-volume
          mountPath: /data/ratelimit/config/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: ratelimit-config
```

*Config*:
These are the envoy filters definitions
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      istio: ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        # Adds the Envoy Rate Limit Filter in HTTP filter chain.
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            # domain can be anything! Match it to the ratelimter service config
            domain: echo-ratelimit
            failure_mode_deny: true
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: rate_limit_cluster
                timeout: 10s
              transport_api_version: V3
    - applyTo: CLUSTER
      match:
        cluster:
          service: ratelimit.rate-limit.svc.cluster.local
      patch:
        operation: ADD
        # Adds the rate limit service cluster for rate limit service defined in step 1.
        value:
          name: rate_limit_cluster
          type: STRICT_DNS
          connect_timeout: 10s
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: rate_limit_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: ratelimit.rate-limit.svc.cluster.local
                          port_value: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-ratelimit-svc
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "api.omitted_domain.com:80"
            route:
              action: ANY
      patch:
        operation: MERGE
        # Applies the rate limit rules.
        value:
          rate_limits:
            - actions: # any actions in here
                - request_headers:
                    header_name: ":path"
                    descriptor_key: "PATH"
```
I enabled debug mode on istio-ingressgateway, and I can't see anything helpful, except the absence of calls to the rate limit service maybe.
I believe I m doing as outlined in the documentation, and I would appreciate any input on how to debug this further, or if it's a bug in Istio rate limits. Thank you :pray:
