### ISSUE TITLE
RBAC filter config on JWT metadata (JwtAuthentication)

### ISSUE THREAD

**Issue by nonefaken** [envoyproxy/envoy#15911]
Hello,

i have problem with configuration of RBAC filter for JWT metadata (JwtAuthentication).

I`m using envoyproxy/envoy-alpine:v1.17-latest

This works:
```
                     "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                           ....
                                  filter: envoy.filters.http.jwt_authn
                                  path:
                                    - key: my_payload
                                    - key: aud
                                  value:
                                    string_match:
                                      exact: api2
```

This does not work:
```
                      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                           ....
                                  filter: envoy.filters.http.jwt_authn
                                  path:
                                    - key: my_payload
                                    - key: resource_access
                                    - key: api2
                                    - key: roles
                                  value:
                                    string_match:
                                      exact: admin
```

This does not work as well:
```
                      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                           ....
                                  filter: envoy.filters.http.jwt_authn
                                  path:
                                    - key: my_payload
                                    - key: roles
                                  value:
                                    string_match:
                                      exact: admin
```

Attaching JWT token dynamicMetadata from Envoy proxy debug log:
```
proxy2         | , dynamicMetadata: filter_metadata {
proxy2         |   key: "envoy.filters.http.jwt_authn"
proxy2         |   value {
proxy2         |     fields {
proxy2         |       key: "my_payload"
proxy2         |       value {
proxy2         |         struct_value {
proxy2         |           fields {
proxy2         |             key: "acr"
proxy2         |             value {
proxy2         |               string_value: "1"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "allowed-origins"
proxy2         |             value {
proxy2         |               list_value {
proxy2         |                 values {
proxy2         |                   string_value: ""
proxy2         |                 }
proxy2         |               }
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "aud"
proxy2         |             value {
proxy2         |               string_value: "api2"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "auth_time"
proxy2         |             value {
proxy2         |               number_value: 1618064947
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "azp"
proxy2         |             value {
proxy2         |               string_value: "api"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "email"
proxy2         |             value {
proxy2         |               string_value: "testing@test.com"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "email_verified"
proxy2         |             value {
proxy2         |               bool_value: true
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "exp"
proxy2         |             value {
proxy2         |               number_value: 1618066747
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "family_name"
proxy2         |             value {
proxy2         |               string_value: "test"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "given_name"
proxy2         |             value {
proxy2         |               string_value: "test"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "iat"
proxy2         |             value {
proxy2         |               number_value: 1618064947
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "iss"
proxy2         |             value {
proxy2         |               string_value: "http://keycloak:8080/auth/realms/api"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "jti"
proxy2         |             value {
proxy2         |               string_value: "fedecf29-d392-438d-8392-5d027f90ed48"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "name"
proxy2         |             value {
proxy2         |               string_value: "test test"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "preferred_username"
proxy2         |             value {
proxy2         |               string_value: "test"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "resource_access"
proxy2         |             value {
proxy2         |               struct_value {
proxy2         |                 fields {
proxy2         |                   key: "api2"
proxy2         |                   value {
proxy2         |                     struct_value {
proxy2         |                       fields {
proxy2         |                         key: "roles"
proxy2         |                         value {
proxy2         |                           list_value {
proxy2         |                             values {
proxy2         |                               string_value: "admin"
proxy2         |                             }
proxy2         |                           }
proxy2         |                         }
proxy2         |                       }
proxy2         |                     }
proxy2         |                   }
proxy2         |                 }
proxy2         |               }
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "scope"
proxy2         |             value {
proxy2         |               string_value: "user email good-service profile"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "session_state"
proxy2         |             value {
proxy2         |               string_value: "c9653f2b-cf02-4400-b3f1-6817dcad67d9"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "sub"
proxy2         |             value {
proxy2         |               string_value: "9c706d88-a5d7-42de-87cd-963219f802ea"
proxy2         |             }
proxy2         |           }
proxy2         |           fields {
proxy2         |             key: "typ"
proxy2         |             value {
proxy2         |               string_value: "Bearer"
proxy2         |             }
proxy2         |           }
proxy2         |         }
proxy2         |       }
proxy2         |     }
proxy2         |   }
proxy2         | }
```

Im sure it is simple, but im stuck due to lack of experience.

Thank you!

**Comment by nonefaken** [comment]
For anyone wondering it was realy easy fix:
```
                                  filter: envoy.filters.http.jwt_authn
                                  path:
                                    - key: my_payload
                                    - key: resource_access
                                    - key: api2
                                    - key: roles
                                  value:
                                    list_match:
                                      one_of:
                                        string_match:
                                          exact: admin
```
