### ISSUE TITLE
How to properly use multiple certificates for downstream tls context

### ISSUE THREAD

**Issue by BatanGaming** [envoyproxy/envoy#15939]
Let's say I have 2 certificates - for `example.com` and for `*.example.com`. 
In envoy config I have 2 virtual host - `mobile.example.com` and `example.com`. 
So how to configure tls to use `example.com` certificate for `example.com` and `*.example.com` for `mobile.example.com`?
I tried to do this:
```yaml
transport_socket:
  name: envoy.transport_sockets.tls
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
    common_tls_context:
      tls_certificates:
      - certificate_chain:
          filename: /etc/ssl/certs/prod/fullchain.pem
        private_key:
          filename: /etc/ssl/certs/prod/privkey.pem
      - certificate_chain:
          filename: /etc/ssl/certs/wildcard/fullchain.pem
        private_key:
          filename: /etc/ssl/certs/wildcard/privkey.pem
```
But it doesn't work
