### ISSUE TITLE
How to use AWS Request signing filter (AwsRequestSigning)

### ISSUE THREAD

**Issue by dragonbone81** [envoyproxy/envoy#15963]
I'm trying to proxy AWS DynamoDB requests through envoy and I'm changing the data in the requests. Because of this I need to re-sign the requests (they've already been signed by the AWS SDK that made the original request). The request goes into a lua filter first.

I configured the filter like this:
```
name: envoy.filters.http.aws_request_signing
  typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
      service_name: dynamodb
      region: us-west-2
      host_rewrite: dynamodb.us-west-2.amazonaws.com
```

I also need to strip the original `authorization` header as it seems the filter just appends onto it.
If I leave the request like this AWS returns a `UnrecognizedClientException: The security token included in the request is invalid. message: 'The security token included in the request is invalid`

I've also tried stripping the other aws specific headers that the SDK inserts like 
```
x-amz-security-token
x-amz-date
x-amz-content-sha256
amz-sdk-invocation-id
amz-sdk-retry
```
However when I do this the error returned from AWS is: `The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

Any help would be appreciated!
