### ISSUE TITLE
Importing multiple Lua scripts through LDS/RDS API?

### ISSUE THREAD

**Issue by v1b1** [envoyproxy/envoy#15991]
*Title*: Possible to import multiple Lua scripts through LDS/RDS API without requiring them to be available on Envoy's filesystem?

*Description*:
I configured my LDS to send a Lua V3 HTTP filter to Envoy v1.17.1 in the following format:

```yaml
http_filters:
- name: envoy.filters.http.lua
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
    inline_code: |
      local lib = require "mylib"
      ...
    source_codes:
      mylib.lua:
        inline_string: ...
      mylib_deps/otherlib.lua:
        inline_string: ...
```

But Envoy outputs the following:
```
[2021-04-15 16:11:52.430][1][warning][config] [source/common/config/http_subscription_impl.cc:123] REST config for /v3/discovery:listeners rejected: Error adding/updating listener(s) service_listener: script load error: [string "local lib = require "mylib"..."]:1: module 'mylib' not found:
      no field package.preload['mylib']
      no file './mylib.lua'
      no file '/tmp/tmp.8O2loKmZrQ/luajit/share/luajit-2.1.0-beta3/mylib.lua'
      no file '/usr/local/share/lua/5.1/mylib.lua'
      no file '/usr/local/share/lua/5.1/mylib/init.lua'
      no file '/tmp/tmp.8O2loKmZrQ/luajit/share/lua/5.1/mylib.lua'
      no file '/tmp/tmp.8O2loKmZrQ/luajit/share/lua/5.1/mylib/init.lua'
      no file './mylib.so'
      no file '/usr/local/lib/lua/5.1/mylib.so'
      no file '/tmp/tmp.8O2loKmZrQ/luajit/lib/lua/5.1/mylib.so'
      no file '/usr/local/lib/lua/5.1/loadall.so'
```

How can I reference `source_codes` files from my `GLOBAL` Lua script?
