### ISSUE TITLE
Support destination port range in config.rbac.Permission

### ISSUE THREAD

**Issue by lexh** [envoyproxy/envoy#16039]
I am using [config.rbac.Permission](https://github.com/envoyproxy/envoy/blob/5a8bfa20dc3c85ecb61826d122696ecaa75dffa0/api/envoy/config/rbac/v3/rbac.proto#L145) to configure RBAC for a dynamic forward proxy.

My proxy configuration needs to support allowing large port ranges.

Today, I can achieved this by combining thousands of [Permission.destination_port](https://github.com/envoyproxy/envoy/blob/5a8bfa20dc3c85ecb61826d122696ecaa75dffa0/api/envoy/config/rbac/v3/rbac.proto#L182) rules using [Permission.Set.or_rules](https://github.com/envoyproxy/envoy/blob/5a8bfa20dc3c85ecb61826d122696ecaa75dffa0/api/envoy/config/rbac/v3/rbac.proto#L164),
similar to this (modified) snippet from the [config.rbac.RBAC docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto#config-rbac-v3-rbac).

```
  "product-viewer":
    permissions:
        - and_rules:
            rules:
              - header: { name: ":method", exact_match: "GET" }
              - url_path:
                  path: { prefix: "/products" }
              - or_rules:
                  rules:
                    - destination_port: 1000
                    - destination_port: 1001
                    # .
                    # ... a lot of lines
                    # .
                    - destination_port: 1999
```

This is functional but cumbersome.

It would be more ergonomic if Permission had a destination port range field, similar to what exists in [config.listener.ListenerFilterChainMatchPredicate](https://github.com/envoyproxy/envoy/blob/5a8bfa20dc3c85ecb61826d122696ecaa75dffa0/api/envoy/config/listener/v3/listener_components.proto#L324).
