### ISSUE TITLE
Stats tag regex not capturing substring ending in non-dot character

### ISSUE THREAD

**Issue by VigneshSP94** [envoyproxy/envoy#16062]
*Description*:
We are trying to utilize the `stats_config` feature to extract/expose some metrics.

Metric page outputs -
```
cluster.appname__someinfo__someotherinfo__anotherinfo.assignment_stale: 0
.
.
```

We are trying to match the `appname` which is between `cluster.` and the first `_`. And the regex we tried is `^cluster\\.((.*?)_)`, this gives no output.

We get everything between two `.`'s when we use `^cluster\\.((.*?)\\.)`, but we need to match the substring.

Config -
```
stats_config:
  use_all_default_tags: false
  stats_tags:
  - tag_name: "app"
    regex: "^cluster\\.((.*?)_)"
```

Is it possible to do what we're trying?
