### ISSUE TITLE
Variables in route match

### ISSUE THREAD

**Issue by darox** [envoyproxy/envoy#16099]
I'd like to make use of variables in route match. Is something like this possible:
```
route_config:
  name: local_route
  virtual_hosts:
  - name: admin
    domains:
    - "*"
    routes:
    - match:
        prefix: "/snmp/{var}"
      route:
        cluster: snmp
        prefix_rewrite: "/snmp?target={var}"
http_filters:
- name: envoy.filters.http.router
  typed_config: {}
```

Note the {var}

Thx a lot!

**Comment by darox** [comment]
I could solve the issue by using regex:
```
- name: admin
              domains:
              - "*"
              routes:
              - match:
                  safe_regex:
                    google_re2: {}
                    regex: "\/snmp.*"
                route:
                  cluster: snmp
```
