### ISSUE TITLE
How to configure query_parameters not exist match

### ISSUE THREAD

**Issue by chenyanshan** [envoyproxy/envoy#16143]
"sign" not exist match. how to configure?

```
              routes:
              - match:
                  prefix: "/log"
                  query_parameters:
                  - name: "sign"
                    present_match: true
```
