### ISSUE TITLE
use_original_dst with original_dst listener filter

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#16179]
The `use_original_dst` is a field in listener config.

The long lasting behavior in Envoy code is to 
1. add an `original_dst_listener_filter` at the last
2. look up the best destination listener in bind_to_port=false listener candiates.

There are more approaches to recover the original_dst address: including proxy protocol and another self-defined recovery method.
We should strip the responsibility (1)  from the field `use_original_dst`

This would prevent DNAT original_dst always win. 
Also Control plane can determine when the original_dst is recovered. 

For compatiblity we can introduce new enum field: 
enum original_dst_option {
   add_original_dst_listener_filter_to_the_last;         // Default behavior
   do_not_add_original_dst_listener_filter;                // listener 
}

**Comment by tomastigera** [comment]
I am not sure the order of filters is the main issue in https://github.com/envoyproxy/envoy/issues/16130 if that is what is proposed here.

**Comment by lambdai** [comment]
original_dst filter is always added to the last is my pain. 

I agree with you that we should add extra configuration to the existing (TPROXY style restore address)

To fulfill #16130 you can set `do_not_add_original_dst_listener_filter` and use the new original_dst_fitler config as you want.

**Comment by tomastigera** [comment]
> To fulfill #16130 you can set `do_not_add_original_dst_listener_filter` and use the new original_dst_fitler config as you want.

I am still not sure I follow here - how would that help me? This is the envoy config I use in my case/tests:

```
static_resources:
  listeners:
    - name: inbound
      transparent: true
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 16001
      listener_filters:
        - name: envoy.filters.listener.original_dst
          typed_config: {}
        - name: envoy.filters.listener.original_src
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.original_src.v3.OriginalSrc
            mark: 12
      filter_chains:
        - filter_chain_match: {}
          filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: ingress_tcp
              cluster: original_dst_cluster
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/tmp/envoy.log"
                  typed_json_format:
                    reporter: "destination"
                    start_time: "%START_TIME%"
                    duration: "%DURATION%"
                    response_code: "%RESPONSE_CODE%"
                    bytes_sent: "%BYTES_SENT%"
                    bytes_received: "%BYTES_RECEIVED%"
                    user_agent: "%REQ(USER-AGENT)%"
                    request_path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    request_method: "%REQ(:METHOD)%"
                    request_id: "%REQ(X-REQUEST-ID)%"
                    type: "tcp"
                    downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                    downstream_local_address : "%DOWNSTREAM_LOCAL_ADDRESS%"
                    domain: "%REQ(HOST?:AUTHORITY)%"
                    upstreamstream_local_address : "%UPSTREAM_LOCAL_ADDRESS%"
                    upstream_transport_failure_reason : "%UPSTREAM_TRANSPORT_FAILURE_REASON%"
  clusters:
    - name: original_dst_cluster
      type: ORIGINAL_DST
      connect_timeout: 6s
      lb_policy: CLUSTER_PROVIDED
```
