### ISSUE TITLE
Simpler listener configuration for multiple domains with TLS support

### ISSUE THREAD

**Issue by shamsimam** [envoyproxy/envoy#16174]
*Title*: Simpler listener configuration for multiple domains with TLS support

[Cross-post from envoy-users group](https://groups.google.com/g/envoy-users/c/NFHBKuLFehE) where there was little response.

*Description*:
**tl;dr** What is the simplest way to provide a mapping of domains to certificates and avoid generating repeated (one that can easily be templated by the domain+cert combination) filter chain configurations in the Envoy listener config?

**Details**:

The example for configuring multiple domains suggests configuring multiple filter chains. For example, using the examples in this document for two custom domains we have something like in our listener configurations:
```
filter_chains:
- filter_chain_match:
    server_names: ["foo.example.com"]
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "/path/foo/cert.pem" }
          private_key: { filename: "/path/foo/key.pem" }
  # other configuration
  ...
- filter_chain_match:
    server_names: "bar.example.com"
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "/path/bar/cert.pem" }
          private_key: { filename: "/path/bar/key.pem" }
  # other configuration (repeat of what we have for foo.example.com
  ...
# repeat for every other domain
```
When configuring listeners for many domains (in the order of thousands) this can become quite cumbersome as there is one entry per domain name with repeated associated configuration on other options and yields a very large configuration file (in the order of MBs). In addition, anytime a domain name gets added or removed, the configuration has to be regenerated (for LDS). Separately, use of CommonTlsContext means reloading the certificate needs an Envoy hot-restart. 

The Envoy documentation of Certificate Management says:

Secret Discovery Service referenced certificates. By using SDS, certificates can either be referenced as files (reloading the certs when the parent directory is moved) or through an external SDS server that can push new certificates.

We explored the use of SDS file as documented in this article:
```
 common_tls_context:
     alpn_protocols: ["h2", "http/1.1"]
     tls_certificate_sds_secret_configs:
         sds_config:
             path: /etc/envoy/sds.yaml
```
But, SDS yaml files can contain only a single entry, and attempting to configure multiple domain mapping fails with the following message:
```
[2021-03-16 23:40:35.661][909395][warning][config] [source/common/config/filesystem_subscription_impl.cc:43] Filesystem config update rejected: Unexpected SDS secrets length: 251
```
As a result, using SDS with the file-based approach means we need to generate additional files, one per domain, to support dynamic refresh of certificates on top of the filter chain listener configurations described above.

**Question**:

What is the better alternative for configuring listeners for multiple domains along with TLS cert configuration? Ideally, we avoid repeating filter chain configurations and generating multiple files for certificates.

**Relevant feature in HAProxy**:

We have previously used HAProxy for similar configurations where a common “listener” configuration can be provided for multiple domains with the per domain certificate lookup dynamically configured via an external table (crt-list option). This yields a much smaller configuration file, in the order of KBs when everything is combined.

**ECDS mentioned in user group**:

There was some [mention of ECDS in the user-group thread](https://groups.google.com/g/envoy-users/c/NFHBKuLFehE/m/Y-mo_DdYCwAJ), but I was unable to find an example. Reading what little I was able to find about it looks promising. Do we have an idea what the example would look like for the dummy configuration with foo.example.com and bar.example.com I have above? A link to a good reference would also be much appreciated.

Thanks in advance for your help.

**Comment by yanavlasov** [comment]
@alyssawilk @htuch @mattklein123 for any comments.

**Comment by htuch** [comment]
You could add support potentially for `> 1` TLS certificate of a given type in `CommonTlsContext` `tls_certificates`, but would need to deal with the challenges around overlapping SANs etc. That would still have the problem of having to update large listeners at scale.

I think FCDS would solve the scaling problem here if we implemented it https://github.com/envoyproxy/envoy/issues/4540, but I don't think anyone is working on it actively.

CC @ggreenway @envoyproxy/tls-watchers @lambdai

**Comment by shamsimam** [comment]
Thanks for the responses.

> Is all other listener/filter configuration identical, and you just want to map a domain to a tls certificate?

That is cirrect.

> And I presume that you can't combine many SANs into the same cert? 

That is correct, we do not want to combine multiple SANs into the same certificate.

> If so, a handshaker that just handles providing the correct certificate might solve some of your problem.

Are there any existing issues around this that I can follow to track progress along these lines?

**Comment by ggreenway** [comment]
You can see an example in the tests: https://github.com/envoyproxy/envoy/blob/63307f55889d35ce98a34afe7a9aaaf0277304d3/test/extensions/transport_sockets/tls/handshaker_test.cc#L179

**Comment by shamsimam** [comment]
Thank you!

**Comment by htuch** [comment]
@shamsimam do you pan on working on this one?

**Comment by shamsimam** [comment]
> @shamsimam do you pan on working on this one?

@htuch I am not planning on working on this at least for the next few months.

**Comment by htuch** [comment]
Ack, I'll leave this Help Wanted as it seems a reasonable ask.

**Comment by doujiang24** [comment]
I'm interested in this feature, and I have implemented a demo of custom TLS handshake extension, that can load/set certificates/keys by SNI server name, on-demand.

I think custom TLS handshake is very powerful.

I have an idea, (like @htuch said here: https://github.com/envoyproxy/envoy/issues/16174#issuecomment-828865092)
that we can make TLS certificate selector more flexible, **without** a custom handshake extension.

Here is my thoughts, any feedbacks welcome, Thanks :)

### Solution:
introduce an optional `matched_domains` fields in `tls_certificates`(also `tls_certificate_sds_secret_configs`).
it can be omitted, use the domains in certificate by default.

This is a demo.
```
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: certs/cert-1.pem
              private_key:
                filename: certs/key-1.pem
              matched_domains:
                ["foo.com", "api.foo.com"]
            - certificate_chain:
                filename: certs/cert-2.pem
              private_key:
                filename: certs/key-2.pem
              matched_domains:
                ["*.foo.com"]
```

This means: `foo.com` and `api.foo.com` will use cert-1, `bar.foo.com` and `blah.foo.com` ... will use cert-2.

### TODO
To reach it we need to improve `ServerContextImpl::selectTlsContext`, select certificate by the SNI server name.

### Result:
We can avoid repeated associated configuration, with this feature.

### Question
But, we can not avoid regenerating configuration (for LDS), when a domain name gets added.

Maybe, we can improve the SDS service?
when a domain have no matched certificate, Envoy will query `SDS` with the domain(not a knowned name),
then, SDS will return the certificate with a name(or not existing),
then, Envoy cache the certificate and refresh it by the name.

Also, we may support ACME after this change? related issue:
https://github.com/envoyproxy/envoy/issues/8372
https://github.com/envoyproxy/envoy/issues/96

Any suggestions? Thanks
