### ISSUE TITLE
Envoy resets http2 stream after downstream response has started

### ISSUE THREAD

**Issue by parkedwards** [envoyproxy/envoy#16219]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Upstream stream reset during gRPC forwarding, causing client failures

*Description*:
>Describe the issue.

We're currently in the process of migrating our sidecars from Envoy 1.10 -> 1.17; we're also introducing an Amazon ALB as the sole upstream to our sidecars, [which forward to gRPC targets](https://aws.amazon.com/about-aws/whats-new/2020/10/application-load-balancers-enable-grpc-workloads-end-to-end-http-2-support/).  This ALB listens on 443, so our sidecars forward gRPC with TLS to this ALB.  The gRPC client is a containerized Node service, uses `grpc-js`, and has been operational for a few years now.

After migration (so grpc client service -> Envoy sidecar (1.17) -> AWS ALB -> target), we're noticing the following client failure under load, at around a 2% clip (but increases as more request connections are made):

```
RST_STREAM with code 0
```

After further investigation, we're seeing a 1:1 correlation between the above failure (timestamp + count) with the following Envoy debug log group:

```
[2021-04-29 02:37:45.669][43][debug][router] [source/common/router/router.cc:1026] [C44][S4956500439520369696] upstream reset: reset reason: remote reset, transport failure reason: 
[2021-04-29 02:37:45.669][43][debug][http] [source/common/http/filter_manager.cc:828] [C44][S4956500439520369696] Resetting stream due to upstream_reset_after_response_started{remote reset}. Prior headers have already been sent
[2021-04-29 02:37:45.669][43][debug][http] [source/common/http/conn_manager_impl.cc:189] [C44][S4956500439520369696] doEndStream() resetting stream
[2021-04-29 02:37:45.669][43][debug][http] [source/common/http/conn_manager_impl.cc:1533] [C44][S4956500439520369696] stream reset
[2021-04-29 02:37:45.669][43][debug][http2] [source/common/http/http2/codec_impl.cc:873] [C44] sent reset code=0
[2021-04-29 02:37:45.669][43][debug][http2] [source/common/http/http2/codec_impl.cc:964] [C44] stream closed: 0
```

The relevant log item here appears to be this statement:

```
Resetting stream due to upstream_reset_after_response_started{remote reset}. Prior headers have already been sent
```

Based on [this comment](https://github.com/envoyproxy/envoy/blob/main/include/envoy/stream_info/stream_info.h#L163-L167) in the Envoy project, I'm interpreting this as the upstream resetting the stream (eg "remote reset") prior to the response fully being transmitted back down.  

My questions are:
1. Is this the correct interpretation of this behavior?  If not, what is going on here?
2. Are there any specific cluster/route configurations I can apply to mitigate this?  I'm a relative gRPC novice, but I've been toying with some cluster timeouts and max_stream_duration configurations, but with no avail.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Envoy configuration below, showing the egress listener + upstream cluster only:

```
# egress listener -> HTTP Connection Manager -> ALB upstream cluster
static_resources:
    listeners:
        - name: egress_http
          traffic_direction: OUTBOUND
          address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 11000
          filter_chains:
              - filters:
                    - name: envoy.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          codec_type: auto
                          stat_prefix: egress_http
                          normalize_path: true
                          route_config:
                              name: routing_config_to_internal_routing_service
                              virtual_hosts:
                                  - name: internal_routing_service
                                    domains: ["*"]
                                    routes:
                                        - match:
                                              prefix: "/"
                                          route:
                                              cluster: internal-routing-service-secure
                                              timeout: 90s
                                              max_stream_duration:
                                                  max_stream_duration: 0s
                                              retry_policy:
                                                  retry_on: connect-failure,refused-stream,gateway-error,deadline-exceeded,unavailable
                                                  num_retries: 2

    # ALB cluster (called "internal-routing-service-secure")
    clusters:
        - name: internal-routing-service-secure
          connect_timeout: 5s
          upstream_connection_options:
            tcp_keepalive:
                keepalive_time: 100
          circuit_breakers:
            thresholds:
                - max_connections: 10000
                  max_pending_requests: 10000
                  max_requests: 10000
                  max_retries: 5000
          type: strict_dns
          lb_policy: round_robin
          typed_extension_protocol_options:
              envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                  "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                  explicit_http_config:
                      http2_protocol_options: {}
          # 'transport_socket' ensures that the request is forwarded as HTTPS
          transport_socket:
              name: envoy.transport_sockets.tap
              typed_config:
                  "@type": type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
                  common_config:
                    static_config:
                        match_config:
                            any_match: true
                        output_config:
                            sinks:
                                - format: PROTO_BINARY
                                  file_per_tap:
                                    path_prefix: /etc/envoy
                  transport_socket:
                      name: envoy.transport_sockets.tls
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          load_assignment:
              cluster_name: internal-routing-service-secure
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: {{ print $internal_routing_host }}
                                      port_value: 443
```

POSSIBLE related Envoy issue:
#11931
#11369

**Comment by yanavlasov** [comment]
From the logs it looks like reset was initiated by the ALB. Do you have any diagnostics from the ALB?
Also you may get better luck asking this the envoy-users slack channel.

**Comment by parkedwards** [comment]
hey @yanavlasov - I've posted this question in the slack channel as well, thanks for that.

> Do you have any diagnostics from the ALB

I passed a packet capture log (PCAP) to Amazon support after reproducing, I'm waiting to hear back from them.  However, I'm wondering if there are any general Envoy-related guidance on managing this type of upstream behavior

**Comment by yanavlasov** [comment]
Retries

**Comment by parkedwards** [comment]
thanks @yanavlasov - based on what I provided in terms of the logs, do you have a reco on which of these error states I should retry on?  

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on

**Comment by parkedwards** [comment]
also, FWIW - i do have this retry_on policy set on the route configuration

```
                                              retry_policy:
                                                  retry_on: connect-failure,refused-stream,gateway-error,deadline-exceeded,unavailable
                                                  num_retries: 2
```

....that said, I don't see the `x-envoy-retry-on` OR `x-envoy-retry-grpc-on` headers in the debug logs.....I only seem to get something like this:

```
':status', '200'
'date', 'Wed, 05 May 2021 22:55:06 GMT'
'content-type', 'application/grpc'
'accept-encoding', 'identity,gzip'
'grpc-accept-encoding', 'identity,deflate,gzip'
'server', 'envoy'
'x-envoy-upstream-service-time', '208'

[2021-05-05 22:55:06.182][41][debug][http] [source/common/http/conn_manager_impl.cc:1500] [C1][S15404213778297715938] encoding trailers via codec:
'grpc-message', 'OK'
'grpc-status', '0'
```

**Comment by yanavlasov** [comment]
I think you should add `reset` in your retry policy, since this is the error you are getting.

**Comment by parkedwards** [comment]
thanks @yanavlasov - i'm adding both `internal,reset` to the policy to account for this, and will report back

additionally, i saw the `host_selection_retry_max_attempts` in the docs; this is supposed to limit retrying on the same host if it is bad.  but in the case of my example (single upstream is an AWS ALB), does this do what I think it does? or is it a noop

```
retry_on: connect-failure,refused-stream,gateway-error,deadline-exceeded,unavailable,internal,reset
    num_retries: 3
    host_selection_retry_max_attempts: 3
    retry_host_predicate:
        - name: envoy.retry_host_predicates.previous_hosts
```
