### ISSUE TITLE
Help setting up https for XDS cluster

### ISSUE THREAD

**Issue by lukos** [envoyproxy/envoy#16233]
*Cannot make CDS over https work*: *upstream connect error or disconnect/reset before headers*

*Description*:
I am trying to setup Envoy as an edge proxy with control-plane data coming from a custom web service written in .Net. The web service is callable from a test client and logs the request as http2 over TLS so I know this is working correctly. However, when I try and point Envoy at this web service for CDS configuration, it cannot load it, I just see a lot of logs of:

`opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] StreamClusters gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination`

I am running envoy, the web service and a sample web application through Docker compose. I can access the web app directly via its exposed port and envoy is running due to a test stub that returns a message directly.

It is likely to be something simple but there are various parts of the documentation, which I might have not understood correctly so I can't break it down into any smaller tests. For example:

- If I exec into the proxy container, I can curl the endpoint I have specified in the xds cluster and the only error I seem to get is that the certificate could not be validated, which is not necessarily surprising since it is an Alpine based image and might well not have the correct root certs installed.
- But, the docs say that Envoy doesn't validate upstream certs by default, so is this a problem?
- I understand that we should always use TLS over HTTP2 and that grpc should always use HTTP2 so that is the only configuration I have enabled on the control plane, and this is verified by calling it from the test client. Cert verifies OK in this scenario because I am calling it from my desktop machine.
- The error message seems to be caused by any number of issues with ssl, but I am unsure how to debug this to determine what I have not done correctly.
- There are various other details around what exactly envoy will handshake with depending on the presence of things like transport_socket, but it is unclear exactly what all of these mean, especially since none of the samples seem to have anything more than I have below.

[optional *Relevant Links*:]
Relevant section of envoy.yml

```yaml
dynamic_resources:
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster

static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 15s
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: containers_webservice_1
                port_value: 443
```

I am happy to write some of this up for the docs once it works, if that is helpful (and I haven't managed to find something that already describes this more clearly!)
