### ISSUE TITLE
HTTP/1.1 CONNECT with Envoy 1.17 and Istio 1.9.0

### ISSUE THREAD

**Issue by luboszk** [envoyproxy/envoy#16318]
*Title*: *HTTP/1.1 CONNECT configuration with Istio*

*Description*:
> I'm using Istio 1.9.0 with Envoy 1.17 (298ff36b2d43794816f7d8cdc5461bf6eed71bba) and I'm trying to configure access via the PROXY CONNECT to the other system.

*Repro steps*:
> curl https://echo.apps.verygood.systems/post -k \
  -x USiyQvWcT7wcpy8gvFb1GVmz:2b48a642-615a-4b3c-8db5-e02a88147174@tntsfeqzp4a.sandbox.verygoodproxy.com:8080 \
  -H "Content-type: application/json" \
  -d '{"account_number": "tok_sandbox_w8CBfH8vyYL2xWSmMWe3Ds"}'

*Config*:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: vgs-connect-proxy
  namespace: default
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          portNumber: 8080
          vhost:
            name: allow_any
      patch:
        operation: INSERT_FIRST
        value:
          match:
            connect_matcher: {}
          name: proxy-connect
          route:
            cluster: outbound|8080||tntsfeqzp4a.sandbox.verygoodproxy.com
            upgrade_configs:
              - connect_config: {}
                upgrade_type: CONNECT
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          name: envoy.filters.network.http_connection_manager
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            upgrade_configs:
              - enabled: true
                upgrade_type: CONNECT
---
kind: ServiceEntry
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: vgs
  namespace: default
spec:
  exportTo:
  - "."
  hosts:
  - tntsfeqzp4a.sandbox.verygoodproxy.com
  resolution: DNS
  location: MESH_EXTERNAL
  ports:
    - name: tcp
      number: 8080
      protocol: TCP
  addresses:
  - 3.215.204.48
  - 3.215.240.222
  - 107.20.75.87
```

*Issue*:
> To be able to establish successfully that HTTP CONNECT TCP Tunnel I have to configure the `addresses` section. Without that, I'm always getting that `server gave HTTP response to the HTTPS request`. As you may assume it's cumbersome and error-prone to have that list of IPs configured manually.
I'm looking for help with debugging why not having that `addresses` section breaks functionality. Is that something on the Envoy side we're missing, maybe Istio does something incorrectly, or maybe it's just me. I would like to get to the bottom of that problem as it prevents me from fully migrating my companies workloads into Istio and thus it prevents me from utilizing all of the nice features from Envoy.

*Solution worth considering*:
> As that connection is a TCP tunnel that encapsulates an HTTPS connection it prevents me from configuring things like retry, or load balancing. Maybe instead of leaving that up to the application to establish that tunnel, it would be worth configuring that on the Envoy side and by doing that still have that traffic marked and processed as HTTPS. Do you think it's something possible to achieve? Also, worth noticing is that only some requests to that server are being proxied.

I will create an issue on the Istio side as well to better manage the scope of work between the projects.
