### ISSUE TITLE
Administration endpoint not available

### ISSUE THREAD

**Issue by vdvarlamov** [envoyproxy/envoy#16381]
https://blog.envoyproxy.io/envoy-proxy-on-windows-containers-193dffa13050
I looked at the example and wanted to repeat it, but I ran into the following problem:
I run container:` docker run --publish 3000:8000 --publish 3001:10000 --detach --name bb1 test:service1`
Checking endpoints from the host:
```
curl "http:\\localhost:3000" -UseBasicParsing
StatusCode        : 200
StatusDescription : OK
```
but:
```
curl "http:\\localhost:3001" -UseBasicParsing
curl : Unable to connect to the remote server
```
At the same time, everything is available from the container.
In envoy-service-config.yaml:
```
admin:
  access_log_path: "./logs/logs.txt"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
```
docker inspect:
```
"PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3000"
                    }
                ],
                "10000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3001"
                    }
                ]
            },
```
The same result is obtained when accessing through the container's ip.
```
curl "http://172.30.206.18:8000/" -UseBasicParsing
StatusCode        : 200
StatusDescription : OK
curl "http://172.30.206.18:10000/" -UseBasicParsing
curl : Unable to connect to the remote server
```
In container:
```
0.0.0.0  10000  0.0.0.0  0  Listen
0.0.0.0  8000  0.0.0.0  0  Listen
```
Windows Server 2019
Docker version 20.10.4
@davinci26

**Comment by vdvarlamov** [comment]
- `envoy.exe  version: version: a5020ce885592e8e3a5d9bb644554a30c0f79a18/1.19.0-dev/Modified/RELEASE/BoringSSL`
- Microsoft Windows Server 2019 Standard 10.0.17763 N/A Build 17763
- envoy-service-config.yaml:

```
static_resources:
    listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8000
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: auto
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: service
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: local_service
            http_filters:
            - name: envoy.filters.http.router
              typed_config: {}
    clusters:
    - name: local_service
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: local_service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 8080
admin:
  access_log_path: "./logs/logs.txt"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
```
