### ISSUE TITLE
envoy code status 413

### ISSUE THREAD

**Issue by baoervsdier** [envoyproxy/envoy#16395]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

The version of istio we installed is 1.7.4. One of the services returned a status code of 413. I understand that it should be to modify a parameter similar to per_connection_buffer_limit_bytes. I looked for the relevant configuration on the Internet, but after the test, it was found to have no effect. The status code is still 413, and the configuration is as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: connection-control
  namespace: uat  ## test env
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        connect_timeout: 5s
        per_connection_buffer_limit_bytes: 10485760  ## 10M
  - applyTo: LISTENER
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        connect_timeout: 5s
        per_connection_buffer_limit_bytes: 10485760  ## 10M
  - applyTo: NETWORK_FILTER
    match:      
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 3600s # 1 hour
            headers_with_underscores_action: REJECT_REQUEST
          stream_idle_timeout: 300s # 5 mins, must be disabled for long-lived and streaming requests
          request_timeout: 300s # 5 mins, must be disabled for long-lived and streaming requests       
```
kiali screenshot:
![image](https://user-images.githubusercontent.com/32762305/117533603-4e0f4e00-b020-11eb-9132-9286bcfe35e2.png)

envoy debug log:
![image](https://user-images.githubusercontent.com/32762305/117533624-5d8e9700-b020-11eb-9cc9-fbc2b5aaa765.png)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
