### ISSUE TITLE
Zipkin Endpoint tracing not working with Jaeger / ok with Zipkin

### ISSUE THREAD

**Issue by darox** [envoyproxy/envoy#16401]
Zipkin Endpoint tracing not working with Jaeger / ok with Zipkin

I have configured my Envoy  setup (v1.18.2 ) with tracing:
```
- name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: true
          tracing:
            provider:
              name: envoy.tracers.zipkin
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                collector_cluster: jaeger
                collector_endpoint: "/api/v2/spans"
                collector_endpoint_version: HTTP_JSON

```

It works fine with Zipkin as endpoint, but not with the Zipkin compatible Endpoint in Jaeger. It seems Envoy isn't exporting any traces to Jaeger. 

I have tested with latest https://hub.docker.com/r/jaegertracing/all-in-one and https://hub.docker.com/r/openzipkin/zipkin
