### ISSUE TITLE
Get empty tls session id with %DOWNSTREAM_TLS_SESSION_ID%

### ISSUE THREAD

**Issue by arikachen** [envoyproxy/envoy#16428]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Get empty tls session id with %DOWNSTREAM_TLS_SESSION_ID%

*Description*:
I'm trying to add tls session id to http headers, but get nothing. Does i miss some config?
I'm using the envoy config from [tls example](https://raw.githubusercontent.com/envoyproxy/envoy/main/examples/tls/envoy-https-http.yaml)
```
  route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                request_headers_to_add:
                  - header:
                      key: "tls-session-id"
                      value: "%DOWNSTREAM_TLS_SESSION_ID%"
```

*Repro steps*:
1. run envoy with debug info
```
./envoy-proxy-static -c envoy.yaml --log-level debug --concurrency 2
```
2. curl -k https://127.0.0.1:10000
3. no tls-sesion-id in header
```
[2021-05-11 08:12:14.104][51209][debug][router] [external/envoy/source/common/router/router.cc:582] [C0][S17837504248343869087] router decoding headers:
':authority', '127.0.0.1:10000'
':path', '/'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.76.1'
'accept', '*/*'
'x-forwarded-proto', 'https'
'x-request-id', '0dde8533-a681-46c0-8396-96db0272bfd1'
'x-envoy-expected-rq-timeout-ms', '15000'
```

*Call Stack*:
![image](https://user-images.githubusercontent.com/2990337/117782056-db96ac00-b273-11eb-9813-7137a70be65e.png)
