### ISSUE TITLE
TCP health check failure misreporting endpoint as healthy with reuse_connection: true

### ISSUE THREAD

**Issue by bdecoste** [envoyproxy/envoy#16433]
Title: TCP health check failure misreporting endpoint as healthy with reuse_connection: true

Description:
I have a tcp service that only responds to a new connection. Any subsequent request data sent over the same connection will fail. I have a tcp healthcheck w/**reuse_connection=false** and envoy behaves correctly and as expected. However, if I have **reuse_connection=true** then the initial HC passes and subsequent HCs are reported in the HC log as failures as expected. However, the endpoint remains marked as healthy and traffic continues to flow. 

There is a inconsistency between the HCs being reported as failed in the HC logs and the healthy status of the endpoint and the resulting traffic flow. 

`{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"172.31.34.75","resolver_name":"","ipv4_compat":false,"port_value":1234}},"cluster_name":"tcp_default_svc_1234","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"timestamp":"2021-05-11T15:25:04.938Z"}`

```
tcp_default_svc_1234::default_priority::max_connections::1024
tcp_default_svc_1234::default_priority::max_pending_requests::1024
tcp_default_svc_1234::default_priority::max_requests::1024
tcp_default_svc_1234::default_priority::max_retries::3
tcp_default_svc_1234::high_priority::max_connections::1024
tcp_default_svc_1234::high_priority::max_pending_requests::1024
tcp_default_svc_1234::high_priority::max_requests::1024
tcp_default_svc_1234::high_priority::max_retries::3
tcp_default_svc_1234::added_via_api::true
tcp_default_svc_1234::172.31.34.75:1234::cx_active::0
tcp_default_svc_1234::172.31.34.75:1234::cx_connect_fail::0
tcp_default_svc_1234::172.31.34.75:1234::cx_total::0
tcp_default_svc_1234::172.31.34.75:1234::rq_active::0
tcp_default_svc_1234::172.31.34.75:1234::rq_error::0
tcp_default_svc_1234::172.31.34.75:1234::rq_success::0
tcp_default_svc_1234::172.31.34.75:1234::rq_timeout::0
tcp_default_svc_1234::172.31.34.75:1234::rq_total::0
tcp_default_svc_1234::172.31.34.75:1234::hostname::
tcp_default_svc_1234::172.31.34.75:1234::health_flags::healthy
tcp_default_svc_1234::172.31.34.75:1234::weight::1
tcp_default_svc_1234::172.31.34.75:1234::region::
tcp_default_svc_1234::172.31.34.75:1234::zone::k8s-1
tcp_default_svc_1234::172.31.34.75:1234::sub_zone::
tcp_default_svc_1234::172.31.34.75:1234::canary::false
tcp_default_svc_1234::172.31.34.75:1234::priority::0
tcp_default_svc_1234::172.31.34.75:1234::success_rate::-1.0
tcp_default_svc_1234::172.31.34.75:1234::local_origin_success_rate::-1.0
```

Repro steps:
```
          health_checks:
            - timeout: 5s
              interval: 5s
              unhealthy_threshold: 1
              healthy_threshold: 1
              reuse_connection: false
              tcp_health_check:
                send:
                  text: 666F6F
                receive:
                  - text: 666F6F
              no_traffic_interval: 60s
              event_log_path: /dev/stdout
              always_log_health_check_failures: true
          common_lb_config:
            healthy_panic_threshold:
              value: 0
```
