### ISSUE TITLE
bootstrap fields for user_agent overwritten internally

### ISSUE THREAD

**Issue by justincely** [envoyproxy/envoy#16471]
*Title*: `user_agent_name` and `user_agent_version` are overwritten if supplied via bootstrap configs. 

*Description*:
The [documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-node) for the bootstrap config indicates that these fields should be free-form strings.  I would expect to be able to override them if I chose, but they always revert back to the envoy build version.  Probably a niche group that would want to set these, but I do expect to be able to do so from the docs and the behavior of every other field i've encountered so far.  

I can get around this a bit by using the metadata field to provide my agent overrides, but seems like the docs should be updated or the behavior changed in order to avoid confusion.  

*Repro steps*:
1. run envoy with a bootstrap config that specifies `node.user_agent_name` and `node.user_agent_version`. 
2. get the config dump from the admin endpoint and verify the output `node` information has been changed.
 
e.g. a bootstrap node of
```
node:
  id: "test"
  cluster: "test-cluster"
  user_agent_name: "test-justin-agent"
  user_agent_version: "33"
```

gives the following from the config dump

```yaml
{
  "id": "test",
  "cluster": "test-cluster",
  "hidden_envoy_deprecated_build_version": "93753017cb8c64ba92536b755ddf756df377c6c3/1.19.0-dev/Clean/RELEASE/BoringSSL",
  "user_agent_name": "envoy",
  "user_agent_build_version": {
    "version": {
      "major_number": 1,
      "minor_number": 19
    },
```

*Config*:
```
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: STRICT_DNS # static
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: web_service
                port_value: 80

node:
  id: "test"
  cluster: "test-cluster"
  user_agent_name: "test-justin-agent"
  user_agent_version: "33"

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
