### ISSUE TITLE
rbac has no effect

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#16472]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
apply the following config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: apply-to
spec:
  workloadSelector:
    labels:
      app: mysqldb
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: 10.68.125.253_3306
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.mysql_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
          stat_prefix: mysql
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: 10.68.125.253_3306
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.network.rbac
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          stat_prefix: rbac
          rules:
             action: DENY
             policies:
               "product-viewer":
                 permissions:
                 - metadata:
                     filter: envoy.filters.network.mysql_proxy
                     path:
                     - key: t1.test
                     value:
                       string_match:
                         prefix: update
                 principals:
                 - any: true
```
connect to mysql.create table t1 in test database,then insert a record.and update the record.
it should deny when update.but has no effect.
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
