### ISSUE TITLE
Using (RBAC) Network Filter with TCP is not working

### ISSUE THREAD

**Issue by thuongnn** [envoyproxy/envoy#16512]
*Title*: *I want to use RBAC network filter with TCP network to deny source IP from client request*

*Description*:
> I have configured RBAC network filter with TCP network to deny source IP (222.252.22.138) but it doesn't work.

Below is my envoy config:
```yaml
resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_0
    reuse_port: true
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 3540
    filter_chains:
      filters:
        - name: envoy.filters.network.rbac
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
            stat_prefix: rbac
            rules:
              action: DENY
              policies:
                "chan_ip_rac":
                  permissions:
                    - any: true
                  principals:
                    - source_ip:
                        address_prefix: 222.252.22.138
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: service
            cluster: echo_tcp_server
```
