### ISSUE TITLE
Double proxy, how to maintain destination port?

### ISSUE THREAD

**Issue by ajsalow** [envoyproxy/envoy#16551]
*Title*: *Double proxy, how to maintain destination port?*

*Description*:
I have one envoy proxy running as a sidecar in a pod. I've used mangled the iptables (`iptables --table nat --append OUTPUT --prot tcp -m owner ! --uid-owner 101 -j DNAT --to-destination 127.0.0.1:10000`) so all output goes to the sidecar proxy.  

The enovy proxy running as a sidecar then forwards all traffic to another envoy proxy in my k8s cluster.
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: dl-proxy_tcp
          cluster: dl-proxy
  clusters:
  - name: dl-proxy
    connect_timeout: 2.0s
    type: STRICT_DNS # static
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: dl-proxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: proxy-dl-api-gateway.cdl-proxy
                port_value: 80
```

When the traffic gets to the second envoy proxy it needs send the traffic to the appropriate services in my cluster. This is easy for HTML services but for postgres it's a little harder. I'm trying to use a filter_chain_match to send any traffic that was originally destined to port 5432 to my postgres service, however, the destination port for all traffic coming form my first proxy is port 80

```json
 "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
            "name": "listener",
            "address": {
                "socket_address": {
                    "address": "0.0.0.0",
                    "port_value": 80
                }
            },
            "listener_filters": [
                {
                    "name": "envoy.filters.listener.original_dst",
                    "typed_config": {}
                }
            ],
            "filter_chains": [
                {
                    "filter_chain_match": {
                        "destination_port": 5432
                    },
                    "filters": [
                        {
                            "name": "envoy.filters.network.postgres_proxy",
                            "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy",
                                "stat_prefix": "egress_postgres"
                            }
                        },
                        {
                            "name": "envoy.filters.network.tcp_proxy",
                            "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                                "stat_prefix": "postgres_tcp",
                                "cluster": "postgres_cluster"
                            }
                        }
                    ]
                },
                {
                    "filters": [
                        {
                            "name": "envoy.filters.network.http_connection_manager",
                            "typed_config": {
                                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                                "stat_prefix": "ingress_http",
                                "codec_type": "AUTO",
                                "route_config": {
                                    "name": "test_route",
                                    "virtual_hosts": [
                                        {
                                            "name": "minio-svc:9000",
                                            "domains": [
                                                "minio-svc:9000",
                                                "minio-svc.svc:9000",
                                                "minio-svc.svc.cluster.local:9000"
                                            ],
                                            "routes": [
                                                {
                                                    "match": {
                                                        "prefix": "/"
                                                    },
                                                    "route": {
                                                        "cluster": "minio-svc:9000"
                                                    }
                                                }
                                            ]
                                        },


```

I realize I could probably fix this by having multiple listeners on both proxies but I would like the sidecar proxy to be as dumb as possible and just forward things to the second proxy where all the complex configuration will take place.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by lambdai** [comment]
> trying to use a filter_chain_match to send any traffic that was originally destined to port 5432 to my postgres service, however, the destination port for all traffic coming form my first proxy is port 80

Raw tcp doesn't preserve the info of "original dest".

You can use various tunnel including
1. http CONNECT: so that envoy recover the original dest from proxy-dl-api-gateway.cdl-proxy:80 
2. iptables REDIRECT at proxy-dl-api-gateway.cdl-proxy workload. Port 81 is preserved for postgres, Port 80 or other traffic. Both 81 and 80 redirect to another magic port (15006 in istio). Then you can set up an envoy listening on workload proxy-dl-api-gateway.cdl-proxy and at port 15006. That listener contains two filter chains: one filter chain matches dest port 80 and the other filter chain matches port 81

**Comment by ajsalow** [comment]
@lambdai Thanks for the response! Can you elaborate more on what you mean by http CONNECT and how I would implement that?

**Comment by lambdai** [comment]
> @lambdai Thanks for the response! Can you elaborate more on what you mean by http CONNECT and how I would implement that?

https://datatracker.ietf.org/doc/html/rfc7540#section-8.3

You client can encode the postgres traffic in a http/2 connect stream within the http2 connection to proxy-dl-api-gateway.cdl-proxy:80 and set the :authority as whatever you want. 
See my example here: https://github.com/lambdai/bts/blob/master/tcp2hbone.yaml

Your Envoy at proxy-dl-api-gateway.cdl-proxy:80 listen on port 80 and reroute the stream based on :authority and method. 
The example config here: https://github.com/lambdai/bts/blob/master/hbone2tcp.yaml#L81-L91

**Comment by ajsalow** [comment]
> > @lambdai Thanks for the response! Can you elaborate more on what you mean by http CONNECT and how I would implement that?
> 
> https://datatracker.ietf.org/doc/html/rfc7540#section-8.3
> 
> You client can encode the postgres traffic in a http/2 connect stream within the http2 connection to proxy-dl-api-gateway.cdl-proxy:80 and set the :authority as whatever you want.
> See my example here: https://github.com/lambdai/bts/blob/master/tcp2hbone.yaml
> 
> Your Envoy at proxy-dl-api-gateway.cdl-proxy:80 listen on port 80 and reroute the stream based on :authority and method.
> The example config here: https://github.com/lambdai/bts/blob/master/hbone2tcp.yaml#L81-L91

@lambdai Thanks again for the help.

I tried your suggestion, see below for the configuration I am using, but I am still having issues. When I run `psql -U postgres -h localhost -p 1999` I get an error 
```
psql: error: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Postgres_proxy output looks like it is reaching the destination port 
```
 transport socket match, socket default selected for host with address 127.0.0.1:10002
postgres_proxy_1  | [2021-06-01 22:16:42.499][1][debug][upstream] [source/common/upstream/strict_dns_cluster.cc:170] DNS refresh rate reset for 127.0.0.1, refresh rate 60000 ms
postgres_proxy_1  | [2021-06-01 22:16:42.499][1][debug][upstream] [source/common/upstream/upstream_impl.cc:278] transport socket match, socket default selected for host with address 172.18.0.2:5432
```
Note, if I run psql -U postgres -h localhost -p 10002 I can connect successfully. Any ideas why I cannot connect to postgres when using http tunneling?

docker-compose.yaml
```yaml
version: "3.7"
services:

  tunnel_proxy:
    build:
      context: .
      dockerfile: Dockerfile-tunnel
    networks:
      envoymesh:
    ports:
      - "1999:1999"
      - "8001:8001"
    command: "/usr/local/bin/envoy -c /etc/encapsulate_in_http1_connect.yaml -l debug"

  postgres_proxy:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    networks:
      envoymesh:
    ports:
      - "10001:10001"
      - "10002:10002"
    command: "/usr/local/bin/envoy -c /etc/envoy.yaml -l debug"

  postgres:
    image: postgres:latest
    networks:
      envoymesh:
    environment:
      # WARNING! Do not use it on production environments because this will
      #          allow anyone with access to the Postgres port to access your
      #          database without a password, even if POSTGRES_PASSWORD is set.
      #          See PostgreSQL documentation about "trust":
      #          https://www.postgresql.org/docs/current/auth-trust.html
      POSTGRES_HOST_AUTH_METHOD: trust

networks:
  envoymesh:
    name: envoymesh
```

Dockerfile-postgres
```dockerfile
FROM envoyproxy/envoy-dev:latest

COPY ./envoy.yaml /etc/envoy.yaml
RUN chmod go+r /etc/envoy.yaml
CMD ["/usr/local/bin/envoy", "-c /etc/envoy.yaml", "-l", "debug"]
```

Dockerfile-tunnel
```dockerfile
FROM envoyproxy/envoy-dev:latest

COPY ./encapsulate_in_http1_connect.yaml /etc/encapsulate_in_http1_connect.yaml
RUN chmod go+r /etc/encapsulate_in_http1_connect.yaml
CMD ["/usr/local/bin/envoy", "-c /etc/encapsulate_in_http1_connect.yaml", "-l", "debug"]

```
envoy.yaml
```yaml
static_resources:
  listeners:
  - name: tunnel_listener 
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10001
    listener_filters:
      - name: "envoy.listener.tls_inspector"
        typed_config: {}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config: 
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: localgw
          # common_http_protocol_options:
          #   max_stream_duration: 3600s
          http2_protocol_options: 
            allow_connect: true
          upgrade_configs: 
            upgrade_type: "CONNECT"
          #            connect_config: 
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend2
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: target
                    exact_match: "postgres"
                route:
                    cluster: "to_postgres"
                    upgrade_configs:
                      upgrade_type: "CONNECT"
                      connect_config:
                      enabled: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}

            
  - name: postgres_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
    - filters:
      - name: envoy.filters.network.postgres_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
          stat_prefix: egress_postgres
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: postgres_tcp
          cluster: postgres_cluster
    listenerFiltersTimeout: 0.100s
    continueOnListenerFiltersTimeout: true

  clusters:
  - name: to_postgres
    dns_refresh_rate: 60s
    connect_timeout: 10s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: to_postgres
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 10002
                protocol: TCP
  - name: postgres_cluster
    connect_timeout: 10s
    dns_refresh_rate: 60s
    type: STRICT_DNS
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: postgres
                port_value: 5432
                protocol: TCP

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
encapsulate_in_http1_connect.yaml
```yaml
# This configuration takes incoming data on port 10000 and encapsulates it in a CONNECT
# request which is sent upstream port 10001.
# It can be used to test TCP tunneling as described in docs/root/intro/arch_overview/http/upgrades.rst
# and running `curl --x 127.0.0.1:10000 https://www.google.com`

admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9903
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 1999
    filter_chains:
    - filters:
      - name: tcp
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_stats
          cluster: "cluster_0"
          tunneling_config:
            hostname: host.com:443
            headers_to_add:
            - header:
                key: target
                value: postgres
  clusters:
    - name: cluster_0
      dns_refresh_rate: 60s
      connect_timeout: 10s
      # This ensures HTTP/1.1 CONNECT is used for establishing the tunnel.
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            # http_protocol_options: {}
            http2_protocol_options: {}
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 10001
```

**Comment by ajsalow** [comment]
I figured it out. The cluster in  encapsulate_in_http1_connect.yaml needed to have be type `strict_dns` and point to `postgres_proxy` not localhost.

```
clusters:
    - name: cluster_0
      dns_refresh_rate: 60s
      connect_timeout: 10s
      type: strict_dns
      # This ensures HTTP/1.1 CONNECT is used for establishing the tunnel.
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            # http_protocol_options: {}
            http2_protocol_options: {}
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: postgres_proxy
                      port_value: 10001
```
The tunneling to postgres now works. Thanks for all the help!

**Comment by ajsalow** [comment]
@lambdai @alyssawilk so actually this only solved my issue for a simple configuration. The HTTP Connect requires I specify in my configs a hostname (and optionally a target) for routeing by the httpconnectionmanager.
```yaml
tunneling_config:
            hostname: host.com:443
            headers_to_add:
            - header:
                key: target
                value: postgres
```
I need to know the original ip or better yet hostname of the original request before iptables mangled it because I have many services that are dynamically discovered by the upstream and thus I can't statically write them into the downstream envoy configuration. This works fine for http traffic because if my application downstream sends a request to `remote_service:80`, the ip mangling sends the request to the enovy downstream proxy which sends it to the upstream proxy's httpconnectionmanger and I can use the authority to then route it to the final destination of `remote_service:80`. I would really like for the authority for the HTTP CONNECT for tcp traffic to be written like this so the httpconnectionmanager can route it like it would http requests. Is there any way I can do this? I have also tried using original destination cluster but that doesn't seem to work with DNAT and a double proxy.
