### ISSUE TITLE
Input matcher that checks that an IP belongs to a list of CIDR ranges

### ISSUE THREAD

**Issue by aguinet** [envoyproxy/envoy#16568]
*Title*: An input matcher that checks that an IP{v4,v6} belongs to a list of CIDR ranges

*Description*:
This input matcher takes an IPv4 or v6 address as input and returns true if it belongs to a list of given CIDR ranges. It uses the existing `LcTrie` facility.

The configuration is simple and looks like this:

```
cidr_ranges:
- address_prefix: "1.1.1.0"
  prefix_len: 24
- address_prefix: "2.2.0.0"
  prefix_len: 16
...
```

I have implemented it here: https://github.com/curiefense/envoy/commit/e4601bb61cf7f0896fdf3e8bfd1b9058efbd6785

If it can be sponsored, I will open the associated PR!

Thanks!
