### ISSUE TITLE
Jwks remote fetch is failed

### ISSUE THREAD

**Issue by maei** [envoyproxy/envoy#16572]
*Title*: Jwks remote fetch is failed from a keycloak server

*Description*:
I run envoy with docker-compose.
Locally the remote jwks fetch is working fine  and the same setup on a digitalocean droplet fine as well.

After I deployed the docker-compose and the envoy.yaml on an ubunutu machine behind a proxy I get the message "Jwks remote fetch is failed"

I  cannot figure out what the problem is....especially because I am able to curl the GET Endpoint for the jwks on the keycloak server from the envoy docker container. I also checked the network traffic and the call is made to the keycloak server.

Thanks to everyone for hints and tipps!!

All Docker proxy configurations are set like:
```
[Service]
Environment="HTTP_PROXY=http://XX.XX.XX.XX:XXXX"
Environment="HTTPS_PROXY=http://XX.XX.XX.XX:XXXX"
```

and the docker config.json
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://XX.XX.XX.XX:XXXX",
     "httpsProxy": "http://XX.XX.XX.XX:XXXX",
     "noProxy": "127.0.0.1, localhost, ::1"
   }
 }
}

```
front-envoy.yaml
```
static_resources:
  listeners:
  - name: http_listener 
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 4443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/api/test/data/"
                route:
                  cluster: testservice                           
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                jwt_endpoints:
                  issuer: https://auth.asoe_url.de:8080/auth/realms/ev
                  remote_jwks:
                    http_uri:
                      uri: https://auth.asoe_url.de:8080/auth/realms/etest/protocol/openid-connect/certs
                      cluster: keycloak
                      timeout: 2s
                    cache_duration:
                      seconds: 300                    
                  from_headers:
                  - name: Authorization
                    value_prefix: "Bearer "
                  forward_payload_header: x-jwt-payload                  
              rules:
              - match:
                  prefix: "/api/test/data/"
                requires:
                  provider_name: "jwt_endpoints"               
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
 
 - name: testservice
    connect_timeout: 2s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: testservice
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: testservice
                port_value: 8088

  - name: keycloak
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 2s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: auth.asoe_url.de
               port_value: 8080
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext


admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000

```

**Comment by qiwzhang** [comment]
It seems that all your remote http calls need to go through a http_proxy.  I am not sure how to config envoy to talk to a http_proxy.   

Maybe you can try to change the cluster address to the http_proxy address?  But I am not sure if it will work

```
 - name: keycloak
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 2s
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: auth.asoe_url.de  ==>  your_http_proxy ip address
               port_value: 8080

```
