### ISSUE TITLE
Envoy generates wrong proxy protocol header for upstreams

### ISSUE THREAD

**Issue by pezzak** [envoyproxy/envoy#16595]
*Description*: It contains ip address of envoy instance in the source address field instead of downstream ip. 

*Config*:

```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              format: "[%START_TIME%] %REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL% %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% %REQ(X-FORWARDED-FOR)% %REQ(USER-AGENT)% %REQ(X-REQUEST-ID)% %REQ(:AUTHORITY)% %UPSTREAM_HOST% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS%\n"
              path: /dev/stdout
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.219.131.132
                port_value: 10001
    transport_socket:
     name: envoy.transport_sockets.upstream_proxy_protocol
     typed_config:
       "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
       config:
         version: V1
       transport_socket:
         name: envoy.transport_sockets.raw_buffer
```

*Logs*:
[envoy_log.txt](https://github.com/envoyproxy/envoy/files/6515726/envoy_log.txt)

*Tcpdump cut*:
```
Internet Protocol Version 4, Src: 10.232.39.173, Dst: 10.219.131.132
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
    Total Length: 105
    Identification: 0x8b7c (35708)
    Flags: 0x4000, Don't fragment
    Fragment offset: 0
    Time to live: 57
    Protocol: TCP (6)
    Header checksum: 0xf51e [validation disabled]
    [Header checksum status: Unverified]
    Source: 10.232.39.173
    Destination: 10.219.131.132

PROXY Protocol
    PROXY v1 magic
    Protocol: TCP4
    Source Address: 10.232.39.173
    Destination Address: 10.219.131.132
    Source Port: 48734
    Destination Port: 10001
```

In case of use `envoy.filters.listener.proxy_protocol` on the listener - the same result.
