### ISSUE TITLE
unclear behavior of max_requests in cluster circuit breakers

### ISSUE THREAD

**Issue by argos83** [envoyproxy/envoy#16610]
*Title*: unclear behavior of max_requests in cluster circuit breakers

(Tested in envoy v1.17.3)

*Description*:

I'm not sure if this is a bug, or me misunderstanding the docs.

```
max_requests: (UInt32Value) The maximum number of parallel requests that Envoy will make to the upstream cluster. If not specified, the default is 1024.
```

Given protocol is HTTP/1.1 and this cluster circuit breaker config:

```
circuit_breakers:
  thresholds:
    - priority: "DEFAULT"
      max_connections: 0xffffffff
      max_requests: 3
      max_pending_requests: 1024
```

If I generate for example 6 long running parallel requests, E.g.:

```
hey -n 6 -c 6 "http://localhost:8080/response?sleep=3000"
```
I would expect all requests to succeed, Envoy sending 3 at a time while queuing the other 3. No overflows.

However the result I see is:

```
Status code distribution:
  [200] 3 responses
  [503] 3 responses
```

Relevant metrics:

```
cluster.service.circuit_breakers.default.cx_open: 0
cluster.service.circuit_breakers.default.cx_pool_open: 0
cluster.service.circuit_breakers.default.rq_open: 0
cluster.service.circuit_breakers.default.rq_pending_open: 0
cluster.service.circuit_breakers.default.rq_retry_open: 0
cluster.service.external.upstream_rq_200: 3
cluster.service.external.upstream_rq_2xx: 3
cluster.service.external.upstream_rq_503: 3
cluster.service.external.upstream_rq_5xx: 3
cluster.service.external.upstream_rq_completed: 6
cluster.service.upstream_cx_connect_fail: 0
cluster.service.upstream_cx_http1_total: 6
cluster.service.upstream_cx_http2_total: 0
cluster.service.upstream_cx_max_requests: 0
cluster.service.upstream_cx_overflow: 0
cluster.service.upstream_cx_pool_overflow: 0
cluster.service.upstream_cx_total: 6
cluster.service.upstream_rq_200: 3
cluster.service.upstream_rq_2xx: 3
cluster.service.upstream_rq_503: 3
cluster.service.upstream_rq_5xx: 3
cluster.service.upstream_rq_active: 0
cluster.service.upstream_rq_cancelled: 0
cluster.service.upstream_rq_completed: 6
cluster.service.upstream_rq_pending_overflow: 3
cluster.service.upstream_rq_pending_total: 6
cluster.service.upstream_rq_total: 3
```

So, you  can see from `upstream_rq_pending_overflow: 3` that the pending circuit breaker was hit, even if it's set to 1024.

Does the max_request limit account for both active and pending requests? That's not clear in the documentation. And I would prefer if it was only meant for active requests.

**Our use case**:

We allow our users to define maxActiveRequests and maxPendingRequests in their upstream dependencies declaration. When we implemented that some time ago, and came across the issue described above we decided to use instead the  `max_connections` limit and make max_requests unrestricted (since we only supported HTTP/1.1) ,  i.e.:

```
circuit_breakers:
  thresholds:
    - priority: "DEFAULT"
      max_connections: {{ maxActiveRequests}}
      max_requests: 0xffffffff
      max_pending_requests: {{ maxPendingRequests }}
```

That works as expected, for the example above, if max_connections is 3, then 3 requests are sent immediately while the other 3 will be queued.

However we are in a position now to transparently support HTTP/2, with ALPN (via the `auto_config` HttpProtocolOptions), so, we would like to change the settings to keep the same behavior despite the underlying negotiated protocol:

```
circuit_breakers:
  thresholds:
    - priority: "DEFAULT"
      max_connections: {{ maxActiveRequests}} // or unrestricted since max_request would be hit ideally
      max_requests: {{ maxActiveRequests}}
      max_pending_requests: {{ maxPendingRequests }}
```

I hope all this makes sense. Is it a bug? or am I missing something? How can you otherwise support having the same limit behavior for inflight and pending requests despite the HTTP version?

Thanks!!
