### ISSUE TITLE
Support Wasm Specific Route 

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#16651]
**Title**:  **Support Wasm filter Specific Route**

**Description**:

As lua filter does, filter can be used in specific route/Path by per route, but Wasm filter doesn`t make it,
Is there any plan of Wasm filter to support per route? Or is there any other plans to make wasm support specfic route?

**Comment by phlax** [comment]
cc @PiotrSikora

**Comment by PiotrSikora** [comment]
There are a few issues already open about this to be added as a generic Envoy feature (i.e. not Wasm specific):
- https://github.com/envoyproxy/envoy/issues/6824
- https://github.com/envoyproxy/envoy/issues/11690
- https://github.com/envoyproxy/envoy/issues/12968

**Comment by Xunzhuo** [comment]
@PiotrSikora Is this feature under developing? I can see these issues open by a year ago, when can envoy make this work? 🤭

**Comment by PiotrSikora** [comment]
Actually, it looks that @snowp added it a few weeks ago (#15198), but it's still an experimental feature behind a runtime flag.

**Comment by Xunzhuo** [comment]
@PiotrSikora Thanks a lot~

**Comment by Xunzhuo** [comment]
Two question about this filter:Can I use ECDS to dynamically send compose-filter`s config to Envoy, because I don`t want to use LDS~

**Comment by Xunzhuo** [comment]
Hi @snowp @PiotrSikora ,I have two more questions about this filter, looking forward to your reply:
1. Can I use ECDS to dynamically send compose-filter`s config to Envoy, because I don`t want to use LDS
2. Can I use compose-filter to bind specific route path to wasm filter? I see demo config`s matcher type is based on Headers, Can I change it to Path type?
Thanks a lot 😀😀~

**Comment by Xunzhuo** [comment]
``` yaml

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: httpbin
                  virtual_hosts:
                    - name: httpbin
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: httpbin
          http_filters:
          - name: composite
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
              extension_config:
                name: composite
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
              matcher:
                matcher_tree:
                  input:
                    name: request-headers
                    typed_config:
                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                      header_name: :path
                  exact_match_map:
                    map:
                      "/test": # inject 10s latency into all requests
                        action:
                          name: composite-action
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                            typed_config:
                              name: envoy.filters.http.wasm
                              typed_config:
                                "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                                type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                value:
                                  config:
                                    name: "my_plugin"
                                    root_id: "my_root_id"
                                    vm_config:
                                      vm_id: "my_vm_id"
                                      runtime: "envoy.wasm.runtime.v8"
                                      code:
                                        local:
                                          filename: "./resbody.wasm"
                                      allow_precompiled: true
                      "/wasm": # inject 1s latency into all requests
                        action:
                          name: composite-action
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                            typed_config:
                              name: envoy.filters.http.wasm
                              typed_config:
                                "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                                type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                value:
                                  config:
                                    name: "my_plugin"
                                    root_id: "my_root_id"
                                    vm_config:
                                      vm_id: "my_vm_id"
                                      runtime: "envoy.wasm.runtime.v8"
                                      code:
                                        local:
                                          filename: "./reqheader.wasm"
          - name: envoy.filters.http.router

  clusters:
    - name: httpbin
      connect_timeout: 5000s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 9001

layered_runtime:
  layers:
    - name: static-layer
      static_layer:
        envoy:
          reloadable_features:
            experimental_matching_api: true


```

I try to do this config, it seems not right  @snowp 

Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0]) http_filters: Cannot find field.) has unknown fields
