### ISSUE TITLE
Support XDS in Rate Limit Service to avoid request all traffic to RateLimit server

### ISSUE THREAD

**Issue by cocotyty** [envoyproxy/envoy#16668]
*Title*: *One line description*

Support XDS in Rate Limit Service to avoid request all traffic to RateLimit server.

*Description*:

Envoy can do a pre check before send a RateLimitRequest to server.
For example, here is a [RateLimit](https://github.com/envoyproxy/ratelimit) configuration:

```yaml
domain: messaging
descriptors:
  # Only allow 5 marketing messages a day
  - key: message_type
    value: marketing
    descriptors:
      - key: to_number
        rate_limit:
          unit: day
          requests_per_unit: 5

  # Only allow 100 messages a day to any unique phone number
  - key: to_number
    rate_limit:
      unit: day
      requests_per_unit: 100
```
Envoy subscribes the configuration by domain , and RateLimit server can push configuration changed events to Envoy.

Envoy checks the descriptors and decide whether it needs to send the RateLimitRequest to server.

[optional *Relevant Links*:] 
>Any extra documentation required to understand the issue.
