### ISSUE TITLE
Dynamic configuration from FileSystem: envoy keeps only the last configuration item (listener in lds.yaml and cluster in cds.yaml) 

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#16697]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

Title: Dynamic configuration from FileSystem: envoy keeps only the last configuration item (listener in lds.yaml and cluster in cds.yaml) 

Description:

Reading the dynamic configuration for envoy from FileSystem, the configuration is loaded correctly from lds.yaml and cds.yaml but one issue is noticed in case we are configuring more listeners and clusters respectively in the file lds.yaml and cds.yaml.

e.g:
```
node:
  cluster: test
  id: id_1
dynamic_resources:
  lds_config:
    path: /etc/envoy/lds.yaml
  cds_config:
    path: /etc/envoy/cds.yaml
```

dynamic LDS file (lds.yaml) content:

lds.yaml:
```
----
version_info: '0'
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_local_proxy__remote_service
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6666
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: remote-service
        stat_prefix: tcp_remote_service
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        require_client_certificate: true
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /certs/sip_tls_ca/tls.crt
          tls_certificates:
          - certificate_chain:
              filename: /certs/sip_tls_certs/tls.crt
            private_key:
              filename: /certs/sip_tls_certs/tls.key

  name: listener_int_to_proxy
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8888
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: proxy_to_proxy
        #proxy_to_proxy
        stat_prefix: tcp_int_to_proxy
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        require_client_certificate: true
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /certs/sip_tls_ca/tls.crt
          tls_certificates:
          - certificate_chain:
              filename: /certs/sip_tls_certs/tls.crt
            private_key:
              filename: /certs/sip_tls_certs/tls.key  
```

In this case it's only done the configuration of last listener entity defined in the lds.yaml: listener_int_to_proxy.

The same behaviour is noticed for clusters defined in cds.yaml file.

What is the expected behaviour from envoy in such case? 

Can we handle more listeners and clusters in dynamic resources from FileSystem (lds.yaml, cds.yaml)?

I would like better to understand it, thanks.

**Comment by phlax** [comment]
@eoregua can you surround code with ` ``` `

i have updated the comment above - but im not sure if i have placed them in the correct places

**Comment by eoregua** [comment]
ok, done! Thanks.

**Comment by phlax** [comment]
@eoregua - i think it is because you need to specify the second listener as a separate resource

i loaded a simplified version of your config via `lds.yaml` - specifying each listener as a separate resource:

```yaml
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_local_proxy__remote_service
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6666
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: remote-service
        stat_prefix: tcp_remote_service

- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_int_to_proxy
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8888
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: proxy_to_proxy
        #proxy_to_proxy                                                                                                                                                             
        stat_prefix: tcp_int_to_proxy
```

and then used config_dump to find out what listeners were registered:

```console
$ curl -s http://localhost:19000/config_dump | jq -r ".configs[2]"
```

```json
{
  "@type": "type.googleapis.com/envoy.admin.v3.ListenersConfigDump",
  "dynamic_listeners": [
    {
      "name": "listener_local_proxy__remote_service",
      "active_state": {
        "listener": {
          "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
          "name": "listener_local_proxy__remote_service",
          "address": {
            "socket_address": {
              "address": "0.0.0.0",
              "port_value": 6666
            }
          },
          "filter_chains": [
            {
              "filters": [
                {
                  "name": "envoy.filters.network.tcp_proxy",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                    "stat_prefix": "tcp_remote_service",
                    "cluster": "remote-service"
                  }
                }
              ]
            }
          ]
        },
        "last_updated": "2021-05-27T12:35:17.756Z"
      }
    },
    {
      "name": "listener_int_to_proxy",
      "active_state": {
        "listener": {
          "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
          "name": "listener_int_to_proxy",
          "address": {
            "socket_address": {
              "address": "0.0.0.0",
              "port_value": 8888
            }
          },
          "filter_chains": [
            {
              "filters": [
                {
                  "name": "envoy.filters.network.tcp_proxy",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy",
                    "stat_prefix": "tcp_int_to_proxy",
                    "cluster": "proxy_to_proxy"
                  }
                }
              ]
            }
          ]
        },
        "last_updated": "2021-05-27T12:35:17.757Z"
      }
    }
  ]
}
```

and it works correctly
