### ISSUE TITLE
Filesystem config update rejected: Failed to load incomplete certificate 

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#16700]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

Title: Filesystem config update rejected: Failed to load incomplete certificate 

Description:

Helm Chart installing envoy with dynamic configuration from Filesystem->problem to load certificates from k8s secrets when k8s secrets are installed in the same Helm Chart of envoy POD.

The secret could be created with empty certificates first and then updated later. If envoy starts and finds empty certificates it fails to become ready:

e.g: `[2021-05-27 14:00:30.860][1][warning][config] [source/common/config/filesystem_subscription_impl.cc:43] Filesystem config update rejected: Failed to load incomplete certificate from , `

If the k8s secrets are created before to install the Helm Chart everything works fine.

lds.yaml:

```
version_info: '0'
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener1
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6666
  filter_chains:
  - filters:
    - name: envoy.filters.network.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        cluster: remote-service
        stat_prefix: tcp_remote_service
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        require_client_certificate: true
        common_tls_context:      
          tls_certificate_sds_secret_configs:
            name: tls_sds
            sds_config:
              path: /etc/envoy/tls_certificate_sds_secret.yaml
          validation_context_sds_secret_config:
            name: validation_context_sds
            sds_config: 
              path: /etc/envoy/validation_context_sds_secret.yaml              
```

tls_certificate_sds_secret.yaml:

```
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: tls_sds
    tls_certificate:
      certificate_chain:
        filename: /certs/sip_tls_certs/tls.crt
      private_key:
        filename: /certs/sip_tls_certs/tls.key
```
validation_context_sds_secret.yaml:

```
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds
    validation_context:
      trusted_ca:
        filename: /certs/sip_tls_ca/tls.crt  

```

The certificates are mounted in envoy POD as secrets. If secrets are created before of the installlation of Helm Chart where is deployed the envoy POD we don't have any issue with certificates loading. If secrets are created inside the same Helm Chart but we are using static configuration for envoy we don't have any issue. If secrets are created inside the same Helm Chart and envoy is creating dynamic resources from Filesystem we trigger the issue reported above.

Why do we have such behaviour? I would like better to understand it. Thanks!
