### ISSUE TITLE
Docker for Windows with Windows Containers, envoyproxy/envoy-windows host.docker.internal DNS does not resolve

### ISSUE THREAD

**Issue by netpoetica** [envoyproxy/envoy#16710]
*Description*:

I am running envoyproxy/envoy-windows, and then I am running my C++ gRPC server on my localhost (host) system on port 50051. If I run Linux container envoyproxy/envoy, everything works without issue, but when I change to Windows containers and use windows image, envoy cannot resolve host.docker.internal
```
envoy_1                   | [2021-05-27 17:32:08.312][1324][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:165] DNS refresh rate reset for host.docker.internal, (failure) refresh rate 5000 ms
```
My gRPC-web requests fail because the upstream cannot be resolved.

The dockerfile looks like:

```
#
# Create a Windows envoy proxy image for gRPC-Web proxying.
#
FROM envoyproxy/envoy-windows:v1.18-latest

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# envoy.yaml is default config file
COPY ./docker/windows/envoy/config.yaml "C:\\ProgramData\\envoy\\config.yaml"

ENTRYPOINT [ "envoy.exe", "-c", "C:\\ProgramData\\envoy\\config.yaml", "-l", "trace" ]
```
the config file looks like
```
admin:
  access_log_path: C:\Windows\Temp\admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ['*']
                      routes:
                        - match: { prefix: '/' }
                          route:
                            cluster: greeter_service
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: '*'
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: '1728000'
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: greeter_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 50051
```
and the docker-compose looks like:
```
  envoy:
    build:
      context: ./
      dockerfile: ./docker/windows/envoy/Dockerfile
    image: napa/envoy
    ports:
      # Expose Envoy admin panel.
      # See: http://localhost:9901/ (when container is running)
      - '9901:9901'
      # Expose endpoint for gRPC client APIcalls
      - '8080:8080
```

For Linux, the dockerfile looks like:
```
#
# Create an envoy proxy image for gRPC-Web proxying.
#

FROM envoyproxy/envoy:v1.18-latest

COPY ./docker/envoy/config.yaml /etc/envoy/config.yaml

CMD /usr/local/bin/envoy -c /etc/envoy/config.yaml -l trace --log-path /tmp/envoy_info.log
```
the config looks like
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ['*']
                      routes:
                        - match: { prefix: '/' }
                          route:
                            cluster: greeter_service
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: '*'
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: '1728000'
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: greeter_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal # 0.0.0.0
                      port_value: 50051

```
and the docker-compose looks like:
```
  envoy:
    # platform: linux
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    image: napa/envoy
    ports:
      # Expose Envoy admin panel.
      # See: http://localhost:9901/ (when container is running)
      - '9901:9901'
      # Expose endpoint for gRPC client APIcalls
      - '8080:8080
```

Everything is essentially the same. I have also created some basic example Python windows container w/ a Python SimpleHTTPServer and was able to communicate with it no issues, so I am concerned that there is some problem with the Envoy DNS resolution that is causing host.docker.internal not to be resolvable.

Docker Engine version 20.10.6, Compose version 1.29.1, Windows 10 Version 1909
