### ISSUE TITLE
Matching api to Compose Wasm filter failed

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#16716]
# Matching api to Compose Wasm filter failed

*Description*:
I try to use match api and compose filter to compose wasm filter, it runs ok but it seems like filter is not working;

I checked stats and it failed:

![image](https://user-images.githubusercontent.com/48784001/119956110-516c7880-bfd3-11eb-9dd7-992c293207e7.png)

Is Compose filter not supported to compose wasm filter or something else? 

config is here:

``` yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: httpbin
                  virtual_hosts:
                    - name: httpbin
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: httpbin
                http_filters:
                - name: composite
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
                    extension_config:
                      name: composite
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
                    matcher:
                      matcher_tree:
                        input:
                          name: request-headers
                          typed_config:
                            "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                            header_name: switch
                        exact_match_map:
                          map:
                            "test": 
                              action:
                                name: composite-action
                                typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                                  typed_config:
                                    name: envoy.filters.http.wasm
                                    typed_config:
                                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                      value:
                                        config:
                                          name: "my_plugin1"
                                          root_id: "my_root_id1"
                                          vm_config:
                                            vm_id: "my_vm_id1"
                                            runtime: "envoy.wasm.runtime.v8"
                                            code:
                                              local:
                                                filename: "./log.wasm"
                                            allow_precompiled: true
                            "wasm": 
                              action:
                                name: composite-action
                                typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                                  typed_config:
                                    name: envoy.filters.http.wasm
                                    typed_config:
                                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                      value:
                                        config:
                                          name: "param-exchange"
                                          root_id: "param-exchange"
                                          vm_config:
                                            runtime: "envoy.wasm.runtime.v8"
                                            code:
                                              local:
                                                filename: "./param-exchange.wasm"
                                            allow_precompiled: true
                                          configuration: 
                                              "@type": "type.googleapis.com/google.protobuf.StringValue"
                                              value: |
                                                {"update_param_list": [
                                                    {
                                                        "old_request": {
                                                            "location": "query_parameter", 
                                                            "key": "source1"
                                                        }, 
                                                        "new_request": {
                                                            "location": "query_parameter", 
                                                            "key": "replace1"
                                                        }
                                                    }, 
                                                    {
                                                        "old_request": {
                                                            "location": "query_parameter", 
                                                            "key": "source2"
                                                        }, 
                                                        "new_request": {
                                                            "location": "query_parameter", 
                                                            "key": "replace2"
                                                        }
                                                    }
                                                ], 
                                                "delete_param_list": [
                                                    {
                                                        "request": {
                                                            "location": "cookie", 
                                                            "key": "destination3"
                                                        }
                                                    }, 
                                                    {
                                                        "request": {
                                                            "location": "cookie", 
                                                            "key": "destination4"
                                                        }
                                                    }
                                                ], 
                                                "add_param_list": [
                                                    {
                                                        "request": {
                                                            "location": "header", 
                                                            "key": "add1"
                                                        }, 
                                                        "value": "true"
                                                    }, 
                                                    {
                                                        "request": {
                                                            "location": "header", 
                                                            "key": "add2"
                                                        }, 
                                                        "value": "true"
                                                    }, 
                                                    {
                                                        "request": {
                                                            "location": "header", 
                                                            "key": "add3"
                                                        }, 
                                                        "value": "true"
                                                    }
                                                ]}
                - name: envoy.filters.http.router

  clusters:
    - name: httpbin
      connect_timeout: 5000s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 9001

layered_runtime:
  layers:
    - name: static-layer
      static_layer:
        envoy:
          reloadable_features:
            experimental_matching_api: true

```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
