### ISSUE TITLE
Question: How do I get the complete gRPC request body when using envoy.filters.http.ext_authz?

### ISSUE THREAD

**Issue by juchaosong** [envoyproxy/envoy#16772]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *How do I get the complete gRPC request body when using envoy.filters.http.ext_authz*

*Description*:
> Here's my http_filters's configuration:
```yaml
http_filters: 
  - name: envoy.filters.http.ext_authz
    typed_config: 
      "@type" : type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      grpc_service: 
        envoy_grpc: 
          cluster_name: envoy-auth
        timeout: 0.25s
      transport_api_version: V3
      with_request_body: 
        max_request_bytes: 1024
        pack_as_bytes: true
  - name: envoy.filters.http.router
```
>And AuthorizationServer codes:
```go
func (a AuthorizationServer) Check(ctx context.Context, req *auth.CheckRequest) (*auth.CheckResponse, error) {
	log.Printf("rowBody[%v]", string(req.Attributes.Request.Http.RawBody))
        ...
}
```
> When I use `grpcurl -d '{"content":"hello, world"}' -proto echo-grpc/api/echo.proto -plaintext -v localhost:8080 api.Echo/Echo`, I expect `rowBody["content":"hello, world"]`. But I got `rowBody[
>
> hello, world]`.
> Why I cannot got the complete request body.

[optional *Relevant Links*:]
>The echo grpc server lay on [grpc-gke-nlb-tutorial](https://github.com/GoogleCloudPlatform/grpc-gke-nlb-tutorial/tree/master/echo-grpc).
>The extauth server lay on [envoy_ratelimit_example](https://github.com/Cluas/envoy_ratelimit_example/blob/master/extauth/main.go).
