### ISSUE TITLE
HTTP healthcheck doesn't affect routing choice on TCP proxy LB

### ISSUE THREAD

**Issue by dmitrytretyakov** [envoyproxy/envoy#16802]
*Description*:
I'm running envoy in docker.
I've configured a static configuration: tcp proxy with transport_socket_match_criteria option in health_check to use https healthcheck.
I have a 1 healthy of 3 endpoints (Vault services). So, traffic should be routed only to this endpoint.
Instead of this traffic is routed to all 3 endpoints.

*Config*:
>Include the config used to configure Envoy.
```
static_resources:
  listeners:
  - name: vault_listener
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: vault_unsealer
          cluster: vault_unsealer
  clusters:
  - name: vault_unsealer
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    transport_socket_matches:
    - name: "enableTLS"
      match:
        useTLS: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: /ca.pem
    health_checks:
    - timeout: 5s
      interval: 30s
      unhealthy_threshold: 3
      healthy_threshold: 2
      transport_socket_match_criteria:
        useTLS: true
      http_health_check:
        path: "/v1/sys/health"
    load_assignment:
      cluster_name: vault_unsealer
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.108.76.46
                port_value: 8200
        - endpoint:
            address:
              socket_address:
                address: 10.108.76.47
                port_value: 8200
        - endpoint:
            address:
              socket_address:
                address: 10.108.76.48
                port_value: 8200
```

So, I see that healthcheck works - 1 of 3 nodes is healthy (see this in trace logs, /stats, and in /clusters endpoint outputs).
But by some reasons traffic is routed to 3 nodes (who also has a failed hc)

Logs and /stats, /clusters and /server_info outputs: [debug-info.tar.gz](https://github.com/envoyproxy/envoy/files/6592741/debug-info.tar.gz)

Could pls assist? Is it my mistake in configuration or a bug?
