### ISSUE TITLE
regression: cluster stats missing when using healtcheck filter

### ISSUE THREAD

**Issue by sschepens** [envoyproxy/envoy#16817]
When using the healthcheck filter in passthrough mode for a local cluster with envoy 1.18 we find that a lot of cluster stats are not being generated while this was not true on 1.17.

Here are sample configs:
```yaml
static_resources:
  listeners:
  - name: ingress
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 15006
    reuse_port: true
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config: 
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: ingress
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
              pass_through_mode: true
              headers:
              - name: :path
                exact_match: /ping
          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: local_service
    type: static
    lb_policy: round_robin
    connect_timeout: 1.030s
    circuit_breakers:
      thresholds:
        max_pending_requests: 65536
        max_requests: 65536
        max_connections: 65536
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.65.2
                port_value: 8080

stats_sinks:
- name: envoy.stat_sinks.dog_statsd
  typed_config:
    "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
    max_bytes_per_datagram: 8192
    prefix: fury_traffic_sidecar
    address:
      socket_address:
        address: 172.19.0.3
        port_value: 8125

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000
```

With this envoy config we generate requests that are forwarded to `local_service`and we find that some stats are missing, for example `cluster.local_service.upstream_rq_time`, but if we remove the healthcheck filter, then all stats are generated.

Here is the complete list of stats generated without the healthcheck filter:
```
curl localhost:15000/stats | grep local_service

cluster.local_service.assignment_stale: 0
cluster.local_service.assignment_timeout_received: 0
cluster.local_service.bind_errors: 0
cluster.local_service.circuit_breakers.default.cx_open: 0
cluster.local_service.circuit_breakers.default.cx_pool_open: 0
cluster.local_service.circuit_breakers.default.rq_open: 0
cluster.local_service.circuit_breakers.default.rq_pending_open: 0
cluster.local_service.circuit_breakers.default.rq_retry_open: 0
cluster.local_service.circuit_breakers.high.cx_open: 0
cluster.local_service.circuit_breakers.high.cx_pool_open: 0
cluster.local_service.circuit_breakers.high.rq_open: 0
cluster.local_service.circuit_breakers.high.rq_pending_open: 0
cluster.local_service.circuit_breakers.high.rq_retry_open: 0
cluster.local_service.default.total_match_count: 1
cluster.local_service.external.upstream_rq_200: 1
cluster.local_service.external.upstream_rq_2xx: 1
cluster.local_service.external.upstream_rq_completed: 1
cluster.local_service.http1.dropped_headers_with_underscores: 0
cluster.local_service.http1.metadata_not_supported_error: 0
cluster.local_service.http1.requests_rejected_with_underscores_in_headers: 0
cluster.local_service.http1.response_flood: 0
cluster.local_service.lb_healthy_panic: 0
cluster.local_service.lb_local_cluster_not_ok: 0
cluster.local_service.lb_recalculate_zone_structures: 0
cluster.local_service.lb_subsets_active: 0
cluster.local_service.lb_subsets_created: 0
cluster.local_service.lb_subsets_fallback: 0
cluster.local_service.lb_subsets_fallback_panic: 0
cluster.local_service.lb_subsets_removed: 0
cluster.local_service.lb_subsets_selected: 0
cluster.local_service.lb_zone_cluster_too_small: 0
cluster.local_service.lb_zone_no_capacity_left: 0
cluster.local_service.lb_zone_number_differs: 0
cluster.local_service.lb_zone_routing_all_directly: 0
cluster.local_service.lb_zone_routing_cross_zone: 0
cluster.local_service.lb_zone_routing_sampled: 0
cluster.local_service.max_host_weight: 0
cluster.local_service.membership_change: 1
cluster.local_service.membership_degraded: 0
cluster.local_service.membership_excluded: 0
cluster.local_service.membership_healthy: 1
cluster.local_service.membership_total: 1
cluster.local_service.original_dst_host_invalid: 0
cluster.local_service.retry_or_shadow_abandoned: 0
cluster.local_service.update_attempt: 0
cluster.local_service.update_empty: 0
cluster.local_service.update_failure: 0
cluster.local_service.update_no_rebuild: 0
cluster.local_service.update_success: 0
cluster.local_service.upstream_cx_active: 1
cluster.local_service.upstream_cx_close_notify: 0
cluster.local_service.upstream_cx_connect_attempts_exceeded: 0
cluster.local_service.upstream_cx_connect_fail: 0
cluster.local_service.upstream_cx_connect_timeout: 0
cluster.local_service.upstream_cx_destroy: 0
cluster.local_service.upstream_cx_destroy_local: 0
cluster.local_service.upstream_cx_destroy_local_with_active_rq: 0
cluster.local_service.upstream_cx_destroy_remote: 0
cluster.local_service.upstream_cx_destroy_remote_with_active_rq: 0
cluster.local_service.upstream_cx_destroy_with_active_rq: 0
cluster.local_service.upstream_cx_http1_total: 1
cluster.local_service.upstream_cx_http2_total: 0
cluster.local_service.upstream_cx_http3_total: 0
cluster.local_service.upstream_cx_idle_timeout: 0
cluster.local_service.upstream_cx_max_requests: 0
cluster.local_service.upstream_cx_none_healthy: 0
cluster.local_service.upstream_cx_overflow: 0
cluster.local_service.upstream_cx_pool_overflow: 0
cluster.local_service.upstream_cx_protocol_error: 0
cluster.local_service.upstream_cx_rx_bytes_buffered: 6
cluster.local_service.upstream_cx_rx_bytes_total: 144
cluster.local_service.upstream_cx_total: 1
cluster.local_service.upstream_cx_tx_bytes_buffered: 0
cluster.local_service.upstream_cx_tx_bytes_total: 199
cluster.local_service.upstream_flow_control_backed_up_total: 0
cluster.local_service.upstream_flow_control_drained_total: 0
cluster.local_service.upstream_flow_control_paused_reading_total: 0
cluster.local_service.upstream_flow_control_resumed_reading_total: 0
cluster.local_service.upstream_internal_redirect_failed_total: 0
cluster.local_service.upstream_internal_redirect_succeeded_total: 0
cluster.local_service.upstream_rq_200: 1
cluster.local_service.upstream_rq_2xx: 1
cluster.local_service.upstream_rq_active: 0
cluster.local_service.upstream_rq_cancelled: 0
cluster.local_service.upstream_rq_completed: 1
cluster.local_service.upstream_rq_maintenance_mode: 0
cluster.local_service.upstream_rq_max_duration_reached: 0
cluster.local_service.upstream_rq_pending_active: 0
cluster.local_service.upstream_rq_pending_failure_eject: 0
cluster.local_service.upstream_rq_pending_overflow: 0
cluster.local_service.upstream_rq_pending_total: 1
cluster.local_service.upstream_rq_per_try_timeout: 0
cluster.local_service.upstream_rq_retry: 0
cluster.local_service.upstream_rq_retry_backoff_exponential: 0
cluster.local_service.upstream_rq_retry_backoff_ratelimited: 0
cluster.local_service.upstream_rq_retry_limit_exceeded: 0
cluster.local_service.upstream_rq_retry_overflow: 0
cluster.local_service.upstream_rq_retry_success: 0
cluster.local_service.upstream_rq_rx_reset: 0
cluster.local_service.upstream_rq_timeout: 0
cluster.local_service.upstream_rq_total: 1
cluster.local_service.upstream_rq_tx_reset: 0
cluster.local_service.version: 0
cluster.local_service.external.upstream_rq_time: P0(nan,100.0) P25(nan,102.5) P50(nan,105.0) P75(nan,107.5) P90(nan,109.0) P95(nan,109.5) P99(nan,109.9) P99.5(nan,109.95) P99.9(nan,109.99) P100(nan,110.0)
cluster.local_service.upstream_cx_connect_ms: P0(nan,1.0) P25(nan,1.025) P50(nan,1.05) P75(nan,1.075) P90(nan,1.09) P95(nan,1.095) P99(nan,1.099) P99.5(nan,1.0995) P99.9(nan,1.0999) P100(nan,1.1)
cluster.local_service.upstream_cx_length_ms: No recorded values
cluster.local_service.upstream_rq_time: P0(nan,100.0) P25(nan,102.5) P50(nan,105.0) P75(nan,107.5) P90(nan,109.0) P95(nan,109.5) P99(nan,109.9) P99.5(nan,109.95) P99.9(nan,109.99) P100(nan,110.0)
``` 

Here is the list when the healthcheck filter is enabled:
```
curl localhost:15000/stats | grep local_service

cluster.local_service.assignment_stale: 0
cluster.local_service.assignment_timeout_received: 0
cluster.local_service.bind_errors: 0
cluster.local_service.circuit_breakers.default.cx_open: 0
cluster.local_service.circuit_breakers.default.cx_pool_open: 0
cluster.local_service.circuit_breakers.default.rq_open: 0
cluster.local_service.circuit_breakers.default.rq_pending_open: 0
cluster.local_service.circuit_breakers.default.rq_retry_open: 0
cluster.local_service.circuit_breakers.high.cx_open: 0
cluster.local_service.circuit_breakers.high.cx_pool_open: 0
cluster.local_service.circuit_breakers.high.rq_open: 0
cluster.local_service.circuit_breakers.high.rq_pending_open: 0
cluster.local_service.circuit_breakers.high.rq_retry_open: 0
cluster.local_service.default.total_match_count: 1
cluster.local_service.http1.dropped_headers_with_underscores: 0
cluster.local_service.http1.metadata_not_supported_error: 0
cluster.local_service.http1.requests_rejected_with_underscores_in_headers: 0
cluster.local_service.http1.response_flood: 0
cluster.local_service.lb_healthy_panic: 0
cluster.local_service.lb_local_cluster_not_ok: 0
cluster.local_service.lb_recalculate_zone_structures: 0
cluster.local_service.lb_subsets_active: 0
cluster.local_service.lb_subsets_created: 0
cluster.local_service.lb_subsets_fallback: 0
cluster.local_service.lb_subsets_fallback_panic: 0
cluster.local_service.lb_subsets_removed: 0
cluster.local_service.lb_subsets_selected: 0
cluster.local_service.lb_zone_cluster_too_small: 0
cluster.local_service.lb_zone_no_capacity_left: 0
cluster.local_service.lb_zone_number_differs: 0
cluster.local_service.lb_zone_routing_all_directly: 0
cluster.local_service.lb_zone_routing_cross_zone: 0
cluster.local_service.lb_zone_routing_sampled: 0
cluster.local_service.max_host_weight: 0
cluster.local_service.membership_change: 1
cluster.local_service.membership_degraded: 0
cluster.local_service.membership_excluded: 0
cluster.local_service.membership_healthy: 1
cluster.local_service.membership_total: 1
cluster.local_service.original_dst_host_invalid: 0
cluster.local_service.retry_or_shadow_abandoned: 0
cluster.local_service.update_attempt: 0
cluster.local_service.update_empty: 0
cluster.local_service.update_failure: 0
cluster.local_service.update_no_rebuild: 0
cluster.local_service.update_success: 0
cluster.local_service.upstream_cx_active: 1
cluster.local_service.upstream_cx_close_notify: 0
cluster.local_service.upstream_cx_connect_attempts_exceeded: 0
cluster.local_service.upstream_cx_connect_fail: 0
cluster.local_service.upstream_cx_connect_timeout: 0
cluster.local_service.upstream_cx_destroy: 0
cluster.local_service.upstream_cx_destroy_local: 0
cluster.local_service.upstream_cx_destroy_local_with_active_rq: 0
cluster.local_service.upstream_cx_destroy_remote: 0
cluster.local_service.upstream_cx_destroy_remote_with_active_rq: 0
cluster.local_service.upstream_cx_destroy_with_active_rq: 0
cluster.local_service.upstream_cx_http1_total: 1
cluster.local_service.upstream_cx_http2_total: 0
cluster.local_service.upstream_cx_http3_total: 0
cluster.local_service.upstream_cx_idle_timeout: 0
cluster.local_service.upstream_cx_max_requests: 0
cluster.local_service.upstream_cx_none_healthy: 0
cluster.local_service.upstream_cx_overflow: 0
cluster.local_service.upstream_cx_pool_overflow: 0
cluster.local_service.upstream_cx_protocol_error: 0
cluster.local_service.upstream_cx_rx_bytes_buffered: 144
cluster.local_service.upstream_cx_rx_bytes_total: 144
cluster.local_service.upstream_cx_total: 1
cluster.local_service.upstream_cx_tx_bytes_buffered: 0
cluster.local_service.upstream_cx_tx_bytes_total: 199
cluster.local_service.upstream_flow_control_backed_up_total: 0
cluster.local_service.upstream_flow_control_drained_total: 0
cluster.local_service.upstream_flow_control_paused_reading_total: 0
cluster.local_service.upstream_flow_control_resumed_reading_total: 0
cluster.local_service.upstream_internal_redirect_failed_total: 0
cluster.local_service.upstream_internal_redirect_succeeded_total: 0
cluster.local_service.upstream_rq_active: 0
cluster.local_service.upstream_rq_cancelled: 0
cluster.local_service.upstream_rq_completed: 0
cluster.local_service.upstream_rq_maintenance_mode: 0
cluster.local_service.upstream_rq_max_duration_reached: 0
cluster.local_service.upstream_rq_pending_active: 0
cluster.local_service.upstream_rq_pending_failure_eject: 0
cluster.local_service.upstream_rq_pending_overflow: 0
cluster.local_service.upstream_rq_pending_total: 1
cluster.local_service.upstream_rq_per_try_timeout: 0
cluster.local_service.upstream_rq_retry: 0
cluster.local_service.upstream_rq_retry_backoff_exponential: 0
cluster.local_service.upstream_rq_retry_backoff_ratelimited: 0
cluster.local_service.upstream_rq_retry_limit_exceeded: 0
cluster.local_service.upstream_rq_retry_overflow: 0
cluster.local_service.upstream_rq_retry_success: 0
cluster.local_service.upstream_rq_rx_reset: 0
cluster.local_service.upstream_rq_timeout: 0
cluster.local_service.upstream_rq_total: 1
cluster.local_service.upstream_rq_tx_reset: 0
cluster.local_service.version: 0
cluster.local_service.upstream_cx_connect_ms: P0(1.0,1.0) P25(1.025,1.025) P50(1.05,1.05) P75(1.075,1.075) P90(1.09,1.09) P95(1.095,1.095) P99(1.099,1.099) P99.5(1.0995,1.0995) P99.9(1.0999,1.0999) P100(1.1,1.1)
cluster.local_service.upstream_cx_length_ms: No recorded values
```
