### ISSUE TITLE
Minikube, No healthy host for TCP connection pool

### ISSUE THREAD

**Issue by ajsalow** [envoyproxy/envoy#16909]
*Description*:
When running envoy on my minikube cluster I get the error
``` [source/common/upstream/cluster_manager_impl.cc:1453] no healthy host for TCP connection pool```
When I run on my aws cluster I don't get this error any everything works as expected.

*Repro steps*:
1. Create minikube clulster. 
2. Deploy downstream and upstream pods (see config below). 
3. From the downstream pod try to curl anything. 
```curl --proxy localhost:10000 https://www.google.com:443```

*Config*:
Downstream
```yaml
admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 10000
        listener_filters:
          - name: envoy.filters.listener.original_dst
            typed_config: {}
        filter_chains:
        - filter_chain_match:
            destination_port: 5432
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: dl-proxy-postgres_tcp
                cluster: dl-proxy-http
                tunneling_config:
                  hostname: postgres-postgresql.postgres.svc.cluster.local:5432
        - filter_chain_match:
            destination_port: 27017
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: dl-proxy-mongo_tcp
                cluster: dl-proxy-http
                tunneling_config:
                  #hostname: mongo-rs-mongodb-headless.mongo-rs.svc.cluster.local:27017
                  hostname: mongo-rs-mongodb-1.mongo-rs-mongodb-headless.mongo-rs.svc.cluster.local:27017
        - filters:
          - name: tcp
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp_stats
              cluster: dl-proxy-http
      clusters:
      - name: dl-proxy-http
        dns_refresh_rate: 60s
        connect_timeout: 10s
        type: strict_dns
        # This ensures HTTP/1.1 CONNECT is used for establishing the tunnel.
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              # http_protocol_options: {}
              http2_protocol_options: {}
        load_assignment:
          cluster_name: dl-proxy-http
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: proxy-dl-api-gateway.cdl-proxy
                    port_value: 80

```

upstream
```yaml
static_resources:
      listeners:
      - name: dynamic_forward_proxy_listeners
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: dynamic_proxy_stat
              http2_protocol_options: 
                allow_connect: true
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  # Support tunneling using HTTP CONNECT
                  # This route is what I had to add to get it working for my case.
                  - match:
                      connect_matcher:
                        {}
                    route:
                      cluster: dynamic_forward_proxy_cluster
                      upgrade_configs:
                        - upgrade_type: CONNECT
                          connect_config:
                            {}
                    typed_per_filter_config:
                      envoy.filters.http.dynamic_forward_proxy:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                  # Support tunneling without using HTTP CONNECT
                  - match:
                      prefix: "/"
                    route:
                      cluster: dynamic_forward_proxy_cluster
                    typed_per_filter_config:
                      envoy.filters.http.dynamic_forward_proxy:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
              http_filters:
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    name: dynamic_forward_proxy_cache_config
                    dns_lookup_family: V4_ONLY
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: dynamic_forward_proxy_cluster
        connect_timeout: 10s
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              name: dynamic_forward_proxy_cache_config
              dns_lookup_family: V4_ONLY
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            use_downstream_protocol_config:
              http_protocol_options: {}
              http2_protocol_options: {}
```
*Logs*:
```
[2021-06-09 18:42:01.537][37][debug][filter] [source/extensions/filters/listener/original_dst/original_dst.cc:20] original_dst: New connection accepted
[2021-06-09 18:42:01.537][37][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:249] [C8] new tcp proxy session
[2021-06-09 18:42:01.537][37][debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:397] [C8] Creating connection to cluster dl-proxy-http
[2021-06-09 18:42:01.537][37][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1453] no healthy host for TCP connection pool
[2021-06-09 18:42:01.537][37][debug][connection] [source/common/network/connection_impl.cc:133] [C8] closing data_to_write=0 type=1
[2021-06-09 18:42:01.537][37][debug][connection] [source/common/network/connection_impl.cc:243] [C8] closing socket: 1
[2021-06-09 18:42:04.331][1][debug][main] [source/server/server.cc:209] flushing stats
```
