### ISSUE TITLE
mongo access log error: invalid mongo op 2013

### ISSUE THREAD

**Issue by Barber0** [envoyproxy/envoy#16908]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: mongo decoding error: invalid mongo op 2013

*Description*:
There isn't record about 'insert', 'update' and 'delete' in mongo proxy's access log.
The main access log showed that 'mongo decoding error: invalid mongo op 2013'.

Should I add something in config?

I used docker image of envoy:v1.18.3 to test. I also tried MongoDB's 3.6 and 4.4.6 versions, but it still couldn't work.

My config:

```
admin:
  profile_path: /tmp/envoy.prof
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: ng
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 81
      filter_chains:
        - filters:
            name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: test_http
              access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
                - name: envoy.filters.http.router
              route_config:
                name: local_route
                virtual_hosts:
                  - name: mysvc
                    domains: [ "*" ]
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          cluster: service1
                          host_rewrite_literal: test
    - name: mgo
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 27018
      filter_chains:
        - filters:
            - name: envoy.filters.network.mongo_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.mongo_proxy.v3.MongoProxy
                stat_prefix: test_mongo
                access_log: /tmp/mongo.log
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: test_tcp
                cluster: service2
  clusters:
    - name: service1
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      connect_timeout: 1s
      load_assignment:
        cluster_name: service1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 80
    - name: service2
      type: strict_dns
      dns_lookup_family: V4_ONLY
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 27017
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
