### ISSUE TITLE
Easier config UX for inlined config-yaml

### ISSUE THREAD

**Issue by codefromthecrypt** [envoyproxy/envoy#16917]
*Title*: Easier config UX for inlined config-yaml

*Description*:
While things are becoming more type-safe, the inline yaml experience is going downhill. I believe it could be possible to have the best of both worlds with sane defaults based on key name.

ex before we could do this:
```bash
envoy --config-yaml "admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}}"
```

Now, it is pretty futile to accomplish the same inlined due to quoting and such. Also, even if you could, it would look horrible.
```yaml
admin:
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      address: '127.0.0.1'
      port_value: 0
```

What if well-known keys could imply the type, especially when no other configuration is needed? This could still be elaborated on config dump to the realized config. This could allow an easier config UX while still allowing people to lock for prod later (by using the configdump variant)

Since this is all compiled in anyway, it seems like a static registry of well-known default config could be used for this, even if only made possible with a dev-mode flag if people are worried.

*Relevant Links*:
https://github.com/envoyproxy/envoy/pull/15461

**Comment by zuercher** [comment]
I'm not sure I understand what you're looking for. Pre-defined configs that can be referenced from the command line?

**Comment by codefromthecrypt** [comment]
sorry I should have been more direct. What I mean is defaulting to the "current type" for well-known `name` keys. This treated the same whether it was passed as yaml literal or config.

ex treat
```
admin:
  access_log:
    - name: envoy.access_loggers.stdout
  address:
    socket_address:
      address: '127.0.0.1'
      port_value: 0
```

like

```admin:
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      address: '127.0.0.1'
      port_value: 0
```
