### ISSUE TITLE
[Question] Filter access logs from specific route

### ISSUE THREAD

**Issue by nulltrope** [envoyproxy/envoy#16986]
*Title*: *Filter access logs from specific route*

*Description*:
I have an HTTP listener with two static routes. One of these routes is used for an oauth callback and as such contains sensitive information in its query params, so I would like to exclude logs for only this route from my access logs.

It seemed the best way to do this was to add filter metadata on that specific route, and then use an access log filter to filter out logs which match that metadata, however I can't seem to get this to work at all. It's not yet clear to me whether the issue is with setting the metadata in the route, or matching on the metadata in the access log (or both?).

Here's an example of my config:

```yaml
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: developer_ingress
      address:
        socket_address: { address: 0.0.0.0, port_value: 9411 }
      filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: developer_ingress
              codec_type: AUTO
              http_protocol_options: 
                accept_http_10: true
              use_remote_address: true
              http_filters:
              - name: envoy.health_check
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                  pass_through_mode: false
                  headers:
                    - name: X-Envoy-Healthcheck
              - name: envoy.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  transport_api_version: "V3"
                  stat_prefix: ext_authz
                  grpc_service:
                    envoy_grpc:
                      cluster_name: oidc-service-grpc
                  failure_mode_allow: false
              - name: envoy.router
              route_config:
                name: local_route
                virtual_hosts:
                  - name: "httpbin"
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/.internal/oidc-service"
                        route:
                          cluster: oidc-service-http
                        metadata:
                          filter_metadata:
                            # don't log this route as it contains sensitive query params
                            "envoy.http_connection_manager.access_log": 
                              no_log: true
                      - match:
                          prefix: "/"
                        route:
                          cluster: httpbin
                        metadata:
                          filter_metadata:
                            # ok to log this route
                            "envoy.http_connection_manager.access_log": 
                              no_log: false
              access_log:
                - name: envoy.file_access_log
                  filter:
                    metadata_filter:
                      matcher:
                        filter: envoy.http_connection_manager.access_log
                        path: 
                          - key: no_log
                        value: 
                          bool_match: false
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: "/dev/stdout"
                    log_format:
                      omit_empty_values: true
                      json_format:
                        timestamp: "%START_TIME%"
                        log_type: "http ingress"
                        request_method: "%REQ(:METHOD)%"
                        request_path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH):256%"
                        request_accept: "%REQ(ACCEPT)%"
                        request_accept_encoding: "%REQ(ACCEPT-ENCODING)%"
                        request_protocol: "%PROTOCOL%"
                        response_code: "%RESPONSE_CODE%"
                        response_flags: "%RESPONSE_FLAGS%"
                        response_content_type: "%RESP(CONTENT-TYPE)%"
                        response_content_encoding: "%RESP(CONTENT-ENCODING)%"
                        bytes_received: "%BYTES_RECEIVED%"
                        bytes_sent: "%BYTES_SENT%"
                        duration: "%DURATION%"
                        response_upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                        request_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                        request_user_agent: "%REQ(USER-AGENT)%"
                        request_authority: "%REQ(:AUTHORITY)%"
                        upstream_host: "%UPSTREAM_HOST%"
                        upstream_cluster: "%UPSTREAM_CLUSTER%"
                        downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                        downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
```

Running this locally still logs both routes, where I would expect it to only log the second route `/`

Would love an extra set of eyes on my config to see if i'm doing something wrong! Also open to suggestions if there is a simpler way to filter out certain routes from access logs.

*Relevant Links*:
[Access Log Metadata Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-metadatafilter)
[config-core-v3-Metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-metadata)
