### ISSUE TITLE
add `go_package` option to all protobuf files

### ISSUE THREAD

**Issue by remyleone** [envoyproxy/envoy#17082]
I’m trying to compile some protobuf messages defined in envoy and I get warnings during the compilation. Could it be possible to add a go_package  option on all the envoy API protobuf? The same way that it is defined for java?

```
2021/06/22 15:26:22 WARNING: Missing 'go_package' option in "envoy/api/v2/core/socket_option.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

**Comment by alyssawilk** [comment]
cc @htuch  @adisuissa @phlax

**Comment by remyleone** [comment]
I don't mind doing the PR if I get some guidance about how to do it.

**Comment by kyessenov** [comment]
Have you used envoyproxy/go-control-plane? The go_package is not mandatory and is auto-generated. The problem with custom go_package is that Golang does not allow import of the same proto under two packages.

**Comment by remyleone** [comment]
Yes indeed, here is my buf configuration

```
version: v1beta1
plugins:
  # Generate marshalling/unmarshalling for messages in golang
  - name: go
    out: generated/go
    opt:
      - paths=source_relative
      # we use envoy messages therefore we need to tell buf where to find those go files for these messages.
      - Mudpa/annotations/migrate.proto=github.com/cncf/udpa/go/udpa/annotations
      - Mudpa/annotations/status.proto=github.com/cncf/udpa/go/udpa/annotations
      - Menvoy/api/v2/core/socket_option.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/api/v2/core/address.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/api/v2/core/backoff.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/api/v2/core/http_uri.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/api/v2/core/base.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/api/v2/core/http_uri.proto=github.com/envoyproxy/go-control-plane/envoy/api/v2/core
      - Menvoy/type/percent.proto=github.com/envoyproxy/go-control-plane/envoy/type
      - Menvoy/type/semantic_version.proto=github.com/envoyproxy/go-control-plane/envoy/type
      - Menvoy/type/http_status.proto=github.com/envoyproxy/go-control-plane/envoy/type
      - Menvoy/service/auth/v2/attribute_context.proto=github.com/envoyproxy/go-control-plane/envoy/service/auth/v2
      - Menvoy/service/auth/v2/external_auth.proto=github.com/envoyproxy/go-control-plane/envoy/service/auth/v2
```
