### ISSUE TITLE
INVALID_ARGUMENT:(dns_cache_config) dns_resolution_config: Cannot find field.

### ISSUE THREAD

**Issue by techpavan** [envoyproxy/envoy#17103]
*Description*:

Error seen:
Unknown field: type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(dns_cache_config) dns_resolution_config: Cannot find field.

After multiple attempts to resolve the above error in my config file, found that the same error is occurring with the configuration documented here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter.html

Envoy is somehow unable to validate the `dns_resolution_config`. In the example linked above, the `dns_resolution_config` is placed as a part of `envoy.filters.http.dynamic_forward_proxy` and its corresponding cluster. The same behavior is seen even when it is placed at the bootstrap level (root).

*Repro steps*:
1. Create a file `test.yaml` from the configuration shared below.
2. Run command: `envoy -c /path/to/test.yaml  --mode validate --bootstrap-version 3 --allow-unknown-static-fields`

*Logs*:
```
[2021-06-23 18:00:46.928][9232][warning][config] [external/envoy/source/common/protobuf/message_validator_impl.cc:43] Unknown field: type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(dns_cache_config) dns_resolution_config: Cannot find field.
```

*System Details*:
>OS: Ubuntu 18.04.5 LTS
Envoy: 98c1c9e9a40804b93b074badad1cdf284b47d58b/1.18.3/clean-getenvoy-b76c773-envoy/RELEASE/BoringSSL

*Config*:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/force-host-rewrite"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                          typed_per_filter_config:
                            envoy.filters.http.dynamic_forward_proxy:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                              host_rewrite_literal: www.example.org
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                        dns_resolution_config:
                          resolvers:
                            - socket_address:
                                address: "8.8.8.8"
                                port_value: 53
                          dns_resolver_options:
                            use_tcp_for_dns_lookups: true
                            no_default_search_domain: true
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: dynamic_forward_proxy_cluster
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
            dns_resolution_config:
              resolvers:
                - socket_address:
                    address: "8.8.8.8"
                    port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true

```

Please help.
