### ISSUE TITLE
IP Maxmind Lookup http filter

### ISSUE THREAD

**Issue by aguinet** [envoyproxy/envoy#17153]
*Title*: IP Maxmind Lookup http filter

*Description*:

This filter reads an IP address from a header or cookie, and generates metadata based on lookups within Maxmind database.
 
A PoC has been implemented here (missing a few things like cookies support, and a few maxmind DB data type): https://github.com/envoyproxy/envoy/compare/main...curiefense:feature/maxmind_lookup

Here is a configuration example:

```
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.ip_maxmind_lookup.v3.Config
  request:
    header: "myip"
  out_metadata_namespace: "mynamespace"
  dbs:
    - path: "/usr/share/geoip/GeoLite2-Country.mmdb"
      data:
        - out_metadata_key: "ip_country_iso"
          path: ["country", "iso_code"]
        - out_metadata_key: "ip_country_ja"
          path: ["country", "names", "ja"]
        - out_metadata_key: "ip_country"
          path: ["country"]
    - path: "/usr/share/geoip/GeoLite2-ASN.mmdb"
      data:
        - out_metadata_key: "ip_asn"
          path: ["autonomous_system_number"]
```

My main remaining question is whether provisioning the Maxmind database files should be a problem solved at the configuration level, or left as a separate problem to the people deploying envoy.

Also, I implemented adding metadata, but I don't know if that also make sens to give the possibility to add headers.

Thanks for any hints!
