### ISSUE TITLE
filter_metadata do not clear the cache after request headers updated

### ISSUE THREAD

**Issue by alex-lx** [envoyproxy/envoy#17167]
*Title*: filter_metadata not clear the cache after updating request headers

*Description*:
There's two route, lt's say r1, which matches http header `x-test-route: r1` and the other, r2, which match `x-test-route: r2`. Both the two routes have an filter_metadata, the key is `foo`, and the value is `r1` and `r2`. 
```yaml
             routes:
              - name: r1
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua:
                      foo: r1
                match:
                  path: '/'
                  headers:
                  - name: 'x-test-route'
                    exact_match: r1
                route:
                  cluster: "nginx"
              - name: r2
                metadata:
                  filter_metadata:
                    envoy.filters.http.lua:
                      foo: r2
                match:
                  path: '/'
                  headers:
                  - name: 'x-test-route'
                    exact_match: r2
                route:
                  cluster: "nginx"
```
The client will call the envoy proxy with header `x-test-route: r1`,
```bash
curl localhost:10000 -v -H 'x-test-route: r1'
```
and there's a lua filter to change the request header `x-test-route` to `r2`. Before and after changing the header, it would print the metadata `foo`.
```lua
                function envoy_on_request(request_handle)
                  request_handle:logInfo(string.format('first foo=%s', request_handle:metadata():get('foo') or nil))
                  request_handle:headers():replace('x-test-route', 'r2')
                  request_handle:logInfo(string.format('second foo=%s', request_handle:metadata():get('foo') or nil))
                end
```
It's expected got
```
first foo=r1
second foo=r2
```
but got
```
first foo=r1
second foo=r1
```
if remove the first logInfo before replacing header
```lua
                function envoy_on_request(request_handle)
                  request_handle:headers():replace('x-test-route', 'r2')
                  request_handle:logInfo(string.format('second foo=%s', request_handle:metadata():get('foo') or nil))
                end
```
would got
```
second foo=r2
```
if replace the first logInfo to just request_handle:metadata()
```lua
                function envoy_on_request(request_handle)
                  request_handle:metadata()
                  request_handle:headers():replace('x-test-route', 'r2')
                  request_handle:logInfo(string.format('second foo=%s', request_handle:metadata():get('foo') or nil))
                end
```
would got
```
second foo=r1
```

*Repro steps*:
see the description section.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
