### ISSUE TITLE
Disable the prompt of picking up the certificate on the browser UI

### ISSUE THREAD

**Issue by xxx0624** [envoyproxy/envoy#17194]
*Title*: *Disable the prompt of picking up the certificate on the browser UI*

*Description*:
>I have one envoy proxy listening on port 443 and when accessing the server https://ip on the browser UI, the browser will prompt that I need to pick up any certificate or cancel to pick up any certificate. Is there any way to avoid that?
And my guess why this happens is because the certificate verification is  enabled. As for why the certificate verification is needed is that some users would like to use certificates to pass the authN. My approach is that once the certificate verification is enabled, the certificate is accessible via the header `x-client-cert` in the ext auth service.

[*my envoy yaml*:]
```yaml
static_resources:
  listeners:
  - name: listener_0
    address: {socket_address: {address: ::, port_value: 443}}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: {prefix: "/"}
                route:
                  cluster: some_service
     http_filters:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            envoy_grpc:
              cluster_name: ext-authz
          with_request_body:
            max_request_bytes: 1024
            allow_partial_message: true
            pack_as_bytes: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: {filename: "certs/servercert1.pem"}
              private_key: {filename: "certs/serverkey1.pem"}
            validation_context: // enabled here!!!!!!!
              match_subject_alt_names:
  		contains: ""
  clusters:
  - name: some_service
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: {"filename": "certs/servercert2.pem"}
            private_key: {"filename": "certs/serverkey2.pem"}
  - name: ext-authz
     ...

```
