### ISSUE TITLE
Envoy crashes when using admin.access_log.filter in config

### ISSUE THREAD

**Issue by negram** [envoyproxy/envoy#17210]
If we use admin.access_log.filter, Envoy immediately crashes on startup. I couldn't find a way to prevent the crash.
Please, see the config along with the startup log attached. 

Checked on **1.18.3**.

```yaml
admin:
  access_log:
  - name: envoy.access_loggers.stream
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

    # !!! If we comment out the following two lines, the problem disappears
    filter:
      not_health_check_filter:  {}

```
Config: [envoy.yaml.txt](https://github.com/envoyproxy/envoy/files/6745992/envoy.yaml.txt)
Startup log: [envoy-crash.log](https://github.com/envoyproxy/envoy/files/6745987/envoy-crash.log)
