### ISSUE TITLE
Certificates prompt on the browser even though the require_client_certificate is specified to be false

### ISSUE THREAD

**Issue by xxx0624** [envoyproxy/envoy#17224]
*Title*: *When accessing the UI of my server, the browser will prompt the certificate selection although the require_client_certificate is specified to be false*

*Description*:
>I have made the `DownstreamTlsContext` to not require a client certificate but seems like it's not working. Because I'm still running into the certificate prompt when accessing my server via the browser.
Another potential bug: when I specify the `include_peer_certificate` to be true in the ext auth service, if and only if the `validation_context` is setup properly, the client certificate will be included in the CheckRequest.

*Repro steps*:
> For the certificate prompt
 1. please use the following envoy yaml config file to start a proxy
 2. access this server via the browser
> For the potential bug I mentioned above
 1. please use the following envoy yaml config file to start a proxy
 2. on the server internally, try this curl API call: `curl -k --key "the location of your private key" --cert "the location of your public certificate" https://localhost/ANY_API_SUPPORTED` and you are supposed to see the client cert in the CheckRequest
 3. remove the config "validation_context" in the yaml config file and restart the proxy
 4. try that above curl API call again and you are supposed to not see the client cert (which confused me a lot.)

*Runtime Envoy Config*:
Here is the listener and cluster config dump for the following envoy yaml config file:  
(some ports used are modified on purpose out of privacy and may not match that in the real envoy yaml config file)
https://paste.ubuntu.com/p/kHbyG7qwpn/

*Logs*:
Here is the envoy log:
(some useless logs are ignored and the most significant part is the client cert shown in the CheckRequest)
https://paste.ubuntu.com/p/s62F24YzvR/

*Envoy yaml*:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: upstream
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/api"
                route:
                  cluster: test-service
              - match:
                  prefix: "/"
                route:
                  cluster: reverse-proxy
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              grpc_service:
                envoy_grpc:
                  cluster_name: ext-authz
                timeout: 0.250s
              transport_api_version: V3
              include_peer_certificate: true
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_params: {"cipherSuites": ["ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-ECDSA-AES128-SHA", "ECDHE-RSA-AES128-SHA", "AES128-GCM-SHA256", "AES128-SHA", "ECDHE-ECDSA-AES256-GCM-SHA384", "ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-ECDSA-AES256-SHA", "ECDHE-RSA-AES256-SHA", "AES256-GCM-SHA384", "AES256-SHA"],"ecdhCurves": ["P-256"]}
            tls_certificates:
            - certificate_chain:
                filename: ".tomcat_cert.pem"
              private_key:
                filename: ".tomcat_key.pem"
            validation_context:
              trust_chain_verification: "ACCEPT_UNTRUSTED"
          require_client_certificate: false

  clusters:
  - name: test-service
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: test-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6502
  - name: ext-authz
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ext-authz
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6501
  - name: reverse-proxy
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: reverse-proxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6500

admin:
  access_log_path: "/dev/null"
  admin_allowed: ["/", "/certs", "/clusters", "/config_dump", "/init_dump", "/listeners", "/logging", "/stats"]
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8082
```
