### ISSUE TITLE
Configure Envoy sidecar to route outbound traffic

### ISSUE THREAD

**Issue by Leschge** [envoyproxy/envoy#17248]
*Title*: *Configure Envoy sidecar to route outbound traffic*

*Notice*: This is a general Envoy configuration question and does not address a bug or feature request. I opened this issue as I could not find any example or detailed instructions on how to set up an outbound/egress configuration file. Thus, I am a beginner in using Envoy and unfortunately does not have the base knowledge to achieve such a task.

*Description*:
My use case is as follows. Inside a Kubernetes Cluster I use Envoy as sidecars for my workloads. Let's say Workload A2 wants to "broadcast" a http(s) request to multiple addresses inside and outside of that cluster. These addresses cloud point to a Workload A1, Workload A3, Workload B1 and Workload B2. Notice that the broadcast targets two "groups" of Workloads.
For that specific task, I want to use the Envoy sidecar of Workload A2.

The diagramm illustrates this problem:
<img src="https://s20.directupload.net/images/210707/z9jybob3.png">

As of my current knowledge, this cloud maybe be achieved with the following approach but I am unable to do so with the official envoy documentation.  
Like, how can I actually apply a filter for outgoing traffic? 
Can I filter by domain and replace that domain with the actual target(s)? 
Therefore I would appreciate help or references to examples/docs that address this area.

```
# Envoy config of Workload A2
{
  traffic: OUTBOUND
  listener:
    filterChain:
  	  filters:
        domains: ["broadcast.group.a"]
        route:
          cluster: group_workload_a
        domains: ["broadcast.group.b"]
        route:
          cluster: group_workload_a
        domains: ["broadcast.all"]
        route:
          cluster: group_workload_a
          request_mirror_policy:
          cluster: group_workload_b
        
  clusters:
  - name: cluster_group_a
    hosts:
  	- socket_address: { 127.0.0.0:3000 } // workload A1
     #- socket_address: { 127.0.0.0:3333 } // workload A2 - points to itself, therefore not necessary
  	- socket_address: { 10.54.51.200:80 } // workload A3
  - name: cluster_group_b
    hosts:
  	- socket_address: { 127.0.0.0:3001 } // workload B1
  	- socket_address: { 10.54.51.200:81 } // workload B2
}
```

Http requests made by Workload A2 that are not made to the URL "broadcast.group.a", "broadcast.group.b" or "broadcast.all" should not be affected by envoy.

**Comment by Leschge** [comment]
Okey a small update so far. I noticed that there is no actual "outbound" traffic. Envoy sees all traffic as "inbound" traffic, therefore I was able to route the "outbound" traffic with a standard listener. 

I also was able to mirror the traffic to another cluster as well. But when I try to mirror the traffic to multiple clusters I receive the following error: `request_mirror_policy: Proto field is not repeating, cannot start list.` I am not quite sure why because the docs [reference it as an array](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/redis_proxy/v3/redis_proxy.proto.html#extensions-filters-network-redis-proxy-v3-redisproxy-prefixroutes-route) with [only the cluster key beeing required](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/redis_proxy/v3/redis_proxy.proto.html#extensions-filters-network-redis-proxy-v3-redisproxy-prefixroutes-route)

```
[...]  
static_resources:
  listeners:
  - name: outbound_broadcast
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 13001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 1s
          codec_type: auto
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/tmp/outbound-proxy.log"
          stat_prefix: ingress_http
          route_config:
            name: service_route
            virtual_hosts:
            - name: outbound_broadcast
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: dummyworkload
                  request_mirror_policy: [{cluster: workload_a }, {cluster: workload_b }]
[...]                  
```
