### ISSUE TITLE
Using URL path as operation name

### ISSUE THREAD

**Issue by vprus** [envoyproxy/envoy#17252]
I am using envoy native jaeger tracing, and am trying to use URL path and the name of operation - by default the operation name is just "ingress". It seems that decorator on a route might work, so I've tried to combine that with variables, like so:

```
              route_config:                                                                                                                                                                               
                name: local_route                                                                                                                                                                         
                virtual_hosts:                                                                                                                                                                            
                - name: local_service                                                                                                                                                                     
                  domains: ["*"]                                                                                                                                                                          
                  routes:                                                                                                                                                                                 
                  - match: { prefix: "/" }                                                                                                                                                                
                    route: { cluster: service }                                                                                                                                                           
                    decorator:                                                                                                                                                                            
                      operation: "%REQ(PATH)%"   
```

What I observe is that variable is not expanded at all, and I get traces with operation name of `"%REQ(PATH)%"`. Am I using wrong syntax, or dynamic operation name for tracing is just not supported?
