### ISSUE TITLE
The performance of direct_response and nginx return is very different

### ISSUE THREAD

**Issue by ztgoto** [envoyproxy/envoy#17266]
*Title*: *The performance of direct_response and nginx return is very different*

*Description*:
>The performance of simple http request test envoy `direct_response` and nginx `return` is very different.  Want to know what caused the problem

os: ubuntu server 20.04
nginx: 1.21.1  

config
```
worker_processes  8;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log off;

    sendfile        on;
    
    keepalive_timeout  65;

    server {
        listen       9101;
        server_name  127.0.0.1;

        location / { 
            default_type application/json;
            return 200 '{"message":"hello"}';
        } 

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
  

}
```

envoy: 1.18.3
command param:  --concurrency 8
config:
```
static_resources:
  listeners:
  - name: listener
    address:
      socket_address: {address: 0.0.0.0, port_value: 9101}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: http_test
          codec_type: AUTO
          generate_request_id: false
          route_config:
            name: route
            virtual_hosts:
            - name: test
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                direct_response:
                  status: 200
                  body:
                    inline_string: "{\"message\":\"hello\"}"
                response_headers_to_add:
                - header:
                    key: "Content-Type"
                    value: "application/json"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              dynamic_stats: false
stats_config:
  stats_matcher:
    reject_all: true
```

wrk command: `./wrk -t 8 -c 500 -d 1m http://127.0.0.1:9101/test`

nginx :
```
Running 1m test @ http://127.0.0.1:9101/test
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.06ms  322.38us   7.13ms   87.43%
    Req/Sec    56.10k     3.26k   67.54k    85.10%
  26793352 requests in 1.00m, 4.32GB read
Requests/sec: 446352.11
Transfer/sec:     73.64MB
```

envoy:
```
Running 1m test @ http://127.0.0.1:9101/test
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.00ms  775.22us  40.86ms   91.57%
    Req/Sec    15.58k     0.91k   17.35k    71.29%
  7441992 requests in 1.00m, 0.98GB read
Requests/sec: 123949.20
Transfer/sec:     16.79MB
```
