### ISSUE TITLE
How to specify the "Certificate authorities" for the "Certificate Request" during the two-way ssl handshake

### ISSUE THREAD

**Issue by xxx0624** [envoyproxy/envoy#17348]
*Title*: *How to specify the "Certificate authorities" for the "Certificate Request" during the two-way ssl handshake*

*Description*:
>During the two way ssl handshake between the Envoy and client, I find out that for the "Certificate Request" sent to the client, the field "Certificate authorities" (https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.4) has none CA even although I've specified the "trusted CA" per the doc https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext. The reason why this configuration "trusted CA" not working is that this is used after the ssl handshake which won't be helpful for the ssl handshake.
And why I'd like to specify this "Certificate authorities" is because I think without this config, when accessing the server via the browser (like Chrome), the browser will prompt a dialog box for users to select any client cert.

![image](https://user-images.githubusercontent.com/5348141/125692297-85d98991-8608-434c-a8e2-ccd89f3f7ffb.png)

**Envoy yaml config**
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: upstream
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/api"
                route:
                  cluster: test-service
              - match:
                  prefix: "/"
                route:
                  cluster: reverse-proxy
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              grpc_service:
                envoy_grpc:
                  cluster_name: ext-authz
                timeout: 0.250s
              transport_api_version: V3
              include_peer_certificate: true
          - name: envoy.filters.http.router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_params: {"cipherSuites": ["ECDHE-ECDSA-AES128-GCM-SHA256", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-ECDSA-AES128-SHA", "ECDHE-RSA-AES128-SHA", "AES128-GCM-SHA256", "AES128-SHA", "ECDHE-ECDSA-AES256-GCM-SHA384", "ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-ECDSA-AES256-SHA", "ECDHE-RSA-AES256-SHA", "AES256-GCM-SHA384", "AES256-SHA"],"ecdhCurves": ["P-256"]}
            tls_certificates:
            - certificate_chain:
                filename: ".tomcat_cert.pem"
              private_key:
                filename: ".tomcat_key.pem"
            validation_context:
              trusted_ca: {"filename":"/etc/ssl/certs/ca-certificates.crt"}

  clusters:
  - name: test-service
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: test-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6502
  - name: ext-authz
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ext-authz
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6501
  - name: reverse-proxy
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: reverse-proxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6500

admin:
  access_log_path: "/dev/null"
  admin_allowed: ["/", "/certs", "/clusters", "/config_dump", "/init_dump", "/listeners", "/logging", "/stats"]
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8082

```
