### ISSUE TITLE
[docs]: Incorrect docs for `present_match` HeaderMatcher

### ISSUE THREAD

**Issue by peterj** [envoyproxy/envoy#17345]
*Title*: *Incorrect docs for `present_match` HeaderMatcher*

*Description*:
The docs for `present_match` state the following:

```
If specified as false, header match will be performed based on whether the header is absent.
```

This is not the case, as setting the `present_match` to  `false` doesn't check for the absence of the header, the behavior is exactly the same as when `present_match` is set to `true`

*Relevant Links*:
This is a [related issue](https://github.com/envoyproxy/envoy/issues/10085) that describes the problem, however, the docs still state `false` would check for absence.

**Comment by phlax** [comment]
@peterj i dont know so much about this specific issue but if you create a PR to fix the docs im happy to review and/or ping others that do

**Comment by peterj** [comment]
I found a newer issue/PR where this functionality was supposed to fix it (https://github.com/envoyproxy/envoy/issues/14656), however, it's not clear if the behavior is by design (i.e. you must the combination of `present_match=false` and `invert_match=true` to check for an absence of the header). 

Using the config below (with `present_match=false`) the behavior I'd expect is the following:

1. `curl localhost:10000` - `hello` header is not present and I should get the HTTP 200 and Hello response back.
2. `curl -H "hello: 1" localhost:1000` - `hello` is header is present,  I should get back a 404 (since we're looking for the absence of the header).

The actual behavior is like this:

1. `curl localhost:10000`  - I get back HTTP 404 which is by my logic wrong; I am looking for the absence of `hello` header, hence the request should go through
2. `curl -H "hello: 1" localhost:1000` - I get back the HTTP 200 response which is wrong again. 

Based on this, regardless of the `present_match` value, it always checks for the presence of the header. 

<details>
  <summary>envoy-config.yaml</summary>
```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: hello
                    present_match: false
                direct_response:
                  status: 200
                  body:
                    inline_string: "Hello"
```
</details>

**Comment by soulxu** [comment]
@peterj https://github.com/envoyproxy/envoy/issues/14656 was fixed by https://github.com/envoyproxy/envoy/pull/16627

And I tested your config, I can get HTTP status code 200 with request 'curl localhost:10000'.

And I can gett 404 with 'curl localhost:10000 -H 'hello: world'

Which version you are testing? The fixed is just merge in main, not release yet. so it works with main branch.

**Comment by peterj** [comment]
ah, you're completely right. I was using the released versions (1.18.x and 1.19).

**Comment by hanjm** [comment]
still valid

**Comment by soulxu** [comment]
@hanjm I tested this on the main branch, it works as expected. Would you like show your envoy config? and which version you are running on?

I tested with config:
```
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  path: /
                  headers:
                  - name: TEST
                    present_match: false
                route:
                  cluster: my_cluster
```

Then without header, it will match:
```
curl -v http://127.0.0.1:33333
*   Trying 127.0.0.1:33333...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 33333 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:33333
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 15 Jun 2022 07:26:57 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact
* 
```
