### ISSUE TITLE
Envoy Sidecar 503 Persists Unexpectedly

### ISSUE THREAD

**Issue by fosterchuck** [envoyproxy/envoy#17363]
***Description***:
Envoy is configured as a sidecar, targeting a single upstream via loopback.  Downstream service and upstream use http keepalive, preserving the socket between requests.  When the upstream container is forcefully restarted by Docker (i.e. OOM), 503 is reported to Downstream for the entire duration of the upstream container restart.  The socket upstream is dead, but there doesn't appear to be a way to force the downstream socket to close.  The downstream service would need cumbersome logic to not only retry (the test is already doing this), but specifically restart the session toward Envoy sidecar to handle this.  I think I'm missing something in the configuration, but I've tried many different configurations, some of them impact closure timing of either the upstream or downstream socket.  None of them seem to propagate an upstream socket disconnect to the downstream socket (or http keepalive), even if all upstream hosts are dead in the cluster (and the Envoy knows this with the alternate configuration attempted).

Is there a specific configuration where the Envoy instance is configured to understand that it is a sidecar serving a single upstream endpoint and behave differently?  Even with a service mesh where the downstream endpoints might be able to react, this seems meaningful in a sidecar to minimize the work that downstream entities have to do.

***Setup***:
Although I simplified the below Envoy config for testing purposes.  We use the Envoy sidecar to:
- offload JWT validation on incoming traffic.  
- To route HTTP to either the main application container, or to other sidecar(s) that have specialized functions such as offloading http subscription & notification functions.
- lua filter that handles readiness and liveness probe routing as well as jwt scope validation.

We don't use Envoy as a part of a service mesh at this time.  Each Envoy sidecar is directly configured to perform these offloading functions.

I noticed that other Envoy sidecar implementations don't use the http connection manager (particularly in a service mesh), but it is needed in our usage.

In our real environment where the issue was discovered, a Quarkus app is communicating from within our AKS cluster to another service on the same cluster.  The target app has 3 instances/pods, each comprised of an Envoy container and an application container.  Envoy 1.16, but tested on Envoy 1.19.

In two private developer PCs, running kubernetes baked into Docker Desktop and microk8s respectively, the client/downstream app has been replaced with the below test Python app.  The upstream service has been replaced with the linked quarkus-example to simplify.  Tested on Envoy 1.16 and 1.18 latest.

***Envoy Config***:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-example-envoy-alpinev1.16-config
data:
  envoy.yaml: |
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9001
    static_resources:
      listeners:
      - name: listener0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9090
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/dev/stdout"
                  log_format:
                    json_format: 
                      v: "1"
                      "@timestamp": "%START_TIME%"
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: __DEPLOY_KUBERNETES_APPNAME__

              http_filters:
              - name: envoy.filters.http.cors
              - name: envoy.filters.http.router

      clusters:
      - name: __DEPLOY_KUBERNETES_APPNAME__
        connect_timeout: 0.25s
        load_assignment:
          cluster_name: __DEPLOY_KUBERNETES_APPNAME__
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-example
  namespace: default
spec:
  selector:
    matchLabels:
      app: quarkus-example
  replicas: 2
  template:
    metadata:
      labels:
        app: quarkus-example
        redeploylabel: sixes
    spec:
      # securityContext:
      # runAsUser: 911
      containers:
        - name: quarkus-example
          image: localhost:5000/quarkus-example
          imagePullPolicy: Always
          env:
          - name: ENVOY_UID
            value: "0"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080

        - name: envoy
          image: envoyproxy/envoy:v1.18-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy
              readOnly: false
            - name: pod-temp-cache
              mountPath: /tmp
      volumes:
        - name: envoy-config-volume
          configMap:
            name: quarkus-example-envoy-alpinev1.16-config
        - name: pod-temp-cache
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-example
  namespace: default
  labels:
    app: quarkus-example
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
#      targetPort: 8080
      targetPort: 9090
  selector:
    app: quarkus-example
```

***Test***:
Have tested in kubernetes that comes with Docker desktop, as well as in microk8s.  Live system presenting the issue is AKS.
1. Deploy any upstream service that implements an http endpoint.  I used both [Quarkus-Example](https://github.com/quarkusio/quarkus-quickstarts/tree/main/getting-started) and a Python Flask app to make sure this wasn't related to just Quarkus.
2. Deploy an Envoy sidecar for that service with the above Envoy configuration.
3. Use a test client that preserves the http session between http requests.  The below Python code will do it.
4. Run the client to watch 200 vs. 503 responses.
5. Execute ```kubectl exec -it quarkus-example-<POD ID> -c quarkus-example -- /bin/sh -c "kill 1"``` to kill the application container, but not the Envoy container.  note: you may have to execute against the other deployed pod and you may have to execute more than once to get a long enough restart time from Docker.
***Result***: client service receives 503 for the entire duration that the application container is down for a restart.
***Expected result***: The downstream socket is closed by Envoy which would allow the downstream client to open a new socket which would be directed to the alternate Envoy by k8s.  Even if this requires outlier detection and disabling healthy panic, so that Envoy knows that it has no remaining upstream path.  I tried the following, but 503 was still returned and downstream socket remained up.

Alternate outlier configuration attempted, which changes the response body, but not the response code:
```
outlier_detection:
  split_external_local_origin_errors: true
  consecutive_local_origin_failure: 1
  max_ejection_percent: 100
  
common_lb_config:
  # disable healthy panic
  healthy_panic_threshold: 
    value: 0
```

***Simple Python Client***:
```
import requests
import time
from datetime import datetime

s = requests.Session()

while True:
  try:
    r = s.get('http://localhost:8181/hello/')
  except:
    print("something went wrong")
    exit()
  print(r.status_code, " - ", r.content, " - ", datetime.now())
  time.sleep(1)
```
note: Docker's built in k8s didn't allow direct connection to service port 80 on my PC, so I port forwarded 8181 to 80.  ```kubectl port-forward service/quarkus-example 8181:80```
