### ISSUE TITLE
Disabling LuaPerRoute  configuration doesn't work with envoy-v1.19.0

### ISSUE THREAD

**Issue by nandu-vinodan** [envoyproxy/envoy#17377]
*Title*: *Disabling LuaPerRoute  configuration doesn't work with envoy-v1.19.0*

*Description*:
Lua filter is executed  for requests which match a route with Lua disabled using [LuaPerRoute](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-luaperroute) configuration. We are seeing this only in the latest envoy version - v1.19.0.

*Repro steps*:

1. Using the example from envoy [doc](https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/examples), add a lua filter before the `envoy.filters.http.router` filter.
```
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:logInfo("Hello World.")
                end
                function envoy_on_response(response_handle)
                  response_handle:logInfo("Goodbye")
                end
```
2.  Create the following route in `envoy.filters.network.http_connection_manager` with lua filter disabled.

```
- match:
       prefix: "/healthcheck"
  direct_response:
       status: 200
  typed_per_filter_config:
     envoy.filters.http.lua:
        "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
         disabled: true
```

3. Start Envoy
```
docker run -it -v $(pwd):/etc -p 10000:10000 -e ENVOY_UID=0 envoyproxy/envoy:v1.19.0 -c /etc/static.yaml
```
3. Make a request to `/healthcheck`.
```
curl -v  localhost:10000/healthcheck

< HTTP/1.1 200 OK
< date: Thu, 15 Jul 2021 14:35:12 GMT
< server: envoy
< content-length: 0
```

Expectation: Lua filter should not be executed

Actual logs:

```
[2021-07-15 14:30:45.627][23][debug][http] [source/common/http/conn_manager_impl.cc:858] [C0][S7712392761175078799] request headers complete (end_stream=true):
':authority', 'localhost:10000'
':path', '/healthcheck'
':method', 'GET'
'user-agent', 'curl/7.64.1'
'accept', '*/*'

[2021-07-15 14:30:45.627][23][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: Hello World.

[2021-07-15 14:30:45.628][23][debug][http] [source/common/http/filter_manager.cc:909] [C0][S7712392761175078799] Sending local reply with details direct_response

[2021-07-15 14:30:45.628][23][info][lua] [source/extensions/filters/http/lua/lua_filter.cc:795] script log: Goodbye
```

*Config*:[ static.yaml](https://gist.github.com/nandu-vinodan/6b90e1160d535b3ee9f6ef75cc1a5356#file-static-yaml)

*Logs*: [trace logs](https://gist.github.com/nandu-vinodan/6b90e1160d535b3ee9f6ef75cc1a5356#file-envoy-logs)

**Comment by nandu-vinodan** [comment]
Found another place where lua invocation is done, when it is not supposed to.

```
- name: envoy.filters.http.health_check
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
    pass_through_mode: false
    headers:
    - name: ":path"
      exact_match: "/health/ready"
- name: envoy.filters.http.lua
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
    inline_code: |
      function envoy_on_request(request_handle)
        request_handle:logInfo("Hello World.")
      end
      function envoy_on_response(response_handle)
        response_handle:logInfo("Goodbye")
      end
```
Since health-check filter is before the lua filter, ideally we expect a  request to `/health/ready` shouldn't execute lua code. 
But we see logs from lua.

**Comment by chrisxrepo** [comment]
i don't think it a bug,  if you set `envoy.filters.http.health_check` pass_through_mode false, the health check will response direct. so next http filters will not exec.

**Comment by mattklein123** [comment]
This is a regression I believe from: https://github.com/envoyproxy/envoy/pull/16673. cc @soulxu 

This code:

https://github.com/envoyproxy/envoy/blob/a1c5a5076e97e6cd3d4b725b6eeb645513c72092/source/common/http/utility.h#L506-L508

Does now return per-route filter configurations for direct response entries. I think this needs to be fixed.

Note that this is a very similar issue to what is being discussed here: https://github.com/envoyproxy/envoy/pull/17359#discussion_r673264014. cc @alyssawilk @snowp @chrisxrepo

**Comment by soulxu** [comment]
I found it only reproduced with direct_response.

```
        virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  path: "/"
                direct_response:
                  status: 200
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    disabled: true
```

but it works as expected with:
```
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  path: "/"
                route:
                  cluster: my_cluster
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    disabled: true
```

so let me debug more on it.
