### ISSUE TITLE
Egress proxy RBAC

### ISSUE THREAD

**Issue by conqerAtapple** [envoyproxy/envoy#17410]
*Title*: *Add support for egress proxy RBAC*

*Description*:
If envoy is used as egress proxy, it looks like currently there is not much support for RBAC. From https://github.com/envoyproxy/envoy/issues/10336, the only way to do this might be to use a config server or DNS records. If we need add further rich  semantics (RBAC), the recommendation is to write a upstream connection filter or something along those lines. 
  One way to achieve this might be to add a filter extension which extends from ListenerFilter and add RBAC like configuration for it. If so, are there any existing examples of this?
  
  The deployment architecture could be stand alone envoy (not side car). So this might mean a tproxy like setup .

  I am happy to add this feature but wanted to clarify the approach and high level design.

https://github.com/envoyproxy/envoy/issues/10336

@alyssawilk

**Comment by mattklein123** [comment]
@conqerAtapple can you describe a bit more what type of RBAC rules you are after? This has come up several times and I would like to make sure we are collecting all similar use cases.

**Comment by conqerAtapple** [comment]
> @conqerAtapple can you describe a bit more what type of RBAC rules you are after? This has come up several times and I would like to make sure we are collecting all similar use cases.

The general use case here is to :

- Deny by default
- Allow only subset of DNS /resolved ip/CIDR
- In addition to above, allow only certain Http paths (or header/tokens)
- Add principal from TLS  context or even a custom identity manager for authorization

Not sure if the above covers everything but I think i got the general idea captured.

thanks @mattklein123

**Comment by mattklein123** [comment]
Couldn't pretty much all of the above be done today using existing filters like RBAC, IP tagging, etc.?

The only part I'm unclear about is DNS restrictions. Do you mean you actually want to put restrictions on the returned resolutions from the DNS resolver?

**Comment by conqerAtapple** [comment]
> Couldn't pretty much all of the above be done today using existing filters like RBAC, IP tagging, etc.?
> I thought RBAC filter is designed for ingress. Are there examples for RBAC filter being used for egress?  Does IP tagging work for TCP proxying?

 
> The only part I'm unclear about is DNS restrictions. Do you mean you actually want to put restrictions on the returned resolutions from the DNS resolver?
> Oh i meant wildcard matching for egress. There might be a way to express "I only want to allow connections to upstream hosts that matches name *good*" but couldnt find an example.

**Comment by conqerAtapple** [comment]
Adding an example configuration I tried:

```
                  virtual_hosts:                                                                     
                    - name: local_service                                                            
                      domains: ["*cnn.*"]                                                             
                      routes:                                                                        
                        - match:                                                                     
                            prefix: "/"                                                              
                          route:                                                                     
                            cluster: dynamic_forward_proxy_cluster                                   
                          typed_per_filter_config:                                                   
                              envoy.filters.http.rbac:                                               
                                "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
                                rbac:                                                                
                                    rules:                                                           
                                        action: ALLOW                                                
                                        policies:                                                    
                                            "per-route-rule":                                        
                                                permissions:                                         
                                                    - any: true                                      
                                                principals:                                          
                                                    - any: true                                      
                    - name: local_service2                                                           
                      domains: ["www.google.com"]                                                    
                      routes:                                                                        
                        - match:                                                                     
                            prefix: "/"                                                              
                          route:                                                                     
                            cluster: dynamic_forward_proxy_cluster2                                  
                          typed_per_filter_config:                                                   
                              envoy.filters.http.rbac:                                               
                                "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
                                rbac:                                                                
                                    rules:                                                           
                                        action: DENY                                                 
                                        policies:                                                    
                                            "per-route-rule":                                        
                                                permissions:                                         
                                                    - any: true                                      
                                                principals:                                          
                                                    - any: true         
```

Expected results: request for `www.google.com` should have been denied access.
Observed result: Envoy successfully proxies requests for `www.google.com` .

Is this because i am misconfiguring ?  Or is it because of the design of rbac filter which is intended for ingress?

@mattklein123

**Comment by conqerAtapple** [comment]
update: 

I was able to enforce the test policy by adding  rbac http filter as:

```
                                                   
                  - name: envoy.filters.http.rbac                                                    
                    typed_config:                                                                    
                        "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC      
                        rules:                                                                       
                            action: DENY                                                             
                            policies:                                                                
                                "per-route-rule":                                                    
                                    permissions:                                                     
                                        - any: true                                                  
                                    principals:                                                      
                                        - any: true     
```

Conclusion: Configuration for route specific rbac policy needs a http filter also to drive the policy.
