### ISSUE TITLE
I'm trying to add custom header from envoy.filters.http.ext_authz with envoy_grpc to nginx client but it's not working

### ISSUE THREAD

**Issue by HejVkt** [envoyproxy/envoy#17450]
I have the simpe config in the envoy version 1.12.0

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                stream_idle_timeout: 0s
                skip_xff_append: false
                use_remote_address: true
                xff_num_trusted_hops: 1
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: app
                            timeout: 60s
                http_filters:
                  - name: envoy.ext_authz
                    config:
                      failure_mode_allow: true
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext-authz
                        timeout: 5s
                  - name: envoy.router

  clusters:
    - name: app
      connect_timeout: 5s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: ext-authz
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: nginx.svc.localhost
                      port_value: 80

    - name: ext-authz
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: ext-authz
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                        address: envoy-waf-filter.svc.localhost
                        port_value: 9996
```
I have to update envoy to version v1.18.3
```
static_resources:
    listeners:
        - name: listener_0
          address:
              socket_address: { address: 0.0.0.0, port_value: 8080 }
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          stat_prefix: ingress_http
                          codec_type: auto
                          stream_idle_timeout: 0s
                          skip_xff_append: false
                          use_remote_address: true
                          xff_num_trusted_hops: 1
                          route_config:
                              name: local_service
                              virtual_hosts:
                                  - name: local_service
                                    domains: ["*"]
                                    routes:
                                        - match:
                                              prefix: "/"
                                          route:
                                              cluster: app
                          http_filters:
                            - name: envoy.filters.http.ext_authz
                              typed_config:
                                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                                  failure_mode_allow: true
                                  transport_api_version: v3
                                  grpc_service:
                                      envoy_grpc:
                                          cluster_name: ext-authz
                                      timeout: 5s
                            - name: envoy.filters.http.router
    clusters:
        - name: app
          connect_timeout: 5s
          type: logical_dns
          lb_policy: round_robin
          load_assignment:
              cluster_name: ext-authz
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: nginx.svc.localhost
                                      port_value: 80
        - name: ext-authz
          connect_timeout: 5s
          type: strict_dns
          typed_extension_protocol_options:
              envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                  "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                  explicit_http_config:
                      http2_protocol_options: {override_stream_error_on_invalid_http_message: true}
          lb_policy: round_robin
          load_assignment:
              cluster_name: ext-authz
              endpoints:
                  -   lb_endpoints:
                          -   endpoint:
                                  address:
                                      socket_address:
                                          address: envoy-waf-grpc.svc.localhost
                                          port_value: 9996
```

I change transport proto version for v3 used in http://github.com/envoyproxy/go-control-plane and add custom header X-Auth to OkHttpResponse, but I can't see the header at the backend php. 

It works fine with v2 with same configurations.

Please help I'm struggling with this.
