### ISSUE TITLE
External processor changes to the :path header are ignored by the router

### ISSUE THREAD

**Issue by negrel** [envoyproxy/envoy#17470]
*Title*: *External processor changes to the :path are ignored by the router*

*Description*:
When the external processor alternate the `:path` header, the router ignore the new path and
route the request as if it was never altered.

*Repro steps*:
- Setup envoy with at least 2 cluster (clusterA and clusterB) and an external processor.
- Configure and starts the external processor to alter requests path.
  - Before alteration, the request path should match clusterA match rules
  - After alteration, the request path match clusterB match rules
- The request is routed to clusterA instead of clusterB

I have made a repo containing an environment to reproduce the bug: https://github.com/negrel/envoy-issue-ext-proc-go 

*Config*:
```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 11001

node:
  cluster: service_greeter
  id: test-id

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10001
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/httpbin"
                          route:
                            prefix_rewrite: "/get"
                            cluster: httpbin
                        - match:
                            prefix: "/httpgo"
                          route:
                            prefix_rewrite: "/get"
                            cluster: httpbingo
                http_filters:
                  - name: envoy.filters.http.ext_proc
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3alpha.ExternalProcessor
                      failure_mode_allow: false
                      async_mode: false
                      processing_mode:
                        request_header_mode: "SEND"
                        response_header_mode: "SKIP"
                        request_body_mode: "NONE"
                        response_body_mode: "NONE"
                        request_trailer_mode: "SKIP"
                        response_trailer_mode: "SKIP"
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext_proc_cluster
                  - name: envoy.filters.http.router
  clusters:
    - name: httpbin
      connect_timeout: 2s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbin.org
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    - name: httpbingo
      connect_timeout: 2s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: mockbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: httpbingo.org
                      port_value: 80
    - name: ext_proc_cluster
      type: STATIC
      connect_timeout: 0.25s
      http2_protocol_options: {}
      load_assignment:
        cluster_name: ext_proc_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 18080
```
