### ISSUE TITLE
support host regular matching

### ISSUE THREAD

**Issue by ChengDuYiyiyi** [envoyproxy/envoy#17485]
*Title*: *support host regular matching*

*Description*:
>example: subdomain-xxxx.domain.com

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  gateways:
    - bookinfo-gateway
  hosts:
    - bookinfo
    - subdomain-*.domain.com
  http:
    - route:
        - destination:
            host: bookinfo
```
