### ISSUE TITLE
http1_bridge:  response different http code fo bad request

### ISSUE THREAD

**Issue by chrisxrepo** [envoyproxy/envoy#17503]
*Title*: *bad request return different http_status*

*Description*:
> i access grpc method by http request, grpc method return grpc_status:2, when there is not head add to response, i got http status 0, but if i add a header to response, i got http status 503. i think it will response same http status, whether add header or not add header to response

*envoy config*:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9090
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: doll_service
          http_filters:
          - name: envoy.filters.http.grpc_http1_bridge
            typed_config: {} 

          - name: envoy.filters.http.router
            typed_config: {}

  clusters:
  - name: doll_service
    connect_timeout: 0.250s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: doll_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1 
                port_value: 9999
```

*The method who respose http status 200*:
```
func (e *echoServer) Error(ctx context.Context, req *pb.ErrorRequest) (*pb.ErrorResponse, error) {
	return nil, status.Error(codes.Unknown, "error test")
}
```

*The method who respose http status *:503
```
func (e *echoServer) Error(ctx context.Context, req *pb.ErrorRequest) (*pb.ErrorResponse, error) {
	grpc.SetHeader(ctx, metadata.Pairs("grpc-header", "header-test"))
	return nil, status.Error(codes.Unknown, "error test")
}
```
