### ISSUE TITLE
Question: How do I filter and compare for azp claim in JWT token

### ISSUE THREAD

**Issue by marlenekoh** [envoyproxy/envoy#17501]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *How do I filter and compare for azp claim in JWT token?*

*Description*:
>Describe the issue.
I have the following config: for the [JWT Authentication Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtrequirement)
```yaml
providers:
    keycloak:
        issuer: https://<keycloak_host>/auth/realms/<keycloak_realm>
        audiences: # this allows me to check that `aud` claim is equal to `my-audience`
            - my-audience
        ... # remote_jwks configuration omitted
    rules:
      - match:
            prefix: /
        requires:
            provider_name: keycloak
```

How can I add config to verify that the `azp` claim is equal to `my-azp`, for example?
Saw that Istio has this `request.auth.presenter` [condition](https://istio.io/latest/docs/reference/config/security/conditions/), is this possible to do in envoy?

Any help is much appreciated, thank you!

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
