### ISSUE TITLE
SPIFFE Cert Validator documentation

### ISSUE THREAD

**Issue by azdagron** [envoyproxy/envoy#17511]
+@mathetake, who authored the extension.

The SPIFFE TLS CertValidator extension metadata currently marks the extension as WIP with an unknown security posture. 

```
envoy.tls.cert_validator.spiffe:
  categories:
  - envoy.tls.cert_validator
  security_posture: unknown
  status: wip
```

This results in cautionary text being added to the documentation. I'm totally on board with setting correct expectations with consumers. I'm also very interested in the extension moving into a more trusted position.

What is the process to go through to get these changed to more favorable values?
