### ISSUE TITLE
oAuth Response with "upstream connect error or disconnect/reset before headers."

### ISSUE THREAD

**Issue by GregorBiswanger** [envoyproxy/envoy#17534]
Hey community, 
I have an oAuth authentication and when I´m successfully logged in and the journey goes back to my API gateway with Envoy, 

I get the following error message:
`response upstream connect error or disconnect / reset before headers. reset reason: connection termination`

Does this require something specific to be configured that Envoy accepts and forwards the response?

My current configuration:

```
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/api/greeting"
                          route:
                            prefix_rewrite: "/v1.0/invoke/servicea/method/api/greeting"
                            cluster: dapr
                        - match:
                            prefix: "/"
                          route:
                            prefix_rewrite: "/v1.0/invoke/mywebapp/method/"
                            cluster: dapr
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/etc/ssl/certs/https.crt"
                    private_key:
                      filename: "/etc/ssl/certs/key.pem"

  clusters:
    - name: dapr
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: dapr
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: apigateway-dapr
                      port_value: 3500
```
