### ISSUE TITLE
Envoy v 1.19 XFF regression?

### ISSUE THREAD

**Issue by nezdolik** [envoyproxy/envoy#17538]
*Title*:  Envoy v 1.19 XFF regression?

*Description*:

We have observed regression in xff behaviour when upgrading to latest stable Envoy version 1.19.0. When `xff_num_trusted_hops` is greater than zero in [http connection manager config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto) and `use_remote_address` is set to true, according to[ Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for),  the trusted client address is the Nth address from the right end of XFF. This behaviour holds in previous Envoys versions, but not in 1.19.0.

*Repro steps*:
Configure Envoy v 1.18.x and v 1.19.0 http connection manager with `xff_num_trusted_hops` greater than 0 and `use_remote_address` set to true:
```
...
          original_ip_detection_extensions:
            - name: envoy.http.original_ip_detection.xff
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.original_ip_detection.xff.v3.XffConfig"
                xff_num_trusted_hops: 2
          use_remote_address: true
```

Spin up Envoy for each version with given config. Issue a curl command to an endpoint which dumps value of xff and real ip headers:

```
curl -k --resolve "noop-web.spotify.com:8443:127.0.0.1" -H "Host: noop-web.spotify.com" -H "X-Forwarded-For: 50.0.0.1, 40.0.0.1" -H "X-Real-IP: 1.1.1.10"  https://noop-web.spotify.com:8443/v1/xff  -v
```

For Envoy version < 1.19.0 we get output:

```
< HTTP/2 200
...
< server: envoy
< via: HTTP/2 edgeproxy
<
XFF header: 50.0.0.1 #this is expected we set value of this header to same value as real ip
X-Real-IP header: 50.0.0.1
``` 

For Envoy version 1.19.0 we get output:
```
< HTTP/2 200
...
< server: envoy
< via: HTTP/2 edgeproxy
<
XFF header: 172.17.0.1
X-Real-IP header: 172.17.0.1
```
 It looks like there is a regression in latest Envoy release and it falls back to using the immediate downstream connection’s source address as trusted client address even though the number of hops in xff header is >= to configured value of `xff_num_trusted_hops`.

*Config*:
Full config can be included upon request.

**Comment by rgs1** [comment]
@nezdolik does it work if instead of doing:

```
          original_ip_detection_extensions:
            - name: envoy.http.original_ip_detection.xff
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.http.original_ip_detection.xff.v3.XffConfig"
                xff_num_trusted_hops: 2
          use_remote_address: true
```

you do:

```
   xff_num_trusted_hops: 2
   use_remote_address: true
```

?

That is you use the deprecated field `xff_num_trusted_hops`.
