### ISSUE TITLE
Outlier detection for outbound traffic with unknown destination

### ISSUE THREAD

**Issue by ivar-lazzaro** [envoyproxy/envoy#17552]
Hello Folks!

I have just recently started playing with Envoy, and I am trying to configure a proxy for my application which implements [outlier_detection](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-msg-config-cluster-v3-outlierdetection) for all the outgoing HTTP traffic.

Because this service can call a variety of destinations, I set up a cluster of the `ORIGINAL_DST` type, and set outlier_detection on it with the expectation that a given destination would error out immediately once "ejected" by Envoy.

After some testing with artificial upstream failures, I realized that the requests are actually forwarded to the upstream despite the `ejections_active` count is non-zero! Which made me think that my initial assumption on how outlier_detection works is wrong. At this point, I am thinking that outlier_detection cannot work with the `CLUSTER_PROVIDED`  load balancing policy, because Envoy cannot enforce active health checking if load balancing is relinquished to the upstream. Is that correct? If I wanted Envoy to "short-circuit" requests directed to an IP (not known beforehand) that has an elevated error rate, how can I achieve it?

Here is my current configuration:

```
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: http1_passthrough_service
  type: ORIGINAL_DST
  lb_policy: CLUSTER_PROVIDED
  connect_timeout: 1000s
  outlier_detection:
      interval: 10s
      base_ejection_time: 20s 
      max_ejection_time: 60s
      max_ejection_percent: 100
      enforcing_consecutive_5xx: 0
      enforcing_success_rate: 0
      split_external_local_origin_errors: false 
      failure_percentage_threshold: 30
      enforcing_failure_percentage: 100
      failure_percentage_minimum_hosts: 1
      failure_percentage_request_volume: 20

- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_outbound
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 16001
  listener_filters:
    - name: envoy.filters.listener.original_dst
    - name: envoy.filters.listener.http_inspector
  filter_chains:
    - filter_chain_match:
        application_protocols: "http/1.1"
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: egress_http
          route_config:
            name: remote_route
            virtual_hosts:
            - name: http1_passthrough_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: http1_passthrough_service
          http_filters:
          - name: envoy.filters.http.router
```

Outbound traffic from the application reaches Envoy on port 16001 via IPTables REDIRECT rule.
