### ISSUE TITLE
HTTPS calls from lua filter through envoy_on_request and request_handle:httpCall

### ISSUE THREAD

**Issue by riyasyash** [envoyproxy/envoy#17615]
*Title*: *HTTPS calls from lua filter through envoy_on_request*

*Description*:

I am using the envoy as an internal router, I need to make an API call to an external app every time a route is resolved. I was able to use `envoy_on_request` and `request_handle:httpCall` to forward this to an envoy cluster that is pointing to the external app. Everything was working perfectly until the external app got rid of the HTTP endpoint. Now it supports only HTTPS and `request_handle:httpCall` is not making an HTTPS request. 

Is there a way I can configure it to use HTTPS instead of HTTP?

**Comment by mattklein123** [comment]
httpCall just uses the configuration for the target cluster. Configure TLS on the target cluster.

**Comment by riyasyash** [comment]
@mattbailey Will I be able to configure the TLS for this cluster since it is for an external app?

**Comment by riyasyash** [comment]
Sorry, @mattbailey for the ping out of nowhere 😅

**Comment by riyasyash** [comment]
Finally solved the issue, for the noobs like me (and as a reference for future me) adding the solution here

For the HTTPS cluster we have to configure the `transport_socket` like this:

```yaml
      - name: external_api_endpoint
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: external_api_endpoint
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: external_api_endpoint.app.io #replace with your external server host name
                    port_value: 443 #ssl port
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
This will enable the SSL traffic from the envoy cluster to the configured external endpoint
Also, in the documentation for `request_handle:httpCall` it is said to pass the `:authority` header, and the documentation passes the cluster name as the value for `:authority`. In my case this was not working and I had to pass the actual endpoint host as the authority value. Like this:
```lua
function envoy_on_request(request_handle)
  local headers, body = request_handle:httpCall(
         'external_api_endpoint',
         {
              [':method'] = 'POST',
              [':path'] = '/api',
              [':authority'] = 'external_api_endpoint.app.io',
              ['set-cookie'] = { 'lang=lua;', 'type=binding; Path=/api' }
        },
      '{}',
       5000
  )
end
```
that was it, and the external calls are working like a charm from the per route filter 🎉 

Thanks to @mattklein123 for pointing me in the right direction and `mattbailey`(not tagging him) for entertaining a random ping 😂
