### ISSUE TITLE
Weird QUIC proxy bug - gives 504 when multiple requests are sent in sequence destined for HTTP/3 upstream

### ISSUE THREAD

**Issue by su225** [envoyproxy/envoy#17664]
*Title*: *When multiple HTTP/3 requests are sent so that it is HTTP/3 -> HTTP/3 proxy then 504 is returned after a couple of requests*

*Description*:
There is a HTTP/3 to HTTP/3 proxy which takes HTTP/3 requests and sends HTTP/3 upstream (scenario while working on https://github.com/envoyproxy/envoy/issues/17145). I get HTTP/3 request and send it to `www.cloudflare.com`. Here is the configuration
```yaml
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9000

static_resources:
  - name: http11_server
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - transport_socket:
        name: envoy.transport_socket.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: ["http/1.1"]
            tls_certificates:
            - certificate_chain: { filename: "/etc/certs/servercert.pem" }
              private_key: { filename: "/etc/certs/serverkey.pem" }
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP1
          stat_prefix: http11_proxy
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: test_route
            virtual_hosts:
            - name: cloudflare_service
              domains: ["*"]
              routes:
              - match: { prefix: "/http11" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http11
              - match: { prefix: "/http2" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http2
              - match: { prefix: "/http3" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http3
  - name: http2_server
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - transport_socket:
        name: envoy.transport_socket.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: ["h2"]
            tls_certificates:
            - certificate_chain: { filename: "/etc/certs/servercert.pem" }
              private_key: { filename: "/etc/certs/serverkey.pem" }
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP2
          stat_prefix: http2_proxy
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: test_route
            virtual_hosts:
            - name: cloudflare_service
              domains: ["*"]
              routes:
              - match: { prefix: "/http11" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http11
              - match: { prefix: "/http2" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http2
              - match: { prefix: "/http3" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http3  

  - name: http3_server
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10002
    udp_listener_config:
      quic_options: {}
      downstream_socket_config:
        prefer_gro: true
    filter_chains:
    - transport_socket:
        name: envoy.transport_sockets.quic
        typed_config:
          "@type":  type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
          downstream_tls_context:
            common_tls_context:
              alpn_protocols: ["h3"]
              tls_certificates:
              - certificate_chain: { filename: "/etc/certs/servercert.pem" }
                private_key: { filename: "/etc/certs/serverkey.pem" }
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP3
          http3_protocol_options: {}
          http_filters:
          - name: envoy.filters.http.router
          stat_prefix: http3_proxy
          route_config:
            name: test_route
            virtual_hosts:
            - name: cloudflare_service
              domains: ["*"]
              routes:
              - match: { prefix: "/http11" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http11
              - match: { prefix: "/http2" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http2
              - match: { prefix: "/http3" }
                route:
                  auto_host_rewrite: true
                  prefix_rewrite: "/"
                  cluster: cloudflare_http3

  clusters:
  - name: cloudflare_http11
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cloudflare_http11
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.cloudflare.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.cloudflare.com
        common_tls_context:
          alpn_protocols: ["http/1.1"]
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
  
  - name: cloudflare_http2
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cloudflare_http2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.cloudflare.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.cloudflare.com
        common_tls_context:
          alpn_protocols: ["h2"]
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}  

  - name: cloudflare_http3
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: cloudflare_http3
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.cloudflare.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
        upstream_tls_context:
          sni: www.cloudflare.com
          common_tls_context:
            alpn_protocols: ["h3"]
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http3_protocol_options: {} 
```

*Repro steps*:
1. Use the Envoy configuration mentioned above
2. Then try with HTTP/3 -> HTTP/2 proxying. It works as expected
    ```sh
    $ for i in {1..5}; do qcurl -svk -o /dev/null --http3 --resolve test.proxy:10002:127.0.0.1  "https://test.proxy:10002/http2" 2>&1 | 
       grep "HTTP/3 200"; done
       < HTTP/3 200
       < HTTP/3 200
       < HTTP/3 200
       < HTTP/3 200
       < HTTP/3 200
    ```
3. But for HTTP/3 -> HTTP/3 it fails after second one
    ```sh
    $ for i in {1..5}; do qcurl -svk -o /dev/null --http3 --resolve test.proxy:10002:127.0.0.1  "https://test.proxy:10002/http3" 2>&1 | 
       grep "HTTP/3 200"; done
       < HTTP/3 200
       < HTTP/3 200
      # No output after this
    ```

I run the same command without loop and grep again to see what is going on
```
$ qcurl -svk -o /dev/null --http3 --resolve test.proxy:10002:127.0.0.1  "https://test.proxy:10002/http3"
* Added test.proxy:10002:127.0.0.1 to DNS cache
* Hostname test.proxy was found in DNS cache
*   Trying 127.0.0.1:10002...
* Connect socket 5 over QUIC to 127.0.0.1:10002
* Sent QUIC client Initial, ALPN: h3,h3-29,h3-28,h3-27
* Connected to test.proxy () port 10002 (#0)
* h3 [:method: GET]
* h3 [:path: /http3]
* h3 [:scheme: https]
* h3 [:authority: test.proxy:10002]
* h3 [user-agent: curl/7.78.0-DEV]
* h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x130f2a0)
> GET /http3 HTTP/3
> Host: test.proxy:10002
> user-agent: curl/7.78.0-DEV
> accept: */*
> 
< HTTP/3 504
< content-length: 24
< content-type: text/plain
< date: Tue, 10 Aug 2021 20:01:24 GMT
< server: envoy
< 
{ [24 bytes data]
* Connection #0 to host test.proxy left intact
```
I got 504.
> The HyperText Transfer Protocol (HTTP) 504 Gateway Timeout server error response code indicates that the server, while acting as a gateway or proxy, did not get a response in time from the upstream server that it needed in order to complete the request.

However, I check directly with `www.cloudflare.com` and it works!
```
$ for i in {1..5}; do qcurl -svk -o /dev/null --http3 "https://www.cloudflare.com" 2>&1 | grep "HTTP/3 200"; done
< HTTP/3 200
< HTTP/3 200
< HTTP/3 200
< HTTP/3 200
< HTTP/3 200
```

Checking stats, this is what I see (only relevant ones included) - [QUIC_IETF_GQUIC_ERROR_MISSING and QUIC_STREAM_STREAM_CREATION_ERROR give some clues]
```
cluster.cloudflare_http3.external.upstream_rq_200: 2
cluster.cloudflare_http3.external.upstream_rq_2xx: 2
cluster.cloudflare_http3.external.upstream_rq_504: 3
cluster.cloudflare_http3.external.upstream_rq_5xx: 3
cluster.cloudflare_http3.external.upstream_rq_completed: 5
....
cluster.cloudflare_http3.http3.tx_reset: 3
....
cluster.cloudflare_http3.update_attempt: 24
cluster.cloudflare_http3.update_empty: 0
cluster.cloudflare_http3.update_failure: 0
cluster.cloudflare_http3.update_no_rebuild: 23
cluster.cloudflare_http3.update_success: 24
...
cluster.cloudflare_http3.upstream_cx_http3_total: 2
...
cluster.cloudflare_http3.upstream_rq_200: 2
cluster.cloudflare_http3.upstream_rq_2xx: 2
cluster.cloudflare_http3.upstream_rq_504: 3
cluster.cloudflare_http3.upstream_rq_5xx: 3
cluster.cloudflare_http3.upstream_rq_active: 0
cluster.cloudflare_http3.upstream_rq_cancelled: 0
cluster.cloudflare_http3.upstream_rq_completed: 5
cluster.cloudflare_http3.upstream_rq_maintenance_mode: 0
cluster.cloudflare_http3.upstream_rq_max_duration_reached: 0
cluster.cloudflare_http3.upstream_rq_pending_active: 0
cluster.cloudflare_http3.upstream_rq_pending_failure_eject: 0
cluster.cloudflare_http3.upstream_rq_pending_overflow: 0
cluster.cloudflare_http3.upstream_rq_pending_total: 2

cluster.cloudflare_http3.upstream_rq_timeout: 3
cluster.cloudflare_http3.upstream_rq_total: 5
cluster.cloudflare_http3.upstream_rq_tx_reset: 3
....
http.http3_proxy.downstream_rq_1xx: 0
http.http3_proxy.downstream_rq_2xx: 2
http.http3_proxy.downstream_rq_3xx: 0
http.http3_proxy.downstream_rq_4xx: 0
http.http3_proxy.downstream_rq_5xx: 3
http.http3_proxy.downstream_rq_active: 0
http.http3_proxy.downstream_rq_completed: 5
http.http3_proxy.downstream_rq_failed_path_normalization: 0
http.http3_proxy.downstream_rq_header_timeout: 0
http.http3_proxy.downstream_rq_http1_total: 0
http.http3_proxy.downstream_rq_http2_total: 0
http.http3_proxy.downstream_rq_http3_total: 5
....
http3.upstream.rx.quic_reset_stream_error_code_QUIC_STREAM_CANCELLED: 3
http3.upstream.tx.quic_reset_stream_error_code_QUIC_STREAM_CANCELLED: 3
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_1xx: 0
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_2xx: 2
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_3xx: 0
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_4xx: 0
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_5xx: 3
listener.0.0.0.0_10002.http.http3_proxy.downstream_rq_completed: 5
listener.0.0.0.0_10002.http3.downstream.rx.quic_connection_close_error_code_QUIC_IETF_GQUIC_ERROR_MISSING: 5
listener.0.0.0.0_10002.http3.downstream.rx.quic_reset_stream_error_code_QUIC_STREAM_STREAM_CREATION_ERROR: 5

```

It works fine for HTTP/3 -> HTTP/3 . So it looks like a problem for HTTP/3 upstream. 

Dockerfile used to build Envoy image
```Dockerfile
FROM envoyproxy/envoy-dev:latest

COPY ./envoy.yaml /etc/envoy.yaml
COPY ./servercert.pem /etc/certs/servercert.pem
COPY ./serverkey.pem /etc/certs/serverkey.pem

# Don't bake secrets into the image in production.
# This is meant for TESTING PURPOSES only
RUN chmod go+r /etc/envoy.yaml \
               /etc/certs/servercert.pem \
               /etc/certs/serverkey.pem

CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", \
                             "--log-level", "debug", \
                             "--concurrency", "1"]

EXPOSE 9000/tcp 10000/tcp 10001/tcp 10002/udp
```
