### ISSUE TITLE
Support multi-filters delegation in Composite filter

### ISSUE THREAD

**Issue by Xunzhuo** [envoyproxy/envoy#17680]
#### **Description**:

When using composite filter to delegate filters with the help of **matching api** , **composite-action** can only delegate only one filter when matching rules.

But sometimes in the same routing rules, there are at least one filter to work, this is what composite filter cannot do now.

I think this is an important feature to improve the ability of multi-filters cooperation by changing **1 match to 1 filter** to **1 match to N filters** pattern

**Comment by ggreenway** [comment]
cc @snowp @mattklein123

**Comment by snowp** [comment]
There are two problems that would need to be solved in order to support this: 

1) The matching API can only resolve one result per match execution. This would require redefining the semantics of the match tree, since it's designed with exactly one match result in mind. 
2) The way the composite filter delegates to the configured filter would not scale well to multiple filters since it would require managing filter iteration within the filter. This would require substantial design work in order to figure out, either we need to integrate it with the HCM so that it can delegate ownership to the HCM or it would need to bring in the FilterManager/something equivalent in order to manage multiple filters.

Overall I'm not sure if it's worth the complexity over just using two back to back composite filters would be worth it, but happy to leave this issue open in case someone wants to dig into this or just to see how many people need this.

**Comment by Xunzhuo** [comment]
@snowp Thanks for your two tips~ In my view, I think matching api works fine, the main problem is No.2 tip.
 If we can do this like below configs:
``` yaml
                    on_match: 
                      action:
                        name: composite-action
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                          - typed_config:
                              name: envoy.filters.http.wasm
                              typed_config:
                                "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                config:
                                  root_id: "wasm.white_list"
                                  vm_config:
                                    runtime: "envoy.wasm.runtime.v8"
                                    code:
                                      local:
                                        filename: "./wasm.white_list.wasm"
                                  configuration:
                                    "@type": type.googleapis.com/google.protobuf.StringValue
                                    value: {}
                          - typed_config:
                              name: envoy.filters.http.wasm
                              typed_config:
                                "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                                config:
                                  root_id: "wasm.black_list"
                                  vm_config:
                                    runtime: "envoy.wasm.runtime.v8"
                                    code:
                                      local:
                                        filename: "./wasm.black_list.wasm"
                                  configuration:
                                    "@type": type.googleapis.com/google.protobuf.StringValue
                                    value: {}
```

We can make composite-action to delegate more filters in onMatch action , but like you said, it needs some work to do.
