### ISSUE TITLE
use envoy and tls to proxy mysql 

### ISSUE THREAD

**Issue by lickes-liu** [envoyproxy/envoy#17754]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>When I use the envoy to proxy mysql and with tls to encode the connction, there were some errors I can't resolve. These are the envoy logs:
![图片](https://user-images.githubusercontent.com/81520087/129849349-ebbc49c0-145c-44f9-a668-9db4d9a39a27.png)
and this is my configuration:
`
```
static_resources:
  listeners:
  - name: mysql_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.filters.network.mysql_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
          stat_prefix: egress_mysql
      
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: mysql_tcp
          cluster: mysql_cluster
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_2
            tls_certificates:
            - certificate_chain: {filename: "certs/servercert.crt"}
              private_key: {filename: "certs/serverkey.key"}
            validation_context:
              trusted_ca:
                filename: certs/cacert.crt

  clusters:
  - name: mysql_cluster
    type: STRICT_DNS
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mysql
                port_value: 3306
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001`
```
         
    
    

            
Can anyone point out the problems that about my operation? This problem has confused me a few weeks!
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
