### ISSUE TITLE
type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute disabled option not working in version 1.19.0

### ISSUE THREAD

**Issue by shamigor** [envoyproxy/envoy#17798]
*Title*: *type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute disabled option not working in version 1.19.0*

*Description*:
**type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute** doesn't apply per route.
The problem reproduces in version 1.19.0.  In 1.18.3 works.

*Config*:
```
              - match:
                  path: "/health/"
                  headers:
                    - name: ":method"
                      exact_match: "GET"
                direct_response:
                  status: 200
                  body:
                    inline_string: "ok"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                    disabled: true
```
