### ISSUE TITLE
local_reply_config mapper metadata_filter does not match route metadata

### ISSUE THREAD

**Issue by petedmarsh** [envoyproxy/envoy#17802]
*Title*: *local_reply_config mapper metadata_filter does not match route metadata*

*Description*:

I will admit it is quite possible that I don't understand how this is supposed to work, though as far as I can tell from reading the documentation this *should* work so at the very least there's some improvements to the documentation that could be made.

I want to apply a locale_reply mapper if and only if certain route metadata is set, like so:

```
local_reply_config:
                  mappers:
                    - filter:
                        metadata_filter:
                          matcher:
                            filter: my_metadata
                            path:
                              - key: my_value
                            value:
                              bool_match: true
                          match_if_key_not_found:
                            value: false
```                            

I have set config on my route like so:

```
routes:
  - match:
      prefix: /
    route:
      cluster: echo-server
    metadata:
      filter_metadata:
        my_metadata:
          my_value: true
```

But the local reply override never applies. 

All responses have the default RBAC body  `RBAC: access denied` and not the local reply override.

*Repro steps*:

```
# docker compose
version: "3"
services:

  # https://github.com/jmalloc/echo-server
  echo-server:
    image: jmalloc/echo-server:0.2.0
    ports:
      - 8080:8080

  envoy-proxy:
    image: envoyproxy/envoy-debug:v1.19.0
    entrypoint: "/usr/local/bin/envoy"
    command:
      - "--service-node proxy"
      - "--service-cluster proxy"
      - "--config-path /etc/envoy/envoy.yaml"
      - "--concurrency 1"
      - "--mode serve"
      - "--log-level debug"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml # use full config in tick
    expose:
       - 8888
       - 8001
    ports:
       - 8888:8888
       - 8001:8001
```

```
docker-compose up
curl http://localhost:8888/something
```

Full config:

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:

```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  clusters:
    - name: echo-server
      connect_timeout: 1s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: echo-server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: echo-server
                      port_value: 8080
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8888
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress
                http_filters:
                  - name: envoy.filters.http.rbac
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                      rules:
                        action: DENY
                        policies:
                          general-rules:
                            permissions:
                              - any: true
                            principals:
                              - any: true
                  - name: envoy.filters.http.router
                    typed_config: {}
                local_reply_config:
                  mappers:
                    - filter:
                        metadata_filter:
                          matcher:
                            filter: my_metadata
                            path:
                              - key: my_value
                            value:
                              bool_match: true
                          match_if_key_not_found:
                            value: false
                      body_format_override:
                        json_format:
                          message: "some message"
                route_config:
                  name: route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: echo-server
                          metadata:
                            filter_metadata:
                              my_metadata:
                                my_value: true

```

*Logs*:

I can provide some but I don't think they are very useful in this case

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
