### ISSUE TITLE
client_ssl_auth should set termination details, and possibly response flag, on deny

### ISSUE THREAD

**Issue by zthomas2** [envoyproxy/envoy#17847]
*Description*:
I have envoy configured with the client_ssl_auth filter:
```
      filters:
        - name: envoy.filters.network.client_ssl_auth
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.client_ssl_auth.v3.ClientSSLAuth
            stat_prefix: client_auth
            auth_api_cluster: client_cert_provider
            refresh_delay: 5s
```
Currently this is working, in that if a call is made with a certificate included in the allowed list it is let through, and if the cert is not in the list it is denied. The problem that I'm trying to solve is that when the caller uses a certificate not included in the list, Envoy seems to simply return an empty reply rather than any useful error message.

I think I understand that this happens because the client_ssl_auth filter happens at the TCP level, before the http_connection_manager is reached. Therefore Envoy wouldn't be able to respond with the relevant HTTP code such as a 401. On top of this, the access logger doesn't appear to include any kind of useful details. Using this access logger formatting
```
    access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: /dev/stdout
        log_format:
          text_format: "[%START_TIME%] LISTENER_LOGGER call_duration_ms=%DURATION% client_address=%DOWNSTREAM_REMOTE_ADDRESS% certificate_subject=%DOWNSTREAM_PEER_SUBJECT% termination_reason=%CONNECTION_TERMINATION_DETAILS% response_flags=%RESPONSE_FLAGS% cipher=%DOWNSTREAM_TLS_CIPHER% tls_version=%DOWNSTREAM_TLS_VERSION% reply=%LOCAL_REPLY_BODY%\n"
```
I only ever receive
```
{"line":"[2021-08-25T14:39:23.391Z] LISTENER_LOGGER call_duration_ms=108 client_address=<IP AND PORT> certificate_subject=- termination_reason=- response_flags=- cipher=- tls_version=- reply=","source":"stdout","tag":"ea541942fb1c"}
```
I would think that `termination_reason` and/or `response_flags` should at least be set if Envoy terminated the connection due to a bad or missing client certificate, no?
