### ISSUE TITLE
Streaming Response Body Timeout

### ISSUE THREAD

**Issue by naaly17** [envoyproxy/envoy#17845]
Streaming Response Body Timeout

I am using Spring Boot StreamingResponseBody and Envoy is timing out, I tried setting the property in my filter chain:  max_stream_duration: 30000s  
Is there another property I should be using? 

Full YAML file: 

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
              path: /dev/stdout
              format: |
                [%START_TIME%] DS:[{%DOWNSTREAM_REMOTE_ADDRESS%}] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %REQ(:AUTHORITY)% %REQ(REFERER)%
          upgrade_configs:
          - upgrade_type: websocket
          http2_protocol_options:
            allow_connect: true
          stream_idle_timeout: 10000s
          common_http_protocol_options:
            max_stream_duration: 300000s  
          route_config:
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
      # - name: envoy.http_connection_manager
      #   typed_config:
      #     "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
      #     stat_prefix: ingress_http
      #     codec_type: AUTO
      #     stream_idle_timeout: 1000s
      #     common_http_protocol_options:
      #       max_stream_duration: 30000s                

  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 4443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          forward_client_cert_details: SANITIZE_SET
          set_current_client_cert_details:
            cert: true
            subject: true
          access_log:
            name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
              path: /dev/stdout
              format: |
                [%START_TIME%] DS:[{%DOWNSTREAM_TLS_VERSION%} {%DOWNSTREAM_REMOTE_ADDRESS%} {%DOWNSTREAM_PEER_SUBJECT%}] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %REQ(:AUTHORITY)% %REQ(REFERER)%
          upgrade_configs:
          - upgrade_type: websocket
          http2_protocol_options:
            allow_connect: true
          stream_idle_timeout: 10000s
          common_http_protocol_options:
            max_stream_duration: 300000s  
      # - name: envoy.http_connection_manager
      #   typed_config:
      #     "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
      #     stat_prefix: ingress_http
      #     codec_type: AUTO
      #     stream_idle_timeout: 1000s
      #     common_http_protocol_options:
      #       max_stream_duration: 30000s    
                        
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/komodo"
                route:
                  cluster: komodo
              # - match:
              #     prefix: "/video"
              #   route:
              #     cluster: "video"
              - match:
                  prefix: "/auth"
                route:
                  cluster: keycloak
              - match:
                  prefix: "/service"
                route:
                  cluster: mapproxy
              
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
    
           

      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: false

          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_1
              cipher_suites: "[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-RSA-AES128-GCM-SHA256|ECDHE-ECDSA-AES128-SHA|ECDHE-RSA-AES128-SHA|AES128-GCM-SHA256|AES128-SHA|ECDHE-ECDSA-AES256-GCM-SHA384|ECDHE-RSA-AES256-GCM-SHA384|ECDHE-ECDSA-AES256-SHA|ECDHE-RSA-AES256-SHA|AES256-GCM-SHA384|AES256-SHA]"
            validation_context:
              trust_chain_verification: VERIFY_TRUST_CHAIN
              trusted_ca:
                filename: "/var/opt/envoy/ca.single.crt.pem"
              crl:
                filename: "/crls/all_crls.pem"
            tls_certificates:
              certificate_chain:
                filename: "/var/opt/envoy/public.crt"
              private_key:
                filename: "/var/opt/envoy/private.key"


  clusters:
  - name: komodo
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    # http2_protocol_options: {} # was here for sidecar
    load_assignment:
      cluster_name: komodo
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: _KOMODO_SERVICE_HOST_
                port_value: 8000
  # - name: video
  #   connect_timeout: 5s
  #   type: strict_dns
  #   lb_policy: round_robin
  #   # http2_protocol_options: {
  #   #     "max_stream_duration": "5000000"
  #   # } # was here for sidecar
  #   load_assignment:
  #     cluster_name: video
  #     endpoints:
  #     - lb_endpoints:
  #       - endpoint:
  #           address:
  #             socket_address:
  #               address: _KOMODO_SERVICE_HOST_
  #               port_value: 8771
  - name: keycloak
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    # http2_protocol_options: {} # was here for sidecar
    load_assignment:
      cluster_name: keycloak
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: _KOMODO_SERVICE_HOST_
                port_value: 8080
  - name: mapproxy
    connect_timeout: 10s
    type: strict_dns
    lb_policy: round_robin
    # http2_protocol_options: {} # was here for sidecar
    load_assignment:
      cluster_name: mapproxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: _KOMODO_SERVICE_HOST_
                port_value: 7000
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000
                ```
