### ISSUE TITLE
How to implement HTTP protocol (non TLS), different domain names are configured under different FilterChain or Filter

### ISSUE THREAD

**Issue by virnet** [envoyproxy/envoy#17866]
*Title*: *How to implement HTTP protocol (non TLS), different domain names are configured under different FilterChain*

*Description*:
> I configure this now, but an error will be reported after running.
**error message**
[2021-08-26 17:18:40.319][1609823][critical][main] [source/server/server.cc:112] error initializing configuration '/etc/envoy/envoy.yaml': error adding listener '0.0.0.0:80': filter chain '' has the same matching rules defined as ''
[2021-08-26 17:18:40.320][1609823][info][main] [source/server/server.cc:855] exiting
error adding listener '0.0.0.0:80': filter chain '' has the same matching rules defined as ''

**configuration file:**
```yaml
static_resources:
  listeners:
  - name: 'listener_quic'
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: HTTP3
            stat_prefix: ingress_http
            route_config:
              name: xxx.abc.com
              virtual_hosts:
                - name: xxx.abc.com
                  domains:
                    - xxx.abc.com
                    - 'xxx.abc.com:80'
                  routes:
                    - match:
                        prefix: /
                      route:
                        cluster: www_abc_com
            http_filters:
              - name: envoy.filters.http.router
            access_log:
              - name: envoy.file.access_log
                typed_config:
                  '@type': >-
                    type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /var/log/envoy/access.log
                  log_format:
                    json_format:
                      time: '%START_TIME%'
                      bytes_sent: '%BYTES_SENT%'
                      http_x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
                      protocol: '%PROTOCOL%'
                      remote_addr: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
                      request_host: '%REQ(:AUTHORITY)%'
                      request_method: '%REQ(:METHOD)%'
                      request_time: '%DURATION%'
                      request_uri: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                      status: '%RESPONSE_CODE%'
                      upstream_addr: '%UPSTREAM_HOST%'
                      upstream_response_time: '%RESPONSE_TX_DURATION%'
            upgrade_configs:
              - upgrade_type: websocket
    - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            route_config:
              name: www.abc.com
              virtual_hosts:
                - name: www.abc.com
                  domains:
                    - www.abc.com
                    - 'www.abc.com:80'
                  routes:
                    - match:
                        prefix: /
                      route:
                        cluster: www_abc_com
            http_filters:
              - name: envoy.filters.http.router
            access_log:
              - name: envoy.file.access_log
                typed_config:
                  '@type': >-
                    type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /var/log/envoy/access.log
                  log_format:
                    json_format:
                      time: '%START_TIME%'
                      bytes_sent: '%BYTES_SENT%'
                      http_x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
                      protocol: '%PROTOCOL%'
                      remote_addr: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
                      request_host: '%REQ(:AUTHORITY)%'
                      request_method: '%REQ(:METHOD)%'
                      request_time: '%DURATION%'
                      request_uri: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                      status: '%RESPONSE_CODE%'
                      upstream_addr: '%UPSTREAM_HOST%'
                      upstream_response_time: '%RESPONSE_TX_DURATION%'
            upgrade_configs:
              - upgrade_type: websocket
   
  clusters:
  - name: www_abc_com
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: blackbox
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.31.153.10
                port_value: 80

admin:
  access_log:
  - name: envoy.file_access_log
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      log_format:
        json_format:
          time: '%START_TIME%'
          bytes_sent: '%BYTES_SENT%'
          http_x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
          protocol: '%PROTOCOL%'
          remote_addr: '%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%'
          request_host: '%REQ(:AUTHORITY)%'
          request_method: '%REQ(:METHOD)%'
          request_time: '%DURATION%'
          request_uri: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
          status: '%RESPONSE_CODE%'
          upstream_addr: '%UPSTREAM_HOST%'
          upstream_response_time: '%RESPONSE_TX_DURATION%'
      path: "/var/log/envoy/admin.access.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8911
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000
        overload:
          global_downstream_max_connections: 50000

```
