### ISSUE TITLE
support on configuring HTTP Tunnel(HTTP CONNECT) + HTTPS 

### ISSUE THREAD

**Issue by stamak** [envoyproxy/envoy#17892]
*Description*:
 There is a need to implement next schema
 >client --clear HTTP--> envoy --CONNECT-over HTTP2-and HTTPS1 --> froward proxy --HTTPS2--> Server 
 
`--CONNECT-over HTTP2-and HTTPS1 -->`  is pretty interesting as it has `Proxy-Authorization` as well as should be validated with custom ca cert

As I understand  [next](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades) should be configured

>Note that for CONNECT-over-tls, Envoy can not currently be configured to do the CONNECT request in the clear and encrypt previously unencrypted payload in one hop. To send CONNECT in plaintext and encrypt the payload, one must first forward the HTTP payload over an “upstream” TLS loopback connection to encrypt it, then have a TCP listener take the encrypted payload and send the CONNECT upstream. 

now My current config looks is below but it still does not work
I would really appreciate if you can help me with
Thx in advance 

```
static_resources:
  listeners:
    - name: main_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8088
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: HTTP2
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: app
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite_literal: mydest.host.com
                            cluster: "loopback_cluster"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    - name: api_proxy_listener
      address:
        pipe:
          path: "@/cluster_0"
      filter_chains:
        - filters:
            - name: tcp
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_stats
                cluster: "proxy_cluster"
                tunneling_config:
                  hostname: mydest.host.com:443
                  headers_to_add:
                    - header:
                        key: Proxy-Authorization
                        value: Basic dXNlcjpwYXNzd29yZA== # replace with your credentials
                      append: false
  clusters:
    - name: proxy_cluster
      http2_protocol_options: {}
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: proxy_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: forward.proxy.com
                      port_value: 8443
      transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: forward.proxy.com
            common_tls_context:
              validation_context:
                match_subject_alt_names:
                  - exact: "forward.proxy.com"
                trusted_ca:
                  filename: /etc/my-certs/forward-proxy-ca.pem
    - name: loopback_cluster
      connect_timeout: 5s
      upstream_connection_options:
        tcp_keepalive: {}
      type: STATIC
      load_assignment:
        cluster_name: loopback_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: "@/cluster_0"
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: mydest.host.com
```

*Relevant Links*:
- https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades
