### ISSUE TITLE
Use Header to select cluster

### ISSUE THREAD

**Issue by juanvasquezreyes** [envoyproxy/envoy#17914]
Is it possible to use any header to select the cluster I want to send the request to?

if not I think will be a nice enhancement, for example

```
              route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: %REQ(Environment)%
```

and at the clusters section, have as many clusters you want that will be selected with the enviroment, example
```
  clusters:
    - name: QA
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: QA
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: qa.com
                  port_value: 80
    - name: PROD
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: PROD
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: prod.com
                  port_value: 80
```
