### ISSUE TITLE
found the oauth2 filter config error 

### ISSUE THREAD

**Issue by busgo** [envoyproxy/envoy#17923]
Hello, when i  inject the oauth2 filter  start the envoy service found error 

``` shell 

[2021-08-31 11:14:56.325][1][critical][main] [source/server/server.cc:113] error initializing configuration '/etc/envoy/envoy.yaml': GenericSecretSdsApi: node 'id' and 'cluster' are required. Set it either in 'node' config or via --service-node and --service-cluster options.
[2021-08-31 11:14:56.326][1][info][main] [source/server/server.cc:880] exiting
GenericSecretSdsApi: node 'id' and 'cluster' are required. Set it either in 'node' config or via --service-node and --service-cluster options.

```

my envoy.yaml is  
``` yaml

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
            - name: envoy.filters.http.oauth2
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3alpha.OAuth2
                config:
                  token_endpoint:
                    cluster: auth_service
                    uri: 127.0.0.1:8002/token
                    timeout: 3s
                  authorization_endpoint: http://127.0.0.1:8002/oauth/authorize/
                  redirect_uri: "%REQ(:x-forwarded-proto)%://%REQ(:authority)%/callback"
                  redirect_path_matcher:
                    path:
                      exact: /callback
                  signout_path:
                    path:
                      exact: /callback
                  credentials:
                    client_id: foo
                    token_secret:
                      name: token
                      sds_config:
                        path: "/etc/envoy/token-secret.yaml"
                    hmac_secret:
                      name: hmac
                      sds_config:
                        path: "/etc/envoy/hmac.yaml"
                
            - name: envoy.router


  clusters:
  - name: local_service
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment: 
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8001
  - name: auth_service
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment: 
      cluster_name: auth_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8002
 
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8082

```
