### ISSUE TITLE
SNI not retrievable streamInfo:requestedServerName() not working

### ISSUE THREAD

**Issue by 7FA49AAC-93BF-411A-A56B-7F0416652D1F** [envoyproxy/envoy#17965]
*Title*: *SNI not retrieved or `nil` with streamInfo:requestedServerName()*

*Description*:
We need a conditional statement which checks whether the originating SNI is `subdomain.domain.tld` or `api-{000...999}.domain.tld`. We use multiple `virtual_hosts` for that.
For this, we planned on using `streamInfo:requestedServerName()` in the lua filter, checking the SNI.
To retrieve it, following documentation, we tried a lot but usually got `nil` back.

```lua
envoy_on_request(request_handle)
  local sni_nm = request_handle:streamInfo():requestedServerName():get()
  request_handle:headers():replace("sni_name", tostring(sni_nm))
end
```

Further, this might be a different issue, we need to filter as follows:
1. cors,
2. run lua script 1 which extracts a JWT from a cookie and adds it to the header,
3. authenticate JWT against our IDP
4. run lua script 2 for one of the many routes. It checks for a 401 status and redirects to our login page while setting a status 301. 

To 4. we want to add our condition.

Sadly, we were not able to have LuaPerRoute run sandwiching the auth .
Our first filter runs 
```yaml
         - name: envoy.filters.http.cors
            typed_config: {}
         - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                --code omitted
         - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
[...]
         - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: {}
              source_codes:
                reroute_status_fourhundredandone.lua:
                  inline_string: |
                    --code omitted
          - name: envoy.filters.http.router
             typed_config: {}
```

This did not work as expected, but did work before on APIv2. Sadly on v2 we were not able to have per route Lua code. Further we need to upgrade anyways since v2 is deprecated.

1. How do we get our SNI from the request of the user from the frontend to our Envoyproxy?
2. How do we sandwich the authentication between two separate Lua codes?

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/v1.16.2/configuration/http/http_filters/lua_filter.html?highlight=servername#requestedservername
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#envoy-v3-api-msg-extensions-filters-http-lua-v3-luaperroute
