### ISSUE TITLE
Upstream connection not closed on certificate expiration

### ISSUE THREAD

**Issue by gitirabassi** [envoyproxy/envoy#17999]
*Title*: *Cluster with client certificate keeps using old connections with expired certificate*

*Description*:
This issue is relevant when the cluster is configured with client certificate (10 days expiration) and envoy keeps using the same connection for issuing requests even after the certificate is expired. new conenctions are issued with the correctly loaded certificate but old connections are not terminated

In our case we use an mTLS authentication system, when requests are made ov

We tried removing tcp_keepalive and the occurrence of this is reduced but not eliminated

Proposed solutions:
1. terminate connections 1s/5s/30s/60s before certificate expiration
2. implement `max_connection_duration` for upstreams in https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto.html#config-core-v3-httpprotocoloptions 

Example cluster configuration
```yaml
static_resources:
  clusters:
    - circuit_breakers:
        thresholds:
          - max_connections: 2048
            max_pending_requests: 65536
            max_requests: 65536
      connect_timeout: 5s
      eds_cluster_config:
        eds_config:
          path: /etc/envoy/eds-someendpoints.yaml
          resource_api_version: V3
      lb_policy: MAGLEV
      name: testcluster
      per_connection_buffer_limit_bytes: 32768
      track_cluster_stats:
        request_response_sizes: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            alpn_protocols:
              - h2
              - http/1.1
            tls_certificate_sds_secret_configs:
              - name: sds-client
                sds_config:
                  path: /etc/envoy/sds-client.yaml
                  resource_api_version: V3
            validation_context_sds_secret_config:
              name: sds-ca
              sds_config:
                path: /etc/envoy/sds-ca.yaml
                resource_api_version: V3
      type: EDS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              hpack_table_size: 65536
              max_concurrent_streams: 2147483647
      upstream_connection_options:
        tcp_keepalive:
          keepalive_interval: 75
          keepalive_probes: 9
          keepalive_time: 600
```
