### ISSUE TITLE
How to configure http-https redirect

### ISSUE THREAD

**Issue by BatanGaming** [envoyproxy/envoy#18092]
*Title*: *Cannot configure http -> https redirect*

*Description*:
Here's my configuration file
```
static_resources:
  listeners:
  - name: http_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
        protocol: TCP
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          route_config:
            name: default_route
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: 
                  prefix: "/"
                redirect:
                  https_redirect: true

  - name: https_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
        protocol: TCP
    filter_chains:
    - filters:
...
```

Https listener works perfectly, but http listener doesn't redirect. When I'm sending a request to 80 port, connection is established, but request is hanging. 
I launch it in docker, 80 and 443 ports are exposed

**Comment by jaywlm** [comment]
add a default router
```
          route_config:
            name: default_route
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: 
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
