### ISSUE TITLE
[Question] Header-To-Metadata Filter -> how should i use?

### ISSUE THREAD

**Issue by rbrandino1** [envoyproxy/envoy#18137]
*Title*: *Header-To-Metadata Filter -> What am I doing wrong?*

*Description*:

I have a project using grpc-web, where I'm working with httpOnly cookie to send a logged user authentication token.
 
Turns out my back-end application gets this information automatically (with no config specs for it) into metadata.cookies (in a string array).

I would like to change this format and for that, I am trying to envoy the Header-To-Metadata Filter with the documentation example itself (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter ).
 
 
Even applying these header_to_metadata HTTP filters, nothing happens. It seems that none of them work. My back-end doesn't add any new metadata properties (version or x-authenticated-user)

The HttpFilters of my envoy config:

```yaml
http_filters:
  - name: envoy.filters.http.grpc_web
  - name: envoy.filters.http.cors
  - name: envoy.filters.http.header_to_metadata
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
      request_rules:
        - header: x-version
          on_header_present:
            metadata_namespace: envoy.lb
            key: version
            type: STRING
          on_header_missing:
            metadata_namespace: envoy.lb
            key: version
            value: '123'
            type: STRING
          remove: false
  - name: envoy.filters.http.header_to_metadata
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
      request_rules:
        - cookie: authToken
          on_header_present:
            key: x-authenticated-user
            type: STRING
          on_header_missing:
            key: x-authenticated-user
            value: 'no-authenticated-user'
            type: STRING
  - name: envoy.filters.http.router
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

Any idea?

**Comment by dio** [comment]
@rbrandino1 the metadata here is https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters.html?#metadata. Used by envoy (and its filters) internally. From my reading, sorry if I'm wrong, are you trying to add more data to the `set-cookie` header itself?

**Comment by rbrandino1** [comment]
@dio Thanks for your response.

Because of my lack of experience, I was making a mess.
Your sentence sums it up: "Used by envoy (and its filters) INTERNALLY."

When I submitted the question, I was with the understanding that the `header_to_metadata` filter besides extracting the information from the cookie or the header, it also automatically created a new property inside the GRPC metadata with the extracted value.

But following my tests, I understood that this "metadata" is not the "GRPC metadata". And I should use this `header_to_metadata` feature along with other features capable of reading this internally saved data, like: "Custom request/response headers" - > %DYNAMIC_METADATA([“namespace”, “key”, …])%.

Answering your question: I just wanted to extract information received inside a cookie, and put it in a new property in the request headers -> This will make my GRPC service receive it inside its `grpc.metadata`.

I'll leave my complete config here with this scenario working to set an example to others:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8801 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                stream_idle_timeout: 0s
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.header_to_metadata
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
                      request_rules:
                        - cookie: 'authToken'
                          on_header_present:
                            metadata_namespace: envoy.lb
                            key: 'authIdToken'
                            type: STRING
                          on_header_missing:
                            metadata_namespace: envoy.lb
                            key: 'authIdToken'
                            value: 'no-authenticated-user'
                            type: STRING
                          remove: false
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                    name: local_route
                    virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                          - match: { prefix: "/" }
                            route:
                              cluster: chat_service
                              max_grpc_timeout: 0s
                              max_stream_duration:
                                grpc_timeout_header_max: 0s
                        request_headers_to_add:
                          - header:
                              key: "x-authenticated-user"
                              value: '%DYNAMIC_METADATA(["envoy.lb","authIdToken"])%'
                            append: true
                        cors:
                          allow_origin_string_match:
                            - prefix: "*"
                          allow_methods: GET, PUT, DELETE, POST, OPTIONS
                          allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                          max_age: "1728000"
                          expose_headers: custom-header-1,grpc-status,grpc-message
  clusters:
    - name: chat_service
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      # upstream_connection_options:
      # tcp_keepalive:
      # keepalive_time: 300
      lb_policy: ROUND_ROBIN
      # win/mac hosts: Use address: host.docker.internal instead of address: localhost in the line below
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 172.17.0.1
                      port_value: 8080
```
