### ISSUE TITLE
[Adaptive Concurrency filter] Occasional 503s while gradient is 1 and minRTT calculation is inactive 

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#18152]
Hi team, we are testing adaptive concurrency on Kubernetes. We noticed some 503s, but we are a bit confused why it happened. As shown in the picture, the gradient was always 1, and the concurrency limit was stable (except when it calculates the minRTT, but when that happened the concurrency was still higher than the actual concurrency 5 > 30 * 0.02). The ingress RPS and ingress latency were also relatively stable. What could be the reason that the filter blocked some requests? 
These are our configurations:
```
                   gradient_controller_config:
                      sample_aggregate_percentile:
                        value: 50
                      concurrency_limit_params:
                        concurrency_update_interval: 10s
                      min_rtt_calc_params:
                        jitter:
                          value: 10
                        interval: 60s
                        request_count: 50
                        min_concurrency: 5
                        buffer:
                          value: 50
                    enabled:
                      default_value: true
                      runtime_key: "adaptive_concurrency.enabled"
```

<img width="1827" alt="Screen Shot 2021-09-16 at 11 43 22 AM" src="https://user-images.githubusercontent.com/53799447/133667964-9ded3e0c-edf6-4dec-9698-bd805c8f26b9.png">
<img width="769" alt="Screen Shot 2021-09-16 at 11 52 39 AM" src="https://user-images.githubusercontent.com/53799447/133668946-90f57a12-e995-4d5c-8c22-db881ad25919.png">
<img width="721" alt="Screen Shot 2021-09-16 at 11 53 05 AM" src="https://user-images.githubusercontent.com/53799447/133668957-7272c0c6-0f55-40f5-ba19-2ca327bfcf7e.png">

Thanks for the help!
