### ISSUE TITLE
503 Service unavailable. How to detect error location.

### ISSUE THREAD

**Issue by MydroX** [envoyproxy/envoy#18181]
*Title*: *503 Service unavailable. How to detect error location*

*Description*:
>I am experiencing 503 errors when I am doing my request with GRPC-web. This request is returning a stream of data. I have 200 response when the method is OPTION. This is my envoy conf : 
```yaml
  admin:
    access_log_path: /tmp/admin_access.log
    address:
      socket_address: { address: 0.0.0.0, port_value: 9901 }

  static_resources:
    listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 9000 }
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            codec_type: auto
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match: { prefix: "/" }
                  route:
                    cluster: position_service
                    max_grpc_timeout: 0s
                cors:
                  allow_origin_string_match:
                  - prefix: "*"
                  allow_methods: GET, PUT, DELETE, POST, OPTIONS
                  allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                  max_age: "1728000"
                  expose_headers: custom-header-1,grpc-status,grpc-message
            http_filters:
            - name: envoy.grpc_web
            - name: envoy.cors
            - name: envoy.router
    clusters:
    - name: position_service
      connect_timeout: 2s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: localhost
                      port_value: 3000
```

I am using the debug mode but it's not giving me much more informations. 

This is the error message : upstream connect error or disconnect/reset before headers. reset reason: connection failure.

So I am looking for a way to have more precise information to locate my error through my network or if you have a solution I will be glad to look at it. 

[optional *Relevant Links*:]
>Network : https://imgur.com/a/RsvBBno
