### ISSUE TITLE
Is it possible to simultaneously accept grpc web requests and standard HTTP/2 grpc requests on the same endpoint?

### ISSUE THREAD

**Issue by rmilejcz** [envoyproxy/envoy#18194]
*Description*:

I currently have an RPC server setup in Go accepting requests from a GRPC web client implemented in Javascript. We are now setting up a flutter mobile app and have established a dart client, but our current proxy does not like the requests:

```
Unhandled Exception: gRPC Error (code: 2, codeName: UNKNOWN, message: HTTP connection completed with 464
instead of 200, details: [], rawResponse: null, trailers: {server: awselb/2.0, date: Wed, 15 Sep 2021 19:12:11 GMT, 
content-length: 0})
```

I am assuming this is because we have the `grpc-web` http filter, so the server is expecting HTTP1/1 requests but the dart client is sending HTTP2 requests. Is there a way I can configure envoy to support both kinds of requests? I will post my envoy config below:

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: $LISTEN_PORT
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: service_route
                  virtual_hosts:
                    - name: service_host
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/ping"
                          direct_response:
                            status: 200
                        - match:
                            prefix: "/"
                          route:
                            cluster: service
                            timeout:
                              seconds: 0
                              nanos: 0
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,authorization
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.router
```
