### ISSUE TITLE
Route match prefix not working

### ISSUE THREAD

**Issue by dclipca** [envoyproxy/envoy#18233]
Envoy doesn't catch the specified config (is not able to detect it). That is, while accessing symmetric.xxx.com/api, there is a 404 error. On the other hand, if the following config
```
- match:
   prefix: "/"
``` 
is being used, the api can be accessed at ```symmetric.xxx.com```. This should mean that the problem is in the prefix specification.

```
static_resources:
  listeners:
    - name: default_listener  
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: xxx-backend-app
                      domains:
                        - "symmetric.xxx.com"
                      routes:
                        - match:
                            prefix: "/api"
                          route:
                            cluster: xxx-backend
                http_filters:
                  - name: envoy.filters.http.router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain: { filename: "/etc/letsencrypt/live/xxx.com/fullchain.pem" }
                    private_key: { filename: "/etc/letsencrypt/live/xxx.com/privkey.pem" }
  clusters:
    - name: xxx-frontend
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: xxx-frontend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 3000
    - name: xxx-backend
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: xxx-backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 4000
```
