### ISSUE TITLE
what is dubbo_proxy route_config group version for?when I add group config,the call will timeout and server no log?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18366]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: envoyfilter-dubbo-proxy
spec:
  workloadSelector:
    labels:
      app: dubbo-hello-provider
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: 10.68.45.215_20880
        filterChain:
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.dubbo_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.dubbo_proxy.v3.DubboProxy
          stat_prefix: outbound|20880||org.example.api.IGroupService
          protocol_type: Dubbo
          serialization_type: Hessian2
          route_config:
          - name: outbound|20880||org.example.api.IGroupService
            interface: org.example.api.IGroupService
            #group: group1
            routes:
            - match:
                method:
                  name:
                    exact: dubboCallProiderService
              route:
                cluster: outbound|20880|v2|dubbo-hello-provider.istio.svc.cluster.local
  - applyTo: NETWORK_FILTER
    match:
      listener:
        name: virtualInbound
        filterChain:
          destinationPort: 20880
          filter:
            name: "envoy.filters.network.tcp_proxy"
    patch:
      operation: REPLACE
      value:
        name: envoy.filters.network.dubbo_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.dubbo_proxy.v3.DubboProxy
          stat_prefix: inbound|20880||
          protocol_type: Dubbo
          serialization_type: Hessian2
          route_config:
          - name: inbound|20880||
            interface: org.example.api.IGroupService
            #group: group1
            routes:
            - match:
                method:
                  name:
                    exact: dubboCallProiderService
              route:
                cluster: outbound|20880|v2|dubbo-hello-provider.istio.svc.cluster.local
```

when I add group config,the call will timeout and server no log?
does it mean client setting or server setting?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
