### ISSUE TITLE
bug in request_mirror_policies when putting large object 

### ISSUE THREAD

**Issue by huangp0600** [envoyproxy/envoy#18364]
I use the feature of mirror policy.
```
                          route:
                            cluster: srvA
                            request_mirror_policies:
                              cluster: srvB
                              runtime_fraction:
                                { default_value: { numerator: 100 } 
```
when I put a small object to envoy(KB), srvA and srvB would both process the request. 
but when I put a larger object(about 10M), only srvA can receive the request.
can someone help?
