### ISSUE TITLE
wasm on_http_request_body never end when decompressing gzipped request

### ISSUE THREAD

**Issue by cortex93** [envoyproxy/envoy#18380]
*Title*: *wasm on_http_request_body never end when decompression gzipped request*

*Description*:
>When GZip decompressor decompress the request before calling the wasm filter, on_http_request_body is never called with end_of_stream = true. Thus, if the wasm plugin need to buffer the body, it can never resume when the body is complete.

*Repro steps*:

With a Wasm plugins doing buffering on request body (see code fragment below), make a gzip encoded POST request. The request will never end.

```
fn on_http_request_body(&mut self, body_size: usize, end_of_stream: bool) -> Action {
        debug!("on_http_request_body: body_size({}) / end_of_stream: ({:?})", body_size, end_of_stream);

        if !end_of_stream {
            // Wait -- we'll be called again when the complete body is buffered
            // at the host side.
            return Action::Pause;
        }
        Action::Continue
    }
```
*Config*:
listeners filters configuration 
```
        http_filters:
          - name: envoy.filters.http.decompressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
              decompressor_library:
                name: small
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.compression.gzip.decompressor.v3.Gzip"
              response_direction_config:
                common_config:
                  enabled:
                    default_value: false
                    runtime_key: response_decompressor_enabled
              request_direction_config:
                common_config:
                  enabled:
                    default_value: true
                    runtime_key: request_decompressor_enabled
          - name: envoy.filters.http.wasm
            typed_config:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              value:
                config:
                  name: "prime_auth"
                  root_id: "prime_auth"
                  configuration:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: {}
                  vm_config:
                    runtime: "envoy.wasm.runtime.v8"
                    vm_id: "my_vm_id"
                    code:
                      local:
                        filename: "/etc/myenvoyfilter.wasm"
                    configuration: {}
          - name: envoy.filters.http.router
            typed_config: {}
```

*Logs*:
```
[2021-10-01 21:47:04.318][49][debug][conn_handler] [source/server/active_tcp_listener.cc:332] [C0] new connection from 172.29.0.1:45082
proxy_1        | [2021-10-01 21:47:04.319][49][debug][http] [source/common/http/conn_manager_impl.cc:274] [C0] new stream
proxy_1        | [2021-10-01 21:47:04.319][49][debug][http] [source/common/http/conn_manager_impl.cc:858] [C0][S11407748546514101329] request headers complete (end_stream=false):
proxy_1        | ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | 'content-length', '93'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'content-encoding', 'gzip'
proxy_1        | 
proxy_1        | [2021-10-01 21:47:04.319][49][debug][filter] [source/extensions/filters/http/decompressor/decompressor_filter.cc:84] [C0][S11407748546514101329] DecompressorFilter::decodeHeaders: ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'content-length', '93'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'content-encoding', 'gzip'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', 'ca44261b-733c-4a68-8299-b54b193fef12'
proxy_1        | 
proxy_1        | [2021-10-01 21:47:04.319][49][debug][filter] [./source/extensions/filters/http/decompressor/decompressor_filter.h:178] [C0][S11407748546514101329] do decompress request: ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', 'ca44261b-733c-4a68-8299-b54b193fef12'
proxy_1        | 
proxy_1        | [2021-10-01 21:47:04.319][49][debug][router] [source/common/router/router.cc:444] [C0][S11407748546514101329] cluster 'web_service' match for URL '/anything'
proxy_1        | [2021-10-01 21:47:04.319][49][debug][router] [source/common/router/router.cc:630] [C0][S11407748546514101329] router decoding headers:
proxy_1        | ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', 'ca44261b-733c-4a68-8299-b54b193fef12'
proxy_1        | 'x-envoy-expected-rq-timeout-ms', '15000'
proxy_1        | 
proxy_1        | [2021-10-01 21:47:04.319][49][debug][pool] [source/common/http/conn_pool_base.cc:74] queueing stream due to no available connections
proxy_1        | [2021-10-01 21:47:04.319][49][debug][pool] [source/common/conn_pool/conn_pool_base.cc:245] trying to create new connection
proxy_1        | [2021-10-01 21:47:04.319][49][debug][pool] [source/common/conn_pool/conn_pool_base.cc:143] creating a new connection
proxy_1        | [2021-10-01 21:47:04.319][49][debug][client] [source/common/http/codec_client.cc:60] [C1] connecting
proxy_1        | [2021-10-01 21:47:04.319][49][debug][connection] [source/common/network/connection_impl.cc:864] [C1] connecting to 172.29.0.2:80
proxy_1        | [2021-10-01 21:47:04.319][49][debug][connection] [source/common/network/connection_impl.cc:880] [C1] connection in progress
proxy_1        | [2021-10-01 21:47:04.319][49][debug][filter] [source/extensions/filters/http/decompressor/decompressor_filter.cc:157] [C0][S11407748546514101329] request data decompressed from 93 bytes to 178 bytes
proxy_1        | [2021-10-01 21:47:04.320][49][debug][wasm] [source/extensions/common/wasm/context.cc:1219] wasm log prime_auth prime_auth my_vm_id: on_http_request_body: body_size(178) / end_of_stream: (false)
proxy_1        | [2021-10-01 21:47:04.320][49][debug][http] [source/common/http/filter_manager.cc:825] [C0][S11407748546514101329] request end stream
proxy_1        | [2021-10-01 21:47:04.320][49][debug][filter] [source/extensions/filters/http/decompressor/decompressor_filter.cc:157] [C0][S11407748546514101329] request data decompressed from 0 bytes to 0 bytes
proxy_1        | [2021-10-01 21:47:04.320][49][debug][wasm] [source/extensions/common/wasm/context.cc:1219] wasm log prime_auth prime_auth my_vm_id: on_http_request_body: body_size(178) / end_of_stream: (false)
proxy_1        | [2021-10-01 21:47:04.320][49][debug][connection] [source/common/network/connection_impl.cc:669] [C1] connected
proxy_1        | [2021-10-01 21:47:04.320][49][debug][client] [source/common/http/codec_client.cc:88] [C1] connected
proxy_1        | [2021-10-01 21:47:04.320][49][debug][pool] [source/common/conn_pool/conn_pool_base.cc:289] [C1] attaching to next stream
proxy_1        | [2021-10-01 21:47:04.320][49][debug][pool] [source/common/conn_pool/conn_pool_base.cc:175] [C1] creating stream
proxy_1        | [2021-10-01 21:47:04.320][49][debug][router] [source/common/router/upstream_request.cc:386] [C0][S11407748546514101329] pool ready
```

on_http_request_body is called twice with same argument 178/ false. The second time should be 178/true.

The same request but not gzip encoded

```
[2021-10-01 21:53:24.570][59][debug][conn_handler] [source/server/active_tcp_listener.cc:332] [C0] new connection from 172.29.0.1:47986
proxy_1        | [2021-10-01 21:53:24.570][59][debug][http] [source/common/http/conn_manager_impl.cc:274] [C0] new stream
proxy_1        | [2021-10-01 21:53:24.570][59][debug][http] [source/common/http/conn_manager_impl.cc:858] [C0][S14750111005009089871] request headers complete (end_stream=false):
proxy_1        | ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | 'user-agent', 'Fiddler'
proxy_1        | 'content-length', '178'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 
proxy_1        | [2021-10-01 21:53:24.570][59][debug][filter] [source/extensions/filters/http/decompressor/decompressor_filter.cc:84] [C0][S14750111005009089871] DecompressorFilter::decodeHeaders: ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'content-length', '178'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', '2be982fb-686a-4d40-8501-c3bb94383e63'
proxy_1        | 
proxy_1        | [2021-10-01 21:53:24.570][59][debug][filter] [./source/extensions/filters/http/decompressor/decompressor_filter.h:182] [C0][S14750111005009089871] do not decompress request: ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'content-length', '178'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', '2be982fb-686a-4d40-8501-c3bb94383e63'
proxy_1        | 
proxy_1        | [2021-10-01 21:53:24.571][59][debug][router] [source/common/router/router.cc:444] [C0][S14750111005009089871] cluster 'web_service' match for URL '/anything'
proxy_1        | [2021-10-01 21:53:24.571][59][debug][router] [source/common/router/router.cc:630] [C0][S14750111005009089871] router decoding headers:
proxy_1        | ':authority', 'localhost:18000'
proxy_1        | ':path', '/anything'
proxy_1        | ':method', 'POST'
proxy_1        | ':scheme', 'http'
proxy_1        | 'user-agent', 'Fiddler'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'x-forwarded-proto', 'http'
proxy_1        | 'x-request-id', '2be982fb-686a-4d40-8501-c3bb94383e63'
proxy_1        | 'x-envoy-expected-rq-timeout-ms', '15000'
proxy_1        | 
proxy_1        | [2021-10-01 21:53:24.571][59][debug][pool] [source/common/http/conn_pool_base.cc:74] queueing stream due to no available connections
proxy_1        | [2021-10-01 21:53:24.571][59][debug][pool] [source/common/conn_pool/conn_pool_base.cc:245] trying to create new connection
proxy_1        | [2021-10-01 21:53:24.571][59][debug][pool] [source/common/conn_pool/conn_pool_base.cc:143] creating a new connection
proxy_1        | [2021-10-01 21:53:24.571][59][debug][client] [source/common/http/codec_client.cc:60] [C1] connecting
proxy_1        | [2021-10-01 21:53:24.571][59][debug][connection] [source/common/network/connection_impl.cc:864] [C1] connecting to 172.29.0.2:80
proxy_1        | [2021-10-01 21:53:24.571][59][debug][connection] [source/common/network/connection_impl.cc:880] [C1] connection in progress
proxy_1        | [2021-10-01 21:53:24.571][59][debug][wasm] [source/extensions/common/wasm/context.cc:1219] wasm log prime_auth prime_auth my_vm_id: on_http_request_body: body_size(178) / end_of_stream: (false)
proxy_1        | [2021-10-01 21:53:24.571][59][debug][http] [source/common/http/filter_manager.cc:825] [C0][S14750111005009089871] request end stream
proxy_1        | [2021-10-01 21:53:24.571][59][debug][wasm] [source/extensions/common/wasm/context.cc:1219] wasm log prime_auth prime_auth my_vm_id: on_http_request_body: body_size(178) / end_of_stream: (true)
proxy_1        | [2021-10-01 21:53:24.572][59][debug][connection] [source/common/network/connection_impl.cc:669] [C1] connected
proxy_1        | [2021-10-01 21:53:24.572][59][debug][client] [source/common/http/codec_client.cc:88] [C1] connected
proxy_1        | [2021-10-01 21:53:24.572][59][debug][pool] [source/common/conn_pool/conn_pool_base.cc:289] [C1] attaching to next stream
proxy_1        | [2021-10-01 21:53:24.572][59][debug][pool] [source/common/conn_pool/conn_pool_base.cc:175] [C1] creating stream
proxy_1        | [2021-10-01 21:53:24.572][59][debug][router] [source/common/router/upstream_request.cc:386] [C0][S14750111005009089871] pool ready
proxy_1        | [2021-10-01 21:53:24.575][59][debug][router] [source/common/router/router.cc:1230] [C0][S14750111005009089871] upstream headers complete: end_stream=false
proxy_1        | [2021-10-01 21:53:24.576][59][debug][filter] [source/extensions/filters/http/decompressor/decompressor_filter.cc:117] [C0][S14750111005009089871] DecompressorFilter::encodeHeaders: ':status', '200'
proxy_1        | 'server', 'gunicorn/19.9.0'
proxy_1        | 'date', 'Fri, 01 Oct 2021 21:53:24 GMT'
proxy_1        | 'connection', 'keep-alive'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'access-control-allow-origin', '*'
proxy_1        | 'access-control-allow-credentials', 'true'
proxy_1        | 'x-envoy-upstream-service-time', '3'
proxy_1        | 
proxy_1        | [2021-10-01 21:53:24.576][59][debug][filter] [./source/extensions/filters/http/decompressor/decompressor_filter.h:182] [C0][S14750111005009089871] do not decompress response: ':status', '200'
proxy_1        | 'server', 'gunicorn/19.9.0'
proxy_1        | 'date', 'Fri, 01 Oct 2021 21:53:24 GMT'
proxy_1        | 'connection', 'keep-alive'
proxy_1        | 'content-type', 'application/json'
proxy_1        | 'access-control-allow-origin', '*'
proxy_1        | 'access-control-allow-credentials', 'true'
proxy_1        | 'x-envoy-upstream-service-time', '3'
```

This time, on_http_request_body is called twice two but the second time, end_of_stream is true.
