### ISSUE TITLE
the envoy document has cluster_header,but when config show error?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18386]
*Title*: *One line description*

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.
```
config.route.v3.WeightedCluster.ClusterWeight¶
[config.route.v3.WeightedCluster.ClusterWeight proto]

{
  "name": "...",
  "cluster_header": "...",
  "weight": "{...}",
  "metadata_match": "{...}",
  "request_headers_to_add": [],
  "request_headers_to_remove": [],
  "response_headers_to_add": [],
  "response_headers_to_remove": [],
  "typed_per_filter_config": "{...}",
  "host_rewrite_literal": "..."
}
name
(string) Only one of name and cluster_header may be specified. Name of the upstream cluster. The cluster must exist in the cluster manager configuration.

cluster_header
(string) Only one of name and cluster_header may be specified. Envoy will determine the cluster to route to by reading the value of the HTTP header named by cluster_header from the request headers. If the header is not found or the referenced cluster does not exist, Envoy will return a 404 response.
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        path: /productpage
                        case_sensitive: false
                      route:
                        weighted_clusters:
                          clusters:
                          - cluster_header: upstream_cluster
                            weight: 100
                          total_weight: 100
                          runtime_key_prefix: test
```

```
[root@node01 httpconnectionmanager]# kubectl apply -f ef-route_config-virtual_hosts-routes-route-weighted_clusters-cluster_header.yaml -n istio-system
Warning: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: unknown field "cluster_header" in envoy.config.route.v3.WeightedCluster.ClusterWeight
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
