### ISSUE TITLE
what is the runtime_key? is it customed or fixed?runtime_key: "bogus_key"

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18383]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
redis_proxy fault config
*Description*:
>Describe the issue.
```
faults:
- fault_type: ERROR
  fault_enabled:
    default_value:
      numerator: 10
      denominator: HUNDRED
    runtime_key: "bogus_key"
    commands:
    - GET
  - fault_type: DELAY
    fault_enabled:
      default_value:
        numerator: 10
        denominator: HUNDRED
      runtime_key: "bogus_key"
    delay: 2s
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
