### ISSUE TITLE
document for filter_metadata (repeated map<string, Struct>) is wrong ,not repeated?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18396]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
config.core.v3.Metadata¶
[config.core.v3.Metadata proto]

Metadata provides additional inputs to filters based on matched listeners, filter chains, routes and endpoints. It is structured as a map, usually from filter name (in reverse DNS format) to metadata specific to the filter. Metadata key-values for a filter are merged as connection and request handling occurs, with later values for the same key overriding earlier values.

An example use of metadata is providing additional values to http_connection_manager in the envoy.http_connection_manager.access_log namespace.

Another example use of metadata is to per service config info in cluster metadata, which may get consumed by multiple filters.

For load balancing, Metadata provides a means to subset cluster endpoints. Endpoints have a Metadata object associated and routes contain a Metadata object to match against. There are some well defined metadata used today for this purpose:

{"envoy.lb": {"canary": <bool> }} This indicates the canary status of an endpoint and is also used during header processing (x-envoy-upstream-canary) and for stats purposes.

{
  "filter_metadata": "{...}",
  "typed_filter_metadata": "{...}"
}
filter_metadata
(repeated map<string, Struct>) Key is the reverse DNS filter name, e.g. com.acme.widget. The envoy.* namespace is reserved for Envoy’s built-in filters. If both filter_metadata and typed_filter_metadata fields are present in the metadata with same keys, only typed_filter_metadata field will be parsed.

typed_filter_metadata
(repeated map<string, Any>) Key is the reverse DNS filter name, e.g. com.acme.widget. The envoy.* namespace is reserved for Envoy’s built-in filters. The value is encoded as google.protobuf.Any. If both filter_metadata and typed_filter_metadata fields are present in the metadata with same keys, only typed_filter_metadata field will be parsed.
```
filter_metadata in document is (repeated map<string, Struct>)  but when I add - infront 

```
Resource: "networking.istio.io/v1alpha3, Resource=envoyfilters", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=EnvoyFilter"
Name: "httpconnectionmanager", Namespace: "istio-system"
for: "ef-route_config-virtual_hosts-routes-route-genral.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: json: cannot unmarshal array into Go value of type map[string]json.RawMessage
```
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        prefix: /product
                      route:
                        cluster_not_found_response_code: 404
                        metadata_match:
                          filter_metadata:
                          - "envoy.lb": 
                              canary: true
                        timeout: 10s
                        idle_timeout: 5s
                        priority: HIGH
                        max_stream_duration: 
                          max_stream_duration: 10s
                          grpc_timeout_header_max: 5s
                          grpc_timeout_header_offset: 3s
                        cluster: outbound|9080||productpage.istio.svc.cluster.local
```

if I delete -,it is ok.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        prefix: /product
                      route:
                        cluster_not_found_response_code: 404
                        metadata_match:
                          filter_metadata:
                            "envoy.lb": 
                              canary: true
                        timeout: 10s
                        idle_timeout: 5s
                        priority: HIGH
                        max_stream_duration: 
                          max_stream_duration: 10s
                          grpc_timeout_header_max: 5s
                          grpc_timeout_header_offset: 3s
                        cluster: outbound|9080||productpage.istio.svc.cluster.local
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
