### ISSUE TITLE
I checked config for many times,I think acording the envoy document ,nothing is wrong,bug comamnd show errors?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18422]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scoped_routes:
                  name: test
                  scope_key_builder:
                    fragments:
                    - header_value_extractor:
                        name: X-Header
                        element_separator: ";"
                        index: 0
                        element:
                          separator: "="
                          key: test
                  rds_config_source:
                    ads: {}
                    initialFetchTimeout: 10s
                    resourceApiVersion: V3
                  scoped_route_configurations_list:
                    scoped_route_configurations:
                    - on_demand: true
                      name: test
                      route_configuration_name: http.8080
                      key:
                        fragments:
                          string_key: test
```

```
Resource: "networking.istio.io/v1alpha3, Resource=envoyfilters", GroupVersionKind: "networking.istio.io/v1alpha3, Kind=EnvoyFilter"
Name: "httpconnectionmanager", Namespace: "istio-system"
for: "ef-scoped_routes-scoped_route_configurations_list.yaml": admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager: json: cannot unmarshal object into Go value of type []json.RawMessage
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
