### ISSUE TITLE
SNI-based routing without TLS termination

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#1843]
Pre-read TLS ClientHello and extract requested SNI, which then can be used for routing, blocked on #95.

cc @louiscryan

**Comment by louiscryan** [comment]
@rshriram FYI

Useful for end-to-end mutual TLS where traffic is routed through edge without TLS termination.

**Comment by rshriram** [comment]
Ooh.. interesting.

**Comment by htuch** [comment]
@PiotrSikora can you elaborate for the non-Istio folks? Why is the client in this scenario presenting a ClientHelo if there is no TLS termination?

**Comment by PiotrSikora** [comment]
The idea is that the client establishes TLS connection "directly" with the backend service, without TLS termination at the proxy, i.e. Envoy is simply doing L4 proxying of TCP packets.

However, instead of making routing decisions only based on the listening and/or destination IP:port, we want to take advantage of the fact that the ClientHello (i.e. first message in the TLS handshake) is unencrypted and contains useful information (i.e. ALPN and SNI) to make routing decisions based on that as well.

e.g.

    "listeners": [
      {
        "address": "tcp://0.0.0.0:443",
        "filters": [
          {
            "name": "tcp_proxy",
            "config": {
              "stat_prefix": "smart_tcp",
              "route_config": {
                "routes": [
                  {
                    "domains": [ "google.com", "*.google.com" ],
                    "cluster": "service_google"
                  },
                  {
                    "domains": [ "*.appspot.com" ],
                    "cluster": "service_app_engine"
                  }
                ]
              }
            }
          }
        ]
      }
    ]

In such scenario, neither the client nor the backend has to trust the proxy, which at this point is just another hop.

**Comment by htuch** [comment]
Yes, this makes sense. Our team also has a need for being able to interpret the initial TCP stream prefix when proxying to extract out additional info, we should sync about this.

**Comment by vadimeisenbergibm** [comment]
@PiotrSikora @mattklein123 any estimation when this feature will be implemented?

**Comment by PiotrSikora** [comment]
@vadimeisenbergibm I'm working on tests for this right now, PR should be out "soon".

**Comment by vadimeisenbergibm** [comment]
@PiotrSikora glad to hear it, good news!

**Comment by evantorrie** [comment]
Also interested in this

**Comment by sureshvis** [comment]
very much interested. We do this today using Apache Traffic Server proxy.

**Comment by mastersingh24** [comment]
@PiotrSikora  - are you planning on supporting both SNI and ALPN?

**Comment by PiotrSikora** [comment]
@mastersingh24 both SNI and ALPN are extracted from the `ClientHello` and available to filters and filter chain selector, but the code I have right now doesn't make decisions based on ALPN.

**Comment by PiotrSikora** [comment]
Sorry, I've got side-tracked with unrelated bug hunting, but I've started working on this again today, so the PR should be out "soon" (the code for this & the rewrite of filter match selection logic has been completed for a while, but I'm still missing a few tests).

**Comment by gtie** [comment]
:+1: :eyes:

**Comment by davidamin** [comment]
Is there an example configuration for this functionality available? I found a config at [How to setup SNI](https://www.envoyproxy.io/docs/envoy/latest/faq/sni#faq-how-to-setup-sni) but it includes a `tls_context` in each match, is it possible to do the routing without that configured?

**Comment by PiotrSikora** [comment]
@davidamin yes, just remove `tls_context`.

**Comment by tortuoise** [comment]
I could do with a little help with the setup for SNI based routing without TLS termination. I've got the SNI setup working with the TLS termination but can't get the tcp_proxy filter to work for sni routing without tls termination. 

This config seems to work for SNI routing (though oddly I can only use it with v2.HttpConnectionManager and not v3) :
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names: ["www.example.com"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext  
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: "/etc/envoy/www-crt.pem" }
              private_key: { filename: "/etc/envoy/www-key.pem" }
      filters:
      - name: envoy.filters.network.http_connection_manager # envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager 
         stat_prefix: ingress_http
         access_log:
          - name: envoy.file_access_log
            config:
              path: "/var/log/envoy_access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/" }
                route: { cluster: service1 }
          http_filters:
          - name: envoy.router
    - filter_chain_match:
        server_names: ["api.example.com"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext  
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: "/etc/envoy/api-crt.pem" }
              private_key: { filename: "/etc/envoy/api-key.pem" }
      filters:
      - name: envoy.filters.network.http_connection_manager # envoy.http_connection_manager 
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager           
          stat_prefix: ingress_http
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/var/log/envoy_access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/" }
                route: { cluster: service2 }
          http_filters:
          - name: envoy.router
    - filter_chain_match:
  
  clusters:
  - name: service1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service1
                port_value: 8000
   - name: service2
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    #http2_protocol_options: {}
    load_assignment:
      cluster_name: service2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service2
                port_value: 8000
admin:
  access_log_path: "/var/log/envoy_admin.log" 
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

But what's wrong with the below additions to the config?

```
....
- filter_chain_match:
        server_names: ["sub.example.com"]
  filters:
      - name: envoy.filters.network.tcp_proxy 
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: passthrough
          
 clusters:
...
  - name: passthrough
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: passthrough
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: passthrough
                port_value: 8000
...
```
The existing filter_chain_matches still work but the new one doesn't. The envoy access log seems to route the connection properly but https clients report the connection as being reset.  
```
[2020-05-26T15:54:55.128Z] "- - -" 0 UF,URX 0 0 0 - "-" "-" "-" "-" "172.18.0.6:8000"
```
