### ISSUE TITLE
Filter matching on metadata

### ISSUE THREAD

**Issue by bnadim** [envoyproxy/envoy#18581]
*Title*: *Use metadata in the filter matching mechanism*

*Description*:
Some filters allow to store data as a metadata but we can not do filtering on the metadata.
It would greatly help to filter by metadata. 
To go further, it could be a standard mechanism to filter metadata for example for domain filtering when reading sni.

**Comment by gregbanks** [comment]
@bnadim I was recently looking into this as well (also in the context of the proxy protocol headers that can be enabled on GCP, AWS, and Azure) and came up with the following:

```
!ignore dynamic_sockets:
- &admin_address {address: 127.0.0.1, port_value: 9901}
- &pong_listener_address {address: 127.0.0.1, port_value: 6666}
- &pong_upstream_address {address: 127.0.0.1, port_value: 6667}

static_resources:
  listeners:
  - name: pong_listener
    address:
      socket_address: *pong_listener_address
    listener_filters:
    - name: downstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
        rules:
        - tlv_type: 5
          on_tlv_present:
            key: uuid
    - name: downstream_tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        server_names: ["pong.foobar.com", "pong1.foobar.com"]
        transport_protocol: tls
      filters:
      - name: downstream_rbac
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          stat_prefix: downstream_rbac_stats
          rules:
            action: ALLOW
            policies:
              "uuid":
                permissions:
                - requested_server_name:
                    exact: "pong.foobar.com"
                principals:
                - metadata:
                    filter: envoy.filters.listener.proxy_protocol
                    path:
                    - key: uuid
                    value:
                      string_match:
                        exact: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"
          enforcement_type: ONE_TIME_ON_FIRST_BYTE
      - name: downstream_tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: downstream_tcp_proxy_stats
          cluster: pong_cluster
  clusters:
  - name: pong_cluster
    type: STATIC
    transport_socket:
      name: upstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config: 
          version: V2
        transport_socket:
          name: upstream_raw_buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
    load_assignment:
      cluster_name: pong_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: *pong_upstream_address



admin:
  address:
    socket_address: *admin_address
```

Note, this has been tested and works to filter out connections to `pong.foobar.com` that do not include the expected UUID (`00000000-0000-0000-0000-000000000001`).

I'm not sure if this is quite what you're looking for, but may be a work around in the immediate future at least.
