### ISSUE TITLE
documentation update: envoy compressor filter

### ISSUE THREAD

**Issue by jgournet** [envoyproxy/envoy#18634]
*Title*: *documentation update: envoy compressor filter*

*Description*:
Documentation here:
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/compressor_filter
states:
```
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
        memory_level: 3
        window_bits: 10
        compression_level: best_compression
        compression_strategy: default_strategy
```

While Gzip compressor extension: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/compression/gzip/compressor/v3/gzip.proto
stays that it should be "BEST_COMPRESSION" and "DEFAULT_STRATEGY"

Not the end of the world, but took me a bit of time finding why I was getting this error:
```
admission webhook "validation.istio.io" denied the request: configuration is invalid: Envoy filter: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip: unknown value "\"default_strategy\"" for enum envoy.extensions.compression.gzip.compressor.v3.Gzip.CompressionStrategy
```
