### ISSUE TITLE
scoped_routes not effective?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#18655]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scoped_routes:
                  name: test
                  scope_key_builder:
                    fragments:
                    - header_value_extractor:
                        name: X-Header
                        element_separator: ";"
                        index: 0
                        element:
                          separator: "="
                          key: test
                  rds_config_source:
                    ads: {}
                    initialFetchTimeout: 10s
                    resourceApiVersion: V3
                  scoped_route_configurations_list:
                    scoped_route_configurations:
                    - on_demand: true
                      name: test1
                      route_configuration_name: "http.8080"
                      key:
                        fragments:
                        - string_key: test1
                    - on_demand: true
                      name: test2
                      route_configuration_name: "http.8081"
                      key:
                        fragments:
                        - string_key: test2
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.on_demand
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
```
I have http.8080 route ,but return 404

```
[root@node01 ~]# curl http://192.168.229.134:32406/productpage -H "X-Header: test=test1" -I
HTTP/1.1 404 Not Found
date: Sun, 17 Oct 2021 07:17:00 GMT
server: istio-envoy
transfer-encoding: chunked
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
