### ISSUE TITLE
[Question] Header-To-Metadata Filter and dynamic_metadata route matching

### ISSUE THREAD

**Issue by systemtrap** [envoyproxy/envoy#18680]
*Header-To-Metadata Filter and dynamic_metadata route matching*: *How to route based on dynamic metadata*

*Description*:
> I'm trying to route to different clusters depending on a cookie sent by the downstream host. I'm able to extract the cookie value as I can see it in the access log with `%DYNAMIC_METADATA(cx:dev)%`. I can't get the route match with dynamic_metadata to work as all requests are sent to the cluster `UI`. What piece of the puzzle am I missing here? Is there a better way to make a routing decision based on a cookie?

```
              http_filters:
                - name: envoy.filters.http.header_to_metadata
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
                    request_rules:
                    - cookie: `
                      on_header_present:
                        metadata_namespace: cx
                        key: dev
                        type: STRING
                      on_header_missing:
                        metadata_namespace: cx
                        key: dev
                        value: nodev
                        type: STRING
                      remove: false
                - name: envoy.filters.http.router
              route_config:
                name: local_route
                virtual_hosts:
                  - name: backend
                    domains:
                      - '*'
                    routes:
                      - match:
                          prefix: /
                          dynamic_metadata:
                          - filter: cx
                            path:
                            - key: dev
                            value:
                              string_match:
                                exact: dev
                        route:
                          cluster: DEV
                      - match:
                          prefix: /
                        route:
                          cluster: UI
```
