### ISSUE TITLE
AWS Request Signing Filter breaks for internal requests if x-envoy-retry-on is set

### ISSUE THREAD

**Issue by wbertelsen** [envoyproxy/envoy#18695]
*Title*: 
The [AWS Request Signing Filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter) breaks for internal requests if the `x-envoy-retry-on` header is set

*Description*:
For requests marked by envoy as "internal", if the `x-envoy-retry-on` header is set to any value, such as `x-envoy-retry-on: 5xx`, the aws request signing filter signs the request using `x-envoy-retry-on:` but the router makes the request with this header missing. This causes signature validation to fail with a `The request signature we calculated does not match the signature you provided. Check your key and signing method.` error

*Repro steps*:
To repro, run envoy with the config below and make sure you have your AWS credential env vars set correctly.
```
export AWS_ACCESS_KEY_ID=<inset>
export AWS_SECRET_ACCESS_KEY=<insert>
export AWS_SESSION_TOKEN=<insert if needed>
envoy --config-path  ./envoy-repro.yaml
```
Then, demonstrate that request signing works correctly without the `x-envoy-retry-on` header
```
curl  localhost:4141/ # this lists buckets successfully as long as you have the right iam permissions
```
Finally, repro the issue by adding the header
```
curl  --header "x-envoy-retry-on: 5xx"  localhost:4141/ # This should respond with an error and the correct string to sign
```

*Config*:
```yaml
static_resources:
  listeners:
    - name: example
      address:
        socket_address: { address: 127.0.0.1, port_value: 4141 }
      traffic_direction: OUTBOUND
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: example
                codec_type: auto
                route_config:
                  name: sts
                  virtual_hosts:
                    - name: sts
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: example } 
                use_remote_address: true # This marks requests as 'internal' and is required to repro this issue
                http_filters:
                  - name: sigv4-signing
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
                      service_name: s3
                      host_rewrite: s3.amazonaws.com
                      region: us-east-1
                      use_unsigned_payload: true
                  - name: envoy.filters.http.router
  clusters:
    - name: example
      type: STRICT_DNS
      connect_timeout: 0.250s
# BEGIN TAP CONFIG - this is useful for debugging this issue but not required to repro      
      transport_socket:
        name: envoy.transport_sockets.tap
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
          common_config:
            static_config:
              match_config:
                any_match: true
              output_config:
                max_buffered_tx_bytes: 1000000
                max_buffered_rx_bytes: 1000000
                sinks:
                  - format: JSON_BODY_AS_STRING
                    file_per_tap:
                      path_prefix: /var/log/envoy/tap/json_tap
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
# END TAP CONFIG
      load_assignment:
        cluster_name: s3
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: s3.amazonaws.com
                      port_value: 443
```
