### ISSUE TITLE
How to set rate limitation for multiple client IPs

### ISSUE THREAD

**Issue by triThirty** [envoyproxy/envoy#18706]
*How to set rate limitation for multiple client IPs?*

*Description*:
> I use `remote_address` action against descriptor to rate limit one specific client IP perfectly. But if I want to rate limit several client IPs, how should I do?

My config looks this:
```YAML
rate_limits:
   - actions:
   - remote_address: {}
---
descriptors:
  - entries:
  - key: remote_address
    value: "172.23.0.1"
  token_bucket:
    max_tokens: 1
    tokens_per_fill: 1
    fill_interval: 60s
```
It works fine, and for client IP `172.23.0.1`, it can only request 1 time per minute. But if I have a bunch of IPs which I want to rate limit, because I suspect these IPs are attacking my service, in this scenario, what should I do? 

Thanks
