### ISSUE TITLE
Set rate limit for virtual hosts, but descriptors doesn't work

### ISSUE THREAD

**Issue by triThirty** [envoyproxy/envoy#18807]
*Set rate limit for virtual hosts, but descriptors doesn't work*

*Description*:

Referring this https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualhost doc. I believe that virtual_hosts suppots rate_limit, and I write my config, but the descriptors doesn't work.
This is what my config looks like:
```YAML
resources:
  - name: test_route
    "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    virtual_hosts:
      - name: local_service
        "@type": type.googleapis.com/envoy.config.route.v3.VirtualHost
        domains:
          - "*"
        routes:
          - match:
              prefix: "/aaa"
            route:
              cluster: example_proxy_cluster
          - match:
              prefix: "/test"
            route:
              cluster: example_proxy_cluster
        rate_limits:
          - actions: # any actions in here
              - request_headers:
                  header_name: ":path"
                  descriptor_key: path
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            stat_prefix: rate_limit
            token_bucket:
              max_tokens: 1
              tokens_per_fill: 1
              fill_interval: 60s
            filter_enabled:
              runtime_key: route2_limit_enabled
              default_value:
                numerator: 100
                denominator: HUNDRED
            filter_enforced:
              runtime_key: route2_limit_enforced
              default_value:
                numerator: 100
                denominator: HUNDRED
            descriptors:
              - entries:
                  - key: path
                    value: /test
                token_bucket:
                  max_tokens: 9999999
                  tokens_per_fill: 9999999
                  fill_interval: 60s
```
When I `curl localhost:10000/test` several time, and get 429 which means descriptors doesn't override the token_bucket.
Is there anything I missed?
