### ISSUE TITLE
Routing for dynamic forward proxy

### ISSUE THREAD

**Issue by kellerkind84** [envoyproxy/envoy#18822]
Hi everyone,

so I'm trying to use envoy as an mTLS sidecar. However, I do not think I can use the double proxy example in the sandboxes, since the other side is not done by me. Also, I'm trying to achieve something where I can actually use envoy in a "https_proxy" setup, instead of having envoy do the routing itself. I would also like to have the ability to manipulate the headers at any point. So what I came up with was the dynamic forward proxy, however it does not seem to work the way I want it to. I hope you can help me.

First of, I'm using the envoy docker image `envoyproxy/envoy-dev:8cf8121300f63a3a8b93e57723c5c57b636ead23`. I have tried a ton of different configurations and routes. My biggest problem is that most routes simply do not seem to work. The only one that seems to work without fail is the connect_matcher, which according to the logs seems to connect to the remote https host perfectly. However, in my understanding this is wrong, since every request should be routed, not only the connect request. I can't get any other request to work though... So since this connect seems to work and the dns resolution seems to work too, I think the tls transport socket is ok (even though I get an error after the connect that the tls version is wrong), and the request routing is wrong. Here is my config (with replaced hostname etc):

```
apiVersion: v1
admin:
address:
socket_address:
  address: 0.0.0.0
  port_value: 9901

static_resources:

listeners:
- name: listener_0
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 10000
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains:
              - "remote.host"
              - "remote.host:80"
              - "remote.host:443"
            routes:
            - match:
                prefix: "/force-host-rewrite"
              route:
                cluster: my_cluster
              typed_per_filter_config:
                envoy.filters.http.dynamic_forward_proxy:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                  host_rewrite_literal: remote.host
            - match:
                prefix: "/"
              route:
                cluster: my_cluster
            - match:
                connect_matcher:
                  {}
              route:
                cluster: my_cluster
                upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
      http_filters:
      - name: envoy.filters.http.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
            typed_dns_resolver_config:
              name: envoy.network.dns_resolver.cares
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                resolvers:
                - socket_address:
                    address: "10.0.0.10"
                    port_value: 53
                dns_resolver_options:
                  use_tcp_for_dns_lookups: true
                  no_default_search_domain: true
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          upstream_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog


clusters:
- name: my_cluster
  connect_timeout: 1s
  lb_policy: CLUSTER_PROVIDED
  cluster_type:
    name: envoy.clusters.dynamic_forward_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
      dns_cache_config:
        name: dynamic_forward_proxy_cache_config
        dns_lookup_family: V4_ONLY
        typed_dns_resolver_config:
          name: envoy.network.dns_resolver.cares
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
            resolvers:
            - socket_address:
                address: "10.0.0.10"
                port_value: 53
            dns_resolver_options:
              use_tcp_for_dns_lookups: true
              no_default_search_domain: true
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      sni: remote.host
      allow_renegotiation: true
      common_tls_context:
        tls_certificates:
          - certificate_chain:
              filename: /cert/certificatechain.pem
            private_key:
              filename: /cert/client-key.pem
        validation_context:
          match_subject_alt_names:
            - exact: remote.host
          trusted_ca:
            filename: /etc/ssl/certs/ca-certificates.crt
```

I try to curl this with `https_proxy=http://localhost:10000 curl -v -L  'https://remote.host/restoftheurl'`.
DNS resolution works according to the logs, I also get an initial 200 for the connect. Please let me know what I'm doing wrong. At the moment the only thing I can think of is that my approach does not work at all.
