### ISSUE TITLE
Weighted load balancing behavior within a locality

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#18836]
Hi community,

Within a locality, I'm trying to use [load_balancing_weight](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-lbendpoint) to send 50% traffic to service_1 and 50% traffic to service_2. 
service_1 has 2 IPs behind it and service_2 has 1 IP behind it. I expect 50% traffic goes to IP3, 25% traffic goes it IP1 and IP2. From the metrics of service_1 and service_2, it seems the actual traffic distribution is 3 * 33.3%. Is this the expected behavior? Thanks. I'm on envoy 1.18.3

```
...
      endpoints:
        - lb_endpoints:
          - load_balancing_weight: 50
            endpoint:
              address:
                socket_address:
                  address: service_1         <--------------------------------------- 2 ips behind it, IP1, IP2
                  port_value: 80
          - load_balancing_weight: 50
            endpoint:
              address:
                socket_address:
                  address: service_2        <--------------------------------------- 1 ip behind it, IP3
                  port_value: 80
...
```
