### ISSUE TITLE
source tcp tunneling host name from SNI

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#18838]
Source host name from SNI for tcp tunneling

*Description*:
We have a scenario to dynamically connect using SNI for tcp tunneling https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#extensions-filters-network-tcp-proxy-v3-tcpproxy-tunnelingconfig

Can this host_name be made dynamic and sourced from SNI?

**Comment by ramaraochavali** [comment]
@alyssawilk @mattklein123 WDYT?

**Comment by mattklein123** [comment]
Isn't this what https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter does?

**Comment by ramaraochavali** [comment]
So the `envoy.filters.network.sni_dynamic_forward_proxy` filters sets the tunneling config host that is used by below
```
      - name: envoy.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          cluster: dynamic_forward_proxy_cluster
          
```
?

**Comment by mattklein123** [comment]
Not sure about that part. Maybe @alyssawilk will know otherwise I would need to look at the code.

**Comment by lambdai** [comment]
I think the missing piece is to support evaluation in the tunnel config. 
Can anyone reopen https://github.com/envoyproxy/envoy/issues/18128 ?

**Comment by ramaraochavali** [comment]
@lambdai Yes. That is the missing piece

**Comment by ramaraochavali** [comment]
https://github.com/envoyproxy/envoy/pull/18858 - This closes this also.

**Comment by ramaraochavali** [comment]
Chatted with @lambdai  and he confirmed that host can be overwritten like this
```
          tunneling_config:
            headers_to_add:
            - header:
                key: :host
                value: "%REQUESTED_SERVER_NAME%"
              append_action: OVERWRITE_IF_EXISTS_OR_ADD
```
Thank you @lambdai for confirming this. 
So closing this issue.

**Comment by pxpnetworks** [comment]
Hello,
i was wondering then what about this snippet from the docs about tunneling config regarding the :host header:
""Neither :-prefixed pseudo-headers nor the Host: header can be overridden.""" @lambdai @ramaraochavali ??

**Comment by ramaraochavali** [comment]
@pxpnetworks  With append action `OVERWRITE_IF_EXISTS_OR_ADD ` it should be possible. See https://github.com/envoyproxy/envoy/issues/18838#issuecomment-966000729

**Comment by scrocquesel** [comment]
@ramaraochavali using the envoyproxy/envoy-dev:latest image, 

```
tunneling_config:
            headers_to_add:
            - header:
                key: :host
                value: "%REQUESTED_SERVER_NAME%"
              append_action: OVERWRITE_IF_EXISTS_OR_ADD
```

fails with 
```
Proto constraint validation failed (TcpProxyValidationError.TunnelingConfig: embedded message failed validation | caused by TunnelingConfigValidationError.Hostname: value length must be at least 1 characters)
```

Adding a dummy value for hostname, fails with 

```
error initializing configuration '/etc/envoy.yaml': :-prefixed or host headers may not be modified
```
