### ISSUE TITLE
Envoy returns status 200 while it's configured to return 503 immediately

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#18835]
Hi community,
I have a server that does nothing but just returns custom responses. I noticed in the below example, while I configure envoy to return 503, the status code in the response is 200 and the grpc-status code is 14.
The client then got confused when they look at the metric `envoy_cluster_upstream_rq`, because all response codes were 200. 

Question:
- is the server behavior expected? is there a way to ask it to return 503 in the response so that client can be aware?
- on the client side, is there any other way to know the actual response code is 503 or 14? Do they have to use [grpc_stats filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_stats_filter)?
Could anyone please kindly give me some hints?

server configuration:
```
resources:
  # inbound listener
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_inbound
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 16000
    traffic_direction: INBOUND
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: ingress
                virtual_hosts:
                  - name: ingress
                    domains:
                      - "*"
                    routes:
                      - match:
                          prefix: "/"
                        direct_response:
                          status: 503
                          body:
                            inline_string: "{'message': 'FAILURE INJECTOIN!'}"
              http_filters:
                - name: envoy.filters.http.router
```

When I enable the debug mode on the server, the response is 
```
':status', '200'
'content-type', 'application/grpc'
'grpc-status', '14'
'grpc-message', '{'message': 'FAILURE INJECTOIN!'}'
'date', 'Sat, 30 Oct 2021 03:12:53 GMT'
'server', 'envoy'
```

client configuration:
```
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: egress_service
    type: STRICT_DNS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    connect_timeout: 100s
    load_assignment:
      cluster_name: egress_service
      endpoints:
        - lb_endpoints:
            - load_balancing_weight: 100
              endpoint:
                address:
                  socket_address:
                    address: egress_service
                    port_value: 80
```
