### ISSUE TITLE
Is the order of `virtual_hosts` important for domain matching?

### ISSUE THREAD

**Issue by thesuperzapper** [envoyproxy/envoy#18874]
There is some [confusion in the Istio community](https://github.com/istio/istio/issues/35826#issuecomment-957184380) about if the ordering of `virtual_hosts` in a [config.route.v3.RouteConfiguration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#config-route-v3-routeconfiguration) will affect which route is matched. 

While the [envoy docs are clear that `route` is matched __in-order__](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/route_matching), it's unclear about if the ordering of `virtual_hosts` will affect the order of `domain` matches.

__I only see two possibilities:__

1. Envoy matches the request _host_ header against each  `virtual_host` by `domain` in-order
    - (meaning if the first `virtual_host` has a wildcard subdomain, any later specific subdomains will be effectively shadowed by the wildcard)
1. Envoy matches the request _host_ header by using the `virtual_host` with the most precise `domain` match

__Example:__

What happens to traffic destined to `http://app1.example.com`, does it end up at `outbound|80||app2.default.svc.cluster.local` or `outbound|80||app1.default.svc.cluster.local`?

```yaml
- name: http.80
  validateClusters: false
  virtualHosts:
    - domains:
        - '*.example.com'
        - '*.example.com:80'
      includeRequestAttemptCount: true
      name: '*.example.com:80'
      routes:
        - decorator:
            operation: app2.default.svc.cluster.local:80/*
          match:
            prefix: /
          metadata:
            filterMetadata:
              istio:
                config: /apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/app2
          route:
            cluster: outbound|80||app2.default.svc.cluster.local
            maxGrpcTimeout: 0s
            retryPolicy:
              hostSelectionRetryMaxAttempts: "5"
              numRetries: 2
              retriableStatusCodes:
                - 503
              retryHostPredicate:
                - name: envoy.retry_host_predicates.previous_hosts
              retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
            timeout: 0s
    - domains:
        - app1.example.com
        - app1.example.com:*
      includeRequestAttemptCount: true
      name: app1.example.com:80
      routes:
        - decorator:
            operation: app1.default.svc.cluster.local:80/*
          match:
            prefix: /
          metadata:
            filterMetadata:
              istio:
                config: /apis/networking.istio.io/v1alpha3/namespaces/default/virtual-service/app1
          route:
            cluster: outbound|80||app1.default.svc.cluster.local
            maxGrpcTimeout: 0s
            retryPolicy:
              hostSelectionRetryMaxAttempts: "5"
              numRetries: 2
              retriableStatusCodes:
                - 503
              retryHostPredicate:
                - name: envoy.retry_host_predicates.previous_hosts
              retryOn: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
            timeout: 0s
```
