### ISSUE TITLE
Pass through Proxy Protocol TLVs to upstream

### ISSUE THREAD

**Issue by visualzhou** [envoyproxy/envoy#18940]
*Title*: *Pass through Proxy Protocol TLVs to upstream*

*Description*:
For our purposes, we need to consume the data present in the Proxy Protocol V2 header TLVs in an upstream service (e.g., we want to announce the UUID provided for connections through a VPC endpoint service in AWS [3]). As such, we have implemented a POC to pass through the TLVs, allowing reconstruction on the upstream Proxy Protocol network filter, by adding a member that captures these to the `ProxyProtocolData` struct that we populate in the listener filter [5] and then reconstruct in the network filter [6]. If this sounds right, we would additionally add another field to the `ProxyProtocol`  message [7] to indicate that the values should be parsed and passed through in the YAML configuration. 

We are happy to contribute in a PR. I realized #18520 is related, but it seems to be about generating new TLVs rather than passing through TLVs from downstream to upstream, so I'm filing a new issue.
 
Questions:
- Is this on the road map or is this already being worked on?
- Does this sound like a reasonable addition and/or is there another way that it should be accomplished?
- Any suggestions on the YAML configuration for this feature?
 
Thanks!
 
Cheers,
Siyuan
 
*Relevant Links*:
[1] [Issue: Extract TLVs from Proxy Protocol v2 and save it in dynamic metadata to be consumed by other filters](https://github.com/envoyproxy/envoy/issues/11336)
[2] [PR: Extract TLVs from Proxy Protocol v2 and emit to dynamic metadata](https://github.com/envoyproxy/envoy/pull/11488)
[3] [AWS Proxy Protocol](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#proxy-protocol)
[4] [ProxyProtocolData](https://github.com/envoyproxy/envoy/blob/94153b4413413bd18d6708e21d04a0ee9b75f467/envoy/network/proxy_protocol.h)
[5] [Proxy Protocol Listener Filter](https://github.com/envoyproxy/envoy/blob/94153b4413413bd18d6708e21d04a0ee9b75f467/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc#L108)
[6] [Proxy Protocol Network Filter](https://github.com/envoyproxy/envoy/blob/94153b4413413bd18d6708e21d04a0ee9b75f467/source/extensions/transport_sockets/proxy_protocol/proxy_protocol.cc#L72)
[7] [proxy_protocol.proto](https://github.com/envoyproxy/envoy/blob/aac113ecae73f18b8ed50a918c81505da65108a1/api/envoy/extensions/filters/listener/proxy_protocol/v3/proxy_protocol.proto#L17)

**Comment by alyssawilk** [comment]
Passing through proxy proto extensions seems reasonable. 

I assume for config we'd do something like having a shared message for TLVs where the listener would save TLVs based on config, and the cluster would emit TLVs based on config, and if you configured the same ones on both ends, all would be passed through?  That's more of an @envoyproxy/api-shepherds question though :-)

**Comment by visualzhou** [comment]
Thank you @alyssawilk ! I'll go ahead to prepare a PR, while we are figuring out the config format.

I like the idea of separating the configs for listener and cluster. To make it more concrete, here is an example config to pass through all TLV types.
```
# On the listener side:
    listener_filters:
    - name: downstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
        rules: []
        pass_through_tlvs:          #   <-----
        - filter_type: include_all

...

# On the cluster side:
    transport_socket:
      name: upstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config: 
          version: V2
        pass_through_tlvs:          #   <-----
        - filter_type: include_all
        transport_socket:
          name: upstream_raw_buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer

```
The two `pass_through_tlvs` sections indicates that we'd like to save and emit all TLVs. Besides `include_all`, its filter type would be expanded to `include` and `exclude` in the future, like the following. `tlv_types` has to be missing when `include_all` is specified.
```
        pass_through_tlvs:
        - filter_type: [include_all|include|exclude]
        - tlv_types:
                - 5   # UUID
                - 234 # PP2_TYPE_AWS (0xEA) for the ID of the private link endpoint
```
I plan to only support `include_all` in the PR, while making sure it's compatible for future extension, when there turns out to be more use cases.
