### ISSUE TITLE
[Oauth] Add Custom Parameters to Oauth2 Filter

### ISSUE THREAD

**Issue by joberdick-rcd** [envoyproxy/envoy#18980]
*Title*: Add Custom Parameters to Oauth2 Filter

*Description*:
Many identity providers have attributes with oauth that the filter does not support today. 

It seems that 'resources' option is attempt to cover what API a token is to be request for. The Oauth RFC doesn't actually dictate that other values can't be used. 

For example Auth0 does not use 'resources' but instead 'audience'. 

I can use the following lua to work around the issue currently:
```
function envoy_on_response(response_handle)
              if (response_handle:headers():get("location") ~= nil and response_handle:headers():get("location"):sub(1,39) == "https://your-idp.com/authorize") then
                location = response_handle:headers():get("location")
                response_handle:headers():replace("location", (location .. "&audience=some-api"))
                response_handle:logErr(location)
              end
            end
```
Instead of requesting that audience be added. I think it makes sense to allow any number of custom attributes be added to avoid more additions in the future.

**Comment by joberdick-rcd** [comment]
Hi @rojkov, is this issue still valid? Do I need to clarify anything?

**Comment by rojkov** [comment]
I'm not an expert in oauth, but the issue sounds legit. It seems all the devs are just too busy with other tasks. Would you like to submit a patch?

**Comment by carnei-ro** [comment]
Thanks for sharing the EnvoyFilter! Auth0 still needs “audience”. I thinks this issue should be reopened!

**Comment by carnei-ro** [comment]
At Auth0 it is possible to set the "Default Audience" at "(Tenant) Settings" > "General" tab >  "API Authorization Settings";

If you're requesting a 'non-default' audience, probably you need the EnvoyFilter.

Customize the vars `authorization_endpoint` and `audience` for what makes sense to you;

```yaml
apiVersion: networking.istio.io/v1beta1
kind: EnvoyFilter
metadata:
  name: oauth2-add-audience-to-authorization-endpoint
spec:
  workloadSelector:
    labels:
      app: my-app
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: oauth2-add-audience-to-authorization-endpoint.lua
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
            inlineCode: |
              local authorization_endpoint = "https://dev-abcdef0123456789.us.auth0.com/authorize"
              local audience = "https://my-aud.carnei.ro"

              function envoy_on_response(response_handle)
                if (response_handle:headers():get("location") ~= nil and response_handle:headers():get("location"):sub(1,#authorization_endpoint) == authorization_endpoint) then
                  location = response_handle:headers():get("location")
                  response_handle:headers():replace("location", (location .. "&audience="..audience))
                  response_handle:logErr(location)
                end
              end
```

**Comment by arkodg** [comment]
this issue can we worked around by appending the `audience` param to the URL
```
authorizationEndpoint: "https://example.xx.auth0.com/authorize?audience=https://api.example.com"
```

relates to https://github.com/envoyproxy/gateway/issues/5133#issuecomment-2620173656

**Comment by mnpenner** [comment]
For anyone else trying to figure out where to put that,

```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
spec:
  oidc:
    provider:
      issuer: https://accounts.google.com
      authorizationEndpoint: "https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account"
```

Seems to work. I wanted to force the account switcher with Google per https://stackoverflow.com/a/14393492/65387
