### ISSUE TITLE
envoy ALS cluster definition in bootstrap configuration

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#19001]
hello, I'm trying to config envoy als with istio envoyfilter, the yaml looks like:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: mantis-centralgateway-als
  namespace: {{ .Release.Namespace }}
spec:
  workloadSelector:
    labels:
      app: mantis-centralgateway
  configPatches:
  - applyTo: NETWORK_FILTER # 添加 HttpGrpcAccessLogConfig
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          access_log:
          - name: envoy.access_loggers.http_grpc
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig"
              common_config: 
                log_name: "http_envoy_accesslog"
                grpc_service: 
                  envoy_grpc: 
                    cluster_name: "outbound|14250||otel-collector.monitoring.svc.cluster.local"
                filter_state_objects_to_log:
                - wasm.upstream_peer
                - wasm.upstream_peer_id
                - wasm.downstream_peer
                - wasm.downstream_peer_id
```

then got some error:
```
2021-11-15T19:57:58.578360Z	16 warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 172.16.0.187_8080: gRPC client cluster 'outbound|14250||otel-collector.monitoring.svc.cluster.local' is not static
```

why should ALS be static? is there any specific reason?
