### ISSUE TITLE
[Feature] PROXY protocol for UDP protocol

### ISSUE THREAD

**Issue by maksim-paskal** [envoyproxy/envoy#19004]
We use network load balancers for testing our HTTP/3 workloads on our edge proxy. We need to use PROXY protocol on network load balancers for getting client IP - but using UDP protocol now it's imposible to add `proxy_protocol` filter to `listener_filters` (current implementation of `envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol` can be used only on TCP protocol)

I want to use PROXY protocol in HTTP/3 - it will be awesome that current filter can be used in UDP prococol - for example:

```yaml
...
- name: listener_udp
  address:
    socket_address:
      protocol: UDP
      address: 0.0.0.0
      port_value: 10000
  listener_filters:
  - name: envoy.filters.listener.proxy_protocol
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
  udp_listener_config:
    quic_options: {}
    downstream_socket_config:
      prefer_gro: true
...
```
