### ISSUE TITLE
New TCP connection pool enforcing max_requests

### ISSUE THREAD

**Issue by aminjam** [envoyproxy/envoy#19033]
*Title*: New TCP connection pool is not respecting max_connections for circuit-breaker's thresholds

*Description*:
After upgrading to envoy 1.19 we've been unable to serve more than 1024 downstream TCP connections. This seems to be coming from the new TCP connection pool. We've been able to mitigate this issue by using the older TCP connection pool.

*Repro steps*:
A detailed repro steps can be found in this gist: https://gist.github.com/aminjam/673aa9a4ed84f018febd7d95d9784bf0

*Admin and Stats Output*:
N/A

*Config*:
In summary, the following config.yaml will fail to serve more than 1024 connections as of envoy 1.19

```
node:
  cluster: proxy-cluster
  id: my-cluster
static_resources:
  secrets:
    - name: server_cert
      tls_certificate:
        certificate_chain:
          filename: certs/server.crt
        private_key:
          filename: certs/server.key
    - name: validation_context
      validation_context:
        trusted_ca:
          filename: certs/ca.crt
  clusters:
  - circuit_breakers:
      thresholds:
      - max_connections: 4294967295
    connect_timeout: 0.250s
    load_assignment:
      cluster_name: 0-service-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
    name: 0-service-cluster
    type: STATIC
  listeners:
  - address:
      socket_address:
        address: 127.0.0.1
        port_value: 61001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: 0-service-cluster
          stat_prefix: 0-stats
      transport_socket:
        name: listener-8080
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols:
            - http/1.1
            tls_certificate_sds_secret_configs:
            - name: server_cert
            validation_context_sds_secret_config:
              name: validation_context
          require_client_certificate: false
    name: listener-8080
# uncomment below configuration to see the previous behavior
# layered_runtime:
#   layers:
#   - name: static-layer
#     static_layer:
#       envoy:
#         reloadable_features:
#           new_tcp_connection_pool: false
```

*Logs*:
N/A

*Call Stack*:
N/A
