### ISSUE TITLE
Global request timeout configuration

### ISSUE THREAD

**Issue by arcanjoaq** [envoyproxy/envoy#19055]
I would like to know if there is a global request timeout configuration in `Envoy v1.20.0`. I have read the docs but I couldn't find an answer. The property 
`route_config.virtual_hosts.routes.route.timeout` works as expected, however, it would be nice if I could configure a `global request timeout` regardless of route.
 
The following _envoy.yaml_ configures a per route timeout (this is OK):

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  timeout: 52s # Route timeout is here!!!! Great!!! (header x-envoy-expected-rq-timeout-ms)
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: local_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081

```

This second strategy does not work:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          common_http_protocol_options:
            max_connection_duration: 10s # Connection timeout
            max_stream_duration: 52s # Is this the same as a global request timeout?
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: local_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
```

And this one does not work as well:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: local_service
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        common_http_protocol_options:
          max_connection_duration: 52s # Timeout
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
```

**Comment by rojkov** [comment]
I presume you want to have timeouts for upstream connections. You could try to set also `max_stream_duration` for the upstream cluster. `max_connection_duration` triggers if there's no active stream.

Maybe @Shikugawa can help.

**Comment by Shikugawa** [comment]
@arcanjoaq There is no effect configuring `max_stream_duration` on `common_http_protocol_options` in HTTP connection manager filter.

**Comment by agrawroh** [comment]
How about using [x-envoy-upstream-rq-timeout-ms](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-upstream-rq-timeout-ms) header on the requests? Do note that if both the header as well as route level timeouts are set then the route level timeout will be ignored and the global timeout will be set from the value specified in the header.

**Comment by vicalixto** [comment]
@agrawroh 
you have an example of configuration x-envoy-upstream-rq-timeout-ms ??
 I tried in several ways and I still get error 504 the same as the @arcanjoaq

**Comment by arcanjoaq** [comment]
> @arcanjoaq There is no effect configuring `max_stream_duration` on `common_http_protocol_options` in HTTP connection manager filter.

So, is there a way to configure a http request connection timeout besides my first example (regardless of route)?

**Comment by agrawroh** [comment]
@arcanjoaq You can use `max_connection_duration` [[Link]](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#:~:text=value%20for%20HTTP_DOWNSTREAM_CONNECTION_IDLE.-,max_connection_duration,-(Duration)%20The%20maximum) regardless of route if you want to close the connection. It works for both the upstream as well as downstream.

**Comment by agrawroh** [comment]
> @agrawroh you have an example of configuration x-envoy-upstream-rq-timeout-ms ?? I tried in several ways and I still get error 504 the same as the @arcanjoaq

@vicalixto The header needs to be added in a way that the router could see it. If you are trying to use `add_request_headers` on the Virtual Host/Route level then it won't work as the headers aggregation happens after the timeouts get finalized. One way is to use the **LUA filter** before the **Router filter** and inject this header directly into the stream so that router can see it.

```
...
"http_filters":
- "name": "envoy.filters.http.lua"
  "typed_config":
    "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
    "inline_code": "function envoy_on_request(request_handle)\n  if request_handle:headers() ~= nil and request_handle:headers():get('x-envoy-upstream-rq-timeout-ms') == nil then\n    request_handle:headers():add('x-envoy-upstream-rq-timeout-ms', '60000')\n  end\nend"
- "name": "envoy.filters.http.router"
  "typed_config": { ... }
...
```

**Comment by vicalixto** [comment]
> > @agrawroh you have an example of configuration x-envoy-upstream-rq-timeout-ms ?? I tried in several ways and I still get error 504 the same as the @arcanjoaq
> 
> @vicalixto The header needs to be added in a way that the router could see it. If you are trying to use `add_request_headers` on the Virtual Host/Route level then it won't work as the headers aggregation happens after the timeouts get finalized. One way is to use the **LUA filter** before the **Router filter** and inject this header directly into the stream so that router can see it.
> 
> ```
> ...
> "http_filters":
> - "name": "envoy.filters.http.lua"
>   "typed_config":
>     "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
>     "inline_code": "function envoy_on_request(request_handle)\n  if request_handle:headers() ~= nil and request_handle:headers():get('x-envoy-upstream-rq-timeout-ms') == nil then\n    request_handle:headers():add('x-envoy-upstream-rq-timeout-ms', '60000')\n  end\nend"
> - "name": "envoy.filters.http.router"
>   "typed_config": { ... }
> ...
> ```

@agrawroh 
I configured but the timeout continues :( , and returning error 504
validate config and is ok - https://envoylint.com

my envoy config :

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
              json_format: {
                  "start_time": "%START_TIME%",
                  "req_method": "%REQ(:METHOD)%",
                  "req_path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
                  "protocol": "%PROTOCOL%",
                  "response_code": "%RESPONSE_CODE%",
                  "response_flags": "%RESPONSE_FLAGS%",
                  "bytes_received": "%BYTES_RECEIVED%",
                  "bytes_sent": "%BYTES_SENT%",
                  "duration": "%DURATION%",
                  "resp_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",
                  "req_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                  "req_user_agent": "%REQ(USER-AGENT)%",
                  "req_id": "%REQ(X-REQUEST-ID)%",
                  "req_authority": "%REQ(:AUTHORITY)%",
                  "upstream_host": "%UPSTREAM_HOST%"
                }
          codec_type: auto
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle) 
                  if request_handle:headers() ~= nil and request_handle:headers():get('x-envoy-upstream-rq-timeout-ms') == nil 
                  then
                    request_handle:headers():add('x-envoy-upstream-rq-timeout-ms', '60000')
                  end
                end
          - name: envoy.filters.http.router
          skip_xff_append: false
          stat_prefix: ingress_http
          use_remote_address: true
          route_config:
            virtual_hosts:
            - name: health_check
              domains:
              - "10.196.*"
              routes:
              - match:
                  prefix: "/health"
                direct_response:
                  status: 200
            - name: kibana
              domains:
              - "kibana.*"
              routes:
              - match:
                  prefix: "/_plugin/kibana"
                route:
                  cluster: kibana
                  timeout: 60s
              - match:
                  prefix: "/"
                route:
                  cluster: kibana
                  prefix_rewrite: "/_plugin/kibana"
                  auto_host_rewrite: true
                  timeout: 60s
            - name: load_balancer_2
              domains:
              - "a*"
              - "b*"
              - "c*"
              - "d*"
              - "e*"
              - "f*"
              - "g*"
              - "h*"
              - "i*"
              - "j*"
              - "k*"
              - "l*"
              - "m*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: load_balancer_2
                  timeout: 60s
            - name: load_balancer_3
              domains:
              - "n*"
              - "o*"
              - "p*"
              - "q*"
              - "r*"
              - "s*"
              - "t*"
              - "u*"
              - "v*"
              - "w*"
              - "x*"
              - "y*"
              - "z*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: load_balancer_3
                  timeout: 60s
  clusters:
  - name: kibana
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: kibana
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: vpc1.es.amazonaws.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
  - name: load_balancer_2
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: load_balancer_2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: LB2.elb.amazonaws.com
                port_value: 80
  - name: load_balancer_3
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: load_balancer_3
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: LB3.elb.amazonaws.com
                port_value: 80

**Comment by agrawroh** [comment]
@vicalixto What are you excepting out of this config? This should make the timeout for all your routes 60s and yes, you will get a 504 (Gateway Timeout) after 60s.

**Comment by arcanjoaq** [comment]
> @arcanjoaq You can use `max_connection_duration` [[Link]](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#:~:text=value%20for%20HTTP_DOWNSTREAM_CONNECTION_IDLE.-,max_connection_duration,-(Duration)%20The%20maximum) regardless of route if you want to close the connection. It works for both the upstream as well as downstream.

I have tried this configuration: 

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          #upstream_protocol_options: # Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:upstream_protocol_options: Cannot find field.) has unknown fields
            #max_connection_duration: 52s
          #upstream_http_protocol_options: #  Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:upstream_http_protocol_options: Cannot find field.) has unknown fields
            #max_connection_duration: 52s
          common_http_protocol_options:
            max_connection_duration: 52s # Does not work
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: local_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
```

But it does not work as expected. It keeps sending "x-envoy-expected-rq-timeout-ms":"15000". If I uncomment upstream_protocol_options or upstream_http_protocol_options, envoy says that it is an invalid argument.

I have searched inside `examples` directory something about it, but I could not find it. Only per route timeout configuration works as expected.
