### ISSUE TITLE
Using the default now-deprecated value AUTO for enum 'envoy.config.core.v3.ConfigSource.resource_api_version'

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#19065]
Hi,

I want to fix the warning messages that I see during the envoy bootstrap:
```
Using the default now-deprecated value AUTO for enum 'envoy.config.core.v3.ConfigSource.resource_api_version'

```
But in my case SDS defined in the envoy confguration is watching only on filesystem,eg:

```
validation_context_sds_secret_config:
    name: validation__context_sip_sds
    sds_config:
        path: /etc/envoy/validation_sip_context_sds_secret.yaml

```

Why shall we  define the xDS version?

```
config.core.v3.ApiVersion

```
If yes, what is the suggested value? V3?

```
resource_api_version: V3
```

Thanks a lot!
