### ISSUE TITLE
deprecated option 'envoy.config.bootstrap.v3.Admin.access_log_path' from file bootstrap.proto

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#19061]
Hi,

Currently in my envoy bootstrap configuration the admin access log is just redirect to null in this way:

```
admin:
    access_log_path: "/dev/null"

```
But from the log  I see that access_log_path for admin configuration is deprecated:

```
deprecated option 'envoy.config.bootstrap.v3.Admin.access_log_path' from file bootstrap.proto

```
What is the simplest way to implement to redirect access log for Adming without using deprecated access_log_path configuration parameter?

Thanks.

/Oreste

**Comment by davinci26** [comment]
Hey, you can use the `access_log` property, see [docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-admin)

For example that would be the snippet to output to stdout:

```
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
```
That being said if you don't want care about the logs (you are piping to /dev/null after all) you can always skip this field

**Comment by eoregua** [comment]
Thanks a lot!

Yes, it's working.

I don't know if you can easily drive to figure out the last deprecated messages that  I see from the log:
```
Using the default now-deprecated value AUTO for enum 'envoy.config.core.v3.ConfigSource.resource_api_version'
```
But In my case sds is watching on filesystem:


```
validation_context_sds_secret_config:
    name: validation__context_sip_sds
    sds_config:
        path: /etc/envoy/validation_sip_context_sds_secret.yaml
```
Do we really specify the xDS version: 
```
config.core.v3.ApiVersion
```
And what is the suggested value? V3?

Thanks a lot!

**Comment by davinci26** [comment]
yeah, something like this should work:

```
validation_context_sds_secret_config:
    name: validation_context
    sds_config:
        resource_api_version: V3
        path: /path/to/secret.yaml
```

As a useful tip, if you are tinkering with the config and you want to find an example code search is super useful. All the configs in main should load on Envoy without any warnings.
