### ISSUE TITLE
The Clusters is not updating in Docker

### ISSUE THREAD

**Issue by F34th3R** [envoyproxy/envoy#19094]
*Title*: *docker envoy is not updating the clusters*

*Description*:
>I have tried to update the config file of envoy.yml, but is not updating the clusters when I try to add or change the clusters.
The docker container have a volume, but is not working when i try to change. I lil help, thanks.

*Repro steps*:
```yml
- name: authentication_cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: authentication_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: authentication
                port_value: 80
```
*Config*:
```yml
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/v1/api/authentication"
                route:
                  host_rewrite_literal: /authentication
                  cluster: authentication_cluster
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io

  clusters:
  - name: authentication_cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: authentication_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: authentication
                port_value: 80
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```

```docker-compose
version: '3.9'

services:
  envoy:
    container_name: efth_envoy
    build:
      context: .
      dockerfile: Envoy/Dockerfile
    ports:
      - "9902:9902"
      - "10000:10000"
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml

  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    container_name: fth_authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    ports:
      - "9081:80"
      - "9071:443"
```
