### ISSUE TITLE
How does RBAC filter restrict access to a specific cluster according to the source IP of the client?

### ISSUE THREAD

**Issue by Panxu1219** [envoyproxy/envoy#19100]
*Title*: How does RBAC filter restrict access to a specific cluster according to the source IP of the client?

*Description*:I want to use RBAC filter to intercept the client's access to an upstream service according to the client's source IP; But I don't know how to configure RBAC permissions; Ask for help。

This is my configuration：

````
   - name: envoy.filters.network.rbac
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
        stat_prefix: tcp.
        rules:
          action: DENY
          policies:
            "foo":
              permissions:
                    ???
              principals:
                  - source_ip:
                      address_prefix: 192.168.0.1
                      prefix_len: 32
````

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Panxu1219** [comment]
I tried to implement it with the following configuration, but there were errors.
````
    - name: envoy.filters.http.rbac
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
        stat_prefix: tcp.
        rules:
          action: DENY
          policies:
            "foo":
              permissions:
                  - and_rules:
                      rules:
                         - header: { name: ":authority", prefix_match: "oa" }
                         - url_path:
                             path: { prefix: "/" }
                         - or_rules:
                             rules:
                               - destination_port: 80
                               - destination_port: 443

              principals:
                  - source_ip:
                      address_prefix: 192.168.0.1
                      prefix_len: 32    

````


Error : 
````
Filesystem config update rejected: Error adding/updating listener(s) listener_0: Found header(name: ":authority"
) rule,not supported by RBAC network filter

````

What is the correct configuration？
