### ISSUE TITLE
Update dinamically stats_matcher inclusion list

### ISSUE THREAD

**Issue by eoregua** [envoyproxy/envoy#19116]
Hi,

Is it possible to update the stats_matcher inclusion list in the envoy configuration dinamycally without the need to restart envoy pod?

e.g Move from this configuration:

```
admin:

stats_config:
  use_all_default_tags: false
  stats_matcher:
    inclusion_list:
      patterns:
      - prefix: listener.
      - prefix: listener_manager.
      - safe_regex:
          google_re2: {}
          regex: tcp.*.downstream_cx_*
      - safe_regex:
          google_re2: {}    
          regex: tcp.*.downstream_flow_control_*
      - safe_regex:
          google_re2: {}      
          regex: cluster.*.upstream_cx_.*
      - safe_regex:
          google_re2: {}      
          regex: cluster.*.upstream_flow_control.*
      - safe_regex:
          google_re2: {}
          regex: cluster.*.ssl.*
      - safe_regex:
          google_re2: {}
          regex: cluster.*.lb_.*
      - prefix: server.
      - prefix: overload.

```
To a new one:

```




stats_matcher:
--
  | inclusion_list:
  | patterns:
  | - safe_regex:
  | google_re2: {}
  | regex: tcp.*.downstream_cx_*
  | - safe_regex:
  | google_re2: {}
  | regex: tcp.*.downstream_flow_control_*
  | - safe_regex:
  | google_re2: {}
  | regex: cluster.*.upstream_cx_.*
  | - safe_regex:
  | google_re2: {}
  | regex: cluster.*.upstream_flow_control.*
  | - safe_regex:
  | google_re2: {}
  | regex: cluster.*.ssl.*




```

If yes, what is the way?

Thanks!
