### ISSUE TITLE
Make the query parameters optional in routing

### ISSUE THREAD

**Issue by ykostsik** [envoyproxy/envoy#19184]
*Title*: *Add an ability to route the traffic based on the query parameters given that some of them could be omitted*

*Description*:
Hi team,
This could be a question or a feature request.
I would like to route traffic based on the query params I specified and I see it's possible when using `virtual_hosts.routes.match.query_parameters`
But it checks all or nothing according to the documentation.

Let's assume we have a string like
`\get?foo=bar&baz=boo&bee=1`,
The following code will match
```
- match:
  prefix: "/"
  query_parameters:
  - name: foo
    string_match:
      exact: bar
  - name: baz
    string_match:
      exact: boo
  - name: bee
    string_match:
      safe_regex: 
        google_re2: {}
        regex: '\d{1,}'
```
However,  I'd like to make `baz` and `bee` optional, so we can skip them, BUT at the same time no any other keys are allowed!
So
`\get?foo=bar&baz=boo`
`\get?foo=bar&bee=1`
`\get?foo=bar`
should match?
but the below doesn't:
`\get?baz=boo&bee=1`  #foo is required
`\get?foo=bar&baz=boo&bee=1&tag=value`  #new key `tag` is not defined
`\get?foo=bar&&bee=1&tag=mytag`  #same, new key `tag` is not defined

OR maybe it's possible to parse all the prefix/path with a query string included. Docs said that it's not, but maybe it's easier to implement.
   
I found something similar was requested before, but I could not find it in the documentation now, so I assume it is not supported.
https://github.com/envoyproxy/envoy/pull/2258

[optional *Relevant Links*:]
(https://github.com/envoyproxy/envoy/pull/2258)
