### ISSUE TITLE
Support TRACE methods in router_check tool

### ISSUE THREAD

**Issue by juliankung-db** [envoyproxy/envoy#19223]
Currently, the router_check tool only supports GET, PUT, and POST methods according to the documentation https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/tools/router_check (in the method section). 

I am looking to create some tests that ensure envoy denies TRACE methods for my route, but can't do so because of this limitation. Would it be a difficult problem to support all methods (or at least TRACE) in the router_check tool?

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by soulxu** [comment]
I tested with router_check tool with config as below:

route config:
```
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  headers:
                    - name: ":method"
                      string_match:
                        exact: "TRACE"
                        ignore_case: true
                route:
                  cluster: my_cluster
```

The test is
```
tests:
- test_name: Cluster_name_test
  input:
    authority: 127.0.0.1:13333
    path: /
    method: TRACE
  validate:
    cluster_name: my_cluster
```

It seems the TRACE method works.
```
bazel-bin/test/tools/router_check/router_check_tool --config-path ./config.yaml -t ./test.yaml -d
Cluster_name_test
Current route coverage: 100%
```

It should be the doc issue.
