### ISSUE TITLE
How to rewrite the response message

### ISSUE THREAD

**Issue by inaryart** [envoyproxy/envoy#19248]
*Description*:
How to rewrite the response to this message
```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: delayed connect error: 111
```
I have tried all the following fields and it doesn't work
```
                          local_reply_config:
                              mappers:
                                  - filter:
                                        status_code_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        duration_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        not_health_check_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        traceable_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        runtime_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        and_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        or_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        header_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        response_flag_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        grpc_status_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        extension_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                        metadata_filter:
                                            comparison:
                                                op: EQ
                                                value:
                                                    default_value: 503
                                                    runtime_key: _ignored
                                    status_code: 199
                                    body_format_override: text_format:"123"
```
