### ISSUE TITLE
Envoy logs unexpected data when proxying the request via a WASM filter

### ISSUE THREAD

**Issue by tkennedy1-godaddy** [envoyproxy/envoy#19273]
*Title*: *Envoy logs unexpected data when proxying via a WASM filter*

*Description*:
We are intercepting requests and proxying those to a different service sometimes, depending on the headers in the request using the `on_http_request_headers` method on the `HttpContext` object, where we invoke `dispatch_http_call` and set `Action::Pause` on the inbound request.

On the `on_http_call_response` method in the `Context` object, we then read the data from the request and in some cases, reply directly to the client, returning their inbound call, so the request never goes through the full cycle in envoy. However, when envoy logs the request, we see unexpected data associated with the request.

Given the following routing setup:

```yaml
- match:
    prefix: "/"
    headers:
      - name: 'x-proxy-this'
  route:
    cluster_header: 'x-proxy-this'
  request_headers_to_remove:
    - x-proxy-this
- match:
    prefix: "/"
  route:
    cluster: beepboop 
    prefix_rewrite: "/beepboop/sales/"
    auto_host_rewrite: true
  request_headers_to_add:
    - header:
        key: X-A-Value
        value: Something

```

A request inbound to `/` will hit the first match, and invoke the proxy if the `x-proxy-this` header has the correct value.  When this happens though we see the log entry say the `upstream_cluster` was set to `beepboop`, even though this request never goes to this cluster.

Is this something that can be configured either not log or can we set the appropriate context data for the log from the WASM filter? (We are using rust to write our filters).
