### ISSUE TITLE
extract jwt token to header with jwtProvider

### ISSUE THREAD

**Issue by 0xbeny** [envoyproxy/envoy#19272]
**I want to extract jwt token that was received from the request header and put the properties into header**
**I tied this yaml file but I got an error**
**i have a problem with defining http_filters using the available extension in envoy such as jwtHeader and jwtProvider,...**

```
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1337
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: 0.0.0.0
                  cluster: web_service
          http_filters:
          - name: config.filter.http.jwt_authn.v2alpha.JwtHeader // I guess this file might change
            from_params:
            - jwt_token
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local meta = request_handle:streamInfo():dynamicMetadata()
                  for key, value in pairs(meta) do
                    request_handle:logInfo("extract dynamicMetadata key: "..key)
                    request_handle:logInfo("extract dynamicMetadata value: "..value.jwt_payload.usr)
                  end
                end
          - name: envoy.filters.http.router
  clusters:
  - name: web_service
    connect_timeout: 5s
    type: STRICT_DNS  # static
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 3000
```

**I really appreciate someone helping me**
