### ISSUE TITLE
How can I set the hostname for upstream

### ISSUE THREAD

**Issue by Demon520-coder** [envoyproxy/envoy#19292]
I have met a issue that : When I set the IPAddress for the upstream's address,envoy works fine. But when I set the hostname for the upstream's address,it show me 'no healthy upstream'. Have someone met this? This is my envoy.yaml. Any help for me will
be appreciated.
Thank you so much.
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener1
    per_connection_buffer_limit_bytes: 31457280
    address:
      socket_address: { address: 0.0.0.0, port_value: 8443 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc_json
          codec_type: AUTO
          access_log:
            name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog      
              path: "/etc/envoy/logs/request_log"      
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/IncidentPkg", case_sensitive: false, grpc: {} }
                route: { cluster: IncidentGrpcSvcPerformance, timeout: { seconds: 30 } }   
                response_headers_to_add:                                 
                - header: { key: "grpc-to-json", value: "grpc-to-json" }
                  append: true 

              - match: { prefix: "/RMSGrpcInterfaceServer", case_sensitive: false, grpc: {} }
                route: { cluster: RMSGrpc, timeout: { seconds: 180 } }   
                response_headers_to_add:                                 
                - header: { key: "grpc-to-json", value: "grpc-to-json" }
                  append: true     
              
              - match: { prefix: "/VehicleSrvPkg", case_sensitive: false, grpc: {} }
                route: { cluster: RMSGrpcVehicle, timeout: { seconds: 30 } }   
                response_headers_to_add:                                 
                - header: { key: "grpc-to-json", value: "grpc-to-json" }
                  append: true    

              - match: { prefix: "/", case_sensitive: false  }
                route: { cluster: AuthenticateSvc, timeout: { seconds: 30 }  }   
                                                                        
                                        
          http_filters:
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/descriptor/incidentsvc.pb"
              services:
              - "IncidentPkg.CreateIncidentGrpc"     
              - "IncidentPkg.SearchIncidentGrpc"        
              print_options:
                add_whitespace: false
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
              auto_mapping: true 

          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/descriptor/grpc_svc_03.pb"
              services:
              - "RMSGrpcInterfaceServer.SyncOfficerGrpc" 
              - "RMSGrpcInterfaceServer.SyncStationGrpc"          
              print_options:
                add_whitespace: false
                always_print_primitive_fields: true
                always_print_enums_as_ints: true
                preserve_proto_field_names: false
              auto_mapping: true                   
          
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/descriptor/vehicle_srv.pb"
              services:
              - "VehicleSrvPkg.VehicleGrpc" 
              print_options:
                add_whitespace: false
                always_print_primitive_fields: true
                always_print_enums_as_ints: true
                preserve_proto_field_names: false
              auto_mapping: true                   
                                                      

          - name: envoy.filters.http.jwt_authn
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                provider_01:
                  issuer: "https://test-idesvr.fgms.test.com:5095"
                  audiences:
                    - "api1"
                    - "api2"
                  forward: true     
                  local_jwks:
                    filename: "/etc/envoy/certs/jwks.json"
                  #remote_jwks:
                  #  http_uri:
                  #    uri: "https://fgms-idsrv.fgms.dev.com:5095/.well-known/openid-configuration/jwks"
                  #    cluster: auth_app        
                  #    timeout: 5s                                 
              rules:
                - match: 
                    prefix: "/IncidentPkg" 
                  requires:
                    provider_name: provider_01                                                
          - name: envoy.filters.http.router
   
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols:
            - "h2"       
            tls_certificates:             
              certificate_chain:
                filename: "/etc/envoy/certs/server_105.crt"
              private_key:
                filename: "/etc/envoy/certs/server_105.key"
       

  clusters:
  - name: IncidentGrpcSvcPerformance
    connect_timeout: 1.25s
    type: STATIC
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}        
    load_assignment:
      cluster_name: IncidentGrpcSvcPerformance
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.5.125
                port_value: 5000            
        
  - name: RMSGrpc
    connect_timeout: 1.25s
    type: STATIC
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}        
    load_assignment:
      cluster_name: RMSGrpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.6.39
                port_value: 5200         

  - name: RMSGrpcVehicle
    connect_timeout: 1.25s
    type: STATIC
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}        
    load_assignment:
      cluster_name: RMSGrpcVehicle
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.6.39
                port_value: 5300          
    
  - name: AuthenticateSvc
    connect_timeout: 1.25s
    type: LOGICAL_DNS
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    dns_refresh_rate: { seconds: 60 }            
    load_assignment:
      cluster_name: AuthenticateSvc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                #If I set Ip address,it works fine.
                #But when I set hostname,it will not work. I am very puzzled for this.
                address: zzl-idsrv.fgms.dev.com
                port_value: 5095         
                          
```
