### ISSUE TITLE
configure histogram buckets, the stats results are not as expected

### ISSUE THREAD

**Issue by bboshiZ** [envoyproxy/envoy#19301]
*Title*:  the stats results are not as expected when  custom histogram buckets

*Description*:
> There is a backend service, the response time is about 100~105ms. Using envoy's default histogram_bucket_settings[0.5,1,5,10,25,50,100,250,500,xxx], the request statistics will fall to 250，which is in line with expectations.
But ,by customizing the bucket[1,10,90,100,103,104,105,106,108,109,110,111,112], the request fell to 110, which did not meet expectations.
Expecte to fall to 105, 104 or other buckets

*Repro steps*:
> vim config.yaml
> envoy -c config.yaml

*env*
> $  envoy --version
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL

> $ cat /proc/version
Linux version 3.10.0-862.14.1.5.h428.eulerosv2r7.x86_64 (abuild@szxrtosci10000) (gcc version 4.8.5 20150623 (EulerOS 4.8.5-28) (GCC) ) #1 SMP Wed Mar 11 06:00:00 UTC 2020

*Admin and Stats Output*:
> curl 0.0.0.0:15000/stats/prometheus |grep 'envoy_cluster_upstream_rq_time_bucket'
```
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="1"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="10"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="90"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="100"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="103"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="104"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="105"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="106"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="108"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="109"} 0
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="110"} 4
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="111"} 4
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="112"} 4
envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name="some_service",le="+Inf"} 4
```

*Config*:
```
stats_config:
  histogram_bucket_settings:
  - match:
      safe_regex:
        google_re2: {}
        regex: ".*?"
    buckets: [1,10,90,100,103,104,105,106,108,109,110,111,112]
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 15000 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: x.x.x.x
                port_value: 80
```

*Logs*:
```
[2021-12-16 08:14:42.080][31114][warning][main] [external/envoy/source/server/server.cc:642] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
[2021-12-16 08:14:42.080][31114][info][main] [external/envoy/source/server/server.cc:745] all clusters initialized. initializing init manager
[2021-12-16 08:14:42.080][31114][info][config] [external/envoy/source/server/listener_manager_impl.cc:888] all dependencies initialized. starting workers
[2021-12-16 08:14:42.117][31114][info][main] [external/envoy/source/server/server.cc:764] starting main dispatch loop
[2021-12-16T08:15:49.041Z] "GET /echo HTTP/1.1" 200 - 0 3 104 104 "-" "curl/7.29.0" "6bff1ff0-8077-4669-91b1-123fe9d00d57" "0.0.0.0" "x.x.x.x:80"
[2021-12-16T08:15:49.905Z] "GET /echo HTTP/1.1" 200 - 0 3 102 102 "-" "curl/7.29.0" "3a4605d3-f837-4b78-9494-a0315f9e0aa9" "0.0.0.0" "x.x.x.x:80"
[2021-12-16T08:15:50.726Z] "GET /echo HTTP/1.1" 200 - 0 3 104 104 "-" "curl/7.29.0" "da948171-970d-4bd2-b94b-4d0d858d6c06" "0.0.0.0" "x.x.x.x:80"
[2021-12-16T08:15:51.525Z] "GET /echo HTTP/1.1" 200 - 0 3 102 102 "-" "curl/7.29.0" "6cf93e8e-446c-417b-ad4d-0d408aaeb074" "0.0.0.0" "x.x.x.x:80"
```
