### ISSUE TITLE
Envoy doesn't escape HTTP response header name writing by Wasm filter

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#19309]
*Title*: *Envoy doesn't escape HTTP response header name writing by Wasm filter*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

Envoy should escape separator in the HTTP response header writing by Wasm filter

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Configure the Wasm filter with the Wasm code below:

```go
	hs, err := proxywasm.GetHttpRequestHeaders()
	if err != nil {
		proxywasm.LogCriticalf("failed to get request headers: %v", err)
		return types.ActionContinue
	}

	for i, h := range hs {
		hs[i][0] = "req-" + h[0]
	}
	err = proxywasm.SendHttpResponse(200, hs, []byte("blahblag"), -1)
	if err != nil {
		proxywasm.LogErrorf("failed to send local response: %v", err)
		return types.ActionContinue
	}
	return types.ActionPause

```

Hit the Wasm filter with a HTTP request, you will see:

```
curl http://xxx -i
HTTP/1.1 200 OK
...
req-:method: GET
```

We can find that the `:` in the HTTP response header name is not escaped.

If we put a proxy in front of Envoy, we will receive:
```
req-: method: GET
```

The `method: ` is treated as part of the header value.

The `req-:method: GET` should be escaped into `req-%3Amethod: GET`.

*Config*:
>Include the config used to configure Envoy.

```
...
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "wasm_code_above.wasm"

```

I have found this issue with Envoy 1.20.1. Not sure if the main branch has the same issue, and whether the Lua filter is also affected.
