### ISSUE TITLE
Getting reset reason: protocol error when working with nodejs

### ISSUE THREAD

**Issue by rseasta** [envoyproxy/envoy#19337]
Hi!
I used to work with envoy as a proxy and load balancer for nginx servers and everything worked fine.
When I try use it for nodejs project I get strange error `upstream connect error or disconnect/reset before headers. reset reason: protocol error` (http code 502).
Thats my config:
```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9900 }

static_resources:
  listeners:
    - name: node-test
      address:
        socket_address: { address: 0.0.0.0, port_value: 8082 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: http
                codec_type: AUTO
                always_set_request_id_in_response: true
                use_remote_address: false
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "test-1.mydomain.com", "test-2.mydomain.com" ]
                      include_request_attempt_count: true
                      include_attempt_count_in_response: true
                      retry_policy:
                        retry_on: "5xx"
                        num_retries: 5
                        host_selection_retry_max_attempts: 1
                      routes:
                        - match:
                            safe_regex:
                              google_re2: { }
                              regex: "\/(img|uploaded-images|uploaded-files|storage|js|css|sitemap).*"
                          route:
                            timeout: 60s
                            cluster: static
                        - match: { prefix: "/" }
                          route:
                            timeout: 60s
                            cluster: backend-nodejs
                http_filters:
                  - name: envoy.filters.http.router
  clusters:
    - name: backend-nodejs
      connect_timeout: 15s
      type: STATIC
      lb_policy: LEAST_REQUEST
      circuit_breakers:
        thresholds:
          - priority: "HIGH"
            max_connections: 1
            max_requests: 1
            max_pending_requests: 1
      max_requests_per_connection: 15
      http_protocol_options: {}
      health_checks:
        timeout: 10s
        interval: 60s
        unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check:
          expected_statuses: { start: 200, end: 400 }
          request_headers_to_add: [
              header: {
                "key": "User-Agent",
                "value": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
              }
          ]
          path: "/"
      load_assignment:
        cluster_name: backend_nodejs_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  hostname: "request-nodejs-1"
                  address:
                    socket_address:
                      address: --changed server ip--
                      port_value: 801
              - endpoint:
                  hostname: "request-nodejs-2"
                  address:
                    socket_address:
                      address: --changed server ip--
                      port_value: 802
              - endpoint:
                  hostname: "request-nodejs-3"
                  address:
                    socket_address:
                      address: --changed server ip--
                      port_value: 803
              - endpoint:
                  hostname: "request-nodejs-4"
                  address:
                    socket_address:
                      address: --changed server ip--
                      port_value: 804
              - endpoint:
                  hostname: "request-nodejs-5"
                  address:
                    socket_address:
                      address: --changed server ip--
                      port_value: 805
    - name: static
      connect_timeout: 30s
      type: STATIC
      lb_policy: LEAST_REQUEST
      circuit_breakers:
        thresholds:
          - priority: "DEFAULT"
            max_requests: 10
            max_pending_requests: 5
            retry_budget:
              budget_percent:
                value: 25.0
              min_retry_concurrency: 10
      load_assignment:
        cluster_name: backend_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  hostname: "static-1"
                  address:
                    socket_address:
                      address: 10.110.32.14
                      port_value: 80
```
For static it works great. But for `backend_nodejs_cluster` I get this error.
If I request server-ip:801/802/etc I get correct response. On server side I use docker with node:latest image. So it ​many instances on one docker image working on different port
