### ISSUE TITLE
Tracing Custom Tags in HTTP Filters Spans

### ISSUE THREAD

**Issue by jeremybaumont** [envoyproxy/envoy#19344]
Title: Tracing Custom Tags in HTTP Filters Spans seems not working

*Description*:
 I setup the following tracing configuration to the HTTP connection manager:
```yaml
...snip...
          - name: "envoy.http_connection_manager"
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                request_id_extension:
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
                    pack_trace_reason: false
                generate_request_id: true
                tracing:
                  custom_tags:
                    - tag: "service.name"
                      environment:
                        name: MY_SERVICE_NAME
                        default_value: local
                    - tag: "deployment.environment"
                      environment:
                        name: MY_AWS_REGION
                        default_value: local
                    - tag: "deployment.environment_type"
                      environment:
                        name: MY_ENVTYPE
                        default_value: dev
                    - tag: "service_proxy_version"
                      environment:
                        name: SERVICE_PROXY_VERSION
                        default_value: local
                  provider:
                    name: envoy.tracers.opencensus
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenCensusConfig
                      stdout_exporter_enabled: false
                      ocagent_exporter_enabled: true
                      ocagent_address: obsvs-sidecar:55678
                      incoming_trace_context: b3
                      incoming_trace_context: trace_context
                      incoming_trace_context: grpc_trace_bin
                      outgoing_trace_context: b3
                      outgoing_trace_context: trace_context
...snip...
```
I have an ext_authz HTTP filter and a Rate Limit HTTP filter configured as HTTP filters (see all envoy config below).
I send traces from Envoy with Opencensus tracer to a opentelementry-collector.
I can see the traces received within the otel-collector logs:
```plaintext
[docker:log]: otel-sidecar        | 2021-12-22T00:11:03.163Z   INFO    loggingexporter/logging_exporter.go:41  TracesExporter  {"#spans": 3}
[docker:log]: otel-sidecar        | 2021-12-22T00:11:03.163Z   DEBUG   loggingexporter/logging_exporter.go:51  ResourceSpans #0
[docker:log]: otel-sidecar        | Resource labels:
[docker:log]: otel-sidecar        |      -> opencensus.starttime: STRING(2021-12-22T00:10:47.481746286Z)
[docker:log]: otel-sidecar        |      -> host.name: STRING(665be0cc2270)
[docker:log]: otel-sidecar        |      -> process.pid: INT(15)
[docker:log]: otel-sidecar        |      -> telemetry.sdk.version: STRING(0.5.0-dev)
[docker:log]: otel-sidecar        |      -> opencensus.exporterversion: STRING(0.5.0-dev)
[docker:log]: otel-sidecar        |      -> telemetry.sdk.language: STRING(cpp)
[docker:log]: otel-sidecar        | InstrumentationLibrarySpans #0
[docker:log]: otel-sidecar        | InstrumentationLibrary
[docker:log]: otel-sidecar        | Span #0
[docker:log]: otel-sidecar        |     Trace ID       : 1337c2358de677f7fe5deaf9af564269
[docker:log]: otel-sidecar        |     Parent ID      : 95d1863bbf40adb9
[docker:log]: otel-sidecar        |     ID             : 1073ae51e266e2d9
[docker:log]: otel-sidecar        |     Name           : async ingress_auth egress
[docker:log]: otel-sidecar        |     Kind           : SPAN_KIND_UNSPECIFIED
[docker:log]: otel-sidecar        |     Start time     : 2021-12-22 00:10:58.072539408 +0000 UTC
[docker:log]: otel-sidecar        |     End time       : 2021-12-22 00:10:58.073194754 +0000 UTC
[docker:log]: otel-sidecar        |     Status code    : STATUS_CODE_UNSET
[docker:log]: otel-sidecar        |     Status message :
[docker:log]: otel-sidecar        | Attributes:
[docker:log]: otel-sidecar        |      -> grpc.status_code: STRING(0)
[docker:log]: otel-sidecar        |      -> ext_authz_status: STRING(ext_authz_ok)
[docker:log]: otel-sidecar        |      -> component: STRING(proxy)
[docker:log]: otel-sidecar        |      -> upstream_cluster: STRING(ingress_auth)
[docker:log]: otel-sidecar        |      -> opencensus.same_process_as_parent_span: BOOL(true)
[docker:log]: otel-sidecar        |      -> library_name: STRING(envoy-cpp.service-proxy.http)
[docker:log]: otel-sidecar        | Span #1
[docker:log]: otel-sidecar        |     Trace ID       : 1337c2358de677f7fe5deaf9af564269
[docker:log]: otel-sidecar        |     Parent ID      : 95d1863bbf40adb9
[docker:log]: otel-sidecar        |     ID             : 5cd97c3d2e92dafe
[docker:log]: otel-sidecar        |     Name           : async ingress_rate_limit egress
[docker:log]: otel-sidecar        |     Kind           : SPAN_KIND_UNSPECIFIED
[docker:log]: otel-sidecar        |     Start time     : 2021-12-22 00:10:58.073107307 +0000 UTC
[docker:log]: otel-sidecar        |     End time       : 2021-12-22 00:10:58.073797446 +0000 UTC
[docker:log]: otel-sidecar        |     Status code    : STATUS_CODE_UNSET
[docker:log]: otel-sidecar        |     Status message :
[docker:log]: otel-sidecar        | Attributes:
[docker:log]: otel-sidecar        |      -> component: STRING(proxy)
[docker:log]: otel-sidecar        |      -> ratelimit_status: STRING(ok)
[docker:log]: otel-sidecar        |      -> grpc.status_code: STRING(0)
[docker:log]: otel-sidecar        |      -> upstream_cluster: STRING(ingress_rate_limit)
[docker:log]: otel-sidecar        |      -> opencensus.same_process_as_parent_span: BOOL(true)
[docker:log]: otel-sidecar        |      -> library_name: STRING(envoy-cpp.service-proxy.http)
[docker:log]: otel-sidecar        | Span #2
[docker:log]: otel-sidecar        |     Trace ID       : 1337c2358de677f7fe5deaf9af564269
[docker:log]: otel-sidecar        |     Parent ID      :
[docker:log]: otel-sidecar        |     ID             : 95d1863bbf40adb9
[docker:log]: otel-sidecar        |     Name           : ingress
[docker:log]: otel-sidecar        |     Kind           : SPAN_KIND_UNSPECIFIED
[docker:log]: otel-sidecar        |     Start time     : 2021-12-22 00:10:58.072514211 +0000 UTC
[docker:log]: otel-sidecar        |     End time       : 2021-12-22 00:10:58.074304977 +0000 UTC
[docker:log]: otel-sidecar        |     Status code    : STATUS_CODE_UNSET
[docker:log]: otel-sidecar        |     Status message :
[docker:log]: otel-sidecar        | Attributes:
[docker:log]: otel-sidecar        |      -> http.method: STRING(GET)
[docker:log]: otel-sidecar        |      -> upstream_cluster: STRING(service)
[docker:log]: otel-sidecar        |      -> http.url: STRING(http://localhost:8080/echo)
[docker:log]: otel-sidecar        |      -> node_id: STRING()
[docker:log]: otel-sidecar        |      -> http.status_code: STRING(200)
[docker:log]: otel-sidecar        |      -> http.response_content_length: STRING(409)
[docker:log]: otel-sidecar        |      -> service_proxy_version: STRING(e2e-tests-version)
[docker:log]: otel-sidecar        |      -> service.name: STRING(a-service-id)
[docker:log]: otel-sidecar        |      -> http.user_agent: STRING(HTTPie/2.6.0)
[docker:log]: otel-sidecar        |      -> component: STRING(proxy)
[docker:log]: otel-sidecar        |      -> guid:x-request-id: STRING(427e3f84-2d5a-40cb-a4a9-01734c624d43)
[docker:log]: otel-sidecar        |      -> http.flavour: STRING(HTTP/1.1)
[docker:log]: otel-sidecar        |      -> deployment.environment_type: STRING(an-environment-type)
[docker:log]: otel-sidecar        |      -> response_flags: STRING(-)
[docker:log]: otel-sidecar        |      -> OperationName: STRING(Ingress)
[docker:log]: otel-sidecar        |      -> upstream_cluster.name: STRING(service)
[docker:log]: otel-sidecar        |      -> downstream_cluster: STRING(-)
[docker:log]: otel-sidecar        |      -> http.request_content_length: STRING(0)
[docker:log]: otel-sidecar        |      -> http.client_ip: STRING(192.168.208.1)
[docker:log]: otel-sidecar        |      -> deployment.environment: STRING(local-region)
[docker:log]: otel-sidecar        |      -> zone: STRING()
[docker:log]: otel-sidecar        |      -> opencensus.same_process_as_parent_span: BOOL(true)
[docker:log]: otel-sidecar        |      -> library_name: STRING(envoy-cpp.service-proxy.http)
[docker:log]: otel-sidecar        | Events:
[docker:log]: otel-sidecar        | SpanEvent #0
[docker:log]: otel-sidecar        |      -> Name: spawnChild
[docker:log]: otel-sidecar        |      -> Timestamp: 2021-12-22 00:10:58.072537509 +0000 UTC
[docker:log]: otel-sidecar        |      -> DroppedAttributesCount: 0
[docker:log]: otel-sidecar        | SpanEvent #1
[docker:log]: otel-sidecar        |      -> Name: spawnChild
[docker:log]: otel-sidecar        |      -> Timestamp: 2021-12-22 00:10:58.073106866 +0000 UTC
[docker:log]: otel-sidecar        |      -> DroppedAttributesCount: 0
[docker:log]: otel-sidecar        |
```

I observe the custom tags/attributes only for the upstream ingress service span (span #2), not for the HTTP filters (ext_authz and rate limit) spans (span#0 and span#1).
Is it the expected behavior with custom tags/attributes?
I would have expected the custom tags/attributes added for the HTTP filters spans. What am I doing wrong?

PS: I know I can add/upsert attributes within the otel-collector, but if I want custom tags based on metadata, it won't help. 

[optional *Envoy config*:]
[Envoy Config](https://envoyproxy.slack.com/files/U9NN9QZEF/F02S0CGPZL1/envoy_yaml.yaml)
