### ISSUE TITLE
HTTP/1.1 Header Casing - Stateful formatters NOT working

### ISSUE THREAD

**Issue by ktalg** [envoyproxy/envoy#19418]
*Title*: *Stateful formatters NOT working*

*Description*:
I use EnvoyFilter to deploy a config like [this](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_casing#stateful-formatters) and it seem that it didn't work,I can confirm the configuration has been successfully delivered with configDump

```
EnvoyFilter:
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: echo-header
spec:
  workloadSelector:
    labels:
      app: echo
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            http_protocol_options:
              header_key_format:
                stateful_formatter:
                  name: preserve_case
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
```
and the config_dump.json:
```
...
            "http_protocol_options": {
             "header_key_format": {
              "stateful_formatter": {
               "name": "preserve_case",
               "typed_config": {
                "@type": "type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig"
               }
              }
             }
            },
...
```
when I use curl to request the server,the expected response is:(notice the Aa,bB header)
```
< HTTP/1.1 200 OK
< Aa: def
< bB: def
< Date: Thu, 06 Jan 2022 08:30:39 GMT
< Content-Length: 0
< X-Envoy-Upstream-Service-Time: 6
< Server: istio-envoy
< 
```
but the actual response is 
```
< HTTP/1.1 200 OK
< aa: def
< bb: def
< date: Thu, 06 Jan 2022 08:48:41 GMT
< content-length: 0
< x-envoy-upstream-service-time: 1
< server: istio-envoy
< 
```
what strange thing is that "Stateless formatters" setting is working properly
```
< HTTP/1.1 200 OK
< Aa: def
< Bb: def
< Date: Thu, 06 Jan 2022 08:30:39 GMT
< Content-Length: 0
< X-Envoy-Upstream-Service-Time: 6
< Server: istio-envoy
< 
```
and the only difference envoy config is 
```
                        "http_protocol_options": {
                          "header_key_format": {
                            "proper_case_words": {}
                          }
                        },
```
EnvoyFilter:
```
...<same content>...
              header_key_format:
                proper_case_words: {}
```
