### ISSUE TITLE
slow start mod on 1.20.1  is invalid

### ISSUE THREAD

**Issue by du2016** [envoyproxy/envoy#19437]
*Title*: *One line description*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

slow start mode at version 1.20.1 is invalid,when i use lb policy with `LEAST_REQUEST `, the new endpoint not receive any traffic in slow start window，if use round robin,the new endpoint has the same weight and receive same requests in slow start window

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

```
{
  "version_info": "2",
  "cluster": {
    "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    "name": "default/slowstart-test/8080/8bf87fefba",
    "type": "EDS",
    "eds_cluster_config": {
      "eds_config": {
        "api_config_source": {
          "api_type": "GRPC",
          "grpc_services": [
            {
              "envoy_grpc": {
                "cluster_name": "xds-server"
              }
            }
          ],
          "transport_api_version": "V3"
        },
        "resource_api_version": "V3"
      },
      "service_name": "default/slowstart-test"
    },
    "connect_timeout": "1s",
    "lb_policy": "LEAST_REQUEST",
    "circuit_breakers": {
      "thresholds": [
        {
          "max_connections": 50000,
          "max_requests": 50000
        }
      ]
    },
    "common_lb_config": {
      "healthy_panic_threshold": {
      }
    },
    "alt_stat_name": "default_slowstart-test_8080",
    "least_request_lb_config": {
      "slow_start_config": {
        "slow_start_window": "30s"
      }
    }
  },
  "last_updated": "2022-01-07T02:36:30.817Z"
}
```

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by du2016** [comment]
i also test by eds file as blow:
envoy.yaml:
```
static_resources:
  listeners:
  - name: http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: collector
          route_config:
            virtual_hosts:
            - name: local
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: collector|8082
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: collector|8082
    connect_timeout: 0.25s
    # OR ROUND_ROBIN
    lb_policy: "LEAST_REQUEST"
    type: EDS
    eds_cluster_config:
      service_name: collector|8082
      eds_config:
        path: './eds.yaml'
    # OR round_robin_lb_config
    least_request_lb_config:
      slow_start_config:
        slow_start_window: "60s"
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9001
```

eds.yaml,open or close to add or remove endpoints:
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  cluster_name: collector|8082
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: "10.23.1.199"
            port_value: "8080"
#    - endpoint:
#        address:
#          socket_address:
#            address: "10.23.0.155"
#            port_value: "8080"
```

with 700qps the LEAST_REQUEST loadbalance policy have work with slow start ,but is not standard linear growth, as blow,the two pods print the requests every seconds:

slowstart-test-597595c8d5-t45xc(10.23.1.199) is the old endpoint,slowstart-test-597595c8d5-tjfxk(10.23.0.155) is the new one
```
slowstart-test-597595c8d5-t45xc: 697
slowstart-test-597595c8d5-t45xc: 717
slowstart-test-597595c8d5-t45xc: 652
slowstart-test-597595c8d5-t45xc: 692
slowstart-test-597595c8d5-t45xc: 678
slowstart-test-597595c8d5-tjfxk: 104
slowstart-test-597595c8d5-tjfxk: 104
slowstart-test-597595c8d5-t45xc: 627
slowstart-test-597595c8d5-tjfxk: 51
slowstart-test-597595c8d5-tjfxk: 139
slowstart-test-597595c8d5-t45xc: 494
slowstart-test-597595c8d5-tjfxk: 164
slowstart-test-597595c8d5-t45xc: 540
slowstart-test-597595c8d5-t45xc: 525
slowstart-test-597595c8d5-tjfxk: 175
slowstart-test-597595c8d5-tjfxk: 199
slowstart-test-597595c8d5-t45xc: 521
slowstart-test-597595c8d5-t45xc: 460
slowstart-test-597595c8d5-tjfxk: 185
slowstart-test-597595c8d5-t45xc: 492
slowstart-test-597595c8d5-tjfxk: 209
slowstart-test-597595c8d5-tjfxk: 219
slowstart-test-597595c8d5-t45xc: 478
slowstart-test-597595c8d5-tjfxk: 225
slowstart-test-597595c8d5-t45xc: 461
slowstart-test-597595c8d5-t45xc: 469
slowstart-test-597595c8d5-tjfxk: 229
slowstart-test-597595c8d5-tjfxk: 224
slowstart-test-597595c8d5-t45xc: 429
slowstart-test-597595c8d5-tjfxk: 248
slowstart-test-597595c8d5-t45xc: 453
slowstart-test-597595c8d5-tjfxk: 250
slowstart-test-597595c8d5-t45xc: 454
slowstart-test-597595c8d5-tjfxk: 238
slowstart-test-597595c8d5-t45xc: 411
slowstart-test-597595c8d5-tjfxk: 257
slowstart-test-597595c8d5-t45xc: 437
slowstart-test-597595c8d5-tjfxk: 257
slowstart-test-597595c8d5-t45xc: 430
slowstart-test-597595c8d5-t45xc: 432
slowstart-test-597595c8d5-tjfxk: 270
slowstart-test-597595c8d5-t45xc: 423
slowstart-test-597595c8d5-tjfxk: 272
slowstart-test-597595c8d5-t45xc: 391
slowstart-test-597595c8d5-tjfxk: 251
```

roundrobin policy have not  any  effect work with slow start to requests
please have a look @nezdolik @mattklein123 , thanks
