### ISSUE TITLE
OAuth flow failed - Oauth breaks at /callback route

### ISSUE THREAD

**Issue by DeroSavage** [envoyproxy/envoy#19478]
Hey there,

im facing some issues with the oauth filter. The authorize requests works correctly, i'm redirected to the auth server and then come back to the /callback route. Here is where im getting the message "OAuth flow failed" all the time. 

Im running envoy as a sidecar in a kubernetes deployment which is running on port 8123. In the same deployment is a nginx with a hello world page running under port 80.
Envoy Version: 1.20-latest

Config: 
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8123
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                http_filters:
                  - name: envoy.filters.http.oauth2
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
                      config:
                        token_endpoint:
                          cluster: oauth_cluster
                          uri: https://authserver.com/token
                          timeout: 3s
                        authorization_endpoint: https://authserver.com/oauth2/authorize
                        redirect_uri: "http://%REQ(:authority)%/callback"
                        redirect_path_matcher:
                          path:
                            exact: /callback
                        signout_path:
                          path:
                            exact: /signout
                        forward_bearer_token: true
                        credentials:
                          client_id: "MYCLIENTID"
                          token_secret:
                            name: token
                            sds_config:
                              path: "/etc/envoy/token.yaml"
                          hmac_secret:
                            name: hmac
                            sds_config:
                              path: "/etc/envoy/hmac.yaml"
                        auth_scopes:
                          - openid
                  - name: envoy.filters.http.router
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: local_service
  clusters:
    - name: local_service
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: random
      load_assignment:
        cluster_name: local_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 80
    - name: oauth_cluster
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: oauth_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: authserver.com
                      port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: authserver.com
```

Maybe a stupid question but do the application needs to implement the /callback route? From the documentation of the oauth filter i would say no, as the oauth filter can redirect the gained access token to the application. 

Any help is highly appreciated.
