### ISSUE TITLE
Transport Socket TCP stats  - emitted counters stay at 0

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#19555]
Hello,
Transport Socket TCP stats  - emitted counters stay at 0, please find below info about the setup.

Envoy: version: a9d72603c68da3a10a1c0d021d01c7877e6f2a30/1.21.0/Clean/RELEASE/BoringSSL
OS: CentOS Linux 7

Cluster config:
..
```
transport_socket:
    name: envoy.transport_sockets.upstream
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tcp_stats.v3.Config
      update_period: 5s
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
          

stats emitted:
envoy_cluster_tcp_stats_cx_rx_data_segments{envoy_cluster_name="abc"} 0
TYPE envoy_cluster_tcp_stats_cx_rx_segments counter
envoy_cluster_tcp_stats_cx_rx_segments{envoy_cluster_name="abc"} 0
TYPE envoy_cluster_tcp_stats_cx_tx_data_segments counter

Thanks!
BR,
Stoyan
