### ISSUE TITLE
https only backend service

### ISSUE THREAD

**Issue by s-maj** [envoyproxy/envoy#19561]
Folks,

I'm looking for some guidance on how to configure sidecar to talk to the backend service that only understands https. By design, all traffic between the sidecar and the service is plaintext, which results in `upstream connect error or disconnect/reset before headers. reset reason: connection failure`, since the service expects TLS handshake. 

From the sidecar I can execute:
```
istio-proxy@playground-vdev2-cm-all-1-5dbcff567c-wtpsc:/$ curl -v -s -o /dev/null -k https://localhost:8443
*   Trying 127.0.0.1:8443...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8443 (#0)
...
< HTTP/1.1 200 OK
< Server: nginx/1.20.2
< Date: Sat, 15 Jan 2022 21:23:09 GMT
< Content-Type: text/html
< Content-Length: 612
< Last-Modified: Tue, 16 Nov 2021 14:44:02 GMT
< Connection: keep-alive
< ETag: "6193c3b2-264"
< Accept-Ranges: bytes
```

I reckon the envoy can be forced to use TLS by using EnvoyFilter which could look like this:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: forcessl
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        name: "force-ssl"
        type: STRICT_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: "force-ssl"
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: localhost
                        port_value: 8443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

which ends in envoy configuration as:
```
    {
    	"version_info": "2022-01-15T21:13:38Z/98",
    	"cluster": {
    		"@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
    		"name": "force-ssl",
    		"type": "STRICT_DNS",
    		"connect_timeout": "0.500s",
    		"transport_socket": {
    			"name": "envoy.transport_sockets.tls",
    			"typed_config": {
    				"@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
    			}
    		},
    		"load_assignment": {
    			"cluster_name": "force-ssl",
    			"endpoints": [{
    				"lb_endpoints": [{
    					"endpoint": {
    						"address": {
    							"socket_address": {
    								"address": "localhost",
    								"port_value": 8443
    							}
    						}
    					}
    				}]
    			}]
    		}
    	},
    	"last_updated": "2022-01-15T21:13:38.483Z"
    }
```
but ultimately the error stays the same.
