### ISSUE TITLE
The performance of Envoy when it as the redis cluster proxy

### ISSUE THREAD

**Issue by hughxia** [envoyproxy/envoy#19629]
*Title*: *The performance of Envoy when it as the redis cluster proxy*

*Description*:
>When I use envoy as a redis cluster proxy in K8s(the envoy pod resources: 4CPU and 1Gi memory), the RPS output tested by `redis-benchmark` is 80K~90K. If i use `redis-benchmark` directly connect the same redis cluster, the output is about 250K.

The worse thing is the performance output can't be better when i increase the envoy pod resources. 

Is this the limit of Envoy?
How can i improve the performance of Envoy when it as the redis cluster proxy?

Envoy Version: 1.20.0  This is my envoy config:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
            enable_redirection: true
            max_buffer_size_before_flush: 1024
            buffer_flush_timeout: 0.003s
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_password:
            inline_string: "xxxxxx" 
  clusters:
  - name: redis_cluster
    cluster_type:
      name: envoy.clusters.redis
    connect_timeout: 10s
    cleanup_interval: 3s
    lb_policy: CLUSTER_PROVIDED
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: xxxxx  
                port_value: 6379
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password:
            inline_string: "xxxxxx"
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
