### ISSUE TITLE
WebSockets with WSS are not working due to EnvoyFilter conflicts

### ISSUE THREAD

**Issue by andrewrmiller** [envoyproxy/envoy#19645]
*Title*: *Websockets with WSS are not working due to EnvoyFilter conflicts*

*Description*:
>An EnvoyFilter applied to an Istio configuration (e.g. to limit request size) will break the WSS and fail to initiate `101 Switching Protocols`.

*Repro steps*:
> Here's an example filter that will cause websocket functionality to stop working:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: max-request-size
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.buffer
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
          max_request_bytes: 52428800
```

If this filter is removed WebSocket functionality returns to normal.

*Related Links*

https://github.com/istio/istio/issues/36545

**Comment by andrewrmiller** [comment]
This is still an issue for us.

**Comment by andrewrmiller** [comment]
This is still an issue for us.

**Comment by phlax** [comment]
cc @alyssawilk

**Comment by alyssawilk** [comment]
Sorry I'm not clear what the problem is, is it that Websockets don't work with the buffer filer?  This is called out explicitly in the docs "Note that buffering is generally not compatible with upgrades, so if the Buffer filter is configured in the default HTTP filter chain it should probably be excluded for upgrades by using upgrade filters and not including the buffer filter in that list."

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades

**Comment by rauanmayemir** [comment]
@alyssawilk I'm guessing you mean buffer filters can't be used for websockets.
In our case, buffer filter is needed for its own thing (i.e limiting the inbound request size in regular http requests), but it's breaking the websockets altogether (that are used in different context).

Can envoy be configured in a way that would allow applying the buffer filter only for regular http requests and ignoring it for websockets/http upgrades?

**Comment by alyssawilk** [comment]
That's exactly what I'm saying.  Please read the links I added in the last comment, and let me know if that does not explain things sufficiciently.

**Comment by satata-clgx** [comment]
Facing the same issue in our cluster.

**Comment by kyessenov** [comment]
For those interested, the answer by Alyssa is the right solution but to make it more prescriptive requires more details about the version of Istio, so I can't provide one that works for all of them. There are two options in Istio here:

* make EnvoyFilter to set filters in the upgrade_config for websocket (which is always enabled in Istio)
* change buffer filter to [ExtensionWithMatcher](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/common/matching/v3/extension_matcher.proto#envoy-v3-api-msg-extensions-common-matching-v3-extensionwithmatcher) to skip its application for particular URL.

**Comment by kyessenov** [comment]
After some prototyping, option (1) is not possible since EnvoyFilters can't edit items in arrays deeper than top-level.
So we're left with option (2), here's an example:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: max-request-size
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: with-matcher
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
          extension_config:
            name: envoy.filters.http.buffer
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
              max_request_bytes: 52428800
          xds_matcher:
            matcher_tree:
              input:
                name: request-headers
                typed_config:
                  "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                  header_name: some-header
              exact_match_map:
                map:
                  some_value_to_match_on:  # This is the header value we're trying to match against.
                    action:
                      name: skip
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
```

**Comment by rauanmayemir** [comment]
@kyessenov Thank you!

Happy to confirm this works on istio upward 1.13. 1.12 will fail with `Internal:Error adding/updating listener(s) virtualInbound: Experimental matching API is not enabled`.

For websocket upgrade requests, browsers send `Upgrade: websocket` in the request headers among other things (but this one is the simplest we could match on). So here's the final working config:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: max-request-size
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
        name: with-matcher
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
          extension_config:
            name: envoy.filters.http.buffer
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
              max_request_bytes: 52428800
          xds_matcher:
            matcher_tree:
              input:
                name: request-headers
                typed_config:
                  "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                  header_name: Upgrade # This is the header value we're trying to match against.
              exact_match_map:
                map:
                  websocket: # Skip buffer filter for requests with `Upgrade: websocket` header.
                    action:
                      name: skip
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
```

**Comment by boomjuice** [comment]
> 

Thank for reply,  I apply the suggestion in my istio  but not effect with buffer size, it stils raise HTTP 413(payload too large)
So i make some changes like this , it's worked out even using websocket and payload size larger than 1MB!

istio version: 1.14

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
        proxy:
          proxyVersion: ^1\.14.*
      patch:
        operation: INSERT_BEFORE
        value:
          name: with-matcher
          typed_config:
            '@type':  type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: envoy.filters.http.buffer
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
                max_request_bytes: 52428800
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    '@type': type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: Upgrade
                exact_match_map:
                  map:
                    websocket:
                      action:
                        name: skip
                        typed_config:
                          '@type':  type.googleapis.com/envoy.extensions.filters.common.matcher.action.v3.SkipFilter
```
