### ISSUE TITLE
Can't add from_cookies config to the v3.JwtProvider, v1.19.1

### ISSUE THREAD

**Issue by DzianisH** [envoyproxy/envoy#19650]
I have config like the following for envoy v1.19.1.

```yaml
                      providers:
                        provider1:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtProvider
                          issuer: "my-issuer"
                          local_jwks:
                            filename: /foo/bar
                          forward: true
                          forward_payload_header: "forward-header-name"
                          from_cookies:
                            - test
```
And when I run  - envoy fails to starts with the message: `Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(providers[0].value) from_cookies: Cannot find field.) has unknown fields`

I don't understand why I can't configure `from_cookies` as writer here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtprovider 

But `from_headers` and `from_params` configs work just fine for me.
