### ISSUE TITLE
`stateful_session` not working on chrome due to favicons

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#19655]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: `stateful_session` not working on chrome

*Description*:

The initial symptom is that `stateful_session` seems to work with curl and firefox, but not with Chrome.

After some debugging, I have narrowed down the root cause to `favicon.ico` requests, although its really more general.

What happens is we have a config like:
```
        name: envoy.filters.http.stateful_session
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
          session_state:
            name: envoy.http.stateful_session.cookie
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
              cookie:
                name: global-session-cookie
                path: /path
                ttl: 120s
```

* first request `ip/path`. I get cookie "1234" set.
* request `ip/path` again. Browser sends "1234" and I get stickyness. This works!
* then request `ip/notpath`. Browser does not send cookie, so I hit a random host. Envoy sets a new cookie "5678"
* request `ip/path` again. Browser sends "5678". Now I hit a different host than I expected!

In chrome's case this was especially bad as it was constantly requesting /favicon.ico, breaking the persistence on every request.

it seems like if /path is set, we should only actually set the persistence cookie when the request also has that path?

*Repro steps*:
Apply config above, load in chrome OR load different URLs.

cc @wbpcode
