### ISSUE TITLE
question: custom sampling on different response code?

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#19676]
*Title*: *custom sampling on different response code*

*Description*:

can I set up something as following:
- when response_code==5xx report every single request
- when response_code==200 report request depends on sampling percent?

**Comment by mattklein123** [comment]
Yes you can use access log filters and the runtime filter: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-runtimefilter

**Comment by zirain** [comment]
> Yes you can use access log filters and the runtime filter: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-runtimefilter

thanks matt, accesslog support cel-filter, can we do same on tracing?

**Comment by mattklein123** [comment]
> thanks matt, accesslog support cel-filter, can we do same on tracing?

I'm not sure. cc @mathetake who has been doing work in this area.

**Comment by kyessenov** [comment]
CC @douglas-reid. Runtime and logic filters for tracing sound nice.

**Comment by zirain** [comment]
after talk with @douglas-reid , I think cel-filter can not support this.
for now, we may set sampling to 100% then do some filter on downstream(OpenTelemetry etc.)

**Comment by noah8713** [comment]
@zirain since use case is pretty much similar for our side. However due to high traffic volume, we have to sample response_code with few % and keep reporting non 200 ones. 


Tried below access log filter, with envoy 1.18.2 based on https://github.com/envoyproxy/envoy/blob/main/source/common/access_log/access_log_impl.cc#L132  it just does random selection so not clear how sampling will work with 200s as expected when using runtime_key as null as we dont use x-request-id. 

Tried below approach but it seems not sure if non-200 oks will be sampled more in this case. 
```
          access_log:
          - filter:
              and_filter:
                filters:
                - not_health_check_filter: {}
                - runtime_filter:
                    runtime_key: "200"
                    percent_sampled:
                      numerator: 1
                      denominator: "MILLION"
                    use_independent_randomness: true
                - or_filter:
                    filters:
                    - not_health_check_filter: {}
                    - status_code_filter:
                        comparison:
                          op: GE
                          value:
                            default_value: 201
                            runtime_key: "null"
                    - status_code_filter:
                      comparison:
                        op: LE
                        value:
                          default_value: 199
                          runtime_key: "null"
````

Did you explore this via filter or should we just keep doing sampling as 100% and let als or other otel service handle the filteration?
