### ISSUE TITLE
Using HTTP_PROXY with ext authz http filter

### ISSUE THREAD

**Issue by Mariappan** [envoyproxy/envoy#19696]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Using HTTP-PROXY with ext authz http filter*

*Description*:
Our setup:

                                 Service
                                     ^
                                     |
    Incoming req ---->     Envoy(sidecar) ----> ExtAuthz  ------> SquidHTTPproxy ---> External Auth server

Envoy is running as a sidecar with our service and Envoy is configured with ext_authz to do authentication to the external server. 
The setup works with our environments.

There is one environment where we need to route the external (auth) traffic through http proxy (squid proxy)
I found some examples from old issues which looked similar:

https://github.com/envoyproxy/envoy/issues/17592
https://gist.github.com/cortex93/6d7cd9738b077d0447ab891cbacd0d5e
https://gist.github.com/grzegorz-mirek/c028a24ec2b32dfa47b1fdb904ed3baa#file-loopback-yaml-L86

But the difference in my case is, the request is the one generated from envoy and not the original request. 
I am not sure, i understand the above example loop-back configs fully. I am still figuring it out.

Can someone point me, whether i am proceeding in the correct direction?
Any help is greatly appreciated. Thanks.

`envoy  version: 8fb3cb86082b17144a80402f5367ae65f06083bd/1.16.0/Clean/RELEASE/BoringSSL`
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Mariappan** [comment]
Ok I finally managed to compose envoy config using the above examples, which works for my setup. I post my config below for  reference in future.
I have some ugly lua filters to replace Host header. I tried host_rewrite which break my use-case.

>    Original `Host` header has to reach the internal protected service,
>    but Host header has to be changed to external service host name,
>    while forwarding to ext_authz service.

One other thing to note is that it works with `envoy 1.21.0` and not with `1.16.0`. So i upgraded our envoy version.

```yaml
static_resources:
  listeners:
  - name: api_proxy_listener
    address:
      pipe:
        path: "@/cluster_0"
    filter_chains:
      - filters:
          - name: tcp
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp_stats
              cluster: proxy_cluster
              tunneling_config:
                hostname: auth.external.com:443
  - name: main_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 16030
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          use_remote_address: true
          xff_num_trusted_hops: 1
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_cluster
                  upgrade_configs:
                    - upgrade_type: "websocket"
                      enabled: true
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local originalHost = request_handle:headers():get("Host")
                  request_handle:streamInfo():dynamicMetadata():set("originalHost", "host", originalHost)
                  request_handle:headers():replace("Host", "auth.external.com")
                end
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              http_service:
                server_uri:
                  uri: squid.default.svc.cluster.local
                  cluster: loopback_cluster
                  timeout: 2s
                path_prefix: /auth_check
                authorization_request:
                  headers_to_add:
                    - key: X-Forwarded-Host
                      value: "%DYNAMIC_METADATA([\"originalHost\", \"host\"])%"
              failure_mode_allow: false
              include_peer_certificate: false
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local originalHost = request_handle:streamInfo():dynamicMetadata():get("originalHost")["host"]
                  request_handle:headers():replace("Host", originalHost)
                end
          - name: envoy.filters.http.router
            typed_config: {}
  clusters:
  - name: loopback_cluster
    connect_timeout: 5s
    upstream_connection_options:
      tcp_keepalive: {}
    type: static
    load_assignment:
      cluster_name: loopback_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: "@/cluster_0"
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: auth.external.com
  - name: proxy_cluster
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: proxy_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: squid.default.svc.cluster.local
                    port_value: 3128
  - name: local_cluster
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: local_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 16040
```
