### ISSUE TITLE
[Help] Got ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by darmawan01** [envoyproxy/envoy#19732]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Got ERR_TOO_MANY_REDIRECTS*

*Description*:
Here is the envoy config:
```
static_resources:
  listeners:
  - name: http_redirector
    address:
      socket_address: {address: 0.0.0.0, port_value: 80}

    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                redirect:
                  path_redirect: "/"
                  https_redirect: true
          http_filters:
          - name: envoy.router
            config: {}

  - name: https_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:

      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          upgrade_configs:
          - upgrade_type: "websocket"
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
          route_config:
            name: registration_route
            virtual_hosts:

            - name: dhis
              domains: ["dhis.org:443", "dhis.org"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: dhis
                  timeout: 360s

          http_filters:
          - name: envoy.gzip
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.gzip.v2.Gzip
              memory_level: 9
              compression_level: BEST
          - name: envoy.router

      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                  filename: "/etc/letsencrypt/live/dhis.org/fullchain.pem"
                private_key:
                  filename: "/etc/letsencrypt/live/dhis.org/privkey.pem"

  clusters:

  - name: dhis
    connect_timeout: 30s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: myhost, port_value: 8080 }}]
```

Using the envoy to pass the request to dhis2 services, dhis2 is java app that using tomcat for server. got `ERR_TOO_MANY_REDIRECTS` . i don't get it what's wrong. maybe someone has any idea ?

[dhis2 deploy guide](https://developers.dhis2.org/blog/2019/10/dhis2-and-docker/#dhis2-with-empty-postgres-database-using-docker-compose)

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
