### ISSUE TITLE
STARTTLS for SMTP

### ISSUE THREAD

**Issue by NotoriousBIT** [envoyproxy/envoy#19765]
*Title*: *How to set up STARTTLS for SMTP?*

*Description*:
Has anyone ever used STARTTLS extension for use with SMTP? I have a setup where envoy is handling TLS termination in front of postfix. Now I would like to also support STARTTLS, but could not get it to work. I’m wondering if the extension even is supposed to work with SMTP.

I googled for hours but couldn’t find an example. Did anyone ever tried it and could share some code?

My setup looks something like this:
```
  static_resources:
    listeners:
      # Mail POSTFIX STARTTLS
      - name: listener_mail_postfix_starttls
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 25
        filter_chains:
          - filters:
              - name: envoy.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: ingress_tcp
                  cluster: mail_postfix
            transport_socket:
              name: envoy.transport_sockets.starttls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.StartTlsConfig
                cleartext_socket_config:
                tls_socket_config:
                  common_tls_context:
                    # For rolling certs
                    tls_certificate_sds_secret_configs:
                      name: tls_sds_mail
                      sds_config:
                        path: /etc/envoy/sds-mail.yaml

      # Mail POSTFIX TLS
      - name: listener_mail_postfix
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 465
        filter_chains:
          - filters:
              - name: envoy.tcp_proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: ingress_tcp
                  cluster: mail_postfix
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  # For rolling certs
                  tls_certificate_sds_secret_configs:
                    name: tls_sds_mail
                    sds_config:
                      path: /etc/envoy/sds-mail.yaml

    clusters:
      # Mail postfix
      - name: mail_postfix
        dns_refresh_rate: 30.00s
        connect_timeout: 1.00s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        transport_socket:
          name: envoy.transport_sockets.upstream_proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
            config:
              version: V1
            transport_socket:
              name: envoy.transport_sockets.raw_buffer
        load_assignment:
          cluster_name: mail_postfix
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: mail-postfix
                        port_value: 25
```
