### ISSUE TITLE
Default JWT locations in JwtProvider does not overrides by explicit from_cookie location. v1.21.0

### ISSUE THREAD

**Issue by DzianisH** [envoyproxy/envoy#19772]
In the `extensions.filters.http.jwt_authn.v3.JwtAuthentication` confing I have a `extensions.filters.http.jwt_authn.v3.JwtProvider` config like the followin:

```yaml
                        cookie_jwt_provider:
                          issuer: "issuer"
                          local_jwks:
                            filename: /my/path/key.txt
                          forward: true
                          forward_payload_header: "my-claims"
                          from_cookies:
                            - my_jwt_cookie
        #                  from_headers:
         #                   - name: workaround
```

When I run config with such provider on Envoy 1.21.0 I see that Envoy accepts authorization via `my_jwt_cookie`, but it also accepts authorization via default locations (query param `access_token` and HTTP header `Authorization` with `Bearer ` prefix.

It looks like a bug, and the only way for me to reject authorization via default locations is to explicitly define a non-empty list of `from_headers` or/and `from_params` locations.

For instance: with config as above Envoy will expect JWT in any of these 3 locations (`my_jwt_cookie` cookie, `Authorization` header and `access_token` query param).
If you uncomment config tail then Envoy will expect JWT only in 2 locations (`my_jwt_cookie` cookie and `workaround` header).
