### ISSUE TITLE
Can envoy queue requests while rate limiting?

### ISSUE THREAD

**Issue by JoseAlvarezSonos** [envoyproxy/envoy#19773]
*Title*: Can envoy queue requests while rate limiting?

*Description*:
We have setup an Envoy proxy configured with Envoy RateLimit. We have a simple setup where we have 3 paths, and each one of them has a global rate limit, something like this:

```
domain: apis
descriptors:
  - key: generic_key
    value: foobar1
    rate_limit:
      unit: second
      requests_per_unit: 10
  - key: generic_key
    value: foobar2
    rate_limit:
      unit: second
      requests_per_unit: 5
  - key: generic_key
    value: foobar3
    rate_limit:
      unit: second
      requests_per_unit: 1
```

Then we have the envoy proxy conf like this:

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: nginx
              domains: ["*"]
              routes:
              - match:
                  prefix: "/foobar1"
                route:
                  cluster: nginx_1
                  include_vh_rate_limits: true
                  rate_limits:
                    - stage: 0
                      actions:
                        - {generic_key: {"descriptor_value": "foobar1"}}
              - match:
                  prefix: "/foobar2"
                route:
                  cluster: nginx_1
                  include_vh_rate_limits: true
                  rate_limits:
                    - stage: 0
                      actions:
                        - {generic_key: {"descriptor_value": "foobar2"}}
              - match:
                  prefix: "/foobar3"
                route:
                  cluster: nginx_1
                  include_vh_rate_limits: true
                  rate_limits:
                    - stage: 0
                      actions:
                        - {generic_key: {"descriptor_value": "foobar3"}}
              - match:
                  prefix: "/"
                route:
                  cluster: nginx_1
          http_filters:
          - name: envoy.rate_limit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
              domain: apis
              failure_mode_deny: false
              rate_limit_service:
                transport_api_version: v3
                grpc_service:
                  envoy_grpc:
                    cluster_name: rate_limit_cluster
                  timeout: 0.25s
          - name: envoy.filters.http.router

  clusters:
  - name: nginx_1
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: nginx_1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: nginx-address
                    port_value: 80
  - name: rate_limit_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: rate_limit_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ratelimit-address
                    port_value: 80
```

My question is, could we have some sort of queueing in the proxy, so when the ratelimit replies with 429 (since it's rate limiting) it tries whenever there is "free space" to keep doing requests? (even though that implies each request to take longer). The idea is to maximize the usage of the available bandwidth. TBH I'm having trouble even finding the right wording for this approach to look for related information in the envoy repos. We chose this approach since it's easier to "optimize" the usage of the available bandwidth given the rate limiting from the proxy than from somewhere else. If you think this is the wrong approach I would also highly appreciate your comments and/or suggestions.

Thanks a lot in advance 🙏 .
