### ISSUE TITLE
proxy_connect.yaml - example not working

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#19794]
Hi, 

I'm trying to proxy a CONNECT request from a L1 envoy to a L2 envoy which will terminate it.

However when applying the configuration provided in **envoy/configs/proxy_connect.yam**l the L1 envoy is not forwarding the CONNECT upstream... the upstream L2 envoy  (configured with **terminate_http2_connect.yaml**) receives the raw tcp payload and logs **dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD**

Tested this on Envoy versions 1.21.0 and 1.20.0.
Can you help me with this issue?

BR,
Stoyan

**Comment by 53jk1** [comment]
Can you provide configuration files and reproduce steps?

**Comment by pxpnetworks** [comment]
**proxy_connect.yaml**

```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9902
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: cluster_0
                  upgrade_configs:
                  - upgrade_type: CONNECT
          http_filters:
          - name: envoy.filters.http.router
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: cluster_0
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 10002
```

**terminate_http2_connect.yaml**
```

admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9903
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 10002
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: service_google
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
          http_filters:
          - name: envoy.filters.http.router
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
```

tcpdump on port 10002 shows receiving Client Hello after the tcp handshake. I guess it should be the HTTP CONNECT req.
so i think proxy_connect.yaml is not forwarding the CONNECT req upstream somehow.

Testing this with curl -XGET https;//www.google.com -x http://127.0.0.1:10001
*   Trying 127.0.0.1:10001...
* Connected to 127.0.0.1 (127.0.0;1) port 10001(#0)
* allocate connect buffer! 
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.80.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< date: Thu, 03 Feb 2022 09:03:51 GMT
date: Thu, 03 Feb 2022 09:03:51 GMT
< server: envoy
server: envoy
<

* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
* Closing connection 0
