### ISSUE TITLE
Override the default configuration problem

### ISSUE THREAD

**Issue by 53jk1** [envoyproxy/envoy#19795]
I'm trying to override the default configuration based on examples in the documentation. I don't know if this is exclusively in my case, but I do everything one by one as it is in the documentation to get to know Envoy better.

Command that I am trying to execute.
```
docker run --rm -it \
      -p 9902:9902 \
      -p 10000:10000 \
      envoyproxy/envoy-dev:0369a62110c04668d982bc37738342ff7148acff \
          -c /etc/envoy/envoy.yaml \
          --config-yaml "$(cat envoy-override.yaml)"
...
```
File with config:
$ cat envoy-override.yaml
```
admin:
        address:
        socket_address:
                address: 127.0.0.1
                port_value: 9902
```

Error message
```
[2022-02-03 09:21:31.874][1][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy/envoy.yaml': yaml-cpp: error at line 2, column 9: illegal map value
```

OS: Ubuntu 20.04 LTS
Using Docker (Linux image)
