### ISSUE TITLE
route mach on # not working

### ISSUE THREAD

**Issue by asayah** [envoyproxy/envoy#19803]
using a config like this: 

```
admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9901}

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: {address: 0.0.0.0, port_value: 10000}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: demo
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: {prefix: "/something/#/status"}
                direct_response:
                  status: 200
                  body:
                    inline_string: "matched #\n"
              - match: {prefix: "/"}
                route: {cluster: demo, timeout: 60s}                
          http_filters:
          - name: envoy.filters.http.router
```

`curl localhost:10000/something/#/status` doesn't work 
Tested with Prefix and Exact matching
