### ISSUE TITLE
HeaderAppendAction is ignored

### ISSUE THREAD

**Issue by enzo-cappa** [envoyproxy/envoy#19856]
*Title*: *HeaderAppendAction is documented but doesn't seem to do anything in practice*

*Description*:

The [HeaderAppendAction configuration](https://github.com/envoyproxy/envoy/blob/9d5627a0879b0a029e90515137c108e1d2884bfc/api/envoy/config/core/v3/base.proto#L334-L348) if supposed to allow the behaviour when setting headers. This configuration is also exposed in the [public documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto.html?highlight=add_if_absent#enum-config-core-v3-headervalueoption-headerappendaction).

However, in practice this does nothing. I think this configuration was part of a bigger change that was never merged: [PR#18130](https://github.com/envoyproxy/envoy/pull/18130). I don't find any reference to it in the code. 

*Repro steps*:

example route config:

```yaml
              route_config:
                name: "all-routes"
                virtual_hosts:
                  - name: "all-routes"
                    domains:
                      - "*"
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          cluster: protected-service
                request_headers_to_add:
                  - header:
                      key: "request-header-expected"
                      value: "%REQ(optional-header-a)%"
                    append_action: 1 # ADD_IF_ABSENT
                  - header:
                      key: "request-header-expected"
                      value: "%REQ(optional-header-b)%"
                    append_action: 1 # ADD_IF_ABSENT
```

*Expectation*: if `request-header-expected` is passed, it should be used. Otherwise it should try to use `optional-header-a`, and that one is not set it should use `optional-header-b`

*Actual result*: The server behind Envoy will get `request-header-expected` with three values when all headers as passed instead of one:
```bash
curl -v "http://localhost:8786/hello_world/" -H "optional-header-a: val2" -H "optional-header-b: val3" -H "request-header-expected: val1"
```

The internal service receives the header: 
```
'request-header-expected': 'val1, val2, val3',
```

I expect it to be

```
'request-header-expected': 'val1',
```

It sounds like the code for `HeaderAppendAction` was merged by mistake so it has to be reverted ([commit](https://github.com/envoyproxy/envoy/commit/01b90ef20f0cdb4c81f23f689bc22488641c9987)). Or [PR#18130](https://github.com/envoyproxy/envoy/pull/18130) must be merged to implement this functionality.
