### ISSUE TITLE
Is possible for Envoy to manage distinct protocols/ports that targets same 'targetPort' on pod?

### ISSUE THREAD

**Issue by paoloyx** [envoyproxy/envoy#19980]
## Description
The environment

* Envoy version: `4cc266a75a84435b26613da6df6c32b4a2df4f3e/1.16.3-dev/Clean/RELEASE/BoringSSL`
* Istio version: `1.8.3`

I have a Deployment on Istio with two services that expose different ports/protocols but map to same targetPort on backing Pod.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: grpc-server:latest
        ports:
           ​- name: http-web
             ​containerPort: 9000
             ​protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-http
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
   - port: 9000
     ​targetPort: http-web
     ​protocol: TCP
     ​name: http
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-grpc
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
   - port: 9000
     ​targetPort: http-web
     ​protocol: TCP
     ​name: grpc
---
```

## The "problem"
Envoy is selecting a protocol from one of two services, and uses that protocol to deal with requests from both services, even they should serve distinct purposes (http vs grpc)

As Kubernetes allows to have duplicate `targetPort` into Services, is possible to manage Envoy to use the right protocol depending of service port the traffic is originating from? Is something that is related to Istio, more than Envoy?

[optional *Relevant Links*:]
* https://github.com/istio/istio/issues/9926
* https://github.com/istio/istio/issues/33379
* https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/
* https://github.com/kubernetes/kubernetes/issues/47222
