### ISSUE TITLE
Listener: Should we allow to listen on ipv4-mapped ipv6 address and the same ipv4 address at same time.

### ISSUE THREAD

**Issue by soulxu** [envoyproxy/envoy#19981]
This is also found when working on https://github.com/envoyproxy/envoy/pull/19716#pullrequestreview-884003540

But this seems a separate topic, so file another issue, and suppose to be a separated PR also.

Envoy allows to listen on `::FFFF:192.168.0.1` with ipv4_compat flag and `192.168.0.1` at same time. But both the requests are from  `::FFFF:192.168.0.1` and `192.168.0.1` will go to the ipv4 listener.

And `netstat -antp` shows that only `192.168.0.1` was listening on the linux. Seems from the kernel level `::FFFF:192.168.0.1` consider as `192.168.0.1`

So this seems a useless use-case, should we reject this from the API?

Envoy also allows to listen on `::` with ipv4_compat flag and `0.0.0.0`, but the requests from ipv4 will go to the ipv4 listener, and the requests from ipv6 will go to the ipv6 listener. This seems workable use-case. Probably worth to check this is valid case or not also.

those tested by this simple config:
```
static_resources:
  listeners:
  - name: ipv6_listener
    enable_reuse_port: true
    address:
      socket_address:
        protocol: TCP
        address: "::FFFF:172.41.3.14"
        port_value: 13333
        ipv4_compat: true
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 201
          http_filters:
          - name: envoy.filters.http.router
  - name: ipv4_listener
    enable_reuse_port: true
    address:
      socket_address:
        protocol: TCP
        address: "172.41.3.14"
        port_value: 13333
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 202
          http_filters:
          - name: envoy.filters.http.router
```

And using `curl -v HTTP://[ipv4]/[ipv6]:13333` to trigger the request.
