### ISSUE TITLE
CORS issue proxying gRPC connect error 99

### ISSUE THREAD

**Issue by rmwarns** [envoyproxy/envoy#20008]
*Description*:
I'm working on testing a small application to connect a JS frontend to a gRPC API endpoint through envoy proxy. The service itself is working if I hit it directly (e.g. with another client). I'm using docker on Windows as my dev environment.

When I initialize the gRPC client, the underlying request gets logged as a CORS error. The request headers sent are all listed under allow_headers

When I hit the full API endpoint directly, I get the following:

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: immediate connect error: 99
```

I don't see any console output that would point to the issue, and in the /clusters page in the admin view only the direct/full URI connections are incrementing the cx_connect_fail counter.

*Repro steps*:
Deploy using provided yaml file, docker on windows, and attempting to access the socket_address for the defined listener. The gRPC server (on port 8182) and the server serving the webapp are running on my local host

*Admin and Stats Output*:
**/clusters** - cx_connect_fail increments on direct/full API hits (e.g. http://localhost:8081/MyGrpcApi/GetData) 
```
my_service::observability_name::my_service
my_service::default_priority::max_connections::1024
my_service::default_priority::max_pending_requests::1024
my_service::default_priority::max_requests::1024
my_service::default_priority::max_retries::3
my_service::high_priority::max_connections::1024
my_service::high_priority::max_pending_requests::1024
my_service::high_priority::max_requests::1024
my_service::high_priority::max_retries::3
my_service::added_via_api::false
my_service::0.0.0.0:8182::cx_active::0
my_service::0.0.0.0:8182::cx_connect_fail::2
my_service::0.0.0.0:8182::cx_total::0
my_service::0.0.0.0:8182::rq_active::0
my_service::0.0.0.0:8182::rq_error::0
my_service::0.0.0.0:8182::rq_success::0
my_service::0.0.0.0:8182::rq_timeout::0
my_service::0.0.0.0:8182::rq_total::0
my_service::0.0.0.0:8182::hostname::0.0.0.0
my_service::0.0.0.0:8182::health_flags::healthy
my_service::0.0.0.0:8182::weight::1
my_service::0.0.0.0:8182::region::
my_service::0.0.0.0:8182::zone::
my_service::0.0.0.0:8182::sub_zone::
my_service::0.0.0.0:8182::canary::false
my_service::0.0.0.0:8182::priority::0
my_service::0.0.0.0:8182::success_rate::-1.0
my_service::0.0.0.0:8182::local_origin_success_rate::-1.0
```

*Config*:
**envoy.yaml** - I've tried 0.0.0.0 and 127.0.0.1 for socket addresses
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: my_service
                  max_stream_duration:
                    grpc_timeout_header_max: 0s
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,accept,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
          http_filters:
          - name: envoy.filters.http.grpc_web
          - name: envoy.filters.http.cors
          - name: envoy.filters.http.router
  clusters:
  - name: my_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 8182
```

**Dockerfile**
```
FROM envoyproxy/envoy-dev:latest
COPY ./envoy.yaml /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
