### ISSUE TITLE
route awareness tracing

### ISSUE THREAD

**Issue by tedli** [envoyproxy/envoy#20061]
*Title*: *One line description*

tracing configuration per route (virtual host)

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

According to [http.tracer](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/skywalking.proto#extension-envoy-tracers-skywalking) and [skywalking example](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/skywalking_tracing), I followed the docs, and http tracing can be achieved.

![4C03F735-E8BA-44c5-A5EE-A401AA2A66EA](https://user-images.githubusercontent.com/3324663/155053453-a6142f94-c60c-4395-a7e0-034ea0fd8a53.png)

However it's a filter-level setting, a single `v3.HttpConnectionManager` may route traffic to various different backend services. Such services may want different tracing configs like sampling rate, etc.

So is it possible to specific different tracing settings within a single `listener - filter - connection manager` in current envoy implementation? Or am I the only one who seeking tracing at route level.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by adisuissa** [comment]
cc @wbpcode @dio @lizan @Shikugawa as owners of the skywalking tracer who may know if this is possible/plausible

**Comment by Shikugawa** [comment]
@tedli AFAIK I think we can't do such a behavior. We may have the following requirements with a route specific config, such as per_filter_config. But I'm not sure the strong usecases to have.

**Comment by tedli** [comment]
Hi @Shikugawa ,

Thanks for reply. Our story is that, we want to using istio EnvoyFilter CRD to turn on/off sidecar tracing at service level (these service behind sidecar runs with APM agent). So when any service runs into terrible latency, we can easily tell it's sidecar caused this or it's just  the backend service's own fault.

And nowadays, there still some developers refuse to use service mesh, because they thought it may introduce extra uncertainty which is not necessary.

So my point of view is that this would be a strong use case.

P.S.
```yaml
# the EnvoyFilter I used
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: demo-a
  namespace: sky
spec:
  workloadSelector:
    labels:
      name: demo-a
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: ANY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: true
          tracing:
            provider:
              name: envoy.tracers.skywalking
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig
                grpc_service:
                  envoy_grpc:
                    cluster_name: skywalking-oap
                  timeout: 0.250s
                client_config:
                  service_name: demo-a-sidecar
                  instance_name: demo-a-sidecar
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        name: skywalking-oap
        type: STRICT_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
        load_assignment:
          cluster_name: skywalking
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: tracing-analysis-server.system-mf
                    port_value: 11800
```

**Comment by wbpcode** [comment]
@tedli I am not sure, but can route level `Tracing` helps? That config can be used to add some custom tags and also override the sampling rate.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-tracing

**Comment by tedli** [comment]
Hi @wbpcode ,
Thanks for pointing out. I didn't express clear above, What I actually want is to turn on/off tracing for a specific service at runtime.
I'm going to try with sampling rate -> 0 in `route_components`. Or may be this really not a general needs. I may try reusing most of envoy current tracing code, to build a wasm filter like `istio/proxy` stats do (no enough confidence :sob:).

**Comment by tedli** [comment]
Here is config I tried:

```yaml
node:
  id: envoy
  cluster: envoy
admin:
  access_log:
  - name: envoy.access_loggers.stdout
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 15000
static_resources:
  listeners:
  - name: http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8887
    access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: http
            virtual_hosts:
            - name: http
              domains:
              - "*"
              routes:
              - match:
                  prefix: /
                route:
                  cluster: http
                tracing:
                  client_sampling:
                    denominator: HUNDRED
                    numerator: 0
                  random_sampling:
                    denominator: HUNDRED
                    numerator: 0
                  overall_sampling:
                    denominator: HUNDRED
                    numerator: 0
          http_filters:
          - name: envoy.filters.http.router
          generate_request_id: true
          tracing:
            # client_sampling:
            #   value: 0
            # random_sampling:
            #   value: 0
            # overall_sampling:
            #   value: 0
            provider:
              name: envoy.tracers.skywalking
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig
                grpc_service:
                  envoy_grpc:
                    cluster_name: skywalking
                  timeout: 0.250s
                client_config:
                  service_name: sidecar
                  instance_name: sidecar
  clusters:
  - name: http
    connect_timeout: 0.25s
    type: STATIC
    load_assignment:
      cluster_name: http
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8888
  - name: skywalking
    type: STRICT_DNS
    connect_timeout: 0.25s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: skywalking
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 11800

```

I want to set sampling rate to 0% at connection manager level, 100% at route level, also I tried 100% at connection manager, and 0% at route. None of those work.

Result is if `tracing` of connection manager is not null, then 0% won't affect.
