### ISSUE TITLE
Load Balancer Subsets: support fallback metadata

### ISSUE THREAD

**Issue by MarcinFalkowski** [envoyproxy/envoy#20063]
When using Load Balancer Subsets we can define a fallback policy which tells envoy what to do if no endpoint matching route/dynamic metadata is found.

But I see no way to define fallback route/dynamic metadata, which will be used if no endpoint matching preferred metadata is found.

Let me illustrate it with following example:

<details>
  <summary>Config - Click to expand!</summary>

```yaml
static_resources:
  listeners:
  - name: listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: routes
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: { prefix: "" }
                route:
                  cluster: backend
          http_filters:
          - name: envoy.filters.http.header_to_metadata
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
              request_rules:
                - header: x-version
                  on_header_present:
                    metadata_namespace: envoy.lb
                    key: version
                    type: STRING
                  remove: false
          - name: envoy.filters.http.router
  clusters:
  - name: backend
    type: STRICT_DNS
    lb_subset_config:
      fallback_policy: ANY_ENDPOINT
      subset_selectors:
      - keys: ["version"]
        fallback_policy: NO_FALLBACK
    load_assignment:
      cluster_name: backend
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend
                port_value: 10001
          metadata:
            filter_metadata:
              envoy.lb:
                version: v1
        - endpoint:
            address:
              socket_address:
                address: backend
                port_value: 10002
          metadata:
            filter_metadata:
              envoy.lb:
                version: v2
        - endpoint:
            address:
              socket_address:
                address: backend
                port_value: 10003
          metadata:
            filter_metadata:
              envoy.lb:
                version: v3
```

</details>

There we have three endpoints of the `backend` cluster:

| endpoint | metadata    |
|----------|-------------|
| 1        | version: v1 | 
| 2        | version: v2 |
| 3        | version: v3 |

We also map header `x-version` to dynamic metadata using `header_to_metadata` filter.

I can issue following requests:

| request header `x-version` | responding endpoint         |
|----------------------------|-----------------------------|
| v1                         | 1                           |
| v2                         | 2                           |
| \<missing>                 | 1, 2 or 3                   |
| ???                        | 1 preferred, 2 if 1 is gone |

Last row with `???` is is the subject of the issue. I think it's currently not possible in envoy.

It can be achieved on the client side. Client can issue a request with `x-version: v1` first, then send a second request with `x-version: v2` if the response for the first request returned `no healthy upstream`.

But it would be nice if such flow would be possible entirely on the envoy side. Client would send a single request with 'preferred' and 'fallback' metadata and envoy would execute a fallback logic.

## Question

Is something like this possible in envoy? The solution doesn't have to be limited to lb subsets - if there is any other way please let me know.

Maybe lua script can re-issue a request with another metadata, just like it was send a second time by the client?

## Proposal

However, if this is currently impossible, I propose following extension to Load Balancer Subsets:

1. Introduce new config option in `clusters[].lb_subset_config`: `metadata_fallback_policy` with possible values: `NO_FALLBACK` (default), `FALLBACK_LIST`
  
    Example:
    ```yaml
    lb_subset_config:
        fallback_policy: ANY_ENDPOINT
        metadata_fallback_policy: FALLBACK_LIST
        subset_selectors:
        - keys: ["version"]
    ```

2. When `metadata_fallback_policy` is set to `FALLBACK_LIST`, route/dynamic metadata can have a field `fallback_list` which is a list and every list element is a metadata struct ordered by priority. In our example it would be:

    ```
    fallback_list:
    - version: v1
    - version: v2
    ```

    Such metadata can be set for example by lua (`dynamicMetadata:set`), `header_to_metadata` filter (`PROTOBUF_VALUE` type) or in a route (`metadata_match.filter_metadata`)

    Add `fallback_list` to [well known names](https://github.com/envoyproxy/envoy/blob/c75c1410c8682cb44c9136ce4ad01e6a58e16e8e/source/common/config/well_known_names.h#L44)

2. In [subset_lb.cc](https://github.com/envoyproxy/envoy/blob/c75c1410c8682cb44c9136ce4ad01e6a58e16e8e/source/common/upstream/subset_lb.cc) implement outer loop, that will repeat whole `chooseHost` logic for every metadata struct in `fallback_list` until a host is found

(All names are of course only a proposal and subject to change)

Let me know what you think. Maybe there is a better way to solve this problem?

I can try to implement this if you give a green light for the proposal
