### ISSUE TITLE
Trouble with websockets: connection closed every 15 seconds

### ISSUE THREAD

**Issue by arggh** [envoyproxy/envoy#20062]
I am comparing different load balancers / proxies to use in front of a Meteor webapp, namely Envoy, HAProxy and Nginx.

I can get the setup to work very easily with **Nginx**:

```cfg
server {
        listen 443 ssl;
        server_name myapp.com;

        location / {
                proxy_pass http://upstream/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;

                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forward-Proto http;
                proxy_set_header X-Nginx-Proxy true;

                proxy_redirect off;
        }
}
```

Even simpler with **HAProxy**:

```cfg
frontend myapp.com
        bind 0.0.0.0:80
        bind 0.0.0.0:443 ssl crt /etc/ssl/ansible/
        default_backend upstream

backend upstream
        balance roundrobin
        server server1 10.0.2.1:3000 check maxconn 20
```

...but for some reason, **every single config variation I've tried with Envoy doesn't really work**: the websocket connection gets upgraded, the response confirms `Upgrade` was succesful, but there are no keep-alive checks (_ping / pong_), instead the connection just closes after ~15 seconds, after which the Meteor client reconnects and starts a new websocket connection, which closes again after ~15 seconds.

I can switch the proxies on the fly with the same backend server running and observe how the websocket persists correctly with Nginx and HAProxy, but Envoy stubbornly keeps closing the websocket.

I've tried my best to decipher the Envoy documentation, but I'm still unsure whether this is something I've misconfigured or a bug / missing feature.

The backend / upstream server supports http2.

The Envoy version I'm using was installed following the guide for Ubuntu (focal), and the installed version is

```
root@proxy1:~# envoy --version

envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL
```

Here is my Envoy config (one of many...):

```yaml
# Recommended settings from https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge.html?highlight=use_remote_address

static_resources:
  listeners:
  - name: listener_1
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true # As per recommendations 
          normalize_path: true # As per recommendations
          merge_slashes: true # As per recommendations
          common_http_protocol_options:
            idle_timeout: 300s # As per recommendations
            headers_with_underscores_action: REJECT_REQUEST # As per recommendations
          http2_protocol_options:
#            allow_connect: true # BREAKS WEBSOCKETS
            max_concurrent_streams: 100 # As per recommendations
            initial_stream_window_size: 65536  # 64 KiB, As per recommendations
            initial_connection_window_size: 1048576  # 1 MiB, As per recommendations
          stream_idle_timeout: 300s
          request_timeout: 300s
          xff_num_trusted_hops: 0 # Don't trust, since we're on the Edge
          skip_xff_append: false # Append, please
          upgrade_configs:
          - upgrade_type: websocket
#          - upgrade_type: CONNECT # No effect whatsoever
          codec_type: AUTO
          route_config:
            name: redirect_route
            virtual_hosts:
            - name: app
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: 
                  cluster: app_cluster
                  hash_policy:
                    cookie:
                      name: sticky_session
                      ttl: "300s"
          http_filters:
          - name: envoy.filters.http.router
      transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain: {filename: "/etc/ssl/ansible/myapp.com.pem"}
                private_key: {filename: "/etc/ssl/ansible/myapp.com.key"}
              alpn_protocols: ["h2,http/1.1"]
  clusters:
  - name: app_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: RING_HASH
    load_assignment:
      cluster_name: app_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.2.1
                port_value: 3000
```

I would very much like to understand what I'm doing wrong, or if this is an issue with Envoy. Any help is much appreciated.
