### ISSUE TITLE
Ratelimit under load - grpc timeouts

### ISSUE THREAD

**Issue by JRemitz** [envoyproxy/envoy#20070]
**Title**: Ratelimit under load timeouts

**Description**:
I have an Envoy edge proxy deployed in Kubernetes, with the ratelimit service.  I'm doing some basic load testing (~100rps) expecting latency to increase however I'm seeing rate limit service errors showing up as grpc upstream timeouts to the rate limiting service.  

I've reviewed and applied/increased as many timeout settings as makes sense [from the docs](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts.html?highlight=request_timeout#http-grpc) just trying to get these to go away, but I'm not having any success.

Initially I opened a ticket, [#322](https://github.com/envoyproxy/ratelimit/issues/322) in the ratelimit repo but after debugging this feels more like an Envoy configuration issue.

I've included most of the timeout hacks that I've been trying, this is the basic configuration that I have.

```yaml
...
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              generate_request_id: true
              request_id_extension:
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
                  use_request_id_for_trace_sampling: false
              stat_prefix: ingress_http
              codec_type: AUTO
              common_http_protocol_options:
                max_connection_duration: 10s
                idle_timeout: 900s
              request_timeout: 30s
              drain_timeout: 10s
...
              http_filters:
              - name: envoy.ratelimit
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit"
                  domain: test_domain
                  rate_limit_service:
                    transport_api_version: "v3"
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ratelimit_service
                      timeout: 90s
                  failure_mode_deny: true
...
      - name: ratelimit_service
        connect_timeout: 90s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        common_http_protocol_options:
          max_connection_duration: 10s
          idle_timeout: 30s
        http2_protocol_options:
          connection_keepalive:
            timeout: 30s
        load_assignment:
          cluster_name: ratelimit_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ratelimit-ratelimit-service
                    port_value: 8081
```

Errors in the logs:
```
'grpc-status', '14'
'grpc-message', 'upstream request timeout'
[2022-02-21 16:39:36.991][13][debug][filter] [source/extensions/filters/common/ratelimit/ratelimit_impl.cc:117] rate limit fail, status=14 msg=upstream request timeout
[2022-02-21 16:39:36.991][13][debug][filter] [source/extensions/filters/http/ratelimit/ratelimit.cc:163] rate limit status, status=1
[2022-02-21 16:39:36.991][13][debug][http] [source/common/http/filter_manager.cc:947] [C271][S10347976980624733423] Sending local reply with details rate_limiter_error
[2022-02-21 16:39:36.991][13][debug][http] [source/common/http/conn_manager_impl.cc:1472] [C271][S10347976980624733423] encoding headers via codec (end_stream=true):
':status', '500'
[2022-02-21 16:39:36.991][13][debug][router] [source/common/router/router.cc:924] [C0][S10762015607805821320] upstream timeout
[2022-02-21 16:39:36.991][13][debug][router] [source/common/router/upstream_request.cc:341] [C0][S10762015607805821320] resetting pool request
[2022-02-21 16:39:36.991][13][debug][client] [source/common/http/codec_client.cc:142] [C53] request reset
[2022-02-21 16:39:36.991][13][debug][pool] [source/common/conn_pool/conn_pool_base.cc:209] [C53] destroying stream: 1 remaining
[2022-02-21 16:39:36.991][13][debug][http2] [source/common/http/http2/codec_impl.cc:1128] [C53] sent reset code=0
[2022-02-21 16:39:36.991][13][debug][http2] [source/common/http/http2/codec_impl.cc:1241] [C53] stream closed: 0
[2022-02-21 16:39:36.991][13][debug][http] [source/common/http/async_client_impl.cc:101] async http request response headers (end_stream=true):
```

**Comment by daixiang0** [comment]
> [2022-02-21 16:39:36.991][13][debug][http] [source/common/http/conn_manager_impl.cc:1472] [C271][S10347976980624733423] encoding headers via codec (end_stream=true):
':status', '500'

500 means internal server error I think.

**Comment by daixiang0** [comment]
> [2022-02-21 16:39:36.991][13][debug][http] [source/common/http/conn_manager_impl.cc:1472] [C271][S10347976980624733423] encoding headers via codec (end_stream=true):
':status', '500'

500 means internal server error I think.

**Comment by JRemitz** [comment]
Correct. There is no corresponding error entry in the upstream rate limit server. Based on the logs, it appears the connection in the connection pool is timing out waiting to connect to see if the rate limit has been exceeded before connecting upstream. I have to imagine that's happening pretty quickly and any level of latency is reaching that threshold. I can't find a timeout setting (or other) that has an impact to this. 

Even if it means the request takes 1s, 5s, 10s? I'd rather troubleshoot that but the request is getting killed. Scaling pods to either Envoy or Ratelimit appears to have no affect either.

**Comment by JRemitz** [comment]
Also, I'm past the fact that the 500 was returned. [It's is expected](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/rate_limit_filter#config-http-filters-rate-limit) when there's an issue with the server based on my configuration. I just want to understand how to configure this for the volume of requests I'm sending.

**Comment by JRemitz** [comment]
OMG... there's a `timeout` on the [Ratelimit extension](https://www.envoyproxy.io/docs/envoy/v1.21.0/api-v3/extensions/filters/network/thrift_proxy/filters/ratelimit/v3/rate_limit.proto.html?highlight=rate_limit_service#extensions-filters-network-thrift-proxy-filters-ratelimit-v3-ratelimit)?
> timeout
>
>    ([Duration](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#duration)) The timeout in milliseconds for the rate limit service RPC. If not set, **this defaults to 20ms**.

I'm so confused... what's the point of this with a `grpc_service.timeout` as well?  Would love some clarity there, I have so many "timeouts" set, including the cluster and headers and stream... 😵 

Here is my final configuration. For me, it was the `ratelimit.timeout: 5s` that fixed it.  I'll be doing more cleanup because this probably doesn't make sense however at least I found something that gets me to the next settings. I'm getting 100% mix of 200s/429s now when I hammer the service. 

```yaml
              http_filters:
              - name: envoy.ratelimit
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit"
                  domain: api_lookups
                  timeout: 5s
                  rate_limit_service:
                    transport_api_version: "v3"
                    grpc_service:
                      envoy_grpc:
                        cluster_name: ratelimit_service
                      timeout: 5s
                  failure_mode_deny: true
```
