### ISSUE TITLE
Prometheus buckets do not have inclusive upper bound

### ISSUE THREAD

**Issue by VillePihlava** [envoyproxy/envoy#20087]
**Title**: Prometheus buckets do not have inclusive upper bound

**Description**:
According to https://prometheus.io/docs/concepts/metric_types/#histogram the output for histogram buckets should be `<basename>_bucket{le="<upper inclusive bound>"}`. However, the stats from `/stats/prometheus` seem to not include the upper bound.

**Repro steps**:
The way I ran into this was when I configured custom buckets for the cryptomb private key provider contrib extension. I ran the contrib image provided by Envoy with different configs:

`docker run --rm -ti -p 9000:9000 -p 9001:9001 -v $(pwd)/conf-1.yaml:/conf.yaml -v $(pwd)/key.pem:/tmp/key.pem -v $(pwd)/cert.pem:/tmp/cert.pem --cpuset-cpus=0-1 envoyproxy/envoy-contrib:v1.21.1 -c /conf.yaml`

`docker run --rm -ti -p 9000:9000 -p 9001:9001 -v $(pwd)/conf-2.yaml:/conf.yaml -v $(pwd)/key.pem:/tmp/key.pem -v $(pwd)/cert.pem:/tmp/cert.pem --cpuset-cpus=0-1 envoyproxy/envoy-contrib:v1.21.1 -c /conf.yaml`

Then I created a request to the configured endpoint:
`curl -k https://localhost:9000`

After a short amount of time the request should have been recorded with a value of 1:
`curl localhost:9001/stats/prometheus?filter=cryptomb`

I created the self-signed certificate used for testing with:
`openssl req -x509 -newkey rsa:2048 -nodes -subj '/CN=localhost' -keyout key.pem -out cert.pem`

**Admin and Stats Output**:
with conf-1.yaml:
`curl localhost:9001/stats/prometheus?filter=cryptomb`:
```
# TYPE envoy_listener_cryptomb_rsa_queue_sizes histogram
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="1"} 0
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="2"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="3"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="4"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="6"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="7"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="8"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="+Inf"} 1
envoy_listener_cryptomb_rsa_queue_sizes_sum{envoy_listener_address="0.0.0.0_9000"} 1.0500000000000000444089209850063
envoy_listener_cryptomb_rsa_queue_sizes_count{envoy_listener_address="0.0.0.0_9000"} 1
```

with conf-2.yaml:
`curl localhost:9001/stats/prometheus?filter=cryptomb`:
```
# TYPE envoy_listener_cryptomb_rsa_queue_sizes histogram
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="1.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="2.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="3.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="4.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="5.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="6.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="7.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="8.5"} 1
envoy_listener_cryptomb_rsa_queue_sizes_bucket{envoy_listener_address="0.0.0.0_9000",le="+Inf"} 1
envoy_listener_cryptomb_rsa_queue_sizes_sum{envoy_listener_address="0.0.0.0_9000"} 1.0500000000000000444089209850063
envoy_listener_cryptomb_rsa_queue_sizes_count{envoy_listener_address="0.0.0.0_9000"} 1
```

**Config**:
conf-1.yaml:
```
stats_config:
  histogram_bucket_settings:
    match:
      contains: "cryptomb"
    buckets: [1,2,3,4,5,6,7,8]

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9000
    filter_chains:
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              certificate_chain: { "filename": "/tmp/cert.pem" }
              private_key_provider:
                provider_name: cryptomb
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.private_key_providers.cryptomb.v3alpha.CryptoMbPrivateKeyMethodConfig"
                  poll_delay: 0.1s
                  private_key: { "filename": "/tmp/key.pem" }
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: / }
                direct_response: { status: 200 }
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001
```
conf-2.yaml (only difference to conf-1.yaml are the buckets):
```
stats_config:
  histogram_bucket_settings:
    match:
      contains: "cryptomb"
    buckets: [1.5,2.5,3.5,4.5,5.5,6.5,7.5,8.5]

...
```
