### ISSUE TITLE
[question]response_header_to_add in global route config only take effect when a request match a route-entry.

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#20104]
Here is my static config:
```
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            response_headers_to_add:
            - header:
                key: "responseflag"
                value: "%RESPONSE_FLAGS%"  
            virtual_hosts:
            - name: local_service
              domains: ["*"]        
              routes:
              - match: { prefix: "/test" }
                route:
                  cluster: some_service        
          http_filters:
          - name: envoy.filters.http.router
```
I curl listen port  with url "/aaa" and the response header would not be added.
I have seen the code , "finalizeResponseHeaders" only be called when the stream_info have route-entry.
Is there any way to add response header no matter it match route or not?
In my case ,I want add response flag to tell downstream what happend when envoy dealing with the request.
