### ISSUE TITLE
Ratelimit by count in header

### ISSUE THREAD

**Issue by JRemitz** [envoyproxy/envoy#20124]
**Title**: Ratelimit by count in header
**Description**: 
The gist of this question is whether I can use a custom rate value that does not equate to 1 per request. I would like to use a count value from a header and it's not clear to me from the documentation if this is possible. 

For example: assume a Ratelimit configuration like this:
```yaml
domain: customers
descriptors:
  - key: items
    value: books
    rate_limit:
      unit: second
      requests_per_unit: 1000
  - key: requests
    value: customer1
    rate_limit:
      unit: second
      requests_per_unit: 10
```

I want to allow only 1000 books to be returned per second at a max rate (requests) of 10 per second. 

The 10 rps is self explanatory from other examples. I'm curious if I can pass a header for the key/value of items for this customer. So they can paginate however they want but never retrieve more than 1000 books per second. Upstream will rate limit by this anyways but this allows me to stay within those boundaries at the proxy. So I can query for 100 books ten times in a second or 1000 books one time. 

Is this possible?
