### ISSUE TITLE
why `HeaderValueMatch` do not have `descriptor_key`

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#20249]
*Title*: *why `HeaderValueMatch` do not have `descriptor_key`*

*Description*:

there's a config as following:
```yaml
rate_limits:
  - actions: # any actions in here
      - header_value_match:
          descriptor_value: "true"
          expect_match: true
          headers:
            - name: :path
              prefix_match: /foo
      - header_value_match:
          descriptor_value: "true"
          expect_match: false
          headers:
            - name: :path
              string_match:
                prefix: /foo2
                ignore_case: true
```
that will populate descriptors like:

```console
[2022-03-08 10:16:07.803][1262983][debug][filter] [external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:96] populate descriptors: key=header_match value=true
[2022-03-08 10:16:07.803][1262983][debug][filter] [external/envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc:96] populate descriptors: key=header_match value=true
```
it will be better to add `descriptor_key` here? @mattklein123
