### ISSUE TITLE
Local reply modification can't overwrite content-type header

### ISSUE THREAD

**Issue by messagell** [envoyproxy/envoy#20267]
Hi, I want envoy local_reply_config to response custom html error page when upstream server is down. I found that headers_to_add can't overwrite content-type to "text/html; charset=UTF-8" when I using body.inline_string to return custom html error page. Please help me abount this.

EnovyVersion:
```
envoy  version: bdf47abe1821c37d739c7467e9c82a3885f208f0/1.19.2-dev/Clean/RELEASE/BoringSSL
```
EnvoyFilter:
```
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            local_reply_config:
              mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 503
                          runtime_key: key_b
                  headers_to_add:
                    - header:
                        key: "content-type"
                        value: "text/html; charset=UTF-8"
                      append: false
                  status_code: 500
                  body:
                    inline_string: "not allowed"
```

Test Output:
```
$ curl http://a.example.com/
not allowed

$ curl -I http://a.example.com/                                                                                                        
HTTP/1.1 500 Internal Server Error
content-type: text/plain  # Here, The content-type's value is not overwrited    
content-length: 11
date: Wed, 09 Mar 2022 04:08:26 GMT
server: istio-envoy
```

**Comment by daixiang0** [comment]
duplicate with #20266

**Comment by RyanTheOptimist** [comment]
cc: @adisuissa

**Comment by adisuissa** [comment]
IIUC the order of operations in the code:
https://github.com/envoyproxy/envoy/blob/1575185d14abc3bc508ce5a6ba45422393322551/source/common/http/utility.cc#L584-L589

which implies that first the headers are modified, and then the `content_type` is rewritten.

**Comment by messagell** [comment]
@adisuissa Thanking you for your reply, I'm confuse about how to config about this, Due to body.inline_string not support content_type parameter, so I use headers_to_add to overwrite Content-Type header, But not take affect. Can you show me example abount this.

**Comment by adisuissa** [comment]
AFAICT It is not possible to change content-type of a local-reply at the moment.
@alyssawilk can you please double check my understanding here?

**Comment by nicoche** [comment]
In case this helps anyone stuck with an older version of Envoy, I managed to make it work by (ab)using `body_format_override`:

```yaml
{
 "filter": {
     ... # Your filter(s) here
 },
 "body": {
  "inline_bytes": "..." # Your HTML here
 },
 "body_format_override": {
  "content_type": "text/html; charset=UTF-8",
  "text_format_source": {
   "inline_string": "%LOCAL_REPLY_BODY%"
  }
 }
}
```
