### ISSUE TITLE
Local reply modification can't overwrite content-type header

### ISSUE THREAD

**Issue by messagell** [envoyproxy/envoy#20266]
Hi, I want envoy response custom html error page when upstream is down. 

EnvoyVersion:
```
```

EnovyFilter:
```
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            local_reply_config:
              mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 503
                          runtime_key: key_b
                  headers_to_add:
                    - header:
                        key: "content-type"
                        value: "text/html; charset=UTF-8"
                      append: false
                  status_code: 500
                  body:
                    inline_string: "not allowed"
```
