### ISSUE TITLE
tracer: skywalking reported wrong instance name

### ISSUE THREAD

**Issue by JaredTan95** [envoyproxy/envoy#20288]
*Title*: *skywalking reported the service name as instance name in tracing segment data*

*Description*:
from docs, skywalking tracer extions could config `servicename` and `instance name` as following:
```yaml
...
          tracing:
            provider:
              name: envoy.tracers.skywalking
              typed_config:
                "@type": type.googleapis.com/envoy.config.trace.v3.SkyWalkingConfig
                grpc_service:
                  envoy_grpc:
                    cluster_name: skywalking
                  timeout: 0.250s
                client_config:
                  service_name: service1-envoy
                  instance_name: service1-envoy-1
...
```

but, I found that `skywalking oap`(skywalking backend, a commponent to receive tracing data from envoy) received the instance name as the same as the service name. That's may be wrong.
