### ISSUE TITLE
Upstream connect error with TLS error: 33556294:system library:OPENSSL_internal:unknown error

### ISSUE THREAD

**Issue by TPB555** [envoyproxy/envoy#20303]
Hi

I have configured Envoy with one listener with TLS and one upstream cluster with TLS too. Envoy and the upstream cluster are running on the different machine. The lister and upstream cluster's TLS has been configured as below,

```
# listener config
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route_http
            virtual_hosts:
            - name: local_service_http
              domains: ["*"]
              routes:
              - match: { prefix: "/api/GetCustomer" }
                route: { cluster: upstream-https, auto_host_rewrite: true, prefix_rewrite: "/MyApp/MyAPI/GetMyCustomer" }
          http_filters:
          - name: envoy.filters.http.router
          access_log:
          - name: envoy.access_loggers.file
            filter:
              not_health_check_filter: {}
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "c:/postbox/logs/envoy_access_log_L0.txt"
              log_format:
                json_format:
                    time: "%START_TIME%"
                    protocol: "%PROTOCOL%"
                    duration: "%DURATION%"
                    request_method: "%REQ(:METHOD)%"
                    request_host: "%REQ(HOST)%"
                    path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    response_code: "%RESPONSE_CODE%"
                    response_flags: "%RESPONSE_FLAGS%"
                    route_name: "%ROUTE_NAME%"
                    upstream_host: "%UPSTREAM_HOST%"
                    upstream_cluster: "%UPSTREAM_CLUSTER%"
                    upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: "c:/cacert.pem"
              private_key:
                filename: "c:/private.pem"
```

```
# upstream cluster config
  - name: upstream-https
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: upstream-https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: upstream_server
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

When trying to access the service on the upstream cluster via Envoy, the status code 503 is returned with this error message,

> upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 33556294:system library:OPENSSL_internal:unknown error

This is what I got from Envoy log,

{"response_code":503,"duration":24,"request_method":"GET","protocol":"HTTP/1.1","upstream_local_address":null,"time":"2022-03-11T01:22:28.266Z","upstream_cluster":"upstream-https","route_name":null,"path":"/api/GetCustomer","response_flags":"UF","request_host":"envoy_listener:8001","upstream_host":"cluster_ip_address:443"}

Any idea if there is anything wrong with the config or anything else to do with the certificate used on the upstream cluster?

Thank you
