### ISSUE TITLE
setting delayed close timer 200ms but still have default 1s

### ISSUE THREAD

**Issue by cobb-tx** [envoyproxy/envoy#20319]
*Title*: *setting delayed close timer but still have default 1s*

*Description*:
>i  setting delayed close timer 200ms ，but still have default 1s
why？
![image](https://user-images.githubusercontent.com/33242758/158099287-9b5d2374-fd81-41ac-b323-34d9abdd7e94.png)

*version*:
istio：1.10.0
envoy：1.18.3

**Comment by daixiang0** [comment]
Look at the following code:
https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L148-L154

Do you enable maxConnectionDuration?

**Comment by ggreenway** [comment]
@cobb-tx can you post your full envoy configuration? 

Based on what you posted, my best guess is that you have two filter chains, and only set this timeout on one of them. But I can't tell without more data.

**Comment by cobb-tx** [comment]
> @cobb-tx can you post your full envoy configuration?
> 
> Based on what you posted, my best guess is that you have two filter chains, and only set this timeout on one of them. But I can't tell without more data.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: default-backend
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            common_http_protocol_options:
              idle_timeout: 75s  # 1 hour
            stream_idle_timeout: 75s
            delayed_close_timeout: 200ms
            local_reply_config:
              mappers:
                - filter:
                    status_code_filter:
                      comparison:
                        op: EQ
                        value:
                          default_value: 404 # Replace to 401 if you want to customize for the JWT validation fail response
                          runtime_key: placeholder
                  body:
                    inline_string: "default backend - 404"

---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ingress-gateway-health-check
  namespace: istio-system
spec:
  workloadSelector:
    # select by label in the same namespace
    labels:
      app: istio-ingressgateway
  configPatches:
    # The Envoy config you want to modify
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value: # lua filter specification
          name: envoy.lua
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
            inline_code: |-
              function envoy_on_request(request_handle)
                if request_handle:headers():get(":path") == "/healthz"then
                  request_handle:respond(
                  {[":status"] = "200" },
                  "")
                end
              end

```
