### ISSUE TITLE
%RESPONSE_CODE_DETAILS% empty for response_headers_to_add

### ISSUE THREAD

**Issue by theganyo** [envoyproxy/envoy#20413]
*Description*:
When adding a response header with the value of `%RESPONSE_CODE_DETAILS%`, a normally completing request from upstream will contain no value instead of the expected `via_upstream` value. However, a similarly defined access_log entry will contain the correct `via_upstream` value.

I will attach a proposed PR that seems to solve the issue.

*Repro steps*:
Start Envoy with the following config. Note that the header value set for `x-response-code-details` is: `=%RESPONSE_CODE_DETAILS%` - this is simply to ensure there will be a value and the header will be added even when the `%RESPONSE_CODE_DETAILS%` is empty.

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: service }
                      response_headers_to_add:
                          - header:
                              key: x-response-code-details
                              value: "=%RESPONSE_CODE_DETAILS%"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config: {}
                access_log:
                    - name: envoy.access_loggers.file
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                          path: "/dev/stdout"
                          log_format:
                              json_format:
                                status: "%RESPONSE_CODE%"
                                resp_code_deets: "%RESPONSE_CODE_DETAILS%"

  clusters:
    - name: service
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: httpbin.org
                  port_value: 80

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

Attempt a curl and check the headers. Note that the `x-response-code-details` header has only the constant value of "=".
```
$ curl localhost:8080/get -i
HTTP/1.1 200 OK
date: Thu, 17 Mar 2022 22:07:37 GMT
content-type: application/json
content-length: 298
server: envoy
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 127
x-response-code-details: = 
```
And note the console output for Envoy will correctly contain the log entry:

```
{"status":200,"resp_code_deets":"via_upstream"}
```
