### ISSUE TITLE
how to use bootstrap watchdog,I can not start the envoy sidecar with error

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#20482]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
how to use bootstrap watchdog,I can not start the envoy sidecar with error.
is my action config right?
*Description*:
>Describe the issue.
I have the following config:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-bootstrap
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: BOOTSTRAP
    patch:
      operation: MERGE
      value:
          watchdogs:
            main_thread_watchdog:
              actions:
              - event: KILL
              - event: MULTIKILL
              - event: MEGAMISS
              - event: MISS
              miss_timeout: 30s
              megamiss_timeout: 20s
              kill_timeout: 10s
              max_kill_timeout_jitter: 20s
              multikill_timeout: 20s
              multikill_threshold: 
                value: 70
            worker_watchdog:
              actions:
              - event: KILL
              - event: MULTIKILL
              - event: MEGAMISS
              - event: MISS
              miss_timeout: 30s
              megamiss_timeout: 20s
              kill_timeout: 10s
              max_kill_timeout_jitter: 20s
              multikill_timeout: 20s
              multikill_threshold: 
                value: 70
```

with the fllowing error:
critical        envoy main      error initializing configuration 'etc/istio/proxy/envoy-rev0.json': Provided name for static registration lookup was empty.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
