### ISSUE TITLE
route match different path and proxy to different endpoints.  

### ISSUE THREAD

**Issue by supermanhuyu** [envoyproxy/envoy#20519]
*Description*:
> route match different path and proxy to different endpoints.  
for example: 
when user use /api/v1/svcA , it will connect to svcA
when user use /api/v1/svcB , it will connect to svcB

and i have nginx config example:

```
server {
    listen       80;
    server_name  www.example.com;

    location ~ ^/api/v1/(.*)/ {
        proxy_pass http://$1/;
    }
}
```

how can i use envoy config to replace it ？

**Comment by wbpcode** [comment]
May be simple route can achieve this:

```
                route_config:
                  virtual_hosts:
                    - name: host-one
                      domains:
                        - "server.com"
                      routes:
                        - match:
                            prefix: "/api/v1/svc1"
                          route:
                            cluster: svc1
                        - match:
                            prefix: "/api/v1/svc2"
                          route:
                            cluster: svc2
```
