### ISSUE TITLE
On-demand DNS resolution

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#20562]
*Title*: On-demand DNS resolution

*Description*:
Currently, DNS clusters (LOGICAL and STRICT), constantly resolve DNS in the background.

We see fairly common reports of DNS servers being overloaded due to having a large explosion of these clusters across many Envoy workloads sharing the same DNS server (typically this is kube-dns).

Often, these workloads are either infrequently or never actually sending requests to these clusters. However, due to the operational complexity involved with having fine grained configuration, the cluster is still present on an excessive number of Envoy instances. Even with perfect configuration, we may have a service we call once per hour but need to resolve repeatedly.

We use the respect_ttl field, so sometimes this can be fixed with a larger TTL. However, this is not always configurable, and even when it is high can still lead to thundering herd problems.

It would be ideal if we could support on-demand DNS resolution. This could be implemented in a few ways:

1. (preferred) on first request to a cluster, do DNS resolution and set timer to re-resolve (based on TTL). Once timer is ready, re-resolve only if there was any requests during this time. This means that as long as `1/QPS > TTL`, we are blocked for DNS only on the first requests. If we have infrequent requests, we only resolve once per request.

2. On the first request to a cluster, start DNS resolution like normal.

If we have full on-demand CDS this would look a lot like (2). However, I expect that will take a long time, and even when we have it this is still likely useful

**Comment by daixiang0** [comment]
Could you share more details about the case that never actually send requests, I do not hear it before. Do you mean health check?

> This means that as long as 1/QPS > TTL, we are blocked for DNS only on the first requests. If we have infrequent requests, we only resolve once per request.
Is there a cache inconsistency issue when `1/QPS > TTL` if I understand correctly?

**Comment by howardjohn** [comment]
I mean a user creates a config that results in a envoy cluster for googeapis.com being sent to a bunch of Envoy instances in the mesh. However, only 1/2 of their applications actually call googleapis.com, so we have a bunch of excess DNS requests.

Even in the 50% of instances we do depend on googleapis.com, we may call googleapis.com infrequently.

> Is there a cache inconsistency issue when 1/QPS > TTL if I understand correctly?

No, this just means we would need to perform a synchronous DNS request

**Comment by mattklein123** [comment]
Could you use dynamic forward proxy for this? Dynamic forward proxy is effectively on demand DNS. :)

**Comment by howardjohn** [comment]
Interesting, hadn't thought of that before but does seem close to what we want. One concern would be it only works for HTTP (I think?), and we would likely need cluster-per-hostname for a lot of cases to have more control. The dynamic proxy could be used in some cases though, I think

**Comment by mattklein123** [comment]
L4 has a variant called the SNI forward proxy which works the same way. I would take a look at that also. Almost certainly we can make one of these work how you want it to.

**Comment by howardjohn** [comment]
We also support just raw TCP without TLS. An example in Istio API:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-database
spec:
  addresses:
  - 1.2.3.4
  ports:
  - number: 1234
  resolution: DNS
  endpoints:
  - address: some-sql-instance.aws.com
```

What this sets up in Envoy terms is a Listener on 1.2.3.4:1234 which forwards to a STRICT_DNS cluster resolving `some-sql-instance.aws.com`.

That may just be a minor edge case though. Let me play around with the HTTP/SNI forms and see if there are any gaps

**Comment by mattklein123** [comment]
If you really needed it we could add an option to the "SNI" filter to just hard code a target if none is supplied or not TLS, etc.

**Comment by ggreenway** [comment]
It may be generally useful to have a way to delay service discovery until a cluster is used (even if it's EDS, not DNS). I think it's similar to why we have a separate healthcheck interval for clusters that have never been used.

**Comment by lambdai** [comment]
I used to explore delaying EDS request until the upstream connection is desired. A huge compleixity there, and the gain is marginal on top of ondemand CDS.

@ggreenway what's your opinion on my proposal https://github.com/envoyproxy/envoy/issues/20953 ? 

I'd like to build a notfication/callback on `endpoint ready` in the `Cluster`. The initial goal was to resolve the race condition at currrent ondemand cds, and my hunch is that the potential delayed discovery is another use case.

**Comment by keithmattix** [comment]
I took a look, and I don't think the semantics and security posture of DFS match the Istio-use case very well. Would love to investigate if we can actually achieve on-demand DNS resolution for these clusters

**Comment by nessa829** [comment]
I just find this issue, and i think this is exactly what we need ! 
Due to architectural history and issues, despite being in the same cluster, all communications are routed through domains registered in Route 53 for now. As a result, the traffic passes unnecessarily through NLB / ingressGW for communication between microservices. 
To address this easily, I tried introducing service entries as below. 
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: sre-test-entry
  namespace: sre-test
spec:
  endpoints:
  - address: sre-test.sre-test.svc.cluster.local
  hosts:
  - sre-test.example.com
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: HTTP
  resolution: DNS
```
but after registering about 100 services, CoreDNS request volume skyrocketed.
I do not understand [why this](https://istio.io/latest/docs/ops/configuration/traffic-management/dns/) is intended. 
```
This happens even if the proxy never sends any requests to these applications.
```

**Comment by ramaraochavali** [comment]
> I do not understand [why this](https://istio.io/latest/docs/ops/configuration/traffic-management/dns/) is intended.

That is only used for DNS queries made by application. DNS queries that are resolved by Envoy (similar to your Service Entry case), will go through core DNS

**Comment by keithmattix** [comment]
> > Would love to investigate if we can actually achieve on-demand DNS resolution for these clusters, carving out just a piece of DFP functionality.
> 
> 
> 
> @keithmattix  When a STRICT_DNS cluster is first time used, we trigger a DNS resolution on the first request, hold it  and initiate async DNS resolution (use the first resolution to make calls) for it so that it continues to do DNS resolutions in the background. Is that what you are thinking? Do you plan to work on this?

Sorry I missed this! I'd be happy to work/collaborate on this. I think that direction makes sense because an Envoy that never directs traffic to a cluster will never have async DNS resolution started for that cluster.

**Comment by keithmattix** [comment]
@ggreenway can you or another maintainer reopen this?

**Comment by keithmattix** [comment]
Not stale

**Comment by keithmattix** [comment]
Not stale

**Comment by aitorpazos** [comment]
Just found this issue, let me give my 2cents:

- Existing behavior, while may be putting additional load on DNS infra it has nice failure mode characteristics.
- IMO, it would be great if we can provide opt-in config to change/tweak its current behavior but will be disappointment if it goes away.
- It makes envoy resilient to issues/outages on the DNS infrastructure. As DNS traffic in many environments is still UDP, is not that uncommon to have a packet drop that times out a query on first try (environments with spikes of 1%-5% packet drops are not that uncommon). So having the health checks having navigated that for you in the background gives greater success chances for first requests.
- In very dynamic (eg: auto-scaled environments) having a first request to an envoy instance is not that uncommon.
- Envoy can withstand somewhat extended DNS outages without impacting traffic as the recently resolved and health-checked backends are fresh.

**Comment by Stevenjin8** [comment]
@ramaraochavali, @keithmattix asked me to work on this issue. Are you still looking into this?

**Comment by keithmattix** [comment]
Not stale

**Comment by ramaraochavali** [comment]
not stale

**Comment by maazghani** [comment]
definitely not stale

**Comment by Stevenjin8** [comment]
no stalebot

**Comment by Stevenjin8** [comment]
no stalebot

**Comment by Stevenjin8** [comment]
@ggreenway @markdroth I might start working on this soon and wanted to get some consensus on the general approach before starting any code. At a high level, I see two options use a a) filter or b) load balancer wrapper.

## a) Using an Extra Filter

For a), the idea is similar to dynamic forward proxy, where the on-demand resolution is triggered by a filter. The config would look as follows

```yaml
static_resources:
  listeners:
    - name: tcp_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.on_demand_dns
              typed_config:
                "@type": ...
                cluster_name: upstream_cluster
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_proxy
                cluster: upstream_cluster
  
  clusters:
    - name: upstream_cluster
      connect_timeout: 5s
      cluster_type:
        name: envoy.clusters.dns
        typed_config:
          "@type": ....
          on_demand: true
      load_assignment:
        cluster_name: upstream_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: example.com
                      port_value: 9000
```

The idea is that when the the cluster is constructed, it will not start resolving DNS as it does right now.
The filter wouldn't do much other than `onNewConnection` it would start dns resolution on the corresponding cluster and block until the first dns query is complete (plus some synchronization plumbing).

## b) Using a Load Balancer Wrapper

I'm less familiar with the load balancer implementation, so I'm not sure if this is even possible. The config would be much simpler:

```yaml
static_resources:
  listeners:
    - name: tcp_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_proxy
                cluster: upstream_cluster
  
  clusters:
    - name: upstream_cluster
      connect_timeout: 5s
      cluster_type:
        name: envoy.clusters.dns
        typed_config:
          "@type": ....
          on_demand: true
      load_assignment:
        cluster_name: upstream_cluster
        lb_policy: XYZ
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: example.com
                      port_value: 9000
```

Here, Envoy would create a load balancer that wraps around `XYZ`. It will have a `chooseHost` that first starts DNS resolution in the cluster, and then calls `XYZ`'s choose host. Or in pseudo code:

```cpp
class OnDemandDnsLoadBalancer {
  LoadBalancer inner;
  DnsCluster& cluster;
  
  HostConstSharedPtr chooseHost(...) {
    cluster.start_resolution();
    // wait for cluster to finish resolution
    return inner.chooseHost();
}
