### ISSUE TITLE
ExtAuthz: Client cert not available to the external Authz service

### ISSUE THREAD

**Issue by batistado** [envoyproxy/envoy#20563]
*Title*: ExtAuthz: Client cert not available to the external Authz service

*Description*:
Our usecase is mentioned here: https://github.com/envoyproxy/envoy/issues/20533 and I was exploring if I can use an external gRPC service that can get an ext authz request from envoy with the client cert and extract the CN to make a decision of proxying or not.

I tried to follow this guide: https://medium.com/google-cloud/envoy-external-authorization-server-envoy-ext-authz-helloworld-82eedc7f8122

And my config is below:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 127.0.0.1
      protocol: TCP
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        protocol: TCP
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: http
              domains:
              - '*'
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: dynamic_forward_proxy_cluster
                  upgrade_configs:
                  - upgrade_type: CONNECT
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              grpc_service:
                envoy_grpc:
                  cluster_name: ext-authz
                # Default is 200ms; override if your server needs e.g. warmup time.
                timeout: 0.5s
              include_peer_certificate: true
              transport_api_version: V3
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.filters.http.router
  clusters:
  - name: ext-authz
    type: static
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: ext-authz
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 50051
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
  - name: dynamic_forward_proxy_cluster_tls
    connect_timeout: 1s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
```

However, the client cert (peer certificate) is not being passed to my Auth server. 

My sample requests:
`
curl https://www.google.com --proxy http://127.0.0.1:10000 --cacert cert.pem
`

I know here is where the cert should be available: https://github.com/envoyproxy/go-control-plane/blob/main/envoy/service/auth/v3/attribute_context.pb.go#L170 but it is `null`.

Can anyone please help!
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by adisuissa** [comment]
@pradeepcrao this seems to be in an area you worked on, thoughts?
cc @mattklein123

**Comment by batistado** [comment]
Hey @pradeepcrao @mattklein123 @adisuissa, Did you guys get a chance to look at this?

**Comment by batistado** [comment]
Hey guys bumping this again as I am urgent need of this feature to correctly work! Thank you!

**Comment by dio** [comment]
@batistado 

There are several factors to make it work here:

1. The `CheckRequestUtils::setAttrContextPeer` asks for `urlEncodedPemEncodedPeerCertificate()` from the underlying (downstream) connection, and it needs to be a TLS connection. Hence the downstream connection needs to be TLS'd and ask for a valid client cert pair.
2. Given the point above, you need to send the client cert pair, optionally with the ca-cert too.

To suffice the first condition above, you need to add something (hint: DownstreamTlsContext)  like the following to your listener filter chain:

```yaml
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          require_client_certificate: true
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: path/to/ca.crt

            tls_certificates:
            - certificate_chain:
                filename: path/to/server.crt
              private_key:
                filename: path/to/server.key
```

And for the second one, your client needs to send the cert pair to the proxy (not to the upstream). Using `curl`, it is something like:

```console
curl https://www.google.com --proxy https://test.local:10000 --proxy-cert path/to/client.crt --proxy-key path/to/client.key --proxy-cacert path/to/ca.crt -v
```

Note: you can map `127.0.0.1` to test.local in your `/etc/hosts`.

Good luck!

**Comment by batistado** [comment]
This worked like a charm. Thank you so much!!

**Comment by guicassolato** [comment]
+1 to @dio's [explanation](https://github.com/envoyproxy/envoy/issues/20563#issuecomment-1085919209), excellent to understand how passing the peer certificate as an attribute of the request to ext-authz works.

I wonder whether there is a way to _avoid_ validating the client certificate in the downstream TLS context, and still get the peer certificate passed to the external authorization service. Say, e.g., the ext-authz service expects to validate the peer certificate by its own means regardless. I see a redundancy with the same also done at Envoy.

If I understand correctly, without downstream `common_tls_context.validation_context`, ext-authz's [`principal`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-peer-principal) won't refer to the leaf subject and [`certificate`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-peer-certificate) will be completely absent.

In other words, is there a config for just normal server TLS (not mTLS) and still get the client cert (non-validated by Envoy) passed to the ext-auth (if sent)?

I'm looking for something like the following:

```yaml
  listeners:
  - name: listener_0
    address: {...}
    filter_chains:
    - transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            require_client_certificate: false
            common_tls_context:
              # no validation_context here
              tls_certificates:
              - certificate_chain:
                  filename: path/to/server.crt
                private_key:
                  filename: path/to/server.key
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          route_config: {...}
          http_filters:
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              transport_api_version: V3
              grpc_service:
                envoy_grpc:
                  cluster_name: ext-authz
              include_peer_certificate: true # still get the peer certificate passed to the ext-authz service
```

I would expect [`certificate`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-peer-certificate) to be available, containing the PEM and URL encoded public client cert, and I wouldn't care about [`principal`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/service/auth/v3/attribute_context.proto#envoy-v3-api-field-service-auth-v3-attributecontext-peer-principal).
