### ISSUE TITLE
Redis Benchmark Performance

### ISSUE THREAD

**Issue by NirmalP29** [envoyproxy/envoy#20583]
I compared the envoy performance with redis cluster using redis benchmark and found the following results for client and server in different vms in same region -  

> Redis cluster - 2M requests sent from one vm to redis cluster
redis-benchmark -t set,get -n 2000000 -q -h ip -p 6379 --cluster --csv -r 100000
"test","rps","avg_latency_ms","min_latency_ms","p50_latency_ms","p95_latency_ms","p99_latency_ms","max_latency_ms"
"SET","64470.38","0.722","0.216","0.623","1.191","3.287","16.591"
"GET","61965.55","0.746","0.216","0.639","1.263","3.463","18.559"

> Redis cluster with envoy proxy - 0.66M requests sent from 3 vms to 3 envoy proxy vms total of 2 M requests
One redis server and one proxy running in one vm
redis-benchmark -t set,get -n 666666 -q -h ip -p 1999 --csv -r 100000
"test","rps","avg_latency_ms","min_latency_ms","p50_latency_ms","p95_latency_ms","p99_latency_ms","max_latency_ms"
"SET","13855.10","3.535","0.512","3.135","6.799","10.127","34.623"
"GET","18646.44","2.594","0.424","2.375","4.711","7.327","33.599"

I even tried to increase `-c` number of clients but there was no change in performance.
Why there is such difference in performance?

```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 10s
            enable_redirection: True
            enable_hashtagging: False
            read_policy: ANY
            max_buffer_size_before_flush: 1024
            buffer_flush_timeout: 0.003s
          prefix_routes:
            routes:
              - prefix: "" # Route based on prefix, keys starting with prefix_ will be written to both standard and new
                cluster: "redis_cluster"
                request_mirror_policy: [{cluster: "redis_cluster_two", exclude_read_commands: True}]
            catch_all_route:
              cluster: "redis_cluster"
  clusters:
  - name: redis_cluster
    connect_timeout: 10s
    type: static  # static
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ip1
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: ip2
                port_value: 6379
    typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
  - name: redis_cluster_two
    connect_timeout: 10s
    type: static  # static STRICT_DNS
    load_assignment:
      cluster_name: redis_cluster_two
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ip1
                port_value: 6379
        - endpoint:
            address:
              socket_address:
                address: ip2
                port_value: 6379
    typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
