### ISSUE TITLE
Cluster common_http_protocol_options requires explicit_http_config

### ISSUE THREAD

**Issue by feature-id** [envoyproxy/envoy#20628]
Hi.

Trying to configure http/1 cluster with common_http_protocol_options set and getting:
```
[2022-04-01 15:14:43.496][1][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy/envoy.yaml': Proto constraint validation failed (field: "upstream_protocol_options", reason: is required): common_http_protocol_options {
  idle_timeout {
    seconds: 600
  }
  max_connection_duration {
    seconds: 600
  }
}
```
But, if I have _explicit_http_config_ option set (with nested _http_protocol_options_ or _http2_protocol_options_), then envoy starts as expected. Also everything is fine if I completely remove _common_http_protocol_options_.

Is _explicit_http_config_ required for _common_http_protocol_options_ in cluster configuration?

Cluster config:
```
    - name: "testcluster"
      connect_timeout: 5s
      per_connection_buffer_limit_bytes: 16777216
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: LEAST_REQUEST
      health_checks:
        healthy_threshold: 3
        interval: 10s
        interval_jitter: 1s
        no_traffic_interval: 60s
        reuse_connection: true
        timeout: 5s
        unhealthy_threshold: 3
        tcp_health_check: {}
      circuit_breakers:
        thresholds:
          - max_retries: 20
      outlier_detection:
        consecutive_5xx: 5
        base_ejection_time: 30s
        max_ejection_percent: 50
        success_rate_minimum_hosts: 2
      common_lb_config:
        healthy_panic_threshold: {}
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
          common_http_protocol_options:
            idle_timeout: 600s
            max_connection_duration: 600s
      load_assignment:
        cluster_name: "testcluster"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.1.2.2
                      port_value: 8080
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.1.2.5
                      port_value: 8080
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.1.2.6
                      port_value: 8080
```

Envoy version 1.21.1.

**Comment by zuercher** [comment]
The error messages are hard to decipher, but the error is that [the upstream_protocol_options one-of](https://github.com/envoyproxy/envoy/blob/7845ef4a466e9a6c4df5667c84eab308a6834424/api/envoy/extensions/upstreams/http/v3/http_protocol_options.proto#L137), which is required, is missing a value. The oneof field name doesn't appear in the yaml, but you need to choose one of:
1. explicit upstream http protocol. For example, forcing h/2 to the upstream:
```yaml
          common_http_protocol_options:
            idle_timeout: 600s
            max_connection_duration: 600s
          explicit_http_config:
            http2_protocol_options: {} # set fields to override defaults
```
2. use the downstream client's http protocol:
```yaml
          common_http_protocol_options:
            idle_timeout: 600s
            max_connection_duration: 600s
          use_downstream_protocol_config: {} # set fields to override defaults
```
3. use an http protocol based on alpn:
```yaml
          common_http_protocol_options:
            idle_timeout: 600s
            max_connection_duration: 600s
          auto_config: {} # set fields to override defaults
```
