### ISSUE TITLE
Cannot use stateful session on route level without enabling it on listener level

### ISSUE THREAD

**Issue by iglin** [envoyproxy/envoy#20658]
Cannot use stateful session on route level without enabling it on listener level, affecting all the other routes. 

*Description*:
We are using envoy as an API gateway according to the API gateway pattern. One listener serves multiple microservices (clusters), routes are matched by path prefixes - see the configuration example in "Config" section. 

**The case is:** one of the microservices requires cookie-based stateful session feature, while other microservices requests balancing must not be affected by any cookie. So we are trying to add _envoy.filters.http.stateful_session_ filter for listener in "disabled" state and to override this filter on route level with actual cookie-based configuration. 
It appears that there is bug disallowing to configure such behavior: we cannot declare _envoy.filters.http.stateful_session_ filter in listener without specifying cookie that will be added as a "set-cookie" header in all the requests. 

*Repro steps*:

1. Run docker image envoyproxy/envoy:v1.21.1 with the yaml configuration from "Config" section. 
**Expected Result:** 
  Envoy starts successfully. 
  Envoy adds "set-cookie" response header to requests on <envoyhost>:10000/api/v1/some-service and balances the traffic according to the cookie. 
  Envoy does not add any "set-cookie" response headers for requests to <envoyhost>:10000/api/v1/another-service and balancing of another-service is not affected by any cookie. 
**Actual Result:** Envoy fails to start: see the error in "Logs" section. 

*Config*:
```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: my-gateway
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: my-gateway-routes
            virtual_hosts:
            - name: common
              domains: ["*"]
              routes:
              - match: { prefix: "/api/v1/some-service" }
                route: { cluster: some-service }
                typed_per_filter_config:
                  envoy.filters.http.stateful_session:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSessionPerRoute
                    stateful_session:
                      session_state: 
                        name: envoy.http.stateful_session.cookie
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
                          cookie:
                            name: some-service-cookie
                            path: /
                            ttl: 120s
              - match: { prefix: "/api/v1/another-service" }
                route: { cluster: another-service }
          http_filters:
          - name: envoy.filters.http.stateful_session
          - name: envoy.filters.http.router
  clusters:
  - name: some-service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: some-service
                port_value: 8080
  - name: another-service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: another-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: another-service
                port_value: 8080
```
*Logs*:
> [2022-04-04 18:53:17.812][1][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy/envoy.yaml': Proto constraint validation failed (StatefulSessionValidationError.SessionState: value is required):
[2022-04-04 18:53:17.813][1][info][main] [source/server/server.cc:925] exiting
Proto constraint validation failed (StatefulSessionValidationError.SessionState: value is required):
