### ISSUE TITLE
`request_mirror_policies` does not honor runtime keys

### ISSUE THREAD

**Issue by balena** [envoyproxy/envoy#20659]
*Title*: `request_mirror_policies` does not honor runtime keys

*Description*:
Documentation says that `request_mirror_policies` can contain runtime keys, but they are not being honored.

*Repro steps*:
At the virtual domains section, we want to mirror from canary to default clusters and vice-versa by using runtime keys.

However modifying the `request_mirror_policies` runtime keys has to effect.

I'm using DockerHub image `envoyproxy/envoy:v1.21.1`.

*Admin and Stats Output*:
- `/stats`: [stats.txt](https://github.com/envoyproxy/envoy/files/8413566/stats.txt)
- `/clusters`: [clusters.txt](https://github.com/envoyproxy/envoy/files/8413568/clusters.txt)
- `/server_info`: [server_info.txt](https://github.com/envoyproxy/envoy/files/8413574/server_info.txt)

*Config*:
```yaml
admin:
  address:
    socket_address: { address: "0.0.0.0", port_value: "9999"}
  access_log:
    name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: "/dev/null"

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: "0.0.0.0", port_value: 7000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: traffic-director
          route_config:
            name: traffic-director
            virtual_hosts:
            - name: traffic-director
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  runtime_fraction:
                    runtime_key: "routing.traffic_shift.static.canary"
                    default_value:
                      numerator: 0
                      denominator: "HUNDRED"
                route:
                  cluster: "traffic-director-canary-static"
                  request_mirror_policies:
                    - cluster: "traffic-director-default-static"
                      runtime_fraction:
                        runtime_key: "routing.mirror.static.canary"
                        default_value:
                          numerator: 0
                          denominator: "HUNDRED"
              - match:
                  prefix: "/"
                  runtime_fraction:
                    runtime_key: "routing.traffic_shift.static.default"
                    default_value:
                      numerator: 0
                      denominator: "HUNDRED"
                route:
                  cluster: "traffic-director-default-static"
                  request_mirror_policies:
                    - cluster: "traffic-director-canary-static"
                      runtime_fraction:
                        runtime_key: "routing.mirror.static.default"
                        default_value:
                          numerator: 0
                          denominator: "HUNDRED"
              - match:
                  prefix: "/"
                  runtime_fraction:
                    runtime_key: "routing.traffic_shift.logical_dns.canary"
                    default_value:
                      numerator: 0
                      denominator: "HUNDRED"
                route:
                  cluster: "traffic-director-canary-logical-dns"
                  request_mirror_policies:
                    - cluster: "traffic-director-default-logical-dns"
                      runtime_fraction:
                        runtime_key: "routing.mirror.logical_dns.canary"
                        default_value:
                          numerator: 0
                          denominator: "HUNDRED"
              - match:
                  prefix: "/"
                route:
                  cluster: "traffic-director-default-logical-dns"
                  request_mirror_policies:
                    - cluster: "traffic-director-canary-logical-dns"
                      runtime_fraction:
                        runtime_key: "routing.mirror.logical_dns.default"
                        default_value:
                          numerator: 0
                          denominator: "HUNDRED"

          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: "traffic-director-canary-logical-dns"
    connect_timeout: "0.25s"
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: "traffic-director-canary-logical-dns"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "traffic-director-canary.query.consul"
                port_value: 2016

  - name: "traffic-director-canary-static"
    connect_timeout: "0.25s"
    type: STATIC
    lb_policy: ROUND_ROBIN
    health_checks:
      - http_health_check: { path: /health }
        timeout: 5s
        interval: 5s
        unhealthy_threshold: 2
        healthy_threshold: 1
    load_assignment:
      cluster_name: "traffic-director-canary-static"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "10.13.100.88"
                port_value: 2016

  - name: "traffic-director-default-logical-dns"
    connect_timeout: "0.25s"
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: "traffic-director-default-logical-dns"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "traffic-director.query.consul"
                port_value: 2016

  - name: "traffic-director-default-static"
    connect_timeout: "0.25s"
    type: STATIC
    lb_policy: ROUND_ROBIN
    health_checks:
      - http_health_check: { path: /health }
        timeout: 5s
        interval: 5s
        unhealthy_threshold: 2
        healthy_threshold: 1
    load_assignment:
      cluster_name: "traffic-director-default-static"
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "10.13.100.87"
                port_value: 2016

layered_runtime:
  layers:
    - name: traffic-director-disk-layer
      disk_layer:
        symlink_root: /srv/runtime/current
        subdirectory: envoy
    - name: traffic-director-admin-layer
      admin_layer: {}
```

*Logs*:
[logs.txt](https://github.com/envoyproxy/envoy/files/8413576/logs.txt)

*Call Stack*:
Not crashing.
