### ISSUE TITLE
num_retries_auto (bool) AND update_frequency_auto (bool) for Nginx-like retries behavior 

### ISSUE THREAD

**Issue by amorozkin** [envoyproxy/envoy#20686]
*Title*: *num_retries_auto (bool) AND update_frequency_auto (bool) for Nginx-like retries behavior *

*Description*:

I'm trying to get kind of "Nginx-like" retries behavior with envoy
For example I have cluster like this one:
```
cluster: 
  - name: TEST
    connect_timeout: 0.25s
...
    load_assignment:
      cluster_name: TEST
      endpoints:
      - priority: 0
        lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: host01, port_value: 80 }
        - endpoint:
            address:
              socket_address: { address: host02, port_value: 80 }
        - endpoint:
            address:
              socket_address: { address: host03, port_value: 80 }
      - priority: 1
        lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: host11, port_value: 80 }
        - endpoint:
            address:
              socket_address: { address: host12, port_value: 80 }
      - priority: 2
        lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: host21, port_value: 80 }
```

Let's consider the moment the cluster is just started/created and all its hosts are considred healthy but the only really alive host is a host21.
I want to ensure the first HTTP request routed to the cluster would be tried once (host_selection_retry_max_attempts=1) per each upstream from priority P0 up to priority P2 and would reach host21 at the end

I'm trying to use "envoy.retry_host_predicates.previous_hosts" and "envoy.retry_priorities.previous_priorities" plugins to achive this as posted in docs:

```
These plugins can be combined, which will exclude both previously attempted hosts as well
previously attempted priorities.

.. code-block:: yaml

  retry_policy:
    retry_host_predicate:
    - name: envoy.retry_host_predicates.previous_hosts
    host_selection_retry_max_attempts: 1
    retry_priority:
      name: envoy.retry_priorities.previous_priorities
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.retry.priority.previous_priorities.v3.PreviousPrioritiesConfig
        update_frequency: ...
```

But it requires to have 'num_retries' and 'update_frequency' values hardcoded, which is not flexible considering the fact you can have different number of upstreams per priority...

I thought that 'num_retries' and 'update_frequency' could be calculated dynamicly depending on the current number of healthy upstreams per each priority.
Like this: 

```
num_retries_P0 = (NUM_HEALTHY_UPSTREAMS_P0 - 1) * host_selection_retry_max_attempts
num_retries_P1 = NUM_HEALTHY_UPSTREAMS_P1 * host_selection_retry_max_attempts
num_retries_P2 = NUM_HEALTHY_UPSTREAMS_P2 * host_selection_retry_max_attempts
...

num_retries = num_retries_P0 + num_retries_P1 + num_retries_P2 ...

update_frequency_P0 = NUM_HEALTHY_UPSTREAMS_P0 * host_selection_retry_max_attempts
update_frequency_P1 = NUM_HEALTHY_UPSTREAMS_P1 * host_selection_retry_max_attempts
update_frequency_P2 = NUM_HEALTHY_UPSTREAMS_P2 * host_selection_retry_max_attempts
...
```

This would add flexebility to configuration and would allow to gain some optimizations in requests retries.
