### ISSUE TITLE
tls: support for validating custom extensions in peer certificate

### ISSUE THREAD

**Issue by derekguo001** [envoyproxy/envoy#20704]
External CA may add custom extensions in certificate when it signs the CSR.
We can implement new custom cert validator to verify these extensions in peer cert.

Could we extend the default validator to make it a generic option?
So that we don't need to write the custom cert validator. 
Instead, what we need to do is specify the fields that need to be matched.

For example,
``` yaml
  - key: "1.2.3.4.5.6.7.8"
    type: "UTF8String"
    value: "custom extension value"
```

Does it make sense?

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-certificatevalidationcontext

@ggreenway @yanavlasov @PiotrSikora
