### ISSUE TITLE
Question: How to properly use google.api.httpBody with gRPC-JSON transcoder to accept arbitrary content?

### ISSUE THREAD

**Issue by rmilejcz** [envoyproxy/envoy#20772]
I am trying to accept arbitrary data via a post request, but I am unable to progress

relevant envoy config:

```
name: envoy.filters.http.grpc_json_transcoder
typed_config:
  '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
  proto_descriptor: '/data/descriptor_set.pb'
  services:
    ['HealthCheck', 'AuthService', 'TrelloSlackBot']
  auto_mapping: false
  request_validation_options:
    reject_unknown_method: false
    reject_unknown_query_parameters: false
   print_options:
     add_whitespace: true
     always_print_primitive_fields: true
     always_print_enums_as_ints: false
     preserve_proto_field_names: false
```

service definition:

```
service TrelloSlackBot {
  rpc Help(HelpRequest) returns (String) {
    option (google.api.http) = {
      post: "/v1/trelloslackbot-help",
      body: "raw_body"
    };
  }
}

message HelpRequest {
  google.api.HttpBody raw_body = 1;
}
```

I have tried altering the service definition in various ways (e.g. using google.api.HttpBody as the message input and specifying "data" as the body mapping target, not specifying a mapping target etc). The above configuration results in 500 internal server error when posting anything to that URL.

[optional *Relevant Links*:]

The documentation [describes this briefly](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter#sending-arbitrary-content) and based on this [comment / example](https://github.com/envoyproxy/envoy/issues/7411#issuecomment-830776233_) and this [pull request 10110](https://github.com/envoyproxy/envoy/pull/10110) I think I am doing this correctly but I cannot get it to work. I am unable to find any other reference for how to proceed and I'm not sure what debugging steps I could take so any help is greatly appreciated.
