### ISSUE TITLE
Significant performance degradation observed with increase in number of clients.

### ISSUE THREAD

**Issue by nikita96** [envoyproxy/envoy#20806]
**Setup :**

LB used : Envoy (running on RHEL 8, 8 core machine)

Benchmarking tool used : 
[Cppserver](https://github.com/chronoxor/CppServer)
TCP echo server
[cppserver-performance-tcp_echo_server](https://github.com/chronoxor/CppServer/blob/master/performance/tcp_echo_server.cpp)
[cppserver-performance-tcp_echo_client](https://github.com/chronoxor/CppServer/blob/master/performance/tcp_echo_client.cpp) --clients 1 --threads 1

**Envoy config file (yaml) :**
```
static_resources:
  listeners:
  - name: nb_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1559
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: postgres_cluster
          stat_prefix: tcp
  clusters:
  - name: postgres_cluster
    type: STRICT_DNS
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host1.domain.com
                port_value: 1559
```
Commands used (an example): 
Start cppserver : ./cppserver-performance-tcp_echo_server -p 1559
Send client requests : ./cppserver-performance-tcp_echo_client -a <host ip> -p 1559 -z 50 -c 600

Benchmarking results : 

https://github.com/nikita96/Envoy-performance-analysis/blob/main/envoy_perf_data.png

Could you please let me know if these results are expected or if I am missing anything?
