### ISSUE TITLE
Envoy cluster switch protocol based on what protocol upstream can speak

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#20836]
Hi team,
We have a client using one HTTP library ([armeria](https://github.com/line/armeria)) to talk to an HTTP/1.1 server. By default, it sends the HTTP/2 connection preface packet first even if the server is an HTTP/1.1 server since it doesn't know what protocol the server can speak. [link](https://github.com/line/armeria/issues/1891), then the connection is downgraded back to HTTP/1.1.

Client <---HTTP/1---> Server

<img width="1532" alt="packet_dump" src="https://user-images.githubusercontent.com/53799447/163464626-353da785-3f1c-49e0-9a87-af3abafdcd5b.png">

Our envoy configuration looks like this:
LDS:
```
resources:
  # outbound listener
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_outbound
    address:
      socket_address:
        protocol: tcp
        address: 0.0.0.0
        port_value: 16001
    traffic_direction: OUTBOUND
    listener_filters:
      - name: envoy.filters.listener.original_dst
      - name: envoy.filters.listener.http_inspector
    filter_chains:
      # http1 egress traffic
      - filter_chain_match:
          application_protocols: "http/1.1"
        filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: egress_http1
              route_config:
                name: egress_http1
                virtual_hosts:
                  - name: egress_http1_passthrough
                    domains:
                      - "*"
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          cluster: egress_http1_passthrough
              http_filters:
                - name: envoy.filters.http.router
      # http2 egress traffic
      - filter_chain_match:
          application_protocols: "h2c"
        filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: egress_http2
              route_config:
                name: egress_http2
                virtual_hosts:
                  - name: egress_http2_passthrough
                    domains:
                      - "*"
                    routes:
                      - match:
                          prefix: "/"
                        route:
                          cluster: egress_http2_passthrough
              http_filters:
                - name: envoy.filters.http.router
```

CDS:
```
resources:
  # egress http1 traffic
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: egress_http1_passthrough
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED
  # egress http2 traffic
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: egress_http2_passthrough
    type: ORIGINAL_DST
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    lb_policy: CLUSTER_PROVIDED
```
Basically, Envoy routes egress traffic using different filter chains based on the downstream application protocol. And in this config, it implicitly assumes the downstream protocol is the same as the upstream protocol (similar to use_downstream_protocol). It makes sense to make this assumption since that's the passthrough cluster.

Here is the issue we noticed:
When we add Envoy as the service mesh sidecar for the client, the client can't talk to the server anymore.
The reason is that the connection between the client and the client envoy is HTTP/2 since Envoy can understand HTTP/2, but the connection between the client envoy and the server is still HTTP/2 since we have the `explicit_http_config` in the egress_http2_passthrough cluster.

Client <---HTTP/2---> Client Envoy  <---HTTP/2---> Server

Ideally, what we want is `Client <---HTTP/2---> Client Envoy  <---HTTP/1---> Server`
When the server is also on the mesh, it will be `Client <---HTTP/2---> Client Envoy  <---HTTP/2---> Server Envoy <----HTTP/1--> Server`

It'd be great if the client envoy can choose protocol based on what the server can speak.
Is it possible to ask Envoy cluster to negotiate the protocol between itself and the server instead of using the downstream protocol or having some prior knowledge?
From [this](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto),
> Currently, Envoy only supports prior knowledge for upstream connections. 

It seems it's not supported.
If it's not supported, is the only solution asking the client to forceHTTP1?
