### ISSUE TITLE
route level http filter chain

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#20867]
*Title*: *route level http filter chain*

*Description*:
Now, http filter chain is defined in the HCM. We will iterate every filter in the chain for every request. But in some scenes, we may need different filters for different routes. **For example, the route A may need buffer filter to be enabled, and the route B may only need cache filter to be enabled.**

Although we provide composite filter as a delegator to enable/disable filter according to the headers matching, we need wrapper every filter by the composite filter and do the repeat matching.

May be we could add some new API (as followed) in the proto `Route` to enable or disable some filters in specificed route entry.
```
  message EnabledOrDisabledFilters {
    // Multiple filter names. Any name in the list MUST be one of :ref:`http filter names
    // <envoy_v3_api_field_extensions.filters.network.http_connection_manager.v3.HttpConnectionManager.http_filters>`.
    repeated string filters = 1;
    // If set to true, then all the filters referenced by the name in the ``filters`` will disabled in current route.
    bool disabled = 2;
  }

  EnabledOrDisabledFilters enabled_or_disabled_filters = 37;

```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
This would be a useful function for gateway/lb. Because they may have lots of routes and different routes may need different filters.

**Comment by wbpcode** [comment]
cc @mattklein123 @snowp

**Comment by zhxie** [comment]
I think every HTTP filters can use `ExtensionWithMatcher` to provide a filter selection (See [Filter Integration](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api#filter-integration)). But you are right, if we have many filters which need to be selected, it will become a nervous work.

Instead of `enabled_or_disabled_filters`, I suggest adding a filter which works like a filter bundle,
```yaml
- name: envoy.filters.network.http_connection_manager
  http_filters:
  - name: filter-1
  - name: filter-2
  - name: filter-bundle
    xds_matcher: /* some matcher*/
    http_filters:
      - filter-3
      - filter-4
  - name:  filter-5
```

**Comment by wbpcode** [comment]
@zhxie This is a way I have thinked about. However, for example, if we has ten different routes, then their may need different filters (an common scene in gateway), then we need created ten different filter bundle. And every request need to match this filter bundle repeatly to ensure if this filter bundle is enabled.

**Comment by snowp** [comment]
>May be we could add some new API (as followed) in the proto Route to enable or disable some filters in specificed route entry.

I think this could be implemented with minimal changes to the HCM/router: either the composite filter or something like it could be used to specify an optional filter which only applies if the per route config contains a specific entry/config. This way only optional filters have to evaluate whether or not they should be executed 

FWIW my original design for composite filters allowed specifying multiple HTTP filters by integrating more closely with the FilterManager: instead of the current behavior where it delegates to an underlying filter implementation, it would inject the resulting filters from the match result into the list of filters. We moved away from this since it was more complicated than what we needed at the time, but might be something to reconsider here.

**Comment by snowp** [comment]
+ @htuch

**Comment by wbpcode** [comment]
> an optional filter which only applies if the per route config contains a specific entry/config.

Yeah. We can design the new proto API first for the `specific entry/config`. And then we can iterate the implementation. 

`EnabledOrDisabledFilters` is my initial idea for the new proto API.

**Comment by htuch** [comment]
Is this something we need a new `Route` feature for? Or can it just be per-route filter configuration?

**Comment by wbpcode** [comment]
cc @htuch It is a new `Route` feature used to tell that which http filters should be enabled for current route.

**Comment by toddmgreer** [comment]
Whatever the APIs look like, it should be feasible to have a default filter config with per-route config overriding only what it needs to. Having many thousands or routes repeating a filter's full config could be painful. My simple-minded approach would be to have all filter config fields be optional, and just using the same proto as the per-route (or per virtual host, or per whatever).

In many cases, there will be a small set of config variants, so a possible optimization would be to let each route's config say something like `compressor_filter_override_config: "fast"`, where "fast" refers to some CompressorFilter config defined elsewhere.

**Comment by wbpcode** [comment]
I just get a new idea about the issue. Currently, `envoy.config.route.v3.FilterConfig` is used as a wrapper of the route-level filter config and additional options could be added to the `envoy.config.route.v3.FilterConfig`.

We can add to new field to the `envoy.config.route.v3.FilterConfig` to tell the envoy a filter is enabled or disabled in the specific route or vh.

Here is the example:

```
            name: local_route
            virtual_hosts:
            - name: www
              domains:
              - "*"
              typed_per_filter_config:
                # Disable the example filter
                envoy.filters.http.example:
                  "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                  is_disabled: true
                # Enable the example2 filter
                envoy.filters.http.example2:
                  "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                  is_disabled: false
                  config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.example2.v3.Example
                    foo: "bar"
                # No config wrapper for example3 filter and enable by default.
                envoy.filters.http.example3:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.example3.v3.Example
                  foo: "bar"
              routes:
              - match:
                  prefix: "/example/open"
                route:
                  cluster: backend_service
```

cc @htuch @kyessenov
