### ISSUE TITLE
Missing TLS1.2 Cipher Suite "ECDHE-ECDSA-CHACHA20-POLY1305"

### ISSUE THREAD

**Issue by Crazyigor1987** [envoyproxy/envoy#20878]
### Bug Description

The Ciphersuite "ECDHE-ECDSA-CHACHA20-POLY1305" is not available if using TLS1.2 as Protocol. I've also raised this problem to istio, but there they referred to you. [https://github.com/istio/istio/issues/38292](https://github.com/istio/istio/issues/38292)

Our Gateway Spec:
```

spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.host-domain.org'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      cipherSuites:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      credentialName: cert-secret
      maxProtocolVersion: TLSV1_2
      minProtocolVersion: TLSV1_2
      mode: SIMPLE

```

As a result, we only get CHACHA20_POLY1305 only with RSA
```

nmap --script ssl-enum-ciphers -p 443 test.host-domain.org

Starting Nmap 7.60 ( https://nmap.org ) at 2022-04-08 15:34 CEST
Nmap scan report for test.host-domain.org (10.5.12.21)
Host is up (0.011s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers:
|   TLSv1.2:
|     ciphers:
|       TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (rsa 2048) - A
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A
|     compressors:
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 1.18 seconds

```

How can we implement the missing cipher?

### Version

```
istioctl version
client version: 1.11.0
control plane version: 1.11.0
data plane version: 1.11.0 (137 proxies)
```

**Comment by moderation** [comment]
Not sure if this helps but this is how I'm specifying the ciphers for h2:
```yaml
---
transport_socket:
  name: envoy.transport_sockets.tls
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    common_tls_context:
      alpn_protocols: h2
      tls_params:
        cipher_suites:
        - "[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]"
        - "[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]"
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        tls_maximum_protocol_version: TLSv1_3
        tls_minimum_protocol_version: TLSv1_2
    sni: www.example.com
```
