### ISSUE TITLE
Use structured data (ie yaml) for changelog (version histories)

### ISSUE THREAD

**Issue by phlax** [envoyproxy/envoy#21065]
### description

Surfacing a conversation on slack with @mattklein123 ...

When adding a changelog entry, instead of editing `current.rst` as we do now we could instead add entries into a eg `changelog.yaml` file

The `current.rst` file could then be built from the yaml

This has the advantage that it would make it easier to validate/manipulate the data in the yaml file

The changelog entries would still want to be valid `rst` 

If we go down this path one question it throws up is how we store historical changelogs - ie do we just generate the `v1.X.Y.rst` file and store it as we do now, or do we retain the yaml files and leave them to be built/rendered in bazel

if we take the latter path we probs want to shift existing rst -> `changelog.v1.X.Y.yaml` and make the version_history rst entirely dynamic and not just `current.rst`

**Comment by phlax** [comment]
possible changelog format

```yaml

version: 1.23.0

behavior_changes:
# Changes that are expected to cause an incompatibility if applicable; deployment changes are likely required

- area: tls-inspector
  change: |
    the listener filter tls inspector's stats ``connection_closed`` and ``read_error`` are removed. The new stats are introduced for listener, ``downstream_peek_remote_close`` and ``read_error`` :ref:`listener stats <config_listener_stats>`.

minor_behavour_changes:
# Changes that may cause incompatibilities for some users, but should not for most
- area: thrift
  change: |
    add validate_clusters in :ref:`RouteConfiguration <envoy_v3_api_msg_extensions.filters.network.thrift_proxy.v3.RouteConfiguration>` to override the default behavior of cluster validation.
- area: tls
  change: |
    if both :ref:`match_subject_alt_names <envoy_v3_api_field_extensions.transport_sockets.tls.v3.CertificateValidationContext.match_subject_alt_names>` and :ref:`match_typed_subject_alt_names <envoy_v3_api_field_extensions.transport_sockets.tls.v3.CertificateValidationContext.match_typed_subject_alt_names>` are specified, the former (deprecated) field is ignored. Previously, setting both fields would result in an error.
- area: tls
  change: removed SHA-1 cipher suites from the server-side defaults.

bug_fixes:
# Changes expected to improve the state of the world and are unlikely to have negative effects

removed_config_or_runtime:
# Normally occurs at the end of the deprecation period
- area: compressor
  change: removed ``envoy.reloadable_features.fix_added_trailers`` and legacy code paths.
- area: dns
  change: removed ``envoy.reloadable_features.use_dns_ttl`` and legacy code paths.
- area: ext_authz
  change: removed ``envoy.reloadable_features.http_ext_authz_do_not_skip_direct_response_and_redirect`` runtime guard and legacy code paths.
- area: http
  change: deprecated ``envoy.reloadable_features.correct_scheme_and_xfp`` and legacy code paths.
- area: http
  change: deprecated ``envoy.reloadable_features.validate_connect`` and legacy code paths.
- area: tcp_proxy
  change: removed ``envoy.reloadable_features.new_tcp_connection_pool`` and legacy code paths.

new_features:

- area: access_log
  change: added new access_log command operators to retrieve upstream connection information change: ``%UPSTREAM_PROTOCOL%``, ``%UPSTREAM_PEER_SUBJECT%``, ``%UPSTREAM_PEER_ISSUER%``, ``%UPSTREAM_TLS_SESSION_ID%``, ``%UPSTREAM_TLS_CIPHER%``, ``%UPSTREAM_TLS_VERSION%``, ``%UPSTREAM_PEER_CERT_V_START%``, ``%UPSTREAM_PEER_CERT_V_END%`` and ``%UPSTREAM_PEER_CERT%``.
- area: dns_resolver
  change: added :ref:`include_unroutable_families<envoy_v3_api_field_extensions.network.dns_resolver.apple.v3.AppleDnsResolverConfig.include_unroutable_families>` to the Apple DNS resolver.
- area: ext_proc
  change: added support for per-route :ref:`grpc_service <envoy_v3_api_field_extensions.filters.http.ext_proc.v3.ExtProcOverrides.grpc_service>`.
- area: thrift
  change: added flag to router to control downstream local close. :ref:`close_downstream_on_upstream_error <envoy_v3_api_field_extensions.filters.network.thrift_proxy.router.v3.Router.close_downstream_on_upstream_error>`.

deprecated:
```
