### ISSUE TITLE
How envoy queues requests?

### ISSUE THREAD

**Issue by exhau** [envoyproxy/envoy#21121]
In my case, there are multiple grpc endpoints, each of which can only process one request at a time. It may take several seconds to several minutes to process one request.

What I need:

Envoy takes a bunch of requests, assigns one to each endpoint, and enqueues the rest. Once an endpoint finishes, envoy assigns the next in queue to this endpoint.

I have looked into "Circuit Breakers", but it just fails the requests beyond max_requests. 

```
    circuit_breakers:
      thresholds:
        - max_connections: 5
          max_pending_requests: 20
          max_requests: 5
```
Using the config above, I send 10 requests, only first 5 are successful.

I have also checked "connection pool" and tested max_concurrent_streams. It seems not relevant.

I am new to envoy. Thanks if anyone could give a hint.
