### ISSUE TITLE
Question: Can envoy be configured to use a second http/https proxy?

### ISSUE THREAD

**Issue by jojimt** [envoyproxy/envoy#21175]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Can envoy be configured to use a second http/https proxy*

*Description*:
I am using envoy as an edge proxy. There is a use case where the whole network is behind an https proxy. Is there a way to have envoy redirect to this second proxy?

i.e. client->envoy->[proxy2]->exampleorg.com

Does envoy honor the HTTP_PROXY/HTTPS_PROXY/NO_PROXY environment variables? Is there another way?

**Comment by lizan** [comment]
You need to explicitly configure them in Envoy configuration.

**Comment by jojimt** [comment]
Thanks @lizan. I was able to use the sample provided here. https://gist.github.com/grzegorz-mirek/c028a24ec2b32dfa47b1fdb904ed3baa

**Comment by Aorimn** [comment]
Hi, any pointer to this configuration documentation?

@jojimt if you could put back online the gist, that'd be really helpful 🙏

**Comment by san-ouadghiri** [comment]
So @Aorimn and a few colleagues found the solution. I thought it deserved to be shared for other folks that would be stucked like us.

So first, envoy is not taking into account local proxy configuration. For example on Windows, configuring it at the OS level doesn't do anything, it has to be explicit on the envoy config.

First solution we found was this one. Pretty straight forward and working.

client --> envoy --> upstream proxy -> exampleorg.com

```
static_resources:
  listeners:
  - name: client_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: tcp
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcpproxy
          cluster: external_proxy_cluster
          tunneling_config:
            hostname: exampleorg.com:443
  clusters:
  - name: external_proxy_cluster
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: proxy_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: my.proxy.ip
                port_value: 8888
```

But in our case we also needed to modify the call header (not the header of the proxy call, the header of the call that arrives to the service). As such we needed to perform an http filter. We did not manage to make a configuration that would both do that and be proxy-compliant. So we are doing it in two time via a an envoy loopback.

client -HTTP-> Envoy -HTTPS, add header-> Envoy -CONNECT-over-HTTP-then-HTTPS-> upstream proxy -> exampleorg.com

```
static_resources:
  listeners:
  - name: client_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: edge
          http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            request_headers_to_add:
              - header:
                  key: "myCustomHeader"
                  value: "its-value-here"
            virtual_hosts:
              - name: direct_response_service
                domains: ["*"]
                routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: itself
                      timeout: 0s
  - name: loopback_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10002
    filter_chains:
      - filters:
        - name: tcp
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: tcpproxy
            cluster: external_proxy_cluster
            tunneling_config:
              hostname: exampleorg.com:443
  clusters:
    - name: itself
      connect_timeout: 30s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: self_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 10002
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    - name: external_proxy_cluster
      connect_timeout: 30s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: proxy_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: my.proxy.ip
                  port_value: 8888
```

Hopefully this will help people stucked on this page
https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/level_two
