### ISSUE TITLE
External Authorisation for Redis via Envoy Proxy

### ISSUE THREAD

**Issue by mukundv18** [envoyproxy/envoy#21194]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: How to configure external Authorisation for Redis Server via Envoy Proxy?

*Description*:
  ```
                     Ext Authz
                          ^
                          |
                          |
Incoming req ---->     Envoy   ----> Redis Server

```

We want to use Envoy for all the traffic to Redis Server. However, we want to be able to do External Authorisation via the Envoy Configuration.
The example mentioned @ https://github.com/envoyproxy/envoy/blob/main/examples/ext_authz/config/opa-service/v3.yaml works for a HTTP request. Not sure if the same is applicable for Redis based requests.

Our filter chain is mentioned below,
```
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          prefix_routes:
            routes:
              - prefix: ""
                cluster: "redis_cluster"
```

Can we provide 'http_filters' as an additional filter? 

```
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager

```
If the HTTP filter is added, then the Lettuce Client used for Redis will not be able to talk to Envoy right?
Please guide us to get the configuration right for External Authorisation for Redis.

**Comment by dio** [comment]
@mukundv18 I think we could try the L4-flavor of ext_authz: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/ext_authz/v3/ext_authz.proto.html

**Comment by mukundv18** [comment]
Let me try this. I'll keep you posted.

**Comment by mukundv18** [comment]
This appears to work as expected. Can you guide us to get the configuration or if you are aware of any plugin to be used with this for Active Directory authentication/authorisation? Should the external authorisation service be only a gRPC service?

**Comment by mukundv18** [comment]
@dio I have added the external authorisation grpc server. However I got the following exception,
```
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /envoy.service.auth.v3.Authorization/Check
```

Then to fix this, I added the following in the cluster configuration,
```
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

Now the reported exception is as follows,
```
io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 160301007d01000079030387ca89902b078d40d46a4ac394
```

How to fix this? Please help
