### ISSUE TITLE
Nginx Module inside of cluster? socket_ip? 

### ISSUE THREAD

**Issue by dangolbeeker** [envoyproxy/envoy#21201]
Does this look like proper syntax? 
I want to implement Nginx RTMP inside of envoy. 
```
  clusters:
  - name: nginx-rtmp
    connect_timeout: 0.25s
    type: EDS
    eds_cluster_config:
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    upstream_connection_options:
      # configure a TCP keep-alive to detect and reconnect to the admin
      # server in the event of a TCP socket half open connection
      tcp_keepalive: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
```
