### ISSUE TITLE
retriable_statuses: Cannot find field 

### ISSUE THREAD

**Issue by aruandre** [envoyproxy/envoy#21232]
*Title*: *retriable_statuses: Cannot find field*

*Description*:
Trying to implement http_health_check with retriable_statuses. 
When adding the retriable_status the following error is encountered any envoy fails to start
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.clusters[1].health_checks.http_health_check) retriable_statuses: Cannot find field.) has unknown fields
No issues when omitting retriable_status property.
Per documentation retriable_statuses is under http_health_check as expected_statuses.
Tested this on envoy 1.19.1 and 1.20.3.

*Config*:
```
clusters:
- name: service_1
    connect_timeout: 60s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service_1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service_1.local
                port_value: 80
    health_checks:
      timeout: 3s
      interval: 2s
      healthy_threshold: 1
      unhealthy_threshold: 3
      http_health_check:
        path: "/status"
        expected_statuses: { start: 200, end: 499 }
        retriable_statuses: { start: 200, end: 499 }
      always_log_health_check_failures: true
      event_log_path: "/dev/stdout"
    outlier_detection:
      consecutive_5xx: 3
      interval: 10s
      base_ejection_time: 30s
      max_ejection_percent: 10
```

*Logs*:
Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.clusters[1].health_checks.http_health_check) retriable_statuses: Cannot find field.) has unknown fields
