### ISSUE TITLE
OAuth2 Filter dynamic host for token and auth endpoints URIs apart just like the redirect_uri

### ISSUE THREAD

**Issue by timmotw** [envoyproxy/envoy#21251]
OAuth2 Filter dynamic host for token and auth endpoints URIs apart just like the redirect_uri

The token and auth URI host to be extract-able from the request headers just like the `redirect_uri` e.g:

```
                token_endpoint:
                  cluster: oauth2
                  uri: "https://%REQ(x-forwarded-for)%/sso/api/oidc/token"
                  timeout: 3s
                authorization_endpoint: "https://%REQ(x-forwarded-for)%/sso/api/oidc/auth"
                redirect_uri: "https://%REQ(x-forwarded-for)%/api/v2/callback"
```

There are cases where the SSO service could running on a portable device which changes IP and this dynamic extraction of the IP is desirable.
