### ISSUE TITLE
Tunneling TCP over HTTP - to original destination cluster

### ISSUE THREAD

**Issue by panchn-n** [envoyproxy/envoy#21266]
*Title*: *Tunneling TCP over HTTP - to original destination cluster*

*Description*:
I am looking to use the TCP tunneling over HTTP feature for one of my use cases. I have been looking at the examples mentioned [here](https://github.com/envoyproxy/envoy/tree/07601069ccd8a93615f2181f8f1b6b45f7b2e5a4/configs), especially [this one](https://github.com/envoyproxy/envoy/blob/07601069ccd8a93615f2181f8f1b6b45f7b2e5a4/configs/encapsulate_in_http1_connect.yaml). The example is great and really works.

But my use case has an additional need, of connecting to dynamic host per request. So downstream host can change for every request. I am guessing the original destination cluster should cater my needs. And so this is what I have tried.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: orig-dest-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: LISTENER
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          name: proxy
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8080
          useOriginalDst: true
          filter_chains:
          - filters:
            - name: "envoy.filters.network.tcp_proxy"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
                stat_prefix: ingress_proxy
                cluster: orig_dest
                tunneling_config:
                  hostname: host.com:443
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value: # cluster specification
          name: orig_dest
          type: ORIGINAL_DST
          connect_timeout: 5s
          # This ensures HTTP/1.1 CONNECT is used for establishing the tunnel.
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http_protocol_options: {}
          original_dst_lb_config:
            use_http_header: true
          lb_policy: CLUSTER_PROVIDED
          dns_lookup_family: V4_ONLY
```
This keeps failing with error: `No downstream connection or no original_dst`

My setup uses k8s with Istio as the service-mesh. I tried posting the question there as well, [link](https://discuss.istio.io/t/tunneling-tcp-over-http-to-original-destination-cluster/12841), but maybe this should be posted here as well.

Can I use `x-envoy-original-dst-host` header to determine the original destination and tunnel TCP over HTTP as mentioned [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-tcp-over-http)?

Any pointers on what I maybe doing wrong is greatly appreciated.

Thanks!
