### ISSUE TITLE
JWT PerRouteConfig disabled is still triggered on specific case?

### ISSUE THREAD

**Issue by valeriano-manassero** [envoyproxy/envoy#21283]
I'm getting a weird behaviour on Envoy 1.22 where I have a JWT auth configured in this way:

```
         - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                jwt_token_file:
                  local_jwks:
                    filename: /opt/config/envoy/authentication-jwks.json
                  forward: true
                  forward_payload_header: x-jwt-payload
                  payload_in_metadata: jwt_payload
              rules:
                - match:
                    prefix: "/"
                  requires:
                    provider_name: "jwt_token_file"
```

everything looks good and authentication works as expected.

Then I needed to have one url-path to not use JWT auth at all so I added:
```
            - match:
                  prefix: "/nojwturl"
                route:
                  cluster: webserver
                typed_per_filter_config:
                  envoy.filters.http.jwt_authn:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
                    disabled: true
```

If I call this urlp-path **without** a token, the JWT is correctly skipped and the request is sent to the backend.

Then I noticed if I call same url-path with an expired token, I got:

```
Jwt is expired
```

I'm not sure if I misunderstood how JWT check works but, since it's disabled this call should get to the backend every time, regardless of token being there or not.

I'm not sure this is a bug or I am missing a specific configuration.
