### ISSUE TITLE
Proxy HTTP Connect - to original destination

### ISSUE THREAD

**Issue by panchn-n** [envoyproxy/envoy#21289]
*Description*:
Hello,

I have a use case where I would like to initiate HTTPConnect from downstream, proxy the connect to upstream, but the upstream can change based on the request header. My setup includes k8s with Istio service-mesh installed on it.

So far I have tried the proxy connect from the examples and it works great. Here is the working config.

`curl -x <gateway_ip>:<gateway_port> https://www.google.com -v`

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: orig-dest-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: LISTENER
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          name: proxy
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8080
          useOriginalDst: true
          filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                  - name: local_service
                    domains:
                    - "*"
                    routes:
                    - match:
                        connect_matcher:
                          {}
                      route:
                        cluster: new-cluster
                http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http_protocol_options:
                  allow_connect: true
                upgrade_configs:
                - upgrade_type: CONNECT
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value: # cluster specification
          name: new-cluster
          connect_timeout: 5s
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http_protocol_options: {}
          load_assignment:
            cluster_name: new-cluster
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 10.42.0.34
                      port_value: 2443
```

Now to implement my use case, I would like to switch the cluster to be original destination cluster. And so changed the config to look like this. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: orig-dest-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: LISTENER
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          name: proxy
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8080
          useOriginalDst: true
          filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                  - name: local_service
                    domains:
                    - "*"
                    routes:
                    - match:
                        connect_matcher:
                          {}
                      route:
                        cluster: new-cluster
                http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http_protocol_options:
                  allow_connect: true
                upgrade_configs:
                - upgrade_type: CONNECT
    - applyTo: CLUSTER
      patch:
        operation: ADD
        value: # cluster specification
          name: new-cluster
          type: ORIGINAL_DST
          original_dst_lb_config:
            use_http_header: true
          connect_timeout: 6s
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http_protocol_options: {}
          lb_policy: CLUSTER_PROVIDED
          dns_lookup_family: V4_ONLY
```

I thought by setting the `x-envoy-original-dst-host` with the above config, I should be able to send the request to the appropriate downstream host.

`curl -x <gateway_ip>:<gateway_port> -H "x-envoy-original-dst-host: <downstream_host_ip>:<downstream_host_port>" https://www.google.com -v`

>Note that my downstream host is again a proxy server.

I keep getting below in the logs
```
2022-05-13T16:56:23.150024Z     debug   envoy filter    original_dst: new connection accepted
2022-05-13T16:56:23.150080Z     debug   envoy conn_handler      [C980582] new connection from 10.42.0.1:1324
2022-05-13T16:56:23.153639Z     debug   envoy http      [C980582] new stream
2022-05-13T16:56:23.153676Z     debug   envoy http      [C980582][S3798738112104652242] request headers complete (end_stream=false):
':authority', 'www.google.com:443'
':method', 'CONNECT'
'user-agent', 'curl/7.65.0'
'proxy-connection', 'Keep-Alive'

2022-05-13T16:56:23.153702Z     debug   envoy router    [C980582][S3798738112104652242] cluster 'new-cluster' match for URL ''
2022-05-13T16:56:23.153715Z     warning envoy upstream  original_dst_load_balancer: No downstream connection or no original_dst.
2022-05-13T16:56:23.153718Z     debug   envoy upstream  no healthy host for HTTP connection pool
2022-05-13T16:56:23.153741Z     debug   envoy http      [C980582][S3798738112104652242] Sending local reply with details no_healthy_upstream

```

What is that I maybe doing wrong? Please help!

**Comment by mattklein123** [comment]
cc @kyessenov @alyssawilk

**Comment by alyssawilk** [comment]
I'm not particularly familiar with the original destination cluster but looking at the code it looks roughly correct.  One thing I'd suggest checking is the IP you are doing curl from is allowed to set x-envoy headers (is trusted) else they will be stripped.  You could try setting an explicit http_header_name which isn't x-envoy based to test that, or if you could provide me with a non-istio config I could try to debug further.

**Comment by panchn-n** [comment]
I am not sure what you mean by `IP you are doing curl from is allowed to set x-envoy headers`? 

To replicate the issue just using Envoy, I deployed Envoy on my local ubuntu VM and here is how the translated config looks like.

```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9902
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: new-cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http_protocol_options:
            {}
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: new-cluster
    type: ORIGINAL_DST
    original_dst_lb_config:
      use_http_header: true
    connect_timeout: 6s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
    lb_policy: CLUSTER_PROVIDED
    dns_lookup_family: V4_ONLY
```

Here is how the curl looks like locally
```
$ curl -x 127.0.0.1:8080 -H "x-envoy-original-dst-host: 127.0.0.1:2443" https://www.google.com -v
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.68.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Mon, 16 May 2022 18:21:11 GMT
< server: envoy
< connection: close
< 
* Received HTTP code 503 from proxy after CONNECT
* CONNECT phase completed!
* Closing connection 0
curl: (56) Received HTTP code 503 from proxy after CONNECT
```

And here is what the envoy prints in the logs
```
[2022-05-16 11:20:48.499][3055][info][config] [source/server/listener_manager_impl.cc:789] all dependencies initialized. starting workers
[2022-05-16 11:20:48.507][3055][info][main] [source/server/server.cc:882] starting main dispatch loop
discovered admin address: 127.0.0.1:9902
[2022-05-16 11:21:11.914][3068][warning][upstream] [source/common/upstream/original_dst_cluster.cc:77] original_dst_load_balancer: No downstream connection or no original_dst.
```

Please let me know if I could provide more details. Any help is greatly appreciated!
