### ISSUE TITLE
Running Envoy binary with debug mode giving error

### ISSUE THREAD

**Issue by ankatare** [envoyproxy/envoy#21298]
*Title*: *Unable to parse JSON as proto (INVALID_ARGUMENT:(request_id_extension.typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig for type Any):*

*Description*: In latest Code compiling and running Envoy producing Error ... 

```console
$ ./envoy-static -c envoy.yaml -l debug
[2022-05-15 17:55:54.934][16808][debug][init] [source/common/init/watcher_impl.cc:31] init manager Server destroyed
Unable to parse JSON as proto (INVALID_ARGUMENT:(request_id_extension.typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig for type Any): 

```

Yaml file (not complete) is as follows:

```yaml

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    traffic_direction: INBOUND
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
            - name: envoy.filters.http.lua
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                inline_code: |
                  function envoy_on_request(request_handle)
                    local originalHeader = request_handle:headers():get("x-pool")
                    if originalHeader then
                      request_handle:headers():remove("x-pool")
                      request_handle:headers():add("x-pool", originalHeader:lower())
                    end
                  end
            - name: envoy.filters.http.router
              typed_config: {}
          request_id_extension:
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              pack_trace_reason: false
          generate_request_id: true
          tracing:
            verbose: true
            client_sampling:
              value: 0.0
            random_sampling:
              value: 0.0
            overall_sampling:
              value: 100.0
            provider:
              name: envoy.tracers.zipkin
        .........

```

**Comment by daixiang0** [comment]
This error may help:
```
Unable to parse JSON as proto (INVALID_ARGUMENT:(request_id_extension.typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig for type Any):
```

An example of this is like:
```
  stat_prefix: ingress_http
  route_config:
    name: local_route
  request_id_extension:
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
      pack_trace_reason: false
      use_request_id_for_trace_sampling: false
  http_filters:
  - name: envoy.filters.http.router
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

You need to put this in right place with right indent.

**Comment by ankatare** [comment]
@daixiang0 Thanks for quick response.. I understand the issue with yaml indentations :( .. seems i followed it. 
see below my config now (with exact indentations)
```
filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
            - name: envoy.filters.http.lua
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                inline_code: |
                  function envoy_on_request(request_handle)
                    local originalHeader = request_handle:headers():get("x-pool")
                    if originalHeader then
                      request_handle:headers():remove("x-pool")
                      request_handle:headers():add("x-pool", originalHeader:lower())
                    end
                  end
            - name: envoy.filters.http.router
              typed_config: {}
          request_id_extension:
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              pack_trace_reason: false
```

**Comment by daixiang0** [comment]
request_id_extension should align with http_filters like:

```
  stat_prefix: ingress_http
  route_config:
    name: local_route
  request_id_extension:
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
      pack_trace_reason: false
      use_request_id_for_trace_sampling: false
  http_filters:
  - name: envoy.filters.http.router
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      ```

**Comment by ankatare** [comment]
@daixiang0 yeah, i aligned it with http_filters as mentioned in .. 
https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extension-envoy-filters-network-http-connection-manager

don't know what exactly is the issue.. :(

**Comment by daixiang0** [comment]
You can take it as example:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9902

    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service1
          request_id_extension:
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
              pack_trace_reason: false
              use_request_id_for_trace_sampling: false
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: service1
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9889
```

I am unfamiliar with lua, hope it helps.
