### ISSUE TITLE
Envoy CORS does not respect allow_methods

### ISSUE THREAD

**Issue by truehhart** [envoyproxy/envoy#21303]
*Title*: *Envoy CORS does not respect allow_methods*

*Description*:
For a couple days now I have been working at enabling CORS on our envoy cluster (specifically - allowing the routes to go through depending on the method being used). 
The problem is that no matter what settings you use - envoy lets every request through.

I have used the configuration example provided here:
https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cors
With the default proxy settings - it's clear that should you send a non-GET request to the /cors/restricted - it will be blocked with a 405.
And it does indeed work (at the first glance):
```
~ curl -I -X PUT localhost:8002/cors/restricted   
HTTP/1.1 405 Method Not Allowed
content-type: text/html; charset=utf-8
allow: HEAD, GET, OPTIONS
content-length: 178
server: envoy
date: Mon, 16 May 2022 08:52:30 GMT
x-envoy-upstream-service-time: 2
```

However, I've modified envoy's backend proxy configuration to only allow DELETE requests, with any origin domain.

And it turns out that it's not the proxy blocking the request, but the actual service underneath:
(Just to make sure - I have rebuilt and re-deployed the containers in multiple different ways, and I have also made sure that envoy is running with the correct configuration in place)
```
~ curl -I -X DELETE localhost:8002/cors/restricted
HTTP/1.1 405 Method Not Allowed
content-type: text/html; charset=utf-8
allow: HEAD, GET, OPTIONS
content-length: 178
server: envoy
date: Mon, 16 May 2022 08:54:27 GMT
x-envoy-upstream-service-time: 2
```

I have first encountered this problem with Envoy 1.18.2, but it's also reproducible with `envoy  version: 6df56d0778dad76880518adb356eb7ff11f271c6/1.23.0-dev/Clean/RELEASE/BoringSSL`

*Config*:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: www
              domains:
              - "*"
              cors:
                allow_origin_string_match:
                - safe_regex:
                    google_re2: {}
                    regex: \*
                allow_methods: "DELETE"
                filter_enabled:
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                  runtime_key: cors.www.enabled
                shadow_enabled:
                  default_value:
                    numerator: 0
                    denominator: HUNDRED
                  runtime_key: cors.www.shadow_enabled
              routes:
              - match:
                  prefix: "/cors/open"
                route:
                  cluster: backend_service
              - match:
                  prefix: "/cors/disabled"
                route:
                  cluster: backend_service
                  cors:
                    filter_enabled:
                      default_value:
                        numerator: 0
                        denominator: HUNDRED
              - match:
                  prefix: "/cors/restricted"
                route:
                  cluster: backend_service
                  cors:
                    allow_origin_string_match:
                    - safe_regex:
                        google_re2: {}
                        regex: \*
                    allow_methods: "DELETE"
              - match:
                  prefix: "/"
                route:
                  cluster: backend_service
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: backend_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-service
                port_value: 8000

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

*Logs*:
```
backend-backend-service-1  |  * Serving Flask app 'service' (lazy loading)
backend-backend-service-1  |  * Environment: production
backend-backend-service-1  |    WARNING: This is a development server. Do not use it in a production deployment.
backend-backend-service-1  |    Use a production WSGI server instead.
backend-backend-service-1  |  * Debug mode: off
backend-backend-service-1  |  * Running on all addresses.
backend-backend-service-1  |    WARNING: This is a development server. Do not use it in a production deployment.
backend-backend-service-1  |  * Running on http://172.20.0.2:8000/ (Press CTRL+C to quit)
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:30] "PUT /cors/restricted HTTP/1.1" 405 -
backend-front-envoy-1      | [2022-05-16T08:42:30.950Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 4 3 "-" "curl/7.77.0" "e57e3f95-1841-4610-9355-4d31fc9934a8" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:34] "PUT /cors/restricted HTTP/1.1" 405 -
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:35] "PUT /cors/restricted HTTP/1.1" 405 -
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:35] "PUT /cors/restricted HTTP/1.1" 405 -
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:36] "PUT /cors/restricted HTTP/1.1" 405 -
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:42:40] "PUT /cors/restricted HTTP/1.1" 405 -
backend-front-envoy-1      | [2022-05-16T08:42:34.913Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 5 5 "-" "curl/7.77.0" "16f81adc-045f-43c1-baff-aa4d0d45f8a3" "localhost:8002" "172.20.0.2:8000"
backend-front-envoy-1      | [2022-05-16T08:42:35.471Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 2 2 "-" "curl/7.77.0" "bf7666dc-939f-42c0-9b57-bd3d0c3bba9f" "localhost:8002" "172.20.0.2:8000"
backend-front-envoy-1      | [2022-05-16T08:42:35.762Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 2 1 "-" "curl/7.77.0" "8b93ec93-78a6-4d7c-8ff6-23c5f88314ee" "localhost:8002" "172.20.0.2:8000"
backend-front-envoy-1      | [2022-05-16T08:42:35.999Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 4 3 "-" "curl/7.77.0" "a64e9c60-7d7e-45e9-82f4-521c0e093dcb" "localhost:8002" "172.20.0.2:8000"
backend-front-envoy-1      | [2022-05-16T08:42:40.894Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 3 2 "-" "curl/7.77.0" "ad7ff1a5-03e1-4cf9-81c7-4d703824da39" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:44:42] "GET /cors/restricted HTTP/1.1" 200 -
backend-front-envoy-1      | [2022-05-16T08:44:42.724Z] "GET /cors/restricted HTTP/1.1" 200 - 0 8 3 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36" "932e74ba-9c3d-4f2e-bf8a-f0b90ef0966a" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:44:45] "GET /cors/open HTTP/1.1" 200 -
backend-front-envoy-1      | [2022-05-16T08:44:45.238Z] "GET /cors/open HTTP/1.1" 200 - 0 8 3 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36" "b343deb0-4435-4e9c-ae38-21acdabf7dcd" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:44:54] "GET /cors/restricted HTTP/1.1" 200 -
backend-front-envoy-1      | [2022-05-16T08:44:54.722Z] "GET /cors/restricted HTTP/1.1" 200 - 0 8 3 2 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36" "f2cb0164-ccf7-441d-8be5-c8ac4fb4a5e3" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:52:28] "PUT /cors/restricted HTTP/1.1" 405 -
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:52:30] "PUT /cors/restricted HTTP/1.1" 405 -
backend-front-envoy-1      | [2022-05-16T08:52:28.274Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 4 3 "-" "curl/7.77.0" "ce0a1b78-6d12-4854-8a4b-618ce7c859b0" "localhost:8002" "172.20.0.2:8000"
backend-front-envoy-1      | [2022-05-16T08:52:30.583Z] "PUT /cors/restricted HTTP/1.1" 405 - 0 178 2 2 "-" "curl/7.77.0" "06bdcec6-2ab0-4769-9df5-cc21d1144dae" "localhost:8002" "172.20.0.2:8000"
backend-backend-service-1  | 172.20.0.3 - - [16/May/2022 08:54:27] "DELETE /cors/restricted HTTP/1.1" 405 -
backend-front-envoy-1      | [2022-05-16T08:54:27.356Z] "DELETE /cors/restricted HTTP/1.1" 405 - 0 178 3 2 "-" "curl/7.77.0" "2bfcbc69-0246-4494-aaea-7cb089a9439f" "localhost:8002" "172.20.0.2:8000"
```

**Comment by snowp** [comment]
@wbpcode (cors owner) can you take a look?

**Comment by wbpcode** [comment]
IMO, the cors filter will not block any request. It just is used to handle the cors pre-check requests. And the cors pre-check requests should with method of "OPTIONS".

Check https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS for more info.

**Comment by truehhart** [comment]
Thank you @wbpcode for the URL.

I've studied the Mozilla's documentation on CORS and does seem that I'm trying to use CORS for something it isn't supposed to be used for.

For future reference (if anyone has the same question):
> CORS also relies on a mechanism by which browsers make a "preflight" request to the server hosting the cross-origin resource, in order to check that the server will permit the actual request.

> For "preflighted" requests the browser first sends an HTTP request using the [OPTIONS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS) method to the resource on the other origin, in order to determine if the actual request is safe to send.

> The [Access-Control-Allow-Methods](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods) header specifies the method or methods allowed when accessing the resource.

As such - while CORS is there to guide the client accessing the resource, it does not specifically block any requests. i.e. (from what it seems) - it requires the client itself to not only check the CORS policies, but also to act on them. (as such - curl won't do any CORS justice, whilst Chrome will)

That's the conclusion I've come up to, but I would appreciate any corrections if there are any to be made.

Nonetheless, at this point I'm not entirely sure how can we use Envoy in order to only allow specific methods to be made for the the path. We are currently using match filters:
```yaml
- match: {{- if ne $method "ANY" }}
    headers:
      name: ":method"
      safe_regex_match:
        google_re2: {}
        regex: "{{ $method }}" {{- end }}
    safe_regex:
      google_re2: {}
      regex: {{ $regex }}
```
This comes with a couple of problems - namely, if the method isn't specified for a route - Envoy will return 404 instead of 405 (because the request just doesn't match any filters).

Is there any functionality in Envoy that would allow us to block requests instead of "not finding them" when there's no specific route? i.e. correctly providing the 405.

Again, I greatly appreciate your help.

Thank you!
