### ISSUE TITLE
Multiple `regex_rewrite` or `prefix_rewrite` operations for the same route

### ISSUE THREAD

**Issue by NomadXD** [envoyproxy/envoy#21329]
*Title*: *Multiple `regex_rewrite` or `prefix_rewrite` operations for the same route*

*Description*:
Is there a way to have multiple `regex_rewrite` or `prefix_rewrite` for the same route ? For example if I'm having separate production and sandbox APIs for the same API, then I need to perform two different rewrites depending on whether the production API or sandbox API is invoked.

At the moment I'm setting up an extra header in the external auth response and using that header to switch between production and sandbox routes. 

```yaml
routes:
    - match:
        prefix: "/api/v1"
        headers:
          - name: x-deployment-cluster
            string_match:
              exact: "sandbox"
      route:
        prefix_rewrite: /bar
        cluster_header: x-deployment-cluster

    - match:
        prefix: "/api/v1"
      route:
        prefix_rewrite: /foo
        cluster_header: x-deployment-cluster
```

But this is NOT a scalable approach when I have like 100s of routes (simply it will x2 all the routes). Is there any other better way to do this in route config?

Or else any hacks we can do using headers, dynamic metadata to conditionally change the rewrite field ?
