### ISSUE TITLE
Envoy requests are failing when Redis replica fails

### ISSUE THREAD

**Issue by NirmalP29** [envoyproxy/envoy#21352]
Envoy set/set requests are failing when any redis replica goes down with error **_upstream failure_**
Retries are successful for the same.
Can anyone help me solve this issue?

I tried with python and redis-benchmark tool. Both were completing successfully when any replica fails in between while executing requests directly using redis endpoint but both were failing in between when any replica fails and gives error **_upstream failure_** while running requests via envoy endpoint.

Config I used - 

```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          downstream_auth_password:
            inline_string: "pass"
          settings:
            op_timeout: 10s
            enable_redirection: True
            enable_hashtagging: false
            enable_command_stats: false
            read_policy: MASTER
          prefix_routes:
            routes:
              - prefix: ""
                cluster: "c1"
                request_mirror_policy: [{cluster: "c2", exclude_read_commands: True}]
            catch_all_route:
              cluster: "c1"
 
  clusters:
  - name: c1
    connect_timeout: 1s
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 1s
          cluster_refresh_timeout: 1s
          redirect_refresh_interval: 1s
          redirect_refresh_threshold: 10
    load_assignment:
      cluster_name: c1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <ip>
                port_value: 6379

    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 1000000000
          max_pending_requests: 1000000000
          max_requests: 1000000000
          max_retries: 1000000000
        - priority: HIGH
          max_connections: 1000000000
          max_pending_requests: 1000000000
          max_requests: 1000000000
          max_retries: 1000000000
    typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
          auth_password:
            inline_string: pass
 
  - name: c2
    connect_timeout: 1s
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 1s
          cluster_refresh_timeout: 1s
          redirect_refresh_interval: 1s
          redirect_refresh_threshold: 10
    load_assignment:
      cluster_name: c2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <ip>
                port_value: 6379
     typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
          auth_password:
            inline_string: pass
  
admin:
  access_log:
    name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: /app/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
  
layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      envoy:
        resource_limits:
          listener:
            example_listener_name:
              connection_limit: 10000
      overload:
        global_downstream_max_connections: 50000
```

**Comment by snowp** [comment]
@mattklein123 any idea who might be able to help with this? I'm not sure if we have someone well versed in the Reddit filters around

**Comment by mattklein123** [comment]
Seems like you need health checking of some type?

**Comment by NirmalP29** [comment]
```
clusters:
  - name: c1
    health_checks: 
      timeout: 0.1s
      interval: 0.1s
      unhealthy_threshold: 3
      healthy_threshold: 2
      custom_health_check: 
        name: envoy.health_checkers.redis,
        typed_config: 
          "@type": "type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis"
      event_log_path: "/app/failover.log"
      always_log_health_check_failures: true
```
I added the health checks. Now, the set requests are still failing for a fraction of a second with **_upstream failure_** error when any redis replica fails which were earlier failing for 8-10s. 
Did I miss any config cause the redis endpoint works seamlessly for this scenario.
How to add envoy retries for redis? Will that solve this issue since all the requests are successful with 1 retry for that time period.
