### ISSUE TITLE
Wildcard request are sent with zero-length ResourceNamesSubscribe

### ISSUE THREAD

**Issue by fiibbb** [envoyproxy/envoy#21416]
*Description*:
The XDS [doc](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-docs/xds_protocol) describes wildcard requests as the following:
```
For [Listener](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/config/listener/v3/listener.proto#envoy-v3-api-msg-config-listener-v3-listener) and [Cluster](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-msg-config-cluster-v3-cluster) resource types, there is also a “wildcard” subscription, which is triggered when subscribing to the special name “*”
```

Historically, wildcard requests are documented as special name "" (empty string).

In practice, when Envoy is configured to [boot with LDS and CDS enabled](https://www.envoyproxy.io/docs/envoy/v1.22.0/api-v3/config/bootstrap/v3/bootstrap.proto#config-bootstrap-v3-bootstrap-dynamicresources), it appears to be sending a [DeltaDiscoveryRequest](https://github.com/envoyproxy/envoy/blob/v1.22.0/api/envoy/service/discovery/v3/discovery.proto#L145) with zero-length [resource_names_subscribe](https://github.com/envoyproxy/envoy/blob/v1.22.0/api/envoy/service/discovery/v3/discovery.proto#L178).

*Repro steps*:
Boot Envoy with the following config:
```
---
node:
  cluster: cluster-42
  id: node-42
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
layered_runtime:
  layers:
    - name: static
      # Without specifying overload.global_downstream_max_connections, Envoy will throw a warning at bootstrap.
      static_layer: {overload.global_downstream_max_connections: 65536}
    - name: admin
      admin_layer: {}
    - name: rtds
      rtds_layer:
        name: rtds
        rtds_config: {ads: {}, resource_api_version: V3, initial_fetch_timeout: 1s}
static_resources:
  clusters:
    - name: xds_cluster
      connect_timeout: 5s
      type: STATIC
      lb_policy: ROUND_ROBIN
      common_http_protocol_options:
        max_stream_duration: 300s
      http2_protocol_options:
        connection_keepalive:
          interval: 30s
          timeout: 5s
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8980
dynamic_resources:
  lds_config: {ads: {}, resource_api_version: V3, initial_fetch_timeout: 1s}
  cds_config: {ads: {}, resource_api_version: V3, initial_fetch_timeout: 1s}
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
      envoy_grpc:
        cluster_name: xds_cluster
cluster_manager:
  load_stats_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      envoy_grpc:
        cluster_name: xds_cluster
```

Observe the initial LDS and CDS request received on the control plane side (we use our in-house control plane). The request will show empty list for `resource_names_subscribe`.
