### ISSUE TITLE
examples/front-proxy: Service requesting to invalid address

### ISSUE THREAD

**Issue by mmiranda96** [envoyproxy/envoy#2144]
*Description*:
File service.py contains an HTTP request to localhost:

`ret = requests.get("http://localhost:9000/trace/2", headers=headers)`

Port 9000 is not exposed. Should this be port 8080? Or perhaps port 9000 should be open?

**Comment by derekargueta** [comment]
@mmiranda96 that route is used in the `zipkin-tracing` example in which the service envoys run a listener on port 9000 - a little confusing IMO but you can see it referred to in the `zipkin-tracing`'s Docker-compose
```
front-envoy:
    build:
      context: ../
      dockerfile: front-proxy/Dockerfile-frontenvoy
    volumes:
      - ./front-envoy-zipkin.json:/etc/front-envoy.json
    networks:
      - envoymesh
    expose:
...
```

I'd like to put up a PR cleanly separating/restructuring these examples if @mattklein123 thinks it's appropriate. I too was confused on what that `/trace` route was for.
