### ISSUE TITLE
SSL Error connecting to a redis cluster 'Elasticache'

### ISSUE THREAD

**Issue by Jacobien1** [envoyproxy/envoy#21455]
I'm trying to connect to my Redis cluster 'Elasticache' through the envoy. when I do it through the TCP filter, it works fine, but the connection pool doesn't work. on the other hand, I've tested the Redis filter and it works perfectly on my local with the connection pool, but when I try to implement it on AWS it doesn't work 'I'm using Redis-py as a client ' and it gives me the following error:
```
    sslsock = context.wrap_socket(sock, server_hostname=self.host)
  File "/usr/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)
```
config file is :
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 1936
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_proxy
          settings:
            op_timeout: 4s
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
  clusters:
    name: redis_cluster
    type: STRICT_DNS
    connect_timeout: 10s
    dns_lookup_family: V4_ONLY
    connect_timeout: 4s 
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
        lb_endpoints:
          endpoint:
            address:
              socket_address:
                address: my-redis
                port_value: 6379 
    upstream_connection_options:
      tcp_keepalive:
        keepalive_interval: 5
        keepalive_probes: 15
        keepalive_time: 30
    upstream_config:
      name: envoy.upstreams.tcp.generic
      typed_config: 
        "@type": type.googleapis.com/envoy.extensions.upstreams.tcp.generic.v3.GenericConnectionPoolProto
```

Thank you in advance.
