### ISSUE TITLE
Can't adjust the descriptor_key for the rate limiting based on remote_address

### ISSUE THREAD

**Issue by style95** [envoyproxy/envoy#21465]
*Description*:
I configured the global rate limit on Istio/Envoy using Envoyfilter.

My rate limit configuration for the ratelimit service looks like this.

configmap
```
...yaml
domain: mydomain.com
descriptors:
    - key: remote_address
      value: 10.10.10.10
      rate_limit:
        unit: minute
        requests_per_unit: 2

...
```

And my envoyfilter looks like this.

```yaml
Spec:
  Config Patches:
    Apply To:  VIRTUAL_HOST
    Match:
      Context:  GATEWAY
      Route Configuration:
        Vhost:
          Name:  mydomain.com:80
          Route:
    Patch:
      Operation:  MERGE
      Value:
        rate_limits:
          Actions:
            remote_address:
.
.
.
```

When I send a request, the envoy sends a ratelimit request to the ratelimit service, but it looks for a different descriptor key.

The ratelimit service uses `mydomain.com.remote_address_10.10.10.10` as a key.
```json
{"@message":"loading descriptor: key=mydomain.com.remote_address_10.10.10.10 ratelimit={requests_per_unit=2, unit=MINUTE, unlimited=false}","@timestamp":"2022-05-27T10:57:46.115910779+09:00","level":"debug"}
```

While the envoy sends a request with `remote_address_10.10.10.10`.

```json
{"@message":"looking up key: remote_address_10.10.10.10","@timestamp":"2022-05-27T11:00:33.149314244+09:00","level":"debug"}
```

It looks the RemoteAddress config does not have any way to configure a descriptor key.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-remoteaddress

How can I do the rate limiting based on the remote address?

I am using the 1.21.1 version of envoy.
```
k exec -it istio-ingressgateway-gateway5-ff8bb5df9-wmf52 -c istio-proxy  -- pilot-agent request GET server_info --log_as_json | jq {version}
{
  "version": "15cc87023540f5f81331c11ef9010784f7ef2460/1.21.2-dev/Clean/RELEASE/BoringSSL"
}
```

**Comment by kyessenov** [comment]
I'm not very familiar with the RLS server implementation. Envoy uses a fixed key literally called `remote_address` for this action. Maybe it's the issue with the mis-matched rate limit domain? It's not virtual host.

**Comment by style95** [comment]
@kyessenov Thank you for the answer.
We are supposed to specify the domain in the configmap for reatelimit service configuration.

```
...yaml
domain: mydomain.com  # mandatory.
descriptors:
    - key: remote_address
      value: 10.10.10.10
      rate_limit:
        unit: minute
        requests_per_unit: 2

...
```

If you mentioned about the EnvoyFilter, could you let me know where to put such configurations?
