### ISSUE TITLE
Envoy routing issue with REACTjs

### ISSUE THREAD

**Issue by jeanpz** [envoyproxy/envoy#21491]
I'm currently tring to implement envoy to be a gateway to route traffic inside my cluster and I'm running into a problem when making the redirect using a frontend application using ReactJs, getting a 404 on the static files.
It seems that the static files are missing the "path" portion of the url that im filtering through envoy, is there any config I'm missing here?
This is the envoy config:

```yaml
routes:
    - match: { prefix: "/foo/" }
      route:
        auto_host_rewrite: true
        prefix_rewrite: "/"
        cluster: foo
clusters:
    - name: foo
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: foo
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: foo-container.foo-namespace.svc.cluster.local
                      port_value: 8080
```
On the webpage i can see the following under developer mode.

![image](https://user-images.githubusercontent.com/9324069/170795888-f05e231c-d925-4ab6-8096-95d818a8b684.png)

It seems to be missing the /foo/ part of the URL (www.foopage.com/ instead of www.foopage.com/foo/), so the front end is not able to find the static files, but if I manually input the /foo/ I am able to access the file.
