### ISSUE TITLE
GrpcJsonTranscoder returns 200 with an empty body when the gRPC message is too deep

### ISSUE THREAD

**Issue by bmonnahan** [envoyproxy/envoy#21490]
*Title*: GrpcJsonTranscoder returns 200 with an empty body when the gRPC message is too deep 

*Description*:

Actual: We have response messages with a recursive structure which can lead to deep objects.  Above 64 levels the json transcoder doesn't successfully convert the message to json. Instead it returns an empty body with a 200 HTTP status. Nothing shows up in the logs even with trace logging turned on.

Expected: An error in the log and if possible a HTTP error status is returned to the client.

*Repro steps*:

Using the code & config below...

This call works:
`curl -v http://localhost:9091/testRead/64`

This one doesn't (empty response body, status 200):
`curl -v http://localhost:9091/testRead/65`

In the logs for the service we can see that the gRPC message is generated successfully in both cases.

Our envoy comes from a docker image based on **envoy-alpine:v1.20.1-1.7**

Proto
```
syntax = "proto3";
package com.test.recursion;

import "google/api/annotations.proto";

option java_multiple_files = true;
option java_package = "com.test.recursion";


service TemplateService {

  rpc testRead(TestReadRequest) returns (TestReadResponse) {
    option (google.api.http) = {
      get : "/testRead/{count}"
    };
  };

  rpc testWrite(TestWriteRequest) returns (TestWriteResponse) {
    option (google.api.http) = {
      post : "/testWrite",
      body : "*"
    };
  };
}

message TestReadResponse {
  string message = 1;
  Tree tree = 2;
}

message TestReadRequest {
  int32 count = 1;
}

message TestWriteRequest {
  Tree tree = 1;
}


message TestWriteResponse {
  string message = 1;
}

message Tree {
  oneof left_child {
    Tree left_tree = 1;
    string left_leaf = 2;
  }
  oneof right_child {
    Tree right_tree = 3;
    string right_leaf = 4;
  }
}
```

Service Impl
```
package com.test.recursion.grpc;


import com.google.protobuf.InvalidProtocolBufferException;
import com.google.protobuf.util.JsonFormat;
import com.test.recursion.TemplateServiceGrpc;
import com.test.recursion.TestReadRequest;
import com.test.recursion.TestReadResponse;
import com.test.recursion.TestWriteRequest;
import com.test.recursion.TestWriteResponse;
import com.test.recursion.Tree;
import io.grpc.ManagedChannel;

import io.grpc.stub.StreamObserver;
import lombok.extern.slf4j.Slf4j;
import net.devh.boot.grpc.server.service.GrpcService;

@Slf4j
@GrpcService
public class GrpcTemplateServiceImpl extends TemplateServiceGrpc.TemplateServiceImplBase {

    private final JsonFormat.Printer printer = JsonFormat.printer().includingDefaultValueFields().omittingInsignificantWhitespace().preservingProtoFieldNames();

    @Override
    public void testWrite(TestWriteRequest request, StreamObserver<TestWriteResponse> responseStreamObserver) {
        log.info("testWrite: >>> request {} ", request);
        TestWriteResponse resp = null;
        try {
            String reqMessageJson = printer.print(request);
            log.info("REQUEST AT SERVER: " + reqMessageJson);
            resp = TestWriteResponse.newBuilder()
                            .setMessage(reqMessageJson)
                            .build();
        responseStreamObserver.onNext(resp);
        responseStreamObserver.onCompleted();
        } catch (InvalidProtocolBufferException e) {
            log.error("Failed to print request");
            responseStreamObserver.onError(e);
        }


        log.info("testWrite: <<< ");
    }
    @Override
    public void testRead(TestReadRequest request, StreamObserver<TestReadResponse> responseStreamObserver) {
        log.info("testRead: >>> request {} ", request);
        TestReadResponse resp = TestReadResponse.newBuilder()
                .setMessage(request.getCount()+"")
                .setTree(buildTree(request.getCount()))
                .build();
                try {
                    log.info("SERVER RESPONSE: " + printer.print(resp));
                    
                } catch(Exception e) {
                    log.error("Failed to print response");
                }
        responseStreamObserver.onNext(resp);
        responseStreamObserver.onCompleted();
       
        log.info("testRead: <<< ");
    }

    private Tree buildTree(int depth) {
        if(depth <= 1) {
            return Tree.newBuilder().setLeftLeaf("LEFT_LEAF").setRightLeaf("RIGHT_LEAF").build();
        }

        return Tree.newBuilder().setLeftTree(buildTree(depth-1)).setRightLeaf("R").build();
    }
}

```

*Config*:

```
admin:
  access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: grpc-service-listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 9090 }
      per_connection_buffer_limit_bytes: 104857600
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                stream_idle_timeout: 1680s
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: grpc-backend-services, timeout: 1680s }
                http_filters:
                  - name: envoy.filters.http.grpc_json_transcoder
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                      proto_descriptor: "/data/template-service.pb"
                      services: ["com.test.recursion.TemplateService"]
                      print_options:
                        add_whitespace: false
                        always_print_primitive_fields: true
                        always_print_enums_as_ints: false
                        preserve_proto_field_names: false
                  - name: envoy.filters.http.router
  clusters:
    - name: grpc-backend-services
      connect_timeout: 1.25s
      type: STRICT_DNS
      lb_policy: LEAST_REQUEST
      dns_lookup_family: V4_ONLY
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: grpc-backend-services
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${GRPC_HOST}
                      port_value: 9090
```
