### ISSUE TITLE
Local RateLimit:  Support customizing response body when request be limited

### ISSUE THREAD

**Issue by zengyuxing007** [envoyproxy/envoy#21513]
*Title*: *Support customizing response body when request be limited*

*Description*:

In some scenarios at the gateway, the corresponding  local ratelimit filter is expected to have the ability to customize the response body, for example

```yaml
  http_filters:
          - name: envoy.filters.http.local_ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10000
                tokens_per_fill: 1000
                fill_interval: 1s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'
              custom_reponse_body:
                   content: "{"ret_code": xxx, "message": "Your request be limited" }"
              local_rate_limit_per_downstream_connection: false
```

Expect to add fields：

```yaml
              custom_reponse_body:
                   content: "{"ret_code": xxx, "message": "Your request be limited" }"
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
