### ISSUE TITLE
ext_authz with http_service - x-forwarded-for incorrect ?

### ISSUE THREAD

**Issue by synologic** [envoyproxy/envoy#21519]
Hi all,

I have a simple api gw setup aith an ext_authz filter set on toip of the router filter, that uses a http_service as backend.

It seems that by default, x-forwarded-for header received by the authorization http service is the IP of the machine running envoy and not the actual client ip address.

Am i missing something here ? How can I get the real ip of the caller ?

Thanks

**Comment by synologic** [comment]
Yes i did:

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 172.16.44.100, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
```

Tested with version 1.21.2, in the auth service i get the following headers:

```
{
  'content-length': '0',
  'x-envoy-internal': 'true',
  'x-forwarded-for': '172.16.44.100',
  'x-envoy-expected-rq-timeout-ms': '250'
}
```

where 172.16.44.100 is the envoy server's IP address

**Comment by KBaichoo** [comment]
what is the IP address of the remote client that directly talks to the Envoy? 


>Envoy’s default rules for determining the trusted client address (before appending anything to XFF) are:
>
>If use_remote_address is false and an XFF containing at least one IP address is present in the request, the trusted client >address is the last (rightmost) IP address in XFF.
>
>Otherwise, the trusted client address is the source IP address of the immediate downstream node’s connection to Envoy.

From https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for

would lead me to think you fall into the second case where the source IP of the immediate downstream node's connection to Envoy is used.

**Comment by synologic** [comment]
The flow is like this:

```
Client 192.168.x.x -> (IP ROUTING)-> Envoy 172.16.44.100 
     -> Auth Service 192.168.44.101
     -> Test backend running on 172.16.44.100:3001
```

Envoy is acting as edge proxy and there's nothing else between the client and Envoy.

In the request which is eventually sent to the backend, I can see just fine the client's IP address in the X-Forwarded-For, however in the authorization request it is not. I am thinking this may be because of the fact the filter is actually considering the http connection manager as the "client" sending the request ?

This can be worked around by adding a custom header in the authorization_request section:

```
 authorization_request:
                  headers_to_add:
                    - key: "RealIP"
                      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
```

which will indeed add the remote address.

I am not sure if this is by design or a bug, however i think X-Forwarded-For should in fact reflect the downstream remote address and not the Envoy's address
