### ISSUE TITLE
Envoy proxy (Error) MOVED on an Elasticache Cluster mode on

### ISSUE THREAD

**Issue by Jacobien1** [envoyproxy/envoy#21564]
We have an Elasticache that we're using and now we're trying to use envoy to have some pool of connections to the cluster but, there is an issue when using Redis-CLI or Redis-py which is the famous error: (Error) MOVED. I've tried muñltiple changes but nothing seems to be working. sometimes it works well but other times it shows that error. any help with the issue, please.

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 1936
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_proxy
          settings:
            op_timeout: 4s
            enable_redirection: true
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
  clusters:
    name: redis_cluster
    type: STRICT_DNS
    connect_timeout: 10s
    dns_lookup_family: V4_ONLY
    connect_timeout: 4s 
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
        lb_endpoints:
          endpoint:
            address:
              socket_address:
                address: my-redis
                port_value: 6379 
    upstream_connection_options:
      tcp_keepalive:
        keepalive_interval: 5
        keepalive_probes: 15
        keepalive_time: 30
    upstream_config:
      name: envoy.upstreams.tcp.generic
      typed_config: 
        "@type": type.googleapis.com/envoy.extensions.upstreams.tcp.generic.v3.GenericConnectionPoolProto
```

**Comment by KBaichoo** [comment]
cc @weisisea

**Comment by ramaraochavali** [comment]
For redis cluster, you need to use lb_policy as `CLUSTER_PROVIDED` and cluster_type as `envoy.clusters.redis`. 

Sample config

```
        lb_policy: CLUSTER_PROVIDED
        cluster_type:
          name: envoy.clusters.redis
          typed_config:
            "@type": type.googleapis.com/google.protobuf.Struct
            value:
              cluster_refresh_rate: 360s
              cluster_refresh_timeout: 4s
              
```
