### ISSUE TITLE
How do I enable io_uring on Envoy?

### ISSUE THREAD

**Issue by martinezlucas98** [envoyproxy/envoy#21582]
*Title*: *How do I enable io_uring on Envoy?*

*Description*:
I'm having some problems while trying to use io_uring with envoy...
Is io_uring being used by default on Linux systems? 
Or do i need to tell Envoy explicitly that I want io_uring to be used? If that's the case then how is it done (by a cmd line flag or a configuration in the YAML config)?

I've seen this config on #17922
```yaml
bootstrap_extensions:
  - name: envoy.extensions.io_socket.io_uring
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.network.socket_interface.v3.IoUringSocketInterface
      use_submission_queue_polling: false
      read_buffer_size: 8192
      io_uring_size: 300
default_socket_interface: "envoy.extensions.network.socket_interface.io_uring"
```
But `IoUringSocketInterface` is not on this project yet, so it returns the following error:
```
[2022-06-05 22:44:57.037][17918][info][main] [external/envoy/source/server/server.cc:815] exiting
Unable to parse JSON as proto (INVALID_ARGUMENT:(bootstrap_extensions[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.network.socket_interface.v3.IoUringSocketInterface for type Any)
```

**Comment by martinezlucas98** [comment]
This is my yaml config file, in case I'm doing it wrong:
```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    connect_timeout: 0.5s
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
bootstrap_extensions:
  - name: envoy.extensions.io_socket.io_uring
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.network.socket_interface.v3.IoUringSocketInterface
      use_submission_queue_polling: false
      read_buffer_size: 8192
      io_uring_size: 300
default_socket_interface: "envoy.extensions.network.socket_interface.io_uring"
```
