### ISSUE TITLE
X-Forwarded-Proto header is set without X-Forwarded-Port

### ISSUE THREAD

**Issue by iglin** [envoyproxy/envoy#21586]
*X-Forwarded-Proto header is set without X-Forwarded-Port*: *Envoy sets X-Forwarded-Proto HTTP header, but does not set X-Forwarded-Port and X-Fowarded-Host*

This is a new copy of issue https://github.com/envoyproxy/envoy/issues/21500, since it was closed without any solution and I have no rights to reopen it. 

*Description*:
>We are using envoy as an API gateway. Envoy sets X-Forwarded-Proto HTTP header, but does not set X-Forwarded-Port and X-Fowarded-Host, which confuses application frameworks (e.g. Quarkus) when calculation incoming request Host. Usually these 3 headers come together, or do not come at all. In envoy it should be possible to configure at least one of the solutions: 
1. Disable setting HTTP header X-Forwarded-Proto;
2. Enable setting all the X-Forwarded headers IN CASE DOWNSTREAM DID NOT SET IT YET - cause usually these headers should be set on load balancer side before the requests gets into cloud network and reaches envoy. 

*Repro steps*:
> Run docker-compose test environment, containing latest envoy-dev with static configuration and simple traffic testing app (app sources can be found [here](https://github.com/iglin/mesh-app)). App responds on every request with the incoming request data, including HTTP request headers. 
Your docker-compose directory should include 3 files:
**docker-compose.yml:**
```
version: "3.3"
services:
  enovy:
    build: .
    ports:
      - "10000:10000"
      - "9901:9901"
    networks:
      - mesh-net
  mesh-app:
    image: "iglin/mesh-app:v1.0"
    ports: 
      - "8080:8080"
    networks:
      - mesh-net
networks:
  mesh-net:
    driver: bridge
```

**Dockerfile:**
```
FROM envoyproxy/envoy-dev:latest

COPY envoy.yaml /etc/envoy/envoy.yaml
RUN chmod go+r /etc/envoy/envoy.yaml

EXPOSE 10000 9901
```

**envoy.yaml:** 
```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: my-gateway
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: my-gateway-routes
            virtual_hosts:
            - name: common
              domains: ["*"]
              routes:
              - match: { prefix: "/api/v1/mesh-app" }
                route: { cluster: mesh-app }
          http_filters:
          - name: envoy.filters.http.stateful_session
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: mesh-app
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: mesh-app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: mesh-app
                port_value: 8080`
```

> Run docker-compose env: `docker-compose up`

> Execute HTTP request `curl -v http://localhost:10000/api/v1/mesh-app`

>**Expected Result**: Request header X-Forwarded-Proto is not added to the request. 

>**Actual Result**: Request header X-Forwarded-Proto is present, see the response:
```
$ curl -v http://localhost:10000/api/v1/mesh-app
*   Trying 127.0.0.1:10000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10000 (#0)
> GET /api/v1/mesh-app HTTP/1.1
> Host: localhost:10000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Mon, 30 May 2022 07:19:17 GMT
< content-length: 362
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 0
< server: envoy
< 
* Connection #0 to host localhost left intact
{"appId":"82d0399b-c394-4881-b399-a61c909cb542","appName":"mesh-app","url":"/api/v1/mesh-app","host":"localhost:10000","method":"GET","proto":"HTTP/1.1","headers":{"Accept":["*/*"],"User-Agent":["curl/7.68.0"],"X-Envoy-Expected-Rq-Timeout-Ms":["15000"],"X-Forwarded-Proto":["http"],"X-Request-Id":["a744f29d-1dd3-4913-ba5f-d1eb7b96be18"]},"body":"","cookies":[]}
```
