### ISSUE TITLE
Unexpected response to cluster slot command 'Redis Elatsicache Cluster'

### ISSUE THREAD

**Issue by Jacobien1** [envoyproxy/envoy#21587]
Hello, 
I've had configurated envoy as my proxy for the Elsaticache 'Redis' cluster mode on. but once I launch the proxy I get Unexpected response to cluster slot command

my envoy configurations:
```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address: { address: 0.0.0.0, port_value: 1936 }
static_resources:
  listeners:
    name: redis_listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 1998 }
    filter_chains:
      filters:
        name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_stats
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          settings:
            op_timeout: 4s
  clusters:
    name: redis_cluster
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 10s
          cluster_refresh_timeout: 4s  
    connect_timeout: 4s
    dns_lookup_family: V4_ONLY
    lb_policy: CLUSTER_PROVIDED      
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
        lb_endpoints:
          endpoint:
            address:
              socket_address: { address: AWS_elasticache, port_value: 6379 }
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password:
            inline_string: "1234562738273645"
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
Error Message:

'''
Unexpected response to cluster slot command: [[0, 16383, ["AWS_elasticache_node1", 6379, "d88ee8e81c6cca4f7d24220f52b6d0f9ede54f1e"], ["AWS_elasticache_node2", 6379, "170a0f46eff96cd21adb7788169682755e655a8e"]]]

'''

Thank you
