### ISSUE TITLE
Envoy proxy to use second corporate proxy for any host requested by client

### ISSUE THREAD

**Issue by dvu714** [envoyproxy/envoy#21598]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Envoy proxy to use second corporate proxy for any hostl requested by client

*Description*:
Is there a way we can setup an envoy proxy to use a secondary corporate proxy for any host requested by the client?

Client -> envoy proxy -> corp proxy -> any host requested by the client

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
Read a few issues that lead back to something like this, but I believe this is for a static host?
https://gist.github.com/grzegorz-mirek/c028a24ec2b32dfa47b1fdb904ed3baa

**Comment by dvu714** [comment]
I'm trying to allow clients make a request to a host destination, i.e. https://www.google.com through an envoy proxy.  The envoy proxy would then use another proxy located at say http://corp.proxy.net.  This would be for both http_proxy and https_proxy.

1. Client makes a request: curl --proxy http://envoy.proxy.net:1000 https://www.google.com
2. Envoy proxy uses another proxy at http://corp.proxy.net to send the request for https://www.google.com
3. Client receives the response from https://www.google.com

**Comment by yanavlasov** [comment]
The difference between http and https is the destination port. You need to configure two clusters in Envoy with host corp.proxy.net and port 80 and 443 for http and https traffic.

**Comment by dvu714** [comment]
> The difference between http and https is the destination port. You need to configure two clusters in Envoy with host corp.proxy.net and port 80 and 443 for http and https traffic.

I think this is the issue we are having.  We need both http and https to use corp.proxy.net, port 80.
Is this achievable with the envoy proxy?

Currently we have clients connected to the corp proxy with the settings below.
https_proxy=http://corp.proxy.net
http_proxy=http://corp.proxy.net

We are looking to put an envoy proxy in front of the corp proxy.

**Comment by dvu714** [comment]
I just want to follow up on this question.

Is it possible to forward all requests (http and https) to a secondary corp proxy using http?

**Comment by yanavlasov** [comment]
You can do it, but it is complicated and we do not have ready made examples. You will need two listeners for this:
1. Listener 1 terminated http CONNECT, there is example in `configs/terminate_http1_connect.yaml`
2. Listener 2 for terminating TLS decapsulated from CONNECT request.
3. Cluster1 for sending CONNECT payload through a loopback socket to listener 2. Listener 1 will use cluster 1.
4. Cluster 1 for sending cleartext TCP payload to the corp proxy.

Adding @alyssawilk to see if we have some examples of such configuration.

**Comment by alyssawilk** [comment]
Not that I know of sorry :-(

**Comment by kamranmohammed** [comment]
Hey guys I will be taking over this request from @dvu714. Would it be possible to create a example config with two listners and loopback?

**Comment by kamranmohammed** [comment]
so this is the config that I could make:
`admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      protocol: TCP
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          protocol: TCP
          port_value: 31000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: http
                      domains:
                        - "*"
                      routes:
                        - match:
                            connect_matcher: {}
                            # prefix: "/"
                          # redirect:
                          #   port_redirect: 31001
                          #   https_redirect: false
                          route:
                            cluster: local_service
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config:
                                    proxy_protocol_config:
                                      version: V1
                                    allow_post: true
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext-authz
                        timeout: 1s
                      include_peer_certificate: true
                      transport_api_version: V3
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http_protocol_options: {}
                # upgrade_configs:
                # - upgrade_type: CONNECT
    - name: listener_1
      address:
        socket_address:
          address: 0.0.0.0
          protocol: TCP
          port_value: 31001
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: http
                      domains:
                        - "*"
                      routes:
                        - match:
                            # connect_matcher: {}
                            prefix: "/"
                          route:
                            cluster: proxy
                            # upgrade_configs:
                            #   - upgrade_type: CONNECT
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: ext-authz
      type: STRICT_DNS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: ext-authz
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: proxy_config
                      port_value: 8100
    - name: proxy
      connect_timeout: 1s
      type: STRICT_DNS
      load_assignment:
        cluster_name: proxy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: <Corp http proxy>
                      port_value: 8080
    - name: local_service
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: local_service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 31001
`
but I get the following error:
`curl -vvv --proxy-insecure --proxy http://localhost:31000 https://www.google.com -U proxyuser:proxypass
*   Trying ::1:31000...
* Connected to localhost (::1) port 31000 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
* Proxy auth using Basic with user 'proxyuser'
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> Proxy-Authorization: Basic cHJveHl1c2VyOnByb3h5cGFzcw==
> User-Agent: curl/7.77.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< date: Wed, 22 Jun 2022 02:30:48 GMT
< server: envoy
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number`

**Comment by kamranmohammed** [comment]
@yanavlasov and @alyssawilk please help!

**Comment by yanavlasov** [comment]
You need to remove `connect_config` from you route and add TLS `transport_socket` configuration to the filter chain in the `listener_1`. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#config-listener-v3-filterchain

**Comment by kamranmohammed** [comment]
so it kinda works but I do not understand it fully. So here is the working configuration:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      protocol: TCP
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          protocol: TCP
          port_value: 31000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: http
                      domains:
                        - "*"
                      routes:
                        - match:
                            connect_matcher: {}
                            # prefix: "/"
                          # redirect:
                          #   port_redirect: 31001
                          #   https_redirect: false
                          route:
                            cluster: local_service
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                # connect_config:
                                #     proxy_protocol_config:
                                #       version: V1
                                #     allow_post: true
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext-authz
                        timeout: 1s
                      include_peer_certificate: true
                      transport_api_version: V3
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                # http_protocol_options: {}
                # upgrade_configs:
                # - upgrade_type: CONNECT
    - name: listener_1
      address:
        socket_address:
          address: 0.0.0.0
          protocol: TCP
          port_value: 31001
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: http
                      domains:
                        - "*"
                      routes:
                        - match:
                            # connect_matcher: {}
                            prefix: "/"
                          route:
                            cluster: proxy
                            # upgrade_configs:
                            #   - upgrade_type: CONNECT
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain: { "filename": "/etc/envoy/tls-crt.pem" }
                    private_key: { "filename": "/etc/envoy/tls-key.pem" }
  clusters:
    - name: ext-authz
      type: STRICT_DNS
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: ext-authz
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: proxy_config
                      port_value: 8100
    - name: proxy
      connect_timeout: 1s
      type: STRICT_DNS
      load_assignment:
        cluster_name: proxy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: <corp http proxy>
                      port_value: 8080
    - name: local_service
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: local_service
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 31001
```

so when I run this:
```
curl -vvv --proxy-insecure --proxy http://localhost:31000 https://www.google.com -U proxyuser:proxypass 
*   Trying ::1:31000...
* Connected to localhost (::1) port 31000 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to www.google.com:443
* Proxy auth using Basic with user 'proxyuser'
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> Proxy-Authorization: Basic cHJveHl1c2VyOnByb3h5cGFzcw==
> User-Agent: curl/7.77.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 OK
< date: Fri, 24 Jun 2022 07:34:25 GMT
< server: envoy
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

but when I run this:
```
curl -vvv --proxy-insecure --proxy http://localhost:31000 https://www.google.com -U proxyuser:proxypass -k
```

it works I get back google.com html page. 
But I don't understand why I need the `-k` flag for it to run? Because my corp proxy is not HTTPS and https://www.google.com should have a valid and legitimate cert so why do I need to even provide a server cert in my transport_socket config. If I don't provide it won't work.

Can you please explain @yanavlasov ? Thank you!
