### ISSUE TITLE
proposal: add regex engine factory and config option

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#21618]
*Title*: Add regex engine factory and config option

*Description*:

Nowadays, we use RE2 as the only regex engine in Envoy. In scenario with a large number of regex matcher like a gateway, users may face high CPU usage and performance bottleneck.

We can make regex engine extensible, to introduce a bootstrap config option to configure regex engine and its option like `SocketInterface`. We can benefit both a simpler regex matcher configuration since engine-specific options will be removed (see API change below) and avoiding the runtime value like `re2.max_program_size.error_level` since they can be configured in `bootstrap_extensions`.

*API change*:

```yaml
safe_regex:
  # All the fields in google_re2 have been deprecated, but google_re2 is still required by safe_regex.
  # We will deprecate it this time.
  # google_re2: {}
  regex: "/safe.*"
```

```yaml
# If the default_regex_engine is unset, RE2 will be used by default.
default_regex_engine: envoy.regex_engine.google_re2
bootstrap_extensions:
- name: envoy.regex_engine.google_re2
  typed_config:
    '@type': type.googleapis.com/envoy.type.matcher.v3.RegexMatcher.GoogleRE2
    # Options like max_program_size can be configured here.
```
