### ISSUE TITLE
[ASK] Envoy Cors Configuration Sample

### ISSUE THREAD

**Issue by syukur91** [envoyproxy/envoy#2167]
@mattklein123  Is there any example how to set cors enabled in route config? I can't find valid example out there.

Thank you

**Comment by codesuki** [comment]
Just found this issue by accident. 
Maybe I find the time to add an example in the near future. For now maybe this helps?
```
listeners:
- address: tcp://0.0.0.0:443
  filters:
  - type: read
    name: http_connection_manager
    config:
      access_log:
      - path: /dev/stdout
      codec_type: auto
      stat_prefix: ingress_http
      route_config:
        virtual_hosts:
        - name: gateway
          domains:
          - "*"
          cors:
            allow_origin: ["*"]
            allow_headers: "content-type, x-grpc-web"
            allow_methods: "POST"
          routes:
          - timeout_ms: 0
            prefix: /serviceA
            cluster: serviceA
          - timeout_ms: 0
            prefix: /serviceB
            cluster: experiment
            cors:
              enabled: false
      filters:
      - type: both
        name: cors
        config: {}
     - type: both
        name: grpc_web
        config: {}
      - type: decoder
        name: router
        config: {}
admin:
  access_log_path: /dev/stdout
  address: tcp://0.0.0.0:8001
cluster_manager:
  clusters:
  - name: featureA
    connect_timeout_ms: 250
    type: strict_dns
    lb_type: round_robin
    hosts:
    - url: tcp://featureA
  - name: featureB
    connect_timeout_ms: 250
    type: strict_dns
    lb_type: round_robin
    hosts:
    - url: tcp://featureB
```
