### ISSUE TITLE
Efficient access logging configuration

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#21718]
*Title*: Efficient access logging configurationrt

*Description*:
Currently, access logging configuration has a massive impact on our XDS configuration size. Because we customize the format, we must repeat this format for many many times. This adds up a lot.

On a fairly small cluster I end up with 400 access log configs. The LDS is 700kb. Disabling access logs drops it down to 200kb.

Example config:

```yaml
typed_config:
  '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
  access_log:
  - name: envoy.access_loggers.file
    typed_config:
      '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      log_format:
        json_format:
          authority: '%REQ(:AUTHORITY)%'
          bytes_received: '%BYTES_RECEIVED%'
          bytes_sent: '%BYTES_SENT%'
          connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
          downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'
          downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
          duration: '%DURATION%'
          method: '%REQ(:METHOD)%'
          path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
          protocol: '%PROTOCOL%'
          request_id: '%REQ(X-REQUEST-ID)%'
          requested_server_name: '%REQUESTED_SERVER_NAME%'
          response_code: '%RESPONSE_CODE%'
          response_code_details: '%RESPONSE_CODE_DETAILS%'
          response_flags: '%RESPONSE_FLAGS%'
          route_name: '%ROUTE_NAME%'
          start_time: '%START_TIME%'
          upstream_cluster: '%UPSTREAM_CLUSTER%'
          upstream_host: '%UPSTREAM_HOST%'
          upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'
          upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
          upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'
          user_agent: '%REQ(USER-AGENT)%'
          x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'
      path: /dev/stdout
```

This same config is repeated verbatum almost every time. While we need the ability to have different formats in different places, and to dynamically update these, we would want some way this config could be shared (ECDS?)

cc @kyessenov on ECDS comment
