### ISSUE TITLE
How can I configure local rate limit for per remote ip address?

### ISSUE THREAD

**Issue by SpecialYang** [envoyproxy/envoy#21734]
In the local rate limit filter, the token bucket is shared across all workers. I found that the option `local_rate_limit_per_downstream_connection` can set rate limit scope to per connection. But now, we expect that scope can be per remote ip.
We can generate remote ip descriptor via [RateLimit Action RemoteAddress](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-ratelimit-action-remoteaddress). But, how can i use the generated remote ip descriptor to configure local rate limit for per remote ip address?

**Comment by RyanTheOptimist** [comment]
@htuch do you have any thoughts here?

**Comment by SpecialYang** [comment]
> @htuch do you have any thoughts here?

Any ideas?

**Comment by htuch** [comment]
This isn't something I'm super familiar with, tagging @mattklein123 @wbpcode

**Comment by wbpcode** [comment]
Sorry. It seems that the limiter for per remote address is not supported for now.

**Comment by vnayar** [comment]
> Sorry. It seems that the limiter for per remote address is not supported for now.

Do you know if this will change in the future? For comparison, other services capable as acting like reverse-proxies, such as Nginx, solve this concept without requiring an external service (like global rate limiting requires): https://www.nginx.com/blog/rate-limiting-nginx/

One possibility could be to allow route descriptor action keys to be placed, like adding the IP of the caller, and then allow route descriptor entries that lack this key to treat each unique value of that key as a separate token bucket.

Using the rate limit example here: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/local_rate_limit_filter#config-http-filters-local-rate-limit-descriptors

Imagine if we had something like:
```
                    - entries:
                      - key: client_cluster
                        value: foo
                      # Idea: By leaving the path empty, each unique path gets its own bucket.
                      #- key: path
                      #  value: /foo/bar2
                      token_bucket:
                        max_tokens: 100
                        tokens_per_fill: 100
                        fill_interval: 60s
```

**Comment by sabershahhoseini** [comment]
Any updates? Does local rate limit support per IP limits?

**Comment by evevseev** [comment]
It would be very helpful for us as well

**Comment by gcalmettes** [comment]
It looks like you can do it using the [local rate limit filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-msg-extensions-filters-http-local-ratelimit-v3-localratelimit)

example configuration:
```
          - name: http_rate_limiter
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit"
              stat_prefix: http_rate_limit
              descriptors:
              - entries:
                - key: remote_address
                  value: ""   # blank value creates a dynamic bucket per unique IP
                token_bucket:
                  max_tokens: 100
                  tokens_per_fill: 100
                  fill_interval: 1s
              # build a descriptor from the trusted client address
              rate_limits:
              - actions:
                - remote_address: {}   # uses envoy's trusted client address from XFF handling
              status:
                code: 429
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
              - header:
                  key: "x-global-rate-limit-status"
                  value: "exceeded"
                append_action: OVERWRITE_IF_EXISTS_OR_ADD
```
