### ISSUE TITLE
EnvoyMetricsService receiving empty histograms and summaries

### ISSUE THREAD

**Issue by marcosrmendezthd** [envoyproxy/envoy#21812]
*Description*:

Using Envoy 1.22.2 and hooking it up to a grpc metric sink for prometheus to scrape later. I'm noticing that while the counters and gauges are coming in correctly, the summaries and histograms are empty. The histograms have buckets, but no samples. If I check on the envoy prometheus metrics, the histograms have values and there are no summaries (not sure why I'm getting those on the grpc sink). Neither the summaries nor the histograms have any actual samples. In the configuration below I tried adding a stats_config to set the default buckets just in case, but it doesn't seem to be working. Any ideas?

```
% envoy --version

envoy  version: c919bdec19d79e97f4f56e4095706f8e6a383f1c/1.22.2/Modified/RELEASE/BoringSSL

```

*Admin and Stats Output*:

/stats/prometheus output for the `envoy_cluster_upstream_cx_connect_ms` histogram

```
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="0.5"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="1"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="5"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="10"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="25"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="50"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="100"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="250"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="500"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="1000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="2500"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="5000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="10000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="30000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="60000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="300000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="600000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="1800000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="3600000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="envoy_exporter",le="+Inf"} 2
envoy_cluster_upstream_cx_connect_ms_sum{envoy_cluster_name="envoy_exporter"} 4.0999999999999996447286321199499
```

*Config*:

```
overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
        max_heap_size_bytes: 2147483648 # 2 GiB
  actions:
    - name: "envoy.overload_actions.shrink_heap"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.95
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
        - name: "envoy.resource_monitors.fixed_heap"
          threshold:
            value: 0.98

static_resources:
  clusters:
    - name: control_plane
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      connect_timeout:
        seconds: 5
      dns_lookup_family: V4_ONLY
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          common_http_protocol_options: { }
          upstream_http_protocol_options: { }
          explicit_http_config:
            http2_protocol_options:
              max_concurrent_streams: 100
              initial_stream_window_size: 65536 # 64 KiB
              initial_connection_window_size: 1048576 # 1 MiB
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 1
          keepalive_time: 10
          keepalive_interval: 10
      load_assignment:
        cluster_name: control_plane
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7001

    - name: envoy_exporter
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      connect_timeout:
        seconds: 5
      dns_lookup_family: V4_ONLY
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          common_http_protocol_options: { }
          upstream_http_protocol_options: { }
          explicit_http_config:
            http2_protocol_options:
              max_concurrent_streams: 100
              initial_stream_window_size: 65536 # 64 KiB
              initial_connection_window_size: 1048576 # 1 MiB
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 1
          keepalive_time: 10
          keepalive_interval: 10
      load_assignment:
        cluster_name: envoy_exporter
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 11001

dynamic_resources:
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: control_plane
  cds_config:
    resource_api_version: V3
    ads: {}
  lds_config:
    resource_api_version: V3
    ads: {}

cluster_manager:
  outlier_detection:
    event_log_path: "/dev/stdout"

node:
  id: service-proxy
  cluster: control_plane

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 15000 }

layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              "listener_443:0.0.0.0:443":
                connection_limit: 10000
        overload:
          global_downstream_max_connections: 50000

#stats_config:
#  histogram_bucket_settings:
#    - match:
#        safe_regex:
#          google_re2: { }
#          regex: ".*?"
#      buckets:
#        - 0.5
#        - 1
#        - 5
#        - 10
#        - 25
#        - 50
#        - 100
#        - 250
#        - 500
#        - 1000
#        - 2500
#        - 5000
#        - 10000
#        - 30000
#        - 60000
#        - 300000
#        - 600000
#        - 1800000
#        - 3600000

stats_sinks:
  - name: envoy.stat_sinks.metrics_service
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.MetricsServiceConfig
      transport_api_version: V3
      emit_tags_as_labels: true
      grpc_service:
        envoy_grpc:
          cluster_name: envoy_exporter

```

**Comment by marcosrmendezthd** [comment]
some screenshots of my empty histograms.

<img width="531" alt="Screen Shot 2022-06-21 at 7 00 04 PM" src="https://user-images.githubusercontent.com/13423168/174911031-9a77b903-c3b7-41ff-9b93-d52c4a9bfc14.png">
<img width="487" alt="Screen Shot 2022-06-21 at 7 00 14 PM" src="https://user-images.githubusercontent.com/13423168/174911038-7202e2ce-8399-49ff-a2d4-746e8715946b.png">
<img width="618" alt="Screen Shot 2022-06-21 at 7 00 38 PM" src="https://user-images.githubusercontent.com/13423168/174911042-a0cf34a5-5c2c-465c-bcea-b4dafc6b3bcf.png">

**Comment by marcosrmendezthd** [comment]
a better example:

this is what envoy exposes on /stats/prometheus


```
# TYPE envoy_cluster_upstream_cx_connect_ms histogram
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="0.5"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="1"} 0
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="5"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="10"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="25"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="50"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="100"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="250"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="500"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="1000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="2500"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="5000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="10000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="30000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="60000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="300000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="600000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="1800000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="3600000"} 2
envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name="exporter",le="+Inf"} 2
envoy_cluster_upstream_cx_connect_ms_sum{envoy_cluster_name="exporter"} 6.0999999999999996447286321199499
envoy_cluster_upstream_cx_connect_ms_count{envoy_cluster_name="exporter"} 2
```

this is what the sample program sees:

```

2022/06/22 11:22:48 empty histogram
2022/06/22 11:22:48 summary cluster.upstream_cx_connect_ms{"envoy.cluster_name"="exporter"} quantile:<quantile:0 value:nan > quantile:<quantile:0.25 value:nan > quantile:<quantile:0.5 value:nan > quantile:<quantile:0.75 value:nan > quantile:<quantile:0.9 value:nan > quantile:<quantile:0.95 value:nan > quantile:<quantile:0.99 value:nan > quantile:<quantile:0.995 value:nan > quantile:<quantile:0.999 value:nan > quantile:<quantile:1 value:nan > 
2022/06/22 11:22:48 empty histogram

```

**Comment by marcosrmendezthd** [comment]
to reproduce this run envoy 1.22.0 with the following configuration.

$ envoy --version
   envoy  version: c919bdec19d79e97f4f56e4095706f8e6a383f1c/1.22.2/Modified/RELEASE/BoringSSL

$ envoy -c envoy.yaml


```

static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: service
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 1
          keepalive_time: 10
          keepalive_interval: 10
      load_assignment:
        cluster_name: service1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8000
    - name: exporter
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      connect_timeout:
        seconds: 5
      dns_lookup_family: V4_ONLY
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          common_http_protocol_options: { }
          upstream_http_protocol_options: { }
          explicit_http_config:
            http2_protocol_options:
              max_concurrent_streams: 100
              initial_stream_window_size: 65536 # 64 KiB
              initial_connection_window_size: 1048576 # 1 MiB
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 1
          keepalive_time: 10
          keepalive_interval: 10
      load_assignment:
        cluster_name: exporter
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9000
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000

#stats_config:
#  histogram_bucket_settings:
#    - match:
#        safe_regex:
#          google_re2: { }
#          regex: ".*?"
#      buckets:
#        - 0.5
#        - 1
#        - 5
#        - 10
#        - 25
#        - 50
#        - 100
#        - 250
#        - 500
#        - 1000
#        - 2500
#        - 5000
#        - 10000
#        - 30000
#        - 60000
#        - 300000
#        - 600000
#        - 1800000
#        - 3600000

stats_sinks:
  - name: envoy.stat_sinks.metrics_service
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.MetricsServiceConfig
      transport_api_version: V3
      emit_tags_as_labels: true
      grpc_service:
        envoy_grpc:
          cluster_name: exporter

```
