### ISSUE TITLE
Dynamic metadata match not working

### ISSUE THREAD

**Issue by andresmargalef** [envoyproxy/envoy#21888]
*Title*: *Dynamic metadata match not working*

*Description*:
I'm using the lua filter to analize some headers and set some dynamic metadata. That metadata is used in `config.route.v3.RouteMatch.dynamic_metadata` for route matching.
Using the following configuration with `curl localhost:8080 -i` then the result is:
```
HTTP/1.1 404 Not Found
date: Sat, 25 Jun 2022 02:42:15 GMT
server: envoy
content-length: 0
```
but if I uncomment these lines in lua method
```
--request_handle:headers():add("my-header", "my-header-value")
--request_handle:headers():remove("my-header")
```
then the result for the same curl is

```
HTTP/1.1 200 OK
content-length: 9
content-type: text/plain
date: Sat, 25 Jun 2022 02:45:59 GMT
server: envoy

It works!
```

*Config*:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  -- UNCOMMENT NEXT 2 LINES TO START WORKING

                  --request_handle:headers():add("my-header", "my-header-value")
                  --request_handle:headers():remove("my-header")

                  request_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.router", "somepath", "somevalue")
                end
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  dynamic_metadata:
                  - filter: "envoy.filters.http.router"
                    path:
                    - key: somepath
                    value:
                      string_match:
                        prefix: somevalue
                direct_response:
                  body:
                    inline_string: 'It works!'
                  status: 200
```

*Repro steps*:
1. Download envoy 1.21.1
2. Run envoy with config file from above
3. run `curl localhost:8080 -i` and expect status code 404
4. stop envoy
5. Uncomment the lines mentioned in the description
6. repeat step 2) and 3) but now expect status code 200
