### ISSUE TITLE
How to verify upstream TLS certificates?

### ISSUE THREAD

**Issue by pschultz** [envoyproxy/envoy#2189]
Can't get Envoy to verify upstream certificates

While playing around with Envoy I noticed some requests succeeding that shouldn't have, because the upstream cluster is serving certificates that Envoy should have rejected.

Consider this configuration:

```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 5000 }

static_resources:
  listeners:
    - name: egress
      address:
        socket_address: { address: 0.0.0.0, port_value: 3128 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: egress_http
                codec_type: AUTO
                http_filters:
                  - name: envoy.router
                route_config:
                  virtual_hosts:
                    - name: egress
                      domains: ['*']
                      routes:
                        - match: { prefix: / }
                          route: { cluster: "my-service" }

  clusters:
    - name: my-service
      connect_timeout: 0.1s
      type: STATIC
      lb_policy: ROUND_ROBIN
      http_protocol_options: {}
      tls_context: {}
      hosts:
        - socket_address: { address: 127.0.0.1, port_value: 4000 }
```
The HTTP server on port 4000 is implemented by this trivial Go programm:

```go
package main

import (
        "log"
        "net/http"
        "os"
)

func main() {
        log.Fatal(http.ListenAndServeTLS(":4000", os.Args[1], os.Args[2], nil))
}
```

No matter what certificate I have the Go program serve, the requests through Envoy always succeed. For instance:

```
$ curl https://localhost:4000
curl: (60) Peer's Certificate has expired.                          
[...]

$ curl -i http://localhost:3128
HTTP/1.1 404 Not Found
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Tue, 12 Dec 2017 10:47:07 GMT
content-length: 19
x-envoy-upstream-service-time: 7
server: envoy

404 page not found
```

How can I enable certificate verification in Envoy?
