### ISSUE TITLE
local reply modification: support non-string values in Substitution format string in json_format

### ISSUE THREAD

**Issue by kfaseela** [envoyproxy/envoy#21941]
*Description*:

We configure “local reply modification” to modify status codes for certain local replies (“local” means that Envoy generates these replies, not an upstream host).
Documentation here: https://www.envoyproxy.io/docs/envoy/v1.22.2/configuration/http/http_conn_man/local_reply.html

We also add a body with content-type application/problem+json according to RFC 7807 (https://www.rfc-editor.org/rfc/rfc7807.html). For this, we use a “SubstitutionFormatString” in “json_format” (documented here: https://www.envoyproxy.io/docs/envoy/v1.22.2/api-v3/config/core/v3/substitution_format_string.proto#envoy-v3-api-field-config-core-v3-substitutionformatstring-json-format).

In this documentation there is an example that shows the JSON object to be created with a “status” field formatted as an integer:

```
                   status_code: 401
                    body_format_override:
                      json_format: 
                        title: "Bad request"
                        status: 400
                        cause: "MANDATORY_IE_INCORRECT"
                       detail: "%RESPONSE_CODE_DETAILS%"
```

However, when we configure a json_format with an integer value, Envoy rejects the configuration because it expects a string. If we put a string there, we get a string value in the JSON output.  The RFC mentioned above specifies an integer value for the “status” field (see chapter 3.1 of the [RFC 7807](https://www.rfc-editor.org/rfc/rfc7807.html), and that is our problem.  The screenshot below shows the error from Envoy (on envoylint.com):

![envoy-json-format-bug](https://user-images.githubusercontent.com/7901446/176433901-ea5e8f51-4328-4cd4-99ac-4e1421a3213c.jpg)

We have checked the Envoy issues on Github to see if somebody else reported this problem already but did not find an existing bug.  We did find however something that is related where somebody fixed a very similar issue in the access log: https://github.com/envoyproxy/envoy/issues/8374

We are using Envoy 1.22.0/1.22.2 (latest released version).
