### ISSUE TITLE
http rbac metadata config is not effectve

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#21975]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
I configured jwt auth,with header to metadata ,then using this metadata to rbac,but not work
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

ef-jwt-providers-header_in_metadata.yaml

kubectl apply -f ef-jwt-providers-header_in_metadata.yaml -n istio-system

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: jwt
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  priority: 20
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.jwt_authn
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
            providers:
              origins-0:
                forward: true
                issuer: testing@secure.istio.io
                header_in_metadata: my_header
                remote_jwks:
                  http_uri: 
                    uri: jwt-server.istio.svc.cluster.local:8080
                    cluster: outbound|8080||jwt-server.istio.svc.cluster.local
                    timeout: 1s
                  retry_policy:
                    retry_back_off:
                      base_interval: 0.01s
                      max_interval: 20s
                    num_retries: 10
                  cache_duration: 60s
            rules:
            - match:
                prefix: /
              requires:
                requiresAny:
                  requirements:
                  - providerName: origins-0
                  - allowMissing: {}
```

ef-rbac-metadata.yaml

kubectl apply -f ef-rbac-metadata.yaml -n istio-sytem

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: match
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  priority: 20
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:         
          name: envoy.filters.http.rbac
          typedConfig:
            '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
            rules:
              action: DENY
              policies:
                "product-viewer":
                  permissions:
                  - metadata:
                      filter: istio_authn
                      path:
                      - key: envoy.filters.http.jwt_authn.my_header.kid
                      value:
                        string_match:
                          exact: "cIcAfQ3B8kj2ucJTDABS7jTqVQ5fjwKQV7whPNLFCW4"
                  principals:
                  - any: true
```

```
TOKEN=eyJraWQiOiJjSWNBZlEzQjhrajJ1Y0pUREFCUzdqVHFWUTVmandLUVY3d2hQTkxGQ1c0IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJmb28iOiJiYXIiLCJzdWIiOiJ0ZXN0aW5nQHNlY3VyZS5pc3Rpby5pbyIsInVzZXJJZCI6Im1hcmsiLCJzY29wZSI6WyJzY29wZTEiLCJzY29wZTIiXSwiaXNzIjoidGVzdGluZ0BzZWN1cmUuaXN0aW8uaW8iLCJleHAiOjE2NTk4Mzc5OTksImlhdCI6MTY1NjMwMDYwOCwiZ3JvdXAiOlsiZ3JvdXAxIiwiZ3JvdXAyIl19.Dfp7uF_GO5h2tvjx74PpzT3Im46jUSmmJjPiAzDr9Z-VYJ1XR5KjIUj8jcB9kDA2rQA-K8IcvO8RE03j2VLg1BCbrOioYR1K-VU95HAjdWudM1MvCQjaMUkrgnPwHYHwd_tUhCRHRGSlyWpGfvn7nnAy4QX838UuyXVI91axpatvCaLjut7W1Y8-Fxwk8XIgVaB2KbyShbc2nfJMDU_cKx4SdXSJKesb1_EcpcdbsCERPDSoU3pNBtsWgyxbPg9E_HaUkiw0ROcgX01VZOONCFSCrtVR6rZombCCvlZ88M1oNWxUWMVsAriOK0zB_tmZM40yGkK78RxlPcdErLG3mg


curl 192.168.229.128:30555/productpage -H "Authorization: Bearer ${TOKEN}"
```
