### ISSUE TITLE
how to send connect method connection?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#21999]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
how to send connect method connection?
*Description*:
>Describe the issue.
[root@node01 httpmatch]# curl -X CONNECT 192.168.229.128:30639 -I
HTTP/1.1 400 Bad Request
content-length: 11
content-type: text/plain
date: Sun, 03 Jul 2022 06:13:15 GMT
server: envoy
connection: close

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: match
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: ADD
      value:
        name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 31400
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains:
                  - "*"
                  routes:
                  - match:
                      connect_matcher:
                        {}
                    route:
                      cluster: service_google
                      upgrade_configs:
                      - upgrade_type: CONNECT
                        connect_config:
                          {}
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              http_protocol_options: {}
              upgrade_configs:
              - upgrade_type: CONNECT
  - applyTo: CLUSTER
    patch:
      operation: ADD
      value: 
        name: service_google
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: service_google
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: www.baidu.com
                    port_value: 443
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
