### ISSUE TITLE
what is   local_reply_config 's function,I test the request,with productpage result,not local_reply_config  body?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22087]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpconnectionmanager
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        prefix: /product
                      route:
                        weighted_clusters:
                          clusters:
                          - name: outbound|9080||productpage.istio.svc.cluster.local
                            weight: 100
                          total_weight: 100
                          runtime_key_prefix: test
                local_reply_config:
                  mappers:
                  - status_code: 200
                    filter:
                      header_filter:
                        header:
                          name: test
                          exact_match: test
                    body: 
                      inline_string: "test"
                    body_format_override:
                      text_format: "%LOCAL_REPLY_BODY%:%RESPONSE_CODE%:path=%REQ(:path)%\n" 
                    headers_to_add:
                    - header:
                        key: test
                        value: test
                      append: true
                  body_format:
                    text_format: "%LOCAL_REPLY_BODY%:%RESPONSE_CODE%:path=%REQ(:path)%\n"      
```

curl -H "test: test" http://192.168.229.128:30563/productpage
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by adisuissa** [comment]
I've compiled the latest Envoy and executed with the following config:
```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: test
            virtual_hosts:
            - name: test
              domains:
              - "*"
              routes:
              - name: testroute
                match:
                  prefix: /product
                route:
                  weighted_clusters:
                    clusters:
                    - name: some_service
                      weight: 100
                    total_weight: 100
                    runtime_key_prefix: test
          local_reply_config:
            mappers:
            - status_code: 200
              filter:
                header_filter:
                  header:
                    name: test
                    exact_match: test
              body:
                inline_string: "test"
              body_format_override:
                text_format: "%LOCAL_REPLY_BODY%:%RESPONSE_CODE%:path=%REQ(:path)%\n"
              headers_to_add:
              - header:
                  key: test
                  value: test
                append: true
            body_format:
              text_format: "%LOCAL_REPLY_BODY%:%RESPONSE_CODE%:path=%REQ(:path)%\n"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
```

Then I ran the following and got the result:
```
$ curl -H "test: test" http://127.0.0.1:10000/productpage
test:200:path=/productpage
```

Note that I needed to add `stat_prefix: ingress_http` to the config, otherwise the config was rejected.
