### ISSUE TITLE
why this config is 404

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22095]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadata
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      metadata:
                        filter_metadata:
                          "envoy.lb": 
                            canary: "true"
                      match: 
                        path: /tEst
                        case_sensitive: false
                        dynamic_metadata:
                        - filter: envoy.lb
                          path:
                          - key: canary
                          value:
                            string_match:
                              exact: "true"
                          invert: false
                      direct_response:
                        status: 200
                        body: 
                          inline_string: "runtime_fraction"
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
