### ISSUE TITLE
Envoy bug of eating and omitting `host` header

### ISSUE THREAD

**Issue by winguse** [envoyproxy/envoy#2209]
## Description

The node.js client want to send traffic to envoy ingress port, using the binding of `ip_address:port`, but setting `host` header for routing by virtual host.

But Envoy will eat and omit the header.

## Reproduce and other information

I've setup a simplest project here: https://github.com/winguse/envoy-grpc-host-header-bug

### Envoy config

```yaml
listeners:
  # ingress
  - address: tcp://127.0.0.1:10001
    filters:
      - name: http_connection_manager
        config:
          codec_type: auto
          stat_prefix: grpc.test.ingress
          route_config:
            virtual_hosts:
              - name: local_test_server
                domains: ["*"]
                routes:
                - prefix: /
                  headers:
                  - name: content-type
                    value: application/grpc
                  cluster: local_test_server
          filters:
            - name: router
              config:
                dynamic_stats: true
          tracing:
            operation_name: ingress
          access_log:
          - path: ./envoy.ingress.log
            filter:
              type: not_healthcheck

# Administration interface
admin:
  access_log_path: /dev/null
  address: tcp://0.0.0.0:10013


# Cluster manager
cluster_manager:
  clusters:
  - name: local_test_server
    type: static
    connect_timeout_ms: 1000
    lb_type: round_robin
    features: http2
    hosts:
    - url: tcp://127.0.0.1:10000
```

### Client code

```javascript
const grpc = require("grpc");

const { Ping } = grpc.load("./ping.proto").test;

const metadata = new grpc.Metadata();
metadata.add("host", "ping.pong:10000");
metadata.add("authority", "ping.pong:10000");

const client = new Ping("127.0.0.1:10001", grpc.credentials.createInsecure());
client.send({ message: "ping via envoy" }, metadata, (error, response) => {
	if (error) {
		console.log("error", error);
	}
	console.log("response", response);
});



const directClient = new Ping("127.0.0.1:10000", grpc.credentials.createInsecure());
directClient.send({ message: "ping directly" }, metadata, (error, response) => {
	if (error) {
		console.log("error", error);
	}
	console.log("response", response);
});
```

### Server code

```javascript
const grpc = require("grpc");

const { Ping } = grpc.load("./ping.proto").test;


const server = new grpc.Server();
server.addService(Ping.service, {
	send: (call, callback) => {
		console.log("got request", call.request, call.metadata.getMap());
		callback(undefined, { message: "pong" });
	}
});
server.bind("127.0.0.1:10000", grpc.ServerCredentials.createInsecure());
server.start();
```

### Server stdout

without envoy

```text
got request { message: 'ping directly' } { host: 'ping.pong:10000',
  authority: 'ping.pong:10000',
  'user-agent': 'grpc-node/1.7.3 grpc-c/5.0.0 (linux; chttp2; gambit)' }
```

with envoy, `host` header is missing.

```text
got request { message: 'ping via envoy' } { authority: 'ping.pong:10000',
  'user-agent': 'grpc-node/1.7.3 grpc-c/5.0.0 (linux; chttp2; gambit)',
  'x-forwarded-proto': 'http',
  'x-request-id': '0bcd8b61-fbe5-94cd-b568-8a6baf9299b7',
  'x-envoy-expected-rq-timeout-ms': '15000' }
```

### Envoy log

```log
[2017-12-14T09:16:04.446Z] "POST /test.Ping/Send HTTP/2" 200 - 21 11 9 8 "-" "grpc-node/1.7.3 grpc-c/5.0.0 (linux; chttp2; gambit)" "0bcd8b61-fbe5-94cd-b568-8a6baf9299b7" "127.0.0.1:10001" "127.0.0.1:10000"
```

We can see `%REQ(:AUTHORITY)%` equals to `127.0.0.1:10001` is not set correctly as expected to be `ping.pong:10000`.

This bug will resulting in we cannot route the traffic base on virtual host name.
