### ISSUE TITLE
how to get route_metadata in wasm?

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22166]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
package main

import (
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

func main() {
        proxywasm.SetVMContext(&vmContext{})
}

type vmContext struct {
        // Embed the default VM context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultVMContext
}

// Override types.DefaultVMContext.
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
        return &pluginContext{}
}

type pluginContext struct {
        // Embed the default plugin context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultPluginContext
}

// Override types.DefaultPluginContext.
func (*pluginContext) NewHttpContext(contextID uint32) types.HttpContext {
        return &httpHeaders{contextID: contextID}
}

type httpHeaders struct {
        // Embed the default http context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultHttpContext
        contextID uint32
}

// Override types.DefaultHttpContext.
func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
        path :=[]string{"plugin_vm_id"}
        data,err := proxywasm.GetProperty(path) 
        if err != nil {
                proxywasm.LogCritical("failed to get property")
        }

        proxywasm.LogCriticalf("property(%s): %s", "plugin_vm_id",string(data))
        
        path=[]string{"route_metadata","envoy.lb","canary"}
        data,err = proxywasm.GetProperty(path)
        
        if err != nil {
                proxywasm.LogCritical("failed to get property")
        }

        proxywasm.LogCriticalf("property(%s): %s", "route_metadata",string(data))
        return types.ActionContinue
}



```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: metadata
spec:
  workloadSelector:
    labels:
      app: productpage
  priority: 10
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          destinationPort: 9080
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: REPLACE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: "inbound_0.0.0.0_9080"
                route_config:
                  name: test
                  virtual_hosts:
                  - name: test
                    domains:
                    - "*"
                    routes:
                    - name: testroute
                      match: 
                        prefix: /
                      metadata:
                        filter_metadata:
                          "envoy.lb": 
                            canary: true
                      route:
                        cluster: inbound|9080||
                        timeout: "0s"
                        max_stream_duration:
                          max_stream_duration: "0s"
                http_filters:
                - name: "envoy.filters.http.router"
                  typed_config:
                    "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
```

```
2022-07-13T09:00:06.471846Z     critical        envoy wasm      wasm log my_plugin attribute_id attribute_vm_id: property(plugin_vm_id): attribute_vm_id
2022-07-13T09:00:06.471868Z     critical        envoy wasm      wasm log my_plugin attribute_id attribute_vm_id: failed to get property
2022-07-13T09:00:06.471871Z     critical        envoy wasm      wasm log my_plugin attribute_id attribute_vm_id: property(route_metadata): 
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
