### ISSUE TITLE
Envoy fails to parse cds v1 responses

### ISSUE THREAD

**Issue by ikruglov** [envoyproxy/envoy#2219]
*Title*: Envoy fails to parse cds v1 responses

*Description*:
when running both v1.5.0 and d5865073b with v1 controlplane envoy fails to validate v1 CDS response with "ssl_context" set in a cluster.

I've tracked the issue and it boils down to adding empty "certificate_chain" and "private_key" fields in UpstreamTlsContext and failing validation later. This bug is similar to #2188 which was fixed in #2190. I didn't have close look, but I suspect that there are might be more bugs of this kind. The code has a pattern which provoking such issues. For instance:
```
upstream_tls_context.set_sni(json_tls_context.getString("sni", ""));
```

I have a patch. I'll prepare a PR.

*Repro steps*:
*Config*:
bootstrap config
```yaml
node:
  id: node-id
  cluster: cluster-id
  locality:
    region: Europe
    zone: zone-id
static_resources:
  listeners:
  - name: tcp-127.0.0.1-9211
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 9211
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: egress_default
          rds:
            route_config_name: default
            config_source:
              api_config_source:
                api_type: REST_LEGACY
                refresh_delay: 1s
                cluster_name: controlplane
          http_filters:
          - name: envoy.router
            config: {}
          add_user_agent: true
          use_remote_address: true
          generate_request_id: true
          idle_timeout: 300s
  clusters:
  - name: controlplane
    type: STRICT_DNS
    lb_policy: RANDOM
    connect_timeout: 1s
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9902
dynamic_resources:
  cds_config:
    api_config_source:
      api_type: REST_LEGACY
      cluster_name: controlplane
      refresh_delay: 1s
  deprecated_v1:
    sds_config:
      api_config_source:
        api_type: REST_LEGACY
        cluster_name: controlplane
        refresh_delay: 1s
admin:
  access_log_path: admin_access.log
  profile_path: envoy.prof
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
runtime:
  symlink_root: "."
  subdirectory: ""
  override_subdirectory: override
```

CDS response:
```json
{
  "clusters": [
    {
      "name": "application",
      "service_name": "24d50d27e783772202ff14f61dbd273b",
      "type": "sds",
      "connect_timeout_ms": 1000,
      "lb_type": "least_request",
      "ssl_context": {
        "ca_cert_file": "ca-bundle.crt"
      }
    }
  ]
}
```

*Logs*:
```
[2017-12-17 01:24:23.616][9026645][warning][upstream] source/common/upstream/cds_subscription.cc:68] cds: fetch failure: Proto constraint validation failed (ClusterValidationError.TlsContext: ["embedded message failed validation"] | caused by UpstreamTlsContextValidationError.CommonTlsContext: ["embedded message failed validation"] | caused by CommonTlsContextValidationError.TlsCertificates[i]: ["embedded message failed validation"] | caused by TlsCertificateValidationError.CertificateChain: ["embedded message failed validation"] | caused by DataSour
ceValidationError.Filename: ["value length must be at least " '\x01' " bytes"]): name: "application"                                                                                                                                                                                  type: EDS
eds_cluster_config {
  eds_config {
    api_config_source {
      cluster_name: "controlplane"
      refresh_delay {
        seconds: 1
      }
    }
  }
  service_name: "24d50d27e783772202ff14f61dbd273b"
}
connect_timeout {
  seconds: 1
}
lb_policy: LEAST_REQUEST
tls_context {
  common_tls_context {
    tls_certificates {
      certificate_chain {
        filename: ""
      }
      private_key {
        filename: ""
      }
    }
    validation_context {
      trusted_ca {
        filename: "ca-bundle.crt"
      }
    }
    deprecated_v1 {
    }
  }
}
dns_lookup_family: V4_ONLY
```
