### ISSUE TITLE
how to config QuicDownstreamTransport ,got connection refused

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22195]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
set env

```
kubectl set env -n istio-system deploy istiod PILOT_ENABLE_QUIC_LISTENERS=true
kubectl rollout restart deploy -n istio-system istiod
```

```
          - name: http3
            port: 443
            targetPort: 8443
            protocol: UDP
```

create secret

httpbin.cnf

```
[req]
default_bits       = 2048
prompt             = no
distinguished_name = req_distinguished_name
req_extensions     = san_reqext

[ req_distinguished_name ]
countryName         = IN
stateOrProvinceName = KA
organizationName    = QuicCorp

[ san_reqext ]
subjectAltName      = @alt_names

[alt_names]
DNS.0   = httpbin.quic-corp.com
```

```
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -subj "/C=IN/ST=KA/O=QuicCorp" -keyout quiccorp-ca.key -out quiccorp-ca.crt

openssl req -out httpbin.csr -newkey rsa:2048 -nodes -keyout httpbin.key -config httpbin.cnf

openssl x509 -req -days 365 -CA quiccorp-ca.crt -CAkey quiccorp-ca.key -set_serial 0 -in httpbin.csr -out httpbin.crt -extfile httpbin.cnf -extensions san_reqext

```

```
kubectl -n istio-system create secret tls httpbin-cred --key=httpbin.key --cert=httpbin.crt
```

ef-filter_chains-quic_downstream.yaml

kubectl apply -f ef-filter_chains-quic_downstream.yaml -n istio-system

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: transport-socket
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: LISTENER
    match:
      context: GATEWAY
    patch:
      operation: ADD
      value:
        name: proxy
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 8443
        filter_chains:
        - filters:
          - name: "envoy.filters.network.http_connection_manager"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              stat_prefix: ingress_proxy
              codec_type: "HTTP3"
              route_config:
                name: route_a
                virtual_hosts:
                - name: envoy_cyz
                  domains:
                  - "*"
                  routes:
                  - name: testroute
                    match: 
                      prefix: /
                    direct_response:
                      status: 200
                      body: 
                        inline_string: "prefix"
                    response_headers_to_add:
                    - header:
                        key: "alt-svc"
                        value: "h3=:443; ma=86400"
                      append: true
              http_filters:
              - name: "envoy.filters.http.router"
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
              http3_protocol_options:
                quic_protocol_options:
                  max_concurrent_streams: 100
                  initial_stream_window_size: 65536 
                  initial_connection_window_size: 65536 
                  num_timeouts_to_trigger_port_migration: 1
                  connection_keepalive:
                    max_interval: 60s
                    initial_interval: 30s
                override_stream_error_on_invalid_http_message: true
                allow_extended_connect: true
          transport_socket: 
            name: "envoy.transport_sockets.quic"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport"
              downstream_tls_context:
                common_tls_context:
                  alpn_protocols:
                  - h3
                  tls_certificate_sds_secret_configs:
                  - name: "kubernetes://httpbin-cred"
                    sds_config:
                      ads: { }
                      resource_api_version: "V3"
                require_client_certificate: 
        traffic_direction: "OUTBOUND"
        udp_listener_config:
          downstream_socket_config: { }
          quic_options: { }
        reuse_port: true
```
```
[root@node01 transport-socket]# telnet 192.168.229.128 30508
Trying 192.168.229.128...
telnet: connect to address 192.168.229.128: Connection refused
[root@node01 transport-socket]# kubectl get svc -n istio-system
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP       PORT(S)                                                                      AGE
grafana                ClusterIP   10.68.126.229   <none>            3000/TCP                                                                     23d
istio-egressgateway    ClusterIP   10.68.67.157    <none>            80/TCP,443/TCP                                                               21d
istio-ingressgateway   NodePort    10.68.181.46    192.168.229.189   15021:32661/TCP,80:30563/TCP,443:30508/UDP,31400:30639/TCP,15443:31702/TCP   21d
istiod                 ClusterIP   10.68.180.246   <none>            15010/TCP,15012/TCP,443/TCP,15014/TCP                                        21d
jaeger-collector       ClusterIP   10.68.177.123   <none>            14268/TCP,14250/TCP                                                          23d
kiali                  ClusterIP   10.68.50.247    <none>            20001/TCP,9090/TCP                                                           23d
prometheus             ClusterIP   10.68.89.176    <none>            9090/TCP                                                                     30d
tracing                NodePort    10.68.82.93     <none>            80:30628/TCP                                                                 23d
zipkin                 ClusterIP   10.68.223.115   <none>            9411/TCP                                                                     23d
```

ingressgateway has no logs

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
