### ISSUE TITLE
connection_failure,QUIC_NO_ERROR_with_details:_Closed_by_application

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22192]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: transport-socket
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        #name: 0.0.0.0_8080  
        portNumber: 8080
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
            name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              codec_type: AUTO
              stat_prefix: ingress_http
              route_config:
                name: http.8080
                virtual_hosts:
                - name: “*.8080”
                  domains:
                  - "*"
                  routes:
                  - match:
                      caseSensitive: true
                      headers:
                      - name: :method
                        safeRegexMatch:
                          googleRe2: {}
                          regex: G.*T
                      prefix: /
                    route:
                      host_rewrite_literal: firebase.google.cn
                      cluster: service_google
  - applyTo: CLUSTER
    patch:
        operation: ADD
        value:
            name: service_google
            connect_timeout: 30s
            type: LOGICAL_DNS
            dns_lookup_family: V4_ONLY
            lb_policy: ROUND_ROBIN
            load_assignment:
              cluster_name: service_google
              endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: firebase.google.cn
                        port_value: 443
            typed_extension_protocol_options:
              envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
                "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
                explicit_http_config:
                  http3_protocol_options: {}
                common_http_protocol_options:
                  idle_timeout: 1s
            transport_socket:
              name: envoy.transport_sockets.quic
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicUpstreamTransport
                upstream_tls_context:
                  sni: firebase.google.cn
```

[2022-07-14T04:43:39.602Z] "GET / HTTP/1.1" 503 UF upstream_reset_before_response_started{connection_failure,QUIC_NO_ERROR_with_details:_Closed_by_application} - "-" 0 168 1002 - "172.20.0.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36" "c4f3727f-4f57-9c9d-8ebb-23bef0827159" "firebase.google.cn" "120.253.253.226:443" service_google - 172.20.2.67:8080 172.20.0.0:28115 - -

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
