### ISSUE TITLE
Memory leak as a Istio sidecar 

### ISSUE THREAD

**Issue by Patrick0308** [envoyproxy/envoy#22218]
*Title*: *Memory leak as a Istio sidecar *

*Description*:
We are migrating some services to Istio. However, we found many service are in memory leaks at different rates. 
below you can see graphs showing istio-proxy container memory utilization metrics: 

![image](https://user-images.githubusercontent.com/5486149/179139057-48a6ce62-999d-4f10-8906-ccaad6be3db0.png)

I enable heap profiler for few hours at that time. And I get a  flame graph about inuse_space: 

![image](https://user-images.githubusercontent.com/5486149/179143467-1331af20-1e58-4131-b5b7-7fa9670d8580.png)

This service has some inbound or outbound grpc requests, and outbound pass-through http1.1 requests with tls. 
I  suspected this is a connection leaks at first. But `netstat -anlp | wc -l` shows connection number is always maintained at around 600.

*Repro steps*:
It can be reproduce on our some services.  

*Admin and Stats Output*:
Sorry, I forgot getting the metric. I will put stats on here when memory get larger again.

*Config*:
If needs, I can provide some configuration.
*Logs*:
No logs

*Call Stack*:
No crash

*Envoy version*:
6ccb2c35a7a22f81181d87dc93d93d9ee48749af/1.19.2-dev/Clean/RELEASE/BoringSSL

**Comment by Patrick0308** [comment]
metrics file: [stats.txt](https://github.com/envoyproxy/envoy/files/9119904/stats.txt)

**Comment by kyessenov** [comment]
Could you disable istio stats filters (istio.stats Wasm extension)? There's a known memory leak with `istio_request_total` never garbage collected.

**Comment by Patrick0308** [comment]
> It might help to also allow-list more envoy metrics (stats_exclusions)

@kyessenov This is an new metrics file. [stats2.txt](https://github.com/envoyproxy/envoy/files/9129095/stats2.txt) 
I still don's see any problem from metrics. I will try to disable stats filters.

**Comment by Patrick0308** [comment]
This is envoy memory graph excluded memory of pilot-agent:
![image](https://user-images.githubusercontent.com/5486149/179438374-b07e127c-a3df-450e-96fe-2113aa15482f.png)

**Comment by kyessenov** [comment]
Do you think you could get a heap sample profile during the leak? We might be able to tell from there. The flame chart is for CPU, not clear what stays resident in memory.

**Comment by kyessenov** [comment]
Yeah, it's a heap sample, sorry. Are you using istio/proxy binary? Which version?

**Comment by Patrick0308** [comment]
@kyessenov The envoy which is build on my own based on 1.19.2 and cherry picked https://github.com/envoyproxy/envoy/pull/17994, Binary is 
[envoy.zip](https://github.com/envoyproxy/envoy/files/9134172/envoy.zip) . The symbols‘ file is 
[lib.zip](https://github.com/envoyproxy/envoy/files/9134176/lib.zip)

**Comment by kyessenov** [comment]
Majority of the memory appears to be related to "RouteConfigUpdateReceiverImpl::onRdsUpdate" so it's churning through xDS updates:
```
 654.52kB 21.34% 21.34%   654.52kB 21.34%  google::protobuf::Arena::CreateMaybeMessage
  407.89kB 13.30% 34.64%   824.38kB 26.88%  Envoy::Router::VirtualHostImpl::VirtualHostImpl
     352kB 11.48% 46.12%      352kB 11.48%  Envoy::Buffer::Slice::Slice
  163.36kB  5.33% 51.45%     1006kB 32.80%  Envoy::Router::RouteMatcher::RouteMatcher
  152.52kB  4.97% 56.42%   152.52kB  4.97%  std::__1::basic_string::basic_string
  141.08kB  4.60% 61.02%   515.53kB 16.81%  std::__1::__tree::__emplace_unique_key_args
  118.59kB  3.87% 64.89%   118.59kB  3.87%  Envoy::Router::RateLimitPolicyImpl::RateLimitPolicyImpl
   97.24kB  3.17% 68.06%   102.36kB  3.34%  Envoy::Stats::ThreadLocalStoreImpl::ScopeImpl::ScopeImpl
```

Are you constantly updating Istio configs? Is the drain duration short on your listeners?

**Comment by kyessenov** [comment]
[profile001.pdf](https://github.com/envoyproxy/envoy/files/9135839/profile001.pdf)

**Comment by Patrick0308** [comment]
We sync consul services to istio service entries. If all endpoint are crash, the service entries will be deleted. I think this is reason why sometimes rds config is updating. It is not need to delete service entries. Thanks, You make me discover this problem.
But I think It's not memory leak really reason. I observed that when I excluded outbound 443,80 ports the rate of memory leak has slowed down a lot.
Not exclude outbound 443,80 ports:
![image](https://user-images.githubusercontent.com/5486149/179653240-9fc697c2-bd13-4801-b16a-88daad2b08c5.png)
Exclude outbound 443,80 ports.
![image](https://user-images.githubusercontent.com/5486149/179653341-6c50de8d-e783-4b85-8c02-01955bba3161.png)

**Comment by kyessenov** [comment]
Happy this was helpful. The fact that memory is not released from RDS updates is not normal, so it's worth investigating further. But I think we can make a synthetic test to force high RDS churn to find out why in_use memory is accumulating.

**Comment by Patrick0308** [comment]
@kyessenov  There is another reason that istio-proxy disconnected istiod every 30 minutes. When istio-proxy reconnect istiod, xds will be sent to proxy again. 
I don't think it's memory leak cause, because an another instance has a faster memory leaks.
![image](https://user-images.githubusercontent.com/5486149/179689699-c943e5b1-a9b3-48c2-a68f-3e7288c37600.png) 
The memory went up to 300M in an hour.

**Comment by Patrick0308** [comment]
May be is another memory leak reason for quote-level.

**Comment by Patrick0308** [comment]
I seriously suspect `origin_dst` cluster caused memory leak.
```
File: envoy
Type: inuse_space
Showing nodes accounting for 14513.52kB, 92.20% of 15741.92kB total
Dropped 718 nodes (cum <= 78.71kB)
      flat  flat%   sum%        cum   cum%
 3256.45kB 20.69% 20.69%  4605.67kB 29.26%  Envoy::Upstream::OriginalDstCluster::LoadBalancer::chooseHost
 2066.47kB 13.13% 33.81%  2066.47kB 13.13%  Envoy::Network::Address::InstanceFactory::createInstancePtr
 1783.72kB 11.33% 45.14%  2401.84kB 15.26%  std::__1::make_unique
 1688.75kB 10.73% 55.87%  3618.75kB 22.99%  Envoy::Upstream::ProdClusterManagerFactory::allocateTcpConnPool
 1330.83kB  8.45% 64.33%  1330.76kB  8.45%  Envoy::Network::TransportSocketOptionsUtility::fromFilterState
  964.88kB  6.13% 70.46%   964.88kB  6.13%  Envoy::Network::Utility::copyInternetAddressAndPort
  626.16kB  3.98% 74.43%   626.16kB  3.98%  std::__1::__function::__func::__clone
  615.52kB  3.91% 78.34%   615.52kB  3.91%  std::__1::basic_string::basic_string
  ```

**Comment by kyessenov** [comment]
@Patrick0308 It's plausible. I think we should see a high number of connections on the passthrough cluster then, but I only see:
```envoy_cluster_upstream_cx_active{cluster_name="PassthroughCluster"} 49```

One experiment we can try is to make clean-up more aggressive with https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-cleanup-interval.

**Comment by Patrick0308** [comment]
I set 1000ms clean-up interval.
```
- circuitBreakers:
    thresholds:
    - maxConnections: 4294967295
      maxPendingRequests: 4294967295
      maxRequests: 4294967295
      maxRetries: 4294967295
      trackRemaining: true
  cleanupInterval: 1s
  connectTimeout: 10s
  filters:
  - name: istio.metadata_exchange
    typedConfig:
      '@type': type.googleapis.com/udpa.type.v1.TypedStruct
      typeUrl: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
      value:
        protocol: istio-peer-exchange
  lbPolicy: CLUSTER_PROVIDED
  name: PassthroughCluster
  type: ORIGINAL_DST
  typedExtensionProtocolOptions:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      useDownstreamProtocolConfig:
        http2ProtocolOptions:
          maxConcurrentStreams: 1073741824
        httpProtocolOptions: {}
```
However the rate of memory leak is faster. 
![image](https://user-images.githubusercontent.com/5486149/179969631-7dc68766-23ec-4fe9-9cf4-2dc333b61427.png)
profile file:  [envoypprof7.zip](https://github.com/envoyproxy/envoy/files/9149286/envoypprof7.zip)
```
File: envoy
Type: inuse_space
Showing nodes accounting for 51124.07kB, 97.25% of 52570.66kB total
Dropped 315 nodes (cum <= 262.85kB)
      flat  flat%   sum%        cum   cum%
12988.27kB 24.71% 24.71% 18369.98kB 34.94%  Envoy::Upstream::OriginalDstCluster::LoadBalancer::chooseHost
 8188.69kB 15.58% 40.28%  8188.69kB 15.58%  Envoy::Network::Address::InstanceFactory::createInstancePtr
 6735.97kB 12.81% 53.10% 14434.22kB 27.46%  Envoy::Upstream::ProdClusterManagerFactory::allocateTcpConnPool
 5302.38kB 10.09% 63.18%  7708.62kB 14.66%  std::__1::make_unique
 5297.70kB 10.08% 73.26%  5297.77kB 10.08%  Envoy::Network::TransportSocketOptionsUtility::fromFilterState
 3848.38kB  7.32% 80.58%  3848.38kB  7.32%  Envoy::Network::Utility::copyInternetAddressAndPort
 2406.60kB  4.58% 85.16%  2406.60kB  4.58%  std::__1::__function::__func::__clone
 1924.64kB  3.66% 88.82%  1954.71kB  3.72%  std::__1::__tree::__emplace_unique_key_args
 1443.45kB  2.75% 91.56%  1443.45kB  2.75%  std::__1::basic_string::basic_string
 ```
Obviously, ` OriginalDstCluster::cleanup()` don't clean up.

**Comment by Patrick0308** [comment]
Setting cleanup_interval  2400h solved my problem.  EnvoyFilter is 
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cleanup-interval
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: PassthroughCluster
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        cleanup_interval: 2400h
  - applyTo: CLUSTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
        cleanup_interval: 2400h
```

**Comment by kyessenov** [comment]
Very interesting! I haven't spotted where the leak is but this is a good signal that `cleanup` is leaky.

**Comment by kyessenov** [comment]
AFAICT the hosts are all shared_ptrs and flat_hash_map stores them in-place. So it shouldn't in theory leak. Mutations are all copy-on-write on the map, so that also excludes concurrent writes. If you can run with `trace` log level, we should see logs on when hosts are removed and added. I've tried running locally with very aggressive cleanup but no luck.

**Comment by kyessenov** [comment]
Ok, I think I can reproduce locally on the latest main. I'll debug to find the root cause.

**Comment by kyessenov** [comment]
Config (run with concurrency):
```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
static_resources:
  listeners:
  - name: outbound
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
      filters:
      - name: inbound-http-proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: outbound
                  timeout: 0s
          http_filters:
          - name: front-router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - connect_timeout: 1s
    name: outbound
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED
    cleanup_interval: { nanos: 1000 }
    original_dst_lb_config:
      use_http_header: true
      http_header_name: dst
```

Backend:
```
fortio server --http-port 8001
```

Load:
```
fortio load -H "dst: 127.0.0.1:8001" -t 20m localhost:8080
```

Memory grows from 70MB to 140MB.
