### ISSUE TITLE
confusions about rate limiter configuration

### ISSUE THREAD

**Issue by uglycow** [envoyproxy/envoy#22226]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
> Question 1: Why `RouteAction. include_vh_rate_limits` only applies to GlobalRateLimiter, not LocalRateLimiter?

[envoy/source/extensions/filters/http/ratelimit/ratelimit.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ratelimit/ratelimit.cc#L52) checked include_vh_rate_limits
[envoy/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/local_ratelimit/local_ratelimit.cc#L221) didn't check include_vh_rate_limits

I'm trying to limit qps of my whole app and at the same time set separate limits for some of the interfaces within it.
I'm considering configuring local rate limit at the VirtualHost level and Route level.

> Question 2: the doc says [RateLimit.stage](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit) is meant to match with LocalRateLimit.stage, does this mean that I can configure multiple LocalRateLimit in the HTTP filterchain ?  not sure how is feature might be used.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by kyessenov** [comment]
Q1: This is a gap in implementation, there's no reason why it shouldn't support the same options.
Q2: Yes, it allows disjoint sets of rate limit policies, similar to global rate limiting.

**Comment by uglycow** [comment]
@kyessenov  thanks and 
Q1: virtual host level local limit for whole app and route level rate limit for interface within it won't work. any suggestion for my case?  

Q2: so if i add two local rate limit filters to HTTP filter chain like this:
```yaml
          http_filters:
          - name: envoy.filters.http.local_ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter1
          - name: envoy.filters.http.local_ratelimit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter2
```
Is it able to configure the details of the limiter at the route level by using `typed_per_filter_config`, maybe like this?
I'm wondering how the config would get bonded to the filter instance
```yaml
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/path/with/rate/limit" }
                route: { cluster: service_protected_by_rate_limit }
                typed_per_filter_config:
                  envoy.filters.http.local_ratelimit:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter1
                    token_bucket:
                      max_tokens: 10000
                      tokens_per_fill: 1000
                      fill_interval: 1s
                    filter_enabled:
                      runtime_key: local_rate_limit_enabled
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    filter_enforced:
                      runtime_key: local_rate_limit_enforced
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    response_headers_to_add:
                      - append: false
                        header:
                          key: x-local-rate-limit
                          value: 'true'
                  envoy.filters.http.local_ratelimit:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter2
                    token_bucket:
                      max_tokens: 10000
                      tokens_per_fill: 1000
                      fill_interval: 1s
                    filter_enabled:
                      runtime_key: local_rate_limit_enabled
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    filter_enforced:
                      runtime_key: local_rate_limit_enforced
                      default_value:
                        numerator: 100
                        denominator: HUNDRED
                    response_headers_to_add:
                      - append: false
                        header:
                          key: x-local-rate-limit
                          value: 'true'
```
