### ISSUE TITLE
Allow http health check configure use http or https

### ISSUE THREAD

**Issue by quserinn** [envoyproxy/envoy#22362]
*Description*:
When envoy do http health check, health check occur over the transport socket specified for the cluster.

But some legacy services offer health check via http, and offer contents via https. So it is useful that tls configuration is added to http health check configuration like below.
```
http_health_check:
  path: "/"
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

```

Please review if this feature is appropriate for envoy. I will try to implement this feature myself if nobody working on this.
