### ISSUE TITLE
locality_weighted_lb_config has no value by config_dump

### ISSUE THREAD

**Issue by wangjianwen** [envoyproxy/envoy#22374]
I create DestinationRule like this

```yaml

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: platform-operation-template
  namespace: operate-center
spec:
  host: platform-operation-template
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 0
        idleTimeout: 2m
        maxRequestsPerConnection: 0
        maxRetries: 3
      tcp:
        connectTimeout: 500ms
        maxConnections: 400
    loadBalancer:
      localityLbSetting:
        distribute:
        - from: region1/*
          to:
            region1/zone1/*: 1
            region1/zone2/*: 99
        - from: region2/*
          to:
             region1/zone1/*: 1
             region1/zone2/*: 99
        enabled: true
      simple: ROUND_ROBIN
    outlierDetection:
      baseEjectionTime: 1m
      consecutiveErrors: 5
      interval: 10s
      maxEjectionPercent: 60
    tls:
      mode: DISABLE

```

Atfer ,  I used  'config_dump'  to download envoy config,  this cluster config is like this

```json
{
     "version_info": "2022-07-23T02:26:54Z/8230",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|19038||platform-operation-template.operate-center.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|19038||platform-operation-template.operate-center.svc.cluster.local"
      },
      "connect_timeout": "0.500s",
      ... ...
       "common_lb_config": {
       "healthy_panic_threshold": {},
       "locality_weighted_lb_config": {}
      },
      ... ...
    }
      

```

My problem is :  why locality_weighted_lb_config is empty object, no value for load_balancing_weight ?
