### ISSUE TITLE
active_connections counter in connection limit filter can underflow

### ISSUE THREAD

**Issue by jparklab** [envoyproxy/envoy#22390]
*Title*: *active_connections counter in connection limit filter can underflow*

*Description*:

When both the local rate limit filter and the connection limit filter are used, and local rate limit filter is applied before the connection limit filter, connections rejected by the local rate limit filter can cause the active connection counter in the connection limit filter to be decremented without incrementing the counter, and thus, cause the counter to underflow, and causing the connection limit filter to **reject further incoming connections**.

When we encountered this issue, the Envoy proxy closed incoming connections immediated without trying to establish connections to the backends. From the metrics, we found that *active_connections* counter from the connection limit filter had extremely high number as below.

```
connection_limit.<listener_name>.active_connections: 18446744073683508455 
connection_limit.<listener_name>.limited_connections: 82560385
local_rate_limit.<listener_name>.rate_limited: 26043161    
```

In the above numbers <active_connections> + <rate_limited> = 2^64, indicating that the *active_connections* counter was decremented by the number of rate limited connnections. It appears that [Filter::onNewConnection](https://github.com/envoyproxy/envoy/blob/ce3b4da34a041c2946dd935524126d0743567466/source/extensions/filters/network/connection_limit/connection_limit.cc#L61) is not called when a connection is rejected by local_rate_limit filter, but [Filter::onEvent](https://github.com/envoyproxy/envoy/blob/ce3b4da34a041c2946dd935524126d0743567466/source/extensions/filters/network/connection_limit/connection_limit.cc#L96) is called when the connection is closed, and thus *active_connections* counter can be decreased even when it is 0.

*Repro steps*:

  * Configure a listener with both local rate limit filter and connection limit filter.
  * Run a webserver to use it as the backend for the cluster. I used python http.server
  
```
$ python3 -m http.server 11080
Serving HTTP on 0.0.0.0 port 11080 (http://0.0.0.0:11080/) ...
127.0.0.1 - - [25/Jul/2022 19:33:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Jul/2022 19:33:07] "GET / HTTP/1.1" 200 -
```

   * Send multiple requests in parallel to trigger local rate limit. I used hey(https://github.com/rakyll/hey)
   
```
$ hey -n 100 -c 1 http://127.0.0.1:10080

Summary:
  Total:        0.0414 secs
  Slowest:      0.0085 secs
  Fastest:      0.0012 secs
  Average:      0.0049 secs
  Requests/sec: 2417.4965
  
  Total data:   1287 bytes
  Size/request: 429 bytes

...

Status code distribution:
  [200] 3 responses

Error distribution:
  [89]  Get "http://127.0.0.1:10080": EOF
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36730->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36734->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36746->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36760->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36772->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36818->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36838->127.0.0.1:10080: read: connection reset by peer
  [1]   Get "http://127.0.0.1:10080": read tcp 127.0.0.1:36872->127.0.0.1:10080: read: connection reset by peer

```

   * Check stats. *active_connections* count shows that the counter underflowed

```
curl -s http://localhost:9901/stats|egrep "connection_limit|local_rate_limit"
connection_limit.lhs-service.active_connections: 18446744073709551519
connection_limit.lhs-service.limited_connections: 0
local_rate_limit.lhs-service.rate_limited: 97
```   

Config:

```
node:
    cluster: test-cluster
    id: test-id
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: sample-listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10080
    filter_chains:
    - filters:
      - name: envoy.filters.network.local_ratelimit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit
          stat_prefix: lhs-service
          token_bucket:
            max_tokens: 3
            tokens_per_fill: 1
            fill_interval: "1s"
      - name: envoy.filters.network.connection_limit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.connection_limit.v3.ConnectionLimit
          stat_prefix: lhs-service
          max_connections: 5
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: lhs-service
          cluster: local-cluster
          max_connect_attempts: 1
  clusters:
  - name: local-cluster
    load_assignment:
      cluster_name: local-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 11080
```
