### ISSUE TITLE
Compression filter with gRPC-WEB filter

### ISSUE THREAD

**Issue by namedanil** [envoyproxy/envoy#22411]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Does compression filter [1] work with grpc-web filter [2]?*

*Description*:
> Hi, team,
I am using the grpc-web client and want to compress the response from the server. As far as I understand, envoy can compress all responses through the gzip compression filter. But when I add this filter the size of the response is not reduced. Part of the config file:
````
http_filters:
- name: envoy.filters.http.grpc_web
- name: envoy.filters.http.compressor
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
    request_direction_config:
      common_config:
        enabled:
          default_value: false
          runtime_key: request_compressor_enabled
    response_direction_config:
      common_config:
        content_type:
          - application/grpc-web-text
          - application/grpc-web-text+proto
    compressor_library:
      name: for_response
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
        memory_level: 3
        window_bits: 10
        compression_level: BEST_COMPRESSION
        compression_strategy: DEFAULT_STRATEGY
- name: envoy.filters.http.cors
- name: envoy.filters.http.router
````

[optional *Relevant Links*:]
>[1] https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/compressor_filter#config-http-filters-compressor
[2] https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter
