### ISSUE TITLE
no accesslog in istio-proxy container when using wasm accesslog

### ISSUE THREAD

**Issue by 13567436138** [envoyproxy/envoy#22438]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.
main.go

```
package main

import (
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

func main() {
        proxywasm.SetVMContext(&vmContext{})
}

type vmContext struct {
        // Embed the default VM context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultVMContext
}

// Override types.DefaultVMContext.
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
        return &pluginContext{}
}

type pluginContext struct {
        // Embed the default plugin context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultPluginContext
}

// Override types.DefaultPluginContext.
func (*pluginContext) NewHttpContext(contextID uint32) types.HttpContext {
        return &httpHeaders{contextID: contextID}
}

type httpHeaders struct {
        // Embed the default http context here,
        // so that we don't need to reimplement all the methods.
        types.DefaultHttpContext
        contextID uint32
}

func (ctx *httpHeaders) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
        path := []string{"%START_TIME%"}
        startTime,err:=proxywasm.GetProperty(path)
        
        if err!=nil{
                proxywasm.LogCriticalf("GetProperty: %v", err)
        	
        }
        
        proxywasm.LogCriticalf("startTime: %s", string(startTime))

        hs, err := proxywasm.GetHttpRequestHeaders()
        if err != nil {
                proxywasm.LogCriticalf("failed to get request headers: %v", err)
        }

        for _, h := range hs {
                proxywasm.LogInfof("request header --> %s: %s", h[0], h[1])
        }
        return types.ActionContinue
}


// Override types.DefaultHttpContext.
func (ctx *httpHeaders) OnHttpStreamDone() {
        path := []string{"%START_TIME%"}
        startTime,err:=proxywasm.GetProperty(path)
        
        if err!=nil{
                proxywasm.LogCriticalf("GetProperty: %v", err)
        	
        }
        
        proxywasm.LogCriticalf("startTime: %s", string(startTime))
        proxywasm.LogCriticalf("%d finished", ctx.contextID)
}
```

```
export GOPROXY=https://proxy.golang.com.cn,direct

tinygo build -o main.wasm -scheduler=none -target=wasi main.go
```

envoyfilter实现：

```
kubectl create cm wasm --from-file=main.wasm -n istio
```

deploy-productpage-with-sidecar-volume.yaml

kubectl apply -f deploy-productpage-with-sidecar-volume.yaml -n istio

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v1
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
      annotations:
        sidecar.istio.io/userVolumeMount: '[{"name":"wasm", "mountPath":"/var/local/lib/wasm-filters", "readonly":true}]'
        sidecar.istio.io/userVolume: '[{"name":"wasm", "configmap":{"name":"wasm"}}]'
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
```

ef-wasm-access-log.yaml

kubectl apply -f ef-wasm-access-log.yaml -n istio

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: wasm
spec:
  workloadSelector:
    labels:
      app: productpage
  configPatches:
  - applyTo: LISTENER
    match:
      context: SIDECAR_INBOUND
      listener:
        name: virtualInbound
    patch:
      operation: MERGE
      value:
        access_log:
          - filter:
              response_flag_filter:
                flags:
                - NR
            name: envoy.access_loggers.wasm
            typedConfig:
                '@type': type.googleapis.com/envoy.extensions.access_loggers.wasm.v3.WasmAccessLog
                config:
                  name: my_plugin
                  configuration:
                    "@type": type.googleapis.com/google.protobuf.StringValue
                    value: |
                      {}
                  vm_config:
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      local:
                        filename: /var/local/lib/wasm-filters/main.wasm
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        name: virtualInbound
        filterChain:
          destinationPort: 9080
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
              name: envoy.filters.network.http_connection_manager
              typedConfig:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.wasm
                    typedConfig:
                        '@type': type.googleapis.com/envoy.extensions.access_loggers.wasm.v3.WasmAccessLog
                        config:
                          name: my_plugin
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: |
                              {}
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: /var/local/lib/wasm-filters/main.wasm
```

by the way: how to get following values:

[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS%
\"%UPSTREAM_TRANSPORT_FAILURE_REASON%\" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% \"%REQ(X-FORWARDED-FOR)%\" \"%REQ(USER-AGENT)%\" \"%REQ(X-REQUEST-ID)%\"
\"%REQ(:AUTHORITY)%\" \"%UPSTREAM_HOST%\" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%\n

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by zuercher** [comment]
You'll need to provide the actual Envoy configuration for us to look at this. I recommend filing this issue with Istio and then can help determine whether the issue is there or in Envoy and how to file the bug.

**Comment by kyessenov** [comment]
I noticed that you are using the wrong property names:
```
   path := []string{"%START_TIME%"}
        startTime,err:=proxywasm.GetProperty(path)
```

I think you want `[]string{"request", "time"}` (encoded as int64) based on https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes.

**Comment by zirain** [comment]
IIRC, `github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm` do not support `onLog` for now, @mathetake can you confirmed that?

**Comment by mathetake** [comment]
> IIRC, `github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm` do not support `onLog` for now, @mathetake can you confirmed that?

`onLog` is hidden behind our API, and technically supported. But `onLog` is nothing to do with the issue here and not relevant.

**Comment by mathetake** [comment]
I don't believe this is the issue of Envoy, you just have to set the proper log level of istio proxies via Istio API. We can close this issue at any time (this person filing this issue always doesn't provide enough detail and is not actionable).

**Comment by zirain** [comment]
this is working with following configuration:
```yaml
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: ./wasm-log.wasm
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

with following output:
```console
[2022-07-30 11:31:38.241][1736436][critical][wasm] [source/extensions/common/wasm/context.cc:1179] wasm log: GetProperty: error status returned by host: not found
[2022-07-30 11:31:38.241][1736436][critical][wasm] [source/extensions/common/wasm/context.cc:1179] wasm log: startTime: 
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> :authority: 127.0.0.1:18000
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> :path: /
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> :method: GET
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> :scheme: http
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> user-agent: curl/7.58.0
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> accept: */*
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> x-forwarded-proto: http
[2022-07-30 11:31:38.241][1736436][info][wasm] [source/extensions/common/wasm/context.cc:1170] wasm log: request header --> x-request-id: 53aeaf2a-8bba-45c4-89ec-c09bdce9c8e3
[2022-07-30 11:31:38.242][1736436][critical][wasm] [source/extensions/common/wasm/context.cc:1179] wasm log: GetProperty: error status returned by host: not found
[2022-07-30 11:31:38.242][1736436][critical][wasm] [source/extensions/common/wasm/context.cc:1179] wasm log: startTime: 
[2022-07-30 11:31:38.242][1736436][critical][wasm] [source/extensions/common/wasm/context.cc:1179] wasm log: 3 finished
```

but I not sure the original question is `How to implement as AccessLog extensions with wasm`?
