### ISSUE TITLE
Access log extension issue

### ISSUE THREAD

**Issue by daniel-yaba** [envoyproxy/envoy#22500]
*Description*: There is an error while loading the YAML file with the specified extention for access logs
extension: type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog

>What issue is being seen? 
After adding the access log filter under "http_filters" section:
http_filters:
                - name: envoy.access_loggers.file
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog

*Config*:

```yaml
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              stat_prefix: http_proxy
              route_config:
                name: all
                virtual_hosts:
                  - name: cluster_hackazon
                    domains:
                      - '*'
                    routes:
                      - match: { prefix: "/"}
                        route:
                          cluster: cluster_hackazon
                          hash_policy:
                            - cookie:
                                name: persistence
                                ttl: 86400s
              http_filters:
                - name: envoy.access_loggers.file
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    # path: "/dev/stdout"
                    # typed_json_format: 
                    #   client.address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                    #   envoy.route.name: "%ROUTE_NAME%"
                    #   http.request.headers.id: "%REQ(X-REQUEST-ID)%"
                    #   service.name: "envoy"
                - name: envoy.filters.http.lua
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                    default_source_code:
                      filename: /etc/envoy/lua/rdwr_oop_connector.lua
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_socket.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  certificate_chain:
                    filename: /etc/envoy/ssl/cert.pem
                  private_key:
                    filename: /etc/envoy/ssl/private.pem
                alpn_protocols: ["h2,http/1.1"]


  clusters:
    - name: cluster_hackazon
      connect_timeout: 1s
      type: STATIC
      lb_policy: RING_HASH
      load_assignment:
        cluster_name: cluster_hackazon
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 10.248.244.57
                  port_value: 80
          - endpoint:
              address:
                socket_address:
                  address: 10.248.244.116
                  port_value: 80
    - name: cluster_cwaf
      connect_timeout: 1s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: cluster_cwaf
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 1.1.1.1
                  port_value: 443
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

*Logs*:

```console
[2022-08-02 10:16:17.161][1][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for 'envoy.access_loggers.file' with type URL: 'envoy.extensions.access_loggers.file.v3.FileAccessLog'
[2022-08-02 10:16:17.162][1][info][main] [source/server/server.cc:962] exiting
[2022-08-02 10:16:17.163][1][info][dns] [source/extensions/network/dns_resolver/cares/dns_impl.cc:540] c-ares library cleaned up.
Didn't find a registered implementation for 'envoy.access_loggers.file' with type URL: 'envoy.extensions.access_loggers.file.v3.FileAccessLog'
```

>**Note**: Pl

**Comment by alyssawilk** [comment]
are you perhaps building envoy without that extension linked in?

https://github.com/envoyproxy/envoy/blob/main/bazel/README.md#enabling-and-disabling-extensions

**Comment by daniel-yaba** [comment]
@alyssawilk
I build the container image with the command:
docker build -t envoy . && docker run -dit --name Envoy -p 443:443 envoy

according to the YAML file I specified in first comment is there anything else I should do ?

**Comment by daixiang0** [comment]
@daniel-yaba which command do you build for Envoy binary?

**Comment by alyssawilk** [comment]
cc @phlax

**Comment by daniel-yaba** [comment]
I used version 1.23:latest from docker hub in my Dockerfile
then I created my own docker image with the YAML file as I specified above and then run my docker image

**Comment by suniltheta** [comment]
```
        access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
        http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              default_source_code:
                filename: /etc/envoy/lua/rdwr_oop_connector.lua
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
Perhaps the access log should be specified under access_log field (envoy [docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-accesslog))?
