### ISSUE TITLE
response set-cookie support

### ISSUE THREAD

**Issue by zuercher** [envoyproxy/envoy#2250]
I find myself wanting to generate HTTP response headers for the "Set-Cookie" header. This works well enough with static data, but in actuality I want the cookie's value to be a piece of metadata from an upstream host.

Response headers currently only support this when the entire header value is the metadata.

I think there are two ways to accomplish what I want.

1. Allow the %-bracketed expressions in Router::HeaderParser to appear anywhere in a header's value. This would allow:
```
response_headers_to_add:
  - header:
      key: Set-Cookie
      value: 'mycookie=%UPSTREAM_METADATA(["envoy.lb", "key"])%; Max-Age=1000'
```
2. Make generation of set-cookie headers a first-class configuration point, such that someone could add (for example):
```
response_cookies_to_add:
  - key: mycookie
    value: '%UPSTREAM_METADATA(["envoy.lb", "key"])%'
    max_age: 1000
```

I'm fairly agnostic to the implementation direction. I think the former is probably less work overall, but makes it easier to generate an invalid cookie (the key and value content has a restricted character set and so on). It's not entirely clear whether the latter idea should escape content vs. stripping vs. not generating a cookie at all.

c.f. https://tools.ietf.org/html/rfc6265
