### ISSUE TITLE
One second delay in gRPC load balancing - is it an Envoy or gRPC issue?

### ISSUE THREAD

**Issue by lenardpi** [envoyproxy/envoy#22522]
*Title*: *One second delay in gRPC load balancing*

*Description*:
We are using Envoy proxy v1.17.0 as a sidecar container in a Kubernetes service to achieve gRPC load balancing to a backend service.

We launch 3 gRPC operations in parallel on the gRPC channel from 3 C++ threads. Setup and operation sketch:

![image](https://user-images.githubusercontent.com/110488252/182440664-e99c6dc7-577c-4a94-92dd-ed238cf65465.png)

Used Envoy configuration:
```
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/backend_service_namespace.BackendService/"
                      headers:
                      - name: content-type
                        exact_match: application/grpc
                    route:
                      cluster: our-backend-service
              http_filters:
              - name: envoy.filters.http.router
      clusters:
      - name: our-backend-service
        connect_timeout: 0.5s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {}
        load_assignment:
          cluster_name: our-backend-service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: backend-service-headless
                    port_value: 8181
```

*Experienced behavior:*
We experience a 1-second delay quite often (~30-50% of cases) in case of one of the three operations. In these cases, the backend service gets the gRPC request only after 1 second. (Note: all operations are served in microseconds in the backends, so the other gRPC requests are not using the channels for anywhere near 1 second.)

*Investigation*:
Envoy logs (`-l trace`) show no errors apart from these:
```
[2022-07-29 06:49:29.417][14][trace][connection] [source/common/network/raw_buffer_socket.cc:39] [C54] read error: Resource temporarily unavailable
```

This seems to be OK, however, as it appears quite often in the logs, even where there is no 1-sec delay.

gRPC logs show errors connecting to Envoy (localhost:10000) after a 1-sec gap from the previous log-entry: 
```
I0801 21:45:23.281823311     780 chttp2_transport.cc:2601]   ipv4:10.255.73.68:53394: Complete BDP ping err="OK"
I0801 21:45:24.277774547     104 subchannel.cc:913]          subchannel 0x7efc7c849c00 {address=ipv6:[::1]:10000, args=grpc.client_channel_factory=0x7efd53808028, grpc.default_authority=localhost:10000, grpc.internal.channel_credentials=0x7efc7c81a4a0, grpc.internal.security_connector=0x7efc7c886800, grpc.internal.subchannel_pool=0x7efc7c812750, grpc.primary_user_agent=grpc-c++/1.45.2, grpc.resource_quota=0x7efcb573d150, grpc.server_uri=dns:///localhost:10000}: failed to connect to channel, retrying
```

Same behavior with v1.22 and v1.23 versions.

*Questions:*
* Is it likely an Envoy or gRPC issue?
* It seems that gRPC issues the 1-sec delay for some reason, but its cause is unclear in the abscence of the gRPC load balancing implementation details in Envoy. (How is gRPC used from within Envoy, with what settings, is the connection error between the service and Envoy, or between Envoy and the backends, etc.)
* Do we have any debug options in Envoy that are worth trying to dig deeper into the issue?
* Do we have any configuration options in Envoy that we can experiece with in order to fine-tune the underlying gRPC load balancing?

Any clue is appreciated, thanks in advance!
