### ISSUE TITLE
Envoy verifying certificate even though validation context is not configured

### ISSUE THREAD

**Issue by Asisranjan** [envoyproxy/envoy#22543]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Envoy verifying certificate even though validation context is not configured

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

We are routing request to target using simple TLS. Envoy is able to establish connection and envoy client disconnected connection due to "failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
`
`

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
```
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
            protocol: TCP
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              http_filters:
              - name: envoy.filters.http.dynamic_forward_proxy
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                  dns_cache_config:
                    dns_lookup_family: V4_ONLY
                    name: dynamic_forward_proxy_cache_config
              - name: envoy.router
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                request_headers_to_remove:
                - x-envoy-peer-metadata
                - x-envoy-peer-metadata-id
                virtual_hosts:
                - domains:
                  - testfqdn*
                  name: https_service
                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: https_dynamic_forward_proxy_cluster
              stat_prefix: ingress_http
        name: proxy
  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: ADD
      value:
        cluster_type:
          name: envoy.clusters.dynamic_forward_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
            dns_cache_config:
              dns_lookup_family: V4_ONLY
              name: dynamic_forward_proxy_cache_config
        connect_timeout: 1s
        http2_protocol_options:
          max_concurrent_streams: 1073741824
        lb_policy: CLUSTER_PROVIDED
        name: https_dynamic_forward_proxy_cluster
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              alpn_protocols:
              - h2
```
*Logs*:
>Include the access logs and the Envoy logs.

2022-08-03T15:15:43.804868Z     debug   envoy connection        [C5026] connecting to 1.2.3.4:8000
2022-08-03T15:15:43.804966Z     debug   envoy connection        [C5026] connection in progress
2022-08-03T15:15:43.805010Z     debug   envoy http      [C127][S16165143462978876482] request end stream
2022-08-03T15:15:43.835305Z     debug   envoy connection        [C5026] connected
2022-08-03T15:15:43.883297Z     debug   envoy connection        [C5026] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2022-08-03T15:15:43.883316Z     debug   envoy connection        [C5026] closing socket: 0
2022-08-03T15:15:43.883331Z     debug   envoy connection        [C5026] TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2022-08-03T15:15:43.883349Z     debug   envoy client    [C5026] disconnect. resetting 0 pending requests
2022-08-03T15:15:43.883360Z     debug   envoy pool      [C5026] client disconnected, failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2022-08-03T15:15:43.883375Z     debug   envoy router    [C127][S16165143462978876482] upstream reset: reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
2022-08-03T15:15:43.883430Z     debug   envoy http      [C127][S16165143462978876482] Sending local reply with details upstream_reset_before_response_started{connection failure,TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED}
2022-08-03T15:15:43.883463Z     debug   envoy http      [C127][S16165143462978876482] encoding headers via codec (end_stream=false):
':status', '503'
'content-length', '195'
'content-type', 'text/plain'
'date', 'Wed, 03 Aug 2022 15:15:43 GMT'
'server', 'envoy'

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
