### ISSUE TITLE
Consistent hashing not consistent for unaffected hosts after other host removal

### ISSUE THREAD

**Issue by zarenner** [envoyproxy/envoy#22558]
***Title*:** Consistent hashing not consistent for unaffected hosts after other host removal

***Description*:** 
When `RING_HASH` policy is used and a host is removed, requests don't remain consistently mapped to other unaffected hosts.
e.g. assume 3 hosts `A, B, C`. If `C` is removed, requests which were previously routed to `A` may be remapped to `B`.

The [documentation](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash) doesn't explicitly say that this shouldn't occur, but does say:
> Each host is mapped onto a circle (the “ring”) by hashing its address; each request is then routed to a host by hashing some property of the request, and finding the nearest corresponding host clockwise around the ring. 
> ...
> With the ring partitioned appropriately, the addition or removal of one host from a set of N hosts will affect only 1/N requests.

which to me implies that unaffected hosts and their requests should not be affected.

Perhaps this is from the ketama implementation used? Seems similar to https://github.com/RJ/ketama/issues/13

FYI, I also reproed this with Istio's consistent hash LB (https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB) which uses envoy's consistent hashing.
Interestingly the Istio docs mention:
> The affinity to a particular destination host will be lost when one or more hosts are added/removed from the destination service.

Which is an interesting statement since (within reason) keeping that affinity whenever possible is the point of _consistent_ hashing over normal hashing!

***Repro steps*:**
1. Configure k8s cluster with envoy v1.22.4 w/ below config.
2. Add k8s deployment and headless service for a simple app which returns pod name/ip.
3. Scale to 3 replicas.
4. Make requests across 10 different request hash inputs (in this case `color` query parameter)
5. Repeat, confirm consistent hashing works.
6. Scale down to 2 replicas.
7. Make requests again. 
8. Note that request keys move between unaffected hosts. (repeat from step 4 until this occurs)

In the below example, I make 1 request for each of 10 input keys (colors). I then remove a host (pod). The other hosts retain the same IPs. Notice that `green` and `purple` requests move from `broker-lite-b48d8c64c-9k5nd` to `broker-lite-b48d8c64c-9v49m` even though neither host changed (only `broker-lite-b48d8c64c-h5vjb` was removed).
```
@zarenner ➜ ~/…/router/experiments/script (7bcdefa ✗) $ go run send_traffic.go
Stats: (10 total requests)
Pod broker-lite-b48d8c64c-9k5nd - 10.244.1.41 - 10.224.0.5:
    black requests: 1
    green requests: 1
    purple requests: 1
Pod broker-lite-b48d8c64c-9v49m - 10.244.0.22 - 10.224.0.4:
    brown requests: 1
    grey requests: 1
    orange requests: 1
    white requests: 1
Pod broker-lite-b48d8c64c-h5vjb - 10.244.2.25 - 10.224.0.6:
    blue requests: 1
    red requests: 1
    yellow requests: 1
@zarenner ➜ ~/…/router/experiments/script (7bcdefa ✗) $ kubectl scale deploy/broker-lite --replicas 2
deployment.apps/broker-lite scaled
@zarenner ➜ ~/…/router/experiments/script (7bcdefa ✗) $ go run send_traffic.go                       
Stats: (10 total requests)
Pod broker-lite-b48d8c64c-9k5nd - 10.244.1.41 - 10.224.0.5:
    black requests: 1
    blue requests: 1
Pod broker-lite-b48d8c64c-9v49m - 10.244.0.22 - 10.224.0.4:
    brown requests: 1
    green requests: 1
    grey requests: 1
    orange requests: 1
    purple requests: 1
    red requests: 1
    white requests: 1
    yellow requests: 1
@zarenner ➜ ~/…/router/experiments/script (7bcdefa ✗) $ go run send_traffic.go
Stats: (10 total requests)
Pod broker-lite-b48d8c64c-9k5nd - 10.244.1.41 - 10.224.0.5:
    black requests: 1
    blue requests: 1
Pod broker-lite-b48d8c64c-9v49m - 10.244.0.22 - 10.224.0.4:
    brown requests: 1
    green requests: 1
    grey requests: 1
    orange requests: 1
    purple requests: 1
    red requests: 1
    white requests: 1
    yellow requests: 1
```

*Config*:
<details><summary>Config</summary>

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: broker-lite
                  cluster: broker_cluster
                  hash_policy:
                  - query_parameter:
                      name: color
  clusters:
  - name: broker_cluster
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: RING_HASH
    load_assignment:
      cluster_name: service_broker_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: broker-lite
                port_value: 8081
```
</details>
