### ISSUE TITLE
num_retries is not set to 0 on route through Envoy Filter

### ISSUE THREAD

**Issue by anand-bidwalkar** [envoyproxy/envoy#22574]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: num_retries is not set to 0 on route through Envoy Filter

*Description*:
Hi Team,
We are trying to set the num_retries to 0 on a route through Envoy Filter. But minimum it is getting set to 1, when we pass value 0 it sets the default to 2. This route is created by Virtual Service through ISTIO 1.13.3  which uses Envoy 1.21.2 Below is the Envoy Filter used. I would highly appreciate your kind response.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: retry-basic-node
  namespace: staging
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
      routeConfiguration:
        vhost:
          name: 'basic-node-green.staging.svc.cluster.local:8080'
          route:
            name: 'default'
       
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": type.googleapis.com/envoy.config.route.v3.RouteAction
        route:
          retry_policy:
            num_retries: 0

```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
