### ISSUE TITLE
stats: need tag-extractor support for multiple regexes targeting same tag name

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#22591]
Istio use ` "regex": "(response_code=\\.=(.+?);\\.;)|_rq(_(\\.d{3}))$"` for response_code stats tag, [here](https://github.com/istio/istio/blob/f0bb371da14af5229cd297c76fc7145771aec6db/tools/packaging/common/envoy_bootstrap.json#L48) is the source code.

## step 1
I test with the following stats, which work as expected:
```yaml
stats_config:
  use_all_default_tags: false
  stats_tags:
    - tag_name: response_code
      regex: "_rq(_(\\d{3}))$"
      #regex: "(response_code=\\.=(.+?);\\.;)|_rq(_(\\d{3}))$"
      #regex: "_rq(_(\\d{3}))$|(response_code=\\.=(.+?);\\.;)"
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: default_service
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: staticreply-8080
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: default_service
      load_assignment:
        cluster_name: default_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
```
output as following:
```console
envoy_cluster_default_service_external_upstream_rq{response_code="200"} 1
envoy_cluster_default_service_upstream_rq{response_code="200"} 1
```
## step 2
Change regex string to `"(response_code=\\.=(.+?);\\.;)|_rq(_(\\d{3}))$"` , I only get output with following:
```console
$ curl 127.0.0.1:10000 && curl 127.0.0.1:9901/stats/prometheus | grep response_code
envoy_cluster_default_service_external_upstream_rq_200{response_code=""} 1
envoy_cluster_default_service_upstream_rq_200{response_code=""} 1
```
## step 3
Change regex string to `"_rq(_(\\d{3}))$|(response_code=\\.=(.+?);\\.;)"`, the output looks good again:
```
envoy_cluster_default_service_external_upstream_rq{response_code="200"} 1
envoy_cluster_default_service_upstream_rq{response_code="200"} 1
```

maybe related to the following code:
https://github.com/envoyproxy/envoy/blob/c4ecdd07585d43fb2bbe145b60417ba412941ec8/source/common/stats/tag_extractor_impl.cc#L123

cc @mattklein123 can take a look at this?
