### ISSUE TITLE
Route Checker error on HTTP filters/extensions 

### ISSUE THREAD

**Issue by dzane17** [envoyproxy/envoy#22648]
*Title*: Route Checker INVALID_ARGUMENT Error

*Description*:
```
% bazel build //test/tools/router_check:router_check_tool

% bazel-bin/test/tools/router_check/router_check_tool -c envoy.yaml -t test.yaml
Protobuf message (type envoy.config.route.v3.RouteConfiguration reason INVALID_ARGUMENT:admin: Cannot find field.) has unknown fields
[2022-08-10 15:56:14.741][1414723][debug][init] [source/common/init/watcher_impl.cc:31] init manager RTDS destroyed
[2022-08-10 15:56:14.742][1414723][debug][init] [source/common/init/watcher_impl.cc:31] RTDS destroyed
```

*Additional Info*:
1. I forked the envoy repo and cloned to mac. Fork and local are synced with upstream.
2. Tried several config files - yaml & json filetype, sample config copied from envoy website, my custom config. All produce same error.
3. Error is non-deterministic. Can error on any top-level field. Ex. `INVALID_ARGUMENT:admin`, `INVALID_ARGUMENT:static_resources`

**Comment by wbpcode** [comment]
Could you post a example yaml that will result in the error here ?

**Comment by dzane17** [comment]
I found out the problem. I was passing the envoy template instead of envoy yaml. Thanks for your response though.

**Comment by dzane17** [comment]
Getting an error on http filters. Do they need to be imported somewhere?
```
% bazel-bin/test/tools/router_check/router_check_tool -c envoy5.yaml -t test.json                       
Unable to parse JSON as proto (INVALID_ARGUMENT:(virtual_hosts[0].routes[0].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.lua.v3.LuaPerRoute for type Any):
```

Testing Config:
```
virtual_hosts:
- name: backend
  domains: ["*"]
  routes:
    - match:
        prefix: "/healthcheck"
      direct_response:
        status: 200
        body:
          inline_string: "Envoy_OK"
      typed_per_filter_config:
        envoy.filters.http.lua:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
          disabled: true
    - match:
        path: "/_internal/path"
        headers:
          - name: ":method"
            string_match:
              exact: PUT
      route:
        cluster: abc
        timeout: 300s
```
