### ISSUE TITLE
Does router checker support extensions?

### ISSUE THREAD

**Issue by vrozov** [envoyproxy/envoy#22665]
Trying to run router checker tool on the routing yaml config with
```
    typed_per_filter_config:
      envoy.filters.http.dynamic_forward_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
        host_rewrite_header: "My_header"
```
getting
```
Unable to parse JSON as proto (INVALID_ARGUMENT:(virtual_hosts[0].routes[55].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig for type Any):
```
