### ISSUE TITLE
Add support for matching VirtualHost.Domains without `port` considered

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#22664]
*Title*: Add support for matching VirtualHost.Domains without `port` considered

*Description*:
We would like a way for `domains` to be matched ignoring port. For example, `domains: [foo.com]` would match `Host: foo.com:1234`, if we configured some setting.

Alternatives considered:

* Set the match to include the port (e.g: `domains: [foo.com, foo.com:1234]`). The issue with this is we don't know all the ports. The most common case for this is when we have multiple different network paths (example: going through Kubernetes LoadBalancer vs NodePort vs direct, etc) - the set could be unbounded
* Use `strip_port_mode` in HCM. This is not viable because it mutates the request; we want to ignore the port in matching but keep it in upstream requests.
* Use a suffix match (e.g: `domains: [foo.com, foo.com:*]`). This *almost* works. The edge case is if we have other prefix matches.

For example:
```yaml
- domains: [*.example.com:443] # match wildcard
- domains: [foo.example.com, foo.example.com:*] # match concrete
```

In this case, `Host: foo.example.com` would correctly match `concrete`. However, due to precedence rules of wildcards, `Host: foo.example.com:443` would end up matching `wildcard`

**Comment by wbpcode** [comment]
```
    // Without setting this option, incoming requests with host ``example:443`` will not match against
    // route with :ref:`domains<envoy_v3_api_field_config.route.v3.VirtualHost.domains>` match set to ``example``. Defaults to ``false``. Note that port removal is not part
    // of `HTTP spec <https://tools.ietf.org/html/rfc3986>`_ and is provided for convenience.
    // Only one of ``strip_matching_host_port`` or ``strip_any_host_port`` can be set.
    bool strip_any_host_port = 42;

```

Sounds it's reasonable to me to add a mode that just ignore port for domain matching but doesn't strip the port from the header.

**Comment by zhxie** [comment]
@wbpcode do you prefer the method to add a new `strip_port_mode` to restore original port back to requests no matter what their method are (compared with `strip_any_host_port`), or a new field to just ignore port on virtual host matching?

**Comment by wbpcode** [comment]
> @wbpcode do you prefer the method to add a new `strip_port_mode` to restore original port back to requests no matter what their method are (compared with `strip_any_host_port`), or a new field to just ignore port on virtual host matching?

For this requirement `we want to ignore the port in matching but keep it in upstream requests`, I prefer the method that to add a new `strip_port_mode`. In this mode, a host value that stripped port will be used to match against host set. But we will not update the host/authority header value truly.
This way will be more simple and clear and it also has no impact on the existing features.

Only a very personal idea.

**Comment by zhxie** [comment]
I would like to fix that, but I am not sure which approach is the best.
You said we could add a `strip_port_mode` which will not update the header value and use stripped port for *matching*. But there is a lot matching like virtual hosts matching, routes matching and its generic matching, and also matchings inside HTTP filters. I do not think we can just use stripped port for virtual hosts matching only mentioned in the issue. It will cause some puzzled like 
```yaml
# request with host: example.com:8080
virtual_hosts:
  - name: app
    domains:
    - "example.com" # read stripped host header "example.com"
    matcher:
      matcher_list:
        matchers:
        - predicate:
            single_predicate:
              input:
                name: request-headers
                typed_config:
                  "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                  header_name: host # read original host header "example.com:8080"
```
So I suggest to add a new field which **just** ignore port on vhost matching, or add a `strip_port_mode` for stripping and storing back. What is your opinion, @wbpcode?

**Comment by wbpcode** [comment]
Sorry, may be my description is not clear. What you said `ignore port on vhost matching` is what I want.

**Comment by zhxie** [comment]
I find that `ignore_port_in_host_matching` field in `route_config` can solve the issue. The configuration

```yaml
route_config:
  name: local_route
  virtual_hosts:
  - name: app
    domains:
    - *.foo.com
    routes:
    - match:
        prefix: /
      route:
        cluster: service-http
  ignore_port_in_host_matching: true
```

can route `www.example.com:1234` to virtual host `app` without modifying host field in HTTP headers.

CC @wbpcode
