### ISSUE TITLE
Communicate with downstream envoy behind private network

### ISSUE THREAD

**Issue by Shinerrs** [envoyproxy/envoy#22697]
*Title*: Is it possible from the downstream envoy to establish a connection with the upstream, from the upstream service to send a tcp request to a service behind the downstream envoy without exposing the downstream envoy to a public IP/Port.

*Description*:
In my scenario, I have a central envoy (Upstream) that contains a management service. This management service is meant to connect to multiple clusters. Each cluster is behind a private network with the only option engress with no ingress option for envoy.

This StackOverFlow describes the senario very well: 

> For a hybrid-cloud use-case we are looking into the suitability of EnvoyProxy to act as a solution to move data across an on-premise firewall. The intended setup is as follows:
> 
> App A is located in an on premise network with no direct outbound or inbound Internet connection
> App B is located on the cloud
> An envoy proxy (PC) is placed in the cloud
> An envoy proxy (PA) is placed in the on-premise network, and configured to allow outbound network connection to PC
> PA creates a open bi-directional authenticated TLS connection to PC, effectively creating a tunnel between them
> App B invokes an API endpoint at PC, which gets routed to PA over the open TLS connection, and forwarded by PA to App A
> Routing data with Envoy to upstream clusters is well documented. However, we are wondering if Envoy is able to setup a TLS connection between two proxy instances and use that channel in both directions. The constraint is that this TLS connection can be setup from one direction (outbound) only.
> 

We want the management service to make requests to applications over HTTP and TCP.

I have been looking into the TCPProxy option that is described in the video in stackOverflow but I am struggling to find the target needed to communicate with the downstream server.

I have also been following the examples in the Sandbox documentation but my issue is that I am not looking to setup a streaming connection but a way to tunnel the two networks so their accessable.

I have been struggling with the understanding due to limited explaination in the docs.

I have also been following the examples in the Sandbox documentation but my issue is that I am not looking to setup a streaming connection but a way to tunnel the two networks so their accessable.

I have been struggling with the understanding due to limited explaination in the docs.

Things I have looked into are and tried a few of the sandboxes examples they give.

WebSocket is a one to one streaming and does not allow reverse proxy to multiple services.

I have read that Envoy Connect/TCPProxy could be a solution, I tried this but struggled to find an endpoint to the DownStream Cluster that is connected to the listener on the Upstream server.

Any advise would be highly apprichiated.

[optional *Relevant Links*:]
>[StackOverflow](https://stackoverflow.com/questions/63706137/use-envoy-to-setup-a-tunnel-between-networks)

**Comment by wbpcode** [comment]
Hi, could you provide some arch graph to help others to understand you issue? It seems that is complicated.

**Comment by Shinerrs** [comment]
![Untitled](https://user-images.githubusercontent.com/6631904/184599075-9fd1da62-e5f0-43b1-9865-52c5879b519e.jpg)

Hello, Thank you for asking for more clarity. I have attached an image to show the direction of envoy traffic and the end goal.

Please let me know if you have any further questions.

**Comment by wbpcode** [comment]
As far as I know, it would be impossible. May be we can implement some special extensions to achieve this, but I personally don't think it's proper way of using Envoy. May be I miss something.

cc @mattklein123 @alyssawilk

**Comment by Shinerrs** [comment]
Hello @wbpcode 

I would have to disagree with you. In the envoy documentation Envoy speak about how the solution would replace stunnel.

In the sTunnel example it is possible to establish a Client to Server Tunnel with the Server only having to expose its port publically. Once the tunnel is up, you can specify to expose services and ports over that tunnel. In essense, creating a sub-network between the two networks. 

If we look at WireGuard for example, again we can have a client to server connection that allows the exposure of some or all the network.

I feel that if there is a tunnel between the two open like webSocket does, then having service discovery or just port exposure should be a small step of this type of implementation.

I have worked in Finance, Telecommunication and Military Enterprise organisations and this style of central management to reduce public internet exposure is a must. 

As for the future, statistics show that the future is Hybrid Cloud. This is a great example to utlise that scenario.

Maybe my opinion is Bias ;)

**Comment by wbpcode** [comment]
> In the envoy documentation Envoy speak about how the solution would replace stunnel.

May be this is what I missed. Could you give a doc link about this?

**Comment by Shinerrs** [comment]
Hey, well its dependent on on how you inturpt the documentation.

https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/tcp_proxy

> The TCP proxy filter performs basic 1:1 network connection proxy between downstream clients and upstream clusters. It can be used by itself as an stunnel replacement

But then there is no documentation explaining this.

**Comment by Shinerrs** [comment]
Another Example of Wireguard doing something almost similiar: 

https://iliasa.eu/wireguard-how-to-access-a-peers-local-network/

**Comment by wbpcode** [comment]
Yeah, it's possible create bi-direction TCP connections by the TCP proxy. It means that the App B can create a connection to App A and then the App A can send anything to the App B proactively.
But I don't think this is what you want. 

From you description, you may want create a tunnel connection between two envoy, and then, the App A can send the request to App B in any time just by create a new connection with the left envoy. Did I understand correctly?

**Comment by Shinerrs** [comment]
On your second point:

> From you description, you may want create a tunnel connection between two envoy proxies, and then, the App A can send the request to App B in any time just by create a new connection with the left envoy. Did I understand correctly?

Yes! exactly. So setting up a Downstream (Right Envoy) to Upstream (Left Envoy) tunnel seems straight forward and I don't seen any issue here.

But the part that is confusing me is the "and then" part of your statement. When App A communicates with the Upstream envoy (Left Envoy) how does this work?

My best guess would be that App A would communicate an a seperate listener from the tunnel, When it connects and listener filter points to a cluster, what would be the target endpoint to target the tunnel connection that is already established so I can forward the listener request the Downstream envoy (Right Envoy)?

**Comment by Shinerrs** [comment]
So to elaborate more on my local env:

Downstream Envoy (Right Envoy):
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9902
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: ingress_http
          cluster: cluster_0
  - name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: ingress_http
          cluster: cluster_1
  clusters:
  - name: cluster_0
    connect_timeout: 5s
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.0.1.52
                port_value: 10000
  - name: cluster_1
    connect_timeout: 5s
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80
```

So from the Right Envoy we are connecting to our UpStream Envoy server via 10000 on listener_0. This is establishing our TCPProxy Tunnel. 

Listener_1 is intended when the envoy Upstream returns  a request via the tunnel.

Upstream Envoy (Left Envoy):
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: ingress_http
```

Missing pieces here are, Upstream Envoy requires a Cluster for TcpProxy.

But in this regard I dont want to request to go any further. I want to tunnel to wait for an application to make a request to the Upstream envoy which will be sent to the downstream envoy and target listener_1
