### ISSUE TITLE
[Question] How can I insert a HTTP header only when that header does not exist?

### ISSUE THREAD

**Issue by SpecialYang** [envoyproxy/envoy#22713]
For example, I want to add a HTTP header `foo: bar` into request when the original request does not have the HTTP header `foo`. But, if the original request have the HTTP header `foo`, envoy should do nothing header manipulation for this request.

The existing setting [HeaderValueOption](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-headervalueoption) can't resolve this issue. Please correct me if i am wrong.

CC @wbpcode

**Comment by wbpcode** [comment]
Hmm, yeah, although the new option was added in the #18246, the implementation is still absent.

**Comment by wbpcode** [comment]
I will try to land it.

**Comment by soulxu** [comment]
A workaround should be able to do that for now
```
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: "foo"
                    present_match: false
                route:
                  cluster: my_cluster
                request_headers_to_add:
                - header:
                    key: foo
                    value: bar
              - match:
                  prefix: "/"
                  headers:
                  - name: "foo"
                    present_match: true
                route:
                  cluster: my_cluster
```
