### ISSUE TITLE
per_connection_buffer_limit_bytes as cluster level does not work as expected

### ISSUE THREAD

**Issue by nguyenptk** [envoyproxy/envoy#22724]
*Title*: *per_connection_buffer_limit_bytes as cluster level does not work as expected*

*Description*:
I'm trying to use per_connection_buffer_limit_bytes per listener & cluster level. But the cluster level seems not to work as expected. I have a few scenarios:
- Use listener level only: **works as expected** with all of the values.
- Use cluster level only: **NOT work as expected**. The request is limited by 1024 KiB (default value) though how much the cluster's variable is.
```
clusters:
- name: some_service
   per_connection_buffer_limit_bytes: 10971520 # ~ 10 MB - still limited by 1048576 ~ 1 MB
```
- Use both listener and cluster: **NOT work as expected**. The request is limited by the listener's variable only, and Envoy ignores the cluster's variable. The cluster level should be the final barrier to protecting the upstream services.
```
listeners:
- name: some_listener
   per_connection_buffer_limit_bytes: 20971520 # 20MB
...
clusters:
- name: some_service
   per_connection_buffer_limit_bytes: 10971520 # ~ 10 MB
```
Envoy version: 1.21.2

**Comment by mattklein123** [comment]
cc @alyssawilk @yanavlasov @KBaichoo

**Comment by KBaichoo** [comment]
@nguyenptk   Can you provide a bit more details, for example the configuration of the envoy for a listener and for a cluster and the protocols used, and the characteristics of the traffic?

**Comment by nguyenptk** [comment]
@KBaichoo 
I've created a small demo [here](https://github.com/nguyenptk/something/tree/main/envoy-file-upload)

I missed one important part here, listener level only works with the `BufferWatermarks` requests. On our side, we have some customization about watermarks (in DecodeHeaders, DecodeData, EncodeHeaders, and EncodeData to get the body of request and response in order to do a different logic) so the listener level can work well in this situation with the endpoints that use watermarks.

But in the above demo without watermarks, `per_connection_buffer_limit_bytes` does not work at both listener and cluster levels.

**Comment by KBaichoo** [comment]
Hi @nguyenptk, thanks for the demo. Can you clarify what your expectation for `per_connection_buffer_limit_bytes` are? What should I be looking at that isn't what is expected?

**Comment by nguyenptk** [comment]
Hi @KBaichoo, I'm expecting my demo can work with per_connection_buffer_limit_bytes by multipart/form-data upload:
- `listener` level will be the first barrier
- `cluster` level will be the second (last) barrier after the listener level if it's configured. Or `cluster` level will be the first barrier if the listener level is not configured.

**Comment by nguyenptk** [comment]
So I think in our Envoy (customization), `per_connection_buffer_limit_bytes ` at listener level can work because of BufferWatermarks at filter level, and in the demo, we don't have any BufferWatermarks then listener level cannot work.

While cluster level does not work in both cases of our Envoy (customization) and Envoy (raw - `FROM envoyproxy/envoy-dev:latest`)

**Comment by nguyenptk** [comment]
About our Envoy (customization), we allow creating new filters by Go language to override the DecodeHeaders, DecodeData, EncodeHeaders, EncodeData with Continue, StopIteration, StopAllIterationAndWatermark, StopIterationAndBuffer, StopIterationNoBuffer.
In these filters, we can do some other custom logic with bodies.

**Comment by KBaichoo** [comment]
Unfortunately, both listener & cluster levels in the demo cannot work now
> In what way do they not work? How are they "not a barrier"?  Are you expecting this to be the post request size limit e.g. post can only be 10MB?

**Comment by nguyenptk** [comment]
Hi @KBaichoo, sorry for the late response
Have you tried my demo yet?
If you try it, you will see there is no limit for file upload here.

I just want to find an variable in Envoy that can help me limit the size of file uploading from downstream. If `per_connection_buffer_limit_bytes` is not the right way, could you point me to other variables?

**Comment by KBaichoo** [comment]
`per_connection_buffer_limit_bytes` is not the right way to do this. You could implement this using https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/buffer/v3/buffer.proto#extensions-filters-http-buffer-v3-buffer if you're fine buffering the 10MB (or whatever your limit is) in the Envoy.

**Comment by KBaichoo** [comment]
From slack:
@nguyenptk : I did some testing that follow you recommendation max_request_bytes . And I realized, I can do it per route level, it will be more useful than filter level in my use case.
But maybe the particular route setting does not work (route level). My configuration is
```
route_config:
    name: local_route
    virtual_hosts:
    - name: backend
      domains:
      - "*"
      routes:
      - match:
          prefix: "/v1/upload"
        route:
          cluster: upload_service
      - match:
          prefix: "/v1/upload/limit-per-route"
        route:
          cluster: upload_service
        # Want to limit particular route here        
        typed_per_filter_config:
          envoy.filters.http.buffer:
            "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
            buffer:
              max_request_bytes: 10485760 # ~10 MB
```


> I *suspect* you need to have the filter configured globally, then disabled for routes that you don't want the buffer filter on. As it's implemented right now, I don't think it supports disabling globally and enabling for a particular route. That would be a welcomed contribution :).

**Comment by nguyenptk** [comment]
@KBaichoo 
I'm thinking about 
> That would be a welcomed contribution :).
also.

The normal behavior here is in the same listener (same port, for example: 8080), we should support `max_request_bytes` per particular route. The filter level will hold the global value and in a particular route, we can override the global there.
```
     filter_chains:
- filters:
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      codec_type: AUTO
      stat_prefix: ingress_http
      route_config:
        name: local_route
        virtual_hosts:
        - name: backend
          domains:
          - "*"
          routes:
          - match:
              prefix: "/v1/something" # there is no max_request_bytes here
            route:
              cluster: upload_service
          - match:
              prefix: "/v1/upload/limit-1"
            route:
              cluster: upload_service
            typed_per_filter_config:
              envoy.filters.http.buffer:
                "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
                buffer:
                  max_request_bytes: 10485760 # ~10 MB  - route's value will override global's value
          - match:
              prefix: "/v1/upload/limit-2"
            route:
              cluster: upload_service
            typed_per_filter_config:
              envoy.filters.http.buffer:
                "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
                buffer:
                  max_request_bytes: 31457280 # ~30 MB - route's value will override global's value
      http_filters:
      - name: envoy.filters.http.buffer
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
          max_request_bytes: 20971520 # ~20 MB - global's value
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
