### ISSUE TITLE
Originating TLS on sidecar proxy for gRPC requests fails with"Received RST_STREAM with code 0" error

### ISSUE THREAD

**Issue by photomoose** [envoyproxy/envoy#22737]
*Description*:
I am using the Google Client Libraries to access Datastore, which use gRPC. My app is able to make a direct connection to Datastore without any issues - however it is the app that is establishing the TLS connection. I am trying to push back the TLS origination to the Envoy sidecar proxy - I've followed the Istio documentation and created a Destination Rule and Service Entry as follows:

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gcp-datastore
spec:
  hosts:
    - datastore.googleapis.com
  exportTo:
    - '.'
  location: MESH_EXTERNAL
  ports:
    - number: 80
      name: http
      protocol: HTTP
      targetPort: 443
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gcp-datastore
spec:
  host: datastore.googleapis.com
  exportTo:
    - '.'
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE
```

I've also created a little test Node application which explicitly tells the Google Datastore library to use port 80 without any TLS:

```
const {Datastore} = require('@google-cloud/datastore');
const {grpc} = require('google-gax');

const datastore = new Datastore({
    projectId: '<project id>',
    namespace: '<namespace>',
    apiEndpoint: 'datastore.googleapis.com:80',
    sslCreds: grpc.ChannelCredentials.createInsecure()
});

async function listTasks() {
  const query = datastore.createQuery('task');
  const [tasks] = await datastore.runQuery(query);
  console.log('Tasks:');
  for (const task of tasks) {
    const taskKey = task[datastore.KEY];
    console.log(taskKey.id, task);
  }
}
listTasks();
```

The output from running this script is as follows:

```
# node test.js
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 13 INTERNAL: Received RST_STREAM with code 0
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:190:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:160:30)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@google-cloud/datastore/build/src/v1/datastore_client.js:181:29
    at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at repeat (/app/node_modules/google-gax/build/src/normalCalls/retries.js:80:25)
    at /app/node_modules/google-gax/build/src/normalCalls/retries.js:118:13
    at OngoingCall.call (/app/node_modules/google-gax/build/src/call.js:67:27)
    at NormalApiCaller.call (/app/node_modules/google-gax/build/src/normalCalls/normalApiCaller.js:34:19)
    at /app/node_modules/google-gax/build/src/createApiCall.js:81:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 13,
  details: 'Received RST_STREAM with code 0',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```

*Logs*:
The Envoy access logs show the following, which I think implies that I'm getting a response from the upstream server on port 443 and that the Service Entry / Destination Rule configuration is correct:
```
istio-proxy [2022-08-17T10:26:29.480Z] "POST /google.datastore.v1.Datastore/RunQuery HTTP/2" 200 - via_upstream - "-" 69 0 12 11 "-" "grpc-node-js/1.6.9" "a58d89b5-0d4b-4707-9556-d66edc55342d" "datastore.googleapis.com:80" "142.250.187.202:443" outbound|80||datastore.googleapis.com 10.80.131.32:43964 240.240.0.26:80 10.80.131.32:47538 - default
```

I have also tried making manual requests to the gRPC discovery endpoint without HTTPS (e.g. `curl http://datastore.googleapis.com/\$discovery/rest?version=v1`) and that returns the correct response that would be expected if I were calling it with HTTPS (the document is not available on HTTP) - which further proves the TLS origination appears to be working.

What could be the issue with gRPC?
