### ISSUE TITLE
Use ENVOY for proxy HTTPS connection (different source IP adresses)

### ISSUE THREAD

**Issue by AlexeyKukin** [envoyproxy/envoy#22747]
Hi all! Please helpme,

My main goal:
Make 5 ENVOY listners on different ports for redirect https requests in different envoy servers for this requests have different source IPs (envoy upstream endpoint)
for Example:
listner on  port 10001 accept, filter, and send traffic to ENVOY IP 10.0.0.1, then initiate https outgoing connection from this IP.
listner on  port 10002 accept, filter, and send traffic to ENVOY IP 10.1.0.1, then initiate https outgoing connection from this IP.
etc... 

So, I want use envoy endpoints  as https proxy server. How can I do that?
I do not want decrypt ssl session just initiate connection trough different envoy proxy. 
CLIENT initiate ssl connection to any site with CONNECT method and use ENVOY as a proxy.

Can you provide config example for this case? (Listner, cluster)

**Comment by AlexeyKukin** [comment]
![image](https://user-images.githubusercontent.com/23698931/185243718-a2e38360-2ccb-495f-a1bd-7bdae064de32.png)

**Comment by zhxie** [comment]
You may listener to multiple address using `additional_address`

```yaml
listeners:
- address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001
  additional_address:
  - address:
      socket_address:
      port_value: 10002
  # and more ...
```

redirect HTTP requests using generic matching

```yaml
virtual_hosts:
- name: app
  domains:
  - "*"
  matcher:
    matcher_tree:
      input:
        name: envoy.matching.inputs.destination_port
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput
      exact_match_map:
        map:
          10000:
            action:
              name: route
              typed_config:
                "@type": type.googleapis.com/envoy.config.route.v3.Route
                match:
                  prefix: /
                route:
                  cluster: service1
          # and more ...
```

and send to upstream HTTPS cluster

```yaml
clusters:
- name: service1
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: service1
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 10.0.0.1
              port_value: 443
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
# and more ...
```

Please refer to [listener](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto.html#config-listener-v3-listener)'s additional address, [virtual host](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost)'s matcher and [TLS sandbox](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/tls) for more information.
