### ISSUE TITLE
[Proposal] matching: add multi regex matcher

### ISSUE THREAD

**Issue by zhxie** [envoyproxy/envoy#22752]
*Title*: matching: add multi regex matcher

*Description*:

In generic matching, we have a linear `matcher_list` and a sublinear `matcher_tree` for different algorithms to apply. The sublinear `matcher_tree` gives us opportunity to accelerate matching against multiple patterns, like select the expected route according to the `SourceIPInput` with trie-based matcher tree `TrieMatcher`. Currently, we have a `exact_match_map` and a `prefix_match_map` works as a hash map and a trie, which provides O(1) and O(n) time complexity searching algorithms. In addition, we have custom map matcher `IPMatcher`, which provides trie matching specifically against IPs.

It is now time to regex. RE2 (and other regex engines) provides ability to match against multiple regex patterns as once, so we can benefit from it to build a map matcher to match multiple regex patterns at the same time. `RE2::Set` can compile multiple regex patterns and returns an array slice of the index of the hit pattern on matching. We can accelerate regex matching for users with multiple regex routing, or multiple security rules like RBAC policies on the same input.

Multi regex matcher will be introduced as a `CompiledMultiMatcher`, provides interfaces including `std::vector<uint_t> matchAll(const absl::string_view value)` to returning all matched patterns' indexes and derived `bool match(const absl::string_view value)`. It can be applied to both traditional string match and generic matching with the following API:

```yaml
# string match
string_match:
  multi_regex:
  - safe_regex:
      regex: abc
  - safe_regex:
      regex: def

# generic matching
matcher_tree:
  regex_match_tree:
    typed_config:
      "@type": some_type
      regexes:
      - regex: abc
        on_match:
          action:
            name: action1
      - regex: def
        on_match:
          action:
            name: action2
```

and when an input `abcdef` get matched, the multi regex matcher will returns both `action1` and `action2`, and the former `action1` will be take in the generic matching.

`CompiledMultiMatcher` may benefit in regions including WAF and path matching.
