### ISSUE TITLE
Document tls_minimum_protocol_version versions below TLSv1.2 require cipher_suites manually set

### ISSUE THREAD

**Issue by gsalisbury** [envoyproxy/envoy#22842]
*Title*: Setting tls_minimum_protocol_version below TLSv1.2 not working with envoy 1.23.0

*Description*:
With envoy 1.23.0, and a config as below, TLS protocols below TLSv1.2 fail. For example, when testing with curl inside the envoyproxy/envoy:1.23.0 docker container (after installing curl inside the container and adding test.example.com to /etc/hosts):

```bash
root@81d22a314505:/etc/envoy# curl --tlsv1.2 https://test.example.com:10000/direct
direct response body

root@81d22a314505:/etc/envoy# curl --tlsv1.1 https://test.example.com:10000/direct
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

root@81d22a314505:/etc/envoy# curl --tlsv1.0 https://test.example.com:10000/direct
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

Appears to be caused by no shared ciphers, see logs below.

*Repro steps*:
Reproducable with the envoyproxy/envoy:1.23.0 docker image. With the same config and the envoyproxy/envoy:1.22.3 image, curl with `--tlsv1.0` for example works.

*Admin and Stats Output*:

*Config*:
```yaml
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 10000
  listener_filters:
  - name: "envoy.filters.listener.tls_inspector"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  filter_chains:
  - filter_chain_match:
      server_names: ["test.example.com"]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        common_tls_context:
          tls_params:
            tls_minimum_protocol_version: TLSv1_0
          alpn_protocols: ["h2,http/1.1"]
          tls_certificate_sds_secret_configs:
            - name: wild_tls_sds
              sds_config:
                path_config_source:
                  path: /etc/envoy/sds/certificate.yaml
                resource_api_version: V3
    filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        codec_type: AUTO
        common_http_protocol_options:
          idle_timeout: 3600s 
          headers_with_underscores_action: REJECT_REQUEST
        http2_protocol_options:
          max_concurrent_streams: 100
          initial_stream_window_size: 65536
          initial_connection_window_size: 1048576 
        stream_idle_timeout: 300s
        request_timeout: 300s
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

        rds:
          route_config_name: test_route_proxy
          config_source:
            resource_api_version: V3
            path_config_source:
              path: /etc/envoy/rds/rds1.yaml
```
*Logs*:
```
[2022-08-29 06:38:28.844][36][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:85] tls inspector: new connection accepted
[2022-08-29 06:38:28.849][36][debug][filter] [source/extensions/filters/listener/tls_inspector/tls_inspector.cc:116] tls:onServerName(), requestedServerName: test.example.com
[2022-08-29 06:38:28.849][36][debug][conn_handler] [source/server/active_tcp_listener.cc:147] [C4] new connection from 127.0.0.1:45058
[2022-08-29 06:38:28.849][36][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:228] [C4] remote address:127.0.0.1:45058,TLS error: 268435640:SSL routines:OPENSSL_internal:NO_SHARED_CIPHER
```
*Call Stack*:
