### ISSUE TITLE
Try to use Kafka Broker filter but it is failed in my local

### ISSUE THREAD

**Issue by ahmedalawady** [envoyproxy/envoy#22846]
*Title*: *Try to use Kafka Broker filter but envoy validation throw unable to parse JSON*

*Description*:
OS: macOS Monterey
Envoy Version: c919bdec19d79e97f4f56e4095706f8e6a383f1c/1.22.2/Modified/RELEASE/BoringSSL
Installed by: `brew install envoy`

This is my configuration
```
static_resources:

  listeners:
  - address:
      socket_address:
        address: 127.0.0.1 # Host that Kafka clients should connect to.
        port_value: 19092  # Port that Kafka clients should connect to.
    filter_chains:
    - filters:
      - name: envoy.filters.network.kafka_broker
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker
          stat_prefix: exampleprefix
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          cluster: localkafka
  clusters:
  - name: localkafka
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: some_service
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1 # Kafka broker's host
                  port_value: 9092 # Kafka broker's port.
                  ```

The error is 

```
[2022-08-25 15:58:25.063][402182][critical][main] [source/server/config_validation/server.cc:63] error initializing configuration 'metrics.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0].filters[0].typed_config): invalid value Invalid type URL, unknown type: envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker for type Any): {"static_resources":{"clusters":[{"lb_policy":"round_robin","load_assignment":{"cluster_name":"some_service","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":9092,"address":"127.0.0.1"}}}}]}]},"type":"strict_dns","connect_timeout":"0.25s","name":"localkafka"}],"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.network.kafka_broker.v3.KafkaBroker","stat_prefix":"exampleprefix"},"name":"envoy.filters.network.kafka_broker"},{"typed_config":{"stat_prefix":"tcp","cluster":"localkafka","@type":"type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"},"name":"envoy.filters.network.tcp_proxy"}]}],"address":{"socket_address":{"port_value":19092,"address":"127.0.0.1"}}}]}}
```

**Comment by daixiang0** [comment]
[Kafka Broker](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/kafka_broker_filter.html) belongs to `contrib`, so you need to use a binary including contrib. I am not sure `brew` provide that binary, but I have test it with contrib image using your config, it works:
```
docker run --rm -v $(pwd)/config.yaml:/config.yaml envoyproxy/envoy-contrib:v1.22-latest -c /config.yaml
```

**Comment by ahmedalawady** [comment]
@daixiang0 Thank you so much, it is working now but I have another problem, I run Kafka using docker and I faced this error 
```
 WARN [Controller id=1, targetBrokerId=1] Connection to node 1 (/127.0.0.1:19092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

I ran Envoy 

```
docker run --rm -p 19000:19000 -p 19092:19092 -v $(pwd)/config.yaml:/config.yaml envoyproxy/envoy-contrib:v1.22-latest -c /config.yaml
```

My docker compose is 

```
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:19092
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

```
