### ISSUE TITLE
envoy doesn't support prefix_rewrite value as empty string value

### ISSUE THREAD

**Issue by ningyougang** [envoyproxy/envoy#22841]
Issue: `envoy doesn't support prefix_rewrite value as empty string value`

Steps to reproduce the issue
* startup a http server on my local ip: `10.168.255.52`
```
# python3 -m http.server 8888
Serving HTTP on 0.0.0.0 port 8888 (http://0.0.0.0:8888/) ...
```
* Wrote a envoy simple example configuration as below
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/foo"
                route:
                  prefix_rewrite: "/"       
                  host_rewrite_literal: 10.168.255.52
                  cluster: test_cluster

  clusters:
  - name: test_cluster
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: test_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.168.255.52
                port_value: 8888
```
* startup a envoy filter with above yaml
```
docker run --name=envoy-example -d -p 81:10000 -v /tmp/envoy.yaml:/etc/envoy/envoy.yaml envoyproxy/envoy:v1.23-latest
```
* Access `curl http://localhost:81/foo`, it is ok, e.g.
```
# python3 -m http.server 8888
Serving HTTP on 0.0.0.0 port 8888 (http://0.0.0.0:8888/) ...
10.105.236.133 - - [25/Aug/2022 11:42:19] "GET / HTTP/1.1" 200 -
```
* Access  `curl http://localhost:81/foo/a`, reported `404`
```
Serving HTTP on 0.0.0.0 port 8888 (http://0.0.0.0:8888/) ...
10.105.236.133 - - [25/Aug/2022 11:42:19] "GET / HTTP/1.1" 200 -
10.105.236.133 - - [25/Aug/2022 11:43:45] "GET //a HTTP/1.1" 404 -
```
the statusCode is correct, but from above log, the path is `//a`,  according to my assumption, there is an extra slash, my expectation of the path should be `/`

* Try to solve it with configure the `prefix_rewrite` to empty string, e.g.
![image](https://user-images.githubusercontent.com/11749867/186562932-a7bdceb9-cb69-40e2-8400-9a1b2bdfaa66.png)

But unfortunately, it seems envoy doesn't have this `prefix_rewrite: ""` if  configure it as empty string.
So it doesn't work as expected, so i access `curl http://localhost:81/foo` again, the client reported
```
10.105.236.133 - - [25/Aug/2022 11:50:11] "GET /foo HTTP/1.1" 404 -
```
We can see  `prefix_rewrite: ""` doesn't work.

Someone knows the reason why  `prefix_rewrite: ""` doesn't work for envoy?
If want to make  `prefix_rewrite: ""` works well, is it possible?

My goal as below if `prefix_rewrite: ""` works well
http://localhost:81/foo      -> http://10.168.255.52:8888
http://localhost:81/foo/a   -> http://10.168.255.52:8888/a
Then, the path changed from `//a` to `/a`

**Comment by bryanwux** [comment]
```
- match:
    prefix: "/foo"
  route:
    prefix_rewrite: "/"       
    host_rewrite_literal: 10.168.255.52
    cluster: test_cluster
```
Use only a single route will route "/prefix/a" to "//a" and forward it.  To route"/prefix/a" to "/a" and "/prefix" to "/", you need to handle all cases and use two routes. 

Something like: 
```
- match:
    prefix: "/foo/"
  route:
    prefix_rewrite: "/"       
    host_rewrite_literal: 10.168.255.52
    cluster: test_cluster
- match:
    prefix: "/foo"
  route:
    prefix_rewrite: "/"       
    host_rewrite_literal: 10.168.255.52
    cluster: test_cluster
```
