### ISSUE TITLE
IPv6 Host format is not validated before it is propagated to :authority

### ISSUE THREAD

**Issue by LithiumSR** [envoyproxy/envoy#22859]
Hello everyone.
I have noticed that in IPv6, when Envoy translates a request to HTTP2 , Envoy does not seem to check and verify the host address format before propagating the value to the :authority pseudo-header.
Host addresses like "2001:db8::2:1:443" (it does not adhere to the [ip]:port format) are applied as "they-are" in the :authority header.
Keep in mind that [RFC3986 ](https://www.rfc-editor.org/rfc/rfc3986.html#section-3.2.2) states the following about host header:

> A host identified by an Internet Protocol literal address, version 6
>    [[RFC3513](https://www.rfc-editor.org/rfc/rfc3513)] or later, is distinguished by enclosing the IP literal
>    within square brackets ("[" and "]").

Therefore I would expect that non-rfc3986-compliant headers would lead to an error and not be propagated to :authority as part of the conversion from http1 to http2.
For your reference, [RFC7230](https://httpwg.org/specs/rfc7230.html#header.host)mentioned host header handling.

> A server MUST respond with a [400 (Bad Request)](https://httpwg.org/specs/rfc7231.html#status.400) status code to any HTTP/1.1 request message that lacks a Host header field and to any request message that contains more than one Host header field or a Host header field with an invalid field-value.

Is the current behavior intentional or is there an actual issue?
I have verified the behavior on Envoy 1.22.2

**Comment by kfaseela** [comment]
cc @soulxu

**Comment by soulxu** [comment]
@LithiumSR @kfaseela I tested this behavior by chaining two Envoy together, the first Envoy accept a HTTP request, then forward a http2 request to the second envoy, but it seems the header is using the format as expected.

My first envoy config is as below:
```
static_resources:
  listeners:
  - name: my_listener
    address:
      socket_address:
        protocol: TCP
        address: "::"
        port_value: 13333
    filter_chains:
    - filters:
      # The HTTP connection manager is the only network filter.
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: my_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: my_cluster
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    protocol_selection: USE_CONFIGURED_PROTOCOL
    http2_protocol_options: {}
    load_assignment:
      cluster_name: my_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "::"
                port_value: 33333

```

My second config is as below:
```
static_resources:
  listeners:
  - name: my_listener
    address:
      socket_address:
        protocol: TCP
        address: "::"
        port_value: 33333
    filter_chains:
    - filters:
      # The HTTP connection manager is the only network filter.
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http2_protocol_options: {}
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: my_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: my_cluster
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    protocol_selection: USE_CONFIGURED_PROTOCOL
    http2_protocol_options: {}
    load_assignment:
      cluster_name: my_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "::"
                port_value: 43333
```

Then I can get a log of the second envoy:

```
[2022-08-28 12:55:09.780][24102][debug][http] [source/common/http/conn_manager_impl.cc:919] [C0][S9521367370826021756] request headers complete (end_stream=true):
':authority', '[::1]:13333'
':path', '/'
':method', 'GET'
':scheme', 'http'
'user-agent', 'curl/7.58.0'
'accept', '*/*'
'x-forwarded-proto', 'http'
'x-request-id', 'af1490b9-14e4-4219-9371-eda2bf963633'
'x-envoy-expected-rq-timeout-ms', '15000'
```

@LithiumSR do you have any different config in your setup?
