### ISSUE TITLE
PostgreSQL HA with Patroni support

### ISSUE THREAD

**Issue by d4j-opensource** [envoyproxy/envoy#22867]
Recently, I built PostgreSQL cluster with Patroni. Using HAProxy simplifies this by giving a single endpoint to which you can connect the application for Master/Replica.

haproxy.conf

```
global
    maxconn 100

defaults
    log global
    mode tcp
    retries 2
    timeout client 30m
    timeout connect 4s
    timeout server 30m
    timeout check 5s

listen stats
    mode http
    bind *:7000
    stats enable
    stats uri /

listen cluster-a-leader
    bind *:5000
    option httpchk OPTIONS /master
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server node1 node1:5432 maxconn 100 check port 8008 inter 1s
    server node2 node2:5432 maxconn 100 check port 8008 inter 1s
    server node3 node3:5432 maxconn 100 check port 8008 inter 1s

listen cluster-a-replicas
    bind *:5001
    option httpchk OPTIONS /replica
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server node1 node1:5432 maxconn 100 check port 8008 inter 1s
    server node2 node2:5432 maxconn 100 check port 8008 inter 1s
    server node3 node3:5432 maxconn 100 check port 8008 inter 1s
```

I tried with Envoy still doesn't route request to correct master/replica nodes.

Envoy configuration:

```
static_resources:
  listeners:
  - name: postgres_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5000
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: postgres_tcp
          cluster: postgres_cluster

  clusters:
  - name: postgres_cluster
    type: STRICT_DNS
    connect_timeout: 1s
    health_checks:
      - interval: 3s
        timeout: 3s
        no_traffic_interval: 4s
        no_traffic_healthy_interval: 4s
        unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check:
          path: "/master"
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: node1
                port_value: 5432
            health_check_config:
              port_value: 8008
        - endpoint:
            address:
              socket_address:
                address: node2
                port_value: 5432
            health_check_config:
              port_value: 8008
        - endpoint:
            address:
              socket_address:
                address: node3
                port_value: 5432
            health_check_config:
              port_value: 8008
```
Enviroment:

```
envoy  version: d362e791eb9e4efa8d87f6d878740e72dc8330ac/1.18.2/clean-getenvoy-76c310e-envoy/RELEASE/BoringSSL
Ubuntu 20.04
```

Thanks for any assistance!

https://github.com/zalando/patroni

**Comment by daixiang0** [comment]
> I tried with Envoy still doesn't route request to correct master/replica nodes.
Does Envoy not do route? Do you mean you can access via HAProxy but can not access Envoy+HAProxy?

**Comment by d4j-opensource** [comment]
@daixiang0 
My configuration for PostgreSQL Master, it check path "/master" that return status 200 (node1)
However, Envoy still route to replica node (node2, node3)

**Comment by fabriziomello** [comment]
Hey @d4j-opensource, thanks for reaching out. To be honest I never used EnvoyProxy as a load balancer for Postgres, but I guess there are missing items in your configuration like `lb_subset_config`. I recommend you check those pages from our documentation:
- https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/locality_load_balancing

**Comment by fabriziomello** [comment]
@d4j-opensource And I found this test configuration that I used when developed the Postgres Network Filter (didn't check if still valid: 
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 54322
    filter_chains:
    - filters:
      - name: envoy.filters.network.postgres_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
          stat_prefix: egress_postgres
      - name: envoy.tcp_proxy
        typedConfig:
          '@type': type.googleapis.com/envoy.config.filter.network.tcp_proxy.v2.TcpProxy
          statPrefix: postgres.internal:5432
          weighted_clusters:
            clusters:
            - name: postgres.internal:5432
              metadata_match:
                filter_metadata:
                  envoy.lb:
                    role: replica
              weight: 100

  clusters:
  - name: postgres.internal:5432
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    lb_subset_config:
      fallback_policy: DEFAULT_SUBSET
      default_subset:
        stage: prod
      subset_selectors:
      - keys:
        - role
    load_assignment:
      cluster_name: postgres.internal:5432
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5432
          metadata:
            filter_metadata:
              envoy.lb:
                role: master
                version: v10
                stage: prod
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5433
          metadata:
            filter_metadata:
              envoy.lb:
                role: replica
                version: v9
                stage: prod
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5434
          metadata:
            filter_metadata:
              envoy.lb:
                role: replica
                version: v9
                stage: prod
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5435
          metadata:
            filter_metadata:
              envoy.lb:
                role: replica
                version: v9
                stage: prod
```
