### ISSUE TITLE
Upstream connect error with envoy.extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport extension

### ISSUE THREAD

**Issue by Amila-Rukshan** [envoyproxy/envoy#22881]
I run squid proxy in `127.0.0.1:3129` location on my machine and I have built envoy with a custom filter same as the [example](https://github.com/envoyproxy/envoy/blob/c3418f14daa6809ab47ce4c8d21ceceabbc7d292/test/integration/filters/header_to_proxy_filter.cc) given under [extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/http_11_proxy/v3/upstream_http_11_connect.proto#extensions-transport-sockets-http-11-proxy-v3-http11proxyupstreamtransport) documentation (Actually I have [modified](https://github.com/Amila-Rukshan/envoy-filter-example/commit/33d7c6f7c2305c896d08d6384a0811de453c6105) the [envoy-filter-example](https://github.com/Amila-Rukshan/envoy-filter-example/tree/main/http-filter-example) to do it for now).

I run the envoy binary with the following config:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/my-api"
                route:
                  cluster: service-squid
          http_filters:
          - name: header-to-proxy          
            typed_config:
              "@type": type.googleapis.com/sample.Decoder
              key: hey
              val: hiya
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: service-squid
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: proxy_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: www.envoyproxy.io
                    port_value: 443
    transport_socket:
        name: envoy.transport_sockets.http_11_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
When I invoke like below:
```
curl localhost:10000/my-api -H "connect-proxy: 127.0.0.1:3129" -H "host: www.envoyproxy.io" -v
```
output:
```
*   Trying ::1:10000...
* connect to ::1 port 10000 failed: Connection refused
*   Trying 127.0.0.1:10000...
* Connected to localhost (127.0.0.1) port 10000 (#0)
> GET /my-api HTTP/1.1
> Host: www.envoyproxy.io
> User-Agent: curl/7.77.0
> Accept: */*
> connect-proxy: 127.0.0.1:3129
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Mon, 29 Aug 2022 17:38:07 GMT
< server: envoy
< 
* Connection #0 to host localhost left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure% 
```
Trace logs: https://gist.github.com/Amila-Rukshan/9977b05e9967470312f07b13a8e99c8c

I have [another setup](https://gist.github.com/Amila-Rukshan/9a557ad53b709a25e80cc255470e88f7) using envoy internal listeners which works fine with the same proxy.

Error log in squid proxy container:
```
connection: conn97 local=172.23.0.3:3129 remote=172.23.0.1:56392 FD 12 flags=1
2022/08/30 08:58:17| ERROR: failure while accepting a TLS connection on conn98 local=172.23.0.3:3129 remote=172.23.0.1:56394 FD 12 flags=1: 0xffff6a09b3e0*1
```

Now I'm struggling to figure out the issue with this config

Another related question:
Do we need to define endpoints section since we configure both `proxy address` and `endpoint hostname` via the filter state?
