### ISSUE TITLE
some questions about lb_policy

### ISSUE THREAD

**Issue by qinrui96** [envoyproxy/envoy#22890]
Can anyone dispel my confusion about **ROUND_ROBIN** load balance policy
my config is shown below

```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 127.0.0.1, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/hello" }
                          route: { cluster: some_service }
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: some_service
      connect_timeout: 2s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: some_service
        endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8000
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8001

```

when I use **curl http://127.0.0.1:10000/hello** to get response from endpoints, I think the outcome should be 
127.0.0.1:8000
127.0.0.1:8001
127.0.0.1:8000
127.0.0.1:8001
127.0.0.1:8000
127.0.0.1:8001
....
in fact the result is:
![image](https://user-images.githubusercontent.com/48122144/187358324-4192cfe2-3e38-4b91-b7f4-4ead73322acb.png)
