### ISSUE TITLE
envoy-1.23 ext_proc routing path override / reply chain bypassing disabled going through the service 

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#22925]
*Description*:
ext_proc filter is configured to be disabled at the virtual host level + configured as a service override at the route level.
For requests matching the route request and reply headers sent as expected.
However, for non-matching requests in the request path, requests that do not match bypassing ext_proc request as expected, while at reply path reply headers been sent through ext_proc. 

*Config*:
```
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/ext_proc_test/"
                route:
                  cluster: app_cluster
                typed_per_filter_config:
                  envoy.filters.http.ext_proc:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                    overrides:
                      grpc_service:
                        envoy_grpc:
                          cluster_name: test_one_cluster
              include_request_attempt_count: true
              require_tls: ALL
              typed_per_filter_config:
                envoy.filters.http.ext_proc:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                  disabled: true
          http_filters:
          - name: envoy.filters.http.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
              pass_through_mode: false
              - name: ":path"
                string_match:
                  exact: "/healthcheck"
          - name: envoy.filters.http.ext_proc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
              failure_mode_allow: false
              message_timeout: 61.5s
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SEND"
                request_body_mode: "NONE"
                response_body_mode: "NONE"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"
              grpc_service:
                envoy_grpc:
                  cluster_name: test_cluster
...
```
