### ISSUE TITLE
Wasm VM failed Failed to initialize Wasm code

### ISSUE THREAD

**Issue by wanggithub08** [envoyproxy/envoy#22920]
I wrote an envoy filter, but an error was reported when deploying, the error message is as follows
```
2022-08-31T13:01:30.849847Z	debug	envoy wasm	WasmVm created envoy.wasm.runtime.v8 now active
2022-08-31T13:01:30.850186Z	debug	envoy wasm	Base Wasm created 21 now active
2022-08-31T13:01:30.941959Z	error	envoy wasm	Wasm VM failed Failed to initialize Wasm code
2022-08-31T13:01:30.942010Z	debug	envoy wasm	~Wasm 20 remaining active
2022-08-31T13:01:30.944416Z	debug	envoy wasm	~WasmVm envoy.wasm.runtime.v8 20 remaining active
2022-08-31T13:01:30.945863Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to create Wasm HTTP filter
```

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: productpage-filter
  namespace: istio
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy_filter
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          value:
            config:
                # 'configuration' available at root_context.getConfiguration()
             # configuration:
             #   '@type': type.googleapis.com/google.protobuf.StringValue
             #   value: '[{"cluster":"demo","namespace":"one","service":"two"}]'
                # root_id MUST match registerRootContext() 2nd param
              root_id: add_header
              vm_config:
                code:
                  local:
                    filename: /var/local/envoyfilter/envoy_filter.wasm
                runtime: envoy.wasm.runtime.v8
                vm_id: my-example
  workloadSelector:
    labels:
      app: demo-default
```

The istio version information is as follows：
>client version: 1.7.8
pilot version: unknown
istiod version: 1.12.8
envoy version: "d68172a37cb87c52d683a906bd2fba90060f8d82/1.15.4-dev/Clean/RELEASE/BoringSSL"
proxy-wasm-rust-sdk:proxy-wasm = "0.2.0"

I used func-e to debug on my laptop and it was successful

**Comment by mattklein123** [comment]
cc @PiotrSikora @mpwarres

**Comment by 13567436138** [comment]
what language of your wasm was written?

**Comment by wanggithub08** [comment]
> what language of your wasm was written?

Rust

**Comment by wanggithub08** [comment]
> I wrote an envoy filter, but an error was reported when deploying, the error message is as follows
> 
> ```
> 2022-08-31T13:01:30.849847Z	debug	envoy wasm	WasmVm created envoy.wasm.runtime.v8 now active
> 2022-08-31T13:01:30.850186Z	debug	envoy wasm	Base Wasm created 21 now active
> 2022-08-31T13:01:30.941959Z	error	envoy wasm	Wasm VM failed Failed to initialize Wasm code
> 2022-08-31T13:01:30.942010Z	debug	envoy wasm	~Wasm 20 remaining active
> 2022-08-31T13:01:30.944416Z	debug	envoy wasm	~WasmVm envoy.wasm.runtime.v8 20 remaining active
> 2022-08-31T13:01:30.945863Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) virtualInbound: Unable to create Wasm HTTP filter
> ```
> 
> ```
> apiVersion: networking.istio.io/v1alpha3
> kind: EnvoyFilter
> metadata:
>   name: productpage-filter
>   namespace: istio
> spec:
>   configPatches:
>   - applyTo: HTTP_FILTER
>     match:
>       context: SIDECAR_INBOUND
>       listener:
>         filterChain:
>           filter:
>             name: envoy.filters.network.http_connection_manager
>             subFilter:
>               name: envoy.filters.http.router
>     patch:
>       operation: INSERT_BEFORE
>       value:
>         name: envoy_filter
>         typed_config:
>           '@type': type.googleapis.com/udpa.type.v1.TypedStruct
>           type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
>           value:
>             config:
>                 # 'configuration' available at root_context.getConfiguration()
>              # configuration:
>              #   '@type': type.googleapis.com/google.protobuf.StringValue
>              #   value: '[{"cluster":"demo","namespace":"one","service":"two"}]'
>                 # root_id MUST match registerRootContext() 2nd param
>               root_id: add_header
>               vm_config:
>                 code:
>                   local:
>                     filename: /var/local/envoyfilter/envoy_filter.wasm
>                 runtime: envoy.wasm.runtime.v8
>                 vm_id: my-example
>   workloadSelector:
>     labels:
>       app: demo-default
> ```
> 
> The istio version information is as follows：
> 
> > client version: 1.7.8
> > pilot version: unknown
> > istiod version: 1.12.8
> > envoy version: "d68172a37cb87c52d683a906bd2fba90060f8d82/1.15.4-dev/Clean/RELEASE/BoringSSL"
> > proxy-wasm-rust-sdk:proxy-wasm = "0.2.0"
> 
> I used func-e to debug on my laptop and it was successful

When I upgrade istio to 1.12, envoyfilter starts to work, but when I call grpc service, the error is as follows
>2022-09-01T08:47:35.145703Z	trace	envoy wasm	[vm->host] env.proxy_log(5, 1255904, 148)
2022-09-01T08:47:35.145710Z	critical	envoy wasm	wasm log: panicked at 'invalid token_id', ~/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proxy-wasm-0.1.4/src/dispatcher.rs:424:14
2022-09-01T08:47:35.145715Z	trace	envoy wasm	[vm<-host] env.proxy_log return: 0
2022-09-01T08:47:35.145912Z	error	envoy wasm	Function: proxy_on_grpc_receive_initial_metadata failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0xcc730 - __rust_start_panic
  1:  0xcc482 - rust_panic
  2:  0xcc3ff - _ZN3std9panicking20rust_panic_with_hook17h0934220b8bcb5bb0E
  3:  0xcb4ac - _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hd757106e895f8529E
  4:  0xcb3eb - _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17hda2217248ddf29b4E
  5:  0xcbd2a - rust_begin_unwind
  6:  0xd18ea - _ZN4core9panicking9panic_fmt17h99615bf411b9c1d7E
  7:  0xd8947 - _ZN4core9panicking13panic_display17h0cbd9d7b67cbe7b8E
  8:  0xd85b2 - _ZN4core9panicking9panic_str17hefaee680dd8e5b26E
  9:  0xd8580 - _ZN4core6option13expect_failed17h71dab1eaa8cb15ffE
2022-09-01T08:47:35.145969Z	trace	envoy wasm	[vm<-host] env.proxy_grpc_stream return: 10
2022-09-01T08:47:35.145976Z	trace	envoy wasm	[vm->host] env.proxy_log(3, 1255904, 34)
2022-09-01T08:47:35.145979Z	warning	envoy wasm	wasm log: echo call rejected InternalFailure
2022-09-01T08:47:35.145982Z	trace	envoy wasm	[vm<-host] env.proxy_log return: 0
2022-09-01T08:47:35.145988Z	trace	envoy wasm	[vm->host] env.proxy_grpc_send(0, 1254208, 1679, 0)
2022-09-01T08:47:35.145990Z	trace	envoy wasm	[vm<-host] env.proxy_grpc_send return: 2
2022-09-01T08:47:35.145999Z	trace	envoy wasm	[vm->host] env.proxy_log(5, 1256000, 184)
2022-09-01T08:47:35.146001Z	critical	envoy wasm	wasm log: panicked at 'called `Result::unwrap()` on an `Err` value: BadArgument', ~/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proxy-wasm-0.1.4/src/traits.rs:167:76
2022-09-01T08:47:35.146004Z	trace	envoy wasm	[vm<-host] env.proxy_log return: 0
2022-09-01T08:47:35.146009Z	trace	envoy wasm	[vm->host] wasi_snapshot_preview1.fd_write(2, 1047400, 1, 1047388)
2022-09-01T08:47:35.146012Z	error	envoy wasm	wasm log: thread panicked while panicking. aborting.
2022-09-01T08:47:35.146014Z	trace	envoy wasm	[vm<-host] wasi_snapshot_preview1.fd_write return: 0
2022-09-01T08:47:35.146114Z	error	envoy wasm	Function: proxy_on_response_body failed: Uncaught RuntimeError: unreachable
Proxy-Wasm plugin in-VM backtrace:
  0:  0xcfb6c - abort
  1:  0xc96b5 - _ZN3std3sys4wasi14abort_internal17hcdc2cafa96f87113E
  2:  0xcc451 - _ZN3std9panicking20rust_panic_with_hook17h0934220b8bcb5bb0E
  3:  0xcb4ac - _ZN3std9panicking19begin_panic_handler28_$u7b$$u7b$closure$u7d$$u7d$17hd757106e895f8529E
  4:  0xcb3eb - _ZN3std10sys_common9backtrace26__rust_end_short_backtrace17hda2217248ddf29b4E
  5:  0xcbd2a - rust_begin_unwind
  6:  0xd18ea - _ZN4core9panicking9panic_fmt17h99615bf411b9c1d7E
  7:  0xd8c45 - _ZN4core6result13unwrap_failed17h42eb2bde7057019eE
  8:  0x24cc4 - _ZN75_$LT$envoy_filter..MyContext$u20$as$u20$proxy_wasm..traits..HttpContext$GT$21on_http_response_body17h24241e9fd73e4e11E
  9:  0x35c5a - _ZN10proxy_wasm10dispatcher10Dispatcher21on_http_response_body17h3d782026dbe86b3aE
2022-09-01T08:47:35.146271Z	debug	envoy wasm	expr_evaluate value error: No value with name "downstream_peer" found in Activation

**Comment by 13567436138** [comment]
check your code

**Comment by mpwarres** [comment]
```
2022-09-01T08:47:35.146001Z critical envoy wasm wasm log: panicked at 'called Result::unwrap() on an Err value: BadArgument', ~/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proxy-wasm-0.1.4/src/traits.rs:167:76
```
and
```
7: 0xd8c45 - _ZN4core6result13unwrap_failed17h42eb2bde7057019eE
8: 0x24cc4 - ZN75$LT$envoy_filter..MyContext$u20$as$u20$proxy_wasm..traits..HttpContext$GT$21on_http_response_body17h24241e9fd73e4e11E
```
suggest that there is something in your on_http_response_body implementation that is blowing up on an Err Result.

**Comment by wanggithub08** [comment]
> ```
> 2022-09-01T08:47:35.146001Z critical envoy wasm wasm log: panicked at 'called Result::unwrap() on an Err value: BadArgument', ~/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/proxy-wasm-0.1.4/src/traits.rs:167:76
> ```
> 
> and
> 
> ```
> 7: 0xd8c45 - _ZN4core6result13unwrap_failed17h42eb2bde7057019eE
> 8: 0x24cc4 - ZN75$LT$envoy_filter..MyContext$u20$as$u20$proxy_wasm..traits..HttpContext$GT$21on_http_response_body17h24241e9fd73e4e11E
> ```
> 
> suggest that there is something in your on_http_response_body implementation that is blowing up on an Err Result.

Yes, I am calling the grpc service in my on_http_response_body implementation, but this grpc call throws an InternalFailure and returns an error. My implementation and configuration are as follows:
```
match self.open_grpc_stream(
            "echo", 
            "traffic.Tap", 
            "Observe",
            vec![("source", b"grpc_stream")],
        ) {
            Ok(token) => {
                stream_token = token;
                info!("echo call succeeded,success token {}", token)
            },
            Err(e) => warn!("echo call rejected {:?}", e),
        }
```

```
configPatches:
    - applyTo: CLUSTER
      match:
        context: ANY
      patch:
        operation: ADD
        value:
          connect_timeout: 0.5s
          hosts:
          - socket_address:
              address: 192.168.34.55
              port_value: 50051
              protocol: TCP
          lb_policy: ROUND_ROBIN
          name: echo
          type: STRICT_DNS
```
The services are normal, I suspect the configuration problem, but I have no idea.
