### ISSUE TITLE
a question about RING_HASH

### ISSUE THREAD

**Issue by qinrui96** [envoyproxy/envoy#22939]
I use RING_HASH as load balance policy, the config is shown below:
```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 127.0.0.1, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/hello" }
                          route:
                            cluster: some_service
                            hash_policy:
                              - header:
                                  header_name: server
                              
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: some_service
      connect_timeout: 2s
      type: STATIC
      lb_policy: RING_HASH
      load_assignment:
        cluster_name: some_service
        endpoints:
        - lb_endpoints:
            - metadata:
                filter_metadata:
                  envoy.lb:
                    hash_key: server1
              endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8000
            - metadata:
                filter_metadata:
                  envoy.lb:
                    hash_key: server2
              endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8001
```
since I set **envoy.lb**, the endpoint's (127.0.0.1:8000) hash key is server1, the endpoint's (127.0.0.1:8001) hash key is server2.
I set **hash_policy** so I get hash key from request header.
In my opinion, when I insert **server: server2** into request header, envoy will get **server2** as hash key to compute value. since I already set **server2** as **endpoint's (127.0.0.1:8001)** hash key, it should select **endpoint (127.0.0.1:8001)**. However I get result below:
![image](https://user-images.githubusercontent.com/48122144/187842133-125b5180-7139-44be-a080-61e78f318a0b.png)
