### ISSUE TITLE
Cant' configure custom DNS resolver

### ISSUE THREAD

**Issue by VictorDM** [envoyproxy/envoy#22945]
*Title*: *Cant' configure custom DNS resolver*

*Description*:
We are trying to configure a custom DNS resolver for a cluster. DNS is a Consul DNS server that returns the IP addresses with their ports (a random port for each IP), so we need to dybamically set that port for each resolved address.

We have tried the following configuration:

```
clusters:
  - name: test-cluster
    type: STATIC
    connect_timeout: 30s
    transport_socket_matches:
      name: test-cluster-ts
      match:
        sni: test.domain.com
      transport_socket:
        name: envoy.transport_sockets.tls        
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext        
          sni: test.domain.com
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                inline_string: "xxx"
              private_key:
                inline_string: "xxxx"
    load_assignment:
      cluster_name: test-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: 
                address: test.domain.com
                named_port: "https"
                resolver_name: dns
          metadata:
            filter_metadata:
              envoy.transport_socket_match:
                sni: test.domain.com 
    typed_dns_resolver_config:
      name: dns
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
        resolvers:
        - socket_address: 
            address: 127.0.0.11
            port_value: 53
```

And the error is
```
Unknown address resolver: dns. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```

We don't know how to link the port dynamically with the cluster nor why envoy is unable to find the resolver.

We have also tried other ways, including using a dynamic_forward_proxy but it doesn't look like the right solution.

Can you help us?

Thank in advance
