### ISSUE TITLE
Forward to private https endpoint 

### ISSUE THREAD

**Issue by chuongnguyen5397** [envoyproxy/envoy#22949]
I'm trying to do this flow: 

Envoy proxy receives traffic from https://mydomain.com/api/v1/test, then it will forward traffic to my another private endpoint, also rewrite the path, let's say https://privatedomain.com/it/api/test. 

But the envoy proxy is behind an ingress controller so traffic really come to envoy proxy is http

Below is the configuration I'm using:

```
admin:
    access_log_path: /tmp/admin_access.log
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 9901
  static_resources:
    listeners:
    - name: listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: [ "*" ]
                routes:
                - match:
                    prefix: "/api/v1/"
                  route:
                    prefix_rewrite: "/it/api/"
                    host_rewrite_literal: "privatedomain.com"
                    cluster: internal_service
            http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    clusters:
    - name: internal_service
      connect_timeout: 60s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: internal_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "privatedomain.com"
                      port_value: 443
```

But from log, it's saying that I have protocol error. So I assume that I can't forward to my private endpoint with https protocol??

```
[2022-09-01 15:29:32.285][17][debug][http] [source/common/http/conn_manager_impl.cc:261] [C51] new stream
[2022-09-01 15:29:32.285][17][debug][http] [source/common/http/conn_manager_impl.cc:882] [C51][S11118208827882801406] request headers complete (end_stream=true):
':authority', 'mydomain.com'
':path', '/api/v1/test'
':method', 'GET'
'x-request-id', '4f039e9813c6ab34baae5b998c08d43b'
'x-real-ip', '172.17.23.162'
'x-forwarded-for', '172.17.23.162'
'x-forwarded-host', 'mydomain.com'
'x-forwarded-port', '80'
'x-forwarded-proto', 'http'
'x-forwarded-scheme', 'http'
'x-scheme', 'http'
'x-original-forwarded-for', '54.251.111.27, 172.70.142.233, 64.252.86.119, 172.17.1.151'
'access-control-allow-origin', '*'
'access-control-allow-methods', 'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'
'access-control-allow-headers', 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'
'user-agent', 'Amazon CloudFront'
'via', '2.0 57f18a988739f5feaf34dc974846ac6c.cloudfront.net (CloudFront)'
'x-amz-cf-id', 'wsrgv6Qb5jx64bAjZhiGQHK-AH2r8vxYUXL8RMFrO8etYdxS9W75zw=='
'x-amzn-cipher-suite', 'ECDHE-RSA-AES128-GCM-SHA256'
'x-amzn-tls-version', 'TLSv1.2'
'x-amzn-trace-id', 'Root=1-6310cfdc-281b638c4e3966ab0a98082f'
'x-amzn-vpc-id', 'vpc-123abc123'
'x-amzn-vpce-config', '1'
'x-amzn-vpce-id', 'vpce-123abc123'
'x-amzn-apigateway-api-id', '123abc123'

[2022-09-01 15:29:32.285][17][debug][http] [source/common/http/filter_manager.cc:779] [C51][S11118208827882801406] request end stream
[2022-09-01 15:29:32.285][17][debug][router] [source/common/router/router.cc:445] [C51][S11118208827882801406] cluster 'internal_service' match for URL '/api/v1/test'
[2022-09-01 15:29:32.285][17][debug][router] [source/common/router/router.cc:631] [C51][S11118208827882801406] router decoding headers:
':authority', 'privatedomain.com'
':path', '/it/api/test'
':method', 'GET'
':scheme', 'http'
'x-request-id', '4f039e9813c6ab34baae5b998c08d43b'
'x-real-ip', '172.17.23.162'
'x-forwarded-for', '172.17.23.162'
'x-forwarded-host', 'mydomain.com'
'x-forwarded-port', '80'
'x-forwarded-proto', 'http'
'x-forwarded-scheme', 'http'
'x-scheme', 'http'
'x-original-forwarded-for', '54.251.111.27, 172.70.142.233, 64.252.86.119, 172.17.1.151'
'access-control-allow-origin', '*'
'access-control-allow-methods', 'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'
'access-control-allow-headers', 'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,sre'
'user-agent', 'Amazon CloudFront'
'via', '2.0 57f18a988739f5feaf34dc974846ac6c.cloudfront.net (CloudFront)'
'x-amz-cf-id', 'wsrgv6Qb5jx64bAjZhiGQHK-AH2r8vxYUXL8RMFrO8etYdxS9W75zw=='
'x-amzn-cipher-suite', 'ECDHE-RSA-AES128-GCM-SHA256'
'x-amzn-tls-version', 'TLSv1.2'
'x-amzn-trace-id', 'Root=1-6310cfdc-281b638c4e3966ab0a98082f'
'x-amzn-vpc-id', 'vpc-123abc123'
'x-amzn-vpce-config', '1'
'x-amzn-vpce-id', 'vpce-123123123'
'x-amzn-apigateway-api-id', '123abc123'
'x-envoy-internal', 'true'
'x-envoy-expected-rq-timeout-ms', '15000'
'x-envoy-original-path', '/api/v1/test'

[2022-09-01 15:29:32.286][17][debug][router] [source/common/router/upstream_request.cc:371] [C51][S11118208827882801406] pool ready
[2022-09-01 15:29:37.296][17][debug][router] [source/common/router/router.cc:1091] [C51][S11118208827882801406] upstream reset: reset reason: protocol error, transport failure reason: 
[2022-09-01 15:29:37.296][17][debug][http] [source/common/http/filter_manager.cc:883] [C51][S11118208827882801406] Sending local reply with details upstream_reset_before_response_started{protocol error}
[2022-09-01 15:29:37.296][17][debug][http] [source/common/http/conn_manager_impl.cc:1455] [C51][S11118208827882801406] encoding headers via codec (end_stream=false):
':status', '502'
'content-length', '87'
'content-type', 'text/plain'
'date', 'Thu, 01 Sep 2022 15:29:36 GMT'
'server', 'envoy'

[2022-09-01T15:29:32.285Z] "GET /api/v1/test HTTP/1.1" 502 UPE 0 87 5011 - "172.17.23.162" "Amazon CloudFront" "4f039e9813c6ab34baae5b998c08d43b" "privatedomain.com" "172.17.20.210:443"
```

I also tried with 
```
            stat_prefix: ingress_http
```

But it didn't work either. I found some issues with protocol error in Github before but I haven't seen the right reason 

Any help will be very appreciated
