### ISSUE TITLE
grpc_transcoder: request_validation support ignore_unknown_fields (ignore_unknown_enum_values)

### ISSUE THREAD

**Issue by northmorn** [envoyproxy/envoy#22966]
*Title*: 
grpc_transcoder: request_validation support ignore_unknown_fields (ignore_unknown_enum_values)

*Description*:
now
while parse invlaid enum value in query url, invlaid enum value is ignored

proto
```
message Theater {
   enum PAYMENT_SYSTEM{
      CASH = 0;
      CREDIT_CARD = 1;
      DEBIT_CARD = 2;
      APP = 3;  
   }
   PAYMENT_SYSTEM payment = 7;
}
```
config
```
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "xxxx"
              services: ["xxxx"]
              ignore_unknown_query_parameters: false
              print_options:
                add_whitespace: true
                always_print_primitive_fields: false
                always_print_enums_as_ints: false
                preserve_proto_field_names: true
              request_validation_options:
                reject_unknown_query_parameters: true
```
url
payment=foo

expected
If ignore_unknown_enum_values is true, an unknown enum value is ignored.
If ignore_unknown_enum_values is false, raise "Failed to transcode request".
