### ISSUE TITLE
The platform does not support either IP_TRANSPARENT or IPV6_TRANSPARENT when IPv6 is disabled

### ISSUE THREAD

**Issue by chfxr** [envoyproxy/envoy#22997]
Hello, we recently detected the following issue, that when IPv6 is disabled on the server, envoy doesn't start with the feature `use_original_src_ip: true`.

 ```
      listener_filters:
        - name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: service
            use_original_src_ip: true
            matcher:
              on_no_match:
                action:
                  name: route
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                    cluster: service_udp
```

Following error appears:
`error initializing configuration '/etc/envoy/envoy.yaml': The platform does not support either IP_TRANSPARENT or IPV6_TRANSPARENT. Or the envoy is not running with the CAP_NET_ADMIN capability.`

IPv6 was disabled via the following approach:
In `/etc/default/grub`
set
`GRUB_CMDLINE_LINUX="ipv6.disable=1"`
then
`update-grub`
and reboot.

System Details:
Envoy Version:  edd69583372955fdfa0b8ca3820dd7312c094e46/1.23.1/Clean/RELEASE/BoringSSL
OS: Ubuntu 22.04.1 LTS
Kernel: 5.15.0-47-generic
