### ISSUE TITLE
ECDS config source from path - discovery response format for resource 

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#23016]
Hi folks,
I'm also trying to implement ECDS but the config should come from a file.
I'm struggling to make it work... please help me with how to define the contents of the yaml file.

this config:
```
version_info: "100"
resources:
- "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
fails with:
`Filesystem config update rejected: Unable to unpack as envoy.config.core.v3.TypedExtensionConfig: [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router] `

```
          http_filters:
          - name: router
            config_discovery:
              type_urls: ["type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"]
              config_source:
                path: /usr/local/bin/test-ecds-v1.yml
              default_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

**Comment by kyessenov** [comment]
The issue is that you need to wrap `Router` message into `TypedExtensionConfig` message. That means something like this:
```
version_info: "100"
resources:
- "@type": type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig
  name: router
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

**Comment by pxpnetworks** [comment]
Thank you @kyessenov , it is accepted now however i tried to add a second http filter (rbac) before router and still get errors loading both rbac and router.
Can you help me with this once again? Thanks!

code:
```
- name: envoy.filters.http.rbac
  typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
    shadow_rules:
      action: LOG
      policies:
        "log":
          permissions: {any: true}
          principals: {any: true}
```
```
version_info: "100"
resources:
- "@type": type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig
  name: router
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
```
http_filters:
- name: router
  config_discovery:
    type_urls:
    - "type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC"
    - "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
    config_source:
      path: /usr/local/bin/test-ecds-v1.yml
    default_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

BR,
Stoyan
