### ISSUE TITLE
Why is the log file of UdpProxy of Envoy always empty

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23033]
I'm using Envoy as the only gateway of my backend micro-services, some of which provides some UDP services. So I need to configure my Envoy to route the UDP requests to the services.

Here is my config file:
```
static_resources:
  listeners:
  - name: listener_udp_test
    reuse_port: true
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 22221
    access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: "/home/administrator/envoy/udp_test.log"  ################## always empty!!!
    udp_listener_config:
      downstream_socket_config:
        max_rx_datagram_size: 9000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: example_ingress_udp
        cluster: cluster_udp_test
        upstream_socket_config:
          max_rx_datagram_size: 9000
  clusters:
  - name: cluster_udp_test
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_udp_test
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.1.2.3
                port_value: 22222
```
Let's say that we have such a kind of situation:
172.1.2.1(client) <---> 172.1.2.2(gateway) <---> 172.1.2.3(server)

So, the gateway is listening the port 22221 and routing requests to 172.1.2.3:22222.
I execute `nc -l -u 172.1.2.3 22222` on the server and I execute `nc -u 172.1.2.2 22221` on the client.

But, as you see I have configured a log file named `udp_test.log`. But it is always empty no matter how I send messages. As my understanding, shouldn't it store some log info about sending and receiving messages or about sender and receiver? If not, which kinds of info would be stored in this log file?

**Comment by giantcroc** [comment]
Hi, I am not familiar with `access_log` in listener, but you can use the following config for udp proxy access logging.
```
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: example_ingress_udp
        cluster: cluster_udp_test
        upstream_socket_config:
          max_rx_datagram_size: 9000
        access_log:
        - name: envoy.access_loggers.file
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: "/home/administrator/envoy/udp_test.log"
            log_format:
              text_format_source:
                inline_string: "[%START_TIME%]" //tokens you want to print
```
