### ISSUE TITLE
Calling `proxy_send_local_response` twice in wasm code results in access to freed memory space

### ISSUE THREAD

**Issue by johnlanni** [envoyproxy/envoy#23047]
*Description*:

I have two filters in my config, cors filter and wasm filter. 

```yaml
node:
  cluster: test-cluster
  id: test-idn

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9903 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
              routes:
              - match: { path: "/" }
                name: test
                route:
                  cluster: some_service
                  cors:
                    allow_methods: "GET,POST,PUT,DELETE,HEAD,OPTIONS,PATCH"
                    allow_headers: "*"
                    expose_headers: "*"
                    max_age: "86400"
                    allow_credentials: true
                    filter_enabled:
                      default_value:
                        numerator: 100
                    allow_origin_string_match:
                      safe_regex:
                        google_re2: {}
                        regex: ".*"
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: wasm
            typed_config:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
              value:
                config:
                  name: wasm
                  fail_open: true
                  vm_config:
                    runtime: envoy.wasm.runtime.v8
                    code:
                      local:
                        filename: /tmp/crash.wasm
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 12345
```

The wasm code is like this:
```go
package main

import (
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm"
        "github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm/types"
)

func main() {
        proxywasm.SetVMContext(&vmContext{})
}
type vmContext struct {
        types.DefaultVMContext
}
func (*vmContext) NewPluginContext(contextID uint32) types.PluginContext {
        return &pluginContext{}
}
type pluginContext struct {
        types.DefaultPluginContext
}
func (*pluginContext) NewHttpContext(contextID uint32) types.HttpContext {
        return &httpHeaders{contextID: contextID}
}
type httpHeaders struct {
        types.DefaultHttpContext
}

func (ctx *httpHeaders) OnHttpRequestBody(bodySize int, endOfStream bool) types.Action {
       proxywasm.SendHttpResponse(510, nil, nil, -1)
       proxywasm.SendHttpResponse(509, nil, nil, -1)
}
```
When I do a request like this, envoy crashes:
```bash
curl localhost:10000 -H 'origin: test'
```
Trace logs:
![image](https://user-images.githubusercontent.com/6763318/189290287-0b2f6aa7-6d49-4850-878d-4e2512336e97.png)

ASAN found `heap-use-after-free`.

I think the problem is : 
1. In wasm  function `proxy_on_request_body` calls host function `proxy_send_local_response` twice, registers the `sendLocalReply` by [addAfterVmCallAction](https://github.com/envoyproxy/envoy/blob/7a56d178771ba267aa2a8fd863a4d8b139fc1caf/source/extensions/common/wasm/context.cc#L1661)
2. this [doAfterVmCallActions](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/4fcf895fa2433a1cdf20704926b8b7e4039a6a04/include/proxy-wasm/wasm.h#L147) only pop the first function in the queue.
3. The first `sendLocalReply`  happens before [onRequestBody](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/4fcf895fa2433a1cdf20704926b8b7e4039a6a04/src/context.cc#L336) return, an it will trigger the wasm' filter's `encodeHeaders` and enter the wasm function `proxy_on_response_header`
4. The second `sendLocalReply` happens before [onResponseHeaders](https://github.com/proxy-wasm/proxy-wasm-cpp-host/blob/4fcf895fa2433a1cdf20704926b8b7e4039a6a04/src/context.cc#L372) return, and it will re-enter the `decoder_callbacks_->sendLocalReply`.
5.  The second call of `sendLocalReply` will trigger [sendDirectLocalReply](https://github.com/envoyproxy/envoy/blob/7a56d178771ba267aa2a8fd863a4d8b139fc1caf/source/common/http/filter_manager.cc#L889), it will override the response headers, and the [reference](https://github.com/envoyproxy/envoy/blob/7a56d178771ba267aa2a8fd863a4d8b139fc1caf/source/common/http/filter_manager.cc#L934)  in the first `sendLocalReply` will be released.
6. The cors filter's `encodeHeaders` will be called after the wasm filter's `encodeHeaders` during the first `sendLocalReply`, and it will access the freed memory by using the reference of the old response headers.
