### ISSUE TITLE
URX not set by network rate limit filter

### ISSUE THREAD

**Issue by simha5009** [envoyproxy/envoy#23058]
*Title*: Wrong response flag

*Description*:
The access log is showing the wrong response flag for all logs. Following is the sample. It has "-" for log messages.

{"path":null,"authority":null,"downstream_remote_address":"49.37.131.33:64345","duration":5303,"upstream_local_address":"0.0.0.0:49171","bytes_sent":8453,"x_forwarded_for":null,"downstream
_local_address":"172.17.160.240:443","upstream_transport_failure_reason":null,"request_id":null,"user_id":null,"response_code":0,"req_method":null,"req_path":null,"**response_flags**":"-","rou
te_name":null,"upstream_cluster":"hosted_proxy","method":null,"req_body":null,"upstream_service_time":null,"upstream_host":"10.0.0.5:8443","start_time":"2022-09-10T14:27:14.956Z","requeste
d_server_name":"4349494d-6743-434b-4167-45416f537949.rapatchimanaged.k8sconnect.azure.com","bytes_received":17341,"protocol":null,"user_agent":null}

### HTTP and TCP

- UH: No healthy upstream hosts in upstream cluster in addition to 503 response code.
- UF: Upstream connection failure in addition to 503 response code.
- UO: Upstream overflow ([circuit breaking](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking#arch-overview-circuit-break)) in addition to 503 response code.
- NR: No [route configured](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#arch-overview-http-routing) for a given request in addition to 404 response code, or no matching filter chain for a downstream connection.
- URX: The request was rejected because the [upstream retry limit (HTTP)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-retrypolicy-num-retries) or [maximum connect attempts (TCP)](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#envoy-v3-api-field-extensions-filters-network-tcp-proxy-v3-tcpproxy-max-connect-attempts) was reached.
- NC: Upstream cluster not found.
- DT: When a request or connection exceeded [max_connection_duration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-max-connection-duration) or [max_downstream_connection_duration](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto#envoy-v3-api-field-extensions-filters-network-tcp-proxy-v3-tcpproxy-max-downstream-connection-duration).

As per the docs, it should show one of the following:

Ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage

**Comment by simha5009** [comment]
I was trying to filter the logs based on rate-limited requests.

**Comment by agrawroh** [comment]
@simha5009 Looks like in this case status code = 0 which means that the downstream closed the connection. You can get more details from `%RESPONSE_CODE_DETAILS%` [[Ref]](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/response_code_details). From what I have seen it's possible that response flags are `null` in cases like `http2.remote_reset` etc.

**Comment by simha5009** [comment]
@agrawroh I have been trying the TCP rate limiter.

As per the docs, it should show URX for both TCP and HTTP connections.

Also, the connection is being terminated at the envoy and not  at downstream. I see the functionality is good but the CODE was wrong.

**Comment by snowp** [comment]
What exactly are you using to limit TCP connections? It's possible that we're not setting the flag in some circumstance

**Comment by simha5009** [comment]
Sample config:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        server_names: ["*.example.com"]
      filters:
      - name: envoy.filters.network.ratelimit
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit
          stat_prefix: hosted_proxy_rate_limits
          share_key: hosted_proxy_rate_limits
          token_bucket:
            max_tokens: 1
            fill_interval: 60s
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: proxy1
          cluster: proxy1
```
