### ISSUE TITLE
Is it possible to make an anchor for a part of object in YAML config file

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23099]
I have such a config file for my Envoy:
```
!ignore tcp_log_path: &tcplog "/tcp.log"
!ignore tcp_log_path: &udplog "/udp.log"
!ignore gw_meta_data:
  - &tcp_access_log [{name: envoy.access_loggers.file, typed_config: {"@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog, path: *tcplog}}]
  - &udp_access_log [{name: envoy.access_loggers.file, typed_config: {"@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog, path: *udplog}}]

static_resources:
  listeners:
  - name: listener_jitsi_https
    address:
      socket_address: *ingress_https_addr
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log: *tcp_access_log
```

It works but I found that this part `{name: envoy.access_loggers.file, typed_config: {"@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog,` was kind of too long and was repeated many times... So I'm thinking if it is possible to make an anchor for just this part so that I can make my config file.
