### ISSUE TITLE
Envoy proxy match and case sensitive

### ISSUE THREAD

**Issue by alimhabib** [envoyproxy/envoy#23127]
*Title*: *Envoy proxy match and case sensitive*

*Description*:
in my current project, I have many routes of the same but different Case example 

Home/test and home/Test or home/test 

Envoy doesn't recognize these differences as one, so I have to repeat the configuration per route 

```
                        - match:
                            prefix: /Home/test/
                          route:
                            cluster: application-cluster 
                        - match:
                            prefix: /home/test
                          route:
                            cluster: application-cluster 
```
   
any way to configure Envoy such that it's not cause sensitive                         

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
