### ISSUE TITLE
Rewriting a prefix matched with `path_separated_prefix` to `/`

### ISSUE THREAD

**Issue by michaelbeaumont** [envoyproxy/envoy#23130]
*Title*: Rewriting a prefix matched with `path_separated_prefix` to `/`

*Description*:

#### Problem

With [the introduction](https://github.com/envoyproxy/envoy/issues/18148) of [`path_separated_prefix`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routematch-path-separated-prefix), it's no longer necessary in all cases to use the trick of adding two matchers to match and rewrite a path-separated prefix:

```
- match:
    prefix: "/prefix/path/"
  route:
    prefix_rewrite: "/path"
- match:
    prefix: "/prefix/path"
  route:
    prefix_rewrite: "/path"
```

becomes:

```
- match:
    path_separated_prefix: "/prefix/path"
  route:
    prefix_rewrite: "/path"
```

and:

- `/prefix/path` -> `/path`
- `/prefix/path/rest` -> `/path/rest`

Except for one case, if we want to drop the prefix:

```
- match:
    path_separated_prefix: "/prefix"
  route:
    prefix_rewrite: "/"
```

results in the rewrites:

- `/prefix` -> `/`
- `/prefix/path` -> `//path`

#### Non-working solutions

The most natural attempt to solve this is probably:

```
- match:
    path_separated_prefix: "/prefix"
  route:
    prefix_rewrite: ""
```

with the expectation of the rewrites:

- `/prefix` -> ` `
- `/prefix/path` -> `/path`

and empty paths are probably less terrible than double slashes in paths.

but unfortunately [setting `prefix_rewrite: ""` causes Envoy to ignore it](https://github.com/envoyproxy/envoy/issues/22841).

#### Workaround

Fixing this actually seems to be impossible using `path_separated_prefix` and one must fall back to the old double `prefix` matches:

```
- match:
    prefix: "/prefix/"
  route:
    prefix_rewrite: "/"
- match:
    prefix: "/prefix"
  route:
    prefix_rewrite: "/"
```

resulting in:

```
- `/prefix/path` -> `/path`
- `/prefix` -> `/`
```

because using `path_separated_prefix` we can never "get rid of" the following `/` and rewriting to `""` doesn't work.

#### Potential solutions

Have I missed anything?

It seems like the purpose of introducing `path_separated_prefix` was to avoid the stumbling block of the double match pattern but this last special case makes it unavoidable.

Other than supporting `prefix_rewrite: ""` as above, we could rewrite `path_separated_prefix` + `prefix_rewrite: "/"` differently:

```
- match:
    path_separated_prefix: "/prefix"
  route:
    prefix_rewrite: "/"
```

- `/prefix` -> `/`
- `/prefix/path` -> `/path`

The semantics here being something like "`path_separated_prefix` matches both the prefix and any following slashes". It's a breaking change though.

**Comment by htuch** [comment]
@yanavlasov for thoughts on how to handle this kind of normalization (stuttered / at start of path) after rewrite.

Also related is [https://github.com/envoyproxy/envoy/pull/22703 and ](https://github.com/envoyproxy/envoy/issues/7763) and how this might work in that situation @silverstar194.

**Comment by holydrug** [comment]
@michaelbeaumont 
thanks a lot 

I killed my two days to be able route traffic success only with

```
- match:
    prefix: "/prefix/"
  route:
    prefix_rewrite: "/"
```

I write like that
```
- match:
    prefix: "/prefix"
  route:
    prefix_rewrite: "/"
```

Some urls excellent work with second configuration, but to be able to start up successfully all parts you need first configuration which is strange
