### ISSUE TITLE
Route is never hit 

### ISSUE THREAD

**Issue by alimhabib** [envoyproxy/envoy#23146]
I have a route like

wss://test.com/ws/4eecf518665840f4af93014e8841035f/Log  and my filter look like : 

```
      
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                upgrade_configs:
                  - upgrade_type: websocket
                access_log:
                  name: envoy.access_loggers
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
                route_config:
                  name: search_route
                  response_headers_to_remove:
                    - authorization
                    - X-Auth-Request-Access-Token
                  response_headers_to_add:
                    - header:
                        key: Content-Security-Policy
                        value: frame-ancestors 'self';
                    - header:
                        key: Strict-Transport-Security
                        value: max-age=31536000
                  virtual_hosts:
                    - name: incharge
                      cors:
                        allow_origin_string_match:
                          - safe_regex:
                              google_re2:
                                max_program_size: 200
                              regex: ^https:\/\/[^.]+\.${FRONTEND_DOMAIN}$
                        allow_methods: "POST, PUT, GET, DELETE"
                        allow_headers: "authorization,x-requested-with"
                        allow_credentials: true
                        max_age: "86400"
                      domains: ["*"]
                      routes:
                         
                        - match:
                            prefix: /ws/
                          route:
                            prefix_rewrite: '/'
                            cluster: clusterl-websocket
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle)
                                    request_handle:logInfo("Hello World.")
                                    request_handle:headers():replace("x-forwarded-proto", "https")
                                  end
                        # Fallback entry point for https redirect
                        - match:
                            prefix: /
                            headers:
                              - name: x-forwarded-proto
                                exact_match: http
                          redirect:
                            path_redirect: /
                            https_redirect: true
                        # Authentication entry point 
                        - match:
                            prefix: /${ADDRESS_POSTFIX}/oauth2/                            
                          route:
                            cluster: oauth-proxy
                        #patient Directory 
                        - match:
                            prefix: /${ADDRESS_POSTFIX}/mainpage
                            case_sensitive: false
                          route:
                            cluster: clusterl
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle) 
                                    request_handle:headers():add("x-app-prefix","/${ADDRESS_POSTFIX}/mainpage")                                    
                                  end 
                        - match:
                            prefix: /${ADDRESS_POSTFIX}/app
                            case_sensitive: false
                          route:
                            cluster: clusterl
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle) 
                                    request_handle:headers():add("x-app-prefix","/${ADDRESS_POSTFIX}/app")                                     
                                  end
                        # Others : Javascript files, css, ........ 
                        - match:
                            prefix: /${ADDRESS_POSTFIX}/Content
                            case_sensitive: false
                          route:
                            cluster: clusterl
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle) 
                                    request_handle:headers():add("x-app-prefix","http://${FRONTEND_URL}/${ADDRESS_POSTFIX}/mainpage")
                                  end  
                        - match:
                            prefix: /${ADDRESS_POSTFIX}/Scripts
                            case_sensitive: false
                          route:
                            cluster: clusterl
                          typed_per_filter_config:
                            envoy.filters.http.lua:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                              source_code:
                                inline_string: |
                                  function envoy_on_request(request_handle)
                                     request_handle:headers():replace("x-forwarded-proto", "https") 
                                    request_handle:headers():add("x-app-prefix","http://${FRONTEND_URL}/${ADDRESS_POSTFIX}/mainpage")
                                  end  
                                   
                http_filters:
                  - name: envoy.filters.http.cors
                    typed_config: {}
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      http_service:
                        server_uri:
                          uri: ${OAUTH_PROXY_ENDPOINT}:{OAUTH_PROXY_PORT}
                          cluster: oauth-proxy
                          timeout: 4.5s
                        authorization_request:
                          allowed_headers:
                            patterns:
                              - exact: cookie
                              - prefix: x-
                        authorization_response:
                          allowed_client_headers:
                            patterns:
                              - exact: set-cookie
                          allowed_client_headers_on_success:
                            patterns:
                              - exact: set-cookie
                              - prefix: x-auth-introspect 
                          allowed_upstream_headers:
                            patterns:
                              - exact: set-cookie
                              - contains: authorization
                              - prefix: x-auth-request
                              - prefix: x-auth-introspect
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        function envoy_on_request(request_handle)
                          local library = require("lib.envoyLibrary")
                          library.setIdToken(request_handle)
                          library.setAccessToken(request_handle) 
                        end
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        function envoy_on_request(request_handle)
                           local library = require("lib.envoyLibrary")
                           library.setIntrospectionValue(request_handle)
                        end
 
                  # Statful session support for Gfn application                
                  - name: envoy.filters.http.stateful_session
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
                      session_state:
                        name: envoy.http.stateful_session.cookie
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
                          cookie:
                            name: hds-av-session-cookie
                            path: /${ADDRESS_POSTFIX}
                            ttl: 300s 
                  - name: envoy.filters.http.router
                    typed_config: {}
  clusters:
    - name: oauth-proxy
      connect_timeout: 4.5s
      type: logical_dns
      load_assignment:
        cluster_name: oauth-proxy
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${OAUTH_PROXY_ENDPOINT}
                      port_value: ${OAUTH_PROXY_PORT}
    - name: clusterl
      connect_timeout: 1200s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: clusterl
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${FRONTEND_URL}
                      port_value: 8080
                      
    - name: clusterl-websocket
      connect_timeout: 1200s
      type: logical_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: clusterl-websocket
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ${FRONTEND_URL}
                      port_value: 8111
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9090

```
but it is never hit or rerouted, do I miss something
