### ISSUE TITLE
listener filter chain match doesn't work for incoming request using proxy protocol

### ISSUE THREAD

**Issue by levimm** [envoyproxy/envoy#23205]
*Title*: *listener filter chain match doesn't work for incoming request using proxy protocol*

*Description*:
I have two envoy proxy chained together: client -> envoy1 -> envoy2 -> server.
envoy1 just does the tcp forward and will use upstream proxy protocol to save the information about client ip.
envoy2 will handle the proxy protocol and route the traffic based on server name. However, envoy2's listener filter chain match won't work(it behaviors like server name match failed though it's the correct server name).

If proxy protocol is not used or envoy2 filter chain match is not used, then everything works fine.

envoy1 cluster snippet:
```
      clusters:
      - name: cluster1
        ...
        transport_socket:
          name: envoy.transport_sockets.upstream_proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
            config:
              version: V1
            transport_socket:
              name: envoy.transport_sockets.raw_buffer
        load_assignment:
          ...
```

envoy2 listener snippet:
```
        listeners:
        - name: listener1
          address:
            socket_address: { address: 0.0.0.0, port_value: 8080 }
          listener_filters:
            - name: envoy.filters.listener.tls_inspector
            - name: envoy.filters.listener.proxy_protocol
            - name: envoy.listener.original_src
          filter_chains:
            - filter_chain_match:
                server_names:
                  - hello1.com
               filters:
               ...
            - filter_chain_match:
                server_names:
                  - hello2.com
               filters:
               ...
            - filters: # request all ends up here
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
