### ISSUE TITLE
Http2 Flow Control with Grpc Streaming not pausing 

### ISSUE THREAD

**Issue by fabiomnk** [envoyproxy/envoy#23221]
*Title*: Http2 Flow Control with Grpc Streaming not pausing 

*Description*:
We are testing a disaster scenario in which our service should pause the inbound grpc streams in order to manage the backpressure of the systems behind it.

We see this behaviour when we test it routing the traffic to the service without envoy in front of it (AWS NLB -> k8s Service -> Pod )
We are using istio so when we route the traffic to envoy as istio ingressgateway and as sidecar it seems that the client don't receives the WINDOW_UPDATE frames that should stop the client from sending more data.
AWS NLB -> Istio Ingressgateway -> k8s Service -> Pod.

*Config*:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: h2-control
  namespace: istio-ingress
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: CLUSTER
    patch:
      operation: MERGE
      value:
        http2_protocol_options:
          initial_stream_window_size: 65536
          initial_connection_window_size: 65536
          connection_keepalive:
              interval: "1s"
              timeout: "2s"
              connection_idle_interval: "3s"
  - applyTo: NETWORK_FILTER
    match:      
      listener:
        portNumber: 10037
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          http2_protocol_options:
            initial_stream_window_size: 65536
            initial_connection_window_size: 65536
            connection_keepalive:
              interval: "1s"
              timeout: "2s"
              connection_idle_interval: "3s"

This same filter is configured to target the sidecar of the grpc server 
```

**Comment by adisuissa** [comment]
cc @alyssawilk @KBaichoo

**Comment by alyssawilk** [comment]
I think we'd need more detail to be of help debugging.  If you check out the flow control docs (https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/flow_control) there's no expectation of any changes to Envoy's normal flow until buffers back up.

"the client don't receives the WINDOW_UPDATE frames that should stop the client from sending more data."
AFIK the key is when buffers back up, Envoy will _stop_ sending window updates, such that the available window runs out and the peer will stop sending.

**Comment by fabiomnk** [comment]
I'm looking at the docs but seems that the only 2 configurations that are not present in my configuration are the following:
codec_type: HTTP2, i'll try to configure it in the envoyfilter
per_connection_buffer_limit_bytes: 1024 which should be defaulted to 1024.

speaking of buffers i tried to monitor this metrics  (envoy_cluster_upstream_cx_rx_bytes_buffered and envoy_cluster_upstream_cx_tx_bytes_buffered) for ingressgateway and application pod and see the following behaviour.

![image](https://user-images.githubusercontent.com/34380079/192558934-297bac80-7569-44ea-8cdf-550225967670.png)

as you can see in the logs the stream should have stopped at 14:27.xx , the graph shows the bytes buffered by the sidecar yet the stream doesn't stop.

**Comment by fabiomnk** [comment]
@alyssawilk any idea? we are kinda stuck on this, should we test to disable the buffer in some way in order to prove the point ? 
i can't seem to find the right configuration to configure the buffer for envoy.

**Comment by alyssawilk** [comment]
sorry for the lag I got side tracked by things.  @KBaichoo any chance you can help out with this one?

**Comment by fabiomnk** [comment]
Hi deep diving envoy metrics in order to find some clues, i noticed the following scenario:

we start streaming data (17:36), everything seems to work properly , the service is correctly receiving data from the client.

![image](https://user-images.githubusercontent.com/34380079/195889981-e792e4bc-eb7c-47cc-9a7a-f9783af659a5.png)

server.log 
Total Item Processed 49852
READ STREAM PAUSED
{"level":"warn","timestamp":"2022-10-14T15:48:45.831Z","TID":"ares-ingress-659676f6f-lq882-AresIngress-logger","service":"AresIngress","name":"logger","message":"Bulk Write to play:infinity:ingress Attempt 1 failed. There are 10 retries left."}

at 17:48 the server paused the stream in order to flow control,  the flow control message is not propagated to the client hence it continues to stream data.

From this point forward the server is not accepting data and we can see envoy memory consumption grow, if the client continue to stream envoy ends up OOM.

 @KBaichoo @alyssawilk

**Comment by KBaichoo** [comment]
Hi @fabiomnk can you provide the redacted Envoy config from the admin endpoint: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--config_dump ?

I'm not familiar with all the intermediary layers you're using on top, and it'd be good to see what the Envoy is actually running with. Thank you

**Comment by fabiomnk** [comment]
attached
ares-ingress is the server 
istio-ingressgateway-ares-fe is the Istio Gateway wich is exposing the service outside of the cluster.

Thanks for support.

[istio-ingressgateway-ares-fe-envoy-config-dump.json.txt](https://github.com/envoyproxy/envoy/files/9791550/istio-ingressgateway-ares-fe-envoy-config-dump.json.txt)
[ares-ingress-envoy-config-dump.json.txt](https://github.com/envoyproxy/envoy/files/9791551/ares-ingress-envoy-config-dump.json.txt)

**Comment by KBaichoo** [comment]
Thanks for providing the config. I think your intended configuration isn't reaching the Envoy, so you should look earlier at the pipe.

To be concrete, looking at your listener for the Envoy, I think you want to apply H2 protocol options to have sensible flow control. If we look at your static listeners from the Envoy's perspective:

```

"static_resources": {
        "listeners": [
         {
          "address": {
           "socket_address": {
            "address": "0.0.0.0",
            "port_value": 15090
           }
          },
          "filter_chains": [
           {
            "filters": [
             {
              "name": "envoy.filters.network.http_connection_manager",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
               "stat_prefix": "stats",
               "route_config": {
                "virtual_hosts": [
                 {
                  "name": "backend",
                  "domains": [
                   "*"
                  ],
                  "routes": [
                   {
                    "match": {
                     "prefix": "/stats/prometheus"
                    },
                    "route": {
                     "cluster": "prometheus_stats"
                    }
                   }
                  ]
                 }
                ]
               },
               "http_filters": [
                {
                 "name": "envoy.filters.http.router",
                 "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                 }
                }
               ]
              }
             }
            ]
           }
          ]
         },
         {
          "address": {
           "socket_address": {
            "address": "0.0.0.0",
            "port_value": 15021
           }
          },
          "filter_chains": [
           {
            "filters": [
             {
              "name": "envoy.filters.network.http_connection_manager",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
               "stat_prefix": "agent",
               "route_config": {
                "virtual_hosts": [
                 {
                  "name": "backend",
                  "domains": [
                   "*"
                  ],
                  "routes": [
                   {
                    "match": {
                     "prefix": "/healthz/ready"
                    },
                    "route": {
                     "cluster": "agent"
                    }
                   }
                  ]
                 }
                ]
               },
               "http_filters": [
                {
                 "name": "envoy.filters.http.router",
                 "typed_config": {
                  "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
                 }
                }
               ]
              }
             }
            ]
           }
          ]
         }
        ],
```

We don't see the protocol options for flow control you intended. If they were there they'd look similar to:

```
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          normalize_path: true
          merge_slashes: true
          path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
          common_http_protocol_options:
            idle_timeout: 3600s  # 1 hour
            headers_with_underscores_action: REJECT_REQUEST
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536  # 64 KiB
            initial_connection_window_size: 1048576  # 1 MiB

```

from https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge
