### ISSUE TITLE
envoy_apply_resources_failed  vhds: only 'DELTA_GRPC' is supported as an api_type

### ISSUE THREAD

**Issue by uglycow** [envoyproxy/envoy#23262]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *envoy_apply_resources_failed  vhds: only 'DELTA_GRPC' is supported as an api_type*

*Description*:
> First of all, we statically configured ads's API type as DELTA_GRPC.

```
dynamic_resources:
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
```

Then, we use rds to get RouteConfiguration with vhds configured. The vhds config_source is set to ads.
we expect the vhds would take effect, but envoy failed to apply it  and report error:

``` 
"2022-09-27 09:08:39.841623|WARN|-|1:0:203|-|server.go:819|-:xds.(*DiscoveryServer).shouldRespondDelta|-|envoy_apply_resources_failed|-:-|error_detail=code:13 message:\"vhds: only 'DELTA_GRPC' is supported as an api_type.\"
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
```
dynamic_resources:
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
```

```

            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                rds:
                  route_config_name: "outbound_route"
                  config_source:
                    ads: {}
                http_filters:
                  - name: envoy.on_demand
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
                      odcds:
                        source:
                          resource_api_version: V3
                          ads: {}
                        resources_locator:
                        timeout: 5s
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
