### ISSUE TITLE
How to hot restart the Envoy with docker-compose

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23300]
I'm using the Envoy as a gateway of my backend web services. I deployed the Envoy with the docker mode. I used the `docker-compose` to help me. Here is my `docker-compose.yml` file:
```
version: "3.5"

x-volumes-common: &volumes_common
  - "/etc/localtime:/etc/localtime:ro"
  - "/etc/timezone:/etc/timezone:ro"
  - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"

services:
  envoy:
    image: envoyproxy/envoy:v1.22-latest
    restart: "no"
    volumes: *volumes_common
    ports:
      - "9992:9992" # admin interface
      - "1444:1444"
```
Of source, I have a config file `envoy.yaml` too.

Now I can run the Envoy with the command `docker-compose up -d`.

However, I don't know how to hot restart my envoy. I knew that we had a python wrapper: https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter, which allows us to hot restart the Envoy but since I used the `docker-compose`, I kind of don't know how to hot restart my envoy.
