### ISSUE TITLE
error initializing configuration '/etc/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains) tls_context: Cannot find field.) has unknown fields

### ISSUE THREAD

**Issue by cheedallarajesh** [envoyproxy/envoy#23310]
*Title*: *filter_chains tls_context: Cannot find field*

*Description*:
>Hi, I am following [documentation ](https://aws.amazon.com/blogs/containers/maintaining-transport-layer-security-all-the-way-to-your-container-using-the-application-load-balancer-with-amazon-ecs-and-envoy/#:~:text=cat%20%3C%3CEOF%20%3E%20envoy.yaml) from AWS on setting up **envoy** as sidecar. 
I built docker image but when running the container, I ran into below error

>2022-09-28 20:22:21.662][7][critical][main] [source/server/server.cc:117] error initializing configuration '/etc/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains) tls_context: Cannot find field.) has unknown fields

>I am using latest envoy-dev docker image - **FROM envoyproxy/envoy-dev:latest**

>Here is the envoy.yaml config file 
```yaml
envoy.yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
      tls_context:
        common_tls_context:
          tls_certificates:
          - certificate_chain:
              filename: "/etc/ssl/my-aws-public.crt"
            private_key:
              filename: "/etc/ssl/my-aws-private.key"
      filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: local_service
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081

```

[*Relevant Links*:]
>Following envoy setup as sidecar documentation from AWS.
>https://aws.amazon.com/blogs/containers/maintaining-transport-layer-security-all-the-way-to-your-container-using-the-application-load-balancer-with-amazon-ecs-and-envoy/#:~:text=cat%20%3C%3CEOF%20%3E%20envoy.yaml
