### ISSUE TITLE
improved runtime guard checks

### ISSUE THREAD

**Issue by alyssawilk** [envoyproxy/envoy#23348]
right now runtime guard checks appear to only work if the guard is mentioned in the first change.  If one adds envoy.reloadable_features.foo

```yaml
area: http
  change: |
    changed implemented something guarded by  ``envoy.reloadable_features.foo`` 
```

will pass but

```yaml
area: http
  change: |
    preexisting feature
  change: |
    changed implemented something guarded by  ``envoy.reloadable_features.foo`` 
```

appears to fail
