### ISSUE TITLE
How actually proxy works

### ISSUE THREAD

**Issue by 3g0r** [envoyproxy/envoy#23355]
How actually proxy works: what is mean in real downstream/upstream tx/rx byte total/buffered metrics.

Hi foks.
I have a simple TCP LB configuration:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
stats_sinks:
  - name: envoy.stat_sinks.statsd
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.StatsdSink
      tcp_cluster_name: statsd
static_resources:
  listeners:
    - name: listener_0
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tcp_stats
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tcp_stats.v3.Config
              transport_socket:
                name: envoy.transport_sockets.raw_buffer
          filters:
            - name: envoy.filters.network.tcp_proxy.v3.TcpProxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: ingest
                cluster: ingest
                idle_timeout: 0s
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  clusters:
    - name: statsd
      connect_timeout: 0.25s
      type: STRICT_DNS
      load_assignment:
        cluster_name: statsd
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: statsd
                      port_value: 9125
    - name: ingest
      per_connection_buffer_limit_bytes: 32768 # 32 KiB
      connect_timeout: 0.25s
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: LEAST_REQUEST
      transport_socket:
        name: envoy.transport_sockets.tcp_stats
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tcp_stats.v3.Config
          transport_socket:
            name: envoy.transport_sockets.raw_buffer
      load_assignment:
        cluster_name: ingest
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: ingest-1
                      port_value: 80
              - endpoint:
                  address:
                    socket_address:
                      address: ingest-2
                      port_value: 80
              - endpoint:
                  address:
                    socket_address:
                      address: ingest-3
                      port_value: 80
```

But I don't understand how it is works in real.
I thought that when envoy received a connection it is read some bytes to downstream_buffer and increase `downstream_rx_byte_total` `downstream_rx_byte_buffered` metrics. After downstream_buffer is full (or incoming stream end) it move data to upstream_buffer and increase `upstream_tx_byte_buffered` metrics, and then flush data to upstream socket and also increase `upstream_rx_byte_total`.

However saw the big difference when I tried to compare that: 
`downstream_rx_byte_total - upstream_rx_byte_total`
`downstream_rx_byte_buffered - upstream_tx_byte_buffered`

Moreover `upstream_tx_byte_buffered` very less than `upstream_rx_byte_total`.

It turns out that I thought about it wrong.
I tried to read the source code for clarifying, but that's a lot.
Please help me understand.
