### ISSUE TITLE
ext_authz with HTTP uses path from request

### ISSUE THREAD

**Issue by aemaem** [envoyproxy/envoy#23360]
*Title*: *ext_authz with HTTP uses path from request instead of URI*

*Description*:
When configuring envoy to use an external auth service to authenticate requests, the URI of the configured auth service is ignored. Instead the path of the incoming request is also used for the auth service request.

*Repro steps*:

1. `docker compose build`
2. `docker compose up`
3. `curl -i -L localhost:8080/` -> OK `{"title":"The index page"}`
4. `curl -i -L localhost:8080/lenny` -> NOT_FOUND `{"detail":"Not Found"}`

Follow the steps in the example repo: https://github.com/aemaem/envoy-proxy-ext-auth-sample

*Admin and Stats Output*:
[admin-stats.txt](https://github.com/envoyproxy/envoy/files/9704562/admin-stats.txt)
[admin-clusters.txt](https://github.com/envoyproxy/envoy/files/9704564/admin-clusters.txt)
[admin-serverinfo.txt](https://github.com/envoyproxy/envoy/files/9704569/admin-serverinfo.txt)

*Config*:
```yaml
admin:
  access_log:
    name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8888
static_resources:
  listeners:
    - name: sample
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: service
                  virtual_hosts:
                    - name: service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: sample-service
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      http_service:
                        server_uri:
                          uri: http://auth-service:8080/authenticate
                          cluster: auth-service
                          timeout: 5s
                        authorization_response:
                          allowed_upstream_headers:
                            patterns:
                              - exact: x-current-user
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: sample-service
      connect_timeout: 10s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: sample-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: sample-service
                      port_value: 8080
    - name: auth-service
      connect_timeout: 10s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: auth-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: auth-service
                      port_value: 8080
```

*Logs*:

_auth-service_
INFO:     172.23.0.4:50136 - "GET / HTTP/1.1" 200 OK
INFO:     172.23.0.4:54662 - "GET /lenny HTTP/1.1" 404 Not Found

_sample-service_
INFO:     172.23.0.4:38562 - "GET / HTTP/1.1" 200 OK
