### ISSUE TITLE
Envoy doesn't forward important TLV header by ProxyProtocol v2

### ISSUE THREAD

**Issue by adam-prohack** [envoyproxy/envoy#23413]
*Title*: Envoy doesn't forward important TLV header by ProxyProtocol v2

*Description*:
I have a problem with Proxy Protocol 2 and the Envoy connected as part of ProxyProtocol v2 proxies/load balancers chain. In my solution architecture, I have connected in series some network proxies and load balancers. Incoming traffic is moved by AWS NLB in TCP mode (without TLS termination), to HAProxy where TLS is terminated and this proxy checks the Client Certificate (mTLS). Finally, traffic from this HAProxy is forwarded with proxy protocol v2 to Envoy instance and next to my application. HAProxy instance set PP2_SUBTYPE_SSL_CN TLV record which is read by my application when it is connected directly to this proxy. Unfortunately, my application couldn't terminate TLS, and to ensure end-to-end encryption I need to have an Envoy instance as a sidecar on the machine (container) where my application is run. Sidecar Envoy doesn't forward PP2_SUBTYPE_SSL_CN TLV record received from HAProxy to my application and I am not able to read the source client certificate CN.

*Repro steps*:
1. You need to install HAProxy with enabled proxy protocol v2 on backend. Configure TLS termination and mTLS authorization on this instance.
2. Install Envoy with enabled proxy protocol v2 on listener and backend. Configure only TLS termination e.q. with self signed certificate
3. Set up HAProxy instance backend to forward traffic to Envoy
4. Connect Envoy instance backend to application which require PP2_SUBTYPE_SSL_CN TLV record like VerneMQ MQTT broker.

*Config*:
```
static_resources:
  listeners:
    - name: listener_http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18888
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/etc/envoy/ssl/envoy-crt.pem"
                    private_key:
                      filename: "/etc/envoy/ssl/envoy-key.pem"
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: destination
                cluster: cluster_http
    - name: listener_mqtt
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 11883
      listener_filters:
        - name: envoy.filters.listener.proxy_protocol
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
            allow_requests_without_proxy_protocol: false
            rules:
              - tlv_type: 0x22
                on_tlv_present:
                  key: "PP2_SUBTYPE_SSL_CN"
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/etc/envoy/ssl/envoy-crt.pem"
                    private_key:
                      filename: "/etc/envoy/ssl/envoy-key.pem"
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: destination
                cluster: cluster_mqtt
  clusters:
    - name: cluster_http
      connect_timeout: 10s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: cluster_http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8888
                      protocol: TCP
    - name: cluster_mqtt
      connect_timeout: 10s
      type: STATIC
      lb_policy: ROUND_ROBIN
      transport_socket:
        name: envoy.transport_sockets.upstream_proxy_protocol
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
          config:
            version: V2
          transport_socket:
            name: envoy.transport_sockets.raw_buffer
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
      load_assignment:
        cluster_name: cluster_mqtt
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 1883
                      protocol: TCP
```
