### ISSUE TITLE
widcard route do not works when used non-standard port

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#23416]
*Title*: *route: add wildcard support for non-standard port*

*Description*:
I need to route the request to a host with a non-standard port. In my case to port 5060
```yaml
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*.example.com:5060"
```
To cover all non-standard ports in need use forms like
```yaml
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*.example.com:*"
```
Could you extend domain matcher rules to cover wildcards in the non-standard port and hostname like `*.example.com:*`

**Comment by wbpcode** [comment]
May strip_matching_host_port could solve your problem?

```
strip_matching_host_port
([bool](https://developers.google.com/protocol-buffers/docs/proto#scalar)) Determines if the port part should be removed from host/authority header before any processing of request by HTTP filters or routing. The port would be removed only if it is equal to the [listener’s](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-address) local port. This affects the upstream host header unless the method is CONNECT in which case if no filter adds a port the original port will be restored before headers are sent upstream. Without setting this option, incoming requests with host example:443 will not match against route with [domains](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-virtualhost-domains) match set to example. Defaults to false. Note that port removal is not part of [HTTP spec](https://tools.ietf.org/html/rfc3986) and is provided for convenience. Only one of strip_matching_host_port or strip_any_host_port can be set.
```

Check more info:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#strip_matching_host_port

**Comment by sergey-safarov** [comment]
For me look like the bug is there.
How I have tested.
I have modified the [forward-proxy config](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter#config-http-filters-dynamic-forward-proxy)
On my server, it looks like
```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 13128
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          strip_matching_host_port: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "sbc-a0.nga911.com"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: dynamic_forward_proxy_cluster
            request_headers_to_remove:
            - x-forwarded-proto
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                    resolvers:
                    - socket_address:
                        address: "8.8.8.8"
                        port_value: 53
                    dns_resolver_options:
                      use_tcp_for_dns_lookups: false
                      no_default_search_domain: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: false
                no_default_search_domain: true
```

Here I have added
```
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          strip_matching_host_port: true
```
With config file above envoy produce this logs
```
[2022-10-16 06:56:50.039][27450][debug][main] [source/server/server.cc:251] flushing stats
[2022-10-16 06:56:50.529][27457][debug][conn_handler] [source/server/active_tcp_listener.cc:147] [C0] new connection from 192.168.88.213:47252
[2022-10-16 06:56:50.534][27457][debug][http] [source/common/http/conn_manager_impl.cc:306] [C0] new stream
[2022-10-16 06:56:50.535][27457][debug][http] [source/common/http/conn_manager_impl.cc:921] [C0][S15631029926687872752] request headers complete (end_stream=true):
':authority', 'sbc-a0.nga911.com:5060'
':scheme', 'http'
':path', '/up'
':method', 'GET'
'user-agent', 'curl/7.71.1'
'accept', '*/*'
'proxy-connection', 'Keep-Alive'

[2022-10-16 06:56:50.536][27457][debug][http] [source/common/http/conn_manager_impl.cc:904] [C0][S15631029926687872752] request end stream
[2022-10-16 06:56:50.536][27457][debug][connection] [./source/common/network/connection_impl.h:92] [C0] current connecting state: false
[2022-10-16 06:56:50.537][27457][debug][router] [source/common/router/router.cc:400] [C0][S15631029926687872752] no route match for URL '/up'
[2022-10-16 06:56:50.537][27457][debug][http] [source/common/http/filter_manager.cc:905] [C0][S15631029926687872752] Sending local reply with details route_not_found
[2022-10-16 06:56:50.538][27457][debug][http] [source/common/http/conn_manager_impl.cc:1542] [C0][S15631029926687872752] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Sun, 16 Oct 2022 06:56:50 GMT'
'server', 'envoy'

[2022-10-16 06:56:50.543][27457][debug][connection] [source/common/network/connection_impl.cc:651] [C0] remote close
[2022-10-16 06:56:50.543][27457][debug][connection] [source/common/network/connection_impl.cc:250] [C0] closing socket: 0
[2022-10-16 06:56:50.543][27457][debug][conn_handler] [source/server/active_stream_listener_base.cc:120] [C0] adding to cleanup list
```
