### ISSUE TITLE
hot-restart killed the envoy container

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23412]
I used `docker-compose` to start a docker container of Envoy.
Here is my `docker-compose.yml`:
```
version: "3.5"

x-volumes-common: &volumes_common
  - "./envoy.yaml:/etc/envoy/envoy.yaml:ro"

x-meta-info: &meta_info
    image: envoyproxy/envoy:v1.22-latest
    container_name: envoy_gw
    restart: "no"
    volumes: *volumes_common

services:
  envoy:
    <<: *meta_info
    ports:
      - "5004:5004" # admin interface
      - "1443:1443"
```
I can execute `docker-compose up -d` to start it, it works as expected.

Now I'm trying to hot-restart the Envoy process inside of the docker container. So I executed the command: `docker exec -it envoy_gw envoy -c /etc/envoy/envoy.yaml --parent-shutdown-time-s 8 --restart-epoch 1`.

However, this command killed/stopped the container. I don't know why... I'm not a docker expert so I don't know if this is some docker feature/issue.

Besides, I don't think `docker-compose restart` is what I need because as my understanding, restarting the container can't benefit from the mechanism of "Envoy can fully reload itself (both code and configuration) without dropping existing connections during the drain process" (https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart).

Am I right about `docker-compose restart`? If I'm right, what is the proper method to hot-restart a envoy process inside a docker container?
