### ISSUE TITLE
The envoy doesn't pickup the newly updated config file

### ISSUE THREAD

**Issue by alphamarket** [envoyproxy/envoy#23433]
We are trying to update our envoy configuration once per minute (if there are any new updates) but after updating the new configuration it seems like the envoy doesn't pick up the changes, there is this [hot restart](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/operations/hot_restart) document but as I understood it the envoy should be able to pick up the changes automatically, how we can accomplish a reload in the envoy?

This is how we launch the envoy:

```bash
/usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```

**Comment by alphamarket** [comment]
Our envoy version: `envoyproxy/envoy:v1.23-latest`

**Comment by dio** [comment]
@alphamarket you need to send a signal (SIGHUP) to the hot restarter script (https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter.html?highlight=sighup), or alternatively, you can start Envoy with dynamic configuration by using files that implement the [xDS](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#xds-protocol) protocol. 
https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-dynamic-filesystem

**Comment by alphamarket** [comment]
@dio Thanks for the response, but using xDS protocol didn't help and still new configs are not getting loaded, here is my configuration:

```yaml
# /etc/envoy/envoy.yaml
node:
  cluster: envoy-cluster
  id: 3921a62b-e522-42d7-88d7-1cbbcbfacbd2

dynamic_resources:
  lds_config:
    path: /etc/envoy/envoy-lds.yaml

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

static_resources:
  ################################################################################
  # Clusters
  ################################################################################
  clusters:

  # Cluster: component
  - name: component_cluster
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: component_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: tracker
                port_value: 80
```

```yaml
# /etc/envoy/envoy-lds.yaml
{% set yaml = imp('yaml') %}
resources:
################################################################################
# HTTP listeners
################################################################################
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 80
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        http_protocol_options:
          accept_http_10: true
        stat_prefix: ingress_http
        use_remote_address: true
        xff_num_trusted_hops: 0
        access_log:
        - name: envoy.access_loggers.stdout
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: services_route
          virtual_hosts:
          {% for site in http_sites %}
          # {{ site["domain"] }}
          - name: {{ site["domain"] }}
            domains: ["{{ site["domain"] }}"]
            routes:
            - match: { prefix: "/" }
              {% if site["meta"]["routes.redirect"] %}
              redirect:
                {% for line in yaml.dump(site["meta"]["routes.redirect"]).split("\n") %}{% if line %}{{ line }}{% endif %}
                {% endfor %}
              {% else %}
              route: { cluster: {{ site["cluster"] }}_cluster }
              {% endif %}
          {% endfor %}
################################################################################
# HTTPS listeners
################################################################################
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: https_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  listener_filters:
  - name: "envoy.filters.listener.tls_inspector"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  filter_chains:
  {% for site in https_sites %}
  # {{ site["domain"] }}
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        http_protocol_options:
          accept_http_10: true
        stat_prefix: ingress_http
        use_remote_address: true
        xff_num_trusted_hops: 0
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: {{ site["domain"] }}
          virtual_hosts:
          - name: {{ site["domain"] }}
            domains: ["*"]
            routes:
            - match: { prefix: "/" }
              {% if site["meta"]["routes.redirect"] %}
              redirect:
                {% for line in yaml.dump(site["meta"]["routes.redirect"]).split("\n") %}{% if line %}{{ line }}{% endif %}
                {% endfor %}
              {% else %}
              route: { cluster: {{ site["cluster"] }}_cluster }
              {% endif %}
    filter_chain_match:
      server_names: ["{{ site["domain"] }}"]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: { filename: {{ site["cert"] }} }
            private_key: { filename: {{ site["key"] }} }
  {% endfor %}
```
The `envoy-lds.yaml` is being generated by a script that we generate it by [jinja](https://jinja.palletsprojects.com/en/3.1.x/). can you see something that I don't see, what am I doing wrong here?

I tried to load the clusters as static resources because using CDS, the envoy keeps complaining about:

```bash
[2022-10-11 12:37:00.721][164][warning][config] [source/common/config/filesystem_subscription_impl.cc:60] Filesystem config update rejected: Error adding/updating listener(s) http_listener: route: unknown cluster 'component_cluster'
```

**PS:** The **node**'s values are constant in `/etc/envoy/envoy.yaml`.

**Comment by wbpcode** [comment]
Hi, could you provide a complete config yaml and lds yaml?

**Comment by alphamarket** [comment]
This is the compiled version of the LDS yaml configuration:

```yaml
# /etc/envoy/envoy-lds.yaml
resources:
################################################################################
# HTTP listeners
################################################################################
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 80
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        http_protocol_options:
          accept_http_10: true
        stat_prefix: ingress_http
        use_remote_address: true
        xff_num_trusted_hops: 0
        access_log:
        - name: envoy.access_loggers.stdout
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: services_route
          virtual_hosts:
              
          
          # example1.com
          - name: example1.com
            domains: ["example1.com"]
            routes:
            - match: { prefix: "/" }
              
              route: { cluster: component_cluster }
              
          
          # example2.com
          - name: example2.com
            domains: ["example2.com"]
            routes:
            - match: { prefix: "/" }
              
              route: { cluster: component_cluster }
              
          
################################################################################
# HTTPS listeners
################################################################################
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: https_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 443
  listener_filters:
  - name: "envoy.filters.listener.tls_inspector"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  filter_chains:
  
  # example1.com
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        http_protocol_options:
          accept_http_10: true
        stat_prefix: ingress_http
        use_remote_address: true
        xff_num_trusted_hops: 0
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: example1.com
          virtual_hosts:
          - name: example1.com
            domains: ["*"]
            routes:
            - match: { prefix: "/" }
              
              route: { cluster: component_cluster }
              
    filter_chain_match:
      server_names: ["example1.com"]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: { filename: /etc/ssl/certs/example1.com.cert.pem }
            private_key: { filename: /etc/ssl/certs/example1.com.key.pem }
  
  # example2.com
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        http_protocol_options:
          accept_http_10: true
        stat_prefix: ingress_http
        use_remote_address: true
        xff_num_trusted_hops: 0
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: example2.com
          virtual_hosts:
          - name: example2.com
            domains: ["*"]
            routes:
            - match: { prefix: "/" }
              
              route: { cluster: component_cluster }
              
    filter_chain_match:
      server_names: ["example2.com"]
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: { filename: /etc/ssl/certs/example2.com.cert.pem }
            private_key: { filename: /etc/ssl/certs/example2.com.key.pem }
```

**Comment by alphamarket** [comment]
Complete config yaml file (which already posted before):

```yaml
# /etc/envoy/envoy.yaml
node:
  cluster: envoy-cluster
  id: 3921a62b-e522-42d7-88d7-1cbbcbfacbd2

dynamic_resources:
  lds_config:
    path: /etc/envoy/envoy-lds.yaml

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

static_resources:
  ################################################################################
  # Clusters
  ################################################################################
  clusters:

  # Cluster: component
  - name: component_cluster
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: component_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: tracker
                port_value: 80
```
