### ISSUE TITLE
bad header key (http/1.1 protocol error HPE_INVALID_HEADER_TOKEN) from internal redirect resulting in HTTP 502

### ISSUE THREAD

**Issue by vindiagram** [envoyproxy/envoy#23461]
*Title*:
Sites with CDN: Imperva result in HPE_INVALID_HEADER_TOKEN errors when processing internal redirects returning 502 to client.

*Description*:
I have a client using envoy as an egress proxy behind a corporate proxy to communicate with a 3rd party REST endpoint (I cannot provided).
This site is using Imperva which provides an invalid header in a HTTP 1.1 response. Specifically this response is a 302 with cookies that must be brought in the next response. From what I can find Browser have no problem resolving this request directly as they will just drop the invalid headers.
But the node js http_parser in envoy is failing to process the 302 response and throwing an HPE_INVALID_HEADER_TOKEN, it then stops processing the request and instead returns a 502 back to the requesting client.
I have attempted to add in `envoy_on_request` and  `envoy_on_response` lua functions to capture the 302 to parse out and drop the invalid headers, but the requests from the `internal_redirect_policy` never make it to these http_filter calls.

Is there a way for me to configure envoy to drop these invalid headers or be more lenient in their processing.
This issue has been mentioned alot for the nodejs https_parser library, is there a similar configuration possible to change its logic for how it handles these malformed headers?

*Repro steps*:
Envoy version `1.21-latest`
Curl Traffic directly to site: 
```
curl -v -s -x "http://<corporate proxy>:<corporate proxy port>" -H "X-token: <api token>" https://<api endpoint>
*   Trying 134.223.121.43...
* TCP_NODELAY set
* Connected to <corporate proxy> (<corporate proxy ip>) port <corporate proxy port>(#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to <api>:443
> CONNECT <api>:443 HTTP/1.1
> Host: <api>:443
> User-Agent: curl/7.61.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Wed, 12 Oct 2022 16:44:04 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 LEPPSW11
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=imperva.com
*  start date: Jul 15 04:03:10 2022 GMT
*  expire date: Jan 11 04:03:10 2023 GMT
*  subjectAltName: host "<api>" matched cert's "*.example.com"
*  issuer: C=BE; O=GlobalSign nv-sa; CN=GlobalSign Atlas R3 DV TLS CA 2022 Q3
*  SSL certificate verify ok.
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /path HTTP/1.1
> Host: <api>
> User-Agent: curl/7.61.1
> Accept: */*
> X-token: <api token>
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/1.1 200 OK
< Date: Wed, 12 Oct 2022 16:44:04 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 36581
< Connection: keep-alive
< Keep-Alive: timeout=10
< Vary: Accept-Encoding
< X-Classification:
< Vary: Origin, Accept-Encoding
< Access-Control-Allow-Credentials: true
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< ETag: W/"8ee5-RV8DhFFzVWA112ajhc87wBnOSfg"
< Strict-Transport-Security: max-age=7200
< Set-Cookie: visid_incap_2734334=650fcJVFSli0iqMCSTY9PdTuRmMAAAAAQUIPAAAAAACg4iKPvZU8gLvh8ZQvZcOz; expires=Thu, 12 Oct 2023 06:16:41 GMT; HttpOnly; path=/; Domain=.example.com
< Set-Cookie: incap_ses_1604_2734334=FxSUBp8tPVoj9+a2rI1CFtTuRmMAAAAAxzHeO+i6ACvfLd2s85U+aA==; path=/; Domain=.example.com
< Set-Cookie: ___utmvmImBuMVEsZ=wjTHYFiJBQD; path=/; Max-Age=900
< Set-Cookie: ___utmvaImBuMVEsZ=ZuOzlrX; path=/; Max-Age=900
< Set-Cookie: ___utmvbImBuMVEsZ=VZD
<     XYCOqalK: Qtp; path=/; Max-Age=900
< X-CDN: Imperva
< X-Iinfo: 17-355692915-355690911 PNNN RT(1665593044410 97) q(0 0 0 -1) r(0 0) U2
<
```
Config:
```
static_resources:
listeners:
    - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          upgrade_configs:
          - upgrade_type: websocket
          http2_protocol_options:
            allow_connect: true
          route_config:
            virtual_hosts:
            - name: uvds_routing
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: <rest endpoint>
                  cluster: loopback
                  timeout: 0s
                  idle_timeout: 300s
                  internal_redirect_policy:
                    redirect_response_codes: [302]
                    allow_cross_scheme_redirect: true
                    max_internal_redirects: 20
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
  - name: api_listener
    address:
      pipe:
        path: "@/cluster_0"
    filter_chains:
      - filters:
          - name: tcp
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp_stats
              cluster: "outbound_proxy"
              tunneling_config:
                hostname: <rest endpoint>:443
  clusters:
  - name: outbound_proxy
    connect_timeout: 60s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: outbound_proxy
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: <corporate proxy>
                    port_value: <corporate proxy port>
  - name: loopback
    connect_timeout: 5s
    upstream_connection_options:
      tcp_keepalive: {}
    type: STATIC
    load_assignment:
      cluster_name: loopback
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: "@/cluster_0"
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
*Logs*:
```
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:605] [C5] parsing 3569 bytes
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:891] [C5] message begin
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Date value=Wed, 12 Oct 2022 16:19:11 GMT
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Content-Type value=text/html
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Content-Length value=2763
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Connection value=keep-alive
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Keep-Alive value=timeout=10
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=ETag value="633c3be9-acb"
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Set-Cookie value=visid_incap_2734334=M0HG943XR2maZ3k16yaDU27qRmMAAAAAQUIPAAAAAAD9U/OdCAH7oH34XPbD3m9n; expires=Thu, 12 Oct 2023 06:17:22 GMT; HttpOnly; path=/; Domain=.example.com
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Set-Cookie value=incap_ses_1604_2734334=85wDV3B7/Fmm6OO2rI1CFm7qRmMAAAAAjxLbnbFaZ6xJZOsS6dyDiw==; path=/; Domain=.example.com
[2022-10-12 16:25:18.463][32][trace][http] [source/common/http/http1/codec_impl.cc:518] [C5] completed header: key=Set-Cookie value=___utmvmImBuMVEsZ=LFqWFPgKFWZ; path=/; Max-Age=900
[2022-10-12 16:25:18.463][32][debug][client] [source/common/http/codec_client.cc:154] [C5] Error dispatching received data: http/1.1 protocol error: HPE_INVALID_HEADER_TOKEN
[2022-10-12 16:25:18.463][32][debug][connection] [source/common/network/connection_impl.cc:138] [C5] closing data_to_write=0 type=1
[2022-10-12 16:25:18.463][32][debug][connection] [source/common/network/connection_impl.cc:249] [C5] closing socket: 1
[2022-10-12 16:25:18.463][32][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:312] [C5] SSL shutdown: rc=0
```
