### ISSUE TITLE
How to set `localEndpoint.serviceName` in Zipkin tracer

### ISSUE THREAD

**Issue by jeffalder** [envoyproxy/envoy#23475]
How do I set the `localEndpoint.serviceName` field in the Zipkin tracer?

*Description*:
Repro: https://github.com/jeffalder/envoy-servicename-repro

I am working to configure Envoy to send spans to the New Relic Trace API, which [accepts Zipkin-formatted spans](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api). I am able to capture the spans with Zipkin, and I am able to send them to the New Relic Trace API. 

My setup is:
* I have a docker-compose with Envoy 1.22 and [httpbin](httpbin.org).
* I have a mitmproxy running. Envoy is configured to send traces to mitmproxy. mitmproxy will dump the contents to the log, then forward the request to httpbin. httpbin will just reply with a 200 so that Envoy thinks it was successful.

The Zipkin spans as produced by Envoy look like this:

```json
        {
            "annotations": [
                {
                    "timestamp": 1665672989469640,
                    "value": "ss"
                }
            ],
            "duration": 100984,
            "id": "654ffe44b877213b",
            "kind": "SERVER",
            "localEndpoint": {
                "ipv4": "172.18.0.3",
                "port": 0
            },
            "name": "mylocalhost:7572",
            "shared": true,
            "tags": {
                "component": "proxy",
                "downstream_cluster": "-",
                "guid:x-request-id": "d15797ea-9666-92b6-8e13-a5e74f36f5a4",
                "http.method": "GET",
                "http.protocol": "HTTP/1.1",
                "http.status_code": "200",
                "http.url": "https://backend/get",
                "peer.address": "172.18.0.1",
                "request_size": "0",
                "response_flags": "-",
                "response_size": "2199",
                "upstream_cluster": "backend_cluster",
                "upstream_cluster.name": "backend_cluster",
                "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0"
            },
            "timestamp": 1665672989368083,
            "traceId": "6cd9a397fab3b11a654ffe44b877213b"
        }
```

My spans are rejected by New Relic because the `localEndpoint.serviceName` field is not set ([docs](https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-zipkin-format-traces-trace-api/#zipkin-transform)). (I also notice that the port is 0, which is strange.) 

It should be set (per [the code](https://github.com/envoyproxy/envoy/blob/0fae6970ddaf93f024908ba304bbd2b34e997a51/source/extensions/tracers/zipkin/span_buffer.cc#L301-L304)) but I can't figure out how. In my envoy yaml, I've configured names for everything I could find that seemed marginally relevant: the listener, route config, virtual host, route, cluster, etc.

🤞 that this is just some configuration I'm missing.

tracing section (subset of [envoy.yaml](https://github.com/jeffalder/envoy-servicename-repro/blob/main/envoy.yaml#L26-L36))
```
static_resources:
  ....
  listeners:
    - name: proxy_listener
       ....
       filter_chains:
       - filters:
         - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              tracing:
                custom_tags:
                  - tag: "service.name"
                    literal:
                      value: "alder-local-envoy"
                provider:
                  name: envoy.tracers.zipkin
                  typed_config:
                    "@type": type.googleapis.com/envoy.config.trace.v3.ZipkinConfig
                    collector_cluster: zipkin
                    trace_id_128bit: true
                    collector_endpoint: "/trace/v1"
                    collector_endpoint_version: HTTP_JSON
                    collector_hostname: "trace-api.newrelic.com"
```

The zipkin and backend clusters are nothing special (and the clusters aren't the problem, I don't think).
