### ISSUE TITLE
Can you still pass response headers (such as CORS headers) from Authentication Server when ExtAuth fails?

### ISSUE THREAD

**Issue by miyamotokenji** [envoyproxy/envoy#23473]
*Title*: *Can you still pass response headers (such as CORS headers) from Authentication Server when ExtAuth fails?*

*Description*:
>When the ext_auth fails the response doesn't return the appropriate CORS headers from the auth server resulting in the browser raising a CORS error when in reality its a session error.

Here's part of my configuration

```          
http_filters:
  - name: envoy.cors
    typed_config: {}
  - name: envoy.ext_authz
    config:
      with_request_body:
        max_request_bytes: 90000000
        allow_partial_message: true
      http_service:
        authorization_request:
          allowed_headers:
            patterns:
            - exact: cookie
            - exact: x-auth-apikey
            - exact: x-auth-nonce
            - exact: x-auth-signature
            - exact: x-csrf-token
            - exact: user-agent
            - exact: x-forwarded-host
            - exact: x-forwarded-for
            - exact: from
            - exact: x-forwarded-proto
            - exact: proxy-authorization
        authorization_response:
          allowed_upstream_headers:
            patterns:
            - exact: authorization
          allowed_client_headers:
            patterns:
            - exact: set-cookie
            - exact: proxy-authenticate
            - exact: www-authenticate
            - exact: location
            - exact: access-control-allow-origin
        path_prefix: "/api/auth"
        server_uri:
          cluster: authservice
          timeout: 1.000s
          uri: http://authservice:8001
```
