### ISSUE TITLE
Is there any way to set multiple 'transport_socket' to one 'cluster'?

### ISSUE THREAD

**Issue by wywanlv** [envoyproxy/envoy#23516]
In [[config.cluster.v3.Cluster proto]](https://github.com/envoyproxy/envoy/blob/adf97d39fbbf64b24a3b143a5dc4a159a1cfc196/api/envoy/config/cluster/v3/cluster.proto#L47) , one "cluster" can have one "transport_socket" struct.

In my project, "Proxy-Protocol" and "TLS" are both important feature to one upstream cluster.
``` 
 cluster:  
    transport_socket:
      name: envoy.transport_sockets.upstream_proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
        config:
          version: V1
        transport_socket:
          name: envoy.transport_sockets.raw_buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
```
```
cluster:
 transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: SOME-PATH
```

It seems that one "cluster" can only support one "transport_socket", but I think some "transport_sockets" are not incompatible. Just link TLS and Proxy-Protocol, the connection can be established via TLS, and then send message encrypted in Proxy-Protocol.

Is there any way to config TLS and Proxy-Protocol "transport_socket" feature to one upstream cluster at same time?

Thanks for help : )

**Comment by pxpnetworks** [comment]
check this out -> [transport_socket_matches](https://www.envoyproxy.io/docs/envoy/v1.23.1/api-v3/config/cluster/v3/cluster.proto.html?highlight=transport_socket_matches)

BR,
Stoyan

**Comment by wywanlv** [comment]
> check this out -> [transport_socket_matches](https://www.envoyproxy.io/docs/envoy/v1.23.1/api-v3/config/cluster/v3/cluster.proto.html?highlight=transport_socket_matches)
> 
> BR, Stoyan

Thanks for replying. I have tried but it seems not work. "transport_socket_matches" configuration can use different transport sockets for different endpoints, but only one transport_socket configuration works at one time.


```
cluster:
    transport_socket_matches:
    - name: "tls"
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            validation_context:
              trusted_ca:
                filename: /data/flowcontrol/adc-proxy-certs/adc-proxy-ca.crt
    - name: "proxy-protocol"
      transport_socket:
        name: envoy.transport_sockets.upstream_proxy_protocol
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
          config:
            version: V1
          transport_socket:
            name: envoy.transport_sockets.raw_buffer
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
```
I use tcpdump to inspect TCP packets, it seems only "tls" can work, and "proxy-protcol" not work.
