### ISSUE TITLE
High memory usage on AMD EPYC machines

### ISSUE THREAD

**Issue by andreas-ahman** [envoyproxy/envoy#23533]
*Title*: *High memory consumption on AMD EPYC*

*Description*:
>When running on AMD EPYC multicore servers we see several times higher memory consumption compared to Intel.
>
>Opening issue after discussion on Slack. [https://envoyproxy.slack.com/archives/C78M4KW76/p1665045739195159](https://envoyproxy.slack.com/archives/C78M4KW76/p1665045739195159)

*Repro steps*:
> Deploy Envoy on AMD EPYC server with basic config and put load on the server. Accessing the metrics endpoint for admin is enough.

*Config*:
```
admin:`
  access_log_path: admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite_literal: myapp, cluster: myapp_cluster, timeout: 60s }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: myapp_cluster
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: myapp_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: myapp
                port_value: 8080
```

*Findings:*
We're experiencing some strange behaviours of Envoy when running high core CPUs
With a very basic Envoy configuration we're seeing these figures.
The reported number of cores is with Hyper-Threading and SMT enabled. I.e. /2 physical cores

Idle:
> 32 cores (AMD EPYC) ~20MiB
> 128 cores (AMD EPYC) ~42MiB
> 16 cores (Intel Xeon) ~20MiB

After load:
> 32 cores (AMD EPYC) ~76MiB
> 128 cores (AMD EPYC) ~180MiB
> 16 cores (Intel Xeon) ~43MiB

*With TCMalloc:*
```
These are the results running on AMD EPYC with TCMalloc. Sent the same amount of requests to both envoy instances.
AMD EPYC 32 cores
-----------------------
# TYPE envoy_server_memory_allocated gauge
envoy_server_memory_allocated{} 15464480
# TYPE envoy_server_memory_heap_size gauge
envoy_server_memory_heap_size{} 73400320
# TYPE envoy_server_memory_physical_size gauge
envoy_server_memory_physical_size{} 85748650

AMD EPYC 128 cores
-------------------
# TYPE envoy_server_memory_allocated gauge
envoy_server_memory_allocated{} 16154224
# TYPE envoy_server_memory_heap_size gauge
envoy_server_memory_heap_size{} 157286400
# TYPE envoy_server_memory_physical_size gauge
envoy_server_memory_physical_size{} 186248106
```

*With gperftools:*
```
These are results when running Envoy built with gperftools instead of tcmalloc.
I've sent roughly the same amount of requests to these deployments as the tcmalloc envoys.
A big difference is that with gperftools it "jumps" up to ca 50MiB and then stays there but with tcmalloc it continues to increase as the requests comes in.
I'm running k6 with 1000 vus for 10 minutes

AMD EPYC 32 cores - gperftools
-----------------------
# TYPE envoy_server_memory_allocated gauge
envoy_server_memory_allocated{} 15720816
# TYPE envoy_server_memory_heap_size gauge
envoy_server_memory_heap_size{} 44040192
# TYPE envoy_server_memory_physical_size gauge
envoy_server_memory_physical_size{} 46792704

AMD EPYC 128 cores - gperftools
-----------------------
# TYPE envoy_server_memory_allocated gauge
envoy_server_memory_allocated{} 15726976
# TYPE envoy_server_memory_heap_size gauge
envoy_server_memory_heap_size{} 42991616
# TYPE envoy_server_memory_physical_size gauge
envoy_server_memory_physical_size{} 45744128
```
