### ISSUE TITLE
Custom `x-b3-traceid` header created via Lua filter gets overwritten.

### ISSUE THREAD

**Issue by MUCZ** [envoyproxy/envoy#23550]
Custom `x-b3-traceid` header created via Lua filter gets overwritten.

***Description***:

We are using Istio and would like to do some transformations on the headers of HTTP requests at its IngressGateway.
The HTTP request arriving at IngressGateway comes with headers `x-uniqueId` and do not contain any `x-b3-*` headers, we are trying to convert the `x-uniqueId` to `x-b3-traceId` via Lua Filter, see the following configuration.
```Lua
 name: envoy.filters.http.lua
 typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
    inline_code: |
      function envoy_on_request(request_handle)
        local uniqueId = request_handle:headers():get('x-uniqueId')

        request_handle:headers():replace("x-b3-traceid", uniqueId)

        request_handle:logCritical("lua_request_after_x_b3_traceid" .. (request_handle:headers():get("x-b3-traceid") or '')) 
        -- We can verify that the x-b3-traceid is correctly set to uniqueId in the log.
        -- However, it gets overwritten afterwards by a random Id.
      end
```

Since we do see in the Lua logs that the `x-b3-traceid` of the request was set correctly, we assume it was subsequently overwritten.

We tried a few other scenario, where the incoming request does not contain an `x-b3-*` header
- If a non-x-b3 header is set in the Lua filter, it will all be retained correctly
- a `x-b3-*` header  set in the Lua filter will be overwritten with a randomly generated id

We have tested it on both v1.13.1 (istio v1.5.1) and v1.23.1 (istio v1.15.1) and the conclusions are the same.

The question is this: is it possible to customize the generation of `x-b3-*` headers with Lua filters (or any other way) for a specific set of incoming requests, and avoid envoy automatically assigning them `x-b3-*` headers with some random ids?

**_Full Configuration_**
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: trace-filter
  namespace: istio-system
spec:
  configPatches:
  # The first patch adds the lua filter to the listener/http connection manager
  - applyTo: HTTP_FILTER	
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_FIRST
      value: # lua filter specification
         name: envoy.filters.http.lua
 typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
    inline_code: |
      function envoy_on_request(request_handle)
        local uniqueId = request_handle:headers():get('x-uniqueId')

        request_handle:headers():replace("x-b3-traceid", uniqueId)

        request_handle:logCritical("lua_request_after_x_b3_traceid" .. (request_handle:headers():get("x-b3-traceid") or '')) 
        -- We can verify that the x-b3-traceid is correctly set to uniqueId in the log.
        -- However, it gets overwritten afterwards by a random Id.
      end

```
