### ISSUE TITLE
RBAC IPMatcher doesn't work expected when more than 1 IP was included in HTTP header x-forwarded-for

### ISSUE THREAD

**Issue by znqjnny** [envoyproxy/envoy#23583]
We test the RBAC IP filtering feature with 1.24 dev version.  Looks like the custom_match feature with [type.googleapis.com/xds.type.matcher.v3.IPMatcher]  currently couldn’t recognize the IP correctly when we have 2 or more IPs from one input.

In our use case, we retrieve the IP from the header with X-forward-for . And since we have proxies between the downstream and upstream services, the additional IP from the proxy was also included in the header when the forward the request,  so we could have 2 or more IPs rather than having only the source IP in this case.

And looks like the IP-matcher seems to be doing a strict match of the whole header and not matching the individual IPs, so it failed to perform filter feature when there’s one of the IPs is actually matched.

Here’s our envoy setting in this case.

```
                    http_filters:
                    - name: envoy.filters.http.rbac
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                        matcher:
                          matcher_tree:
                            input:
                              name: ip
                              typed_config:
                                "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                                header_name: x-forwarded-for
                            custom_match:
                              name: ip-matcher
                              typed_config:
                                "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                                range_matchers:
                                  #foo ip, leave it with testing. Will add the list of blocking IPs on next step
                                  - ranges:
                                      - address_prefix: 192.168.0.0
                                        prefix_len: 24
                                      - address_prefix: 10.0.0.74
                                        prefix_len: 24
                                    on_match:
                                      action:
                                        name: envoy.filters.rbac.action
                                        typed_config:
                                          "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                                          name: deny-request
                                          action: DENY
                          on_no_match:
                            action:
                              name: action
                              typed_config:
                                "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                                name: allow-request
                                action: ALLOW
```

We hope that a feature for multiple IP in HTTP header x-forward-for could be supported for IP Matcher filtering.

CC: @zhxie  @kyessenov
