### ISSUE TITLE
How to pass route metadata to ext_authz

### ISSUE THREAD

**Issue by jeffalder** [envoyproxy/envoy#23615]
*Title*: How to pass route metadata to ext_authz?

*Goal*: I want to be able to use the same ext_authz service with slightly different configuration parameters on different routes. For example, I want to say "/api/v1 uses auth method X and /api/v2 uses auth method Y" _without_ having to deploy my single ext_authz service with every possible permutation of auth method. 

_add_ I also don't want to have to program the logic of "this route uses this method" in my ext_authz service because then I have to re-implement Envoy's matching logic in my ext_authz service and sadness results

The best way I can identify to solve this is via metadata [set by the matched route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction) and [passed to ext_authz](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz), so that's what I've been trying to do. You can see from my examples that I've tried _many_ things.

I have a route configured like this:
```yaml
          route_config:
            name: local_route
            virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                  - name: my_cool_route
                    match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: backend
                      cluster: backend_cluster
                    metadata:
                      filter_metadata:
                        envoy.filters.http.ext_authz: {"metadata1":"value1","metadata2","value2"}
                        foo.mynamespace:
                          thing1: v1
                          thing2: ["a","b","c"]
```

(`backend` is just an `httpbin` running in docker)

And I have ext_authz configured as a filter:

```yaml
          http_filters:
            - name: envoy.filters.http.ext_authz
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                typed_metadata_context_namespaces:
                  - foo.mynamespace
                  - envoy.filters.http.ext_authz
                  - filter_metadata
                  - metadata1
                  - thing1
                  - '*'
                metadata_context_namespaces:
                  - foo.mynamespace
                  - envoy.filters.http.ext_authz
                  - filter_metadata
                  - metadata1
                  - thing1
                  - '*'
                status_on_error:
                  code: PaymentRequired
                transport_api_version: V3
                grpc_service:
                  envoy_grpc:
                    cluster_name: authz_cluster
                  initial_metadata:
                    - key: initial1
                      value: result-abc
```

Yet no matter what I do, the `metadata_context` attribute in my `CheckRequest` is an empty `Metadata` object. I can verify that the ext_authz service _is_ getting called and _otherwise_ contains all the correct data about the request.

What am I doing wrong? Is there a confusion of what metadata goes where? I see references to ["static" state and to "dynamic" metadata](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/data_sharing_between_filters) so maybe my expectation is wrong about how this should work.

**Comment by wbpcode** [comment]
Yeah, `typed_metadata_context_namespaces` only be used for dynamic matadata which is created dynamicly in the runtime by other filters.

**Comment by jeffalder** [comment]
@wbpcode OK, so _typed_ metadata aside (and I presume this limitation applies to _untyped_ as well), any thoughts on how to accomplish the original goal?

My next thought was to use `request_headers_to_add` on the route. Then I _should_ have a header that I can observe in the ext_authz service. I'll try that next.

**Comment by jeffalder** [comment]
```yaml
                 - name: my_cool_route
                    match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: backend
                      cluster: backend_cluster
                    request_headers_to_add:
                      - header:
                          key: x-my-auth
                          value: login_a_not_b
                        append_action: OVERWRITE_IF_EXISTS_OR_ADD
```

This did not appear to work either; the header was added to the proxied request but not to the request sent to ext_authz.

**Comment by jeffalder** [comment]
ah ha, I finally found it.

ext_authz supports "per-route configuration": https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/ext_authz_filter#per-route-configuration

The protobuf definition is here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto.html?highlight=extauthzperroute#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthzperroute

```yaml
                  - name: my_cool_route
                    match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: backend
                      cluster: backend_cluster
                    typed_per_filter_config:
                      envoy.filters.http.ext_authz:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                        check_settings:
                          context_extensions:
                            ext1: value1
                            ext2: value2
```

So this data did show up in my ext_authz request, here's a log

```
Descriptor: envoy.service.auth.v3.AttributeContext.context_extensions, value (class java.util.Collections$UnmodifiableRandomAccessList): [key: "ext2"
value: "value2"
, key: "ext1"
value: "value1"
]
```

I can work with this.
