### ISSUE TITLE
How does https Passthrough work when proxying iptables

### ISSUE THREAD

**Issue by twogoods** [envoyproxy/envoy#23620]
*Description*:

In an container injected envoy, curl https://xxx.com will success ,envoy proxying iptables and route to PassthroughCluster.
but if envoy config like this:
```
  listeners:
  - name: test_listener
    use_original_dst: true
    address:
      socket_address:
        address: "0.0.0.0"
        port_value: 16500
    filter_chains:      
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: TestPassthroughCluster
          cluster: TestPassthroughCluster  

  clusters:
  - name: TestPassthroughCluster
    type: ORIGINAL_DST
    connect_timeout: 10s
    dns_lookup_family: V4_ONLY
    lb_policy: CLUSTER_PROVIDED
```
TestPassthroughCluster may not send tls request to upstream

```
  - name: TestPassthroughCluster
    type: ORIGINAL_DST
    connect_timeout: 10s
    dns_lookup_family: V4_ONLY
    lb_policy: CLUSTER_PROVIDED
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext  
```
it will send tls request to upstream。in this case envoy accept http call and proxy to upstream with tls, it need extra config `transport_socket`

so I interested in，when proxying iptables , may envoy get https call and proxy to upstream with tls，it will work without extra config. Anyone can help me？tell me the difference of two case，show me the key implementation code will be better
