### ISSUE TITLE
receive 2 health check requests each time when configure endpoint's healthcheck's hostname field

### ISSUE THREAD

**Issue by ningyougang** [envoyproxy/envoy#23687]
## Envoy Env
Use envoy under istio. 
Envoy version: v1.13.2

Some knowledage: we can configure healthcheck's `hostname` field to make its own endpoint to get the custom Host heade value when get health check request (e.g. the same value with $hostname)
![image](https://user-images.githubusercontent.com/11749867/197968171-f22ef190-4859-4a9a-91d6-3d634c05ec9a.png)

## Issue desc
* If configure every endpoint's healthcheck's hostname, every backend endpoint server will receive 2 http healthcheck requests for each time,g.
 
  ```
  10.113.229.102 - - [26/Oct/2022:16:45:54 +0900] GET /monitor/l7check.nhn HTTP/1.1 200 0 - Envoy/HC - test.test-nyg -
  10.113.229.102 - - [26/Oct/2022:16:45:54 +0900] GET /monitor/l7check.nhn HTTP/1.1 200 0 - Envoy/HC - lambda-test.navercorp.com:80 
  ```
  corresponding envoyFilter configuration:
  ```
        health_checks:
        - always_log_health_check_failures: true
          event_log_path: /dev/stdout
          healthy_threshold: 10
          http_health_check:
            codec_client_type: HTTP1
            host: test.test-nyg
            path: /monitor/l7check.nhn
          interval: 5s
          no_traffic_healthy_interval: 5s
          no_traffic_interval: 5s
          timeout: 60s
          unhealthy_threshold: 10
        load_assignment:
          cluster_name: outbound|80||test.test-nyg
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: lambda-test.navercorp.com
                    port_value: 80
                health_check_config:
                  hostname: lambda-test.navercorp.com:80
            - endpoint:
                address:
                  socket_address:
                    address: lambda-real.navercorp.com
                    port_value: 80
                health_check_config:
                  hostname: lambda-real.navercorp.com:80
  ```

My question is:
* For each time, why the backend endpoint receives `2` health check request? Seems only 1 request for each time is enough.
* For the `2` health check requests
   - 1 request with custom Host header value(lambda-test.navercorp.com:80)
     - This result is as expected
   - Another request with orginal Host header value (test.test-nyg)
     - This result seems not as expected, since i already configured the custom header for every endpoint, why the request with original Host header comes, normally, this request can't be received.

Has any idea of make the endpoint not receive the http request with original Host header when configured the custom Host header for the backend endpoint?

* If don't configure every endpoint's healthcheck hostname, every backend endpoint server will receive only 1 http health check request with same header: `$backendName.namespace` for each time, e.g.

   ```
   10.113.229.102 - - [26/Oct/2022:16:45:54 +0900] GET /monitor/l7check.nhn HTTP/1.1 200 0 - Envoy/HC - test.test-nyg -
   ```
   corresponding envoyFilter configuration:
   ```
    patch:
      operation: MERGE
      value:
        health_checks:
        - always_log_health_check_failures: true
          event_log_path: /dev/stdout
          healthy_threshold: 10
          http_health_check:
            codec_client_type: HTTP1
            host: test.test-nyg
            path: /monitor/l7check.nhn
          interval: 5s
          no_traffic_healthy_interval: 5s
          no_traffic_interval: 5s
          timeout: 60s
          unhealthy_threshold: 10
         # remove the custom Host header configuration here
  ```

  This is normally, no question under this scene.
