### ISSUE TITLE
how to use original destination as hostname in tunneling_config

### ISSUE THREAD

**Issue by levimm** [envoyproxy/envoy#23700]
*how to use original destination as hostname in tunneling_config*

*Description*:
I'm using iptables to redirect certain traffic to envoy (for example: `iptables -t nat -A OUTPUT -p tcp --dst 10.10.1.0/24 -j REDIRECT --to-port 8099`) and then encapsulate it in HTTP1.1 CONNECT following the sample [here](https://github.com/envoyproxy/envoy/blob/582ae02170/configs/encapsulate_in_http1_connect.yaml).

Is there a way to retrieve the original destination at envoy side and dynamically set it as hostname in tunneling_config? Btw, the destination is not https so %REQUESTED_SERVER_NAME% is null here. I also tried with `DOWNSTREAM_LOCAL_ADDRESS`, the original dst ip:port is retrieved, but set it in hostname doesn't work. (hardcode with ip:port works)
```
      listener_filters:
      - name: envoy.listener.original_dst
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
      filter_chains:
      - filters:
        - name: envoy.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: passthrough
            cluster: mycluster
            tunneling_config:
              hostname: "%DOWNSTREAM_LOCAL_ADDRESS%"
```
