### ISSUE TITLE
AWS Lambda authorization header isn't generating properly.

### ISSUE THREAD

**Issue by YasiruShaminda** [envoyproxy/envoy#23702]
*Title*: *AWS Lambda authorization header isn't generating properly*

*Description*:
I tried to invoke a AWS Lambda function  with envoy AWS lambda filter and AWS Request Signing filter. I passed the Access token and Secret key in docker environment. But when I try to send request to the aws lambda it shows following error;
>"message":"'AWS4-HMAC-SHA256' not a valid key=value pair (missing equal-sign) in Authorization header:

and I noticed that the authorization header was generated twice in the request like this.
>AWS4-HMAC-SHA256 Credential=AK**************/20221026/us-east-1/lambda/aws4_request, SignedHeaders=accept;accept-encoding;accept-language;host;sec-fetch-dest;sec-fetch-mode;sec-fetch-site;sec-fetch-user;upgrade-insecure-requests;user-agent;x-amz-content-sha256;x-amz-date;x-request-id, Signature=0fb5eb87fb7e9***********************,AWS4-HMAC-SHA256 Credential=AK******************/20221026/us-east-1/lambda/aws4_request, SignedHeaders=accept;accept-encoding;accept-language;authorization;content-length;content-type;host;sec-fetch-dest;sec-fetch-mode;sec-fetch-site;sec-fetch-user;upgrade-insecure-requests;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id, Signature=4666a70c***************************************

*Config*:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9902 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log: 
          - name: router_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /tmp/access.log
              format: '"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %REQUEST_HEADERS_BYTES% %BYTES_RECEIVED% %BYTES_SENT% %UPSTREAM_HEADER_BYTES_SENT% %DURATION%%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% ""%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%""%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"\n'
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: lambda_egress_gateway }
          http_filters:
          - name: envoy.filters.http.aws_request_signing
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
              service_name: lambda
              region: us-east-1
              host_rewrite: lambda.us-east-1.amazonaws.com
              use_unsigned_payload: false
              match_excluded_headers:
              - prefix: x-envoy
              - prefix: x-forwarded
              - exact: x-amzn-trace-id
          - name: envoy.filters.http.aws_lambda
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.aws_lambda.v3.Config
              arn: "arn:aws:lambda:us-east-1:*****************:function:************"
              payload_passthrough: false
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: lambda_egress_gateway
    connect_timeout: 10s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    metadata:
      filter_metadata:
        com.amazonaws.lambda:
          egress_gateway: true
    load_assignment:
      cluster_name: lambda_egress_gateway
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: lambda.us-east-1.amazonaws.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: "*.amazonaws.com"

```

*Logs*:
````
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][debug][conn_handler] [source/server/active_tcp_listener.cc:147] [C5] new connection from 192.168.16.1:46378
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/connection_impl.cc:563] [C5] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/connection_impl.cc:674] [C5] write ready
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/connection_impl.cc:563] [C5] socket event: 3
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/connection_impl.cc:674] [C5] write ready
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/connection_impl.cc:603] [C5] read ready. dispatch_buffered_data=0
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C5] read returns: 123
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C5] read error: Resource temporarily unavailable
envoytest-envoy-1  | [2022-10-27 06:53:10.519][16][debug][connection] [./source/common/network/connection_impl.h:92] [C5] current connecting state: false
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/credentials_provider_impl.cc:43] Getting AWS credentials from the environment
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/credentials_provider_impl.cc:56] Found following AWS credentials in the environment: AWS_ACCESS_KEY_ID=AKI********************************** AWS_SECRET_ACCESS_KEY=*****, AWS_SESSION_TOKEN=
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:64] Canonical request:
envoytest-envoy-1  | POST
envoytest-envoy-1  | /addressCheck
envoytest-envoy-1  | 
envoytest-envoy-1  | accept:*/*
envoytest-envoy-1  | content-type:application/json
envoytest-envoy-1  | host:lambda.us-east-1.amazonaws.com
envoytest-envoy-1  | user-agent:curl/7.68.0
envoytest-envoy-1  | x-amz-content-sha256:e3b0c44298fc1c149afbf4c*********************************************
envoytest-envoy-1  | x-amz-date:20221027T065300Z
envoytest-envoy-1  | x-request-id:7d25e420-3475-4cd5-8363-064642ad2c20
envoytest-envoy-1  | 
envoytest-envoy-1  | accept;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-request-id
envoytest-envoy-1  | e3b0c4429**********************************************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:68] String to sign:
envoytest-envoy-1  | AWS4-HMAC-SHA256
envoytest-envoy-1  | 20221027T065300Z
envoytest-envoy-1  | 20221027/us-east-1/lambda/aws4_request
envoytest-envoy-1  | 6da0feaf89be7b2ba9**********************************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:75] Signing request with: AWS4-HMAC-SHA256 Credential=AKI*************************/20221027/us-east-1/lambda/aws4_request, SignedHeaders=accept;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-request-id, Signature=de7c3a**************************************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/credentials_provider_impl.cc:43] Getting AWS credentials from the environment
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/credentials_provider_impl.cc:56] Found following AWS credentials in the environment: AWS_ACCESS_KEY_ID=AKI****************************, AWS_SECRET_ACCESS_KEY=*****, AWS_SESSION_TOKEN=
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:64] Canonical request:
envoytest-envoy-1  | POST
envoytest-envoy-1  | /2015-03-31/functions/arn%3Aaws%3Alambda%3Aus-east-1%3A825678434177%3Afunction%3AaddressCheck/invocations
envoytest-envoy-1  | 
envoytest-envoy-1  | accept:*/*
envoytest-envoy-1  | authorization:AWS4-HMAC-SHA256 Credential=AKI*********************************20221027/us-east-1/lambda/aws4_request, SignedHeaders=accept;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-request-id, Signature=de7c3a3b*******************************************************
envoytest-envoy-1  | content-length:678
envoytest-envoy-1  | content-type:application/json
envoytest-envoy-1  | host:lambda.us-east-1.amazonaws.com
envoytest-envoy-1  | user-agent:curl/7.68.0
envoytest-envoy-1  | x-amz-content-sha256:e7e783***************************************************
envoytest-envoy-1  | x-amz-date:20221027T065300Z,20221027T065300Z
envoytest-envoy-1  | x-amz-invocation-type:RequestResponse
envoytest-envoy-1  | x-request-id:7d25e42***********************************
envoytest-envoy-1  | 
envoytest-envoy-1  | accept;authorization;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id
envoytest-envoy-1  | e7e78*****************************************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:68] String to sign:
envoytest-envoy-1  | AWS4-HMAC-SHA256
envoytest-envoy-1  | 20221027T065300Z
envoytest-envoy-1  | 20221027/us-east-1/lambda/aws4_request
envoytest-envoy-1  | 0676f34e4c22f947e****************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][aws] [source/extensions/common/aws/signer_impl.cc:75] Signing request with: AWS4-HMAC-SHA256 Credential=AKI*******************/20221027/us-east-1/lambda/aws4_request, SignedHeaders=accept;authorization;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-invocation-type;x-request-id, Signature=7b81***********************************************************
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][connection] [./source/common/network/connection_impl.h:92] [C7] current connecting state: true
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][client] [source/common/http/codec_client.cc:57] [C6] connecting
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][connection] [source/common/network/connection_impl.cc:924] [C7] connecting to 100.25.115.21:443
envoytest-envoy-1  | [2022-10-27 06:53:10.520][16][debug][connection] [source/common/network/connection_impl.cc:943] [C7] connection in progress
envoytest-envoy-1  | [2022-10-27 06:53:10.764][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:10.764][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:10.764][16][debug][connection] [source/common/network/connection_impl.cc:683] [C7] connected
envoytest-envoy-1  | [2022-10-27 06:53:10.764][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:10.814][16][debug][connection] [source/common/network/connection_impl.cc:924] [C8] connecting to 100.25.115.184:443
envoytest-envoy-1  | [2022-10-27 06:53:10.814][16][debug][connection] [source/common/network/connection_impl.cc:943] [C8] connection in progress
envoytest-envoy-1  | [2022-10-27 06:53:11.012][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 3
envoytest-envoy-1  | [2022-10-27 06:53:11.012][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.012][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.012][16][trace][connection] [source/common/network/connection_impl.cc:603] [C7] read ready. dispatch_buffered_data=0
envoytest-envoy-1  | [2022-10-27 06:53:11.012][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.013][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:11.013][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.013][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.050][16][trace][connection] [source/common/network/connection_impl.cc:563] [C8] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:11.050][16][trace][connection] [source/common/network/connection_impl.cc:674] [C8] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.050][16][debug][connection] [source/common/network/connection_impl.cc:683] [C8] connected
envoytest-envoy-1  | [2022-10-27 06:53:11.050][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_handshaker.cc:93] [C8] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.120][16][debug][connection] [source/common/network/connection_impl.cc:924] [C9] connecting to 100.25.115.210:443
envoytest-envoy-1  | [2022-10-27 06:53:11.120][16][debug][connection] [source/common/network/connection_impl.cc:943] [C9] connection in progress
envoytest-envoy-1  | [2022-10-27 06:53:11.258][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 3
envoytest-envoy-1  | [2022-10-27 06:53:11.258][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.258][16][trace][connection] [source/common/network/connection_impl.cc:418] [C7] raising connection event 2
envoytest-envoy-1  | [2022-10-27 06:53:11.258][16][debug][connection] [source/common/network/connection_impl.cc:139] [C8] closing data_to_write=0 type=1
envoytest-envoy-1  | [2022-10-27 06:53:11.258][16][debug][connection] [source/common/network/connection_impl.cc:250] [C8] closing socket: 1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:418] [C8] raising connection event 1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][debug][connection] [source/common/network/connection_impl.cc:139] [C9] closing data_to_write=0 type=1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][debug][connection] [source/common/network/connection_impl.cc:250] [C9] closing socket: 1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:418] [C9] raising connection event 1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][debug][client] [source/common/http/codec_client.cc:88] [C6] connected
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:478] [C7] writing 1131 bytes, end_stream false
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:478] [C7] writing 678 bytes, end_stream false
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][debug][client] [source/common/http/codec_client.cc:139] [C6] encode complete
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:268] [C7] ssl write returns: 1809
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:603] [C7] read ready. dispatch_buffered_data=0
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C7] ssl read returns: -1
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:127] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:163] [C7] ssl read 0 bytes
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:11.259][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:563] [C7] socket event: 3
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:674] [C7] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:603] [C7] read ready. dispatch_buffered_data=0
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C7] ssl read returns: 923
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:87] [C7] ssl read returns: -1
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:127] [C7] ssl error occurred while read: WANT_READ
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:163] [C7] ssl read 923 bytes
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:478] [C5] writing 271 bytes, end_stream false
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:478] [C5] writing 679 bytes, end_stream false
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][debug][client] [source/common/http/codec_client.cc:126] [C6] response complete
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:563] [C5] socket event: 2
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/connection_impl.cc:674] [C5] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.510][16][trace][connection] [source/common/network/raw_buffer_socket.cc:67] [C5] write returns: 950
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][connection] [source/common/network/connection_impl.cc:563] [C5] socket event: 3
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][connection] [source/common/network/connection_impl.cc:674] [C5] write ready
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][connection] [source/common/network/connection_impl.cc:603] [C5] read ready. dispatch_buffered_data=0
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C5] read returns: 0
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][debug][connection] [source/common/network/connection_impl.cc:651] [C5] remote close
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][debug][connection] [source/common/network/connection_impl.cc:250] [C5] closing socket: 0
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][connection] [source/common/network/connection_impl.cc:418] [C5] raising connection event 0
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][trace][conn_handler] [source/server/active_stream_listener_base.cc:111] [C5] connection on event 0
envoytest-envoy-1  | [2022-10-27 06:53:11.511][16][debug][conn_handler] [source/server/active_stream_listener_base.cc:120] [C5] adding to cleanup list
envoytest-envoy-1  | [2022-10-27 06:53:13.921][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:108] starting async DNS resolution for lambda.us-east-1.amazonaws.com
envoytest-envoy-1  | [2022-10-27 06:53:13.934][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:116] async DNS resolution complete for lambda.us-east-1.amazonaws.com
envoytest-envoy-1  | [2022-10-27 06:53:13.934][1][debug][upstream] [source/common/upstream/logical_dns_cluster.cc:167] DNS refresh rate reset for lambda.us-east-1.amazonaws.com, refresh rate 5000 ms
````
