### ISSUE TITLE
Envoy Filter Or Command %REQ(X?Y):Z% not working as expected

### ISSUE THREAD

**Issue by edubonifs** [envoyproxy/envoy#23727]
Hi, regarding the documentation: https://www.envoyproxy.io/docs/envoy/v1.22.5/configuration/observability/access_log/usage#config-access-log-format
If we have an envoy filter and we set a header with an or command %REQ(X?Y):Z%, the envoy filter will skip this configuration and will skip this header.

Steps to reproduce:

```
# Install a modern istio
export ISTIO_VERSION=1.15.1
curl -L https://istio.io/downloadIstio | sh -
./istio*/bin/istioctl install -y

# Install some apps
kubectl label ns default istio-injection=enabled
kubectl apply -n default -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/httpbin/httpbin.yaml
kubectl apply -n default -f https://raw.githubusercontent.com/istio/istio/release-1.15/samples/extauthz/ext-authz.yaml

# Expose a route
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-gw-vs
spec:
  hosts:
  - "*"
  gateways:
  - api-gateway
  http:
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF

# Apply extauthz
kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: authn-filter
  namespace: istio-system
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_authz
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
            http_service:
              server_uri:
                cluster: outbound|8000||ext-authz.default.svc.cluster.local
                timeout: 10s
                uri: http://ext-authz.default.svc.cluster.local:8000/status/200
              authorizationRequest:
                allowedHeaders:
                  patterns:
                  - exact: cookie
                    ignoreCase: true
                  - exact: x-forwarded-access-token
                    ignoreCase: true
                  - exact: x-ext-authz
                    ignoreCase: true
                headersToAdd:
                - key: x-auth-request-redirect
                  value: '%REQ(x-h1)%%REQ(x-h2)%'
  workloadSelector:
    labels:
      istio: ingressgateway
EOF

GATEWAY_IP=$(kubectl get svc -n istio-system istio-ingressgateway -o jsonpath="{.status.loadBalancer.ingress[0].ip}")

# This is accepted
curl -H "x-ext-authz: allow" -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get

# This is rejected
curl -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get

#check logs
kubectl logs deploy/ext-authz

# Now change the value in the envoyfilter for '%REQ(x-h1)%%REQ(x-h3?x-h2)%' , it will stop working, the header will not appear any more nor with h2 nor h3
```
