### ISSUE TITLE
Envoy Filter Or Command %REQ(X?Y):Z% not working as expected

### ISSUE THREAD

**Issue by edubonifs** [envoyproxy/envoy#23753]
Hi, regarding the documentation: https://www.envoyproxy.io/docs/envoy/v1.22.5/configuration/observability/access_log/usage#config-access-log-format
If we have an envoy filter and we set a header with an or command %REQ(X?Y):Z%, the envoy filter will skip this configuration and will skip this header.

```
If we set the header without the conditional:
value: '%REQ(x-h1)%%REQ(x-h2)%'

# This is accepted
curl -H "x-ext-authz: allow" -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get

# This is rejected
curl -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get

# Now change the value in the envoyfilter for '%REQ(x-h1)%%REQ(x-h3?x-h2)%' , it will stop working, the header will not appear any more nor with h2 nor h3
```

**Comment by KBaichoo** [comment]
cc @cpakulski I think this might be related to unified formatters

**Comment by cpakulski** [comment]
Looking into it. Thanks!

**Comment by cpakulski** [comment]
@edubonifs What is the version of Envoy you are using?

**Comment by edubonifs** [comment]
Hi, I am using version 1.23.2

**Comment by cpakulski** [comment]
@edubonifs I just tried 1.23.2 and everything seems to be working fine. I added basic access log to the 
HttpConnectionManager:

```
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /dev/stdout
                json_format:
                  headers: "%REQ(x-h1)%%REQ(x-h3?x-h2)%"
```
 
And I get the right output for:
`curl -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get`

I think I am missing something here. Can you provide a config snippet? I also do not understand what do you mean by _rejected_:

> This is accepted
> curl -H "x-ext-authz: allow" -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get
> 
> This is rejected
> curl -H "x-h1: h1" -H "x-h2: h2" http://$GATEWAY_IP/get
