### ISSUE TITLE
How to direct response a static resource

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23755]
I'm using Envoy as the gateway of my web servers. I have some static files, such as index.html, which should be sent back to the clients while receiving the requests from the clients.

For example, `https://example.com/static` should get the file at `/static/index.html`.

Here is the part of my config:
```
virtual_hosts:
  - name: local
    domains: ["*"]
    routes:
      - match:
           prefix: "/static"
        redirect:
           path_redirect: "/static/index.html"
           https_redirect: true
```

However, when I visit `https://example.com/static`, I will get a 301 and then a 404. I couldn't get the static resource `index.html`...

With Nginx, I know that we should use `alias /static/`...

Can someone help me?

**Comment by wbpcode** [comment]
I think you should use `direct_response` rather than `redirect`.

```
virtual_hosts:
  - name: local
    domains: ["*"]
    routes:
      - match:
           prefix: "/static"
        direct_response:
          status: 200
          body:
            filename: "/static/index.html"
```
