### ISSUE TITLE
Set gRPC ext_authz request headers based on incoming request header

### ISSUE THREAD

**Issue by qixuan-li1** [envoyproxy/envoy#23762]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: _Set gRPC ext_authz request headers based on incoming request header_

*Description*:
I have a list of headers that I want to set before sending it to gRPC/HTTP ext_authz filter. I want to set different values to those headers based on the request’s :path. Is there any way to achieve this in Envoy? I know we can add static headers using things like `initial_metadata` but those can not be dependent on the request information. Ideally, I want to have a knob like initial_metadata_based_on_request like the following. Is similar functionality supported in Envoy or is there any workarounds to achieve the same goal? 
```
http_filters:
  - name: envoy.filters.http.ext_authz
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      grpc_service:
        envoy_grpc:
          cluster_name: ext-authz
        initial_metadata_based_on_request: [
	  - match:
	      prefix: "path1"
	    initial_metadata:
	       {key: "header-based-on-bath", value: "value1" }
      	  - match:
	      prefix: "path2"
	    initial_metadata:
	        {key: "header-based-on-bath", value: "value2" }
        ]
```
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
