### ISSUE TITLE
TLS decryption of an HTTP CONNECT tunnel using dynamic forward proxy?

### ISSUE THREAD

**Issue by hbagdi** [envoyproxy/envoy#23811]
*Title*: Is it possible to terminate TLS of the byte stream within an HTTP CONNECT tunnel?

*Description*:

I was able to set up Envoy to terminate HTTP CONNECT (i.e. establish a tunnel between the client and the upstream) and use it as a dynamic forward proxy.
After the tunnel is established, I'd like to know if it is possible to intercept the TLS traffic within the tunnel (assuming that envoy has the certificate to man in the middle of the connection). 

As far as I can see, this is not possible but I'm new to Envoy so here I'm. If this is the wrong place to ask this question, please redirect me.

I should add that there are two workarounds that I have been able to figure out:
- Use another Envoy to intercept traffic of the tunnel transparently, let's call this Envoy B. Envoy B then terminates TLS and can optionally parse HTTP within the tunnel if needed. Envoy B is essentially a reverse proxy in this case.
- Do the same but using a single Envoy by using loopback an some trickery to manage ports.

Both of these options have their overheads.
I'd prefer to use a single Envoy and I'd prefer not to have to route traffic through Envoy two times. Is something like this feasible out of the box?

If this is not possible out of the box today, is it even feasible to add something like this to Envoy?

**Comment by soulxu** [comment]
@hbagdi The internal listener could help you on this case https://www.envoyproxy.io/docs/envoy/latest/configuration/other_features/internal_listener.html?highlight=internal%20listener#internal-listener, then you can done something like a listener to terminal the CONNECT, then another internal listener for terminate tls.

**Comment by shibin-george** [comment]
> I was able to set up Envoy to terminate HTTP CONNECT (i.e. establish a tunnel between the client and the upstream) and use it as a dynamic forward proxy.

@hbagdi - would you mind sharing the config for this? I was able to get envoy work as a forward proxy for http calls, but I get a 404 with the https ones.
Here's the config I'm currently working with and can't figure why https results in a 404
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/force-host-rewrite"
                route:
                  cluster: dynamic_forward_proxy_cluster
                typed_per_filter_config:
                  envoy.filters.http.dynamic_forward_proxy:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                    host_rewrite_literal: www.example.org
              - match:
                  prefix: "/"
                route:
                  cluster: dynamic_forward_proxy_cluster
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: dynamic_forward_proxy_cluster
                  upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config:
                        {}
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                    resolvers:
                    - socket_address:
                        address: "8.8.8.8"
                        port_value: 53
                    dns_resolver_options:
                      use_tcp_for_dns_lookups: true
                      no_default_search_domain: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http_protocol_options: {}
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: dynamic_forward_proxy_cluster_tls
    connect_timeout: 2s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca: {filename: /etc/ssl/certs/ca-certificates.crt}
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 2s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true

```
