### ISSUE TITLE
How would one return CORS headers along with a 404 via Envoy?

### ISSUE THREAD

**Issue by truehhart** [envoyproxy/envoy#23839]
*Title*: *How would one return CORS headers along with a 404 via Envoy?*

*Description*:
We are using Envoy as our API Gateway. Every filter chain only has one virtual_host under its route_config and when the traffic gets there, we are using routes to figure out where to send traffic next.

If a route has not been defined under the configuration - a 404 will automatically be returned by Envoy (since there’s nowhere to route the traffic to).
When a 404 happens - we always receive a CORS error, since there are no CORS headers included with the request.
Here’s an example of our configuration:
```yaml
static_resources:
  listeners:
  - name: listener_http
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          use_remote_address: true
          access_log: 
          - name: redirect_access_log
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /var/log/envoy-proxy/lb/redirect/redirect.log
          route_config:
            name: http_redirect
            response_headers_to_remove: ['x-envoy-upstream-service-time']
            virtual_hosts:
            - name: http_redirect
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                redirect: { https_redirect: true }
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

### dynamic block https listener ###
  - name: listener_https_public
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    listener_filters:
      - name: "envoy.filters.listener.tls_inspector"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:   
    - filter_chain_match:
        server_names: ["somenvironment-api.somedomain"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: { filename: "/etc/ssl/somedomain.crt" } 
              private_key: { filename: "/etc/ssl/somedomain.key" }
            tls_params:
              tls_minimum_protocol_version: "TLSv1_2"
      filters: 
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: somenvironment-api.somedomain
          upgrade_configs:
          - upgrade_type: websocket
          codec_type: AUTO
          use_remote_address: true
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          access_log: 
            - name: somenvironment-api.somedomain
              typed_config: 
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /var/log/envoy-proxy/lb/access/somenvironment-api.somedomain.log
          route_config:
            name: somenvironment-api.somedomain
            response_headers_to_remove: ['x-envoy-upstream-service-time']
            virtual_hosts:
            - name: somenvironment-api.somedomain
              domains: ["somenvironment-api.somedomain"]
              cors:
                allow_origin_string_match:
                - safe_regex:
                    google_re2: {}
                    regex: \*
              routes:
              - match:
                  safe_regex:
                    google_re2: {}
                    regex: \/API\/route
                route:
                  cluster:  "someenvironment-api" 
                  cors:
                    allow_methods: POST
                    allow_headers: "*"
                  timeout: 0s
              - match:
                  safe_regex:
                    google_re2: {}
                    regex: \/OtherAPI\/route\/path
                route:
                  cluster:  "someotherenvironment-api" 
                  cors:
                    allow_methods: GET
                    allow_headers: "*"
                  timeout: 0s
              - match:
                  prefix: "/"
                direct_response:
                  status: 404

  - name: someenvironment-api
    connect_timeout: 7s 
    circuit_breakers: 
      thresholds:
      - priority: 0
        max_connections: 25000
        max_pending_requests: 10000
        max_requests: 25000
        max_retries: 3
    type: STATIC
    lb_policy: ROUND_ROBIN 
    load_assignment:
      cluster_name: someenvironment-api
      endpoints: 
      - lb_endpoints: 
        - endpoint: 
            address: 
              socket_address:
                address: 10.0.0.175
                port_value: 27022
  - name: someotherenvironment-api
    connect_timeout: 7s 
    circuit_breakers: 
      thresholds:
      - priority: 0
        max_connections: 25000
        max_pending_requests: 10000
        max_requests: 25000
        max_retries: 3
    type: STATIC
    lb_policy: ROUND_ROBIN 
    load_assignment:
      cluster_name: someotherenvironment-api
      endpoints: 
      - lb_endpoints: 
        - endpoint: 
            address: 
              socket_address:
                address: 10.0.0.123
                port_value: 18632
```

We have tried adding a default direct_response route to the end of the chain as follows :
```yaml
  - match:
      prefix: “/“
    direct_response:
      status: 404
```
Unfortunately, though, that didn’t help.
Is there a way to have Envoy return CORS headers along with a 404?

**Comment by phlax** [comment]
cc @wbpcode @daixiang0

**Comment by wbpcode** [comment]
@truehhart So you want add cors headers to the 404 response? right?

As far as I know, cors is only enabled for the requests that will match routes that have a `route` action.

**Comment by truehhart** [comment]
Hey there,

We basically wanted to make sure that when we are deploying new applications under the same virtual host - we would receive a 404 from a front-end application as opposed to the CORS error if a route wasn’t defined for it in Envoy.
What was happening is that since envoy returned a blank 404 - there was no header information and browsers would treat it as a CORS failure.

@wbpcode I do appreciate your advice on the direct response with response_headers_to_add, though it hadn’t worked for me previously. Nonetheless, I’ve dug deeper and found what was the cause of the problem, maybe this would help someone in the future.

What was happening is that we needed 2 different direct responses with CORS headers - one for a preflight request and another one for a 404.

Here’s what we went for:

```yaml
              - match:
                  prefix: "/"
                  headers:
                    - name: ":method"
                      exact_match: "OPTIONS"
                direct_response:
                  status: 200
                response_headers_to_add:
                  - header: {key: "access-control-allow-origin", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-methods", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-headers", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-credentials", value: "false"}
                    append_action: "ADD_IF_ABSENT"
              - match:
                  prefix: "/"
                direct_response:
                  status: 404
                response_headers_to_add:
                  - header: {key: "access-control-allow-origin", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-methods", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-headers", value: "*"}
                    append_action: "ADD_IF_ABSENT"
                  - header: {key: "access-control-allow-credentials", value: "false"}
                    append_action: “ADD_IF_ABSENT"
```

Whenever Envoy receives a request to a route that is not defined - it reaches these two routes at the end of the list. First, it would reply with a 200 to preflight with “allow all but credentials” CORS statement, and then - with a similar 404.

Again, very thankful for your insights guys, take care and keep working on an amazing product!
