### ISSUE TITLE
How to make a direct response with RBAC

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23830]
I need to set a RBAC rule in my Envoy http-config: Only several segments of IPs have the right to access my cluster, others would be denied. Here is the part of my config file:
```
http_filters:
  - name: envoy.filters.http.rbac
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
      rules:
        action: ALLOW
        politics:
          "general-rules":
            permissions:
            - any: true
            principals:
            - direct_remote_ip:
                 address_prefix: 44.33.55.22
                 prefix_len: 16
...
...
```
As you see, now only `44.33.55.22/16` can access my http cluster. It works as exptected.
However, for the others, who are not `44.33.55.22/16`, they will get such a response with the status code `403` on their browser:
```
RBAC: access denied
```

I'm wondering if I can customized this response, just like the `direct_response`:
```
virtual_hosts:
  - name: local_host
    domains: ["*"]
    routes:
    - match:
        prefix: "/"
      direct_response:
        status: 404
        inline_string: "lol"
```
