### ISSUE TITLE
Does QUIC work with UDP proxy?

### ISSUE THREAD

**Issue by rohrit** [envoyproxy/envoy#23857]
*Title*: *Is it possible to use QUIC support in Envoy with a upstream server that handles QUIC datagrams*

*Description*:
It was not clear from the documentation whether this use case is supported or if this works only with HTTP/3. Nevertheless, I tried to see if this works with the configuration shown below and I see the error "error building network filter chain for quic listener: requires exactly one http_connection_manager filter".

Related question: Does TLS inspector work with QUIC for selection of selection of different upstreams based on SNI?

configuration used below

```
     - name: listener_0
        address:
          socket_address:
            protocol: UDP
            address: 0.0.0.0
            port_value: 10443
        udp_listener_config:
          quic_options: {}
          downstream_socket_config:
            prefer_gro: true
        filter_chains:
        - filter_chain_match:
            server_names: foo.domain
          transport_socket:
            name: envoy.transport_sockets.quic
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
              downstream_tls_context:
                common_tls_context:
                  tls_certificates:
                  - certificate_chain:
                      filename: cert.pem
                    private_key:
                      filename: key.pem
          filters:
          - name: envoy.filters.udp_listener.udp_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
              stat_prefix: service
              matcher:
                on_no_match:
                  action:
                    name: route
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                      cluster: quic-server
              upstream_socket_config:
                max_rx_datagram_size: 9000
```
