### ISSUE TITLE
Rate limit does not close connection and forwards via proxy

### ISSUE THREAD

**Issue by hanem100k** [envoyproxy/envoy#23865]
*Description*:
>Requests are forwarded by TCP-proxy filter despite local rate limit filter kicking in.

I might be missing something here, ( The L7 rate limiter works out of the box, however, this L4 one does not seem to impose any limits. Do I need to add circuit breaking instead of this? )

Current envoy config
```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: rate-limiter
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.local_ratelimit.v3.LocalRateLimit
          stat_prefix: l4_rate_limiter
          token_bucket:
            max_tokens: 1
            tokens_per_fill: 1
            fill_interval: 5s
      - name: tcp
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_stats
          max_connect_attempts: 3
          idle_timeout: 5s
          cluster: some_service

  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3000
```
