### ISSUE TITLE
A large http request will lose its body

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#23934]
I'm using Envoy V1.22 as the gateway of my backend web servers. The web servers provided http POST requests, one of them is about uploading files to server.

To my surprise, if I upload a tiny file, such as a 3KB file, it works as expected but if I upload a larger file, such as a 20KB file, it would fail.

So I'm trying to add a Lua script to figure out what happened.

Here is my config file of Envoy:
```
static_resources:
  listeners:
  - name: listener_common_https
    address:
      socket_address: *common_ingress_https_addr
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          access_log: *common_https_access_log
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code:
                function envoy_on_request(request_handle)
                  local index = 0
                  local header = request_handle:headers()
                  request_handle:logInfo("header:")
                  request_handle:logInfo(tostring(header:get("content-length")))
                  request_handle:logInfo("body:")
                  local body = request_handle:body()
                  if body == nil then
                    request_handle:logInfo("nil? wtf man!")
                  else
                    request_handle:logInfo(body:length())
                  end
                end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: file_service
              domains: ["fileserver.example.com:*", "fileserver2.example.com:*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_filesvr_https
                  timeout: 1200s
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context: *ingress_https_crt
      transport_socket_connect_timeout: 30s
  clusters:
  - name: cluster_filesvr_https
    connect_timeout: 30s
    type: LOGICAL_DNS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
        common_http_protocol_options:
          idle_timeout: 3600s
        explicit_http_config:
          http_protocol_options: {}
#    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_filesvr_https
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: *filesvr_egress_https_addr
```

Now, if I upload a tiny file, the Lua script will print the log as below:
```
header:
123
body:
123
```
Which looks fine.

But a larger file will print:
```
header:
34333
body:    # it would block here for a long time
nil? wtf man!
```

I've tried to add some other configs about timeout and buffer size, but nothing changed.
**It seems that the Envoy started to receive the request packet and suddenly all of received data was abandoned so that the variable `body` in Lua script became `nil`.**
Could someone help me on this issue?
BTW, I deployed my Envoy with Docker container and I just tried to use Nginx and it works fine even with larger file...
