### ISSUE TITLE
Redis Proxy: Auth password per endpoint in a cluster?

### ISSUE THREAD

**Issue by dceravigupta** [envoyproxy/envoy#23962]
Hi, is it possible to use different auth passwords for connecting to different redis endpoints as part of a single redis upstream clusters?

```
  clusters:
  - name: redis_cluster
    type: STRICT_DNS
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: abc.redis.net
                port_value: 6380
        - endpoint:
            address:
              socket_address:
                address: xyz.redis.net
                port_value: 6380
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
        auth_password:
          inline_string: "??" <-- auth password is different for the above mentioned redis endpoints.
```

In the example config above, both redis instances i.e. abc.redis.net and xyz.redis.net have different auth passwords.
