### ISSUE TITLE
GrpcJsonTranscoder error 415 when matching similar path

### ISSUE THREAD

**Issue by icerockq** [envoyproxy/envoy#24019]
For settings:
```
route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: [ "*" ]
                    routes:
                      - match: { prefix: "/api/v1/service" }
                        route: { cluster: service, timeout: 60s }
http_filters:
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/etc/envoy/some_proto.pb"
                    match_incoming_request_route: true
                    services: [
                      "ExampleService"
                    ]
                    convert_grpc_status: true
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: false
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
And if we have this proto:
```
service ExampleService{
  rpc getEvent(GetEventRequest) returns (SomeResponse) {
    option(google.api.http) = {
      get: "/api/v1/service/{id}"
    };
  }
  rpc getHistory(ServiceRequest) returns (SomeResponse) {
    option(google.api.http) = {
      get: "/api/v1/service/{id}/history"
    };
  }
message ServiceRequest{
  int64 id = 1;
  string data = 2;
}
message GetEventRequest{
  int64 id = 1;
}
}
```
And when I try get ```/api/v1/service/2/history?data=some_data``` then I get error 415 Unsupported media type
