### ISSUE TITLE
envoy as sidecar failed since we switch to containerd

### ISSUE THREAD

**Issue by smartnews-weitao** [envoyproxy/envoy#24025]
Previously we have been using envoy as a sidecar in our kubernetes service to do the client side loadbalance. However since our kubernetes upgrade to use containerd as runtime. We no longer can connect to backend successfully via envoy. But envoy itself has no error log. I am wondering have anyone encountered this before?

**Comment by smartnews-weitao** [comment]
And this is my envoy configuration:

`static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8500
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route_dnn_service
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dnn_service
                http_filters:
                  - name: envoy.router
                    config: {}
  clusters:
    - name: dnn_service.svc.cluster.local
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      http2_protocol_options: {}
      drain_connections_on_host_removal: true
      load_assignment:
        cluster_name: dnn_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  health_check_config:
                    port_value: 8501
                  address:
                    socket_address:
                      address: dnn_service.svc.cluster.local
                      port_value: 8500
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8090
`

**Comment by phlax** [comment]
are connections getting into the container? can the container connect to the upstream cluster?

if both of those are yes - it might be worth trying to use debug logging https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#debugging-envoy

**Comment by smartnews-weitao** [comment]
Sorry i am not familiar with the container runtime. Can you instruct me how to make sure whether connections getting into the container?

**Comment by phlax** [comment]
it depends on your environment and setup

i guess firstly i would check Envoy access logs to see if there is incoming connections

**Comment by smartnews-weitao** [comment]
I am running my envoy as a side-car, and here's the part of my k8s deployment yaml related with envoy:

```
- name: envoy
          image: envoyproxy/envoy:v1.9.1
          resources:
            limits:
              memory: "200Mi"
            requests:
              memory: "100Mi"
              cpu: "200m"
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 60" ]
          ports:
            - name: http
              containerPort: 8081
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
      volumes:
        - name: config
          configMap:
            name: envoy-inference
```

After i log into the envoy container, do you know how can i check the access logs? i didn't find any log file in /var/log/

**Comment by smartnews-weitao** [comment]
BTW, my envoy configuration always report error whenever i try to upgrade to latest envoy version, and the error message is: 

Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[0].filters[0]) config: Cannot find field.) has unknown fields

```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 8500
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route_dnn_service
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dnn_service
                http_filters:
                  - name: envoy.router
                    config: {}
  clusters:
    - name: dnn_service.svc.cluster.local
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      http2_protocol_options: {}
      drain_connections_on_host_removal: true
      load_assignment:
        cluster_name: dnn_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  health_check_config:
                    port_value: 8501
                  address:
                    socket_address:
                      address: dnn_service.svc.cluster.local
                      port_value: 8500
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8090
```
