### ISSUE TITLE
v2 API Access Log Filter Schema is incorrect

### ISSUE THREAD

**Issue by winguse** [envoyproxy/envoy#2408]
v2 API Access Log Filter Schema is incorrect

This is the V1 config:

```yaml
              filter:
                type: logical_and
                filters:
                - type: logical_or
                  filters:
                  - type: status_code
                    op: ">="
                    value: 400
                  - type: status_code
                    op: "="
                    value: 0
                  - type: duration
                    op: ">="
                    value: 2000
                  - type: traceable_request
                - type: not_healthcheck
```

This is one V2 config I can think of: 

```yaml
            filter:
              and_filter:
                filters:
                  - not_health_check_filter: {}
                  - or_filter:
                      filters:
                        - status_code_filter:
                            comparison:
                              op: GE
                              value:
                                default_value: 300
                                runtime_key: "" # What's this? And this is required.
                        - status_code_filter:
                            comparison:
                              op: EQ
                              value:
                                default_value: 0
                                runtime_key: "" # What's this?
                        - duration_filter:
                            comparison:
                              op: GE
                              value:
                                default_value: 2000
                                runtime_key: "" # What's this?
                        - traceable_filter: {}
```

As searching the code, I can see `runtime_key` is something like `access_log.access_error.status`.

And I think the problem here is incorrect use of [`RuntimeUInt32 `](https://github.com/envoyproxy/data-plane-api/blob/master/api/base.proto#L109) [inside](https://github.com/envoyproxy/data-plane-api/blob/master/api/filter/accesslog/accesslog.proto#L342) [`ComparisonFilter`](https://github.com/envoyproxy/data-plane-api/blob/master/api/filter/accesslog/accesslog.proto#L329).

`RuntimeUInt32.runtime_key` looks like is to extract information from log and fall back to 
`RuntimeUInt32.default_value`.
