### ISSUE TITLE
Dynamic forward proxy with connect termination

### ISSUE THREAD

**Issue by shibin-george** [envoyproxy/envoy#24139]
*Description*:
I am trying to set up Envoy to act as a forward proxy for my internet-outbound needs.
essentially, `curl -x <Envoy-service's public IP>:<listener port> xyz.com`
should result in Envoy starting a TCP tunnel between client (curl) and destination.

Here's the config that I'm using:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: dynamic_forward_proxy_cluster
                  upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config:
                        {}
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                    resolvers:
                    - socket_address:
                        address: "8.8.8.8"
                        port_value: 53
                    dns_resolver_options:
                      use_tcp_for_dns_lookups: true
                      no_default_search_domain: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: dynamic_forward_proxy_cluster
    connect_timeout: 2s
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true
```

When I run `curl -x IP:10010 https://api.ipify.org -v`, here's the output I get:
```
* Connected to <REDACTED> port 10010 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to api.ipify.org:443
> CONNECT api.ipify.org:443 HTTP/1.1
> Host: api.ipify.org:443
> User-Agent: curl/7.83.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 404 Not Found
< date: Tue, 22 Nov 2022 06:41:38 GMT
< server: istio-envoy
< connection: close
< content-length: 0
<
* Received HTTP code 404 from proxy after CONNECT
* CONNECT phase completed
* Closing connection 0
curl: (56) Received HTTP code 404 from proxy after CONNECT
```
If the destination is http instead of https, its still a 404, but a different reason:
```
`curl -x IP:10010 http://api.ipify.org -v`
* Connected to <REDACTED> port 10010 (#0)
> GET http://api.ipify.org/ HTTP/1.1
> Host: api.ipify.org
> User-Agent: curl/7.83.1
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Tue, 22 Nov 2022 06:43:30 GMT
< server: istio-envoy
< content-length: 0
< x-envoy-upstream-service-time: 0
< x-envoy-decorator-operation: envoy-forward-proxy.default.svc.cluster.local:10010/*
<
```

My config is borrowed from [here](https://github.com/envoyproxy/envoy/blob/main/configs/terminate_http1_connect.yaml) but for DFP cluster type.
Appreciate any help in figuring out what's going wrong here. 
squid as forward proxy is working but I don't want to use squid, if I can.
