### ISSUE TITLE
Different stream IDs in the application log (ENVOY_STREAM_LOG) and the access log (%STREAM_ID%)

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#24155]
Commit 04dd76b051c99f82abda081e1d04cac38667ef88 added `%STREAM_ID%` for the access log. But this stream ID is not the same as in the application log: `ENVOY_STREAM_LOG()` and `%STREAM_ID%` log different stream IDs. This is confusing.

*Example from the application log:*
```
[2022-11-22 20:54:08.768][578202][debug][http] [source/common/http/conn_manager_impl.cc:907] [C0][S16272860808686838220] request end stream
```
Here, `S16272860808686838220` is the stream ID, logged with the macro `ENVOY_STREAM_LOG()`.

*Example from the access log, for the same request:*

`%STREAM_ID%` has the value `7b073e78-a9bc-4ec2-953a-7b6766d95262`

*Possible solutions:*

A) Rename `%STREAM_ID%` to `%REQUEST_ID%`
B) Change the implementation of `%STREAM_ID%` and/or `ENVOY_STREAM_LOG()` so that they log the same value

*Repro steps:*

Start Envoy with `envoy -c test-config.yaml --component-log-level http:debug`. Perform an HTTP request (`curl http://localhost:10000/`) and look at the logs.

Configuration (test-config.yaml):
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          scheme_header_transformation:
            scheme_to_overwrite: https
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                json_format:
                  path: "%REQ(:PATH)%"
                  request_id: "%REQ(X-REQUEST-ID)%"
                  stream_id: "%STREAM_ID%"
  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```
