### ISSUE TITLE
CORS allowmethods not working

### ISSUE THREAD

**Issue by Naskitu** [envoyproxy/envoy#24191]
I am trying to test allowmethods,
however envoy, setting whatever method it is, keeps going, so it doesn't work.

I have tried these two configurations, always with the same result, the back is returning unsupported method, instead of envoy.
        
              cors:
                allow_origin_string_match:
                - safe_regex:
                    google_re2: {}
                    regex: \*
                allow_methods: "DELETE"
                filter_enabled:
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                  runtime_key: cors.www.enabled
                shadow_enabled:
                  default_value:
                    numerator: 0
                    denominator: HUNDRED
                  runtime_key: cors.www.shadow_enabled
              routes:
              - match:
                  prefix: "/test/test2"
                route:
                  cluster: backend
                  cors:
                    allow_origin_string_match:
                    - safe_regex:
                        google_re2: {}
                        regex: \*
                    allow_methods: "DELETE"
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

I have also tried this configuration

          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              cors:
                allow_origin_string_match:
                - safe_regex:
                    regex: \*                  
                allow_methods: GET, PUT, DELETE, POST, PATCH, OPTIONS                              
              routes:
  
              - match:
                 safe_regex:
                  google_re2: {}
                  regex: "/.*\/test"                             
                route:
                  cluster: backend
                  cors:
                    allow_origin_string_match:
                    - safe_regex:
                        google_re2: {}
                        regex: \*
                    allow_methods: "DELETE"

any help for this?

thanks

**Comment by wbpcode** [comment]
🤔  what are your test requests look like?

**Comment by Naski86** [comment]
hello
thanks for you reply

curl -X POST http://localhost:8080/rest/test 
and curl -X POST http://localhost:8080/rest/test2
and the back-end return 405 method not allowed, but not envoy... :(

**Comment by wbpcode** [comment]
`cors` filter is used to reply `OPTION` request of browser. It can't be used as a blocker, actually. 🤣

**Comment by Naski86** [comment]
> `cors` filter is used to reply `OPTION` request of browser. It can't be used as a blocker, actually. 🤣

mmm it´s true , but envoy does not allow certain methods to be used in the paths, if a post comes instead of a get, skip a method not allowed ?

thanks :)

**Comment by wbpcode** [comment]
If you just want to block requests with specified methods in specified routes. Then simple header match is enough.
Name `:method` is used to represent method of HTTP request. 

```
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      stat_prefix: ingress_http
      route_config:
        virtual_hosts:
        - name: local_service
          domains:
          - "*"                        
          routes:
          - match:
             headers:
             - name: ":method"
               string_match:
                 exact: "DELETE"
             safe_regex:
               google_re2: {}
               regex: "/.*\/test"         
            route:
              cluster: backend
```

**Comment by Naski86** [comment]
thanks for u reply

I have tried these values you have given me.

but it still does not validate, it gives me a 404, since it does not find the back(it is correct because I do not have it up), however I am putting a POST and it does not validate it.

the code
```
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: local_service
              domains:
              - "*"    
              routes:
              - match:
                 headers:
                 - name: ":method"
                   string_match:
                     exact: "DELETE"
                 safe_regex:
                   google_re2: {}
                   regex: "/.*\/test"         
                route:
                  cluster: backend
```

the curl : 
curl -X POST -vki  http://localhost:8080/rest/test

[2022-11-28 09:22:30.057][17][debug][http] [source/common/http/conn_manager_impl.cc:305] [C2] new stream
[2022-11-28 09:22:30.057][17][debug][http] [source/common/http/conn_manager_impl.cc:924] [C2][S16067996592764525365] request headers complete (end_stream=true):
':authority', 'localhost:8080'
':path', '/rest/test'
':method', 'POST'
'user-agent', 'curl/7.68.0'
'accept', '*/*'

and the output

[2022-11-28 09:22:51.959][17][debug][router] [source/common/router/router.cc:400] [C4][S6853706816114715145] no route match for URL '/rest/test'
[2022-11-28 09:22:51.959][17][debug][http] [source/common/http/filter_manager.cc:904] [C4][S6853706816114715145] Sending local reply with details route_not_found
[2022-11-28 09:22:51.959][17][debug][http] [source/common/http/conn_manager_impl.cc:1534] [C4][S6853706816114715145] encoding headers via codec (end_stream=true):
':status', '404'
'date', 'Mon, 28 Nov 2022 09:22:51 GMT'
'server', 'envoy'

maybe there is something wrong with it? 

thanks in advance
