### ISSUE TITLE
envoy.filters.http.dynamic_forward_proxy can it support host_rewrite_regex in addition to host_rewrite_literal

### ISSUE THREAD

**Issue by MyCADDev** [envoyproxy/envoy#24214]
I want to rewrite the route like this and lookup DNS

http://example.com/guid/getstuff

http://guid.example.internal/guid/getstuff

So can something like this be supported - host_rewrite_regex instead of host_rewrite_literal which is currently supported
```
          typed_per_filter_config:
            envoy.filters.http.dynamic_forward_proxy:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
              host_rewrite_regex:
                pattern:
                  regex: "^/(.+)/(.+$)"
                substitution: \1.example.internal
```

The full listener

```
    - name: listener_1
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                generate_request_id: true
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            host_rewrite_path_regex:
                              pattern:
                                regex: "^/(.+)/(.+$)"
                              substitution: \1.example.internal
                            append_x_forwarded_host: true
                            cluster: example_dns
                          typed_per_filter_config:
                            envoy.filters.http.dynamic_forward_proxy:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                              host_rewrite_regex:
                                pattern:
                                  regex: "^/(.+)/(.+$)"
                                substitution: \1.example.internal
                http_filters:
                - name: envoy.filters.http.dynamic_forward_proxy
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                    dns_cache_config:
                      name: dynamic_forward_proxy_cache_config
                      dns_lookup_family: V4_ONLY
                      typed_dns_resolver_config:
                        name: envoy.network.dns_resolver.cares
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                          resolvers:
                            - socket_address:
                                address: "172.16.238.10"
                                port_value: 53
                          dns_resolver_options:
                            use_tcp_for_dns_lookups: true
                            no_default_search_domain: true
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
