### ISSUE TITLE
Support route list for route matcher action

### ISSUE THREAD

**Issue by tony612** [envoyproxy/envoy#24238]
*Title*: Support route list in route matcher action

*Description*:

Now only a single `Route` can be used in router matcher as this code shows: https://github.com/envoyproxy/envoy/blob/4e40d6ad5f98cd3c86f1398bb8990b1d88bdfe92/source/common/router/config_impl.cc#L1880-L1883

But we may need a list of routes under a branch of the matcher tree. `matcher_list` is similar, but not flexible like `RouteMatch `. For example, `RouteMatch ` supports `uri_template`, `headers` and so on.

I wrote an implementation for this: https://github.com/envoyproxy/envoy/compare/main...tony612:route-match-action?expand=1#diff-c1e4a3798005eb4f69d0ea87905f7117810f3c2ef2fd3e06df2d75f3724b5fd7R228

With this new code, we can write config like below, which will be easier than config with only `v3.Route` as matcher's action.

```
route_config:
  virtual_hosts:
  - name: default
    domains: ["*"]
    matcher:
      matcher_tree:
        input:
          name: req-headers
          typed_config:
            "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
            header_name: :path
        prefix_match_map:
          map:
            "/service-1/":
              action:
                name: route
                typed_config:
                  "@type": type.googleapis.com/envoy.config.route.v3.RouteMatchAction
                  routes:
                  - match:
                      path_match_policy:
                        name: envoy.path.match.uri_template.uri_template_matcher
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
                          path_template: "/service-1/foo/{country}/{lang}"
                    route:
                      cluster: svc1
                      path_rewrite_policy:
                        name: envoy.path.rewrite.uri_template.uri_template_rewriter
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.path.rewrite.uri_template.v3.UriTemplateRewriteConfig
                          path_template_rewrite: "/foo/{lang}/{country}"
                  - match:
                      headers:
                      - name: "x-custom"
                        exact_match: "foo"
                    route:
                      cluster: svc1
                      timeout: 5s
```

In my implementation, I added a new message `RouteMatchAction`, which is a wrapper of the route list(like VirtualHost but simpler) and maybe more fields can be added in the future.

If this looks good, I can add tests and send a PR.
