### ISSUE TITLE
Why upstream filters are only available for L3/L4 layers?

### ISSUE THREAD

**Issue by gabrielgiussi** [envoyproxy/envoy#24275]
*Title*: Why upstream filters are only available for L3/L4 layers?

*Description*:
Filters can be defined in upstream clusters only at the [network](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/upstream_filters) L3/L4 level. Why is that? Is there any technical limitation or they were not just implemented for L7 layer yet?

I think I have a use case for such thing although perhaps the current alternative is simple enough that won't justify impl filters for L7 layer by itself.
I'm doing requets to s3 from a wasm filter and the [proxy_dispatch_http_call](https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#proxy_dispatch_http_call) requires passing the cluster name, but if I pass directly the s3 cluster name I can't configure the `AwsRequestSigning` filter, so I had to configure another cluster `token-fetcher` which is the one I call from the wasm filter.

My current config
```yaml
    - name: s3-listener
    address:
      socket_address: { address: 127.0.0.1, port_value: 4141 }
    filter_chains:
      - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: s3-listener
              codec_type: auto
              route_config:
                name: sts
                virtual_hosts:
                  - name: sts
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/"
                        route:
                         cluster: s3         
              http_filters:
                - name: sigv4-signing
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
                    service_name: s3
                    host_rewrite: s3.amazonaws.com
                    region: us-east-1
                    use_unsigned_payload: true
                    match_excluded_headers:
                      - prefix: x-envoy
                - name: envoy.filters.http.router

  - name: token-fetcher
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: token-fetcher
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 4141

  - name: s3
    type: LOGICAL_DNS
    connect_timeout: 2s
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    load_assignment:
      cluster_name: s3
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: s3.amazonaws.com
                    port_value: 443

```

Being able to configure the filter in the cluster I would simplify this configuration avoiding the listener and the `token-fetcher` cluster.
