### ISSUE TITLE
http local rate limit  can not get expected QPS ？

### ISSUE THREAD

**Issue by song0071000** [envoyproxy/envoy#24282]
*Description*:
>
we have local rate limit config as follow:

```
  token_bucket:
    max_tokens: 1000
    tokens_per_fill: 1000
    fill_interval: 1s
```

we send 5k grpc request  in one second to this service,  the success response is only 600-700 a second.
that mean client send 5k request and only get 600-700 request be handled correctly which is not expected (the expectation is almost 1000 ).
why this happened？
is there something we have ignored？

envoy version: 1.19.3
