### ISSUE TITLE
Envoy filter for outbound https traffic

### ISSUE THREAD

**Issue by solarkaka** [envoyproxy/envoy#24281]
I am trying to intercept all outbound http/s traffic from a pod and add a custom header to the request. After reading some documentation I came to the understanding that an envoy filter on SIDECAR_OUTBOUND with some custom lua code would do the trick. So this is the configuration that I did:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: outbound-filter
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.lua
          typed_config:
            '@type': type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
            inlineCode: |
              function envoy_on_request(request_handle)
                  request_handle:logWarn("Hello World")
                  request_handle:headers():add("origin", os.getenv("ISTIO_META_WORKLOAD_NAME"))
              end
```
And it works perfectly fine for http requests. However, it seems that the filter does not run at all when the request is over https.
As such I tried to use the Egress gateway for it. This is what I did
1. Deploy an egress gateway in my k8s cluster
2. Change the outbound mesh traffic to registry only
3. Create a service entry for a particular host
4. Create a gateway kubernetes object which routes the requests from the egress gateway to a particular URL and listens at a particular port
5. Create a virtualService which serves the purpose of making sure that the routing of all http requests that are going to a particular URL are redirected to the egress gateway service and then the egress gateway can send it to its destination which is the final URL

All of this is good, but this can only be done for one particular remote service outside the mesh and for every service I want to add , I would have to add its url in the preexisting serviceentry and basically go over the full loop again.

Is there a way I can do that for all requests going out of my mesh ?
