### ISSUE TITLE
How to configure scoped_routes with scoped_rds ?

### ISSUE THREAD

**Issue by mozartz** [envoyproxy/envoy#24416]
*Description*:
>I am trying configure scoped_rds with filesystem rds. But I got an error `Unexpected RDS resource length: 2`. How can I configure scoped_routes with multi-routes. configure as followed.

start.sh
```
#!bin/bash

docker run --rm \
    --name envoy \
    -v $(pwd)/envoy.yaml:/etc/envoy/envoy.yaml \
    -v $(pwd)/xds:/etc/envoy/xds \
    -p 10002:10002 \
    -p 9081:9081 \
    envoyproxy/envoy:v1.24.0
```

envoy.yaml
```yaml
node:
  cluster: cluster-1
  id: envoy-instance-1

dynamic_resources:
  lds_config:
    resource_api_version: V3
    path_config_source:
      path: "/etc/envoy/xds/lds/lds.yaml"
      watched_directory:
        path: "/etc/envoy/xds/lds"

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9081
```

xds/lds/lds.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: "listener_0"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http_scoped
              http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              scoped_routes:
                name: rds_scoped
                scope_key_builder:
                  fragments:
                    - header_value_extractor:
                        name: "X-Route-Selector"
                        element_separator: ";"
                        index: 0
                scoped_rds:
                  scoped_rds_config_source:
                    resource_api_version: V3
                    path_config_source:
                      path: /etc/envoy/xds/rds/rds_scoped.yaml
                      watched_directory:
                        path: /etc/envoy/xds/rds
                rds_config_source:
                  resource_api_version: V3
                  path_config_source:
                    path: /etc/envoy/xds/rds/rds_scoped_route.yaml
                    watched_directory:
                      path: /etc/envoy/xds/rds
```

**Comment by mozartz** [comment]
rds_scoped.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.route.v3.ScopedRouteConfiguration
    name: route_scope_1
    route_configuration_name: rds_scoped_config_1
    key:
      fragments:
        - string_key: "web1"

  - "@type": type.googleapis.com/envoy.config.route.v3.ScopedRouteConfiguration
    name: route_scope_2
    route_configuration_name: rds_scoped_config_1
    key:
      fragments:
        - string_key: "web2"
```

rds_scoped_route.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: rds_scoped_config_1
    virtual_hosts:
      - name: direct_response_service
        domains: ["*"]
        routes:
          - match:
              prefix: "/"
            direct_response:
              status: 200
              body:
                inline_string: "scoped yay 1\n"

  - "@type": type.googleapis.com/envoy.config.route.v3.RouteConfiguration
    name: rds_scoped_config_2
    virtual_hosts:
      - name: direct_response_service
        domains: ["*"]
        routes:
          - match:
              prefix: "/"
            direct_response:
              status: 200
              body:
                inline_string: "scoped yay 2\n"
```
