### ISSUE TITLE
[Jwt_authn filter] Local reply modification to identify 401 errors

### ISSUE THREAD

**Issue by amiozzo** [envoyproxy/envoy#24427]
***Local reply modification to identity 401 errors***

>We are using jwt_autn filter to validate the signature of two jwt. To guide us we can called them test_1 and the second test_2.
We want to know which one failed (test_1 or test_2). For this we thought that it would be all right to use local reply using two filters: status_code_filter (identify 401) and metadata_filter (we want to know if the first filter passed so we can make sure that the second was the one which failed).
If the first filter pass, it will filled dynamic metadata with test_1 info 
For example:
`{
   "test_1_payload":{
      "field1":"data1",
      "field2":["data2"]
   }
}`
So we code something like this:
```
` - filter:
         and_filter:
                  filters:
                    - status_code_filter:
                        comparison:
                          op: EQ
                          value:
                            default_value: 401
                            runtime_key: jwt_verification_key
                    _**- metadata_filter:
                        matcher:
                          filter: envoy.filters.http.jwt_authn
                          path:
                            - key: test_1_payload
                            - key: field1
                          value:
                            present_match: true
                        match_if_key_not_found: false**_
              headers_to_add: ....`
```

This is not working.  Can anyone know why? The metadata filter is not matching the dynamic data.

**_[Jwt-authn config]_**
```
`test_1:
        issuer: "test"
        local_jwks:
          filename: "..."
          forward: true
        from_headers:
        - name: "header_to_extract_jwt"
        payload_in_metadata: "test_1_payload"`
```
