### ISSUE TITLE
File/Directory watches not set for Generic Secrets via SDS

### ISSUE THREAD

**Issue by ruwaifaa** [envoyproxy/envoy#24481]
*Title*: *GenericSecrets stored in separate files do not have inotify watches*

*Description*:
Unlike for TLS certificates, envoy does not set inotify watches if the secrets are stored using filename as a [datasource](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-datasource) option

In the example config below, envoy won't set inotify watch on `secret.txt` so any changes in that file won't be picked up automatically

envoy.yaml
```
  credentials:
    token_secret:
      name: token
      sds_config:
        path_config_source: 
          path: "/Users/ruwaifaa/token.yaml"

```

token.yaml 
```
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: token
    generic_secret:
      secret:
        filename: secret.txt
```
This happens because SDS API returns an empty vector for datasource filenames for generic secrets  [here](https://github.com/envoyproxy/envoy/blob/086bc865801f2be0c0ac937658115798d9e48682/source/common/secret/sds_api.cc#L209)

Inotify is set for the config file however, so any changes to inline_secret or inline_bytes get propagated properly. The issue only lies when filename option is used

Is someone working on it currently? I figure this would useful for existing oauth2 filter and also when developing custom filters involving generic secrets

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
