### ISSUE TITLE
How to fetch data from initial_metadata field with network.ext_authz

### ISSUE THREAD

**Issue by chengdol** [envoyproxy/envoy#24505]
*Description*:
Hi folks, I am using the [**envoy.filters.network.ext_authz**](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/ext_authz_filter) for tcp proxy external auth, part of my config is shown as below:
```
    filter_chains:
    - filters:
      - name: envoy.filters.network.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.ext_authz.v3.ExtAuthz
          stat_prefix: ext_authz
          grpc_service:
            timeout: 2s
            envoy_grpc:
              cluster_name: ext-authz
            initial_metadata:
            - key: "x-foo"
              value: "bar"
          failure_mode_allow: false
          include_peer_certificate: true
          transport_api_version: V3
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: dest
          cluster: dest
```
I need to pass additional data to auth server so I use the [`initial_metadata`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice) field, from the envoy log I see the key-value pair is in the header of the request.

The **question** is how can I fetch `x-foo` value from the auth grpc server? I have found some [example code](https://github.com/envoyproxy/envoy/blob/a12869fa9e9add4301a700978d5489e6a0cc0526/examples/ext_authz/auth/grpc-service/pkg/auth/v3/auth.go#L33), but looks like they are not working with **envoy.filters.network.ext_authz** but **http.ext_authz** and I got panic runtime error `invalid memory address or nil pointer dereference` if I try to fetch the target header, my code snippet is as below:
```go
auth_pb "github.com/envoyproxy/go-control-plane/envoy/service/auth/v3"

func (s *service) Check(ctx context.Context, r *auth_pb.CheckRequest) (*auth_pb.CheckResponse, error) {
	fmt.Println("received check request")
	foo := r.Attributes.Request.Http.Headers["x-foo"]
	fmt.Println(foo)
	// return nil, fmt.Errorf("error")
	return &auth_pb.CheckResponse{}, nil
}
```

Or if this header way does not work for **network.ext_authz** filter, is there any workaround that I can send additional data to external auth server?

I appreciate it if anyone can share some light on this problem.
