### ISSUE TITLE
Allow request_headers_to_add in weighted clusters

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#2455]
**Allow ability to configure  %headers_to_% at weighted cluster level**

**Description**:
This gives a way to inject headers that are specific to route+weighted cluster combination.

The specific use case I am looking at is to forward `x-destination-cluster` header and some related information to the actual upstream cluster. The upstream envoy can then use `cluster_header: x-destination-cluster` in its vhost configuration.

This will be used by Istio to inject intermediaries between two workloads.
With `subset_lb` there would be additional headers sent.

Following is an example where the proposed istio `via` directive is used.
```yaml
destination:
    name: httpbin
  precedence: 1
  route:
 - labels:
      version: v50
    weight: 90
  - labels:
      version: v51
    weight: 10
    Via:
      Service: inter
      Labels:
        Version: v1
```
This rule says that traffic to `httpbin` host should be sent via the `inter` service.

The original rule
```yaml
    virtual_hosts:
    - domains:
      - httpbin
      - 10.7.250.118:8000
      - 10.7.250.118
      name: httpbin.default.svc.cluster.local|http
      routes:
      - decorator:
          operation: details-default
        match:
          prefix: /
        route:
          timeout: 0s
          weighted_clusters:
            clusters:
            - name: out.httpbin.default.svc.cluster.local|http|version=v50
              weight: 90
            - name: out.httpbin.default.svc.cluster.local|http|version=v51
              weight: 10
```
becomes --

```yaml
    virtual_hosts:
    - domains:
      - httpbin
      - 10.7.250.118:8000
      - 10.7.250.118
      name: httpbin.default.svc.cluster.local|http
      routes:
      - decorator:
          operation: details-default
        match:
          prefix: /
        route:
          timeout: 0s
          weighted_clusters:
            clusters:
            - name: out.inter.default.svc.cluster.local|http|version=v1
              weight: 90
              request_headers_to_add:
              - key: x-destination-cluster
                value: out.httpbin.default.svc.cluster.local|http|version=50
            - name: out.inter.default.svc.cluster.local|http|version=v1
              weight: 10
              request_headers_to_add:
              - key: x-destination-cluster
                value: out.httpbin.default.svc.cluster.local|http|version=51
```

Here is a link to the istio doc.
 https://goo.gl/wKNf87
