### ISSUE TITLE
Can I communicate with zookeeper from a wasm filter?

### ISSUE THREAD

**Issue by gabrielgiussi** [envoyproxy/envoy#24568]
*Title*: Can I communicate with zookeeper from a wasm filter?

*Description*:
I want to create an ephemeral node on envoy bootstrap so using a wasm singleton context and do it on `proxy_on_context_create` seems a good place.
But the ABI only allow me to send http requests to a cluster and zookeeper seems to have a binary protocol over TCP. 
Is there any way I could communicate to the zookeeper cluster from the wasm filter?

Also, I saw this [example configuration](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/zookeeper_proxy_filter) for the zookeeper proxy but I don't understand why the cluster is configured with http
```yaml
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
```

By the way, how did you implemented the zookeeper proxy? Just looking at source code from the zk client? I couldn't find the protocol documented anywhere in zk docs.
