### ISSUE TITLE
host_rewrite_path_regex and regex_rewrite together

### ISSUE THREAD

**Issue by superset1** [envoyproxy/envoy#24588]
*Title*: *How can I use these commands together: host_rewrite_path_regex and regex_rewrite*

*Description*:
I have url https://envoy.workspace.svc.k8s.stage-dp/ns/suppliers/suppliers-portal-core/one
And envoy config:
```
                    routes:
                    - match:
                        prefix: /
                      route:
                        host_rewrite_path_regex:
                          pattern:
                            google_re2: {}
                            regex: ^/ns/([^/]+)/([^/]+)(/.*|)$
                          substitution: \1.\2.svc.k8s.stage-dp
                        append_x_forwarded_host: true

                        regex_rewrite: 
                          pattern:
                            google_re2: {}
                            regex: ^/ns/([^/]+)/([^/]+)(/.*|)$
                          substitution: \3
```

In this case regex_rewrite change uri and host_rewrite_path_regex does not work correct. 
host_rewrite_path_regex thinks that host is `/one`
I want to use dynamic_forward_proxy_cluster_http and automatically change:
1) uri `ns/suppliers/suppliers-portal-core/one` to `one`
2) host `envoy.workspace.svc.k8s.stage-dp` to `suppliers.suppliers-portal-core.svc.k8s.stage-dp`
3) So the final request should change
- from: `https://envoy.workspace.svc.k8s.stage-dp/ns/suppliers/suppliers-portal-core/one`
- to: `https://suppliers.suppliers-portal-core.svc.k8s.stage-dp/one`

Note: I cant use host_rewrite_literal because I have very many URI and fqdn in Kubernetes. I have to use regex.
