### ISSUE TITLE
When using TCP tunneling and streaming, connection closing does not cause filter chain draining

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#24704]
*Title*: When using TCP tunneling, client closing a connection does not cause filter chain draining

*Description*:
Say there is the following setup:
1. TCP client
2. Envoy process with the following filters:
a. Custom passthrough filter
b. TCP proxy filter with TCP tunneling (upgrade to HTTP/2) applied
4. HTTP/2 server

After this setup running, the TCP client opens a connection, then streams data for 5 seconds, then waits for 5 seconds and closes the connection using FIN TCP flag. The outcome observed is that the HTTP/2 server is aware of the connection being closed, but in Envoy perspective, the filter chain is not being drained, and all filters are still alive (although upstream and downstream both have closed the connection).

Further information per local debugging:
1. The destructor for the custom passthrough filter was not called
2. [void Filter::onDownstreamEvent(Network::ConnectionEvent event)](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/tcp_proxy.cc#:~:text=void%20Filter%3A%3AonDownstreamEvent(Network%3A%3AConnectionEvent%20event)%20%7B) is never called (in common/tcp_proxy/tcp_proxy.cc, line 661)
3. [HttpUpstream::onDownstreamEvent(Network::ConnectionEvent event)](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/upstream.cc#:~:text=HttpUpstream%3A%3AonDownstreamEvent(Network%3A%3AConnectionEvent%20event)%20%7B) is never called (in common/tcp_proxy/upstream.cc, line 100)
4. [void HttpUpstream::doneReading()](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/upstream.cc#:~:text=void%20HttpUpstream%3A%3AdoneReading()%20%7B) is never called (in common/tcp_proxy/upstream.cc, line 142)
5. [void HttpUpstream::doneWriting()](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/upstream.cc#:~:text=void%20HttpUpstream%3A%3AdoneWriting()%20%7B) is being called once after the HTTP/2 server closes the connection (in common/tcp_proxy/upstream.cc, line 149), however read_half_closed_ is false at this time (which is because doneReading was not called)
6. I have enabled 'connection half close', but this still happens. I am not sure this is really related, because it is expected that end_stream from downstream would never be true, regardless of half close state. That's because the TCP client closes the connection with a delayed TCP packet, and not in conjunction with a data payload.
7. Seems like what could have solved it, is if "doneReading" was called. However, the only place this function is being called is in [decodeData](https://github.com/envoyproxy/envoy/blob/main/source/common/tcp_proxy/upstream.h#:~:text=parent_.doneReading()%3B), when end_stream is true. But again, it would never be true.
In all the sections above, the determination if a function was called or not was made by printing logs and verifying that they do not exist in the output.

I'm not an Envoy expert so I might have missed something here, but overall, the observable behavior is not as expected. Seems to me that calling doneReading when FIN event is received would solve this, but I am still not sure.

*Config*:
```
- name: custom_filter
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.custom_filter.CustomFilterConfig
- name: tcp_proxy
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
  stat_prefix: tcp_stats
  cluster: "upstream"
  tunneling_config:
	hostname: host.com:443
	use_post: true
	post_path: <path>
```
