### ISSUE TITLE
How to perform CN/Hostname verification in UpstreamTlsContext?

### ISSUE THREAD

**Issue by gabrielgiussi** [envoyproxy/envoy#24714]
### Description:

I'm trying to force envoy to perform CN/Hostname validation and I was able to do it but with a more complex configuration than what I was expecting based on existing configuration.
My goal is to make a request to envoy using host `abc`, and route to a cluster that use a domain name assigned by k8s, `abc-staging.default.svc.cluster.local` but this service presents a certificate with cn=*.envoy.com and I want to validate the host matches the certificate subject name.
The only way I was able to force envoy to do this check is using `auto_sni` in `HttpProtocolOptions` in the cluster, only then I'm getting the following error

> "upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED"

#### What is currently working

Listener configuration
```yaml
resources:
  - name: outbound-listener
    "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    address:
      socket_address:
        protocol: TCP
        address: ${DOWNSTREAM_BIND_ADDR}
        port_value: ${OUTBOUND_DOWNSTREAM_PORT}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: egress_http
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: client
              domains:
              - "abc"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: abc-cluster
          common_http_protocol_options:
            max_stream_duration: 900s
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |

                function envoy_on_request(handle)
                  handle:headers():add("X-Sni", "abc.envoy.com")
                end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

Cluster configuration
```yaml
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: abc-cluster
  connect_timeout: 1.25s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  typed_extension_protocol_options:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      common_http_protocol_options:
        idle_timeout: 600s
        max_connection_duration: 600s
      auto_config: {}
      upstream_http_protocol_options:
        auto_sni: true
        auto_san_validation: true
        override_auto_sni_header: "X-Sni"
  load_assignment:
    cluster_name: abc-cluster
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: abc-staging.default.svc.cluster.local
                  port_value: 443
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      common_tls_context:
        tls_certificates:
          - certificate_chain: {"filename": "/etc/credentials/client_cert.pem"}
            private_key: {"filename": "/etc/credentials/client_key.pem"}
        validation_context:
          trusted_ca:
            filename: /etc/ssl/certs/ca-certificates.crt
```

#### Using `host_rewrite_literal`

If I configure the router to rewrite the host to avoid the custom X-Sni header and the lua filter, this doesn't seem to have effect on the TLS handshake because I captured traffic and it is still presenting `abc` in the SNI extension.
Why the host is overwritten after the TLS handshake? Because I log the host header in the access log and it is correctly set to abc.envoy.com.

```yaml
route_config:
  name: local_route
  virtual_hosts:
  - name: client
    domains:
    - "abc"
    routes:
    - match:
        prefix: "/"
      route:
        cluster: abc-cluster
        host_rewrite_literal: abc.envoy.com.  # added!
```

In the cluster I removed the `override_auto_sni_header` so the authority/host header is used for the sni, but it presents `abc` instead of `abc.envoy.com`

#### Using `sni` in UpstreamTlsContext

I've also tried removing `upstream_http_protocol_options` and using [sni](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#envoy-v3-api-field-extensions-transport-sockets-tls-v3-upstreamtlscontext-sni) and looking at captured traffic it works as expected since is presenting `abc.envoy.com` as server name indication but envoy doesn't perform the CN/Hostname check, i.e. if I set `sni: abc.baddomain.com` the TLS handshake and the request succeed. 

```yaml
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: abc-cluster
    connect_timeout: 1.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        common_http_protocol_options:
          idle_timeout: 600s
          max_connection_duration: 600s
        auto_config: {}
    # removed upstream_http_protocol_options
    load_assignment:
      cluster_name: abc-cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: abc-staging.default.svc.cluster.local
                    port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: abc.baddomain.com # added!
        common_tls_context:
          tls_certificates:
            - certificate_chain: {"filename": "/etc/credentials/client_cert.pem"}
              private_key: {"filename": "/etc/credentials/client_key.pem"}
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
```

Shouldn't setting SNI here force the validation? Otherwise is like a configuration with no effect.

**Comment by snowp** [comment]
I believe you want to use `match_typed_subject_alt_names` or `match_subject_alt_names` on the validation context. 

Specifying the SNI to use is used to allow specifying an arbitrary string for use in SNI-based routing, and for better or worse is configured independently of how the SNI is validated

**Comment by gabrielgiussi** [comment]
Thanks, this configuration does the validation and presents the correct sni name.
```yaml
sni: abc.envoy.com
common_tls_context:
  tls_certificates:
    - certificate_chain: {"filename": "/etc/credentials/client_cert.pem"}
      private_key: {"filename": "/etc/credentials/client_key.pem"}
  validation_context:
    match_typed_subject_alt_names:
    - san_type: DNS
      matcher:
        exact: "*.envoy.com"
    trusted_ca:
      filename: /etc/ssl/certs/ca-certificates.crt
```

However the thing I can't understand how it should work is the `host_rewrite_literal` in the route because right now I'm sending as sni `abc.envoy.com` but `abc` in the host header and the server is complaining (although I can disable the check or even adding the header in a lua filter works, but I want to avoid this).


Using a wildcard domain is working (the host ends up being abc.envoy.com)
```yaml
route_config:
  name: local_route
  virtual_hosts:
  - name: abc-client
    domains:
    - "*"
    routes:
    - match:
        prefix: "/"
      route:
        cluster: abc-cluster
        host_rewrite_literal: abc.envoy.com
```

But this doesn't work, in this case the host is not being rewritten and is sent as abc so I'm getting the sni!=host validation in the target server. I have workarounds but I want to understand why this is happening.

```yaml
route_config:
  name: local_route
  virtual_hosts:
  - name: abc-client
    domains:
    - "abc"
    routes:
    - match:
        prefix: "/"
      route:
        cluster: abc-cluster
        host_rewrite_literal: abc.envoy.com
```
