### ISSUE TITLE
Is it possible to make health check and custom routing-hash work together

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#24731]
I'm using Envoy as the gateway of my backend of micro-services.

I have deployed three same services, which offer the service of meeting. Each of HTTP requests of clients contains a meeting ID, so at the Envoy side, I have to route the requests with the same meeting ID to the same meeting services.

Here is how a request looks like:
```
https://www.example.com/12345/other_info
```

What I do is to extract the meeting ID from a request, hash the meeting ID, add the hash value into the header of the request, and route the request by the hash value.

Here is the main config of Envoy:
```
http_filters:
- name: envoy.filters.http.lua
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
    inline_code:
      function envoy+on_request(request_handle)
        request_handle:headers():add("x-hash-value", tonumber(string.match(request_handle:body():path(), "%d\/")) % 3)
      end
```
As you see, I get the meeting ID and moduled it by 3, and add the result into the header of the request.

Then I can route it with the load-balancing way:
```
http_filters:
- name: envoy.filters.http.header_to_medatada
  typed_config: type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
  request_rules:
  - headers: x-hash-value
    on_header_present:
      metadata_namespace: envoy.lb
      key: ...
```

Now I can route all of requests to the three upstream services.

But, I don't know what if I enable the health check mechanism of Envoy and at some moment, one of the three upstream services is removed by the envoy... As you see, the lua script above is static, meaning that if one service is removed, I don't think the script could work as expected...

For me, it doesn't seem that I couldn't enable the health check mechanism if I used some custom routing-hash...

Is there some method to make the health check mechanism and custom routing-hash work together?
