### ISSUE TITLE
Rerouting requests to a self listener from mirror traffic increases upstream_rq_pending_overflow

### ISSUE THREAD

**Issue by sjanel** [envoyproxy/envoy#24788]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
Configuration of listener branched on envoy upstream misconfigured with lots of `upstream_rq_pending_overflow`

*Description*:
I have an envoy setup configured as both an HTTP frontend and a request mirror policy to a shadow cluster.
I have two listeners: one plugged on the external traffic configured as untrusted traffic as explained [here](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge.html?highlight=filter_chains), one taking self requests from a cluster (`self`) receiving the mirrored requests and rewriting the host name header as an alternative solution to solve problem described [here](https://github.com/envoyproxy/envoy/issues/9094).

*Particularities of underlying application*:
It is a Spring boot java app listening to port 8000 on `localhost` for the `main` which can have up to 30 seconds of response time (hence the timeouts set to `32s`).
It is the same in the `staging` cluster but external.

The configuration looks like this:
```
 static_resources:
      listeners:
      - name: external_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8888
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: external_downstream_http
              # Below config taken from https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge.html?highlight=filter_chains
              use_remote_address: true
              normalize_path: true
              merge_slashes: true
              path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
              common_http_protocol_options:
                idle_timeout: 3600s  # 1 hour
                headers_with_underscores_action: REJECT_REQUEST
              http2_protocol_options:
                max_concurrent_streams: 1000
                initial_stream_window_size: 65536  # 64 KiB
                initial_connection_window_size: 1048576  # 1 MiB
              stream_idle_timeout: 620s  # 10 mins, must be disabled for long-lived and streaming requests
              request_timeout: 300s  # 5 mins, must be disabled for long-lived and streaming requests
              codec_type: AUTO
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      host_rewrite_literal: "localhost"
                      cluster: main
                      request_mirror_policies:
                      - cluster: self
                      timeout: 32s
      - name: internal_listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8889
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: internal_downstream_http
              codec_type: AUTO
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      auto_host_rewrite: "true"
                      cluster: staging
                      timeout: 32s
      clusters:
      # This cluster represents the app flow
      - name: main
        type: STATIC
        load_assignment:
          cluster_name: main
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8000
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 800s
            explicit_http_config:
              http2_protocol_options:
                max_concurrent_streams: 500
      - name: self
        type: STATIC
        load_assignment:
          cluster_name: self
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 8889
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 600s
            explicit_http_config:
              http2_protocol_options:
                max_concurrent_streams: 300
                initial_stream_window_size: 65536  # 64 KiB
                initial_connection_window_size: 1048576  # 1 MiB
      - name: staging
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: staging
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: <some external address that will receive shadow traffic>
                    port_value: 443
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: <external address from upwards>
            common_tls_context:
              validation_context:
                trusted_ca:
                  filename: /etc/ssl/certs/ca-certificates.crt
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            common_http_protocol_options:
              idle_timeout: 300s
            explicit_http_config:
              http2_protocol_options:
                max_concurrent_streams: 300
```
The problem I am facing concerns `self` cluster. Looking at the `/stats`, it drops a significant percentage of requests and return HTTP 503 errors, which seem to come from `upstream_rq_pending_overflow`. Here is an extract of the `self.upstream` stats, where all are included except the counters set at 0:
```
cluster.self.default.total_match_count: 1
cluster.self.http2.streams_active: 959
cluster.self.http2.tx_reset: 662
cluster.self.internal.upstream_rq_200: 178064
cluster.self.internal.upstream_rq_2xx: 178064
cluster.self.internal.upstream_rq_302: 2
cluster.self.internal.upstream_rq_3xx: 2
cluster.self.internal.upstream_rq_400: 1
cluster.self.internal.upstream_rq_4xx: 1
cluster.self.internal.upstream_rq_503: 6167
cluster.self.internal.upstream_rq_504: 848
cluster.self.internal.upstream_rq_5xx: 7015
cluster.self.internal.upstream_rq_completed: 185082
cluster.self.membership_change: 1
cluster.self.membership_healthy: 1
cluster.self.membership_total: 1
cluster.self.upstream_cx_active: 22
cluster.self.upstream_cx_http2_total: 22
cluster.self.upstream_cx_rx_bytes_buffered: 34397
cluster.self.upstream_cx_rx_bytes_total: 1282822326
cluster.self.upstream_cx_total: 22
cluster.self.upstream_cx_tx_bytes_total: 93481829
cluster.self.upstream_rq_200: 178064
cluster.self.upstream_rq_2xx: 178064
cluster.self.upstream_rq_302: 2
cluster.self.upstream_rq_3xx: 2
cluster.self.upstream_rq_400: 1
cluster.self.upstream_rq_4xx: 1
cluster.self.upstream_rq_503: 6167
cluster.self.upstream_rq_504: 848
cluster.self.upstream_rq_5xx: 7015
cluster.self.upstream_rq_active: 959
cluster.self.upstream_rq_completed: 185082
cluster.self.upstream_rq_pending_overflow: 6166
cluster.self.upstream_rq_pending_total: 22
cluster.self.upstream_rq_timeout: 662
cluster.self.upstream_rq_total: 179874
cluster.self.upstream_rq_tx_reset: 662
```

Could you please help me to understand the root cause of the issue here and to fix it?

Thanks a lot in advance
