### ISSUE TITLE
gRPC reverse bridge uses many more connections than not using reverse bridge

### ISSUE THREAD

**Issue by KamiKuroro** [envoyproxy/envoy#24786]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *gRPC reverse bridge uses many more connections than not using reverse bridge*

*Description*:

The set up consists of a grpc client behind an envoy, which acts as a client proxy, and a grpc server behind another envoy which acts as a server proxy.

Client's envoy uses grpc reverse bridge to convert client's grpc requests into http/1 requests, which are sent over to server's envoy running on a remote machine. Server's envoy uses bridge to convert http/1 requests back to grpc requests, which are sent over to the upstream grpc server.

Both the client and the server has another set of ports opened and proxied that aren't using bridge. This is used as a comparison.

The grpc client and the server are borrowed from envoy/examples/grpc-bridge. In my test, the client sends over set requests to the server. I didn't use the python client, wrote one in go that uses the same protobuf as the server in the envoy example.

There are 2 things that puzzles me when I run the test in cases of using reverse bridge/bridge and not using reverse bridge/bridge:

i) When I use the client to concurrently send 1000 set requests over to the server, through envoy with reverse bridge, client's envoy admin statistics "/clusters" shows e.g. cx_active::597, cx_active can go up to hundreds. Whereas not using reverse bridge/bridge, the same number of requests resolves to cx_active::1, which seems only to use 1 active connection.

The problem I have with using reverse bridge/bridge is that as "cx_active" go up, for example to 1024, with the default settings, the following requests would fail with resp flag UT, and client gets "rpc error: code = Unavailable, desc = upstream timeout", and the UT requests in client's envoy grpc logs also shows "-" for the upstream host section.

ii) For the grpc requests that are successfully sent over bridge, client's envoy admin statistics "/clusters" collected all the successful requests under "rq_error", while the grpc logs show these requests' resp code to be 200, and these requests indeed were successful as the server did receive them, and the client did get the right responses without error. when checking "/stats", the requests were collected under "rq_200" and "rq_2xx", an example of this is shown below.

"/clusters"
backend-proxy::xxx.xxx.xxx.x:9003::rq_active::0
backend-proxy::xxx.xxx.xxx.x:9003::rq_error::21
backend-proxy::xxx.xxx.xxx.x:9003::rq_success::0
backend-proxy::xxx.xxx.xxx.x:9003::rq_timeout::0
backend-proxy::xxx.xxx.xxx.x:9003::rq_total::21

"/stats"
cluster.backend-proxy.http1.response_flood: 0
cluster.backend-proxy.internal.upstream_rq_200: 21
cluster.backend-proxy.internal.upstream_rq_2xx: 21
cluster.backend-proxy.internal.upstream_rq_completed: 21

In comparison, successful grpc requests sent through envoy without using bridge, "/clusters" collected them under "rq_success".

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

## envoy version
af790e2f2baa0b124c0e5e368a38cbd36694b91f/1.21.0-dev/Clean/RELEASE/BoringSSL
built using Dockerfile taken from envoy/examples/grpc-bridge, which uses "envoyproxy/envoy-dev:latest"

## client envoy config
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          add_user_agent: true
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          stat_prefix: egress_http
          common_http_protocol_options:
            idle_timeout: 0.840s
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: backend-proxy
          http_filters:
          - name: envoy.filters.http.grpc_http1_reverse_bridge
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_http1_reverse_bridge.v3.FilterConfig
              content_type: application/grpc
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9006
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          add_user_agent: true
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          stat_prefix: egress_http
          common_http_protocol_options:
            idle_timeout: 0.840s
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
                - match:
                    prefix: "/"
                    grpc: {}
                  route:
                    cluster: backend-proxy-no-bridge
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: backend-proxy
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http_protocol_options: {}
    load_assignment:
      cluster_name: backend-proxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: xxx.xxx.xxx.x
                port_value: 9003
  - name: backend-proxy-no-bridge
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: backend-proxy-no-bridge
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: xxx.xxx.xxx.x
                port_value: 9005
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

## server envoy config
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9003
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: backend_grpc_service
          http_filters:
          - name: envoy.filters.http.grpc_http1_bridge
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_http1_bridge.v3.Config
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9005
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
                - match:
                    prefix: "/"
                    grpc: {}
                  route:
                    cluster: backend_grpc_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: backend_grpc_service
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: backend_grpc_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "host.docker.internal"
                port_value: 9004
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8002
```
