### ISSUE TITLE
How can I redirect the traffic coming on port 80 to https without altering the URL?

### ISSUE THREAD

**Issue by ghevge** [envoyproxy/envoy#24814]
I am trying to redirect all the http traffic hitting my envoy proxy, to 443 port.

What I did so far, partially works, in the sense that the requests get redirected to 443 port but the URL gets altered (some context elements are being removed)

This is how my envoy yaml looks like 

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  path_redirect: "/"
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config: {}
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    per_connection_buffer_limit_bytes: 10000000 #~10MB
    filter_chains:
    - filters:
    ........
```
 With this configuration a URL like : **http://localhost/p/index.html?page=1&search=tt&locale=en&dk=5**
gets changed to : **https://localhost/?page=1&search=tt&locale=en**

**p/index.html** gets removed from the URL

If I leave only the  https_redirect: true (remove the   path_redirect: "/") redirection doesn't work at all.

Any idea how I can achieve  this redirects without altering the URL ?

Thanks

PS: my envoy version is: envoyproxy/envoy-alpine:v1.21.5
