### ISSUE TITLE
Why doesn't the DestinationIPInput work with UDP proxy

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#24834]
I have a UDP server, which is deployed on the server `57.66.233.9`. It is listening the port `10000`.
Now I deployed an Envoy on another server `122.22.22.22`, which is used as a gateway of the UDP server. Here is the config of Envoy:
```
static_resources:
  - name: listener_svr_udp
    enable_reuse_port: true
    address:
      socket_address: {address: 0.0.0.0, port_value: 10000}
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: ingress_udp
        cluster: cluster_svr_udp
clusters:
  - name: cluster_svr_udp
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_svr_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: 57.66.233.9, port_value: 10000}
```

So here is how it looks like:
```
client -> 122.22.22.22:10000 ->57.66.233.9:10000
```
It works as exptected.

After reading the doc: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/udp_proxy, I'm trying to learn how to configure some routing rules for UDP. So I change the config of the Envoy as below:
```
static_resources:
  - name: listener_svr_udp
    enable_reuse_port: true
    address:
      socket_address: {address: 0.0.0.0, port_value: 10000}
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: ingress_udp
        matcher:
          matcher_list:
            matchers:
            - predicate:
                single_predicate:
                  input:
                    name: envoy.matching.inputs.destination_port
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationPortInput
                  value_match:
                    exact: "10000"    # the destination port of each UDP packet should be 10000, am I right?
              on_match:
                matcher:
                  matcher_tree:
                    input:
                      name: envoy.matching.inputs.destination_ip
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.DestinationIPInput
                    exact_match_map:
                      map:
                        "57.66.233.9":    # the destination ip of each UDP packet should be... hmm, I don't know...
#                        "122.22.22.22":
                          action:
                            name: route
                            typed_config:
                              '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                              cluster: cluster_svr_udp
                  on_no_match:
                    action:
                      name: route
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                        cluster: cluster_jitsi_udp2    # an illegal cluster
clusters:
  - name: cluster_svr_udp
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_svr_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: 57.66.233.9, port_value: 10000}
```
As you see, I tried to add such a rule:
If the destination port of UDP packet is `10000` and the destination IP of UDP packet is `57.66.233.9`, route the UDP packet to the cluster_svr_udp, otherwise, route the UDP packet to an illegal cluster.

To my surprise, this is not working. It doesn't seem that the UDP packets are routed to the cluster_svr_udp. I've also changed the destination IP to `122.22.22.22` but nothing changed.

Then I reused the first config of Envoy, which works without any error, and at the same time, I tried to capture the UDP packets on the Envoy server(`122.22.22.22`). Here is a part of output:
```
00:42:23.902200 IP (tos 0x0, ttl 64, id 47351, offset 0, flags [DF], proto UDP (17), length 104)
    mirror-dfx0.novalocal.56166 > 57.66.233.9.ndmp: [bad udp cksum 0xd5ed -> 0xe2de!] UDP, length 76
        0x0000:  4500 0068 b8f7 4000 4011 ac05 ac10 0034  E..h..@.@......4
        0x0010:  3a3f ef04 db66 2710 0054 d5ed 80c8 0006  :?...f'..T......
        0x0020:  8c16 0e1e 357a 3056 fbc4 cf71 b776 d5d9  ....5z0V...q.v..
        0x0030:  f082 7096 9dc3 3cdf 3755 e6e7 b95c 0ecb  ..p...<.7U...\..
        0x0040:  3826 0872 6e84 d90d d379 fb57 df2c 6a5a  8&.rn....y.W.,jZ
        0x0050:  5566 19ae ff59 78eb 4a6a 6e64 9279 6e92  Uf...Yx.Jjnd.yn.
        0x0060:  c797 bf1c 8000 007f                      ........
00:42:23.902288 IP (tos 0x0, ttl 109, id 7864, offset 0, flags [none], proto UDP (17), length 1214)
    214.23.129.181.world-lm > mirror-dfx0.novalocal.ndmp: [udp sum ok] UDP, length 1186
```
`214.23.129.181` is the IP of the client, `mirror-dfx0.novalocal` is the localhost(`127.0.0.1`) of the Envoy server (`122.22.22.22`), `57.66.233.9` is the IP of the UDP server. So it seems that the DestinationIPInput should be `57.66.233.9`? But as I said, it's not working...

Is there something wrong? Have I misunderstood the meaning of DestinationIPInput and/or DestinationPortInput?

BTW, the version of Envoy that I used is 1.22.0.
