### ISSUE TITLE
Add %ORIGINAL_DST% as a header variable

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#2484]
**Add %ORIGINAL_DST% as a header variable**

*Description*:
When the original destination `ip` as resolved by the client is disregarded by the local proxy, it may still be relevant to an upstream. 

This enables configuration like
```yaml
request_headers_to_add:
- key: x-original-destination
  value: %ORIGINAL_DST%
```

For reference istio via directive: https://docs.google.com/document/d/1BGi18QnpqceEMzGAPWlzOTvlu65QRvbiWtyWK9jtddU/edit#heading=h.ouc0ih1n6vge
