### ISSUE TITLE
Support Route Entry Metadata in External Authorization Filter

### ISSUE THREAD

**Issue by RiverPhillips** [envoyproxy/envoy#25134]
*Title*: *Support Route Entry Metadata in External Authorization Filter*

*Description*:
External Authorization currently supports passing Dynamic Metadata. I would like to be able to pass metadata statically per route. This enhancement was made to the Rate Limiting filter in #13269 and I foresee the changes required by the External Authorization filter to be broadly similar.

After the changes it  should be possible to configure it as follows:

``` yaml
metadata:
  filter_metadata:
    envoy.filters.external_authorization:
      foo: bar
```
This should result in `foo` being set on the filterMetadata map passed to ext_authz Check method
