### ISSUE TITLE
ext_proc panic when lua respond directly and grpc_service is configured at route level

### ISSUE THREAD

**Issue by scrocquesel** [envoyproxy/envoy#25219]
*Title*: *ext_proc panic when lua respond directly and grpc is configured per route*

*Description*:

I'm trying to configure and enable ext_proc only for some route. Globally, the filter config do not provide `grpc_service`. At `virtual_hosts` level, filter is disabled. Complete filter config is only provided at `route` level when required.

I combine ext_proc with a lua filter that can respond directly on some context.

When lua do not respond directly, ext_proc works correcly.
When lua do respond directly, ext_proc panic and complains about grpc_service not being set. It seems that in this case, the filter do not use the config override and use only the `http_filters` level config which by default tries to `SEND` response headers to an unconfigured grpc_service. Setting `processing_mode/response_header_mode` to `SKIP` at  `http_filters` level, effectively avoid the call to grpc.

I expect the lua response to be processed by ext_proc with route level overrides.

Use the following filter chain to reproduce

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                              status: 404
                              body:
                                inline_string: "not found"
                          # route:
                          #   cluster: service_httpbin
                          typed_per_filter_config:
                            envoy.filters.http.ext_proc:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                              overrides:
                                processing_mode:
                                  request_header_mode: "SEND"
                                  response_header_mode: "SKIP"
                                  request_body_mode: "NONE"
                                  response_body_mode: "BUFFERED"
                                  request_trailer_mode: "SKIP"
                                  response_trailer_mode: "SKIP"
                                grpc_service:
                                  envoy_grpc:
                                    cluster_name: ext_proc_cluster
                      typed_per_filter_config:
                        envoy.filters.http.ext_proc:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                          disabled: true
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string: |
                          function envoy_on_request(request_handle)
                            request_handle:respond( {[":status"] = "403"}, "Forbidden")
                          end
                  - name: envoy.filters.http.ext_proc
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                      failure_mode_allow: false
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: ext_proc_cluster
      type: STATIC
      connect_timeout: 0.25s
      http2_protocol_options: {}
      load_assignment:
        cluster_name: ext_proc_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 18080
```

` curl -v -H "host: http.domain.com"  --resolve  http.domain.com:8080:127.0.0.1  http://http.domain.com:8080/status/404`

crash envoy with a panic

*Logs*:
```
[2023-01-27 22:51:41.278][11625][debug][http] [source/common/http/filter_manager.cc:917] [C1][S16806786532637578606] Preparing local reply with details lua_response
[2023-01-27 22:51:41.278][11625][debug][lua] [source/extensions/filters/common/lua/lua.cc:42] coroutine yielded
[2023-01-27 22:51:41.278][11625][debug][http] [source/common/http/filter_manager.cc:959] [C1][S16806786532637578606] Executing sending local reply.
[2023-01-27 22:51:41.278][11625][debug][ext_proc] [source/extensions/filters/http/ext_proc/ext_proc.cc:122] Opening gRPC stream to external processor
[2023-01-27 22:51:41.278][11625][critical][assert] [source/common/grpc/async_client_manager_impl.cc:131] panic: unset oneof
```

`version: 9184b84cd0dcb3a6c57eb44b177d91c70e1a0901/1.25.0/Clean/RELEASE/BoringSSL`
