### ISSUE TITLE
Rotating upstream Redis password at at runtime

### ISSUE THREAD

**Issue by dceravigupta** [envoyproxy/envoy#25217]
I'm looking for ways to rotate upstream redis password dynamically at runtime without the need to restart envoy proxy. Seems like is it not possible to use SDS to supply upstream redis password. Are there any other ways to achieve it?

Here is my sample upstream cluster config
```
  clusters:
  - name: redis_cluster
    type: STRICT_DNS
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: abc.redis.net
                port_value: 6380
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
    typed_extension_protocol_options:
      envoy.filters.network.redis_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
        auth_password:
          inline_string: "password" <-- want to rotate this password without need to restart envoy process
```

Scenario: I was trying to use Envoy as Redis proxy with AWS ElastiCache with IAM Authentication where we need to use short-lived IAM authentication token instead of a long-lived password. Hence I need a way to rotate the upstream Redis auth password periodically.

From AWS [doc](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth-iam.html): 
"An IAM authenticated connection to ElastiCache for Redis will automatically be disconnected after 12 hours. The connection can be prolonged for 12 hours by sending an AUTH or HELLO command with a new IAM authentication token."
