### ISSUE TITLE
Logging: `omit_empty_values: true` does not work for nested log fields

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#25211]
*Description*:
The setting `omit_empty_values: true` does not work for nested JSON log fields.

Example configuration (excerpt):
```
access_log:
  - name: envoy.access_loggers.stdout
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
      log_format:
        json_format:
          timestamp: "%START_TIME%"
          field_1:
            field_1_1: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
            field_1_2: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
          field_2: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
        omit_empty_values: true
```

If the request header "X-FIELD-DOES-NOT-EXIST" really does not exist, then this is logged:
```
{"timestamp":"2023-01-27T15:59:44.142Z","field_1":{}}
```

The fields `field_1_1` and `field_1_2` have been removed properly, but `field_1` is now also empty and it should be removed too.

The expected log output is:
```
{"timestamp":"2023-01-27T15:59:44.142Z"}
```

*Repro steps*:
Start envoy with the given configuration and run `curl http://localhost:10000/`.

*Config*:
The complete Envoy configuration:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          scheme_header_transformation:
            scheme_to_overwrite: https
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                log_format:
                  json_format:
                    timestamp: "%START_TIME%"
                    field_1:
                      field_1_1: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
                      field_1_2: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
                    field_2: "%REQ(X-FIELD-DOES-NOT-EXIST)%"
                  omit_empty_values: true
  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```

*Logs*:
Already discussed above.
