### ISSUE TITLE
Don't require pseudo-headers in Lua requests handler httpCall

### ISSUE THREAD

**Issue by CharlieC3** [envoyproxy/envoy#25250]
*Title*: Don't require pseudo-headers in Lua requests handler httpCall

*Description*:

Related to [this issue](https://github.com/envoyproxy/envoy/issues/25190) for my situation, I'm trying to use the [Lua httpCall function](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter#httpcall) to contact various GCP services during certain requests Envoy handles. Through my testing with curl and postman, it seems the request fails when it includes a pseudo-header (e.g. `:authority`, `:method`, or `:path`). Excluding these pseudo-headers results in a successful request. For some context, I'm not sure why Google would be rejecting requests with these pseudo-headers, but it seems they are.

However, the three aforementioned pseudo-headers currently must be defined when using the `httpCall` Lua function, otherwise the function will fail with the following error:
`http call headers must include ':path', ':method', and ':authority'"`
[I believe this is the related code.](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/lua/lua_filter.cc#L169)

Is there any way I can get around this requirement with the `httpCall` Lua function? Would it require a code change?

**Comment by wbpcode** [comment]
These pseudo-headers won't be send to server because envoy http1 codec only use these headers to construct request line of http1. So I think maybe the root cause is not these special headers.

**Comment by CharlieC3** [comment]
@wbpcode Thanks for the context! With the info you provided, I discovered a misconfiguration with the outbound cluster I was using.

I needed to specify the `transport_socket` for it to communicate over TLS, and the failure I was seeing was a `503` because Envoy was attempting to communicate via plain-text over port 443.
Closing this issue and posting the cluster snippet in case this helps anyone in the future:

```
          name: my_cluster
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          load_assignment:
            cluster_name: my_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          protocol: TCP
                          address: my.cluster.com
                          port_value: 443
```
