### ISSUE TITLE
Is it possible to configure different health_checks for different LocalityLbEndpoints

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#25336]
I'm using Envoy as the gateway of my backend micro-services.

I'm thinking if it's possible to make different health_checks for different LocalityLbEndpoints.

Here is a part of my config file:
```
  - name: service_testing
    connect_timeout: 30s
    type: STATIC
    lb_policy: RING_HASH
    health_checks:
    - timeout: 1s
      interval: 10s
      interval_jitter: 1s
      unhealthy_threshold: 2
      healthy_threshold: 1
      http_health_check:
        path: "/"
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_testing
      endpoints:
      - locality: *localityA
        lb_endpoints:
        - endpoint:
            health_check_config:
              port_value: 8089
            address:
              socket_address: *addrD
        - endpoint:
            health_check_config:
              port_value: 8000
            address:
              socket_address: *addrE
      - locality: *localityB
        lb_endpoints:
        - endpoint:
            health_check_config:
              port_value: 8089
            address:
              socket_address: *addrF
        - endpoint:
            health_check_config:
              port_value: 8000
            address:
              socket_address: *addrE
```

As you see, I have two different lb_endpoints with different localities in the cluster. However, they shared the same `health_checks`.

I want to know if I can set different `health_checks` for each of them, for example, `healthy_threshold: 1` for `localityA` and `healthy_threshold: 3` for `localityB`.
