### ISSUE TITLE
Circuit breakers trigger outlier detection

### ISSUE THREAD

**Issue by Hexta** [envoyproxy/envoy#25487]
*Title*: *Circuit breakers trigger outlier detection*

*Description*:
Max requests circuit breaker triggers outlier detections to eject unrelated endpoints.

*Repro steps*:
- Enable CB and OD.
- Trigger CB.

*Admin and Stats Output*:
```
cluster.a.outlier_detection.ejections_active: 1
cluster.a.outlier_detection.ejections_consecutive_5xx: 0
cluster.a.outlier_detection.ejections_detected_consecutive_5xx: 0
cluster.a.outlier_detection.ejections_detected_consecutive_gateway_failure: 0
cluster.a.outlier_detection.ejections_detected_consecutive_local_origin_failure: 1
cluster.a.outlier_detection.ejections_detected_failure_percentage: 0
cluster.a.outlier_detection.ejections_detected_local_origin_failure_percentage: 0
cluster.a.outlier_detection.ejections_detected_local_origin_success_rate: 0
cluster.a.outlier_detection.ejections_detected_success_rate: 0
cluster.a.outlier_detection.ejections_enforced_consecutive_5xx: 0
cluster.a.outlier_detection.ejections_enforced_consecutive_gateway_failure: 0
cluster.a.outlier_detection.ejections_enforced_consecutive_local_origin_failure: 1
cluster.a.outlier_detection.ejections_enforced_failure_percentage: 0
cluster.a.outlier_detection.ejections_enforced_local_origin_failure_percentage: 0
cluster.a.outlier_detection.ejections_enforced_local_origin_success_rate: 0
cluster.a.outlier_detection.ejections_enforced_success_rate: 0
cluster.a.outlier_detection.ejections_enforced_total: 1
cluster.a.outlier_detection.ejections_overflow: 0
cluster.a.outlier_detection.ejections_success_rate: 0
cluster.a.outlier_detection.ejections_total: 0
```

*Config*:
```yaml
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: a
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_requests: 0

    outlier_detection:
      interval: 1s
      
      consecutive_local_origin_failure: 1
      enforcing_consecutive_local_origin_failure: 100
      split_external_local_origin_errors: true

      base_ejection_time: 200s
      max_ejection_time: 200s
    load_assignment:
      cluster_name: a
          
      endpoints:
        - priority: 0
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9900
```

*Logs*:
```
[16][debug][pool] [source/common/http/conn_pool_base.cc:78] queueing stream due to no available connections (ready=0 busy=0 connecting=0)
[16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:291] trying to create new connection
[16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:145] creating a new connection (connecting=0)
[16][debug][connection] [./source/common/network/connection_impl.h:92] [C1] current connecting state: true
[16][debug][client] [source/common/http/codec_client.cc:57] [C1] connecting
[16][debug][connection] [source/common/network/connection_impl.cc:939] [C1] connecting to 127.0.0.1:9900
[16][debug][connection] [source/common/network/connection_impl.cc:958] [C1] connection in progress
[16][debug][connection] [source/common/network/connection_impl.cc:688] [C1] connected
[16][debug][client] [source/common/http/codec_client.cc:88] [C1] connected
[16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:328] [C1] attaching to next stream
[16][debug][pool] [source/common/conn_pool/conn_pool_base.cc:176] max streams overflow
[16][debug][router] [source/common/router/router.cc:1208] [C0][S18144849846439401274] upstream reset: reset reason: overflow, transport failure reason: 
[9][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1195] membership update for TLS cluster a added 0 removed 0
[9][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:878] host 127.0.0.1:9900 in cluster a was ejected by the outlier detector
```
