### ISSUE TITLE
XFF trusted client ip detection with port

### ISSUE THREAD

**Issue by murphy85** [envoyproxy/envoy#25517]
I try to determine the original client ip by using HttpConnectionManager configuration like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gw-xff
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          use_remote_address: true
          xff_num_trusted_hops: 4
```

If the X-Forwarded-For header contains an IP adress without a port, it works.

For example:

x-forwarded-for: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,5.5.5.5
x-envoy-external-address: 2.2.2.2

But if the ip at the right position contains a port, the fallback will be used and the x-envoy-external-address will be set with the last ip address in the list.

For example:

x-forwarded-for: 1.1.1.1,2.2.2.2:1234,3.3.3.3,4.4.4.4,5.5.5.5
x-envoy-external-address: 5.5.5.5

What am I doing wrong? Is this a bug? I read about an extension envoy.http.original_ip_detection.xff which can be used, but at some other point it was stated as deprecated?!

I tried it like this:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: gw-xff
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
    patch:
      operation: MERGE
      value:
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          original_ip_detection_extensions:
          - name: envoy.http.original_ip_detection.xff
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.http.original_ip_detection.xff.v3.XffConfig
              xff_num_trusted_hops: 4
```

The extension will not set the header correctly at all.

For example:

x-forwarded-for: 1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4,5.5.5.5
x-envoy-external-address: 5.5.5.5

x-forwarded-for: 1.1.1.1,2.2.2.2:1234,3.3.3.3,4.4.4.4,5.5.5.5
x-envoy-external-address: 5.5.5.5

The IP with port is set by Azure Application Gateway. If it's not an Envoy bug, we need to remove the port in Azure Application Gateway described here: [https://azure.microsoft.com/de-de/blog/rewrite-http-headers-with-azure-application-gateway/](https://azure.microsoft.com/de-de/blog/rewrite-http-headers-with-azure-application-gateway/)
