### ISSUE TITLE
Support custom formatters in custom request/response headers

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#25571]
Envoy's standard [command operators](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#config-access-log-command-operators) can be used in the value for [custom request/response headers](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers). Please also support **custom formatters** (or custom command operators?) in addition to the built-in formatters.

Custom formatters are already supported in the access log configuration (see "formatters" in [config.core.v3.SubstitutionFormatString](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/substitution_format_string.proto)), so maybe this can be implemented in a similar way.

Example:
```
route_config:
  name: local_route
  request_headers_to_add:
  - header:
    key: "x-my-header"
    value: "%MY_CUSTOM_COMMAND_OPERATOR%"
```
