### ISSUE TITLE
Support configuring the compressor filter per-request

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy#25581]
*Title*: *Support configuring the compressor filters per-request*

*Description*:

The [compressor](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/compressor/v3/compressor.proto) filter currently is either enabled or disabled globally.

Ideally there would be some mechanism to configure it to be enabled only for a subset of requests.

The motivating use case for this request is so that Envoy Mobile can apply request compression only for requests that are being made to endpoints known to support request decompression.

There are a few different ways I can think of to accomplish this:

* Add an `enabled_hostnames` field to the [compressor proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/compressor/v3/compressor.proto)
* Add some sort of a matcher field to the [compressor proto](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/compressor/v3/compressor.proto), and users could configure it to match on hostnames, paths, or headers. For example, requests could set an internal header (e.g. `x-envoy-mobile-enable-compression`) and the compressor proto matcher could be configured to apply compression when the header is set, or act as a passthrough filter otherwise.

*Relevant Links*:

Request compression was added to Envoy Mobile in https://github.com/envoyproxy/envoy/pull/25352.

**Comment by alyssawilk** [comment]
As you said, I wonder what if any existing matcher code is reusable here: we could possibly use existing header matches both for  (match for host: www.google.com but not host: legacy.website.com, match if x-envoy-compress-this present, don't match if absent)

cc @adisuissa ?

**Comment by kyessenov** [comment]
Why not use  the composite filter  which can enable/disable a filter based on the unified matchers?

**Comment by jpsim** [comment]
> Why not use the composite filter which can enable/disable a filter based on the unified matchers?

I wasn't aware that existed, but that sounds like a perfect fit for this use case! I'll look into it and report back, unless someone thinks we should go a different route.

**Comment by jpsim** [comment]
Based on the [docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter.html), looks like a config like this would work:

```yaml
- name: compression_composite
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
    extension_config:
      name: composite
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
    xds_matcher:
      matcher_tree:
        input:
          name: request-headers
          typed_config:
            "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
            header_name: x-envoy-mobile-compression
        exact_match_map:
          map:
            "brotli":
              action:
                name: composite-action
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                  typed_config:
                    name: envoy.filters.http.compressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                      compressor_library:
                        name: text_optimized
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.compression.brotli.compressor.v3.Brotli
                      request_direction_config:
                        common_config:
                          enabled:
                            default_value: true
                      response_direction_config:
                        common_config:
                          enabled:
                            default_value: false
            "gzip":
              action:
                name: composite-action
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                  typed_config:
                    name: envoy.filters.http.compressor
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                      compressor_library:
                        name: gzip
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                          window_bits: 15
                      request_direction_config:
                        common_config:
                          enabled:
                            default_value: true
                      response_direction_config:
                        common_config:
                          enabled:
                            default_value: false
```

I'll see if I can hook that up into Envoy Mobile.
