### ISSUE TITLE
Jwks RSA [n] or [e] field is missing or has a parse error

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#25618]
I'm using Envoy as the gateway of my backend micro-services. And I want to use the JWT mechanism of Envoy.

Here is what I've done:

1. generate a pair of private key and public key with the command `openssl`.
```
openssl genrsa -out key.pem 512
openssl rsa -in key.pem -pubout -out pubkey.crt
```
Now the private key is in the file `key.pem` and the public key is in the file `pubkey.crt`.

2. Generate a JWT token, which should be added into each request of clients.
```
#!/usr/bin/env python3

import base64
import jwt
import datetime

header = {
    "alg": "RS256",
    "typ": "JWT"
}

# Set the payload
payload = {
    'iss': 'ImIss',
    'sub': 'ImSub',
    'user_id': 123,
    'username': 'johndoe',
    'exp': datetime.datetime.utcnow() + datetime.timedelta(minutes=30)
}

# Load the secret key from a file
with open('key.pem', 'r') as f:
    secret = f.read()

# Generate the JWT token
token = jwt.encode(payload, secret, algorithm='RS256', headers=header)

# Print the token
print(token)

# Load the public key from a file
with open('pubkey.crt', 'r') as ff:
    pubkey = ff.read()

print(pubkey)
```
3. Configure Envoy with the public key.
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9989
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              http_filters:
                - name: envoy.filters.http.jwt_authn
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                    providers:
                      remote_jwt_provider:
                        issuer: "ImIss"
#                        remote_jwks:
#                          http_uri:
#                            uri: http://172.16.0.12/get_pub_key
#                            cluster: auth_service
#                            timeout: 5s
                        local_jwks:
                          inline_string: |
                            {
                              "keys": [
                                {
                                  "kty": "RSA",
                                  "kid": "my-key-id",
                                  "use": "sig",
                                  "n": "aaaYgaIWoWAObbb6J1sSUY/uev/ebnpNUzK7OcccwEAAQ==",    # a very long string (multiple lines), coming from the file pubkey.crt
                                  "e": "AQAB",
                                }
                              ]
                            }
                        forward: true
                        from_params:
                          - jwt_token
                    rules:
                      - match:
                          prefix: "/"
                        requires:
                          provider_name: remote_jwt_provider
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match: { prefix: "/" }
                        route:
                          cluster: cluster_example
  clusters:
  - name: auth_service
    connect_timeout: 30s
    type: STATIC
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: auth_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.16.0.12
                port_value: 8081
  - name: cluster_example
    connect_timeout: 30s
    type: STATIC
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_example
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.16.0.222
                port_value: 11111
```

As you see, I just assign the public key in the file `pubkey.crt` to the `inline_string` under `local_jwks` in the  config file of Envoy. However, when I run my Envoy, I get an error: 
```
[1][critical][main] [source/server/config_validation/server.cc:63] error initializing configuration '/etc/envoy/envoy.yaml': Provider 'remote_jwt_provider' in jwt_authn config has invalid local jwks: Jwks RSA [n] or [e] field is missing or has a parse error
```

As I noted above, the value of the `"n"` is a very long string, which is the public key. It looks like this:
```
inline_string: |
  {
    "keys": [
       {
          "kty": "RSA",
          "n": "-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADfdsafsd1NGK6Slv/8olf2eE3PpfgR+G\nUe0dfasfsdafdK4+8fMMHTAo5q9ffdsafasdfKfh9bUCAwEAAQ==\n-----END PUBLIC KEY-----",
          "e": "AQAB",
       }
    ]
}
```
As you see, I added `\n` to make the public key into one single line.

To my surprise, if I remove the characters `/` and `=` in the public key, the error would disappear... I don't know why.

Did I do something wrong? Or did I misunderstand how JWT works? Shouldn't I assign the public key to `n` immediately?

BTW, I could decode the token successfully with Python3 script:
```
#!/usr/bin/env python3

import jwt
import datetime

pubkey = '-----BEGIN PUBLIC KEY-----\nMFwwDQYJKdddddddEBBQADsssssnC+h491NGK6Slv/8olf2eE3PpfgR+G\nUe0wZ8zzzzzzzzzzzzzal6K4+8fMMttttttttttttttttttttAwEAAQ==\n-----END PUBLIC KEY-----'

token='aaaaaaJhbGciOiJSUzI1NiJ9.ebbbbbbbbbbidXNlcl9pZCI6MTIzLCJ1c2VybmFtZSI6ImpvaG5kb2UiLCJleHAiOjE2NzY4ODQ5OTV9.WbyTHxJmF6oT9N_Q0s-4g86HccccccccccccclKkc6K4umgJGrjLPdddddddddddddMDb6p7Lkbg'

header_data = jwt.get_unverified_header(token)
print(header_data)

# using that variable in the decode method
res = jwt.decode(
    token,
    key=pubkey,
    algorithms=[header_data['alg'], ]
)
print(res)
```
