### ISSUE TITLE
Envoy not using locality weights for load balancing within the same priority

### ISSUE THREAD

**Issue by liamhazell** [envoyproxy/envoy#25692]
*Title*:  Envoy not using locality weights for load balancing within the same priority

*Description*:
I'm messing around with the locality weighted load balancing, and found that if I have 2 endpoints that are within the same priority that use different load balancing weights the weights aren't respected. Using 2 endpoints that have a weight of 2 and 1 should be routed 67% and 33% respectively based on these [docs](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight#:~:text=Assume%20a%20simple%20set%2Dup%20with%202%20localities%20X%20and%20Y%2C%20where%20X%20has%20a%20locality%20weight%20of%201%20and%20Y%20has%20a%20locality%20weight%20of%202%2C%20L%3DY%20100%25%20available%2C%20with%20default%20overprovisioning%20factor%201.4.). Traffic ends up being split 50/50 between the endpoints however. I thought that I was misconfiguring something, however slightly modifying the [example config](https://github.com/envoyproxy/envoy/blob/main/examples/locality-load-balancing/envoy-proxy.yaml) for locality load balancing yields the same result. I'm wondering if I have a misunderstanding of this feature, or if this isn't working as expected.
 
*Repro steps*:
Modify the example config from the [example directory](https://github.com/envoyproxy/envoy/blob/main/examples/locality-load-balancing/envoy-proxy.yaml) to have 2 endpoints with priorities of 0 with a weight of 1 and 2:

```
      endpoints:
      - locality:
          region: local
          zone: zone-1
        load_balancing_weight: 2
        priority: 0  # highest
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-1
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-1
      - locality:
          region: local
          zone: zone-2
        load_balancing_weight: 1
        priority: 0
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-2
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-2
```

*Config*:
Full config used:
```
node:
  cluster: test-cluster
  id: test-id
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - name: backend
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 3000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: backend
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: backend
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    health_checks:
    - interval: 2s
      timeout: 3s
      no_traffic_interval: 4s
      no_traffic_healthy_interval: 4s
      unhealthy_threshold: 1
      healthy_threshold: 1
      http_health_check:
        path: "/"
    load_assignment:
      cluster_name: backend
      endpoints:
      - locality:
          region: local
          zone: zone-1
        load_balancing_weight: 1
        priority: 0  # highest
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-1
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-1
      - locality:
          region: local
          zone: zone-2
        load_balancing_weight: 1
        priority: 0
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-2
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-2
```

Thanks in advance for the help!

**Comment by phlax** [comment]
@liamhazell not sure if this is helpful - but i went through previously when updating the sandbox - did you try working through it?

https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/locality_load_balancing

iirc it wasnt immediately obvious how it worked

**Comment by liamhazell** [comment]
@phlax I can reproduce using the sandox. So using this config:

```
...  
  clusters:
  - name: backend
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    health_checks:
    - interval: 2s
      timeout: 3s
      no_traffic_interval: 4s
      no_traffic_healthy_interval: 4s
      unhealthy_threshold: 1
      healthy_threshold: 1
      http_health_check:
        path: "/"
    load_assignment:
      cluster_name: backend
      endpoints:
      - locality:
          region: local
          zone: zone-1
        load_balancing_weight: 2
        priority: 0  # highest
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-1
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-1
      - locality:
          region: local
          zone: zone-2
        load_balancing_weight: 1
        priority: 0
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-local-2
                port_value: 8080
            health_check_config:
              port_value: 8080
            hostname: backend-local-2
```

Based on the docs [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight#:~:text=Assume%20a%20simple%20set%2Dup%20with%202%20localities%20X%20and%20Y%2C%20where%20X%20has%20a%20locality%20weight%20of%201%20and%20Y%20has%20a%20locality%20weight%20of%202%2C%20L%3DY%20100%25%20available%2C%20with%20default%20overprovisioning%20factor%201.4.), it sounds like traffic should be routed to `backend-local-1` 67% of the time, and `backend-local-2` 33% of the time because of the different weights within the priority.

However what I actually see is this:
```
$ docker-compose exec -T client-envoy python3 client.py http://localhost:3000/ 100

Hello from backend-local-1!: actual weight 49.0%
Hello from backend-local-2!: actual weight 51.0%
Failed: 0
```

Seems like a bug with how the `load_balancing_weight` option works within the same priority?
