### ISSUE TITLE
HTTP endpoint fallback in case non-http content

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#25741]
Assuming I have two TCP listeners in my config, one of them has HCM filter (expecting http traffic) and the second has tcp_Proxy filter. Would it be possible to route traffic from the listener with HCM filter chain to the listener with tcp_proxy filter chain (through loopback), in case that non-http traffic was sent to the listener with the HCM? 
Thanks

**Comment by phlax** [comment]
not that im aware of - there may be some workaround you could use that i dont know of tho

i was looking here to try and see if there was an obvious way:

- https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster (`transport_socket_matches`)
- https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster-transportsocketmatch


but im not sure if that would help

**Comment by ohadvano** [comment]
Thanks @phlax, do you have an idea what kind of change can be made so it would be supported?

**Comment by phlax** [comment]
assuming its not supported currently - i guess this is something you could write a filter for - im not sure how desirable this is as a general case and can think of quite a few reasons you wouldnt want to do this or problems it might create

**Comment by ohadvano** [comment]
What kind of filter? I mean, L4 filter won't indicate if HTTP is involved on one hand, and on the other hand L7 filter would not even be triggered, as the HTTP filter chain would not be invoked if it's non-http traffic. Am I missing something?

Also can you please give an example of a problem it might create? Maybe I have missed something

**Comment by phlax** [comment]
i may be wrong about whether this is supported - i asked chatGPT

>> Q: is there a way to use the envoy proxy for opportunistic http - by which i mean if a connection appears to be http upgrade otherwise proxy to a tcp upstream

> Yes, it is possible to use Envoy proxy for opportunistic HTTP, which means upgrading a plain text HTTP connection to a secured HTTP or WebSocket connection if possible, or proxying it to a TCP upstream if not. This can be achieved by using Envoy's connection manager filters and upgrading headers.
> To enable opportunistic HTTP, you can use the upgrade_configs field of the Envoy HTTP connection manager ...

>> how about if an incoming connection is not http - can envoy take a peek and route correctly in that case to a plain tcp upstream

> Yes, Envoy can route non-HTTP traffic to a plain TCP upstream using the TCP proxy filter. The TCP proxy filter allows Envoy to handle generic TCP traffic and can be used as a fallback for non-HTTP traffic that cannot be upgraded to HTTP or WebSocket.
> To configure Envoy to route non-HTTP traffic to a plain TCP upstream, you can use a network filter chain and include the TCP proxy filter. Here's an example configuration that routes traffic to a TCP upstream for any port that is not explicitly defined as HTTP or WebSocket traffic:

```yaml

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          ...
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: my_tcp_cluster
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          ...
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: my_tcp_cluster
    ...
  clusters:
  - name: my_http_cluster
    ...
  - name: my_tcp_cluster
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: my_tcp_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234

```

The config definitely wont work as chatGPT is out of date (and often wrong) - but it might provide some helpers

---

for the design and potential pitfalls of such a filter im afraid that is not my area
