### ISSUE TITLE
Websocket client disconnects when related upstream is down

### ISSUE THREAD

**Issue by zargor** [envoyproxy/envoy#25754]
*Description*:
We run kubernetes websocket server pods.
 
Between clients and the services we want envoy proxy to take care of connections lifecycle.
 
More precisely, the idea is to "preserve" a websocket connection in such way that the connection is taken over by another healthy upstream (once original upstream is gone).
 
We are not in control of the clients.
 
So far, we tried different configuration options in order to reroute/fail over/keep alive/prevent disconnecting websocket connection, but we keep failing.
 
Once pod is `Terminating`/`Terminated` the downstream connection got broken too - the client gets disconnected.
 
Let me share what we tried to do:
 - First, we do gracefully close websocket connections on SIGTERM signal
 - With Lua script, we cannot intercept any request/response since the connection is upgraded from the start and the communication is binary from that point on
 - Health checks, circuit breaker and weighted clusters don't help mitigate this issue
 
We strongly believe this preservation of websocket connection is possible to manage with envoy.
Could you please give us a hand how best we can approach this problem.

Here is the current`envoy.yaml` example:
```yaml
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 14000
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 7070
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: filter_wsprogram
          codec_type: auto
          upgrade_configs:
          - upgrade_type: websocket
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  idle_timeout: 0s
                  priority: HIGH
                  weighted_clusters:
                    clusters:
                      - name: wsprogram_cluster
                        weight: 90
                      - name: wsprogram_backup_cluster
                        weight: 10
                    total_weight: 100
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: wsprogram_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    #connect_timeout: 1s
    dns_refresh_rate: 0.01s
    load_assignment:
      cluster_name: wsprogram_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: wsprogram-headless-zero
                    port_value: 80
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 1000
          max_pending_requests: 1000
          max_requests: 10000
          max_retries: 3
          track_remaining: true
    
    health_checks:
      - timeout: 1s
        interval: 1s
        unhealthy_threshold: 1
        healthy_threshold: 2
        tcp_health_check:
          send:
            text: "00"
          receive:
            text: "00"
  - name: wsprogram_backup_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    #connect_timeout: 1s
    dns_refresh_rate: 0.01s
    load_assignment:
      cluster_name: wsprogram_backup_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: wsprogram-headless-one
                port_value: 80
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 1000
          max_pending_requests: 1000
          max_requests: 10000
          max_retries: 3
          track_remaining: true

    health_checks:
    - timeout: 1s
      interval: 1s
      unhealthy_threshold: 1
      healthy_threshold: 2
      tcp_health_check:
        send:
          text: "00"
        receive:
          text: "00"
```
