### ISSUE TITLE
https_passthrough with jwt_authn in the middle

### ISSUE THREAD

**Issue by rbahegne** [envoyproxy/envoy#25774]
I'm trying to set up a proxy with a jwt auth in the middle of a client/server communicating using https.

So i tried something like : 

```
static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9901
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: qm
          stat_prefix: https_passthrough

          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                jwt_auth:
                  local_jwks:
                    inline_string: '{"keys":[{"kty":"oct","alg":"HS256","k":"cGFydGVj"}]}'
                  from_headers:
                  - name: Authorization
                    value_prefix: "Bearer "
              rules:
              - match:
                  prefix:  "/"
                requires:
                  provider_name:  jwt_auth    
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: xxxxx.com
                  cluster: qm-cluster


  clusters:
  - name: qm
    type: STRICT_DNS
    lb_policy: round_robin
    load_assignment:
      cluster_name: qm
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: xxxxx.com
                port_value: 443
```
 
But i get this error : Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:http_filters: Cannot find field.) has unknown fields

I manage to get jwt_auth work with http so i feel like the config for jwt_auth and router are OK.

I don't really know what's wrong with this config so i get to ask myself : 
**Is this even possible to combine https_passthrough and jwt_auth ?**
