### ISSUE TITLE
Proxy Minio S3

### ISSUE THREAD

**Issue by abdennour** [envoyproxy/envoy#25782]
*Title*: *One line description*

*Description*:
Trying to proxy a Minio S3 with envoy. And i was following the config mentioned in this question: https://github.com/envoyproxy/envoy/issues/18695#issue-1031699848

Since it's not AWS S3, i just changed `host_rewrite:` value to be the address of the Minio Endpoint
```yaml
  typed_config:
      "@type": ...... AwsRequestSigning
      service_name: s3
      host_rewrite: hostname.myminio.com
```

It does not work when testing it with `aws --endpoint s3 ls`
