### ISSUE TITLE
How to send Envoy log to a remote syslog server with custom format

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#25878]
I'm using Envoy as the gateway of my http backend services.

Now I'm trying to make Envoy send its logs to a remote syslog server.

It seems that `HttpGrpcAccessLogConfig` is what I need but it doesn't seem that it supports customizing the format of log.

Here is my config file:
```
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10020
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.http_grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
              common_config:
                log_name: egressenvoyaccesslog
                grpc_service:
                  envoy_grpc:
                    cluster_name: syslog_cluster
                transport_api_version: V3
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

There is no fields, such as `format` or `json_format`, under the `HttpGrpcAccessLogConfig`.

I also checked the `FileAccessLog`, but the field `path` is noted as "A path to a local file to which to write the access log entries." and I don't think that syslog is a local file...

In a word, I don't know how to send the logs of Envoy to a remote syslog server with some custom format.
