### ISSUE TITLE
Improve the logic for XFF and internal/external client detection

### ISSUE THREAD

**Issue by brian-pane** [envoyproxy/envoy#2590]
*Description*:
Per the discussion in PR [2559](https://github.com/envoyproxy/envoy/pull/2559), Envoy's logic for determining whether any given request is internal or external, and what the trusted address of the origin client is, has become very complicated. And even with this complexity, the mechanism isn't sufficiently general to cover the needs of all users.

One potential improvement would be to create a plug-in interface so Envoy users can plug in their own logic. Another would be to simplify the configuration semantics for the current functionality.

**Comment by slovdahl** [comment]
I just stumbled upon this problem while trying to figure out why my local Envoy in a Docker container allowed my `curl` requests to spoof the `x-envoy-external-address` header when having Envoy configured to act as an edge proxy. It took me a while to figure out that the problem was the source IP of my requests :slightly_smiling_face: 

For reference, the configuration I use (inspired by https://www.envoyproxy.io/docs/envoy/v1.12.0/configuration/http/http_conn_man/headers#config-http-conn-man-headers-x-forwarded-for):

```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80

      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                codec_type: AUTO

                use_remote_address: true
                xff_num_trusted_hops: 0

                route_config:
                  name: local_route
                  virtual_hosts:
                    {
                      name: local_service,
                      domains: ["*"],

                      routes: [
                        {
                          match: { prefix: "/" },
                          route: { cluster: backend },
                        }
                      ]
                    }

                http_filters:
                  - name: envoy.router
```

Doing a curl request like this:
```shell
$ curl -sv -H "x-envoy-external-address: 1.2.3.4" http://localhost/foo
```
..and the traffic dump shows that the backend request actually got the spoofed `x-envoy-external-address`:
![image](https://user-images.githubusercontent.com/1417619/68212235-c9ceab80-ffe1-11e9-9384-f3f84b5b02e3.png)

We would like to put Envoy in front of all incoming HTTP traffic to our backend services. The problem is that our edge might see untrusted traffic from both internal and external IP addresses. Having read through some discussions in e.g. #2559 and #4383, it sounds like just another configuration option is not the way forward here? Not asking for a solution, just want to start a discussion about the right way to solve this problem.
