### ISSUE TITLE
envoyproxy with v2 ADS Discovery not routing

### ISSUE THREAD

**Issue by kenjones-cisco** [envoyproxy/envoy#2594]
**Issue Template**

*Title*: envoyproxy with v2 ADS Discovery not routing

*Description*:
Using envoyproxy v1.5.0 (`FROM envoyproxy/envoy-alpine:v1.5.0`) with an implementation of the the v2 ADS Discovery API.

I can see the correct configuration being received by the envoyproxy. (see link for logs below).
Behind the proxy are two microservices, `tenantmgr` and `openstack-svc`. There are 2 different paths currently exposed. `v1/tenants` and `v1/openstack/projects`. 

The `envoyproxy` as API Gateway, `discovery` as v2 Discovery APIs, `tenantmgr`, and `openstack-svc` are deployed on a Kubernetes using the Front-Proxy deployment. `tenantmgr` and `openstack-svc` have envoyproxy running as a side-car with a very simple static configuration.

Make a calling `/v1/openstack/projects` works with no issues, as the request gets routed. When trying to call the `/v1/tenants` no route is found and a 404 response is returned.

I can see in the logs that the `listener`, `clusters`, `routes`, and `endpoints` are all being received.

https://gist.github.com/kenjones-cisco/ccaccb8090970aeefaf833e3e4d8833d#file-envoy-logs-L992-L1275

After reviewing the logs, and configuration details, and the fact that routing to one of the services works with no issue. I'm trying to determine if the configuration updates being streamed are not being processed correctly or possibly not being provided correctly. 

Any feedback would be appreciated.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

*Config*:
**dynamic configuration for APIGW**
```yaml
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address: { address: 0.0.0.0, port_value: 8001 }

    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_name: [ads]
      lds_config: {ads: {}}
      cds_config: {ads: {}}

    static_resources:
      clusters:
      - name: ads
        connect_timeout: 0.25s
        type: LOGICAL_DNS
        lb_policy: ROUND_ROBIN
        http2_protocol_options: {}
        hosts: [{ socket_address: { address: discovery, port_value: 18000 }}]
```

**static configuration for private microservices**
```yaml
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address: { address: 0.0.0.0, port_value: 8001 }

    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 80 }
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: local_cluster }
              http_filters:
              - name: envoy.router
      clusters:
      - name: local_cluster
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: ROUND_ROBIN
        hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8080 }}]
```

*Logs*:
>Include the access logs and the Envoy logs.
https://gist.github.com/kenjones-cisco/ccaccb8090970aeefaf833e3e4d8833d
