### ISSUE TITLE
An updated version of @jevonearth snippet

### ISSUE THREAD

**Issue by nulldoot2k** [envoyproxy/envoy#26002]
I have the same situation when configuring the following, it says stdout
```yaml
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              path: /dev/stdout
```
