### ISSUE TITLE
Load balancing behaviors with different service discovery types

### ISSUE THREAD

**Issue by zihuaweng** [envoyproxy/envoy#26021]
Hi team, I have a few questions about the load balancers mentioned here https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers

1. Are these load balancers supported in all service discovery types: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery
2. If so, what is the behavior of combining load balancer with Strict DNS and Logical DNS type? especially in a k8s setting?

**Comment by mattklein123** [comment]
In general all load balancers are supported for all SD types. I would need more information to specifically comment further.

**Comment by zihuaweng** [comment]
Thanks @mattklein123 , regarding question 2, for example, we have a k8s service called hello, and here is the cluster config we have. In this case, k8s service will resolve the endpoints for the pods under it, does enovy do load balancing (using LEAST_REQUEST set in the config) to these endpoints, or just send the requests to the service and k8s does the load balancing? 
```
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: LEAST_REQUEST
    load_assignment:
      cluster_name: hello
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: hello
                port_value: 1234
```

**Comment by suniltheta** [comment]
You might want to check the [Logical DNS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#logical-dns) and [Strict DNS](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#strict-dns) options provided by Envoy proxy config, if that is what you are interested in.

Also can you elaborate on the k8s load balancing that you mentioned here?

**Comment by zihuaweng** [comment]
So for the example I posted, enovy will resolve the DNS target and apply load balancer LEAST_REQUEST to the return Ip addresses? The reason I am asking is that k8s will resolve DNS target and route traffic through kube-proxy [link](https://kubernetes.io/docs/reference/networking/virtual-ips/), I want to understand if the envoy load balancer will apply when we use STRICT_DNS or LOGICAL_DNS.

**Comment by suniltheta** [comment]
Yes, Envoy will resolve DNS targets and apply Load balancing.

As far as I know kube-proxy will not do the L4 & L7 load balancing of connections/requests.

I think you might want to see this https://thenewstack.io/why-do-you-need-istio-when-you-already-have-kubernetes/

**Comment by zihuaweng** [comment]
Thanks @suniltheta for the clarification!

**Comment by shashankn91** [comment]
@suniltheta For envoy to be able to resolve the hosts and apply client-side load balancing. The application must use headless service which provides the IP address of all hosts and as well will it work without configuring any of the DNS resolvers in the extension - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/dns_resolver/dns_resolver

**Comment by suniltheta** [comment]
Envoy uses Cares Dns Resolver by default. So there is no need to explicitly configure CaresDnsResolverConfig extension.

While Cares client tries to resolve DNS it is the job of coredns or kube-dns in kubernetes cluster to resolve the DNS to a list of IP address. After Envoy received these IP address the client side load balancing algorithm will apply based on resolved IP addresses.

**Comment by shashankn91** [comment]
@suniltheta Based on this doc - https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-dns-resolvers envoy defaults to /etc/resolv.conf for configuration . 

In the K8s world if the service configured is not a headless server DNS resolver would resolve it to the Service IP address (Single IP address).  Is it a requirement to have a headless service to have client-side load balancing? If the Service is of type load balancer how would STRICT_DNS resolve to hosts?

**Comment by suniltheta** [comment]
I would like someone else who is more familiar on this topic to weigh in here. If I made wrong assumptions please correct me.

From what I know /etc/resolv.conf will not contain the resolved DNS address but only the list of nameserver addresses to reachout to and any DNS resolver configuration such as search namespace. Inside Kubernetes cluster I see the following file stored in a pod container

```
bash-4.2# cat /etc/resolv.conf
nameserver 10.100.0.10
search <namespace>.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```

We would still need a DNS resolver client to reachout to the nameservers.


---

Meanwhile I am not familiar with headless server aspects.

**Comment by zihuaweng** [comment]
I did some testings with the combination of STRICT_DNS type and lb. In the config, I added a resolver config with the kube-dns endpoint 10.96.5.5. When my upstream service is a regular service, the same request will be routed to all upstream hosts. But when I changed the upstream service to be a headless service, the same request will only be routed to 1 particular upstream host, which should be the expected behavior for RING_HASH. Looks like lb is not working with STRICT_DNS type unless we use headless service. 
```
  clusters:
  - name: service_backend
    type: STRICT_DNS  
    lb_policy: RING_HASH
    typed_dns_resolver_config:
      name: envoy.network.dns_resolver.cares
      typed_config: 
        "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
        resolvers: 
          - socket_address:
              address: 10.96.5.5
    ring_hash_lb_config:
      minimum_ring_size: 1024
      maximum_ring_size: 8192
    load_assignment:
      cluster_name: upstream_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: upstream
                port_value: 8000
```
