### ISSUE TITLE
Grpc healthcheck not working properly 

### ISSUE THREAD

**Issue by zihuaweng** [envoyproxy/envoy#26020]
*Description*:
I have been testing the grpc health check with a simple health check example here: https://github.com/grpc/grpc-go/tree/master/examples/features/health. But the health check configured through envoy is not working properly. When the service status is NO_SERVING, envoy still sends requests to the server. 

Below are the only changes I made to the grpc-go example:
in service/main.go, update: system = "Echo"
in client/main.go, delete grpc.WithDefaultServiceConfig(serviceConfig), update Addr: "localhost:9911"

here is my envoy config:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9911
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: greeter_route # configure the localclus routes
            virtual_hosts:
            - name: servicegreeter
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: grpc1
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: grpc1
      connect_timeout: 1.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      dns_lookup_family: V4_ONLY
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: grpc1
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 50052
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 50051
      health_checks:   
        - timeout: 1s
          interval: 1s
          no_traffic_interval: 0.001s
          unhealthy_threshold: 1
          healthy_threshold: 1
          grpc_health_check:
            service_name: "Echo"
          event_log_path: ./health_check.log
          always_log_health_check_failures: true
          reuse_connection: false
```

log:
server 50051:
```
8350 ± : go run server/main.go -port=50051 -sleep=10s                                         ⏎ [154d9h10m] ✹ ✭
Update server to SERVING
Update server to NOT_SERVING
Update server to SERVING
Update server to NOT_SERVING
```
server 50052:
```
8349 ± : go run server/main.go -port=50052 -sleep=20s                                         ⏎ [154d9h10m] ✹ ✭
Update server to SERVING
Update server to NOT_SERVING
```
client: (here both 50051 and 50052 keep responding to client even though they are NO_SERVING)
```
UnaryEcho:  hello from localhost:50052
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50052
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50052
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50051
UnaryEcho:  hello from localhost:50052
```
