### ISSUE TITLE
the upstream receive double /

### ISSUE THREAD

**Issue by qicz** [envoyproxy/envoy#26024]
when the httproute config with urlrewrite from envoy-gateway like follows:

```yaml
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: backend
spec:
  parentRefs:
    - name: eg
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
              type: ReplacePrefixMatch
      matches:
        - path:
            type: PathPrefix
            value: /om/test
```

the upstream receive double `/`

![image](https://user-images.githubusercontent.com/2174082/219278148-3d8cd923-1bca-4745-bfde-4d5d0e721aa8.png)

envoy doc

![image](https://user-images.githubusercontent.com/2174082/219282696-055201f0-ffd1-4dc0-97ab-892ec84ed0b1.png)

reference https://github.com/envoyproxy/gateway/issues/1044
