### ISSUE TITLE
Cors issue with cognito for JWT validation

### ISSUE THREAD

**Issue by zadm** [envoyproxy/envoy#26054]
*Title*: *Cors issue with Cognito *

I'm trying to get envoy working in front on my flask backend application but I'm stuck with a CORS issue even by following the documentation 

Here is my confoguration file 
```

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              cors:
                allow_origin_string_match:
                  prefix:
                    http://*
                    https://*
                allow_methods: GET, PUT, POST, DELETE, OPTIONS
                allow_headers: "*"
                expose_headers: "Authorization, content-length, content-type"
              routes:
              - match: { prefix: "/api" }
                route: { cluster: backend-flask }
                typed_per_filter_config:
                  envoy.filters.http.cors:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                    allow_origin_string_match:
                      prefix:
                        http://*
                        https://*
                    allow_methods: GET, PUT, POST, DELETE, OPTIONS
                    allow_headers: "*"
                    expose_headers: "Authorization, content-length, content-type"
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication"
              providers:
                cognito_provider:
                  clock_skew_seconds: 600
                  issuer: "https://cognito-idp.eu-west-1.amazonaws.com/{COGNITO_POOL_ID}"
                  remote_jwks:
                    http_uri:
                      uri: "https://cognito-idp.{AWS_REGION}.amazonaws.com/{COGNITO_POOL_ID}/.well-known/jwks.json"
                      cluster: jwks_cluster
                      timeout: 5s

                  forward: true
              rules:
                - match:
                    prefix: "/api"
                  requires:
                    provider_name: cognito_provider
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: backend-flask
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend-flask
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-flask
                port_value: 4567`
```

When I try ro connect to the application via my REACT front app, I get this error in the browser 

![image](https://user-images.githubusercontent.com/18516249/224576800-0fa2d9d6-a260-44d7-8d9a-bb25534a5b72.png)

And  from enjoy server 
![image](https://user-images.githubusercontent.com/18516249/224576864-9b6bee14-bab3-465f-92ec-c4be0ea53eaa.png)

in my REACT app, I'am passing correctly the token 

![image](https://user-images.githubusercontent.com/18516249/224577005-aa64e7c4-4e9e-4095-a84a-ab1fba3bf69d.png)

**Comment by wbpcode** [comment]
Could you provide some more detailed debug envoy logs about the request and response? thanks.

**Comment by zadm** [comment]
Hello, 

Thank you for your response, 
bellow debug log from envoy 
```

aws-bootcamp-cruddur-2023-frontend-react-js-1  | webpack compiled with 3 warnings
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.159][18][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:155] [C0] new connection from 172.18.0.1:57314
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.160][18][debug][http] [source/common/http/conn_manager_impl.cc:334] [C0] new stream
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.160][18][debug][http] [source/common/http/conn_manager_impl.cc:1019] [C0][S2670146588892280726] request headers complete (end_stream=true):
aws-bootcamp-cruddur-2023-envoy-1              | ':authority', '127.0.0.1'
aws-bootcamp-cruddur-2023-envoy-1              | ':path', '/api/activities/home'
aws-bootcamp-cruddur-2023-envoy-1              | ':method', 'OPTIONS'
aws-bootcamp-cruddur-2023-envoy-1              | 'user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0'
aws-bootcamp-cruddur-2023-envoy-1              | 'accept', '*/*'
aws-bootcamp-cruddur-2023-envoy-1              | 'accept-language', 'en-US,en;q=0.5'
aws-bootcamp-cruddur-2023-envoy-1              | 'accept-encoding', 'gzip, deflate, br'
aws-bootcamp-cruddur-2023-envoy-1              | 'access-control-request-method', 'GET'
aws-bootcamp-cruddur-2023-envoy-1              | 'access-control-request-headers', 'authorization'
aws-bootcamp-cruddur-2023-envoy-1              | 'referer', 'http://127.0.0.1:3000/'
aws-bootcamp-cruddur-2023-envoy-1              | 'origin', 'http://127.0.0.1:3000'
aws-bootcamp-cruddur-2023-envoy-1              | 'connection', 'keep-alive'
aws-bootcamp-cruddur-2023-envoy-1              | 'sec-fetch-dest', 'empty'
aws-bootcamp-cruddur-2023-envoy-1              | 'sec-fetch-mode', 'cors'
aws-bootcamp-cruddur-2023-envoy-1              | 'sec-fetch-site', 'same-site'
aws-bootcamp-cruddur-2023-envoy-1              | 
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.160][18][debug][http] [source/common/http/conn_manager_impl.cc:1002] [C0][S2670146588892280726] request end stream
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.160][18][debug][connection] [./source/common/network/connection_impl.h:98] [C0] current connecting state: false
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:157] Called Filter : setDecoderFilterCallbacks
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:53] Called Filter : decodeHeaders
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/matcher.cc:71] Prefix requirement '/api' matched.
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/extractor.cc:254] extract authorizationBearer 
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:151] cognito_provider: JWT authentication starts (allow_failed=false), tokens size=0
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:374] cognito_provider: JWT token verification completed with: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:378] status is: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:109] Jwt authentication completed with: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.161][18][debug][http] [source/common/http/filter_manager.cc:917] [C0][S2670146588892280726] Preparing local reply with details jwt_authn_access_denied{Jwt_is_missing}
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.162][18][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:97] Called Filter : decodeHeaders Stop
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.162][18][debug][http] [source/common/http/filter_manager.cc:959] [C0][S2670146588892280726] Executing sending local reply.
aws-bootcamp-cruddur-2023-envoy-1              | [2023-03-12 22:07:02.162][18][debug][http] [source/common/http/conn_manager_impl.cc:1635] [C0][S2670146588892280726] encoding headers via codec (end_stream=false):
aws-bootcamp-cruddur-2023-envoy-1              | ':status', '401'
aws-bootcamp-cruddur-2023-envoy-1              | 'www-authenticate', 'Bearer realm="http://127.0.0.1/api/activities/home"'
aws-bootcamp-cruddur-2023-envoy-1              | 'content-length', '14'
aws-bootcamp-cruddur-2023-envoy-1              | 'content-type', 'text/plain'
aws-bootcamp-cruddur-2023-envoy-1              | 'date', 'Sun, 12 Mar 2023 22:07:02 GMT'
aws-bootcamp-cruddur-2023-envoy-1              | 'server', 'envoy'
aws-bootcamp-cruddur-2023-envoy-1              | 

```

**Comment by wbpcode** [comment]
Seems the origin header is not match the requirement and the cors filter is bypassed directly.

I think this is not like a correct prefix match of `StringMatcher` ?

![image](https://user-images.githubusercontent.com/12389633/224913236-5be1792d-cbee-4adb-ae4d-8ffe232cc5a8.png)

**Comment by zadm** [comment]
```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          stat_prefix: ingress_http
          codec_type: AUTO
          access_log:
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              cors:
                allow_origin_string_match:
                - safe_regex:
                    regex: \*
                allow_methods: GET, PUT, POST, DELETE, OPTIONS
                allow_headers: Origin, Content-Type, Accept, Authorization
                expose_headers: Authorization
              routes:
              - match:
                  prefix: "/api"
                route:
                  cluster: backend-flask
                typed_per_filter_config:
                  envoy.filters.http.cors:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
 
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication"
              providers:
                cognito_provider:
                  issuer: "https://cognito-idp.eu-west-1.amazonaws.com/{POOL_ID}"
                  remote_jwks:
                    http_uri:
                      uri: "https://cognito-idp.eu-west-1.amazonaws.com/{POOL_ID}/.well-known/jwks.json"
                      cluster: jwks_cluster
                      timeout: 5s
                  from_headers:
                    - name: Authorization
                      value_prefix: "Bearer "
                  clock_skew_seconds: 600

                  forward: true
              rules:
                - match:
                    prefix: "/api"
                  requires:
                    provider_name: cognito_provider
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  
  clusters:
  - name: backend-flask
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend-flask
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend-flask
                port_value: 4567
  - name: jwks_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: jwks_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: cognito-idp.eu-west-1.amazonaws.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt



```

I used the bellow regex to allow all the origins
```
                allow_origin_string_match:
                - safe_regex:
                    regex: \*
```

Bellow the logs 


```

aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.072][17][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:155] [C0] new connection from 172.18.0.1:61788
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.074][17][debug][http] [source/common/http/conn_manager_impl.cc:334] [C0] new stream
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.075][17][debug][http] [source/common/http/conn_manager_impl.cc:1019] [C0][S2936510301289698954] request headers complete (end_stream=true):
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | ':authority', '127.0.0.1:8080'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | ':path', '/api/activities/notifications'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | ':method', 'OPTIONS'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'accept', '*/*'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'accept-language', 'en-US,en;q=0.5'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'accept-encoding', 'gzip, deflate, br'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'access-control-request-method', 'GET'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'access-control-request-headers', 'authorization'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'referer', 'http://127.0.0.1:3000/'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'origin', 'http://127.0.0.1:3000'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'connection', 'keep-alive'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'sec-fetch-dest', 'empty'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'sec-fetch-mode', 'cors'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'sec-fetch-site', 'same-site'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.075][17][debug][http] [source/common/http/conn_manager_impl.cc:1002] [C0][S2936510301289698954] request end stream
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.075][17][debug][connection] [./source/common/network/connection_impl.h:98] [C0] current connecting state: false
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.075][17][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:157] Called Filter : setDecoderFilterCallbacks
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:53] Called Filter : decodeHeaders
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/matcher.cc:71] Prefix requirement '/api' matched.
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/extractor.cc:254] extract authorizationBearer 
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:151] cognito_provider: JWT authentication starts (allow_failed=false), tokens size=0
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:374] cognito_provider: JWT token verification completed with: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:378] status is: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:109] Jwt authentication completed with: Jwt is missing
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][http] [source/common/http/filter_manager.cc:917] [C0][S2936510301289698954] Preparing local reply with details jwt_authn_access_denied{Jwt_is_missing}
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:97] Called Filter : decodeHeaders Stop
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.076][17][debug][http] [source/common/http/filter_manager.cc:959] [C0][S2936510301289698954] Executing sending local reply.
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | [2023-03-14 20:22:30.077][17][debug][http] [source/common/http/conn_manager_impl.cc:1635] [C0][S2936510301289698954] encoding headers via codec (end_stream=false):
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | ':status', '401'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'www-authenticate', 'Bearer realm="http://127.0.0.1:8080/api/activities/notifications"'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'content-length', '14'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'content-type', 'text/plain'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'date', 'Tue, 14 Mar 2023 20:22:30 GMT'
aws-bootcamp-cruddur-2023-envoy-jwt-local-1    | 'server', 'envoy'
aws-bootcamp-cruddur-
```
