### ISSUE TITLE
All cluster endpoints are active despite health checks

### ISSUE THREAD

**Issue by lazovskiy** [envoyproxy/envoy#26066]
Hi there!

I'm trying to set up a proxy for PostgreSQL servers that forwards connections on the current Postgres master.
I have an HTTP endpoint that returns 200 at the master server and 500 on standby.
The problem is that even though active health checks fail on standby endpoints, connections are still distributed to every cluster endpoint.

Here is the configuration:
```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
static_resources:
  listeners:
  - name: postgres
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5432
    filter_chains:
    - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: postgres
            cluster: postgres_cluster
  clusters:
  - name: postgres_cluster
    connect_timeout: 1s
    type: STATIC
    lb_policy: ROUND_ROBIN
    outlier_detection: null
    health_checks:
    - http_health_check:
        path: /master
      interval: 1s
      no_traffic_interval: 5s
      timeout: 1s
      unhealthy_threshold: 2
      healthy_threshold: 1
      transport_socket_match_criteria:
        useTlsAuth: true
    transport_socket_matches:
    - name: useTlsAuth
      match:
        useTlsAuth: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /etc/envoy/tls/client.crt
              private_key:
                filename: /etc/envoy/tls/client.key
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
          - endpoint:
              hostname: postgres-0
              address:
                socket_address:
                  address: 10.0.0.1
                  port_value: 5432
              health_check_config:
                hostname: postgres-0
                port_value: 443
          - endpoint:
              hostname: postgres-1
              address:
                socket_address:
                  address: 10.0.0.2
                  port_value: 5432
              health_check_config:
                hostname: postgres-1
                port_value: 443
          - endpoint:
              hostname: postgres-2
              address:
                socket_address:
                  address: 10.0.0.3
                  port_value: 5432
              health_check_config:
                hostname: postgres-2
                port_value: 443
```

In the clusters dump, I can see
```
     "health_status": {
      "failed_active_health_check": true,
      "eds_health_status": "HEALTHY"
     },
```
for standbys, and
```
     "health_status": {
      "eds_health_status": "HEALTHY"
     },
```
for the master.

There are two issues here:
1. Even though the endpoint is failing its active health check, it's not removed from load balancing
2. I can stop postgres at the target server, but the corresponding endpoint is not removed from balancing. Envoy will report the "Connection refused" error to log, and the client connection is closing immediately.

Why is that happening, and how can I teach the envoy to respect active health checks?
