### ISSUE TITLE
envoy VCL interface  registered  faild with Vpp 

### ISSUE THREAD

**Issue by YanLongDai** [envoyproxy/envoy#26085]
***Title*: envoy 1.21.6 VCl can‘t work with vpp 21.10，I suspect there is a problem with the compilation process envoy，Please take a look ， I need  help，  thank you**

**start envoy log：** 
![envoy_log](https://user-images.githubusercontent.com/127860365/225019944-fc62e610-4e43-4a2d-9432-f4d79f1ac86d.jpg)

**vpp log：**
![vpp_log](https://user-images.githubusercontent.com/127860365/225020473-c296954b-c4d3-4a9c-9a68-65b314e8ca91.jpg)

**vcl.conf :**
```
vcl {
  rx-fifo-size 400000
  tx-fifo-size 400000
  app-scope-global
  api-socket-name /tmp/vpp-api.sock
  use-mq-eventfd
}

```

`**envoy proxy.yaml:**`

```
 admin:
  access_log_path: /tmp/envoy.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
static_resources:
  listeners:
  # define a reverse proxy on :10001 that always uses :80 as an origin.
  - address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: proxy_service
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: proxy_service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: proxy_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.1.1
                port_value: 80
bootstrap_extensions:
  - name: envoy.extensions.vcl.vcl_socket_interface
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.vcl.v3alpha.VclSocketInterface
default_socket_interface: "envoy.extensions.vcl.vcl_socket_interface"
```

**Envoy Compile and run steps：**

1、bazel build -c dbg --verbose_failures --verbose_explanations --config=clang //contrib/exe:envoy-static --sandbox_debug
2、start_envoy.sh:
```
#!/usr/bin/env bash
BIN_TYPE=k8-dbg
ENVOY_CFG=configs/proxy.yaml
VCL_CFG=configs/vcl_2.conf

sudo taskset -c 1 sh -c "VCL_CONFIG=$VCL_CFG /home/daiyl/01_work/envoy_vpp/envoy/bazel-bin/contrib/exe/envoy-static --concurrency 1 -c $ENVOY_CFG  --log-level debug
```

3、VPP Compile and run separately，According to the official website
```
unix {
  nodaemon
  interactive
  exec configs/vpp.cli
  log /tmp/vpp.log
  full-coredump
  #cli-listen /run/vpp/cli.sock
  cli-listen 127.0.0.1:5002 
  gid vpp
}

heapsize 4g
api-trace {
  on
}

api-segment {
  global-size 2G
  api-size 1G
  gid vpp
}

socksvr {
  socket-name /tmp/vpp-api.sock
}

cpu {
  skip-cores 0
  main-core 1

  ## Set logical CPU core(s) where worker threads are running. For performance testing make
  ## sure the cores are on the same numa as the NIC(s). Use lscpu to determine the numa of
  ## a cpu and "sh hardware" in vpp cli to determine the numa of a NIC
  corelist-workers 2
}

buffers {
  buffers-per-numa 16384
}

dpdk {
  # Note:
  # - Assuming only one NIC
  # - The PCI address is an example, the actual one should be found using dpdk_devbind
  #    https://github.com/DPDK/dpdk/blob/main/usertools/dpdk-devbind.py
  # - Number of rx queues (num-rx-queus should be number of workers + 1)
#  dev 0000:00:18.0 {
#    num-tx-desc 256
#    num-rx-desc 256
#    num-rx-queues 2
#  }
 # dev 0000:00:13.0 {
 #   num-tx-desc 256
 #   num-rx-desc 256
 #   num-rx-queues 2
#  }

}

session {
  evt_qs_memfd_seg
  event-queue-length 100000
}




```
