### ISSUE TITLE
What is the proper config for a gRPC stream

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#26084]
I'm developing a pair of client & server with gRPC stream. Here is the code of my client:

Basically, the client will send a msg to the server and then the server will keep sending msgs to the client.

Here is how the server works:
```
// receive msg from the client
// send msg1 to client
// sleep(1s)
// send msg2 to client
// sleep(1s)
...
...
```

I just tested the client and the server, it works fine without any error.

However, when I use Envoy as the gateway of the server, the client always disconnect after receiving some msgs from the server.

Here is the config of my Envoy:
```
  - name: listener_robot_grpc
    address:
      socket_address: {address: 0.0.0.0, port_value: 14461}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 200s
          stream_idle_timeout: 100s
          upgrade_configs:
          - upgrade_type: websocket
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["example.com:*"]
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: cluster_robot_grpc
                  timeout: 15s    # Hmm... should this be 0s???

  - name: cluster_robot_grpc
    connect_timeout: 30s
    type: LOGICAL_DNS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
        common_http_protocol_options:
          idle_timeout: 3600s
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_robot_grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: 172.16.0.25, port_value: 8607}
```

After testing many times, I just found that it seems that `timeout: 15s` control the disconnection of the client.

I'm confused. As the server is keeping sending messages to the client, why the config `timeout` under `route` could disconnect the client? As my understanding, there are always msgs in this connection, which should mean that this connnection is active, so why would Envoy disconnect it?
