### ISSUE TITLE
Getting the error : Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''

### ISSUE THREAD

**Issue by ruthwik3690** [envoyproxy/envoy#26118]
Getting the following error : 
`Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''`

My envoy version is 1.25.1.
I am facing this issue while validating the Envoy environment.

my YAML snippet : 
```
http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

I have verified that my YAML has the latest configuration like, `filters.http.router` instead of ` http.router `

Please help me on how to proceed with this.

**Comment by phlax** [comment]
see here https://github.com/envoyproxy/envoy/issues/21464#issuecomment-1139540234

**Comment by phlax** [comment]
noticing that your snippet does include the `typed_config` - so not clear exactly - would need to see all config and logs -  but that is what the error is telling you

**Comment by ruthwik3690** [comment]
i have seen the issue mentioned above, but the yaml file has the correct configuration.
how to solve this error now?

**Comment by phlax** [comment]
as i said - the error is telling you that you are missing the router `typed_config` configuration - check your config - perhaps start with something simple until you have it working

**Comment by phlax** [comment]
that is not a valid envoy config - i would need to see the total config to comment further

**Comment by ruthwik3690** [comment]
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          scheme_header_transformation:
            scheme_to_overwrite: https
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io

```
