### ISSUE TITLE
Sharp increase of active connections after 'enable_reuse_port' enable

### ISSUE THREAD

**Issue by usovamaria** [envoyproxy/envoy#26120]
*Title*: *Sharp increase of active connections after turning on option 'enable_reuse_port'*

*Description*:
We're working on tuning Envoy in order to speed it up and make our timings better. After upgrading Envoy to `1.24.1` we noticed that `enable_reuse_port` became `true` by default. We made some experiments and saw sharp increase of active connections for some of our clusters when enabling this option . 

This increase wasn't equal among the clusters (e.g. x2 or smth like this). It strongly depends on clusters' load. Moreover, there's a risk over overflowing circuit breakers (this happened to our cluster, that's why we disabled this option).

Moreover, the number of answer codes hasn't changed.

Here's the graph (annotation shows timestamp of enabling port reuse):

<img width="1051" alt="Screen Shot 2023-03-16 at 14 28 40" src="https://user-images.githubusercontent.com/62989519/225603552-5daa3ae6-5a80-4377-b9b6-441722a733d8.png">

When tcpdump'ing, we saw lots of "empty" requests to services that were quite similar to health checking requests. 

According to the docs, reusing ports allows threads (Envoy workers) to be equally loaded and manage requests more efficiently. We don't see any other reasons for increased number of active connections but `enable_reuse_port`. We tend to thinks that it is incorrect behavior and that may be a bug.

Environment and settings:
1. Ubuntu 20.04, kernel 5.8.0-40-generic
2. IPv6 network
3. Exact envoy listener settings:

```
static_resources:
  listeners:
  - name: listener_lb_int
    address: { socket_address: { address: "::", port_value: 80 } }
    enable_reuse_port: false
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          common_http_protocol_options: { idle_timeout: 120s }
          http2_protocol_options: { max_outbound_frames: 20000 }
          rds:
            route_config_name: local_route
            config_source: *xds_config
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

**In case this isn't a bug, the questions are**:  
1) Why did connections number increase?
2) What are these new connections for?

*Relevant Links*:

* Similar issue: https://github.com/envoyproxy/envoy/issues/18700
