### ISSUE TITLE
Want a working Example of upstream_http_filters

### ISSUE THREAD

**Issue by mjallday** [envoyproxy/envoy#26138]
*Title*: *Want a working Example of upstream_http_filters*

*Description*:

Looking at https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto and trying to understand how to use the `upstream_http_filters` section. 

I've been attempting to inject a header into a forward proxy request in envoy and whenever I use this config section I get the following message

```
[2023-03-16 23:08:55.359][1][critical][main] [source/server/server.cc:131] error initializing configuration '/etc/terminate_http1_connect.yaml': Error: non-terminal filter named upstream_header of type envoy.filters.http.header_mutation is the last filter in a router upstream http filter chain.
[2023-03-16 23:08:55.360][1][info][main] [source/server/server.cc:980] exiting
Error: non-terminal filter named upstream_header of type envoy.filters.http.header_mutation is the last filter in a router upstream http filter chain.
```

Here's the partial config section to help show what i'm trying to do

```yaml
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_http_filters:
              - name: upstream_header
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                  mutations:
                    request_mutations:
                      append:
                        header:
                          key: "a"
                          value: "b"
```

The full config looks like this

```yaml
# `curl -k -v -x 127.0.0.1:10001 --proxy-header "foo: bar" https://127.0.0.1:10003`.
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9902
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        protocol: TCP
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: true
          stat_prefix: ingress_http
          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: service_google
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                    resolvers:
                    - socket_address:
                        address: "8.8.8.8"
                        port_value: 53
                    dns_resolver_options:
                      use_tcp_for_dns_lookups: true
                      no_default_search_domain: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_http_filters:
              - name: upstream_header
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                  mutations:
                    request_mutations:
                      append:
                        header:
                          key: "a"
                          value: "b"
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: service_google
    lb_policy: CLUSTER_PROVIDED
    original_dst_lb_config:
      use_http_header: true
    connect_timeout: 6s
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true
```

I saw https://github.com/envoyproxy/envoy/issues/7767 which mentions the terminal filters I could apply after this are "tcp_proxy, router, and HCM" but these do not seem to be acceptable options to place here. Valid options appear to be https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-msg-extensions-filters-network-http-connection-manager-v3-httpfilter.

I'm sure this I'm missing something simple, anyone got an example of how to use this functionality?

**Comment by wbpcode** [comment]
If an explicit upstream filter is configured, then an additional  `envoy.filters.http.upstream_codec` must be configured.

```
              upstream_http_filters:
              - name: upstream_header
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                  mutations:
                    request_mutations:
                      append:
                        header:
                          key: "a"
                          value: "b"
              - name: envoy.filters.http.upstream_codec
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec

```
