### ISSUE TITLE
Can't use domain name for dogstatsd address

### ISSUE THREAD

**Issue by stan-irl** [envoyproxy/envoy#26150]
# Can't use domain name for dogstatsd address

It seems that its not possible to pass a domain name as the address of a DogStatsdSink.
```
stats_sinks:
  - name: datadog
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
      address:
        socket_address:
          address: datadog.dev
          port_value: 8125
```

throws error: 
```
[2023-03-17 13:02:10.471][11][critical][main] [source/server/server.cc:131] error initializing configuration '/app/build/envoy.yaml': malformed IP address: datadog.dev
malformed IP address: datadog.dev
```

This seems like a pretty common usecase? Does anyone have a workaround?

## Relevant Links
Previous discussion: https://github.com/envoyproxy/envoy/issues/3143#issuecomment-383435852
