### ISSUE TITLE
Envoy crash while dynamic update of UDP lb_endpoints

### ISSUE THREAD

**Issue by dergeberl** [envoyproxy/envoy#26206]
*Title*: *Envoy crash while dynamic update of UDP lb_endpoints*

After clarify with `envoy-security@googlegroups.com` (this is config driven issue) I open a issue here in GitHub.

*Description*:

We found a issue where the envoy crashes, while dynamic updateding the `UDP` lb_endpoints. If you remove and/or add `lb_endpoints` to a `UDP` listener the envoy crashes while the next `UDP` connection.

*Repro steps*:

1. Start envoy with the following config. (There is no need that the `lb_endpoints` are reachable)

`envoy -c envoy.yaml`

>`envoy.yaml`
```yaml
node:
  id: foobar
  cluster: foobar

dynamic_resources:
  cds_config:
    path: /home/debian/cds.yaml
  lds_config:
    path: /home/debian/lds.yaml

```

>`lds.yaml`
```yaml
version_info: "1"
resources:  
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_0
    address:
      socket_address:
        protocol: UDP
        address: 127.0.0.1
        port_value: 12345
    udp_listener_config:
      downstream_socket_config:
        max_rx_datagram_size: 9000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: service
        matcher:
            on_no_match:
              action:
                name: route
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                  cluster: service_udp
        upstream_socket_config:
          max_rx_datagram_size: 9000
```

>`cds.yaml` - with 2 endpoints
```yaml
version_info: "1"
resources:  
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.10.10
                port_value: 54321
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.10.20
                port_value: 54321
```

2. Connect to the listener port with netcat (no reply if nothing runs on the `lb_endpoints`)

`echo "test" | nc -u 127.0.0.1 12345`

3. Update the config to remove a `lb_endpoint`
 
>`cds-2.yaml` - with 1 endpoints
```yaml
version_info: "2"
resources:  
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.10.10
                port_value: 54321
```

`mv cds-2.yaml cds.yaml`

4. Connect to the listener port with netcat (no reply if nothing runs on the `lb_endpoints`)

`echo "test" | nc -u 127.0.0.1 12345`

5. Update the config to add a lb_endpoint

>`cds-3.yaml` - with 2 endpoints
```yaml
version_info: "3"
resources:  
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.10.10
                port_value: 54321
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.10.20
                port_value: 54321
```

`mv cds-3.yaml cds.yaml`

6. Connect to the listener port with netcat (here envoy crashes)

`echo "test" | nc -u 127.0.0.1 12345`

*Call Stack*:

```
[2023-03-20 16:40:03.955][769][critical][backtrace] [./source/server/backtrace.h:104] Caught Segmentation fault, suspect faulting address 0xd8
[2023-03-20 16:40:03.955][769][critical][backtrace] [./source/server/backtrace.h:91] Backtrace (use tools/stack_decode.py to get line numbers):
[2023-03-20 16:40:03.955][769][critical][backtrace] [./source/server/backtrace.h:92] Envoy version: afa98867c807dee0d833da701ba3ab0c9ace9ada/1.25.2/Clean/RELEASE/BoringSSL
[2023-03-20 16:40:03.956][769][critical][backtrace] [./source/server/backtrace.h:96] #0: __restore_rt [0x7f8595ed3140]
[2023-03-20 16:40:03.988][769][critical][backtrace] [./source/server/backtrace.h:96] #1: Envoy::Extensions::UdpFilters::UdpProxy::UdpProxyFilter::StickySessionClusterInfo::onData() [0x5594210460d0]
[2023-03-20 16:40:04.003][769][critical][backtrace] [./source/server/backtrace.h:96] #2: Envoy::Extensions::UdpFilters::UdpProxy::UdpProxyFilter::onData() [0x559421044b13]
[2023-03-20 16:40:04.017][769][critical][backtrace] [./source/server/backtrace.h:96] #3: Envoy::Server::ActiveRawUdpListener::onDataWorker() [0x559422713a9d]
[2023-03-20 16:40:04.031][769][critical][backtrace] [./source/server/backtrace.h:96] #4: Envoy::Network::UdpListenerImpl::processPacket() [0x559422799900]
[2023-03-20 16:40:04.046][769][critical][backtrace] [./source/server/backtrace.h:96] #5: Envoy::Network::passPayloadToProcessor() [0x55942294ba3a]
[2023-03-20 16:40:04.060][769][critical][backtrace] [./source/server/backtrace.h:96] #6: Envoy::Network::Utility::readFromSocket() [0x55942294d0b4]
[2023-03-20 16:40:04.074][769][critical][backtrace] [./source/server/backtrace.h:96] #7: Envoy::Network::Utility::readPacketsFromSocket() [0x55942294dec3]
[2023-03-20 16:40:04.088][769][critical][backtrace] [./source/server/backtrace.h:96] #8: Envoy::Network::UdpListenerImpl::handleReadCallback() [0x5594227992d6]
[2023-03-20 16:40:04.102][769][critical][backtrace] [./source/server/backtrace.h:96] #9: Envoy::Network::UdpListenerImpl::onSocketEvent() [0x559422799096]
[2023-03-20 16:40:04.117][769][critical][backtrace] [./source/server/backtrace.h:96] #10: std::__1::__function::__func<>::operator()() [0x559422782c31]
[2023-03-20 16:40:04.131][769][critical][backtrace] [./source/server/backtrace.h:96] #11: Envoy::Event::FileEventImpl::assignEvents()::$_1::__invoke() [0x559422783ffd]
[2023-03-20 16:40:04.146][769][critical][backtrace] [./source/server/backtrace.h:96] #12: event_process_active_single_queue [0x559422b35d00]
[2023-03-20 16:40:04.161][769][critical][backtrace] [./source/server/backtrace.h:96] #13: event_base_loop [0x559422b34641]
[2023-03-20 16:40:04.176][769][critical][backtrace] [./source/server/backtrace.h:96] #14: Envoy::Server::WorkerImpl::threadRoutine() [0x5594220971c4]
[2023-03-20 16:40:04.190][769][critical][backtrace] [./source/server/backtrace.h:96] #15: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::{lambda()#1}::__invoke() [0x559422b3c193]
[2023-03-20 16:40:04.190][769][critical][backtrace] [./source/server/backtrace.h:96] #16: start_thread [0x7f8595ec7ea7]
```

> Testet with envoy version `1.25.2` and `v1.24.3` (from the github releases) on debian11.

**Comment by alyssawilk** [comment]
cc @adisuissa

**Comment by JuliusSte** [comment]
Hey,
are there any news regarding this bug? Would be greatly appreciated. 

Thanks :-)

**Comment by nschad** [comment]
bump

**Comment by robinschneider** [comment]
bump

**Comment by robinschneider** [comment]
bump

**Comment by robinschneider** [comment]
bump

**Comment by Kumm-Kai** [comment]
bump

**Comment by robinschneider** [comment]
Bump

**Comment by robinschneider** [comment]
Bump

**Comment by adams-shaun** [comment]
not stale

**Comment by eranr** [comment]
I am experiencing the exact same behavior with 1.30.2 (post the above merge #33824).
**Dynamic update to UDP proxy (CDS) followed by issuing UDP traffic causes a crash** with the exact same stack trace as above. The dynamic change is adding an endpoint to a cluster. All the information is provided below.
Steps to repro:
1. start the cluster with one endpoint (docker-compose and relevant Dockerfiles are provided below).
2. Add an endpoint to the cluster
3. Send a UDP packet ( echo -n "hello" >/dev/udp/192.168.1.10/12000)
4. Crash...
Interestingly, if after the update in step 2 above  I revert the CDS configuration back to a single endpoint, the UDP traffic works.
Starting with 2 endpoints and reducing to 1 has the exact same behavior.

envoy.yaml
```node:
  cluster: default-cluster
  id: default-node

dynamic_resources:
  cds_config:
    resource_api_version: V3
    path_config_source:
      path: /etc/envoy/cds.yaml
  lds_config:
    resource_api_version: V3
    path_config_source:
      path: /etc/envoy/lds.yaml

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10001
```
lds.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.listener.v3.Listener
    name: listener_1
    address:
      socket_address:
        protocol: UDP
        address: 192.168.20.10
        port_value: 12000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: service
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: service_vanilla_udp
```

1 endpoint cds.yaml
```resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_vanilla_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_vanilla_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.30
                port_value: 12000
```
2 endpoints cds.yaml
```resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_vanilla_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_vanilla_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.30
                port_value: 12000
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.40
                port_value: 12000
```
Stack trace
```
envoy-udp  | [2024-06-09 19:46:26.439][25][debug][misc] [source/common/network/utility.cc:701] Receive a packet with 4 bytes from 192.168.20.1:34759
envoy-udp  | [2024-06-09 19:46:26.439][25][critical][backtrace] [./source/server/backtrace.h:127] Caught Segmentation fault, suspect faulting address 0x18
envoy-udp  | [2024-06-09 19:46:26.439][25][critical][backtrace] [./source/server/backtrace.h:111] Backtrace (use tools/stack_decode.py to get line numbers):
envoy-udp  | [2024-06-09 19:46:26.439][25][critical][backtrace] [./source/server/backtrace.h:112] Envoy version: d79f6e8d453ee260e9094093b8dd31af0056e67b/1.30.2/Clean/RELEASE/BoringSSL
envoy-udp  | [2024-06-09 19:46:26.439][25][critical][backtrace] [./source/server/backtrace.h:114] Address mapping: 556d71e78000-556d74820000 /usr/local/bin/envoy
envoy-udp  | [2024-06-09 19:46:26.439][25][critical][backtrace] [./source/server/backtrace.h:121] #0: [0x7fdf0a9e6520]
envoy-udp  | [2024-06-09 19:46:26.451][25][critical][backtrace] [./source/server/backtrace.h:119] #1: Envoy::Extensions::UdpFilters::UdpProxy::UdpProxyFilter::StickySessionClusterInfo::onData() [0x556d72582ffa]
envoy-udp  | [2024-06-09 19:46:26.464][25][critical][backtrace] [./source/server/backtrace.h:119] #2: Envoy::Extensions::UdpFilters::UdpProxy::UdpProxyFilter::onData() [0x556d72580f0f]
envoy-udp  | [2024-06-09 19:46:26.476][25][critical][backtrace] [./source/server/backtrace.h:119] #3: Envoy::Server::ActiveRawUdpListener::onDataWorker() [0x556d73e9bd1d]
envoy-udp  | [2024-06-09 19:46:26.488][25][critical][backtrace] [./source/server/backtrace.h:119] #4: Envoy::Network::UdpListenerImpl::processPacket() [0x556d73e9ffb0]
envoy-udp  | [2024-06-09 19:46:26.500][25][critical][backtrace] [./source/server/backtrace.h:119] #5: Envoy::Network::(anonymous namespace)::passPayloadToProcessor() [0x556d741ca791]
envoy-udp  | [2024-06-09 19:46:26.512][25][critical][backtrace] [./source/server/backtrace.h:119] #6: Envoy::Network::Utility::readFromSocket() [0x556d741c845f]
envoy-udp  | [2024-06-09 19:46:26.524][25][critical][backtrace] [./source/server/backtrace.h:119] #7: Envoy::Network::Utility::readPacketsFromSocket() [0x556d741c95ff]
envoy-udp  | [2024-06-09 19:46:26.536][25][critical][backtrace] [./source/server/backtrace.h:119] #8: Envoy::Network::UdpListenerImpl::handleReadCallback() [0x556d73e9f956]
envoy-udp  | [2024-06-09 19:46:26.548][25][critical][backtrace] [./source/server/backtrace.h:119] #9: Envoy::Network::UdpListenerImpl::onSocketEvent() [0x556d73e9f6fe]
envoy-udp  | [2024-06-09 19:46:26.560][25][critical][backtrace] [./source/server/backtrace.h:119] #10: std::__1::__function::__func<>::operator()() [0x556d73f98a31]
envoy-udp  | [2024-06-09 19:46:26.572][25][critical][backtrace] [./source/server/backtrace.h:119] #11: Envoy::Event::FileEventImpl::assignEvents()::$_1::__invoke() [0x556d73f99fdd]
envoy-udp  | [2024-06-09 19:46:26.587][25][critical][backtrace] [./source/server/backtrace.h:119] #12: event_process_active_single_queue [0x556d741ea810]
envoy-udp  | [2024-06-09 19:46:26.599][25][critical][backtrace] [./source/server/backtrace.h:119] #13: event_base_loop [0x556d741e9151]
envoy-udp  | [2024-06-09 19:46:26.612][25][critical][backtrace] [./source/server/backtrace.h:119] #14: Envoy::Server::WorkerImpl::threadRoutine() [0x556d73827f9f]
envoy-udp  | [2024-06-09 19:46:26.624][25][critical][backtrace] [./source/server/backtrace.h:119] #15: Envoy::Thread::PosixThreadFactoryImpl::createThread()::{lambda()#1}::__invoke() [0x556d742667d3]
envoy-udp  | [2024-06-09 19:46:26.624][25][critical][backtrace] [./source/server/backtrace.h:121] #16: [0x7fdf0aa38ac3]
```

My udp-envoy Dockerfile
```
FROM envoyproxy/envoy:debug-v1.30.2

COPY --chmod=777 envoy/envoy/conf/envoy.yaml /etc/envoy
COPY --chmod=777 envoy/envoy/conf/cds.yaml /etc/envoy
COPY --chmod=777 envoy/envoy/conf/lds.yaml /etc/envoy
COPY --chmod=777 envoy/envoy/conf/cds_1.yaml /etc/envoy
COPY --chmod=777 envoy/envoy/conf/cds_2.yaml /etc/envoy
COPY --chmod=777 envoy/envoy/conf/switch_2_1.sh /etc/envoy
COPY --chmod=777 envoy/envoy/conf/switch_2_2.sh /etc/envoy
```
The "switch to" bash scripts atomically change the cds.yaml file with either the content of cds_1.yaml  or cds_2.yaml (doing cp to a tmp file followed by mv)

For completion:
docker-compose.yaml
```
services:
  udp-backend1:
    build:
      context: .
      dockerfile: udp-backend1/Dockerfile
    image: udp-backend1
    container_name: udp-backend1
    restart: unless-stopped
    networks:
        backend-network:
          ipv4_address: 192.168.10.30
  udp-backend2:
    build:
      context: .
      dockerfile: udp-backend2/Dockerfile
    image: udp-backend2
    container_name: udp-backend2
    restart: unless-stopped
    networks:
        backend-network:
          ipv4_address: 192.168.10.40
  envoy-udp:
    build:
      context: .
      dockerfile: envoy/Dockerfile
    image: envoy_udp
    container_name: envoy-udp
    environment:
      - loglevel=debug
    networks:
        backend-network:
          ipv4_address: 192.168.10.100
        frontend-network:
          ipv4_address: 192.168.20.10
    depends_on:
      - udp-backend1
      - udp-backend2

networks:
  backend-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.10.0/24"
  frontend-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.20.0/24"
```

udp-backend1[2]/Dockerfile
```
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y python3

WORKDIR backend1[2]
COPY udp-backend/server.py ./
CMD ["python3", "-u", "server.py" ,"backend-1[2]"]
```

udp-backend/server.py
```
import sys
import socket

if __name__ == '__main__':
    server_name = sys.argv[1]
    server_udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    server_udp_socket.bind(('', 12000))

    while True:
        message, address = server_udp_socket.recvfrom(1024)
        port = address[1]
        message = message.upper()
        print(f"Got message {message}")
        server_udp_socket.sendto(f"{server_name}: {message}".encode('utf-8'), address)
```

cds_1.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_vanilla_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_vanilla_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.30
                port_value: 12000
```
cds_2.yaml
```
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: service_vanilla_udp
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_vanilla_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.30
                port_value: 12000
        - endpoint:
            address:
              socket_address:
                protocol: UDP
                address: 192.168.10.40
                port_value: 12000
```

switch_2_1.sh
```
cp cds_1.yaml cds_tmp
mv cds_tmp cds.yaml
```
switch_2_2.sh
```
cp cds_2.yaml cds_tmp
mv cds_tmp cds.yaml
```

Envoy's log during switching from 1 to 2 endpoints:
```
envoy-udp     | [2024-06-09 20:42:49.886][1][debug][upstream] [source/common/upstream/cds_api_helper.cc:51] cds: add/update cluster 'service_vanilla_udp'
envoy-udp     | [2024-06-09 20:42:49.886][1][info][upstream] [source/common/upstream/cds_api_helper.cc:71] cds: added/updated 1 cluster(s), skipped 0 unmodified cluster(s)
envoy-udp     | [2024-06-09 20:42:49.886][17][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][23][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][22][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1283] updating TLS cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][16][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1283] updating TLS cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][17][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][22][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][22][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][20][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][20][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][15][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][15][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][16][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][16][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][23][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][1][debug][config] [source/extensions/config_subscription/filesystem/filesystem_subscription_impl.cc:91] Filesystem config update accepted for /etc/envoy/cds.yaml: resources {
envoy-udp     |   [type.googleapis.com/envoy.config.cluster.v3.Cluster] {
envoy-udp     |     name: "service_vanilla_udp"
envoy-udp     |     type: STATIC
envoy-udp     |     load_assignment {
envoy-udp     |       cluster_name: "service_vanilla_udp"
envoy-udp     |       endpoints {
envoy-udp     |         lb_endpoints {
envoy-udp     |           endpoint {
envoy-udp     |             address {
envoy-udp     |               socket_address {
envoy-udp     |                 protocol: UDP
envoy-udp     |                 address: "192.168.10.30"
envoy-udp     |                 port_value: 12000
envoy-udp     |               }
envoy-udp     |             }
envoy-udp     |           }
envoy-udp     |         }
envoy-udp     |         lb_endpoints {
envoy-udp     |           endpoint {
envoy-udp     |             address {
envoy-udp     |               socket_address {
envoy-udp     |                 protocol: UDP
envoy-udp     |                 address: "192.168.10.40"
envoy-udp     |                 port_value: 12000
envoy-udp     |               }
envoy-udp     |             }
envoy-udp     |           }
envoy-udp     |         }
envoy-udp     |       }
envoy-udp     |     }
envoy-udp     |   }
envoy-udp     | }
envoy-udp     |
envoy-udp     | [2024-06-09 20:42:49.886][1][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:76] notification: fd: 1 mask: 80 file: cds.yaml
envoy-udp     | [2024-06-09 20:42:49.886][25][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1283] updating TLS cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][24][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1283] updating TLS cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][24][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.886][24][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
envoy-udp     | [2024-06-09 20:42:49.886][25][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:1542] membership update for TLS cluster service_vanilla_udp added 2 removed 0
envoy-udp     | [2024-06-09 20:42:49.887][25][debug][filter] [source/extensions/filters/udp/udp_proxy/udp_proxy_filter.cc:44] udp proxy: attaching to cluster service_vanilla_udp
```
