### ISSUE TITLE
Are cert files watched when defining them in `static_resources.secrets`?

### ISSUE THREAD

**Issue by zhouxiaobo1990** [envoyproxy/envoy#26276]
I am looking at [this example](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-one-static-resource). Cert files are defined in `static_resources.secrets`:

```
static_resources:
  secrets:
    - name: server_cert
      tls_certificate:
        certificate_chain:
          filename: certs/servercert.pem
        private_key:
          filename: certs/serverkey.pem
    - name: client_cert
      tls_certificate:
        certificate_chain:
          filename: certs/clientcert.pem
        private_key:
          filename: certs/clientkey.pem
    - name: validation_context
      validation_context:
        trusted_ca:
          filename: certs/cacert.pem
        verify_certificate_hash:
          E0:F3:C8:CE:5E:2E:A3:05:F0:70:1F:F5:12:E3:6E:2E:97:92:82:84:A2:28:BC:F7:73:32:D3:39:30:A1:B6:FD
```

They are referenced in `tls_certificate_sds_secret_configs` and `validation_context_sds_secret_config`:
```
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: server_cert
            validation_context_sds_secret_config:
              name: validation_context
```

Will envoy watch the `certs/` directory in this case? Or shall I follow [example three](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-three-certificate-rotation-for-xds-grpc-connection) instead?
