### ISSUE TITLE
udp: support udp proxy to use original_dst_cluster 

### ISSUE THREAD

**Issue by skiptomyliu** [envoyproxy/envoy#26285]
*Title*: support udp proxy to use original_dst_cluster 

*Description*:
Looking to forward UDP traffic that has been redirected via iptables to use the original_dst_cluster, identical to how TCP is supported via the [original_dst filter](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_dst_filter#config-listener-filters-original-dst)

Attempted the following config but looks like UDP only supports a single listener filter, so seems like we need to extend the udp_proxy listener similarly what was done with use_original_src_ip [[pr](https://github.com/envoyproxy/envoy/pull/12586)]

`error adding listener '0.0.0.0:10005': Only 1 UDP listener filter per listener supported`

```yaml
admin:
  access_log_path: admin_access.log
  address:
    socket_address:
      address: 127.0.0.1
      protocol: TCP
      port_value: 9901

static_resources:
  listeners:
    - name: original_dst_cluster_listener
      address:
        socket_address:
          protocol: UDP
          address: 0.0.0.0
          port_value: 10005
      listener_filters:
      - name: envoy.filters.listener.original_dst
        typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst"
      - name: envoy.filters.udp_listener.udp_proxy
        typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig"
            stat_prefix: udp_egress
            cluster: original_destination_cluster
  clusters:
  - name: original_dst_cluster
    connect_timeout: 5s
    lb_policy: CLUSTER_PROVIDED
    type: ORIGINAL_DST
    dns_lookup_family: V4_ONLY
```
