### ISSUE TITLE
Unable to get ssl connection info in stream info when starttls transport socket is used for both upstream/downstream

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#26344]
*Title*: *Unable to get ssl connection info in stream info when starttls transport socket is used for both upstream/downstream*

*Description*:
>When a starttls transport socket is configured for both listener and upstream cluster, ssl connection info like tls version, cipher used is not getting stored in stream_info and hence can't be used in access logs.

*Repro steps*:
> Run the below provided config example to see access log fields for ssl connection info, they will be empty.

*Config*:
> 

```
static_resources:
  listeners:
    - name: smtp
      address:
        socket_address: { address: 127.0.0.1, port_value: 8000 }
      filter_chains:
      - filters:
        - name: envoy.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            cluster: smtp_cluster
            access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: "./smtp_access.log"
                log_format:
                json_format:
                  upstream_peer_cert_v_end : "%UPSTREAM_PEER_CERT_V_END%"
                  upstream_peer_subject: "%UPSTREAM_PEER_SUBJECT%"
                  upstream_peer_issuer: "%UPSTREAM_PEER_ISSUER%"
                  upstream_tls_cipher: "%UPSTREAM_TLS_CIPHER%"
                  upstream_tls_version: "%UPSTREAM_TLS_VERSION%"
                  downstream_tls_cipher: "%DOWNSTREAM_TLS_CIPHER%"
                  downstream_tls_version: "%DOWNSTREAM_TLS_VERSION%"

        transport_socket:
          name: envoy.transport_sockets.starttls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.StartTlsConfig
            tls_socket_config:
              common_tls_context: {}

  clusters:
  - name: smtp_cluster

    transport_socket:
      name: envoy.transport_sockets.starttls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.UpstreamStartTlsConfig
        tls_socket_config:
          common_tls_context: {}
```

*Logs*:
> All the access log fields configured in above example will be emtpy e.g. ,"upstream_tls_cipher":"-"

**Comment by lizan** [comment]
You'll need a L4 filter (e.g. postgresql) that supports upstream/downstream starttls transport socket configured to make envoy actually receives/send STARTTLS.

cc @cpakulski

**Comment by VishalDamgude** [comment]
Hey @lizan , I am already developing a SMTP filter that contains STARTTLS command.

**Comment by VishalDamgude** [comment]
There is a PR open for this issue: https://github.com/envoyproxy/envoy/pull/26486

Kindly reopen this issue.

**Comment by Yuanguo-notebook** [comment]
Hi @VishalDamgude , I wonder if the PR fixes the issue. When I use tcpproxy with starttls, access log still all shows "null". 
```
{"downstream dns":null,"downstream_tls_cipher":null,"peer_subject":null,"uri":null,"downstream_tls_version":null}
```

config(using examples/double-proxy):
envoy-backend.yaml:
```
static_resources:
  listeners:
  - name: postgres_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5432
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: postgres_tcp
          cluster: postgres_cluster
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                json_format:
                  peer_subject: "%DOWNSTREAM_PEER_SUBJECT%"
                  downstream dns: "%DOWNSTREAM_PEER_DNS_SAN%"
                  uri: "%DOWNSTREAM_PEER_URI_SAN%"
                  downstream_tls_cipher: "%DOWNSTREAM_TLS_CIPHER%"
                  downstream_tls_version: "%DOWNSTREAM_TLS_VERSION%"
      transport_socket:
        name: envoy.transport_sockets.starttls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.StartTlsConfig
          tls_socket_config:
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: certs/servercert.pem
                private_key:
                  filename: certs/serverkey.pem
              validation_context:
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: proxy-postgres-frontend.example.com
                trusted_ca:
                  filename: certs/cacert.pem
      
  clusters:
  - name: postgres_cluster
    type: STRICT_DNS
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: postgres
                port_value: 5432
```
