### ISSUE TITLE
Routing decision based on first body chunk?

### ISSUE THREAD

**Issue by cbenien** [envoyproxy/envoy#2635]
This is a question, not a bug report.

I have a project with a difficult application protocol over HTTP. The use case involves streaming data from the client to the server in HTTP chunked encoding. The first chunk contains a session token. 

What we want to achieve is a load balancing solution where requests with the same session ID end up with the same backend server, something that would be very easy to achieve if the session ID were in an HTTP header. 

The other requirement is that we can't buffer the whole request in the proxy, the streaming data is real-time and very time critical, and besides that, the overall requests are long.

An example request might look like this:
```
POST / HTTP/1.1
Host: localhost:8081
User-Agent: Go-http-client/1.1
Transfer-Encoding: chunked

41
<data><sessionId>12345</sessionId><somethingElse>abc</somethingElse></data>

5c4
<Binary stream of data starts here>

```

I have tried the [Lua](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter.html#config-http-filters-lua-buffer-wrapper) integration and can see the sessionId by iterating through the [bodyChunks](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter.html#bodychunks). I tried to set an HTTP header, but at that time it's already too late because the headers have already been forwarded to the next filter. Error message: "header map can no longer be modified"

Here's my Lua script:
```
function envoy_on_request(req)

  for chunk in req:bodyChunks() do
    local data = chunk:getBytes(0, chunk:length())
    local _,sessionId,_ = string.match(data, "(<sessionId>)(.*)(</sessionId>)")

    if not (sessionId == nil) then
      req:logInfo("Session ID found - " .. sessionId)
      req:headers():add("X-SessionId", sessionId)
    end

end
```

Any other ideas how I could achieve this?

**Comment by dio** [comment]
Hi, @cbenien I'm not sure if you favour taking the c++ path. I tried to play around with your case in here: https://github.com/dio/envoy-filter-example/tree/experiment-2635 (modified version of [envoy-filter-example](https://github.com/envoyproxy/envoy-filter-example) to accommodate your case) in this very commit: https://github.com/dio/envoy-filter-example/commit/ad3f926fffdbd1ab0baf901c34d8bf14d0abec98

With a suboptimal matcher as you can check [here](https://github.com/dio/envoy-filter-example/commit/ad3f926fffdbd1ab0baf901c34d8bf14d0abec98#diff-d8cfb998e0f6ec1ea7d0de4b87e601b3R34) 😅and a simple config to httpbin as follow:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite: httpbin.org, cluster: service_bin }
          http_filters:
          - name: "sample"
            config: { key: session-id, val: ok }
          - name: envoy.router
  clusters:
  - name: service_bin
    connect_timeout: 25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: httpbin.org, port_value: 443 }}]
    tls_context: { sni: httpbin.org }
```
running it in my local I get it working:

![session](http://g.recordit.co/jK5RkPJD4I.gif)

NOTE: 

1. If you like us, we find ourselves wanting to add more than one custom filter to envoy for various reasons (e.g. proprietary, specific use-case etc). A setup, for having multiple filters can be seen in https://github.com/rotimanis/envoy-filter-example (while it is a WIP still)
2. About the config, as you can see from above yaml, I add an additional sample filter. The `key` will be the header key.

```yaml
          http_filters:
          - name: "sample"
            config: { key: session-id, val: ok }
          - name: envoy.router
```
