### ISSUE TITLE
mTLS and traffic split

### ISSUE THREAD

**Issue by adrienjt** [envoyproxy/envoy#2638]
# Background

I am preparing a traffic shift from a web API in a Swarm cluster (let's call it `swarm_api`) to the same API in a Kubernetes cluster (`k8s_api`). The two clusters are on distinct private networks. The API's clients are on the same private network as the Swarm cluster, making requests over HTTP. However, the Kubernetes cluster is isolated (and fully managed by a cloud provider; the nodes' network is abstracted); the connection must therefore be secured.

My plan is to add an edge envoy in the Swarm cluster (`swarm_proxy`) to split traffic between `swarm_api` and a second edge envoy in the Kubernetes cluster (`k8s_proxy`), which would route traffic to `k8s_api`. The connection between `swarm_proxy` and `k8s_proxy` must be secured with mutual TLS as it goes through the Internet.

```
Private network 1
                      (swarm_proxy)---HTTP--->(swarm_api)
____________________________|__________________________
Internet                    |
                          HTTPS
____________________________|__________________________
Private network 2           |
                            ⌄
                       (k8s_proxy)----HTTP---->(k8s_api)
```

# What I have so far

1) One the one hand, I have successfully prototyped a traffic split over HTTP, *without* mTLS:
    ```
    Private network 1
                          (swarm_proxy)---HTTP--->(swarm_api)
    ____________________________|__________________________
    Internet                    |
                              HTTP
    ____________________________|__________________________
    Private network 2           |
                                ⌄
                           (k8s_proxy)----HTTP---->(k8s_api)
    ```
    `swarm_proxy` uses an `http_connection_manager` to split traffic between `swarm_api` and `k8s_proxy`; `k8s_proxy` simply routes traffic to `k8s_api` (see configurations below).
2) On the other hand, I have successfully prototyped simple routing with mTLS:
    ```
    Private network 1
                          (swarm_proxy)
    ____________________________|__________________________
    Internet                    |
                              HTTPS
    ____________________________|__________________________
    Private network 2           |
                                ⌄
                           (k8s_proxy)----HTTP---->(k8s_api)
    ```
    `swarm_proxy` uses a `tcp_proxy` to route traffic to `k8s_proxy`; the envoy _cluster_ adds a `tls_context` including a client certificate; `k8s_proxy` requires TLS with client certificate, then routes traffic to `k8s_api` (see configurations below).

# Issue

Now I'm struggling to make both traffic split and mTLS work at the same time: if I try to combine the two approaches in a third prototype, `swarm_proxy` returns 301 Moved Permanently when it routes traffic to `k8s_proxy` (see configurations below).

Is there something I'm missing / don't understand, or is this a bug?

# Envoy Configurations

## Prototype 1: traffic split

```yaml
# swarm_proxy
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress
          route_config:
            virtual_hosts:
            - name: api
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/myapi/v1"
                route:
                  weighted_clusters:
                    runtime_key_prefix: routing.traffic_split.api
                    clusters:
                    - name: swarm_api
                      weight: 50
                    - name: k8s_proxy
                      weight: 50
          http_filters:
          - name: envoy.router
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
  clusters:
  - name: swarm_api
    type: strict_dns
    hosts:
    - socket_address:
        address: swarm_api
        port_value: 80
    connect_timeout: 1s
  - name: k8s_proxy
    type: strict_dns
    hosts:
    - socket_address:
        address: k8s_proxy # TODO replace with public DNS when implemented
        port_value: 80
    connect_timeout: 1s
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```

```yaml
# k8s_proxy
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress
          route_config:
            virtual_hosts:
            - name: k8s_api
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/myapi/v1"
                route:
                  cluster: k8s_api
          http_filters:
          - name: envoy.router
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
  clusters:
  - name: k8s_api
    type: strict_dns
    hosts:
    - socket_address:
        address: k8s_api
        port_value: 80
    connect_timeout: 1s
admin: {...}
```

## Prototype 2: mutual TLS

```yaml
# swarm_proxy
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress
          cluster: k8s_proxy
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
  clusters:
  - name: k8s_proxy
    type: strict_dns
    hosts:
    - socket_address:
        address: k8s_proxy # TODO replace with public DNS when implemented
        port_value: 443
    connect_timeout: 1s
    tls_context:
      common_tls_context:
        validation_context:
          trusted_ca:
            filename: /etc/certs/ca.crt.pem
        tls_certificates:
        - certificate_chain:
            filename: /etc/certs/swarm_proxy.crt.pem
          private_key:
            filename: /etc/certs/swarm_proxy.key.pem
admin: {...}
```

```yaml
# k8s_proxy
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress
          route_config:
            virtual_hosts:
            - name: k8s_api
              domains:
              - "*"
              require_tls: ALL
              routes:
              - match:
                  prefix: "/myapi/v1"
                route:
                  cluster: k8s_api
          http_filters:
          - name: envoy.router
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
      tls_context:
        require_client_certificate: true
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/certs/ca.crt.pem
          tls_certificates:
          - certificate_chain:
              filename: /etc/certs/k8s_proxy.crt.pem
            private_key:
              filename: /etc/certs/k8s_proxy.key.pem
  clusters:
  - name: k8s_api
    type: strict_dns
    hosts:
    - socket_address:
        address: k8s_api
        port_value: 80
    connect_timeout: 1s
admin: {...}
```

## Prototype 3: traffic split and mutual TLS (NOT WORKING)

```yaml
# swarm_proxy
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress
          route_config:
            virtual_hosts:
            - name: api
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/myapi/v1"
                route:
                  weighted_clusters:
                    runtime_key_prefix: routing.traffic_split.api
                    clusters:
                    - name: swarm_api
                      weight: 50
                    - name: k8s_proxy
                      weight: 50
          http_filters:
          - name: envoy.router
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout"
  clusters:
  - name: swarm_api
    type: strict_dns
    hosts:
    - socket_address:
        address: swarm_api
        port_value: 80
    connect_timeout: 1s
  - name: k8s_proxy
    type: strict_dns
    hosts:
    - socket_address:
        address: k8s_proxy # TODO replace with public DNS when implemented
        port_value: 443
    connect_timeout: 1s
    tls_context:
      common_tls_context:
        validation_context:
          trusted_ca:
            filename: /etc/certs/ca.crt.pem
        tls_certificates:
        - certificate_chain:
            filename: /etc/certs/swarm_proxy.crt.pem
          private_key:
            filename: /etc/certs/swarm_proxy.key.pem
admin: {...}
```

```yaml
# k8s_proxy : same as prototype 2
```
