### ISSUE TITLE
For load balancing, what's the best way to handle upstream gRPC server shutdown?

### ISSUE THREAD

**Issue by zhouxiaobo1990** [envoyproxy/envoy#26391]
Here is my envoy config:

```
  clusters:
    - name: cluster_0
      connect_timeout: 30s
      type: STATIC
      lb_policy: round_robin
      http2_protocol_options: {}
      health_checks:
        - timeout: 1s
          interval: 5s
          unhealthy_interval: 5s
          no_traffic_interval: 5s
          unhealthy_threshold: 1
          healthy_threshold: 1
          grpc_health_check: {}
      common_lb_config:
        healthy_panic_threshold: 
          value: 0
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      (gRPC server A)
              - endpoint:
                  address:
                    socket_address:
                      (gRPC server B)
```

While rolling restart the upstream gRPC servers, I want to make sure that downstream clients won't see any errors. What's the best way to achieve this?

My current solution is to implement the following logic in the gRPC server to handle shutdown signal:

- Make the health check service return `UNHEALTHY`.
- Sleep 10 seconds so that Envoy know about the `UNHEALTHY` status. (Skipping this may cause downstream client receiving gRPC errors.)
- Shutdown the gRPC server gracefully for pending requests.

The solution works but it's quite ugly.

An alternative solution is to update the list of endpoints through an xDS protocol. But this seems complicated.

Any other solutions?
