### ISSUE TITLE
Multiple health checks not supported

### ISSUE THREAD

**Issue by zihuaweng** [envoyproxy/envoy#26455]
Hi team, I am testing the health check feature but got Multiple health checks not supported error. But it seems to support multiple health checks based on the cluster proto. Is multiple health checks actually supported? If not, will it be supported in the future? 
https://github.com/envoyproxy/envoy/blob/084794dd06c36edbcb27e05dc06c9d56a72b403f/api/envoy/config/cluster/v3/cluster.proto#L861

envoy  version: afa98867c807dee0d833da701ba3ab0c9ace9ada/1.25.2/Distribution/RELEASE/BoringSSL
Below is my config 
```
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9000

node:
  cluster: mycluster
  id: test-id

static_resources:
  listeners:
  - name: listener_0

    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }

    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:  
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager  
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service_backend }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router         
  clusters:
  - name: service_backend
    type: EDS  
    connect_timeout: 0.25s
    ignore_health_on_host_removal: true
    health_checks: 
      - timeout: 1s
        interval: 5s
        unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check: 
          path: /healthz/1
      - timeout: 1s
        interval: 10s
        unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check: 
          path: /healthz/2
    eds_cluster_config:
      service_name: myservice
      eds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
          - envoy_grpc:
              cluster_name: eds_cluster
          refresh_delay: 5s
  - name: eds_cluster
    type: STATIC
    connect_timeout: 0.25s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: eds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
```

**Comment by wbpcode** [comment]
as far as i know, multiple health checkers are not supported for now.

Although i had a try (long time ago), but i didn't get it done. 😔

**Comment by zihuaweng** [comment]
Got it thanks! I also have a question about the routing behaviors when using STRICT DNS service discovery type. I found out that if using STRICT_DNS, envoy will do health checks but traffic will still be sent to all upstream hosts within the upstream cluster, even if they are unhealthy, is this expected? 

Example config
```
  clusters:
  - name: service_backend
    type: STRICT_DNS  
    lb_policy: RING_HASH
    health_checks: 
      - timeout: 1s
        interval: 1s
        unhealthy_threshold: 1
        healthy_threshold: 1
        http_health_check: 
          path: /healthz
    ring_hash_lb_config:
      minimum_ring_size: 1024
      maximum_ring_size: 8192
```
