### ISSUE TITLE
Redirect SchemeRewriteSpecifier doesn't seem to strip ports as specified

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#26516]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Redirect SchemeRewriteSpecifier doesn't seem to strip ports as specified

*Description*:
According to the docs
```
	// When the scheme redirection take place, the following rules apply:
	//  1. If the source URI scheme is ``http`` and the port is explicitly
	//     set to ``:80``, the port will be removed after the redirection
	//  2. If the source URI scheme is ``https`` and the port is explicitly
	//     set to ``:443``, the port will be removed after the redirection
```

However, with 
```
      redirect:
        pathRedirect: /full-path-replacement
        responseCode: FOUND
        schemeRedirect: http
```

I see:
* `Host: a:80` -> Location: http://a:80`
* `Host: a` -> Location: http://a`

Wwith 
```
      redirect:
        pathRedirect: /full-path-replacement
        responseCode: FOUND
        portRedirect: 80
        schemeRedirect: http
```

I see:
* `Host: a:80` -> Location: http://a:80`
* `Host: a` -> Location: http://a:80`

Neither of these seem to represent a way to strip the port, which the docs suggest.

Related is https://github.com/envoyproxy/envoy/pull/25573, which I believe suggests a new explicit field to strip.
