### ISSUE TITLE
Update CNCF Landscape Summary Table with Envoy details

### ISSUE THREAD

**Issue by siforster** [envoyproxy/envoy#26576]
Hi All,

The CNCF Business Value Subcommittee has developed a project summary table to supplement the CNCF Landscape and include further information about CNCF projects for the wider cloud native community. We would like to request the Envoy project submit a PR to the CNCF Landscape repository with additional details that will help further inform the community about your project and its use cases through the popular landscape and this new addition.

The table is located here: https://landscape.cncf.io/summary
There are directions located here: https://github.com/cncf/landscape/blob/master/readme_summary.md

Many thanks for this - we hope it will help further get the word out about your project.

Simon Forster
CNCF Business Value Subcommittee

**Comment by phlax** [comment]
thanks for raising this @siforster - i can follow up

**Comment by phlax** [comment]
k - so asking chatGPT do do this for me (who i find mostly useless, but perhaps on this occasion not too bad)

```yaml
 - item:
     name: Envoy
     homepage_url: https://www.envoyproxy.io
     project: graduated
     repo_url: https://github.com/envoyproxy/envoy
     logo: envoy.svg
     twitter: https://twitter.com/envoyproxy
     crunchbase: https://www.crunchbase.com/organization/cloud-native-computing-foundation
     extra:
       accepted: '2017-09-13'
       incubating: '2017-09-13'
       graduated: '2018-11-28'
       dev_stats_url: https://envoy.devstats.cncf.io/
       artwork_url: https://github.com/cncf/artwork/blob/master/examples/graduated.md#envoy-logos
       stack_overflow_url: https://stackoverflow.com/questions/tagged/envoyproxy
       slack_url: https://envoyproxy.slack.com/
       chat_channel: '#envoy'
       summary_personas: Developers, SREs, Platform Engineers, Network Engineers
       summary_tags: networking, service mesh, security, observability, API gateway
       summary_use_case: high-performance proxy server for cloud-native applications; service mesh implementation; API gateway
       summary_business_use_case: 'Secure, scalable, and resilient traffic management; observability and insights into application performance; API management and security at scale'
       summary_release_rate: quarterly
       summary_integrations: >-
         Istio, Linkerd, Consul Connect, OpenTelemetry, Prometheus, WebAssembly
       summary_intro_url: 'https://www.envoyproxy.io/learn/introduction-to-envoy'
 ```
 
 a starting point at least
