### ISSUE TITLE
Cannot rate-limit on dynamic metadata created with in Header-to-Metadata filter

### ISSUE THREAD

**Issue by pisces-period** [envoyproxy/envoy#26588]
*Title*: *Cannot rate-limit on dynamic metadata created with in Header-to-Metadata filter*

*Description*:
Hi, I'm somewhat of a n00b with Envoy - it's a complex product and sifting through the documentation I couldn't find a solution to my problem.

My end goal is to use Envoy filters to configure path-based global rate limiting.

Using the builtin Envoy `:path` header proved somewhat difficult because it includes query parameters, so instead of something like `/this` we could end up with `/this?a=b&c=1`.

Because of this, I'm trying to [follow the documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter#config-http-filters-header-to-metadata) to extract the URI from the `:path` header with REGEX (the intention is to remove query parameters and such) and assign the REGEX substitution to a metadata key named `uri`:

```yaml
        name: envoy.filters.http.header_to_metadata
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
          request_rules:
          - header: :path
            on_header_present:
              key: uri
              metadata_namespace: custom_metadata
              regex_value_rewrite:
                pattern:
                  google_re2: {}
                  regex: ^(\/[\/\d\w-]+)\??.*$
                substitution: \1
```

I then try to use that value in the [rate limit actions](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit) to create a descriptor and rate-limit based on the metadata extracted from the headers at a previous step:

```yaml
          rate_limits:
            - actions:
              - generic_key:
                  descriptor_value: generic_descriptor
              - metadata:
                  descriptor_key: PATH
                  metadata_key:
                    key: custom_metadata
                    path:
                    - key: uri
```

This is my rate-limit service config:

```yaml
    domain: foobarlis
    descriptors:
    - key: generic_key
      value: generic_descriptor
      descriptors:
      - key: PATH
        rate_limit:
          requests_per_unit: 5
          unit: minute
        value: /healthz
```

However, this configuration does not work. Traffic sent to this path is never rate-limited.

If I instead replace the `metadata` action with `request_headers`, then the `PATH` descriptor becomes available and rate limiting is successful. This leads me to the conclusion that rate limiting itself works, but somehow I'm either unable to extract the dynamic metadata at all, or I'm able to extract it but not assign it to the rate limit action.

Here's the `request_headers` action that works:

```yaml
          rate_limits:
            - actions:
              - generic_key:
                  descriptor_value: generic_descriptor
              - request_headers:
                  descriptor_key: PATH
                  header_name: :path
```

As I've mentioned however, this is suboptimal because the rate limit service expects an exact match of value, and query parameters are arbitrary.

Is my understanding perhaps misguided that using http-header-to-metadata filter allows you to create dynamic metadata to rate-limit on, or how would it be possible to otherwise troubleshoot this?

Any advice would be appreciated here.

**Comment by MinusRF** [comment]
I too couldn't find anything in docs, one solutions I have is try Lua processing to add one additional header which will only contain URI and based on this you can rate limit. This should be easy to implement, but not sure if it is the best way.

**Comment by pisces-period** [comment]
Hi @MinusRF, sorry for delayed response. I was on PTO holiday. I'm taking a look at both Lua and Envoy documentation to be able to add a Lua snippet in line. I'll attempt it this week and provide an update here.

**Comment by pisces-period** [comment]
I have replaced the `header_to_metadata` filter with this in-line `lua` filter:

```yaml
        name: envoy.lua
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(request_handle)
                local headers = request_handle:headers()
                local path = headers:get(":path")
                local uri = string.gsub(path, "^(/[/%d%w-]+)%??.*$", "%1")
                request_handle:headers():add("uri", uri)
                print(request_handle:headers():get("uri"))
            end
```

To test if the script is working, I increased the log verbosity of my Istio Gateway Pod (to which the Lua filter is to be applied):

```shell
$ istioctl proxy-config log ${ISTIO_INGRESS_POD_IP} --level lua:debug
```

Looking at the logs, I can see that a header was added within the context of the request, performing the substitution to remove the query parameters from the original path:

```shell
/healthz
[2023-04-20T11:44:43.190Z] "HEAD /healthz?a=1&b=3 HTTP/1.1" 200 - via_upstream - "-" 0 0 3 2 ...
2023-04-20T11:44:48.516534Z	debug	envoy lua external/envoy/source/extensions/filters/common/lua/lua.cc:39	coroutine finished	thread=33
```

This is my rate limit actions:

```yaml
rate_limits:
- actions:
   - generic_key:
       descriptor_value: generic_descriptor
   - request_headers:
       descriptor_key: URI
       header_name: uri
```

And my rate limit service configuration:

```yaml
    domain: foobarlis
    descriptors:
    - key: generic_key
      value: generic_descriptor
      descriptors:
      - key: URI
        rate_limit:
          requests_per_unit: 5
          unit: minute
        value: /healthz
```

However, rate limiting still does not work. I can send cURL requests to the Istio Gateway all day and not a single HTTP/429. If I simply replace the `header_name` from `uri` to Envoy builtin `:path` in the rate-limit actions and make requests without query parameters, rate-limiting starts working again.

From this, my understanding is that the rate-limiting configuration in itself is valid, but the header that was added by the Lua filter is somewhat "lost" down the filter chain, or perhaps the order in which I'm inserting/updating filters in the chain is incorrect.

I'm at a loss to be honest.
