### ISSUE TITLE
Some headers are not encoded when using Grpc::AsyncClient

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#26591]
*Title*: Some headers are not encoded when using Grpc::AsyncClient*One line description*

*Description*:
I am trying to write an extension that uses ``Grpc::AsyncClient``, and sends a message to external upstream.
I am observing weird behavior where the logs show that the correct headers have been decoded, but using WireShark, I can see that practically they have empty value.
I understand that it's using a common code from HTTP and there's a low probability that there's an actual bug with the encoding layer, but I don't think WireShark lies either. **Is it possible that I have misconfigured something?**

Grpc::RawAsyncClientSharedPtr is created using the following code:
`server.clusterManager().grpcAsyncClientManager().getOrCreateRawAsyncClient(grpc_service, server.scope(), false)`
where grpc_service points to the cluster below:

request is sent using:
`client_->send(service_method_, *export_request, *this, Tracing::NullSpan::instance(), Http::AsyncClient::RequestOptions());`

```
  - name: open_telemetry_sink
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: open_telemetry_sink
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6060
```

*Logs*:
> router decoding headers:\n':method', 'POST'\n':path', '/opentelemetry.proto.collector.metrics.v1.MetricsService/Export'\n':authority', 'open_telemetry_sink'\n':scheme', 'http'\n'te', 'trailers'\n'content-type', 'application/grpc'\n'x-envoy-internal', 'true'\n'x-forwarded-for', '10.5.0.4'\n"

WireShark snapshot:
```
Frame 50: 348 bytes on wire (2784 bits), 348 bytes captured (2784 bits)
HyperText Transfer Protocol 2
    Stream: HEADERS, Stream ID: 57, Length 53, POST /opentelemetry.proto.collector.metrics.v1.MetricsService/Export
        Length: 53
        Type: HEADERS (1)
        Flags: 0x04, End Headers
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0011 1001 = Stream Identifier: 57
        [Pad Length: 0]
        Header Block Fragment: 8304ac60f596a49682d254d9e97aec3a4eb90f4505224f62f4953618885fb857d054d862…
        [Header Length: 199]
        [Header Count: 8]
        Header: :method: POST
        Header: :path: /opentelemetry.proto.collector.metrics.v1.MetricsService/Export
        Header: <unknown>: 
        Header: :scheme: http
        Header: <unknown>: 
        Header: <unknown>: 
        Header: <unknown>: 
        Header: <unknown>: 
HyperText Transfer Protocol 2
    Stream: DATA, Stream ID: 57, Length 205
        Length: 205
        Type: DATA (0)
        Flags: 0x01, End Stream
        0... .... .... .... .... .... .... .... = Reserved: 0x0
        .000 0000 0000 0000 0000 0000 0011 1001 = Stream Identifier: 57
        [Pad Length: 0]
```
