### ISSUE TITLE
Could someone show me how to use jwt_authn.v3.PerRouteConfig

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#26623]
I used Envoy as the gateway of my backend. Here is a part of my config:
```
static_resources:
  listeners:
  - name: listener_repo_http
    address:
      socket_address: *repo_ingress_http_addr
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          http_filters:
          - name: envoy.filters.http.router
             typed_config:
               "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
               route_config:
                 name: local_route
                 virtual_hosts:
                   - name: local_service
                     domains: ["aaa.example.com:*"]
                     routes:
                       - match: { prefix: "/" }
                         route:
                           cluster: cluster_example
                   - name: local2_service
                     domains: ["bbb.example.com:*"]
                     routes:
                       - match: { prefix: "/abc" }
                         route:
                           cluster: cluster_example_abc
                       - match: { prefix: "/def" }
                         route:
                           cluster: cluster_example_def
```
As you see, there are three route rules with two domain names.

What I'm trying to do is to configure a jwt_authn for only the route `/def`.

It seems that `typed_per_filter_config` is what I need but I don't know how. I just tried as below but it's not working:

```
- match: { prefix: "/def" }
  route:
    cluster: cluster_example_def
  typed_per_filter_config:
    envoy.filters.http.jwt_authn:
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
        requirement_name: ???
```
It seems that I need to define a requirement somehow but I don't know how. Could you please show me an example?

**Comment by mattklein123** [comment]
cc @qiwzhang

**Comment by LironEr** [comment]
I also struggled with this issue,  I think I found the solution

You need to add `envoy.filters.http.jwt_authn` to HTTP filters with `requirement_map`
Full example of my listener file:

```yaml
resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8443
    filter_chains:
      - transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              alpn_protocols: ['h2,http/1.1']
              tls_certificates:
                - certificate_chain:
                    filename: /var/lib/envoy/certs/cert.pem
                  private_key:
                    filename: /var/lib/envoy/certs/key.pem
        filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              upgrade_configs:
                - upgrade_type: websocket
              codec_type: AUTO
              server_header_transformation: PASS_THROUGH
              http_filters:
                - name: envoy.filters.http.jwt_authn
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                    providers:
                      default_provider:
                        payload_in_metadata: 'payload'
                        issuer: https://cognito-idp.us-west-2.amazonaws.com/xxxxxxxxxxxxxxx
                        remote_jwks:
                          http_uri:
                            uri: https://cognito-idp.us-west-2.amazonaws.com/xxxxxxxxxxxxxxx/.well-known/jwks.json
                            cluster: cognito_jwks
                            timeout: 1s
                          # jwks cache
                          cache_duration:
                            seconds: 900
                          # fetch jwks on proxy startup
                          async_fetch:
                            fast_listener: false
                        from_cookies:
                          - CognitoIdentityServiceProvider.1hc7mdccn3ri95k4200k21gv2j.e7aa664a-36bf-49fb-bec0-beb486559b35.accessToken
                    requirement_map:
                      default_req:
                        provider_name: default_provider
                - name: 'envoy.filters.http.cache'
                  typed_config:
                    '@type': 'type.googleapis.com/envoy.extensions.filters.http.cache.v3.CacheConfig'
                    typed_config:
                      '@type': 'type.googleapis.com/envoy.extensions.http.cache.simple_http_cache.v3.SimpleHttpCacheConfig'
                # must be last
                - name: envoy.filters.http.router
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                  - name: cluster
                    domains:
                      - 'mydomain.com'
                    routes:
                      - match:
                          prefix: '/'
                        route:
                          cluster: some_service
                    typed_per_filter_config:
                      envoy.filters.http.jwt_authn:
                        '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
                        requirement_name: 'default_req'
```

Also, I think you can see the documentation for each requirement [here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtrequirement)
