### ISSUE TITLE
Original source listener filter not working when envoy and upstream not on same host

### ISSUE THREAD

**Issue by kzorfy** [envoyproxy/envoy#26685]
I have envoy running on an AWS EC2 instance inside a VPC as a TCP proxy routing traffic to different upstreams. Each upstream is an ALB (Application Load Balancer) running in its individual VPC and load balances traffic from envoy to its targets. 

The EC2 instance where envoy is running is on a public subnet routing traffic to upstream(ALB) through AWS Internet Gateway. The downstream for envoy are a pool of EC2 instances situated in the same VPC where envoy is running. The downstream EC2 instances do not have public IP addresses and connect to envoy using private IP. 

My use case is to preserve client IP address (private IP address) to the upstream servers (ALB) when envoy establishes TCP connection to the upstream and have the upstream forward the response back to envoy which inturn will forward the response back to the downstream instances. I am using original source listener filter to preserve the client IP but TCP connections from envoy to upstream is failing with response status `UF, URX`. I disabled source/destination check on the EC2 instance where envoy is running but its not helping.

Envoy public doc has below information when upstream is not on the same host as envoy.

```
By default, packets returning from the upstream host to that address will not route through Envoy. The network must be configured to forcefully route any traffic whose IP was replicated by Envoy back through the Envoy host.
```

ref: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/original_src_filter

I do not see any details on how to configure the network for preserving client IP address when both envoy and upstream are not on same host. Any help on how to get the client IP preservation working for my use case is appreciated.

Sharing the envoy configuration below

```
static_resources:
  listeners:
    - name: listener_443
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 443
      listener_filters:
        - name: envoy.filters.listener.proxy_protocol
          typed_config:
            '@type':
              type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
        - name: envoy.filters.listener.original_src
          typed_config:
            '@type':
              type.googleapis.com/envoy.extensions.filters.listener.original_src.v3.OriginalSrc
              mark: 123
      filter_chains:
        - filters:
            - name: envoy.filters.network.sni_dynamic_forward_proxy
              typed_config:
                '@type':
                  type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
                port_value: 443
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
                  dns_query_timeout: 5s
            - name: envoy.tcp_proxy
              typed_config:
                '@type':
                  type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      '@type':
                        type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                      log_format:
                        json_format:
                          ConnectionId: '%CONNECTION_ID%'
                          StartTime: '%START_TIME%'
                          DownstreamRemoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
                          UpstreamRemoteAddress: '%UPSTREAM_REMOTE_ADDRESS%'
                          UpstreamConnectionAttemptCount: '%UPSTREAM_REQUEST_ATTEMPT_COUNT%'
                          ConnectionTerminationDetails: '%CONNECTION_TERMINATION_DETAILS%'
                          ResponseFlags: '%RESPONSE_FLAGS%'
                cluster: dynamic_forward_proxy_cluster
                idle_timeout: 320s
                max_connect_attempts: 2
  clusters:
    - name: dynamic_forward_proxy_cluster
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          '@type':
            type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
            dns_query_timeout: 5s
      connect_timeout: 5s
```
