### ISSUE TITLE
gRPC-JSON transcoder ignoring CORS

### ISSUE THREAD

**Issue by RickCurrey** [envoyproxy/envoy#26684]
I am currently having an issue with the transcoder ignoring the preflight CORS and returning a 405 when OPTIONS is being sent.

Here is my current config:
```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: grpc-listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: grpc_json
                codec_type: AUTO
                access_log:
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      typed_per_filter_config:
                        envoy.filters.http.cors:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                          allow_origin_string_match:
                          - safe_regex:
                              regex: \*
                          allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
                      routes:
                        - match: { prefix: "/"}
                          route: { cluster: Greeter, timeout: { seconds: 60 } }
                        - match: { prefix: "/", grpc: {} }
                          route: { cluster: Illustration, timeout: { seconds: 60 } }
                        - match: { prefix: "/", grpc: {} }
                          route: { cluster: Products, timeout: { seconds: 60 } }
                        - match: { prefix: "/", grpc: {} }
                          route: { cluster: Validate, timeout: { seconds: 60 } }
                http_filters:
                - name: envoy.filters.http.cors
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/greet.pb"
                    services: ["greet.v1.Greeter"]
                    match_incoming_request_route: false
                    ignore_unknown_query_parameters: true
                    auto_mapping: false
                    convert_grpc_status: true
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: true
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/illustration.pb"
                    services: ["illustration.v1.Illustration"]
                    match_incoming_request_route: false
                    ignore_unknown_query_parameters: true
                    auto_mapping: false
                    convert_grpc_status: true
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: true
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/products.pb"
                    services: ["products.v1.Products"]
                    match_incoming_request_route: false
                    ignore_unknown_query_parameters: true
                    auto_mapping: false
                    convert_grpc_status: true
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: true
                - name: envoy.filters.http.grpc_json_transcoder
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                    proto_descriptor: "/validate.pb"
                    services: ["validate.v1.Validate"]
                    match_incoming_request_route: false
                    ignore_unknown_query_parameters: true
                    auto_mapping: false
                    convert_grpc_status: true
                    print_options:
                      add_whitespace: true
                      always_print_primitive_fields: true
                      always_print_enums_as_ints: false
                      preserve_proto_field_names: true
                - name: envoy.filters.http.router
                  typed_config: 
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: Greeter
      connect_timeout: 1.25s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: Greeter
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 5202
    - name: Illustration
      connect_timeout: 1.25s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: Illustration
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 5184
    - name: Products
      connect_timeout: 1.25s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: Products
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 5202
    - name: Validate
      connect_timeout: 1.25s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: Validate
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 5202
```
