### ISSUE TITLE
how envoy close the connection actively  when upstream clusters changed？

### ISSUE THREAD

**Issue by mloves0824** [envoyproxy/envoy#26719]
I would like to ask a question. 
Envoy uses TcpProxy to proxy redis. The upstream redis cluster changes, and the control plane sends changes. Envoy updates the upstream cluster. 
The new connection of the redis client can point to the new cluster, but the existing long connection always exists. 
Does envoy have it? How to transfer the old connection to the new cluster or disconnect the old connection?

The configuration file is as follows：
### envoy.yaml
```
node:
  id: id_1
  cluster: test

dynamic_resources:
  cds_config:
    path_config_source:
      path: examples/dynamic-config-fs/tcp-proxy-configs/cds.yaml
  lds_config:
    path_config_source:
      path: examples/dynamic-config-fs/tcp-proxy-configs/lds.yaml

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
```

### lds.yaml
```
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_2222
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 2222
  filter_chains:
    - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: destination
            cluster: cluster_2222
            access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
```

### cds.yaml
```
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: cluster_2222
  connect_timeout: 30s
  type: LOGICAL_DNS
  dns_lookup_family: V4_ONLY
  load_assignment:
    cluster_name: cluster_2222
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 7777
```

The startup command is as follows：
`./linux/amd64/build_envoy_debug/envoy -c examples/dynamic-config-fs/envoy.yaml --concurrency 1 --log-level trace
`

Start the redis server:
```
redis-server --port 7777   #redis1
redis-server --port 8888   #redis2
```

Start the redis client:
`redis-cli -p 2222
`

As you can see, envoy establishes a connection with redis1.
At this time, change the port_value in cds.yaml from 7777 to 8888.
When creating a new connection to envoy, envoy establishes a connection with redis2, but the connection with redis1 will always exist.
I want to disconnect the connection between envoy and redis1 now, is there any way?

Looking forward to your answer.
Thanks.
