### ISSUE TITLE
DNS address not validated

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [envoyproxy/envoy#26720]
*Title*: DNS addresses are not validated

*Description*:
When setting `address` in `clusters` config, the value only gets evaluated if `type` is set to use IPs.
DNS strings are not evaluated.
Thus it is possible to enter utter garbage and for envoy to start up without complaining.

Example:
```yaml
 clusters:
  - name: payments
    type: STRICT_DNS
    load_assignment:
      cluster_name: load
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: http://thisismytotallygreatserver.com/create/you
```
