### ISSUE TITLE
use DOWNSTREAM_REMOTE_PORT as port value in sni_dynamic_forward_proxy filter

### ISSUE THREAD

**Issue by levimm** [envoyproxy/envoy#26800]
*Title*: *is it possible to use %DOWNSTREAM_REMOTE_PORT% as port value in sni_dynamic_forward_proxy filter*

*Description*:
In L4 sni based dynamic forward proxy, we don't want to use fixed 443 as port value. Wondering is it possible to use the downstream port here? Trying with `%DOWNSTREAM_REMOTE_PORT%` but clearly it's not correct type with error `invalid value "%DOWNSTREAM_REMOTE_PORT%" for type TYPE_UINT32` 

```
    filter_chains:
    - filters:
      - name: envoy.filters.network.sni_dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
          port_value: 443 #  -> %DOWNSTREAM_REMOTE_PORT%
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
```
