### ISSUE TITLE
connection_pool_per_downstream_connection==true cluster setting doesn't take effect if cluster is set up as a mirror

### ISSUE THREAD

**Issue by igor-anferov** [envoyproxy/envoy#26820]
*Title*: *connection_pool_per_downstream_connection==true cluster setting doesn't take effect if cluster is set up as a mirror*

*Description*:
[connection_pool_per_downstream_connection](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-connection-pool-per-downstream-connection) cluster setting was designed to, when set to `True`, prevent requests from different downstream connections from being aggregated inside single upstream connection. That works perfectly when cluster configured this way is used in [route](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-route) directive. But when such cluster is used in [request_mirror_policies](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-request-mirror-policies), connections to send requests to upstreams are being taken from single connection pool, despite the fact they came from different downstream connections. This behaviour is inconsistent and unexpected.

*Config*:
```yaml
static_resources:
  listeners:
  - filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          route_config:
            virtual_hosts:
            - routes:
              - match:
                  prefix: "/"
                route:
                  cluster: main  # <— OK: requests from different downstream connections being sent through different upstream connections
                  request_mirror_policies:
                  - cluster: mirror  # <— ERROR: requests from different downstream connections being aggregated inside single upstream connection

  clusters:
  - name: main
    connection_pool_per_downstream_connection: true
  - name: mirror
    connection_pool_per_downstream_connection: true
```
