### ISSUE TITLE
`google_re2` for type `type.matcher.v3.RegexMatcher` is marked as required in doc and isn't since 1.23

### ISSUE THREAD

**Issue by davinkevin** [envoyproxy/envoy#26875]
*Description*:
I've upgraded envoy and had this in my config:

```
                    - name: podcast
                      domains: ["foo.bar.com"]
                      routes:
                        - match:
                            safe_regex:
                              google_re2: {}
                              regex: "^/api/.*$"
                            headers:
                              - name: ":method"
                                string_match:
                                  exact: "GET"
```

After restart, I had this message in the app:

```
[2023-04-22 09:35:46.284][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.type.matcher.v3.RegexMatcher Using deprecated option 'envoy.type.matcher.v3.RegexMatcher.google_re2' from file regex.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
```

If I follow the [documentation for this type](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/regex.proto), the field `google_re2` is still mandatory

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1970922/233776821-02d4dc97-d359-4ea4-b5f1-8a8063981967.png">

So, I was in a situation between configuration saying to remove this field and the doc making it mandatory. I've removed it and tried and the app started without problem, so I think the doc has to be updated to reflect this. 

I haven't find the doc location to propose a PR on this, so I've chosen to open an issue to keep track of this, in case some others face the same issue.
