### ISSUE TITLE
how to generate a json format log from envoy? like nginx (escape=json)

### ISSUE THREAD

**Issue by danlanxiaohei** [envoyproxy/envoy#2692]
i want to get a json format log like nginx(escape=json),any plan to support it?

**Comment by mattklein123** [comment]
@danlanxiaohei what is this referring to? The HTTP access log? Envoy's application log?

**Comment by ggreenway** [comment]
I looked up the nginx documentation. It looks like the setting causes emitted values to be json escaped. And the structure of the json is from the format string in the config.

**Comment by ggreenway** [comment]
I'm the access logs

**Comment by danlanxiaohei** [comment]
@mattklein123 @ggreenway Thanks for your reply.

**Comment by htuch** [comment]
If you take the existing path for proto logging and do a proto3->JSON conversion at the end of it, you have JSON logging effectively. I don't think we do proto logging to files today. What I would suggest is to build the proto3 logging and you basically have the JSON equivalent. We could re-use large  parts of the existing gRPC acccess log sink to do this.

**Comment by drichelson** [comment]
Would the proposed solution also cover Envoy's application logs?

**Comment by htuch** [comment]
@drichelson No, Envoy's debug logs use a different mechanism; these are likely to be plain text for the foreseeable future. However, they are implemented via macros in such a way (see https://github.com/envoyproxy/envoy/blob/master/source/common/common/logger.h#L282) that it would be possible to add alternative implementations, which might be able to emit JSON. What you might really want though is to have `spdlog` introduce a JSON mode.

**Comment by aa-stripe** [comment]
Hi @htuch, thanks for your comment! I was wondering if you could clarify what exactly you are referring to with the proto3 logging, and where in the source I might be able to find that and insert the 'convert to json' code. 

Additionally, what are your thoughts about an approach where we basically write a version of https://github.com/envoyproxy/envoy/blob/master/source/common/access_log/access_log_formatter.cc that outputs logs in JSON instead of plaintext? Is the proto3 method preferred over something like this or would that suffice as well?

**Comment by htuch** [comment]
@aa-stripe you can definitely write an access log formatter that emits JSON. The existing proto logging is in https://github.com/envoyproxy/envoy/blob/master/source/extensions/access_loggers/http_grpc/grpc_access_log_impl.cc. This is actually coupled with gRPC output, so you might want to just take this as inspiration.

**Comment by aa-stripe** [comment]
Awesome, thanks for clarifying! The proto angle makes more sense now. I'll look at a JSON access log formatter in the spirit of `access_log_formatter.cc`

**Comment by aa-stripe** [comment]
Hi @htuch and others, just wanted to outline my basic approach to JSON logging here, and get any thoughts or comments from folks. I propose the following:

1. Currently, in [`config.accesslog.v2.FileAccessLog`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/accesslog/v2/file.proto#envoy-api-msg-config-accesslog-v2-fileaccesslog), we allow you to specify a `format` key, in which you can specify a plaintext log format using specifiers like `%PROTOCOL%` and `%START_TIME%`
2. I propose adding an alternative key called `json_format`. You will only be allowed to specify one of `format` or `json_format`. Not both. This is implemented in protobuf as a `OneOf` field.
3. The `json_format` key contains a mapping of keys in the output JSON to specifiers. This is done because the format specfiers themselves can sometimes be complex. Thus we allow users to give a more human friendly name. Side note: this was not necessary in the past, since we never actually logged the “names” of fields - just the fields themselves.
4. For example, you might specify a `json_format` like:
`{"protocol": "%PROTOCOL%", "duration": "%DURATION%", "request_method": "%REQ(:METHOD)%"}`.
5. This would result in the access log outputting a JSON dictionary as follows:
`{"protocol": "HTTP/1.1", "duration": "226", "request_method": "POST"}`

I’m happy to answer any questions or make adjustments to this approach if folks have feedback! If we agree on an approach, I will move forward with a code review! Also happy to share implementation details if folks are interested at this point.

**Comment by ggreenway** [comment]
Another idea to think about. (I'm not claiming it's necessarily better, just different).

Add a config for escape-type, default value of None. If you set it to Json, then all replacement strings get json-escaping applied. The structure of the json is written in the existing format string. This would have the downside of having to explicitly format the json in the config, but the upside of more control over the exact output (for example, the whitespace in the json for single-line vs pretty-printed).

**Comment by mattklein123** [comment]
> Add a config for escape-type, default value of None. If you set it to Json, then all replacement strings get json-escaping applied. The structure of the json is written in the existing format string. This would have the downside of having to explicitly format the json in the config, but the upside of more control over the exact output (for example, the whitespace in the json for single-line vs pretty-printed).

This is actually the solution I was envisioning, so +1 from me.

**Comment by aa-stripe** [comment]
Thanks for your comment @ggreenway @mattklein123. I did consider this approach, but went against it for two reasons:

1. I imagine the primary use case for this being parsing the logs into some further downstream service (like Splunk) for aggregation and searching. In that case the specific formatting wouldn't matter, rather it would matter that the JSON is well formatted. If you are manually parsing the logs, you can feed it into your favorite `jq` or `python -m json.tool`
2. Having users manually specify the format is error-prone, and could result in JSON syntax errors. While we could attempt a parse when starting and throw an exception immediately to alert them, it could still be tedious to find the exact source of the syntax error. Because we serialize with `rapidjson`, we guarantee that the output JSON will be well formatted.

I do agree with you that a case could be made for a more detailed JSON structure. Maybe with further nested fields like 
```
{
    "request": {
        "headers": {
            "header1": "%REQ(header1)%",
            "header2": "%REQ(header2)%"
        }
    }
    "response": {
        "headers": { ... }
    }
}
```
If there is a need for this kind of thing in the future, it should be fairly straightforward to add, now that the plumbing is laid out. However I do believe keeping the current scope contained to a single level dictionary is a tractable place to start.

**Comment by mattklein123** [comment]
OK, that's a fair point. Can you potentially propose the config changes so that we can review/discuss?

**Comment by aa-stripe** [comment]
Sure! I'm happy to do that. I am working on getting a full example config set up, but the relevant section would look like this:

```
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              config:
                json_format:
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  request_method: "%REQ(:METHOD)%"
                path: "/tmp/access.log"
```

For this example I borrowed this snippet from another github issue (3185) where someone posted a simple config. I will follow up with a more fleshed out config when I have it ready, but hopefully this is a good start for discussion.

**Comment by mattklein123** [comment]
Sorry I meant the actual API config changes in the protos.

**Comment by aa-stripe** [comment]
Ah gotcha. That looks like this:

```diff
+message FileAccessLogJsonFormat {
+  map<string, string> mapping = 1;
+}
+
 // Custom configuration for an :ref:`AccessLog <envoy_api_msg_config.filter.accesslog.v2.AccessLog>`
 // that writes log entries directly to a file. Configures the built-in *envoy.file_access_log*
 // AccessLog.
@@ -17,5 +21,8 @@ message FileAccessLog {
   // Access log format. Envoy supports :ref:`custom access log formats
   // <config_access_log_format>` as well as a :ref:`default format
   // <config_access_log_default_format>`.
-  string format = 2;
+  oneof access_log_format {
+    string format = 2;
+    FileAccessLogJsonFormat json_format = 3;
+  }
 }
```

**Comment by aa-stripe** [comment]
(It has to be a separate message type because you can't have a `map` directly in a `oneof`)

**Comment by htuch** [comment]
@aa-stripe will you ever need nesting, or is flat likely be sufficient for all use cases?

**Comment by aa-stripe** [comment]
@htuch I think for now, a flat format is sufficient. I think we can wait until there's a clear need for a more nested format. If that need arises in the future, the code is compartmentalized enough such that this will be a small, contained change. I am happy to advise and/or be a part of that in the future.

**Comment by aa-stripe** [comment]
Such a change in the future would also be backwards compatible, since a flat dict is just a subset of a more nested dict.

**Comment by htuch** [comment]
@aa-stripe yep, it would be log compatible for sure. I think you would want to evolve `FileAccessLogJsonFormat` to be a `google.protobuf.Struct` rather than a simple map. You could even do that today and just say "only flat formats are supported for now", rejecting anything nested at config ingestion time.

**Comment by mattklein123** [comment]
> @aa-stripe yep, it would be log compatible for sure. I think you would want to evolve FileAccessLogJsonFormat to be a google.protobuf.Struct rather than a simple map. You could even do that today and just say "only flat formats are supported for now", rejecting anything nested at config ingestion time.

+1. Let's future proof for nesting in the config even if we reject nesting right now during config load.

**Comment by aa-stripe** [comment]
I agree with this. I can change it to be a struct, and then validate at load time that it is a map of strings to strings, and throw an exception if otherwise.

**Comment by aa-stripe** [comment]
I've got a working example of a config and some output that results from this change. I just used the 'proxy localhost:10000 to google.com' example from the envoy docs:

Config:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
            name: envoy.file_access_log
            config:
              path: /tmp/envoy.log
              json_format:
                mapping:
                  protocol: "%PROTOCOL%"
                  duration: "%DURATION%"
                  cluster: "%UPSTREAM_CLUSTER%"
                  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite: www.google.com, cluster: service_google }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }
```

Output in `/tmp/envoy.log`:
```
{"cluster":"service_google","duration":"55","path":"/gen_204?atyp=csi&ei=eva3W6fKKov00wL6n6vADg&s=jsa&jsi=s,t.0,et.focus,n.iDPoPb,cn.1&zx=1538782866576","protocol":"HTTP/1.1"}
{"cluster":"service_google","duration":"24","path":"/gen_204?atyp=csi&ei=eva3W6fKKov00wL6n6vADg&s=jsa&jsi=s,et.focus,n.iDPoPb,cn.2&zx=1538782867475","protocol":"HTTP/1.1"}
```
This is pretty much what we have discussed so far, except there's the small annoyance of that `mapping` key under `json_format`, because of the `FileAccessLogJsonFormat`. I'm hoping this changes when we move to using a struct, but I haven't actually tried that yet. If anyone has thoughts or expertise here, I'm happy to hear it. Ideally it would look like:
```
json_format:
  protocol: "%PROTOCOL%"
  duration: "%DURATION%"
  cluster: "%UPSTREAM_CLUSTER%"
  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
```

Barring the change to a proto struct vs. message, do folks agree on this approach? If so I will go ahead and get the code ready for a review.
