### ISSUE TITLE
enabling access logs (newbie submitter)

### ISSUE THREAD

**Issue by mslearner** [envoyproxy/envoy#26995]
Hi. I am a newbie here. I am trying to enable access logs in envoy. I am not using istio but loading envoy in kubernetes in a pod. This is my envoy.yaml. I have tried getting the access log in local file (/var/log/envoy/access.log) and in stdout but I do not see any logs. The file does get created. When I turn on the debug logs, I do see debug logs flowing. Here is the yaml. I even turned off (commented TLS) to get the access log but it is not coming through. I am sure I am doing something obvious wrong. I am sending RPC traffic through envoy and it is configured as a side car right before upstream service.  Also, I have not enabled admin here since I did not need it. Do I need admin for access logs? Thank you so much for all the guidance.

Here is my envoy.yaml
`node:
    id: test
    cluster: test
static_resources:
  listeners:
  - name: mainapp_sidecar_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 5199
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": [type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager](http://type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager)
          stat_prefix: mainapp_sidecar_hcm_filter
          access_log:
          - name: envoy.file_access_log
            typed_config:
              "@type": [type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog](http://type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog)
              path: /var/log/envoy/access.log
              format: "[%START_TIME%] \"%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%\" %RESPONSE_CODE% %RESPONSE_FLAGS% \n"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router](http://type.googleapis.com/envoy.extensions.filters.http.router.v3.Router)
          route_config:
            name: mainapp_sidecar_http_route_config
            virtual_hosts:
            // name used when emitting stats, not imp for routing itself
            - name: mainapp_sidecar_virtual_host
              domains:
              - "*"
              routes:
              - name:
                match:
                  prefix: "/"
                route:
                  cluster: mainapp_service
  clusters:
  - name: mainapp_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: mainapp_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # reroute to service container in the same K8s deployment
                address: 127.0.0.1
                port_value: 8090
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: spire_agent
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                pipe:
                  path: /run/spire/sockets/agent.sock

**Comment by adisuissa** [comment]
The new naming scheme should probably be used:
`envoy.file_access_log`  ->  `envoy.access_loggers.file`

Are there any errors when Envoy is initializing?
If the format is removed and the default one is used, are there any log entries?

**Comment by mslearner** [comment]
Thanks for your response.  I changed the yaml to below. There are no errors at envoy bootup. I get all the access logs if I disable the TLS transport socket. I do not get any access log as soon as I enable it. I also upgraded my envoy version to 1.27 ( 2418a2d9b0280dbaa1979309a8e744565d62b950/1.27.0-dev/Clean/RELEASE/BoringSSL). Is there anything else that I should try?


`node:
    id: test
    cluster: test
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
 # ingress
  - name: mainapp_sidecar_listener
    address:
      socket_address:
        # Entrypoint for service through Envoy
        address: 0.0.0.0
        port_value: 5199
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          # used when emitting stats
          stat_prefix: upstream
          access_log:
          - name: envoy.file_access_log.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format: 
                json_format: 
                  status: "%RESPONSE_CODE%"
                  message: "%LOCAL_REPLY_BODY%"
                  timestamp: "%START_TIME%"
                  protocol: "%PROTOCOL%"
                  method: "%REQ(:METHOD)%"
                  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                  status_code: "%RESPONSE_CODE%"
                  response_flags: "%RESPONSE_FLAGS%"
                  bytes_received: "%BYTES_RECEIVED%"
                  bytes_sent: "%BYTES_SENT%"
                  duration: "%DURATION%"
                  upstream_host: "%UPSTREAM_HOST%"
                  upstream_cluster: "%UPSTREAM_CLUSTER%"
                  upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
                  downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                  upstream_tls_version: "%UPSTREAM_TLS_VERSION%"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router 
          route_config:
            name: mainapp_sidecar_http_route_config
            virtual_hosts:
            # name used when emitting stats, not imp for routing itself
            - name: mainapp_sidecar_virtual_host
              domains: 
              - "*"
              routes:
              - name:
                match:
                  prefix: "/"
                route:
                  cluster: mainapp_service
          #   - name: envoy.file_access_log
          #     typed_config: 
          #       "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          #       path: /var/log/envoy/access.json
          #       log_format:
          #         json_format:
          #           status: "%RESPONSE_CODE%"
          #           message: "%LOCAL_REPLY_BODY%" 
          # # - name: envoy.file_access_log.stdout
          # #   typed_config:
          # #     "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          # #     log_format: 
          # #       json_format: 
          # #         status: "%RESPONSE_CODE%"
          # #         message: "%LOCAL_REPLY_BODY%"
                     
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: "spiffe://example.org/server"
              sds_config:
               resource_api_version: V3
               api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
            combined_validation_context:
              default_validation_context:
                match_subject_alt_names:
                  exact: spiffe://example.org/client1
              validation_context_sds_secret_config:
               name: "spiffe://example.org"
               sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
  clusters:
  - name: mainapp_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: mainapp_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # reroute to service container in the same K8s deployment
                address: 0.0.0.0
                port_value: 8090
  - name: spire_agent
    connect_timeout: 0.25s
    http2_protocol_options: {}
    load_assignment:
      cluster_name: spire_agent
      endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                pipe:
                  path: /run/spire/sockets/agent.sock        
  # - name: spire_agent
  #   connect_timeout: 0.25s
  #   load_assignment:
  #     cluster_name: local_service_tls
  #   transport_socket:
  #     name: envoy.transport_sockets.tls
  #     typed_config:
  #       "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
  #       common_tls_context:
  #         tls_certificate_sds_secret_configs:
  #         - name: client_cert
  #           sds_config:
  #             resource_api_version: V3
  #             api_config_source:
  #               api_type: GRPC
  #               transport_api_version: V3
  #               grpc_services:
  #                 google_grpc:
  #                   target_uri: unix:/run/spire/sockets/agent.sock
  #                   stat_prefix: pong-server-spire
`

**Comment by adisuissa** [comment]
> I get all the access logs if I disable the TLS transport socket (see YAML below).

Do you mean that you receive the access-logs if you disable the Downstream-TLS-Socket or the Upstream-TLS-Socket?
and just to make sure, when TLS is enabled and there are no logs, the traffic still passes through the proxy, right?

**Comment by mslearner** [comment]
Correct, the traffic passes through the proxy with and without TLS Socket. The logs work when I disable the following 
```yml
  transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: "spiffe://example.org/server"
              sds_config:
               resource_api_version: V3
               api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
            combined_validation_context:
              default_validation_context:
                match_subject_alt_names:
                  exact: spiffe://example.org/client1
              validation_context_sds_secret_config:
               name: "spiffe://example.org"
               sds_config:
                resource_api_version: V3
                api_config_source:
                  api_type: GRPC
                  transport_api_version: V3
                  grpc_services:
                    envoy_grpc:
                      cluster_name: spire_agent
```
