### ISSUE TITLE
Envoy returns 403 Forbidden error when requesting with websockets from client

### ISSUE THREAD

**Issue by kicks321** [envoyproxy/envoy#27056]
*Title*: *Envoy returns 403 Forbidden error when requesting with websockets from client*

*Description*:
Whenever we connect to our API server via **websockets**, Node.js v18+, running in Docker,  we get 403 errors coming from Envoy.  When we connect directly via websockets to our docker containers by static IP like so: "ws://10.10.2.10/graphql" & "wss://10.10.2.10/graphql" it works just fine, we get proper responses.

Our configuration works properly for Http 1.1 -> Http2 so all our regular HTTP requests work just fine.  Connecting from a client  over Http 1.1 -> Envoy (which is suppose to allow Http 2 hops to Http 1.1 API as shown here: [Websocket over HTTP/2 or HTTP/3 hops](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#websocket-over-http-2-or-http-3-hops) we then receive the 403 errors.

We have enabled the upgrade_configs to upgrade to websockets.  We have also tried the "allow_connect: true" option in the level 2 http2 configuration option which still didn't resolve the issue.

We have also tried the wss -> wss connections, by setting the TLS configuration for the cluster explicitly as well.

*Versions*:
**Docker Version**: 20.10.22
**Envoy Version (Image)**: envoyproxy/envoy:v1.26-latest

*Config*:
Docker containers are running with mapped ports:
```sh
-p 80:10000 -p 443:10001
```

```yaml
static_resources:
    listeners:
        - name: listener_0
          address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 10000
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          stat_prefix: ingress_http
                          upgrade_configs:
                              - upgrade_type: websocket
                          access_log:
                              - name: envoy.access_loggers.stdout
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                          http_filters:
                              - name: envoy.filters.http.router
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                          route_config:
                              name: local_route
                              virtual_hosts:
                                  - name: local_service
                                    domains: ["*"]
                                    routes:
                                        - match:
                                              prefix: "/graphql"
                                          route:
                                              cluster: api
                                        - match:
                                              prefix: "/"
                                          route:
                                              cluster: website

        - name: listener_1
          address:
              socket_address:
                  address: 0.0.0.0
                  port_value: 10001
          filter_chains:
              - filters:
                    - name: envoy.filters.network.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                          stat_prefix: ingress_http
                          upgrade_configs:
                              - upgrade_type: websocket
                          access_log:
                              - name: envoy.access_loggers.stdout
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                          http_filters:
                              - name: envoy.filters.http.router
                                typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                          route_config:
                              name: local_route
                              virtual_hosts:
                                  - name: local_service
                                    domains: ["*"]
                                    routes:
                                        - match:
                                              prefix: "/graphql"
                                          route:
                                              cluster: secure_api
                                        - match:
                                              prefix: "/"
                                          route:
                                              cluster: website
                transport_socket:
                    name: envoy.transport_sockets.tls
                    typed_config:
                        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                        common_tls_context:
                            tls_certificates:
                                certificate_chain:
                                    { filename: "etc/envoy/certs/cert.pem" }
                                private_key:
                                    { filename: "etc/envoy/certs/key.pem" }

        - name: website
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: website
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.10.2.11
                                      port_value: 80
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.10.2.10
                                      port_value: 80

        - name: secure_api
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: secure_api
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.10.2.11
                                      port_value: 8081
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.10.2.10
                                      port_value: 8081

        - name: api
          type: STATIC
          lb_policy: ROUND_ROBIN
          load_assignment:
              cluster_name: api
              endpoints:
                  - lb_endpoints:
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.42.1.20
                                      port_value: 8080
                        - endpoint:
                              address:
                                  socket_address:
                                      address: 10.42.1.21
                                      port_value: 8080

```

*Logs*:
The only logs we are receiving from Envoy are 403's as shown below.  We thought it was coming from our Node.js server, but I can confirm we are not even receiving the request.  Our logging service in Node.js shows no requests.

`
[2023-04-28T18:17:53.576Z] "GET /graphql HTTP/1.1" 403 - 0 0 0 - "-" "-" "802fc627-ca09-4f9d-b4f1-69b0e845af84" "dev.sample.com" "-"
`

**Comment by yanavlasov** [comment]
Can you modify the access log format string to include the `%RESPONSE_CODE_DETAILS%` value, please? It could explain better where Envoy fails the request.

Your configuration seems correct. You can also enable detailed debug logs with the `-l trace` option to help diagnose the problem.

**Comment by kicks321** [comment]
> Can you modify the access log format string to include the `%RESPONSE_CODE_DETAILS%` value, please? It could explain better where Envoy fails the request.
> 
> Your configuration seems correct. You can also enable detailed debug logs with the `-l trace` option to help diagnose the problem.

We have a demo on that site today, but I will get back with you first thing tomorrow on 5/2/2023 ASAP.  Thank you for the quick response.

**Comment by kicks321** [comment]
> 

I've tried about 15 variations of configuring the access_log files to output in JSON_FORMAT, and something else is odd.  I can't even log the access_logs to another file per your recommendations.

None of these are actually creating log files within our Docker containers, nor are they creating log files when mapped mounted.  I run our envoy containers like so, (I tired to run as root as well):

 docker run -d --name envoy --network public -v $(pwd)/logs:/var/log -p 80:10000 -p 443:10001 **-e ENVOY_UID=0** example.com:8080/development/envoy:latest

Here are a few variations:
```yaml
access_log:
    - name: envoy.file_access_log
      config:
          path: "/tmp/envoy_access.log"
```

```yaml
access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
          "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          path: "/var/logs/envoy_access.log"
          typed_json_format:
              details: "%RESPONSE_CODE_DETAILS%"
```

```yaml
access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
          "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          path: "/var/logs/envoy_access.log"
          json_format:
              details: "%RESPONSE_CODE_DETAILS%"
```

```yaml
access_log:
        - name: envoy.access_loggers.stdout
          typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/dev/stdout"
              typed_json_format:
                  details: "%RESPONSE_CODE_DETAILS%"
```
