### ISSUE TITLE
Enhance RBAC matching flexibility with ListStringMatcher support in MetadataMatcher

### ISSUE THREAD

**Issue by mpromet-meli** [envoyproxy/envoy#27065]
# Title: Add support for xds.type.matcher.v3.ListStringMatcher in RBAC Principal MetadataMatcher

### Current Behavior
Currently, if I want to match against multiple values for a single field in RBAC Principal MetadataMatcher, I would have to create separate entries for each value. For example, if I want to match against three different application names in `my_key` claim of a JWT token I should end up using the `or_ids` syntax, configuration would look something like this:

```yaml
policies:
  - name: allow-multiple-apps
    policy:
      permissions:
        - any: true
      principals:
        - or_ids:
            ids:
              - metadata:
                  filter: envoy.filters.http.jwt_authn
                  path:
                    - key: my_payload
                    - key: my_key
                  value:
                    string_match:
                      exact: app1
              - metadata:
                  filter: envoy.filters.http.jwt_authn
                  path:
                    - key: my_payload
                    - key: my_key
                  value:
                    string_match:
                      exact: app2
              - metadata:
                  filter: envoy.filters.http.jwt_authn
                  path:
                    - key: my_payload
                    - key: my_key
                  value:
                    string_match:
                      exact: app3
```

This can be very verbose and cumbersome for matching against a large number of values.

### Proposed Behavior
I would like to request support for `xds.type.matcher.v3.ListStringMatcher` to be added to `type.matcher.v3.ValueMatcher` used in `type.matcher.v3.MetadataMatcher` for RBAC Principal in EnvoyProxy. Currently, only `xds.type.matcher.v3.StringMatcher` is supported for `type.matcher.v3.ValueMatcher`, which limits the ability to match against multiple values for a single field.

With support for xds.type.matcher.v3.ListStringMatcher, I could achieve the same result with a much simpler configuration, like this:

```yaml
policies:
  - name: allow-multiple-apps
    policy:
      permissions:
        - any: true
      principals:
        - metadata:
            filter: envoy.filters.http.jwt_authn
            path:
              - key: my_payload
              - key: my_key
            value:
              patterns:
                - string_match:
                    exact: app1
                - string_match:
                    exact: app2
                - string_match:
                    exact: app3
```

This approach is much more concise and easier to read.

### Context

This feature would greatly enhance the RBAC capability of EnvoyProxy by allowing for more flexible matching against metadata fields.

### Proposed Solution

The solution would be to add support for xds.type.matcher.v3.ListStringMatcher in the type.matcher.v3.ValueMatcher used in type.matcher.v3.MetadataMatcher for RBAC Principal.

### Additional Information

I am happy to provide any additional information or clarifications that may be necessary to implement this feature.

Thank you for your consideration!
