### ISSUE TITLE
GRPC service mesh, configuration example

### ISSUE THREAD

**Issue by ArkadyB** [envoyproxy/envoy#2712]
Hi,

Im trying to build grpc service mesh. For the reason i consider to use tenvoy.tcp_proxy filter type, but it does not seem to work. Assuming we have two miscroservices both running GRPC with client application talking them GRPC too, what is my most basic configuration to use. Is there anywhere a reasonable example? Would i still have to use http-grpc bridge?

**Comment by dio** [comment]
Assuming one of your gRPC services runs at e.g. port `50051` and the client could connect insecurely (no TLS e.g. if using go we use [`grpc.Dial(address, grpc.WithInsecure())`](https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_client/main.go#L38)) to the server, the simplest config (.yaml v2) will be something like:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service_grpc }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_grpc
    connect_timeout: 25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: server, port_value: 50051 }}]
```
