### ISSUE TITLE
Envoy proxy on GCP Cloud Run shows 100s of requests forward to GRPC service but none getting through

### ISSUE THREAD

**Issue by shanifdhanani** [envoyproxy/envoy#27161]
*Title*: Cannot successfully set up Envoy on Google Cloud Run to forward grpc-web requests to backend GRPC service

*Description*:
Hi all, thanks for the help in advance. I've also posted this on StackOverflow [here](https://stackoverflow.com/questions/76168707/envoy-proxy-on-gcp-cloud-run-shows-100s-of-requests-forward-to-grpc-service-but).

I've got a backend GRPC service running on Google Cloud Run which I'm able to interact with just fine using another GRPC client. I now need to set up an Envoy proxy in front of it so that I can hit the backend with grpc-web requests. I've got this whole setup working fine on my local machine but am having a really hard time configuring it on Google Cloud.

The process I'm taking is to use an `envoy.yaml` file, along with Docker, to spin up a new Cloud Run service for Envoy. That service is supposed to accept requests from web browsers over SSL and forward them to the backend service (right now I'm just using the public URL of the GRPC backend server).

I'm seeing some really strange behavior in the Envoy service's logs. First, whenever Envoy gets a request, it seems like there are hundreds of requests being sent to the backend service, some of which have a 429 response, but most of which have a 200 response (see the image here) [log file from Envoy service showing hundreds of requests being sent to the backend service](https://i.stack.imgur.com/bDAWo.jpg).

The strange part is that none of these requests make it to the backend server, so I'm not sure how the 200 responses are being generated, or even why there are so many requests.

Here are the details of my setup and config files. Is there anyone out there that might be able to provide some guidance? I'm a relatively newbie with Envoy and am having trouble figuring out what to do from here, thanks so much!

Details of my setup:

**Backend service**

Running on a GRPC Cloud Run service, standard access at the instance URL running on port 8080 but externally available on port 443. The standard instance URL is https://api-service-rbuazbm3ua-uk.a.run.app/ but I've also tried mapping it to api-service.locusive.com, neither one does the trick.

```
envoy.yaml

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: api_service
                            max_grpc_timeout: 60s
                            retry_policy:
                              retry_on: connect-failure,refused-stream,unavailable,cancelled
                              num_retries: 3
                              per_try_timeout: 10s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: accept,access-control-allow-origin,origin,accept-encoding,accept-language,connection,authorization,keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message,grpc-status-details-bin,authorization
                http_filters:
                  - name: envoy.filters.http.grpc_web
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: api_service
      connect_timeout: 50s
      type: logical_dns
      lb_policy: round_robin
      http2_protocol_options: {}
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
      load_assignment:
        cluster_name: api_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: https://api-service-rbuazbm3ua-uk.a.run.app
                      port_value: 443
```

**Docker file**

```
FROM envoyproxy/envoy:v1.26-latest
COPY envoy.yaml /etc/envoy/envoy.yaml
EXPOSE 8080
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l off --component-log-level upstream:debug,connection:debug
```

**Deploy command**

```
gcloud builds submit --tag gcr.io/locusive/envoy-for-api-service
gcloud run deploy envoy-for-api-service --image gcr.io/locusive/envoy-for-api-service --platform managed --region=us-east4 --quiet --set-env-vars=ENVOY_UID=0 --min-instances=1 --max-instances=1 --memory=1Gi --cpu=1 --timeout=10m
```

Thanks again!
