### ISSUE TITLE
Why do I get "jwt is missing" when the method of HTTP mismatched

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#27162]
I'm using Envoy as the gateway of my backend micro-services. The requests of clients are HTTP and I'm trying to use jwt and rbac to acess or deny the requests. Here is the config of my Envoy:
```
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          codec_type: AUTO
          upgrade_configs:
          - upgrade_type: websocket
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                remote_jwt_provider:
                  remote_jwks:
                    http_uri:
                      uri: http://192.168.1.2:11223/security/jwks
                      cluster: jwt_dev_service
                      timeout: 3s
                    cache_duration:
                      seconds: 300
                  forward: true
                  from_headers:
                  - name: Authorization
                    value_prefix: "Bearer "
                  payload_in_metadata: jwt_payload
              rules:
                - match:
                    prefix: "/"
                  requires:
                    provider_name: remote_jwt_provider
          - name: envoy.filters.http.rbac
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              rules:
                action: ALLOW
                policies:
                  "loginUser":
                    permissions:
                      - any: true
                    principals:
                      - metadata:
                            filter: envoy.filters.http.jwt_authn
                            path:
                              - key: jwt_payload
                              - key: role
                            value:
                              string_match:
                                exact: "loginUser"
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["www.example.com:*"]
              typed_per_filter_config:
                envoy.filters.http.jwt_authn:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
                  "disabled": true    # disable jwt
                envoy.filters.http.rbac:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute    # disable rbac
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: ":method"
                    safe_regex_match: { google_re2: {}, regex: "GET|POST" }    # oops, DELETE is missing
                route:
                  cluster: my_cluster
```
As you see, I disabled `jwt` and `rbac` with the config `typed_per_filter_config`.

Now, when a client sends a request to Envoy, the client will get the error: `jwt is missing`. This error message does confuse me. As my understanding, I don't think Envoy should check jwt anymore as I have disabled jwt.

The real problem is that the request used the method `DELETE`. So I should add `DELETE` in the regex: `safe_regex_match: { google_re2: {}, regex: "GET|POST|DELETE" }`.

So I think it should tell me something like "method mismatched", instead of `jwt is missing`.

**Comment by yanavlasov** [comment]
Is this your complete configuration? It looks Envoy matched a different route that did not have jwt disabled.

**Comment by YvesZHI** [comment]
@yanavlasov  Here is the complete configuration of Envoy:
```
static_resources:
  listeners:
  - name: listener_common_https
    address:
      socket_address: *common_ingress_https_addr
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        transport_protocol: raw_buffer
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 200s
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["www.example.com:*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
    - filter_chain_match:
        transport_protocol: tls
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          codec_type: AUTO
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 1200s
          upgrade_configs:
          - upgrade_type: websocket
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                remote_jwt_provider:
                  remote_jwks:
                    http_uri:
                      uri: http://192.168.1.2:11223/security/jwks
                      cluster: jwt_dev_service
                      timeout: 3s
                    cache_duration:
                      seconds: 300
                  forward: true
                  from_headers:
                  - name: Authorization
                    value_prefix: "Bearer "
                  payload_in_metadata: jwt_payload
              rules:
                - match:
                    prefix: "/"
                  requires:
                    provider_name: remote_jwt_provider
          - name: envoy.filters.http.rbac
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              rules:
                action: ALLOW
                policies:
                  "loginUser":
                    permissions:
                      - any: true
                    principals:
                      - metadata:
                            filter: envoy.filters.http.jwt_authn
                            path:
                              - key: jwt_payload
                              - key: role
                            value:
                              string_match:
                                exact: "loginUser"
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["www.example.com:*"]
              typed_per_filter_config:
                envoy.filters.http.jwt_authn:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
                  "disabled": true
                envoy.filters.http.rbac:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
              routes:
              - match:
                  prefix: "/report"
                route:
                  cluster: cluster_report_https
              - match:
                  prefix: "/sso/"
                  headers:
                  - name: ":method"
                    safe_regex_match: { google_re2: {}, regex: "GET|POST|PUT" }
                route:
                  cluster: cluster_sso_https
              - match:
                  prefix: "/h5/"
                route:
                  cluster: cluster_static_resources_https
              - match:
                  prefix: "/attend/"
                  headers:
                  - name: ":method"
                    safe_regex_match: { google_re2: {}, regex: "GET|POST|DELETE" }    # DELETE was missing
                route:
                  cluster: cluster_common_https
```
The config above will redirect `http://www.example.com` to `https://www.example.com`. And the domain name of all requests is `www.example.com`.

In my real case, I just tried to access `https://www.example.com:80/attend/xxxx?xxx=xxx` but I got the error: `jwt is missing`.

I don't think it could be routed to another `route` as the domain name is unique in my config file. And I configured `typed_per_filter_config` to disable the jwt for all of requests with the same domain name `www.example.com`.

BTW, I just tried to modify `prefix: "/attend/"` to an illegal prefix `prefix: "/nonexist/"` and I got the same error: `jwt is missing`.
