### ISSUE TITLE
Response time of non-retry requests are abnormal when retry is enabled and load balance is ROUND_ROBIN

### ISSUE THREAD

**Issue by skyao** [envoyproxy/envoy#27200]
*Description*:

When retry is enabled and some of the upstream instance are unavailable, some of the requests will retry and their response time will be longer than normal because of retry excution times and retry interval. This is acceptable.

But unexpectedl I found that in my tests the response time of those requests that did not retry also increased substantially ( from 10x to 100x). 

envoy version in test: 

- envoy-1.23.3-linux-x86_64
- envoy-1.26.1-linux-x86_64
- envoy 1.26.0 on macbook with m1 (arm64)

*Repro steps*:

To reproduce this bug, first let us setup a simple test envioment:

1. run 3 instances of upstream service
2. configure envoy with dynamic_resources, set 3 hosts in eds
3. run client servie to send request to envoy and let envoy forward to upstream service, output the response time

In my local test, the response time is less than 1 ms. 

```bash
took 1.271935ms to handle request by 127.0.0.1:8081
took 379.598µs to handle request by 127.0.0.1:8082
took 401.386µs to return 502 by 127.0.0.1:8083
took 292.454µs to handle request by 127.0.0.1:8081
took 278.957µs to handle request by 127.0.0.1:8082
took 414.878µs to return 502 by 127.0.0.1:8083
took 234.92µs to handle request by 127.0.0.1:8081
took 396.238µs to handle request by 127.0.0.1:8082
took 340.616µs to return 502 by 127.0.0.1:8083
took 231.773µs to handle request by 127.0.0.1:8081
took 359.313µs to handle request by 127.0.0.1:8082
took 412.139µs to return 502 by 127.0.0.1:8083
took 260.813µs to handle request by 127.0.0.1:8081
took 251.288µs to handle request by 127.0.0.1:8082
took 261.323µs to return 502 by 127.0.0.1:8083
```

And then based on above test, we can enable retry:

1. stop 2 instances of upstream service (only one instance is available now)
2. still configure envoy with 3 hosts in eds, and set retry_policy to enable retry 2 times on connect failure. Note: Outlier detection is not enabled in this test to keep retry.
3. run client servie to send request to envoy and let envoy forward to upstream service, output the response time

```bash
took 11.360901ms to handle request by 127.0.0.1:8081
took 18.491406ms to handle request by 127.0.0.1:8081
took 36.326699ms to handle request by 127.0.0.1:8081
took 48.75473ms to handle request by 127.0.0.1:8081
took 21.637112ms to handle request by 127.0.0.1:8081
took 44.483578ms to handle request by 127.0.0.1:8081
took 47.538851ms to handle request by 127.0.0.1:8081
took 23.6226ms to handle request by 127.0.0.1:8081
took 23.692491ms to handle request by 127.0.0.1:8081
took 19.763271ms to handle request by 127.0.0.1:8081
took 37.53864ms to handle request by 127.0.0.1:8081
took 19.494346ms to handle request by 127.0.0.1:8081
took 54.641747ms to handle request by 127.0.0.1:8081
took 27.53774ms to handle request by 127.0.0.1:8081
took 48.463673ms to handle request by 127.0.0.1:8081
took 59.74403ms to handle request by 127.0.0.1:8081
took 19.564345ms to handle request by 127.0.0.1:8081
took 45.597605ms to handle request by 127.0.0.1:8081
took 30.664109ms to handle request by 127.0.0.1:8081
took 16.526893ms to handle request by 127.0.0.1:8081
took 34.471695ms to handle request by 127.0.0.1:8081
took 52.494014ms to handle request by 127.0.0.1:8081
took 55.586249ms to handle request by 127.0.0.1:8081
took 37.473847ms to handle request by 127.0.0.1:8081
took 26.514283ms to handle request by 127.0.0.1:8081
took 42.547209ms to handle request by 127.0.0.1:8081
took 52.782606ms to handle request by 127.0.0.1:8081
took 38.132269ms to handle request by 127.0.0.1:8081
took 37.349695ms to handle request by 127.0.0.1:8081
took 51.434794ms to handle request by 127.0.0.1:8081
took 41.489521ms to handle request by 127.0.0.1:8081
took 18.600715ms to handle request by 127.0.0.1:8081
took 55.583291ms to handle request by 127.0.0.1:8081
took 53.627493ms to handle request by 127.0.0.1:8081
took 26.456102ms to handle request by 127.0.0.1:8081
took 15.601114ms to handle request by 127.0.0.1:8081
took 63.590623ms to handle request by 127.0.0.1:8081
took 35.613699ms to handle request by 127.0.0.1:8081
took 50.385991ms to handle request by 127.0.0.1:8081
took 6.447477ms to handle request by 127.0.0.1:8081
took 34.412057ms to handle request by 127.0.0.1:8081
took 32.574641ms to handle request by 127.0.0.1:8081
took 16.486381ms to handle request by 127.0.0.1:8081
took 20.345687ms to handle request by 127.0.0.1:8081
took 59.523671ms to handle request by 127.0.0.1:8081
took 67.416321ms to handle request by 127.0.0.1:8081
took 34.524363ms to handle request by 127.0.0.1:8081
took 40.69275ms to handle request by 127.0.0.1:8081
took 51.936263ms to handle request by 127.0.0.1:8081
took 59.549922ms to handle request by 127.0.0.1:8081
took 19.435513ms to handle request by 127.0.0.1:8081
took 35.508126ms to handle request by 127.0.0.1:8081
took 58.637257ms to handle request by 127.0.0.1:8081
took 45.682466ms to handle request by 127.0.0.1:8081
took 55.54234ms to handle request by 127.0.0.1:8081
took 16.586397ms to handle request by 127.0.0.1:8081
took 25.433052ms to handle request by 127.0.0.1:8081
took 59.449766ms to handle request by 127.0.0.1:8081
took 58.588755ms to handle request by 127.0.0.1:8081
took 31.39941ms to handle request by 127.0.0.1:8081
took 55.686881ms to handle request by 127.0.0.1:8081
took 71.712516ms to handle request by 127.0.0.1:8081
took 25.74517ms to handle request by 127.0.0.1:8081
took 21.444026ms to handle request by 127.0.0.1:8081
took 24.569773ms to handle request by 127.0.0.1:8081
took 28.561783ms to handle request by 127.0.0.1:8081
took 42.353906ms to handle request by 127.0.0.1:8081
took 56.746627ms to handle request by 127.0.0.1:8081
took 20.384583ms to handle request by 127.0.0.1:8081
took 38.461693ms to handle request by 127.0.0.1:8081
took 22.393831ms to handle request by 127.0.0.1:8081
took 57.581472ms to handle request by 127.0.0.1:8081
took 47.556484ms to handle request by 127.0.0.1:8081
took 26.637028ms to handle request by 127.0.0.1:8081
took 23.413741ms to handle request by 127.0.0.1:8081
took 49.518896ms to handle request by 127.0.0.1:8081
took 12.47054ms to handle request by 127.0.0.1:8081
took 52.588586ms to handle request by 127.0.0.1:8081
took 38.572617ms to handle request by 127.0.0.1:8081
took 59.506564ms to handle request by 127.0.0.1:8081
took 40.519687ms to handle request by 127.0.0.1:8081
took 11.526154ms to handle request by 127.0.0.1:8081
took 32.542305ms to handle request by 127.0.0.1:8081
took 17.434735ms to handle request by 127.0.0.1:8081
took 49.495409ms to handle request by 127.0.0.1:8081
took 63.578263ms to handle request by 127.0.0.1:8081
took 27.606858ms to handle request by 127.0.0.1:8081
took 44.525296ms to handle request by 127.0.0.1:8081
took 24.398293ms to handle request by 127.0.0.1:8081
took 47.548674ms to handle request by 127.0.0.1:8081
took 31.437452ms to handle request by 127.0.0.1:8081
took 35.510384ms to handle request by 127.0.0.1:8081
took 63.776661ms to handle request by 127.0.0.1:8081
took 34.543402ms to handle request by 127.0.0.1:8081
took 37.530207ms to handle request by 127.0.0.1:8081
took 19.521264ms to handle request by 127.0.0.1:8081
took 15.769832ms to handle request by 127.0.0.1:8081
took 19.564991ms to handle request by 127.0.0.1:8081
took 30.668763ms to handle request by 127.0.0.1:8081
took 70.534826ms to handle request by 127.0.0.1:8081
took 19.464819ms to handle request by 127.0.0.1:8081
took 14.510138ms to handle request by 127.0.0.1:8081
took 32.536146ms to handle request by 127.0.0.1:8081
took 36.4547ms to handle request by 127.0.0.1:8081
```

Now we can't find any response time which is less than 1 ms. However, according to the probability, 33% of the requests should directly forward to the upstream instance without retry. if we ignore the requests with retry, at least 1/3 of the request should be as fast as retry is not enabled.

-------

Following are the details to reproduce this bug:

### envoy 

run envoy with command: `envoy-1.23.3-linux-x86_64 -c dynamic-filesystem.yaml`

dynamic-filesystem.yaml:

```yaml
node:
  cluster: test-cluster
  id: test-id
dynamic_resources:
  cds_config:
    path: /path-to/xds/cds.yaml
  lds_config:
    path: /path-to/xds/lds.yaml
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
```

cds.yaml:

```yaml
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: example_proxy_cluster
  type: EDS
  eds_cluster_config:
    service_name: server-service
    eds_config:
      path: /path-to/xds/eds.yaml

```

lds.yaml:

```yaml
resources:
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        http_filters:
        - name: envoy.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains:
            - "*"
            routes:
            - match:
                prefix: "/"
              route:
                cluster: example_proxy_cluster
```

when retry is enabled, set retry_policy as:

```yaml
                cluster: example_proxy_cluster
                retry_policy:
                  retry_on: connect-failure
                  num_retries: 2
                  host_selection_retry_max_attempts: 2
```

eds.yaml:

```yaml
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  cluster_name: server-service
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8081
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8082
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8083
```

### client and server app

server.go will write its port in the response so that we can know which upstream instance handled the request:

```go
package main

import (
	"fmt"
	"net/http"
	"os"
	"strconv"
)

var port int = 8080

func main() {
	// read environment variable
	var portstr = os.Getenv("PORT")
	if portstr != "" {
		port, _ = strconv.Atoi(portstr)
	}

	//write a log with port
	fmt.Printf("Server is running on port %d\n", port)

	// start a http server
	http.HandleFunc("/", handler)
	listenAddress := fmt.Sprintf(":%d", port)
	http.ListenAndServe(listenAddress, nil)
}

// handler echoes the Path component of the request URL r.
func handler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "handle request by 127.0.0.1:%d\n", port)
}
```

client.go:

```go
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"time"
)

func main() {

	// loop endlessly
	for {
		err := sendHttpRequest()
		if err != nil {
			println(err.Error())
		}
		time.Sleep(time.Millisecond * 100)
	}
}

func sendHttpRequest() error {
	startTime := time.Now()
	response, err := http.Get("http://localhost:10000")
	if err != nil {
		return err
	}

	defer response.Body.Close()
	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return err
	}

	endTime := time.Now()
	elapsedTime := endTime.Sub(startTime)

	fmt.Printf("took %s to %s\n", elapsedTime, string(body))

	return nil
}
```

**Comment by skyao** [comment]
This bug won't happen if we only retry for one time:

```yaml
                retry_policy:
                  retry_on: connect-failure
                  num_retries: 1
                  host_selection_retry_max_attempts: 1
```

```bash
took 13.183045ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 669.364µs to handle request by 127.0.0.1:8081
took 23.387859ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 277.972µs to handle request by 127.0.0.1:8081
took 16.979968ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 249.621µs to handle request by 127.0.0.1:8081
took 15.327207ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 330.03µs to handle request by 127.0.0.1:8081
took 24.434615ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 316.864µs to handle request by 127.0.0.1:8081
took 24.423659ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 297.968µs to handle request by 127.0.0.1:8081
took 23.470143ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 350.731µs to handle request by 127.0.0.1:8081
took 18.636382ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 230.035µs to handle request by 127.0.0.1:8081
took 246.698µs to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 239.083µs to handle request by 127.0.0.1:8081
took 7.345959ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 345.649µs to handle request by 127.0.0.1:8081
took 12.358176ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 276.469µs to handle request by 127.0.0.1:8081
took 2.309526ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 281.277µs to handle request by 127.0.0.1:8081
took 22.415821ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 234.286µs to handle request by 127.0.0.1:8081
took 24.511896ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 359.177µs to handle request by 127.0.0.1:8081
took 6.561762ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 294.052µs to handle request by 127.0.0.1:8081
took 268.99µs to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 265.566µs to handle request by 127.0.0.1:8081
took 16.380472ms to upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
took 244.707µs to handle request by 127.0.0.1:8081
```

**Comment by skyao** [comment]
I continue to test a special case that only 2 upstream instances. 

**2 instances, 1 unavailable, retry 1 times**: bug happend!

```bash
took 19.033707ms to handle request by 127.0.0.1:8081
took 23.623793ms to handle request by 127.0.0.1:8081
took 449.287µs to handle request by 127.0.0.1:8081
took 6.590654ms to handle request by 127.0.0.1:8081
took 23.376216ms to handle request by 127.0.0.1:8081
took 11.560476ms to handle request by 127.0.0.1:8081
took 24.388845ms to handle request by 127.0.0.1:8081
took 7.535776ms to handle request by 127.0.0.1:8081
took 15.440906ms to handle request by 127.0.0.1:8081
took 20.510225ms to handle request by 127.0.0.1:8081
took 4.389539ms to handle request by 127.0.0.1:8081
took 12.307194ms to handle request by 127.0.0.1:8081
took 12.355533ms to handle request by 127.0.0.1:8081
took 16.471154ms to handle request by 127.0.0.1:8081
took 8.384255ms to handle request by 127.0.0.1:8081
took 23.334937ms to handle request by 127.0.0.1:8081
took 17.472123ms to handle request by 127.0.0.1:8081
took 7.502983ms to handle request by 127.0.0.1:8081
took 12.412607ms to handle request by 127.0.0.1:8081
took 23.363491ms to handle request by 127.0.0.1:8081
took 15.616005ms to handle request by 127.0.0.1:8081
took 405.026µs to handle request by 127.0.0.1:8081
took 11.501683ms to handle request by 127.0.0.1:8081
took 12.381471ms to handle request by 127.0.0.1:8081
took 20.43174ms to handle request by 127.0.0.1:8081
took 2.333788ms to handle request by 127.0.0.1:8081
took 20.143866ms to handle request by 127.0.0.1:8081
took 11.481136ms to handle request by 127.0.0.1:8081
took 22.396374ms to handle request by 127.0.0.1:8081
took 3.338339ms to handle request by 127.0.0.1:8081
took 2.409408ms to handle request by 127.0.0.1:8081
took 8.405725ms to handle request by 127.0.0.1:8081
took 18.478946ms to handle request by 127.0.0.1:8081
took 24.419709ms to handle request by 127.0.0.1:8081
took 12.427245ms to handle request by 127.0.0.1:8081
took 3.312997ms to handle request by 127.0.0.1:8081
took 15.329045ms to handle request by 127.0.0.1:8081
took 16.401032ms to handle request by 127.0.0.1:8081
took 19.563468ms to handle request by 127.0.0.1:8081
took 7.452485ms to handle request by 127.0.0.1:8081
took 18.457694ms to handle request by 127.0.0.1:8081
took 22.348759ms to handle request by 127.0.0.1:8081
took 11.350426ms to handle request by 127.0.0.1:8081
took 11.38008ms to handle request by 127.0.0.1:8081
took 311.678µs to handle request by 127.0.0.1:8081
took 12.444826ms to handle request by 127.0.0.1:8081
took 15.358556ms to handle request by 127.0.0.1:8081
took 12.348852ms to handle request by 127.0.0.1:8081
took 11.05344ms to handle request by 127.0.0.1:8081
took 12.538124ms to handle request by 127.0.0.1:8081
took 20.409907ms to handle request by 127.0.0.1:8081
took 24.416305ms to handle request by 127.0.0.1:8081
took 8.374528ms to handle request by 127.0.0.1:8081
took 12.359491ms to handle request by 127.0.0.1:8081
took 24.485717ms to handle request by 127.0.0.1:8081
took 6.362937ms to handle request by 127.0.0.1:8081
took 23.605332ms to handle request by 127.0.0.1:8081
took 15.589942ms to handle request by 127.0.0.1:8081
took 18.410244ms to handle request by 127.0.0.1:8081
took 12.432423ms to handle request by 127.0.0.1:8081
took 6.422169ms to handle request by 127.0.0.1:8081
took 22.91782ms to handle request by 127.0.0.1:8081
took 1.362722ms to handle request by 127.0.0.1:8081
took 15.324939ms to handle request by 127.0.0.1:8081
took 22.3792ms to handle request by 127.0.0.1:8081
took 14.3228ms to handle request by 127.0.0.1:8081
took 20.437892ms to handle request by 127.0.0.1:8081
took 7.337243ms to handle request by 127.0.0.1:8081
took 24.394608ms to handle request by 127.0.0.1:8081
took 10.559763ms to handle request by 127.0.0.1:8081
took 4.499601ms to handle request by 127.0.0.1:8081
took 19.47917ms to handle request by 127.0.0.1:8081
took 23.331788ms to handle request by 127.0.0.1:8081
took 16.377681ms to handle request by 127.0.0.1:8081
took 3.633699ms to handle request by 127.0.0.1:8081
took 23.456589ms to handle request by 127.0.0.1:8081
took 3.533648ms to handle request by 127.0.0.1:8081
took 16.553462ms to handle request by 127.0.0.1:8081
took 8.418963ms to handle request by 127.0.0.1:8081
took 11.565639ms to handle request by 127.0.0.1:8081
took 24.462946ms to handle request by 127.0.0.1:8081
took 18.442129ms to handle request by 127.0.0.1:8081
took 7.324723ms to handle request by 127.0.0.1:8081
took 16.508848ms to handle request by 127.0.0.1:8081
took 11.596251ms to handle request by 127.0.0.1:8081
took 11.456268ms to handle request by 127.0.0.1:8081
took 16.50645ms to handle request by 127.0.0.1:8081
took 16.443705ms to handle request by 127.0.0.1:8081
took 19.495417ms to handle request by 127.0.0.1:8081
took 24.447679ms to handle request by 127.0.0.1:8081
took 12.307913ms to handle request by 127.0.0.1:8081
took 6.439305ms to handle request by 127.0.0.1:8081
took 4.626659ms to handle request by 127.0.0.1:8081
took 2.501228ms to handle request by 127.0.0.1:8081
took 18.434805ms to handle request by 127.0.0.1:8081
took 4.405084ms to handle request by 127.0.0.1:8081
took 23.983272ms to handle request by 127.0.0.1:8081
took 12.422538ms to handle request by 127.0.0.1:8081
took 4.509564ms to handle request by 127.0.0.1:8081
took 4.305524ms to handle request by 127.0.0.1:8081
took 3.465597ms to handle request by 127.0.0.1:8081
took 3.45064ms to handle request by 127.0.0.1:8081
```

This is a big risk!

**Comment by yanavlasov** [comment]
What is the load balancing policy on your cluster? It is possible that with some load balancing policies and without endpoint health status Envoy always ends up picking a dead host and has to retry.

@snowp @mattklein123 for any other ideas.

**Comment by skyao** [comment]
> What is the load balancing policy on your cluster? It is possible that with some load balancing policies and without endpoint health status Envoy always ends up picking a dead host and has to retry.
> 
> @snowp @mattklein123 for any other ideas.

By default it's round robin and I have tried Ramdom, the result is the same as round robin.

**Comment by skyao** [comment]
To make this problem more clear, I repeated the test: 

only start 2 instances and set in EDS:

```yaml
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8081
    - endpoint:
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 8082
```

RDS setting: 

```yaml
              route:
                cluster: example_proxy_cluster
                lb_policy: RANDOM
                retry_policy:
                  retry_on: connect-failure
                  num_retries: 1
                  host_selection_retry_max_attempts: 1
                  retry_back_off:
                    base_interval: 1s
                    max_interval: 1s
```

- set retry_back_off to 1s so that we can see the retry effect more clear
- load balance set to RANDOM, so as we expected, at least 50% requests should be assigned to the health instance and will succeed without retry. 

Start client to set, first 2 upstream are available and the latency is very small (about 0.2-0.3ms):

```bash
took 253.49µs to handle request by 127.0.0.1:8082
took 263.913µs to handle request by 127.0.0.1:8081
took 213.977µs to handle request by 127.0.0.1:8082
took 182.108µs to handle request by 127.0.0.1:8081
took 195.947µs to handle request by 127.0.0.1:8082
took 197.202µs to handle request by 127.0.0.1:8081
took 151.472µs to handle request by 127.0.0.1:8082
took 272.305µs to handle request by 127.0.0.1:8081
took 277.203µs to handle request by 127.0.0.1:8082
took 246.205µs to handle request by 127.0.0.1:8081
took 176.576µs to handle request by 127.0.0.1:8082
took 184.77µs to handle request by 127.0.0.1:8081
took 156.938µs to handle request by 127.0.0.1:8082
took 337.919µs to handle request by 127.0.0.1:8081
``` 

During the test, I stopped one of the upsteam instance:

```bash
......
took 156.938µs to handle request by 127.0.0.1:8082
took 337.919µs to handle request by 127.0.0.1:8081

# here we stopped one instance 8082
took 219.855778ms to upstream connect error or disconnect/reset before headers. reset reason: connection termination
took 319.669µs to handle request by 127.0.0.1:8081

# now only 8081 is available and retry is triggered
took 969.776559ms to handle request by 127.0.0.1:8081
took 527.558071ms to handle request by 127.0.0.1:8081
took 339.241858ms to handle request by 127.0.0.1:8081
took 441.595478ms to handle request by 127.0.0.1:8081
took 755.829149ms to handle request by 127.0.0.1:8081
took 10.461357ms to handle request by 127.0.0.1:8081
took 84.583089ms to handle request by 127.0.0.1:8081
took 559.573755ms to handle request by 127.0.0.1:8081
took 400.366397ms to handle request by 127.0.0.1:8081
took 750.696936ms to handle request by 127.0.0.1:8081
took 583.76399ms to handle request by 127.0.0.1:8081
took 619.755591ms to handle request by 127.0.0.1:8081
took 949.108269ms to handle request by 127.0.0.1:8081
took 898.989973ms to handle request by 127.0.0.1:8081
took 203.958741ms to handle request by 127.0.0.1:8081
took 725.794645ms to handle request by 127.0.0.1:8081
took 251.677415ms to handle request by 127.0.0.1:8081
took 472.082455ms to handle request by 127.0.0.1:8081
took 212.633811ms to handle request by 127.0.0.1:8081
took 534.055735ms to handle request by 127.0.0.1:8081
took 936.135804ms to handle request by 127.0.0.1:8081
took 785.954271ms to handle request by 127.0.0.1:8081
took 964.884317ms to handle request by 127.0.0.1:8081
```
