### ISSUE TITLE
how to properly configure authz extension to use https scheme in gRPC requests to auth server

### ISSUE THREAD

**Issue by anmelegov** [envoyproxy/envoy#27254]
In some reason authz http filter send requests to auth server with **http** scheme. Here is my envoy configuration:
```
http_filters:
  - name: envoy.filters.http.ext_authz
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
      grpc_service:
        envoy_grpc:
          cluster_name: ext-authz
        timeout: 0.5s
      include_peer_certificate: true
      transport_api_version: V3
      failure_mode_allow: true
...
clusters:
  - name: ext-authz
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: ext-authz
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: auth
                    port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

When request passing auth server I see the following logs in envoy container
```
[trace][ext_authz] [source/extensions/filters/http/ext_authz/ext_authz.cc:74] [C0][S1696271195143286478] ext_authz filter calling authorization server
[trace][ext_authz] [source/extensions/filters/common/ext_authz/ext_authz_grpc_impl.cc:42] Sending CheckRequest: attributes {
  source {
    address {
      socket_address {
        address: "192.168.0.1"
        port_value: 56542
      }
    }
  }
  destination {
    address {
      socket_address {
        address: "192.168.0.7"
        port_value: 5001
      }
    }
    principal: ******
  }
  request {
    time {
      seconds: 1683622927
      nanos: 9955000
    }
    http {
      id: "1696271195143286478"
      method: "GET"
      headers {
        key: ":authority"
        value: ******
      }
      headers {
        key: ":method"
        value: "GET"
      }
      headers {
        key: ":path"
        value: ******
      }
      headers {
        key: ":scheme"
        value: "https"
      }
      headers {
        key: "accept"
        value: "*/*"
      }
      headers {
        key: "accept-encoding"
        value: "gzip, deflate, br"
      }
      headers {
        key: "cache-control"
        value: "no-cache"
      }
      headers {
        key: "user-agent"
        value: ******
      }
      headers {
        key: "x-forwarded-proto"
        value: "https"
      }
      headers {
        key: "x-request-id"
        value: "38778e04-67ab-4d2a-bcb5-397157c0f465"
      }
      path: *****
      host: *****
      scheme: "https"
      protocol: "HTTP/1.1"
    }
  }
  metadata_context {
  }
}

[debug][router] [source/common/router/router.cc:478] [C0][S804008839173026723] cluster 'ext-authz' match for URL '/envoy.service.auth.v3.Authorization/Check'
[debug][router] [source/common/router/router.cc:686] [C0][S804008839173026723] router decoding headers:
':method', 'POST'
':path', '/envoy.service.auth.v3.Authorization/Check'
':authority', 'ext-authz'
':scheme', 'http'
'te', 'trailers'
'grpc-timeout', '500m'
'content-type', 'application/grpc'
'x-envoy-internal', 'true'
'x-forwarded-for', '192.168.0.7'
'x-envoy-expected-rq-timeout-ms', '500'
```
Is there a way to enforce envoy using **https** scheme in auth requests?
