### ISSUE TITLE
The Envoy xDS Socket can be configured to use either a VCL socket or a Kernel socket through YAML configuration.

### ISSUE THREAD

**Issue by YanLongDai** [envoyproxy/envoy#27267]
*Title*: *The Envoy xDS socket can be configured to use either a VCL socket or a Kernel socket through YAML configuration.*

*Description*:
>1. The current status of Envoy configuration with VCL is that the Admin Socket uses Kernel Socket, while the Grpc Socket and the data plane Listener Socket use VCL Socket.

>2.The current issue is that our company's project requires the control plane XDS Socket and management plane Admin Socket to use the kernel for reliability reasons. However, this configuration is not supported at the moment.

>3.So it would be ideal for Envoy to develop a feature that allows specifying whether the XDS Socket should use VCL Socket or Kernel Socket directly in the YAML configuration.

@htuch @lizan 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by daiyl123** [comment]
I have successfully tested this feature locally. Now, I would like to know if I can apply to merge it into the main branch.
@htuch @lizan @ravenblackx

**Comment by htuch** [comment]
I'm not sure what this looks like API or implementation wise. Can you share? @adisuissa as well.

**Comment by daiyl123** [comment]
> I'm not sure what this looks like API or implementation wise. Can you share? @adisuissa as well.


**1、Let me describe the purpose and specific presentation effect of the change:**

> a、The purpose of this change is to decouple the control surface and data surface from each other. In some demand scenarios, the management surface and control surface need to use kernel mode network interfaces, while the data surface needs to use VPP network interfaces

> b、From the perspective of reliability, in addition, it is to ensure that the control surface can still receive configurations even if the VPP is coredump



**2、Presentation of the modified effect:**
Modify envoy.yaml file，Add ‘socket_vcl_or_kernel’ field 
![image](https://github.com/envoyproxy/envoy/assets/127860365/543d7140-5437-448e-afe0-850d60e07e67)

**Comment by htuch** [comment]
So, to be clear here, this is using Envoy gRPC (vs. Google gRPC) and you just want to be able to configure what kind of socket is used for the cluster that is handling the Envoy gRPC for the xDS server?

@florincoras do you have any thoughts on how you envisaged VPP config modeling for clusters?

**Comment by daiyl123** [comment]
> 所以，这里要明确的是，这是使用Envoy gRPC（相对于Google gRPC），你只是希望能够配置哪种套接字用于处理xDS服务器的Envoy gRPC的集群？
> 
> 您对如何设想集群的 VPP 配置建模有什么想法吗？




====================================================
Yes, I hope to configure the Xds Server Socket to choose between VCL Socket or Kernel Socket through configuration. I hope that the Admin and XDS of the management and control surfaces will go through the kernel，Dataplane Socket go through Vcl


**1、The Envoy architecture is as follows,  there are three types of sockets :** 

- [ ]            a、Admin Socket
- [ ]            b、Grpc Xds Server Socket 
- [ ]            c、 Dataplane Socket

**2、The current functional status of Envoy on our official website after using the VCL plugin is as follows:**
       

- [ ]     a、The Admin Socket uses Kernel Socket
- [ ]            b、The Grpc Xds Server Socket uses VCL Socket
- [ ]            c、The Dataplane Socket uses VCL Socket

<img width="552" alt="image" src="https://github.com/envoyproxy/envoy/assets/127860365/879d3b27-db92-4258-9edc-611880cd1b6f">

I don't quite understand why the design of our official website is even configured with VCL configuration. The Admin Socket also runs through the kernel socket, while the Grpc Socket runs through VCL Socket, What are the special uses of the two designs that are different

**Comment by florincoras** [comment]
> So, to be clear here, this is using Envoy gRPC (vs. Google gRPC) and you just want to be able to configure what kind of socket is used for the cluster that is handling the Envoy gRPC for the xDS server?
> 
> @florincoras do you have any thoughts on how you envisaged VPP config modeling for clusters?

@htuch because of how Envoy bootstrap works, current approach separates the admin socket from the rest of sockets. Consequently, because xDS is configured on a cluster, the socket allocated by the cluster will just use the default socket interface which, when vcl is enabled, will be `VclSocketInterface`. 

@daiyl123 instead of enforcing the socket type at cluster level, we could maybe do it by setting the socket type (here)[https://github.com/envoyproxy/envoy/blob/8cfeabd5bd0b15b5e6ef029bf9fef4dcaa1c8254/api/envoy/config/core/v3/address.proto#L175) or by adding a custom resolver that returns an `InstanceConstSharedPtr` that would return the default socket interface on `socketInterface()` call.

**Comment by htuch** [comment]
Yes, the `Address` proto seems a better option here.

**Comment by daiyl123** [comment]
> > So, to be clear here, this is using Envoy gRPC (vs. Google gRPC) and you just want to be able to configure what kind of socket is used for the cluster that is handling the Envoy gRPC for the xDS server?
> > @florincoras do you have any thoughts on how you envisaged VPP config modeling for clusters?
> 
> @htuch because of how Envoy bootstrap works, current approach separates the admin socket from the rest of sockets. Consequently, because xDS is configured on a cluster, the socket allocated by the cluster will just use the default socket interface which, when vcl is enabled, will be `VclSocketInterface`.
> 
> @daiyl123 instead of enforcing the socket type at cluster level, we could maybe do it by setting the socket type [here](https://github.com/envoyproxy/envoy/blob/8cfeabd5bd0b15b5e6ef029bf9fef4dcaa1c8254/api/envoy/config/core/v3/address.proto#L175) or by adding a custom resolver that returns an `InstanceConstSharedPtr` that would return the default socket interface on `socketInterface()` call.


==============================================================
@florincoras @htuch  Thank you very much for the explanations of the two experts, your plan is more beautiful.  And now there are two conclusions that need to be compared with experts to see if my understanding is correct

> 1、If I complete the development and debugging according to the solution we discussed above, can I share this function to the envoy main line？ I also want to contribute my strength to the community
> 
> 2、As suggested above, I sorted out the interface presented to the user, is it as follows:

![image](https://github.com/envoyproxy/envoy/assets/127860365/4b4296ed-156c-4e59-a571-ef8517593910)

**Comment by htuch** [comment]
Yes, I think we would take such a change in Envoy main, but I don't think the current example you give is the right one exactly. Agree with moving this to address 👍 but I think the idea that @florincoras mentioned that seemed good was to use a resolver  extension https://github.com/envoyproxy/envoy/blob/8cfeabd5bd0b15b5e6ef029bf9fef4dcaa1c8254/api/envoy/config/core/v3/address.proto#L87 to allow the address to be "resolved" to a VCL provider. So there shouldn't need to be any API change for this.

**Comment by YanLongDai** [comment]
> 

========================================================
1、@htuch Thank you for your reply, I have thought about your suggestion, and some details of the plan need to be communicated，

2、Do you mean to set the socket to vcl Socket Interface through the resolver_name field?   Is it the following format?
![image](https://github.com/envoyproxy/envoy/assets/127860365/d8ee9193-9a6f-47d2-a810-076642625b72)

3、If the above configuration is ok .    I have some doubts：

Normally, after we configure   _**default_socket_interface: "envoy.extensions.vcl.vcl_socket_interface"**_, all listeners and grpcs use vcl sockets,  However, I now want grpc to take the kernel socket, the factory that needs resolver_name to specify the kernel socket, but I can't find it , can you tell me how to configure the kernel socket factory?

I understand that after configuring **_default_socket_interface: "envoy.extensions.vcl.vcl_socket_interface"_**, all should use vcl by default, and only those with the same resolver_name specified as kernel will use the kernel socket；Conversely, the configuration **_default_socket_interface: "envoy.extensions.vcl.vcl_socket_interface"_** is meaningless



4、If there is a problem with my understanding of the configuration interface, please help me to use the following configuration to give an example. What method do you want to use to specify the socket to use the kernel or vcl?


 ```
 clusters:
    - type: STATIC
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      name: xds_cluster
      socket_vcl_or_kernel: socket_kernel
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 192.168.53.101
                      port_value: 9999
                      resolver_name: "envoy.extensions.vcl.vcl_socket_interface"

bootstrap_extensions:
  - name: envoy.extensions.vcl.vcl_socket_interface
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.vcl.v3alpha.VclSocketInterface
default_socket_interface: "envoy.extensions.vcl.vcl_socket_interface"

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000


```
