### ISSUE TITLE
Why requests are routed to different upstream servers even with same consistent hashing LB and hash key?

### ISSUE THREAD

**Issue by krapie** [envoyproxy/envoy#27358]
*Title*: *Why requests are routed to different upstream servers even with same consistent hashing LB and hash key?*

*Description*:
Hi, I'm currently using envoy's consistent hashing (ring hash, maglev) for load balance workloads to upstream servers, and I'm using header `x-shard-key` as hash parameter for consistent hashing.

I have two different request type: SDK API request which uses server port `11101`, and admin API request which uses server port `11103`. I want to route both requests to same upstream server (server affinity) when they have same `x-shard-key` value.

But even they have same `x-shard-key`, they routed differently (eg: SDK API request get routed to server A, and admin API request get routed to server B, even if they have same `x-shard-key: chegor8n2c3c73dms560/codepair-1234`).

I thought it was due to upstream servers have different host address(because two requests are routed to different ports), hashed output of upstream servers are different (eg: for SDK API request, host address will be `10.1.1.1:11101` and `10.1.1.1:11103` for admin API request).

So I configured [`hash_key`](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/load_balancers#ring-hash) to set same host address between two request type, but it did not work.

Below is example(test) of my `envoy.yaml`:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: yorkie_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: yorkie_ring_hash_routes
                  virtual_hosts:
                    - name: yorkie_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: yorkie_service
                            hash_policy:
                              header:
                                header_name: x-shard-key
                            # https://github.com/grpc/grpc-web/issues/361
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-api-key,x-shard-key,x-user-agent,x-grpc-web,grpc-timeout,authorization,x-yorkie-user-agent
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message, grpc-status-details-bin
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
    - name: admin_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 9090 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: yorkie_ring_hash_routes
                  virtual_hosts:
                    - name: yorkie_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: admin_service
                            hash_policy:
                              header:
                                header_name: x-shard-key
                            # https://github.com/grpc/grpc-web/issues/361
                            max_stream_duration:
                              grpc_timeout_header_max: 0s
                      cors:
                        allow_origin_string_match:
                          - prefix: "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-api-key,x-shard-key,x-user-agent,x-grpc-web,grpc-timeout,authorization,x-yorkie-user-agent
                        max_age: "1728000"
                        expose_headers: custom-header-1,grpc-status,grpc-message, grpc-status-details-bin
                http_filters:
                  - name: envoy.filters.http.grpc_web
                  - name: envoy.filters.http.cors
                  - name: envoy.filters.http.router
  clusters:
    - name: yorkie_service
      connect_timeout: 0.25s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: ring_hash
      ring_hash_lb_config:
        minimum_ring_size: 125
      load_assignment:
        cluster_name: yorkie_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11101
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie1"
              - endpoint:         
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11201
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie2"
              - endpoint:   
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11301
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie3"
    - name: admin_service
      connect_timeout: 0.25s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: ring_hash
      ring_hash_lb_config:
        minimum_ring_size: 125
      load_assignment:
        cluster_name: admin_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11103
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie1"
              - endpoint:  
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11203
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie2"
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 11303
                metadata:
                  filter_metadata:
                    envoy.lb:
                      hash_key: "yorkie3"

```

As you can see, there are two listeners and clusters for two different request type, but they have same hash parameter `x-shard-key` and also same host address `hash_key: "yorkie[n]"` for consistent hashing lb. But requests were routed differently even they have same hash `x-shard-key`.

I could not find any other reasons for this behavior. Any ideas will be helpful.
