### ISSUE TITLE
Envoy listener should enhance listening to IPv6 addresses

### ISSUE THREAD

**Issue by opencmit2** [envoyproxy/envoy#27362]
When I test envoy's support for IPv4/IPv6 dual stack, I need to add '' when listening to all IPv6 addresses

```
- name: listener_1
          address:
            socket_address: { address: '::' , port_value: 10000 }
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    codec_type: AUTO
                    route_config:
                      name: local_route
                      virtual_hosts:
                      - name: local_service
                        domains: ["*"]
                        routes:
                        - match: { prefix: "/" }
                          route: { cluster: some_service }
                    http_filters:
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
