### ISSUE TITLE
What are the load balancing strategies for lb_endpoints and for endpoints?

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#27364]
I'm kind of confused by `lb_policy` under `cluster`. Let's say I have two `lb_endpoints` and there are two `endpoints` in each of them.
```
clusters:
- name: xxx
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: xxx
    endpoints:
    - lb_endpoints:
      - endpoint: {address: ...}
      - endpoint: {address: ...}
    - lb_endpoints:
      - endpoint: {address: ...}
      - endpoint: {address: ...}
```

I'm not sure which kind of load balancing strategy is controlled by `lb_policy`. Is it the load balancing strategy of `lb_endpoints` or of `endpoint` under each `lb_endpoints`?
