### ISSUE TITLE
Lua filter - peerCertificateValidated() - not available for 100% of the mTLS connections

### ISSUE THREAD

**Issue by pxpnetworks** [envoyproxy/envoy#27370]
Hello, 
given the following check:
```
if connection:ssl() and stream:downstreamSslConnection() then
  if stream:downstreamSslConnection():peerCertificatePresented() then
    request_handle:logInfo("peer certificate is presented")
    if stream:downstreamSslConnection():peerCertificateValidated() then
      request_handle:logInfo("peer certificate is validated")
    else
      request_handle:logInfo("peer certificate is NOT validated")
    end
  else
    request_handle:logInfo("mTLS required!")
  end
else
  request_handle:logInfo("TLS = false")
end
```
All of the downstream mtls connections log that "peer certificate is presented" 
Some of the downstream mtls connections log that "peer certificate is **NOT** validated" 

Anyone has an idea what is causing this?

**image: envoyproxy/envoy:dev**

**Comment by ggreenway** [comment]
It depends on your configuration. In the TLS context, you can specify how certificates are validated, and what should happen if they cannot be validated. See https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#envoy-v3-api-msg-extensions-transport-sockets-tls-v3-certificatevalidationcontext. My guess is that your TLS context allows unvalidated certs.

**Comment by pxpnetworks** [comment]
@ggreenway, thanks for your help. Let me show the setup i'm using.
Client_Envoy---->Server_Envoy
Client_Envoy - tunneling downstream TCP traffic using a cluster which adds ProxyProtocol and TLS
Server_Envoy - terminating the ProxyProtocol, TLS and the tunnel

Client_Envoy:
```
  transport_socket:
    name: envoy.transport_sockets.upstream_proxy_protocol
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.proxy_protocol.v3.ProxyProtocolUpstreamTransport
      config:
        version: V2
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          sni: netcore.pxpfinancial.com
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_2
            alpn_protocols:
            - h2
            validation_context:
              trusted_ca: { "filename": "/etc/epn/secrets/ca.crt" }
            tls_certificates:
              certificate_chain: { "filename": "/etc/epn/secrets/cert.crt" }
              private_key: { "filename": "/etc/epn/secrets/base.key" }
```
Server_Envoy:
```
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            require_client_certificate: true
            common_tls_context:
              tls_params:
                tls_minimum_protocol_version: TLSv1_2
                tls_maximum_protocol_version: TLSv1_3
              alpn_protocols:
              - h2
              validation_context:
                trusted_ca:
                  inline_string: |
                    -----BEGIN CERTIFICATE-----
                    ...
                    -----END CERTIFICATE-----
              tls_certificates:
                certificate_chain: 
                  inline_string: |
                    -----BEGIN CERTIFICATE-----
                    ...
                    -----END CERTIFICATE-----
                private_key: 
                  inline_string: |
                    -----BEGIN PRIVATE KEY-----
                    ...
                    -----END PRIVATE KEY-----
```
