### ISSUE TITLE
Envoy admin runtime endpoint broken

### ISSUE THREAD

**Issue by milton0825** [envoyproxy/envoy#27376]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Envoy admin runtime endpoint broken

*Description*:

Envoy admin [runtime endpoint](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--runtime) is returning empty string everywhere. We are expecting it to show values in string.

*Repro steps*:
Deployed version: https://github.com/envoyproxy/envoy/commit/bb619eaeb2a1ee3f30cdd2aa087b7c9bee604ff8

*Admin and Stats Output*:
Actual
```
0:9901/runtime | grep -A10 "circuit_breakers.compliance.default.max_requests"
  "circuit_breakers.compliance.default.max_requests": {
   "final_value": "",
   "layer_values": [
    "",
    "",
    "",
    "",
    ""
   ]
  },
```
Expected
```
0:9901/runtime | grep -A10 "circuit_breakers.compliance.default.max_requests"
  "circuit_breakers.compliance.default.max_requests": {
   "final_value": "",
   "layer_values": [
    "1024",
    "",
    "",
    "",
    ""
   ]
  },
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by ggreenway** [comment]
@milton0825 can you post what you expect the runtime values to be here?

@alyssawilk is there any way this is related to removing yaml from runtime parsing? That change is a few commits before the one being tested.

**Comment by ggreenway** [comment]
@milton0825 thanks!

@alyssawilk can you investigate?

**Comment by milton0825** [comment]
We have two layers (disk & rtds) and it seems like they are both not loading properly:
```
layered_runtime:
  layers:
    - name: root
      disk_layer:
        symlink_root: /srv/configset/envoydata/current
        subdirectory: envoy

    - name: rtds_override
      rtds_layer:
        name: rtds
        rtds_config:
          resource_api_version: V3
          api_config_source:
            api_type: GRPC
            transport_api_version: V3
            grpc_services:
              envoy_grpc: {cluster_name: envoymanager}
```

Disk is pretty simple. Just a directory containing envoy runtime files. For example:
```
cat upstream/zone_routing/enabled
0
```
For RTDS, it is:
```
artLayer := map[string]*structpb.Value
...
# Adding some structpb.StringValue to artLayer
...

&runtimev3.Runtime{Name: "rtds", Layer: &structpb.Struct{Fields: artLayer}}
```
