### ISSUE TITLE
Inconsistent behaviour in copying x-b3-traceid using upstream http filters

### ISSUE THREAD

**Issue by DPham-X** [envoyproxy/envoy#27416]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Inconsistent behaviour in copying x-b3-traceid using upstream http filters*

*Description*:
Envoy will only sometimes be able copy the x-b3-traceid header into another header using using upstream http filters.

```yaml
            - name: copy-trace
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                mutations:
                  request_mutations:
                    append:
                      header:
                        key: copy-trace
                        value: "%REQ(x-b3-traceid)%"
                      append_action: OVERWRITE_IF_EXISTS_OR_ADD
```

*Repro steps*:
1. Clone this repo https://github.com/DPham-X/upstream-header-mutation
2. Run curl -v http://localhost:8081/headers multiple times
3. Look for Copy-Trace header, this header will only sometimes appear.

*Config*:
>Include the config used to configure Envoy.

https://github.com/DPham-X/upstream-header-mutation/blob/main/config.yaml
