### ISSUE TITLE
gRPC routing based on Method, ServiceName. How does it work?

### ISSUE THREAD

**Issue by ArkadyB** [envoyproxy/envoy#2742]
Hi,

I cant seem to find any documentation (example) where two or more gRPC services running behind Envoy would actually have routing based on either gRPC definitons, service/method names or something more H2 like approach. Everythin is about routing H1 to H2. Is it possible to have Envoy doing routing for pure gRPC services?

**Comment by mattklein123** [comment]
Yes. gRPC is just HTTP. Each service is under a specific path. You can setup prefix routing to route to different service clusters.

**Comment by ArkadyB** [comment]
@mattklein123 thank you for answer! 

It does not seem to work for some reason. I have Service1 running behind Envoy with given configuration:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 30271 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: service1_grpc
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service1_grpc }
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: service1_grpc
    connect_timeout: 25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 30270 }}]
```

With docker compose i have launched two instances of this service. 
```
version: '3'
services:
  callerservice_grpc:
    image: "callerservice:latest"
    networks:
      - envoymesh
    ports:
      - "30336"

  service1_grpc:
    image: "service1_grpc:latest"
    networks:
      envoymesh:
        aliases:
          - service1_grpc
    expose:
      - "30271"

networks:
  envoymesh: {}
```

Making callerservice to call service1 method aways calls the same instance in service1 docker container. Any idea why? What am i doing wrong?
