### ISSUE TITLE
slow-start not work with zone aware

### ISSUE THREAD

**Issue by paragor** [envoyproxy/envoy#27440]
*Title*: *slow-start not work with zone aware*

*Description*:
In production we use cluster with zone aware endpoints. When main zone's endpoint restarted, we expect that traffic follow to other zone until health check on main will not to be ok, and finally traffic should return to main endpoint with slow start. But slow start doesnot work in case zone aware. Screens (north - main zone): 

When enable zone-aware, slow start doesnt work as expected:
north (main):
![image](https://github.com/envoyproxy/envoy/assets/31911894/b832b10e-1126-4d29-b09d-33d9d1c099aa)
west:
![image](https://github.com/envoyproxy/envoy/assets/31911894/3112a933-2d37-4d49-8d77-e10ddae72984)
east:
![image](https://github.com/envoyproxy/envoy/assets/31911894/3fbef1fc-f080-48e0-90f3-b6a591ed49ab)

But when zone aware is disabled - slow start works ok, but logic with main and second's endpoints doesnt work:
north (main):
![image](https://github.com/envoyproxy/envoy/assets/31911894/6e357fe7-38b5-4be2-a965-123a114e63de)
west:
![image](https://github.com/envoyproxy/envoy/assets/31911894/225c09ca-546c-4c65-9ca0-f97674c390ec)
east:
![image](https://github.com/envoyproxy/envoy/assets/31911894/15c68e26-5f8f-4c51-80fd-a2536aada5c2)

*Config*:
envoy version: v1.25
config with zone aware:
```yaml
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
cluster_manager:
  local_cluster_name: local_cluster

node:
  locality:
    zone: north
layered_runtime:
  layers:
    - name: "layer1"
      static_layer:
        upstream.zone_routing.min_cluster_size: 1
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: service }
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: local_cluster
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: local_cluster
        endpoints:
          - locality: { zone: "north" }
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 80 }
          - locality: { zone: "east" }
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 80 }
          - locality: { zone: "west" }
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 80 }

    - name: service
      connect_timeout: 0.25s
      type: STRICT_DNS
      health_checks:
        - timeout: 10s
          interval: 10s
          unhealthy_threshold: 1
          healthy_threshold: 1
          http_health_check:
            path: /readyz
      round_robin_lb_config:
        slow_start_config:
          slow_start_window: 60s
          aggression:
            default_value: 1
            runtime_key: "slow-start-aggression"
          min_weight_percent:
            value: 10
      lb_policy: ROUND_ROBIN
      common_lb_config:
        zone_aware_lb_config: {}
      load_assignment:
        cluster_name: service
        endpoints:
          - locality: { zone: "north" }
            load_balancing_weight: 100
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: upstream-north, port_value: 80 }
          - locality: { zone: "east" }
            load_balancing_weight: 100
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: upstream-east, port_value: 80 }
          - locality: { zone: "west" }
            load_balancing_weight: 100
            lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: upstream-west, port_value: 80 }
```
envoy cmd:
```
    command:
      - envoy 
      - -c 
      - /examples/envoy-docker.yaml 
      - --service-node
      - node-id 
      - --service-cluster
      - cluster-id
      - --service-zone
      - north
```
