### ISSUE TITLE
gRPC load balancing

### ISSUE THREAD

**Issue by ArkadyB** [envoyproxy/envoy#2744]
I cant seem to make Envoy working with multiple gRPC services deployed. gRPC call always goes to the same instance. How does Envoy load balancer discovers there are other instances of same service were launched with docker-compose scale?

 Service1 configuration i use:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 30271 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: service1_grpc
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service1_grpc }
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: service1_grpc
    connect_timeout: 25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 30270 }}]
```

Now caller service has gRPC client init with:
`grpc.Dial("service1_grpc:30271", grpc.WithInsecure())`

Problem is, whenever i launch multiple instances of service1 using docker-compose scale command, newly launched ones never receive any calls. Where is the problem with my configuration?
