### ISSUE TITLE
TCP stream hanging on connection creation

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#27485]
*Description*:
New TCP get to ``tcp_proxy`` - ``onNewConnection()``, and ``onUpstreamConnection()`` is not called. 15 minutes later, the stream is destroyed.

*Config*:

Filter chain config:
```
    filter_chains:
    - filters:
      - name: envoy.filters.network.sni_dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
          port_value: 443
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
      - name: tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_proxy
          cluster: [sanitized]
          tunneling_config:
            hostname: host.com:443
            use_post: true
```

Cluster config:

```
  - name: [sanitized]
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
        allow_insecure_cluster_options: true
        allow_coalesced_connections: true
```

*Logs*:
Trace logs for the connection:
```
05-18-2023     12:24:30    trace    tcp_proxy.cc:716                      [C6638] on downstream event 2, has upstream = false
05-18-2023     12:24:30    trace    connection_impl.cc:423                [C6638] raising connection event 2
05-18-2023     12:24:30    debug    active_tcp_listener.cc:155            [C6638] new connection from [sanitized]
05-18-2023     12:24:30    trace    connection_impl.cc:679                [C6638] write ready
05-18-2023     12:24:30    trace    connection_impl.cc:568                [C6638] socket event: 2
05-18-2023     12:24:30    trace    connection_impl.cc:362                [C6638] readDisable: disable=true disable_count=0 state=0 buffer_length=0
05-18-2023     12:24:30    debug    tcp_proxy.cc:234                      [C6638] new tcp proxy session
05-18-2023     12:24:30    trace    proxy_filter.cc:44                    [C6638] sni_dynamic_forward_proxy: new connection with server name '[sanitized]'
05-18-2023     12:24:30    debug    tcp_proxy.cc:413                      [C6638] Creating connection to cluster [sanitized]
05-18-2023     12:24:30    debug    proxy_filter.cc:83                    [C6638] DNS cache entry already loaded, continuing
05-18-2023     12:40:15    trace    tcp_proxy.cc:716                      [C6638] on downstream event 1, has upstream = false
05-18-2023     12:40:15    trace    active_stream_listener_base.cc:111    [C6638] connection on event 1
05-18-2023     12:40:15    debug    active_stream_listener_base.cc:121    [C6638] adding to cleanup list
05-18-2023     12:40:15    trace    connection_impl.cc:423                [C6638] raising connection event 1
05-18-2023     12:40:15    debug    tcp_proxy.cc:413                      [C6638] Creating connection to cluster [sanitized]
05-18-2023     12:40:15    debug    connection_impl.cc:139                [C6638] closing data_to_write=0 type=1
05-18-2023     12:40:15    debug    connection_impl.cc:250                [C6638] closing socket: 1
```

Notice the time, there's 15 minutes gap between the "Creating connection to cluster" log, and the "on downstream event 1" log. In a normal flow, I would expect to see the following log, or some other error indicating logs mid-way:
https://github.com/envoyproxy/envoy/blob/1816b675dbd3e6ae10ac01778f5b9aca6e54f71d/source/common/tcp_proxy/tcp_proxy.cc#L799

Will appreciate any help understanding what may cause this.
