### ISSUE TITLE
HTTP Route priority example

### ISSUE THREAD

**Issue by redonkulus** [envoyproxy/envoy#27500]
I've checked the docs and tests but haven't been able to find a simple example of [route priority](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#arch-overview-http-routing-priority). 

With the below example, I would assume that requests to `/api` would go to the `api_service`. If that is not available, then it would go to `default_service`.

```yaml
routes:
  - match:
      prefix: "/api"
    route:
      cluster: "api_service"
      priority: "high"
  - match:
      prefix: "/api"
    route:
      cluster: "default_service"
```

However, when I use this, the default cluster is never used. The request just fails to load. 

Is there something I'm missing?
