### ISSUE TITLE
Why can't I add xff to the headers of requests in Envoy

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#27501]
I'm trying to add `X-Forwarded-For` into the headers of requests with Envoy. Here is the part of my config:
```
route_config:
  name: my_route
  request_headers_to_add:
    header:
      key: "X-Forwarded-For"
      value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
  virtual_hosts:
  ...
```
The upstream is `httpbin`, which can show me the headers of request.

But it doesn't seem to work as expected. The `httpbin` show me the whole header but without `X-Forwarded-For`. So it seems that `request_headers_to_add` isn't working.

Then I changed the key to `X-Real-IP` but I got the same result. I haven't seen `X-Real-IP` in the output of `httpbin`.

However, if I use some other keys, such as `key: hello`, I could see `hello: xx.xx.xx.xx` in the header...

It seems that I can add anything in the header with Envoy except `X-Forwarded-For` and `X-Real-IP`.

**Comment by wbpcode** [comment]
Could you provide a complete example config? And specific to your current config snippet, seems it's wrong. The `request_headers_to_add` should be a array.

**Comment by YvesZHI** [comment]
@wbpcode  You are right about array, I changed it to an array but noting changed.

Here is the config of my Envoy.
```
static_resources:
  listeners:
  - name: listener_test_http
    address:
      socket_address: {address: 0.0.0.0, port_value: 9001}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 200s
          access_log: [{name: envoy.access_loggers.stdout, typed_config: {"@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog}}]
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          use_remote_address: true
#          skip_xff_append: false
#          xff_num_trusted_hops: 1
          route_config:
            name: local_route
            request_headers_to_add:
            - header:
#                key: "X-Real-IP"                     # NOT OK
#                key: "X-Forwarded-For"        # NOT OK
               key: "xxxx"                                # OK
                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
#              append: true
            virtual_hosts:
            - name: notice_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/bin/"
                route:
                  cluster: cluster_httpbin
                  prefix_rewrite: "/"
  clusters:
  - name: cluster_httpbin
    connect_timeout: 10s
    type: LOGICAL_DNS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
        common_http_protocol_options:
          idle_timeout: 3600s
        explicit_http_config:
          http_protocol_options: {}
    load_assignment:
      cluster_name: cluster_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: {address: 172.16.0.44, port_value: 12780}
```

I send a request to `http://172.16.0.42:9001/bin/get` (I deployed my Envoy on `172.16.0.42`) and my Envoy routes the request to the upstream host `172.16.0.44:12780`, which is a `httpbin`. Then I can see the header of request but there is no `X-Forwarded-For`.
