### ISSUE TITLE
load balancer behavior from envoy after changing server application to headless

### ISSUE THREAD

**Issue by mcfongtw** [envoyproxy/envoy#27548]
*Title*: load balancer behavior after changing service to headless

*Description*:
We are looking for help/advise/pointer on the particular problem below.

We want to use client-side load balancing from envoy, and we change our server application service to headless. 

We now observe some behavior change that client grpc requests of the same connection do not go to the same pod; in other words, the requests could be routed to any of the application pod (depending on which LB strategy we pick). We want to know if there is a way make envoy always stay a particular pod for the same client connection once it's established?

Given that the server application might be stateful and perform based on client state kept in its memory. 

Here is an example of our envoy configuration
```
    - name: server-app
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      load_assignment:
        cluster_name: server-app
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: server-app-headless
                      port_value: <port>
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
