### ISSUE TITLE
Question: rewriting the request path like "host_rewrite_header"

### ISSUE THREAD

**Issue by WeixinX** [envoyproxy/envoy#27572]
*Description*:

Is there any way I can rewrite the request path during forwarding? Just like `host_rewrite_header` does

**Comment by pxpnetworks** [comment]
Hi, is this what you are looking for?
[https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-prefix-rewrite](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-prefix-rewrite)

**Comment by WeixinX** [comment]
Thank you ~ This does work. 

But I wanted to do it in a more dynamic way. For example, by modifying the request header in the **Wasm plugin** and making it match the original path.

As shown below with `host_rewrite_header`:

envoy.yaml:
```yaml
# ...
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                scheme_header_transformation:
                  scheme_to_overwrite: https
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["foo.com"]
                      routes:
                        - match:
                            prefix: "/foo"
                          name: "foo"
                          route:
                            host_rewrite_header: x-my-custom-host # Look at this
                            cluster: echoserver
                http_filters:
                  - name: wasmdemo
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          name: wasmdemo
                          vm_config:
                            runtime: envoy.wasm.runtime.v8
                            code:
                              local:
                                filename: /etc/envoy/main.wasm
                          configuration:
                            "@type": "type.googleapis.com/google.protobuf.StringValue"
                            value: |
                              {}
                  - name: envoy.filters.http.router
# ...
```
plugin.go:
```go
// <Snip ...>
	proxywasm.ReplaceHttpRequestHeader("x-my-custom-host", "example.com")
	log.Debug("rewrite host successful")
// <Snip ...>
```

result:
```bash
curl -i 127.0.0.1:10000/foo -H "host: foo.com"
HTTP/1.1 200 OK
content-type: application/json
x-content-type-options: nosniff
date: Tue, 23 May 2023 09:21:10 GMT
content-length: 565
req-cost-time: 4
req-arrive-time: 1684833670039
resp-start-time: 1684833670043
x-envoy-upstream-service-time: 2
server: envoy

{
 "path": "/foo",
 "host": "example.com",
 "method": "GET",
 "proto": "HTTP/1.1",
 "headers": {
  "Accept": [
   "*/*"
  ],
  "Original-Host": [
   "foo.com"
  ],
  ...
  "X-My-Custom-Host": [
   "example.com"
  ],
 ...
```
