### ISSUE TITLE
aws x-ray tracer configuration with hostname

### ISSUE THREAD

**Issue by SPopenko** [envoyproxy/envoy#27570]
Hello guys, 
Standard configuration works fine
```
tracing:
  http:
    name: envoy.tracers.xray
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.XRayConfig
      segment_name: "Envoy" # You must set this until v1.14 
      daemon_endpoint:
        protocol: UDP
        address: 127.0.0.1
        port_value: 2000
      sampling_rule_manifest:
        filename: /xray_daemon/rules.json
```

But how to use configuration with a host name like this:

```
tracing:
  http:
    name: envoy.tracers.xray
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.XRayConfig
      segment_name: "Envoy" # You must set this until v1.14 
      daemon_endpoint:
        protocol: UDP
        address: xray-service.amazon-cloudwatch.svc.cluster.local
        port_value: 2000
      sampling_rule_manifest:
        filename: /xray_daemon/rules.json
```

Error that happened with such config in EKS + Istio 

warning envoy config  gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8080: malformed IP address: xray-service.amazon-cloudwatch.svc.cluster.local:2000
0.0.0.0_8443: malformed IP address: xray-service.amazon-cloudwatch.svc.cluster.local:2000

Related to 
#10442 
https://github.com/aws/aws-app-mesh-roadmap/issues/319
