### ISSUE TITLE
ExternalProcessor only receives one "type" of request

### ISSUE THREAD

**Issue by schulmanworks** [envoyproxy/envoy#27582]
*Title*: *ExternalProcessor does not send requests properly*

*Description*:
> I expect that an external processing server can receive request and response headers and body information in a single filter. It seems I only receive one option. For example, I can receive request headers or request body information, but not both. Additionally, it seems my server never receives response data at all.

*Repro steps*:

HTTP filter:
```
          http_filters:
            - name: envoy.filters.http.ExternalProcessor
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                grpc_service:
                  # envoy_grpc:
                  #   cluster_name: validation_service
                  google_grpc:
                      target_uri: grpc-processor:9920
                      stat_prefix: ext_proc
                  timeout: 10s
                failure_mode_allow: false
                async_mode: false
                request_attributes:
                - user
                response_attributes:
                - server
                processing_mode: 
                  request_header_mode: SEND
                  response_header_mode: SEND
                  request_body_mode: BUFFERED
                  response_body_mode: BUFFERED
                  request_trailer_mode: SKIP
                  response_trailer_mode: SKIP
```

Process function:

```
func (s *extProcServerV3) Process(p procv3.ExternalProcessor_ProcessServer) error {
	iterations := 0
	// var requests []procv3.ProcessingRequest
	var err error
	ctx := p.Context()
	var resp *procv3.ProcessingResponse
	for req, err := p.Recv(); req != nil; {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}
		if err == io.EOF {
			return nil
		}
		if err != nil {
			log.Fatal("Failed to receive processing request.")
			return err
		}
		log.Printf("%d", iterations)
		log.Printf("%s", req.GetRequest())
		iterations += 1
		switch req.Request.(type) {
		case *procv3.ProcessingRequest_RequestHeaders:
			log.Printf("ProcessingRequest_RequestHeaders\n")
			resp = &procv3.ProcessingResponse{
				Response: &procv3.ProcessingResponse_RequestHeaders{
					RequestHeaders: &procv3.HeadersResponse{
						Response: &procv3.CommonResponse{
							HeaderMutation: &procv3.HeaderMutation{
								SetHeaders: []*envoy_api_v3_core.HeaderValueOption{
									{
										Append: &wrappers.BoolValue{Value: false},
										Header: &envoy_api_v3_core.HeaderValue{
											// For a successful request, the authorization server sets the
											// x-current-user value.
											Key:   "x-test-header",
											Value: "test-value",
										},
									},
								},
							},
						},
					},
				},
			}
			if err := p.Send(resp); err != nil {
				log.Printf("send error %v", err)
			}
			return err
		case *procv3.ProcessingRequest_ResponseHeaders:
			log.Printf("ProcessingRequest_ResponseHeaders\n")
			resp = &procv3.ProcessingResponse{
				Response: &procv3.ProcessingResponse_ResponseHeaders{
					ResponseHeaders: &procv3.HeadersResponse{
						Response: &procv3.CommonResponse{
							HeaderMutation: &procv3.HeaderMutation{
								SetHeaders: []*envoy_api_v3_core.HeaderValueOption{
									{
										Append: &wrappers.BoolValue{Value: false},
										Header: &envoy_api_v3_core.HeaderValue{
											// For a successful request, the authorization server sets the
											// x-current-user value.
											Key:   "x-test-header",
											Value: "test-value",
										},
									},
								},
							},
						},
					},
				},
			}
			if err := p.Send(resp); err != nil {
				log.Printf("send error %v", err)
			}
			return err
		case *procv3.ProcessingRequest_RequestBody:
			log.Printf("ProcessingRequest_RequestBody\n")
			log.Printf("EndOfStream %s\n", req.GetRequestBody().EndOfStream)

			if req.GetRequestBody().EndOfStream {
				resp = &procv3.ProcessingResponse{
					Response: &procv3.ProcessingResponse_RequestHeaders{
						RequestHeaders: &procv3.HeadersResponse{
							Response: &procv3.CommonResponse{
								HeaderMutation: &procv3.HeaderMutation{
									SetHeaders: []*envoy_api_v3_core.HeaderValueOption{
										{
											Append: &wrappers.BoolValue{Value: false},
											Header: &envoy_api_v3_core.HeaderValue{
												// For a successful request, the authorization server sets the
												// x-current-user value.
												Key:   "x-test-header",
												Value: "test-value",
											},
										},
									},
								},
							},
						},
					},
				}
				if err := p.Send(resp); err != nil {
					log.Printf("send error %v", err)
				}
				return err
			}
		case *procv3.ProcessingRequest_ResponseBody:
			log.Printf("ProcessingRequest_ResponseBody\n")
			if req.GetResponseBody().EndOfStream {
				resp = &procv3.ProcessingResponse{
					Response: &procv3.ProcessingResponse_ResponseHeaders{
						ResponseHeaders: &procv3.HeadersResponse{
							Response: &procv3.CommonResponse{
								HeaderMutation: &procv3.HeaderMutation{
									SetHeaders: []*envoy_api_v3_core.HeaderValueOption{
										{
											Append: &wrappers.BoolValue{Value: false},
											Header: &envoy_api_v3_core.HeaderValue{
												// For a successful request, the authorization server sets the
												// x-current-user value.
												Key:   "x-test-header",
												Value: "test-value",
											},
										},
									},
								},
							},
						},
					},
				}
				if err := p.Send(resp); err != nil {
					log.Printf("send error %v", err)
				}
				return err
			}
		}
	}
	return err
}
```

Output:
```
2023/05/23 15:50:38 Starting gRPC server at [::]:9920
2023/05/23 15:55:23 0
2023/05/23 15:55:23 &{headers:{headers:{key:":path"  value:"/kv.KV/Set"}  headers:{key:":authority"  value:"172.18.0.6:9912"}  headers:{key:":method"  value:"POST"}  headers:{key:":scheme"  value:"http"}  headers:{key:"content-type"  value:"application/grpc"}  headers:{key:"te"  value:"trailers"}  headers:{key:"grpc-accept-encoding"  value:"identity, deflate, gzip"}  headers:{key:"user-agent"  value:"grpc-python/1.53.0 grpc-c/30.1.0 (linux; chttp2)"}  headers:{key:"client_header"  value:"client header data"}  headers:{key:"x-forwarded-proto"  value:"http"}  headers:{key:"x-request-id"  value:"9dbe6a4b-a879-4739-87a1-8e8b968010bb"}}}
2023/05/23 15:55:23 ProcessingRequest_RequestHeaders
2023/05/23 15:55:24 0
2023/05/23 15:55:24 &{headers:{headers:{key:":path"  value:"/kv.KV/Set"}  headers:{key:":authority"  value:"172.18.0.6:9912"}  headers:{key:":method"  value:"POST"}  headers:{key:":scheme"  value:"http"}  headers:{key:"content-type"  value:"application/grpc"}  headers:{key:"te"  value:"trailers"}  headers:{key:"grpc-accept-encoding"  value:"identity, deflate, gzip"}  headers:{key:"user-agent"  value:"grpc-python/1.53.0 grpc-c/30.1.0 (linux; chttp2)"}  headers:{key:"client_header"  value:"client header data"}  headers:{key:"x-forwarded-proto"  value:"http"}  headers:{key:"x-request-id"  value:"114ac6e8-455d-4fca-8446-849633c254c6"}}}
2023/05/23 15:55:24 ProcessingRequest_RequestHeaders
```
Here, I am expecting to see output from all four ProcessingRequest types.
