### ISSUE TITLE
How to make use of ClusterManager object during server init process

### ISSUE THREAD

**Issue by suniltheta** [envoyproxy/envoy#27586]
**Description**:

This is follow up on https://github.com/envoyproxy/envoy/issues/25918 where my understanding was wrong as I thought I can't access threadLocalCluster from inside main thread.

But after I came across https://github.com/envoyproxy/envoy/issues/26653 and some discussion I realized that `clusterManager()` interface is invalid during server initialization process. So my attempt to get thread local cluster with `cluster_manager.getThreadLocalCluster(cluster_name_)` fails at https://github.com/envoyproxy/envoy/blob/fe55c4f8a9989b10367f86eab224b218d3bdc835/source/common/thread_local/thread_local_impl.cc#L65-L68
```
[2023-03-03 04:23:51.749][2171546][critical][assert] [source/common/thread_local/thread_local_impl.cc:66]
 assert failure: currentThreadRegisteredWorker(index).
```

I want to get the  thread local cluster to make HTTP calls to fetch aws metadata credentials. This is required to get rid of libcurl. The credentials will be used when I want to specify Google gRPC service call credentials via [Grpc Credentials AWS IAM](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/grpc_credential/v3/aws_iam.proto.html) plugin.

Here I am using Google gRPC service, but in case of [EnvoyGrpc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice-envoygrpc) it is able to take the `cluster_name`, so that means it should be possible to use the functionality of cluster manager during server init process. I believe I should be able to overcome my issue by changing the initialization order, but just not able to figure out how.

**Changes on my forked repo**  https://github.com/suniltheta/envoy/blob/dffdf598d8395afea0ad86077cd709b6220e252f/source/extensions/common/aws/metadata_fetcher.cc#L78-L84

**Config**:
```
dynamicResources:
  adsConfig:
    apiType: GRPC
    grpcServices:
    - googleGrpc:
        callCredentials:
        - fromPlugin:
            name: envoy.grpc_credentials.aws_iam
            typedConfig:
              '@type': type.googleapis.com/envoy.config.grpc_credential.v3.AwsIamConfig
              region: us-west-2
              serviceName: xds_controlplane
        channelArgs:
          sslCredentials:
            rootCerts:
              filename: cert.pem
        credentialsFactoryName: envoy.grpc_credentials.aws_iam
        statPrefix: ads
        targetUri: <xds_controlplane>
    transportApiVersion: V3
  cdsConfig:
    ads: {}
    initialFetchTimeout: 0s
    resourceApiVersion: V3
  ldsConfig:
    ads: {}
    initialFetchTimeout: 0s
    resourceApiVersion: V3
```

**Call Stack**:
Here is the call stack decoded https://gist.github.com/suniltheta/43a3bf684d8fe350cb0d083774e2d111 during failure.
