### ISSUE TITLE
Static EDS Cluster fails with ADS as EDS Config

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#2759]
We have defined two static cluster, one for ADS and another static cluster of type EDS with ADS as the EDS Config. Envoy crashes while initializing the Static Cluster.

Here is the boot strap config

```
node:
  id: id_1
  cluster: test_cluster
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
dynamic_resources:
  ads_config:
    api_type: GRPC
    cluster_names: [xds_cluster]
  lds_config: {ads: {}}
  cds_config: {ads: {}}
static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {} 
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 15001
  - name: test
    connect_timeout: 0.25s
    type: EDS
    eds_cluster_config:
      eds_config: {ads: {}}
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {} 
```
Envoy crashes while loading the "test" cluster.
**Debug Notes:**
It is failing at `cluster_manager_impl` [constructor](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L211) 
This is because, the cluster that is being initialized tries to use `ADS` but ADS is initialized after this call. 
We need to ensure either ADS is initialized before or such clusters are initialized later.
