### ISSUE TITLE
503s if Cloudflare is behind Envoy

### ISSUE THREAD

**Issue by molbal** [envoyproxy/envoy#27649]
*Title*: Frequent 503s if Cloudflare is behind Envoy

*Real life effect*

Integration with legal research software using a REST API experiences 503 errors intermittently, affecting the overall reliability of the service. We have a workaround in place now for this particular API, but we anticipate similar issues in the future. 

*Description of the issue*:
Envoy encounters an issue when sending requests to a REST API, resulting in 503 errors. The expected behavior should be consistent communication with the REST API without 503 errors.

*Description of environment*

The issue was recreated in a controlled environment using HTTPBin to simulate a REST API (routed through Cloudflare), and Envoy to route requests. 

```
,---------------.     ,-----.     ,----------.     ,----------------------.
|Client (JMeter)| --> |Envoy| --> |CloudFlare| --> |Upstream API (HTTPBin)|
`---------------'     `-----'     `----------'     `----------------------'
```

*Reproduction steps*:
JMeter was used to reproduce the issue. The script contained the following steps:
 
1. Infinite loop
  a. Call HTTPBin with an endpoint that takes 10s to return (`/drip?duration=10&numbytes=10&code=200&delay=2`)
  b. Wait 10m

The issue could be reproduced with low concurrency (10 concurrent threads, or around 1 req/minute), but it was most reliably replicated with 1000 concurrent threads. Due to the exact origin of the issue, I do not have an exact 

*Unsuccessful fixes*

The following attempts were made to address the issue, but none successfully resolved the problem:
- Disabling 0-RTT Connection Resumption on Cloudflare
- Disabling HTTP3 QUIC entirely on Cloudflare

*Working config*

After applying the following configuration settings in Envoy, the issue with 503 errors was resolved:

```
common_http_protocol_options:
  idle_timeout: 1800s
upstream_connection_options:
  tcp_keepalive:
    keepalive_time: 1800
    keepalive_probes: 10
    keepalive_interval: 60
drain_timeout: 30s
```

This makes me assume that in some cases, Envoy is trying to use a thread that has already been closed.

An example request/response pair:
*Request*
````
GET https://[URL]/drip?duration=10&numbytes=10&code=200&delay=2
Connection: keep-alive
Host: [URL]
User-Agent: Apache-HttpClient/4.5.13 (Java/1.8._371)
````

*Response body*
````json
{
  "errorCode": "01-01-0199",
  "message": "General gateway exception. Code: 'upstream_reset_before_response_started{connection_termination}' - 'upstream connect error or disconnect/reset before headers. reset reason: connection termination'"
}
````

*Response headers*
````
HTTP/1.1 503 Service Unavailable
Date: Tue, 23 May 2023 09:09:46 GMT
Content-Type: application/json
Content-Length: 237
Connection: keep-alive
correlationid: ...
server: envoy
````

*Configuration*
Configuration with 503s
````yaml
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: httpbin
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    common_http_protocol_options:
      idle_timeout: 300s
    load_assignment:
      cluster_name: httpbin
      endpoints:
        - lb_endpoints:
            - endpoint: { address: { socket_address: { address: [Upstream's CloudFlare URL], port_value: 443 } } }
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: [Upstream's CloudFlare URL]
````

Working config

**clusters.yaml**
````yaml
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: httpbin
    connect_timeout: 5s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    common_http_protocol_options:
      idle_timeout: 300s
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 1800
        keepalive_probes: 10
        keepalive_interval: 60
    drain_timeout: 30s
    load_assignment:
      cluster_name: httpbin
      endpoints:
        - lb_endpoints:
            - endpoint: { address: { socket_address: { address: [Upstream's CloudFlare URL], port_value: 443 } } }
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: [Upstream's CloudFlare URL]
````

I would like to raise this issue, because other teams may run into a similar situation, where external requirements cause _unconventional_ setups. Primarily, I would like to understand if this issue is caused by incorrect default Envoy configuration or is the root cause something else? If it is confirmed, I will raise a PR to change these default values to improve the interoperability of Envoy.
