### ISSUE TITLE
How to append header on response to client?

### ISSUE THREAD

**Issue by Haim-Barilan** [envoyproxy/envoy#27758]
Hi,
We have an old backend server that return "set-cookie" header to client.
I wish to update the cookie and add "HttpOnly; Secure" which currently it does not contain it.

I tried to use response_headers_to_add with the same cookie name but it's just adding another header with the same name and not replacing the existing cookie.

Is there any way to do it without using Lua script?

This is what I tired:
```
response_headers_to_add:
                    - header:
                        key: "set-cookie"
                        value: "%RESP(set-cookie)%; HttpOnly; Secure"
```
and this is what i get:
![image](https://github.com/envoyproxy/envoy/assets/100832412/d5f500ec-54e0-42f2-b527-98de601561b9)

I got it working with:
```
                            #envoy.filters.http.lua:
                            #  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                            #  source_code:
                            #    inline_string: |
                            #      function envoy_on_response(response_handle)
                            #        function set_cookie_header(rh)
                            #          s = rh:headers():get("Set-Cookie")
                            #          if string.find(s, "usertoken=" ) then
                            #            s = s.."; HttpOnly; Secure"
                            #          end
                            #          return s
                            #        end
                            #        if response_handle:headers():get("Set-Cookie") then
                            #          secure_cookie_header = set_cookie_header(response_handle)
                            #          response_handle:headers():replace("Set-Cookie",secure_cookie_header)
                            #        end
                            #      end   
```

But I believe there is a better answer than this.

Thanks for your help!

**Comment by phlax** [comment]
iiuc the question it is how to _append_ headers to an upstream response

**Comment by ohadvano** [comment]
Reading the docs: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-headervalueoption, it says that the default action is appending the value to existing headers, if exists. Maybe try without the ``%RESP(set-cookie)`` in the value?

**Comment by Haim-Barilan** [comment]
> Reading the docs: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#config-core-v3-headervalueoption, it says that the default action is appending the value to existing headers, if exists. Maybe try without the `%RESP(set-cookie)` in the value?

I tried that, this is what i get without RESP value -
![image](https://github.com/envoyproxy/envoy/assets/100832412/e96d61b7-28b1-48a6-9b67-2f333fbb53d5)

**Comment by ohadvano** [comment]
So unless I misunderstood the docs, it's either a bug or possible there's  another configuration in your yaml is causing this. Could you try adding the ``APPEND_IF_EXISTS_OR_ADD`` explicitly? Might be helpful if you share the relevant parts of the config here

**Comment by Haim-Barilan** [comment]
> So unless I misunderstood the docs, it's either a bug or possibly there's another configuration in your yaml that is causing this. Could you try adding the `APPEND_IF_EXISTS_OR_ADD` explicitly? Might be helpful if you share the relevant parts of the config here

Thanks.

I removed some routes to reduce content length.

```
static_resources:
  listeners:
    - name: listener_https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                http_protocol_options:
                  header_key_format:
                    stateful_formatter:
                      name: preserve_case
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
                upgrade_configs:
                  - upgrade_type: websocket
                access_log:
                  name: envoy.access_loggers
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
                route_config:
                  name: search_route
                  response_headers_to_add:
                    - header:
                        key: Content-Security-Policy
                        value: frame-ancestors 'self';
                    - header:
                        key: Strict-Transport-Security
                        value: max-age=31536000
                    - header:
                        key: "set-cookie"
                        value: ";HttpOnly; Secure"
                      append_action: APPEND_IF_EXISTS_OR_ADD 
      
                  virtual_hosts:      
                    - name: service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: /
                            case_sensitive: false
                          route:
                            cluster: some-cluster
                          typed_per_filter_config:
                            envoy.filters.http.ext_authz:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                              disabled: true
                            envoy.http.stateful_session.cookie:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSessionPerRoute
                              disabled: true

                # Each HTTP request to all virtual hosts - filters being triggerd sequentially
                http_filters:
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      http_service:
                        server_uri:
                          uri: ${OAUTH_PROXY_ENDPOINT}:{OAUTH_PROXY_PORT}
                          cluster: auth-service
                          timeout: 4.5s
                        path_prefix: "/Auth"
                        authorization_request:
                          allowed_headers:
                            patterns:
                              - exact: cookie
                  #Lua filter to support override some query parameters
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  # Statful session support for Gfn application                
                  - name: envoy.filters.http.stateful_session
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
                      session_state:
                        name: envoy.http.stateful_session.cookie
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
                          cookie:
                            name: session-cookie
                            path: /
                            ttl: 300s 
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                - certificate_chain:
                    filename: /etc/certs/fullchain.pem
                  private_key:
                    filename: /etc/certs/privkey.pem

  clusters:
    - name: some-cluster
      connect_timeout: 120s
      type: logical_dns
      load_assignment:
        cluster_name: av-server-backend-tenant-a
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 172.0.3.40
                      port_value: 80
    
    - name: auth-service
      connect_timeout: 120s
      type: logical_dns
      load_assignment:
        cluster_name: auth-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 172.0.3.152
                      port_value: 80

admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

```
