### ISSUE TITLE
Envoy not matching network RBAC policy 

### ISSUE THREAD

**Issue by maoudia-via** [envoyproxy/envoy#27876]
*Title*: *Request matching fails with network RBAC filter*

*Description*:

I have the following filter configuration to allow TLS traffic only to nytimes.com

```
static_resources:
  listeners:
  - name: listener_443
    address:
      socket_address: {address: 0.0.0.0, port_value: 443}
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    per_connection_buffer_limit_bytes: 32768 # 32 KiB
    filter_chains:
    - filters:
      - name: envoy_rbac
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC
          stat_prefix: "allowed_"
          rules:
            action: ALLOW
            policies:
              "allow":
                principals:
                  - any: true
                permissions:
                - and_rules:
                    rules:
                    - requested_server_name:
                        contains: "nytimes.com"
                    - destination_port: 443
```
I am trying to send a request through the envoy proxy 

`curl --proxy <proxy-ip>:443 https://www.nytimes.com`

However, when looking the the logs I see the following:

CONNECTION_TERMINATION_DETAILS is `rbac_access_denied_matched_policy[none]`
REQUESTED_SERVER_NAME is empty.
It looks like the policy does not match and the requested_server_name is not captured but I am not sure why. 
Can anybody help with this ?
