### ISSUE TITLE
How to use third-party packages such as json in Lua of EnvoyFilter

### ISSUE THREAD

**Issue by Tiam2Y** [envoyproxy/envoy#27889]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
>Describe the issue.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Hello, first of all thank you very much for your open source project Envoy.
I'm currently having some issues with Istio-EnvoyFilter.

I need to use httpCall() to request an external service for data validation, so I need to parse the body of request and response through json. But when I try to require the module 'json', I get the following exception:
```text
module 'json' not found:
no field package.preload['json']
no file './json.lua'
....
```
My EnvoyFilter configuration is as follows:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: oauth-choice
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
    patch:
        operation: INSERT_BEFORE
        value:
            name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inlineCode: |
                  local json = require "json"
                  function envoy_on_request(request_handle)
                    local auth_headers = {
                      [":method"] = "POST",
                      [":path"] = "/oauth/authorize",
                      [":authority"] = "xxx.xxx.xxx.xxx",
                      ["Content-Type"] = "application/json"
                    }
                    local auth_token = request_handle:headers():get("token")
                    local auth_body_temp = {}
                    auth_body_temp["token"] = auth_token
                    local auth_body = json:encode(auth_body_temp)
                    local headers, body = request_handle:httpCall("lua_cluster",auth_headers,auth_body,5000)
                    ...
                  end
                  function envoy_on_response(response_handle)
                    response_handle:headers():add("hehehe", "heheheh1")
                  end
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: lua_cluster
        connect_timeout: 0.75s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: lua_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: "xxx.xxx.xxx.xxx"
                    port_value: xxxx
```

I read in the documentation [envoy-1.7-zh](https://www.bookstack.cn/read/envoy-1.7-zh/configuration-http_filters-lua_filter.md) that `This filter only supports loading Lua code built into the configuration. If you need code from your local filesystem, you can use a built-in scriptlet to load the rest from your local environment.` So where is the built-in scriptlet? What should I do?

I also saw a similar [issue](https://github.com/envoyproxy/envoy/issues/21900) with a solution:
>Please install the cjson in the image first. You can rebuild a image with cjson as following code:
```
FROM    envoyproxy/envoy-dev:6abcebc93f3d0616ba38ad9c5fec97dfc9c32645

RUN     apt update && apt install -y \
            luarocks

RUN    luarocks install lua-cjson
```

But Envoy is built into Istio, how can I find this image, and how can I replace it after rebuilding so that `kubectl apply -f EnvoyFilter.yaml` can achieve automatic replacement?
