### ISSUE TITLE
How to define multiple rbac rules and apply some of them for different routes

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#27891]
I used `jwt_authn` and `rbac` for a listener in my Envoy. Here is a part of the config of my Envoy:
```
          http_filters:
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                remote_jwt_provider:
                  remote_jwks:
                    http_uri:
                      uri: *jwks_url
                      cluster: cluster_jwks_http
                      timeout: 1s
                    cache_duration:
                      seconds: 300
                  forward: true
                  from_headers:
                  - name: Authorization
                    value_prefix: "Bearer "
                  payload_in_metadata: jwt_payload
              rules:
                - match:
                    prefix: "/"
                  requires:
                    provider_name: remote_jwt_provider
          - name: envoy.filters.http.rbac
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
              rules:
                action: ALLOW
                policies:
                  "loginUser":
                    permissions:
                      - any: true
                    principals:
                      - metadata:
                            filter: envoy.filters.http.jwt_authn
                            path:
                              - key: jwt_payload
                              - key: role
                            value:
                              string_match:
                                exact: "loginUser"
                  "ip-whitelist":
                    permissions:
                      - any: true
                    principals:
                      - remote_ip: { address_prefix: 111.111.111.111, prefix_len: 28}
                      - remote_ip: { address_prefix: 111.111.111.112, prefix_len: 28}
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["example.com"]
              routes:
              - match:        # disable jwt, disable rbac-loginUser, enable rbac-ip-whitelist
                  prefix: "/gray/"
                route:
                  cluster: cluster_common_https
              - match:        # enable jwt, enable rbac-loginUser, disable rbac-ip-whitelist
                  prefix: "/portal/"
                route:
                  cluster: cluster_common_https
              - match:        # enable jwt, enable rbac-loginUser, enable rbac-ip-whitelist
                  path: "/version/getAllVersion"
                route:
                  cluster: cluster_common_https
```

As you see, I want to make three different rules for the three route configs. I've known how to disable jwt and disable rbac for a route config:
```
              typed_per_filter_config:
                envoy.filters.http.jwt_authn:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.PerRouteConfig
                  "disabled": true
                envoy.filters.http.rbac:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
```

But my case is more complicated so I don't think the config above could help me.

**Comment by ravenblackx** [comment]
`RBACPerRoute` disables RBAC if you put its config empty like in your example, but it has an `rbac` field in it, so you can simply define your different rules inside that `typed_per_filter_config` for the route. ([docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/rbac/v3/rbac.proto#extensions-filters-http-rbac-v3-rbacperroute))
Something like
```
              typed_per_filter_config:
                envoy.filters.http.rbac:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
                  rbac:
                    rules:
                      action: ALLOW
                      policies:
                        "loginUser":
                          permissions:
                            - any: true
                          principals:
                            - metadata:
                                  filter: envoy.filters.http.jwt_authn
                                  path:
                                    - key: jwt_payload
                                    - key: role
                                  value:
                                    string_match:
                                      exact: "loginUser"
                        "ip-whitelist":
                          permissions:
                            - any: true
                          principals:
                            - remote_ip: { address_prefix: 111.111.111.111, prefix_len: 28}
                            - remote_ip: { address_prefix: 111.111.111.112, prefix_len: 28}
```
