### ISSUE TITLE
response_header_to_add - not append to existing header instead create new header

### ISSUE THREAD

**Issue by hbarilan** [envoyproxy/envoy#27907]
Description:
Once Set-Cookie header existing in the response, trying to append a value will create new header with same name instead of appending the value to the existing header.

![image](https://github.com/envoyproxy/envoy/assets/100832412/e5b7e5f3-ee89-4b21-92f1-65d90b2ed422)
![image](https://github.com/envoyproxy/envoy/assets/100832412/ddbbdac3-81a0-471b-94ce-7b56bbfb80d2)

I tried also with append_action: OVERWRITE_IF_EXISTS_OR_ADD - same result. 
please see also thread https://github.com/envoyproxy/envoy/issues/27758 where I was requested to open an issue.

*Repro steps*:
1) Add response_header_to_add to the route
```
response_header_to_add 
   - header:
       key: "set-cookie"
       value: ";HttpOnly; Secure"
```
2) If in the response of the API you have "set-cookie" header, a new header is created instead of append to existing header

**Comment by Haim-Barilan** [comment]
@cpakulski  - FYI

**Comment by cpakulski** [comment]
Starting to work on it!

**Comment by wbpcode** [comment]
I think the weird point is why `OVERWRITE_IF_EXISTS_OR_ADD` didn't works. It should work. 🤔

**Comment by wbpcode** [comment]
Could you provide a complete example yaml with `OVERWRITE_IF_EXISTS_OR_ADD` then we can try to reproduce it in the local env?

**Comment by hbarilan** [comment]
@wbpcode  & @cpakulski ,
Thanks for investigating this issue.
It looks like when I tested it with `OVERWRITE_IF_EXISTS_OR_ADD` the updated yaml was not copied to the server for some reason.
I am sorry for the misunderstanding.

I can confirm that after testing it again when created example yaml it is working as expected using this example.

```
static_resources:
  listeners:
    - name: listener_https
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                http_protocol_options:
                  header_key_format:
                    stateful_formatter:
                      name: preserve_case
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
                upgrade_configs:
                  - upgrade_type: websocket
                access_log:
                  name: envoy.access_loggers
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                    path: /dev/stdout
                route_config:
                  name: search_route
                  response_headers_to_add:
                    - header:
                        key: Content-Security-Policy
                        value: frame-ancestors 'self';
                    - header:
                        key: Strict-Transport-Security
                        value: max-age=31536000
      
                  virtual_hosts: 
                    - name: n-service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: /
                            case_sensitive: false
                          route:
                            cluster: test-service
                          response_headers_to_add:
                            - header:
                                key: "set-cookie"
                                value: "%RESP(set-cookie)%;HttpOnly;Secure"
                              append_action: OVERWRITE_IF_EXISTS_OR_ADD
                http_filters:
                  - name: envoy.filters.http.cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors               
                  - name: envoy.filters.http.stateful_session
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
                      session_state:
                        name: envoy.http.stateful_session.cookie
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.http.stateful_session.cookie.v3.CookieBasedSessionState
                          cookie:
                            name: session-cookie
                            path: /
                            ttl: 300s 
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: test-service
      connect_timeout: 120s
      type: logical_dns
      load_assignment:
        cluster_name: test-service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: #some ip
                      port_value: #some port
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

```
