### ISSUE TITLE
Envoy extension path matcher and path rewrite

### ISSUE THREAD

**Issue by cleveritcz** [envoyproxy/envoy#27905]
Hello,
I am trying to get work envoy proxy which should to be match path and then rewrite it and call upstream host in cluster.

Unfortunately, I can't get trough envoy. I get connected to envoy but after that I am getting 503. I am using envoy version 1.26.2 in docker.

```
 curl -v http://envoy:9000/asd-carContexts/vin/VF36J
* Uses proxy env variable no_proxy == 'envoy'
*   Trying 172.17.0.3:9000...
* Connected to envoy (172.17.0.3) port 9000 (#0)
> GET /asd-carContexts/vin/VF36JUHZJ21587242 HTTP/1.1
> Host: envoy:9000
> User-Agent: curl/8.1.2
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< content-length: 91
< content-type: text/plain
< date: Sat, 10 Jun 2023 10:26:13 GMT
< server: envoy
<
* Connection #0 to host envoy left intact
upstream connect error or disconnect/reset before headers. reset reason: connection failure
```

Here is the response from envoy log:

```
{
    "upstream_transport_failure_reason": null,
    "duration": 20543,
    "connection_termination_details": null,
    "downstream_remote_address": "172.17.0.5:36020",
    "upstream_remote_address": "34.241.162.166:443",
    "response_duration": null,
    "upstream_request_attempt_count": 1,
    "timestamp": "2023-06-10T10:25:52.832Z",
    "grpc_status": "Unavailable",
    "user_agent": "curl/8.1.2",
    "downstream_handshake_duration": null,
    "protocol": "HTTP/1.1",
    "downstream_transport_failure_reason": null,
    "upstream_local_address": null,
    "request_duration": 0,
    "request_tx_duration": null,
    "upstream_host": "34.241.162.166:443",
    "response_code_details": "upstream_reset_before_response_started{connection_failure}",
    "response_flags": "UF,URX",
    "response_tx_duration": null,
    "response_code": 503,
    "path": "/asd-carContexts/vin/VF36J",
    "upstream_protocol": null,
    "route_name": null,
    "virtual_cluster_name": null,
    "upstream_cluster": "asd-carContexts/vin/{param1}",
    "connection_id": 2,
    "stream_id": "a47a6b19-021b-406a-9719-722eb4ca36e8"
}
```

Here is the code:

```
static_resources:
  listeners:
  - name: envoy_listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 9000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          common_http_protocol_options:
            idle_timeout: 0s
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                json_format:
                  "timestamp": "%START_TIME%"
                  "protocol": "%PROTOCOL%"
                  "duration": "%DURATION%"
                  "response_code": "%RESPONSE_CODE%"
                  "user_agent": "%REQ(USER-AGENT)%"
          route_config:
            name: routes
            virtual_hosts:
            - name: 1po
              domains:
              - "*"
              routes:
              - match:
                  path_match_policy:
                    name: envoy.path.match.uri_template.uri_template_matcher
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
                      path_template: "/hobby"
                route:
                  path_rewrite_policy:
                    name: envoy.path.rewrite.uri_template.uri_template_rewriter
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.path.rewrite.uri_template.v3.UriTemplateRewriteConfig
                      path_template_rewrite: "/translate"
                  cluster: "aia-recommendations"
                  retry_policy:
                    retry_on: "5xx"
                    num_retries: 0
              - match:
                  path_match_policy:
                    name: envoy.path.match.uri_template.uri_template_matcher
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
                      path_template: "/test"
                route:
                  path_rewrite_policy:
                    name: envoy.path.rewrite.uri_template.uri_template_rewriter
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.path.rewrite.uri_template.v3.UriTemplateRewriteConfig
                      path_template_rewrite: "/imghp"
                  cluster: "asd-contents/accessCookies"
                  retry_policy:
                    retry_on: "5xx"
                    num_retries: 0
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: aia-recommendations
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
        common_http_protocol_options:
          idle_timeout: 600s
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 100
    connect_timeout: 5.0s
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 1024
        - priority: DEFAULT
          max_pending_requests: 1024
        - priority: DEFAULT
          max_requests: 1024
        - priority: DEFAULT
          max_retries: 0
    type: STRICT_DNS
    dns_refresh_rate: 3600s
    load_assignment:
      cluster_name: aia-recommendations
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: google.com
                port_value: 443
  - name: asd-contents/accessCookies
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
        common_http_protocol_options:
          idle_timeout: 600s
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 100
    connect_timeout: 5.0s
    circuit_breakers:
      thresholds:
        - priority: DEFAULT
          max_connections: 1024
        - priority: DEFAULT
          max_pending_requests: 1024
        - priority: DEFAULT
          max_requests: 1024
        - priority: DEFAULT
          max_retries: 0
    type: STRICT_DNS
    dns_refresh_rate: 3600s
    load_assignment:
      cluster_name: asd-contents/accessCookies
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: google.com
                port_value: 443
admin:
  access_log:
  - name: envoy.access_loggers.stdout
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9045
```

Could you help me, please?
