### ISSUE TITLE
DNS Resolver Option no_default_search_domain Not Working

### ISSUE THREAD

**Issue by brodmerkle** [envoyproxy/envoy#27911]
Our Envoy configuration will at times included a moderate number of non-existent DNS names. Since we generate our configuration to always utilize fully qualified DNS names, we want to minimize hits to our DNS servers by avoiding needless us of the OS-level default search domain(s) specified in /etc/resolv.conf. Per the Envoy  We're attempting to use a typed_dns_resolver_config directly in our bootstrap configuration to disable default search domains:
```
typed_dns_resolver_config:
  name: envoy.network.dns_resolver.cares
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
    resolvers:
    dns_resolver_options:
      no_default_search_domain: true
      use_tcp_for_dns_lookups: false
```
Per https://www.envoyproxy.io/docs/envoy/v1.26.2/api-v3/config/core/v3/resolver.proto#envoy-v3-api-msg-config-core-v3-dnsresolveroptions (referenced in https://www.envoyproxy.io/docs/envoy/v1.26.2/api-v3/extensions/network/dns_resolver/cares/v3/cares_dns_resolver.proto#envoy-v3-api-msg-extensions-network-dns-resolver-cares-v3-caresdnsresolverconfig), this sounds like it should work, but alas when running this configuration on Envoy 1.26.2 we still see extra DNS queries corresponding to the /etc/resolv.conf search entries.

Here's a minimal self-contained config.yaml that demonstrates the problem:
```
node:
  cluster: envoy
  id: envoy-worker
typed_dns_resolver_config:
  name: envoy.network.dns_resolver.cares
  typed_config:
    '@type': type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
    resolvers:
    dns_resolver_options:
      no_default_search_domain: true
      use_tcp_for_dns_lookups: false
static_resources:
  clusters:
  -   name: test
      type: STRICT_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: test
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: fake123.fmr.com
                  port_value: 443
  listeners:
  - name: listener-8443
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8443
    filter_chains:
    - filters:
      - name: httpfilter
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          stat_prefix: http
          route_config:
            name: local-routes
            virtual_hosts:
            - domains:
              - '*'
              name: http
              routes:
              - match:
                 prefix: /
                route:
                 cluster: test
```
On startup on a host where /etc/resolve.conf includes a "search fmr.com fmr2.com" line, a tcpdump on port 53 shows 3 distinct queries (I've generalized the hostname running Envoy to myhost and the DNS server name to mydns):
```
11:52:05.434275 IP myhost.fmr.com.37725 > mydns.fmr.com.domain: 21627+ A? fake123.fmr.com. (33)
11:52:05.434666 IP mydns.fmr.com.domain > myhost.fmr.com.37725: 21627 NXDomain* 0/1/0 (104)
11:52:05.434900 IP myhost.fmr.com.37725 > mydns.fmr.com.domain: 64318+ A? fake123.fmr.com.fmr.com. (41)
11:52:05.435139 IP mydns.fmr.com.domain > myhost.fmr.com.37725: 64318 NXDomain* 0/1/0 (119)
11:52:05.435269 IP myhost.fmr.com.37725 > mydns.fmr.com.domain: 34208+ A? fake123.fmr.com.fmr2.com. (42)
11:52:05.435663 IP mydns.fmr.com.domain > myhost.fmr.com.37725: 34208 NXDomain 0/1/0 (136)
```
What's especially puzzling is that the problem is very specific to the search domain functionality - if I set use_tcp_for_dns_lookups to true I indeed see TCP connections being used for DNS queries.

I tried the same test using the latest Envoy 1.25, 1.24, and 1.23 versions and got the same result. I even tried changing to the older dns_resolution_config syntax to test on Envoy 1.19 and 1.20:
```
dns_resolution_config:
  resolvers:
    - socket_address:
          address: 1.2.3.4
          port_value: 53
  dns_resolver_options:
    no_default_search_domain: true
    use_tcp_for_dns_lookups: false
```
I could see DNS queries flow to the 1.2.3.4 (obviously not the real IP) DNS server as expected, but again I saw queries for each search domain suffix.

In Envoy itself the no_default_search_domain flag looks like it should cause Envoy to pass ARES_FLAG_NOSEARCH to c-ares (which Envoy logs are confirming is the DNS resolver we're running) - https://github.com/envoyproxy/envoy/blob/v1.26.2/source/extensions/network/dns_resolver/cares/dns_impl.cc#L86. There's even a test to confirm that this occurs - https://github.com/envoyproxy/envoy/blob/v1.26.2/test/extensions/network/dns_resolver/cares/dns_impl_test.cc#L1930.

I've reproduced this on an Ubuntu 20.04 VM directly on the VM - at first we hit the issue when running in a container, but removing Docker/containerd from the flow made no difference in the behavior.

Am I missing something obvious here - or is this either an Envoy or c-ares bug?
