### ISSUE TITLE
Add Route Match to match a URL with a query parameter

### ISSUE THREAD

**Issue by BLasan** [envoyproxy/envoy#27939]
*Description*:
Trying to add a route for the path `/api/foo` with a query parameter `foo:bar`. Tried multiple ways of implementing this, but none worked for me.

 ```
             routes:
              - match:
                  prefix: "/hello"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
              - match:
                  path: "/api/foo"
                  query_parameters:
                    - name: query
                      string_match:
                        exact: "true"
                route:
                    cluster: "service_envoyproxy_io"
                    prefix_rewrite: "/api/foo/bar?query=true"
                    auto_host_rewrite: true
```
 

[optional *Relevant Links*:]
- [envoy doc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-regex-rewrite)

Envoy version - `1.26.2`

Is there a standard way to implement this?

Thanks
