### ISSUE TITLE
whether the max_request_bytes option is available for limiting HTTP/2 request body size?

### ISSUE THREAD

**Issue by sssyyss** [envoyproxy/envoy#27938]
I want to use envoyfilter to limit the size of the http request body, the following is my configuration, but it only takes effect for http1.1, not for http2. I want to ask if envoy's max_request_bytes configuration is only effective for http2, or is there something wrong with my configuration
------
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: size-limit
  namespace: istio-external
spec:
  workloadSelector:
    labels:
      istio: external
      app: external
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.buffer
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
            maxRequestBytes: 50000000
```
------
