### ISSUE TITLE
Envoy is not setting content-length header for request/response headers

### ISSUE THREAD

**Issue by shibin-aot** [envoyproxy/envoy#27968]
***Envoy is not setting content-length header for response headers***

When i moved from Envoy 1.19 to 1.25 my code is crashing due to content length was not calculated correctly. The code is relying on the request and response content length to send request.
I am using envoy filter ext_proc to capture the original request / response.

I am using Istio 1.17 and sending a request without content-length header is going through as the envoy is calculating header correctly. But, while receiving the response the content-length header is missing and i had to add extra line of code to capture length from Body data.

If i am not passing content-length header in request / response my understanding is that Envoy compute the content-length header and append with request / response.

**Comment by KBaichoo** [comment]
Can you provide some example concrete logs of this? e.g. this could vary depending on the protocol, whether transfer encoding, etc. In some of those cases content-length isn't a required header.

**Comment by shibin-aot** [comment]
``I use ExternalProcessor filter and The ext_proc is running on go server accepting GRPC streams. No transfer encoding is set. The configuration mentioned below for the reference.

```
configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_FIRST
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            failure_mode_allow: true
            message_timeout: 1s
            processing_mode:
              request_header_mode: "SEND"
              response_header_mode: "SEND"
              request_body_mode: "BUFFERED"
              response_body_mode: "BUFFERED"
              request_trailer_mode: "SKIP"
              response_trailer_mode: "SKIP"
            grpc_service:
              timeout: 1s
              envoy_grpc:
                cluster_name: "outbound|5001||xxx.svc.cluster.local"
                authority: xxx.svc.cluster.local
    - applyTo: NETWORK_FILTER # http connection manager is a filter in Envoy
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
```
