### ISSUE TITLE
ERROR - UDP Proxy - "use_per_packet_load_balancing"

### ISSUE THREAD

**Issue by AravindhStanley** [envoyproxy/envoy#27973]
**UDP Proxy - "use_per_packet_load_balancing" usage.**
**Envoy Document** - https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/udp/udp_proxy/v3/udp_proxy.proto#envoy-v3-api-msg-extensions-filters-udp-udp-proxy-v3-udpproxyconfig

**Description: **
I tried to add this paramter in my static envoy config with v3 API, but the startup crashes with the following error.

```
[2023-06-15 10:02:31.842][209839][info][main] [external/envoy/source/server/server.cc:334]   envoy.tracers: envoy.dynamic.ot, envoy.lightstep, envoy.tracers.datadog, envoy.tracers.dynamic_ot, envoy.tracers.lightstep, envoy.tracers.opencensus, envoy.tracers.skywalking, envoy.tracers.xray, envoy.tracers.zipkin, envoy.zipkin
[2023-06-15 10:02:31.852][209839][critical][main] [external/envoy/source/server/server.cc:113] error initializing configuration '/etc/envoy/envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT:use_per_packet_load_balancing: Cannot find field.) has unknown fields
```

**Envoy Listener**

```
 - name: filebeat_storage
      reuse_port: true
      address:
        socket_address:
          protocol: UDP
          address: <IPADDRESS>
          port_value: 514
      udp_listener_config:
        downstream_socket_config:
          max_rx_datagram_size: 9000
      listener_filters:
      - name: envoy.filters.udp_listener.udp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
          stat_prefix: filebeat_storage
          cluster: filebeat_storage
          use_original_src_ip: true
          use_per_packet_load_balancing: true
          upstream_socket_config:
            max_rx_datagram_size: 9000

```
