### ISSUE TITLE
Envoy Health Check: Both Failure and Success Counters Increased At The Same Time

### ISSUE THREAD

**Issue by Winbobob** [envoyproxy/envoy#28050]
*Title*: Envoy Health Check: Both Failure and Success Counters Increased At The Same Time

*Description*:
When we use Envoy TCP health check feature to check a ZooKeeper cluster, we noticed that both `health_check.network_failure` and `health_check.success` counters increased at the same time.

After checking the tcpdump outputs, we found that ZooKeeper cluster did send back the expected response back to Envoy and the ZooKeeper cluster also sent FIN immediately after that. We think that could be the reason why both failure and success counter increased at the same time.

Our solution is to set the `reuse_connection` to false.

Question: would it be better to only increase the failure counter under this situation to make it less confusing? 

*Admin and Stats Output Example*:

```
cluster.name.health_check.attempt: 15600
cluster.name.health_check.failure: 15600
cluster.name.health_check.healthy: 0
cluster.name.health_check.network_failure: 15600
cluster.name.health_check.passive_failure: 0
cluster.name.health_check.success: 15596
cluster.name.health_check.verify_cluster: 0
```

*Config Example*:

```
healthy_threshold: 2
unhealthy_threshold: 2
interval: 5s
timeout: 1s
tcp_health_check:
    send:
        text: 72756F6B # ruok
    receive:
        - text: 696D6F6B # imok
```
