### ISSUE TITLE
how to manipulate tracing spans in lua handlers?

### ISSUE THREAD

**Issue by rafaeljesus** [envoyproxy/envoy#28126]
**Title** how to manipulate tracing spans in lua handlers?

**Description**

I would like to be able to manipulate tracing spans directly from lua scripts, for example:
```lua
function envoy_on_response(response_handle)
  local mark_span_err = response_handle:headers():get("SET_ENVOY_SPAN_TAG_ERROR")
  -- add a tag to the active span indicating an error occurred during `/_bulk` insert
  if mark_span_err ~= nil and mark_span_err == "true"
   response_handle:tracing():setTag("error", "true")
end
```

I have a service that serves a `/_bulk` endpoint, it returns 2xx status code and the errors are set in the response body as `errors=true` with an error message on each failed item when that happens, I want to set the active span of the request in envoy as `error=true`,

**Comment by zuercher** [comment]
@wbpcode might be able to provide a more detailed answer, but I think you should be able to [set metadata](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/lua_filter.html#dynamic-metadata-object-api) using the LUA filter and then include the metadata in the span using [custom tags](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-tracing-custom-tags).

**Comment by rafaeljesus** [comment]
@zuercher thanks for the quick response!

I've incorporated your suggestion to use dynamic metadata in the lua filter, and defined custom tags in the `HttpConnectionManager` to pull these values into the span,

here's the updated Lua filter and `HttpConnectionManager`:

The lua filter:
```yaml
name: envoy.filters.http.lua
typed_config:
  '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
  default_source_code:
    inline_string: |
      function envoy_on_response(response_handle)
        local bulk_errors = response_handle:headers():get("OVERRIDE_ENVOY_SPAN_TAG_ERROR")
        if bulk_errors == nil then
          return
        end

        response_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "error", "true")
        response_handle:headers():remove("OVERRIDE_ENVOY_SPAN_TAG_ERROR")

        local status_code = response_handle:headers():get("OVERRIDE_ENVOY_SPAN_TAG_STATUS_CODE")
        if status_code == nil then
          return
        end
        response_handle:streamInfo():dynamicMetadata():set("envoy.filters.http.lua", "http.status_code", status_code)
        response_handle:headers():remove("OVERRIDE_ENVOY_SPAN_TAG_STATUS_CODE")
      end
```
The `envoy.http_connection_manager`:

```yaml
filter_chains:
  - filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          tracing:
            provider:
              name: envoy.tracers.opentelemetry
              typed_config:
                '@type': type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                grpc_service: ...
                service_name: envoy
            custom_tags:
              - tag: error
                metadata:
                  kind: REQUEST
                  metadata_key:
                    key: envoy.filters.http.lua.error
                    path: []
              - tag: http.status_code
                metadata:
                  kind: REQUEST
                  metadata_key:
                    key: envoy.filters.http.lua.http.status_code
                    path: []
```

One concern that I have is that it is not clear to me if the `error` and `http.status_code` tags set by the Lua filter will correctly override the envoy's default behavior, my expectation is that if these tags are set by the lua filter, they should override what Envoy would normally set, however, if these tags are not set by the lua filter, I expect envoy to continue its normal behavior,

I would appreciate if anyone could clarify this piece, thanks for your help!
