### ISSUE TITLE
Local reply modification body substitution

### ISSUE THREAD

**Issue by pchaseh** [envoyproxy/envoy#28207]
*Title*: *Local reply modification body substitution*

*Description*:
As it currently stands, one can use local reply format modification to do something such as the following:
```
mappers:
- filter:
    status_code_filter:
      comparison:
        op: EQ
        value:
          default_value: 400
          runtime_key: key_b
  status_code: 401
  body:
    inline_string: "not allowed"
body_format:
  text_format: "%LOCAL_REPLY_BODY% %CEL(request.id)%"
```
While this works for simple use cases, I would like to be able to treat `%LOCAL_REPLY_BODY%` as a template, meaning that if `body` looks like the following:
```
  body:
    inline_string: "not allowed! request id: %CEL(request.id)%"
```
`%CEL(request.id)%` should be replaced with the request ID, however no substitution can currently happen on `%LOCAL_REPLY%` from within `body_format`.
To circumvent this, I would need to have something along the lines of:
```
mappers:
- filter:
    status_code_filter:
      comparison:
        op: EQ
        value:
          default_value: 400
          runtime_key: key_b
  status_code: 401
  body:
    inline_string: "not allowed! request id:"
body_format:
  text_format: "%LOCAL_REPLY_BODY% %CEL(request.id)%"
```
However, this is also not a very viable solution since the response body needs to be split between `body` and `body_format`, with the separator being where the variable is to be inserted, and will also not work for multiple attributes. I have also tried putting the entire contents of my local reply in `body_format`, however Envoy will fail to load the configuration depending on what the content of the local reply is. Is there any currently supported way to go about this?
