### ISSUE TITLE
Rate Limiting Configuration Not Working

### ISSUE THREAD

**Issue by fenngwd** [envoyproxy/envoy#2820]
I have set a envoy as front proxy in my k8s cluster. I'm trying to set rate limiting, but it's not working. I can not find a example which enable rate limiting. I have deployed a rate-limit service, but no traffic sent to it.

Could you help me to figure this out?

Configuration:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: qwer-envoyconf
  namespace: ingress
data:
  envoy.yaml: |
    static_resources:
      clusters:
      - name: zipkin
        connect_timeout: 0.25s
        type: strict_dns
        hosts:
        - socket_address:
            address: zipkin.guardian
            port_value: 9411
      - name: ratelimit
        connect_timeout: 0.25s
        type: strict_dns
        hosts:
        - socket_address:
            address: candy.ingress
            port_value: 8081
    dynamic_resources:
      lds_config:
        path: /etc/qwer/xds/lds.yaml
      cds_config:
        path: /etc/qwer/xds/cds.yaml
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 15000
    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: zipkin
          collector_endpoint: "/api/v1/spans"
    rate_limit_service:
      cluster_name: ratelimit
```
```yaml
    version_info: "0"
    resources:
    - "@type": type.googleapis.com/envoy.api.v2.Listener
      name: l7bk
      address:
        socket_address:
          address: "0.0.0.0"
          port_value: 1080
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            server_name: qwer
            codec_type: AUTO
            stat_prefix: l7bk
            use_remote_address: false
            generate_request_id: false
            tracing: {}
            access_log:
            - name: envoy.file_access_log
              config:
                path: /var/log/access.log
            http_filters:
            - name: envoy.cors
              config: {}
            - name: envoy.router
              config: {}
            - name: envoy.rate_limit
              config:
                domain: edge_proxy_per_ip
                stage: 0
            rds:
              route_config_name: qwer
              config_source:
                path: /etc/shentu/xds/rds.yaml
```
```yaml
   virtual_hosts:
      - name: api
        domains:
        - "****" // Ignoring this
        require_tls: ALL
        cors:
          allow_origin:
          - "*"
          allow_methods: GET, PUT, DELETE, POST, OPTIONS
          allow_headers: DNT,X-Csrftoken,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
          max_age: "1728000"
          allow_credentials: true
          enabled: true
        rate_limits:
          - actions: 
              - remote_address: {}
```

Please ignore these indentation.
Thanks!
