### ISSUE TITLE
Circuit breakers - limit concurrent users per cluster? 

### ISSUE THREAD

**Issue by hbarilan** [envoyproxy/envoy#28218]
Hi,

I wish to limit maximum concurrent users per cluster.
For example, I wish only 5 users will have access to cluster, other new users requests will be rejected.

My app has multiple HTTP requests for static assets along with several WebSocket open connections.

3 questions:
1) Should I use max_connections  or max_connection_pools ?
2) What response will a user get if he tries to access, and he is over the limit?
3) In Stats page should I look for `cluster.backendservice.upstream_cx_active` or `cluster.backendservice.upstream_cx_total`?

Config example:
```
 clusters:
    - name: backendservicecluster
      connect_timeout: 0.25s
      type: STRICT_DNS 
      lb_policy: ROUND_ROBIN 
      load_assignment:
        cluster_name: backendservicecluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: backendservice 
                  port_value: 8080
      # https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto#envoy-v3-api-msg-config-cluster-v3-circuitbreakers
      circuit_breakers:
        thresholds:
          - max_retries: 0 
            max_connections: 5?
            max_connection_pools: 5?
            max_pending_requests: 0
            track_remaining: true
```
