### ISSUE TITLE
Does Envoy proxy accept client hello with TLS Record Layer version 1.0?

### ISSUE THREAD

**Issue by nadeshpa** [envoyproxy/envoy#28289]
I am trying to use Envoy as an HTTP(S) dynamic forward proxy. I don't want to terminate the TLS connection in Envoy. From Wireshark capture I see my client is receiving HTTP 400 to a request, by just eyeballing the capture I see this is the client hello with TLS Record Layer Version 1.0 (in snapshot below). 

Does Envoy accept this request, is this the reason for HTTP 400? I read that Envoy does not support the TLS version 1.1 below, but this is a version in Record Layer.
Appreciate any feedback/ recommendations.

![image](https://github.com/envoyproxy/envoy/assets/57644746/4bc963c8-3dd9-4dc0-8640-5ac2588ee383)

Following is my envoy config

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                use_remote_address: true
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            connect_matcher: {}
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config: {}
                              - upgrade_type: websocket
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http_protocol_options:
                  accept_http_10: true
  clusters:
    - name: dynamic_forward_proxy_cluster
      connect_timeout: 360s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          allow_insecure_cluster_options: true
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
```

            
---

Following are the logs from Envoy Proxy
        
        
 [2023-07-07 20:01:23.756][13][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:155] [C22] new connection from 10.224.0.4:56057
[2023-07-07 20:01:23.756][13][trace][connection] [source/common/network/connection_impl.cc:568] [C22] socket event: 2
[2023-07-07 20:01:23.756][13][trace][connection] [source/common/network/connection_impl.cc:679] [C22] write ready
[2023-07-07 20:01:24.709][20][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3469ff13f600 for 3600000ms, min is 3600000ms
[2023-07-07 20:01:24.709][20][trace][connection] [source/common/network/connection_impl.cc:423] [C23] raising connection event 2
[2023-07-07 20:01:24.709][20][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:155] [C23] new connection from 10.224.0.6:40899
[2023-07-07 20:01:24.709][20][trace][connection] [source/common/network/connection_impl.cc:568] [C23] socket event: 2
[2023-07-07 20:01:24.709][20][trace][connection] [source/common/network/connection_impl.cc:679] [C23] write ready
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/connection_impl.cc:568] [C23] socket event: 3
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/connection_impl.cc:679] [C23] write ready
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/connection_impl.cc:608] [C23] read ready. dispatch_buffered_data=0
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/raw_buffer_socket.cc:24] [C23] read returns: 517
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/raw_buffer_socket.cc:38] [C23] read error: Resource temporarily unavailable
[2023-07-07 20:01:24.713][20][trace][http] [source/common/http/http1/codec_impl.cc:639] [C23] parsing 517 bytes
[2023-07-07 20:01:24.713][20][trace][http] [source/common/http/http1/codec_impl.cc:581] [C23] message begin
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:349] [C23] new stream
[2023-07-07 20:01:24.713][20][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3469fee28300 for 300000ms, min is 300000ms
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/filter_manager.cc:996] [C23][S2609131389624112574] Sending local reply with details http1.codec_error
[2023-07-07 20:01:24.713][20][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3469fee28300 for 300000ms, min is 300000ms
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:1615] [C23][S2609131389624112574] closing connection due to connection close header
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:1680] [C23][S2609131389624112574] encoding headers via codec (end_stream=false):
':status', '400'
'content-length', '11'
'content-type', 'text/plain'
'date', 'Fri, 07 Jul 2023 20:01:24 GMT'
'server', 'envoy'
'connection', 'close'

 

[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/connection_impl.cc:483] [C23] writing 145 bytes, end_stream false
[2023-07-07 20:01:24.713][20][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3469fee28300 for 300000ms, min is 300000ms
[2023-07-07 20:01:24.713][20][trace][http] [source/common/http/conn_manager_impl.cc:1690] [C23][S2609131389624112574] encoding data via codec (size=11 end_stream=true)
[2023-07-07 20:01:24.713][20][trace][connection] [source/common/network/connection_impl.cc:483] [C23] writing 11 bytes, end_stream false
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:1772] [C23][S2609131389624112574] Codec completed encoding stream.
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:215] [C23][S2609131389624112574] doEndStream() resetting stream
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:1736] [C23][S2609131389624112574] stream reset: reset reason: local reset, response details: http1.codec_error
[2023-07-07 20:01:24.713][20][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=1)
[2023-07-07 20:01:24.713][20][trace][misc] [source/common/event/scaled_range_timer_manager_impl.cc:60] enableTimer called on 0x3469ff13f600 for 3600000ms, min is 3600000ms
[2023-07-07 20:01:24.713][20][trace][main] [source/common/event/dispatcher_impl.cc:250] item added to deferred deletion list (size=2)
[2023-07-07 20:01:24.713][20][debug][connection] [source/common/network/connection_impl.cc:139] [C23] closing data_to_write=156 type=2
[2023-07-07 20:01:24.713][20][debug][connection] [source/common/network/connection_impl_base.cc:47] [C23] setting delayed close timer with timeout 1000 ms
[2023-07-07 20:01:24.713][20][debug][http] [source/common/http/conn_manager_impl.cc:396] [C23] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD
