### ISSUE TITLE
Golang L4: host selection without HTTP context

### ISSUE THREAD

**Issue by antJack** [envoyproxy/envoy#28300]
motivation:

Currently the golang l4 network filter uses an original dst cluster and `Upstream::LoadBalancerContextBase` (more specifically, an HTTP header map) to tell envoy which upstream host to connect. But it's quite counterintuitive for a l4 extension. 
```yaml
  clusters:
  - name: plainText
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED
    original_dst_lb_config:
      use_http_header: true   // <--
```

This issue requires a better way to do the upstream host selection and should get rid of HTTP header map for golang l4 filter.
