### ISSUE TITLE
Doesn't Round Robin policy distribute requests to upstream endpoints one by one

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#28301]
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9999
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: example_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_example
                  retry_policy:
                    retry_on: "5xx,unavailable,connection-failure"
                    num_retries: 1
                  timeout: 60s
  clusters:
  - name: cluster_example
    connect_timeout: 30s
    type: STATIC
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_example
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.1.0.2
                port_value: 9999
        - endpoint:
            address:
              socket_address:
                address: 172.1.0.1
                port_value: 9999
```
Here is my config of Envoy. I use it to handle my grpc clients and distribute requests of clients to the two endpoints.

I used one client to do testing. It seems that everything works fine. The two servers can process requests and the client can get the responses.

But I just found that the two servers did NOT process the requests one after another. I mean I've thought if the nth request had been sent to the server `172.1.0.1`, the (n+1)th request would be sent to the server `172.1.0.2` definitely. But it doesn't seem that Envoy work like this. I can see that sometimes one server would keep processing requests while the other server is idle.

I don't know why. As my understanding, Round Robin means processing requests one after another. But obviously the case above is not working like this.
