### ISSUE TITLE
SinkPredicates implementation

### ISSUE THREAD

**Issue by calcium6** [envoyproxy/envoy#28308]
We've been using regex to filter statistics but it causes a lot of load to the CPUs so we would like to [implement SinkPredicates](https://envoyproxy.slack.com/archives/C78HA81DH/p1688463504726159).
It should be possible to do this via configuration.

Our current implementation of statistics:
```
stats_config:
  stats_matcher:
    inclusion_list:
      patterns:
      - prefix: server.
      - safe_regex: {regex: "cluster.([^.]*).membership_(healthy|total)$"}
      - safe_regex: {regex: "cluster.([^.]*).health_check.*"}
      - safe_regex: {regex: "cluster.([^.]*).outlier_detection.*ejections_active.*"}
      - safe_regex: {regex: "cluster.([^.]*).upstream_cx_(none_healthy|pool_overflow|connect_fail|destroy_local_with_active_rq|connect_timeout|total)$"}
      - safe_regex: {regex: "cluster.([^.]*).upstream_rq_(pending_overflow|timeout|[1-5][0-9x]{2}|retry)$"}
      - safe_regex: {regex: "cluster.([^.]*).outlier_detection.*ejections.*consecutive.*5xx"}
      - safe_regex: {regex: "cluster.([^.]*).ratelimit.*"}
      - safe_regex: {regex: "http.([^.]*).downstream_cx_(active|rx_bytes_total|total|tx_bytes_total)$"}
      - safe_regex: {regex: "http.([^.]*).downstream_rq_(rx_reset|total|[1-5][0-9x]{2})$"}
      - safe_regex: {regex: "listener.([^.]*).downstream_cx_active$"}
```
