### ISSUE TITLE
 HTTP/1.1 TCP connections are closed without sending a FIN

### ISSUE THREAD

**Issue by river-phillips-cko** [envoyproxy/envoy#28313]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: HTTP/1.1 TCP connections are closed without sending a FIN

*Description*:
We are using an ALB in front of Envoy. We see that the ALB sometimes responds with 502s without receiving a response from Envoy. After running a packet capture on Envoy, we can see that Envoy sends an RST packet to the ALB when the request is made. The ALB then responds to the client with an HTTP 502.

We expected Envoy to close the connection with a TCP 4-way close gracefully. However, that does not appear to be the case.

![image](https://github.com/envoyproxy/envoy/assets/105640644/3ed8d40c-b280-4d3e-8d0b-02d2096f7da2)

*Repro steps*:
> Client -- HTTP/1.1 or H2 --> ALB -- HTTP/1.1 --> Envoy

Make requests to ALB, eventually observe 502s

*Config*:

``` yaml
listeners:
    - address:
        socket_address:
            address: 0.0.0.0
            port_value: "80"
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                common_http_protocol_options:
                    max_connection_duration: 1s
                http_protocol_options:
                        accept_http_10: true
                        default_host_for_http_10: foo.com
                        header_key_format:
                            proper_case_words: {}
                    merge_slashes: true
                    normalize_path: true
                    path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
                    request_timeout: 60s
                    server_header_transformation: PASS_THROUGH
                    stream_error_on_invalid_http_message: true
                    stream_idle_timeout: 120s
                    use_remote_address: true
                    xff_num_trusted_hops: "1"
```

I've included what we believed to be relevant config. Decreasing the `max_connection_duration` to 1s was an attempt to reproduce the issue. It increases the likelihood of this issue occurring, but it still happened at higher values.

*Logs*:
>Include the access logs and the Envoy logs.

There are no access logs for these requests.
