### ISSUE TITLE
Does envoy supports different healthcheck path for each endpoint?

### ISSUE THREAD

**Issue by ningyougang** [envoyproxy/envoy#28375]
Below is my envoyfilter for healthcheck, works well with  `each endpoint has same healthcheck url`
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  generation: 7
  name: test1-health-check-envoy-filter
  namespace: test-namespace
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        portNumber: 80
        service: test1.test-namespace
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        health_checks:
        - always_log_health_check_failures: true
          event_log_path: /dev/stdout
          healthy_threshold: 2
          http_health_check:
            codec_client_type: HTTP1
            expected_statuses:
            - end: 301
              start: 200
            host: test1.test-namespace
            path: /healthcheckPath                 # this path is shared for all endpoints
            retriable_statuses:
            - end: 600
              start: 100
          interval: 5s
          no_traffic_healthy_interval: 5s
          no_traffic_interval: 5s
          timeout: 10s
          unhealthy_threshold: 2
        load_assignment:
          cluster_name: outbound|80||test1.test-namespace
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ${A_ENDPOINT_IP}
                    port_value: 80
                health_check_config:
                  hostname: ${A_ENDPOINT_IP}
                  port_value: 80
            locality:
              cluster: ""
              region: ""
            priority: 2
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ${B_ENDPOINT_IP}
                    port_value: 80
                health_check_config:
                  hostname: ${B_ENDPOINT_IP}
                  port_value: 80
            locality:
              cluster: ""
              region: ""
            priority: 2
  workloadSelector:
    labels:
      istio: istio-ingressgateway-test-namespace
```
Works well, but each endpoint has same healthcheck url.
*  a_endpoint -> http://${A_ENDPOINT_IP}:80/healthcheckPath 
*  b_endpoint  -> http://${B_ENDPOINT_IP}:80/healthcheckPath

I want to `make each endpoint has different healthcheck path`, e.g.
*  a_endpoint  -> http://${A_ENDPOINT_IP}:80/healthcheckPath1 
*  b_endpoint  -> http://${B_ENDPOINT_IP}:80/healthcheckPath2

I checked the envoy configuration, seems not supported
* http_health_check
  https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/health_check.proto#config-core-v3-healthcheck-httphealthcheck
  the `path` is a required parameter, and it is for all endpoints

* Each endpoint's healthcheck configuration
  
   https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/endpoint_components.proto#envoy-v3-api-msg-config-endpoint-v3-endpoint-healthcheckconfig

   There has port_value, but does not have `path` configuration.

My question, does i miss something? does envoy itself support `make cluster's each endpoint has different healthcheck path`?
