### ISSUE TITLE
Unable to parse envoy.yaml for opentelemetry config

### ISSUE THREAD

**Issue by Akshit96-ar** [envoyproxy/envoy#28378]
Getting the error: 

```console
_**error initializing configuration '/etc/envoy/envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(static_resources.clusters[1].typed_extension_protocol_options[1].value): invalid value Missing @type for any field in envoy.config.bootstrap.v3.Bootstrap for type Any): {"layered_runtime":{"layers":[{"static_layer":{"envoy":{"resource_limits":{"listener":{"example_listener_name":{"connection_limit":10000}}}}},"name":"static_layer_0"}]},"static_resources":{"clusters":[{"dns_lookup_family":"V4_ONLY","name":"my_cluster","type":"STRICT_DNS","load_assignment":{"cluster_name":"my_cluster","endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"address":"host.docker.internal","port_value":8085}}}}]}]}},{"type":"STRICT_DNS","name":"opentelemetry_collector","typed_extension_protocol_options":{"envoy.extensions.upstreams.http.v3.HttpProtocolOptions":{"explicit_http_config":{"http2_protocol_options":{}},"@type":"type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"},"load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"address":"host.docker.internal","port_value":4317}}}}]}],"cluster_name":"opentelemetry_collector"}},"lb_policy":"ROUND_ROBIN"}],"listeners":[{"address":{"socket_address":{"port_value":10000,"address":"0.0.0.0"}},"filter_chains":[{"filters":[{"typed_config":{"codec_type":"AUTO","stat_prefix":"ingress_http","http_filters":[{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"generate_request_id":true,"tracing":{"provider":{"typed_config":{"grpc_service":{"envoy_grpc":{"cluster_name":"opentelemetry_collector"},"timeout":"0.250s"},"@type":"type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig","service_name":"front-envoy"},"name":"envoy.tracers.opentelemetry"}},"access_log":[{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog"},"name":"envoy.access_loggers.stdout"}],"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","route_config":{"virtual_hosts":[{"domains":["*"],"routes":[{"route":{"cluster":"my_cluster"},"match":{"prefix":"/serviceA"}},{"route":{"cluster":"my_cluster"},"match":{"prefix":"/serviceB"}}],"name":"backend"}],"name":"local_route"}},"name":"envoy.filters.network.http_connection_manager"}]}]}]},"admin":{"address":{"socket_address":{"address":"0.0.0.0","port_value":9910}}},"stats_sinks":[{"name":"envoy.stat_sinks.statsd","typed_config":{"address":{"socket_address":{"port_value":8092,"address":"10.131.50.226"}},"@type":"type.googleapis.com/envoy.config.metrics.v3.StatsdSink"}}]}**_
```

Here is my envoy.yaml

```
stats_sinks:
  - name: envoy.stat_sinks.statsd
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.StatsdSink
      address:
        socket_address:
          #address: 10.187.53.183
          address: 10.131.50.226
          port_value: 8092
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                generate_request_id: true
                tracing:
                  provider:
                    name: envoy.tracers.opentelemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                      grpc_service:
                        envoy_grpc:
                          cluster_name: opentelemetry_collector
                        timeout: 0.250s
                      service_name: front-envoy
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/serviceA"
                          route:
                            #prefix_rewrite: "/hello"
                            cluster: my_cluster
                        #- match:
                        #    prefix: "/b"
                        #  route:
                        #    prefix_rewrite: "/bye"
                        #   cluster: my_cluster
                        - match:
                            prefix: "/serviceB"
                          route:
                            #prefix_rewrite: "/hello"
                            cluster: my_cluster
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: my_cluster
    type: STRICT_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: my_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    #address: 10.187.53.183
                    #address: 10.131.50.226
                    address: host.docker.internal
                    port_value: 8085


  - name: opentelemetry_collector
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
      load_assignment:
        cluster_name: opentelemetry_collector
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: host.docker.internal
                      port_value: 4317

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9910
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              example_listener_name:
                connection_limit: 10000
```
I want to enable trace for the my application, i have taken the reference from the example of opentelemetry. Could anyone help here what am i doing wrong?
