### ISSUE TITLE
Ingress gateway fails to start when using "extensions.filters.http.oauth2.v3.OAuth2"

### ISSUE THREAD

**Issue by marcantoine-bibeau** [envoyproxy/envoy#28392]
*Title*: Ingress gateway fails to start when using "extensions.filters.http.oauth2.v3.OAuth2"

*Description*:
ingress-gateway is failing to start when using "type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2" EnvoyFilter

*Repro steps*:
Add following EnvoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: oauth2-auth
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
      type: public-secure
  priority: 10
  configPatches:
    - applyTo: CLUSTER
      match:
        cluster:
          service: oauth
      patch:
        operation: ADD
        value:
          name: oauth
          connect_timeout: 5s
          type: LOGICAL_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: oauth
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: obfuscated.okta.com
                          port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: sonder-fed.okta.com
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.jwt_authn"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.oauth2
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2"
            config:
              token_endpoint:
                cluster: oauth
                uri: "https://obfuscated.okta.com/oauth2/default/v1/token"
                timeout: 5s
              authorization_endpoint: "https://obfuscated.okta.com/oauth2/default/v1/authorize"
              redirect_uri: "https://%REQ(:authority)%/_oauth2_callback"
              redirect_path_matcher:
                path:
                  exact: /_oauth2_callback
              signout_path:
                path:
                  exact: /signout
              forward_bearer_token: true
              auth_scopes:
                - openid
                - profile
              credentials:
                client_id: {{ .Values.oktaClientId }}
                token_secret:
                  name: token
                  sds_config:
                    path: "/etc/istio/config/oauth2-token-secret.yaml"
                hmac_secret:
                  name: hmac
                  sds_config:
                    path: "/etc/istio/config/oauth2-hmac-secret.yaml"
              pass_through_matcher:
              - name: x-sndr-oauth2-original-auth
                present_match: true
```
                
*Config*:
see above
Using Istio 1.18.0 underlying Envoy version

*Logs*:
{"level":"warning","time":"2023-07-13T20:40:16.778355Z","scope":"envoy config","msg":"gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 0.0.0.0_8443: Didn't find a registered config subscription factory implementation for name: 'envoy.config_subscription.filesystem'\n","caller":"external/envoy/source/common/config/grpc_subscription_impl.cc:128","thread":14}

>**Note**: 
Seems to be related to commit https://github.com/envoyproxy/envoy/pull/26521
