### ISSUE TITLE
RouteConfiguration rejected when `weighted_clusters` route action is combined with `typed_per_filter_config/envoy.filters.http.local_ratelimit`

### ISSUE THREAD

**Issue by v1b1** [envoyproxy/envoy#28426]
*Title*: *RouteConfiguration rejected when `weighted_clusters` route action is combined with `typed_per_filter_config/envoy.filters.http.local_ratelimit`*

*Description*:
Envoy v1.26.2 rejects a `RouteConfiguration` received via gRPC when an individual `Route` is configured similar to the following:
```
match:
  prefix: /some/path
  headers:
    - name: x-customer-key
      string_match:
        exact: specific-value
route:
  weighted_clusters:
    clusters:
      - name: passive
        weight: 0
      - name: active
        weight: 100
  timeout: 60s
typed_per_filter_config:
  envoy.filters.http.local_ratelimit:
    stat_prefix: public_limiter_specific-value
    token_bucket:
      max_tokens: 1
      tokens_per_fill: 1
      fill_interval: 120s
    filter_enabled:
      default_value:
        numerator: 100
      runtime_key: local_rate_limit_enabled
    filter_enforced:
      default_value:
        numerator: 100
      runtime_key: local_rate_limit_enforced
    enable_x_ratelimit_headers: true
    '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
```

Envoy rejects the above route with the following log message:

```
gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Didn't find a registered implementation for 'envoy.filters.http.local_ratelimit' with type URL: ''
```

However if the route is changed to the following:

```
match:
  prefix: /some/path
  headers:
    - name: x-customer-key
      string_match:
        exact: specific-value
route:
  cluster: active
  timeout: 60s
typed_per_filter_config:
  envoy.filters.http.local_ratelimit:
    stat_prefix: public_limiter_specific-value
    token_bucket:
      max_tokens: 1
      tokens_per_fill: 1
      fill_interval: 120s
    filter_enabled:
      default_value:
        numerator: 100
      runtime_key: local_rate_limit_enabled
    filter_enforced:
      default_value:
        numerator: 100
      runtime_key: local_rate_limit_enforced
    enable_x_ratelimit_headers: true
    '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
```

Then Envoy accepts the configuration without issue.

*Admin and Stats Output*:

/server_info
```
{
 "version": "4aa28dcbfdaf17b754ee6d4ca4f1fdf6f84c99dc/1.26.2/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "hot_restart_version": "11.104",
 "command_line_options": {
  "base_id": "0",
  "use_dynamic_base_id": false,
  "base_id_path": "",
  "concurrency": 12,
  "config_path": "/etc/envoy/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_static_fields": false,
  "reject_unknown_dynamic_fields": false,
  "ignore_unknown_dynamic_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] [%g:%#] %v",
  "log_format_escaped": false,
  "log_path": "",
  "service_cluster": "",
  "service_node": "",
  "service_zone": "",
  "drain_strategy": "Gradual",
  "mode": "Serve",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "disabled_extensions": [],
  "enable_fine_grain_logging": false,
  "socket_path": "@envoy_domain_socket",
  "socket_mode": 0,
  "enable_core_dump": false,
  "stats_tag": [],
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "node": {
  "id": "host-1",
  "cluster": "app",
  "dynamic_parameters": {},
  "user_agent_name": "envoy",
  "user_agent_build_version": {
   "version": {
    "major_number": 1,
    "minor_number": 26,
    "patch": 2
   },
   "metadata": {
    "revision.sha": "4aa28dcbfdaf17b754ee6d4ca4f1fdf6f84c99dc",
    "ssl.version": "BoringSSL",
    "build.type": "RELEASE",
    "revision.status": "Clean"
   }
  },
  "extensions": [
...
```

*Config*:
>Include the config used to configure Envoy.

*Logs*:
```
[2023-07-16 20:19:55.374][1][warning][config] [source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Didn't find a registered implementation for 'envoy.filters.http.local_ratelimit' with type URL: ''
```
