### ISSUE TITLE
How does remote_jwks work with pure ip uri

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#28427]
I just read the doc of jwt and I have known how to configure a remote jwks. Here is my config:
```
...
providers:
  provider_name1:
    issuer: xxx
    audiences:
    - yyy
    remote_jwks:
      http_uri:
        uri: https://192.168.1.10:6668/jwks.json
        cluster: example_jwks_cluster
clusters:
  - name: example_jwks_cluster
    type: STATIC
    load_assignment:
      cluster_name: example_jwks_cluster
      endpoints:
      - endpoint: {address: {socket_address: {address: 192.168.1.10, port_value: 6668}}}
####      - endpoint: {address: {socket_address: {address: 192.168.1.11, port_value: 6668}}}
```
It works as expected without any error.

Now I want to add another endpoint for the `example_jwks_cluster`.

So I simply added a new line: `- endpoint: {address: {socket_address: {address: 192.168.1.11, port_value: 6668}}}` (the commented line).

Now I have two endpoints, both of them provided the same jwks API.

However, in the config `remote_jwks`, there is `uri: https://192.168.1.10/jwks.json`.

I'm confused now. I added another new endpoint to load-balance the jwks requests. But the uri is still `192.168.1.10:6668`...
