### ISSUE TITLE
Can't start envoy when the cluster endpoint>socket_address>port_value is a 5 digit number

### ISSUE THREAD

**Issue by najaarv** [envoyproxy/envoy#28537]
Here's an example container configuration:
```
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: Cluster_service_1
    connect_timeout: 25s
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: Cluster_1
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 10.10.1.100
                    port_value: 50051
```
I have a few other clusters as well as part of the envoy.yaml configuration that have a 4 digit port number. But, when I include this entry, the envoy process just wouldn't start. Is there any reason for this? It's a valid port number and a functioning grpc-server that I'm able to connect to from other sources.
