### ISSUE TITLE
How to redirect request using prefix other than "/".

### ISSUE THREAD

**Issue by lps0535** [envoyproxy/envoy#2857]
*Title*: How to redirect request using prefix other than "/".

*Description*:
I want to redirect an incoming request to envoy to one of my services. Currently I'm using Envoy as a Front proxy only. Till now I've been using prefix = "/" but when I try putting prefix = "serviceA"or anything other than "/", it doesn't redirect and shows 404 Error. I'm accessing the service as
http://localhost:10000/serviceA
Below config file works if I put prefix = "/".
Sharing simple config file used here: https://www.envoyproxy.io/docs/envoy/latest/start/start 
*Config*:
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/serviceA" }
                route: { host_rewrite: www.google.com, cluster: serviceA }
          http_filters:
          - name: envoy.router
  clusters:
  - name: serviceA
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }

Any pointers what I'm doing wrong? 
Thanks

**Comment by zuercher** [comment]
Your config is forwarding your request to "www.google.com/serviceA", which is going to return a 404 (from Google).

If you add `prefix_rewrite: "/"` to your route action (where the host_rewrite is), it will forward to "www.google.com/" and you should get a 200.

**Comment by phylake** [comment]
I'm facing a similar issue. [`prefix_rewrite`](https://www.envoyproxy.io/docs/envoy/v1.6.0/api-v2/api/v2/route/route.proto.html#route-routeaction) should be replacing only the matched prefix but it appears to be replacing the entire matched **path** based on my observation

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/some_service" }
                route:
                  prefix_rewrite: "/"
                  cluster: some_service
          http_filters:
          - name: envoy.router
  clusters:
  - name: some_service
    hosts:
    - socket_address:
        address: 127.0.0.2
        port_value: 1234
```

I expected the request to `127.0.0.1:10000/some_service/health` to map to `127.0.0.2:1234/health`

I can only think that [`matched_path`](https://github.com/envoyproxy/envoy/blob/v1.6.0/source/common/router/config_impl.cc#L361) is exactly what it describes: the full path, not the prefix

**Comment by phylake** [comment]
Should have waited a few more minutes to post. `prefix: "/some_service/"` works

**Comment by zuercher** [comment]
I'm going to close this, but just to clarify:

```
match: 
  prefix: "/prefix"
route:
  prefix_rewrite: "/"
```

will happily rewrite "/prefix/foo" to "//foo" and forward it. Depending on the upstream that can have odd results.

To correctly rewrite "/prefix" to "/" and "/prefix/foo" to "/foo", you need two routes.
