### ISSUE TITLE
Configuring OpenTelemetry tracing with custom OpenTelemetry Collector

### ISSUE THREAD

**Issue by vmihailenco** [envoyproxy/envoy#28608]
There is a document that describes how to use Envoy with OpenTelemetry: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/opentelemetry

Let's suppose I have an OpenTelemetry Collector running at `my.domain.com:4317` using SSL. I also want to pass a custom authentication header to the Collector. How should I configure Envoy?

I've tried this:

```yaml
                tracing:
                  provider:
                    name: envoy.tracers.opentelemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                      grpc_service:
                        google_grpc:
                          target_uri: my.domain.com:4317
                          channel_credentials:
                            ssl_credentials: {}
                        timeout: 3s
                        initial_metadata:
                          - key: "custom-header"
                            value: "custom-value"
```

But it looks like `initial_metadata` headers are just ignored. But it could be something else (SSL). The logs are empty no matter what configuration I try.
