### ISSUE TITLE
Envoy request header casing

### ISSUE THREAD

**Issue by kpramesh2212** [envoyproxy/envoy#28610]
Hi Team,

Envoy is lowering the case of all the request headers. This is causing our application to break. For a few reasons, we are unable to make changes to our server code to use lowercase headers.

I have a sample envoy configuration 

```
static_resources:
  listeners:
    - name: header-manipulation
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                http_protocol_options:
                    header_key_format:
                      stateful_formatter:
                        name: preserve_case
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
                http_filters:
                  - name: http_route_filter
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                stat_prefix: header-manipulation
                route_config:
                  name: header-manipulation-config
                  virtual_hosts:
                    - name: all_hosts
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: app
  clusters:
    - name: app
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http_protocol_options:
                header_key_format:
                  stateful_formatter:
                    name: preserve_case
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.http.header_formatters.preserve_case.v3.PreserveCaseFormatterConfig
      load_assignment:
        cluster_name: app
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 80
```

Here is a sample docker configuration file to test it. 

```
services:
  envoy:
    container_name: envoy
    image: envoyproxy/envoy:v1.26-latest
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - ./envoy:/etc/envoy/
  sidecar:
    container_name: sidecar
    image: ealen/echo-server
    network_mode: service:envoy
```

Steps To Reproduce:

1. create a folder test
2. place the docker-compose.yml file shown above
3. create a folder test/envoy and place the envoy.yaml file shown above
4. cd test
5. docker-compose up -d
6. curl --header 'ININ-Authentication: aux123' localhost:8080

Actual Response:

```
{
  "host": {
    "hostname": "localhost",
    "ip": "::ffff:127.0.0.1",
    "ips": []
  },
  "http": {
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/"
    },
    "query": {},
    "cookies": {},
    "body": {},
    "headers": {
      "host": "localhost:8080",
      "user-agent": "curl/7.81.0",
      "accept": "*/*",
      "inin-authentication": "aux123",
      "x-forwarded-proto": "http",
      "x-request-id": "dbd6ccfb-dc21-44d5-aa64-1060901ed0fe",
      "x-envoy-expected-rq-timeout-ms": "15000"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "f2c35b490dce",
    "NODE_VERSION": "16.16.0",
    "YARN_VERSION": "1.22.19",
    "HOME": "/root"
  }
}

```

Expected Response:

```
{
  "host": {
    "hostname": "localhost",
    "ip": "::ffff:127.0.0.1",
    "ips": []
  },
  "http": {
    "method": "GET",
    "baseUrl": "",
    "originalUrl": "/",
    "protocol": "http"
  },
  "request": {
    "params": {
      "0": "/"
    },
    "query": {},
    "cookies": {},
    "body": {},
    "headers": {
      "host": "localhost:8080",
      "user-agent": "curl/7.81.0",
      "accept": "*/*",
      "ININ-authentication": "aux123",
      "x-forwarded-proto": "http",
      "x-request-id": "dbd6ccfb-dc21-44d5-aa64-1060901ed0fe",
      "x-envoy-expected-rq-timeout-ms": "15000"
    }
  },
  "environment": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "f2c35b490dce",
    "NODE_VERSION": "16.16.0",
    "YARN_VERSION": "1.22.19",
    "HOME": "/root"
  }
}

```

Please look at request.headers object in the above response

Could you please help us here?

Thanks 
Regards
Ramesh
