### ISSUE TITLE
Envoy as Front Proxy and exposing backend service which use gRPC

### ISSUE THREAD

**Issue by lps0535** [envoyproxy/envoy#2873]
Hi,

**_Description_**
I'm trying to use Envoy as front proxy only and I'm using filter "gRPC-JSON transcoder" for incoming HTTP or gRPC calls and this filter works fine.

When I use  "prefix": "/" and "prefix_rewrite": "/", and hit **localhost:3000/errorclass** I get 200 response code which is good and I think "localhost:3000/errorclass" gets mapped to "10.104.3.32:50054/errorclass". Please correct me if my understanding is wrong.

But when I use  "prefix": "/serviceA/" and "prefix_rewrite": "/", and hit **localhost:3000/serviceA/errorclass** I get error 
**on client side** : "Couldn't get any response"  and 
**On server side** :  "WARNING: Exception in onDataRead() java.lang.NullPointerException  and io.grpc.netty.NettyServerHandler onStreamError WARNING: Stream Error io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream " 

In above case, I'm expecting when I hit "**localhost:3000/serviceA/errorclass**" it should be mapped to "**10.104.3.32:50054/errorclass**".

I am unable to figure what's going wrong. May you please share your thoughts on this?

**FYI:**
If I use expose backend service as REST. Both the above scenarios work meaning prefix_rewrite works as expected.

I generate the proto.pb file using following Proto file.
**_Proto File:_**
```
syntax = "proto3";
import "google/api/annotations.proto";

service Errors {
    rpc GetErrorClass (GetErrorClassRequest) returns (GetErrorClassResponse) {
        option (google.api.http) = {
            post: "/errorclass"
            body: "*"
        };
    }
}
message GetErrorClassRequest {
    string error_id = 1;
}

message GetErrorClassResponse {
    string error_class = 1;
}

```
**_Config File:_** 
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 3000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/serviceA/" }
                route: { prefix_rewrite: "/", cluster: serviceA }
          http_filters:       
          - name: envoy.grpc_json_transcoder
            config:
                proto_descriptor: "/etc/proto.pb"
                services: ["Errors"]
                print_options:
                    add_whitespace: false
                    always_print_primitive_fields: true
                    always_print_enums_as_ints: false
                    preserve_proto_field_names: false
          - name: envoy.router
            config: {}
                           
          
  clusters:
  - name: serviceA
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 10.104.3.32
        port_value: 50054
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902
```
