### ISSUE TITLE
Configuring HTTP health check filters with aggregate clusters?

### ISSUE THREAD

**Issue by v1b1** [envoyproxy/envoy#28908]
*Title*: *Configuring HTTP health check filters with aggregate clusters?*

*Description*:
I have implemented a route that sends requests to an aggregate cluster. I assume that, with active cluster health checking configured for all of the clusters referenced by the aggregate cluster, if one host in one of those clusters is healthy then Envoy will route requests to that host. The issue I'm having is being able to expose that health status through the `envoy.filters.http.health_check` HTTP filter.

Given aggregate cluster `A` that references clusters `a1`, `a2`, etc. I tried configuring the filter like the following but it returns a 503 when one of the clusters `ak` is healthy but the others are not:

```
name: envoy.filters.http.health_check
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
  pass_through_mode: false
  cluster_min_healthy_percentages:
    A:
      value: 1
  headers: [...]
```

I also tried this, but as expected this returns 503 if one of the clusters is unhealthy:

```
name: envoy.filters.http.health_check
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
  pass_through_mode: false
  cluster_min_healthy_percentages:
    a1:
      value: 1
    a2:
      value: 1
    ...
  headers: [...]
```

Any help to resolve this would be appreciated!
