### ISSUE TITLE
OpenTelemetry tracer - Hability to configure a resource detector

### ISSUE THREAD

**Issue by joaopgrassi** [envoyproxy/envoy#28929]
*Description*:

The OpenTelemetry project defines the concept of a [Resource](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md). A resource is useful to "link" telemetry with a process, host/pod/container running for example in a Cloud environment. It is more or less a bag of attributes.

A resource can be configured in different ways in OpenTelemetry. Via environment variables, explicitly in code or via [Resource detectors](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#detecting-resource-information-from-the-environment).

Basically, the idea is that anyone could provide a resource detector package, that knows how to load relevant attributes from a place, and then return a `Resource` object populated with those attributes. For example, in the OpenTelemetry collector, there's several detectors for [Google Cloud, Heroku, AWS and others](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md). A detector could, for example, read attributes from a file, take them from k8s metadata or the like. 

In Envoy, we have the [OpenTelemetry tracer](https://github.com/envoyproxy/envoy/tree/main/source/extensions/tracers/opentelemetry), but the only attribute that is possible to configure on the `Resource` object is the [service.name](https://github.com/envoyproxy/envoy/blob/main/source/extensions/tracers/opentelemetry/tracer.cc#L125). This causes telemetry data produced by Envoy to have less information and limits the use-cases that you can achieve with richer resource objects. 

*Feature request*

1. Introduce a new interface inside the `opentelemetry` folder for a resource detector. The interface would need to have only one method called `detect` that would follow the OTel specification in regards to how fast it should execute, error handling etc. 

2. Invoke the resource detector at the start of the tracer, and when constructing the OTLP message, populate the `Resource` object with the attributes returned from the detector. We can start easy and allow only string key:value pairs. 

3. This then allows anyone (Cloud vendors, Observability back-ends etc) to define their own resource detectors in a new folder `tracers/opentelemetry/resource_detectors`

4. Allow which resource detector to be used by the tracer. Something like this:

```yaml
tracing:
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      resource_detector:
        name: envoy.opentelemetry.resource_detector.some_cloud_provider
```

I believe the addition of this interface will benefit everyone and will open up for a lot of great opportunities in the observability space for Envoy.

**Comment by KBaichoo** [comment]
This sounds like a great idea.

cc @AlexanderEllis @htuch

**Comment by joaopgrassi** [comment]
@KBaichoo cool! I'm interested in working in this :)

**Comment by joaopgrassi** [comment]
Hi @KBaichoo , @htuch 
I started taking a look at this. I'm using the OTel collector as inspiration https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor

Basically the way it works there is you can configure multiple detectors, and under the hood, the `ResourceProvider`  has a reference to all detectors configured and it calls a `detect` method on each, merges all attributes and returns a populated `Resource` object. 

I started drafting the types and thinking on how I'd like to configure this in Envoy:

```
tracing:
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      service_name: envoy-HTTP-exporter
	  resource_detectors:
		timeout: 10s
        overwrite: true
		detectors:
   			- name: envoy.tracers.opentelemetry.reosurce_detector.env
			- name: envoy.tracers.opentelemetry.resource_detector.dynatrace
			- name: envoy.tracers.opentelemetry.resource_detector.cloud_provider
			"@type": type.googleapis.com/envoy.config.trace.v3.CloudProviderResourceDetectorConfig
			# provider-specific config
```

What I'm a bit stuck now is:

1. Is there a way to automatically load/instantiate different detectors in code? Something like I pass all the `names` above and somehow figure out the actual type/class to instantiate?

2. And then, can also each individual detector receive the OpenTelemetryConfig::resourcedetector config object and somehow find its own config that it needs to use to work? 

In the collector, when you create a factory, it has all the known types already https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/factory.go#L48. Then, the main config object also has a property for each detector https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/config.go#L46 that gets passed down when instantiating them. 

Ad 1, worst case, I thought of manually checking each string name and manually instantiating them. 

I know it's a lot, but if you could point me into some direction I'd really appreciate it. Thanks!
