### ISSUE TITLE
dynamic_resources not work under windows 10 ?

### ISSUE THREAD

**Issue by dannyxu2015** [envoyproxy/envoy#28923]
*Title*: *dynamic_resources seems not work under windows 10*

*Description*:
Environment: 
  Windows 10 virtual host
  envoy version 1.24.0

After start envoy, I've tried to modify the lds.yaml(change listening port) or cds.yaml(change upstream service), both not worked. I've tried it under Mac pro, the change worked immediately.(I use curl to check it).
By searching closing issue, #23433 , create a new config file and replace the config file also not work.
Any ideas? Thanks in advance,

Danny 

Following is my config files:

envoy.yaml:

```
node:
  id: id_1
  cluster: test

dynamic_resources:
  cds_config:
    path_config_source:
      path: ./cds.yaml
  lds_config:
    path_config_source:
      path: ./lds.yaml
```

cds.yaml: (change the port value)
```
resources:
- "@type": [type.googleapis.com/envoy.config.cluster.v3.Cluster](http://type.googleapis.com/envoy.config.cluster.v3.Cluster)
  name: example_proxy_cluster
  type: STRICT_DNS
  load_assignment:
    cluster_name: example_proxy_cluster
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 192.168.2.16
              port_value: 8080
```

lds.yaml: (change the port_value)
```
resources:
- "@type": [type.googleapis.com/envoy.config.listener.v3.Listener](http://type.googleapis.com/envoy.config.listener.v3.Listener)
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
  filter_chains:
  - filters:
      name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": [type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager](http://type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager)
        stat_prefix: ingress_http
        http_filters:
        - name: envoy.filters.http.router
          typed_config:
            "@type": [type.googleapis.com/envoy.extensions.filters.http.router.v3.Router](http://type.googleapis.com/envoy.extensions.filters.http.router.v3.Router)
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains:
            - "*"
            routes:
            - match:
                prefix: "/"
              route:
                cluster: example_proxy_cluster
```
