### ISSUE TITLE
Configuration envoy.overload_actions.shrink_heap is not working

### ISSUE THREAD

**Issue by anvo1115** [envoyproxy/envoy#28948]
*Title*: Configuration envoy.overload_actions.shrink_heap is not working

*Description*:
We use envoy v1.26.4. We deploy it on the Kubernetes. We tried to configure overload_manager but I can see that envoy.overload_actions.shrink_heap doesn't work. Envoy heap is growing but not released. We have max_heap_size_bytes = 40 Mb but it grows even up to 44 Mb and not shrinked back. Probably my configuration is not correct?

*Repro steps*:
- envoy v1.26.4
- send many requests through envoy so that the memory grows up

*Admin and Stats Output*:
Output of /memory after the load test:
```
{
 "allocated": "11643744",
 "heap_size": "46137344",
 "pageheap_unmapped": "6782976",
 "pageheap_free": "8192",
 "total_thread_cache": "18394288",
 "total_physical_bytes": "44147406"
}
```

*Config*:
Set set the following properties in /envoy/config/envoy.yaml
```
overload_manager:
  refresh_interval: 0.25s
  resource_monitors:
    - name: "envoy.resource_monitors.fixed_heap"
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
        max_heap_size_bytes: 41943040
  actions:
    - name: "envoy.overload_actions.disable_http_keepalive"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.92
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.95
    - name: "envoy.overload_actions.stop_accepting_connections"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.98
    - name: "envoy.overload_actions.shrink_heap"
      triggers:
      - name: "envoy.resource_monitors.fixed_heap"
        threshold:
          value: 0.85
```

*Logs*:
No errors in envoy logs
