### ISSUE TITLE
possible to suppress the access log V3 by routes

### ISSUE THREAD

**Issue by amankumarcs** [envoyproxy/envoy#28995]
*Title*: *unclear to me if it's possible to suppress using access logging V3*

*Description*:
  I want to ignore two routes to capture access logs such as
  1. GET /healthz
  2. /bundle/bundle.tar.gz

**Comment by yanavlasov** [comment]
You can use the `filter` configuration to emit access log for the requests you want: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/accesslog/v3/accesslog.proto#envoy-v3-api-msg-config-accesslog-v3-accesslog

You can use the CEL extension_filter to write an expression for which requests NOT to emit access logs.

**Comment by amankumarcs** [comment]
@yanavlasov 
is it the correct configuration?
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ext-authz
  namespace: istio-system
spec:
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.http_connection_manager"
      patch:
        operation: MERGE
        value:
          name: envoy.access_loggers.stdout
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          filter:
            extension_filter:
              name: envoy.access_loggers.extension_filters.cel
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.filters.cel.v3.ExpressionFilter"
              expression: "not request.path.startsWith('/bundle')"
```
