### ISSUE TITLE
tracers/skywalking: sw8 header invalid when value is set to `[""]` in gRPC metadata 

### ISSUE THREAD

**Issue by suninuni** [envoyproxy/envoy#29003]
*Title*: *tracers/skywalking: sw8 header invalid when value is set to `[""]` in gRPC metadata*

*Description*:

When we set sw8 as  `[""]` in gRPC metadata, we will get a  warning log `warning envoy tracing New SkyWalking Span/Segment with previous span context cannot be created for error: Invalid span context format. It must have 8 fields.`, it doesn't make sense. The reason is the code only check whether the `propagation_header` is a null pointer, but does not check whether its value is empty.

https://github.com/envoyproxy/envoy/blob/a0c50af79c7790227294f8e3a2523fd2b6255b67/source/extensions/tracers/skywalking/skywalking_tracer_impl.cc#L54-L79

**Comment by yanavlasov** [comment]
Adding @lizan @wbpcode @Shikugawa as codeowners

**Comment by wbpcode** [comment]
Sorry, I didn't get your point. We will treat the "" value as illegal sw8 header, what's problem with it?

**Comment by suninuni** [comment]
@wbpcode the "" value in gRPC metadata should be ignored like "" value in HTTP headers, which means envoy should not output the warning log `warning envoy tracing New SkyWalking Span/Segment with previous span context cannot be created for error: Invalid span context format. It must have 8 fields.`.

**Comment by wbpcode** [comment]
Got it. But I don't think `not exist/present` is equal to `empty ""`. If a related rfc has covered this point, please paste it here.

**Comment by suninuni** [comment]
@wbpcode 

test case in k8s cluster

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-reflection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-reflection
  template:
    metadata:
      labels:
        app: grpc-reflection
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/componentLogLevel: "misc:error"
    spec:
      containers:
      - name: grpc-reflection
        image: romk/grpc-helloworld-reflection
        ports:
        - containerPort: 50051
---

apiVersion: v1
kind: Service
metadata:
  name: grpc-reflection
spec:
  selector:
    app: grpc-reflection
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051

```

`docker run --network=host fullstorydev/grpcurl -plaintext -H sw8: 10.104.218.125:50051 helloworld.Greeter.SayHello`

![image](https://github.com/envoyproxy/envoy/assets/7345529/2d75ba49-bbea-4b23-9140-cc7472e9a6ac)
