### ISSUE TITLE
zstd compression-decompression sometimes corrupts the HTTP response

### ISSUE THREAD

**Issue by ikalchev** [envoyproxy/envoy#29020]
*Title*: zstd compression-decompression sometimes corrupts the HTTP response

*Description*:
We have a workflow that can be summarised as:
downstream ------> envoy A ------> envoy B ------> upstream
Here:
- The communication between all entities is HTTP 1.1
- Downstream to envoy A and envoy B to upstream is plain HTTP
- envoy A to envoy B is over TLS
- Envoy A sets the "Accept-Encoding: gzip, zstd" header (through the Zstd, gzip decompressor filters) and subsequently decompresses the body
- Envoy B compresses the http response body (through the Zstd compressor filter)

Rarely (in the single digit percent), the body we get on the downstream is different to the one that was sent from the upstream. I say different because I am not sure if there are just bytes missing or it gets corrupted. This happens only with zstd - when I leave only the gzip filter, the problem disappears. 

Since this happens rarely and for 1-2MB responses, I am yet to get my hands on one of the responses. Will upload one if I can.

*Repro steps*:
The two envoys above are configured with the "default" zstd decompressor and compressor config.

The decompressor:
```
- name: envoy.filters.http.decompressor
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.decompressor.v3.Decompressor
                response_direction_config:
                  common_config:
                    enabled:
                      default_value: true
                      runtime_key: zstd_response_decompressor
                decompressor_library:
                  name: zstd_decompressor
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.compression.zstd.decompressor.v3.Zstd
```

The compressor:
```
{
  "name": "envoy.filters.http.compressor.zstd",
  "typedConfig": {
    "@type": "type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor",
    "chooseFirst": true,
    "compressorLibrary": {
      "name": "zstd_compressor",
      "typedConfig": {
        "@type": "type.googleapis.com/envoy.extensions.compression.zstd.compressor.v3.Zstd",
        "compressionLevel": 1,
        "strategy": "FAST"
      }
    },
    "responseDirectionConfig": {
      "removeAcceptEncodingHeader": true
    }
  }
}
```

*Logs*:
Here is snippet from the logs on debug:
```
[Originator@6876 sub=http] [C1417][S12670642521859171609] request headers complete (end_stream=false):
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::decodeHeaders advertise Accept-Encoding with value 'gzip'
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::decodeHeaders: ':authority', 'localhost'
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::decodeHeaders advertise Accept-Encoding with value 'gzip,zstd'
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::decodeHeaders: ':authority', 'localhost'
[Originator@6876 sub=router] [C1417][S12670642521859171609] cluster REDACTED match for URL REDACTED
[Originator@6876 sub=router] [C1417][S12670642521859171609] router decoding headers:
[Originator@6876 sub=router] [C1417][S12670642521859171609] pool ready
[Originator@6876 sub=http] [C1417][S12670642521859171609] request end stream
[Originator@6876 sub=router] [C1417][S12670642521859171609] upstream headers complete: end_stream=false
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::encodeHeaders: ':status', '200'
[Originator@6876 sub=filter] [C1417][S12670642521859171609] DecompressorFilter::encodeHeaders: ':status', '200'
[Originator@6876 sub=http] [C1417][S12670642521859171609] encoding headers via codec (end_stream=false):
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 6321 bytes to 131072 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 2523 bytes to 262144 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 331 bytes to 131072 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 6738 bytes to 393216 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 1751 bytes to 262144 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 1362 bytes to 131072 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 551 bytes to 131072 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 353 bytes to 131072 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 8713 bytes to 917504 bytes
[Originator@6876 sub=filter] [C1417][S12670642521859171609] response data decompressed from 0 bytes to 0 bytes
[Originator@6876 sub=http] [C1417][S12670642521859171609] encoding trailers via codec:
[Originator@6876 sub=http] [C1417][S12670642521859171609] Codec completed encoding stream.
```

In that particular case, the upstream sent 2'499'159 bytes, but the downstream got 2'490'368. One of the decompression messages claims some 396x compression ratio, but that is in line with other similar responses that were intact.
