### ISSUE TITLE
response code is 200 while the response_flags=UH

### ISSUE THREAD

**Issue by zhangbo1882** [envoyproxy/envoy#29052]
It is very strange that envoy return 200 while there is no health upstream. 
The access log is as follows:

```
 bytes_received | 0
bytes_sent | 0
duration | 0
method | POST
protocol | HTTP/2
response_code | 200
response_code_details | no_healthy_upstream
response_flags | UH
user_agent | grpc-java-netty/1.31.1

**Comment by zhangbo1882** [comment]
In my opinion, envoy should return 503 in this case. Is there any bug?

**Comment by kyessenov** [comment]
Related to https://github.com/envoyproxy/envoy/pull/29028?

**Comment by jbohanon** [comment]
Very interesting. Does the client receive 200 as well, or 503? I would expect the code to be 0 in the access logs if it were unset. Not sure where the 200 would be coming from. If the 200 is leaking in before the call to `sendNoHealthyUpstreamResponse` (e.g. because of a call to an upstream in the filter chain such as `ext_authz` or `ext_proc`), it's likely the response code needs to be explicitly set on the stream info [here](https://github.com/envoyproxy/envoy/blob/main/source/common/router/router.cc#L790). If it's coming in after that call, then that would explain why the client receives the 200 as well, and something something funky with the `DownstreamFilterManager` ([link](https://github.com/envoyproxy/envoy/blob/main/source/common/http/filter_manager.cc#L881)) seems more likely.

Can you please share sanitized config, specifically the filter chain for the route that is producing this?

**Comment by zhangbo1882** [comment]
Client received 200

**Comment by Lingtaonju** [comment]
Hi guys, thanks for the reply @jbohanon @kyessenov 
I works with zhangbo, and i will follow this problem. Do you think following config will help you ? 

> the envoy version we used
`/usr/local/bin/envoy  version: 314bdeaf0e5d69df58f2aa4d54e1047ed7f0bb50/1.25.2-dev/Clean/RELEASE/BoringSSL`

>router config
`

{
    "version_info": "2023-08-10T23:29:14Z/1176",
    "route_config": {
     "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
     "name": "http.10000",
     "virtual_hosts": [
      {
       "name": "xxx:10000",
       "domains": [
        "xxx"
       ],
       "routes": [
        {
         "match": {
          "prefix": "/",
          "case_sensitive": true
         },
         "route": {
          "cluster": "outbound|10000||xxxx",
          "timeout": "0s",
          "retry_policy": {
           "retry_on": "connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes",
           "num_retries": 2,
           "retry_host_predicate": [
            {
             "name": "envoy.retry_host_predicates.previous_hosts",
             "typed_config": {
              "@type": "type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"
             }
            }
           ],
           "host_selection_retry_max_attempts": "5",
           "retriable_status_codes": [
            503
           ]
          },
          "max_grpc_timeout": "0s"
         }
        }
       ],
       "include_request_attempt_count": true
      }
     ],
     "validate_clusters": false,
     "ignore_port_in_host_matching": true
    },
    "last_updated": "2023-08-10T23:29:30.092Z"
   }`

**Comment by Lingtaonju** [comment]
And, i think version: 314bdeaf0e5d69df58f2aa4d54e1047ed7f0bb50/1.25.2-dev/Clean/RELEASE/BoringSSL may not include this PR?

**Comment by jbohanon** [comment]
I am unable to reproduce the issue with an http upstream with the following config. I might have something to do with being HTTP/2 and/or gRPC.

<details>
<summary>config</summary>

```yaml
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 19000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: auto
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      validate_clusters: false
                      ignore_port_in_host_matching: true
                      virtual_hosts:
                        - name: backend
                          domains:
                            - "*"
                          include_request_attempt_count: true
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: service
                                timeout: 0s
                                # max_grpc_timeout": "0s"
                                retry_policy:
                                 retry_on: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
                                 num_retries: 2
                                 retry_host_predicate:
                                 - name: envoy.retry_host_predicates.previous_hosts
                                   typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
                                 host_selection_retry_max_attempts: 5
                                 retriable_status_codes:
                                 - 503
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 8082
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    access_log:
                    - name: file_access_log
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /tmp/29052/test_output/access.log
                        log_format:
                          text_format: "%REQ(:path)% - %RESPONSE_CODE% - %RESPONSE_CODE_DETAILS%\n"
                    codec_type: auto
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/node"
                              route:
                                cluster: test-node-server
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: service
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 19001
        - name: test-node-server
          common_lb_config:
            healthy_panic_threshold:
              value: 0
          health_checks:
          - timeout: 0.5s
            interval: 1s
            unhealthy_threshold: 1
            healthy_threshold: 1
            http_health_check:
              path: /health
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: test-node-server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 4000
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19001
```
</details>

**Comment by jbohanon** [comment]
I was able to reproduce this with the following script and config

<details>
<summary>config</summary>

```yaml
    static_resources:
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 19000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: auto
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      validate_clusters: false
                      ignore_port_in_host_matching: true
                      virtual_hosts:
                        - name: backend
                          domains:
                            - "*"
                          include_request_attempt_count: true
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: service
                                timeout: 0s
                                # max_grpc_timeout": "0s"
                                retry_policy:
                                 retry_on: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
                                 num_retries: 2
                                 retry_host_predicate:
                                 - name: envoy.retry_host_predicates.previous_hosts
                                   typed_config:
                                    "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
                                 host_selection_retry_max_attempts: 5
                                 retriable_status_codes:
                                 - 503
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 8082
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    access_log:
                    - name: file_access_log
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /tmp/29052/test_output/access.log
                        log_format:
                          text_format: "%REQ(:path)% - %RESPONSE_CODE% - %RESPONSE_CODE_DETAILS%\n"
                    codec_type: auto
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: "/"
                              route:
                                cluster: test-grpc-server
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: service
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 19001
        - name: test-grpc-server
          common_lb_config:
            healthy_panic_threshold:
              value: 0
          health_checks:
          - timeout: 0.5s
            interval: 1s
            unhealthy_threshold: 1
            healthy_threshold: 1
            http_health_check:
              path: /healthbad
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          load_assignment:
            cluster_name: test-grpc-server
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      health_check_config:
                        port_value: 5001
                        address:
                          socket_address:
                            address: 127.0.0.1
                            port_value: 5001
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 5000
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19001
```
</details>

<details>
<summary>run script</summary>

```bash
#!/usr/bin/bash

SCRIPT_CALL_PATH="$(ps $$ | tail -1 | awk '{print $6}')"
if [[ $SCRIPT_CALL_PATH =~ [^.]/get-deps-and-run-test.sh ]]; then
  echo "script must be run from within testing directory"
  exit 1
fi

if [[ -z $(which curl) ]]; then
  echo "script requires curl command to download dependencies"
  exit 1
fi

# Get gRPC server
if [ ! -d "./foo-grpc-server" ]; then
  git clone https://github.com/jbohanon/foo-grpc-server.git
fi

# Get envoy
if [ ! -f "./envoy" ]; then
  curl -LO "https://github.com/envoyproxy/envoy/releases/download/v1.25.2/envoy-1.25.2-linux-x86_64"
  mv envoy-1.25.2-linux-x86_64 envoy
  chmod +x envoy

  # print envoy version
  ./envoy --version
fi

# Run envoy
./envoy --config-path ./envoy.yaml --log-level debug 1>./envoy.log 2>&1 &

# Run our grpc server
pushd foo-grpc-server
go run pkg/server/server.go &
GRPC_SERVER_PID=$1

# Run our gRPC client
for i in {1..50}
do
  go run pkg/client/client.go --port 8082
done
popd

TMP_OUTDIR=/tmp/29052/test_output
mkdir -p "$TMP_OUTDIR"
curl http://localhost:19000/stats -o $TMP_OUTDIR/envoy_metrics
curl http://localhost:19000/clusters -o $TMP_OUTDIR/envoy_clusters
curl http://localhost:19000/routes -o $TMP_OUTDIR/envoy_routes
curl http://localhost:19000/server_info -o $TMP_OUTDIR/envoy_server_info
read -r -n 1 -p "Waiting for keypress to continue"
curl -X POST http://localhost:19000/quitquitquit

kill -9 $GRPC_SERVER_PID
```
</details>

This repeatedly produced a `200` response code with a `no_healthy_upstream` response code details:
`/api.Foo/GetFoo - 200 - no_healthy_upstream`
```
./envoy --version

./envoy  version: afa98867c807dee0d833da701ba3ab0c9ace9ada/1.25.2/Clean/RELEASE/BoringSSL
```
