### ISSUE TITLE
Is it possible to add X-REQUEST-ID into header of response

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#29056]
I used `httpbin` to simulate my server (upstream), and I deployed an envoy as my gateway (192.168.1.10). Here is the part of its config:
```
          route_config:
            name: local_route
#            request_headers_to_add:
            response_headers_to_add:
            - header:
                key: "x-request-id"
                value: "%REQ(X-REQUEST-ID)%"
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_http
```
As my understanding, `X-REQUEST-ID` is generated by Envoy. What I'm trying to do is to add it into the header of response. However, it doesn't seem to work as expected. Here is the output of `http://192.168.1.10/headers`:
```
{
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", 
    "Accept-Encoding": "gzip, deflate", 
    "Accept-Language": "en-US,en;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6", 
    "Cache-Control": "max-age=0", 
    "Host": "192.168.1.10:80", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  }
}
```
As you see, `X-REQUEST-ID` isn't here.

Did I do something wrongly? Or did I misunderstand something?
