### ISSUE TITLE
GZip Filter doesn't work on some clients

### ISSUE THREAD

**Issue by yudiandreanp** [envoyproxy/envoy#2909]
**Title**: GZip filter doesn't work on some http clients

**Description**:
Using Gzip filter doens't work some http client (apache http client).

**Repro steps**:

1. Using curl , netcat and gunzip
- Enable GZip Filter:

```
static_resources:
  listeners:
  - address: #http-address
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: AUTO
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.gzip
            config:
              memory_level: 9
              compression_level: BEST
          - name: envoy.router
          route_config:
            virtual_hosts: #http-hosts
            - name: local-test-server
              domains:
              - test-server.com
              routes:
              - match:
                  prefix: ""
                route:
                  cluster: local-test-server
  clusters:
  - name: local-test-server
    type: STRICT_DNS
    connect_timeout:
      seconds: 60
      nanos: 0
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 1234
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

- Run a netcat server -> ./test-server
```
#!/bin/bash

echo -n -e "HTTP/1.1 200 OK\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Length: 64\r\n\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" | nc -l -p 1234
```

- Curl and try to decompress using gunzip:

```
curl -XPOST http://127.0.0.1:80 -H 'Host: test-server.com' -H 'Accept-Encoding: gzip' | gunzip -
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
gzip: stdin: unexpected end of file
```

```
curl -XGET http://127.0.0.1:80 -H 'Host: test-server.com' -H 'Accept-Encoding: gzip' | gunzip -
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
gzip: stdin: unexpected end of file
```

2. Using apache http client:

- Create a simple http client-server
- Do Request to a server returning payload >30 bytes to trigger gzip compression
- the http client raises exception

Stacktrace of the http-client:

> com.xxx.cham.http.DefaultHttpClient [DEFAULT_HTTP_CLIENT] An error occurred when trying to perform HTTP request. Request: HttpRequest{uri='http://test-api.example.com', headers={}, params={}, method=POST, body='{"example":"tetst"}', contentType=JSON, options=HttpRequestOptions{proxy='null', requestTimeout=-1, ignoreSocketTimeout=false}}::java.io.EOFException: Unexpected end of ZLIB input stream 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) 	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70) 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) 	at java.io.InputStreamReader.read(InputStreamReader.java:184) 	at java.io.BufferedReader.fill(BufferedReader.java:161) 	at java.io.BufferedReader.readLine(BufferedReader.java:324) 	at java.io.BufferedReader.readLine(BufferedReader.java:389) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.processHttpResponse(DefaultHttpClient.java:90) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.doPostRequest(DefaultHttpClient.java:154) 	at com.airy.cham.http.DefaultHttpClient$HttpSendRunnable.run(DefaultHttpClient.java:187) 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)
> --

The GZIP filter's test cases also doesn't seem to include HTTP POST requests
