### ISSUE TITLE
Request: Support zone aware routing for CDS-only clusters

### ISSUE THREAD

**Issue by wbertelsen** [envoyproxy/envoy#2918]
*Title*: Support zone aware routing for CDS-only clusters

*Description*:
Right now, in order to set `local_cluster_name` and enable zone aware routing, the matching local cluster needs to be statically defined at bootstrap. It would be preferable if this information could be sourced from CDS when available. 

 *Relevant Links*:
https://groups.google.com/forum/#!topic/envoy-users/x4Vo3scNeo0
https://groups.google.com/forum/#!topic/envoy-users/dGbaMNGKQS4

**Comment by cmluciano** [comment]
cc @liamawhite

**Comment by cmluciano** [comment]
I'm interested in picking this up @mattklein123 . We have some teams that are interested in using this in Istio. Can you post on what the edge cases are that were mentioned in the mailing lists from your perspective?

cc @linsun

**Comment by mattklein123** [comment]
@cmluciano unfortunately this is going to be really thorny to fix and will require a bunch of thinking. I would honestly have to set down for a focused effort to help come up with a plan.

The issues basically stems from the fact that as has already been mentioned the local cluster is assumed to be statically defined and exist at startup. You can start to follow the code threads here:
https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_manager_impl.cc#L637

Changing the code to lazily load this in from CDS will be quite complicated, and further, if the local cluster can be removed from CDS, removal notifications will need to be handled by all of the read local load balancers which depend on it. (@nt just added some callbacks that might help here).

This has come up several times in the context of error checking around gRPC clients and other places, but I honestly wonder whether we should introduce the concept of a "locked" CDS cluster. A "locked" cluster is a cluster that when delivered via CDS in the initial startup load can never be removed. I think if we made this assumption, a lot of things would get simpler. (It also wouldn't be that hard to change CM init to wait for the initial CDS load before initialing the local cluster on all threads).

Anyway, I don't have any other thoughts on this right now without carving out some dedicated time. Maybe you want to dig in a bit and we can chat?

Also cc @alyssawilk and @htuch who have worked in this area.

**Comment by rene-m-hernandez** [comment]
I would like to be able to load the local_cluster via CDS, as well; however, if I were able to simply provide the Cluster configuration via the command line option `--config-yaml`, that would also be extremely helpful.

It is my understanding that any configuration passed through config YAML would be merged with the config file. Unfortunately, when I pass something like this:
```yaml
--config-yaml "
      cluster_manager:
        local_cluster_name: svc_a
      static_resources:
        clusters:
        - name: svc_a
          connect_timeout: 1s
          type: EDS
          eds_cluster_config:
            eds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: xds_cluster
```
Envoy will throw: "local cluster 'svc_a' must be defined. Is this the correct behavior? I would expect the config merging to happen prior to the local cluster validation.
