### ISSUE TITLE
Memory Utilization Concerns in Envoy Router Deployment

### ISSUE THREAD

**Issue by Tharsanan1** [envoyproxy/envoy#29206]
*Description*:

We are deploying Envoy router in Azure AKS cluster with the following memory and CPU requisites

    ```
    resources:
      requests:
        memory: "500Mi"
        cpu: "2000m"
      limits:
        memory: "500Mi"
        cpu: "2000m"
    ```

  As part of our performance validation, which involves subjecting the system to a load of 1000 concurrent users, each transmitting a payload of 100Kib. During this performance test, the router's memory consumption surges beyond the specified limits. Consequently, Kubernetes intervenes by terminating the respective pod, accompanied by an "Out Of Memory (OOM) Killed" message.

This is the config_dump that the router is using: [config_dump.txt](https://github.com/envoyproxy/envoy/files/12416719/config_dump.txt)

Could you please advise on this behavior?
