### ISSUE TITLE
new endpoints receive no traffic when min_weight_percent is 1

### ISSUE THREAD

**Issue by AndyEWang** [envoyproxy/envoy#29259]
*Description*:
Whether in or beyond the slow start window, the new endpoints never receive traffic when min_weight_percent is 1.
(there are 130 Pods in the upstream service and then scale out 2 new Pods.)

*Repro steps*:
1) install the latest contour 1.25.2 which is using envoy image tag 1.26.4-debian-11-r20
2) Configure HTTPProxy with slowStartPolicy.minWeightPercent=1
```
  routes:
    - services:
        - name: test
          port: 80
          slowStartPolicy:
            window: 3m
            minWeightPercent: 1
      loadBalancerPolicy:
        strategy: WeightedLeastRequest
```
the generated envoy cluster config will be
```
      "lb_policy": "LEAST_REQUEST",
      "least_request_lb_config": {
        "slow_start_config": {
          "slow_start_window": "180s",
          "aggression": {
            "default_value": 1,
            "runtime_key": "contour.slowstart.aggression"
          },
          "min_weight_percent": {
            "value": 1
          }
        }
      },

```
3) let target upstream service scale out replicas (I'm using Nginx as target upstream services with **130Pods**)
4) run fortio with 100qps to access envoy service
5) find the access logs in both old and new target Pods
6) also check the envoy access logs
7) no any traffic in new target Pods and envoy only route to old Pods
8) continue to run fortio after the slow start window but still no traffic
