### ISSUE TITLE
dynamic forward proxy: Support HCM authority rewrites

### ISSUE THREAD

**Issue by nbaws** [envoyproxy/envoy#29282]
HCM supports host_rewrite_path_regex. dynamic forward proxy only supports single replacements

*Description*:
A simple rewrite scenario is to use the example code from host_rewrite_path_regex to rewrite the authority from path /envoyproxy.io/test to envoyproxy.io

```
...
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_path_regex:
                    pattern:
                      google_re2: {}
                      regex: "^/(.+)/.+$"
                    substitution: \1
                  cluster: simple_cluster
          http_filters:
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
...
```

It does not appear to be possible to implement this, as the dns caching of dynamic_forward_proxy comes before the HCM authority rewrite. Therefore the destination remains the original authority from the request.

```envoy-test-envoy-1  | [2023-08-28 03:23:26.164][36][debug][http] [source/common/http/conn_manager_impl.cc:1089] [Tags: "ConnectionId":"9","StreamId":"11777945304543669776"] request headers complete (end_stream=true):
envoy-test-envoy-1  | ':authority', 'example.org'
envoy-test-envoy-1  | ':path', '/ccccccc.testing/test'
envoy-test-envoy-1  | ':method', 'GET'
envoy-test-envoy-1  | 'user-agent', 'curl/8.0.1'
envoy-test-envoy-1  | 'accept', '*/*'
envoy-test-envoy-1  |
envoy-test-envoy-1  | [2023-08-28 03:23:26.164][36][debug][http] [source/common/http/conn_manager_impl.cc:1072] [Tags: "ConnectionId":"9","StreamId":"11777945304543669776"] request end stream
envoy-test-envoy-1  |
envoy-test-envoy-1  | [2023-08-28 03:23:26.165][36][debug][connection] [./source/common/network/connection_impl.h:98] [C9] current connecting state: false
envoy-test-envoy-1  | [2023-08-28 03:23:26.165][36][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:91] thread local lookup for host 'example.org:80'
envoy-test-envoy-1  | [2023-08-28 03:23:26.165][36][debug][forward_proxy] [source/extensions/common/dynamic_forward_proxy/dns_cache_impl.cc:112] cache miss for host 'example.org:80', posting to main thread
...
envoy-test-envoy-1  | [2023-08-28 03:23:26.170][36][debug][router] [source/common/router/router.cc:478] [Tags: "ConnectionId":"9","StreamId":"11777945304543669776"] cluster 'simple_cluster' match for URL '/ccccccc.testing/test'
envoy-test-envoy-1  | [2023-08-28 03:23:26.171][36][debug][router] [source/common/router/config_impl.cc:846] Calling host_rewrite_path_regex
envoy-test-envoy-1  | [2023-08-28 03:23:26.171][36][debug][router] [source/common/router/config_impl.cc:849] authority before = example.org
envoy-test-envoy-1  | [2023-08-28 03:23:26.171][36][debug][router] [source/common/router/config_impl.cc:859] authority after = ccccccc.testing
envoy-test-envoy-1  | [2023-08-28 03:23:26.171][36][debug][router] [source/common/router/router.cc:690] [Tags: "ConnectionId":"9","StreamId":"11777945304543669776"] router decoding headers:
envoy-test-envoy-1  | ':authority', 'ccccccc.testing'
envoy-test-envoy-1  | ':path', '/ccccccc.testing/test'
envoy-test-envoy-1  | ':method', 'GET'
envoy-test-envoy-1  | ':scheme', 'http'
envoy-test-envoy-1  | 'user-agent', 'curl/8.0.1'
```

The feature request is to either perform the dns lookup post HCM authority rewrites, or to be able to perform the equivalent host rewrite functionality inside dynamic_forward_proxy.
