### ISSUE TITLE
Envoy 1.27 fails to find UpstreamTlsContext

### ISSUE THREAD

**Issue by yael-abramovici** [envoyproxy/envoy#29293]
my transport socket is set up like this:

   ```
   transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

when running an envoy container, im getting an error:
error initializing config '  /etc/envoy/envoy.yaml': Didn't find a registered implementation for 'envoy.transport_sockets.tls' with type URL: 'envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext'

does anyone know more about this?
