### ISSUE TITLE
Use cluster metadata as dimension of stats

### ISSUE THREAD

**Issue by siyigao1212** [envoyproxy/envoy#29294]
*Title*: *Use cluster metadata as dimension of stats*

*Description*:
As this [issue](https://github.com/envoyproxy/envoy/issues/7899) mentioned , from the doc, we see 
> The Metadata field can be used to provide additional information about the cluster. It can be used for **stats**, logging, and varying filter behavior. 

So we expect that we could set some stats dimension from cluster metadata for upstream metric, we tried below config
```
clusters:
- name: service_foo
  connect_timeout: 0.25s
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  metadata:
    filter_metadata:
      envoy.lb:
        tag1: tag1
        tag2: tag2
  load_assignment:
    cluster_name: service_foo
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 1.2.3.4
              port_value: 443
```
Take metric upstream_rq_active for example, the original stats name is cluster.ClusterName.upstream_rq_active, the expected stats name is cluster.ClusterName.**tag1.tag2**.upstream_rq_active. However we couldn't see some new dimensions added for the metric.

Please help point out how to configure the cluster metadata for stats. We are using envoy 1.26.1 version. Thanks
