### ISSUE TITLE
Is it necessary for go extension route config to store the configuration of different plugins

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#29315]
*Title*: *Is it necessary for go extension route config to store the configuration of different plugins?*

*Description*:
```
message ConfigsPerRoute {
  // Configuration of the Go plugin at the per-router or per-virtualhost level,
  // keyed on the :ref:`plugin_name <envoy_v3_api_field_extensions.filters.http.golang.v3alpha.Config.plugin_name>`
  // of the Go plugin.
  //
  map<string, RouterPlugin> plugins_config = 1;
}
```
Since now getting per filter config by the http filter config name is supported, is it necessary for go extension route config to  store the configuration of different go filters? For example, if we have two go filters `go-basic-auth` and `go-rate-limit`, for `http_filters` and `typed_per_filter_config`, the config name can be the same, so the go filter can get its own route config.

```
          http_filters:
          - name: go-basic-auth
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              ......
          - name: go-rate-limit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              ......

          route_config:
            name: local_route
            virtual_hosts:
              - name: host-one
                domains:
                  - "*"
                routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: httpbin
                    typed_per_filter_config:
                      go-basic-auth:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
                        config:
                        ......
                      go-rate-limit:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
                        config:
                        ......
```

In this way, the go filter will just be like a c++ filter, every go filter has its own route config, which maybe simple for control plane.
