### ISSUE TITLE
multi-value support in header match

### ISSUE THREAD

**Issue by yogeshkrbhat** [envoyproxy/envoy#29317]
my header is as follows:

```console
curl --header "x-custom-route-svc:abcxyz:demo-service1.ns1.cluster.local" --header "x-custom-route-svc:mnop:demo-service2.ns2.cluster.local"  URL
```
Format - x-custom-route-svc:[token1:service1,token2:service2]

And envoy route config:
```yaml
                 routes:
                  - match: 
                      prefix: "/"
                      headers:
                        - name: "x-custom-route-svc"
                          contains_match: "demo-service2.ns2.cluster.local"
```
                          
here the header    "x-custom-route-svc" is a multi-value with different service names and user-token. Since user-token is varying in every request, I would like to do substring match as above.

Unfortunately, contains_match does substring match with only first value. 

any suggestions for this?

_Originally posted by @yogeshkrbhat in https://github.com/envoyproxy/envoy/issues/13751#issuecomment-1694217102_
