### ISSUE TITLE
envoy-1.27: aggregate cluster upstream filter does not work when configured on target clusters

### ISSUE THREAD

**Issue by pgeler** [envoyproxy/envoy#29318]
Aggregate cluster configured as default:
```
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.aggregate
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.aggregate.v3.ClusterConfig
        clusters:
        - a_cluster
        - b_cluster
```

while cluster a/b configured to propagate HTTP headers through upstream filters:
```
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
        http_filters:
        - name: envoy.filters.http.header_mutation
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
            mutations:
              request_mutations:
                - append:
                    header:
                      key: "x-route"
                      value: "a/b"
                    append_action: OVERWRITE_IF_EXISTS_OR_ADD
        - name: envoy.filters.http.upstream_codec
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
```

Our expectations would be for the header to be populated upstream according to the target cluster configuration, if a http route configured to route through aggregate cluster.
