### ISSUE TITLE
[upstream cluster] membership_healthy gauge does not include canary endpoints

### ISSUE THREAD

**Issue by kindermoumoute** [envoyproxy/envoy#29359]
*Title*: *membership_healthy gauge does not include canary endpoints*

*Description*:
After configuring canary on an upstream cluster I can see health checks calls success on my endpoints, but the envoy metric `envoy_cluster_membership_healthy` only reflect the non-canary endpoints. I would either expect to have this metric reflect all the healthy nodes (canary or not), OR have another metric `envoy_cluster_membership_canary_healthy`.

*Repro steps*:
- Configure an upstream cluster with the canary feature using `lb_subset_config` and healthchecks (see config below)
- Verify healthchecks arrive on both canary and default addresses
- envoy_cluster_membership_total shows all the endpoints
- envoy_cluster_membership_healthy shows only default endpoints

*Config*:
<details><summary>UPSTREAM CLUSTER ENVOY CONFIG</summary>
<p>

```yaml
  - name: test_canary
    type: STRICT_DNS
    common_lb_config:
      healthy_panic_threshold:
        value: 33
    connect_timeout: 30s
    dns_refresh_rate: 7200s
    health_checks:
    - healthy_threshold: 1
      http_health_check:
        codec_client_type: HTTP2
        path: /health
        service_name_matcher:
          exact: test_canary
      interval: 15s
      no_traffic_interval: 15s
      timeout: 10s
      unhealthy_threshold: 1
    lb_subset_config:
      default_subset:
        canary: default
      fallback_policy: DEFAULT_SUBSET
      subset_selectors:
      - keys:
        - canary
    load_assignment:
      cluster_name: test_canary
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: address-default
                port_value: 8080
          metadata:
            filter_metadata:
              envoy.lb:
                canary: default
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: address-canary
                port_value: 8080
          metadata:
            filter_metadata:
              envoy.lb:
                canary: canary-group
```

</p>
</details>
