### ISSUE TITLE
Cannot Configure Envoy as Forward HTTPS Proxy, Looking for Help

### ISSUE THREAD

**Issue by gangware72** [envoyproxy/envoy#29381]
*Description*:
I have been trying on and off to get envoy to serve as a proxy. I enabled connect, double checked my certs, priv/pub key are in order. I used the dynamic forward proxy example as a base and suggestions from what I have found here in the issues and on Stacks and I can't seem to get envoy to budge in the right direction.

I am attempting to call the proxy with this curl command:
`curl --proxy 0.0.0.0:10000 https://www.example.com:443`

Can someone here help nudge me in the right direction. From what I can tell, the filter should terminate the tls connection downstream and then upstream host (example.com) should terminate with the Cluster using the validation_context trusted_ca?

Here is my config file:

```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match:
                    prefix: "/force-host-rewrite"
                  route:
                    cluster: dynamic_forward_proxy_cluster
                    upgrade_configs:
                      upgrade_type: CONNECT
                      connect_config: {}
                  typed_per_filter_config:
                    envoy.filters.http.dynamic_forward_proxy:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                      host_rewrite_literal: www.example.org
                - match:
                    connect_matcher: {}
                  route:
                    cluster: dynamic_forward_proxy_cluster
                    upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config:
                        proxy_protocol_config: {}
            http_filters:
            - name: envoy.filters.http.dynamic_forward_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
                  typed_dns_resolver_config:
                    name: envoy.network.dns_resolver.cares
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                      resolvers:
                      - socket_address:
                          address: "8.8.8.8"
                          port_value: 53
                      dns_resolver_options:
                        use_tcp_for_dns_lookups: true
                        no_default_search_domain: true
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain: {filename: "certs/fullchain.pem"}
                private_key: {filename: "certs/privkey.pem"}
              alpn_protocols: ["h2,http/1.1"]
              validation_context:
                trusted_ca:
                  filename: certs/certbundlepem.pem
  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: {"filename": "certs/fullchain.pem"}
            private_key: {"filename": "certs/privkey.pem"}
          validation_context:
            trusted_ca:
              filename: certs/certbundlepem.pem
```

Logs
`[2023-09-01 09:52:34.671][3148291][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_tcp_listener.cc:157] [Tags: "ConnectionId":"0"] new connection from 127.0.0.1:52819
[2023-09-01 09:52:34.671][3148291][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:247] [Tags: "ConnectionId":"0"] remote address:127.0.0.1:52819,TLS error: 268435611:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST
[2023-09-01 09:52:34.671][3148291][debug][connection] [source/common/network/connection_impl.cc:250] [Tags: "ConnectionId":"0"] closing socket: 0
[2023-09-01 09:52:34.671][3148291][debug][connection] [source/extensions/transport_sockets/tls/ssl_socket.cc:247] [Tags: "ConnectionId":"0"] remote address:127.0.0.1:52819,TLS error: 268435611:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST
[2023-09-01 09:52:34.671][3148291][debug][conn_handler] [source/extensions/listener_managers/listener_manager/active_stream_listener_base.cc:121] [Tags: "ConnectionId":"0"] adding to cleanup list
`

I have never posted in the issues section of a repo before, sorry if this isn't the place for this.

Best,

**Comment by gangware72** [comment]
Properly formatted config:

admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_http
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match:
                    prefix: "/force-host-rewrite"
                  route:
                    cluster: dynamic_forward_proxy_cluster
                    upgrade_configs:
                      upgrade_type: CONNECT
                      connect_config: {}
                  typed_per_filter_config:
                    envoy.filters.http.dynamic_forward_proxy:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.PerRouteConfig
                      host_rewrite_literal: www.example.org
                - match:
                    connect_matcher: {}
                  route:
                    cluster: dynamic_forward_proxy_cluster
                    upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config:
                        proxy_protocol_config: {}
            http_filters:
            - name: envoy.filters.http.dynamic_forward_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
                  typed_dns_resolver_config:
                    name: envoy.network.dns_resolver.cares
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                      resolvers:
                      - socket_address:
                          address: "8.8.8.8"
                          port_value: 53
                      dns_resolver_options:
                        use_tcp_for_dns_lookups: true
                        no_default_search_domain: true
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
            common_tls_context:
              tls_certificates:
              - certificate_chain: {filename: "certs/fullchain.pem"}
                private_key: {filename: "certs/privkey.pem"}
              alpn_protocols: ["h2,http/1.1"]
              validation_context:
                trusted_ca:
                  filename: certs/certbundlepem.pem
  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: true
                no_default_search_domain: true
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: {"filename": "certs/fullchain.pem"}
            private_key: {"filename": "certs/privkey.pem"}
          validation_context:
            trusted_ca:
              filename: certs/certbundlepem.pem

**Comment by moderation** [comment]
I've been running a dynamic forward proxy for quite a while and have `git`, `apt` and `cargo` all configured to use it.  Shortened config below
```yaml
static_resources:
  clusters:
    - name: dynamic_forward_proxy_cluster
      connect_timeout: 2s
      dns_lookup_family: ALL
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          allow_coalesced_connections: true
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: ALL
  listeners:
    - name: dynamic_forward_proxy_upgrade
      additional_addresses:
        - address:
            socket_address:
              address: "::1"
              port_value: 9904
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: ALL
                  - name: envoy.filters.http.router
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http2_protocol_options:
                  allow_connect: true
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /
                          route:
                            cluster: dynamic_forward_proxy_cluster
                        - match:
                            connect_matcher: {}
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config: {}
                stat_prefix: dynamic_forward_proxy_upgrade
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9904
      traffic_direction: OUTBOUND
```
