### ISSUE TITLE
Why does `retry policy` send all of requests to the unhealthy endpoint

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#29409]
I deployed two grpc servers as a cluster and I configured `retry_policy` as below:
```
...
virtual_hosts:
- name: test
  domains: ["*"]
  routes:
  - match:
      prefix: "/com.api.test"
    route:
      cluster: cluster_test
      retry_policy:
        retry_on: "5xx,unavailable.connection-failure"
        num_retries: 1
        per_try_timeout: 5s
...
clusters:
- name: cluster_test
... 
  load_assignment:
    endpoints:
    - lb_endpoints:
      - endpoint: {address: {socket_address: {address: 192.168.10.1, port_value: 10000}}}
      - endpoint: {address: {socket_address: {address: 192.168.10.2, port_value: 10000}}} ### timeout endpoint
```
Now, I intentionally make the endpoint `192.168.10.2:10000` timeout, which means that any request routed to this endpoint will get the grpc timeout error: `14 UNAVAILABLE`.

I was expecting that some requets could be routed to `192.168.10.1:10000` and others are routed to the timeout endpoint. And for those requests of `192.168.10.2:10000`, they should spend more than 10 seconds to get their responses because they need to do retry on the other endpoint.

But to my surprise, it seems that all of requests are routed to the timeout endpoint because they all spent more than 10 seconds. 

Why does Envoy route all of requests to the unhealthy endpoint? Or did I misunderstand something?
