### ISSUE TITLE
Certificate change/removal does not take effect in Envoy

### ISSUE THREAD

**Issue by calikonur** [envoyproxy/envoy#29406]
*Title*: *Certificate change/removal does not take effect in Envoy*

*Description*:
Hi,

I would like to test sds feature of envoy by connecting to a server, which accepts mTLS traffic.
I want to see that when content of the TLS certificate is changed or removed, envoy proxy to make necessary changes automatically without restarting itself. If the TLS certificates is changed to the empty one or removed or changed with the invalid one, after those changes the traffic should not be allowed to the destination.

I have configured my envoy like this
```
node:
  cluster: envoy_cluster
  id: envoy_node
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: <IP of the destination>
                  cluster: service_envoyproxy_io
  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <IP of the destination>
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificate_sds_secret_configs:
            name: tls_sds
            sds_config:
              path_config_source:
                path: /etc/envoy/tls_certificate_sds_secret.yaml
                watched_directory:
                  path: /certs/current
              resource_api_version: V3
          validation_context_sds_secret_config:
            name: validation_context_sds
            sds_config:
              path_config_source:
                path: /etc/envoy/validation_context_sds_secret.yaml
                watched_directory:
                  path: /certs/current
              resource_api_version: V3
```
tls_certificate_sds_secret.yaml
```
version_info: "0"
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: tls_sds
    tls_certificate:
      certificate_chain:
        filename: /certs/current/client.example.com.crt
      private_key:
        filename: /certs/current/clientcombined.example.pem
      watched_directory:
        path: /certs
```
validation_context_sds_secret.yaml
```
version_info: "0"
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_sds
    validation_context:
      trusted_ca:
        filename: /certs/current/example.com.crt
      watched_directory:
        path: /certs
```
With those configuration everything is working fine and I can connect to my nginx server through envoy with mTLS.
However, when I try to change and put an invalid certificate to client.example.com.crt by copying the invalid content inside the docker environment, the certificates are not getting updated, although in envoy debug logs I can see that the change has been notified by inotify.
```
[2023-09-01 15:23:58.705][1][debug][main] [source/server/server.cc:263] flushing stats  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: client.example.com.crt  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: client.example.com.crt  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: client.example.com.crt  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: client.example.com.crt  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: clientcombined.example.pem  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: clientcombined.example.pem  [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: clientcombined.example.pem [2023-09-01 15:24:01.018][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: clientcombined.example.pem  [2023-09-01 15:24:01.019][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: example.com.crt  [2023-09-01 15:24:01.019][1][debug][file]
[source/common/filesystem/inotify/watcher_impl.cc:73] notification: fd: 1 mask: 2 file: example.com.crt 
```              
So in that situation I would expect Envoy to get the new invalid certificate and returns an error and not let me to reach nginx server.
Is it expected behavior of envoy to work like this? If not how can I make it work as intended?
Best regards
