### ISSUE TITLE
2 Tier Envoy with gRPC-Web filter fails with `503`

### ISSUE THREAD

**Issue by negator** [envoyproxy/envoy#2942]
`envoy v1.5.0`
`grpc-go v1.6.0`

*Description*:
Using a 2 tier envoy setup with a gRPC-Web filter on the downstream envoy, and proxying a `go-grpc` service on the upstream envoy, returns a `RST_STREAM` midway through the request to the backend, causing the downstream envoy to return `503` to the javascript client. 

The logs show the upstream envoy sends a `RST_STREAM` frame to the downstream envoy as well as the upstream service.

req:       `browser` --grpc-web--> `envoy-1` --h2--> `envoy-2` --h2--> `service`
resp:      `browser` <--503-- `envoy-1` <--RST-- `envoy-2` --RST--> `service`

A single tier envoy works as expected however. That is the browser receives a `200` status code with base64 encoded protobuf response.

*Repro steps*:
Configure a downstream envoy with a cors and grpc-web filter enabled on a route on a http2 http_connection_manager, specifying an upstream envoy cluster. Configure the upstream envoy to proxy a grpc service. Invoke a grpc-web request on the downstream, and observe `503`.
Tried envoy `v1.6.0` and grpc-go `v1.10.1` with same results.

*Config*:
Downstream envoy:
```listeners:
- address: tcp://0.0.0.0:6555
  filters:
  - name: http_connection_manager
    type: read
    config:
      add_user_agent: true
      codec_type: auto
      stat_prefix: ingress_http
      use_remote_address: true
      route_config:
        virtual_hosts:        
        - name: default
          domains: ["*"]
          routes:
          - prefix: "/"
            timeout_ms: 0
            cluster: default
            cors:
              allow_origin: ["*"]
              allow_methods: "OPTIONS"
              allow_headers: "Content-Type, Authorization, x-grpc-web, X-User-Agent"
              allow_credentials: true                          
      filters:    
      - type: decoder
        name: cors
        config: {}      
      - type: auto 
        name: grpc_web
        config: {}
      - type: decoder
        name: router        
        config: {}

statsd_udp_ip_address: 127.0.0.1:8125
admin:
  access_log_path: /var/log/admin_access.log
  address: tcp://127.0.0.1:9901

cluster_manager:
  clusters:  
  - name: default
    features: http2
    connect_timeout_ms: 100
    type: logical_dns
    lb_type: round_robin    
    hosts:  [{ url: tcp://docker.for.mac.localhost:6554 }]
```

Upstream:
```
listeners:
- address: tcp://0.0.0.0:6554
  filters:
  - name: http_connection_manager
    type: read
    config:
      add_user_agent: true
      codec_type: http2
      stat_prefix: ingress_http
      use_remote_address: true
      route_config:
        virtual_hosts:        
        - name: default
          domains: ["*"]
          routes:
          - prefix: "/"            
            cluster: default            
      filters:
      - type: decoder
        name: router
        config: {}      
statsd_udp_ip_address: 127.0.0.1:8125
admin:
  access_log_path: /var/log/admin_access.log
  address: tcp://127.0.0.1:9901

cluster_manager:
  clusters:  
  - name: default
    connect_timeout_ms: 100
    type: logical_dns
    lb_type: round_robin
    features: http2
    hosts:  [{ url: tcp://docker.for.mac.localhost:5461 }]
```

*Logs*:
Upstream envoy:
```[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:309] [C3] dispatched 582 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:507] [C3] send data: bytes=15
[2018-03-29 18:28:44.116][11][trace][connection] source/common/network/connection_impl.cc:300] [C3] writing 15 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:467] [C3] sent frame type=4
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:507] [C3] send data: bytes=9
[2018-03-29 18:28:44.116][11][trace][connection] source/common/network/connection_impl.cc:300] [C3] writing 9 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:467] [C3] sent frame type=4
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:507] [C3] send data: bytes=13
[2018-03-29 18:28:44.116][11][trace][connection] source/common/network/connection_impl.cc:300] [C3] writing 13 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:467] [C3] sent frame type=8
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:507] [C3] send data: bytes=13
[2018-03-29 18:28:44.116][11][trace][connection] source/common/network/connection_impl.cc:300] [C3] writing 13 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:467] [C3] sent frame type=3
[2018-03-29 18:28:44.116][11][debug][http2] source/common/http/http2/codec_impl.cc:477] [C3] sent reset code=1
[2018-03-29 18:28:44.116][11][debug][http2] source/common/http/http2/codec_impl.cc:518] [C3] stream closed: 1
[2018-03-29 18:28:44.116][11][debug][router] source/common/router/router.cc:856] [C3][S12760462210153772685] resetting pool request
[2018-03-29 18:28:44.116][11][debug][client] source/common/http/codec_client.cc:91] [C4] request reset
[2018-03-29 18:28:44.116][11][trace][main] source/common/event/dispatcher_impl.cc:133] item added to deferred deletion list (size=1)
[2018-03-29 18:28:44.116][11][debug][pool] source/common/http/http2/conn_pool.cc:186] [C4] destroying stream: 0 remaining
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:507] [C4] send data: bytes=13
[2018-03-29 18:28:44.116][11][trace][connection] source/common/network/connection_impl.cc:300] [C4] writing 13 bytes
[2018-03-29 18:28:44.116][11][trace][http2] source/common/http/http2/codec_impl.cc:467] [C4] sent frame type=3
[2018-03-29 18:28:44.116][11][debug][http2] source/common/http/http2/codec_impl.cc:477] [C4] sent reset code=0
[2018-03-29 18:28:44.116][11][debug][http2] source/common/http/http2/codec_impl.cc:518] [C4] stream closed: 0```
