### ISSUE TITLE
Dynamic Forward Proxy with Static Hosts

### ISSUE THREAD

**Issue by brvn0c** [envoyproxy/envoy#29452]
*Title*: *Dynamic Forward Proxy with Static Hosts*

*Description*:
I have deployed Envoy as a dynamic forward proxy and it is working correctly. However, there is a need to set custom hosts that are not in a DNS, similar to placing them in the `/etc/hosts` file. In this example, I want to match the domain _example.corp_ to the IP address 192.168.1.1.

I have tried this configuration:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: https_passthrough
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                upgrade_configs:
                  - upgrade_type: CONNECT
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: custom_hosts
                      domains: ["example.corp"]
                      typed_per_filter_config:
                        envoy.config.route.v3.FilterConfig:
                          "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                          config:
                            "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                          disabled: true
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: security_service
                        - match:
                            connect_matcher: {}
                          route:
                            cluster: security_service
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config: {}
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                        - match:
                            connect_matcher: {}
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config: {}
                http_filters:
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                        typed_dns_resolver_config:
                          name: envoy.network.dns_resolver.cares
                          typed_config:
                            "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                            resolvers:
                              - socket_address:
                                  address: "8.8.8.8"
                                  port_value: 53
                            use_resolvers_as_fallback: true
                            dns_resolver_options:
                              use_tcp_for_dns_lookups: true
                              no_default_search_domain: true
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: dynamic_forward_proxy_cluster
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
            typed_dns_resolver_config:
              name: envoy.network.dns_resolver.cares
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                resolvers:
                  - socket_address:
                      address: "8.8.8.8"
                      port_value: 53
                use_resolvers_as_fallback: true
                dns_resolver_options:
                  use_tcp_for_dns_lookups: true
                  no_default_search_domain: true
    - name: security_service
      type: STATIC
      load_assignment:
        cluster_name: security_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 192.168.1.1
                      port_value: 443
```
However, requests to example.corp are logging as 
```
CONNECT - HTTP/1.1" 503 UH 0 19 0 - "-" "PostmanRuntime/7.32.3" "example.corp:443" "-"
```

My initial thought was that the *dynamic_forward_proxy* http_filter should be skipped, as per [this issue](https://github.com/envoyproxy/envoy/pull/27210), but it was not the solution.

Any help is kindly appreciated.

Bruno
