### ISSUE TITLE
Application log: Add a format flag for log tags

### ISSUE THREAD

**Issue by mkauf** [envoyproxy/envoy#29523]
Envoy 1.27 introduced *log tags* in the application log. Currently the connection ID and the stream ID are log tags. They are added to the log messages as a prefix (if a [text_format](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-field-config-bootstrap-v3-bootstrap-applicationlogconfig-logformat-text-format) is configured) or as JSON keys (if a [json_format](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto#envoy-v3-api-field-config-bootstrap-v3-bootstrap-applicationlogconfig-logformat-json-format) is configured).

Currently, it's not possible to configure the JSON key names for the log tags. They are always the same as the log tag name, e.g. `{"ConnectionId":"0","StreamId:"123"}`. This is unfortunate, because some log systems prefer JSON keys in snake_case instead of CamelCase, e.g. `{"connection_id":"0","stream_id:"123"}`. One example is the [Elastic Common Schema](https://www.elastic.co/guide/en/ecs/current/index.html) (ECS).

**Feature request**: Implement a [log format flag](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-log-format) that can reference log tags, e.g. "%Z(Tag-Name)". A configuration like this should be possible:
```
application_log_config:
  log_format:
    json_format:
      message: "%j"
      my_custom_fields:
        log_tags:
          connection_id: "%Z(ConnectionId)"
          stream_id: "%Z(StreamId)"
```

Example log line for this configuration:
```
{"message":"test message","my_custom_fields":{"log_tags":{"connection_id":123,"stream_id":456}}}
```
