### ISSUE TITLE
Adding cors.v3.policy would not allow the envoy container to start

### ISSUE THREAD

**Issue by mkokabi** [envoyproxy/envoy#29530]
*Title*: *cors not working*

*Description*:
I have a yaml config as following and the docker doesn't start and crash with
rror initializing configuration '/etc/envoy/config.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy for type Any)

*Repro steps*:
> Including the typed_per_filter_config: section in my config

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 7071
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: local_route
            virtual_hosts:
            - name: www
              domains:
              - "*"
              typed_per_filter_config:
                envoy.filters.http.cors:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                  allow_origin_string_match:
                  - safe_regex:
                      regex: \*
                  allow_methods: "GET"
                  filter_enabled:
                    default_value:
                      numerator: 100
                      denominator: HUNDRED
                    runtime_key: cors.www.enabled
                  shadow_enabled:
                    default_value:
                      numerator: 0
                      denominator: HUNDRED
                    runtime_key: cors.www.shadow_enabled
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: portal-service
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: portal-service
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: portal-service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: portal-api
                port_value: 80
```

*Logs*:
`
error initializing configuration '/etc/envoy/config.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy for type Any): {"admin":{"address":{"socket_address":{"address":"0.0.0.0","protocol":"TCP","port_value":9901}},"access_log_path":"/tmp/admin_access.log"},"static_resources":{"clusters":[{"name":"portal-service","type":"LOGICAL_DNS","dns_lookup_family":"V4_ONLY","load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":80,"address":"portal-api"}}}}]}],"cluster_name":"portal-service"},"connect_timeout":"0.25s","lb_policy":"ROUND_ROBIN"}],"listeners":[{"filter_chains":[{"filters":[{"name":"envoy.filters.network.http_connection_manager","typed_config":{"http_filters":[{"name":"envoy.filters.http.cors","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors"}},{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"codec_type":"AUTO","stat_prefix":"ingress_http","@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","access_log":[{"name":"envoy.access_loggers.stdout","typed_config":{"@type":"type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog"}}],"route_config":{"name":"local_route","virtual_hosts":[{"name":"www","domains":["*"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"portal-service"}}],"typed_per_filter_config":{"envoy.filters.http.cors":{"filter_enabled":{"runtime_key":"cors.www.enabled","default_value":{"numerator":100,"denominator":"HUNDRED"}},"shadow_enabled":{"default_value":{"denominator":"HUNDRED","numerator":0},"runtime_key":"cors.www.shadow_enabled"},"allow_methods":"GET","allow_origin_string_match":[{"safe_regex":{"regex":"\\*"}}],"@type":"type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy"}}}]}}}]}],"address":{"socket_address":{"port_value":7071,"address":"0.0.0.0"}}}]}}
`

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
