### ISSUE TITLE
oauth2 filter support per-route configuration

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#29641]
*Title*: *oauth2 filter support per-route configuration*

*Description*:
Currently, oauth2 filter can only be configured in the `http_filters` section of the `HCM`. It would be very useful to enable oauth2 filter to support per-route configuration, so users can also configure oauth2 at route level.

Here's a rough idea on how to make the oauth2 filter support per-rout configuration:

### API Changes

1. Adding an OIDC Provider Map: Let's include a map in the filter configuration to set up OIDC providers.

```yaml
providers:
   provider1:
     token_endpoint:
       cluster: oauth
       uri: oauth.com/token
       timeout: 3s
     authorization_endpoint: https://oauth.com/oauth/authorize/
     redirect_uri: "%REQ(x-forwarded-proto)%://%REQ(:authority)%/callback"
     redirect_path_matcher:
       path:
         exact: /callback
     signout_path:
       path:
         exact: /signout
     credentials:
       client_id: foo
       token_secret:
         name: token
         sds_config:
           path: "/etc/envoy/token-secret-foo.yaml"
       hmac_secret:
         name: hmac
         sds_config:
           path: "/etc/envoy/hmac-foo.yaml"
  provider2:
     token_endpoint:
       cluster: oauth
       uri: oauth.com/token
       timeout: 3s
     authorization_endpoint: https://oauth.com/oauth/authorize/
     redirect_uri: "%REQ(x-forwarded-proto)%://%REQ(:authority)%/callback"
     redirect_path_matcher:
       path:
         exact: /callback
     signout_path:
       path:
         exact: /signout
     credentials:
       client_id: bar
       token_secret:
         name: token
         sds_config:
           path: "/etc/envoy/token-secret-bar.yaml"
       hmac_secret:
         name: hmac
         sds_config:
           path: "/etc/envoy/hmac-bar.yaml"
```

2.  Using Map Keys for Per-Route Config: In the per-route configuration, use the map key to point to a specific provider:

```yaml
          route_config:
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/app1"
                route:
                  cluster: app1_service
                typed_per_filter_config:
                  envoy.filters.http.csrf:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
                    provider: provider1
               - match:
                  prefix: "/app2"
                route:
                  cluster: app1_service
                typed_per_filter_config:
                  envoy.filters.http.csrf:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
                    provider: provider2              
```

3. Backwards Compatible

The current `config` will be reserved for backward-compatible, but will be declared as deprecated. A new `default` will be added as the global default.

```yaml
providers:
  provider1:
     ......
default: provider1
config:  // deprecated
  token_endpoint:
    cluster: oauth
    uri: oauth.com/token
    timeout: 3s
   ......
```

### Token Cookies

The oauth2 filter stores tokens in cookies. Since all the HTTP requests on the same domain share the same cookies, it will mess up the tokens even if we do per-route OIDC configuration.  

Solution: we could namespace through cookie-name by prefixing cookie-name with provider kyes. To avoid exposing tokens to requests that they don't have access to, we can remove cookies for non-matching providers prior to sending requests to upstreams.

**Comment by adisuissa** [comment]
Not an oauth expert, but I think it may be possible to support per-route override (similar to [ext-authz](https://github.com/envoyproxy/envoy/blob/272d8e4983c920e2d1fe68c345fab58c12e4e345/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L335) and others).

cc @derekargueta @mattklein123 as oauth2 code-owners

**Comment by zhaohuabing** [comment]
I would like to work on this if it's not taken yet.

**Comment by zhaohuabing** [comment]
@derekargueta @mattklein123 I'd appreciate your input on this proposal. If you agree with the proposed approach, I'll go ahead and make a PR. Thanks.

**Comment by zhaohuabing** [comment]
Close this because we can achieve per-route oauth2 using [route level filter disable support](https://github.com/envoyproxy/envoy/pull/27210).

**Comment by reinoudk** [comment]
👋 Sorry to bring up such an old thread again @zhaohuabing , but with how I understand route level filter disable support, how would this work? It would need to have the OAuth2 filter defined (but disabled) on the listener level multiple times, with the route-level config enabling the specific OAuth2 filter that is needed, right? If so, it's not possible to define the OAuth2 filter on the listener multiple times, or is it? 

If using route level filter disable support is not a viable solution after all, could this issue be reopened? Having this would enable to perform more granular authz on the IdP side, as one could have one OAuth/OIDC app per route.

**Comment by leonardbiofi** [comment]
I am also very interested in this feature. I am having a hard time understand how to disable/enable it at the route level. 

However the Oauth2PerRoute config does not exist. Will it be supported in the future ? 
```yaml
typed_per_filter_config:
                  oauth2:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2PerRoute
                    disabled: true  # 👈 Explicitly disable oauth2 here
```

Which typed config should be used ?
