### ISSUE TITLE
stats: GRPC_BRIDGE_* not working correctly

### ISSUE THREAD

**Issue by zirain** [envoyproxy/envoy#29735]
GRPC stats not working correctly if service name contains `.`

reproduce with following configuration:

docker-compose.yml

```yaml
version: "3"
services:
  # Envoy
  envoy:
    depends_on:
      - greeter
    image: envoyproxy/envoy:v1.27.0
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "info"]
    ports:
      - "10000:10000"
      - "19000:19000" # admin interface
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  greeter:
    # image build from https://github.com/GoogleCloudPlatform/istio-samples/tree/master/sample-apps/grpc-greeter-go/server
    image: ghcr.io/zirain/grpc-greeter-go-server
    command:
      - "--address=:8080"

  client:
    depends_on:
      - envoy
      - greeter
    # image build from https://github.com/GoogleCloudPlatform/istio-samples/tree/master/sample-apps/grpc-greeter-go/client
    image: ghcr.io/zirain/grpc-greeter-go-client
    environment:
      - no_proxy=envoy
      - NO_PROXY=envoy
    command:
      - --address=envoy:10000
      - --insecure

```

envoy.yaml
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 19000
stats_config:
  use_all_default_tags: true

static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      log_format:
                        text_format_source:
                          inline_string: |
                            [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %RESPONSE_CODE_DETAILS% %CONNECTION_TERMINATION_DETAILS% "%UPSTREAM_TRANSPORT_FAILURE_REASON%" %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %REQUEST_TX_DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%" %UPSTREAM_CLUSTER% %UPSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_LOCAL_ADDRESS% %DOWNSTREAM_REMOTE_ADDRESS% %REQUESTED_SERVER_NAME% %ROUTE_NAME%
                      path: /dev/stdout
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                            grpc: {}
                          route:
                            cluster: greeter_service
                http_filters:
                  - name: envoy.filters.http.grpc_stats
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                      stats_for_all_methods: true
                      enable_upstream_stats: true
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: greeter_service
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: greeter_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: greeter
                      port_value: 8080
```

got:
```bash
curl localhost:19000/stats/prometheus | grep grpc
 TYPE envoy_cluster_grpc_SayHello_0 counter
envoy_cluster_grpc_SayHello_0{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_SayHello_request_message_count counter
envoy_cluster_grpc_SayHello_request_message_count{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_SayHello_response_message_count counter
envoy_cluster_grpc_SayHello_response_message_count{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_SayHello_success counter
envoy_cluster_grpc_SayHello_success{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_SayHello_total counter
envoy_cluster_grpc_SayHello_total{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_SayHello_upstream_rq_time histogram
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="0.5"} 8
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="1"} 8
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="5"} 8
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="10"} 8
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="25"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="50"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="100"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="250"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="500"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="1000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="2500"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="5000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="10000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="30000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="60000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="300000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="600000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="1800000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="3600000"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_bucket{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service",le="+Inf"} 9
envoy_cluster_grpc_SayHello_upstream_rq_time_sum{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 20.5
envoy_cluster_grpc_SayHello_upstream_rq_time_count{envoy_grpc_bridge_method="Greeter",envoy_grpc_bridge_service="helloworld",envoy_cluster_name="greeter_service"} 9
```

expected output:
```bash
curl localhost:19000/stats/prometheus | grep grpc
# TYPE envoy_cluster_grpc_0 counter
envoy_cluster_grpc_0{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_request_message_count counter
envoy_cluster_grpc_request_message_count{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_response_message_count counter
envoy_cluster_grpc_response_message_count{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_success counter
envoy_cluster_grpc_success{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_total counter
envoy_cluster_grpc_total{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9
# TYPE envoy_cluster_grpc_upstream_rq_time histogram
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="0.5"} 8
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="1"} 8
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="5"} 8
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="10"} 8
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="25"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="50"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="100"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="250"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="500"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="1000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="2500"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="5000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="10000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="30000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="60000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="300000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="600000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="1800000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="3600000"} 9
envoy_cluster_grpc_upstream_rq_time_bucket{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service",le="+Inf"} 9
envoy_cluster_grpc_upstream_rq_time_sum{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 20.5
envoy_cluster_grpc_upstream_rq_time_count{envoy_grpc_bridge_service="helloworld.Greeter",envoy_grpc_bridge_method="SayHello",envoy_cluster_name="greeter_service"} 9

```
