### ISSUE TITLE
What does `max_retries` mean in circuit breaker

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#29762]
I just read the doc https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/circuit_breaker.proto, but I still can't quite understand what `max_retries` mean in the config of circuit breaker.

> max_retries
> The maximum number of parallel retries that Envoy will allow to the upstream cluster. If not specified, the default is 3.

Let's say I would configure `retry_policy` as below:
```
...
domains: ["example.com:*"]
retry_policy:
  num_retries: 3
routes:
- match:
    prefix: "/"
  route:
    cluster: my_cluster
...
```
As you see, I configure the retry policy with 3. So any failure of request should retry 3 times.

Now I want to configure circuit breaker for `my_cluster`.
```
clusters:
- name: my_cluster
  circuit_breakers:
    thresholds:
      max_retries: 3
...
```

I can't understand what `max_retries` mean under the circuit breaker.

Let's say that there are four clients sending requests at the same time. If all of their requests fail, the retry would be triggered because of `retry_policy`. In this case, does it mean that only the retries of three of them could work as expected, the retries of the last user would be blocked by the circuit breaker because of `max_retries: 3`? Am I right about this?
