### ISSUE TITLE
Question: TLS termination and sds 

### ISSUE THREAD

**Issue by islamyakin** [envoyproxy/envoy#29769]
Dear envoy team, 

I have a question when I want to adopt envoy proxy at our place. Later the envoy proxy will be used as TLS Termination. which is connected to each sidecar.
- Can the envoy proxy accommodate approximately 300 certificates at the edge as shown in the image below.
- if envoy can do that, is there a way/config to add the certificate dynamically. because later there will be approximately 300 certificates.

![envoy](https://github.com/envoyproxy/envoy/assets/73155834/94ab161b-34c6-491d-a58b-a4be60fe5e38)

Thank You.

**Comment by ravenblackx** [comment]
cc @adisuissa , xds appears to be your domain.

I think the answer is "yes, no problem" to 300 certs, and "something to do with XDS and control plane" for how you'd dynamically configure, those terms might be enough to get you some traction in the docs. Definitely not my forte.

**Comment by islamyakin** [comment]
> cc @adisuissa , xds appears to be your domain.
> 
> I think the answer is "yes, no problem" to 300 certs, and "something to do with XDS and control plane" for how you'd dynamically configure, those terms might be enough to get you some traction in the docs. Definitely not my forte.

Can SDS accommodate more than 1 certificate?

**Comment by adisuissa** [comment]
SDS is a protocol that allows Envoy to dynamically fetch certificates. Each cluster/listener may have a different name for the cert, so over SDS Envoy will be able to fetch multiple certificates.
Not sure what are the limitations in terms of number of certificates, but pretty sure it could be more than 300, assuming sufficient memory.

**Comment by islamyakin** [comment]
> SDS is a protocol that allows Envoy to dynamically fetch certificates. Each cluster/listener may have a different name for the cert, so over SDS Envoy will be able to fetch multiple certificates. Not sure what are the limitations in terms of number of certificates, but pretty sure it could be more than 300, assuming sufficient memory.

do you have a reference for building an sds server?, previously I used static lds with a file path, it could only hold 1 certificate

**Comment by adisuissa** [comment]
The [go-control-plane](https://github.com/envoyproxy/go-control-plane) may be able to help.
Note that if you use a static lds path, you can still use multiple SDS paths, each holding a single certificate.
I'm not sure I fully understand your settings, but both Upstream and Downstream have a Tls-Context that has the [tls_certificate_sds_secret_configs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#extensions-transport-sockets-tls-v3-commontlscontext) field, which allows for multiple named SDS configs.

**Comment by islamyakin** [comment]
> Pesawat [kendali](https://github.com/envoyproxy/go-control-plane) mungkin bisa membantu. Perhatikan bahwa jika Anda menggunakan jalur lds statis, Anda masih dapat menggunakan beberapa jalur SDS, masing-masing memiliki satu sertifikat. Saya tidak yakin saya sepenuhnya memahami pengaturan Anda, tetapi baik Upstream maupun Downstream memiliki Tls-Context yang memiliki bidang [tls_certificate_sds_secret_configs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#extensions-transport-sockets-tls-v3-commontlscontext) , yang memungkinkan beberapa konfigurasi SDS bernama.

I tried static SDS with a path downstream. However, I can only add 1 certificate. How do I add more than one certificate?

This is an example of my static SDS path configuration

file ```envoy.yaml```
```yaml
      filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context: 
                alpn_protocols: [ "h2" ]
                tls_certificate_sds_secret_configs:
                  - name: "sds-client-ds"
                    sds_config:
                      path: "certs-key.yaml"
```
file ```certs-key.yaml```

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: sds-client-ds
    tls_certificate:
      certificate_chain:
        filename: fullchain.pem
      private_key:
        filename: privkey.pem
```

My expectation is that the ```certs-key.yaml``` file can add more than 1 certificate
