### ISSUE TITLE
`RESPONSE_CODE` is always zero when added as a response header

### ISSUE THREAD

**Issue by inssein** [envoyproxy/envoy#29814]
*Title*: `RESPONSE_CODE` is always zero when added as a response header

*Description*:
I am trying to add `RESPONSE_CODE` to the header of calls going through envoy, but have not been successful. This may sound like an odd request because the call already returns status, but we have a few microservices that are responsible for communicating with third-parties and proxying the response, and we want to be 100% sure the issue is not inside the microservice.

*Repro steps*:
I have crafted what I think is the simplest possible example where envoy is doing a direct response, and the response code header is still 0. I have tons of other examples but this is the smallest.
```
static_resources:
  listeners:
    - name: reverse_proxy
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10005
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  response_headers_to_add:
                    - header:
                        key: "response-code"
                        value: "%RESPONSE_CODE%"
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "{true}"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

At this point I am thinking its just an edge-case problem, or I am missing something small but critical.
