### ISSUE TITLE
`Content-Length: 0` header breaking the gRPC HTTP/1.1 reverse bridge

### ISSUE THREAD

**Issue by natetarrh** [envoyproxy/envoy#29989]
*Title*: `Content-Length: 0` header breaking the gRPC HTTP/1.1 reverse bridge

*Description*:
>Puma 6 and above [introduced changes to HTTP/1.1 response headers](https://github.com/puma/puma/pull/2896). Specifically, a 0-byte `application/grpc` response (i.e., a Protobuf object with no non-defaults set) from a Puma 5.X server has a `Transfer-Encoding: chunked` header set but no content length header, and a 0-byte response from a Puma 6.X server has a `Content-Length: 0` header set but no transfer encoding header. The gRPC HTTP/1.1 reverse bridge fails to parse the Puma 6.X server response because it sees that the response [cannot have a body](https://github.com/squareup/envoy-fork/blob/0ec348c07a91d776874bad3a70c94ee918008553/source/common/http/http1/codec_impl.cc#L1379) and then [optimizes away](https://github.com/squareup/envoy-fork/blob/0ec348c07a91d776874bad3a70c94ee918008553/source/common/http/http1/codec_impl.cc#L1453-L1454) the [encodeData](https://github.com/envoyproxy/envoy/blob/ffad28b6c58f9895a885e418495b503c0fcb4cd0/source/extensions/filters/http/grpc_http1_reverse_bridge/filter.cc#L187) response of the gRPC HTTP/1.1 reverse bridge.

*Repro steps*:
> See [this repo](https://github.com/mattbooks/envoy-reverse-grpc-filter-error-repro/tree/main) for a minimally-reproducing test case with a gRPC request against a both a working and broken upstream HTTP server example.

*Admin and Stats Output*:
> N/A

*Config*:
```yaml
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.filters.http.grpc_http1_reverse_bridge
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_http1_reverse_bridge.v3.FilterConfig
              content_type: application/x-protobuf
              withhold_grpc_frames: true
              response_size_header: X-Content-Length
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: web_service
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: web_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 3000
```

*Logs*:
>N/A

*Call Stack*:
> N/A
