### ISSUE TITLE
access_log: add posibility to omit empty values for opentelemetry access log

### ISSUE THREAD

**Issue by gray-oni** [envoyproxy/envoy#30017]
*Title*: *access_log: add possibility to omit empty values for OpenTelemetry access log*

*Description*:
Example of configuration
```
- name: envoy.access_loggers.open_telemetry
  typed_config:
    "@type": "type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig"
    common_config:
	  log_name: "otel_logs"
	  grpc_service:
		envoy_grpc:
		  cluster_name: "otel_collector"
  	    timeout: 3s
	body:
	  kvlist_value:
	    values:
		  - key: "key1"
		    value:
			  kvlist_value:
			    values:
				  - key: "protocol"
				    value:
					  string_value: "%PROTOCOL%"
				  - key: "field1"
				    value:
					  string_value: "%REQ(:X-FIELD-DOES-NOT-EXIST)%"
		  - key: "key2"
		    value:
			  string_value: "%REQ(:X-FIELD-DOES-NOT-EXIST)%"
```

With the current implementation properties `field1` and `key2` will be sent to OpenTelementry collector with value "-".  An Access Log configuration with a large number of dynamic properties might produce a payload with a lot of properties having the default "-" value.

*Proposal*
Introduce `omit_empty_values` property the same as Envoy has for [SubstitutionFormatString](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/substitution_format_string.proto#envoy-v3-api-msg-config-core-v3-substitutionformatstring) which will omit string properties from sending if it has the default value string "-". It would help reduce the Access Log payload sent to the OTEL collector and simplify log transformation on the collector side.
