### ISSUE TITLE
Question - Examples on how to pass Mongo Client configurations into the Mongo Proxy?

### ISSUE THREAD

**Issue by tkuisel** [envoyproxy/envoy#30042]
*Title*: *Question - Examples on how to pass Mongo Client configurations into the  Envoy Mongo Proxy?*

*Description*:
Hi there - we are currently using envoy proxy on a NodeJS api to and leverage the MongoProxy. We have been able to configure the MongoProxy to pair with a TCP cluster and  it works as expected with a barebones connection string.

However, when we try to pass MongoClient configurations into the connection string when sending the call to the Envoy Proxy listener/filter, we noticed in the DEBUG mode output that the MongoClient that Envoy is using did not preserve/receive those configurations, and it was defaulting to the same MongoClient configuration every time when outputting the settings.

The configuration we specifically are looking to pass into Envoy's Mongo Client is ```readPreference```, as we want to target a specific region on our mongo database, and both regions share the same connection string.  Whenever we pass readPreference into both our application code's Mongo client, or into the localhost connection string itself that is sent to Envoy, Envoy is not picking up that configuration when it ends up setting up its own client for the Mongo Proxy in the envoy sidecar.  We confirmed that the connection string itself works fine and properly uses the right readPreference setting when we remove Envoy from the equation and just call the DB directly.

To my question: Is there a known way to configure the MongoProxy or its corresponding cluster to pass the ```readPreference``` configuration (or any configuration for that matter) into the underlying MongoClient used by Envoy?  I have not been able to find any working examples online that pass in mongo client configurations.

Here is how we are currently setting up our envoy template:
Filters:

```
- filters:
  - name: envoy.filters.network.mongo_proxy
    typed_config:
      "@type": [type.googleapis.com/envoy.extensions.filters.network.mongo_proxy.v3.MongoProxy](http://type.googleapis.com/envoy.extensions.filters.network.mongo_proxy.v3.MongoProxy)
      stat_prefix: mongodb
      access_log: /tmp/mongo_stats00.log
      emit_dynamic_metadata: true
  
  - name: envoy.tcp_proxy
    typed_config:
      "@type": [type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy](http://type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy)
      stat_prefix: ingress_tcp1
      cluster: mongo
      access_log:
        - name: envoy.file_access_log
          typed_config:
            "@type": [type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog](http://type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog)
            path: "/tmp/access1.log"
```

 Cluster:
```
- name: mongo
  connect_timeout: 20s
  type: LOGICAL_DNS
  dns_lookup_family: V4_ONLY
  load_assignment:
    cluster_name: mongo
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: {{ .Env.MONGO_HOSTNAME }}
                  port_value: 10255
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": [type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext](http://type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext)
      sni: {{ .Env.MONGO_HOSTNAME }}
```
