### ISSUE TITLE
access_log: support for logging route/listener/cluster metadata

### ISSUE THREAD

**Issue by glicht** [envoyproxy/envoy#3006]
*Title*: *access_log: support for logging route/listener/cluster metadata*

*Description*:
Suggest by @htuch during review of implementation of access log support for dynamic metadata (#2895) .  There are cases that logging route/listener/cluster metadata can come useful such as multitenant environments.

**Comment by bartebor** [comment]
@mattklein123 I think it is not addressed yet, in fact a [TODO](https://github.com/envoyproxy/envoy/blob/master/source/common/access_log/access_log_formatter.cc#L510) still exists in access log implementation. Could you consider reopening?

I have one listener with multiple virtual hosts and it looks like marking log entries with per virtual host/route data is not possible.

I could try to implement this, but need some guidance as to how you think it should be done.

**Comment by bartebor** [comment]
I found a workaround - it is possible to transfer data by setting custom header and using its value in access log definition. It is not pretty, but it works. As a bonus string data remain plain string with no quotes instead of JSON strings provided by `DYNAMIC_METADATA`.

**Comment by fxposter** [comment]
Are there any plans to proceed on this one? Adding headers will work, but this is definitely a hack.

**Comment by cpakulski** [comment]
I am working on the implementation. I believe that cluster part is taken care of by UPSTREAM_CLUSTER tag and route is taken care by ROUTE_NAME. I am going to add a formatter for VHOST.

**Comment by rgs1** [comment]
@cpakulski could this be implemented as an extension (e.g.: via #14512)?

**Comment by cpakulski** [comment]
I will try to implement it as extension.

**Comment by eeliu** [comment]
Does this awesome feature released ?

**Comment by eeliu** [comment]
Hmm, why  `connection().streamInfo().setDynamicMetadata()` not working in access_log ? I tried, but failed.

**Comment by cpakulski** [comment]
It should work. Can you share your config?

**Comment by eeliu** [comment]
I wrote a listener_filters name tcpinfo
``` yaml
listener_filters:
      - name: "abc.filters.tcpinfo"
      typed_config:
        "@type": type.googleapis.com/abc.v1.abcTcpInfoProto
        enable_logger: true

 filter_chains:
  - filters:
    -  - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.file
              typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "logs/access.log"
              json_format:
                {      
                        "net_info": "%DYNAMIC_METADATA(abc:net_info)%",
```

But when I move `streamInfo().setDynamicMetadata()` (not connection().streamInfo().setDynamicMetadata()), it working

```cpp
REGISTER_FACTORY(AbcTcpInfoConfigFactory,
                 Server::Configuration::NamedListenerFilterConfigFactory);
Network::FilterStatus Filter::onAccept(Network::ListenerFilterCallbacks& cb) {
 cb.setDynamicMetadata( abc, keyValueStruct{net_info : xxx} ); //<--not working 
}
```

I don't find the reason, please correct me
