### ISSUE TITLE
gRPC HTTP/1.1 reverse bridge filter does not allow modification of grpc-message trailer

### ISSUE THREAD

**Issue by Zjaemingo** [envoyproxy/envoy#30113]
*Title*: gRPC HTTP/1.1 reverse bridge filter does not allow modification of grpc-message trailer

*Description*:
I am sandboxing an environment with a upstream gRPC client (via postman) and downstream REST server (simple django app). Envoy will convert the gRPC request to a REST call. 

When the REST server responds with a 404, we want to add a `grpc-message` trailer to the response for the client to receive. I have tried to achieve this by adding a `grpc-message` header in the http response, and a lua filter to parse it and add it as a trailer and from there envoy should pick it up and send back as a H2 response to the grpc client, trailer included. However, the `grpc-message` trailer does not get added to the response. It seems the `grpc-message` can not be added, but other standard trailers, such as `grpc-status`, can. To add to this, it seems if the http response is an OK status (which translate to 0 status in gRPC), then we can not even edit the `grpc-status` as well. Thankfully, custom trailer messages can be freely added.

Is there a reason why we can not edit/add the `grpc-message` trailer to a response via a lua filter? If we can edit the `grpc-status` trailer somewhat freely, then it seems we should be able to edit the `grpc-message` as well?

*Repro steps*:
envoy config
```yaml
admin:
    address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
    listeners:
        -   name: listener_0
            address:
                socket_address: { address: 0.0.0.0, port_value: 10000 }
            filter_chains:
                -   filters:
                        -   name: envoy.filters.network.http_connection_manager
                            typed_config:
                                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                                stat_prefix: ingress_http
                                codec_type: AUTO
                                route_config:
                                    name: local_route
                                    virtual_hosts:
                                        -   name: local_service
                                            domains: [ "*" ]
                                            routes:
                                                -   match: { prefix: "/api" }
                                                    route:
                                                        cluster: cluster_service
                                                    typed_per_filter_config:
                                                        # per_filter_config enables the filter for this route
                                                        envoy.filters.http.grpc_http1_reverse_bridge:
                                                            "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_http1_reverse_bridge.v3.FilterConfigPerRoute
                                                            disabled: false
                                http_filters:
                                    -   name: envoy.filters.http.lua
                                        typed_config:
                                            "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                                            inline_code: |
                                                function envoy_on_response(response_handle)
                                                  if (response_handle:headers() and response_handle:trailers())
                                                  then
                                                    if (response_handle:headers():get("grpc-status")) 
                                                    then
                                                      response_handle:trailers():replace("grpc-status", response_handle:headers():get("grpc-status"))
                                                    end
                                                    if (response_handle:headers():get("grpc-message")) 
                                                    then
                                                      response_handle:trailers():replace("grpc-message", response_handle:headers():get("grpc-message"))
                                                    end
                                                  end
                                                  response_handle:trailers():add("test-custom-trailer","This trailer can be added...")
                                                end
                                    -   name: envoy.filters.http.grpc_http1_reverse_bridge
                                        typed_config:
                                            "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_http1_reverse_bridge.v3.FilterConfig
                                            content_type: application/grpc+proto
                                            withhold_grpc_frames: true
                                    -   name: envoy.filters.http.router
                                        typed_config:
                                            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    clusters:
        -   name: cluster_service
            connect_timeout: 10s
            type: strict_dns
            lb_policy: ROUND_ROBIN
            load_assignment:
                cluster_name: cluster_service
                endpoints:
                    -   lb_endpoints:
                            -   endpoint:
                                    address:
                                        socket_address:
                                            address: 127.0.0.1
                                            port_value: 80
```
create a simple gRPC definition since it is not too important for the repro, such as:
```proto
package some.service;

message SomeRequest {
    optional string msg = 1;
}

message SomResponse {
    optional string msg = 1;
}

service SomeService {
  rpc get(SomeRequest) returns (SomResponse);
}
```
make a gRPC call via localhost:1000/some.service.SomeService/get
have your REST server return a 404 Http Response, and add a header with a grpc-message, in my case:
```python
@require_POST
def some_service_rest_endpoint(request):
    from django.http import HttpResponseNotFound

    responseTest = HttpResponseNotFound(b'', content_type="application/grpc+proto")
    responseTest["grpc-status"] = 8
    responseTest["grpc-message"] = "Test Hello there grpc message"
    return responseTest
```
sample responses' trailer via postman:
<img width="1118" alt="Screenshot 2023-10-11 at 2 01 50 PM" src="https://github.com/envoyproxy/envoy/assets/114090406/824ba40e-a1bc-4309-8f4e-c5aa725d4d54">
