### ISSUE TITLE
golang filter: introduce filter manager

### ISSUE THREAD

**Issue by spacewander** [envoyproxy/envoy#30221]
*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

While developing Go plugins with the Envoy Go feature, we discovered that it's useful to provide a golang side filter manager to manage the Go plugins.

Here are the Pros of adding a new filter manager:
1. reduce the cgo calls that call into Go
2. allow sharing data between plugins' filters, for example, the cached headers
3. allow experimenting with special filter orders. For instance, specifying the order of plugins at the route level.
4. more user-friendly to write Go plugin

The Go filter manager will work similarly to the one in Envoy, for example, when `StopXXX` is returned from one of the Go plugin, the remain plugins won't be executed.

Here is the configuration of the filter manager:
```
name: golang
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
  library_id: xx
  library_path: xxx
  plugin_name: xxx
  plugin_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.FilterManagerConfig
    configs:
      - name: log
      - name: nonblocking
      - name: addHeader
        config:
          "@type": type.googleapis.com/xds.type.v3.TypedStruct
          value:
            AddReqHeaderName: "name"
            AddReqHeaderValue: "value"
```

We will add two protobuf messages for this configuration:
```
message FilterManagerConfigPerFilter {
  string name = 1 [(validate.rules).string = {min_len: 1}];
  google.protobuf.Any config = 2;
}

message FilterManagerConfig {
  repeated FilterManagerConfigPerFilter configs = 1 [(validate.rules).repeated = {min_items: 1}];
}

```

CC @doujiang24

**Comment by doujiang24** [comment]
lgtm, thanks~

1. please also show a per-route configuration example, there might be some more details that need to be confirmed, i.e, duplicated filter name, or order controlling.
2. for the data sharing, we may need to improve the dynamic metadata implementation, i.e. add Go side caching.

**Comment by spacewander** [comment]
> please also show a per-route configuration example

Here it is:
```
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
              plugins_config:
                xxx:
                  config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.FilterManagerConfig
                    configs:
                      - name: addHeader
                        config:
                          "@type": type.googleapis.com/xds.type.v3.TypedStruct
                          value:
                            AddReqHeaderName: "route"
                            AddReqHeaderValue: "value"
                      - name: log
                      - name: nonblocking

```

> .e, duplicated filter name, or order controlling.

The filter name doesn't affect the Go side filter manager. As for order controlling, the plugins inside a filter are executed one by one.

> for the data sharing, we may need to improve the dynamic metadata implementation

When talking about the sharing, I actually want to mean the sharing in our implementation, not the user's code. Sharing in the user's code would be another topic.
