### ISSUE TITLE
Envoy + OpenTelemetry causing heap overflow

### ISSUE THREAD

**Issue by inssein** [envoyproxy/envoy#30243]
We recently had an issue where the `overload_manager` was kicking in quite frequently and in the process of trying to figure out what could be causing it, we found this graph:
![image](https://github.com/envoyproxy/envoy/assets/882228/678b34b0-60d3-40d8-b83d-9b09ecbff580)

This graph is showing the metric `envoy_cluster_http2_pending_sending_bytes` and the red line is the `opentelemetry_collector` cluster. Unfortunately for us, the drops in the graph that you are seeing are from envoy running out of heap space and us manually restarting it.

In the interim, we have disabled tracing in envoy and memory usage looks much better, but we'd like to get this functionality back.

**Question**: What we are seeing is that the pending_send_bytes is going up and seems to be unbounded. Is that a bug in the tracer or something we have misconfigured / forgot to tune?

Configuration for the tracer:
```
tracing:
  provider:
    name: envoy.tracers.opentelemetry
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
      grpc_service:
        envoy_grpc:
          cluster_name: opentelemetry_collector
        timeout: 0.250s
      service_name: envoy-service
```

Configuration for the upstream cluster:
```
- name: opentelemetry_collector
  type: STRICT_DNS
  lb_policy: ROUND_ROBIN
  typed_extension_protocol_options:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      explicit_http_config:
        http2_protocol_options: {}
  load_assignment:
    cluster_name: opentelemetry_collector
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: otel-collector
              port_value: 4317
```

Looks like this configuration is also identical to what is available at https://opentelemetry.io/docs/demo/services/frontend-proxy/.
