### ISSUE TITLE
Heap size calculation for envoy

### ISSUE THREAD

**Issue by anvo1115** [envoyproxy/envoy#30280]
*Title*: *Heap size calculation for envoy*

*Description*:
We use envoy v1.26.5. We deploy it on the Kubernetes. We configured overload_manager. As I wrote in https://github.com/envoyproxy/envoy/issues/28948 we had an issue with heap constantly growing.
We are trying to calculate some dependency between envoy heap size and some metrics like: routes amount, amount of clusters for those routes, amount of requests per second. 

For example, we have 
10 clusters, 
for each cluster we have a route:
```
                      routes:
                        - match:
                            prefix: /
                          request_headers_to_add:
                            - header:
                                key: "X-Forwarded-Host"
                                value: "my-host"
                            - header:
                                key: "X-Forwarded-Port"
                                value: "%DOWNSTREAM_LOCAL_PORT%"
                            - header:
                                key: "X-Forwarded-Proto"
                                value: "%PROTOCOL%"
                          route:
                            host_rewrite_literal: my-host-rewrite:8080
                            cluster: my-host-rewrite||my-host-rewrite||8080
                            timeout: 120s
```
For 300 requests per second envoy memory ~ 100 mb.

Can you help with that?
- is 300 rps  for 100 mb is a normal value?
- what parameters/metrics influence heap size?
- is there any configuration to minimize/decrease heap size? for example, turn off statistics or other features...
