### ISSUE TITLE
Envoy odcds can only discover the first requested cluster normally, and the following clusters cannot be discovered.

### ISSUE THREAD

**Issue by chuntaojun** [envoyproxy/envoy#30305]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*

*Description*:
> Envoy odcds can only discover the first requested cluster normally, and the following clusters cannot be discovered.

> Envoy Version is 1.27.2, and go-control-plane version is 0.11.0

*Repro steps*:
> Run a server that supports ODCDS (implemented based on LinearCache in go-control-plane)
> Run envoy in docker: docker run -it  --rm -p 15001:15001 -p 15000:15000 --privileged --cap-add sys_ptrace --env SIDECAR_NAMESPACE=bookinfo -v $(pwd)/sidecar_xds_test.yaml:/sidecar_xds_test.yaml envoyproxy/envoy:dev  -c /sidecar_xds_test.yaml --log-level debug
> create to service(service-a, service-b)
> first exec "curl -H 'Host: service-a' http://127.0.0.1:15001", and will receive server response
> second exec "curl -h 'Host: service-b' http://127.0.0.1:15001", envoy will occur odcds timeout, but my odcds server already send expect service-b resource to envoy and envoy print receive deltaresponse

> And I found a phenomenon. When odcds initiated the query service-b cluster, the onConfigUpdate logical callback of OdcdsApiHelper was not executed. Normally, the next related operation should be initiated in the onConfigUpdate of OdcdsApiHelper, but it did not happen here, so I personally There are two more suspicious codes

![WeChatWorkScreenshot_3bb30c26-f62e-4034-908a-20eab85f34b2](https://github.com/envoyproxy/envoy/assets/23445172/24a6ce45-b0ce-4ad5-ac84-7ff30775b033)

*Admin and Stats Output*:

[envoy_dump.json](https://github.com/envoyproxy/envoy/files/13038055/envoy_dump.json)

*Config*:

```yaml
node:
  id: "sidecar~bookinfo/c962adc3-673e-4637-9ba8-969d755ef66a~127.0.0.1"
  cluster: "CLUSTER_NAME"
  metadata:
    polarismesh.cn/tls-mode: none
    app: reviews
    sidecar.polarismesh.cn/serviceNamespace: bookinfo
    sidecar.polarismesh.cn/serviceName: reviews
    sidecar.polarismesh.cn/openOnDemand: true
    sidecar.polarismesh.cn/odcdsServerEndpoint: xxx.xxx.xxx.xxx:15010
dynamic_resources:
  lds_config:
    api_config_source:
      api_type: DELTA_GRPC
      transport_api_version: V3
      grpc_services:
        - google_grpc:
            target_uri: xxx.xxx.xxx.xxx:15010
            stat_prefix: polarismesh
            channel_args:
              args:
                grpc.http2.max_ping_strikes:
                  int_value: 0
                grpc.keepalive_time_ms:
                  int_value: 10000
                grpc.keepalive_timeout_ms:
                  int_value: 20000
                grpc.max_receive_message_length:
                  int_value: -1
  ads_config:
    api_type: DELTA_GRPC
    transport_api_version: V3
    grpc_services:
      - google_grpc:
          target_uri: xxx.xxx.xxx.xxx:15010
          stat_prefix: polarismesh
          channel_args:
            args:
              grpc.http2.max_ping_strikes:
                int_value: 0
              grpc.keepalive_time_ms:
                int_value: 10000
              grpc.keepalive_timeout_ms:
                int_value: 20000
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000
```

*Logs*:

[envoy_server.log](https://github.com/envoyproxy/envoy/files/13038053/envoy_server.log)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
