### ISSUE TITLE
[envoy moblie]error:Didn't find a registered implementation for name: 'envoy.listener_manager_impl.default'

### ISSUE THREAD

**Issue by kdsunset** [envoyproxy/envoy#30344]
title:error:Didn't find a registered implementation for name: 'envoy.listener_manager_impl.default'
Description:
I'm attempting to create a proxy service example using Envoy Mobile on an Android application . I've tried both the official YAML example and my own, but I keep encountering this error.
 It seems like there might be an issue with my configuration.  
Thanks  for your help！

```
//build.gradle.kts
api("io.envoyproxy.envoymobile:envoy:0.5.0.20231016")
```
```
//MainActivity
 engine = AndroidEngineBuilder(application, Custom(readEnvoyConfig()))
            .addLogLevel(LogLevel.DEBUG)
            .setLogger { Log.d("MainActivity", it) }
            .build()
```
```
//envoy_config_example.yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: app
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service-https
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: service-https
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service-https
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 220.181.38.148
                      port_value: 80
```
error logs :
```
[2023-10-20 14:56:10.521][4895][critical][main] [external/envoy/source/server/server.cc:133] 
error initializing config ' static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: app
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service-https
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: service-https
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service-https
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 220.181.38.148
                      port_value: 80
 ': Didn't find a registered implementation for name: 'envoy.listener_manager_impl.default'
[2023-10-20 14:56:10.531][4895][info][main] [external/envoy/source/server/server.cc:997] exiting
[2023-10-20 14:56:10.532][4895][debug][main] [external/envoy/source/common/access_log/access_log_manager_impl.cc:21] destroyed access loggers
[2023-10-20 14:56:10.532][4895][debug][main] [external/envoy/source/common/event/dispatcher_impl.cc:89] destroying dispatcher main_thread
[2023-10-20 14:56:10.533][4895][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] init manager Server destroyed
[2023-10-20 14:56:10.534][4895][critical][assert] [library/common/engine.cc:80] panic: Didn't find a registered implementation for name: 'envoy.listener_manager_impl.default'
```

**Comment by abeyad** [comment]
Hi, if you're passing in the bootstrap on your own, you will want to use the `ApiListenerManager` in your bootstrap config, similar to what is done here: https://github.com/envoyproxy/envoy/blob/dc841d18fd45ff8043dcc0d3bb9e7f8e84768d55/mobile/library/cc/engine_builder.cc#L929C1-L932

This is how the YAML config looks: https://github.com/envoyproxy/envoy/blob/dc841d18fd45ff8043dcc0d3bb9e7f8e84768d55/mobile/test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java#L98C1-L101.

Note that you can also not pass in the Bootstrap YAML to the EngineBuilder and instead, use the EngineBuilder's functions (plus its defaults) to configure your Envoy Mobile instance.

But to get things working with your current setup, adding the ApiListenerManager as shown in https://github.com/envoyproxy/envoy/blob/dc841d18fd45ff8043dcc0d3bb9e7f8e84768d55/mobile/test/java/io/envoyproxy/envoymobile/engine/testing/QuicTestServerTest.java#L98C1-L101 should work.

Let me know if that doesn't help solve your problem!

**Comment by kdsunset** [comment]
> passing in the bootstrap on your ow

I added the listener_manager field to the configuration, and now it reports the following error (I tried all Cluster.DiscoveryType values and still the same)
//added in configuration
```
listener_manager:
  name: envoy.listener_manager_impl.api
  typed_config:
    "@type": type.googleapis.com/envoy.config.listener.v3.ApiListenerManager
````
error logs:
```
  ': Didn't find a registered cluster factory implementation for name: 'envoy.cluster.static'
 D  [2023-10-22 07:30:50.947][16754][info][main] [external/envoy/source/server/server.cc:997] exiting
 D  [2023-10-22 07:30:50.948][16754][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] init manager RTDS destroyed
 D  [2023-10-22 07:30:50.948][16754][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] RTDS destroyed
```

My purpose is to implement a front-proxy on the android application to forward the request to the specified server.
Thank you very much for your reply

**Comment by kdsunset** [comment]
@abeyad I added the listener_manager field to the configuration, and now it reports the following error (I tried all Cluster.DiscoveryType values and still the same)
//added in configuration
```
listener_manager:
  name: envoy.listener_manager_impl.api
  typed_config:
    "@type": type.googleapis.com/envoy.config.listener.v3.ApiListenerManager
````
error logs:
```
  ': Didn't find a registered cluster factory implementation for name: 'envoy.cluster.static'
 D  [2023-10-22 07:30:50.947][16754][info][main] [external/envoy/source/server/server.cc:997] exiting
 D  [2023-10-22 07:30:50.948][16754][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] init manager RTDS destroyed
 D  [2023-10-22 07:30:50.948][16754][debug][init] [external/envoy/source/common/init/watcher_impl.cc:31] RTDS destroyed
```

My purpose is to implement a front-proxy on the android application to forward the request to the specified server.
Thank you very much for your reply
