### ISSUE TITLE
envoy response 404 status code when remove x-forwarded-proto header

### ISSUE THREAD

**Issue by IsraelZeromski** [envoyproxy/envoy#30358]
*Title*: *Envoy returns status 404 without calling the service when x-forwarded-proto header is removed*

*Description*:
I add a lua filter to remove x-forwarded-proto header and the result is that envoy response 404 and does not call service

*yaml Configuration*
```
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: some_service }
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local headers = request_handle:headers()
                  request_handle:logInfo("removing header: X-Forwarded-Proto")
                  headers:remove("X-Forwarded-Proto")
                end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.133.101.81
                port_value: 8092
```

Is there another way to prevent this header from being sent to the service?

thanks in advance
