### ISSUE TITLE
Elevated upstream_cx_protocol_error count when setting cluster max_requests_per_connection

### ISSUE THREAD

**Issue by dvilaverde** [envoyproxy/envoy#30580]
*Title*: When setting `max_requests_per_connection` on an cluster, noticing elevated `upstream_cx_protocol_error` in stats

*Description*:
We just recently updated from envoy 1.18.2 to 1.27.2 and when rolling it out we immediately noticed an increase in the metric `upstream_cx_protocol_error` that wasn't previously there in 1.18.2. 

After some investigate we were able track down this issue to being related to `max_requests_per_connection`. There is a direct correlation between `max_requests_per_connection` and `upstream_cx_protocol_error`, in that setting a smaller `max_requests_per_connection` value results in more `upstream_cx_protocol_error` errors. 

When we tried repro with envoy v1.18.2, there was no impact on `upstream_cx_protocol_error` when adjusting `max_requests_per_connection` either up or down, so this looks like a regression of some sort.

The expectation is that the configuration of `max_requests_per_connection` does not cause `upstream_cx_protocol_error` to increment, as it was in previous versions of envoy.

Note: that downstream connections never see any HTTP errors during testing, all envoy responses to downstream were HTTP 200.

*Repro steps*:

I've created this docker compose to simulate the problem:

```
version: '2.4'
services:
  envoy-proxy1:
    image: envoyproxy/envoy:v1.27.2
    # image: envoyproxy/envoy:v1.18.2
    command: 
      - envoy
      - --component-log-level client:debug
      - -c /etc/envoy/envoy.yaml
    hostname: envoy1
    ports:
      - "9090:8080"
      - "9901:9901"
    volumes:
      - ./envoy1.yaml:/etc/envoy/envoy.yaml
      #- ./envoy_1.18.yaml:/etc/envoy/envoy.yaml
  
  envoy-proxy2:
    image: envoyproxy/envoy:v1.27.2
    command: 
      - envoy
      - --log-level trace
      - -c /etc/envoy/envoy.yaml
    hostname: envoy2
    volumes:
      - ./envoy2.yaml:/etc/envoy/envoy.yaml
  
  httpbin:
    image: kennethreitz/httpbin
    hostname: httpbin
    ports:
      - "9092:80"
```

Before issuing testing I gathered the stats using cURL:

```
% curl -s localhost:9901/stats | grep upstream_cx_protocol
cluster.envoy2_service.upstream_cx_protocol_error: 0
```

To reproduce I used this [hey](https://github.com/rakyll/hey) request:

```
% hey -n 20000 http://localhost:9090/anything
Summary:
  Total:        13.4786 secs
  Slowest:      0.1154 secs
  Fastest:      0.0016 secs
  Average:      0.0336 secs
  Requests/sec: 1483.8316
...

Status code distribution:
  [200] 20000 responses
```

And after the test I checked the stats endpoint again:

```
% curl -s localhost:9901/stats | grep upstream_cx_protocol
cluster.envoy2_service.upstream_cx_protocol_error: 35
```

Additionally checking the logs I see this:

```
[2023-10-28 00:40:31.002][17][debug][client] [source/common/http/codec_client.cc:128] [Tags: "ConnectionId":"30"] response complete
[2023-10-28 00:40:31.003][17][debug][client] [source/common/http/codec_client.cc:128] [Tags: "ConnectionId":"30"] response complete
[2023-10-28 00:40:31.003][17][debug][client] [source/common/http/codec_client.cc:107] [Tags: "ConnectionId":"30"] disconnect. resetting 0 pending requests
[2023-10-28 00:40:31.003][17][debug][client] [source/common/http/codec_client.cc:170] [Tags: "ConnectionId":"30"] Error dispatching received data: Connection was closed while dispatching frames
```

All the connections show the same pattern where the disconnect is happening followed immediately by the 'Error dispatching received data'.  Additionally if I check that connection for how many times it was used it is exactly 500, the same value as my `max_requests_per_connection` setting.

```
% cat envoy.log|grep "\"ConnectionId\":\"30\""|grep encode|wc -l
500
```

This seems like some sort of race condition that was introduced in later versions of envoy because this same test with envoy 1.18.2 doesn't produce any errors in the logs or in the stats.

*Config*:

Configuration for Envoy 1.27.2, file named `envoy1.yaml` in the docker compose above.

```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: envoy2_service }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              suppress_envoy_headers: 
          http_protocol_options:
            accept_http_10: true
            default_host_for_http_10: "*"
          server_name: test
    #enable_reuse_port: false
  clusters:
  - name: envoy2_service
    connect_timeout: 1s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    upstream_connection_options:
      tcp_keepalive:
        keepalive_interval: 30
        keepalive_time: 30
    load_assignment:
      cluster_name: envoy2_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy2
                port_value: 8080
    typed_extension_protocol_options:
      "envoy.extensions.upstreams.http.v3.HttpProtocolOptions":
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
        common_http_protocol_options:
          idle_timeout: 30s
          max_requests_per_connection: 500
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 64
```

Configuration for Envoy 1.18.2, file named `envoy_1.18.yaml` in the docker compose above.

```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: envoy2_service }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              suppress_envoy_headers: 
          http_protocol_options:
            accept_http_10: true
            default_host_for_http_10: "*"
          server_name: test
  clusters:
  - name: envoy2_service
    connect_timeout: 1s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    max_requests_per_connection: 500
    upstream_connection_options:
      tcp_keepalive:
        keepalive_interval: 30
        keepalive_time: 30
    load_assignment:
      cluster_name: envoy2_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy2
                port_value: 8080
    typed_extension_protocol_options:
      "envoy.extensions.upstreams.http.v3.HttpProtocolOptions":
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions"
        common_http_protocol_options:
          idle_timeout: 30s
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 64
```

Configuration for second Envoy 1.27.2, file named `envoy2.yaml` in the docker compose above:

```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: http_bin }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: http_bin
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: http_bin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin
                port_value: 80
```

*Logs*:

Envoy logs are attached.

[envoy.log.zip](https://github.com/envoyproxy/envoy/files/13194106/envoy.log.zip)
