### ISSUE TITLE
Add support for redirecting to a specific listener

### ISSUE THREAD

**Issue by georgi-d** [envoyproxy/envoy#3060]
We have a use case where some prefixes need to be redirected from one listener port to another. In most cases this is HTTP -> HTTPS but not always.

The reason this cannot be done with `host_redirect` is because the redirect needs to use the same hostname the client used when accessing the proxy which is not known statically.

One way I see this can be added is to add `listener_redirect` option to the `routes` section which takes as a parameter the name of a listener.

A sample config would look like this:

```
 static_resources:
  listeners:
  - name: "https"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
  - name: "http"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/foo"
                listener_redirect: "https"
          http_filters:
          - name: envoy.router
            config: {}
```

In this case when a request comes for `/foo` on port 80 the proxy should return a redirect for the same host the client used but for port 443. The proxy should also switch between http:// and https:// on the redirect based on whether there is TLS enabled on the target listener.

Thanks
