### ISSUE TITLE
router cluster specifier supports extension plugin based on header match

### ISSUE THREAD

**Issue by StarryVae** [envoyproxy/envoy#30624]
*Title*: *router cluster specifier supports extension plugin based on header match*

*Description*:

The extension cluster specifier plugin can support select cluster based on header match. If it is reasonable, i can try to submit a PR, thanks.

**Comment by lizan** [comment]
Can you elaborate a bit? It sounds like what http router does today.

**Comment by StarryVae** [comment]
maybe we want to select different clusters under a  route instead of creating multiple routes to simplify management of the configuration.

**Comment by StarryVae** [comment]
friendly ping @lizan , also cc @wbpcode as code owner.

**Comment by wbpcode** [comment]
**The DR of Istio may create multiple clusters for different version of same service.** We hope to select different versions based on additional header match and avoid the creations of multiple routes.

I see it as something like the subset lb: choosing subset of specific service. (subset lb is super powerful but sometimes hard to debug)

**Comment by StarryVae** [comment]
cc @lizan If this feature is reasonable, i will try to submit API first, thanks.

**Comment by StarryVae** [comment]
```
routes:
  - match:
      prefix: "/"
    route:
      inline_cluster_specifier_plugin:
        extension:
          name: condition_cluster_specifier
          typed_config:
            "@type": type.googleapis.com/proxy.router.cluster_specifier.condition_cluster_specifier.v3.ConditionClusterSpecifierConfig
            matchers:
              - matcher:
                  headers:
                    - name: foo1
                      string_match:
                        exact: bar1
                cluster: service-v1
              - matcher:
                  headers:
                    - name: foo2
                      string_match:
                        exact: bar2
                cluster: service-v2
            default_cluster: service-v1
```

here is a example, we can select different versions of same service under a route instead of creating multiple routes. @lizan
