### ISSUE TITLE
How to config access log sample for multiple layer envoy

### ISSUE THREAD

**Issue by masquee** [envoyproxy/envoy#30646]
I configured Envoy with a sampling rate of 10%, and our requests went through two layers of envoy. How to ensure that the request for sampling at the first layer will also be sampled at the second layer?

<img width="1674" alt="image" src="https://github.com/envoyproxy/envoy/assets/8470824/05c86cee-761a-4f92-8b48-9948028efbfc">

```yaml
- runtime_filter:
    runtime_key: "percent_sampled"
    percent_sampled:
      numerator: 10
      denominator: HUNDRED
```
