### ISSUE TITLE
Redis proxy with tls mode simple breaks envoy startup

### ISSUE THREAD

**Issue by armasanea** [envoyproxy/envoy#30673]
*Title*: *Redis proxy with tls mode simple breaks envoy startup*

*Description*:
Redis proxy with tls mode simple breaks envoy startup. Note that the same config works fine before app startup is attempted - redis connectivity seems to be working fine.
To put it differently, when redis cluster is added at runtime it works - associated with this message in logs:
> add/update cluster message.cluster.wbx3 starting warming

When the app attempts a restart the same configuration prevents envoy startup - associated with this message in logs:

> add/update cluster message.cluster.wbx3 during init

This seems related to envoy having 2 different paths for runtime addition of cluster vs init addition: https://github.com/envoyproxy/envoy/blob/v1.25.11/source/common/upstream/cluster_manager_impl.cc#L766-L775

*Repro steps*:
Save the below config to a file and apply: kubectl apply -f test.yaml

*Config*:
this was configured with this istio config, using istio 1.17 and envoy 1.25
```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: elasticache-redis-proxy-hello-world-test
  labels:    
    app.kubernetes.io/name: hello-world
spec:
  location: MESH_EXTERNAL
  resolution: DNS
  hosts:
    - message.elasticache-proxy.wbx3
  exportTo:
    - .
  endpoints:
    - address: clustercfg.endpoint.cache.amazonaws.com
  ports:
    - number: 36379
      name: redis
      protocol: REDIS
      targetPort: 6379

---

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: elasticache-redis-proxy-hello-world-test
  labels:    
    app.kubernetes.io/name: hello-world
spec:
  host: message.elasticache-proxy.wbx3
  exportTo:
    - .
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 500ms
        tcpKeepalive:
          time: 300s
          interval: 60s
    tls:
      mode: SIMPLE
      caCertificates: /etc/ssl/certs/ca-certificates.crt

---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: elasticache-redis-cluster-hello-world-test
  labels:    
    app.kubernetes.io/name: hello-world
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: hello-world
  configPatches:
    - applyTo: CLUSTER
      match:
        context: SIDECAR_OUTBOUND
        cluster:
          service: message.elasticache-proxy.wbx3
          portNumber: 36379
      patch:
        operation: MERGE
        value:
          name: message.cluster.wbx3
          lb_policy: CLUSTER_PROVIDED
          connect_timeout: 2s
          cluster_type:
            name: envoy.clusters.redis
            typed_config:
              "@type": type.googleapis.com/google.protobuf.Struct
              value:
                cluster_refresh_rate: 10s
                cluster_refresh_timeout: 1s
          health_checks:
            - custom_health_check:
                name: envoy.health_checkers.redis
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
              timeout: 1s
              interval: 10s
              unhealthy_threshold: 5
              healthy_threshold: 1
          typed_extension_protocol_options:
            envoy.filters.network.redis_proxy:
              "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
              auth_password:
                inline_string: passwd

---

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: elasticache-redis-proxy-hello-world-test
  labels:
    app.kubernetes.io/name: hello-world
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: hello-world
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.redis_proxy
    patch:
      operation: MERGE
      value:
        name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_stats_message
          downstream_auth_passwords:
            - inline_string: passwd
          prefix_routes:
            catch_all_route:
              cluster: message.cluster.wbx3
          settings:
            op_timeout: 2s
            enable_redirection: true
            enable_command_stats: true
            read_policy: ANY
            dns_cache_config:
              name: redis-dns-cache
              dns_lookup_family: V4_ONLY
              dns_refresh_rate: 300s
              max_hosts: 100
```

*Logs*:
failing startup logs have this related to the TLS mode simple of the cluster:
```
2023-10-31T17:01:52.220602Z	debug	envoy dns external/envoy/source/extensions/network/dns_resolver/cares/dns_impl.cc:275	dns resolution for clustercfg.ec-message-int135.jlgat1.use1.cache.amazonaws.com completed with status 0	thread=43
2023-10-31T17:01:52.220620Z	debug	envoy upstream external/envoy/source/common/upstream/upstream_impl.cc:451	transport socket match, socket default selected for host with address 172.16.164.39:6379	thread=43
2023-10-31T17:01:52.220629Z	debug	envoy config external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:398	Create NotReadySslSocket	thread=43
2023-10-31T17:01:52.220674Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:939	[C1] connecting to 172.16.164.39:6379	thread=43
2023-10-31T17:01:52.220753Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:958	[C1] connection in progress	thread=43
2023-10-31T17:01:52.220811Z	debug	envoy upstream external/envoy/source/extensions/clusters/redis/redis_cluster.cc:307	executing redis cluster slot request for 'message.cluster.wbx3'	thread=43
2023-10-31T17:01:52.221698Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:688	[C1] connected	thread=43
2023-10-31T17:01:52.221709Z	debug	envoy connection external/envoy/source/common/network/connection_impl.cc:250	[C1] closing socket: 0	thread=43
2023-10-31T17:01:52.221750Z	debug	envoy upstream external/envoy/source/extensions/clusters/redis/redis_cluster.cc:566	redis cluster slot request for 'message.cluster.wbx3' failed	thread=43
```
