### ISSUE TITLE
Proxying UDP over HTTP/2 is not working

### ISSUE THREAD

**Issue by Bfarkiani** [envoyproxy/envoy#30709]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Proxying UDP over HTTP/2*

*Description*:

I want to tunnel UDP over HTTP/2: client sends requests to the first envoy. The first Envoy creates a HTTP/2 tunnel and sends it to another upstream Envoy proxy. The upstream Envoy should unpack the UDP packet and deliver it to the destination.  
For the first Envoy, I am using the following configuration to tunnel UDP over HTTP/2, which is very similar to configuration here 
[https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-udp-over-http](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#tunneling-udp-over-http)  ( I only set the IP addresses and I did not change proxy_host and target_host)

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: foo
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: cluster_0
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          # note: proxy_host supports string substitution, for example setting "%FILTER_STATE(proxy.host.key:PLAIN)%"
          # will take the target host value from the session's filter state.
          proxy_host: proxy.host.com
          # note: target_host supports string substitution, for example setting "%FILTER_STATE(target.host.key:PLAIN)%"
          # will take the target host value from the session's filter state.
          target_host: target.host.com
          # note: The target port value can be overridden per-session by setting the required port value for
          # the filter state key ``udp.connect.target_port``.
          default_target_port: 443
          retry_options:
            max_connect_attempts: 2
          buffer_options:
            max_buffered_datagrams: 1024
            max_buffered_bytes: 16384
          headers_to_add:
          - header:
              key: original_dst_port
              value: "%DOWNSTREAM_LOCAL_PORT%"

  clusters:
  - name: cluster_0
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: upstreamEnvoyIP
                port_value: 443
```
The upstream Envoy has the following configuration. Since whatever downstream Envoy sends should be in format of Connect request, it should terminate the connect and deliver it to the destination over UDP. So, I am using the HTTP/2  CONNECT termination config here 
[https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#connect-support](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/upgrades#connect-support)

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: service_google
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT
  clusters:
  - name: service_google
    connect_timeout: 5s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: destinationIP
                port_value: 443        
```  

This configuration is not successful. No UDP packet will be delivered to the destination. Actually, the TCP connection between two Envoys will be terminated with a RST packet from upstream Envoy.  
So, How the upstream Envoy should be configured to deliver the packet as UDP to the destination? 

Thanks.
