### ISSUE TITLE
rbac: url fragment matchers

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#30724]
*Title*: rbac: url fragment matchers

*Description*:

In HTTP APIs, it is extremely common to have paths of the form `/orders/{storeid}/{orderId}/view`.

It is useful to be able to safely match over these URLs in RBAC.

RBAC [URL matching](https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/path.proto#envoy-v3-api-msg-type-matcher-v3-pathmatcher) is currently a `StringMatcher`.

One could attempt to match these urls with regex. For example, I believe the above is roughly `/orders/[^/]+/[^/]+/view`.

However, regex matching against URLs feels fraught with issues. URL parsing confusion attacks are extremely common, and has had a lot of consideration in Envoy ([path normalization](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-normalize-path), etc).

It would be great to have a first class way to match these in regex. I could see two approaches for this:

1. Adopt a new URL-aware matching setup. https://github.com/cncf/xds/pull/40/files may provide some previous discussion
2. Document, test, and support a canonical regex representation for URLs of this nature. As part of this, it would be desired that the security of this regex usage is treated the same as RBAC more broadly (e.g if the canonical regex has issues, its treated as a high severity CVE).

**Comment by howardjohn** [comment]
Kuat pointed me towards https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/match/uri_template/v3/uri_template_match.proto#extensions-path-match-uri-template-v3-uritemplatematchconfig - looks like a perfect fit if it was added to RBAC

**Comment by kyessenov** [comment]
I don't see why not as long as their relative security/stability status match each other.

**Comment by howardjohn** [comment]
It is `stable` and `robust_to_untrusted_downstream_and_upstream` which I think is the highest tier?
Seems like this could plausibly become a new `envoy.rbac.matchers.uri_template_match`?

**Comment by kyessenov** [comment]
@KSmigielski please take a look at other similar PRs, e.g. https://github.com/envoyproxy/envoy/pull/23828. There are two parts to the change - an API addition, and an implementation. You can combine them, but they'd be reviewed separately, starting from the API.

**Comment by sschepens** [comment]
So this is currently an extension, I guess the question is if we want to use the extension from rbac, which would make it very verbose, it would look something like this:
```yaml
action: ALLOW
policies:
  "policy":
    permissions:
        - uri_template_match:
            name: envoy.path.match.uri_template.uri_template_matcher
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
              path_template: "/something"
        - uri_template_match:
            name: envoy.path.match.uri_template.uri_template_matcher
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig
              path_template: "/somethingelse"
```

Or do we want to incorporate the extension as part of RBAC? if we do so, do we maintain the extension for the Route usages? 🤔
