### ISSUE TITLE
MaxMind GeoIP Provider doesn't work on MacOS

### ISSUE THREAD

**Issue by zvlb** [envoyproxy/envoy#30764]
MacOS version:
```bash
sw_vers
ProductName:		macOS
ProductVersion:		13.4.1
...
```

Envoy version:
```bash
envoy --version
envoy  version: b5ca88acee3453c9459474b8f22215796eff4dde/1.28.0/Distribution/RELEASE/BoringSSL
```

Envoy Config-file:
```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 8081

static_resources:
  listeners:
  - name: listener
    enable_reuse_port: false
    address:
      socket_address:
        protocol: TCP 
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - name: "test-test"
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: test-test
          use_remote_address: true
          codec_type: AUTO
          route_config:
            name: test-test
            virtual_hosts:
            - name: test-test
              domains:
              - "test.test"
              routes:
              - match:
                  prefix: "/"
                route: 
                  cluster: local-test
          http_filters:
            - name: envoy.filters.http.geoip
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.geoip.v3.Geoip
                provider:
                  name: envoy.geoip_providers.maxmind
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig
                    common_provider_config:
                      geo_headers_to_add:
                        country: "X-Location-Country"
                        city: "X-Location-City"
                    city_db_path: "/Users/zvlb/GeoIP/GeoIP2-City.mmdb"
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  -   name: local-test
      connect_timeout: 1s
      lb_policy: LEAST_REQUEST
      type: STATIC
      load_assignment:
        cluster_name: local-test
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 8765
```

Envoy Logs:
> [2023-11-06 14:25:58.529][261372][warning][misc] [source/common/protobuf/message_validator_impl.cc:35] message 'envoy.extensions.filters.http.geoip.v3.Geoip' is contained in proto file 'envoy/extensions/filters/http/geoip/v3/geoip.proto' marked as work-in-progress. API features marked as work-in-progress are not considered stable, are not covered by the threat model, are not supported by the security team, and are subject to breaking changes. Do not use this feature without understanding each of the previous points.
> [2023-11-06 14:25:58.531][261372][critical][main] [source/server/server.cc:133] error initializing config '  ./geo-ip.yml': Didn't find a registered implementation for 'envoy.geoip_providers.maxmind' with type URL: 'envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig'
> [2023-11-06 14:25:58.531][261372][info][main] [source/server/server.cc:997] exiting
Didn't find a registered implementation for 'envoy.geoip_providers.maxmind' with type URL: 'envoy.extensions.geoip_providers.maxmind.v3.MaxMindConfig'

*Some Details:*

I [ask about this question in Slack](https://envoyproxy.slack.com/archives/C78M4KW76/p1699273686075619), and @nezdolik found reason - https://github.com/envoyproxy/envoy/pull/28490/commits/d5fdbf7ec0027a74c1d1c0d800d636ae382f26b2
