### ISSUE TITLE
Use Envoy as tcp/http proxy for all outbound traffic

### ISSUE THREAD

**Issue by wknd-dev** [envoyproxy/envoy#3078]
Hello,

Thank you for sharing this wonderful project.

We want to route all inbound & outbound traffic from our node app via envoy. Inbound config is easy and have plenty of examples. 

Our outbound traffic does not have fixed hosts/port so egress examples that route traffic to fixed target are not helping.

Going through documentation, came across _original_dst_ and wondering this can be used to tcp/http proxy for all outbound traffic from server? 

Pls let me know if following config will serve the purpose  - 
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8081
    listener_filters:
      name: envoy.listener.original_dst
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          tracing:
            operation_name: egress
          codec_type: auto
          stat_prefix: egress_http
          route_config:
            name: local_egress_route
            virtual_hosts:
            - name: outbound-vh
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: outbound-cluster
                retry_policy:
                  retry_on: 5xx
                  num_retries: 3
                decorator:
                  operation: outbound-proxy
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: outbound-cluster
    connect_timeout: 1s
    type: original_dst
    lb_policy: original_dst_lb
    cleanup_interval_ms: 60000
  - name: zipkin
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: zipkin
        port_value: 9411
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: zipkin
      collector_endpoint: "/api/v1/spans"
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
With above config, we plan to use https://www.npmjs.com/package/global-tunnel to route outbound traffic through envoy sidecar as - 
```
globalTunnel.initialize({
  host: '127.0.0.1',
  port: 8081,
  sockets: 50  
});
```
