### ISSUE TITLE
Envoy crashes when using static as the cluster_type

### ISSUE THREAD

**Issue by xocasdashdash** [envoyproxy/envoy#3083]
*Envoy crashes when using static as the cluster_type*

*Description*:
Envoy should not crash

*Repro steps*:
Using the following config envoy crashes when trying to check the config:
```bash
/usr/local/bin/envoy --mode validate -c /opt/envoy/config.yaml --v2-config-only --service-cluster envoy --service-node
```

```yaml
admin:
  access_log_path: /var/log/envoy.admin.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - config:
          codec_type: auto
          http_filters:
          - config: {}
            name: envoy.router
          route_config:
            name: local_route
            virtual_hosts:
            - domains:
              - '*'
              name: cluster
              routes:
                match:
                  prefix: /
                route:
                  cluster: a-cluster
                  prefix_rewrite: /
          stat_prefix: ingress_http
        name: envoy.http_connection_manager
  clusters:
  - connect_timeout: 0.25s
    health_checks:
    - healthy_threshold: 3
      http_health_check:
        path: /health
      interval:
        seconds: 30
      interval_jitter:
        seconds: 4
      reuse_connection: true
      timeout:
        seconds: 2
      unhealthy_threshold: 5
    hosts:
    - socket_address:
        address: 10.1.1.10
        port_value: '8080'
    - socket_address:
        address: 10.1.1.9
        port_value: '8080'
    - socket_address:
        address: 10.1.1.8
        port_value: '8080'
    - socket_address:
        address: 10.1.1.11
        port_value: '8080'
    lb_policy: round_robin
    name: a-cluster
    outlier_detection:
      base_ejection_time:
        seconds: 30
      consecutive_5xx: 10
      interval:
        seconds: 10
      max_ejection_percent: 15
    type: static        
stats_sinks:
  config:
    tcp_cluster_name: statsd
  name: envoy.statsd 
```
I've hit this with this versions:
- envoy-alpine-debug:1255ac81f6af588a4f0d7daa03e1b9cd8a330130
- envoy-alpine:1255ac81f6af588a4f0d7daa03e1b9cd8a330130
- envoy-alpine:da0dc5f5dac12651f211e321f9cd7b2c70bedde9
*Config*:
>Include the config used to configure Envoy.

*Logs*:
No logs are produced. It crashes on start.

*Call Stack*:
I'm not able to decode the backtrace with the available tools
https://gist.github.com/xocasdashdash/c416b5891f956d7468c96c204f8e13a4
