### ISSUE TITLE
rbac: allow HttpAttributesCelMatchInput xDS Matcher

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#30839]
## Description

Today, Envoy explicitly allowlists the xDS matchers which RBAC filter could instantiate:
https://github.com/envoyproxy/envoy/blob/d3464bfd6d247530e669688c79e99c7245299df7/source/extensions/filters/http/rbac/rbac_filter.cc#L17-L54

It allow `HttpRequestHeaderMatchInput` but does not allow a more generic `HttpAttributesCelMatchInput`. It could be quite useful to allow `HttpAttributesCelMatchInput` for some advanced use-cases. 

For example, in our use-case we want to first evaluate a CEL based on some HTTP header and then further match on a list of IPs based on the result of the CEL evaluation.

Below YAML throws an error saying: _"requirement violation while creating RBAC match tree: INVALID_ARGUMENT: RBAC HTTP filter cannot match on 'type.googleapis.com/xds.type.matcher.v3.HttpAttributesCelMatchInput'"_

```yaml
static_resources:
  listeners:
    - name: my_listener
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 443
      listener_filters:
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: main_routes
                  virtual_hosts:
                    - name: main_vh
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: /
                          direct_response:
                            body:
                              inline_string: OK
                            status: 200
                http_filters:
                  - name: envoy.filters.http.rbac
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                      matcher:
                        matcher_list:
                          matchers:
                            - predicate:
                                single_predicate:
                                  input:
                                    name: host-header-match
                                    typed_config:
                                      "@type": type.googleapis.com/xds.type.matcher.v3.HttpAttributesCelMatchInput
                                  custom_match:
                                    name: header-cel-matcher
                                    typed_config:
                                      "@type": type.googleapis.com/xds.type.matcher.v3.CelMatcher
                                      expr_match:
                                        parsed_expr:
                                          expr:
                                            id: 3
                                            call_expr:
                                              function: _==_
                                              args:
                                              - id: 2
                                                select_expr:
                                                  operand:
                                                    id: 1
                                                    ident_expr:
                                                      name: request
                                                  field: path
                                              - id: 4
                                                const_expr:
                                                  string_value: "/foo"
                              on_match:
                                matcher:
                                  matcher_tree:
                                    input:
                                      name: ip
                                      typed_config:
                                        "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.SourceIPInput
                                    custom_match:
                                      name: ip-matcher
                                      typed_config:
                                        "@type": type.googleapis.com/xds.type.matcher.v3.IPMatcher
                                        range_matchers:
                                          - ranges:
                                              - address_prefix: 127.0.0.1
                                            on_match:
                                              action:
                                                name: envoy.filters.rbac.action
                                                typed_config:
                                                  "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                                                  name: deny-request
                                                  action: DENY
                                  on_no_match:
                                    action:
                                      name: action
                                      typed_config:
                                        "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                                        name: allow-request
                                        action: ALLOW
                        on_no_match:
                          action:
                            name: action
                            typed_config:
                              "@type": type.googleapis.com/envoy.config.rbac.v3.Action
                              name: allow-request
                              action: ALLOW
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
