### ISSUE TITLE
TLS error: 268435611:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST

### ISSUE THREAD

**Issue by HaimMyasnikoff** [envoyproxy/envoy#30889]
Hi Team,

We can't use envoy proxy via secure connection.

**Full error:**

external/envoy/source/extensions/transport_sockets/tls/ssl_socket.cc:219] [C28] TLS error: 268435611:SSL routines:OPENSSL_internal:HTTPS_PROXY_REQUEST.

**Configuration:**

```
  static_resources:
    clusters:
    - name: dynamic_forward_proxy_cluster
      lb_policy: CLUSTER_PROVIDED
      connect_timeout: 120s
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
    listeners:
    - name: listener_wss
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 4444
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: egress_http
            upgrade_configs:
            - upgrade_type: CONNECT
            - upgrade_type: websocket
            access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains:
                - "*"
                routes:
                - match:
                    connect_matcher: {}
                  route:
                    cluster: dynamic_forward_proxy_cluster
                    upgrade_configs:
                    - upgrade_type: CONNECT
                      connect_config: {}
                    - upgrade_type: websocket
                - match:
                    prefix: "/"
                  route:
                    cluster: dynamic_forward_proxy_cluster
            http_filters:
            - name: envoy.filters.http.dynamic_forward_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

```
