### ISSUE TITLE
SNI-based routing without TLS termination not working

### ISSUE THREAD

**Issue by HZ1234567891q2** [envoyproxy/envoy#30955]
*Title*: SNI-based routing without TLS termination

*Description*:
Based on the attached configuration, I'd expect the following to happen.

Case 1: A Client Hello with the right SNI (httpbin) is sent to Envoy. Envoy forwards it to the upstream cluster so that the Client and Cluster can do the TLS handshake.
Case 2: A Client Hello without the right SNI (httpbin) is sent to Envoy. Envoy finds no matching filters, and closes the connection.

What I actually see is that Envoy will forward the Client Hello to the Cluster in Case 2, even through the SNI is wrong.

*Repro steps*:
Run Envoy using the provided config. 

`docker run --rm -it -v $(pwd)/envoy-custom2.yaml:/envoy-custom2.yaml -p 9901:9901 -p 10000:10000 envoyproxy/envoy:dev-1cc4b96293c50eb595f5bd268cb9f6dd11217104     -c /envoy-custom2.yaml`

Send a request to Envoy using the following:
Case 1: `curl --connect-to httpbin.org:10000:localhost:10000 --insecure https://httpbin.org:10000/anything`
Case 2: `curl --insecure https://localhost:10000/anything`

The first curl command generates a Client Hello with httpbin in the SNI. You should get a response. The second one command should result in a closed connection, but instead passes.

*Admin and Stats Output*:
[server_info.txt](https://github.com/envoyproxy/envoy/files/13396749/server_info.txt)
[routes.txt](https://github.com/envoyproxy/envoy/files/13396750/routes.txt)
[clusters.txt](https://github.com/envoyproxy/envoy/files/13396751/clusters.txt)
[stats.txt](https://github.com/envoyproxy/envoy/files/13396752/stats.txt)

*Config*:
```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  # Downstream configurations
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    listener_filters:
    - name: tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    #Start network filters
    filter_chains:
    #Start filter for httpbin
    - filter_chain_match:
        server_names: ["httpbin"]
        #- httpbin
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: route_to_httpbin
          stat_prefix: https_passthrough

  # Upsteam Configurations            
  clusters:
  - name: route_to_httpbin
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: route_to_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin.org
                port_value: 443
```

*Logs*:
>Include the access logs and the Envoy logs.

Couldn't find how to get these. Please let me know and I'll be happy to attach them.

*Call Stack*:
N/A
