### ISSUE TITLE
Tracing Sampling Configuration Ignored

### ISSUE THREAD

**Issue by joshuarubin** [envoyproxy/envoy#3105]
We would like to be able to bootstrap a different sampling configuration than the runtime default, but it doesn't appear that updating our config as follows changes anything as all requests still seem to be sampled at the default 100%

```yaml
static_resources:
  listeners:
    - filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                tracing:
                  random_sampling:
                    value: 0.1
```

I'm not too familiar with the codebase, but it looks like the [this](https://github.com/envoyproxy/envoy/blob/master/source/common/tracing/http_tracer_impl.cc#L63) may be the culprit
