### ISSUE TITLE
Observed change in the load balancing behavior in v1.28.0

### ISSUE THREAD

**Issue by VishalDamgude** [envoyproxy/envoy#31126]
*Title*: *Observed change in the load balancing behavior in v1.28.0*

*Description*:
> We are currently on envoy version 1.26.1. Trying to upgrade to[ v1.28.0](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.28/v1.28.0)
We see a behavioural change in envoy lb routing. Below is our cluster config (added via CDS mgmt server), we are providing load_balancing_weight to each endpoint.
Two upstream cluster endpoints E1 and E2, single envoy.
E1 is in same/local zone of envoy, so our CDS  server allocated weight of 2
E2 is in cross zone, so weight is 1.
We expect roughly 66% requests to go to E1, 34% to go to E2. -> This is working behaviour as of 1.26.1
With v1.28.0, We get 49% and 51% distribution to E1 and E2 respectively. The endpoint weights of 2:1 are not being honored.

Can we please know what has changed. Or something incorrrect with expected behaviour.

We tried to test this with below flag set to false as suggested in the changelog, but its not giving us the old behavior.
envoy.reloadable_features.locality_routing_use_new_routing_logic

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>
```
{
     "version_info": "1270240254121585355",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "evenly_distributed_cluster",
      "type": "STATIC",
      "connect_timeout": "15s",
      "lb_policy": "LEAST_REQUEST",
      "health_checks": [
       {
        "timeout": "4s",
        "interval": "10s",
        "interval_jitter": "1s",
        "unhealthy_threshold": 6,
        "healthy_threshold": 1,
        "tcp_health_check": {},
        "event_log_path": "/dev/stdout",
        "always_log_health_check_failures": true
       }
      ],
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 20000,
         "max_pending_requests": 20000,
         "max_requests": 20000,
         "retry_budget": {
          "budget_percent": {
           "value": 25
          },
          "min_retry_concurrency": 10
         }
        },
        {
         "priority": "HIGH",
         "max_connections": 20000,
         "max_pending_requests": 20000,
         "max_requests": 20000,
         "retry_budget": {
          "budget_percent": {
           "value": 25
          },
          "min_retry_concurrency": 10
         }
        }
       ]
      },
      "dns_refresh_rate": "5s",
      "dns_lookup_family": "V4_ONLY",
      "outlier_detection": {
       "interval": "10s",
       "base_ejection_time": "30s",
       "max_ejection_percent": 10,
       "consecutive_gateway_failure": 5,
       "split_external_local_origin_errors": true,
       "consecutive_local_origin_failure": 5
      },
      "common_lb_config": {
       "healthy_panic_threshold": {
        "value": 50
       },
       "locality_weighted_lb_config": {},
       "ignore_new_hosts_until_first_hc": true
      },
      "upstream_connection_options": {
       "tcp_keepalive": {
        "keepalive_probes": 5,
        "keepalive_time": 300,
        "keepalive_interval": 5
       }
      },
      "load_assignment": {
       "cluster_name": "evenly_distributed_cluster",
       "endpoints": [
        {
         "locality": {
          "region": "use1",
          "zone": "az6",
          "sub_zone": "az6"
         },
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "172.28.0.3",
              "port_value": 80
             }
            }
           }
          }
         ],
         "load_balancing_weight": 2
        },
        {
         "locality": {
          "region": "cross-zone",
          "zone": "cross-zone",
          "sub_zone": "cross-zone"
         },
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "172.28.0.16",
              "port_value": 80
             }
            }
           }
          }
         ],
         "load_balancing_weight": 1
        }
       ],
       "policy": {
        "overprovisioning_factor": 1
       }
      },
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "common_http_protocol_options": {
         "idle_timeout": "55s",
         "max_headers_count": 170
        },
        "explicit_http_config": {
         "http_protocol_options": {
          "allow_absolute_url": false
         }
        }
       }
      },
      "respect_dns_ttl": true,
      "dns_failure_refresh_rate": {
       "base_interval": "1s",
       "max_interval": "10s"
      },
      "track_cluster_stats": {
       "timeout_budgets": true,
       "request_response_sizes": true
      }
     },
     "last_updated": "2023-11-30T07:25:10.217Z"
    },
 ```   
    

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).

**Comment by yanavlasov** [comment]
Can you try specifying runtime like so, please?
```
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      envoy.reloadable_features.locality_routing_use_new_routing_logic: false
```

**Comment by VishalDamgude** [comment]
@yanavlasov 
Tried as you suggested with below config, still the behavior is roughly equal (~50% ) distribution of load to each Endpoint.

```
layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy.reloadable_features.locality_routing_use_new_routing_logic: false

```

**Comment by VishalDamgude** [comment]
Also, we are getting expected behavior till version v1.26.6
We are seeing change in behavior in v1.27.0 itself, its not introduced in v1.28.0 it seems.

**Comment by VishalDamgude** [comment]
@yanavlasov any inputs to debug this further?

**Comment by yanavlasov** [comment]
I do not have any more inputs at this point. Looking for other maintainers suggestions.

**Comment by yanavlasov** [comment]
There are not tests for locality-based load balancing, which is why it changed without anyone noticing.
There are 999 PRs between 1.26.6 and 1.27.0 release. The only way to find the culprit is to add a test (and the possibly bisect after that).

I will mark this is a bug. It would have to wait for someone to pick it up to add the test and diagnose the problem

**Comment by wbpcode** [comment]
Seems that at least not the effect of the LB policy. Here is my local config:

```
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      envoy.reloadable_features.http1_use_balsa_parser: false
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 9090
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: host-one # prefix route
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: httpbin
                            timeout: 0s
                http_filters:
                - name: envoy.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    dynamic_stats: false
  clusters:
    - name: httpbin
      connect_timeout: 5s
      type: static
      common_lb_config:
        locality_weighted_lb_config: {}
      lb_policy: LEAST_REQUEST
      load_assignment:
        cluster_name: httpbin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 90
            locality: {"region": "use1","zone": "az6","sub_zone": "az6"}
            load_balancing_weight: 2
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 91
            locality: {"region": "cross-zone","zone": "cross-zone","sub_zone": "cross-zone"}
            load_balancing_weight: 1
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 20000
```

And here is the result:

```
httpbin::127.0.0.1:90::rq_total::200
httpbin::127.0.0.1:91::rq_total::100
```
