### ISSUE TITLE
 Envoy filter is not supporting if https request

### ISSUE THREAD

**Issue by amankumarcs** [envoyproxy/envoy#31159]
i have below ext_authz where every http request flow will go the the ext_authz OPA 
```
- applyTo: HTTP_FILTER
  match:
    context: SIDECAR_OUTBOUND
    listener:
      filterChain:
        filter:
          name: "envoy.filters.network.http_connection_manager"
        subFilter:
          name: "envoy.filters.http.router"
  patch:
    operation: INSERT_BEFORE
    value:
      name: envoy.ext_authz
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
        transport_api_version: V3
        status_on_error:
          code: ServiceUnavailable
        grpc_service:
          google_grpc:
            target_uri: 127.0.0.1:9191
          stat_prefix: "ext_authz"
```
but when request is http then it's working fine as expected. but when i request https then it's not reaching in this filter block.
