### ISSUE TITLE
Question about external authz configuration

### ISSUE THREAD

**Issue by arowden86-suki** [envoyproxy/envoy#31170]
# Description
I have `auth-service` which implements the gRPC Check method used for the external auth plugin and some other endpoints for authorization. My goal is to have calls to `service-a` to be authorized via the Check method on the `auth-service`. But with the following configuration, that method is never called and the request just times out. I have debug logs turned on on envoy, it says it's able to resolve the `auth-service` address with a 0 exit code. But there are no logs at all about making a request to it. When I remove the `ext_authz` filter, the calls go through as expected to `service-a`. If I remove `service-a` and have all traffic routed to the `auth-service`, I'm able to call any of it's endpoints and each one does call the Check method via the `ext_authz` filter. 

Have I misconfigured something? I cannot understand why it's not working as expected or how to troubleshoot this further since the logs don't really show anything. 

```
    static_resources:
        listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 443
          filter_chains:
          - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/dev/stdout"
                codec_type: AUTO
                stat_prefix: ingress_https
                route_config:
                  name: local_route
                  virtual_hosts:
                  - name: https
                    domains:
                    - "*"
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        cluster: service-a
                http_filters:
                - name: envoy.filters.http.grpc_web
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                - name: envoy.filters.http.ext_authz
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                    grpc_service:
                      envoy_grpc:
                        cluster_name: auth-service
                      timeout: 5s
                    transport_api_version: V3
                    failure_mode_allow: false
                    with_request_body:
                      max_request_bytes: 81920
                      allow_partial_message: true
                      pack_as_bytes: true
                    status_on_error:
                      code: 503
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                common_tls_context:
                  tls_certificates:
                  - certificate_chain:
                      filename: "/etc/ssl/envoy/tls.crt"
                    private_key:
                      filename: "/etc/ssl/envoy/tls.key"
        clusters:
        - name: auth_service
          connect_timeout: 0.5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: auth_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: auth_service.backend.svc.cluster.local
                          port_value: 10001
        - name: service-a
          connect_timeout: 0.5s
          type: STRICT_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          http2_protocol_options: {}
          load_assignment:
            cluster_name: service-a
            endpoints:
            - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: service-a.backend.svc.cluster.local
                      port_value: 10001
```
