### ISSUE TITLE
envoy on panic-related learning issues

### ISSUE THREAD

**Issue by suyanhj** [envoyproxy/envoy#31238]
Q: Hello, I am learning envoy, today from the official document to see panic related content, the link is as follows:
https://www.envoyproxy.io/docs/envoy/v1.28.0/intro/arch_overview/upstream/load_balancing/panic_threshold.html

After reading this document, I also entered the relevant sub-link in the page, but I did not see the relevant configuration case. Later, I tried to find help in google search, but I did not see what I wanted. Could you please tell me how to configure the new version of panic?

Here is my profile:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    name: listener_http
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: webcluster1
          http_filters:
          - name: envoy.filters.http.router

  clusters:
  - name: webcluster1
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: webcluster1
      policy:
        overprovisioning_factor: 140
      endpoints:
      - locality:
          region: cn-north-1
        priority: 0
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: webservice1
                port_value: 80
      - locality:
          region: cn-north-2
        priority: 1
        lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: webservice2
                port_value: 80
    health_checks:
    - timeout: 5s
      interval: 10s
      unhealthy_threshold: 2
      healthy_threshold: 1
      http_health_check:
        path: /livez
        expected_statuses:
          start: 200
          end: 399
```

**Comment by wbpcode** [comment]
I believe this link have pointed a specific field that used to configure the panic threshold. It's a field of cluster's `common_lb_config`.

```
    - name: example
      connect_timeout_ms: 300
      type: static
      lb_type: round_robin
      common_lb_config:
        healthy_panic_threshold:
          value: 49
      ...
```
