### ISSUE TITLE
issue connecting to external auth cluster for the first time

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#3131]
We have configured external_auth_cluster as  
```
 - name: external_auth_cluster
    connect_timeout: 0.25s
    type: EDS
    eds_cluster_config:
      eds_config: {ads: {}}
      service_name: extauthservice
    lb_policy: LEAST_REQUEST
    http2_protocol_options: {} 
```
Please note that extauthservice is deployed locally for testing on the same machine as envoy is running.
With this configuration, it consistently fails for the first request with a "gateway-time-out" error.  I increased the connect_timeout to 1s (not sure why it is required for this cluster though, we have other service clusters deployed on the same host which works fine with 0.25 s timeout), it works for few requests.
To make it consistently work for the first request, we also had to set the --drain-time-s less than the connect time out.  Also this is only for the initial request - subsequent requests work fine even with out these settings.

This seems to be a bug to me in the ext_auth filter connection management with EDS type of clusters. 
Any suggestion?

**Comment by ramaraochavali** [comment]
@saumoh @htuch any ideas on this would be very useful.

**Comment by maxmalakhov** [comment]
Could you please share the entire configuration file? Does Authorization work fine with a static cluster without EDS?
I'm not sure if it's possible right now to configure Envoy to use the embedded gRPC client to send Authorization requests and EndpointDiscoveryService requests at the same time.

**Comment by ramaraochavali** [comment]
Static Cluster with out EDS works fine IIRC. Also please note with EDS also this comes only for first few requests. Are you suspecting that for first few requests it is not able to load EDS? The error we are getting is "gateway timeout" - if we increase connect timeout it works some time.

Here is the full config
```
node:
  id: id_1
  cluster: test
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }
dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services: {envoy_grpc: {cluster_name: xds_cluster}}
  lds_config: {ads: {}}
  cds_config: {ads: {}}
static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {} 
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 15001
  - name: zipkin
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 9411
  - name: external_auth_cluster
    connect_timeout: 1s
    type: EDS
    eds_cluster_config:
      eds_config: {ads: {}}
      service_name: extauth
    lb_policy: LEAST_REQUEST
    http2_protocol_options: {} 
```
