### ISSUE TITLE
The round_robin load balance policy does not evenly distribute gRPC connections

### ISSUE THREAD

**Issue by truongdo** [envoyproxy/envoy#3132]
The round_robin load balance policy does not evenly distribute gRPC connections

*Description*:
The load balancer does not seem to route gRPC connections evenly across backends. Below is my configuation,
```
admin:
  access_log_path: /var/log/envoy/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8081 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 50051 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: my_service }
          http_filters:
          - name: envoy.router
  clusters:
  - name: my_service
    connect_timeout: 20s
    type: STRICT_DNS
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: service1, port_value: 50051 } }]
```
I confirmed that the DNS server resolves 3 backends for the address `service1` and envoy seems to have 3 backends in the cluster 

*Admin and Stats Output*:
```
cluster.my_service.membership_healthy: 3
cluster.my_service.membership_total: 3
```
When I set the DNS type to LOGICAL_DNS, it becomes
```
cluster.asr.membership_healthy: 1
cluster.asr.membership_total: 1
```
is it the desired behavior?

* With DNS type is **LOGICAL_DNS** and sending 3 concurrent requests from 1 machine: most of the time they all end up in 1 backend.
* With DNS type is **STRICT_DNS**: 3 concurrent requests seems to be distributed more evenly, but sometime only 2 backends receive request. 

Is there anything wrong with my configuration? How can I configure it so that the requests are distributed evenly across all backends?
