### ISSUE TITLE
Is it possible to make http1.1 and grpc use one same port

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#31367]
I want to know if it is possible to make http1.1 and grpc use a same port. Here is what I've tried:
```
  - name: listener_portal_https
    address:
      socket_address: *portal_ingress_https_addr    # port 9991
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        server_names: ["example.com"]
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 1200s
          access_log: *http_syslog_access_log
          upgrade_configs:
          - upgrade_type: websocket
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: redirect_service
              domains:
              - "example.com:*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_example_https
                  timeout: 3600s
              typed_per_filter_config:
                envoy.filters.http.buffer:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.buffer.v3.BufferPerRoute
                  buffer:
                    max_request_bytes: *file_size_max_bytes
              per_request_buffer_limit_bytes: *file_size_bytes_by_default
      transport_socket: *downstream_tls
      transport_socket_connect_timeout: 30s
    - filter_chain_match:
        server_names: ["grpc-example.com"]
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          common_http_protocol_options:
            idle_timeout: 3600s
          request_timeout: 1200s
          access_log: *http_syslog_access_log
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              compressor_library:
                name: text_optimized
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: ai_service
              domains: ["grpc-example.com:*"]
              routes:
              - match:
                  prefix: "/com.example.MyGrpcService"
                  headers:
                  - name: "content-type"
                    string_match: {exact: "application/grpc"}
                route:
                  cluster: cluster_example_grpc
```

As you see, I have two domain names: `example.com` and `grpc-example.com`. `example.com` is used to process requests of HTTP1.1 with TLS and `grpc-example.com` is used to process gRPC requests without TLS.

However, when I tried to create gRPC connection at the client side, I got an error:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
```

Did I do something wrong? Or HTTP1.1 and gRPC can not share the same port?
