### ISSUE TITLE
Endpoints weight are not respected from the start

### ISSUE THREAD

**Issue by StupidScience** [envoyproxy/envoy#31378]
*Title*: Endpoints weight are not respected from the start

*Description*:

When there are multiple endpoints with different weights (100 and 10 in our case), endpoints with lower weight are not being called till some point. I've done some local testing  and with these weights at least 50 of first requests are going to endpoints endpoint with higher weight. In our environment sometime it requires much more requests to reach lower weighted endpoints that results those endpoints might get no traffic at all for hours when added for some low traffic services.

*Repro steps*:
I tested locally with this envoy config:
```yaml
node:
  cluster: cluster-1
  id: envoy-instance-1
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
  access_log:
  - name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
static_resources:
  clusters:
  - name: cluster_0
    connect_timeout: 5s
    type: STATIC
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - load_balancing_weight: 100
          endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5050
      - lb_endpoints:
        - load_balancing_weight: 10
          endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 5051
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: listener_http
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            virtual_hosts:
            - name: route_0
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_0
  - name: primary
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 5050
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: primary
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            virtual_hosts:
            - name: primary
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: primary
  - name: canary
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 5051
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: canary
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            virtual_hosts:
            - name: canary
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: canary
```

And was just curling in the loop like this:
```sh
for i in {1..10}; do echo "Iteration ${i}:" && for i in {1..50}; do curl -s localhost:10000 && echo ""; done | sort | uniq -c; done
```

It almost always return `50 primary` for first iteration. Example of output:
```
Iteration 1:
  50 primary
Iteration 2:
   6 canary
  44 primary
Iteration 3:
   4 canary
  46 primary
Iteration 4:
   5 canary
  45 primary
Iteration 5:
   5 canary
  45 primary
Iteration 6:
   3 canary
  47 primary
Iteration 7:
   7 canary
  43 primary
Iteration 8:
   3 canary
  47 primary
Iteration 9:
   4 canary
  46 primary
Iteration 10:
   5 canary
  45 primary
```

Let me know if you actually need other debug information. I just do not think it is relevant here.
Tested on envoy version 1.24.2 and 1.28.0. Was able to reproduce on both of them.
