### ISSUE TITLE
Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.

### ISSUE THREAD

**Issue by andreibogdan** [envoyproxy/envoy#31429]
*Title*: *There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.*

*Description*:
I am using envoy 1.28.0 and I am receiving the message: `There is no configured limit to the number of allowed active downstream connections. Configure a limit in `envoy.resource_monitors.downstream_connections` resource monitor.`

 I looked into the documentation and I found these 2 links: [1] and [2].
I added the config like: 
```
overload_manager:
  resource_monitors:
  - name: "envoy.resource_monitors.downstream_connections"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
      max_active_downstream_connections: 10000
```
and I am getting the error: 
```
Didn't find a registered implementation for 'envoy.resource_monitors.downstream_connections' with type URL: 'envoy.extensions.resource_monitors.downstr │
│ [2023-12-18 11:59:15.145][1][info][main] [source/server/server.cc:997] exiting                                                                                                                                                                                                          │
│ Didn't find a registered implementation for 'envoy.resource_monitors.downstream_connections' with type URL: 'envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig'
```

Am I doing something wrong?

Thank you in advance.

[optional *Relevant Links*:]
>[1](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto#envoy-v3-api-msg-extensions-resource-monitors-downstream-connections-v3-downstreamconnectionsconfig)

> [2](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/overload/v3/overload.proto#config-overload-v3-resourcemonitor)

**Comment by phlax** [comment]
im also seeing this and wondering similar

**Comment by santhosh234** [comment]
can i work on this one?

**Comment by phlax** [comment]
@santhosh234 i think the first step is establishing what the issue is - possibly its a case of updating/fixing config and maybe some related docs

**Comment by santhosh234** [comment]
Hi phlax, I'm new to contributing to open source projects. Let me explain my understanding of the issue related to 'Envoy.resource_monitor.downstream_connections'. It seems that this resource monitor is responsible for monitoring downstream connections.

My task involves configuring this resource monitor to set a limit on the number of active downstream connections.
Am i right?

**Comment by phlax** [comment]
So for Envoy's CI where this problem occurs is when we run our examples - not sure if all triggers this but many do seem to

typical warning can be seen here https://github.com/envoyproxy/envoy/actions/runs/7275678141/job/19823997237#step:8:4874

This one has some config but i guess not up to date:

https://github.com/envoyproxy/envoy/blob/b039d8a316a081d1eae3e3222e045b749d26765e/examples/front-proxy/envoy.yaml#L159-L167

Im thinking if we fix our examples to prevent the warning we can resolve this ticket also

**Comment by dmazine** [comment]
Hello, I managed to configure it as follows:

```yaml
resource_monitors:
  - name: "envoy.resource_monitors.global_downstream_max_connections"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
      max_active_downstream_connections: 1000
```

Reference: [Envoy documentation 1.29.0-dev-d1d6be](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#limiting-active-connections)
