### ISSUE TITLE
How to set `x-real-ip` header.

### ISSUE THREAD

**Issue by zzjin** [envoyproxy/envoy#31428]
Is there any method to let backend upstreams get some wild-known headers, such as `x-real-ip`?

**Comment by StarryVae** [comment]
```
          request_headers_to_add:
            - header:
                key: "x-real-ip"
                value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
```

maybe config in route above can satisfy your requirement.
