### ISSUE TITLE
panic when unable to connect to stats_sinks

### ISSUE THREAD

**Issue by truongdo** [envoyproxy/envoy#3143]
*Envoy crashed on start up when unable to connect to stats_sinks*

*Description*:
When setting a wrong IP address of a dog statsd or the dog_statsd service is offline, envoy is crashed on start up.

Below is the configuration,
```
stats_sinks:
  name: envoy.dog_statsd
  config:
    address:
      socket_address:
        protocol: udp
        address: 172.25.0.512
        port_value: 8125
```
