### ISSUE TITLE
JWT-SVID support for jwt_authn filter

### ISSUE THREAD

**Issue by mattjo** [envoyproxy/envoy#31455]
*JWT-SVID restrictions*: *Add configuration options for `jwt_authn` to implement the JWT-SVID spec*

*Description*:
Based on the JWT-SVID standard, the jwt_authn filter will accept JWT-SVIDs today, but won't apply stricter requirements of the spec. Based on the standard, I believe the gaps are the following:

1. [3.1 Subject](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#31-subject): jwt_authn doesn't have restrictions on the `sub` claims for a JWT provider. To meet the standard, we should only allow SPIFFE IDs for the subject
2. [3.3 Expiration Time](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#33-expiration-time): jwt_authn needs a way to require an expiration time
3. [6.1 Publishing SPIFFE Bundle Elements](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#61-publishing-spiffe-bundle-elements): `JwtProvider` does not provide a way to require a specific `use` paramater for a JWK entry. Per the spec, only `jwt-svid` is allowed
4. [6.1 Publishing SPIFFE Bundle Elements](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#61-publishing-spiffe-bundle-elements): There's no way to specify that a given `JwtProvider` can only sign JWTs for a specific trust domain

My general proposal is to add some additional configuration to `jwt_authn` for general restrictions and maybe provide a convenience JWT-SVID configuration. The proposed changes are:

**`sub` restrictions**:
For a given `JwtProvider` add a `subjects` field similar to `audiences`. The values would be a list of acceptable subjects with wildcards. Subjects that don't match a requirement would be rejected. This also solves problem 4 above by restricting the trust domain of the subject.

Example:
```yaml
issuer: spiffe://trustdomain.example.com
subjects:
- spiffe://trustdomain.example.com/*
```

**`exp` restrictions**:
For a given `JwtProvider` add a `max_expiration` field that would be duration representing the maximum expiration of a JWT. We would need a special value for any expiration, as long as there is one.

Example:
```yaml
issuer: spiffe://trustdomain.example.com
max_expiration: 4h
```

**`use` restrictions**:
For a given `JwtProvider` add a `uses` field similar to `audiences`. This would be a filter on JWK entries in the specified JWKS.

Example
```yaml
issuer: spiffe://trustdomain.example.com
uses:
- jwt-svid
```

**Convenience config**:
To help users configure the filter correctly, we could provide a configuration similar to `extensions.transport_sockets.tls.v3.SPIFFECertValidatorConfig`. The config could be part of the `JwtProvider` or if needed we could create a new `SpiffeJwtProvider`.

Example JwtProvider extension:
```yaml
spiffe_trust_domain: trustdomain.example.com #required
max_expiration: 4h #optional, defaults to present
remote_jwks: ...
```

Would be equivalent to:
```yaml
issuer: spiffe://trustdomain.example.com
max_expiration: 4h
uses:
- jwt-svid
subjects:
- spiffe://trustdomain.example.com/*
```

*Relevant Links*:
* https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto
* https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md

**Comment by mattjo** [comment]
Oops, forgot [2.1 Algorithm](https://github.com/spiffe/spiffe/blob/main/standards/JWT-SVID.md#21-algorithm). I think we do the same thing where we have an `algorithms` field in the `JwtProvider`. Or do nothing, the diff between the spiffe spec and `jwt_authn` are only the HMAC algorithms.

**Comment by wbpcode** [comment]
@lizan

**Comment by mattjo** [comment]
Just wanted to confirm if this sounds like a reasonable direction, if so, I can start a PR.

**Comment by mattjo** [comment]
no stalebot
still in progress, but going slowly

**Comment by mattjo** [comment]
This is now implemented, except for the `use` restriction above, since the Google JWT verifier does not expose the field. To configure envoy for JWT-SVIDs, this configuration should work:

```
providers:
  spiffe_provider:
      issuer: https://spiffe.example.com
      subjects:
        prefix: spiffe://spiffe.example.com/
      require_expiration: true
```
