### ISSUE TITLE
Possible to use local rate limit by IP?

### ISSUE THREAD

**Issue by joberdick** [envoyproxy/envoy#31450]
*Title*: *Possible to use local rate limit by IP?*

*Description*:
I have been unable to get rate limit by IP to work with local http rate limits. Pieces of docs seem to imply it might be possible, but I have been unable to find any full examples.

This is example of failed attempt:
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: httpbin-ratelimit
  namespace: test
spec:
  workloadSelector:
    labels:
      app : test
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 100
                tokens_per_fill: 50
                fill_interval: 60s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append_action: APPEND_IF_EXISTS_OR_ADD
                  header:
                    key: x-rate-limited
                    value: TOO_MANY_REQUESTS
              descriptors:
              - entries:
                - key: remote_address
                  value: "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT%"
                token_bucket:
                  max_tokens: 1
                  tokens_per_fill: 1
                  fill_interval: 60s
    - applyTo: VIRTUAL_HOST
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          vhost:
            name: ""
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          rate_limits:
          - actions:
            - remote_address: {}

```

**Comment by StarryVae** [comment]
AFAIK, local ratelimit only support ip limit based on the ip configured, so here

```              descriptors:
              - entries:
                - key: remote_address
                  value: "%DOWNSTREAM_DIRECT_REMOTE_ADDRESS_WITHOUT_PORT%"
```
should be like:

```
              descriptors:
              - entries:
                - key: remote_address
                  value: 192.168.1.2
```
