### ISSUE TITLE
Possible to dynamically set the port value in `sni_dynamic_forward_proxy_filter`?

### ISSUE THREAD

**Issue by vipulx44** [envoyproxy/envoy#31481]
*Title*: *Need help dynamically setting port value in sni_dynamic_forward_proxy_filter*

*Description*:
We followed the following documentation to achieve SNI-based dynamic forward proxy.
Documentation: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/sni_dynamic_forward_proxy_filter

Our configuration is extremely similar to:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filters:
      - name: envoy.filters.network.sni_dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
          port_value: 443
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
      - name: envoy.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp
          cluster: dynamic_forward_proxy_cluster
  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
```

With this, we are able to achieve correct forwarding for CONNECT requests for URLs such as https://google.com
Eg: `curl -x http://envoy-host:envoy:port https://google.com` gives the correct response.

However,  it does not work when the URL contains a port other than 443.

The documentation mentions that it is possible to dynamically set the port value by setting a per-connection state object under the key `envoy.upstream.dynamic_port`. 

Can we have an example of this? Or maybe point me towards documentation where this is explained in more detail.

Thanks in advance!
