### ISSUE TITLE
How to configure google_grpc for continuous DNS name resolution/target service discovery?

### ISSUE THREAD

**Issue by ori-nat** [envoyproxy/envoy#31522]
Hello,

I'm using [google_grpc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#config-core-v3-grpcservice-googlegrpc) for the ext_proc filter and trying to make it continuously resolve the target URI (which belongs to a headless service with horizontal pod autoscaling) in order to discover new pod IPs for load-balancing. Currently, the gRPC client will resolve the target URI **once** on startup and therefore never discover the new pod IPs, unless all existing targets are dead.

Below is my current `grpc_service` configuration
```
grpc_service:
  google_grpc:
    target_uri: "<headless-service-name>.default.svc.cluster.local:443"
    stat_prefix: ext_proc
    channel_args:
      args:
        "grpc.lb_policy_name": { string_value: "round_robin" }
        "grpc.dns_min_time_between_resolutions_ms": { int_value: 1 }
```

With [envoy_grpc](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/grpc_service.proto#envoy-v3-api-msg-config-core-v3-grpcservice-envoygrpc), this works out-of-the-box when specifying a cluster using [strict DNS service discovery](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/service_discovery#strict-dns).

Any ideas how to achieve the same for google_grpc?
