### ISSUE TITLE
envoy.reloadable_features.send_header_raw_value causing empty headers when using ext_proc

### ISSUE THREAD

**Issue by chrislovecnm** [envoyproxy/envoy#31555]
*Description*:

I'm using a ext_proc server and sending back a `ProcessingResponse_ImmediateResponse` during the `ProcessingRequest_RequestHeaders` phase.

By default `envoy.reloadable_features.send_header_raw_value` is enabled, and this line:

https://github.com/envoyproxy/envoy/blob/21323d483ed163155fb8ceba0935c33c6dae7a2f/source/extensions/filters/http/ext_proc/mutation_utils.cc#L172

Is setting the header values to "".  So we have a header(s) with empty values.  I put in place debug logging to track down this issue, and building this project is complicated.  Thank you for having a docker build.

*Repro steps*:

I have recreated the bug using a local build on the main branch.
Here is the code that I'm using to send back the headers from the ext_proc grpc server:

```
package xdsserver

import (
	"io"

	core "github.com/envoyproxy/go-control-plane/envoy/config/core/v3"
	pb "github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3"
	v32 "github.com/envoyproxy/go-control-plane/envoy/type/v3"
	"github.com/rs/zerolog/log"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type processServer struct {
}

func (s *processServer) Process(srv pb.ExternalProcessor_ProcessServer) error {
	ctx := srv.Context()
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
			break
		default:
		}

		req, err := srv.Recv()
		if err == io.EOF {
			log.Debug().Msg("EOF received")
			return nil
		}
		if err != nil {
			log.Error().Err(err).Msg("Error received")
			return status.Errorf(codes.Unknown, "cannot receive stream request: %v", err)
		}

		resp := &pb.ProcessingResponse{}
		switch v := req.Request.(type) {
		case *pb.ProcessingRequest_RequestHeaders:
			log.Debug().Msg("ProcessingRequest_RequestHeaders")

			hm := &pb.HeaderMutation{
				SetHeaders: []*core.HeaderValueOption{
					{
						Header: &core.HeaderValue{
							Key:   "foo",
							Value: "bar",
						},
						AppendAction: core.HeaderValueOption_APPEND_IF_EXISTS_OR_ADD,
					},
				},
			}
			resp = &pb.ProcessingResponse{
				Response: &pb.ProcessingResponse_ImmediateResponse{
					ImmediateResponse: &pb.ImmediateResponse{
						Headers: hm,
						Status: &v32.HttpStatus{
							Code: v32.StatusCode_TemporaryRedirect,
						},
						Details: "set headers",
					},
				},
			}

			break
		case *pb.ProcessingRequest_RequestBody:
			log.Debug().Msg("ProcessingRequest_RequestBody")
			break
		case *pb.ProcessingRequest_ResponseHeaders:
			log.Debug().Msg("ProcessingRequest_ResponseHeaders")
			break
		case *pb.ProcessingRequest_ResponseBody:
			log.Debug().Msg("ProcessingRequest_ResponseBody")
			break
		default:
			log.Debug().Msgf("Unknown Request type %v\n", v)
		}
		if resp != nil {
			log.Debug().Interface("resp", resp).Msg("sent response")
			if err := srv.Send(resp); err != nil {
				log.Err(err).Msgf("send error %v", err)
			}
		}
		log.Debug().Msg("response sent")
	}
	return nil
}
```

I put in place the following logging to debug this bug:

```c++
   absl::string_view header_value;
    if (Runtime::runtimeFeatureEnabled("envoy.reloadable_features.send_header_raw_value")) {
      header_value = sh.header().raw_value();
      ENVOY_LOG(trace, "header_value set sh.header().raw_value(): {}", header_value);
    } else {
      header_value = sh.header().value();
      ENVOY_LOG(trace, "header_value set sh.header().value(): {}", header_value);
    }
```

And the line:

```c++
      header_value = sh.header().raw_value();
```

Is setting header_value to an empty string.

When you disable `envoy.reloadable_features.send_header_raw_value` the header value is set correctly.  So, for my use case

```c++
      header_value = sh.header().value();
```

Is the only way I can get this to work.

*Config*:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
# Uncomment this stanza, and the headers are set correctly.
#layered_runtime:
#  layers:
#    - name: static-layer
#      static_layer:
#        envoy.reloadable_features.send_header_raw_value: false
dynamic_resources:
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
      set_node_on_first_message_only: true
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: GRPC
      transport_api_version: V3
      grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster
      set_node_on_first_message_only: true
node:
  cluster: test-cluster
  id: test-id
static_resources:
  clusters:
    - connect_timeout: 1s
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: xdsserver.default.svc.cluster.local
                      port_value: 8080
      health_checks:
        timeout: 1s
        interval: 10s
        unhealthy_threshold: 2
        healthy_threshold: 2
        grpc_health_check: {}
      http2_protocol_options: {}
      name: xds_cluster
      dns_lookup_family: V4_ONLY
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options:
              connection_keepalive:
                interval: 30s
                timeout: 5s
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: render_redirect
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: /
                          redirect:
                            port_redirect: 8080
                http_filters:
                  - name: envoy.filters.http.ext_proc
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                      failure_mode_allow: false
                      mutation_rules:
                        allow_all_routing: true
                        allow_envoy: true
                      grpc_service:
                        envoy_grpc:
                          cluster_name: xds_cluster
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

*Logs*:

*Call Stack*:

It is not crashing just sending back a bad response to the http client.
