### ISSUE TITLE
Protobuf error: INVALID_ARGUMENT for typed_extension_protocol_options

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#31607]
*Title*: Can't pass values for typed_extension_protocol_options 

*Description*:
I've added an extra field in `cluster` for `envoy.filters.network.mysql_proxy`. Here is my extra part to [mysql_proxy.proto](https://github.com/envoyproxy/envoy/blob/main/api/contrib/envoy/extensions/filters/network/mysql_proxy/v3/mysql_proxy.proto):
```proto
...
message MySQLProtocolOptions {
  option (udpa.annotations.versioning).previous_message_type =
    "envoy.config.filter.network.mysql_proxy.v1alpha1.MySQLProtocolOptions";


  string auth_password = 1;
}
```
But when I applied the modified config yaml I got this error:
```bash
[2024-01-03 19:12:09.675][41858][critical][main] [source/server/server.cc:131] error initializing configuration 'envoy.yaml': Protobuf message (type envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy reason INVALID_ARGUMENT:auth_password: Cannot find field.) has unknown fields
[2024-01-03 19:12:09.675][41858][info][main] [source/server/server.cc:980] exiting
Protobuf message (type envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy reason INVALID_ARGUMENT:auth_password: Cannot find field.) has unknown fields
```
the config file- envoy.yaml:
```yaml
static_resources:
  listeners:
  - name: mysql_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
      - filters:
        - name: envoy.filters.network.mysql_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProxy
            stat_prefix: mysql
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: mysql_tcp
            cluster: mysql-cluster
      
  clusters:
  - name: mysql_cluster
    type: STRICT_DNS
    load_assignment:
      cluster_name: mysql_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ***
                port_value: 3306
    typed_extension_protocol_options:
      envoy.filters.network.mysql_proxy:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          auth_password: "jhdf"
```

**Comment by wbpcode** [comment]
If you want to add new protocol options support.

First, you should create a new message for these new options:

```
message MySQLProtocolOptions {
}
```

Second, declare it in your filter factory.

```
class MySQLConfigFactory
    : public Common::FactoryBase<envoy::extensions::filters::network::mysql_proxy::v3::MySQLProxy, 
             Common::FactoryBase<envoy::extensions::filters::network::mysql_proxy::v3::MySQLProtocolOptions> {
public:
  // ......
};
```

Third, configure it in the cluster by the actual type or typed struct:

```
    typed_extension_protocol_options:
      envoy.filters.network.mysql_proxy:
        "@type": type.googleapis.com/envoy.extensions.filters.network.mysql_proxy.v3.MySQLProtocolOptions
        auth_password: "jhdf"
```
