### ISSUE TITLE
accesslog: expose all fields in FileAccessLogger in data.accesslog.v3.AccessLog for ALS

### ISSUE THREAD

**Issue by liwanxue** [envoyproxy/envoy#31636]
*Title*: *expose all fields in FileAccessLogger into data.accesslog.v3.AccessLog for ALS*

*Description*:
>There are multiple fields availiable in [FileAccessLogger](https://github.com/envoyproxy/envoy/blob/ec4faf01d9da2a971623d79b2c28714b278d34db/source/common/formatter/stream_info_formatter.cc#L638), but some of them were not exposed in [ALS](https://github.com/envoyproxy/envoy/blob/main/api/envoy/data/accesslog/v3/accesslog.proto), considering ALS have better performance compare with FileAccessLogger  to collect access logs, expose those fields in ALS is what needed.

e.g. 
`DOWNSTREAM_PEER_ISSUER`, `UPSTREAM_PEER_CERT`, `DOWNSTREAM_PEER_FINGERPRINT_256`, `DOWNSTREAM_PEER_FINGERPRINT_1`, `DOWNSTREAM_PEER_SERIAL`, `DOWNSTREAM_HANDSHAKE_DURATION` etc...

**Comment by adisuissa** [comment]
cc @zuercher as codeowner

**Comment by zuercher** [comment]
I don't know of any reason not to add these.

**Comment by daganibhanu** [comment]
I too have a similar requirement where the properties like TRACE-USER-ID, REMOTE_USER, X-ENVOY-UPSTREAM-SERVICE-TIME 
and UBER-TRACE-ID are not available in TLS proto.

I have looped through the available request and response header map, but did not find these values?
Is there any other way to access these properties? OR is it feasible to add these to the proto?

Please share thoughts

**Comment by daganibhanu** [comment]
Found that if at we need the request headers available along with the protobuf, we may need to set them explicitly as `additional_request_headers_to_log` if its a request header attribute and `additional_response_headers_to_log` if we want to pass response headers to the envoy config.


sample config below,

```
                      common_config:
                        log_name: "access_log_grpc_test4"
                        grpc_service:
                          envoy_grpc:
                            cluster_name: grpc_access_log_service
                        transport_api_version: V3
                      additional_request_headers_to_log:
                        - "REMOTE_USER"
                        - "UBER-TRACE-ID"
                        - "DURATION"
                      additional_response_headers_to_log:
                        - "X-ENVOY-UPSTREAM-SERVICE-TIME"
```

Envoy would replace the headers with respective values and wraps them in protobuf message object.
