### ISSUE TITLE
Potential memory leak after requests ?

### ISSUE THREAD

**Issue by quantumsheep** [envoyproxy/envoy#31673]
### Description
We noticed that Envoy accumulated memory when receiving requests, never releasing it. It's especially noticeable when performing a lot of requests at once. Is it normal?

The case was found in 1.25.11 and 1.28.0. I haven't tried other versions.

The following screenshot demonstrate the effects of a spam on Envoy and shows that the memory usage never drops after the request has ended. It was done using HTTP/2.

I tried outputting a flame-graph but wasn't successful exploring the heap dump.

![Memory usage](https://github.com/envoyproxy/envoy/assets/7271496/303c7547-41e6-49f7-8c16-56e29712172a)

<details><summary>Minimal configuration</summary>
<p>

```yaml
static_resources:
  listeners:
    - name: hello_envoy
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: hello_envoy
                  virtual_hosts:
                    - name: hello_envoy_main
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: /
                          direct_response:
                            body:
                              inline_string: '{"message":"hello"}'
                            status: 200
                stat_prefix: hello_envoy
```

</p>
</details>
