### ISSUE TITLE
Combining Lua and LuaPerRoute filters

### ISSUE THREAD

**Issue by rogervinas** [envoyproxy/envoy#31723]
**Description**:

Documentation about [Lua](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-lua) and [LuaPerRoute](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/lua/v3/lua.proto#extensions-filters-http-lua-v3-luaperroute) filters is a bit confusing, one may think that LuaPerRoute script is executed in addition to Lua scripts in the main filter chain but it is not the case. In fact, **LuaPerRoute script may replace the ones in the main filter chain**.

Having the following Lua filters in the main filter chain:
|Filter|default_source_code|source_codes[A.lua]|source_codes[B.lua]|
|---|---|---|---|
|1|Global default script 1|A.lua script 1|B.lua script 1|
|2|Global default script 2|A.lua script 2|∅|

And the following routes:
| Path| LuaPerRoute filter|LUA executions|
|---|---|---|
|/lua-global|∅|Global default script 1 + Global default script 2 ✅|
|/lua-per-route-inlined|inline_string = Lua per route script|Lua per route script x **2 times** ❌|
|/lua-per-route-by-name-A|name = A.lua|A.lua script 1 + A.lua script 2 ✅|
|/lua-per-route-by-name-B|name = B.lua|B.lua script 1 ✅|
|/lua-per-route-disabled|disabled = true|∅ ✅|

The weird case is `/lua-per-route-inlined` where the inlined script replaces all the scripts in the main filter chain, resulting in the same script executed as many times as Lua filters there. Maybe this case should be considered a **bug**.

**Reproduce the issue**:

```shell
docker run --rm \
    -p 8080:8080 \
    -v ./envoy.yml:/envoy.yml \
    envoyproxy/envoy:v1.28.0 \
    /usr/local/bin/envoy -l info -c /envoy.yml

curl -i http://localhost:8080/lua-global
curl -i http://localhost:8080/lua-per-route-inlined
curl -i http://localhost:8080/lua-per-route-by-name-A
curl -i http://localhost:8080/lua-per-route-by-name-B
curl -i http://localhost:8080/lua-per-route-disabled
```

envoy.yml
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: "0.0.0.0"
        port_value: 8080
    filter_chains:
    - filters:
      - name: "envoy.filters.network.http_connection_manager"
        typed_config:
          '@type': "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          stat_prefix: "my_ingress"
          route_config:
            name: "my_route"
            virtual_hosts:
            - name: "my_virtual_host"
              domains:
              - "*"
              routes:
              - match:
                  path: "/lua-global"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Route with global LUA"
              - match:
                  path: "/lua-per-route-inlined"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Route with LUA inlined"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute"
                    source_code:
                      inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                        Executing luaPerRoute inlined script\")\nend"
              - match:
                  path: "/lua-per-route-by-name-A"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Route with LUA by name"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute"
                    name: "A.lua"
              - match:
                  path: "/lua-per-route-by-name-B"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Route with LUA by name"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute"
                    name: "B.lua"
              - match:
                  path: "/lua-per-route-disabled"
                direct_response:
                  status: 200
                  body:
                    inline_string: "Route with LUA disabled"
                typed_per_filter_config:
                  envoy.filters.http.lua:
                    '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute"
                    disabled: true
          http_filters:
          - name: "envoy.filters.http.lua"
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
              source_codes:
                A.lua:
                  inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                    Executing A.lua script #1\")\nend"
                B.lua:
                  inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                    Executing B.lua script #1\")\nend"
              default_source_code:
                inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                  Executing global default script #1\")\nend"
          - name: "envoy.filters.http.lua"
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
              source_codes:
                A.lua:
                  inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                    Executing A.lua script #2\")\nend"
              default_source_code:
                inline_string: "function envoy_on_request(handle)\n  handle:logInfo(\"\
                  Executing global default script #2\")\nend"
          - name: "envoy.filters.http.router"
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
          access_log:
          - name: "envoy.access_loggers.file"
            typed_config:
              '@type': "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
              path: "/dev/stdout"
```
