### ISSUE TITLE
Envoy does not release memory when upstream is websocket server

### ISSUE THREAD

**Issue by ningyougang** [envoyproxy/envoy#31791]
## Description

* Envoy does not release memory when upstream is websocket server
  - does not exist the problem if upstream is http server

## Repro steps

* startup a envoy container to make envoy as proxy pointing to websocket server

   ```shell
  docker run -v /envoy-websocket.yaml:/etc/envoy/envoy.yaml  -d  --name envoy-websocket-container -p 9901:9901 -p 10000:10000 \
  envoyproxy/envoy:v1.28-latest  -c /etc/envoy/envoy.yaml
  ```

* config(/envoy-websocket.yaml)

  ```yaml
  $ cat /envoy-websocket.yaml
  admin:
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9901

  static_resources:
    listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
      - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: ingress_ws_to_ws
            upgrade_configs:
            - upgrade_type: websocket
            route_config:
              name: local_route
              virtual_hosts:
              - name: app
                domains:
                - "*"
                routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: service_ws
            http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  
    clusters:
    - name: service_ws
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service_ws
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: xxx.xxx.xxx.xxx // this is my local websocket address
                  port_value: 80
  
  ```
  Fyi, i refered this article: https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/websocket

* send requests to envoy address using below client codes

  <details>
    <summary>click here to check client codes</summary>
    <pre><code>
  package main
    
    import (
    	"fmt"
    	"github.com/gorilla/websocket"
    	"strconv"
    	"strings"
    	"sync"
    	"time"
    )
    
    func main() {
    	// raw envoy
    	serverURL := "ws://$myEnvoyAddress:10000"
    	connectionCount := "500"
    	durationSeconds := "300"
    	interval := "500"
    	payloadSize := "16"
    
    	// Parse durationSeconds from string to int
    	duration, err := time.ParseDuration(durationSeconds + "s")
    	if err != nil {
    		fmt.Println("Invalid duration provided:", err)
    		return
    	}
    
    	// Convert connectionCount from string to int
    	connCount, err := strconv.Atoi(connectionCount)
    	if err != nil {
    		fmt.Println("Invalid connection count provided:", err)
    		return
    	}
    
    	sz, err := strconv.Atoi(payloadSize)
    	if err != nil {
    		fmt.Println("Invalid connection count provided:", err)
    		return
    	}
    
    	payload := strings.Repeat("a", sz*1024) // if sz==16, set 16KB payload
    
    	fmt.Println("Connecting to server:", serverURL)
    
    	// Create a wait group to wait for all goroutines to finish
    	var wg sync.WaitGroup
    
    	// Store latency values for later calculation
    	var latencies []time.Duration
    	totalConnCount := 0
    
    	errorCount := 0
    	uniqueErrors := make(map[string]int)
    	errorMutex := sync.Mutex{}
    
    	// Perform connections and communication
    	for i := 0; i < connCount; i++ {
    		wg.Add(1)
    		go func() {
    			defer wg.Done()
    
    			conn, _, err := websocket.DefaultDialer.Dial(serverURL, nil)
    			if err != nil {
    				fmt.Println("WebSocket connection error:", err)
    				errorMutex.Lock()
    				if strings.Contains(err.Error(), "read: connection reset by peer") {
    					uniqueErrors["read: connection reset by peer"]++
    				} else if strings.Contains(err.Error(), "write: broken pipe") {
    					uniqueErrors["write: broken pipe"]++
    				} else {
    					uniqueErrors[err.Error()]++
    				}
    				errorCount++
    				errorMutex.Unlock()
    				return
    			}
    			totalConnCount++
    			defer conn.Close()
    
    			// Send and receive messages for the specified duration
    			startTime := time.Now()
    
    			for time.Since(startTime) < duration {
    				// Send message
    				sendTime := time.Now()
    				err = conn.WriteMessage(websocket.TextMessage, []byte(payload))
    				if err != nil {
    					fmt.Println("Message send error:", err)
    					return
    				}
    
    				// Receive response with timeout
    				_, response, err := conn.ReadMessage()
    				if err != nil {
    					fmt.Println("Message receive error:", err)
    					errorMutex.Lock()
    					if strings.Contains(err.Error(), "read: connection reset by peer") {
    						uniqueErrors["read: connection reset by peer"]++
    					} else if strings.Contains(err.Error(), "write: broken pipe") {
    						uniqueErrors["write: broken pipe"]++
    					} else {
    						uniqueErrors[err.Error()]++
    					}
    					errorCount++
    					errorMutex.Unlock()
    					return
    				}
    
    				messageSize := len(response)
    				sizeString := fmt.Sprintf("%d Byte", messageSize)
    				if messageSize >= 1024 {
    					sizeString = fmt.Sprintf("%.2f KB", float64(messageSize)/1024)
    				}
    
    				// Calculate and store latency
    				endTime := time.Now()
    				latency := endTime.Sub(sendTime)
    				latencies = append(latencies, latency)
    
    				fmt.Printf("%d/%d %d:%d:%d Received response, size: %s\n", endTime.Month(), endTime.Day(), endTime.Hour(), endTime.Minute(), endTime.Second(), sizeString)
    
    				// Wait for 0.5 seconds before sending the next message
    				iint, err := strconv.Atoi(interval)
    				if err != nil {
    					fmt.Println("Convert str to int error:", err)
    				}
    				time.Sleep(time.Duration(iint) * time.Millisecond)
    			}
    		}()
    	}
    
    	// Wait for all goroutines to finish
    	wg.Wait()
    
    	// Calculate and display average latency
    	totalLatency := time.Duration(0)
    	for _, latency := range latencies {
    		totalLatency += latency
    	}
    	//totalCount := len(latencies)
    	averageLatency := totalLatency / time.Duration(len(latencies))
    	fmt.Println("Average latency:", averageLatency)
    	fmt.Println("Total send messages:", len(latencies))
    	fmt.Println("Total connections:", totalConnCount)
    	// Print unique error messages and count
    	fmt.Println("Total errors:", errorCount)
    	for errMsg := range uniqueErrors {
    		fmt.Println("Error:", errMsg, "(", uniqueErrors[errMsg], ")")
    	}
    }
    </code></pre>
  </details>

## check memory using ctop tool
* Before `send requests to envoy`

  ![image](https://github.com/envoyproxy/envoy/assets/11749867/01e25425-d8c8-4a52-947c-95ee3b051a67)
  We can see, the memory is `16M` initally.

* After send requests to envoy

  ![image](https://github.com/envoyproxy/envoy/assets/11749867/7cc2847d-f08f-46d8-bb5d-45d461a822db)
  We can see, current memory is `39M`.
  I waited about at least 30.minutes, the memory is `39M` still.

## My question
* Is the envoy itself bug?(I used envoy's lastest image to test)
* If not, what did i miss?
