### ISSUE TITLE
Lua HTTP filter seems to continue making http calls even if the target cluster is unhealthy

### ISSUE THREAD

**Issue by blaisewang** [envoyproxy/envoy#31801]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Lua HTTP filter seems to continue making http calls even if the target cluster is unhealthy*

*Description*:
> I have an external authentication service that expects requests to go through the authentication service before being sent to the real services. I expect that if the authentication service is unavailable, the Lua HTTP filter will no longer send requests to the authentication service to avoid some additional failed requests. But it seems that even if the health check of the auth cluster is marked as unhealthy, `handle:httpCall()` will still send the request. I wonder if this is a bug or by design.

[optional *Relevant Links*:]

Minimal reproducible envoy configuration:

```yaml
static_resources:
  listeners:
    - name: http
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: web_server
                http_filters:
                  - name: auth_filter
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      default_source_code:
                        inline_string: |
                          function envoy_on_request(request_handle)
                            local auth_headers, _ = request_handle:httpCall(
                                    "auth_cluster",
                                    {
                                      [":method"] = "GET",
                                      [":path"] = "/auth",
                                      [":authority"] = "auth_cluster",
                                    },
                                    nil,
                                    10000,
                                    false
                            )
                            if auth_headers ~= nil then
                              request_handle:respond(
                                { [":status"] = "403" },
                                "access denied\n"
                              )
                            end
                          end
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: real_service
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 30080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "passed to the real service\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: auth_cluster
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: auth_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  health_check_config:
                    port_value: 8889
                  address:
                    socket_address:
                      address: 192.168.31.84
                      port_value: 8888
      health_checks:
        - timeout: 1s
          interval: 1s
          unhealthy_threshold: 1
          healthy_threshold: 1
          http_health_check:
            path: "/health"

    - name: web_server
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: web_server
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 30080

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

```

`socket_address` of `auth_cluster` can be replaced by an address of a reachable HTTP service.
