### ISSUE TITLE
First Use of envoyproxy with Rest services

### ISSUE THREAD

**Issue by raboutech** [envoyproxy/envoy#3185]
**Issue Template**

*Title*: *One line description*
First use of envoy
*Description*:
Hi, i am new in using envoy, i am trying to use it on one rest service deployed on tomcat in address : localhost:8080/easyrest/employee/getAll  .
envoy process is in a container but not my service because my services now are in VMs and not in containers.  below is my code, it's basic but not working for me. when i try to get localhost:10000/easyrest/employee/getAll , i get this response : upstream connect error or disconnect/reset before headers

**Bug Template**
upstream connect error or disconnect/reset before headers

*Config*:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/tmp/access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/easyrest/employee/getAll"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: local_service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080
admin: 
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

```
*Logs*:
`"GET /easyrest/employee/getAll HTTP/1.1" 503 UF 0 57 1 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36" "1ede2a09-94fd-44d2-b8ef-0e265b595eaa" "127.0.0.1:10000" "127.0.0.1:8080"`
