### ISSUE TITLE
oauth2 filter does not verify tokenEndpoint certificate where SNI is not set

### ISSUE THREAD

**Issue by arminabf** [envoyproxy/envoy#31885]
When activating TLS and explicitly specifying a _trusted_ca_ in the corresponding upstream cluster, the oauth2 filter does not check the server certificate for the correctness of the CA.

 In fact, the oauth2 filter accepts any upstream, non-expired certificate even though not signed by a whitelisted _trusted_ca_.

Please find bellow the oaut2 Filter configuration and the cluster configuration with which the issue can be reproduced. In our tests, the /etc/ssl/certs/ca-certificates.crt _trusted_ca_ does NOT contain the CA certificate with which the certificate of the _authorizationEndpoint_  has been issued.

The Envoy version in use is v1.28.

```
        - name: "envoy.filters.http.oauth2"
          typedConfig:
            '@type': "type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2"
            config:
              tokenEndpoint:
                uri: "https://myhost.online/login/sls/oidc-token"
                cluster: "oauth-myauth"
                timeout: "3s"
              authorizationEndpoint: "https://myhost.online/login/sls/oidc-auth"
              credentials:
                clientId: "client"
                tokenSecret:
                  name: "client-secret-ref"
                  sdsConfig:
                    pathConfigSource:
                      path: "/etc/envoy/secrets/oauth/myauth/clientSecret/clientSecret.yaml"
                hmacSecret:
                  name: "hmac-secret-ref"
                  sdsConfig:
                    pathConfigSource:
                      path: "/etc/envoy/secrets/oauth/myauth/hmacSecret/hmacSecret.yaml"
              redirectUri: "%REQ(x-forwarded-proto)%://%REQ(:authority)%/oauth-myauth-callback"
              redirectPathMatcher:
                path:
                  exact: "/oauth-myauth-callback"
              signoutPath:
                path:
                  exact: "/oauth-myauth-signout"
              forwardBearerToken: true
              authScopes:
              - "openid"
```

```
- '@type': "type.googleapis.com/envoy.config.cluster.v3.Cluster"
  name: "oauth-myauth"
  type: "LOGICAL_DNS"
  connectTimeout: "5s"
  dnsLookupFamily: "V4_ONLY"
  transportSocket:
    name: "envoy.transport_sockets.tls"
    typedConfig:
      '@type': "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
  common_tls_context:
    validation_context:
      trusted_ca:
        filename: /etc/ssl/certs/ca-certificates.crt
  loadAssignment:
    clusterName: "oauth-myauth"
    endpoints:
    - lbEndpoints:
      - endpoint:
          address:
            socketAddress:
              address: "myhost.online"
              portValue: 443
```
