### ISSUE TITLE
Use envoy inside another system/company proxy

### ISSUE THREAD

**Issue by Nihal987** [envoyproxy/envoy#31917]
I'm using envoy in a test server that does not have access to the public internet. To make an outbound request I need to route it through a proxy.

For example to curl google.com I would have to do `curl -x <proxy_ip>:80 http://www.google.com`

Now suppose I want to route any requests that come with the path prefix `/changeHeaders` to www.envoyproxy.io. 

How would I modify my envoy yaml file to do that?

```
static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/changeHeaders"
                request_headers_to_add: # this happens first
                - append: false
                  header:
                    key: Referer
                    value: www.envoyproxy.io
                - append: false
                  header:
                    key: Origin
                    value: www.envoyproxy.io
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
              - match:
                  prefix: "/keepHeaders"
                route:
                  host_rewrite_literal: ""
                  cluster: service_envoyproxy_io

  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```
