### ISSUE TITLE
DNS Proxy

### ISSUE THREAD

**Issue by eliassteiner** [envoyproxy/envoy#32006]
*DNS Proxy *

*Description*:
Hello everyone, I have an issue with my UDP Envoy Proxy. Individual DNS requests (both IPv4 and IPv6 requests) from the client are being sent separately. However, Envoy is forwarding both requests as a single packet to the DNS server. Does anyone have an idea of what could be causing this? Thank you for your help.

```
    -   connect_timeout: 5s
        load_assignment:
            cluster_name: dns_test
            endpoints:
            -   lb_endpoints:
                -   endpoint:
                        address:
                            socket_address:
                                address: bla.bla.bla
                                port_value: 32053
        name: dns_test
        per_connection_buffer_limit_bytes: 32768
        type: strict_dns
...
    -   address:
            socket_address:
                address: 0.0.0.0
                port_value: 32053
                protocol: UDP
        listener_filters:
        -   name: envoy.filters.udp_listener.udp_proxy
            typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
                cluster: dns_test
                stat_prefix: dns_test
        name: listener_dns_test
        per_connection_buffer_limit_bytes: 32768
        reuse_port: true
```
