### ISSUE TITLE
Modify location header before internal redirect action

### ISSUE THREAD

**Issue by larvinloy** [envoyproxy/envoy#32003]
*Title*: *Modify location header before internal redirect action*

*Description*:
 I have a use case where upstream responds with a 307 and a few headers and we want to handle the redirect internally. I was able to do that successfully by setting up a redirect policy and it works as expected. However, now I want to intercept the 307 response before the redirect is handled by envoy and swap the host in the `location` header to the value from one of headers in the redirect response. I tried to create a Lua filter to test it out but it does not seem to work. I'd like to know if this is possible using Envoy before checking if Istio supports it. 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: modify-location-headers
  namespace: test
spec:
  workloadSelector:
    labels:
      type: internal
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          route:
            name: echo-us-west-2
    patch:
      operation: INSERT_FIRST
      value:
        name: envoy.lua
        typed_per_filter_config:
          # I should be setting the host value in the location from another header, but for the sake of simplicity, I am hardcoding it.
          envoy.filters.http.lua:
            '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
            source_code:
                inline_string: |
                  function envoy_on_response(response_handle) 
                    if response_handle:headers():get(":status") == "307" then
                      response_handle:headers():replace("location", "http://new-location-from-header.example.com")
                    end
                  end
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          route:
            name: echo-us-west-2
    patch:
      operation: INSERT_AFTER # This filter only seems to work when it is set to MERGE.
      value:
        name: redirect-filter
        route:
          internal_redirect_policy:
            max_internal_redirects: 5
            redirect_response_codes:
            - "307"
            
```

Envoy version: `1.26.6`

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
