### ISSUE TITLE
FQDN Filter

### ISSUE THREAD

**Issue by eliassteiner** [envoyproxy/envoy#32004]
*FQDN Filter*:

*Description*:
Hello everyone,
The following question: Is it possible to implement a listener with an FQDN? I want Envoy to only forward traffic when Test.test.io is called. Currently, Envoy Proxy forwards all traffic that comes to port 443.

```
    -   connect_timeout: 5s
        load_assignment:
            cluster_name: ingress_https
            endpoints:
            -   lb_endpoints:
                -   endpoint:
                        address:
                            socket_address:
                                address: bla.bla.bla.io
                                port_value: 443
                                
         name: ingress_https
        per_connection_buffer_limit_bytes: 32768
        type: strict_dns
```
``
    -   address:
            socket_address:
                address: 0.0.0.0
                port_value: 443
        filter_chains:
        -   filters:
            -   name: envoy.filters.network.tcp_proxy
                typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                    access_log:
                    -   name: envoy.access_loggers.file
                        typed_config:
                            '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                            path: /var/log/envoy/ingress_https_access.log
                    cluster: ingress_https
                    stat_prefix: ingress_https
        name: listener_ingress_https

**Comment by zuercher** [comment]
I'm not sure I understand your question.

Your config has the listener accept connections on port 443 for any IPv4 assigned to the host (that's what 0.0.0.0 implies). A specific IP can be configured (e.g. 10.0.0.1), which would cause Envoy to only listen on that IP address (not, for example, 127.0.0.1). But most hosts only have 1 IP and localhost, and your DNS name presumably points at the IP address.

**Comment by jewertow** [comment]
@eliassteiner you need tls_inspector in you listener:
```
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: "envoy.filters.listener.tls_inspector"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    filter_chains:
    - filter_chain_match:
        server_names: ["test.test.io"]
      filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          ...
```
