### ISSUE TITLE
Use VHDS with static route config

### ISSUE THREAD

**Issue by zhaoyangli311** [envoyproxy/envoy#32035]
In case there are hundreds of routes under each virtual host within same route configuration, would it be better to use RDS + VHDS than just RDS? Or the difference can be ignored? If not, should VHDS + static route config be supported?

**Comment by ljluestc** [comment]
```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              config:
                codec_type: AUTO
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: example_virtual_host
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: "example_cluster" }
                http_filters:
                  - name: envoy.filters.http.router
  clusters:
    - name: example_cluster
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      hosts:
        - socket_address: { address: example_service, port_value: 8080 }

dynamic_resources:
  cds_config:
    path: "/path/to/cds_config"
  rds_config:
    path: "/path/to/rds_config"
  vhds_config:
    path: "/path/to/vhds_config"

```
