### ISSUE TITLE
grpc transcoder: support HttpBody proto

### ISSUE THREAD

**Issue by lps0535** [envoyproxy/envoy#3205]
*Title*: *Unwanted characters coming while adding response_headers_to_add*

*Description*:
> I've a gRPC server and an HTTP client (browser). I'm trying to send an html file from gRPC server to HTTP client (browser) and I want it to be rendered on browser itself. I've added following lines in config file but it is throwing some noisy data along with data which is required. 
```
response_headers_to_add:
                            header: { key: "Content-Type", value: "text/html" }
                            append: false
```

*Config*:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 3000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/serverSide.FileSender/sendfile" }   # Here pulseiot, CampaignService and createCampaign is the name of package, Service and rpc Call we defined in proto file
                route:
                    response_headers_to_add:
                            header: { key: "Content-Type", value: "text/html" }
                            append: false
                    cluster: cluster1
          http_filters:
            - name: envoy.grpc_json_transcoder
              config: { proto_descriptor: "/etc/proto.pb", services: ["serverSide.FileSender"]}
            - name: envoy.router
              config: {}

  clusters:
  - name: cluster1
    connect_timeout: 11.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 10.112.82.129
        port_value: 15001

admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902

```

ISSUE: Noise at starting of html file. I've tried with other files also but facing same issues with every file.
```

�
<!DOCTYPE html>
<html>
    <head>
        <script type="application/javascript">
function msg(){
 alert("Hello Javatpoint");
}
</script>
    </head>
    <body>
        <p>Welcome to JavaScript</p>
        <form>
            <input type="button" value="click" onclick="msg()"/>
        </form>
    </body>
</html>
```

*Logs*:
>[2018-04-25 11:11:46.671][11][debug][main] source/server/connection_handler_impl.cc:195] [C1] new connection
[2018-04-25 11:11:46.671][11][debug][http] source/common/http/conn_manager_impl.cc:186] [C1] new stream
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:790] [C1][S2066557439932801438] request end stream
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:455] [C1][S2066557439932801438] request headers complete (end_stream=true):
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   ':authority':'localhost:3000'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'connection':'keep-alive'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'upgrade-insecure-requests':'1'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'accept-encoding':'gzip, deflate, br'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   'accept-language':'en-US,en;q=0.9'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   ':path':'/getfile'
[2018-04-25 11:11:46.672][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S2066557439932801438]   ':method':'GET'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:250] [C1][S2066557439932801438] cluster 'cluster1' match for URL '/serverSide.FileSender/sendfile'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   ':authority':'localhost:3000'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'upgrade-insecure-requests':'1'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'accept':'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'accept-encoding':'gzip, deflate, br'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'accept-language':'en-US,en;q=0.9'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   ':path':'/serverSide.FileSender/sendfile'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   ':method':'POST'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'x-forwarded-proto':'http'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'x-request-id':'d6a83655-3068-4366-84c4-c0e0a1a4cdc4'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'content-type':'application/grpc'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'x-envoy-original-path':'/getfile'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'te':'trailers'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   'x-envoy-expected-rq-timeout-ms':'15000'
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:298] [C1][S2066557439932801438]   ':scheme':'http'
[2018-04-25 11:11:46.672][11][debug][client] source/common/http/codec_client.cc:25] [C2] connecting
[2018-04-25 11:11:46.672][11][debug][connection] source/common/network/connection_impl.cc:568] [C2] connecting to 192.168.137.1:15001
[2018-04-25 11:11:46.672][11][debug][connection] source/common/network/connection_impl.cc:577] [C2] connection in progress
[2018-04-25 11:11:46.672][11][debug][http2] source/common/http/http2/codec_impl.cc:624] [C2] setting stream-level initial window size to 268435456
[2018-04-25 11:11:46.672][11][debug][http2] source/common/http/http2/codec_impl.cc:648] [C2] updating connection-level initial window size to 268435456
[2018-04-25 11:11:46.672][11][debug][pool] source/common/http/http2/conn_pool.cc:97] [C2] creating stream
[2018-04-25 11:11:46.672][11][debug][router] source/common/router/router.cc:966] [C1][S2066557439932801438] pool ready
[2018-04-25 11:11:46.686][11][debug][connection] source/common/network/connection_impl.cc:464] [C2] connected
[2018-04-25 11:11:46.686][11][debug][client] source/common/http/codec_client.cc:63] [C2] connected
[2018-04-25 11:11:46.709][12][debug][main] source/server/connection_handler_impl.cc:195] [C3] new connection
[2018-04-25 11:11:47.380][11][debug][router] source/common/router/router.cc:590] [C1][S2066557439932801438] upstream headers complete: end_stream=false
[2018-04-25 11:11:47.380][11][debug][http] source/common/http/conn_manager_impl.cc:963] [C1][S2066557439932801438] encoding headers via codec (end_stream=false):
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   ':status':'200'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'grpc-encoding':'identity'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'grpc-accept-encoding':'gzip'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'x-envoy-upstream-service-time':'708'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'content-type':'text/html; charset=utf-8'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'date':'Wed, 25 Apr 2018 11:11:47 GMT'
[2018-04-25 11:11:47.381][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S2066557439932801438]   'server':'envoy'
[2018-04-25 11:11:47.450][11][debug][client] source/common/http/codec_client.cc:94] [C2] response complete
[2018-04-25 11:11:47.450][11][debug][pool] source/common/http/http2/conn_pool.cc:189] [C2] destroying stream: 0 remaining
[2018-04-25 11:11:47.450][11][debug][http] source/common/http/conn_manager_impl.cc:1049] [C1][S2066557439932801438] encoding trailers via codec
[2018-04-25 11:11:47.450][11][debug][http] source/common/http/conn_manager_impl.cc:1054] [C1][S2066557439932801438]   'grpc-status':'0'
[2018-04-25 11:11:47.450][11][debug][http2] source/common/http/http2/codec_impl.cc:517] [C2] stream closed: 0
[2018-04-25 11:11:48.114][6][debug][main] source/server/server.cc:130] flushing stats
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:186] [C1] new stream
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:790] [C1][S5174642106963361548] request end stream
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:455] [C1][S5174642106963361548] request headers complete (end_stream=true):
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   ':authority':'localhost:3000'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'connection':'keep-alive'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'accept':'image/webp,image/apng,image/*,*/*;q=0.8'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'referer':'http://localhost:3000/getfile'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'accept-encoding':'gzip, deflate, br'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   'accept-language':'en-US,en;q=0.9'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   ':path':'/favicon.ico'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:460] [C1][S5174642106963361548]   ':method':'GET'
[2018-04-25 11:11:48.321][11][debug][router] source/common/router/router.cc:204] [C1][S5174642106963361548] no cluster match for URL '/favicon.ico'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:963] [C1][S5174642106963361548] encoding headers via codec (end_stream=true):
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S5174642106963361548]   ':status':'404'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S5174642106963361548]   'date':'Wed, 25 Apr 2018 11:11:48 GMT'
[2018-04-25 11:11:48.321][11][debug][http] source/common/http/conn_manager_impl.cc:968] [C1][S5174642106963361548]   'server':'envoy'
