### ISSUE TITLE
How to incorporate the event_logger into HealthCheck as an alternative to the deprecated event_log_path option.

### ISSUE THREAD

**Issue by anshadafu** [envoyproxy/envoy#32106]
*Title*: *How to incorporate the event_logger into HealthCheck as an alternative to the deprecated event_log_path option.*

*Description*:
> I am in the process of updating the envoy to the latest v1.29. But started getting below-warning. How i can migrate this to event_logger? Tried many ways but nothing worked. 

Deprecated field: type envoy.config.core.v3.HealthCheck Using deprecated option 'envoy.config.core.v3.HealthCheck.event_log_path' from file health_check.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.

Current health check:

> health_checks:
    - timeout: 3s
      interval: 5s
      interval_jitter: 1s
      unhealthy_threshold: 2
      no_traffic_interval: 5s
      healthy_threshold: 2
      event_log_path: /var/log/envoy/listener-https_access.log

**Comment by alyssawilk** [comment]
cc @botengyao

**Comment by alyssawilk** [comment]
also cc @adisuissa @envoyproxy/api-shepherds for thoughts about removing deprecated config warnings

**Comment by adisuissa** [comment]
> also cc @adisuissa @envoyproxy/api-shepherds for thoughts about removing deprecated config warnings

I don't think that removing is the right thing to do, but maybe log-once-every-nth could be a reasonable alternative.

**Comment by botengyao** [comment]
Hi @anshadafu, we can use the file event_logger [config](https://envoyproxy.io/docs/envoy/v1.27.2/api-v3/config/core/v3/health_check.proto#envoy-v3-api-field-config-core-v3-healthcheck-event-logger), with this [file extension](https://www.envoyproxy.io/docs/envoy/v1.27.2/api-v3/extensions/health_check/event_sinks/file/v3/file.proto#extension-envoy-health-check-event-sinks-file).

**Comment by botengyao** [comment]
An example:
```
tcp_health_check:
        send:
          text: foo
        receive:
        - text: boo
      event_logger:
      - name: logger
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.health_check.event_sinks.file.v3.HealthCheckEventFileSink
          event_log_path: /foo/boo.txt
```
