### ISSUE TITLE
Missing health check logs

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#32119]
I'm testing a scenario where I have a ``STRICT_DNS`` cluster with a single endpoint. The DNS resolution of that endpoint returns 5 different IPs. I enabled health checks for that clusters as well as health checks logging to a file.
In my setup, only 1 out of the 5 IPs will respond to the health check, so it's expected that 5 simultaneous health checks will be performed on each interval, 1 of them will succeed and the rest won't, and that this will be indicated in the health check logs.
However, what I observe is that in the first interval, 5 log lines are printed, describing the health checks correctly, but for later intervals, only the 4 health checks that are failing are being logged, while the health check that is passing is discarded from the log (although I can verify that the help check is actually executing on that IP as well).

Config:
```
static_resources:
  listeners:
  - name: main
    stat_prefix: main
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1234
    filter_chains:
    - name: main
      filters:
      - name: tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: main
          cluster: main_cluster
          max_connect_attempts: 1

  clusters:
  - name: main_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: main_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: myhost.com
                port_value: 1111
    health_checks:
      timeout: 1s
      interval: 10s
      no_traffic_interval: 10s
      no_traffic_healthy_interval: 10s
      unhealthy_threshold: 1
      healthy_threshold: 1
      reuse_connection: false
      tcp_health_check:
        send:
          text: 6865616C7468
        receive:
        - text: 4563686F206865616C7468
      event_logger:
      - name: logger
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.health_check.event_sinks.file.v3.HealthCheckEventFileSink
          event_log_path: /data/health.json
      always_log_health_check_failures: true
```

Health check log output:
```
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.1","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:40.811Z","health_check_failure_event":{"failure_type":"NETWORK","first_check":true},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.3","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","add_healthy_event":{"first_check":true},"timestamp":"2024-01-31T12:00:40.817Z","metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.5","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:41.815Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":true},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.2","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:41.815Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":true},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.4","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:41.815Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":true},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.1","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:50.806Z","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.5","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:52.819Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.4","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:52.820Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.2","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:00:52.820Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.1","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:00.812Z","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.5","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:03.821Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.4","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:03.822Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.2","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:03.822Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.1","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:10.804Z","health_check_failure_event":{"failure_type":"NETWORK","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.2","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:14.813Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.5","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:14.813Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
{"health_checker_type":"TCP","host":{"socket_address":{"protocol":"TCP","address":"10.5.0.4","port_value":5556,"resolver_name":"","ipv4_compat":false}},"cluster_name":"main_cluster","timestamp":"2024-01-31T12:01:14.813Z","health_check_failure_event":{"failure_type":"NETWORK_TIMEOUT","first_check":false},"metadata":{"filter_metadata":{},"typed_filter_metadata":{}},"locality":{"region":"","zone":"","sub_zone":""}}
```

Note that the health check for ``10.5.0.3`` (the only responding IP) is only logged once at the beginning.
