### ISSUE TITLE
Upgrade to Websocket seems to ignore 'typed_per_filter_config' of route when using default HTTP filter chain

### ISSUE THREAD

**Issue by bruegth** [envoyproxy/envoy#32142]
![image](https://github.com/envoyproxy/envoy/assets/1318408/3ae0b893-6597-4424-af67-1d7aa5eec7c6)

Config:
```
                        - match:
                            path: "/mqtt"
                          route:
                            upgrade_configs:
                              upgrade_type: "websocket"
                            cluster: service_mqtt
                          decorator:
                            operation: "mqtt"
                          typed_per_filter_config:
                            internal_oauth2_oidc:
                              "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                              disabled: true
```

Logs:
```
[2024-02-01 07:12:11.904][34][debug][oauth2] [source/extensions/filters/http/oauth2/filter.cc:441] can not skip oauth flow
[2024-02-01 07:12:11.904][34][debug][oauth2] [source/extensions/filters/http/oauth2/filter.cc:373] path /mqtt does not match with redirect matcher. redirecting to OAuth server.
```

Version: Docker v1.29-latest
