### ISSUE TITLE
gRPC-JSON transcoder: Different protobuf message sent to upstream when using query string instead of request body

### ISSUE THREAD

**Issue by n0v1** [envoyproxy/envoy#32143]
Envoy seems to send a different protobuf message to the upstream when data is passed in query string instead of request body

*Description*:
When passing an array of objects to the upstream via Envoy gRPC-JSON transcoder, the  protobuf message which Envoy sends to the upstream differs depending on how data is sent to Envoy. When data is sent in request body, everything works as expected. When the same data is sent in the query string, the protobuf message has fewer bytes and the upstream only recognises one of two objects.

*Repro steps*:
Check this [repository](/n0v1/envoy-grpc-json-transcoder-object-array-query-string) for the complete reproduction code.

Proto file used for testing:
```proto
syntax = "proto3";
package bookstore;
import "google/api/annotations.proto";

message Book {
  string author = 1;
  string title = 2;
}

message EchoBooksRequest {
  repeated Book books = 1;
}

message EchoBooksResponse {
  repeated Book books = 1;
}

service Bookstore {
  rpc EchoBooks (EchoBooksRequest) returns (EchoBooksResponse) {
    option (google.api.http) = {
      post: "/echoBooks"
    };
  }
}
```

*Envoy Config* (tested with version v1.29.0)
<details>
<summary>envoy.yaml</summary>

```yaml
---
admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9901}

static_resources:
  listeners:
  - name: listener_1
    address:
      socket_address: {address: 0.0.0.0, port_value: 20000}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: grpc_json
          codec_type: AUTO
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: {prefix: "/bookstore.Bookstore"}
                route: {cluster: cluster_bookstore, timeout: {seconds: 60}}
          http_filters:
          - name: envoy.filters.http.grpc_json_transcoder
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
              proto_descriptor: "/etc/envoy/descriptor_set.pb"
              services:
              - "bookstore.Bookstore"
              convert_grpc_status: true
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: true
                stream_newline_delimited: true
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: cluster_bookstore
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    load_assignment:
      cluster_name: grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: bookstore
                port_value: 10000
```
</details>

### 1. Sending data in **request body** to Envoy gRPC-JSON transcoder:

```shell
HEADERS='--header Accept:application/json --header Content-Type:application/json'
DATA='{
  "books": [
    {"author": "Hello", "title": "World"},
    {"author": "Foo", "title": "Bar"}
  ]
}'
curl ${HEADERS} --data "${DATA}" --request 'POST' 'http://127.0.0.1:20000/echoBooks'
```
-> Both books are received and returned by gRPC service as expected.

<details>
<summary>Resulting protobuf buffer received by upstream</summary>

Raw buffer binary file:
[protobuf-request-body.dmp](https://github.com/envoyproxy/envoy/files/14125556/protobuf-request-body.dmp)

`xxd protobuf-request-body.dmp`:
```text
00000000: 0000 0000 1c0a 0e0a 0548 656c 6c6f 1205  .........Hello..
00000010: 576f 726c 640a 0a0a 0346 6f6f 1203 4261  World....Foo..Ba
00000020: 72
```

Raw buffer (33 bytes):

```text
<Buffer 00 00 00 00 1c 0a 0e 0a 05 48 65 6c 6c 6f 12 05 57 6f 72 6c 64 0a 0a 0a 03 46 6f 6f 12 03 42 61 72>
```
As hex string:
```text
000000001c0a0e0a0548656c6c6f1205576f726c640a0a0a03466f6f1203426172
```

[Protobuf Decoder](https://protobuf-decoder.netlify.app) output:
![image](https://github.com/envoyproxy/envoy/assets/1246586/27383378-ce41-4e3b-88d3-ec18a4fa433e)
</details>

### 2. Sending data in **query string** to Envoy gRPC-JSON transcoder:

```shell
HEADERS='--header Accept:application/json --header Content-Type:application/json'
curl ${HEADERS} --request 'POST' 'http://127.0.0.1:20000/echoBooks?books.author=Hello&books.title=World&books.author=Foo&books.title=Bar'
```
-> Only last book (Foo Bar) is returned by gRPC service, the other one is lost (Hello World).

<details>
<summary>Resulting protobuf buffer received by upstream</summary>

Raw buffer binary file:
[protobuf-query-string.dmp](https://github.com/envoyproxy/envoy/files/14125550/protobuf-query-string.dmp)

`xxd protobuf-query-string.dmp`:
```text
00000000: 0000 0000 1a0a 180a 0548 656c 6c6f 1205  .........Hello..
00000010: 576f 726c 640a 0346 6f6f 1203 4261 72    World..Foo..Bar
```

Raw buffer (31 bytes):
```text
<Buffer 00 00 00 00 1a 0a 18 0a 05 48 65 6c 6c 6f 12 05 57 6f 72 6c 64 0a 03 46 6f 6f 12 03 42 61 72>
```
As hex string:
```text
000000001a0a180a0548656c6c6f1205576f726c640a03466f6f1203426172
```

[Protobuf Decoder](https://protobuf-decoder.netlify.app) output:
![image](https://github.com/envoyproxy/envoy/assets/1246586/69c29894-6faa-49c7-b9d6-3faf87e16f4e)
</details>

---

I would expect to see identical results in both cases. However in the query string case (2) the resulting protobuf buffer has two bytes less than in the request body case (1). Both books ("Hello World" and "Foo Bar") seem to be contained inside both buffers (see stringifyed buffers above). However in the query string case only one book is left after deserializing the buffer.

Yes, this might be a rather uncommon use case but as Envoy did not complain, I'd like to gather some feedback whether this is a bug or works as expected.
