### ISSUE TITLE
RouteMatch Query Parameter Question

### ISSUE THREAD

**Issue by lee-aaron** [envoyproxy/envoy#32231]
Are there some examples on use cases with routing to one cluster and only taking requests _without_ any query parameters? I saw that the path matcher strips the query parameters when matching so that doesn't fit the use case I have.

```
                      routes:
                        - match:
                            safe_regex:
                              google_re2: {}
                              regex: "^/$"
                            headers:
                              - name: ":method"
                                string_match:
                                  safe_regex:
                                    google_re2: {}
                                    regex: "^(?:DELETE|PUT)$"
                          route:
                            cluster: cluster_a
                            timeout: 0s # disable timeout
                        - match:
                            prefix: "/"
                          route:
                            cluster: cluster_b
                            timeout: 0s # disable timeout
```

I'd like to route only PUT / DELETE requests without any query parameters to cluster_a but it captures all requests even with query parameters.
