### ISSUE TITLE
Dyanmic cluster hostname based on regex path

### ISSUE THREAD

**Issue by songwillow** [envoyproxy/envoy#32242]
*Description*:
I'm not sure if this is possible or not and I can't seem to find any documentation around it. I'm trying to use envoy's regex route match and somehow append the captured matches to a cluster hostname. Say I have 3 containers containerA, containerB and containerC names of the containers are dynamically created so I can't statically define the hostname of each container. How can I direct the request?

```
- match:
    safe_regex:
      google_re2: {}
      regex: '/(.*)/hello'
  route:
    timeout: 240s
    prefix_rewrite: "/"
    cluster: authrz_web
    auto_host_rewrite: true
- name: container
  dns_lookup_family: V4_ONLY
  lb_policy: ROUND_ROBIN
  connect_timeout: 60s
  type: LOGICAL_DNS
  load_assignment:
    cluster_name: container
    endpoints:
      - lb_endpoints:
          - endpoint:
              hostname: container+(append captured regex)
              address:
                socket_address:
                  address: container+(append captured regex)
                  port_value: 80

```
A request comes in as  **/A/hello** I want to be able to capture **A** and include that to the hostname of the cluster and properly resolve the request to the container named containerA. Similarly, if a request comes in as **/Z/hello** I want to be able to resolve it to containerZ.
