### ISSUE TITLE
Per-Route custom_tags for tracing are not being added.

### ISSUE THREAD

**Issue by ldb** [envoyproxy/envoy#32342]
*Title*: *Per-Route custom_tags for tracing are not being added*

*Description*:
I configured custom_tags using the [per-route `tracing` config](https://www.envoyproxy.io/docs/envoy/v1.29.0/api-v3/config/route/v3/route_components.proto#config-route-v3-tracing). All of them are non-empty literal values. I expect them to show up in my traces, but they do not show up.

Meanwhile, additional_tags configured on the connection manager do show up.

*Config*:
```yaml
- match:
    [...]
  name: GET#/echo/public
  tracing:
    custom_tags:
      - literal:
          value: /echo/public
        tag: http.route
      - literal:
          value: GET#/echo/public
        tag: envoy.filters.http.router.route.name
  [...]
```
