### ISSUE TITLE
route level filter chain - handling requests not matching defined routes

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#32484]
Envoy Gateway recently implemented route level filter chain using https://github.com/envoyproxy/envoy/pull/27210 and https://github.com/envoyproxy/envoy/pull/30141

Initially, this worked perfectly. However, we encountered an issue where a request that didn't match any defined routes still proceeded through the filters configured in the HCM.

For instance, consider the following envoy configuration, which defines two routes: /foo, and /bar.  /foo route is configured with a basic auth filter, and /bar is not.
```yaml
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.basic_auth-foo
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.basic_auth.v3.BasicAuth
              users:
                inline_string: |-
                    foo:{SHA}Ys23Ag/5IOWqZCw9QGaVDdHwH00=
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            typed_per_filter_config:
              envoy.filters.http.basic_auth-foo:
                "@type":  type.googleapis.com/envoy.config.route.v3.FilterConfig
                disabled: true
            virtual_hosts:
            - name: service
              domains:
              - "127.0.0.1:8080"
              routes:
              - match:
                  prefix: "/foo"
                route:
                  cluster: local_service
                typed_per_filter_config:
                  envoy.filters.http.basic_auth-foo:
                    "@type":  type.googleapis.com/envoy.config.route.v3.FilterConfig
                    config: {}
              - match:
                  prefix: "/bar"
                route:
                  cluster: local_service
```
full file: https://gist.github.com/zhaohuabing/4d6d788002b7ca6b563933b42282ac42

Requests to /foo and /bar behaved as expected:
```bash
$ curl http://127.0.0.1:8080/foo
User authentication failed. Missing username and password.%     

$ curl http://127.0.0.1:8080/bar
Request served by b00d8d72f15e

GET /bar HTTP/1.1

Host: 127.0.0.1:8080
Accept: */*
User-Agent: curl/8.4.0
X-Envoy-Expected-Rq-Timeout-Ms: 15000
X-Forwarded-Proto: http
X-Request-Id: 3061ff10-bf80-458c-aae5-37690e0b06be
```

However, requests to non-existing routes also trigger the basic auth filter, contrary to expectations, and should ideally return a 404 error.
```bash
$ curl -s http://127.0.0.1:8080/non-existing-route
User authentication failed. Missing username and password.
```

To address this issue, EG generates a `catch-all-return-404` as a workaround.

```yaml
              - match:    
                  prefix: "/"
                direct_response: 
                  status: 404 
```

This workaround resolves the problem, but it raises the question of whether Envoy itself should handle such cases. It seems logical that requests should not pass through filters disabled in the `route_config`.

 @wbpcode
