### ISSUE TITLE
OpenTelemetry (gRPC) Access Log: envoy exits with error

### ISSUE THREAD

**Issue by shiponcs** [envoyproxy/envoy#32483]
*Title*: *OpenTelemetry (gRPC) Access Log: envoy exits with error*

*Description*:
I configured envoy for OpenTelemetry for gRPC access log but envoy failed

*Config*:
Here is my config file:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    traffic_direction: OUTBOUND
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          generate_request_id: true
          access_log:
          - name: envoy.access_loggers.open_telemetry
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig
              common_config:
                log_name: envoy-log
                grpc_service:
                  envoy_grpc:
                    cluster_name: opentelemetry_collector
          codec_type: AUTO
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: proxy_routes
            virtual_hosts:
            - name: proxy
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/home/1"
                route:
                  cluster: envoy_cluster1
                decorator:
                  operation: routeToEnvoy1
              
  clusters:
  - name: envoy_cluster1
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: envoy_cluster1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-1
                port_value: 10000
  - name: opentelemetry_collector
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: opentelemetry_collector
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: opentelemetry
                port_value: 4317

```

*Logs*:
```bash
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.011][1][info][main] [source/server/server.cc:492]   response header map: 432 bytes: :status,access-control-allow-credentials,access-control-allow-headers,access-control-allow-methods,access-control-allow-origin,access-control-allow-private-network,access-control-expose-headers,access-control-max-age,age,cache-control,connection,content-encoding,content-length,content-type,date,etag,expires,grpc-message,grpc-status,keep-alive,last-modified,location,proxy-connection,proxy-status,server,transfer-encoding,upgrade,vary,via,x-envoy-attempt-count,x-envoy-decorator-operation,x-envoy-degraded,x-envoy-immediate-health-check-fail,x-envoy-ratelimited,x-envoy-upstream-canary,x-envoy-upstream-healthchecked-cluster,x-envoy-upstream-service-time,x-request-id
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.011][1][info][main] [source/server/server.cc:492]   response trailer map: 144 bytes: grpc-message,grpc-status
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.053][1][info][main] [source/server/server.cc:859] runtime: {}
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.053][1][info][main] [source/server/server.cc:721] No admin address given, so no admin HTTP server started.
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.053][1][info][config] [source/server/configuration_impl.cc:164] loading tracing configuration
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.053][1][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.053][1][info][config] [source/server/configuration_impl.cc:130] loading 3 cluster(s)
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.055][1][info][config] [source/server/configuration_impl.cc:134] loading 1 listener(s)
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.056][1][info][tracing] [source/common/tracing/tracer_manager_impl.cc:42] instantiating a new tracer: envoy.tracers.opentelemetry
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.056][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.extensions.access_loggers.grpc.v3.CommonGrpcAccessLogConfig Using the default now-deprecated value AUTO for enum 'envoy.extensions.access_loggers.grpc.v3.CommonGrpcAccessLogConfig.transport_api_version' from file als.proto. This enum value will be removed from Envoy soon so a non-default value must now be explicitly set. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.056][1][warning][misc] [./source/common/config/utility.h:171] V2 (and AUTO) xDS transport protocol versions are deprecated in log_name: "envoy-log"
opentelemetry-envoy-front-proxy-1  | grpc_service {
opentelemetry-envoy-front-proxy-1  |   envoy_grpc {
opentelemetry-envoy-front-proxy-1  |     cluster_name: "opentelemetry_collector"
opentelemetry-envoy-front-proxy-1  |   }
opentelemetry-envoy-front-proxy-1  | }
opentelemetry-envoy-front-proxy-1  | . The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version, see the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3.
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.057][1][critical][main] [source/server/server.cc:417] error initializing config '  /etc/envoy.yaml': V2 (and AUTO) xDS transport protocol versions are deprecated in log_name: "envoy-log"
opentelemetry-envoy-front-proxy-1  | grpc_service {
opentelemetry-envoy-front-proxy-1  |   envoy_grpc {
opentelemetry-envoy-front-proxy-1  |     cluster_name: "opentelemetry_collector"
opentelemetry-envoy-front-proxy-1  |   }
opentelemetry-envoy-front-proxy-1  | }
opentelemetry-envoy-front-proxy-1  | . The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version, see the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3.
opentelemetry-envoy-front-proxy-1  | [2024-02-20 08:45:33.057][1][info][main] [source/server/server.cc:1024] exiting
opentelemetry-envoy-front-proxy-1  | V2 (and AUTO) xDS transport protocol versions are deprecated in log_name: "envoy-log"
opentelemetry-envoy-front-proxy-1  | grpc_service {
opentelemetry-envoy-front-proxy-1  |   envoy_grpc {
opentelemetry-envoy-front-proxy-1  |     cluster_name: "opentelemetry_collector"
opentelemetry-envoy-front-proxy-1  |   }
opentelemetry-envoy-front-proxy-1  | }
opentelemetry-envoy-front-proxy-1  | . The v2 xDS major version has been removed and is no longer supported. You may be missing explicit V3 configuration of the transport API version, see the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/envoy_v3.
opentelemetry-envoy-front-proxy-1 exited with code 1
```

**Comment by ohadvano** [comment]
Try update to:
```
          - name: envoy.access_loggers.open_telemetry
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig
              common_config:
                log_name: envoy-log
                transport_api_version: V3
                grpc_service:
                  envoy_grpc:
                    cluster_name: opentelemetry_collector
```
