### ISSUE TITLE
How to pass custom filter state from one listener to upstream internal listener   

### ISSUE THREAD

**Issue by sghiocel** [envoyproxy/envoy#32491]
*Title*: *Share Custom Filter State to Upstream Internal Listener*

*Description*:

1. listener 1 which is listening for HTTP CONNECT
    1. reads a custom header (`X-CUSTOM-HEADER`) from CONNECT and sets its value using `envoy.filters.http.set_filter_state`
    2. terminates the CONNECT and chains it to an internal listener
2. listener 2 which is an internal listener handling the subsequent HTTP requests
    1. reads the HTTP requests using `envoy.filters.http.router`
    2. adds the custom header to the HTTP request by reading the custom filter state (set by listener 1)

When I attempt this, I see the log line:
`[source/extensions/filters/common/set_filter_state/filter_config.cc:73] Created the filter state 'custom_key' from value 'test!'` which implies it was successfully set by listener 1. But my attempts to use it in listener 2 via `"%FILTER_STATE(envoy.string.custom_key)%"` does not work.

Config:
```
# This configuration terminates h2 CONNECT on port 10000 and then chains an HTTP filter that adds a custom header from CONNECT using
# an internal listener.
bootstrap_extensions:
- name: envoy.bootstrap.internal_listener
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.bootstrap.internal_listener.v3.InternalListener
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 127.0.0.1
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: decap_cluster
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
          http_filters:
          - name: envoy.filters.http.set_filter_state
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
              on_request_headers:
              - object_key: custom_key 
                factory_key: envoy.string
                format_string:
                  text_format_source:
                    inline_string: "%REQ(X-CUSTOM-HEADER)%"
                shared_with_upstream: TRANSITIVE
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http2_protocol_options:
            allow_connect: true
          upgrade_configs:
          - upgrade_type: CONNECT
  - name: decap
    internal_listener: {}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_http_filters:
                - name: upstream_header
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                    mutations:
                      request_mutations:
                        append:
                          header:
                            key: "X-CUSTOM-HEADER"
                            value: "%FILTER_STATE(envoy.string.custom_key)%"
                - name: envoy.filters.http.upstream_codec
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
  clusters:
  - name: decap_cluster
    load_assignment:
      cluster_name: decap_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              envoy_internal_address:
                server_listener_name: decap
  - name: local_service
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    lb_subset_config:
      fallback_policy: ANY_ENDPOINT
    load_assignment:
      cluster_name: local_service
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1 
                    port_value: 3000
    transport_socket:
      name: envoy.transport_sockets.internal_upstream
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport
        transport_socket:
          name: envoy.transport_sockets.raw_buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
```

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/set_filter_state
https://www.envoyproxy.io/docs/envoy/latest/configuration/advanced/well_known_filter_state#well-known-filter-state

**Comment by lizan** [comment]
cc @kyessenov

**Comment by sghiocel** [comment]
I figured this out:
```
    transport_socket:
      name: envoy.transport_sockets.internal_upstream
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.internal_upstream.v3.InternalUpstreamTransport
        transport_socket:
          name: envoy.transport_sockets.raw_buffer
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer
```
this should be under `decap_cluster` and not `local_service`. This change, along with:
```
value: "%FILTER_STATE(envoy.string.custom_key)%"
```
to:
```
value: "%FILTER_STATE(custom_key)%"
```
allows this configuration to work as expected
