### ISSUE TITLE
Envoy TCP Proxy Fails to Gracefully Drain Connections During Kubernetes Pod Updates

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#32510]
## Description

We're utilizing Envoy in Kubernetes as a TCP Proxy and aiming for graceful draining of existing connections while disallowing new workloads during pod updates. However, we've observed that the behavior we expect, akin to HTTP health check failure using the admin interface's `/healthcheck/fail`, is not supported for TCP. 

Quote from [Life of a request](https://www.envoyproxy.io/docs/envoy/latest/intro/life_of_a_request#life-of-a-request):
_"Draining: the listener no longer accepts new TCP connections while its existing TCP connections are allowed to continue for a drain period."_ [Link](https://arc.net/l/quote/ocqnmhrc)

We also attempted to use `POST /drain_listeners?graceful` and `POST /drain_listeners?graceful&skip_exit`, but Envoy continues to accept new connections. Is there an alternative method to achieve graceful draining using TCP Proxy?

**NOTE:** It functions correctly when graceful draining is not initiated i.e. `POST /drain_listeners`. In this case, Envoy promptly closes any new TCP connections. For instance,
```
curl -vik --resolve google.com:443:127.0.0.1 https://google.com

* Added google.com:443:127.0.0.1 to DNS cache
* Hostname microsoft.com was found in DNS cache
*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 failed: Connection refused
* Failed to connect to microsoft.com port 443 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to google.com port 443 after 0 ms: Couldn't connect to server
```

## Repro Steps

1. Start Envoy using the provided configuration.
2. Execute cURL requests similar to the following:
```
curl -vik --resolve google.com:443:127.0.0.1 https://google.com
```
3. Once confirming Envoy successfully handles these requests, transition Envoy to draining mode with the following cURL command:
```
curl -X POST 'http://localhost:9901//drain_listeners?graceful&skip_exit'
```

### Expectation
Envoy should cease accepting new connections.

### Actual Behavior
Envoy continues accepting new requests and returns successful results.

### Configuration

**NOTE:** `traffic_direction` for the 443 listener is set as **INBOUND**

```yaml
node:
  id: id_01
  cluster: cluster_01
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: selective_traffic_drop_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      traffic_direction: INBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.sni_dynamic_forward_proxy
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
                dns_cache_config:
                  name: dynamic_forward_proxy_cache_config
                  dns_lookup_family: V4_ONLY
                port_value: 443
            - name: envoy.tcp_proxy
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp
                cluster: dynamic_forward_proxy_cluster_sni
          name: allow-traffic
        - filters:
            - name: envoy.filters.network.direct_response
              typed_config:
                '@type': >-
                  type.googleapis.com/envoy.extensions.filters.network.direct_response.v3.Config
                response:
                  inline_string: '-'
          name: deny-traffic
      listener_filters:
        - name: envoy.filters.listener.tls_inspector
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
      access_log:
        - name: envoy.access_loggers.file
          typed_config:
            '@type': >-
              type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
            path: envoy-tcp.log
            log_format:
              json_format:
                duration: '%DURATION%'
                start_time: '%START_TIME%'
                response_flags: '%RESPONSE_FLAGS%'
                upstream_request_attempt_count: '%UPSTREAM_REQUEST_ATTEMPT_COUNT%'
                bytes_received: '%BYTES_RECEIVED%'
                downstream_wire_bytes_sent: '%DOWNSTREAM_WIRE_BYTES_SENT%'
                downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
                requested_server_name: '%REQUESTED_SERVER_NAME%'
                connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
                upstream_wire_bytes_received: '%UPSTREAM_WIRE_BYTES_RECEIVED%'
                upstream_wire_bytes_sent: '%UPSTREAM_WIRE_BYTES_SENT%'
                log_type: TCP
                bytes_sent: '%BYTES_SENT%'
                downstream_wire_bytes_received: '%DOWNSTREAM_WIRE_BYTES_RECEIVED%'
      filter_chain_matcher:
        matcher_list:
          matchers:
            - predicate:
                single_predicate:
                  input:
                    name: envoy.matching.inputs.server_name
                    typed_config:
                      '@type': >-
                        type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.ServerNameInput
                  value_match:
                    safe_regex:
                      google_re2: {}
                      regex: .*
              on_match:
                action:
                  name: pick-allow-traffic-chain
                  typed_config:
                    '@type': type.googleapis.com/google.protobuf.StringValue
                    value: allow-traffic
        on_no_match:
          action:
            name: pick-deny-traffic-chain
            typed_config:
              '@type': type.googleapis.com/google.protobuf.StringValue
              value: deny-traffic
  clusters:
    - name: dynamic_forward_proxy_cluster_sni
      connect_timeout: 5s
      lb_policy: CLUSTER_PROVIDED
      circuit_breakers:
        thresholds:
          - max_connections: 1024
            max_pending_requests: 1024
            max_requests: 1024
      dns_refresh_rate: 30s
      upstream_connection_options:
        tcp_keepalive:
          keepalive_probes: 15
          keepalive_time: 25
          keepalive_interval: 25
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
      respect_dns_ttl: true
      dns_failure_refresh_rate:
        base_interval: 5s
        max_interval: 60s
```
