### ISSUE TITLE
Websocket connection killed 1006

### ISSUE THREAD

**Issue by brunopbarrote** [envoyproxy/envoy#32525]
*Title*: *Unexpected Termination of WebSocket Connection through Envoy Proxy with SignalR: Error 1006 without Reason*

*Description*:
In the context of deploying an Angular application, which is served via an Nginx web server and communicates with a backend utilizing SignalR, I am encountering a perplexing issue. This configuration is orchestrated using Docker Compose locally, where it operates flawlessly. This seamless operation extends to scenarios where a YARP gateway substitutes Envoy, suggesting the infrastructure's inherent compatibility with alternative proxies.

When i deploy to my GKE environment, and pass through Envoy, my connection stays open for 30 seconds, and no matter what configuration i did, it gets killed after these 30 seconds. I can see on envoy deployment a log of DC with timeout 30001 seconds.

I have comented everything i already tried, but that didn't worked.

This is the log i get inside my envoy container
`
POST /websocket/event/negotiate?negotiateVersion=1 HTTP/1.1" 0 DC 0 0 30000
`

here is my envoy config:
```yaml
# admin:
#   address:
#     socket_address:
#       address: 0.0.0.0
#       port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          upgrade_configs:
          - upgrade_type: websocket
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          route_config:
            name: services_route_config
            virtual_hosts:
            - name: services-routes-debug
              domains: ["dev-debug.my-test.com","qa-debug.my-test.com","uat-debug.my-test.com"]
              cors:
                allow_origin_string_match:
                  - safe_regex:
                      google_re2: { }
                      regex: \*
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,resource,resource-name,authorization,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,x-requested-with,x-signalr-user-agent
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message                    
              routes:                                 
              - match:
                  prefix: "/websocket-angular"
                route:
                  timeout: 0s
                  prefix_rewrite: "/"
                  cluster: test-websocket-angular
              - match:
                  prefix: "/websocket/"
                  # headers:
                  #   - name: "upgrade"
                  #     exact_match: "websocket"                  
                route:
                  timeout: 0s
                  prefix_rewrite: "/"
                  cluster: test-websocket
                  # hash_policy:
                  # - cookie:
                  #     name: "YourCookieName"  # Replace with your actual cookie name
                  #     ttl: 0s  # Use 0s for session cookies, or specify a TTL if it's a persistent cookie
                  #     path: "/"  # Optional, specify if your cookie is scoped to a specific path                  
                  # upgrade_configs:
                  #   - upgrade_type: "websocket"
                  #     enabled: true            
          http_filters:
            - name: envoy.filters.http.cors
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors          
            - name: envoy.filters.http.compressor
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                response_direction_config:
                  common_config:
                    min_content_length: 100
                    content_type:
                      - text/html
                      - application/json
                  disable_on_etag_header: true
                request_direction_config:
                  common_config:
                    enabled:
                      default_value: false
                      runtime_key: request_compressor_enabled
                compressor_library:
                  name: text_optimized
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                    memory_level: 3
                    window_bits: 10
                    compression_level: BEST_COMPRESSION
                    compression_strategy: DEFAULT_STRATEGY
            - name: envoy.filters.http.router
              typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: test-websocket-angular
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    # connect_timeout: 30s
    load_assignment:
      cluster_name: test-websocket-angular
      endpoints: 
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: test-websocket-angular-service
                port_value: 80
  - name: test-websocket
    # lb_policy: RING_HASH
    # http2_protocol_options: {}
    # upstream_connection_options:
    #   tcp_keepalive: {}    
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    # connect_timeout: 30s
    load_assignment:
      cluster_name: test-websocket
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: test-websocket-service
                port_value: 80
```

Network tab log:
![image](https://github.com/envoyproxy/envoy/assets/8440065/32626309-3eb1-425c-b7ec-a9ebe8568017)

I'll appreaciate any helps, thoughts or anything that might help!
Thankz in advance.
