### ISSUE TITLE
Allow filters to set metadata matches from request

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3255]
This is related to #2436, but geared towards exposing the right APIs for filter writers to do what #2436 wants to expose via config language. 

I am playing with https://github.com/envoyproxy/envoy/pull/3254 to prototype how this would look.

To reiterate, the main use case I can think of (and which I am currently trying to solve) is being able to set metadata matches from a header (e.g.: `X-Version`) instead of having to hard-code route entries with each possible version, e.g.:

```
---
match:
  prefix: /
route:
  cluster: cluster-name
  metadata_match:
    filter_metadata:
      envoy.lb:
        version: '1.0'
```

(Assume using RDS to construct all the possible route combinations dynamically isn't a desired path).

Thoughts on how this should be approached?
