### ISSUE TITLE
how to use two typed_per_filter_config envoy.filters.http.local_ratelimit for two LocalRateLimit  filter?

### ISSUE THREAD

**Issue by penghuazhou** [envoyproxy/envoy#32677]
how to use two typed_per_filter_config envoy.filters.http.local_ratelimit for two LocalRateLimit  filter?
*Description*:
![image](https://github.com/envoyproxy/envoy/assets/13001038/532205bb-e6d0-42c2-bdbb-a3598ce9eec1)

It can work when use two envoy.filters.http.local_ratelimit typed_per_filter_config to applyTo HTTP_ROUTE?

```

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  labels:
    captain.zego.im/usage: ratelimit
  name: ef-local-ratelimit-ingress-rtc-smalpha-media-gw
  namespace: rtc-smalpha
spec:
  configPatches:
    - applyTo: HTTP_ROUTE
      patch:
        operation: MERGE
        value:
          name: default
          route:
            rate_limits:
              - actions:
                  - request_headers:
                      descriptor_key: Zgw-Appid
                      header_name: Zgw-Appid
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: >-
              type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      patch:
        operation: MERGE
        value:
          name: local_ratelimit
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              '@type': >-
                type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              descriptors: []
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              response_headers_to_add:
                - append: false
                  header:
                    key: x-envoy-ratelimited
                    value: 'true'
              stat_prefix: zego_local_rate_limit
              token_bucket:
                fill_interval: 0.1s
                max_tokens: 90
                tokens_per_fill: 9
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.local_ratelimit
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.emergency_local_ratelimit
          typed_config:
            '@type': type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: >-
              type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: HTTP_ROUTE
      patch:
        operation: MERGE
        value:
          name: emergency_local_ratelimit
          typed_config:
            envoy.filters.http.emergency_local_ratelimit:
              '@type': >-
                type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              descriptors:
                - entries:
                    - key: Zgw-Appid
                      value: '1057806480'
                  token_bucket:
                    fill_interval: 0.1s
                    max_tokens: 30
                    tokens_per_fill: 3
              filter_enabled:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enabled
              filter_enforced:
                default_value:
                  denominator: HUNDRED
                  numerator: 100
                runtime_key: local_rate_limit_enforced
              response_headers_to_add:
                - append: false
                  header:
                    key: x-envoy-ratelimited
                    value: 'true'
              stat_prefix: zego_local_rate_limiter
              token_bucket:
                fill_interval: 0.1s
                max_tokens: 5000000
                tokens_per_fill: 5000000
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            route:
              action: ROUTE
      patch:
        operation: INSERT_FIRST
        value:
          direct_response:
            body:
              inline_string: refuse
            status: 222
          match:
            prefix: /istio-hb
          name: hb
  workloadSelector:
    labels:
      app.kubernetes.io/name: ingress-rtc-smalpha-media-gw

```

**Comment by KBaichoo** [comment]
Can you provide the generated Envoy configuration from running this? Currently this is Istio config.

cc @wbpcode

**Comment by penghuazhou** [comment]
It throw this err. I not found a way to config two LocalRateLimit HTTP_ROUTE for two LocalRateLimit filter.

`2024-03-05T11:30:10.251260Z	warning	envoy config	gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Didn't find a registered implementation for name: 'envoy.filters.http.emergency_local_ratelimit'`

**Comment by KBaichoo** [comment]
I think the emergency_local_ratelimit is not a filter type e.g.

```
         name: emergency_local_ratelimit
          typed_config:
            envoy.filters.http.emergency_local_ratelimit:
```

should instead be `envoy.filters.http.local_ratelimit` for Envoy to find the filter you're trying to create.

**Comment by penghuazhou** [comment]
> envoy.filters.http.local_ratelimit
@KBaichoo K
But how to make the HTTP-ROUTE of two LocalRateLimits match the HTTP-FILTER of the corresponding LocalRateLimit?

**Comment by wbpcode** [comment]
Take the https://github.com/envoyproxy/envoy/blob/main/examples/lua/envoy.yaml as an example. There are `name` and `type`. The type of local rate limit filter should always be `type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit`, the `name` could be any string like `custom_rate_limit_1` and `custom_rate_limit_2`. See this doc to check how the filter relate to the route level config https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_filters#route-specific-config.

**Comment by penghuazhou** [comment]
@wbpcode 
I want to let direct_response exec before LocalRateLimit, so I config LocalRateLimit in HTTP_ROUTE. If I config LocalRateLimit in HTTP_FILTER, it will exec after  LocalRateLimit.

```
    - applyTo: HTTP_ROUTE
      match:
        routeConfiguration:
          vhost:
            route:
              action: ROUTE
      patch:
        operation: INSERT_FIRST
        value:
          direct_response:
            body:
              inline_string: refuse
            status: 222
          match:
            prefix: /istio-hb
          name: hb
```
