### ISSUE TITLE
Docs: Not clear how to use "request_attributes"

### ISSUE THREAD

**Issue by tfrokt** [envoyproxy/envoy#32678]
I am struggling reading the docs. It has no .yaml (or JSON) examples which makes it really hard.

I have successfully added an ext_proc [1] to my envoy proxy, but the the `path` does not reach the external processor (it does reach the cluster). I had a look at `request_attributes`, but it is not clear to me if that would solve my issue or even what the correct syntax is.

E.g. is this correct? If yes, what does it do?

```
http_filters:
          - name: envoy.filters.http.ext_proc
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
              failure_mode_allow: true
              async_mode: false
              message_timeout:
                seconds: 5
                nanos: 0
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SEND"
                request_body_mode: "NONE"
                response_body_mode: "NONE"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"
              request_attributes:
                - "request.path"
              grpc_service:
                google_grpc:
                  target_uri: "<external processor>"
                  stat_prefix: "<metric prefix>"
```

[1] https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_proc/v3/ext_proc.proto
