### ISSUE TITLE
Domains with underscores return 400 Bad Request

### ISSUE THREAD

**Issue by mikezsin** [envoyproxy/envoy#32736]
**Title:** Domains with underscores return 400 Bad Request

**Description:**
When configuring Envoy with a domain name that contains underscores, Envoy returns a `400 Bad Request` error for incoming requests. According to RFC 1035, underscores in domain names are not recommended, but they are commonly used in internal domain names and should be supported or handled gracefully.

**Reproduction Steps:**
1. Configure an Envoy listener with a route that specifies a domain name containing an underscore.
2. Send a request to the Envoy instance targeting the domain with the underscore.
3. Observe a `400 Bad Request` response.

**Config Snippet:**
```yaml
static_resources:
  listeners:
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http  
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: gm_tool
                      domains: ["gm_tool.test.local"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: gm_tool_cluster }
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:

    - name: gm_tool_cluster
      type: STRICT_DNS
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: gm_tool_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: gm_tool.test.local
                      port_value: 80
```
**Logs:**
`[2024-03-05T20:52:45.395Z] "- - HTTP/1.1" 400 DPE 0 11 0 - "-" "-" "-" "-" "-" 10.15.38.183`
