### ISSUE TITLE
ECDS config dump shows resources that were never recieved

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#32796]
*Title*: ECDS config dump shows resources that were never recieved

*Description*:
In the config dump, ECDS resources show up even if envoy never recieved them. This differs from other types. I would expect consistently to only show received resources, or at least mark them in some way

*Repro steps*:
```yaml
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 15000
node:
  id: id
  cluster: test
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          rds:
            route_config_name: my-route
            config_source:
              path: /dev/null
          http_filters:
          - config_discovery:
              config_source:
                path_config_source:
                  path: /dev/null
                initial_fetch_timeout: 0s
                resource_api_version: V3
              type_urls:
              - type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
            name: ecdstest
          - name: envoy.filters.http.router
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters: []
```

*Admin and Stats Output*:
```
  {
   "@type": "type.googleapis.com/envoy.admin.v3.EcdsConfigDump",
   "ecds_filters": [
    {
     "ecds_filter": {
      "@type": "type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig",
      "name": "ecdstest"
     },
     "last_updated": "2024-03-08T19:05:04.118Z"
    }
   ]
  },
```
