### ISSUE TITLE
Route table matches on filter state

### ISSUE THREAD

**Issue by zhaoyangli311** [envoyproxy/envoy#32807]
*Title*: *Route table matches on filter state*

*Description*:

Hello, I would like to enable route table to match on filter state. The idea is to make use of route table features using matcher, which matches on filter state. The config is like below

```
filters:
- name: envoy.filters.network.http_connection_manager
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
    stat_prefix: http
    route_config:
      name: route-config
      virtual_hosts:
      - name: all-domains
        domains: ["*"]
        matcher:
          matcher_tree:
            input:
              name: envoy.matching.inputs.filter_state
              typed_config:
                "@type": type.googleapis.com/envoy.type.matcher.v3.FilterStateMatchInput
                filter_state_key: abc
            exact_match_map:
              map:
                "abc":
                  action:
                    name: abc
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.route.v3.Route
                      match:
                        prefix: /
                      route:
                        cluster: abc_cluster
    http_filters:
    - name: envoy.filters.http.router
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```

While I'm trying to add this new FilterStateMatchInput, I notice Route table can only match on request headers. If I want to make filter state match work, I might need to change limitation here.
https://github.com/envoyproxy/envoy/blob/1ddf0f5d8fade9c4209a12b34f6959bc7a90e840/source/common/router/config_impl.cc#L144
In this case, may I know if this is the right way to go, or are there any other ways to achieve similar functionality? If it is, I would like to take it and make it work, thanks.
