### ISSUE TITLE
Setting a tracing tag based on the response of ratelimit?

### ISSUE THREAD

**Issue by DanTulovsky** [envoyproxy/envoy#32815]
*Title*: Setting a tracing tag based on the response of ratelimit?

*Description*:
I have a fairly standard config where we use:

```
'@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
```

This filter is executed correctly.  What I would like to do is to set a tracing tag on the *main* envoy span generated that is based on the response of this filter.  This is what the filter looks like:

```
                      - name: envoy.filters.http.ratelimit
                        typed_config:
                          '@type': type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
                          domain: public_api
                          enable_x_ratelimit_headers: DRAFT_VERSION_03
                          failure_mode_deny: false
                          rate_limited_as_resource_exhausted: true
                          timeout: 1s
                          response_headers_to_add:
                            header:
                              key: rate-limit-exceeded
                              value: "true"
                            append_action: OVERWRITE_IF_EXISTS_OR_ADD
                          rate_limit_service:
                            grpc_service:
                              envoy_grpc:
                                cluster_name: xlimit
                              timeout: 1s
                            transport_api_version: V3
```

So when the rate limit is exceeded, the filter sets the "rate-limit-exceeded" header on the response.  What I can't figure out is how can I then use this header to set a tag on the envoy span?

I tried adding a lua filter *after* the ratelimit filter that looks like this:

```
                              typed_per_filter_config:
                                custom-lua-filter-tags:
                                  '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.LuaPerRoute
                                  name: tags.lua
```

```
local HEADER_LS_RATE_LIMIT_EXCEEDED = "rate-limit-exceeded"
local CUSTOM_LUA_FILTER = "custom-lua-filter-tags"
local RATELIMIT_TAG = "ratelimit_exceeded"

local function process_response_headers(response_handle)
  -- this is used to set the ratelimit_exceeded attribute on the spans
  -- when a call xlimit using the built in envoy machanism returns a 429
  -- we insert dynamicMetadata, and then use that value to set the attribute
  -- the xlimit call sets the "rate-limit-exceeded" when rate limit is exceeded
  local limit_exceeded_header = response_handle:headers():get(HEADER_LS_RATE_LIMIT_EXCEEDED)

  if limit_exceeded_header ~= nil then
    local request_handle = response_handle:request()
    if request_handle == nil then
      return
    end

    request_handle:streamInfo():dynamicMetadata():set(CUSTOM_LUA_FILTER, RATELIMIT_TAG, "true")
  end
end

function envoy_on_response(response_handle)
  local ok, err = pcall(process_response_headers, response_handle)
  if not ok then
    response_handle:logErr("lua script error: failed to execute process_response_headers: " .. (err or ""))
  end
end
```

And then I added this to `custom_tags` config of tracing:

```
                        - tag: ratelimit_exceeded
                          metadata:
                            kind:
                              request: {}
                            metadata_key:
                              key: custom-lua-filter-tags
                              path:
                                - key: ratelimit_exceeded
```

Is there another way to do what I want.  The end result just needs to be a `ratelimit_exceeded` tag on the main envoy span generated for the request.

Thank you
Dan

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
