### ISSUE TITLE
[1.26.4] extproc setting "response_header_mode" seems to have no impact

### ISSUE THREAD

**Issue by tfrokt** [envoyproxy/envoy#32835]
We have set up an ext proc envoy filter being interested only in "header" requests. But even if setting only `request_header_mode: SEND` and all others to `SKIP` or `NONE` (as described here [[1](https://www.envoyproxy.io/docs/envoy/v1.26.4/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto.html#extensions-filters-http-ext-proc-v3-processingmode)]) we are seeing "response" requests.

We are counting every single incoming request (metricRequestReceivedCount) as well as:

- any issues (metricRequestReceivedErrorCount)
- a "header" request (metricRequestHeadersReceivedCount)
- a "body" request (metricRequestBodyReceivedCount) and
- a "response" request (metricResponseReceivedCount)

We are always seeing: `metricRequestReceivedCount = metricRequestReceivedErrorCount + metricRequestHeadersReceivedCount + metricResponseReceivedCount`

![Screenshot 2024-03-12 at 4 42 54 pm](https://github.com/envoyproxy/envoy/assets/82917641/566adcd8-77b4-4b43-a04c-38be92c72aa8)

Regarding the above, I have two questions:

1. Why are we getting "response" requests at all?
2. What could be a reason for getting any `io.EOF`s?

istio: 1.18.2
envoy: 1.26.4

**golang (stripped down)**
```
extProcPb "github.com/envoyproxy/go-control-plane/envoy/service/ext_proc/v3"

[..]

requestReceived, receivedError := processServer.Recv()
metricRequestReceivedCount += 1

if receivedError == io.EOF {
    metricRequestReceivedErrorCount += 1
}

switch castedRequest := requestReceived.Request.(type) {

case *extProcPb.ProcessingRequest_RequestHeaders:

metricRequestHeadersReceivedCount += 1

case *extProcPb.ProcessingRequest_RequestBody:

metricRequestBodyReceivedCount += 1

case *extProcPb.ProcessingRequest_ResponseHeaders:

metricResponseReceivedCount += 1

[..]
```

**envoyfilter.yaml**
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: <name>-internal
  namespace: <namespace>
spec:
  workloadSelector:
    labels:
      edgeType: internal
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ext_proc
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
            value:
              stat_prefix: <stat_prefix>
              failure_mode_allow: true
              async_mode: false
              message_timeout:
                seconds: 0
                nanos: 30000000
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SKIP"  <-- this one
                request_body_mode: "NONE"
                response_body_mode: "NONE"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"
              grpc_service:
                google_grpc:
                  target_uri: <service>.<namespace>.svc.cluster.local:9090
                  stat_prefix: required_but_does_nothing
```

[1] https://www.envoyproxy.io/docs/envoy/v1.26.4/api-v3/extensions/filters/http/ext_proc/v3/processing_mode.proto.html#extensions-filters-http-ext-proc-v3-processingmode
