### ISSUE TITLE
Access logs showing blanks: "-"

### ISSUE THREAD

**Issue by tfrokt** [envoyproxy/envoy#32925]
I have the following envoy.yaml config:

```
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 15000 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8081 }
    access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: /var/log/envoy/access.log
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: routes
            virtual_hosts:
            - name: localhost
              domains: ["*"]
              routes:
              - name: catchall
                match: { prefix: "/" }
                route: { cluster: echo_service }
          http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: echo_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: echo
                port_value: 8080
```

when `curl -v localhost:8081/foo` -ing it, I am getting the following logs:

```
[2024-03-15T04:27:37.009Z] "- - HTTP/1.1" 0 - 80 573 8 - "-" "-" "-" "-" "-"
[2024-03-15T04:27:37.980Z] "- - HTTP/1.1" 0 - 80 573 6 - "-" "-" "-" "-" "-"
[2024-03-15T04:27:38.417Z] "- - HTTP/1.1" 0 - 80 573 5 - "-" "-" "-" "-" "-"
[2024-03-15T04:27:59.832Z] "- - HTTP/1.1" 0 - 80 573 4 - "-" "-" "-" "-" "-"
```

most of them are blank, does anyone know why?

tried:
version: 83126f4a14c5dd34ea088871b9b0b371b26fb1f2/1.30.0-dev/Clean/RELEASE/BoringSSL and
version: 4fda4d79d06e1bd59e591be3f348223495083648/1.29.1/Clean/RELEASE/BoringSSL
