### ISSUE TITLE
CORS filter: Enable strict CORS enforcement with direct preflight response option

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#32947]
The current CORS filter implementation forwards preflight requests down to the upstream if a request doesn't match its configured condition(origins, methods, headers, etc.) .  This makes upstream response unpredictable, potentially allowing cross-origin requests even when they should be disallowed. 

Adding a configuration option to the CORS filter, enabling direct preflight responses, would allow enforcement of strict CORS rules regardless of the upstream behavior.

```
    envoy.filters.http.cors:
      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
      direct_response_when_mismatch: true         # Send a direct response and disallow the cross-origin request when the request deosn't match   
      allow_origin_string_match:
      - safe_regex:
          regex: ".*"
      allow_headers: "content-type,x-grpc-web"
      allow_methods: "GET,POST"
```
