### ISSUE TITLE
Wildcard records support in DNS filter inline table

### ISSUE THREAD

**Issue by StupidScience** [envoyproxy/envoy#32941]
**Add support for wildcard records in DNS filter inline table**

I've tested locally and DNS filter doesn't seem to support wildcard records for inline table, e.g. snippet below does not match `abc.example.com` and forward request to configured resolvers.
```yaml
inline_dns_table:
  virtual_domains:
    - name: "*.example.com"
      endpoint:
        address_list:
          address:
          - 127.0.5.5
```

Didn't find any other available options to configure this in docs so I assume it is not supported yet.
