### ISSUE TITLE
Running extp roc per route or vhost

### ISSUE THREAD

**Issue by tfrokt** [envoyproxy/envoy#32951]
We would like to run an ext proc for selected routes. At the beginning we would like to enable a few selected routes only (allowlist), later in the project we want to open most routes to the ext proc after testing, but still keep some unaffected (denylist). The latter I can achieve by doing the following:

```
http_filters:
- name: envoy.filters.http.ext_proc
  typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
    failure_mode_allow: true
    async_mode: false
    message_timeout:
      seconds: 5
      nanos: 0
    processing_mode:
      request_header_mode: "SEND"
      response_header_mode: "SKIP"
      request_body_mode: "NONE"
      response_body_mode: "NONE"
      request_trailer_mode: "SKIP"
      response_trailer_mode: "SKIP"
    grpc_service:
      google_grpc:
        target_uri: "<our service>:9090"
        stat_prefix: "<prefix>"
```

and then disabling every single vhost/route like this:

```
routes:
- name: root
   match: { prefix: "/" }
   route: { cluster: echo_service }
  typed_per_filter_config:
    envoy.filters.http.ext_proc:
      "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute"
      disabled: true
```

Any attempt to allow a few selected routes/vhosts have failed so far. 
I have tried applying `ExtProcPerRoute` with `disabled: true` to all VIRTUAL_HOSTs and then re-enable some routes with `disabled: false`, but "false" is not allowed.
Also using "overrides" either empty (`{}`) or with the same grpc service does not re-enable anything.

Is there a simple, working approach to have ext proc on _some_ routes?
