### ISSUE TITLE
Routing PostgreSQL queries based on query type

### ISSUE THREAD

**Issue by dev-sap** [envoyproxy/envoy#32954]
Hi,

I want to route PostgreSQL queries to different clusters based on the query type (e.g., SELECT statements should be routed to a replica cluster, while other queries should be routed to a master cluster).
The Postgres filter parses SQL statements and emits dynamic metadata, but I have not found a built-in way to route requests based on this metadata. I have tried using the envoy.filters.network.tcp_proxy.v3.TcpProxy filter along with a Lua filter to extract the query type and route to the right cluster, but this approach did not work as expected.

This my base configuration

**envoy.yaml:**

```
node:
  cluster: envoy-node-1
  id: envoy-node-1

dynamic_resources:
  lds_config:
    resource_api_version: V3
    path: /etc/envoy/lds.yaml
  cds_config:
    resource_api_version: V3
    path: /etc/envoy/cds.yaml

```

**/etc/envoy/lds.yaml:**

```
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
  filter_chains:
  - filters:
    - name: envoy.filters.network.postgres_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
        stat_prefix: postgres
    - name: envoy.tcp_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
        stat_prefix: tcp
        cluster: postgres_cluster_master
```

**/etc/envoy/cds.yaml:**

```
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: postgres_cluster_master
  connect_timeout: 0.25s
  lb_policy: round_robin
  load_assignment:
    cluster_name: postgres_cluster_master
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 192.168.0.111
              port_value: 6432
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: postgres_cluster_replica
  connect_timeout: 0.25s
  lb_policy: round_robin
  load_assignment:
    cluster_name: postgres_cluster_replica
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 192.168.0.110
              port_value: 6432    
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 192.168.0.112
              port_value: 6432

```
