### ISSUE TITLE
Allow coexists of cluster name and cluster_header to make dynamic cluster selection more flexible

### ISSUE THREAD

**Issue by LoremipsumSharp** [envoyproxy/envoy#32999]
*Title*: *Coexists of cluster name and cluster header to allow dynamic cluster selection more flexible*

*Description*:
Currently we use istio virtual service to configure the envoy instance (`istio ingress gateway`) and we are trying to select the cluster dynamically for the incoming request. For example, when the request has a particular `header baggager-cluster-A=cluster-b`, then I use `cluster-b` as the upstream cluster for the request。I have used the `EnvoyFilter` to patch the envoy config:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cluster-name-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: "httpbin.example.com:80"
    patch:
      operation: MERGE
      value:
        route:
          cluster_header: baggager-cluster-A
```
 According to the document, for dynamic cluster selection, we should configure the `cluster_header` filed for the routes, and the cluster `name` field and `cluster_header` field are unable to configure at the same time However, for some scenario  the `header baggager-cluster-A` does not always present in the request, when the `header baggager-cluster-A` is miss, the request would fail because the envoy has no knowledge about which cluster to forward the request.

 Soultion1:
I come out with an idea that to use the wasm plugin to fill the value to header `baggager-cluster-A` if header `baggager-cluster-A` is miss, however, the wasm plugin has to the maintain a huge configuration for the relationship of route and cluster which already exists (`VirtualService`) it makes things more complicate,

Put it all together, if the `header baggager-cluster-A=cluster-b` miss,how can i keep the request forward to the original cluster?

**Comment by htuch** [comment]
It seems a reasonable behavior, basically a default cluster header value. @markdroth @yanavlasov thoughts?

**Comment by markdroth** [comment]
The behavior does seem reasonable.  However, I don't understand why it's complicated to have a filter set the header if it doesn't already exist.  Note that if you need to set the default on a per-route basis, you can do that by overriding the filter's config for each route.

**Comment by LoremipsumSharp** [comment]
> The behavior does seem reasonable. However, I don't understand why it's complicated to have a filter set the header if it doesn't already exist. Note that if you need to set the default on a per-route basis, you can do that by overriding the filter's config for each route.

 OK I would demonstrate the idea through code briefly.
```golang
func (*httpContext) OnHttpRequestHeaders(numHeaders int, endOfStream bool) types.Action {
	key := "x-dynamic-cluster"
	_, err := proxywasm.GetHttpRequestHeader(key)
	if err == nil {
		proxywasm.LogCriticalf("the header %s already exists", key)
		return types.ActionContinue
	}
        // trying to figure out the default cluster for the request,howerver the defaultClusterName is always empty beacuse the envoyfilter has patch the cluster_name filed
	defaultClusterName := properties.GetXdsClusterName()
       // parsing the default cluster name into a struct
	defaultCluster := ParseClusterName(defaultClusterName)
       // when fail to parse ,using the default cluster name to allow the request forward to default cluster
	if defaultCluster == nil {
		proxywasm.LogCriticalf("failed to parse the cluster info %s", defaultClusterName)
		proxywasm.AddHttpRequestHeader(key, defaultClusterName)
		return types.ActionContinue
	}
	allHeaders, err := proxywasm.GetHttpRequestHeaders()
	if err != nil {
		proxywasm.LogCriticalf("failed to get the headers %v", err)
		proxywasm.AddHttpRequestHeader(key, defaultClusterName)
		return types.ActionContinue
	}
	for _, header := range allHeaders {
                // get all the headers from the request,and compare to determine if the request should forward to another  cluster
		if strings.HasPrefix(header[0], "baggage-host-rewrite-") {
			originCluster := strings.TrimPrefix(header[0], "baggage-host-rewrite-")
			targetCluster := header[1]
			if originCluster == defaultCluster.ServiceName {
				targetClusterName := strings.Replace(defaultClusterName, defaultCluster.ServiceName, targetCluster, 1)
				proxywasm.AddHttpRequestHeader(key, newClusterName)
				return types.ActionContinue
			}
		}
	}
	proxywasm.AddHttpRequestHeader(key, defaultClusterName)

	return types.ActionContinue
}
```


```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: cluster-name-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      app: istio-ingressgateway
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: "httpbin.example.com:80"
    patch:
      operation: MERGE
      value:
        route:
          cluster_header: x-dynamic-cluster
```
My main purpose is to allow QA and DEV to choose the cluster dynamically for all the route configue by `VirutalService` ,  how can I determine a default cluster for a request after the `EnvoyFilter` apply?
