### ISSUE TITLE
route direct_response does not allow to set the response headers using response_headers_to_add

### ISSUE THREAD

**Issue by ldb** [envoyproxy/envoy#33113]
**Title**: **`response_headers_to_add` does not work in a `direct_response` route**

*Description*:
When using a `direct_response` route, `response_headers_to_add` are not respected.

*Config*:
```yaml
- direct_response:
    body:
      inline_string: |
        <!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>
          <body>Nothing to see here (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧</body>
        </html>
    response_headers_to_add:
      - header:
          key: content-type
          value: text/html
      - header:
          key: x-testing
          value: value
    status: 404
  match:
    prefix: /
  name: default_route_notfound
```

*curl output*:
```bash
~ $ curl -v localhost:8080/
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: somesanitizedhost.com
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< content-length: 168
< content-type: text/plain
< access-control-allow-methods: GET,HEAD,PUT,PATCH,POST,DELETE
< access-control-allow-origin: *
< access-control-max-age: 300
< date: Tue, 26 Mar 2024 11:21:59 GMT
< server: envoy
< x-request-id: f567c4cb-ffbb-97b6-bc4f-53a799f83bd3
<
<!DOCTYPE html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>
  <body>Nothing to see here (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧</body>
</html>
* Connection #0 to host localhost left intact
```

neither `content-type` nor `x-testing` appear in the response.
