### ISSUE TITLE
Overload manager action to fail readiness check

### ISSUE THREAD

**Issue by inssein** [envoyproxy/envoy#33168]
The recommendation in https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge#best-practices-edge for configuring an overload manager looks like so:

```
  - name: "envoy.overload_actions.shrink_heap"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.95
  - name: "envoy.overload_actions.stop_accepting_requests"
    triggers:
    - name: "envoy.resource_monitors.fixed_heap"
      threshold:
        value: 0.98
```

For folks who are running envoy in a cloud native environment, would it not be better to provide an action that will start failing the healtcheck, so the `/ready` endpoint starts failing? In this scenario, traffic won't be sent to the pod until the service is healthy again.
