### ISSUE TITLE
Http to TCP

### ISSUE THREAD

**Issue by evertondmorais** [envoyproxy/envoy#33171]
Hello, I've set up an envoy proxy to receive HTTP requests and forward them over TCP. The communication is successful, but the behavior is not okay. After Envoy forwards the data to the TCP server, Envoy sends a .FIN to the server, which responds with an ACK. The expectation is that the connection would be maintained so that the TCP server can return a response. I have changed various connection timeout parameters, but none have been successful.

```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9902
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                            headers:
                              - name: ":method"
                                string_match:
                                  exact: "POST"
                          route:
                            cluster: service
                            upgrade_configs:
                              - upgrade_type: CONNECT
                                connect_config:
                                  allow_post: true
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http2_protocol_options:
                  allow_connect: true
  clusters:
    - name: service
      connect_timeout: 30s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 192.168.0.31
                      port_value: 13370
```
