### ISSUE TITLE
Understanding Maglev and Ring-Hash with Health Checks in Envoy

### ISSUE THREAD

**Issue by iMeth0d** [envoyproxy/envoy#33209]
I'm encountering difficulties understanding how Maglev and Ring-Hash load balancing strategies function alongside health checks. I've set up a local environment using docker-compose to reproduce the scenario. Envoy-1.29.0
The setup includes:
	•	3 curl containers for sending requests.
	•	3 backend containers running Nginx.
When all instances are operational, everything functions as expected. However, issues arise when I manually disable 2 out of the 3 Nginx containers. Despite these backends being marked as unhealthy by Envoy's health checks (transitioning to an 'unhealth' status within the cluster), load rebalancing does not seem to occur. Consequently, 2 out of the 3 curl containers continue to direct requests towards the disabled backends.
I'm wondering whether this behavior is expected or if I'm missing a specific configuration to handle such scenarios. Could you please advise on this matter?
Thank you for your assistance.
```
---
version_info: '0'
resources:
- '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
  connect_timeout: 2s
  name: envoy-clstr
  type: STATIC
  lb_policy: maglev
  load_assignment:
    cluster_name: envoy-clstr
    endpoints:
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "stateful-nginx1-1"
                port_value: 80
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "stateful-nginx2-1"
                port_value: 80
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: "stateful-nginx3-1"
                port_value: 80
  health_checks:
    - timeout: 10s
      interval: 5s
      no_traffic_interval: 5s
      unhealthy_threshold: 2
      healthy_threshold: 1
      http_health_check:
        path: "/"
        expected_statuses:
          - start: 200
            end: 299
...
---
resources:
  - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
    name: ext-envoy-lstnr
    address:
      socket_address: { address: "0.0.0.0", port_value: 8080 }
    filter_chains:
      - filters:
        - name: envoy.filters.network.tcp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            cluster: envoy-clstr
            stat_prefix: envoy
            hash_policy:
            - source_ip: {}
            access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                log_format:
                  json_format:
                    downstream: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                    protocol: "%PROTOCOL%"
                    duration: "%DURATION%"
                    method: "%REQ(:METHOD)%"
                    path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    resp_code: "%RESPONSE_CODE%"
                    xff: "%REQ(X-FORWARDED-FOR)%"
                    backend: "%UPSTREAM_HOST%"
                    start_time: "%START_TIME%"
                    request_id: "%REQ(REQUEST-ID)%"
                    caller: "%REQ(CALLER)%"

...

```
