### ISSUE TITLE
Didn't find a registered implementation for 'envoy.filters.network.wasm'

### ISSUE THREAD

**Issue by oripka** [envoyproxy/envoy#33337]
I am trying to use a rust wasm module to set to set the sni port dynamically but envoy does give errors when starting with this config.

```
      | [2024-04-04 10:45:41.735][10][debug][config] [source/common/listener_manager/listener_manager_impl.cc:168]   config: {"@type":"type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm","config":{"name":"dynamic_port_filter","root_id":"dynamic_port_filter_root","vm_config":{"runtime":"envoy.wasm.runtime.v8","code":{"local":{"filename":"/etc/envoy/proxy-wasm-plugins/dynamic_port_filter.wasm"}},"allow_precompiled":true},"configuration":{"@type":"type.googleapis.com/google.protobuf.StringValue","value":"{}"}}}
envoy-1        | [2024-04-04 10:45:41.735][10][debug][init] [source/common/init/watcher_impl.cc:31] Listener-local-init-watcher listener_0 destroyed
envoy-1        | [2024-04-04 10:45:41.735][10][debug][init] [source/common/init/watcher_impl.cc:31] init manager Listener-local-init-manager listener_0 8978400395211644739 destroyed
envoy-1        | [2024-04-04 10:45:41.735][10][debug][init] [source/common/init/target_impl.cc:34] target Listener-init-target listener_0 destroyed
envoy-1        | [2024-04-04 10:45:41.735][10][critical][main] [source/server/server.cc:416] error initializing config '  /etc/envoy/envoy-transparent.yaml': Didn't find a registered implementation for 'envoy.filters.network.wasm' with type URL: 'envoy.extensions.filters.network.wasm.v3.Wasm'
```

envoy-transparent.yaml

```
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 15001
    listener_filters:
    - name: "envoy.filters.listener.original_dst"
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
    - name: envoy.filters.network.wasm
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
        config:
          name: "dynamic_port_filter"
          root_id: "dynamic_port_filter_root"
          configuration: 
            "@type": type.googleapis.com/google.protobuf.StringValue
            value: "{}"
          vm_config:
            runtime: "envoy.wasm.runtime.v8"
            code:
              local:
                filename: "/etc/envoy/proxy-wasm-plugins/dynamic_port_filter.wasm"
            allow_precompiled: true
    filter_chains:
      - filter_chain_match: 
          transport_protocol: tls
          #destination_port: 443
        filters:
          - name: envoy.filters.network.sni_dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.sni_dynamic_forward_proxy.v3.FilterConfig
              # Note: The port_value is removed. Ensure your WASM filter sets the dynamic port correctly.
              # port_value: 443
              dns_cache_config:
                name: dynamic_forward_proxy_cache_config
                dns_lookup_family: V4_ONLY
          - name: envoy.tcp_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              stat_prefix: tcp
              cluster: dynamic_forward_proxy_cluster
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/dev/stdout"
                  json_format:
                    start_time: "%START_TIME%"
                    method: "%REQ(:METHOD)%"
                    path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    protocol: "%PROTOCOL%"
                    response_code: "%RESPONSE_CODE%"
                    response_flags: "%RESPONSE_FLAGS%"
                    bytes_received: "%BYTES_RECEIVED%"
                    bytes_sent: "%BYTES_SENT%"
                    duration: "%DURATION%"
                    upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                    x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                    user_agent: "%REQ(USER-AGENT)%"
                    request_id: "%REQ(X-REQUEST-ID)%"
                    authority: "%REQ(:AUTHORITY)%"
                    upstream_host: "%UPSTREAM_HOST%"
                    upstream_cluster: "%UPSTREAM_CLUSTER%"
                    upstream_local_address: "%UPSTREAM_LOCAL_ADDRESS%"
                    downstream_local_address: "%DOWNSTREAM_LOCAL_ADDRESS%"
                    downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                    requested_server_name: "%REQUESTED_SERVER_NAME%"
                    route_name: "%ROUTE_NAME%"
  clusters:
  - name: dynamic_forward_proxy_cluster
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dynamic_forward_proxy_cache_config
          dns_lookup_family: V4_ONLY
```

docker-compose.yml

```
version: '3.7'
services:
  envoy:
    build:
      context: . # The directory containing your Dockerfile and iptables script
      dockerfile: Dockerfile.envoy # The path to your Dockerfile
    volumes:
      - ./envoy-config:/etc/envoy
    networks:
      - envoy-net
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
      - "15001:15001"

networks:
  envoy-net:
    driver: bridge
```

Dockerfile.envoy

```
# Use the Envoy image as the base
FROM envoyproxy/envoy:v1.29-latest

# Install nftables
RUN apt-get update && apt-get install -y nftables iptables

COPY wasm/dynamic_port_filter.wasm /etc/envoy/proxy-wasm-plugins/dynamic_port_filter.wasm
COPY nftables.conf /etc/nftables.conf
COPY start-envoy.sh /usr/local/bin/start-envoy.sh
RUN chmod +x /usr/local/bin/start-envoy.sh

USER root
# Use the new script as the entry point
ENTRYPOINT ["/usr/local/bin/start-envoy.sh"]


```

dyamic_port_filter.rs
```
use proxy_wasm::traits::*;
use proxy_wasm::types::*;
use std::str; // Ensure this is kept if you're using str::from_utf8

#[no_mangle]
pub fn _start() {
    proxy_wasm::set_log_level(LogLevel::Trace);
    proxy_wasm::set_stream_context(|context_id, _| -> Box<dyn StreamContext> {
        Box::new(DynamicPortTcpFilter { context_id })
    });
}

struct DynamicPortTcpFilter {
    #[allow(dead_code)]
    context_id: u32,
}

impl Context for DynamicPortTcpFilter {}

impl StreamContext for DynamicPortTcpFilter {
    fn on_new_connection(&mut self) -> Action {
        // Extract the original destination port and set it as the dynamic port
        if let Some(data) = self.get_property(vec![
            "envoy.network.transport_socket.original_dst_address",
        ]) {
            if let Ok(original_dst) = str::from_utf8(&data) {
                if let Some(pos) = original_dst.rfind(':') {
                    let port_str = &original_dst[(pos + 1)..];
                    // Corrected the set_property call
                    self.set_property(
                        vec!["envoy.upstream.dynamic_port"],
                        Some(port_str.as_bytes()),
                    );
                }
            }
        }
        Action::Continue
    }
}

```

**Comment by oripka** [comment]
Was my mistake

```
    filter_chains:
      - filter_chain_match: 
          transport_protocol: tls
          #destination_port: 443
        filters:
          - name: envoy.filters.network.wasm
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm
              config:
                name: "dynamic_port_filter"
                root_id: "dynamic_port_filter_root"
                configuration: 
                  "@type": type.googleapis.com/google.protobuf.StringValue
                  value: "{}"
                vm_config:
                  runtime: "envoy.wasm.runtime.v8"
                  code:
                    local:
                      filename: "/dynamic_port_filter.wasm"
                  allow_precompiled: true
```

fitler was in listener filters not filter_chains
