### ISSUE TITLE
Ability to format the outlier event log entry

### ISSUE THREAD

**Issue by charliezgc** [envoyproxy/envoy#3335]
*Title*: *Ability to custom format the outlier event log entry by configuration*

*Description*:
Please provide a means to configure a format for outlier event log entries, much the same way of access logs. E.g.,
```
cluster_manager:
  outlier_detection:
    event_log_path: /var/log/envoy/outlier-event.log
    format: [log entry format_ similar to file access log configuration]
```
In our use case, we consolidate all envoy logs to a unified format and transmit to a central location for further processing. Currently we tail the outlier event log, translate it, and write out a new log in a new format. It would be great if the event log records are immediately consumable.
