### ISSUE TITLE
working example for zone aware routing?

### ISSUE THREAD

**Issue by mousimin** [envoyproxy/envoy#33501]
*Title*: Do we have a working example for the zone aware routing?

*Description*:
I am trying the zone aware routing feature for envoy, and I see from the document, [it](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/zone_aware_routing.html) says I need to set the local_cluster_name as the source cluster, so my questions are:
1. Can I select any cluster in static_resources.clusters as the local_cluster_name? Is there any requirement for it? such as the zone information must be same with the envoy instance - just my quess, I didn't find any document for this.
2. If I have clustera, clusterb, clusterc, clusterd, let's say we set local_cluster_name as clustera, so only the traffic sent from clustera will be routed following the zone, but how about the traffic sent from the other clusters like clusterb, clusterc, clusterd? I'd like to let all traffic follow the zone, how to do that?

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/zone_aware_routing.html

**Comment by phlax** [comment]
i think the answer is no, but probably it would be useful if we did

**Comment by RyanTheOptimist** [comment]
cc: @alyssawilk @mattklein123

**Comment by mousimin** [comment]
I tried the following steps to test the behavior:
1. Configure envoy using two virtual_hosts(s1.example.com/s2.example.com) and two clusters(cluster_1/cluster_2), each cluster contains 6 endpoints(cluster_1->e1/e2/e3/e4/e5/e6, cluster_2->e1/e2/e3/e4/e5/e6), the endpoints have different zone settings, s1.example.com maps to cluster_1 and s2.example.com maps to cluster_2
2. Run the programs. The program behind cluster_1/cluster_2 is very simple, program1(cluster_1) presents a /query API which will call program2(cluster_2)'s / API, and get the zone setting of the node it's running on and  the node program2(cluster_2) is running on, so we can see the request will go cross zone or not.  
3. call https://s1.example.com/query, unfortunately I see the request goes cross the zone
the output will be gic-seli->gic-seli or gic-sero->gic-seli, but never gic-sero->gic-sero or gic-seli->gic-sero

Anything I missed?
The config files I used(Only essential parts are listed)
#########envoy.yaml#########
```
cluster_manager:
  local_cluster_name: "cluster_1"
static_resources:
  clusters:
    - name: cluster_1
      lb_policy: round_robin
      common_lb_config:
        zone_aware_lb_config:
          min_cluster_size: 6
      eds_cluster_config:
        eds_config:
          path_config_source:
            path: '/local/envoy/conf/eds_c1.yaml'
      type: EDS
    - name: cluster_2
      lb_policy: round_robin
      common_lb_config:
        zone_aware_lb_config:
          min_cluster_size: 6
      eds_cluster_config:
        eds_config:
          path_config_source:
            path: '/local/envoy/conf/eds_c2.yaml'
      type: EDS
```
	  
	  
#########eds_c1.yaml#########
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  cluster_name: cluster_1
  endpoints:
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.1
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-seli
        zone: "11"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.2
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-seli
        zone: "12"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.3
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-seli
        zone: "13"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.4
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-sero
        zone: "21"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.5
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-sero
        zone: "22"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.6
                port_value: 30001
            health_check_config:
              port_value: 30001
      locality:
        region: gic-sero
        zone: "23"
```
		
#########eds_c2.yaml#########
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
  cluster_name: cluster_2
  endpoints:
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.1
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-seli
        zone: "11"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.2
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-seli
        zone: "12"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.3
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-seli
        zone: "13"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.4
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-sero
        zone: "21"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.5
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-sero
        zone: "22"
    - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 100.76.120.6
                port_value: 30000
            health_check_config:
              port_value: 30000
      locality:
        region: gic-sero
        zone: "23"
```
