### ISSUE TITLE
Proxy both HTTP and HTTPS to upstream http_proxy

### ISSUE THREAD

**Issue by sabershahhoseini** [envoyproxy/envoy#33532]
*Title*: Proxy both http and https to upstream http_proxy

*Description*: Hey folks, I need some help figuring out how to configure envoy to proxy both HTTP and HTTPS to an upstream proxy. My configuration works perfect for HTTPS requests. But I get 404 or 502 or 503 depending on config I'm using on HTTP requests and sometimes envoy doesn't even bother to proxy it to the upstream proxy server.

Here's my plan: [Client => envoy => Upstream proxy (http) => htttp(s)//example.org ]

My configuration:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 81
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          upgrade_configs:
            upgrade_type: CONNECT

          codec_type: AUTO
          stat_prefix: service1
          route_config:
            request_headers_to_add:
              - header:
                  key: "Proxy-Authorization"
                  value: "Basic Ynp3eWdmY3o6NTc0aGFmcHRjaG15Cg=="
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  connect_matcher: {}
                route:
                  cluster: external_proxy_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: external_proxy_cluster
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: external_proxy_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: http_proxy_server
                port_value: proxy_port
```

And here are some logs. First line is HTTPS request and second is HTTP:

```
[2024-04-15T08:22:22.557Z] "CONNECT - HTTP/1.1" 200 downstream_remote_disconnect - DownstreamEnd DC 840 17379 2063 - "-" "curl/7.81.0" "ee200bac-d321-44ec-8a13-a6a323459ebe" "example.com:443" "http_proxy_server:port"
[2024-04-15T08:22:26.582Z] "GET / HTTP/1.1" 502 via_upstream - DownstreamEnd - 0 19 384 384 "-" "curl/7.81.0" "1b65c4c5-6b92-4013-80d1-930f1813d640" "example.com" "http_proxy_server:port"
```

Edit: I should also note tham I've read some issues relating my problem and tested other people configurations, no luck.

For example, I've added a second route like:

```
              - match:
                  prefix: "/"
                route:
                  cluster: external_proxy_cluster
                  upgrade_configs:
                    upgrade_type: CONNECT
```

With or without upgrade configs, it does not work.
