### ISSUE TITLE
Most of the subsequent requests fails (HTTP 503) if there is any issue in the WASM plugin

### ISSUE THREAD

**Issue by swapnilaniljanorkarjanorkar-sap** [envoyproxy/envoy#33600]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
All the subsequent requests fails if there is any issue in the WASM plugin

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
WASM plugin reads the Authorisation header (bearer token) from request and decode it. After decoding the token some info from token (user information) is set in the request header. 

I have observed that some times `GetHttpRequestHeaders` method of [proxy-wasm-go-sdk](https://github.com/tetratelabs/proxy-wasm-go-sdk) is returning the following error, and after retuning this error most of the subsequent request are returning error (Socket closed by remote peer). (These requests are supposed to be retuning HTTP 200) 
```
2024-04-09T16:58:38.711061Z critical envoy wasm external/envoy/source/extensions/common/wasm/context.cc:1157
wasm log istio-system.istio-tenant-id-wasm-filter: Failed to get request headers: unknown status code: 6 thread=48
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
I could not reproduce the exact scenario but managed to do work around to reproduce it.
1. Pass the header [error: true] in request.
2. If this error is present then to simulate the plugin crash, divide the integer by zero. 
3. Send few request with header [error: true], wasm filter returns an error. (Socket closed by remote peer). 
4. Now remove the  header [error: true]. Even after removing the header wasm filter returns an error. (Socket closed by remote peer).  
5. WASM filter only starts returning HTTP 200 after restarting the plugin.

```
requestHeaders, err := proxywasm.GetHttpRequestHeaders()

	for _, header := range requestHeaders {
		//proxywasm.LogCriticalf("header: %s, value: %s", header[0], header[1])
		if strings.EqualFold(header[0], "error") {
			proxywasm.LogCritical("simulating header retrieval error, Setting requestHeaders error")
			i := 0
			abca := 1 / I
			proxywasm.LogCriticalf("abc %d", abca)
			// requestHeaders, err = returnError()
			// break
			return types.ActionContinue
		}
	}
```
>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
```
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 18000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: web_service
                http_filters:
                  - name: envoy.filters.http.wasm
                    typed_config:
                      "@type": type.googleapis.com/udpa.type.v1.TypedStruct
                      type_url: type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
                      value:
                        config:
                          configuration:
                            "@type": type.googleapis.com/google.protobuf.StringValue
                            value: |
                              {
                                "header": "<header-name>",
                                "value": "<header-value>"
                              }
                          vm_config:
                            runtime: "envoy.wasm.runtime.v8"
                            code:
                              local:
                                filename: "/etc/envoy/istio-plugin.wasm"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

    - name: staticreply
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8099
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "example body\n"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: web_service
      connect_timeout: 0.25s
      type: STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: mock_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8099

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
