### ISSUE TITLE
force (zipkin) tracing to create new span for ingress operation

### ISSUE THREAD

**Issue by wknd-dev** [envoyproxy/envoy#3361]
*Title*: *force (zipkin) tracing to create new span for ingress operation*

*Description*:
>We want all ingress operation to -
1. start new span in same trace id
2. use incoming span id (x-b3-spanid) as parent span id (x-b3-parentspanid)of new span.

I tried various things without any success

- sending x-b3-parentspanid and/or not sending x-b3-spanid

- setting x-client-trace-id from client

- setting config: { start_child_span: "true" } in router

Can you pls confirm what should be the envoy.http_connection_manager config to force new span under incoming trace & span?

Here is my config -
```
...
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          tracing:
            operation_name: ingress
          #generate_request_id: true
          codec_type: auto
          stat_prefix: echo_stat
          route_config:
            name: echo_route
            virtual_hosts:
            - name: echo_vh
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: echo_cluster
                  auto_host_rewrite: true
                decorator:
                  operation: echo_ingress
          http_filters:
          - name: envoy.router
            #config: { start_child_span: "true" }
            config: { }
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain: { filename: "/data/cert.pem" }
              private_key: { filename: "/data/key.pem" }
...
```
