### ISSUE TITLE
Envoy Logs are on in json format and Logviewer identified them as error

### ISSUE THREAD

**Issue by lijie123bes** [envoyproxy/envoy#33640]
I am very much new to envoy. I am trying to print the envoy container logs in json format and print them in console.

Below is my configuration but it seems to make no difference

```yaml
admin:
  access_log:
    - name: envoy.access_loggers.stdout
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        log_format:
          json_format:
            start_time: "%START_TIME%"
            status: "%RESPONSE_CODE%"
            server_protocol: "%PROTOCOL%"
            request_method: "%REQ(:METHOD)%"
            request_uri: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            response_flags: "%RESPONSE_FLAGS%"
            request_length: "%BYTES_RECEIVED%"
            bytes_sent: "%BYTES_SENT%"
            request_time: "%DURATION%"
            upstream_response_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
            http_x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
            http_user_agent: "%REQ(USER-AGENT)%"
            request_id: "%REQ(X-REQUEST-ID)%"
            request_authority: "%REQ(:AUTHORITY)%"
            upstream: "%UPSTREAM_HOST%"
....
....
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { protocol: TCP, address: 0.0.0.0, port_value: 8000 }
    # -----PROXY protocol configurations-----
    listener_filters:
    - name: envoy.filters.listener.proxy_protocol
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
    # -----PROXY protocol configurations-----
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
            - name: envoy.access_loggers.stdout
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                log_format:
                  json_format:
                    start_time: "%START_TIME%"
                    status: "%RESPONSE_CODE%"
                    server_protocol: "%PROTOCOL%"
                    request_method: "%REQ(:METHOD)%"
                    request_uri: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                    response_flags: "%RESPONSE_FLAGS%"
                    request_length: "%BYTES_RECEIVED%"
                    bytes_sent: "%BYTES_SENT%"
                    request_time: "%DURATION%"
                    upstream_response_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                    http_x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                    http_user_agent: "%REQ(USER-AGENT)%"
                    request_id: "%REQ(X-REQUEST-ID)%"
                    request_authority: "%REQ(:AUTHORITY)%"
                    upstream: "%UPSTREAM_HOST%"
````
And the envoy logs are still in plain text When the logs are pushed to gcp cloud logging, they are identified as erors Podlogs:

[2024-04-03 08:03:12.802][1][info][main] [source/server/server.cc:849] all clusters initialized. initializing init manager
[2024-04-03 08:03:12.802][1][info][config] [source/server/listener_manager_impl.cc:784] all dependencies initialized. starting workers
[2024-04-03 08:03:12.807][1][warning][main] [source/server/server.cc:747] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
