### ISSUE TITLE
My Envoy gateway tcp proxy max connections too low，what's the problem?

### ISSUE THREAD

**Issue by chunhanRyan** [envoyproxy/envoy#33723]
When the Envoy is started in static configuration mode, the maximum number of connections can only reach about 1024.
Envoy version is :1.25.11, The configuration like:
```yaml
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9902 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 20000 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: tcp_local_service
          cluster: some_service
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 66.66.10.196
                port_value: 80
        - endpoint:
            address:
              socket_address:
                address: 66.66.10.195
                port_value: 80
layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      envoy:
        resource_limits:
          listener:
            listener_0:
              connection_limit: 200000
      overload:
        global_downstream_max_connections: 200000
```
I use a client to test envoy supported max keepalived connections with 2000 connection (i changed the linux process max open file，and local port ....), but i can only reach max 1024 active connection with envoy admin stats interface,
![image](https://github.com/envoyproxy/envoy/assets/19781152/4a458294-1c23-4624-af7a-9b228ef50afb)
Instead, the max connctions can be  100k+ or more when use envoy.filters.network.http_connection_manager.  Is there any key different reason?
