### ISSUE TITLE
Selecting a list of WASM filters that a request will run through based on domain/host

### ISSUE THREAD

**Issue by marc-barry** [envoyproxy/envoy#33791]
*Title*: *Question about how to select a list of WASM filters that a request will run through based on domain/host.*

*Description*:

I have a need to proxy plaintext HTTP and dynamically select the list of WASM filters a request will go through based on the domain/host. The HTTP connection manager (https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html#http-connection-manager-proto) only supports a single list of filters. I do have virtual hosts (https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto) which match based on domain and cannot use the `typed_per_filter_config` as this isn't supported for WASM filters as per https://github.com/envoyproxy/envoy/issues/26440.

To better explain what I'd like to do is the following:

- `www.example.com`
  - WASM filter 1
  - WASM filter 2
  - WASM filter 3
- `example.com`
  - WASM filter 1
- `github.com`
  - WASM filter 2
- `api.github.com`
  - WASM filter 4

I attempted to use a composite filter https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter but it is designed to match based on the [matching API](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/matching/matching_api#arch-overview-matching-api) and select a single filter. The list of domains and configurations above is simplified as I'm dealing with 100's to 1000's of domains and have many WASM filters. I am aware that I can match based on the `:authority` header but I can't direct that to a filter list.

I'm reaching out to the community to see if there is a way to accomplish what I'm trying to do with WASM filters in the absence of not being able to support it on the per route basis like other filters can.

*Relevant Links*:

- https://github.com/envoyproxy/envoy/issues/26440
- https://github.com/envoyproxy/envoy/issues/16651
- https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/188
- https://github.com/envoyproxy/envoy/issues/16651#issuecomment-847980534
- https://github.com/envoyproxy/envoy/issues/31482

**Comment by marc-barry** [comment]
I also found https://github.com/envoyproxy/envoy/issues/16651 which seems to indicate that it isn't supported yet. I also found https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/188.

**Comment by marc-barry** [comment]
A large list of issues which might be related: https://github.com/envoyproxy/envoy/issues/16651#issuecomment-847980534

**Comment by marc-barry** [comment]
The error message you get when you try to use it per filter is:
> "The filter envoy.filters.http.wasm doesn't support virtual host or route specific configurations".

**Comment by wbpcode** [comment]
cc @mpwarres

**Comment by wbpcode** [comment]
Does this make sense? https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_filters#route-based-filter-chain

By that way, you can disable all wasm filters by default in the HCM and them enable specific some wasm filters on specific virtual host.

Considering that the wasm filter has no per route level config, you can use a hack way to enable the filter.

```
  # See https://github.com/envoyproxy/envoy/issues/31482 
  typed_per_filter_config:
   wasm_x:
      "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
      config: # Note this config field could not be empty because the xDS API requirement.
        "@type": type.googleapis.com/google.protobuf.Empty  # Empty as a placeholder.
      is_optional: true
```
