### ISSUE TITLE
Start envoy error

### ISSUE THREAD

**Issue by JinmingHao** [envoyproxy/envoy#3384]
*Title*: *JSON at lines 0-0 does not conform to schema.*

*Description*:
>[2018-05-15 06:28:03.145][22][critical][main] source/server/server.cc:76] error initializing configuration '/code/service-envoy.yaml': JSON at lines 0-0 does not conform to schema.
 Invalid schema: #/properties/admin/properties/address
 Schema violation: type
 Offending document key: #/admin/address
[2018-05-15 06:28:03.145][22][info][main] source/server/server.cc:451] exiting

here is my envoy.yaml:

```
static_resources:
  listeners:
  - name: listener_0
  - address:
      socket_address:
          address: 0.0.0.0
          port_value: 9211
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: content-type
                    value: application/grpc
                route:
                  cluster: xboard
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: xboard
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8081

admin:
  access_log_path: "/var/log/envoy/admin_access.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
```
