### ISSUE TITLE
Rate limiting not working

### ISSUE THREAD

**Issue by HappyStoic** [envoyproxy/envoy#3388]
**Rate limit service**

*No request from envoy goes to my rate limit service*

Hello, I am having long term issue and I had to give up. As a rate limit service I am using reference implementation lyft rate limit running on localhost.

I recreated config to small files, so I can demonstrate my issue.
This is e.g. my rate limit config:
```
domain: rate_per_ip
descriptors:
  - key: remote_address
    rate_limit:
      unit: minute
      requests_per_unit: 3

```

and this is my simple envoy config.yaml
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:

      - name: envoy.http_connection_manager
        config:
          use_remote_address: true 
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              rate_limits:
                - stage: 0
                  actions:
                     - remote_address: {}
              routes:
                - match: { prefix: "/" }
                  route:
                       host_rewrite: www.google.com
                       cluster: service_google

          http_filters:
          - name: envoy.rate_limit
            config:
                stage: 0
                domain: rate_per_ip
          - name: envoy.router

  clusters:
  - name: rate_limit_cluster
    type: STATIC
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8081 }}]

  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }


rate_limit_service:
    grpc_service:
        envoy_grpc:
            cluster_name: rate_limit_cluster
        timeout: 0.25s
```

I intend it to do simple rate limit on ip address and then redirect me to google.com, but it never even tries to access my rate limit service. 
I spent literally hours in docs, so sorry if I miss some newbie thing.
Thanks for any response.
