### ISSUE TITLE
Stream Idle Timer Fires Even When Stream Was Active

### ISSUE THREAD

**Issue by modatwork** [envoyproxy/envoy#34035]
*Description*:

Envoy should not fire stream idle timer when it's active.

*Repro steps*:

1. create a listener with `stream_idle_timeout` set to `60s`
2. a client with a low bandwidth network download a file through Envoy proxy, `curl -v -k --limit-rate 1 https://localhost:7443/2MB.txt -o 2MB.txt`
3. after about 65 seconds, envoy close the connection and output an access log with an `SI` flag in it: `[2024-05-09T03:15:14.949Z] "GET /2MB.txt HTTP/1.1" 200 SI 0 835584 60020 2 "172.16.120.74" "curl/8.6.0" "bc69c5d5-e27e-4809-aac4-420acaae5b47" "localhost:7443" "127.0.0.1:8080"`

*Admin and Stats Output*:

- stats: [stats.log](https://github.com/envoyproxy/envoy/files/15257127/stats.log)
- clusters: [clusters.log](https://github.com/envoyproxy/envoy/files/15257132/clusters.log)
- routes: [routes.log](https://github.com/envoyproxy/envoy/files/15257136/routes.log)
- server info: [server_info.log](https://github.com/envoyproxy/envoy/files/15257140/server_info.log)

*Config*:

```yaml
- name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          use_remote_address: true
          normalize_path: true
          merge_slashes: true
          path_with_escaped_slashes_action: UNESCAPE_AND_REDIRECT
          request_timeout: 1200s
          request_headers_timeout: 65s
          stream_idle_timeout: 60s
          common_http_protocol_options:
            max_stream_duration: 3600s
            idle_timeout: 70s
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536 # 64 KiB
            initial_connection_window_size: 1048576 # 1 MiB
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "debug/logs/access_7443.log"
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: {prefix: "/"}
                route:
                  cluster: service_foo
                  timeout: 3600s
```

*Logs*:

- debug log: [stdout.log](https://github.com/envoyproxy/envoy/files/15257198/stdout.log)
