### ISSUE TITLE
Non-TLS http_health_check on cluster with tls_context

### ISSUE THREAD

**Issue by rene-m-hernandez** [envoyproxy/envoy#3410]
*Description*:
It seems a http_health_check will attempt a TLS connection if the cluster is configured with a tls_context. The ability to allow a non-TLS http_health_check in such a situation would be nice. Apologies if I am simply not reading the documentation close enough or if such an issue exists (I did a quick search for `health` in the open issues.

Configuration (please note my EDS is returning an endpoint definition that uses the health_check_config { port_value: port } option)
```
  clusters:
  - name: upstream
    connect_timeout:
      seconds: 1
    lb_policy: ROUND_ROBIN
    health_checks:
    - timeout:
        seconds: 1
      interval:
        seconds: 5
      interval_jitter:
        nanos: 500000000
      no_traffic_interval:
        seconds: 15
      unhealthy_threshold: 1
      healthy_threshold: 2
      http_health_check:
        path: "/"
        request_headers_to_add: []
    common_lb_config:
      healthy_panic_threshold: 
        value: 0.0
    type: EDS
    eds_cluster_config:
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
          - envoy_grpc:
              cluster_name: xds_cluster
    tls_context:
      sni: some.domain.com
```
Output from envoy:
```
[client] source/common/http/codec_client.cc:25] [C41] connecting
[connection] source/common/network/connection_impl.cc:568] [C41] connecting to x.x.x.x:port
[connection] source/common/network/connection_impl.cc:577] [C41] connection in progress
[connection] source/common/network/connection_impl.cc:322] [C41] writing 78 bytes, end_stream false
[connection] source/common/network/connection_impl.cc:385] [C41] socket event: 2
[connection] source/common/network/connection_impl.cc:453] [C41] write ready
[connection] source/common/network/connection_impl.cc:462] [C41] connected
[connection] source/common/ssl/ssl_socket.cc:110] [C41] handshake error: 2
[connection] source/common/network/connection_impl.cc:385] [C41] socket event: 3
[connection] source/common/network/connection_impl.cc:453] [C41] write ready
[connection] source/common/ssl/ssl_socket.cc:110] [C41] handshake error: 1
[connection] source/common/ssl/ssl_socket.cc:138] [C41] SSL error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
[connection] source/common/network/connection_impl.cc:134] [C41] closing socket: 0
[http] source/common/http/http1/codec_impl.cc:305] [C41] parsing 0 bytes
[http] source/common/http/http1/codec_impl.cc:322] [C41] parsed 0 bytes
[client] source/common/http/codec_client.cc:81] [C41] disconnect. resetting 1 pending requests
[client] source/common/http/codec_client.cc:104] [C41] request reset
[main] source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=1)
[hc] source/common/upstream/health_checker_impl.cc:155] [C41] connection/stream error health_flags=/failed_active_hc
[main] source/common/event/dispatcher_impl.cc:126] item added to deferred deletion list (size=2)
[main] source/common/event/dispatcher_impl.cc:52] clearing deferred deletion list (size=2)
```
