### ISSUE TITLE
EnvoyFilter RateLimit pattern regex not working , need help!

### ISSUE THREAD

**Issue by wmashal** [envoyproxy/envoy#34197]
Hi 

I am trying to configure my Global Rate limit in istio using the EnvoyFilter resource to handle a a dynamic URL requests rate limit, my url contains a dynamic UUID in the path so I tried to use regex_value_rewrite pattern but its not working as expected, I expect to have a request count for each unique UUID,  and not apply the rate limit on any other paths just if I have the UUID Regex

Example:

lets say we have **limit 50 req/minute**, and 2 requests with 2 different UUIDs
 
/cloudautomation/v1/solutions/UUID-1/spfi/notify   called 2 times --- > **count1 is 2 out of 50**
/cloudautomation/v1/solutions/UUID-2/spfi/notify   called 10 times ---> **count2 is 10 out of 50**

**My Configurations**

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ratelimit-envoy-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: 'envoy.filters.network.http_connection_manager'
              subFilter:
                name: 'envoy.filters.http.router'
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.header_to_metadata
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
            request_rules:
            - header: ':path'
              on_header_present:
                # use an arbitary name for the namespace
                # will be used later to extract descriptor value
                metadata_namespace: spfi
                # use an arbitary key for the metadata
                # will be used later to extract descriptor value
                key: uri
                regex_value_rewrite:
                  pattern:
                    # regex matcher
                    google_re2: {}
                    # truncates parameters from path
                    regex: '^\/cloudautomation\/v1\/solutions\/(.+)\/spfi\/notify$'
                  substitution: '\1'
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
              subFilter:
                name: "envoy.filters.http.router"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.ratelimit
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ratelimit.v3.RateLimit
            domain: atom-istio-ratelimit
            failure_mode_deny: false
            timeout: 10s
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: outbound|8081||ratelimit.istio-system.svc.cluster.local
                  authority: ratelimit.istio-system.svc.cluster.local
              transport_api_version: V3

```
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: uca-spfi-ratelimit-actions
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: VIRTUAL_HOST
    match:
      context: GATEWAY
      routeConfiguration:
        vhost:
          name: {{ .Values.uca.ingress.appPrefix }}.ingress.{{ .Values.domain }}:443
          route:
            action: ANY
    patch:
      operation: MERGE
      value:
        rate_limits:
        - actions:
          - metadata:
              descriptor_key: SPFI
              metadata_key:
                key: spfi
                path:
                - key: uri
```

In the rate limit service config I configured

```yaml
   - key: SPFI
     rate_limit:
       unit: MINUTE
       requests_per_unit: 50
```
Please Advice ?
Thanks

**Comment by ravenblackx** [comment]
I think `substitution: '\1'` is telling it to replace the pattern with itself, so making no change. For what you describe it looks like `substitution: ""` would do what you intended?

**Comment by ravenblackx** [comment]
@mattklein123 as ratelimit primary owner.

**Comment by wmashal** [comment]
@mattklein123 can help plz ?

**Comment by wmashal** [comment]
@ravenblackx  u think its a bug ? or no support for such a scenario ?

**Comment by ravenblackx** [comment]
Not really my area, that's why I tried to ping Matt to look. Maybe @wbpcode might know more, as someone touching rate limit related stuff recently?

**Comment by wbpcode** [comment]
so, what is the current behavior? Seems the configuration is fine. It would be better to log the dynamic metadata or check the stats of rate limit server to find what actually happend.

**Comment by wmashal** [comment]
@wbpcode 

lets say we set the limit 50 req/minute, and we have 2 requests with **2 different UUIDs** UUID-1 and UUID-2

### The expected behavior the following ( What I want to achieve)

/cloudautomation/v1/solutions/**UUID-1**/spfi/notify **called 2 times** --- > count1 is 2 out of 50
/cloudautomation/v1/solutions/**UUID-2**/spfi/notify **called 10 times** ---> count2 is 10 out of 50  --> **note the count2 used with the second UUID UUID2**


### The existing behavior is 

/cloudautomation/v1/solutions/**UUID-1**/spfi/notify called 2 times --- > count1 is 2 out of 50
/cloudautomation/v1/solutions/**UUID-2**/spfi/notify called 10 times ---> **count1 is 12 out of 50** --> **note the count1 used again with the second UUID UUID2 its should be a new counter for the new UUID**

**Comment by wmashal** [comment]
@wbpcode can help plz ?

**Comment by wbpcode** [comment]
@wmashal sorry for the delay. But as I said before, you can print the dynamic metadata in the access log to see if the value is set correctly. And you can check the stats of rate limit server to see which key/values are actually received from Envoy. 

Then we can narrow the possible scope of the issue.

**Comment by wmashal** [comment]
I fixed the issue by changing the the following parts from my original configurations

**ratelimit-envoy-filter**

metadata_namespace: spfi ---> **metadata_namespace: envoy.lb**
key: uri ---> **key: uuid**

**uca-spfi-ratelimit-actions**

```yaml
    patch:
      operation: MERGE
      value:
        rate_limits:
        - actions:
          - metadata:
              descriptor_key: uuid
              metadata_key:
                key: envoy.lb
                path:
                - key: uuid
```
