### ISSUE TITLE
Increasing `max_request_headers_kb` in HCM not working properly

### ISSUE THREAD

**Issue by xr** [envoyproxy/envoy#34231]
*Title*: *Increasing `max_request_headers_kb` in HCM not working*

*Description*:
I got `431 Request Header Fields Too Large` from envoy as we are adding some larger request header within wasm filter (size might slight over 60KiB),  by doing some researching, the default value is `60KiB` and we could increase the `max_request_headers_kb ` based on the [doc here](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#extensions-filters-network-http-connection-manager-v3-httpconnectionmanager) but seems like it's not working properly.

here is the partial of the HCM config:
```
  ...
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                generate_request_id: true
                preserve_external_request_id: true
                max_request_headers_kb: 96
...
```

our envoy version: 1.30

i'm sure my envoy config is correct and other fields in the HCM config works properly, only the max_request_headers_kb doesn't have any effect, I have tried to increase `max_request_headers_kb` to even few hundreds or thousands which is enough size, as this field max value has been increased to 8MiB since 1.19, [ref](https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.19/v1.19.0.html)

> http: raise max configurable max_request_headers_kb limit to 8192 KiB (8MiB) from 96 KiB in http connection manager.

But envoy still gives me `431 Request Header Fields Too Large`, this config didn't seem to increase the `max_request_headers_kb` properly.

Also i have also tried to increase  `common_http_protocol_options.max_headers_count` to ensure the 431 is not causing by the headers count overflow, but it doesn't help either as I'm quite sure the problem was causing from one header field was larger than 60KiB (if not set that large request header, everything is fine)

Any ideas would be appreciated, thank yoU!
