### ISSUE TITLE
Missing metrics for resource monitor global_downstream_max_connections

### ISSUE THREAD

**Issue by aerialls** [envoyproxy/envoy#34283]
*Title*: Missing metrics for resource monitor global_downstream_max_connections

*Description*: When the Overload Manager is enabled with the [envoy.resource_monitors.downstream_connections](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/resource_monitors/downstream_connections/v3/downstream_connections.proto) resource monitor, some metrics are missing. Only the `failed_updates` metric is available.

```
overload.envoy.resource_monitors.global_downstream_max_connections.failed_updates: 0
```

The `pressure` and `skipped_updates` are missing as stated in the documentation. Other resource monitors are not impacted. 

```
overload.envoy.resource_monitors.fixed_heap.failed_updates: 0
overload.envoy.resource_monitors.fixed_heap.pressure: 6
overload.envoy.resource_monitors.fixed_heap.skipped_updates: 0
```

```yaml
refresh_interval:
  seconds: 0
  nanos: 250000000
resource_monitors:
  - name: "envoy.resource_monitors.global_downstream_max_connections"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.resource_monitors.downstream_connections.v3.DownstreamConnectionsConfig
      max_active_downstream_connections: 1000
actions:
  - name: "envoy.overload_actions.disable_http_keepalive"
    triggers:
      - name: "envoy.resource_monitors.global_downstream_max_connections"
        threshold:
          value: 0.95
```

Is it intended?
