### ISSUE TITLE
HTTP/2 enforcement causes "upstream connect error" with external forwarding proxy

### ISSUE THREAD

**Issue by firstoc** [envoyproxy/envoy#34326]
**Environment:**
- Envoy version: eda7d32bd54d95008b82f2cc7327d63dbd887df0/1.31.0-dev/Clean/RELEASE/BoringSSL
- Operating System: Ubuntu 22.04

**Issue Description:**
I am encountering an issue with Envoy where enforcing HTTP/2 for upstream connections through an external forwarding proxy leads to a protocol error. The setup is intended to create an HTTP listener that adds some headers and then routes requests through this proxy. When the configuration is set to use HTTP/1.1, it works correctly, but switching to HTTP/2 results in a "502 Bad Gateway" error.

**Steps to Reproduce:**
1. Configure Envoy to use an external forwarding proxy with HTTP/1.1. This setup works as expected:

 `curl -v --proxy http://localhost:10001 http://httpbin.org/get --http2-prior-knowledge`

Response is HTTP/1.1 200 OK.

2. Modify the Envoy configuration to enforce HTTP/2 by setting alpn_protocols: ["h2"]

`curl -v --proxy http://localhost:10001 http://httpbin.org/get --http2-prior-knowledge`

This results in a "502 Bad Gateway" error, and the connection logs show:

upstream connect error or disconnect/reset before headers. reset reason: protocol error

**Expected Behavior:**
I expect Envoy to successfully route HTTP/2 requests through the external forwarding proxy without protocol errors.

**Actual Behavior:**
Enforcing HTTP/2 results in protocol errors and a "502 Bad Gateway" response, indicating an issue with upstream connection handling.

I am testing this behavior using curl with the --http2-prior-knowledge option to explicitly use HTTP/2.
The external proxy supports HTTP/2.

Please let me know if there are any configuration adjustments I can make to resolve this issue or if this might be a bug related to HTTP/2 handling in Envoy.
Config: 
```
static_resources:
  listeners:
  - name: client_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: edge
          http_filters:
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          http2_protocol_options:
            allow_connect: true
          route_config:
            #request_headers_to_add:
             # - header:
                  #key: "myCustomHeader"
                  #value: "its-value-here"
            virtual_hosts:
              - name: direct_response_service
                domains: ["*"]
                routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: itself
                      timeout: 0s
  - name: loopback_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10002
    filter_chains:
      - filters:
        - name: tcp
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
            stat_prefix: tcpproxy
            cluster: external_proxy_cluster
            tunneling_config:
              hostname: httpbin.org:443
  clusters:
    - name: itself
      connect_timeout: 30s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: self_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 0.0.0.0
                  port_value: 10002
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_params:
              tls_minimum_protocol_version: TLSv1_2
              tls_maximum_protocol_version: TLSv1_3
            #alpn_protocols: ["h2"]
    - name: external_proxy_cluster
      connect_timeout: 30s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: proxy_cluster
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 207.XXX.XX.XX
                  port_value: 1027
```
