### ISSUE TITLE
Envoy Filter Only Send one Message per Stream

### ISSUE THREAD

**Issue by thiagomata** [envoyproxy/envoy#34400]
*Title*: *Envoy Filter Only Send one Message Per Stream*

*Description*:
We are using envoy filters 
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
# ...
    patch:
      operation: MERGE
      value:
        typed_per_filter_config:
          envoy.filters.http.ext_proc:
            "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute"
```

That filter calls our GRPC server, which measures some metrics, including the number of messages per stream.
When we load test our GRPC server locally, using GRPCurl, for example, we can see the number of messages in the same stream is around 10k for a 5-second load test. But when we measure the stream size of the actual GRPC calls from the Envoy filter, all are size 2.  Also, the number of EOFs matches the number of calls to the GRPC server. So, there are only two messages in each stream, one of which is an EOF.

It looks like we are not using the best of the streaming capability during these calls, which can reuse the same GRPC request to send multiple messages, creating new streams for each message instead. If we do that properly, we may considerably reduce the latency around network protocols shaking hands.
