### ISSUE TITLE
json log with sort_properties prints decimals for all numbers

### ISSUE THREAD

**Issue by larhauga** [envoyproxy/envoy#34420]
*Title*: *json log with sort_properties prints decimals for all numbers*

*Description*:

The json logs when using FileAccessLog are serialized as floating numbers with decimals rather than integers.
An example is response codes which are logged as "HTTP" `200.0`.
We see this when `json_format_options.sort_properties: true` is set (introduced in https://github.com/envoyproxy/envoy/commit/fc33e5d94f6919f6748e468b75df607bdd667e24).

```json
{"bytes_received":0.0,"bytes_sent":11576.0,"duration":6.0,"method":"GET","response_code":200.0,"upstream_service_time":"6"}...
```

*Repro steps*:
To reproduce, we use istio 1.22 (envoy `b2dd15dc498b84431c063042e7821e179d5a3c41/1.30.2-dev`) with the following configuration. The change in the format is `json_format_options.sort_properties: true`.

```yaml
          - name: envoy.filters.network.http_connection_manager                                                                                                                                                                                                                                                                
            typed_config:                                                                                                                                                                                                                                                                                                      
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager                                                                                                                                                                                                   
              access_log:                                                                                                                                                                                                                                                                                                      
              - name: envoy.access_loggers.file                                                                                                                                                                                                                                                                                
                typed_config:                                                                                                                                                                                                                                                                                                  
                  '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog                                                                                                                                                                                                                           
                  log_format:                                                                                                                                                                                                                                                                                                  
                    json_format:                                                                                                                                                                                                                                                                                               
                      authority: '%REQ(:AUTHORITY)%'                                                                                                                                                                                                                                                                           
                      bytes_received: '%BYTES_RECEIVED%'                                                                                                                                                                                                                                                                       
                      bytes_sent: '%BYTES_SENT%'                                                                                                                                                                                                                                                                               
                      connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'                                                                                                                                                                                                                                       
                      downstream_local_address: '%DOWNSTREAM_LOCAL_ADDRESS%'                                                                                                                                                                                                                                                   
                      downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'                                                                                                                                                                                                                                                 
                      duration: '%DURATION%'                                                                                                                                                                                                                                                                                   
                      method: '%REQ(:METHOD)%'                                                                                                                                                                                                                                                                                 
                      path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'                                                                                                                                                                                                                                                               
                      protocol: '%PROTOCOL%'                                                                                                                                                                                                                                                                                   
                      request_id: '%REQ(X-REQUEST-ID)%'                                                                                                                                                                                                                                                                        
                      requested_server_name: '%REQUESTED_SERVER_NAME%'                                                                                                                                                                                                                                                         
                      response_code: '%RESPONSE_CODE%'                                                                                                                                                                                                                                                                         
                      response_code_details: '%RESPONSE_CODE_DETAILS%'                                                                                                                                                                                                                                                         
                      response_flags: '%RESPONSE_FLAGS%'                                                                                                                                                                                                                                                                       
                      route_name: '%ROUTE_NAME%'                                                                                                                                                                                                                                                                               
                      start_time: '%START_TIME%'                                                                                                                                                                                                                                                                               
                      upstream_cluster: '%UPSTREAM_CLUSTER%'                                                                                                                                                                                                                                                                   
                      upstream_host: '%UPSTREAM_HOST%'                                                                                                                                                                                                                                                                         
                      upstream_local_address: '%UPSTREAM_LOCAL_ADDRESS%'                                                                                                                                                                                                                                                       
                      upstream_service_time: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'                                                                                                                                                                                                                                           
                      upstream_transport_failure_reason: '%UPSTREAM_TRANSPORT_FAILURE_REASON%'                                                                                                                                                                                                                                 
                      user_agent: '%REQ(USER-AGENT)%'                                                                                                                                                                                                                                                                          
                      x_forwarded_for: '%REQ(X-FORWARDED-FOR)%'                                                                                                                                                                                                                                                                
                    json_format_options:                                                                                                                                                                                                                                                                                       
                      sort_properties: true                                                                                                                                                                                                                                                                                    
                  path: /dev/stdout                                                                                                                                                                                                                                                                                            

```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/main/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

```
 "version": "b2dd15dc498b84431c063042e7821e179d5a3c41/1.30.2-dev/Clean/RELEASE/BoringSSL",
  "user_agent_name": "envoy",
  "user_agent_build_version": {
   "version": {
    "major_number": 1,
    "minor_number": 30,
    "patch": 2
   },
   "metadata": {
    "revision.sha": "b2dd15dc498b84431c063042e7821e179d5a3c41",
    "ssl.version": "BoringSSL",
    "build.label": "dev",
    "revision.status": "Clean",
    "build.type": "RELEASE"
   }
  },

```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
