### ISSUE TITLE
What will happen to web socket connections when envoy reload new envoyfilters (hot restart )

### ISSUE THREAD

**Issue by Yufeireal** [envoyproxy/envoy#34498]
Hi team, I have a general question regarding what will happen to the requests when envoy hot load the configs.

We're using istio in our eks cluster, I added an access logging envoyfilter recently.
I've observed an interesting thing:

When I change the envoyfilter configuration, it looks like the upstream service will temporarily get ~"doubled" requests, latency will jump and decrease in 1 minute.

![image](https://github.com/envoyproxy/envoy/assets/106118747/a2f6b29d-0953-442c-9d5f-b804b84f4e21)

So I am wondering what's actually happned under the hood.. Is this specifically related to access logs changes, thanks!

If someone could tell me more about how envoy hot reload this config, would be very helpful, thanks in advance.

Here is the envoyfilter:
```
spec:
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: MERGE
      value:
        name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          access_log:
          - filter:
              and_filter:
                filters:
                - not_health_check_filter: {}
                - or_filter:
                    filters:
                    - status_code_filter:
                        comparison:
                          op: GE
                          value:
                            default_value: 402
                            runtime_key: "null"
                    - runtime_filter:
                        percent_sampled:
                          denominator: HUNDRED
                          numerator: 1
                        runtime_key: "null"
            name: envoy.access_loggers.open_telemetry
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.access_loggers.open_telemetry.v3.OpenTelemetryAccessLogConfig
              body:
                string_value: |-
                  {SOME FORMAT STUFF}
              common_config:
                grpc_service:
                  envoy_grpc:
                    authority: opentelemetry-collector.opentelemetry.svc.cluster.local
                    cluster_name: outbound|4317||opentelemetry-collector.opentelemetry.svc.cluster.local
                log_name: main_gw_http_al
                transport_api_version: V3
              resource_attributes:
                values:
                - key: log_category
                  value:
                    string_value: envoy-access-logs
  workloadSelector:
    labels:
      app: istio-ingressgatewa
```
