### ISSUE TITLE
Support OData endpoint in UriTemplateMatchConfig

### ISSUE THREAD

**Issue by DieBauer** [envoyproxy/envoy#34507]
*Title*: OData style endpoints cannot be configured in UriTemplateMatchConfig

*Description*:
>Describe the desired behavior, what scenario it enables and how it
would be used.

I have a route with a path parameter, `/api/MyFunction('{id}')` this is following the OData specification[0]. 

If I add this to Envoy's path_match_policy

```yaml
"path_match_policy": {
                        "name": "envoy.path.match.uri_template.uri_template_matcher",
                        "typed_config": {
                            "@type": "type.googleapis.com/envoy.extensions.path.match.uri_template.v3.UriTemplateMatchConfig",
                            "path_template": "/api/MyFunction('{id}')"
                        }
                    }
```

it fails with
```
Error adding/updating listener(s) incoming: path_match_policy.path_template /api/MyFunction('{id}') is invalid
```

The desired behavior is that I can match on these endpoints in Envoy.

[optional *Relevant Links*:]
[0](https://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793787)
https://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793769
