### ISSUE TITLE
Support single instance of a Listener that listens both TCP and UDP traffic on the same port

### ISSUE THREAD

**Issue by aculnaig** [envoyproxy/envoy#34627]
*Title*: *Support single instance of a Listener that listens both TCP and UDP traffic on the same port*

*Description*:

I would like to define one Listener only that listens both TCP and UDP traffic on the same port

This is what I came up doing:

```
static_resources:
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9000
      
      listener_filters:
        - name: envoy.filters.listener.original_dst
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.listener.original_dst.v3.OriginalDst
      
      filter_chains:
        - filter_chain_match:
            transport_protocol: raw_buffer # for TCP
          filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: civo_stat_tcp
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                cluster: civo_tcp_cluster
              
        - filter_chain_match:
            transport_protocol: udp # for UDP
          filters:
            - name: envoy.filters.udp_listener.udp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
                cluster: civo_udp_cluster
                stat_prefix: civo_stat_udp
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

  clusters:
    - name: civo_tcp_cluster
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: civo_tcp_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: TCP
                    address: 0.0.0.0
                    port_value: 8081

    - name: civo_udp_cluster
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: civo_udp_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    protocol: UDP
                    address: 0.0.0.0
                    port_value: 8082

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000

```

**Comment by alyssawilk** [comment]
cc @RyanTheOptimist @ggreenway

**Comment by aculnaig** [comment]
This is what I came up with that is working:

```
static_resources:

  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9000
      filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
              cluster: cluster_0
              stat_prefix: stat_prefix_0

    - name: listener_1
      address:
        socket_address:
          protocol: UDP
          address: 0.0.0.0
          port_value: 9000
      listener_filters:
        - name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            cluster: cluster_0
            stat_prefix: stat_prefix_1
  
  clusters:
    - name: cluster_0
      load_assignment:
        cluster_name: cluster_0
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 8081
            - endpoint:
                address:
                  socket_address:
                    address: 0.0.0.0
                    port_value: 8082

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 10000
```

but I am not sure it is syntactically correct/standard.
