### ISSUE TITLE
Didn't find a registered implementation for 'tcp' with type URL: 'envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy'

### ISSUE THREAD

**Issue by ChrWeissDe** [envoyproxy/envoy#34631]
Dear Envoy Community, 

We try to use Envoy in conjunction with Istio. 
Our goal is to route specific traffic via an additional proxy. 

We setup the following Envoy object (see below) in Istio but receive the following error: 

```
_warning	envoy config external/envoy/source/extensions/config_subscription/grpc/delta_subscription_state.cc:269	
delta config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: 
Error adding/updating listener(s) virtualOutbound: 
Didn't find a registered implementation for 'tcp' with type URL: 
'envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy'_
```

Any help / guidance what we do wrong is appreciated - thanks in advance 

Here our config: 

```
metadata:
  name: traffic-routing
  namespace: envoy-config
spec:
  configPatches:
  - applyTo: LISTENER_FILTER
    match:
      listener:
        portNumber: 15001
    patch:
      operation: INSERT_FIRST
      value:
        name: tcp
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: TCPProxy
          cluster: externalProxyCluster
  - applyTo: CLUSTER
    match:
      context: ANY
    patch:
      operation: ADD
      value:
        name: externalProxyCluster
        load_assignment:
          cluster_name: proxyCluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: IP.address
                    port_value: portNumber
```
