### ISSUE TITLE
Force tracing based on header matches

### ISSUE THREAD

**Issue by arkodg** [envoyproxy/envoy#34658]
*Title*: *One line description*

*Description*:
**What**
Enhance the tracing API to force tracing based on a matching request headers.
Here's a suggestion for UX
```
tracing:
  samplingRate: 5
  matches:
    header:
      name: x-user-id
      value: "one"
```

This config would tracing 5% percent of all requests but would force tracing (100% tracing) when the request header `x-user-id` has value `one`

**Why**
Platform teams managing envoy (at the edge/ingress) may not have the ability to add/modify the client to add the `x-envoy-force-trace` header into the request

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
