### ISSUE TITLE
Any way to route specific traffic to a external proxy 

### ISSUE THREAD

**Issue by ChrWeissDe** [envoyproxy/envoy#34651]
Dear Community, 

We have got the requirement to route specific traffic - based on the domain name via an additional external proxy.

Example 
client request 01: https://my-api.internal.com/hello          --> should be routed directly  
client request 02: https://other-api.external.com/hello     --> should be routed via an additional (external) proxy  

Is there any way to achieve this with Envoy?

We already tried to use "extensions.filters.network.tcp_proxy.v3.TcpProxy" - but failed as it seems that it allows only one entry (so one proxy for all TCP Traffic - or not proxy at all)

**Comment by nbaws** [comment]
For this you want two virtual hosts, and two static clusters.
vhost 1 is for my-api
vhost 2 is for other-api
You will reach each vhost depending on the Host/Authority header your client sends. You can test this with curl like follows
`
curl localhost:8099 -H "Host: other-api.internal.com" -v
`

cluster 1 and 2 is effectively statically routed from each vhost.

This is using cleartext http, converting to tls is left as an exercise for the reader :)

Example config is here:

```
static_resources:
  listeners:
  - name: http_connect
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8099
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: "ingress_http"
          route_config:
            name: test
            virtual_hosts:
            - name: my-api
              domains:
              - "my-api.internal.com"
              routes:
              - match:
                  prefix: '/'
                route:
                  cluster: my-api
            - name: other-api
              domains:
              - "other-api.internal.com"
              routes:
              - match:
                  prefix: '/'
                route:
                  cluster: other-api
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: my-api
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: my-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 1.2.3.4
                port_value: 80
  - name: other-api
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: other-api
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 2.3.4.5
                port_value: 80
```
