### ISSUE TITLE
FilterChainMatch doesn't always find match when it should, when multiple criteria are present

### ISSUE THREAD

**Issue by ggreenway** [envoyproxy/envoy#3471]
```
- filter_chain_match:
    server_names: ["*.com"]
  filters: {...}
- filter_chain_match:
    server_names: ["example.com"]
    application_protocols: ["h2"]
  filters: {...}
```

A request comes in for {"example.com", "http/1"}. The documentation suggests that this would match the first chain (for *.com), because that is the most-specific fully-matching chain. I think the current algorithm wouldn't match any chain, because it would find "example.com" as the most specific server_name match, then find that it doesn't match the application_protocol, and stop searching.

We should either clarify the documentation, or not stop searching in this case.
