### ISSUE TITLE
Envoy HTTP Local rate Limit Inconsistent Token available with load

### ISSUE THREAD

**Issue by cam634** [envoyproxy/envoy#34893]
We currently implement an envoy filter using Istio for HTTP Local rate limiting, We had se the rate limit at 100 request per second which I acknowledge is fairly low. Across 1 Gateway pod so we expected to see around ~100 RPS or 6,000rpm allowed. , as we saw our traffic climb up to 5,000 RPS or 300,000rpm. We saw the tokens available go up to around 300RPS or 19,000 rpm. 

With that said some key points I would like to include we are using descriptor paths to set our health checks at a higher point but since we aren't calling there I do not think that should matter. As well for the test we had it in a count mode with the filter not enforced. Auto scaling was also turned off for this load test. CPU at the time was set to 46% 

Looking to see if anyone has any explanation for this behavior. Since it worked perfectly fine up until 2,000 rps 

<img width="1154" alt="image" src="https://github.com/envoyproxy/envoy/assets/105078054/d6b565b1-1f4d-46f3-8458-bf43d0e0984f">

**Comment by mattklein123** [comment]
cc @wbpcode who has been looking at this recently

**Comment by wbpcode** [comment]
could you provide a configuration about your test?

**Comment by cam634** [comment]
```
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.local_ratelimit
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
          value:
            stat_prefix: http_local_rate_limiter
  - applyTo: HTTP_ROUTE
    match:
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        route:
          rate_limits:
          - actions:
            - remote_address: {}
          - actions:
            - header_value_match:
                descriptor_value: healthcheck
                expect_match: false
                headers:
                - name: :path
                  string_match:
                    ignore_case: true
                    prefix: /healthcheck/
        typed_per_filter_config:
          envoy.filters.http.local_ratelimit:
            '@type': type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            always_consume_default_token_bucket: false
            descriptors:
            - entries:
              - key: header_match
                value: service
              token_bucket:
                fill_interval: 1s
                max_tokens: 100
                tokens_per_fill: 100
            enable_x_ratelimit_headers: DRAFT_VERSION_03
            filter_enabled:
              default_value:
                denominator: HUNDRED
                numerator: 100
              runtime_key: http_local_rate_limiter
            filter_enforced:
              default_value:
                denominator: HUNDRED
                numerator: 0
              runtime_key: http_local_rate_limiter
            response_headers_to_add:
            - append: false
              header:
                key: x-local-rate-limit
                value: "true"
            stat_prefix: http_local_rate_limiter
            token_bucket:
              fill_interval: 1s
              max_tokens: 1100
              tokens_per_fill: 1100
  workloadSelector:
    labels:
      app.kubernetes.io/component: istio-ingressgateway
```
