### ISSUE TITLE
Envoy's DNS filter fails to handle DNS messages with an ID equal to 0

### ISSUE THREAD

**Issue by michaelbeaumont** [envoyproxy/envoy#35097]
*Description*:
We've configured the DNS filter and we're seeing

```
Unable to parse query buffer from '127.0.0.1' into a DNS object
```

intermittently. With DEBUG logs enabled we can also see we're hitting

```
    ENVOY_LOG(debug, "No ID in DNS query");
```

[here in the DNS parser](https://github.com/envoyproxy/envoy/blob/a1214c87854071d0cd5de6286af0425cc1ef131f/source/extensions/filters/udp/dns_filter/dns_parser.cc#L220).

As far as we can tell [from RFC 1035 though, an ID of `0` is perfectly valid](https://datatracker.ietf.org/doc/html/rfc1035#section-4.1.1).

*Repro steps*:
We're making the DNS queries using [`lua-resty-dns` which constructs queries](https://github.com/openresty/lua-resty-dns/blob/8bb53516e2933e61c317db740a9b7c2048847c2f/lib/resty/dns/resolver.lua#L873) potentially [with an ID of 0](https://github.com/openresty/lua-resty-dns/blob/8bb53516e2933e61c317db740a9b7c2048847c2f/lib/resty/dns/resolver.lua#L786).

*Admin and Stats Output*:
None to include

*Config*:
Will work on getting this if necessary

*Logs*:
As mentioned above we have

```
Unable to parse query buffer from '127.0.0.1' into a DNS object
No ID in DNS query
```

**Comment by slonka** [comment]
As pointed out by @dndx nginx resolver can also generate ID=0 

https://github.com/nginx/nginx/blob/e734df6664e70f118ca3140bcef6d4f1750fa8fa/src/core/ngx_resolver.c#L3698-L3704

https://github.com/nginx/nginx/blob/e734df6664e70f118ca3140bcef6d4f1750fa8fa/src/core/ngx_config.h#L57

https://man7.org/linux/man-pages/man3/random.3.html

**Comment by jakubdyszkiewicz** [comment]
Just to add more data. It can be reproduced with bind's dig as well.

Steps
1) Run Envoy with the following config
```
static_resources:
  listeners:
  - name: listener_8080
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: '{"msg": "Hello"}'
          http_filters:
          - name: envoy.filters.http.router
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - name: dns_resolver
    address:
      socketAddress:
        address: 0.0.0.0
        portValue: 8053
        protocol: UDP
    enableReusePort: true
    listenerFilters:
    - name: envoy.filters.udp.dns_filter
      typedConfig:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.dns_filter.v3.DnsFilterConfig
        serverConfig:
          inlineDnsTable:
            virtualDomains:
            - answerTtl: 30s
              endpoint:
                addressList:
                  address:
                  - 127.0.0.1
              name: service-1.mesh
        statPrefix: custom_dns
    name: custom:dns
    trafficDirection: INBOUND
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```

2) Run the following script
```
#!/bin/bash

while true
do
    dig @localhost -p 8053 service-1.mesh | grep 'HEADER'
done
```
I run 4 of them in parallel

3) Eventually you can see the problem
```
❯❯❯ cat output output2 output3 output4 | wc -l
  104202

❯❯❯ cat output output2 output3 output4 | grep -v 'NOERROR'
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 0
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 0
```
