### ISSUE TITLE
configdump `include_eds` giving unexpected behavior for  `additional_addresses`

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#35100]
Followup to https://github.com/envoyproxy/envoy/issues/34740.

What we send to envoy:
```
clusterName: outbound|80||echo-v6v4.default.svc.cluster.local
endpoints:
- lbEndpoints:
  - endpoint:
      additionalAddresses:
      - address:
          socketAddress:
            address: fd00:10:244::8
            portValue: 80
      address:
        socketAddress:
          address: 10.244.0.8
          portValue: 80
    healthStatus: HEALTHY
    loadBalancingWeight: 1
    metadata:
      filterMetadata:
        istio:
          workload: echo;default;echo;;Kubernetes
  loadBalancingWeight: 1
  locality: {}
'@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
clusterName: outbound|15010||istiod.istio-system.svc.cluster.local
endpoints:
- lbEndpoints:
  - endpoint:
      additionalAddresses:
      - address:
          socketAddress:
            address: fd00:10:244::e
            portValue: 15010
      address:
        socketAddress:
          address: 10.244.0.14
          portValue: 15010
    healthStatus: HEALTHY
    loadBalancingWeight: 1
    metadata:
      filterMetadata:
        istio:
          workload: istiod;istio-system;istiod;;Kubernetes
  loadBalancingWeight: 1
  locality: {}

```

What configdump shows
```yaml
- endpoint_config:
    '@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
    cluster_name: outbound|80||echo-v6v4.default.svc.cluster.local
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: 10.244.0.8
              port_value: 80
          health_check_config: {}
        health_status: HEALTHY
        load_balancing_weight: 1
        metadata:
          filter_metadata:
            istio:
              workload: echo;default;echo;;Kubernetes
      load_balancing_weight: 1
      locality: {}
    policy:
      overprovisioning_factor: 140
- endpoint_config:
    '@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
    cluster_name: outbound|15010||istiod.istio-system.svc.cluster.local
    endpoints:
    - lb_endpoints:
      - endpoint:
          additional_addresses:
          - address:
              socket_address:
                address: 10.244.0.13
                port_value: 15010
          - address:
              socket_address:
                address: fd00:10:244::d
                port_value: 15010
          address:
            socket_address:
              address: 10.244.0.13
              port_value: 15010
          health_check_config: {}
        health_status: HEALTHY
        load_balancing_weight: 1
        metadata:
          filter_metadata:
            istio:
              workload: istiod;istio-system;istiod;;Kubernetes
      load_balancing_weight: 1
      locality: {}
    policy:
      overprovisioning_factor: 140
```

We see one is missing the endpoint, and one is duplicating them

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.
