### ISSUE TITLE
Dynamic forward proxy with sub_clusters_config get stuck with wait for warmup

### ISSUE THREAD

**Issue by itsLucario** [envoyproxy/envoy#35171]
*Title*: *DynamicForwardProxy with sub_clusters_config get stuck with `Sub cluster warming timeout` after dynamic CDS add/update*

*Description*:
I am trying to use dynamic_forward_proxy with `sub_clusters_config` to get the benefits that it provides. 
Things work fine at start and envoy is able to forward the request to upstream but the moment we receive the CDS and the cluster initialization happens and the DFPClusters gets removed. Once the DFPCluster removed after CDS, all the further requests results in `Sub cluster warming timeout`. 

We initially noticed this with Istio on CDS add/update and tried to reproduce the same on envoy with filesystem-based dynamic config.

*We were able to identify the root cause for this and a potential fix!*
The dynamic_forward_proxy maintains a [`cluster_map_` of its own](https://github.com/envoyproxy/envoy/blob/main/source/extensions/clusters/dynamic_forward_proxy/cluster.h#L199). When CDS trigger happens, DFPClusters aren't part of the CDS and cluster manager removes it, but a stale entry gets left over in the `cluster_map_` of dynamic_forward_proxy cluster. 
When this happens, the further requests dynamic_forward_proxy assumes that the cluster is already present and waits for a warmup and eventually times out as the cluster is already removed ([Ref](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc#L93)). This keeps happening until dynamic_forward_proxy removes it from its map after ttl expire. 

Potential Fix:
We tried a potential fix, When enter the wait-for warmup condition ([Ref](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc#L93)), we check again with cluster manager if the cluster is present. If not, clear the cluster from DFP map and trigger the add subcluster again so the cluster gets added back to cluster manager and DFP map.

If you feel above-mentioned is a bug and not intended behavior, I can try to work on my first contribution to envoy. (Super excited 😄 )

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs

Below are the configuration I'm using to reproduce the issue:
```
# bootstrap.yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
dynamic_resources:
  cds_config:
    path: ./cds.yaml
  lds_config:
    path: ./lds.yaml
node:
  cluster: test-cluster
  id: test-id
```

```
# cds.yaml
resources:
- "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: dynamic_forward_proxy_cluster_http
  lb_policy: CLUSTER_PROVIDED
  cluster_type:
    name: envoy.clusters.dynamic_forward_proxy
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
      sub_clusters_config:
        lb_policy: LEAST_REQUEST
        sub_cluster_ttl: 600s
```
```
# lds.yaml
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_0
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 10000
  filter_chains:
  - filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: ingress_http
        route_config:
          name: local_route
          virtual_hosts:
          - name: local_service
            domains: ["*"]
            routes:
            - match:
                prefix: "/"
              route:
                cluster: dynamic_forward_proxy_cluster_http
        http_filters:
        - name: envoy.filters.http.dynamic_forward_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
            sub_cluster_config:
              cluster_init_timeout: 5s
        - name: envoy.filters.http.router
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
- Start envoy with above config
`envoy -c bootstrap.yaml -l debug`
- Send some request to httpbin.org 
`curl -vL -H 'Host: httpbin.org' http://localhost:10000/status/201`
- Check envoy clusters to see if DFPClusters are present
![image](https://github.com/user-attachments/assets/28749d4f-ab9d-4135-960d-297330de416d)
- Do some change on cds.yaml to trigger cds add/updates 
`vi cds.yaml` make changes and save
- Once cds update triggers, check envoy clusters again and we'll see the DFP clusters are removed
![image](https://github.com/user-attachments/assets/75e68beb-2591-4fa7-a33a-66cc32fc3069)
- Send a request to httpbin.org again and we'll see `Sub cluster warming timeout`
`curl -vL -H 'Host: httpbin.org' http://localhost:10000/status/201`

*Config*:
>Include the config used to configure Envoy.
Tried with below versions and the bug exists
```
346cc3385269016f7c36ad15a23a7b382348f7af/1.28.6-dev/Modified/RELEASE/BoringSSL
10e1e425fd84cc2cde985179655da08f68c9cb30/1.29.3/Distribution/RELEASE/BoringSSL
```

*Logs*:
>Include the access logs and the Envoy logs.
[accesslogs.log](https://github.com/user-attachments/files/16194407/accesslogs.log)
