### ISSUE TITLE
Upgrade to Websocket doesn't ignore disabled 'typed_per_filter_config' for this route

### ISSUE THREAD

**Issue by DvoryankinEvgeny** [envoyproxy/envoy#35191]
*Title*: *Upgrade to Websocket doesn't ignore disabled 'typed_per_filter_config' for this route*

*Description*:
We have a configuration where we have two http filters: basic_auth and router. We also have a set of routes:
- `/`: all request to the root must be authorized through basic auth
- /`disable-basic-auth`: for this route we use typed_per_filter_config to disable basic auth filter

This configuration works as expected:
```
curl http://localhost:8080/ 
User authentication failed. Missing username and password.%
```
Request to the root without credentials rejected
```
curl -u user:password http://localhost:8080
OK%
```
Request to the root with correct pair of username and password succeeded.(OK is direct_response from envoy)
```
curl http://localhost:8080/disable-basic-auth
OK%
```
Request without credentials to the endpoint with disabled basic authorization also works fine.

By analogy with those endpoints we have two endpoints for WebSocket connections with upgrade_configs and upgrade_type equal to websocket:
- `/ws`: endpoint with configured upgrade_configs 
- `/ws-disable-basic-auth`: same upgrade_config but with typed_per_filter_config to disable basic auth filter

Request to the first Websocket endpoint finishes with 401 Unauthorized as expected because we didn't disabled basic auth for this endpoint.
```
websocat ws://localhost:8080/ws
websocat: WebSocketError: WebSocketError: Received unexpected status code (401 Unauthorized)
```
Request to /ws-disable-basic-auth is expected to be successfully passed to the upstream, but unfortunately it is not.
```
websocat ws://localhost:8080/ws-disable-basic-auth
websocat: WebSocketError: WebSocketError: Received unexpected status code (401 Unauthorized)
```

*Repro steps*:

1. Save config from Config section into envoy.yaml file
2. Create docker-compose.yaml file with following content:
```
services:
  websocat_server:
    image: ghcr.io/vi/websocat
    command: [ "-s", "0.0.0.0:8082" ]
    ports:
      - 8082:8082
    networks:
      my_network:
        ipv4_address: 172.20.0.2

  envoy:
    image: envoyproxy/envoy:v1.30.4
    command:
      [
        "envoy",
        "-l",
        "trace",
        "-c",
        "/etc/envoy/envoy.yaml"
      ]
    volumes:
      - .envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - 8080:8080
      - 9902:9902
    depends_on:
      - websocat_server
    networks:
      my_network:
        ipv4_address: 172.20.0.3

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16

```
3. Run `docker-compose up -d`
4. Run locally `websocat ws://localhost:8080/ws-disable-basic-auth` or curl equivalent `curl -v -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: bKAazDmMg16GANGcKoHGFg==" -H "Connection: Upgrade" -H "Upgrade: websocket" http://localhost:8080/ws-disable-basic-auth`

**Expected result:** basic_auth filter is disabled for websocket calls to `/ws-disable-basic-auth` endpoint
**Actual behaviour:** websocket calls to `/ws-disable-basic-auth` endpoint require basic auth

*Admin and Stats Output*:
[server_info.json](https://github.com/user-attachments/files/16237122/server_info.json)
[cluster.log](https://github.com/user-attachments/files/16237123/cluster.log)
[stats.log](https://github.com/user-attachments/files/16237124/stats.log)

*Config*:
```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: typed-per-filter-config-for-ws
          route_config:
            name: typed-per-filter-config-for-ws
            virtual_hosts:
            - name: app-ws
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/disable-basic-auth"
                direct_response:
                  status: 200
                  body: 
                    inline_string: "OK"
                typed_per_filter_config:
                  envoy.filters.http.basic_auth:
                    "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                    disabled: true
              - match:
                  prefix: "/ws-disable-basic-auth"
                route: 
                  cluster: service_ws
                  upgrade_configs:
                  - upgrade_type: websocket
                typed_per_filter_config:
                  envoy.filters.http.basic_auth:
                    "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                    disabled: true
              - match:
                  prefix: "/ws"
                route: 
                  cluster: service_ws
                  upgrade_configs:
                  - upgrade_type: websocket
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body: 
                    inline_string: "OK"
          http_filters:
            - name: envoy.filters.http.basic_auth
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.basic_auth.v3.BasicAuth
                users:
                  inline_string: |-
                    user:{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=
            - name: envoy.filters.http.router
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: service_ws
    type: STATIC
    load_assignment:
      cluster_name: service_ws
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.20.0.2
                port_value: 8082
```

*Logs*:
I attached two logs files:
- [basic-auth-bug.log](https://github.com/user-attachments/files/16237048/basic-auth-bug.log) contains logs for the problematic case when basic_auth filter is presented in the configuration
- [no-basic-auth.log](https://github.com/user-attachments/files/16237049/no-basic-auth.log) contains logs for case when there is no basic_auth filter in the configuration and request is passed to the upstream

**Comment by KBaichoo** [comment]
Thank you for the reproduction @DvoryankinEvgeny . ISTM like a bug, possibly here:
https://github.com/envoyproxy/envoy/blob/f79b881883e862bc0f7dc7f09d3bc811fb0944f6/source/common/http/filter_manager.cc#L1571

Where we create the upgraded filter chain and not setting the route info. 

I wonder if you flip the filter to be default off but enabled for the routes if that would be a hacky workaround.

**Comment by DvoryankinEvgeny** [comment]
> Thank you for the reproduction @DvoryankinEvgeny . ISTM like a bug, possibly here:
> 
> https://github.com/envoyproxy/envoy/blob/f79b881883e862bc0f7dc7f09d3bc811fb0944f6/source/common/http/filter_manager.cc#L1571
> 
> Where we create the upgraded filter chain and not setting the route info.
> 
> I wonder if you flip the filter to be default off but enabled for the routes if that would be a hacky workaround.

Hello Kevin,
Thank you for the response.
I am quite novice with the envoy, so I am struggling with making basic_auth disabled by default. If I add `disabled: true` like this:
```yaml
http_filters:
  - name: envoy.filters.http.basic_auth
    disabled: true
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.basic_auth.v3.BasicAuth
      users:
        inline_string: |-
          user:{SHA}W6ph5Mm5Pz8GgiULbPgzG37mj9g=
```
then envoy start fails with error
_Empty route/virtual host per filter configuration for envoy.filters.http.basic_auth filter_
Could you please help with configuration?
