### ISSUE TITLE
unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy

### ISSUE THREAD

**Issue by gyancloud** [envoyproxy/envoy#35279]
*Title*: *unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy*

*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.
The Envoy proxy pod should start, with a cors filter that filters the traffic corresponding to the set configuration
Instead the envoy proxy cannot parse the JSON object due a unrecognizable type.

Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy for type Any)

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

We deploy the envoy proxy as a pod on our AKS cluster

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)
Unable to do so seeing as the envoy proxy pod is in a CrashLoopBackOff

*Config*:
>Include the config used to configure Envoy.
`#https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: redirect_route
            virtual_hosts:
            - name: backend
              domains:
              - "[REDACTED]"
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                aadb2c:
                  issuer: https://[REDACTED]/[REDACTED]/v2.0/
                  audiences:
                  - [REDACTED]
                  remote_jwks:
                    http_uri:
                      uri: https://[REDACTED]/discovery/v2.0/keys
                      cluster: jwtcluster
                      timeout: 5s
                    cache_duration:
                      seconds: 300
                  forward: true
                  forward_payload_header: x-jwt-payload
              rules:
              - match:
                  prefix: /health
              - match:
                  prefix: /
                requires:
                  provider_name: aadb2c
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "[REDACTED]"
              typed_per_filter_config:
                envoy.filters.http.cors:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                  allow_origin_string_match:
                    - safe_regex:
                        google_re2: {}
                        regex: ".*"
                  allow_methods:  GET, POST, PUT, DELETE, PATCH, OPTIONS
                  allow_headers: Origin, X-Requested-With, Content, Accept, Content-Type, Authorization,[REDACTED]
                  allow_credentials: true
                  max_age: "1728000"
                  forward_not_matching_preflights: false
                  allow_private_network_access: true
              routes:
              - match:
                  prefix: "/pd-test/"
                route:
                  prefix_rewrite: "/"
                  cluster: pd-test
                request_headers_to_add:
                - header:
                    key: dapr-app-id
                    value: pd-test
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: {filename: [REDACTED]}
              private_key: {filename: [REDACTED]}
            validation_context:
              trusted_ca:
                filename: /etc/ssl/certs/ca-certificates.crt
  clusters:
  - name: pd-test
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: pd-test
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: pd-test-service
                port_value: 80
  - name: jwtcluster
    connect_timeout: 100s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: jwtcluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: [REDACTED]
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

The following v2 api config does work

```#https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: redirect_route
            virtual_hosts:
            - name: backend
              domains:
              - "[REDACTED]"
              routes:
              - match:
                  prefix: "/"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  - name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.cors
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
          - name: envoy.filters.http.jwt_authn
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
              providers:
                aadb2c:
                  issuer: https://[REDACTED]/[REDACTED]/v2.0/
                  audiences:
                  - [REDACTED]
                  remote_jwks:
                    http_uri:
                      uri: https://[REDACTED]/discovery/v2.0/keys
                      cluster: jwtcluster
                      timeout: 5s
                    cache_duration:
                      seconds: 300
                  forward: true
                  forward_payload_header: x-jwt-payload
              rules:
              - match:
                  prefix: /health
              - match:
                  prefix: /
                requires:
                  provider_name: aadb2c
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "[REDACTED]"
              cors:
                allow_origin_string_match:
                - prefix: "*"
                allow_methods:  GET, POST, PUT, DELETE, PATCH, OPTIONS
                allow_headers: Origin, X-Requested-With, Content, Accept, Content-Type, Authorization, userid, houseid
                allow_credentials: true
              routes:
              - match:
                  prefix: "/pd-test/"
                route:
                  prefix_rewrite: "/"
                  cluster: pd-test
                request_headers_to_add:
                - header:
                    key: dapr-app-id
                    value: pd-test
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: {filename: [REDACTED]}
              private_key: {filename: [REDACTED]}
            validation_context:
              trusted_ca:
                filename: /etc/ssl/certs/ca-certificates.crt
  clusters:
  - name: pd-test
    connect_timeout: 1s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: pd-test
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: pd-test-service
                port_value: 80
  - name: jwtcluster
    connect_timeout: 100s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: jwtcluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: [REDACTED]
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

```
*Logs*:
>Include the access logs and the Envoy logs.

Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].typed_per_filter_config[0].value): invalid value Invalid type URL, unknown type: envoy.extensions.filters.http.cors.v3.CorsPolicy for type Any)
