### ISSUE TITLE
How to add a fallback http virtual host

### ISSUE THREAD

**Issue by imlk0** [envoyproxy/envoy#35297]
*Title*: *How to add a fallback http virtual host*

*Description*:

I'm writing a listener that is a [dynamic forward proxy](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/dynamic_forward_proxy_filter) (using the `envoy.filters.http.dynamic_forward_proxy` http filter) that will distribute requests based on the target domain name to two different clusters.

The basic requirement is that I want to dispatch requests sent to `*.examples.com` to `cluster1` and then dispatch the remaining (other domains) requests to `cluster2`.

So I wrote something like this:

```yaml
static_resources:

  listeners:
  - name: ingress0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 41000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_protocol_options:
            accept_http_10: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*.examples.com"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: cluster1
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
              - match:
                  prefix: "/"
                route:
                  cluster: cluster1
            - name: direct # Fallback route
              domains:
                - "*"
              routes:
              - match:
                  connect_matcher:
                    {}
                route:
                  cluster: cluster2
                  upgrade_configs:
                  - upgrade_type: CONNECT
                    connect_config:
                      {}
              - match:
                  prefix: "/"
                route:
                  cluster: cluster2
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              suppress_envoy_headers: true
          upgrade_configs:
          - upgrade_type: CONNECT
```

However it complains:
```
Only a single wildcard domain is permitted in route local_route
```

I have searched for info on this but no one asked how to set up a fallback virtual host. Does anyone have any suggestions for this?
