### ISSUE TITLE
 503 UC upstream_reset_before_response_started{connection_termination} and Invalid HTTP header field errors

### ISSUE THREAD

**Issue by sahityacodes** [envoyproxy/envoy#35296]
I'm occasionally seeing 503 UC upstream_reset_before_response_started{connection_termination} errors in my service mesh ingress gateway. Around the same time, I'm also seeing Invalid HTTP header field errors in an upstream service (API Gateway). I believe this occurs when trying to establish a WebSocket connection. All pods are up and running.
Interestingly, after refreshing the browser several times, the connection often works fine again. The issue seems to disappear after applying an EnvoyFilter, or changing the port names in the service definition from http2 to http.However, I'm troubled by the intermittent nature of the problem. If this was strictly an HTTP/2 issue, I would expect it to occur consistently.

The EnvoyFilter that seems to resolve the issue: 

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: sef-http2-websockets
spec:
  workloadSelector:
    labels:
      app: api-gateway
  configPatches:
    - applyTo: NETWORK_FILTER
      match:
        context: SIDECAR_INBOUND
        proxy:
          proxyVersion: '^1\.*.*'
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
      patch:
        operation: MERGE
        value:
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            http2_protocol_options:
              allow_connect: true
```

Here's the service configurations. 
Before changing the ports:
api-gateway      ClusterIP     x.x.x.x                    http2-proxy:8080►0 http-pm-tls:8999►0 http2-forward:8888►0
After changing the ports
api-gateway      ClusterIP     x.x.x.x                    http-proxy:8080►0 http-pm-tls:8999►0 http-forward:8888►0

Logs in my upstream envoy:
envoy http2\t[Tags: \"ConnectionId\":\"29367\"] invalid http2: **Invalid HTTP header field was received: frame type: 1, stream: 3, name: [:protocol], value: [websocket]**
http2\t[Tags: \"ConnectionId\":\"29367\"] invalid frame: Invalid HTTP header field was received on stream 3
http\t[Tags: \"ConnectionId\":\"29367\"] dispatch error: The user callback function failed

Around the same time in ingress gateway - down stream service:
"GET [priv100]/log/viewer/[/priv100] **HTTP/1.1\" 503 UC upstream_reset_before_response_started{connection_termination}** - \"-\" 0 95 1002 - \"[priv8]x.x.x.x[/priv8]\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36\" \"17bfbac0-0424-494a-9be6-bf51a32cb346\" \"xyz.com\" \"[priv8]x.x.x.x[/priv8]:8080\" outbound|8080||api-gateway.deploy.svc.cluster.local [priv8]x.x.x.x[/priv8]:49186 [priv8]x.x.x.x[/priv8]:8443 [priv8]x.x.x.x[/priv8]:53300 xyz.com
"GET [priv100]/log/viewer/[/priv100] **HTTP/2\" **503 UC upstream_reset_before_response_started{connection_termination**}** - \"-\" 0 95 1420 - \"[priv8]x.x.x.x[/priv8]\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36\" \"d1088bff-d57b-4d4b-98d5-b287bc79916b\" \"xyz.com\" \"[priv8]x.x.x.x[/priv8]:8080\" outbound|8080||api-gateway.deploy.svc.cluster.local [priv8]x.x.x.x[/priv8]:49186 [priv8]x.x.x.x[/priv8]:8443 [priv8]x.x.x.x[/priv8]:2009 xyz.com
