### ISSUE TITLE
How to balance the number of quic connections on each thread

### ISSUE THREAD

**Issue by hyasysu** [envoyproxy/envoy#35396]
*Title*: *How to balance the number of quic connections on each thread*

*Description*:
I have a QUIC Listener as follows:
```
  - name: listener_5  # listen tcp connection from high_domian get response
    address:
      socket_address:
        protocol: UDP
        address: ip
        port_value: port
    udp_listener_config:
      quic_options:
        quic_protocol_options:
          initial_stream_window_size: 65536
          max_concurrent_streams: 8192
      downstream_socket_config:
        prefer_gro: true  # GRO（Generic Receive Offload）
      udp_packet_packet_writer_config:
        name: envoy.udp_packet_writer.udp_gso_batch_writer
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.udp_packet_writer.v3.UdpGsoBatchWriterFactory
    per_connection_buffer_limit_bytes: 10000000
```
I found that the number of quic connections per thread was not evenly distributed. Is there a mechanism to distribute it as evenly as possible on each worker thread?
