### ISSUE TITLE
Bad characters in header metadata

### ISSUE THREAD

**Issue by maxlein** [envoyproxy/envoy#35403]
*Title*:  
Bad characters in header metadata

*Description*:
We pass metadata from the `JwtAuthentication` filter to the backend grpc server to see which user called the request.  
This is working but the data has bad characters or additional characters included:  

```
Metadata: accept -> application/json��6���
Metadata: origin//localhost�6��� -> https://localhost�6���
Metadata: sec-ch-ua-platform��w -> "Linux"
Metadata: x-envoy-original-method -> POSTw
Metadata: x-forwarded-proto���w -> https
Metadata: jwt-usernamew -> ibn�w
```

*Repro steps*:

This is the relevant envoy filter config:

```
http_filters:
                - name: envoy.filters.http.JwtAuthentication
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                    providers:
                      # Each JWT authentication provider has a name to be used in routing rules.
                      provider_keycloak:
                        # The name of the entity that is providing the JWT.
                        issuer: https://$KC_ISSUER_1/keycloak/auth/realms/test
                        # Obtain a JSON Web Key Set from a remote server for JWT validation.
                        claim_to_headers:
                          - header_name: "jwt-email"
                            claim_name: "email"
                          - header_name: "jwt-username"
                            claim_name: "preferred_username"
                        remote_jwks:
                          http_uri:
                            uri: https://$KC_ISSUER_1/keycloak/auth/realms/test/protocol/openid-connect/certs
                            cluster: keycloak
                            timeout: 1s
                          cache_duration:
                            seconds: 300
                        payload_in_metadata: "payload"
                      provider_1:
                        # The name of the entity that is providing the JWT.
                        issuer: https://$KC_ISSUER_2/keycloak/auth/realms/test
                        # Obtain a JSON Web Key Set from a remove server for JWT validation.
                        claim_to_headers:
                          - header_name: "jwt-email"
                            claim_name: "email"
                          - header_name: "jwt-username"
                            claim_name: "preferred_username"
                        remote_jwks:
                          http_uri:
                            uri: https://$KC_ISSUER_2/keycloak/auth/realms/test/protocol/openid-connect/certs
                            cluster: keycloak
                            timeout: 1s
                          cache_duration:
                            seconds: 300
                        payload_in_metadata: "payload"
                      provider_2:
                        # The name of the entity that is providing the JWT.
                        issuer: https://$KC_ISSUER_3/keycloak/auth/realms/test
                        # Obtain a JSON Web Key Set from a remote server for JWT validation.
                        claim_to_headers:
                          - header_name: "jwt-email"
                            claim_name: "email"
                          - header_name: "jwt-username"
                            claim_name: "preferred_username"
                        remote_jwks:
                          http_uri:
                            uri: https://$KC_ISSUER_3/keycloak/auth/realms/test/protocol/openid-connect/certs
                            cluster: keycloak
                            timeout: 1s
                          cache_duration:
                            seconds: 300
                        payload_in_metadata: "payload"
```
*Logs*:

The username in the logs itself looks correct:

```
[source/extensions/filters/http/jwt_authn/authenticator.cc:191] provider_keycloak: Verifying JWT token of issuer https://localhost/keycloak/auth/realms/test
[2024-07-24 07:29:31.515][74][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:324] --------claim : preferred_username with value : ibn is added to the header : jwt-username -----------
[2024-07-24 07:29:31.515][74][debug][jwt] [source/extensions/filters/http/jwt_authn/authenticator.cc:374] provider_keycloak: JWT token verification completed with: OK
[2024-07-24 07:29:31.515][74][debug][jwt] [source/extensions/filters/http/jwt_authn/filter.cc:109] Jwt authentication completed with: OK
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.
