### ISSUE TITLE
jwt: Reject requests with HTTP headers present in claim to headers

### ISSUE THREAD

**Issue by cainelli** [envoyproxy/envoy#35553]
*Title*: Reject requests with HTTP headers present in claim to headers

*Description*: I would like to optionally block requests that contain HTTP headers which are also present in the claim-to-header JWT configuration. This ensures that headers used to carry JWT claims cannot be tampered with by downstream clients.  My current workaround is to remove these headers with HeaderMutation before JWT filter.

Note that the filter overrides the header value if present but if the rule is optional (contain `allow_missing: {}`) then it will also allow the header to be forwarded.

Proposed:

Implement a new [JwtRequirement](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto#envoy-v3-api-msg-extensions-filters-http-jwt-authn-v3-jwtrequirement) option to fail requests containing headers specified in the claim-to-header configuration. When this requirement is enabled, incoming request with a header that matches a claim-to-header mapping should be rejected with an appropriate HTTP error code.

```yaml
...
http_filters:
  - name: envoy.extensions.filters.http.jwt_authn
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
      providers:
        firebase:
          claim_to_headers:
          - claim_name: user_id
            header_name: x-firebase-uid
          - claim_name: firebase.sign_in_provider
            header_name: x-firebase-provider
      rules:
      - match:
          prefix: "/"
        requires:
          requires_all:
            requirements:
              - provider_name: firebase
              - strict_claim_to_headers: {} # block requests with matching headers.
...
```
