### ISSUE TITLE
TlsInspector filter chain

### ISSUE THREAD

**Issue by a-b-v** [envoyproxy/envoy#35656]
Hi,

I have several HTTPS domain names, each covered by a wildcard TLS certificate (*.domain.com). However, different domains require different settings for HttpConnectionManager, such as upgrade_configs, server_header_transformation, stat_prefix, idle_timeout, etc. I attempted to add multiple HttpConnectionManager filters to the TlsInspector filter chains, but Envoy throws the following error: "Filesystem config update rejected: Error adding/updating listener(s) https: Error: terminal filter named https-a_domain_com of type envoy.filters.network.http_connection_manager must be the last filter in a network filter chain."

How can I resolve this issue?

My Envoy config:

```
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: https
  address:
    socket_address:
      address: x.x.x.x
      port_value: 443
      protocol: TCP
  per_connection_buffer_limit_bytes: 10000000
  listener_filters:
  - name: "envoy.filters.listener.tls_inspector"
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
  filter_chains:
    filter_chain_match:
      server_names:
      - "*.example.com"
      - "b.example.com"
      - "c.example.com"
    filters:
    - name: https-*_example_com
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: x_x_x_x-443-*_example_com
        upgrade_configs:
          - upgrade_type: websocket
        route_config:
          name: x_x_x_x-443-*_example_com
          virtual_hosts:
          - name: '*_example_com-_'
          ...
    - name: https-a_example_com
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
        stat_prefix: x_x_x_x-443-a_example_com
        upgrade_configs:
          - upgrade_type: websocket
          - upgrade_type: spdy/3.1
        route_config:
          name: x_x_x_x-443-a_example_com
          virtual_hosts:
          - name:  'a_example_com-_'
         ...
```
