### ISSUE TITLE
tracing: Health check filter only prevents sampling of root span

### ISSUE THREAD

**Issue by objectiser** [envoyproxy/envoy#3569]
*Description*:

When the health check filter is used, any invocation that matches the health check path causes the root span to not be sampled, but the sampled flag is not be propagated to subsequent services. The subsequent services (or child spans) should also not be sampled.

*Repro steps*:

* Change to the `examples/jaeger-tracing` folder
* Edit the `front-envoy-jaeger.yaml` to update the `http_filter` to be:
```
          http_filters:
          - name: envoy.health_check
            config:
              endpoint: "/trace/1"
              pass_through_mode: true
          - name: envoy.router
            config:
               start_child_span: true
```
* Start the example using `docker-compose up --build -d`
* Send a request using `curl -v localhost:8000/trace/1`
* Access the Jaeger UI at endpoint `http://localhost:16686`
You should see a single trace, which when selected will show something like:
![envoy-hc-traced](https://user-images.githubusercontent.com/164562/41096269-013c5a04-6a4c-11e8-9bda-d37b9d9afc17.png)

The root span has not been reported due to the classification as a health check, but the sampled status has not been passed to the child span created in the proxy, or on to the subsequent `service1`, etc.

The same applies if the `start_child_span` is false, the spans for `service1` and `service2` are created - this time with `service1` as the root span - so indicates that the root span in the ingress is being created but not reported, but the sampled flag is not being propagated to the child span or subsequent services.

Also the other strange thing is that if the `X-B3-Sampled` header is supplied (whether with 0 or 1 value), it does not cause a trace to be created.
