### ISSUE TITLE
How to use bypass_overload_manager in static_resources config

### ISSUE THREAD

**Issue by nev888** [envoyproxy/envoy#35706]
When trying to use bypass_overload_manager  envoy crashes. I want bypass overload manager for the K8S probes.

Logs:
`{"timestamp": "2024-08-14T11:12:01.627+00:00", "severity": "critical", "extra_data": {"lineNumber": 412, "file": "external/envoy/source/server/server.cc", "thread-id": "234-234"}, "message": "error initializing config ' overload_manager: {refresh_interval: {seconds: 0, nanos: 200000000}, resource_monitors: [{name: envoy.resource_monitors.fixed_heap, typed_config: {\"@type\": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig, max_heap_size_bytes: 6442450944}}, {name: envoy.resource_monitors.cpu, typed_config: {\"@type\": type.googleapis.com/envoy.extensions.resource_monitors.injected_resource.v3.InjectedResourceConfig, filename: notUsed}}] , actions: [{name: raise_alarm_cpu, triggers: [{name: envoy.resource_monitors.cpu, scaled: {scaling_threshold: 0.9, saturation_threshold: 0.98}}]}, {name: raise_alarm_memory, triggers: [{name: envoy.resource_monitors.fixed_heap, scaled: {scaling_threshold: 0.9, saturation_threshold: 0.98}}]}, {name: envoy.overload_actions.shrink_heap, triggers: [{name: envoy.resource_monitors.fixed_heap, threshold: {value: 0.9}}]}]} /tmp/envoy_config.yaml': Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT: invalid JSON in envoy.config.bootstrap.v3.Bootstrap   @   static_resources.listeners[0].filter_chains[0].filters[0].typed_config.<any>.route_config.virtual_hosts[0].routes[0].route:  message  envoy.config.route.v3.RouteAction, near 1:2406 (offset 2405): no such  field: 'bypass_overload_manager') has unknown fields"}
{"timestamp": "2024-08-14T11:12:01.627+00:00", "severity": "info", "extra_data": {"lineNumber": 1038, "file": "external/envoy/source/server/server.cc", "thread-id": "234-234"}, "message": "exiting"}
{"timestamp": "2024-08-14T11:12:01.000+00:00", "severity": "debug", "message": "Protobuf message (type envoy.config.bootstrap.v3.Bootstrap reason INVALID_ARGUMENT: invalid JSON in envoy.config.bootstrap.v3.Bootstrap   @   static_resources.listeners[0].filter_chains[0].filters[0].typed_config.<any>.route_config.virtual_hosts[0].routes[0].route:  message  envoy.config.route.v3.RouteAction, near 1:2406 (offset 2405): no such  field: 'bypass_overload_manager') has unknown fields"}`

Envoy: v1.31.0

Partial config:
```
   static_resources:
      listeners:
      - name: health_probe_listener
        address:
          socket_address:
            address: localhost
            resolver_name: resolver
            port_value: 34522
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              stat_prefix: readiness_check
              route_config:
                name: readiness_check_route_config
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/ready"
                    route:
                      cluster: admin_cluster
                      bypass_overload_manager: true
              http_filters:
              - name: adc.readinessCheck
                typed_config:
                  "@type": type.googleapis.com/sample.Decoder
                  cluster: admin_cluster
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
        metadata:
          filter_metadata:
            overload_protection:
              enabled: true
```
