### ISSUE TITLE
No recorded value for upstream_rq_time

### ISSUE THREAD

**Issue by Bfarkiani** [envoyproxy/envoy#35724]
*Title*: *No recorded value for downstream_rq_time and upstream_rq_time*

*Description*:
I have the following envoy configuration. 

```
stats_config:
  use_all_default_tags: true
stats_flush_interval: 5s
  
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9001
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: foo
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: cluster_0
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          proxy_host: proxy.host.com
          target_host: target.host.com
          default_target_port: 443
          retry_options:
            max_connect_attempts: 2
          buffer_options:
            max_buffered_datagrams: 1024
            max_buffered_bytes: 16384

  - name: listener_HTTP
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 12000
    filter_chains:
      - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: listener_HTTP
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog                
              route_config:              
                name: remote_route
                virtual_hosts:
                  - name: connect
                    domains: ["*"]
                    routes:                      
                      - match:
                          connect_matcher: {}
                        route:
                          timeout: 0s
                          idle_timeout: 0s
                          max_stream_duration:
                            max_stream_duration: 0s

                          cluster: cluster_1
                      - match:
                          prefix: "/"                          
                        route:
                          timeout: 0s
                          idle_timeout: 0s
                          max_stream_duration:
                            max_stream_duration: 0s
                          cluster: cluster_1

              http_filters:
                - name: envoy.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              http2_protocol_options:
                allow_connect: true
              upgrade_configs:
              - upgrade_type: CONNECT-UDP                      
       


              
  clusters:
  - name: cluster_0
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_0
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 12000  
  - name: cluster_1
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: remoteServer
                port_value: 10000
```
          
So traffic goes through a UDP listener and then it redirects it to the local HTTP listener listener_HTTP. It then will be routed to a remote server. I am curious about latency to remoteServer cluster so I am looking for upstream_rq_time. I have the following list of reported statistics through admin page. 

```
cluster.cluster_0.upstream_cx_connect_ms: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,0) P99.5(nan,0) P99.9(nan,0) P100(nan,0)
cluster.cluster_1.upstream_cx_connect_ms: P0(nan,130) P25(nan,132.5) P50(nan,135) P75(nan,137.5) P90(nan,139) P95(nan,139.5) P99(nan,139.9) P99.5(nan,139.95) P99.9(nan,139.99) P100(nan,140)
http.admin.downstream_cx_length_ms: P0(nan,33) P25(nan,33.75) P50(nan,125000) P75(nan,262500) P90(nan,267000) P95(nan,268500) P99(nan,269700) P99.5(nan,269850) P99.9(nan,269970) P100(nan,270000)
http.admin.downstream_rq_time: P0(nan,0) P25(nan,0) P50(nan,0) P75(nan,0) P90(nan,0) P95(nan,0) P99(nan,1.0877999999999997) P99.5(nan,2.0694999999999992) P99.9(nan,3.0738999999999974) P100(nan,3.1)
listener.0.0.0.0_12000.connections_accepted_per_socket_event: P0(nan,1) P25(nan,1.025) P50(nan,1.05) P75(nan,1.075) P90(nan,1.09) P95(nan,1.095) P99(nan,1.099) P99.5(nan,1.0995) P99.9(nan,1.0999) P100(nan,1.1)
listener.admin.connections_accepted_per_socket_event: P0(nan,1) P25(nan,1.025) P50(nan,1.05) P75(nan,1.075) P90(nan,1.09) P95(nan,1.095) P99(nan,1.099) P99.5(nan,1.0995) P99.9(nan,1.0999) P100(nan,1.1)
listener.admin.downstream_cx_length_ms: P0(nan,33) P25(nan,33.75) P50(nan,125000) P75(nan,262500) P90(nan,267000) P95(nan,268500) P99(nan,269700) P99.5(nan,269850) P99.9(nan,269970) P100(nan,270000)
server.initialization_time_ms: P0(nan,37) P25(nan,37.25) P50(nan,37.5) P75(nan,37.75) P90(nan,37.9) P95(nan,37.95) P99(nan,37.99) P99.5(nan,37.995) P99.9(nan,37.999) P100(nan,38)
```

I don't understand why it there is no upstream_rq_time.  Latency between these two systems is like 130ms (ping).
I do have other dynamic statistics like cluster.cluster_1.upstream_rq_completed: 2 but not this one. I am using latest envoy dev version container. 

Thank you for your help.
