### ISSUE TITLE
Hold the health check attempts when downstream tls context (mTLS client certificate) is not ready

### ISSUE THREAD

**Issue by jijiechen** [envoyproxy/envoy#35874]
*Title*: *Hold the health check attempts when downstream tls context (mTLS client certificate) is not ready*

*Description*:
> Envoy should hold the initial active health check connect attempt when it does not have a correct client certificate ready for building a tls transport socket. In this case, the health check attempt will always fail and the failure is known to the client side hence should not be treated as a server/network failure.
> When Envoy is connected with a control plane, mTLS client certificates usually can get ready in a few seconds, but health checks connect earlier than the SDS request. So the initial attempt will always fail. This will block the cluster initialization for long: When 'no_traffic_interval' is not set on the cluster `health_checks`, Envoy will use default `60s`: because of the initial attempt failure, the cluster initialization process will last more than 60s even when the endpoints are actually healthy.

*Repro steps*:
> We encountered in the [Kuma service mesh](https://kuma.io), while it applies to any setup with mTLS and active health checks enabled.
> Steps:
> 1. create a Kuma service mesh following the tutorial at https://kuma.io/docs/2.8.x/quickstart/kubernetes-demo/
> 2. enable mTLS for the mesh using example policy at https://kuma.io/docs/2.8.x/policies/mutual-tls/#usage-of-builtin-ca
> 3. create a `MeshHealthCheck` policy with `noTrafficInterval` not specified, using the example from this page: https://kuma.io/docs/2.8.x/policies/meshhealthcheck/#mesh-health-check ,  or use the policy underneath.
> 4. trigger a pod restart on the demo app: `kubectl -n kuma-demo rollout restarrt deploy/demo-app`, we'll see the pod becomes ready after longer than 60s.

Example Kuma `MeshHealthCheck` policy:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHealthCheck
metadata:
  name: hc-default
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        interval: 10s
        timeout: 2s
        unhealthyThreshold: 3
        healthyThreshold: 1
        tcp: {}
        http:
          path: /
``` 

*Config*:
> I'll put it in a comment reply as it's too large.

*Logs*:
> I'll put it in a comment reply as it's too large.
