### ISSUE TITLE
xDS not reloading file after modification

### ISSUE THREAD

**Issue by inssein** [envoyproxy/envoy#35888]
I have envoy configured to do file based xDS, like so:

```
dynamic_resources:
  cds_config:
    path: /app/config/cds.yaml
  lds_config:
    path: /app/config/lds.yaml
```

When I start envoy with debug logging on, I see that a watch was added:
```
[45][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:76] notification: fd: 1 mask: 2 file: cds.yaml
```

When a file gets modified, I see the appropriate notification:
```
[45][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:50] added watch for directory: '/app/config' file: 'cds.yaml' fd: 1
```

However, I don't get any "matched callback" log statements from https://github.com/envoyproxy/envoy/blob/main/source/common/filesystem/inotify/watcher_impl.cc#L89-L99.

Initially I thought it was `inotify` related issues since I am running in a docker container, but the log statements show thats not it. I also tried moving to the new config format (`path_config_source`), and even tried playing around with `watched_directory`, but haven't got anything to work.
