### ISSUE TITLE
envoy's least request load balancing not working perfectly when there are multiple envoy pods

### ISSUE THREAD

**Issue by apatwal-suki** [envoyproxy/envoy#35935]
*Title*: *Envoy's load balancing not working perfectly when there are multiple envoy pods*

*Description*:
We have a hard limit of 2 on the maximum number of active requests that can be served by a backend application pod(`ms-dummy-suki-asr-v2` in this case). With this envoy config and only **one** envoy pod, least request load balancing works fine:
```apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-ms-dummy-suki-asr-v2-conf
data:
  envoy.yaml: |
    node:
      id: "nvidia"
      cluster: "suki-dev"

    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 443
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              access_log:
              - name: envoy.file_access_log
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/dev/stdout"
              codec_type: AUTO
              stat_prefix: ingress_https
              route_config:
                name: local_route
                virtual_hosts:
                - name: https
                  domains:
                  - "*"
                  retry_policy:
                    num_retries: 10
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: ms-dummy-suki-asr-v2
                      timeout: 300s
                    response_headers_to_add:
                      - header:
                          key: "x-content-type-options"
                          value: "nosniff"
                        append: true
                      - header:
                          key: "x-frame-options"
                          value: "deny"
                        append: true
                      - header:
                          key: "x-xss-protection"
                          value: "1; mode=block"
                        append: true
                      - header:
                          key: "strict-transport-security"
                          value: "max-age=63072000; includeSubDomains; preload;"
                        append: true
                      - header:
                          key: "content-security-policy"
                          value: "default-src 'none'; frame-ancestors 'none';"
                        append: true
              http_filters:
              - name: envoy.health_check
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                  pass_through_mode: false
                  headers:
                  - name: ":path"
                    exact_match: "/healthz"
                  - name: "x-envoy-livenessprobe"
                    exact_match: "healthz"
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "/etc/ssl/envoy/tls.crt"
                    private_key:
                      filename: "/etc/ssl/envoy/tls.key"
                alpn_protocols: ["h2", "http/1.1"]
      clusters:
      - name: ms-dummy-suki-asr-v2
        connect_timeout: 0.5s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        least_request_lb_config: {"choice_count": 10000}
        common_http_protocol_options: {"idle_timeout": 0.1s}
        http2_protocol_options: {}
        load_assignment:
          cluster_name: ms-dummy-suki-asr-v2
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: ms-dummy-suki-asr-v2.microservices.svc.cluster.local
                    port_value: 10001      
    admin:
      access_log_path: "/dev/stdout"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8090
```

Envoy's service and deployment yaml, for reference:
```
apiVersion: v1
kind: Service
metadata:
  name: envoy-ms-dummy-suki-asr-v2
  namespace: microservices
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin-port
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: envoy-ms-dummy-suki-asr-v2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    suki.ai/owner: '@DevOps'
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: envoy-ms-dummy-suki-asr-v2
    app.kubernetes.io/part-of: suki-Network
  name: envoy-ms-dummy-suki-asr-v2
  namespace: microservices
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: envoy-ms-dummy-suki-asr-v2
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        prometheus.io/scrape-envoy: "true"
      labels:
        app: envoy-ms-dummy-suki-asr-v2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - envoy-ms-dummy-suki-asr-v2
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: ENVOY_UID
          value: "0"
        image: envoyproxy/envoy:tools-v1.29.7
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: x-envoy-livenessprobe
              value: healthz
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
        name: envoy-ms-dummy-suki-asr-v2
        ports:
        - containerPort: 443
          name: https
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: x-envoy-livenessprobe
              value: healthz
            path: /healthz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 3
        resources:
          limits:
            cpu: 7000m
            memory: 4000Mi
          requests:
            cpu: 7000m
            memory: 4000Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - any
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/envoy
          name: config
        - mountPath: /etc/ssl/envoy
          name: certs
      volumes:
      - name: certs
        secret:
          secretName: letsencrypt-suki-dev-tls-digicert
      - configMap:
          name: envoy-ms-dummy-suki-asr-v2-conf
        name: config
```

The above config with 1 envoy replica works fine, and I am able to create 600 concurrent active requests from our test client. However when I increase the number of envoy pods to 2, the load balancing does not work properly anymore, and I get a few errors due to envoy not sending the new request to the pod with the least number of active requests. How can I fix this to make it work for multiple envoy pods as well for high availability?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
