### ISSUE TITLE
Matcher-based Listener filters

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#35958]
*Title*: Matcher-based Listener filters

*Description*:
Currently, we use tls_inspector and http_inspector in a variety of places to inspect traffic. The problem with these is its not safe to unconditionally enable them, as some protocols are "server first" protocols where the server sends the first bytes of traffic.

In the past, we worked around this by using the `FilterDisabled` field on the listener filter. For our simple use case we had at the time, this was sufficient because we only needed to classify based on port. We used many bind_to_port=false listeners, rather than 1 large listener with a match on IP, effectively giving us an IP-match implicitly 

We are moving towards a more complex matching model, reliant on a single listener with lots of chains and using the filter_chain_matcher API. This breaks our ability to disable the filter appropriately.

## Option 1: integrated into the matcher
In the ideal scenario, the listener filters could be enable in the matching tree itself:
```yaml
filterChainMatcher:
  matcherTree:
    input:
      name: ip
      rangeMatchers:
      - ranges:
        - addressPrefix: 240.240.0.2
        onMatch:
          listenerFilters: ["http_inspector"] # THIS WOULD BE NEW
          exactMatchMap:
            input:
              name: port
            map:
              "465":
                action: cluster-465
              "587":
                action: cluster-587
```

Basically we do some preliminary matching, then run the listener filter, then can do more matching. Obviously the user will need to ensure they run the filter before matching the output of it.

## Option 2: a new dedicated match

Rather than the `FilterDisabled` approach which just handles ports, we could have a `FilterDisabledMatcher` or equivalent which uses the new matcher framework.

The downside of this approach is that it requires generating a mirror matcher tree. This may be expensive and complex to maintain

cc @keithmattix

**Comment by keithmattix** [comment]
I'm not sure option 1 is feasible unfortunately. If you have a FCM based off of SNI, how could it match without running tls inspector first?

**Comment by howardjohn** [comment]
You would need to put the "use tls inspector" before the SNI match

**Comment by keithmattix** [comment]
Am I understanding you correctly that we would need to also have a (small) dependency tree of shorts for matches and listener filters in order to know if there's a listener filter that needs to be inserted even if the control plane/user didn't specify it? In other words: if I specify a server_name match without putting tls_inspector in my listenerFilter list, will that filter get added or will the match always fail?

**Comment by howardjohn** [comment]
Maybe this is more clear:
```yaml
matcher:
  # Match IP first
  matchType: IP
  matchers:
    1.2.3.4:
      onMatch:
        # We match, run inspector
        enableListenerFilter: my-tls_inspector
        matchTree:
          # Now match SNI
          matchType: SNI
          ...
    3.4.5.6:
      onMatch: # Match SNI without enabling the listener... this is broken, will never match; users should just not do this
        matchTree:
          # Now match SNI
          matchType: SNI
          ...
    5.6.7.8:
      onMatch: # here I don't enable tls inspector but also do not needed
        matchTree:
          # Now match port
          matchType: port
          ...
listener_filters:
- name: my-tls_inspector
  typed_config: ...
  use_matcher: true # signal to not always enable. But we don't want to put the full spec in the tree probably ,just  the named reference
- name: my-http_inspector
  typed_config: ...
  use_matcher: true

```
