### ISSUE TITLE
Redis can only connect to the default database (0)

### ISSUE THREAD

**Issue by rjl126** [envoyproxy/envoy#36031]
Can redis clusters be configured to connect to databases other than 0?

I am using envoy as a redis proxy, and using `redis-cli` to connect. 
I am specifying a database number to connect to e.g. `redis-cli -n 1` However in practice this connects me to database 0. So, I cannot read keys that were created in another database.

Is there a way to configure envoy to connect to redis on a different database?

Example config that I have so far:
```  
clusters:
  - name: redis_test1
    connect_timeout: 3s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis_test1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: my-redis-address
                port_value: 6379
```
