### ISSUE TITLE
CORS: support `*` for `expose_headers` and treate `*` as literal when `allow_credentials` is set to true.

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#36066]
*Title*: CORS: support `*` for `expose_headers` and treate `*` as literal when `allow_credentials` is set to true.

*Description*:

According to the [CORS specification](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers#directives), `expose_headers` should also allow `*` to expose all headers, and if `allow_credentials ` is true, then the `*` in `allow_methods`, `allow_headers`, and `expose_headers` should be treated as a literal.

The current implementation:

`allow_methods`:  [the CORS filter use `*` to match all methods](https://github.com/envoyproxy/envoy/blob/eb61f368690cae173502f80549b7e2169ec24766/source/extensions/filters/http/cors/cors_filter.cc#L140-L159).
`allow_headers`:  [he CORS filter use `*` use it to match all headers](https://github.com/envoyproxy/envoy/blob/eb61f368690cae173502f80549b7e2169ec24766/source/extensions/filters/http/cors/cors_filter.cc#L140-L159).
`expose_headers`: `*` is treated as a normal character.

Test:

```yaml
                envoy.filters.http.cors:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                  allowCredentials: true
                  allowHeaders: '*'
                  allowMethods: '*'
                  exposeHeaders: '*'
                  allowOriginStringMatch:
                  - safeRegex:
                      regex: .*
  ```
  
  ```bash
  curl -H "Origin: http://www.foo.com/" \
  -H "Host: www.example.com" \
  -H "Access-Control-Request-Method: GET" \
  -H "Access-Control-Request-Headers: Content-Type, x-resp" \
  -H "Access-Control-Expose-Headers: xxxxxx, yyyyy" \
  -X OPTIONS -v -s \
http://172.18.255.200/  \
  1> /dev/null

< HTTP/1.1 200 OK
< access-control-allow-origin: http://www.foo.com/
< access-control-allow-methods: GET
< access-control-allow-headers: Content-Type, x-resp
< access-control-expose-headers: *
< date: Tue, 10 Sep 2024 08:43:47 GMT
< content-length: 0
```
