### ISSUE TITLE
Hey guys i'm currently checking out envoy with opa integration with http but i have an issue that the opa is throwing 404

### ISSUE THREAD

**Issue by achainarong** [envoyproxy/envoy#36112]
*Title*:  Error 404 when envoy checks opa for authorization

*Description*:
Im currently using the envoy and opa container in my docker compose environment. I tested the routes without external authorization with opa and they worked. Now i added the opa with a config that allows all. 

Envoy now tries to query the permissions without a request body and with the wrong path.

Here the opa logs

This is a curl request for the opa:
<code>
2024-09-13 09:00:53 {"client_addr":"172.18.0.1:40678","level":"info","msg":"Received request.","req_body":"{\r\n    \"input\": {\r\n        \"attributes\": {\r\n            \"request\": {\r\n                \"http\": {\r\n                    \"method\": \"OPTIONS\",\r\n                    \"path\": \"/api"\r\n                }\r\n            }\r\n        }\r\n    }\r\n}","req_id":4,"req_method":"POST","req_params":{},"req_path":"/v1/data/envoy/authz","time":"2024-09-13T07:00:53Z"}`
2024-09-13 09:00:53 {"decision_id":"612d5490-0f45-47f5-9650-7f8af5e62588","input":{"attributes":{"request":{"http":{"method":"OPTIONS","path":"/api"}}}},"labels":{"id":"a446bfba-462f-4b39-9502-9b0a241b4fb7","version":"0.67.1-envoy-4"},"level":"info","metrics":{"counter_server_query_cache_hit":1,"timer_rego_external_resolve_ns":513,"timer_rego_input_parse_ns":77520,"timer_rego_query_eval_ns":218094,"timer_server_handler_ns":376393},"msg":"Decision Log","path":"envoy/authz","req_id":4,"requested_by":"172.18.0.1:40678","result":{"allow":true},"time":"2024-09-13T07:00:53Z","timestamp":"2024-09-13T07:00:53.125330015Z","type":"openpolicyagent.org/decision_logs"}
2024-09-13 09:00:53 {"client_addr":"172.18.0.1:40678","level":"info","msg":"Sent response.","req_id":4,"req_method":"POST","req_path":"/v1/data/envoy/authz","resp_body":"{\"decision_id\":\"612d5490-0f45-47f5-9650-7f8af5e62588\",\"result\":{\"allow\":true}}\n","resp_bytes":79,"resp_duration":0.797659,"resp_status":200,"time":"2024-09-13T07:00:53Z"}
</code>

This is the envoy request:
<code>
2024-09-13 09:02:12 {"client_addr":"172.18.0.31:44880","level":"info","msg":"Received request.","req_body":"","req_id":5,"req_method":"OPTIONS","req_params":{},"req_path":"/api","time":"2024-09-13T07:02:12Z"}
2024-09-13 09:02:12 {"client_addr":"172.18.0.31:44880","level":"info","msg":"Sent response.","req_id":5,"req_method":"OPTIONS","req_path":"/api","resp_body":"404 page not found\n","resp_bytes":19,"resp_duration":0.554975,"resp_status":404,"time":"2024-09-13T07:02:12Z"}
</code>

My envoy config for the opa:
```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              http_filters:
              - name: envoy.filters.http.ext_authz
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                  http_service:
                    server_uri:
                      uri: http://opa:8181
                      cluster: opa_cluster
                      timeout: 5s
...
...
  clusters:
    - name: opa_cluster
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: round_robin
      load_assignment:
        cluster_name: opa_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: opa
                      port_value: 8181
```

Did i set up envoy wrong, or what could the problem be?
 I tested it in multiple envoy version (1.23, .1.28, 1.31)
