### ISSUE TITLE
Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''

### ISSUE THREAD

**Issue by bytersproblem** [envoyproxy/envoy#36121]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''*

*Description*:
>I am very new to this software. I set up an `envoy.yaml` with 12 listeners and 12 clusters. I formatted the `yaml` correctly and I get the following error 
```
Didn't find a registered implementation for 'envoy.filters.http.router' with type URL: ''
```
This is the beginning of one of my listeners:

```yaml
  listeners:
  # Listener for port 1
  - name: listener_1
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 50001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: grpc_service_1
          route_config:
            name: grpc_service_1_route
            virtual_hosts:
            - name: grpc_service_1_host
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: grpc_service_1_cluster
                  timeout: 0s
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
I installed envoy 1.31 via debian repository for `bullseye` What is wrong with my setup? Thanks for your patience!
