### ISSUE TITLE
filter_chain_match.server_names is not working for TCP filter

### ISSUE THREAD

**Issue by andytruong** [envoyproxy/envoy#3615]
*Title*: *filter_chain_match.server_names is not working for TCP filter*

*Description*:

Per my configuration bellow, I can't route my TCP request to NATS:

```
telnet nats.dev.my.service 4222 # Doesn't work
telnet nats-seed.dev.my.service 4444 # Doesn't work
```

If I remove the `filter_chain_match`, it's working as expected.

*Config*:

```
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: nats
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 4222
    filter_chains:
    - filter_chain_match: { server_names: "nats.dev.my.service" }
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: nats_cluster
    - filter_chain_match: { server_names: "nats-seed.my.go1.service" }
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: ingress_tcp
          cluster: nats_seed

  clusters:
  - name: nats_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    hosts:
    - { socket_address: { address: seed, port_value: 4222 }}
  - name: nats_seed
    connect_timeout: 0.25s
    type: STRICT_DNS
    hosts:
    - { socket_address: { address: seed, port_value: 4444 }}
```
