### ISSUE TITLE
config validation: validator only checks for file presence not content

### ISSUE THREAD

**Issue by cpakulski** [envoyproxy/envoy#36289]
when file system is used to configure Envoy, the config validator (`-mode validate`) only checks if files are present but does not load those files to check if their content is valid.

In this super simple config:
```
dynamic_resources:
  cds_config:
    resource_api_version: V3
    path_config_source:
      path: /test/cds.yaml
  lds_config:
    resource_api_version: V3
    path_config_source:
      path: /test/lds.yaml
```

the validator will accept empty and non-yaml files when run in `validate` mode.
