### ISSUE TITLE
Happy eyeballs crashes on request, rather than NACKs, invalid configuration

### ISSUE THREAD

**Issue by howardjohn** [envoyproxy/envoy#36318]
Example config:

```
- clusterName: outbound|80||echo.default.svc.cluster.local
  endpoints:
  - lbEndpoints:
    - endpoint:
        additionalAddresses:
        - address:
            envoyInternalAddress:
              endpointId: '[fd00:10:244::10]:80'
              serverListenerName: connect_originate
        address:
          envoyInternalAddress:
            endpointId: 10.244.0.16:80
            serverListenerName: connect_originate
        healthCheckConfig: {}
      healthStatus: HEALTHY
      loadBalancingWeight: 1
      metadata:
        filterMetadata:
          envoy.filters.listener.original_dst:
            local: 10.244.0.16:80
          envoy.transport_socket_match:
            tunnel: http
          istio:
            workload: echo;default;echo;;Kubernetes
    loadBalancingWeight: 1
    locality: {}
  policy:
    overprovisioningFactor: 140
```

This line crashes on requests:
https://github.com/envoyproxy/envoy/blob/a65765e00f4dda2bd92aee7b263ffcdbee08775a/source/common/network/happy_eyeballs_connection_impl.cc#L121.

The problem here is we try to access the `ip` field but there is none.

If happy eyeballs does not support non-IP fields it would be preferred for it to NACK rather than crash at runtime.

Note: for our specific case here, it doesn't really make sense to use additional_addresses anyways; we are doing HTTP CONNECT tunneling and need to put the target address in the `metadata` field. Since metadata is not tied to an address, you can see we always set the IPv4 there which makes it kind of obsolete anyways. I was mostly trying to see what would happen if I did this.
