### ISSUE TITLE
Send response header to gRPC access logs server, but don't send it to user

### ISSUE THREAD

**Issue by asidorochev** [envoyproxy/envoy#36338]
I use gRPC server to collect access logs. My service responses with header I need to log. So my config looks like this:
```
- name: envoy.access_loggers.http_grpc
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
      additional_response_headers_to_log:
        - x-header-to-log
      additional_request_headers_to_log:
        - Range
      common_config:
        log_name: grpc
        grpc_service:
          google_grpc:
            target_uri: "[grpc.server.ip.address]:5001"
            stat_prefix: streams_total
```
But I need not to send this header to user. I tried to use `response_headers_to_remove: - x-header-to-log` inside `route_config` section to achieve it, but in this case header doesn't present in access log message. How can I fix it?
