### ISSUE TITLE
Not logging policies name if denied

### ISSUE THREAD

**Issue by zvlb** [envoyproxy/envoy#36346]
*Title*: *Not logging policies name if denied*

*Description*:
> I have Filter with simple RBAC http Filter:
```
    - name: envoy.filters.http.rbac
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
        rules:
          action: ALLOW
          policies:
           whitelist:
              permissions:
                - any: true
              principals:
                - source_ip:
                    address_prefix: 127.0.0.1
                    prefix_len: 32
```

If i create requests from localhost all work good, and i see in logs:
```
[2024-09-26 11:40:13.329][3492045][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:182] enforced allowed, matched policy whitelist
```

But if I create request from external server, envoy block my request (`RBAC: access denied`), but in logs:
```
[2024-09-26 11:41:28.955][3492043][debug][rbac] [source/extensions/filters/http/rbac/rbac_filter.cc:194] enforced denied, matched policy none
```

Envoy doesn't print policy name(
