### ISSUE TITLE
Possible to set "whitelisted ips" in ratelimiting

### ISSUE THREAD

**Issue by zetaab** [envoyproxy/envoy#36442]
*Title*: Set ratelimiting to all cidrs with exceptions

*Description*:

I have usecase that I should add ratelimiting to all addresses (0.0.0.0/0) EXCEPT few "whitelisted ips". As I see it, it is quite common use case that people want to set rate limits to everything except few internal api ips (whitelist services that should work always, no matter what).

*Relevant Links*:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-ratelimit-action

currently envoy does not support exceptions to the `remote_address` matcher. But it could have "not logic"?

**Comment by kyessenov** [comment]
I think a "composite" filter could help here. You could wrap the enforcement in a conditional filter that limits the application of the enforcement filter.

**Comment by avinandi** [comment]
@kyessenov Do you have any idea why this does not work, this is built following the reference [here](https://gateway.envoyproxy.io/contributions/design/rate-limit/)

The idea is to set a higher limit for certain CIDR blocks and for rest restrict to lower limit.

```yaml
---

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: api--rate-limit-all
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api--http-route
  rateLimit:
    type: Global
    global:
      rules:
        - limit:
            requests: 100
            unit: Second
        - limit:
            requests: 500
            unit: Minute

---

apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: api--limit-whitelist
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api--http-route
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
          - sourceCIDR:
              value: x.y.z.r/30
              type: Distinct
          - sourceCIDR:
              value: x.y.x.r/32
          - sourceCIDR:
              value: x.y.x.r/32
          - sourceCIDR:
              value: x.y.x.r/32
          - sourceCIDR:
              value: x.y.x.r/31
              type: Distinct
          limit:
            requests: 10000
            unit: Minute

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api--http-route
  annotations:
    repository: "https://github.devcloud.elisa.fi/hy/contentful-api"
  labels:
    app.kubernetes.io/name: contentful-api
    application: contentful-api
    app: contentful-api
    team: aspa
spec:
  parentRefs:
    - name: external-gateway
  hostnames:
    - example.com
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: RateLimitFilter
            name: api--limit-whitelist
      backendRefs:
        - name: api--service
          port: 3000
    - matches:
      - path:
          type: PathPrefix
          value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.envoyproxy.io
            kind: RateLimitFilter
            name: api--rate-limit-all
      backendRefs:
        - name: api--service
          port: 3000
```
