### ISSUE TITLE
Run go extension for separate routes only

### ISSUE THREAD

**Issue by alex-sorochkin** [envoyproxy/envoy#36669]
*Title*: *Is there an opportunity to run go extensions separately for different routes?*

*Description*:
I'm starting to use Envoy as API GW for my project. I already have some services and now I want to organize routing via that all. Additionally I'd like to use some modules on go, but for separate groups of URLs. So, other URLs shouldn't be processed by modules.
The other issue I want to cover is that I have more than one module, and I don't want them all be executed per each configured route. Other words I want each route be able to configure the list of extensions be executed.
I use `envoy.filters.network.http_connection_manager` filter but I can't have them more than one in my config.

Is there any chance to solve that?

My config is below. Thanks!

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/hallo1"
                          route:
                            cluster: cluster1
#                            want my extension be executed here
                        - match:
                            prefix: "/hallo2"
                          route:
                            cluster: cluster2
#                            DON'T want my extension be executed here
                        - match:
                            prefix: "/"
                          route:
                            cluster: cluster1
                http_filters:
                  - name: envoy.filters.http.golang
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
                      library_id: mypluginid
                      library_path: "/etc/envoy/bin/envoy-gw.so"
                      plugin_name: simple
                      plugin_config:
                        "@type": type.googleapis.com/xds.type.v3.TypedStruct
                        value:
                          prefix_localreply_body: "Configured local reply from go"
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: cluster1
      connect_timeout: 30s
      type: STATIC
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: cluster1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 9091
    - name: cluster2
      connect_timeout: 30s
      type: STATIC
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: cluster2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 9092

```
