### ISSUE TITLE
PreviousHostsPredicate does not retry

### ISSUE THREAD

**Issue by erikschul** [envoyproxy/envoy#36736]
I'm using k6 to make concurrent requests to Envoy, which should then forward to two upstream services.

Scenario:

1. docker-compose is running, using `nginx` for lb_endpoints
2. lb_endpoints are healthy (I wait for 30s just to be sure)
3. service1 is killed (`docker compose kill service1`)
4. wait 1 second and run k6

Expected: 
- lb_endpoints should still be "healthy". Requests to service1 should fail and retry on service2. Because all requests were started after kill, I expect 100% status 200.

Actual: 
- if I run k6 with concurrency of 1 (`vus: 1`), then I get 100% status 200, also when extending duration to `100s`.
- concurrency of 5: 100.00% 20 out of 20
- concurrency of 50: 56.32% 178 out of 316

What could be the problem?
It seems related to concurrency, so maybe use a high number when trying to reproduce.
I've spent a whole day trying to debug this, so I would appreciate any help.

Logs:
[logs.txt.tar.gz](https://github.com/user-attachments/files/17466628/logs.txt.tar.gz)

## k6
```
import http from "k6/http"
import { check, sleep } from "k6"

export let options = {
	vus: 1,
	duration: "10s",
}

export default function () {
	let res = http.get("http://localhost:8080/")
	check(res, {
		"status is 200": (r) => r.status === 200,
		"body has expected value": (r) => r.body.includes("start"),
	})
	sleep(1)
}
```

## retry_policy
```
retry_policy:
  # I tried these:
  retry_on: "5xx,gateway-error,reset,connect-failure"
  # retry_on: "connect-failure"
  # retry_on: "5xx"

  # I've tried variations: 1, 3, 10, 50, 1000
  num_retries: 1000
  host_selection_retry_max_attempts: 1000

  # I've tried with and without:
  retry_back_off:
    base_interval: 1s
    max_interval: 1s

  retry_host_predicate:
  - name: envoy.retry_host_predicates.previous_hosts
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
```

## endpoints
```
version_info: '0'
resources:
  - "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
    name: balanced

    # Tried:
    lb_policy: RANDOM
    # lb_policy: ROUND_ROBIN
    # lb_policy: LEAST_REQUEST
    # lb_policy: MAGLEV
    
    type: STATIC
    connect_timeout: 1s
    health_checks:
      - timeout: 1s
        interval: 1s
        unhealthy_threshold: 10
        healthy_threshold: 1
        http_health_check: { path: "/" }
    load_assignment:
      cluster_name: balanced
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 172.28.1.11
                    port_value: 80
            - endpoint:
                address:
                  socket_address:
                    address: 172.28.1.12
                    port_value: 80
```
