### ISSUE TITLE
Error: terminal filter named envoy.filters.network.golang of type envoy.filters.network.golang must be the last filter in a network filter chain.

### ISSUE THREAD

**Issue by owayss** [envoyproxy/envoy#36829]
*Title*:
Error: terminal filter named envoy.filters.network.golang of type envoy.filters.network.golang must be the last filter in a network filter chain.

*Description*:
Seen on `contrib-dev`, but also on all v1.30+ releases that admit the golang filter.

It seems that the golang network filter implementation is hardcoded to be a terminal filter https://github.com/envoyproxy/envoy/blob/63d4fb0c442d6362bcf5101fc2a5279aeaef31bb/contrib/golang/filters/network/source/config.h#L42, while the HTTP golang filter can be placed anywhere in the chain.

*Repro steps*:
Add any network filter in a chain after `envoy.filters.network.golang`

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.
```yaml
# envoy demo with golang extension enabled
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.golang
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.golang.v3alpha.Config
          is_terminal_filter: false
          library_id: simple
          library_path: "/lib/simple.so"
          plugin_name: simple
          plugin_config:
            "@type": type.googleapis.com/xds.type.v3.TypedStruct
            value:
              echo_server_addr: echo_service
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: destination
          cluster: cluster_0
  clusters:
  - name: plainText
    type: ORIGINAL_DST
    lb_policy: CLUSTER_PROVIDED
  - name: cluster_0
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: cluster_0
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: localhost
                    port_value: 5000
```

*Logs*:
```
golang-network-proxy-1         | [2024-10-25 08:55:50.756][1][critical][main] [source/server/server.cc:412] error initializing config '  /etc/envoy.yaml': Error: terminal filter named envoy.filters.network.golang of type envoy.filters.network.golang must be the last filter in a network filter chain.
golang-network-proxy-1         | [2024-10-25 08:55:50.756][1][info][main] [source/server/server.cc:1050] exiting
golang-network-proxy-1         | Error: terminal filter named envoy.filters.network.golang of type envoy.filters.network.golang must be the last filter in a network filter chain.
```

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
