### ISSUE TITLE
Proxy protocol support for HTTP3 (UDP)

### ISSUE THREAD

**Issue by hwyuan** [envoyproxy/envoy#36881]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Proxy protocol support for HTTP/3 (UDP)*

*Description*:
>Has anyone tried proxy protocol with HTTP/3 (UDP). From [source code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/listener/proxy_protocol/config.cc), proxy protocol listener filter is registered under `NamedListenerFilterConfigFactory`, does this work with HTTP/3 (UDP) traffic? is `NamedUdpListenerFilterConfigFactory` required for a filter to work with UDP?

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by nezdolik** [comment]
cc @ggreenway @alyssawilk

**Comment by alyssawilk** [comment]
I'm not sure how you envision proxy protocol working with HTTP/3?  
for TCP, the middlebox injects bytes at the beginning of the the TCP stream, which it can do even for TLS because the (plaintext) payload precedes the TLS handshake.  With HTTP/3 I don't think there's an equivalent mechanism to either have a transparent proxy terminating HTTP/3 or to inject bytes but @RyanTheOptimist and @danzh2010 can correct me if there's some IETF standard workaround that's not on my radar

**Comment by RyanTheOptimist** [comment]
I'm also unaware of such a mechanism...

**Comment by hwyuan** [comment]
Our use case would be using an IPv6-only NLB in front of IPv4 Envoy L7 proxy, in which case we'll have to rely on something like proxy protocol to pass the real client IP. 
- It seems NLB's proxy protocol would support UDP ([blog post link](https://aws.amazon.com/blogs/networking-and-content-delivery/preserving-client-ip-address-with-proxy-protocol-v2-and-network-load-balancer/))
- The current envoy proxy protocol implementation seems to have considered UDP as it's checking for STREAM for TCP and DGRAM for UDP ([code pointer](https://github.com/envoyproxy/envoy/blob/ec94989f7ecce064a130ae43070352bbf4a0b7b6/source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc#L360)), but it's not clear if we could configure it for http/3.
- An earlier issue on this topic is in https://github.com/envoyproxy/envoy/issues/19004, where the desired config would be
```
...
- name: listener_udp
  address:
    socket_address:
      protocol: UDP
      address: 0.0.0.0
      port_value: 10000
  listener_filters:
  - name: envoy.filters.listener.proxy_protocol
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol
  udp_listener_config:
    quic_options: {}
    downstream_socket_config:
      prefer_gro: true
```

I tried this config and got the following answer
```
Error adding/updating listener(s) trk_h3:443: Didn't find a registered implementation for name: 'envoy.filters.listener.proxy_protocol'
```

What would it take to make the proxy_protocol work with the listener that has UDP selected as protocol?
