### ISSUE TITLE
lua EnvoyFilter consumes a large amount of memory.

### ISSUE THREAD

**Issue by bergen4** [envoyproxy/envoy#36904]
*Description*:
>I use higress as the gateway for my service. Currently, I want to upgrade from higress 1.3.6 to 2.0.1. I found that the memory used by higress in the production environment has increased from 2GB to 12GB. Further analysis revealed that all 12GB of memory was consumed by envoy. 
![image](https://github.com/user-attachments/assets/8d0ee255-2c04-4632-8e13-25aad777caa3)

>However, when I checked the mem statistics and pprof analysis of envoy, I found that envoy only consumed 600MB of memory, which is inconsistent with the 12GB reported by the OS. 
![image](https://github.com/user-attachments/assets/63e04a02-568a-4423-ab7a-b30f0815c747)
![image](https://github.com/user-attachments/assets/0c565199-bade-4a1a-adf8-32f6232f1396)

>Therefore, I suspect that the memory consumption is due to the lua filter. So, I tested higress v1.3.6 (using envoy v1.20) and higress v2.0.1 (using envoy 1.27) in the test environment, and observed the impact of lua envoyFilter on envoy memory under both versions. Here are my findings: 
1. In the pre-upgrade version 1.3.6 of higress, adding one lua envoyfilter would increase envoy’s memory by 150MB. 
2. After upgrading to higress version 2.0.1, adding one lua envoyfilter would increase envoy’s memory by 2GB. 
3. Adding other types of envoyfilters (non-lua) did not affect envoy’s memory.

>Both test versions were tested under the same conditions, using approximately 4000 routing rules, 300 clusters, and the lua filter had no business logic, serving only to print a log message.

>So, I would like to ask if there have been any changes between Envoy 1.20 and 1.27 that could cause the lua envoyfilter to consume a large amount of memory? thanks.

**Comment by nezdolik** [comment]
cc @wbpcode

**Comment by bergen4** [comment]
[filters.tar.gz](https://github.com/user-attachments/files/17580751/filters.tar.gz)
This EnvoyFilter file contains 3 Lua filters and several non-Lua filters. According to my tests, the Lua filters have a significant impact on memory, whereas the non-Lua filters do not affect memory

**Comment by wbpcode** [comment]
> However, when I checked the mem statistics and pprof analysis of envoy, I found that envoy only consumed 600MB of memory, which is inconsistent with the 12GB reported by the OS.

It's weird result. Will the memory increase after the configuration is applied and even there is no traffic? Then I can try to reproduce this problem.

**Comment by bergen4** [comment]
Yes, after startup, without  any traffic, as soon as the configuration is synchronized to Envoy, the memory  will increase

**Comment by johnlanni** [comment]
@wbpcode Higress's Envoy has not made any modifications to the Lua filter. I will test to reproduce this issue using pure Envoy and config.yaml.

**Comment by johnlanni** [comment]
I tried and couldn't reproduce this scenario, whether using higress or simply using envoy + config. Below is the docker-compose configuration I used for testing:

docker-compose.yaml:

```yaml
version: '3.7'
services:
  envoy:
    image: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/gateway:v2.0.2
    entrypoint: /usr/local/bin/envoy
    command: -c /etc/envoy/envoy.yaml
    depends_on:
    - httpbin
    networks:
    - higress
    ports:
    - "10000:10000"
    volumes:
    - ./envoy.yaml:/etc/envoy/envoy.yaml

  httpbin:
    image: kennethreitz/httpbin:latest
    networks:
    - higress
    ports:
    - "12345:80"

networks:
  higress: {}
```

envoy.yaml:

```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          scheme_header_transformation:
            scheme_to_overwrite: https
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: httpbin
          http_filters:
          - name: lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(handle)
                  handle:logWarn("hello lua")
                end
          - name: lua2
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(handle)
                  handle:logWarn("hello lua")
                end
          - name: lua3
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(handle)
                  handle:logWarn("hello lua")
                end
          - name: lua4
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(handle)
                  handle:logWarn("hello lua")
                end
          - name: lua5
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(handle)
                  handle:logWarn("hello lua")
                end
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: httpbin
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin
                port_value: 80
```

Start using the command below:

```bash
docker compose up
```

It looks like the memory usage is very small, and for each added Lua filter, the increase in memory does not exceed 3MB.

@bergen4 Can you use this configuration as a template, modify the lua filter configuration to the one you actually use, and then conduct the test?
