### ISSUE TITLE
Is it possible to use dynamic metadata to select directly endpoint of a cluster

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#36963]
I know that we can select endpoints by metadata. For example,

```
  load_assignment:
    cluster_name: cluster_gateway_https
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address: *gateway_224_https_addr
        metadata:
          filter_metadata:
            envoy.lb:
              canary: "0"
      - endpoint:
          address:
            socket_address: *gateway_225_https_addr
        metadata:
          filter_metadata:
            envoy.lb:
              canary: "1"
```
Now I want to select endpoints by dynamic metadata which comes from JWT.
```
         - name: envoy.filters.http.jwt_authn
           typed_config:
             "@type": type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
             providers:
               sso_jwt_provider:
                 local_jwks:
                   filename: /conf/envoy/jwks.json
                 from_headers:
                 - name: YL-Authorization
                   value_prefix: "Bearer "
                 payload_in_metadata: jwt_payload
```
As my understanding, the config of JWT writes its payload into the dynamic metadata in the `envoy.filters.http.jwt_authn`. Then I want to use the kvs in the `envoy.filters.http.jwt_authn` to select some endpoints in a cluster. It seems that I need to transmit the dynamic metadata into the metadata `envoy.lb`.but I don't know how.
