### ISSUE TITLE
Envoy truncates request payload when using bandwidth limiting and external auth filter

### ISSUE THREAD

**Issue by niax** [envoyproxy/envoy#36983]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

When Envoy is configured with both the bandwidth limit and external authorization filter, _sometimes_ requests with chunked transfer encoding are truncated. Requests with content-length time out (the endpoint does not see all the expected bytes).

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

Envoy reports version: e3b4a6e9570da15ac1caffdded17a8bebdc7dfc9/1.32.1/Clean/RELEASE/BoringSSL
Envoy is running inside docker, using arm64 running Amazon Linux 2023.

Running a simple client with a server that returns the size of the data it saw, the client eventually does a request that does server does not get all the data for. The client/server were written for repro, but we've seen this behaviour in clients and servers. This combines with a do-nothing external auth implementation that waits a second before OKing the request. All the code for this are in the [attached tarball](https://github.com/user-attachments/files/17625525/envoy-bwlimit-auth-truncation.tar.gz).

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

These are in the [attached tarball](https://github.com/user-attachments/files/17625525/envoy-bwlimit-auth-truncation.tar.gz).

*Config*:
>Include the config used to configure Envoy.

Full config is in the tarball, but the filter chain included here:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    per_connection_buffer_limit_bytes: 10240
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.bandwidth_limit
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.bandwidth_limit.v3.BandwidthLimit
              stat_prefix: rate_limit
              limit_kbps: 128
              fill_interval: 0.02s
              enable_mode: "REQUEST_AND_RESPONSE"
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              transport_api_version: V3
              grpc_service:
                envoy_grpc:
                  cluster_name: ext_authz_cluster
                timeout: 3s
              status_on_error:
                code: ServiceUnavailable
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_echo_http
```

I'm not sure how much the connection buffer or bandwidth limit rate play in to things, but setting it lower seems to make the bug more reliable to reproduce.

*Logs*:
>Include the access logs and the Envoy logs.

Envoy Logs are in the [tarball](https://github.com/user-attachments/files/17625525/envoy-bwlimit-auth-truncation.tar.gz). In the logs, the failed request is to `/0a9748ab-5ab5-4783-83a2-4b98cf832875`, the server reports it only saw 8232 bytes of the expected 10240.
