### ISSUE TITLE
[envoy.filters.http.credential_injector]: Add prefix value to injected credentials 

### ISSUE THREAD

**Issue by salrashid123** [envoyproxy/envoy#37001]
hi-

I've got [envoy.filters.http.credential_injector](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/credential_injector_filter) working fine given the examples in the docs (and below)...but what i'd like to do is add a prefix value to the sourced credential.

In my case, i'd like to read `/var/run/secrets/kubernetes.io/serviceaccount/token` and prefix a "Bearer " value to it.

It seems the secret is read as-is which is fine but if i wanted to add a prefix value without altering the file contents itself, is there any creative workaround right now?

@zhaohuabing 

```yaml
node:
  cluster: service_greeter
  id: test-id

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080      
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          http2_protocol_options: {}          
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_httpbin
          http_filters:
          - name: envoy.filters.http.credential_injector
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
              allow_request_without_credential: false
              overwrite: true
              credential:
                name: envoy.http.injected_credentials.generic
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.generic.v3.Generic
                  credential:
                    name: credential-bearer
                  header: "Authorization"
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router    

  secrets:
  - name: credential-bearer
    generic_secret:
      secret:
        filename: /var/run/secrets/kubernetes.io/serviceaccount/token

  clusters:
  - name: service_httpbin
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin.org
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```

**Comment by KBaichoo** [comment]
You might be able to do this using header mutation filter: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_mutation_filter

By using an append mutation to overwrite the header:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-msg-config-core-v3-headervalueoption

**Comment by salrashid123** [comment]
Thanks  but unless the config below is not right, it seems that i can only append, not prepend

It also adds the header value with the comma-separated

output of the config below is: 

```json
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Authorization": "thetoken,Bearer", 
    "Host": "localhost", 
    "User-Agent": "curl/8.8.0", 
    "X-Amzn-Trace-Id": "Root=1-672ba1ac-2eedf6d17a3719e53aa297de", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  }, 
  "url": "https://localhost/get"
}
```


```yaml
admin:
node:
  cluster: service_greeter
  id: test-id

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080      
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          http2_protocol_options: {}          
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_httpbin
          http_filters:
          - name: envoy.filters.http.credential_injector
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
              allow_request_without_credential: false
              overwrite: true
              credential:
                name: envoy.http.injected_credentials.generic
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.generic.v3.Generic
                  credential:
                    name: credential-bearer
                  header: "Authorization"
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router    
              upstream_http_filters:
              - name: upstream_header
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                  mutations:
                    request_mutations:
                      append:
                        append_action: APPEND_IF_EXISTS_OR_ADD
                        header:
                          key: "Authorization"
                          value: "Bearer "
              - name: envoy.filters.http.upstream_codec
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec



  secrets:
  - name: credential-bearer
    generic_secret:
      secret:
        inline_string: "thetoken"

  clusters:
  - name: service_httpbin
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin.org
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

```

**Comment by salrashid123** [comment]
thanks!  that worked

following gives

```json
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Authorization": "Bearer thetoken", 
    "Host": "localhost", 
    "User": "sal", 
    "User-Agent": "curl/8.8.0", 
    "X-Amzn-Trace-Id": "Root=1-672bb50d-6ddb9c0b7fa4accd5f5de9f0", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  }, 
  "origin": "redacted", 
  "url": "https://localhost/get"
}
```

```yaml
admin:
node:
  cluster: service_greeter
  id: test-id

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080      
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          http2_protocol_options: {}          
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_httpbin
          http_filters:
          - name: envoy.filters.http.credential_injector
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.credential_injector.v3.CredentialInjector
              allow_request_without_credential: false
              overwrite: true
              credential:
                name: envoy.http.injected_credentials.generic
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.http.injected_credentials.generic.v3.Generic
                  credential:
                    name: credential-bearer
                  header: "Authorization"
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router    
              upstream_http_filters:
              - name: upstream_header
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
                  mutations:
                    request_mutations:
                      append:
                        append_action: OVERWRITE_IF_EXISTS
                        header:
                          key: "Authorization"
                          value: "Bearer %REQ(Authorization)%"
              - name: envoy.filters.http.upstream_codec
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec



  secrets:
  - name: credential-bearer
    generic_secret:
      secret:
        inline_string: "thetoken"

  clusters:
  - name: service_httpbin
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: service_httpbin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: httpbin.org
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
