### ISSUE TITLE
Modify grpc web socket address to route through ingress

### ISSUE THREAD

**Issue by dingyiyi0226** [envoyproxy/envoy#37021]
*Title*: *Modify grpc web socket address to route through ingress*

*Description*:

For the gRPC-web implementation, the socket address and port are currently set to the name and port of the gRPC service. I would like to wrap this service within the ingress. Is this configuration possible?
I attempted to set it up but encountered a “404 Not Found” error.

The original configuration is similar to [this example](https://grpc.io/docs/platforms/web/basics/#configure-the-envoy-proxy)
and change the following lines

```diff
 - lb_endpoints:
  - endpoint:
     address:
       socket_address:
-         address: grpc-svc
-         port_value: 12345
+         address: abc.com
+         port_value: 80

```

The ingress configuration
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abc
  labels:
    app.kubernetes.io/name: abc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: abc.com
    kubernetes.io/ingress.class: traefikclass
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: abc.com
      http:
        paths:
          - path: /some.Endpoint
            pathType: Prefix
            backend:
              service:
                name: grpc-svc
                port:
                  number: 12345
```
