### ISSUE TITLE
Can we set metadata for HTTP with an environment variable or a static file

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#37116]
I've known how to set metadata for a HTTP so that we can select endpoint with the metadata:
```
...
route_config:
  name:
  virtual_hosts:
  metadata:
    filter_metadata:
      "envoy.lb": 
         canary: true
```
In the example above, we can use `canary: true` to select endpoint in cluster.

My question is if it is possible to get the value of `canary` from an environment variable of OS or from a static file?

For example, after executing `export var=true` or there is a file containing `var=true`, I can configure my envoy as below:
```
...
route_config:
  name:
  virtual_hosts:
  metadata:
    filter_metadata:
    - "envoy.lb": 
         canary: $var    # $var coming from an environment variable or a static file, Is this possible???
```
