### ISSUE TITLE
Golang custom http filter failed with Unable to parse JSON as proto (INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config')

### ISSUE THREAD

**Issue by satya256** [envoyproxy/envoy#37124]
*Title*: *Testing the go custom http filter as provided in the envoy examples and looks like go filter  is not enabled ????*

I am testing on the arm64 env.

*Description*:
>when starting the envoy with below configuration looks like the go http filter is not enabled by default or am I missing something

From logs I can see only the below filters but go is not present not sure why
```
envoy.filters.http: envoy.bandwidth_limit, envoy.buffer, envoy.cors, envoy.csrf, envoy.ext_authz, envoy.ext_proc, envoy.fault, envoy.filters.http.adaptive_concurrency, envoy.filters.http.admission_control, envoy.filters.http.alternate_protocols_cache, envoy.filters.http.aws_lambda, envoy.filters.http.aws_request_signing, envoy.filters.http.bandwidth_limit, envoy.filters.http.basic_auth, envoy.filters.http.buffer, envoy.filters.http.cache, envoy.filters.http.cdn_loop, envoy.filters.http.composite, envoy.filters.http.compressor, envoy.filters.http.connect_grpc_bridge, envoy.filters.http.cors, envoy.filters.http.credential_injector, envoy.filters.http.csrf, envoy.filters.http.custom_response, envoy.filters.http.decompressor, envoy.filters.http.dynamic_forward_proxy, envoy.filters.http.ext_authz, envoy.filters.http.ext_proc, envoy.filters.http.fault, envoy.filters.http.file_system_buffer, envoy.filters.http.gcp_authn, envoy.filters.http.geoip, envoy.filters.http.grpc_field_extraction, envoy.filters.http.grpc_http1_bridge, envoy.filters.http.grpc_http1_reverse_bridge, envoy.filters.http.grpc_json_transcoder, envoy.filters.http.grpc_stats, envoy.filters.http.grpc_web, envoy.filters.http.header_mutation, envoy.filters.http.header_to_metadata, envoy.filters.http.health_check, envoy.filters.http.ip_tagging, envoy.filters.http.json_to_metadata, envoy.filters.http.jwt_authn, envoy.filters.http.local_ratelimit, envoy.filters.http.lua, envoy.filters.http.match_delegate, envoy.filters.http.oauth2, envoy.filters.http.on_demand, envoy.filters.http.original_src, envoy.filters.http.rate_limit_quota, envoy.filters.http.ratelimit, envoy.filters.http.rbac, envoy.filters.http.router, envoy.filters.http.set_filter_state, envoy.filters.http.set_metadata, envoy.filters.http.stateful_session, envoy.filters.http.tap, envoy.filters.http.thrift_to_metadata, envoy.filters.http.wasm, envoy.geoip, envoy.grpc_http1_bridge, envoy.grpc_json_transcoder, envoy.grpc_web, envoy.health_check, envoy.ip_tagging, envoy.local_rate_limit, envoy.lua, envoy.rate_limit, envoy.router
```
```
envoy  version: 7b8baff1758f0a584dcc3cb657b5032000bcb3d7/1.31.0/Distribution/RELEASE/BoringSSL
```
```
 envoy -c ~/Downloads/golang.yaml --mode validate  --enable-fine-grain-logging -l trace
```
The server is throwing the following error.

```

[2024-11-13 21:07:49.577][3560563][critical][main] [source/server/config_validation/server.cc:71] error initializing configuration '/Users/satya.kotipalli/Downloads/golang.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT: could not find @type 'type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config'): {"static_resources":{"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"route_config":{"name":"route_0","virtual_hosts":[{"name":"service_0","domains":["*"],"routes":[{"match":{"prefix":"/"},"route":{"cluster":"cluster_0"}}]}]},"@type":"type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager","http_filters":[{"name":"envoy.filters.http.golang","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config","plugin_name":"my_plugin","library_path":"lib/my_plugin.so","library_id":"my-plugin-id"}},{"typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config"},"name":"envoy.filters.http.header_to_metadata"},{"typed_config":{"library_id":"my-other-plugin-id","@type":"type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config","library_path":"lib/my_other_plugin.so","plugin_name":"my_other_plugin"},"name":"envoy.filters.http.golang"},{"name":"envoy.filters.http.router","typed_config":{"@type":"type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"}}],"codec_type":"AUTO","stat_prefix":"ingress_http"},"name":"envoy.filters.network.http_connection_manager"}]}],"address":{"socket_address":{"address":"0.0.0.0","port_value":8080,"protocol":"TCP"}},"name":"listener_0"}],"clusters":[{"type":"LOGICAL_DNS","name":"cluster_0","dns_lookup_family":"V4_ONLY","lb_policy":"ROUND_ROBIN","load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":80,"address":"service.local"}}}}]}
```

[optional *Relevant Links*:]
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              library_id: my-plugin-id
              library_path: "lib/my_plugin.so"
              plugin_name: my_plugin
          - name: envoy.filters.http.header_to_metadata
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
          - name: envoy.filters.http.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              library_id: my-other-plugin-id
              library_path: "lib/my_other_plugin.so"
              plugin_name: my_other_plugin
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: route_0
            virtual_hosts:
            - name: service_0
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: cluster_0

  clusters:
  - name: cluster_0
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service.local
                port_value: 80

```
