### ISSUE TITLE
Use type URL for cluster factories

### ISSUE THREAD

**Issue by Stevenjin8** [envoyproxy/envoy#37144]
*Title*: *Use type URL for cluster factories*

*Description*:
> from #36353. We want to use type URL instead of names for cluster factories. That is refactor the following code

https://github.com/envoyproxy/envoy/blob/f918986198223bc707c01a230242ad136012e677/source/common/upstream/cluster_factory_impl.cc#L18-L66

This is somewhat complex some cluster types (original dst, static), don't have type URLs, so we're probably going to need to create placeholder protos for them.

There is also a question for how much backcompatibility we want to preserve. For example, the following cluster is valid,

```yaml
cluster_type:
  name: envoy.cluster.original_dst # or static
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.network.dns.v3.GetAddrInfo  # or anything else, but not empty
```

This means that if we want to be strict about backcompatibility, **we will never be able to select cluster factories purely by type_url**. However, I'd be pretty surprised if anybody is using a config like the one above, since it doesn't make a lot of sense.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
