### ISSUE TITLE
Support runtime_fraction in the external processing filter 

### ISSUE THREAD

**Issue by hochuenw-dd** [envoyproxy/envoy#37326]
Similar to the runtime_fraction config in the request_mirror_policies, it'd be nice if we can send only x% of the traffic to the external processing filter. 
```
                - name: envoy.filters.http.ext_proc
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                    runtime_fraction:
                      default_value:
                      numerator: 1
                    failure_mode_allow: ...
                    observability_mode: ...
                    processing_mode: ...
                    grpc_service: ...
```

As a workaround, currently it seems we have to duplicate the virtual host/match to achieve this.

```
                    - match:
                        prefix: "/"
                        runtime_fraction:
                          runtime_fraction:
                            default_value:
                              numerator: 1
                      route:
                        cluster: cluster1
                      typed_per_filter_config:
                        envoy.filters.http.ext_proc:
                          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                          disabled: false
                    - match:
                        prefix: "/"
                      route:
                        cluster: cluster1
                      typed_per_filter_config:
                        envoy.filters.http.ext_proc:
                          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExtProcPerRoute
                          disabled: true
```
