### ISSUE TITLE
ECDS complains TypedConfig: value is required 

### ISSUE THREAD

**Issue by ttc0419** [envoyproxy/envoy#37431]
I'm using the following config to receive descriptor from control plane dynamically:
```yaml
                  - name: grpc_json_transcoder
                    config_discovery:
                      type_urls:
                        - type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                      config_source:
                        api_config_source:
                          api_type: DELTA_GRPC
                          grpc_services:
                            - envoy_grpc:
                                cluster_name: control_plane
```

Control plane:
```go
tc := &grpc_json_transcoderv3.GrpcJsonTranscoder{
    Services:      services,
    DescriptorSet: &grpc_json_transcoderv3.GrpcJsonTranscoder_ProtoDescriptorBin{ProtoDescriptorBin: data},
}

var cfg *anypb.Any
cfg, err = anypb.New(tc)
if err != nil {
    return nil
}

snapshot, err := evcache.NewSnapshot(base64.RawURLEncoding.EncodeToString(bv), map[resource.Type][]types.Resource{
	resource.ExtensionConfigType: {&http_connection_managerv3.HttpFilter{
            Name:       "grpc_json_transcoder",
            ConfigType: &http_connection_managerv3.HttpFilter_TypedConfig{TypedConfig: cfg},
        }},
})
```

But envoy complained:
```
[2024-12-01 00:21:01.417][4220397][warning][config] [source/extensions/config_subscription/grpc/delta_subscription_state.cc:269] delta config for type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig rejected: Proto constraint validation failed (TypedExtensionConfigValidationError.TypedConfig: value is required): name: "grpc_json_transcoder"
```

What wrong with the setup?
