### ISSUE TITLE
Fine-tuning of happy eyeballs dns resolution

### ISSUE THREAD

**Issue by VladislavAtanasov95** [envoyproxy/envoy#37478]
*Title*: *Fine-tuning of happy eyeballs dns resolution*

*Description*:

With that configuration and clusterType "LOGICAL_DNS"

```
        caresDnsResolverConfig, err := anypb.New(&cares.CaresDnsResolverConfig{
		DnsResolverOptions: &configCoreV3.DnsResolverOptions{
			UseTcpForDnsLookups: true,
		},
	})
	if err != nil {
		log.Println("error converting to Any: %v\n", err)
	}
	dnsResolverConfig := &configCoreV3.TypedExtensionConfig{
		Name:        "envoy.network.dns_resolver.cares",
		TypedConfig: caresDnsResolverConfig,
	}

	return &clusterV3.Cluster{
		Name:                   clusterName,
		ConnectTimeout:         durationpb.New(time.Duration(connectTimeout) * time.Second),
		ClusterDiscoveryType:   &clusterV3.Cluster_Type{Type: clusterType},
		LoadAssignment:         BuildEndpoint(clusterName, host, port),
		DnsLookupFamily:        clusterV3.Cluster_ALL,
		CircuitBreakers:        circuitBreakers,
		TypedDnsResolverConfig: dnsResolverConfig,
	}
}
```

We are having issues to access a system that has both valid IPv6 and IPv4 addresses like www.google.com. We are trying to access it from a proxy that relies on Envoy and when source IP is V4 we are getting 
`upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: Network is unreachable|remote address:[2404:6800:4004:818::2004]:443`
and it it did not pick the IPv4 address. We have tried adding "UseTcpForDnsLookups" with no success. Could you help on that, how can we fine-tune happy eyeballs to pick IPv4 when source is IPv4 and to pick IPv6 when source is IPv6 in order to work for such dual-stack target systems?

**Comment by ggreenway** [comment]
cc @RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
Hm. I'm surprised. I would have expected that with `DnsLookupFamily` set to `ALL` that DNS would have returned both IPv4 and IPv6 addresses. Then the Happy Eyeballs code would make connection attempts for each address in the list until the a connection succeeded. Is that not what you're seeing? Do you have a log?

**Comment by VladislavAtanasov95** [comment]
We sometimes receive

< HTTP/1.1 503 Service Unavailable
< content-length: 231
< content-type: text/plain
< date: Thu, 21 Nov 2024 13:43:13 GMT
< upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: immediate connect error: Network is unreachable|remote address:[2404:6800:4004:818::2004]:443

When the client service only has IPv4 and we are trying to reach google.com through our envoy-based proxy, sometimes it picks ipv6, sometime ipv4 of the target url.

**Comment by VladislavAtanasov95** [comment]
The Cluster type is actually "STRICT_DNS", not "LOGICAL_DNS"(my mistake) when we sporadically receive the error. I ran an example with static envoy locally 
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 2000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager 
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: http
          route_config:
            name: search_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/abv"
                route:
                  cluster: abv
                  host_rewrite_literal: www.abv.bg
              - match:
                  prefix: "/"
                route:
                  cluster: google
                  host_rewrite_literal: www.google.com
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: google
    connect_timeout: 10s
    type: strict_dns
    dns_lookup_family: ALL
    load_assignment:
      cluster_name: google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.google.com
  - name: abv
    connect_timeout: 10s
    type: logical_dns
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    load_assignment:
      cluster_name: google
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.abv.bg
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.abv.bg
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15000
```

When I change it from STRICT_DNS to LOGICAL_DNS, requests to google are working stable every time, but when it is STRICT_DNS sometimes I receive 
`upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 61`
 Is that makes sense?
