### ISSUE TITLE
auth filter headers causing unauthorised memory access

### ISSUE THREAD

**Issue by michalholecek** [envoyproxy/envoy#3750]
When I add a http header to a request via ext_auth filter, and the header's key is longer than 15 characters, envoy turns it into something like this:
**headers recieved from ext_auth filter printed via lua filter:**
```
:authority	0.0.0.0:777
:path	/
:method	GET
user-agent	curl/7.52.1
accept	*/*
x-forwarded-proto	http
x-request-id	2c6274e9-680d-4c86-af87-2b8fb609a7ec
x	1
xx	2
xxx	3
xxxx	4
xxxxx	5
xxxxxx	6
xxxxxxx	7
xxxxxxxx	8
xxxxxxxxx	9
xxxxxxxxxx	10
xxxxxxxxxxx	11
xxxxxxxxxxxx	12
xxxxxxxxxxxxx	13
xxxxxxxxxxxxxx	14
xxxxxxxxxxxxxxx	15
xxxxxxxxxxxxxxxx	16
xxxxxxxxxxxxxxxxx	17
xxxxxxxxxxxxxxxxxx	18
xxxxxxxxxxxxxxxxxxx	19
xxxxxxxxxxxxxxxxxxxx	20
xxxxxxxxxxxxxxxxxxxxx	21
xxxxxxxxxxxxxxxxxxxxxx	22
xxxxxxxxxxxxxxxxxxxxxxx	23
xxxxxxxxxxxxxxxxxxxxxxxx	24
xxxxxxxxxxxxxxxxxxxxxxxxx	25
date	Thu, 28 Jun 2018 17:44:29 GMT
x-envoy-upstream-service-time	0
```
**headers received by cluster in the envoy route:** (nginx server, receiving requests from envoy)
```
GET / HTTP/1.1
host: 0.0.0.0:777
user-agent: curl/7.52.1
accept: */*
x-forwarded-proto: http
x-request-id: 2c6274e9-680d-4c86-af87-2b8fb609a7ec
x: 1
xx: 2
xxx: 3
xxxx: 4
xxxxx: 5
xxxxxx: 6
xxxxxxx: 7
xxxxxxxx: 8
xxxxxxxxx: 9
xxxxxxxxxx: 10
xxxxxxxxxxx: 11
xxxxxxxxxxxx: 12
xxxxxxxxxxxxx: 13
xxxxxxxxxxxxxx: 14
xxxxxxxxxxxxxxx: 15
�[vxxxxxxxx: 16
�Kvxxxxxxxxx: 17
�vxxxxxxxxxx: 18
`Kvxxxxxxxxxxx: 19
�vxxxxxxxxxxxx: 20
�Kvxxxxxxxxxxxxx: 21
�
 vxxxxxxxxxxxxxx: 22
Hvxxxxxxxxxxxxxxx: 23

vxxxxxxxxxxxxxxxx: 24
x
�x
���tx: 25
date: Thu, 28 Jun 2018 17:44:29 GMT
x-envoy-upstream-service-time: 0
x-envoy-expected-rq-timeout-ms: 15000
content-length: 0
```

and when the headers key is e.g. "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" (key: 47*x), envoy replaces it with this: "cluster.web.upstream_cx_connect_ms"

I can provide more info if you want to. I am using an external auth service written in Golang, communicating via http.

**Comment by mattklein123** [comment]
@gsagula

**Comment by gsagula** [comment]
@michalholecek Let me take a look at this issue and I get back to you.

**Comment by gsagula** [comment]
@michalholecek It seems to work perfectly fine for me. I could be missing something but here is:

1. Client calls `curl -v localhost:8000`:

2. HTTP server sends the following headers to EXT_AUTHZ filter:
```
Xxxxx: 5 char header
Xxxxxxxxxxxxxxxxxxxx: 20 char header
Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 40 char header
```
3. The filter dispatches the following request to an upstream HTTP echo server:
```
GET / HTTP/1.1
Host: localhost:8000
Accept: */*
Content-Length: 0
Date: Fri, 29 Jun 2018 03:16:23 GMT
User-Agent: curl/7.58.0
X-Envoy-Expected-Rq-Timeout-Ms: 15000
X-Envoy-Upstream-Service-Time: 0
X-Forwarded-Proto: http
X-Request-Id: a26e2fdc-4060-41ec-b395-185f184daecb
Xxxxx: 5 char header
Xxxxxxxxxxxxxxxxxxxx: 20 char header
Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 40 char header
```

4. The downstream client receives the following response:
```
< HTTP/1.1 200 OK
< access-control-allow-headers: Content-Range, Content-Disposition, Content-Type, ETag
< access-control-allow-origin: *
< date: Fri, 29 Jun 2018 03:16:23 GMT
< content-length: 383
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 0
< server: envoy
<
GET / HTTP/1.1
Host: localhost:8000
User-Agent: curl/7.58.0
Accept: */*
Date: Fri, 29 Jun 2018 03:16:23 GMT
X-Envoy-Expected-Rq-Timeout-Ms: 15000
X-Envoy-Upstream-Service-Time: 0
X-Forwarded-Proto: http
X-Request-Id: a26e2fdc-4060-41ec-b395-185f184daecb
Xxxxx: 5 char header
Xxxxxxxxxxxxxxxxxxxx: 20 char header
Xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: 40 char header
```

Envoy config:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: echo
                  
          http_filters:
          - name: envoy.ext_authz
            config:
              http_service:
                server_uri:
                  uri: "127.0.0.1:9000"
                  cluster: "ext_authz"
                  timeout: 0.25s
              failure_mode_allow: false
          - name: envoy.router
            config: {}

  clusters:
  - name: ext_authz
    connect_timeout: 0.25s
    type: logical_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9000
  
  - name: echo
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 3333

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

Could please provide more information or the exact steps to reproduce it? 
Thanks!
