### ISSUE TITLE
Unable to use DNS and resolver_name in DogStatsdSink

### ISSUE THREAD

**Issue by akashjain971** [envoyproxy/envoy#37519]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Unable to set DNS address while configuring DogStatsdSink*

*Description*:

I am trying to configure a DogStatsdSink as metrics sink to send metrics to Telegraf which is running in the same namespace as envoy.
As per the docs, the address has to be an IP address. If it has to be a DNS, then a resolver must be set. I am not able to understand what to set here. The documentation is unclear and could not find an example anywhere.

Envoy errors with DNS address without setting the resolver name.

```
│ 2024-12-05T13:49:43.374404Z    critical    envoy main external/envoy/source/server/server.cc:133    error initializing config '  etc/istio/proxy/envoy-rev.json': malformed IP address: telegraf-service.services-gateway-apigw-usw2-prf-jain.svc.cluster.local.    thread=28                                                                                                                                                                                                                 
```

Envoy Config
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter
spec:
  workloadSelector:
    labels:
      app: istio-gateway
  configPatches:
    - applyTo: BOOTSTRAP
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          stats_flush_interval: 30s
          stats_sinks:
          - name: envoy.stat_sinks.dog_statsd
            typed_config:
              "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
              address:
                socket_address:
                  protocol: UDP
                  address: telegraf-service.default.svc.cluster.local
                  port_value: 6999
                  resolver_name: ???
```

Telegraf Config
```
[agent]
  debug = true
  quiet = false
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
[[inputs.statsd]]
  protocol = "udp"
  service_address = ":8125"
  datadog_extensions = true
  datadog_distributions = true
  datadog_keep_container_tag = true
```

[optional *Relevant Links*:]

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#extension-envoy-stat-sinks-dog-statsd
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/statsd/README.md

**Comment by ggreenway** [comment]
cc @taiki45 @jmarantz

**Comment by taiki45** [comment]
Thank you for bringing this up. I’ll try to provide some clarification, though my response may not fully reflect the latest updates in the project.

The statsd_sink and dog_statsd_sink extensions do not support DNS resolution over UDP. For UDP-based configurations, the address field must specify a logical or physical IP address. More details can be found in here: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-address

If DNS resolution is required, you can use statsd_sink with the tcp_cluster_name field, which allows for DNS-based resolution for TCP connections. Unfortunately, dog_statsd_sink does not support tcp_cluster_name, so enabling DNS resolution for dog_statsd_sink would require additional implementation.

For context, the current implementation assumes a common use case where metrics are sent to a local statsd daemon. In such scenarios, specifying a physical IP address for UDP communication is sufficient and aligns with the intended design. If this approach fits your architecture, it might be a simpler alternative to consider.

**Comment by akashjain971** [comment]
The problem with stasd sink is, it does not support tags and Telegraf errors when parsing Istio metrics from statsd sink because of additional colons in the `source_principal` and `destination_principal`. Also, stats config does not work with statsd so I cannot even drop this tags to solve this. 

```
telegraf-576cc6bddb-wnfnj telegraf 2024-12-09T15:47:55Z E! [inputs.statsd] Splitting '|', unable to parse metric
```

Dogstatsd sink works perfectly with Telegraf but it does not support TCP or DNS.

**Comment by akhilsingh-git** [comment]
When configuring DogStatsdSink, Envoy requires that UDP addresses be specified either as numeric IPs or accompanied by a DNS resolver configuration. By default, Envoy will not do DNS resolution for UDP endpoints just by providing a DNS name. If you specify a DNS hostname, you must also define and reference a DNS resolver extension in the bootstrap configuration, then reference it by resolver_name in the socket address.

Why Is This Necessary?
The resolver_name field in Envoy’s address configuration points to a named DNS resolver extension. Without a configured resolver, Envoy treats UDP addresses as literal IPs. If you provide a DNS name without a resolver, Envoy can’t resolve it and will produce an error like malformed IP address: <hostname>.

What resolver_name Should Contain
resolver_name must match the name of a DNS resolver extension that you have configured in the Envoy bootstrap. Envoy comes with built-in DNS resolvers such as envoy.network.dns_resolver.cares or envoy.network.dns_resolver.apple (on macOS). You must explicitly configure one of these in your bootstrap (not via an EnvoyFilter) so that Envoy knows how to resolve the provided hostname.

Example Bootstrap Configuration
Suppose you want to use the c-ares DNS resolver. In your Envoy bootstrap configuration (the main config file loaded on startup), you might specify something like:

# Partial example of bootstrap config
static_resources:
  # Your existing clusters, listeners, etc.

# Configure the DNS resolver extension.
typed_dns_resolver_config:
  name: envoy.network.dns_resolver.cares
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
    resolvers:
      # Typically the cluster DNS IP (e.g., from within K8s this might be the cluster DNS IP)
      - 10.0.0.10
    # Optional: other c-ares configurations

This configuration tells Envoy to use the c-ares DNS resolver with the given resolvers. The name field here matches what you’ll use in the resolver_name in your EnvoyFilter.

Using the Resolver in the EnvoyFilter
Once the bootstrap has the DNS resolver defined, you can reference it in your EnvoyFilter:

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: stats-filter
spec:
  workloadSelector:
    labels:
      app: istio-gateway
  configPatches:
    - applyTo: BOOTSTRAP
      match:
        context: GATEWAY
      patch:
        operation: MERGE
        value:
          stats_flush_interval: 30s
          stats_sinks:
          - name: envoy.stat_sinks.dog_statsd
            typed_config:
              "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
              address:
                socket_address:
                  protocol: UDP
                  address: telegraf-service.default.svc.cluster.local
                  port_value: 6999
                  resolver_name: envoy.network.dns_resolver.cares

Important Notes:
	1.	Bootstrap Is Required:
You cannot add DNS resolver configurations solely via EnvoyFilter. DNS resolvers must be set in the main Envoy bootstrap configuration which Istio’s sidecar is using. Adjusting that may require a custom sidecar proxy configuration or a custom bootstrap template.
	2.	Cannot Use Clusters for DogStatsdSink:
The DogStatsdSink does not support referencing a cluster name like some other sinks do. If it did, you could rely on Envoy’s cluster-level DNS resolution. Since it doesn’t, you must define a resolver as shown.
	3.	No TCP or Cluster Option for DogStatsd:
DogStatsd is inherently UDP-based. If you require DNS or dynamic resolution, the resolver approach is the only way. Using a static IP address is simpler if you can ensure a stable IP for your Telegraf instance.

**Comment by JeremyHub-DV** [comment]
a pretty awful workaround is to route the stats sink traffic to localhost and then have a udp_proxy forward that to where you need to send it, eg:

```
stats_sinks:
  - name: envoy.stat_sinks.dog_statsd
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8125
      prefix: envoy
static_resources:
  listeners:
    - name: dogstatsd_forwarder
      address:
        socket_address:
          protocol: UDP
          address: 127.0.0.1
          port_value: 8125
      listener_filters:
        - name: envoy.filters.udp_listener.udp_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
            stat_prefix: dogstatsd_forward
            cluster: dogstatsd_svc
  clusters:
    - name: dogstatsd_svc
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: dogstatsd_svc
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: dogstatsd.ops.svc.cluster.local
                      port_value: 8125
```
