### ISSUE TITLE
local_replay_config RESPONSE_CODE is override before body_format

### ISSUE THREAD

**Issue by juanmolle** [envoyproxy/envoy#37577]
Description:

local_replay_config allows to change response code, body and other local replay parameters
unfortunately using the RESPONSE_CODE in the body will use the override value, the original response value is not present anymore.

```
        local_reply_config:
            mappers:
            - filter:
                status_code_filter:
                  comparison:
                   op: EQ
                   value:
                     default_value: 400
                     runtime_key: "%RESPONSE_CODE%"
              status_code: 500
              body_format_override:
                text_format: "Original code: %RESPONSE_CODE%"
```

In this example the body will be:
```
Original code: 500
```
instead of
```
Original code: 400
```

Present in version 1.33

**Comment by juanmolle** [comment]
Some thing I could see is the body is replace after headers update, but headers to add is evaluated before, the looks inconsistent here the example

```
local_reply_config:
            mappers:
            - filter:
                status_code_filter:
                  comparison:
                   op: EQ
                   value:
                     default_value: 400
                     runtime_key: unexistant
              headers_to_add:
                - header:
                    key: "x-foo"
                    value: "%RESPONSE_CODE%"
                  append: false
              status_code: 500
              body_format_override:
                text_format: "Original code: %RESPONSE_CODE% from header %RESP(x-foo)%"
```

In this example the body will be:
```
Original code: 500 from header 400
```

instead of

```
Original code: 400 from header 400
```
