### ISSUE TITLE
connection_pool_per_downstream_connection - close upstream connection when downstream closes

### ISSUE THREAD

**Issue by Pawan-Bishnoi** [envoyproxy/envoy#37617]
*Title*: Close upstream connection soon after downstream connection is closed.

*Description*:
Enabling connection_pool_per_downstream_connection increases the number of open connections on the server app side (which is expected).
What is worrisome though is that these connections remain open for much longer than needed and are closed by idleTimeout (which takes atleast 8 minutes? Even if tcp keepalive time it set really small)

In case of connection_pool_per_downstream_connection, we don't have to wait for idleTimeout once the downstream is disconnected since the mapping is 1:1.

**Comment by Pawan-Bishnoi** [comment]
I read somewhere (unable to find the doc now) that the 8 minute number is coming from this calculation:
1. keepalive_probes - 7 is the default value
2. keepalive_interval - 75 seconds
3. keepalive_time -  tried setting it to 1 second. This is the only configurable value?

keepalive_time + keepalive_probes * keepalive_interval = 526 seconds → 8.77 minutes

**Comment by wbpcode** [comment]
I think this logic may could be optimized. But I cannot think of anyone have related experience. Will mark this as help wanted first.

**Comment by wbpcode** [comment]
Wait a minute, cannot the `idle_timeout` (in the upstream cluster configuration) helps?

**Comment by Pawan-Bishnoi** [comment]
oh, I see. The other two fields are also configurable. Trying this, will update:

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
..
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: "inbound_cluster_name"
    patch:
      operation: MERGE
      value:
        "upstream_connection_options":
         "tcp_keepalive":
          "keepalive_time": 30
          "keepalive_probes": 2
          "keepalive_interval": 50
```


Btw the connections are always supposed to be 1:1, right? Or can the upstream _pool_ have more than one connection for any given downstream connection?
