### ISSUE TITLE
After recreateStream, there is a risk of crash because the filter continue was not interrupted.

### ISSUE THREAD

**Issue by johnlanni** [envoyproxy/envoy#37625]
*Description*:

Here is an example. I apologize for not being able to provide a `custom_xxx` filter (which we implemented internally) that could reproduce the issue, but I can confirm that the filter contains a common logic: returning `stopIteration` at the `encodeHeader` stage, and then processing the buffer's body and returning `continue` at the `encodeData` stage.

```yaml
                   http_filters:
                   - name: envoy.filters.http.custom_response
                     typed_config:
                       "@type": type.googleapis.com/envoy.extensions.filters.http.custom_response.v3.CustomResponse
                        value:
                          custom_response_matcher:
                            matcher_list:
                              matchers:
                              - predicate:
                                  or_matcher:
                                    predicate:
                                    - single_predicate:
                                        input:
                                          name: "4xx_response"
                                          typed_config:
                                            "@type": type.googleapis.com/envoy.type.matcher.v3.HttpResponseStatusCodeClassMatchInput
                                        value_match:
                                          exact: "4xx"
                                    - single_predicate:
                                        input:
                                          name: "5xx_response"
                                          typed_config:
                                            "@type": type.googleapis.com/envoy.type.matcher.v3.HttpResponseStatusCodeClassMatchInput
                                        value_match:
                                          exact: "5xx"
                                 on_match:
                                   action:
                                     name: action
                                     typed_config:
                                       "@type": type.googleapis.com/envoy.extensions.http.custom_response.redirect_policy.v3.RedirectPolicy
                                       status_code: 299
                                       uri: "https://foo.example/gateway_error"
                                       response_headers_to_add:
                                       - header:
                                         key: "foo2"
                                         value: "x-bar2"
                   - name: envoy.filters.http.custom_xxx_filter
                     typed_config:
                       "@type": type.googleapis.com/envoy.extensions.filters.http.custom_xxx.v3.custom_xxx                
                   - name: envoy.filters.http.router
                     typed_config:
                       "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
Because the `custom_xxx` filter returned `stopIteration` during the `encodeHeader` phase, after returning `continue` in the `encodeData` phase, it will enter [commonContinue](https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/filter_manager.cc#L52) for processing, and then continue to execute the `encodeHeader` of the `custom_response` filter. Note that here, the `recreateStream` of `RedirectPolicy` was triggered:

https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/filter_manager.cc#L94

Since the `encodeHeader` of the `custom_response` filter also returned `stopIteration`, after returning `continue` in the `encodeData` phase, it will again enter [commonContinue](https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/filter_manager.cc#L52) for processing, and ultimately call into here:

1. FilterManager::encodeHeaders https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/filter_manager.cc#L1306
2. ConnectionManagerImpl::ActiveStream::encodeHeaders
https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/conn_manager_impl.cc#L1914

However, here the `response_encoder_` is a nullptr because it has already been moved to a new stream during the `recreateStream`:

https://github.com/envoyproxy/envoy/blob/602a2b97a54435c38cb5bacf133b9984d2212498/source/common/http/conn_manager_impl.cc#L2214-L2231

*Call Stack*:

![image](https://github.com/user-attachments/assets/03179b6f-4ee2-4786-ae2c-0ffab78c5a53)
