### ISSUE TITLE
Route request based on JWT claims

### ISSUE THREAD

**Issue by atali** [envoyproxy/envoy#3763]
*Title*: *I would like to route a request containing a jwt header to a dedicated tenant micro-service based on a claim.*

*Description*:
Once my client is authenticated, he will receive a JWT with some claims. I have a micro-service A that will receive this query and dispatch the query to a micro-service B. There is a micro-service B per tenant. I would like the query to be routed seamlessly to the micro-service B specific to a tenant, the routing will be based on a jwt claim.

You already have the same request on this [thread](https://groups.google.com/forum/#!topic/istio-users/zKyWBkhlJps)

I like the proposition from @galo

```
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: meme-lz
spec:
  destination:   
    name: meme
  precedence: 2
  match:
    request:
      headers:
        jwt_auth.country_code:
          regex: "^(.*?;)?(fr)(;.*)?$"  
  - destination:
      service: meme-france
```

I think nginx already managed that [here](https://www.nginx.com/blog/authentication-content-based-routing-jwts-nginx-plus/)
