### ISSUE TITLE
Debugging 503s

### ISSUE THREAD

**Issue by dnivra26** [envoyproxy/envoy#3771]
*Title*: *Debugging 503s*

*Description*:
We have a service which is returning 503s for like 1% of the total traffic.
This target service has a replication of 100 and the calling service has a replication of 50.
We have updated the circuit_breaking configuration as below

```
circuit_breakers:
             thresholds:
              -
               priority: DEFAULT
               max_connections: 10000
               max_pending_requests: 10000
               max_requests: 10000
               max_retries: 3

```
The traffic would be around 10,000 requests/second.
And the latency is around 200ms. So i guess this configuration is sufficient enough to handle this traffic.

From the stats,
there is no upstream_rq_pending_overflow.
We have upstream_rq_pending_failure_eject and upstream_cx_connect_timeout.
I can understand upstream_cx_connect_timeout and we have a connection timeout of 0.25s.
But what could be the other reasons for upstream_rq_pending_failure_eject?
Also any suggestions to debug this 503 issues would be really helpful.
