### ISSUE TITLE
Zipkin Custom Headers

### ISSUE THREAD

**Issue by keitwb** [envoyproxy/envoy#3772]
I have Envoy configured to send traces via the builtin Zipkin tracer, but my Zipkin instance is in front of a (non-envoy) reverse-proxy that requires an authentication token to provide some measure of protection to Zipkin.

I have created the following config based on the basic google.com proxy example that opens up a local listener (pointed to by cluster `zipkin_inbound`) that zipkin is configured to send to in order to get the header added, before forwarding it to the `zipkin_outbound` cluster where it goes to the real zipkin server.

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
.....
  - name: trace_0
    address:
      socket_address: { address: 127.0.0.1, port_value: 19876 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: zipkin_http
          route_config:
            name: local_route
            request_headers_to_add:
              - header: {key: MY-AUTH-HEADER, value: MY-AUTH-TOKEN}
            virtual_hosts:
            - name: local_service
              domains: ["zipkin_inbound"]
              routes:
              - match: { path: "/api/v1/spans" }
                route: { host_rewrite: 'my.real.zipkin.server', cluster: zipkin_outbound }
          http_filters:
          - name: envoy.router

  clusters:
.....
  - name: zipkin_inbound
    connect_timeout: 1s
    type: static
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 19876

  - name: zipkin_outbound
    connect_timeout: 2s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: my.real.zipkin.server
        port_value: 9411
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: zipkin_inbound
      collector_endpoint: "/api/v1/spans"
```

This works but I was wondering if there was a less roundabout way of doing this?  I am willing to contribute config options to add arbitrary headers under the `tracing.http.[name=envoy.zipkin]` section if that is the better way to go about this.
