### ISSUE TITLE
invalid format of uuid generated for the x-request-id

### ISSUE THREAD

**Issue by xr** [envoyproxy/envoy#37758]
*Description*:
Envoy generates wrong format of uuid for `x-request-id` when enable `generate_request_id`.
The doc said it should generate random UUID4 but seems not.

*Repro steps*:
1. enable the request_id generation
```
name: "envoy.filters.network.http_connection_manager"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
            generate_request_id: true
```

2. send any request, it will generate uuid like: `ca480f47-005c-99b7-9ea0-38674649d65b`

*validation*
- online validator: https://tools.namlabs.com/uuid-validation/, it said "invalid"
- other online validator like: https://cloud.magiclen.org/us/uuid/checker it said:
```
UUID: ca480f47-005c-99b7-9ea0-38674649d65b

Version: 9

Variant: RFC4122
```
- using validator lib like https://www.npmjs.com/package/uuid#uuidvalidatestr it said invalid.
