### ISSUE TITLE
DogStatsdSink lowers performance at higher CPU + concurrency

### ISSUE THREAD

**Issue by DukeyToo** [envoyproxy/envoy#37831]
*Title*: *DogStatsdSink lowers performance at higher CPU + concurrency*

*Description*:
>We have scaled up some Envoy edge instances (added more CPU + increased concurrency), and noticed that these new, larger 16-32 core Envoy instances did not perform as well as expected. Specifically, latency increased well before reaching high CPU usage, and we saw more watchdog misses on the main thread. After a lot of investigation, we found that removing the DogStatsdSink fixed the problem for us.

*Repro steps*:
> Run an envoy instance with 16 cores and 16 concurrency. Include DogStatsdSink. It is not necessary to have a real destination, since it uses UDP and will not affect anything if the destination is not real. Run enough load to the instance that it should get above 60% mean cpu. Note how response times are poor, and CPU higher, compared to the same test without configuring DogStatsdSink. (You can maybe reproduce with less cores/concurrency, but this is what we used in our tests).

*Admin and Stats Output*:
> I don't have a sanitized stats to share

*Config*:

```yaml
stats_sinks:
  - name: envoy.stat_sinks.dog_statsd
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
      address:
        socket_address:
          address: $STATSD_SERVICE_IP
          port_value: 8125
      prefix: envoy
```

*Logs*:
>No relevant logs

*Metrics*:

Each of the below panels are from the same 2 perf runs, the first with the DogStatsdSink included, and the **second without**.  There were no other changes between the 2 tests/runs. This was also reproduced multiple times on different days. The perf test:
- runs http1.1 requests against Envoy listener on port 443, routing based on host header
- Envoy itself autoscales out at 40% cpu, from an initial 3 instances, using k8s HPA
- lbtester-child is the name of one of the backend/upstream workloads. It is part of our standard suite we use for testing load balancer behavior, and its performance is well-known and predictable
- lbtester-child was configured to respond to GET queries in 10ms. Any latency above that is generally attributable elsewhere

> The first perf run (left side) shows the problem behavior, and the second one (right side) shows what we consider to be normal, well-performing behavior

![cdc1431a-0969-47a8-9550-40b83c4ccb39](https://github.com/user-attachments/assets/fdcb21d5-ed7c-487d-aa33-86b441a36ff0)

The above panel shows mean latency as measured by the app (yellow line, opentelemetry histogram metric) and at the load balancer (green line, also an opentelemetry histogram metric). Note the green line jumps significantly in the first perf test, representing latency that Envoy is adding. (This is the mean, so even a small bump represents a significant change). In the second perf test, there is a smaller bump. This bump is more "normal" - we expect some small loss of performance when scaling out under increasing perf loads. In both cases, the yellow line (self-reported upstream cluster latency) is stable, even dropping in the beginning as it warms up.

This next panel shows the Envoy TPS (rate derived from `http.downstream_rq_http1_total` counter) during the 2 tests:
![4fe14e18-4356-46b0-9e21-6898bcd9eac3](https://github.com/user-attachments/assets/d8a49a1f-731b-43e9-a2a6-d992e2024b63)

The pattern is significantly different in the 2 tests. In test 1, Envoy reaches a max of around 16K ops per instance. As autoscaling happens, the overall rate drops to a steady state of around 10K ops per instance. In test 2, the first instances get all the way up to 27K ops per instance, before dropping to a steady state of about 16K ops per instance (i.e. steady state in test 2 was the same as the peak in test 1). Also, the final instance count for Envoy was 12 in test 1, and 8 in test 2, i.e. test 1 used 50% more envoy instances to support the same traffic.

In summary, we were able to reproduce performance we saw in prod with an artificial performance test, but only when configuring the DogStatsdSink sink. Thus we concluded that the source of the performance problems is something in the DogStatsdSink. We don't observe the same issues when using Prometheus scraping, or the OpenTelemetry sink.

**Comment by DukeyToo** [comment]
Some additional info...

<details>
<summary>Full Envoy config yaml used during testing incl DogStatsdSink </summary>

(there is some envsubst done beforehand to set variables)

```yaml
node:
  id: allnodes
  cluster: $NODE_CLUSTER
admin:
  access_log:
    name: envoy.access_loggers.file
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
      path: /dev/null
  address:
    socket_address: { "address": "0.0.0.0", "port_value": 9090 }
dynamic_resources:
  lds_config:
    resource_api_version: V3
    api_config_source:
      api_type: DELTA_GRPC
      transport_api_version: V3
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
  cds_config:
    resource_api_version: V3
    api_config_source:
      api_type: DELTA_GRPC
      transport_api_version: V3
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster
static_resources:
  clusters:
  - name: xds_cluster
    alt_stat_name: cluster=envoy-xds;server_group=envoy-xds-v001;service=envoy-xds/envoy-xds-v001;application=envoy;
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    circuit_breakers:
      thresholds:
        - priority: high
          max_connections: 100000
          max_pending_requests: 100000
          max_requests: 60000000
          max_retries: 50
        - priority: default
          max_connections: 100000
          max_pending_requests: 100000
          max_requests: 60000000
          max_retries: 50
    upstream_connection_options:
      # https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/address.proto#envoy-api-msg-core-tcpkeepalive
      tcp_keepalive:
        keepalive_probes: 3
        keepalive_time: 30
        keepalive_interval: 5
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: $CONTROL_PLANE_IP
                port_value: 5678
  - name: logs
    alt_stat_name: cluster=envoy-logs;server_group=envoy-logs-v001;service=envoy-logs/envoy-logs-v001;application=envoy;
    connect_timeout: 5s
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: logs
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: $ALS_SERVER_IP
                port_value: 8080
               
watchdogs:
  main_thread_watchdog: 
    miss_timeout: 0.5s
    megamiss_timeout: 2s
  worker_watchdog:
    miss_timeout: 0.05s
    megamiss_timeout: 0.5s

stats_sinks:
  - name: envoy.stat_sinks.open_telemetry
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.stat_sinks.open_telemetry.v3.SinkConfig
      grpc_service:
        google_grpc:
          target_uri: "127.0.0.1:4317"
          stat_prefix: envoy_grpc_otel
      report_counters_as_deltas: false
      report_histograms_as_deltas: true
      emit_tags_as_attributes: true
      use_tag_extracted_name: true
      prefix: envoy_otel
  - name: envoy.stat_sinks.dog_statsd
    typed_config:
      "@type": type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink
      address:
        socket_address:
          address: $STATSD_SERVICE_IP
          port_value: 8125
      prefix: envoy

stats_config:
  stats_tags:
    - tag_name: service
      regex: ^cluster\..*?(service=(.+?);).*$
    - tag_name: server_group
      regex: ^cluster\..*?(server_group=(.+?);).*$
    - tag_name: application
      regex: ^cluster\..*?(application=(.+?);).*$
    - tag_name: cluster
      regex: ^cluster\..*?(cluster=(.+?);).*
    - tag_name: host
      fixed_value: $POD_NAME
    - tag_name: lb_type
      fixed_value: envoy
    - tag_name: traffic_source
      fixed_value: $TRAFFIC_SOURCE
```

</details>

Envoy startup script looks like:

```shell
envoy -c /etc/envoy/config/envoy.yaml \
  --restart-epoch $RESTART_EPOCH \
  --concurrency $CONCURRENCY \
  --service-zone $zone \
  --service-cluster $NODE_CLUSTER \
  --service-node $NODE_ID
```
