### ISSUE TITLE
What's the recommended way to migrate header injection away from HTTP route configuration?

### ISSUE THREAD

**Issue by pascalpandey** [envoyproxy/envoy#37840]
*Title*: What's the recommended way to migrate header injection away from HTTP route configuration?

*Description*:
We are using Istio with K8S, currently to expose user defined deployments we use Istio VirtualServices which under the hood this maps one to one to Envoy's HTTP route configuration. These route configurations matches requests with url prefixes to inject headers to the request. 

```
route_config:
  "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration"
  name: "http.8443"
  virtual_hosts:
    - name: "inference-deployment"
      domains:
        - "example.com"
      routes:
        - match:
            prefix: "/inference/deployments/<some-deployment-id>"
          route:
            cluster: "inference-service"
            rewrite:
              substitution: "/"
          request_headers_to_add:
                - header:
                    key: "custom-header"
                    value: "example"
                  append_action: "OVERWRITE_IF_EXISTS_OR_ADD"
```

An incoming request will have the following path `/inference/deployments/<some-deployment-id>`. The proper route config will match the deployment-id and inject the correct headers for that deployment-id. 

To lessen the load to K8S etcd database, we want to move away from this setup. We will be removing Istio VirtualServices and, thus, route_configs from our ingress. We decided to use a Composite External Processing Filter to query another service which fetches the appropriate headers from an external database. Incoming requests on the ingress with `/inference/deployments/` path prefix gets sent to the external processor to get enriched with the appropriate headers. Because external processor doesn't do routing, we still keep one route_config matching the same prefix`/inference/deployments/` to route these requests to `inference-service` cluster. But at least now instead of having one route_config/VirtualService for each deployment, we have only one route_config/VirtualService for all deployments, lessening the load on etcd.

The issue arises because we have 2 types of user defined deployments, A and B. We want to keep the first one using HTTP Route Configuration, but the other one to rely on the external processor. There is no way to distinguish between type A and type B deployments, all requests come in with the same path `/inference/deployments/<some-deployment-id>`, they just get routed differently in the http_config, type A requests go to the specific `inference-service-A-<deployment-id>`while type B requests go to a single generic `inference-service-B`.

What would be a nice solution is this:
1. Remove all type B route_configs
2. Matched type A requests just follow the preexisting route_config
3. Unmatched requests means that they are of type B and will be sent to ext_proc and then routed to `infenerce-service-B`

The issue is that route_configs are read by http.router filter which must be the terminal filter in http_connection_manager. This means that all `/inference/deployments/<some-deployment-id>` requests must go through the external processor first. Our workaround is only storing type B deployments on the database, deployment-ids not found on the DB are type A by definition and the ext_proc does nothing to these requests. These type A requests then get its headers from its corresponding route_config. On the other hand, deployment-ids found on the DB, are type B and get enriched with appropriate headers and an extra internal only header `deployment-type: B`. Then a route_config matching to a generic `/inference/deployments/` path with `deployment-type: B` internal header routes the request to the generic `inference-service-B`.

Is this the acceptable approach of doing this, or is there some method which is easier to do and aligns better with Envoy's principles? In the end, we just want to move away from Istio VirtualServices, which means moving away from http.route_configs, if any other method exists, please share.

Thank you!

**Comment by ravenblackx** [comment]
> The issue is that route_configs are read by http.router filter which must be the terminal filter in http_connection_manager. This means that all /inference/deployments/<some-deployment-id> requests must go through the external processor first.

I think you could configure the `ext_proc` filter as an [upstream filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions), which would place it after the `http.router` filter, if that would help. (It [says](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions) it's compatible with `http.upstream`.)

@yanavlasov or @gbrail might have a better handle on this, as `ext_proc` codeowners.

**Comment by pascalpandey** [comment]
@ravenblackx Worked wonderfully. Thank you so much!

**Comment by pascalpandey** [comment]
Hi @ravenblackx, just curious, last time i managed to attach upstream filters (header_mutation and ext_proc) to http.router and it worked
```
name: envoy.filters.http.router
typed_config:
  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  upstream_http_filters:
    - name: ext-proc-test
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
        grpc_service:
          google_grpc:
            target_uri: ext-proc.namespace.svc.cluster.local:50051
            stat_prefix: ext_proc
          timeout: 10s
        processing_mode:
          request_header_mode: SEND
          response_header_mode: SKIP
          request_trailer_mode: SKIP
          response_trailer_mode: SKIP
    - name: header-mutation-test
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
        mutations:
          request_mutations:
            - append:
                header:
                  key: test
                  value: test
    - name: envoy.filters.http.upstream_codec
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
```
but when trying to attach the filters to a cluster through [envoy.upstreams.http.http_protocol_options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extension-envoy-upstreams-http-http-protocol-options) in [config.cluster.v3.Cluster.upstream_config](<https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#extension-category-envoy-upstreams:~:text=of%20track_cluster_stats.-,upstream_config,-(config.core>) neither the header mutation nor the ext_proc worked
```
cluster:
  "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: outbound|5000||service.namepsace.svc.cluster.local
  upstream_config:
    name: test-upstream-config
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      http_filters:
        - name: ext-proc-test
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
            grpc_service:
              google_grpc:
                target_uri: ext-proc.namespace.svc.cluster.local:50051
                stat_prefix: ext_proc
              timeout: 10s
            processing_mode:
              request_header_mode: SEND
              response_header_mode: SKIP
              request_trailer_mode: SKIP
              response_trailer_mode: SKIP
        - name: header-mutation-test
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
            mutations:
              request_mutations:
                - append:
                    header:
                      key: test
                      value: test
        - name: envoy.filters.http.upstream_codec
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
```
is this not the intended way of attaching filters to a cluster?
