### ISSUE TITLE
Resolve FQDN in domain of VirtualHost before matching a request.

### ISSUE THREAD

**Issue by Atish-iaf** [envoyproxy/envoy#37861]
*Description*:
We have fqdn as domain in virtualHost and want that domain (fqdn) to be resolved to IP address before matching a request. Request doesn't contain fqdn in header, it contains IP, so it is required that domain fqdn in virtualHost resolves to IP address first before matching.
Is there a way to achieve this?

**Comment by ravenblackx** [comment]
@yanavlasov or @adisuissa might know?

**Comment by adisuissa** [comment]
It is not clear to me how what should be done in this case.
Say the FQDN can be mapped to N IP addresses, how should the matching be done.
If possible, please add an explicit example of the desired config and desired behavior.

**Comment by Atish-iaf** [comment]
> It is not clear to me how what should be done in this case. Say the FQDN can be mapped to N IP addresses, how should the matching be done. If possible, please add an explicit example of the desired config and desired behavior.

Hi @adisuissa
Thanks for the response, here is my current config
```
virtual_hosts:
  - name: example-host
    domains:
      - "IP1:Port1"
      - "IP1:Port2"
      - "IP2:Port1"
      - "IP2:Port2"
    routes:
      - match:
          prefix: "/"
        route:
          cluster: example-cluster
``` 

I want to use FQDN instead of IP and before matching the request header, the provided FQDN should be resolved to IPs and then match "IP:Port" with request header.
If FQDN can be mapped to N IP addresses, all N IP addresses should be used in domains as any IP can be matched with request header.
Lets say FQDN1 maps to IP1 and IP2, then below config should result same as above provided config.
```
virtual_hosts:
  - name: example-host
    domains:
      - "FQDN1:Port1"
      - "FQDN1:Port2"
    routes:
      - match:
          prefix: "/"
        route:
          cluster: example-cluster
```
