### ISSUE TITLE
[Question] How to change the relative redirect location to absolute url?

### ISSUE THREAD

**Issue by instcode** [envoyproxy/envoy#37883]
*Title*: *How to change the relative redirect location to absolute url?*

*Description*:

I have an upstream server that responses a request with status code = 303 and a relative location such as: "/session/12345/status". Hence, when I use the following route config, the redirection failed with an error: "Internal redirect failed: invalid location...":
```
route:
    cluster: my_upstream
    auto_host_rewrite: true
    max_internal_redirects: 5
    internal_redirect_action: HANDLE_INTERNAL_REDIRECT
    internal_redirect_policy:
      max_internal_redirects: 5
      redirect_response_codes:
        - 303
```
Checking the document seems to require an absolute path for the location: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_connection_management#internal-redirects 

Is there any work around for this? Thank you.

**Comment by zuercher** [comment]
Per the docs, Envoy only supports fully qualified URLs at the moment. I've not looked closely, but It should be possible to implement a change to handle relative URLs.

**Comment by GnaneshK24** [comment]
Hi @instcode , i would like to contribute in this issue and this would be my first pr . I can find a workaround to solve this issue. Can u assign this for me??

**Comment by instcode** [comment]
@GnaneshK24  I have no authority to do that. You may ask the maintainers of this project instead.

BTW, I had a workaround in case anyone needs it. The idea is to add the http filters in the cluster section to change the "location" header from relative to absolute as in the cluster endpoint:
```
    name: puppycloud
    type: STRICT_DNS
    dns_refresh_rate: 30s
    lb_policy: ROUND_ROBIN
    load_assignment:
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: puppycloud.com
                port_value: 443
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        auto_config:
          http_protocol_options: {}
        http_filters:
          - name: envoy.filters.http.header_mutation
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_mutation.v3.HeaderMutation
              mutations:
                response_mutations:
                  append:
                    header:
                      key: "location"
                      value: "https://puppycloud.com%RESP(location)%"
                    append_action: OVERWRITE_IF_EXISTS
          - name: envoy.filters.http.upstream_codec
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
```
