### ISSUE TITLE
add regex match and substitute support to the header mutation

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#37885]
*Title*: *One line description*

*Description*:

Now, the header mutation (both the header mutation filter and `headers_to_add`) could set/add headers by the substitution formatter. (like `%REQ(xxxxx)%`. But it's impossible to extract more fine-grained part of one header or path. It would be great to
extract sub-value from a header or path by the regex and set the sub-value to a new header.

For example:

```
        header:
          key: "x-new-key-anyway"
          value: "%REQ(:PATH)%"
        rewrite:
           pattern:
             regex: "/prefix/proxy/(.+)"
           substitution: "\\1"
        append_action: APPEND_IF_EXISTS_OR_ADD

```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
