### ISSUE TITLE
Gaeger Tracing encounters "unknown-service-name"

### ISSUE THREAD

**Issue by DavadDi** [envoyproxy/envoy#3792]
## Gaeger Tracing encounters "unknown-service-name"

> $ envoy-static --version
> version: 56a047b5064bba8108ec31c2b6a1f94da1711c20/1.8.0-dev/Clean/DEBUG
>
> $ /usr/local/bin/envoy-static -c echo_envoy.yaml -l info

Data flow likes `curl -> envoy -> echo_service`.  

But Jaeger UI shows "unknown-service-name" for  the tracing record. **Do I  miss something in the envoy config** ?

![image](https://user-images.githubusercontent.com/7161135/42301159-7b6ec9d2-8046-11e8-955e-ef0253d7a5b2.png)

The full config for Envoy looks like this:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          generate_request_id: true
          tracing: 
            operation_name: egress
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: echo-service
                decorator:
                  operation: call-echo-service  # x-envoy-decorator-operation

          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: echo-service
    connect_timeout: 0.25s
    type: static # strict_dns
    lb_policy: round_robin
    # http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080
  - name: jaeger 
    connect_timeout: 1s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9411
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: jaeger
      collector_endpoint: "/api/v1/spans"

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001

```
