### ISSUE TITLE
log: omit_empty_values not works correctly for new json formatter

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#37941]
*Title*: *[One line description](log: omit_empty_values not works correctly for new json formatter)*

*Description*:

#35545 added new json formatter which provide much better performance than the legacy one by pre-serialize the json template when loading the configuration. 

But this also result in a behavior change. In the previous implementation, if the `omit_empty_values` is set to true explicitly, one key/value pair will be ignore in the finaly json output if the value is `null`.

But now, it will be kept.

For example, given following log formatter

```
json_format: 
  key: %REQ(header-key)%
```

If the `header-key` is not exist in the request headers,

in the previous implementation,  the final json output will be `{}`,

in the new implementation, the final json output will be `{"key":null}`

**Comment by fxposter** [comment]
In addition to that - it support not adding nested stuff if it's all empty:
```
log_format:
  omit_empty_values: true
  json_format:
    protocol: "%PROTOCOL%"
    duration: "%DURATION%"
    data:
      custom: "%REQ(MY_CUSTOM_HEADER)%"
```
will not include data at all if there is no MY_CUSTOM_HEADER
