### ISSUE TITLE
how to return different response code for different url or cluster in envoy

### ISSUE THREAD

**Issue by milocc** [envoyproxy/envoy#37996]
*Description*:
I have two clusters defined in envoy yaml, which are for two servers. They map to different url prefix. And they have their own health check logic. When the cluster is unhealthy, the requests will return error code 503. Now, I want envoy returns error code 501 for server2 when server2 is unhealthy. So user will receive 503 if server1 is unhealthy, and receive 501 if server2 is unhealthy.

```
- match:
    prefix: "/v1"
  route:
    cluster: server1
- match:
    prefix: "/v2"
  route:
    cluster: server2
```

I don't want do any changes to server2. I tried **local_reply_config** config, but it impacts both prefixes. Is there a way to get this ?

```
local_reply_config:
  mappers:
    - filter:
        status_code_filter:
          comparison:
            op: EQ
            value:
              default_value: 503
              runtime_key: key_b
      status_code: 501

**Comment by agrawroh** [comment]
You can try using CEL expressions via `extension_filter` [[Ref](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/access_loggers/filters/cel/v3/cel.proto#envoy-v3-api-msg-extensions-access-loggers-filters-cel-v3-expressionfilter)]

You basically will have to use both the `status_code_filter` and `extension_filter` like below. I haven't tried the config so you might have to adjust it but you get the idea.

```yaml
local_reply_config:
  mappers:
    - filter:
      and_filter:
        filters:
          - extension_filter:
              name: "envoy.filters.accesslog.cel"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.access_loggers.filters.cel.v3.ExpressionFilter"
                expression: "(request.path == '/v2')"
          - status_code_filter:
              comparison:
                op: EQ
                value:
                  default_value: 503
                  runtime_key: key_b
        status_code: 501
```

A full list of attributes is listed [here](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/advanced/attributes#arch-overview-attributes).
