### ISSUE TITLE
inactive subsets not being removed?

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#3803]
We are tracking down why our active subsets keep growing, without the unused ones being removed. Given the following subset load balancer config:

```
    "lb_subset_config": {
      "fallback_policy": "DEFAULT_SUBSET",
      "default_subset": {
        "default": "true"
      },
      "subset_selectors": [
        {
          "keys": [
            "default"
          ]
        },
        {
          "keys": [
            "version"
          ]
        },
        {
          "keys": [
            "canary"
          ]
        }
      ]
    }
```

and given that we never have more than 6 possible subsets at a given time:

```
default/true
version/v1
version/v2
version/v3
version/v4
canary/true
```

we end up seeing a higher count of active subsets than what we would expect:

```
$ curl -s localhost:9901/stats | grep subset | grep app
cluster.app.lb_subsets_active: 396
cluster.app.lb_subsets_created: 396
cluster.app.lb_subsets_fallback: 1171992
cluster.app.lb_subsets_removed: 0
cluster.app.lb_subsets_selected: 46201647
```

We run with a concurrency of 32, derived via `std::thread::hardware_concurrency()`. So if there is one load balancer per worker thread and subsets are created independently for each worker, at most we'd have 32 * 6 subsets (or 32*7, if there's a duplicate subset for the default subset).

Of course, versions keep changing but there are never more than 4 at the same time. It looks like the old ones are not being removed.

One important note is that our endpoints (e.g.: (ip, port)) remain constant, but their metadata changes (e.g.: the version). So our EDS service implementation might serve the following versions of its view of the world:

1st EDS snapshot:
```
---
endpoint:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 8888
metadata:
  filter_metadata:
    envoy.lb:
      version: '1.0'
      stage: 'prod'
```

2nd EDS snapshot (only the version changes):
```
---
endpoint:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 8888
metadata:
  filter_metadata:
    envoy.lb:
      version: '2.0'
      stage: 'prod'
```

I wrote a test case to see if the metadata is updated and it looks like it isn't: https://github.com/rgs1/envoy/commit/0fd3dd1194c1b203750a000f716828c3d24daa4b. I am not sure if this is by design and if using EDS in this way would be related to the subset load balancer leaking inactive subsets.

This could also be related to the fact that endpoints aren't immediately removed if their healthchecks are still passing, which maybe means the new metadata is ignored if there's never a removal for the previous version of an endpoint.

Thoughts?

cc: @zuercher

**Comment by rgs1** [comment]
@zuercher any ideas on why subsets might not get removed as endpoint metadata changes? This is causing the subset loadbalancer to work way harder — when the number of subsets gets big.

I am not unsure if this is because a) the way we implement EDS and publish metadata changes (without the IP/port tuple changing) or b) an actual bug in the Subset Loadbalancer...

**Comment by rgs1** [comment]
Ok, this doesn't look like a bug in the subset load balancer but in the way we use EDS. It looks like
EDS *won't* update the metadata for existing endpoints, e.g.:

1st EDS snapshot
```
---
endpoint:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 8888
metadata:
  filter_metadata:
    envoy.lb:
      version: '1.0'
      stage: 'prod'
```

2nd EDS snapshot (only the version changes):
```
---
endpoint:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 8888
metadata:
  filter_metadata:
    envoy.lb:
      version: '2.0'
      stage: 'prod'
```

... but version remains in 1.0, the metadata isn't updated. I am not sure if this is by
design though... is it?
