### ISSUE TITLE
Fine control over the request body compression in compression envoy filter

### ISSUE THREAD

**Issue by shaoxt** [envoyproxy/envoy#38097]
*Title*: Fine control over the request body compression in compression envoy filter

*Description*:
> Envoy has the compression feature on request body and also has the global feature flag.
   Request body compression requires the backend services to support decompression.  Otherwise the backend services will run into problems.
   The global feature flag doesn't enough to cover the following cases
   - Only a feature backend services or APIs supports the request body decompression
   - Only allow a portion of the requests to have request body compressed
  
  The above cases can not be covered by the global feature flag only.

Sample of the current global feature flag "enabled: false"
```
          http_filters:
          - name: envoy.filters.http.compressor
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
              request_direction_config:
                common_config:
                  enabled:
                    default_value: false
                    runtime_key: request_compressor_enabled
```

Even through the global feature flag was set to "false",  the compressor filter will check the request header
if the request header contains "X-Request-Compression: true",  the request body will be compressed.

This will give more fine control for the istio-proxy outbound traffic.
 
[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by shaoxt** [comment]
Here is the use case.
The envoy is used for the outbound request proxy to the backends.
Some backends can not handle the compressed request.
The current compression request direction config only has true/false applies to all backends

![Image](https://github.com/user-attachments/assets/0cc19702-a704-4ad1-b6ae-757c24da86b9)

**Comment by KBaichoo** [comment]
Thank you for the diagram @shaoxt! This was very useful for helping me understand your use case.

I think in this case you can already achieve this by selectively apply the compression filter based on that header by wrapping the compressor filter in the composite filter. https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/composite_filter.  

e.g. if `request_headers` "x-request-compression` has value `true` then enable the compressor filter. 

Can you try that approach first? Thank you.

**Comment by shaoxt** [comment]
Thanks for the recommendations.

The following settings works exact as same as the PR.  

Cool, thanks! Will close the PR and this issue.

```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  annotations:
  name: composite-filter
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_OUTBOUND
        listener:
          filterChain:
            filter:
              name: envoy.filters.network.http_connection_manager
              subFilter:
                name: envoy.filters.http.router
          portNumber: 80
      patch:
        operation: INSERT_BEFORE
        value:
          name: composite
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.common.matching.v3.ExtensionWithMatcher
            extension_config:
              name: composite
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.Composite
            xds_matcher:
              matcher_tree:
                input:
                  name: request-headers
                  typed_config:
                    "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                    header_name: X-Request-Compression
                exact_match_map:
                  map:
                    "true":  # Compression
                      action:
                        name: composite-action
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                          typed_config:
                            name: envoy.filters.http.compressor
                            typed_config:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                              compressor_library:
                                name: text_optimized
                                typed_config:
                                  '@type': type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                                  compression_level: COMPRESSION_LEVEL_4
                              request_direction_config:
                                common_config:
                                  enabled:
                                    default_value: true
                                    runtime_key: request_compressor_enabled
                    "false":  # No compression
                      action:
                        name: composite-action
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.composite.v3.ExecuteFilterAction
                          typed_config:
                            name: envoy.filters.http.compressor
                            typed_config:
                              "@type": type.googleapis.com/envoy.extensions.filters.http.compressor.v3.Compressor
                              compressor_library:
                                name: text_optimized
                                typed_config:
                                  '@type': type.googleapis.com/envoy.extensions.compression.gzip.compressor.v3.Gzip
                                  compression_level: COMPRESSION_LEVEL_4
                              request_direction_config:
                                common_config:
                                  enabled:
                                    default_value: false
                                    runtime_key: request_compressor_enabled
```
