### ISSUE TITLE
Admin Interface Port Reuse with Hot Reload

### ISSUE THREAD

**Issue by bspavan25** [envoyproxy/envoy#38146]
*Title*: Admin Interface Port Reuse with Hot Reload

*Description*:
I'm using the hot restart Python wrapper provided by Envoy (https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter) to run Envoy with a configuration that includes an admin interface. When I include the following admin interface configuration in my Envoy config:
```
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001
```
However, I encounter a "address already in use" error when trying to hot reload:
```
[2025-01-22 21:19:43.436][10832][critical][main] [source/server/server.cc:412] error initializing config '  bin/config.yaml': cannot bind '127.0.0.1:8001': Address already in use
```
However, when I add the following socket options to the admin interface configuration:
```
admin:
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001
  socket_options:
    - level: 1  # SOL_SOCKET
      name: 15  # SO_REUSEPORT
      int_value: 1
      state: STATE_PREBIND
```
The hot reload works as expected.

My understanding is that the admin interface runs on the main thread and does not allow port reuse by default. The added socket options enable port reuse, allowing the hot reload to work. I would like to confirm if this understanding is correct and if this approach is recommended. Are there any potential issues with using this socket option for the admin interface?

[Relevant Links:]
https://www.envoyproxy.io/docs/envoy/latest/operations/hot_restarter
https://github.com/envoyproxy/envoy/blob/41d8ccc79c4b98104475b55b5639567b14466190//restarter/hot-restarter.py
