### ISSUE TITLE
CRL reload from local file

### ISSUE THREAD

**Issue by sergey-safarov** [envoyproxy/envoy#38198]
*Title*: *CRL reload from local file*

*Description*:
> According to https://github.com/envoyproxy/envoy/issues/27750 and https://github.com/envoyproxy/envoy/pull/27751 CRL reload without envoy restart is supported. I have configured certificates using [`static resources`](https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-one-static-resource) and looks like this feature is not working as expected.

*Repro steps*:
> Required start envoy with expired CRL. When the client provides not expired cert then in the log you will see messages like

```
[source/common/tls/cert_validator/default_validator.cc:339] verify cert failed: X509_verify_cert: certificate verification error at depth 0: CRL has expired
```

If you replace the expired CRL with a valid not expired CRL then the envoy will not  catch the new CRL and still generate an error `CRL has expired`.

*Config*:
> For config I used reference example at https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret#example-one-static-resource

```
static_resources:
  secrets:
    - name: server_cert
      tls_certificate:
        certificate_chain:
          filename: certs/servercert.pem
        private_key:
          filename: certs/serverkey.pem
    - name: validation_context
      validation_context:
        trusted_ca:
          filename: certs/cacert.pem
        crl:
          filename: certs/crl.pem
  listeners:
    ....
    filter_chains:
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: server_cert
            validation_context_sds_secret_config:
              name: validation_context
```

*Logs*:
> [2025-01-26 13:50:08.317][3867863][debug][filter] [source/extensions/filters/listener/proxy_protocol/proxy_protocol.cc:176] proxy_protocol: New connection accepted
[2025-01-26 13:50:08.328][3867863][debug][conn_handler] [source/common/listener_manager/active_tcp_listener.cc:158] [Tags: "ConnectionId":"287"] new connection from 84.54.152.55:34648
[2025-01-26 13:50:08.630][3867863][debug][connection] [source/common/tls/cert_validator/default_validator.cc:339] verify cert failed: X509_verify_cert: certificate verification error at depth 0: CRL has expired
[2025-01-26 13:50:08.630][3867863][debug][connection] [source/common/tls/ssl_socket.cc:246] [Tags: "ConnectionId":"287"] remote address:84.54.152.55:34648,TLS_error:|268435581:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED:TLS_error_end
[2025-01-26 13:50:08.630][3867863][debug][connection] [source/common/network/connection_impl.cc:276] [Tags: "ConnectionId":"287"] closing socket: 0
[2025-01-26 13:50:08.630][3867863][debug][conn_handler] [source/common/listener_manager/active_stream_listener_base.cc:136] [Tags: "ConnectionId":"287"] adding to cleanup list

**Comment by alyssawilk** [comment]
@yanavlasov @ggreenway @tsaarni

**Comment by tsaarni** [comment]
Hi @sergey-safarov, I believe reload works with SDS based secrets. When using them with files, it looks like this:


```yaml
static_resources:
  listeners:
    ...
    filter_chains:
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            validation_context_sds_secret_config:
              name: validation_context_secret
              sds_config:
                resource_api_version: V3
                path_config_source:
                  path: /path/to/sds-auth-secret-validation-context.yaml
```


Then in `/path/to/sds-auth-secret-validation-context.yaml`

```yaml
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: validation_context_secret
    validation_context:
      trusted_ca:
        filename: /path/to/certs/client-ca.pem
      crl:
        filename: /path/to/certs/client-ca-crl.pem

      # Optionally the inotify watch can be specified expicitly with watched_directory like this:
      #watched_directory:
      #  path: /path/to/certs/
```
