### ISSUE TITLE
Allow configuring HCM filter with ECDS in QUIC listeners

### ISSUE THREAD

**Issue by iczero** [envoyproxy/envoy#38201]
*Description*:
The QUIC transport requires the last filter in the filter chain to be an HTTP connection manager. However, the check for this only supports inline `typed_config` and not ECDS. Since `config_discovery` explicitly specifies `type_urls`, I believe it should be possible to support ECDS as well.

Config example:
```yaml
static_resources:
  listeners:
    name: quic-listener
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 443
    udp_listener_config:
      quic_options:
        idle_timeout: 900s
      downstream_socket_config:
        prefer_gro: true
    filter_chains:
      - transport_socket:
          name: quic-tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
            downstream_tls_context:
              common_tls_context:
                tls_certificates: [...]
        filters:
          - name: quic-http3-hcm
            config_discovery:
              config_source:
                path_config_source:
                  path: '/path/to/ecds.yaml'
              type_urls: ['type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager']
```

I have written a patch, however I am not sure if it is correct: https://github.com/iczero/envoy/commit/afc6a4bd4708ae8350b6b9e1ed12261940566c62. Could you please take a look? I will open a PR if it is workable.
