### ISSUE TITLE
Dynamically add path to lb_endpoints endpoints for load balancing

### ISSUE THREAD

**Issue by shivamkumar99** [envoyproxy/envoy#38293]
*Title*: *Add path to upstream endpoint or cluster endpoint*

*Description*:
I want to setup load balance which uses round robin.
Endpoints for forwarding request will be : 
https://subdomain1.envoy.io/base-path-1
https://subdomain2.envoy.io/base-path-2
Now i want that when i make request to envoy for example : 
https://proxy.envoy.io/test then request should be forward to anyone of these route using round robin algo.
https://subdomain1.envoy.io/base-path-1/test
or
https://subdomain2.envoy.io/base-path-2/test

Since base-path-1 and base-path-2 is linked with sub domain so i need to provided it according to address where request is getting forward . How can i achieve this ?

[optional *Relevant Links*:]
File i am using for testing
```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9000
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 5000
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config: 
              '@type': "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
              stat_prefix: http_proxy
              route_config: 
                name: all
                virtual_hosts:
                  - name: allbackend_cluster
                    domains: 
                      - '*'
                    routes:
                      - match: { prefix: "/"}
                        route:
                          cluster: allbackend_cluster
              http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: allbackend_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: allbackend_cluster
        endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: flask_app_1
                    port_value: 3000
            
            - endpoint:
                address:
                  socket_address:
                    address: flask_app_2
                    port_value: 3001
```
