### ISSUE TITLE
Unable to use RegEx functions in CEL expressions

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#38303]
## Description

I'm unable to use regular expression functions (like [re.capture](https://cloud.google.com/eventarc/advanced/docs/receive-events/use-cel)) in CEL expressions, even though they should be available through the [built-in functions registration](https://github.com/envoyproxy/envoy/blob/057f7e0223d1985fd3b8f1adb1f6191454d963de/source/extensions/filters/common/expr/evaluator.cc#L119).

I verified that `options.enable_regex` is [enabled](https://github.com/envoyproxy/envoy/blob/057f7e0223d1985fd3b8f1adb1f6191454d963de/source/extensions/filters/common/expr/evaluator.cc#L105) and that [RegisterRegexFunctions](https://github.com/google/cel-cpp/blob/master/eval/public/builtin_func_registrar.cc#L57-L58) is included as part of `RegisterBuiltinFunctions(...)`

### Expected Behavior
Regular expression functions like `re.capture` should be available for use in CEL expressions since they're registered through `RegisterBuiltinFunctions(...)`.

### Current Behavior

RegEx functions are not accessible in CEL expressions despite proper configuration. When I try to do something like this, it fails with an error saying: _"failed to create an expression: No overloads provided for FunctionStep creation"_

```yaml
format_string:
  formatters:
  - name: envoy.formatter.cel
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.formatter.cel.v3.Cel
  text_format_source:
    inline_string: '%CEL(re.capture(connection.requested_server_name, R"hell(o)"))%'
```
