### ISSUE TITLE
Adaptive Concurrency Tuning Incase of Sustained Degredation

### ISSUE THREAD

**Issue by deveshkandpal1224** [envoyproxy/envoy#38338]
[](url)I have a question about behaviour for adaptive concurrency. My setup looks like as follows:
 
- I have a client k8s pod with envoy proxy.
- 3 server pod with envoy proxy as well.
- I've configured the adaptive concurrency filter on the inbound side of each server pod.
- After a given server envoy receives traffic, its forwarding the traffic to a single endpoint which is 127.0.0.1:7443.

My gradientControllerConfig looks something like as shown below, i've put my thoughts around how am I thinking about this config:

```

          gradientControllerConfig:
            concurrencyLimitParams:
              # every second influence concurrency calculation
              concurrencyUpdateInterval: 1s
              max_concurrency_limit: 50000
            minRttCalcParams:
              min_concurrency: 5000
              buffer:
                # buffer preferably should be 0, to react quickly incase of traffic burst
                value: 0
              # in intervals of 300s + jitter start the timer and collect 50 samples and get p95
              # delaying minRTT calculation seems to naturally help with traffic burst
              # but if initial minRTT calculation is too optimistic ( low value ), it might take a while
              # before you get to recalculate it. In which case sampleRTT might not be able
              # to catch up, so concurrency will be low. I guess that's where some buffer helps with minRTT. But if your
              # min_concurrency is decently high, you might need not worry about it I think.
              interval: 300s
              jitter:
                # adds variance to when minRTT should be started and not at a constant interval always
                value: 50
              requestCount: 50
            sampleAggregatePercentile:
              value: 95


```

My understanding about the behavior so far has been that:
- In a normal situation where `sampleRTT` keeps getting better, `concurrency_limit` keeps increasing, which is great.
- Incase of burst traffic, `sampleRTT` is calculated every second in my case.  This will help take down the `concurrency_limit` instantly assuming `minRTT` recalculation hasn't happened yet and it was much lower than reported `sampleRTT` during traffic burst.  If `minRTT` recalculation does happen at around the time of traffic burst, it will bring down the `concurrency_limit` to `min_concurrency` first and `minRTT` will get locked to a higher value until next calculation. Since sampleRTT is high, it will stay at a lower concurrency. Once the spike dies, `sampleRTT` - if it keeps getting better, it will increase the concurrency instantly even though it will be a while before `minRTT` can improve. This also seems fine I think.
- The problem i'm having with is what if the **degradation is sustained**. In that case if you end up in a situation
where `sampleRTT` and `minRTT` both are reporting high values ( nearly same ), you'll end up with an increasing `concurrency_limit`
due to `headroom` being accounted for (see graph below). That will probably make the situation worse I think. So i'm wondering
how do you deal with this behaviour ? 

I've attached a graph below. The two green lines in below screenshot are RTT calculations and light blue line is the `concurrency_limit`.

 Really appreciate any thoughts in this area!
