### ISSUE TITLE
Question: Unable to Send Traces to Dynatrace Through Corporate Proxy

### ISSUE THREAD

**Issue by joumenharzli** [envoyproxy/envoy#38354]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: Unable to Send Traces to Dynatrace Through Corporate Proxy

*Description*:
I am running Envoy behind a corporate proxy and trying to send traces to Dynatrace via OpenTelemetry.  
However, Envoy is unable to establish a connection through the proxy.  

*Observed Behavior:*
- to debug, I set up a local proxy and configured `envoy.http11_proxy_transport_socket.proxy_address`, but it appears to be ignored.
- Envoy is not connecting to the Proxy that's why traces are not reaching Dynatrace.

*Questions:*
1. Is my configuration correct?
2. Is using the `http_11_proxy transport socket` is the correct approach?

[I followed this documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/http_11_proxy/v3/upstream_http_11_connect.proto).

Any insights or guidance would be greatly appreciated!  
Thanks in advance.

---

*Tracing Config*:
```yaml
                tracing:
                  random_sampling:
                    value: 100
                  provider:
                    name: envoy.tracers.opentelemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                      service_name: ${SERVICE_NAME}
                      http_service:
                        http_uri:
                          uri: "${DT_TENANT_ID}.live.dynatrace.com/api/v2/otlp/v1/traces"
                          cluster: dynatrace-otel
                          timeout: 10s
                        request_headers_to_add:
                          - header:
                              key: "Authorization"
                              value: "Api-Token ${DT_API_TOKEN}"
                      sampler:
                        name: envoy.tracers.opentelemetry.samplers.dynatrace
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.tracers.opentelemetry.samplers.v3.DynatraceSamplerConfig
                          cluster_id: ${DT_CLUSTER_ID}
                          tenant: ${DT_TENANT_ID}
                          http_service:
                            http_uri:
                              cluster: "dynatrace-otel"
                              uri: "${DT_TENANT_ID}.live.dynatrace.com/api/v2/samplingConfiguration"
                              timeout: 10s
                            request_headers_to_add:
                              - header:
                                  key: "authorization"
                                  value: "Api-Token ${DT_API_TOKEN}"
```

*Cluster Config*:
```yaml
clusters:
  - name: dynatrace-otel
    connect_timeout: 10s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: dynatrace-otel
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: "${DT_TENANT_ID}.live.dynatrace.com"
                    port_value: 443
              metadata:
                typed_filter_metadata:
                  envoy.http11_proxy_transport_socket.proxy_address:
                    "@type": type.googleapis.com/envoy.config.core.v3.SocketAddress
                    address: ${HTTP_PROXY_HOST}
                    port_value: ${HTTP_PROXY_PORT}
    transport_socket:
      name: envoy.transport_sockets.http_11_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.http_11_proxy.v3.Http11ProxyUpstreamTransport
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
```
