### ISSUE TITLE
Add filter_enabled flag to RBAC filter

### ISSUE THREAD

**Issue by LaureHalabi** [envoyproxy/envoy#38435]
*Title*: Add filter_enabled flag to RBAC filter

*Description*:
Currently, [Envoy's RBAC filter](https://github.com/envoyproxy/envoy/blob/0bf518c005dc2372e40ee79e9f22fefb07abe29a/api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#L61) does not have a `filter_enabled` field that other http filters have (e.g. [localRateLimit](https://github.com/envoyproxy/envoy/blob/0bf518c005dc2372e40ee79e9f22fefb07abe29a/api/envoy/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#L61) and [extAuth](https://github.com/envoyproxy/envoy/blob/0bf518c005dc2372e40ee79e9f22fefb07abe29a/api/envoy/extensions/filters/http/ext_authz/v3/ext_authz.proto#L158)) . Adding this flag to the rbac filter would provide flexibility in enabling or disabling the filter at runtime based on runtime settings allowing for dynamic management of filter behavior without requiring a full configuration deployment.

I can prepare a patch for this if it sounds reasonable.

**Comment by mattklein123** [comment]
I believe this is supported generically now: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_filters#route-based-filter-chain

cc @wbpcode

**Comment by LaureHalabi** [comment]
Thank you for pointing me to that. As far as I can tell, I don't think the filterConfig values can be set dynamically through runtime configuration. I'll reword my idea: Can we modify the `disabled` key to read its value from a runtime key? 

```
typed_per_filter_config:
    envoy.filters.http.rbac:
        "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
        disable: 
            runtime_key: "rbac.filter_disabled"
            default_value:
                numerator: 0
                denominator: 100
```


If that doesn't seem feasible, will the original idea of supporting `filterEnabled` in the RBAC filter work here? The aim is to be able to enable/disable these filters dynamically through runtime configuration instead of having our control plane modify routes from RDS each time.
