### ISSUE TITLE
`generate_request_id` does not generate `x-request-id` if it is present but empty

### ISSUE THREAD

**Issue by quantumsheep** [envoyproxy/envoy#38445]
*Title*: *`generate_request_id` does not generate `x-request-id` if it is present but empty*

# Description
I expected `generate_request_id` to generate a `x-request-id` if it isn't present OR empty. But this seems to not be the case. Is this intended? If so, do you have a solution to generate it if it's empty?

# Repro steps
The config (found bellow) is run with the following command:
```bash
docker run --rm -v $(pwd)/envoy.yaml:/etc/envoy/envoy.yaml -p 80:80 envoyproxy/envoy:v1.31-latest
```

## Without passing `x-request-id`
In this case, the `x-request-id` header is generated.

```bash
# x-request-id present in response
curl http://localhost:80/ -v
```

**Output:**
```
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< date: Thu, 13 Feb 2025 10:34:01 GMT
< server: envoy
< x-request-id: e4dcd48e-9914-416d-a60e-fa57e119c1a8
<
* Connection #0 to host localhost left intact
OK
```

## Explicitly passing `x-request-id`
In this case, the `x-request-id` header is forwarded in the response because of `always_set_request_id_in_response: true`.

```bash
curl -H"x-request-id: hello" http://localhost:80/ -v
```

**Output:**
```
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/8.7.1
> Accept: */*
> x-request-id: hello
>
* Request completely sent off
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< date: Thu, 13 Feb 2025 10:37:13 GMT
< server: envoy
< x-request-id: hello
<
* Connection #0 to host localhost left intact
OK
```

## Explicitly passing an empty `x-request-id`
In this case, the `x-request-id` header is forwarded in the response because of `always_set_request_id_in_response: true`. But `generate_request_id: true` should have generated one.

```bash
curl -H"x-request-id;" http://localhost:80/ -v
```

**Output:**
```
* Host localhost:80 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:80...
* Connected to localhost (::1) port 80
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/8.7.1
> Accept: */*
> x-request-id:
>
* Request completely sent off
< HTTP/1.1 200 OK
< content-length: 2
< content-type: text/plain
< date: Thu, 13 Feb 2025 10:38:18 GMT
< server: envoy
< x-request-id:
<
* Connection #0 to host localhost left intact
OK
```

# Config
```yaml
admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 80 }
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                generate_request_id: true
                always_set_request_id_in_response: true
                route_config:
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          direct_response:
                            status: 200
                            body:
                              inline_string: "OK"
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
```
