### ISSUE TITLE
Support role chaining in AWS signing filter

### ISSUE THREAD

**Issue by Nevon** [envoyproxy/envoy#38455]
*Title*: Support role chaining in AWS signing filter

*Description*:
Currently the AWS signing filter supports a few different ways of getting credentials to use for signing requests. However, as far as I can tell, it does not support role chaining where one set of credentials is used in order to assume another role with which to sign the requests.

In my particular case, I need to configure Envoy as a signing proxy deployed as part of an ECS task, where the identity used to sign requests is not the ECS task role, but another role that the ECS task is able to assume. I would imagine that this would be a new credential provider like `AssumeRoleProvider` that would in turn receive a credential provider from which to get the credentials needed to assume the role as needed.

*Relevant Links*:
* [Role chaining documentation](https://docs.aws.amazon.com/sdkref/latest/guide/feature-assume-role-credentials.html)
* [Envoy AWS request signing filter credentials documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/aws_request_signing_filter.html#credentials)

**Comment by nbaws** [comment]
This seems like a reasonable request. The devil would be in the details for implementing this however, probably some refactoring of the credential caching system to handle the extra layer of redirection.
I'd be happy to take this on but it would be a few months out given the current backlog of fixes for this extension.

**Comment by nbaws** [comment]
Just a heads up I have a patch ready to go for this, its just dependent on merge of https://github.com/envoyproxy/envoy/pull/39616

**Comment by nbaws** [comment]
This feature is now available in the dev release :) Please give it a try and see how it works for you.

**Comment by nbaws** [comment]
Here is an example configuration for this feature. I'm currently working on adding this sample to the documentation.

For an `assume_role_credential_provider` we are able to configure a secondary custom credential provider to tell it where to source the original credentials from. In this example, we're saying to use the instance profile as the credential source for the assume role credential provider, which will then be used as the credential source for your request signing. It's not totally straightforward to understand, but you'll understand it if you understand role chaining.

We don't currently support multiple levels of role chaining in this manner, attempting to use more than one layer of assume role provider will be ignored at the second layer.


```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - domains:
              - '*'
              name: local_service
              routes:
              - match: {prefix: "/"}
                route: {cluster: default_service}
  clusters:
  - name: default_service
    load_assignment:
      cluster_name: default_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 10001
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        upstream_http_protocol_options:
          auto_sni: true
          auto_san_validation: true
        auto_config:
          http2_protocol_options: {}
        http_filters:
        - name: envoy.filters.http.aws_request_signing
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
            credential_provider:
              custom_credential_provider_chain: true
              assume_role_credential_provider:
                role_arn: arn:aws:iam::12345678:role/testassume
                credential_provider:
                  custom_credential_provider_chain: true
                  instance_profile_credential_provider: {}
            service_name: vpc-lattice-svcs
            region: 'ap-southeast-2'
            signing_algorithm: AWS_SIGV4
            use_unsigned_payload: true
            match_excluded_headers:
            - prefix: x-envoy
            - prefix: x-forwarded
            - exact: x-amzn-trace-id
        - name: envoy.filters.http.upstream_codec
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext

```
