### ISSUE TITLE
www -> nonwww redirect for many domains

### ISSUE THREAD

**Issue by dolgovas** [envoyproxy/envoy#38466]
I can't find any directive for massive host_rewrite configuration.
I want to make something like this

```
www.example.com    301 to example.com
www.example1.com   301 to example1.com
www.example2.com   301 to example2.com
www.example3.com   301 to exampel3.com
```

I tried to use route like this
```
 kind: Route
 metadata:
   name: www-redirect
 spec:
   - name: www-redirect
     match:
       prefix: "/"
     redirect:
       https_redirect: true
       regex_rewrite:
         pattern:
           google_re2: {}
          regex: "^www\\.(.*)$"
        substitution: "\\1"
```

But I realized that regex_rewrite works only with path, but not with host.

For now, I use this construction

```
routeConfigurations:
  - name: exc-configs/www
    virtual_hosts:
      - name: exc-configs/www
        domains:
          - www.example.com
        routes:
          - name: www-redirect
            match:
              PathSpecifier:
                Prefix: /
            Action:
              Redirect:
                SchemeRewriteSpecifier:
                  HttpsRedirect: true
                host_redirect: example.com
---
routeConfigurations:
  - name: exc-configs/www
    virtual_hosts:
      - name: exc-configs/www
        domains:
          - www.example1.com
        routes:
          - name: www-redirect
            match:
              PathSpecifier:
                Prefix: /
            Action:
              Redirect:
                SchemeRewriteSpecifier:
                  HttpsRedirect: true
                host_redirect: example1.com
---
routeConfigurations:
  - name: exc-configs/www
    virtual_hosts:
      - name: exc-configs/www
        domains:
          - www.example2.com
        routes:
          - name: www-redirect
            match:
              PathSpecifier:
                Prefix: /
            Action:
              Redirect:
                SchemeRewriteSpecifier:
                  HttpsRedirect: true
                host_redirect: example2.com
---
routeConfigurations:
  - name: exc-configs/www
    virtual_hosts:
      - name: exc-configs/www
        domains:
          - www.example3.com
        routes:
          - name: www-redirect
            match:
              PathSpecifier:
                Prefix: /
            Action:
              Redirect:
                SchemeRewriteSpecifier:
                  HttpsRedirect: true
                host_redirect: example3.com

```

And it works. But may be I can improve it?
