### ISSUE TITLE
Global Rate Limit - safeRegexMatch does not match with Path

### ISSUE THREAD

**Issue by aydinnyunus** [envoyproxy/envoy#38473]
*Title*: *Global Rate Limit - safeRegexMatch does not match with Path*

*Description*:

safeRegexMatch does not match when query parameter is existing in the path.

*Repro steps*:

```yaml
- properties:
            global:
              rate:
                - dimensions:
                    - headerValueMatch:
                        descriptorValue: test
                        headers:
                          - name: :path
                            safeRegexMatch:
                              regex: /test/([^/]+)/test
                    - requestHeaders:
                        descriptorKey: user-check
                        headerName: x-userid
                  requestPerUnit: 1
                  unit: minute
          type: ratelimit
```

I sent request with 

`curl http://test.service/test/123/test -H "x-userid: 1"` it is matching.
`curl "http://test.service/test/123/test?a=1" -H "x-userid: 1"` does not match.

I think safeRegexMatch should match both of them because when I try on [regex101](https://regexr.com/) etc it was matched.
