### ISSUE TITLE
Is there a way to enable gzip compression for XDS?

### ISSUE THREAD

**Issue by berkeli** [envoyproxy/envoy#38482]
*Title*: Is it possible to enable gzip compression for xDS responses

*Description*:
Hello, we would like to know if it's possible to use gzip compression for xDS (specifically ADS streams). Our xDS server supports gzip and we've tried adding initial metadata (`grpc-accept-encoding: gzip`) but that didn't do the trick.

```yaml
dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: xds-cluster
      initial_metadata:
        key: grpc-accept-encoding
        value: gzip
```

I understand that the large response sizes could be overcome with delta xDS, but we do not have that currently implemented.
