### ISSUE TITLE
redis_proxy: KEYS command hangs

### ISSUE THREAD

**Issue by urusha** [envoyproxy/envoy#38508]
*Description*:
`KEYS` command hangs with envoy redis_proxy, after such query envoy can't be killed normally by TERM,INT signals.

*Repro steps*:
debian 12 amd64, redis 7.4.1, envoy-contrib-1.33.0-linux-x86_64
```
echo 'SET test test123' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
OK
echo 'GET test' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
"test123"
```
while
```
echo 'KEYS *' | redis-cli -h 127.0.0.1 -p 6380 -a pass1
```
hangs forever, other queries continue to work, but after `KEYS *` query - envoy can't be killed by TERM,INT (KILL works).

*Config*:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 6380
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_passwords:
          - inline_string: "pass1"
  clusters:
  - name: redis_cluster
    connect_timeout: 3s
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: redis
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 6379
    typed_extension_protocol_options:
        envoy.filters.network.redis_proxy:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProtocolOptions
          auth_password:
            inline_string: "pass2"
```

*Logs*:
Just one line about the query, with debug enabled:
```
[2025-02-20 17:03:25.591][4005349][debug][redis] [source/extensions/filters/network/redis_proxy/command_splitter_impl.cc:875] splitting '["KEYS", "*"]'
```
