### ISSUE TITLE
RING_HASH lb policy doesn't adjust load balancing weights when upstream hosts become unhealthy

### ISSUE THREAD

**Issue by cxhiano** [envoyproxy/envoy#38525]
*Title*: *RING_HASH lb policy doesn't adjust load balancing weights when upstream hosts become unhealthy*

*Description*:
>According to [this doc](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/locality_weight#arch-overview-load-balancing-locality-weighted-lb), Envoy adjusts traffic weights based on overprovisioning_factor and upstream host health status. This does not seem to be the case when lb_policy is set to RING_HASH.

*Repro steps*:
>Configure a cluster with lb_policy set to RING_HASH and a load_assignment with endpoints across at least 2 localities, traffic distribution across localities doesn't seem to change as some upstream hosts become unhealthy. 

*Config*:
```
  clusters:
  - name: test_service
    lb_policy: RING_HASH
    common_lb_config:
      locality_weighted_lb_config: {}
      healthy_panic_threshold:
        value: 1
    load_assignment:
 ...
```

cc: @tonya11en
