### ISSUE TITLE
Cors and rbac filter has unexpected behavior, Cors is not responding instantly

### ISSUE THREAD

**Issue by mhbahmani** [envoyproxy/envoy#38556]
*Description*:
I'm using Envoy with istio as API Gateway and have several plugins configured in my envoy  
The problem is that I want to put `cors` filter, ahead of the rbac filter, meaning that if the incoming request matches with the cors policy, the envoy instantly responds with 200 (or 204), and the request doesn't go through rbac filter. However, even when I managed to put cors as the first http_filter, the request still goes through the rbac filter. This will make us add `OPTIONS` to authorization policy resources (with allow action).  
  
Here is http_filters section of the envoy config:
```yaml
              http_filters:
              - name: envoy.filters.http.cors
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
              - name: envoy.filters.http.rbac
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                  shadow_rules:
                    action: DENY
                    policies:
                      istio-ext-authz-ns[istio-system]-policy[sample-policy]-rule[0]:
                        permissions:
                        - and_rules:
                          <rbac rules>
                           ...
```

And here is corsPolicy (defined in every virtual_host of our environment):
```yaml
        typed_per_filter_config:
          envoy.filters.http.cors:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
            allow_credentials: true
            allow_headers: '*'
            allow_methods: '*'
            allow_origin_string_match:
            - exact: https://test.com
            - safe_regex:
                regex: https:\/\/.*\.test\.com
            allow_private_network_access: true
            expose_headers: X-JWT-REFRESH, X-JWT-ERROR
            max_age: "3600"
```  

And this is my curl request:
```bash
curl http://api.test.com/v1/foo/bar' \
  -X 'OPTIONS' -H 'accept: */*' -H 'access-control-request-headers: authorization,content-type,x-screen-size' -H 'access-control-request-method: POST' -H 'origin: https://test.com'
```

**Comment by KBaichoo** [comment]
cc @wbpcode @yanavlasov

**Comment by wbpcode** [comment]
Could you provide the original configdump in this scenario. I did a quick test with your configuration snippet in my local env, and I think the pre-flight request should be responded directly.

```
 curl localhost:8080/anything -v \
  -X 'OPTIONS' -H 'accept: */*' -H 'access-control-request-headers: authorization,content-type,x-screen-size' -H 'access-control-request-method: POST' -H 'origin: https://test.com'
* Uses proxy env variable no_proxy == 'code.byted.org,127.0.0.1,localhost'
*   Trying ::1:8080...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> OPTIONS /anything HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> accept: */*
> access-control-request-headers: authorization,content-type,x-screen-size
> access-control-request-method: POST
> origin: https://test.com
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< access-control-allow-origin: https://test.com
< access-control-allow-credentials: true
< access-control-allow-methods: POST
< access-control-allow-headers: authorization,content-type,x-screen-size
< access-control-max-age: 3600
< access-control-expose-headers: X-JWT-REFRESH, X-JWT-ERROR
< date: Wed, 26 Feb 2025 03:03:21 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by mhbahmani** [comment]
This is more of my config file. My original configdump is too long to post (it's around 110k lines). I put all the related configurations and deleted extra parts like other routes and stuff.
 Can I see your full configuration to compare to mine?

```yaml
configs:
- '@type': type.googleapis.com/envoy.admin.v3.ListenersConfigDump
  dynamic_listeners:
  - active_state:
      last_updated: "2025-02-25T08:29:27.846Z"
      listener:
        '@type': type.googleapis.com/envoy.config.listener.v3.Listener
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 10000
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              http_filters:
              - name: envoy.filters.http.cors
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
              - name: envoy.filters.http.rbac
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBAC
                  shadow_rules:
                    action: DENY
                    policies:
                      istio-ext-authz-ns[istio-system]-policy[sample-policy]-rule[0]:
                        permissions:
                        - and_rules:
                          <rbac rules>
                           ...
              - name: istio.metadata_exchange
                typed_config:
                  '@type': type.googleapis.com/udpa.type.v1.TypedStruct
                  type_url: type.googleapis.com/io.istio.http.peer_metadata.Config
                  value:
                    upstream_discovery:
                    - istio_headers: {}
                    - workload_discovery: {}
                    upstream_propagation:
                    - istio_headers: {}
              - name: envoy.filters.http.grpc_stats
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
                  emit_filter_state: true
                  stats_for_all_methods: false
              - name: istio.alpn
                typed_config:
                  '@type': type.googleapis.com/istio.envoy.config.filter.http.alpn.v2alpha1.FilterConfig
                  alpn_override:
                  - alpn_override:
                    - istio-http/1.0
                    - istio
                    - http/1.0
                  - alpn_override:
                    - istio-http/1.1
                    - istio
                    - http/1.1
                    upstream_protocol: HTTP11
                  - alpn_override:
                    - istio-h2
                    - istio
                    - h2
                    upstream_protocol: HTTP2
              - name: envoy.filters.http.fault
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault
              - name: istio.stats
                typed_config:
                  '@type': type.googleapis.com/stats.PluginConfig
                  disable_host_header_fallback: true
              - name: envoy.filters.http.jwt_authn
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.jwt_authn.v3.JwtAuthentication
                  providers:
                    auth_provider:
                      claim_to_headers:
                      - claims ...
                      forward: true
                  rules:
                  - match:
                      prefix: /
                    requires:
                      requires_any:
                        requirements:
                        - provider_name: auth_provider
              - name: envoy.filters.http.router
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              http_protocol_options: {}
              merge_slashes: true
              normalize_path: true
              path_with_escaped_slashes_action: KEEP_UNCHANGED
              proxy_100_continue: true
              rds:
                config_source:
                  ads: {}
                  initial_fetch_timeout: 0s
                  resource_api_version: V3
                route_config_name: http.10000
              request_id_extension:
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
                  use_request_id_for_trace_sampling: true
              server_name: istio-envoy
              set_current_client_cert_details:
                cert: true
                dns: true
                subject: true
                uri: true
              stat_prefix: outbound_0.0.0.0_10000;
              stream_idle_timeout: 0s
              upgrade_configs:
              - upgrade_type: websocket
              use_remote_address: true
          transport_socket_connect_timeout: 15s
        name: 0.0.0.0_10000
        traffic_direction: OUTBOUND
    name: 0.0.0.0_10000
  static_listeners:
  - static listeners ...
- '@type': type.googleapis.com/envoy.admin.v3.RoutesConfigDump
  dynamic_route_configs:
  - last_updated: "2025-02-24T18:23:36.607Z"
    route_config:
      '@type': type.googleapis.com/envoy.config.route.v3.RouteConfiguration
      ignore_port_in_host_matching: true
      max_direct_response_body_size_bytes: 1048576
      name: http.10000
      validate_clusters: false
      virtual_hosts:
      - domains:
        - api.test.com
        include_request_attempt_count: true
        name: api.test.com:10000
        routes:
        - decorator:
            operation: restfull-service.namespace.svc.cluster.local:80/*
          match:
            case_sensitive: true
            path_separated_prefix: /v1/foo/bar
          metadata:
            filter_metadata:
              istio:
                config: /apis/networking.istio.io/v1/namespaces/NS/virtual-service/svc
          name: namespace.restfull-service.0
          route:
            cluster: outbound|80||restfull-service.namespace.svc.cluster.local
            cluster_not_found_response_code: INTERNAL_SERVER_ERROR
            max_grpc_timeout: 4s
            retry_policy:
              host_selection_retry_max_attempts: "5"
              num_retries: 2
              retry_host_predicate:
              - name: envoy.retry_host_predicates.previous_hosts
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
              retry_on: connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes
            timeout: 4s
        typed_per_filter_config:
          envoy.filters.http.cors:
            '@type': type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
            allow_credentials: true
            allow_headers: '*'
            allow_methods: '*'
            allow_origin_string_match:
            - exact: https://test.com
            - safe_regex:
                regex: https:\/\/.*\.test\.com
            allow_private_network_access: true
            expose_headers: X-JWT-REFRESH, X-JWT-ERROR
            max_age: "3600"
  static_route_configs:
  - ... static route configs
```

Just in case, do you agree that cors filter in envoy works just for defined routes that have OPTIONS method (I mean we should specifically mention OPTIONS method in the route definition in route methods)?
