### ISSUE TITLE
Access log configuration at route level

### ISSUE THREAD

**Issue by daganibhanu** [envoyproxy/envoy#38572]
Do we have any API support to add access log configuration at route level, sample configuration given below

```
access_log:
  - name: envoy.access_loggers.file
	typed_config:
	  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
	  path: "/dev/stdout"
	  format: |
		[%START_TIME%] "%REQ(TRACE-USER-ID?REMOTE_USER)%" "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(UBER-TRACE-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
  - name: envoy.access_loggers.grpc
	typed_config:
	  "@type": type.googleapis.com/envoy.extensions.access_loggers.grpc.v3.HttpGrpcAccessLogConfig
	  common_config:
		log_name: "access_log_grpc"
		grpc_service:
			cluster_name: grpc_access_log_service
		transport_api_version: V3
```

to send access logs to a grpc endpoint. 
Adding the configuration at listener level, we end up listening to the unwanted traffic, instead can we have this configuration at route level, is it possible ? or do we need to apply extension filters to achieve this?
