### ISSUE TITLE
Asymmetry between upload and download when streaming HTTP/2

### ISSUE THREAD

**Issue by ohadvano** [envoyproxy/envoy#38573]
We're running some use case that uses HTTP/2 streams and noticed that download throughputs do not reach upload throughputs. Directions of looking into tuning the HTTP/2 stream and connection window sizes only helped by a bit, but in general we're still seeing a behavior where upload throughputs are higher by around 60% than download throughputs, over the same client and server connection.

I tried to reproduce this with a very simple setup that I could also share here, and found similar results.
I am running Envoy with the configuration below. The downstream client is ``curl``, and the upstream server is a simple Node JS program (also tested with some .NET program to compare but got similar results).

In both upload and download, I'm trying to stream a 5 GB file. While in upload scenario I get around 1600 Mbps, in the download direction I could only get around 800-900 Mbps.

Will appreciate insights whether this is an expected behavior. Is there some misconfiguration here?

cc @alyssawilk, @mattklein123 

Envoy config:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1234
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
                - match:
                    prefix: "/"
                  route:
                    cluster: service_backend
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: service_backend
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service_backend
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80
```

Curl commands:
```
curl --http2-prior-knowledge -v -w '%{speed_upload}' -X PUT -T /temp/large-file.txt http://localhost:1234/upload
curl --http2-prior-knowledge -v -w '%{speed_download}' http://localhost:1234/download -o /tmp/file1.txt
```
