### ISSUE TITLE
no_healthy_upstream 503 errors with static configuration since 1.31.0

### ISSUE THREAD

**Issue by michalmiddleton** [envoyproxy/envoy#38577]
*Title*: *no_healthy_upstream 503 errors with static configuration since 1.31.0*

*Description*:
We've identified what seems to be a regression in Envoy behavior starting with version 1.31.0 where services experience intermittent 503 errors with `no_healthy_upstream` responses and UH response flags.
This occurs with static configurations and affects various upstream services - both internal and external. The issue happens sporadically and the frequency seems to correlate with load. To troubleshoot and reproduce this error,
I used our "canary-service" in nonprod, which has no incoming traffic besides the kubernetes probes every 30s. I wired the service health check endpoint to make one http1.1 GET call a few different endpoints (vault, sqs, sts). With this kind of 
traffic (or a lack of) I am able to reproduce the problem about once a day. However in our production, we see this issue at a rate of 30k-60k errors per hour during the peak across all our mesh services. Other than the errors, we are not seeing any resource issues.
With multiple services, we have confirmed that the envoy version is the only component that affects our situation (ie. same configuration, differnet envoy versions). 

- Last working version: Up to 1.30.9 (FIPS build)
- First affected version: 1.31.0 (tested up to the current stable 1.33.0, using the official build toolchain, no source modifications, only added `build --define boringssl=fips`)

Our environment:
- Kubernetes 1.30.9 on RHEL8
- Container images based on RHEL 9.2 (patched via EUS)
- Container resources typically around 1Gi memory and 500m-2 cpi limit. Varies by service and its configuration and load
- Envoy is mostly executed with `-concurrency 4` (since it runs on 72CPU K8S servers) and the following Env vars (that are referenced in the configuration)
```
          - name: APPLICATION_VERSION
            value: "v1.0.1"
          - name: ENABLE_SHUTDOWN
            value: "0"
          - name: HELM_CHART_VERSION
            value: 1.57.5-pr-3830568
          - name: INBOUND_PORT
            value: "9211"
          - name: OUTBOUND_PORT
            value: "12345"
          - name: GRPC_PORT
            value: "8081"
          - name: HTTP_PORT
            value: "8080"
          - name: HEALTH_PORT
            value: "8080"
          - name: HEALTH_PATH
            value: "/health"
          - name: ADMIN_PORT
            value: "9901"
          - name: TRUSTED_PROXIES
            value: com.mysvc.prod.apigateway
          - name: SERVICE_TIMEOUT
            value: "15"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ROLETYPE
            value: "svcmsh"
          - name: SERVICE
            value: canary-service
          - name: CONFIG_HASH
            value: 937718b33f8c5f5b619cc73994b54d29dafb1b84240c0749b6418c0a972c648b
          - name: STABLE_CLUSTER
            value: "local_service"
          - name: UNSTABLE_CLUSTER
            value: "other_pool"
          - name: OTHER_HOST
            value: "unstable-servicemesh-test.k8s.mysvc.tech"
```

*Repro steps*:
- in our case, the standard configuration consists of vhost and cluster such as this external example (using aws sqs)
```
  - connect_timeout: 5s
    lb_policy: round_robin
    load_assignment:
      cluster_name: sqs
      endpoints:
      - lb_endpoints:
          endpoint:
            address:
              socket_address:
                address: sqs.us-west-2.amazonaws.com
                port_value: 443
    name: sqs
    transport_socket:
      name: envoy.transport_sockets.tap
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.tap.v3.Tap
        common_config:
          admin_config:
            config_id: cluster_sqs
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            allow_renegotiation: true
            common_tls_context:
              tls_params:
                cipher_suites:
                - ECDHE-ECDSA-AES128-GCM-SHA256
                - ECDHE-RSA-AES128-GCM-SHA256
                - ECDHE-ECDSA-AES256-GCM-SHA384
                - ECDHE-RSA-AES256-GCM-SHA384
                tls_maximum_protocol_version: TLSv1_2
                tls_minimum_protocol_version: TLSv1_2
              validation_context_sds_secret_config:
                name: client-validation
                sds_config:
                  path_config_source:
                    path: /etc/envoy/xds/sds-client-validation.yaml
                  resource_api_version: V3
            sni: sqs.us-west-2.amazonaws.com
    type: STRICT_DNS
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        common_http_protocol_options:
          idle_timeout: 300s
        explicit_http_config:
          http_protocol_options: {}
```

```
            - domains:
              - sqs.us-west-2.amazonaws.com
              name: sqs
              routes:
              - decorator:
                  operation: sqs
                match:
                  prefix: /
                route:
                  auto_host_rewrite: true
                  cluster: sqs
                  timeout: 30s
```

*Admin and Stats Output*:
- /clusters - see api_clusters.txt
- /routes - n/a
- /server_info - see api_server_info.txt
  
*Config*:
- full config is attached - see config.yaml

*Logs*:
- I switched all components to trace level and captured the events. Due to verbosity, I trimmed the log to 10s before and 10s after the event. I do have the full logs available locally, if needed.
- Search for `no_healthy_upstream`
- see envoy-internal.log for issue on internal endpoint (vault)
- see envoy-external.log for issue on external endpoint (sqs)

[api_clusters.txt](https://github.com/user-attachments/files/18993433/api_clusters.txt)
[api_server_info.txt](https://github.com/user-attachments/files/18993430/api_server_info.txt)
[config.yaml.txt](https://github.com/user-attachments/files/18993438/config.yaml.txt)
[envoy-external.log](https://github.com/user-attachments/files/18993431/envoy-external.log)
[envoy-internal.log](https://github.com/user-attachments/files/18993432/envoy-internal.log)
