### ISSUE TITLE
Got segfault with redis proxy cluster

### ISSUE THREAD

**Issue by keyolk** [envoyproxy/envoy#38585]
With Istio, found it got segfault when the redis related destination rule is added or removed.
It does not happen in Istio v1.22, which uses the 1.30 version of Envoy.
And reproduced in Istio v1.23 using 1.31.5 Envoy
Also able to reproduce it with latest envoy as well https://github.com/envoyproxy/envoy/commit/b0f43d67aa25c1b03c97186a200cc187f4c22db3

```
(gdb) bt full
#0  0x0000ffffb388f200 in __pthread_kill_implementation (threadid=281473696309280, signo=signo@entry=11, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:66
        __futex = 0x491bfd2e970
        __private = 0
        __oldval = <optimized out>
        pd = 0xffffb3aea020
        old_mask = {__val = {281473696119632, 0, 0, 0, 0, 281473696119312, 281473693538492, 8, 281473696119368, 281473696363044, 281473696363082,
            281473696364576, 281473696362904, 5, 281473696119368, 281473696119440}}
        ret = 11
#1  0x0000ffffb388f244 in __pthread_kill_internal (signo=11, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x0000ffffb384a67c in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x0000aaaabc9ab040 in Envoy::SignalAction::sigHandler(int, siginfo_t*, void*) ()
No symbol table info available.
#4  <signal handler called>
No symbol table info available.
#5  0x0000000000000000 in ?? ()
No symbol table info available.
#6  0x0000aaaaba94692c in Envoy::Extensions::Clusters::Redis::RedisCluster::RedisDiscoverySession::startResolveRedis() ()
No symbol table info available.
#7  0x0000aaaabcac2910 in event_process_active_single_queue ()
No symbol table info available.
#8  0x0000aaaabcac1454 in event_base_loop ()
No symbol table info available.
#9  0x0000aaaabc0cd554 in Envoy::Server::InstanceBase::run() ()
No symbol table info available.
#10 0x0000aaaabc078da4 in Envoy::MainCommonBase::run() ()
No symbol table info available.
#11 0x0000aaaabc079540 in Envoy::MainCommon::main(int, char**, std::__1::function<void (Envoy::Server::Instance&)>) ()
No symbol table info available.
#12 0x0000aaaaba8ed038 in main ()
No symbol table info available.
(gdb)
```

The related destinationrule I used is like
```
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: test
  namespace: test
spec:
  exportTo:
    - '*'
  host: test.com
  trafficPolicy:
    tls:
      mode: DISABLE
```

It would be nothing to be changed.
When I see the related envoy cluster, 
seems the only diff it made was adding the 

`metadata.filter_metadata.istio.config: "/apis/networking.istio.io/v1alpha3/namespace/test/destination-rule/test"`

```
cluster:
  "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: outbound|6379||test.com
  connect_timeout: 1s
  lb_policy: CLUSTER_PROVIDED
  health_checks:
    - timeout: 0.500s
      interval: 2s
      unhealthy_threshold: 2
      healthy_threshold: 1
      custom_health_check:
        name: envoy.health_checkers.redis
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
  circuit_breakers:
    thresholds:
      - max_connections: 4294967295
        max_pending_requests: 4294967295
        max_requests: 4294967295
        max_retries: 4294967295
        track_remaining: true
  dns_refresh_rate: 60s
  dns_lookup_family: V4_ONLY
  metadata:
    filter_metadata:
      istio:
        services:
          - host: test.com
            name: test.com
            namespace: test
        external: true
  common_lb_config:
    locality_weighted_lb_config: {}
  alt_stat_name: outbound|6379||test
  load_assignment:
    cluster_name: outbound|6379||test.com
    endpoints:
      - locality: {}
        lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: test.com
                  port_value: 6379
            metadata:
              filter_metadata:
                istio:
                  workload: ;;;;
            load_balancing_weight: 1
        load_balancing_weight: 1
  cluster_type:
    name: envoy.clusters.redis
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.clusters.redis.v3.RedisClusterConfig
      cluster_refresh_rate: 5s
      cluster_refresh_timeout: 3s
      redirect_refresh_interval: 5s
      redirect_refresh_threshold: 5
      failure_refresh_threshold: 5
      host_degraded_refresh_threshold: 1
  respect_dns_ttl: true
  filters:
    - name: istio.metadata_exchange
      typed_config:
        "@type": type.googleapis.com/udpa.type.v1.TypedStruct
        type_url: type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange
        value:
          protocol: istio-peer-exchange
          enable_discovery: true
last_updated: "2025-02-27T06:35:02.084Z"
```

What can I do to solve this problem?
I'm, testing it on v1.30 EKS, aarch64 machine

**Comment by KBaichoo** [comment]
cc @msukalski @HenryYYang

**Comment by keyolk** [comment]
@jaellio Not sure if this is the right approach, I tried with the below yaml

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:debug-v1.31.5
          args:
          - "--config-path"
          - "/etc/envoy/envoy.json"
          - "--service-node"
          - "envoy-node"
          - "--service-cluster"
          - "envoy-cluster"
          - "--enable-core-dump"
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
            - name: core
              mountPath: /mnt/extras
          ports:
            - containerPort: 9901
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: core
          hostPath:
            path: /mnt/extras
            type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: default
data:
  envoy.json: |
    {
      "admin": {
        "access_log_path": "/dev/stdout",
        "address": {
          "socket_address": {
            "address": "0.0.0.0",
            "port_value": 9901
          }
        }
      },
      "dynamic_resources": {
        "lds_config": {
          "path_config_source": {
            "path": "/etc/envoy/listeners.yaml",
            "watched_directory": {
              "path": "/etc/envoy"
            }
          }
        },
        "cds_config": {
          "path_config_source": {
            "path": "/etc/envoy/clusters.yaml",
            "watched_directory": {
              "path": "/etc/envoy"
            }
          }
        }
      }
    }
  listeners.yaml: |
    resources:
      - 
        "@type": type.googleapis.com/envoy.config.listener.v3.Listener
        name: unix:///tmp/rediscluster.clustercfg.apn2.cache.amazonaws.com.sock_0
        traffic_direction: OUTBOUND
        address:
          pipe:
            path: "/tmp/rediscluster.sock"
        filter_chains:
          - filters:
              - name: "envoy.filters.network.redis_proxy"
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy"
                  stat_prefix: "rediscluster"
                  settings:
                    op_timeout: "5s"
                    enable_hashtagging: true
                    enable_redirection: true
                    max_upstream_unknown_connections: 100
                    read_policy: "PREFER_REPLICA"
                    enable_command_stats: true
                  prefix_routes:
                    catch_all_route:
                      cluster: outbound|6379||rediscluster.clustercfg.apn2.cache.amazonaws.com
  clusters.yaml: |
    resources:
      - 
        "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        alt_stat_name: outbound|6379||rediscluster
        name: outbound|6379||rediscluster.clustercfg.apn2.cache.amazonaws.com
        connect_timeout: "1s"
        lb_policy: "CLUSTER_PROVIDED"
        health_checks:
          - timeout: "0.500s"
            interval: "2s"
            unhealthy_threshold: 2
            healthy_threshold: 1
            custom_health_check:
              name: "envoy.health_checkers.redis"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis"
        circuit_breakers:
          thresholds:
            - max_connections: 4294967295
              max_pending_requests: 4294967295
              max_requests: 4294967295
              max_retries: 4294967295
              track_remaining: true
        dns_refresh_rate: "60s"
        dns_lookup_family: "V4_ONLY"
        respect_dns_ttl: true
        cluster_type:
          name: "envoy.clusters.redis"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.clusters.redis.v3.RedisClusterConfig"
            cluster_refresh_rate: "5s"
            cluster_refresh_timeout: "3s"
            redirect_refresh_interval: "5s"
            redirect_refresh_threshold: 5
            failure_refresh_threshold: 5
            host_degraded_refresh_threshold: 1
        common_lb_config:
          locality_weighted_lb_config: {}
        load_assignment:
          cluster_name: outbound|6379||rediscluster.clustercfg.apn2.cache.amazonaws.com
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: rediscluster.clustercfg.apn2.cache.amazonaws.com
                    port_value: 6379
              load_balancing_weight: 1
              metadata:
                filter_metadata:
                  istio:
                    workload: ;;;;
            load_balancing_weight: 1
            locality: {}
```

The envoy crashed after making the clusters to 
```
  clusters.yaml: |
    resouces: []
```


```
[2025-03-11 10:55:46.678][1][info][main] [source/server/server.cc:978] starting main dispatch loop
[2025-03-11 10:59:53.357][1][info][upstream] [source/common/upstream/cds_api_helper.cc:32] cds: add 1 cluster(s), remove 0 cluster(
[2025-03-11 10:59:53.358][1][info][upstream] [source/common/upstream/cds_api_helper.cc:71] cds: added/updated 1 cluster(s), skipped
[2025-03-11 11:01:03.337][1][warning][config] [source/common/protobuf/message_validator_impl.cc:61] Unknown field: type envoy.servi
[2025-03-11 11:01:03.337][1][info][upstream] [source/common/upstream/cds_api_helper.cc:32] cds: add 0 cluster(s), remove 1 cluster(
[2025-03-11 11:01:03.337][1][info][upstream] [source/common/upstream/cds_api_helper.cc:71] cds: added/updated 0 cluster(s), skipped
[2025-03-11 11:01:03.367][1][critical][backtrace] [./source/server/backtrace.h:127] Caught Segmentation fault, suspect faulting add
[2025-03-11 11:01:03.367][1][critical][backtrace] [./source/server/backtrace.h:111] Backtrace (use tools/stack_decode.py to get lin
[2025-03-11 11:01:03.367][1][critical][backtrace] [./source/server/backtrace.h:112] Envoy version: 688c4bbe47f4d05bb8ed268f5172bb02
[2025-03-11 11:01:03.367][1][critical][backtrace] [./source/server/backtrace.h:114] Address mapping: aaaac1841000-aaaac3ef9000 /usr
[2025-03-11 11:01:03.368][1][critical][backtrace] [./source/server/backtrace.h:119] #0: __kernel_rt_sigreturn [0xffffa3b76820]
[2025-03-11 11:01:03.382][1][critical][backtrace] [./source/server/backtrace.h:119] #1: event_process_active_single_queue [0xaaaac3
[2025-03-11 11:01:03.396][1][critical][backtrace] [./source/server/backtrace.h:119] #2: event_base_loop [0xaaaac396c648]
[2025-03-11 11:01:03.411][1][critical][backtrace] [./source/server/backtrace.h:119] #3: Envoy::Server::InstanceBase::run() [0xaaaac
[2025-03-11 11:01:03.425][1][critical][backtrace] [./source/server/backtrace.h:119] #4: Envoy::MainCommonBase::run() [0xaaaac2f9b63
[2025-03-11 11:01:03.439][1][critical][backtrace] [./source/server/backtrace.h:119] #5: Envoy::MainCommon::main() [0xaaaac2f9bdc4]
[2025-03-11 11:01:03.454][1][critical][backtrace] [./source/server/backtrace.h:119] #6: main [0xaaaac1841174]
[2025-03-11 11:01:03.454][1][critical][backtrace] [./source/server/backtrace.h:121] #7: [0xffffa38b73fc]
[2025-03-11 11:01:03.454][1][critical][backtrace] [./source/server/backtrace.h:119] #8: __libc_start_main [0xffffa38b74cc]
```

wanted to check backtrace from its core but failed

```
docker run -ti -v (pwd):/tmp --platform=linux/arm64 --entrypoint=/usr/bin/bash envoyproxy/envoy:debug-v1.31.5
gdb /usr/local/bin/envoy -c ./core.envoy.1.envoy-5d76479559-7ndf4.1741690863
Core was generated by `envoy --config-path /etc/envoy/envoy.json --service-node envoy-node --service-c'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x007974203a226570 in ?? ()
[Current thread is 1 (Thread 0xffffa3b69020 (LWP 1))]
(gdb) bt full
Python Exception <class 'gdb.error'>: Dwarf Error: bad DWP hash table, lookup didn't terminate [in module /usr/local/bin/envoy.dwp]
#0  0x007974203a226570 in ?? ()
No symbol table info available.
(gdb)
```

Any tips to see this more?

**Comment by keyolk** [comment]
Ah ... Seems lldb works for this case

```
(lldb) bt all
This version of LLDB has no plugin for the language "assembler". Inspection of frame variables will be limited.
* thread #1, name = 'envoy', stop reason = signal SIGSEGV
  * frame #0: 0x000074203a226570
    frame #1: 0x0000aaaab2e9b5f4 envoy`Envoy::Extensions::Clusters::Redis::RedisCluster::RedisDiscoverySession::startResolveRedis() at redis_cluster.cc:303:31
    frame #2: 0x0000aaaab5c719f4 envoy`event_process_active_single_queue + 636
    frame #3: 0x0000aaaab5c70538 envoy`event_base_loop + 1524
    frame #4: 0x0000aaaab45cdd3c envoy`Envoy::Server::InstanceBase::run() at server.cc:997:16
    frame #5: 0x0000aaaab4579db0 envoy`Envoy::MainCommonBase::run() at stripped_main_base.h:60:14
    frame #6: 0x0000aaaab457a544 envoy`Envoy::MainCommon::main(int, char**, std::__1::function<void (Envoy::Server::Instance&)>) at main_common.h:96:29
    frame #7: 0x0000aaaab2e20174 envoy`main at main.cc:24:10
    frame #8: 0x0000ffff8c8373fc libc.so.6`__libc_start_call_main(main=(envoy`main), argc=8, argv=0x0000ffffff2be468) at libc_start_call_main.h:58:16
    frame #9: 0x0000ffff8c8374cc libc.so.6`__libc_start_main_impl(main=(envoy`main), argc=8, argv=0x0000ffffff2be468, init=(envoy`__libc_csu_init), fini=<unavailable>, rtld_fini=<unavailable>, stack_end=<unavailable>) at libc-start.c:392:3
    frame #10: 0x0000aaaab2e20034 envoy`_start + 52
```

**Comment by keyolk** [comment]
another reproducible yaml using redis cluster pods
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
        - name: envoy
          image: envoyproxy/envoy:debug-v1.32.3
          args:
          - "--config-path"
          - "/etc/envoy/envoy.json"
          - "--service-node"
          - "envoy-node"
          - "--service-cluster"
          - "envoy-cluster"
          - "--enable-core-dump"
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
            - name: core
              mountPath: /mnt/extras
          ports:
            - containerPort: 9901
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: core
          hostPath:
            path: /mnt/extras
            type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: default
data:
  envoy.json: |
    {
      "admin": {
        "access_log_path": "/dev/stdout",
        "address": {
          "socket_address": {
            "address": "0.0.0.0",
            "port_value": 9901
          }
        }
      },
      "dynamic_resources": {
        "lds_config": {
          "path_config_source": {
            "path": "/etc/envoy/listeners.yaml",
            "watched_directory": {
              "path": "/etc/envoy"
            }
          }
        },
        "cds_config": {
          "path_config_source": {
            "path": "/etc/envoy/clusters.yaml",
            "watched_directory": {
              "path": "/etc/envoy"
            }
          }
        }
      }
    }
  listeners.yaml: |
    resources:
      - 
        "@type": type.googleapis.com/envoy.config.listener.v3.Listener
        name: unix:///tmp/redis-service.sock
        traffic_direction: OUTBOUND
        address:
          pipe:
            path: "/tmp/redis-service.sock"
        filter_chains:
          - filters:
              - name: "envoy.filters.network.redis_proxy"
                typed_config:
                  "@type": "type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy"
                  stat_prefix: "redis"
                  settings:
                    op_timeout: "5s"
                    enable_hashtagging: true
                    enable_redirection: true
                    max_upstream_unknown_connections: 100
                    read_policy: "PREFER_REPLICA"
                    enable_command_stats: true
                  prefix_routes:
                    catch_all_route:
                      cluster: outbound|6379||redis-service.default.svc.cluster.local
  clusters.yaml: |
    resources:
      - 
        "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
        alt_stat_name: outbound|6379||redis-service
        name: outbound|6379||redis-service.default.svc.cluster.local
        connect_timeout: "1s"
        lb_policy: "CLUSTER_PROVIDED"
        health_checks:
          - timeout: "0.500s"
            interval: "2s"
            unhealthy_threshold: 2
            healthy_threshold: 1
            custom_health_check:
              name: "envoy.health_checkers.redis"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis"
        circuit_breakers:
          thresholds:
            - max_connections: 4294967295
              max_pending_requests: 4294967295
              max_requests: 4294967295
              max_retries: 4294967295
              track_remaining: true
        dns_refresh_rate: "60s"
        dns_lookup_family: "V4_ONLY"
        respect_dns_ttl: true
        cluster_type:
          name: "envoy.clusters.redis"
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.clusters.redis.v3.RedisClusterConfig"
            cluster_refresh_rate: "5s"
            cluster_refresh_timeout: "3s"
            redirect_refresh_interval: "5s"
            redirect_refresh_threshold: 5
            failure_refresh_threshold: 5
            host_degraded_refresh_threshold: 1
        common_lb_config:
          locality_weighted_lb_config: {}
        load_assignment:
          cluster_name: outbound|6379||redis-service.default.svc.cluster.local
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: redis-service.default.svc.cluster.local
                    port_value: 6379
              load_balancing_weight: 1
              metadata:
                filter_metadata:
                  istio:
                    workload: ;;;;
            load_balancing_weight: 1
            locality: {}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: default
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
          name: client
        - containerPort: 16379
          name: gossip
        command: ["/conf/update-node.sh", "redis-server", "/conf/redis.conf"]
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: conf
          mountPath: /conf
          readOnly: false
      volumes:
      - name: conf
        configMap:
          name: redis-service
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-service
  namespace: default
data:
  update-node.sh: |
    #!/bin/sh
    REDIS_NODES="/data/nodes.conf"
    sed -i -e "/myself/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/${POD_IP}/" ${REDIS_NODES}
    exec "$@"
  redis.conf: |+
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    cluster-migration-barrier 1
    appendonly yes
```
