### ISSUE TITLE
GenericSecret using local filesystem data source cannot be watched

### ISSUE THREAD

**Issue by minuyim** [envoyproxy/envoy#38684]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *GenericSecret using local filesystem data source cannot be watched*

*Description*:
As described [here](https://github.com/envoyproxy/envoy/issues/24481),  sds config file can be watched.

But when I set the `filename` in `sds_config`, the secret file cannot be watched from Envoy.

*Config*:
```
  credentials:
    token_secret:
      name: token
      sds_config:
        path_config_source: 
          path: "config.yaml"
```
```
resources:
  - "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.Secret"
    name: token
    generic_secret:
      secret:
        filename: jwt_svid.token
```
In this example, even if `jwt_svid.token` is updated by move event, the secret is not updated.
