### ISSUE TITLE
Add client to request headers/body on API key authentication

### ISSUE THREAD

**Issue by dudicoco** [envoyproxy/envoy#38690]
The API key auth plugin assigns a client per key:

```yaml
          - name: api_key_auth
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.api_key_auth.v3.ApiKeyAuth
              credentials:
              - key: one_key
                client: one_client
              - key: another_key
                client: another_client
              key_sources:
              - header: Authorization
```

It would be beneficial to be able to pass the client information to the upstream via headers/body.
