### ISSUE TITLE
config_load_check_tool crashes on typed_dns_resolver_config

### ISSUE THREAD

**Issue by DanTulovsky** [envoyproxy/envoy#38720]
*Title*: config_load_check_tool crashes on typed_dns_resolver_config

*Description*:
config_load_check_tool should not crash.

This is happening with 1.32.0, 1.32.2, 1.33.

I don't know about previous versions, as this is a new config we are trying to use.

*Repro steps*:
Adding the following snippet to a cluster under "clusters" makes the tool crash.

```
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
                - socket_address:
                    address: 10.16.0.10
                    protocol: UDP
                    port_value: 53
              udp_max_queries: 100
              use_resolvers_as_fallback: true
```
*Config*:
```
        - connect_timeout: 10s
          type: static
          name: blackhole
        - name: collector-saas-headless
          connect_timeout: 40s
          track_cluster_stats:
            timeout_budgets: true
            request_response_sizes: true
          type: strict_dns
          lb_policy: least_request
          least_request_lb_config:
            slow_start_config:
              slow_start_window: 120s
              min_weight_percent:
                value: 10
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: collector-saas-headless
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: collector-saas-headless
                          port_value: 80
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
                - socket_address:
                    address: 10.16.0.10
                    protocol: UDP
                    port_value: 53
              udp_max_queries: 100
              use_resolvers_as_fallback: true
```

*Call Stack*:
> If the Envoy binary is crashing, a call stack is **required**.
Please refer to the [Bazel Stack trace documentation](https://github.com/envoyproxy/envoy/tree/main/bazel#stack-trace-symbol-resolution).
