### ISSUE TITLE
Any way to pass data from WASM network filter to envoy access logs

### ISSUE THREAD

**Issue by rishabh78** [envoyproxy/envoy#38738]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Any option to pass data from WASM network filter to envoy access logs *

*Description*:
I am woking on a ldap envoy proxy where I am extracting client details from request using WASM network filter and then using tcp_proxy filter. I am able to extract all data in WASM network filter and even those logs are coming in envoy logs , but I am not able to push that information to access logs . I tries using DYNAMIC_METADATA ad FILTER_STATE but noting seems to b working .

On WASM network filter wriiten in rust , I am setting value as 

self.set_property(vec!["filter_state", "proxy_protocol", "ldap_accountname"], Some(sam_value.as_bytes()));

```
admin:
  access_log_path: "/var/log/envoy/admin_access.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
    - name: ldap_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      listener_filters:
        - name: envoy.filters.listener.proxy_protocol
          typed_config:
            "@type": "type.googleapis.com/envoy.extensions.filters.listener.proxy_protocol.v3.ProxyProtocol"
            allow_requests_without_proxy_protocol: true  


      filter_chains:
        - filters:
            - name: envoy.filters.network.wasm
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm"
                config:
                  vm_config:
                    runtime: "envoy.wasm.runtime.v8"
                    code:
                      local:
                        filename: "/etc/envoy/ldap_wasm_filter.wasm"
                  configuration:
                    "@type": "type.googleapis.com/google.protobuf.StringValue"
                    value: "ldap_wasm_filter"
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
                stat_prefix: "ldap_proxy"
                cluster: "ldap_backend"
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                      path: "/var/log/envoy/ldap_access.log"
                      format: '{
                        "timestamp":"%START_TIME%",
                        "client_ip":"%DOWNSTREAM_REMOTE_ADDRESS%",
                        "upstream_host":"%UPSTREAM_HOST%",
                        "bytes_received":"%BYTES_RECEIVED%",
                        "bytes_sent":"%BYTES_SENT%",
                        "sAMAccountName":"%DYNAMIC_METADATA(envoy.filters.listener.proxy_protocol:ldap_accountname)%"
                      }'

  clusters:
    - name: ldap_backend
      type: STRICT_DNS
      connect_timeout: 5s
      load_assignment:
        cluster_name: ldap_backend
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: <backend>
                      port_value: 389
```

Any pointers on how can I push the extracted information from WASM to envoy access logs ?

**Comment by botengyao** [comment]
Hi @rishabh78, the `setProperty()` will always introduce a `wasm.` prefix to the filter state. You could also try to use `setEnvoyFilterState()` api for your customized filter key and value. Also the access log one should be `FILTER_STATE` rather than `DYNAMIC_METADATA`. Hope this helps.

cc @mpwarres @kyessenov

**Comment by rishabh78** [comment]
@botengyao - I tried setting the property like 

```
// Set filter state (simplified keys)
                self.set_property(vec!["filter_state", "ldap_ou"], Some(ou_value.as_bytes()));
                self.set_property(vec!["filter_state", "ldap_dc"], Some(dc_value.as_bytes()));
                self.set_property(vec!["filter_state", "ldap_accountname"], Some(sam_value.as_bytes()));
```


And envoy access logs like 

```
access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                      path: "/var/log/envoy/ldap_access.log"
                      json_format:
                        timestamp: "%START_TIME%"
                        client_ip: "%DOWNSTREAM_REMOTE_ADDRESS%"
                        upstream_host: "%UPSTREAM_HOST%"
                        bytes_received: "%BYTES_RECEIVED%"
                        bytes_sent: "%BYTES_SENT%"
                        connection_id: "%CONNECTION_ID%"
                        ldap:
                          ou: "%FILTER_STATE(ldap_ou)%"
                          dc: "%FILTER_STATE(ldap_dc)%"
                          samaccountname: "%FILTER_STATE(ldap_accountname)%"
```

response 
```
{"bytes_sent":"16438","upstream_host":"10.0.0.0:389","client_ip":"127.0.0.1:56464","ldap":{"ou":"-","dc":"-","accountname":"-"},"bytes_received":"199","timestamp":"2025-03-14T06:28:47.755Z","connection_id":"0"}
```
I am able to see extracted value in envoy logs though .


Any pointers of what I am doing wrong ?

**Comment by ramaraochavali** [comment]
you should set `%FILTER_STATE(wasm.ldap_ou)%` instead of `%FILTER_STATE(ldap_ou)%`

**Comment by rishabh78** [comment]
@ramaraochavali @botengyao 
Its not working even with prefix wasm.

I am using following version 
```
[package]
name = "ldap_wasm_filter"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = { git = "https://github.com/proxy-wasm/proxy-wasm-rust-sdk.git", branch = "main" }
log = "0.4"

[profile.release]
opt-level = 3
```

Access logs 

```
          - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy"
                stat_prefix: "ldap_proxy"
                cluster: "ldap_backend"
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
                      path: "/var/log/envoy/ldap_access.log"
                      json_format:
                        timestamp: "%START_TIME%"
                        client_ip: "%DOWNSTREAM_REMOTE_ADDRESS%"
                        upstream_host: "%UPSTREAM_HOST%"
                        bytes_received: "%BYTES_RECEIVED%"
                        bytes_sent: "%BYTES_SENT%"
                        connection_id: "%CONNECTION_ID%"
                        ldap:
                          ou: "%FILTER_STATE(wasm.ldap_ou)%"
                          dc: "%FILTER_STATE(wasm.ldap_dc)%"
                          samaccountname: "%FILTER_STATE(wasm.ldap_accountname)%"
```


Wsm filter 

```
 self.set_property(vec!["filter_state", "ldap_ou"], Some(ou_value.as_bytes()));
                self.set_property(vec!["filter_state", "ldap_dc"], Some(dc_value.as_bytes()));
                self.set_property(vec!["filter_state", "ldap_samaccountname"], Some(sam_value.as_bytes()));
```


Access log 
```
{"client_ip":"127.0.0.1:33764","bytes_received":"199","upstream_host":"10.0.0.0:389","timestamp":"2025-03-14T14:48:56.714Z","ldap":{"ou":"-","dc":"-","accountname":"-"},"connection_id":"2","bytes_sent":"16438"}
```

Am I missing something ?
