### ISSUE TITLE
External Auth filter's CheckRequest message should provide a means to access the destination hostname.

### ISSUE THREAD

**Issue by mancini0** [envoyproxy/envoy#3876]
*Description*:
I'm trying to have Envoy handle my applications' Kerberos authentication concerns. I'd like Envoy inject an "Authorization: Negotiate [token] "  header to my applications' service calls.  The problem _is that the [token]  hash is a function of the destination host_ ...if I have a service running on three hosts, I need to know which of the hosts in the cluster the call is actually going to be routed to in order to generate the kerberos token.

Initially I handled this in the control plane - my xds service found all instances of foo service, and created a cluster for each instance, adding these clusters as weighted_clusters to the route action, each weighted_cluster setting the authorization header using the weighted_cluster's request_headers_to_add functionality. 

This solution works, but only on the initial call. Subsequent requests will fail with a Kerberos "request is a replay attack" error, as the token can only be used once. Subsequent requests will continue to fail until the next xds poll, at that time the token is regenerated, and the service will again be able to make a single successful call.

Next I tried using the external auth filter, but soon realized that the CheckRequest proto message provides no means to inspect the route table.  My services only communicate with the envoy proxy at localhost, so the host header is not set to the actual destination until it passes through the envoy.router filter, but envoy.router is a terminal filter, and subsequent filters are not called after envoy.router, so the ext_auth filter must fire before that  (before the envoy.route filter has a chance to populate the actual destination header)

I am now trying to achieve this functionality via a custom HTTP filter, as the following types are accessible to a StreamDecoderFilter.

```
 Http::StreamDecoderFilterCallbacks* decoder_callbacks_;
Upstream::ClusterManager& cm_;
Router::RouteConstSharedPtr route = decoder_callbacks_->route();
Router::RouteEntry *route_entry =  route->routeEntry();
Upstream::ThreadLocalCluster *threadLocalCluster = cm_.get(route_entry->clusterName());
//From here  I think I'll be able to pull the hostName from threadLocalCluster's loadBalancer() or info() methods ..
```

Is there any other way to perform additional manipulation after the host destination is selected but before the request is actually sent?

**Comment by monsterrev** [comment]
I am facing a similar issue and was wondering if this has been solved
@mancini0  Were you able to get this resolved ?

**Comment by mancini0** [comment]
I ended up doing it in c++ as a custom filter. I will provide more details
tomorrow. What are you using for discovery?

**Comment by monsterrev** [comment]
We are using XDS - https://github.com/envoyproxy/data-plane-api/blob/master/XDS_PROTOCOL.md for discovery, but the issue that I am trying to resolve is to figure out a way at http_filter level (ext_authz) to figure out the destinationHostname before the request hits the http_connection_manager filter.

**Comment by ptone** [comment]
For those looking for a solution to this, I found a way to do it with 

```yaml
              - match: { prefix: "/prefix" }
                route: 
                  prefix_rewrite: "/"
                  host_rewrite: httpbin-zzzz-uc.a.run.app 
                  cluster: service_httpbin
                per_filter_config:
                  envoy.ext_authz:
                    check_settings:
                      context_extensions:
                        aud_host: httpbin-zzzz-uc.a.run.app  
```

Then if you are using a golang authz server, you can retrieve from `audhost, ok := req.Attributes.ContextExtensions["aud_host"]`
