### ISSUE TITLE
WASM Filter Properties Logged as Encoded BytesValue Protobufs Instead of Plain Text in Envoy Access Log

### ISSUE THREAD

**Issue by rishabh78** [envoyproxy/envoy#38795]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *WASM Filter Properties Logged as Encoded BytesValue Protobufs Instead of Plain Text in Envoy Access Log*

*Description*:
>When using the Rust SDK to set filter state properties in a WASM filter for Envoy, the properties are logged in the access log as Base64-encoded BytesValue protobufs rather than plain text values. This requires additional post-processing to decode the values, which is inconvenient for users expecting human-readable output directly in the logs.

*Repro steps*:
WASM Filter Code: In a Rust-based WASM filter, set properties using set_property:
```
self.set_property(vec!["ou"], Some(ou_value.as_bytes()));
self.set_property(vec!["dc"], Some(dc_value.as_bytes()));
self.set_property(vec!["accountname"], Some(sam_value.as_bytes()));
```
Where:
ou_value = "Users"
dc_value = "test.com"
sam_value = "dummy"

Envoy Configuration: Configure the access log to include these properties in JSON format:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    access_log:
    - name: envoy.access_loggers.file
      typed_config:
        "@type": "type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog"
        path: "/var/log/envoy/access.log"
        format: |
          {
            "wasm_ou": "%FILTER_STATE(wasm.ou)%",
            "wasm_dc": "%FILTER_STATE(wasm.dc)%",
            "wasm_sam": "%FILTER_STATE(wasm.accountname)%"
          }
    filter_chains:
    - filters:
      - name: envoy.filters.network.wasm
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.wasm.v3.Wasm"
          config:
            name: "test_filter"
            vm_config:
              runtime: "envoy.wasm.runtime.v8"
              code:
                local:
                  filename: "/etc/envoy/ldap_wasm_filter.wasm"
```

Expected Behavior
The access log should output plain text values directly:
```
"wasm_ou": "Users",
  "wasm_dc": "test.com",
  "wasm_sam": "dummy"
}
```

Actual Behavior
The access log outputs Base64-encoded BytesValue protobufs:
```
{
  "wasm_ou": "{\"@type\":\"type.googleapis.com/google.protobuf.BytesValue\",\"value\":\"twsgHDKA=\"}",
  "wasm_dc": "{\"@type\":\"type.googleapis.com/google.protobuf.BytesValue\",\"value\":\"Y29t\"}",
  "wasm_sam": "{\"@type\":\"type.googleapis.com/google.protobuf.BytesValue\",\"value\":\"BKVADBKJEAVna=\"}"
}
```

Additional Context
The filter sets properties as bytes using set_property, which is correct per the SDK’s API.
Envoy’s %FILTER_STATE(wasm.<key>)% placeholder serializes these bytes as BytesValue protobufs, encoding the value field in Base64.

Is there any way to get plain text strings, so %FILTER_STATE(wasm.<key>)% logs them directly without Base64 encoding. For example:
