### ISSUE TITLE
Is there a way to filter access logs

### ISSUE THREAD

**Issue by rishabh78** [envoyproxy/envoy#38804]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *Is there a way to filter access logs in envoy*

*Description*:
>I have an envoy tcp proxy setup which publish a lot of junk access logs due to health checks . Is there a way to limit such log based on some filter such that envoy emits access logs only when byte_sent / received is greater than some bytes 

and or or_filter is not working as expected 

```
    - name: envoy.access_loggers.file
      filter:
        or_filter:
          filters:
          - metadata_filter:
              matcher:
                filter: "test_filter"
                path:
                - key: "valid_request"
                value:
                  string_match:
                    exact: "true"
          - runtime_fraction_filter:
              runtime_key: "bytes_received"
              default_value:
                numerator: 1
                denominator: HUNDRED
              comparison:
                op: GT
                value:
                  default_value: 0
```
