### ISSUE TITLE
RING_HASH Load Balancer Not Routing to Healthy Endpoints When an Endpoint Becomes Unhealthy

### ISSUE THREAD

**Issue by jfulmali-supra** [envoyproxy/envoy#38815]
We are experiencing an issue with Envoy's RING_HASH load balancing policy. When using RING_HASH, if a request is consistently routed to a specific endpoint and that endpoint becomes unhealthy, Envoy does not reroute the request to a healthy endpoint. However, if we use a different load balancing policy (e.g., ROUND_ROBIN or LEAST_REQUEST), the traffic correctly fails over to a healthy node.

Configuration Details:
Here is a snippet of our Envoy configuration:

```
clusters:
  - name: external_service_cluster
    connect_timeout: 20s
    type: STRICT_DNS
    lb_policy: RING_HASH
    ring_hash_lb_config:
      minimum_ring_size: 2048
      maximum_ring_size: 4096
    load_assignment:
      cluster_name: external_service_cluster
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 80
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 5000
    health_checks:
      - timeout: 3s
        interval: 5s
        unhealthy_interval: "600s"
        unhealthy_threshold: 3
        healthy_threshold: 1
        tcp_health_check: {}
```
**Issue Reproduction Steps:**

1. Start Envoy with the above configuration.
2. Send a request to a specific endpoint (Envoy consistently routes it to one backend due to hashing).
3. Make that endpoint unhealthy (e.g., stop the service or simulate a failure).
4. Envoy does not reroute the request to a healthy endpoint, leading to failed requests.
5. Switching the lb_policy to ROUND_ROBIN or LEAST_REQUEST resolves the issue, and traffic correctly moves to a healthy node.

**Expected Behavior:**
When an endpoint becomes unhealthy, Envoy should automatically reroute traffic to a healthy endpoint, even when using RING_HASH.

**Actual Behavior:**
Envoy continues sending traffic to the same (now unhealthy) endpoint instead of rerouting it to a healthy one.

**Additional Context:**
- Envoy Version: 1.32.2

Would appreciate any insights on whether this is expected behavior or a possible bug. Thanks!
