### ISSUE TITLE
How to print the client's original request URL in the logs instead of the rewritten URL

### ISSUE THREAD

**Issue by wuzhuoquan** [envoyproxy/envoy#38812]
*Title*: *One line description*

*Description*:
I wanted to print the client's original request URL in the logs, so I used ```request_url: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%' ``` in logFormat to output it to the logs. Later, I discovered that the ```X-ENVOY-ORIGINAL-PATH``` header was also being forwarded to the server. In cases where the URL contains many parameters or is particularly long, this could cause the header to become too large and result in a 431 error. Therefore, I used ```suppress_envoy_headers``` to remove this header.
However, after making this change, I noticed that the request_url field in the logs no longer shows the original path from the client request, but instead shows the path after Envoy's rewrite. For example, when a client requests ```/payment/v1/list```, it gets rewritten to ```/payment/list``` before being sent to the server, and at this point the printed request_url is ```/payment/list``` instead of ```/payment/v1/list```. This behavior is very different from Nginx. Could you please help me how to print the client's original path while still using ```suppress_envoy_headers``` to remove the ```X-ENVOY-ORIGINAL-PATH``` header? Thank you.

**Comment by RyanTheOptimist** [comment]
cc:  @auni53 @zuercher

**Comment by agrawroh** [comment]
One way to do this is by using [H2M](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/header_to_metadata_filter) to write the value of this header to metadata, remove the header so that it does not get propagated to the backend server and then use the metadata in your access logs. 

For example, you can do:
```
http_filters:
  - name: envoy.filters.http.header_to_metadata
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
      request_rules:
        - header: x-envoy-original-path
          on_header_present:
            metadata_namespace: metadata.incoming_request
            key: original_path
            type: STRING
          remove: true
        - header: :path
          on_header_present:
            metadata_namespace: metadata.incoming_request
            key: path
            type: STRING
          remove: false
...
```

And then in [access logs](https://arc.net/l/quote/xratmwgt),  you can use `%DYNAMIC_METADATA(metadata.incoming_request:original_path)%` instead of the header.
