### ISSUE TITLE
CORS headers are not applied for grpc json transcoded responses

### ISSUE THREAD

**Issue by ttc0419** [envoyproxy/envoy#38813]
**Config:**
```yaml
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8082
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: [ "*" ]
                      typed_per_filter_config:
                        cors:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.CorsPolicy
                          allow_methods: "*"
                          allow_headers: "*"
                          allow_origin_string_match:
                            - prefix: "*"
                          expose_headers: "*"
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: upstream }
                http_filters:
                  - name: cors
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                  - name: grpc_json_transcoder
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_json_transcoder.v3.GrpcJsonTranscoder
                      proto_descriptor: ../kube-flow/internal/proto/all.desc
                      services:
                        - x.y.k.AuthService
                        - x.y.k.CoreService
                  - name: router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: upstream
      load_assignment:
        cluster_name: upstream
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: { }
```

**Output:**
```
[u@h d]% curl -v -H 'Origin: http://abc.com -H 'Authorization: Bearer token' http://127.0.0.1:8082/path
*   Trying 127.0.0.1:8082...
* Connected to 127.0.0.1 (127.0.0.1) port 8082
> GET /path HTTP/1.1
> Host: 127.0.0.1:8082
> Origin: http://abc.com
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: Bearer token
> 
* Request completely sent off
< HTTP/1.1 200 OK
< content-type: application/json
< x-envoy-upstream-service-time: 2
< grpc-status: 0
< grpc-message: 
< content-length: 126
< date: Thu, 20 Mar 2025 09:23:54 GMT
< server: envoy
< 
* Connection #0 to host 127.0.0.1 left intact
...
```

**Version:** envoy  version: b0f43d67aa25c1b03c97186a200cc187f4c22db3/1.33.0/Distribution/RELEASE/BoringSSL
