### ISSUE TITLE
envoy.access_loggers.fluentd: crash when using STATIC_DNS or LOGICAL_DNS as Fluentd cluster

### ISSUE THREAD

**Issue by aqua777** [envoyproxy/envoy#38918]
*Title*: *envoy.access_loggers.fluentd: crash when using STATIC_DNS or LOGICAL_DNS as Fluentd cluster*

*Description*:

I recently worked on testing Envoy configuration for logging to remote Fluentd servers using "[type.googleapis.com/envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig](http://type.googleapis.com/envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig)" extension. My configuration file for Envoy is listed in *Config* section of this issue.

When I configured Fluentd extension to use STRICT_DNS or LOGICAL_DNS cluster type as destination, I observed that upon receiving first HTTP request Envoy crashes with the following output:
```
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:129] Caught Segmentation fault, suspect faulting address 0x0
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:113] Backtrace (use tools/stack_decode.py to get line numbers):
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:114] Envoy version: b0f43d67aa25c1b03c97186a200cc187f4c22db3/1.33.0/Clean/RELEASE/BoringSSL
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:116] Address mapping: aaaac1777000-aaaac3f96000 /usr/local/bin/envoy
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:121] #0: __kernel_rt_sigreturn [0xffff81bb97a0]
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:123] #1: [0xaaaac35b15dc]
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:123] #2: [0xaaaac35b10f0]
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:123] #3: [0xaaaac35b089c]
[2025-03-20 12:07:51.429][30][critical][backtrace] [./source/server/backtrace.h:123] #4: [0xaaaac36630f0]
```

The backtrace also contains information on active connections and streams which is not shown on the above example.

If I modify Fluentd configuration to use direct IP address instead of FQDN the crashes will no longer occur.

I am running Envoy v1.33.0 for this tests.

Please let me know if there is something fundamentally wrong with my configuration, I would appreciate your advise.

*Repro steps*:

I created a simple test project which uses Docker Compose to create simulated environment with Envoy and Fluentd servers which allows to replicate crash, see here https://github.com/aqua777/envoy-fluentd-access-logging.

*Config*:
```yaml
admin:
  profile_path: /var/log/envoy/envoy.prof
  address:
    socket_address: { address: 127.0.0.1, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          # ------------------------------------------------
          access_log:
            - name: envoy.access_loggers.fluentd
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig
                cluster: fluent-bit
                stat_prefix: fluent-bit
                tag: test.fluentd-logging
                record:
                  log: "%START_TIME%,DC1,%REQ(:METHOD)%,\"%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%\",%RESPONSE_CODE%,%RESPONSE_FLAGS%,%DURATION%,%BYTES_RECEIVED%,%BYTES_SENT%,\"%REQ(USER-AGENT)%\",%UPSTREAM_HOST%,%UPSTREAM_CLUSTER%,%DOWNSTREAM_REMOTE_ADDRESS%,%REQ(REFERER)%,%REQ(HOST)%,\"%REQ(X-FORWARDED-FOR)%\""
          # ------------------------------------------------
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: envoy_admin }
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
            
  clusters:
  - name: fluent-bit
    type: STRICT_DNS
    respect_dns_ttl: true
    load_assignment:
      cluster_name: fluent-bit
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: fluent-bit.mydomain.net
                # comment line above and uncomment line below to prevent Envoy from crashing
                # address: 192.168.16.20
                port_value: 24224
  - name: envoy_admin
    load_assignment:
      cluster_name: envoy_admin
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8001
```
