### ISSUE TITLE
Discrepancy between documented and actual behavior of failure_mode_allow

### ISSUE THREAD

**Issue by yukunlin** [envoyproxy/envoy#38927]
*Title*: *Discrepancy between documented and actual behavior of failure_mode_allow*

*Description*:

We have envoy acting as a reverse proxy for our services. The specific version is

```
/usr/local/bin/envoy  version: 86dc7ef91ca15fb4957a74bd599397413fc26a24/1.32.0/Distribution/RELEASE/BoringSSL
```

Our reverse proxy is configured with the external authorization filter, calling our own authorization service. We have `failure_mode_allow` set to `true`.

The [documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto) of `failure_mode_allow` of the external authorization filter states that

> When set to true, the filter will accept client request even if the communication with the authorization service has failed, or if the authorization service has returned a HTTP 5xx error

However we've observed that when the authorization service returns a HTTP 500 error, the downstream caller also gets a HTTP 500 status code (note, I've verified (i) that the request is not getting to the upstream service, and (ii) that request can be served without 500s from the upstream, so the 500 is from envoy). This contradicts the documentation which states the request should've gone on to be served by the upstream service.

I want to check if is this discrepancy between documented and actual behavior is a bug, or if it's the documentation that's out of date and needs updating.

**Comment by yukunlin** [comment]
We are using grpc:

```yaml
name: envoy.filters.http.ext_authz
  typed_config:
    "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz"
    transport_api_version: v3
    failure_mode_allow: true
    grpc_service:
      envoy_grpc:
        cluster_name: ...
      timeout: ...
```
