### ISSUE TITLE
stateful session enhancement: to support the MCP protocol session management

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#38983]
*Title*: *stateful session enhancement: to support the MCP protocol session management*

*Description*:

See https://github.com/modelcontextprotocol/specification/blob/main/docs/specification/2025-03-26/basic/transports.md#session-management

MCP protocol is become more and more popular for AI agent developing. The session affinity is very important part for proxying MCP traffic becase it's stateful protocol.

But fortunately, Envoy have provided the stateful sesssion filter which could provide a stateful session support based on the header or cookie. This would be great if we can support the MCP session affinity support.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by wbpcode** [comment]
@wbpcode @cpakulski

**Comment by cpakulski** [comment]
Statefulness support for MCP would be super helpful. Thanks for raising this issue.

**Comment by botengyao** [comment]
It seems this is a config stuff, and we can use something like

```
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.stateful_session.v3.StatefulSession
              session_state:
                name: envoy.http.stateful_session.header
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.http.stateful_session.header.v3.HeaderBasedSessionState
                  name: Mcp-Session-Id
```
?
