### ISSUE TITLE
Support TLS Exported Key Material (EKM)

### ISSUE THREAD

**Issue by salrashid123** [envoyproxy/envoy#39015]
Extract the `Exported Key Material (EKM)` [rfc5705](https://datatracker.ietf.org/doc/html/rfc5705)) from a TLS connection.

If the  `EKM` value is extracted and surfaced as metadata or to the backend, users can use that to verify if the provided application-level bearer token is be bound to the given TLS connection.

This is similar to verifying if a bearer token is bound to a given mTLS connection (see [envoy_cert_bound_token](https://github.com/salrashid123/envoy_cert_bound_token)) except that using the EKM binds any application/bearer token to a spceific TLS connection (ref [go_ekm_tls](https://github.com/salrashid123/go_ekm_tls))

The EKM is extracted at the TLS connection layer using [BoringSSL SSL_export_keying_material](https://commondatastorage.googleapis.com/chromium-boringssl-docs/ssl.h.html#SSL_export_keying_material)

and can get surfaced for consumption via LUA, wasm handler or backend.

---

I have it working as a demo with envoy which emits an EKM with a given label and application context value as a LUA variable:

* http://gist.github.com/salrashid123/c165c6c267fa1d121385bf2eaf60d34b

---

Note, calculating the EKM involves a label and context and i'm not at all sure how that could get configured (_maybe_ something here:

```yaml
    filter_chains:
    - filter_chain_match:
        server_names: ["httpbin.org"]
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          ekm:
           label: "EXPORTER-Channel-Binding"
           context: "my_app_context"
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: certs/httpbin.crt
              private_key:
                filename: certs/httpbin.key    
```
