### ISSUE TITLE
Update Documentation on v2 fault injection

### ISSUE THREAD

**Issue by willrichboa** [envoyproxy/envoy#3902]
*Description*:
I decided to use the v2 file format for some internal testing.  Unfortunately I found that while there seems to be decent info on how to add fault filters to your config file for v1, examples for the v2 format were lacking.  This is unfortunate because all of the variable names have changed.  

Example: In v1 the delay filter would use variables "fixed_delay_percent" and "fixed_duration_ms", but in v2 these are "percent" and "fixed_delay".  

The error message generated for an incorrectly defined "delay" is unhelpful as well, since it refers to a "fault_delay_secifier".  

```
error initializing configuration '/etc/envoy.yaml': Proto constraint validation failed (HTTPFaultValidationError.Delay: ["embedded message failed validation"] | caused by field: "fault_delay_secifier", reason: is required): delay {
}
```

[optional *Relevant Links*:]
https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/fault_filter 
Current documentation only shows the v1 variable names.  Fault filters are not included in any of the v2 example configs either.  

*Config*:
Here is an example config with the correct v2 naming.  Maybe someone will find this useful until the docs are updated.

```
static_resources:
  listeners:
  - address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: { path: "/websocket" }
                route: { cluster: service1 , use_websocket: true }
              - match: { path: "/example" }
                route: { cluster: service1 }
          http_filters:
          - name: envoy.fault
            config: 
              delay: { fixed_delay: 20s, percent: 50 } 
              upstream_cluster: service1
              abort: { percent: 50, http_status: 555 }
              upstream_cluster: service1
          - name: envoy.router
  clusters:
  - name: service1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address: { address: 127.0.0.1, port_value: 8000 }
admin:
  access_log_path: /tmp/admin_access.log
  address: { socket_address: { address: 0.0.0.0, port_value: 80 }}
```
