### ISSUE TITLE
envoy/config/route/v3.Route.NonForwardingAction for golang filters

### ISSUE THREAD

**Issue by jochumdev** [envoyproxy/envoy#39044]
*Title*: envoy/config/route/v3.Route.NonForwardingAction for golang filters

*Description*:
I'm trying to implement a client directly into a golang filter here:

https://github.com/go-orb/envoy/blob/main/orbproxy/filter.go

My direct_response hack doesn't work as this skips DecodeData() for the golang filter.

Hack: https://github.com/go-orb/envoy/blob/main/examples/helloworld/envoy.yaml#L46

So I wish this to be implemented:

https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L284

**Comment by nezdolik** [comment]
cc @doujiang24 @wangfakang @StarryVae

**Comment by jochumdev** [comment]
I'm working on that one.

**Comment by doujiang24** [comment]
@jochumdev You want to keep `DecodeData()` for the golang filter, maybe you could try `sendLocalReply` in golang filter?

**Comment by doujiang24** [comment]
That means `SendLocalReply` could take place of `direct_response`

**Comment by jochumdev** [comment]
> [@jochumdev](https://github.com/jochumdev) You want to keep `DecodeData()` for the golang filter, right? maybe you could try `sendLocalReply` in golang filter?

Many thanks for locking into this! `SendLocalReply` doesn't look like a solution for me, as I want to be envoy a full blown HTTP/gRPC Server/Client, not jus a proxy.

**The main goal here is to use the golang filter to implement it as HTTP -> gRPC/DRPC gateway to a bunch of micro services.**

This would mean envoy acts as customer facing or maybe 2nd level proxy for these protocols. One thing is that the 

I would love to have a config like this:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP1
          stat_prefix: ingress_http
          generate_request_id: false
          # access_log:
          # - name: envoy.access_loggers.stdout
          #   typed_config:
          #     "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
          http_filters:
          - name: envoy.filters.http.golang
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.Config
              library_id: orbproxy
              library_path: "lib/orbproxy.so"
              plugin_name: orbproxy
              plugin_config:
                "@type": type.googleapis.com/xds.type.v3.TypedStruct
                value:
                  service: "none"
                  endpoint: "/none.v1.None/None"
                  stream: false
                  config: '{"logger": {"level": "trace"}, "client": {"poolSize": 256, "poolHosts": 32, "middlewares": [{"name": "retry"}, {"name": "log"}]}, "registry": {"plugin": "kvstore", "kvstore": {"plugin": "natsjs", "servers": ["nats://nats:4222"]}}}'
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              # this route contains the changes, you can see we use the typed_per_filter_config here
              routes:
              - match:
                  prefix: "/api/v1/user/token"
                direct_response:
                  status: 200
                  body:
                    inline_string: "This is a direct response from envoy"
                typed_per_filter_config:
                  envoy.filters.http.golang:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
                    plugins_config:
                      orbproxy:
                        config:
                          "@type": type.googleapis.com/xds.type.v3.TypedStruct
                          value:
                            service: "user"
                            endpoint: "/user.v1.User/token"
                            stream: false
                            config: ''
              - match:
                  prefix: "/api/v1/user/refresh"
                direct_response:
                  status: 200
                  body:
                    inline_string: "This is a direct response from envoy"
                typed_per_filter_config:
                  envoy.filters.http.golang:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.golang.v3alpha.ConfigsPerRoute
                    plugins_config:
                      orbproxy:
                        config:
                          "@type": type.googleapis.com/xds.type.v3.TypedStruct
                          value:
                            service: "user"
                            endpoint: "/user.v1.User/refresh"
                            stream: false
                            config: ''
```

You can see 2 routes to different, in the end there are many of this. Forming an API Gateway for [go-orb](https://github.com/go-orb/go-orb)
