### ISSUE TITLE
Running in validate mode creates missing log files

### ISSUE THREAD

**Issue by andreaso** [envoyproxy/envoy#39156]
Running `envoy --mode validate` appear to create log files that are referenced within the configuration file but which at the moment doesn't exist.

At least based on my personal experience that is a somewhat unexpected behavior.

It's also a potentially impractical behavior, in that it risks creating log files that Envoy aren't allowed to write to, in cases where the validate command is run as different user than the user which the Envoy service will be running as. Such a scenario isn't uncommon when it comes to configuration management and orchestration tooling.

*Repro steps*:

We start with an empty `/var/log/test` directory.

```
# ls -1 /var/log/test/
#
```

Then we run the validate command.

```
# envoy --mode validate -c /etc/test/envoy.yaml
[2025-04-17 10:36:32.776][2486][info][main] [source/server/server.cc:901] runtime: {}
[2025-04-17 10:36:32.776][2486][info][config] [source/server/configuration_impl.cc:173] loading tracing configuration
[2025-04-17 10:36:32.776][2486][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2025-04-17 10:36:32.776][2486][info][config] [source/server/configuration_impl.cc:130] loading 1 cluster(s)
[2025-04-17 10:36:32.777][2486][info][config] [source/server/configuration_impl.cc:140] loading 1 listener(s)
[2025-04-17 10:36:32.781][2486][info][config] [source/server/configuration_impl.cc:156] loading stats configuration
configuration '/etc/test/envoy.yaml' OK
#
```

Then the `/var/log/test` directory isn't empty anymore.

```
# ls -1 /var/log/test/
envoy.log
#
```

This being Envoy 1.34.0.

```
# envoy --version

envoy  version: d7809ba2b07fd869d49bfb122b27f6a7977b4d94/1.34.0/Clean/RELEASE/BoringSSL

#
```

*Config*:

Here's the `/etc/test/envoy.yaml` I used in the repro step.

```yaml
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8765
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          access_log:
            - name: envoy.access_loggers.file
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                path: /var/log/test/envoy.log
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: some_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: some_service
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234

```
