### ISSUE TITLE
ext_proc filter: New TCP connections being established per request?

### ISSUE THREAD

**Issue by xr** [envoyproxy/envoy#39281]
*Description*:
We're using the ext_proc filter in a high-throughput environment and observing performance issues. While by checking [from the code](https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/ext_proc/ext_proc.cc) that the filter creates and terminates a new gRPC stream for each HTTP request (via openStream() and closeStream()), our profiling data suggests that entirely new TCP connections may be getting established for each request as well.

Our profiler shows significant CPU time spent in:
```
google.golang.org/grpc/internal/transport.NewServerTransport.func2
grpc.(*Server).handleRawConn
```

so seems like these functions suggest new TCP connection establishment overhead, not just HTTP/2 stream creation.

### Questions
- Is the ext_proc filter designed to reuse the underlying TCP connections when creating new streams, or does it create new connections for each request?

- If connection reuse is expected, why might we be seeing significant time in connection establishment code (NewServerTransport, handleRawConn)?

- Are there any configuration parameters (either in ext_proc filter config or in the cluster config) that control connection pooling behavior specifically for ext_proc?

- Under what circumstances would the ext_proc filter bypass connection reuse and create new connections? Is this related to how the gRPC client factory is configured internally?

- Are there any metrics we should be monitoring to confirm whether connections are being reused or recreated?

### More Context:
we are using envoy_grpc impl
envoy version: 1.32

thanks!

**Comment by paul-r-gall** [comment]
You can check the `upstream_cx_http2_total`  and `upstream_cx_destroy` cluster stats and compare them with `upstream_rq_completed` stat.

the async gRPC client used by the ext_proc filter uses the same connection management system as the rest of envoy, so I can't imagine a reason that it's making a new connection for each request. What does the cluster configuration on your gRPC Envoy cluster look like?

**Comment by xr** [comment]
hey @paul-r-gall thanks for the answer, i checked the metrics, seems like `upstream_cx_http2_total` indeed maintains at low level, i guess it means not creating new connections constantly, however, the `upstream_cx_destroy` seems maintaining at a high level, so i guess this came from the streams been terminated? is it normal?

![Image](https://github.com/user-attachments/assets/f25a781e-e447-4803-8c42-1d502d846750)

![Image](https://github.com/user-attachments/assets/e3af156b-32d2-4c20-a01c-d97b09c16ded)

here is the example of our grpc envoy cluster:
```
{
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "outbound|20001||ext-proc-test.svc.cluster.local",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "initial_fetch_timeout": "0s",
        "resource_api_version": "V3"
       },
       "service_name": "outbound|20001||ext-proc-test.svc.cluster.local"
      },
      "connect_timeout": "10s",
      "lb_policy": "LEAST_REQUEST",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 4294967295,
         "max_pending_requests": 4294967295,
         "max_requests": 4294967295,
         "max_retries": 4294967295,
         "track_remaining": true
        }
       ]
      },
      "metadata": {
       "filter_metadata": {
        "istio": {
         "services": [
          {
           "namespace": "test-ns",
           "host": "ext-proc-test.svc.cluster.local",
           "name": "ext-proc-gateway"
          }
         ]
        }
       }
      },
      "common_lb_config": {},
      "alt_stat_name": "outbound|20001||ext-proc-test.svc.cluster.local;",
      "typed_extension_protocol_options": {
       "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
        "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
        "explicit_http_config": {
         "http2_protocol_options": {}
        }
       }
      },
      "filters": [
       {
        "name": "istio.metadata_exchange",
        "typed_config": {
         "@type": "type.googleapis.com/udpa.type.v1.TypedStruct",
         "type_url": "type.googleapis.com/envoy.tcp.metadataexchange.config.MetadataExchange",
         "value": {
          "protocol": "istio-peer-exchange",
          "enable_discovery": true
         }
        }
       }
      ],
      "transport_socket_matches": [
       {
        "name": "tlsMode-istio",
        "match": {
         "tlsMode": "istio"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "tls_params": {
            "tls_minimum_protocol_version": "TLSv1_2",
            "tls_maximum_protocol_version": "TLSv1_3"
           },
           "alpn_protocols": [
            "istio-peer-exchange",
            "istio",
            "h2"
           ],
           "tls_certificate_sds_secret_configs": [
            {
             "name": "default",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           ],
           "combined_validation_context": {
            "default_validation_context": {
             "match_subject_alt_names": [
              {
               "exact": "spiffe://cluster.local/ns/test-ns/sa/ext-proc-gateway-k8s-service-account"
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "ROOTCA",
             "sds_config": {
              "api_config_source": {
               "api_type": "GRPC",
               "grpc_services": [
                {
                 "envoy_grpc": {
                  "cluster_name": "sds-grpc"
                 }
                }
               ],
               "set_node_on_first_message_only": true,
               "transport_api_version": "V3"
              },
              "initial_fetch_timeout": "0s",
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "outbound_.20001_._.ext-proc-test.svc.cluster.local"
         }
        }
       },
       {
        "name": "tlsMode-disabled",
        "match": {},
        "transport_socket": {
         "name": "envoy.transport_sockets.raw_buffer",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.raw_buffer.v3.RawBuffer"
         }
        }
       }
      ]
     },
     "last_updated": "2025-04-21T10:55:01.488Z"
    },
```


and ext-proc filter config;
```
{
  "name": "ext_proc.test",
  "typed_config": {
   "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor",
   "grpc_service": {
    "envoy_grpc": {
     "cluster_name": "outbound|20001||ext-proc-test.svc.cluster.local"
    },
    "timeout": "30s",
    "initial_metadata": [
     {
      "key": "route",
      "value": "{}"
     }
    ]
   },
   "processing_mode": {
    "request_header_mode": "SEND",
    "response_header_mode": "SEND",
    "request_body_mode": "BUFFERED_PARTIAL",
    "response_body_mode": "BUFFERED_PARTIAL"
   },
   "request_attributes": [
    "request.path",
    "request.url_path",
    "request.size",
    "request.total_size"
   ],
   "response_attributes": [
    "response.code",
    "response.size",
    "response.total_size",
    "request.duration"
   ],
   "message_timeout": "5s",
   "allow_mode_override": true,
   "metadata_options": {
    "forwarding_namespaces": {
     "untyped": [
      "envoy.filters.http.jwt_authn"
     ]
    }
   }
  },
  "disabled": true
 }
```

thank you!

**Comment by paul-r-gall** [comment]
Two more stats you can check: `upstream_cx_destroy_remote` and `upstream_cx_destroy_local`. They should sum to the `upstream_cx_destroy` stat, and indicate whether the connection close is being triggered locally or remotely. 

Another question: how many worker threads are you using on Envoy? Connections are not shared across threads.

**Comment by paul-r-gall** [comment]
OK so looks like you've got a steady rate of local connection closes and a few spikes of remote connection terminations. I can't make any suggestions about why the remote connection close is happening. 

Another thing you can try that will give more detail into why Envoy is closing connections locally: You can enable [fine grained logging](https://www.envoyproxy.io/docs/envoy/latest/operations/cli#cmdoption-enable-fine-grain-logging) and then use the [admin interface](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#post--logging) to turn on trace logging for  source/common/network/connection_impl.cc.

**Comment by xr** [comment]
@paul-r-gall thanks, ok here is the logs, i don't see anything obviously wrong, only thing in my mind is that the ext-proc filter will create new stream for every single requests and terminate it in the end, also found similar issue https://github.com/envoyproxy/envoy/issues/34400, maybe nothing too much we could do for now to improve the performance.

with the ext-proc observability_mode is fast, but not suitable for our use cases, we need to proceed the message in sync mode as well.

[log.txt](https://github.com/user-attachments/files/20054689/log.txt)

**Comment by xr** [comment]
@paul-r-gall oh, sorry, i've been testing with multiple options of ext-proc filter config locally, including grpc impl vs envoy impl, tcp and unix socket etc, seems like i was using google grpc client mode when i captured the logs.

here is the latest log with envoy_grpc_impl, test with this ext-proc config:
```
- filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route: 
                  cluster: service_httpbin
          http_filters:
          - name: envoy.filters.http.ext_proc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
              failure_mode_allow: false
              allow_mode_override: true
              message_timeout: 5s
              processing_mode:
                request_header_mode: "SEND"
                response_header_mode: "SEND"
                request_body_mode: "BUFFERED_PARTIAL"
                response_body_mode: "BUFFERED_PARTIAL"
                request_trailer_mode: "SKIP"
                response_trailer_mode: "SKIP"
              grpc_service:
                timeout: "30s"
                initial_metadata:
                  - key: "x-foo"
                    value: "bar"
                  - key: "route"
                    value: '{"disabled":false,"host":"","path":"^/test$","method":"GET","upstream":{"host":"","port":0,"supportsHttps":false},"id":"31f759ec-ecb0-4923-9bed-45299d329938","service":"test-backend-service","rewrite":{},"authentication":{"disabled":true},"authorization":{"disabled":true},"headers":{"in":["example1","example2","timeout"],"out":["x-extproc-names","x-extproc-duration-ns"]},"validation":{"bodySizeLimit":""},"payload":{"in":{"ignoreUndefinedFields":false,"filter":null},"out":{"ignoreUndefinedFields":false,"filter":null}}}'
                  - key: "request-id"
                    value: '%REQ(x-request-id)%'
                envoy_grpc:                  
                  cluster_name: ext_proc_cluster
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router  
```


not seeing much diff between envoy vs google grpc impl though.

from ext-proc logic, i think the latency is coming from ext-proc needs to wait until the response from the upstream.

for example:

on line 124-125:
```
[2025-05-07 10:01:24.362][63250332][trace] [source/common/http/async_client_impl.cc:207] async http request response data (length=434 end_stream=false)
[2025-05-07 10:01:24.362][63250332][debug] [source/extensions/filters/http/ext_proc/ext_proc.cc:1234] Received request headers response
```
ext-proc sent and received request headers response instantly


then on line 287-288:
```
[2025-05-07 10:01:24.369][63250332][trace] [source/common/http/async_client_impl.cc:207] async http request response data (length=337 end_stream=false)
[2025-05-07 10:01:24.369][63250332][debug] [source/extensions/filters/http/ext_proc/ext_proc.cc:1234] Received response headers response
```
envoy ext-proc started sending and received response data instantly as well.

by the problem is that time between `envoy Received request headers response` and `started sending response headers to ext-proc` (line 125 - line 287) based on the timestamp, it blocked 7ms before ext-proc filter has data ready before it could start sending to ext-proc, of course, this includes all the upstream latency and later envoy filter etc, which i don't think we could control if we have to stick with the sync mode?

[envoy_client_log.txt](https://github.com/user-attachments/files/20078079/envoy_client_log.txt)
