### ISSUE TITLE
Unable to use string extensions in CEL expressions

### ISSUE THREAD

**Issue by a-thaler** [envoyproxy/envoy#39307]
*Title*: *Support string extension functions for CEL*

*Description*:
Similar to https://github.com/envoyproxy/envoy/issues/38303, I'm unable to use string extension functions (like [x.lowerAscii](https://cloud.google.com/eventarc/advanced/docs/receive-events/use-cel)) in CEL expressions, even though they should be available through the [built-in functions registration](https://github.com/google/cel-cpp/blob/87dedeb9fa7f52aaa2489de2ede4ae04343fdf06/eval/public/builtin_func_registrar.cc#L36-L37).

**Expected Behavior**
It will be great to have these additional string manipulation functions like lowerAscii available.

**Current Behavior**
String extension functions are not accessible in CEL expressions despite proper configuration. When I try to do something like this, it fails with an error saying: "No overload found in reference resolve step for lowerAscii"

```yaml
format_string:
  formatters:
  - name: envoy.formatter.cel
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.formatter.cel.v3.Cel
  text_format_source:
    inline_string: '%CEL(request.protocol.lowerAscii())%'
```

**Comment by zirain** [comment]
this is part of extension functions, you can find it [here](https://github.com/google/cel-cpp/blob/87dedeb9fa7f52aaa2489de2ede4ae04343fdf06/extensions/strings.cc#L321).

I'm not sure whether we need import every functions CEL support into envoy, @kyessenov WDYT?

**Comment by a-thaler** [comment]
My use case is to emit access logs using the OPenTelemetry access logger. Hereby, I want to leverage the OTEL attributes to transport the access log attributes, following the [OTEL semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/attributes-registry/network.md). Attributes like the protocol name should be in lower case and I cannot find a better way to achieve that.

In the logger configuration I like to achieve this:
```yaml
- key: "network.protocol.name"
  value:
    string_value: '%CEL(re.capture(request.protocol,R"(.+)/.+").lowerAscii())%'
- key: "network.protocol.version"
  value:
    string_value: '%CEL(re.capture(request.protocol,R".+/(.+)"))%'
```
