### ISSUE TITLE
Need help getting minimal VHDS setup working

### ISSUE THREAD

**Issue by onemanbucket** [envoyproxy/envoy#39315]
*Title*: *Minimal config for VHDS with go control plane*

I'm trying to construct a minimal setup where I run envoy configured with VHDS to dynamically fetch vhosts on request time.

I'm using the go control plane example, adding a VHDS server ( `routeservice.RegisterVirtualHostDiscoveryServiceServer(grpcServer, server)`).

However, I'm not seeing envoy make any attempt to discover VHosts from the control plane. I have the following envoy config:

```node:
  id: erik-test
  cluster: test-cluster

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9001 }

#dynamic_resources:
#  cds_config:
#    ads: { }
#  ads_config:
#    api_type: DELTA_GRPC
#    grpc_services:
#      envoy_grpc:
#        cluster_name: xds_control_plane

static_resources:
  clusters:
    - name: xds_control_plane
      type: STATIC
      lb_policy: ROUND_ROBIN
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: { }
      load_assignment:
        cluster_name: xds_control_plane
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 9510
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.on_demand
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: virtual
                  vhds:
                    config_source:
#                      ads: { }
                      "api_config_source": {
                        "api_type": "DELTA_GRPC",
                        "transport_api_version": "V3",
                        "grpc_services": [
                          {
                            "envoy_grpc": {
                              "cluster_name": "xds_control_plane"
                            }
                          }
                        ]
                      }

```

When i make a request (`curl -v -H "host: www.foo.com" http://localhost:8080/`) I can see the request being accepted by envoy, but then nothing more happens:
```
[2025-05-04 10:15:04.690][218445][debug][conn_handler] [source/common/listener_manager/active_tcp_listener.cc:160] [Tags: "ConnectionId":"0"] new connection from 127.0.0.1:42274
[2025-05-04 10:15:04.690][218445][debug][http] [source/common/http/conn_manager_impl.cc:394] [Tags: "ConnectionId":"0"] new stream
[2025-05-04 10:15:04.690][218445][debug][http] [source/common/http/conn_manager_impl.cc:1196] [Tags: "ConnectionId":"0","StreamId":"8444646063331171296"] request headers complete (end_stream=true):
':authority', 'www.foo.com'
':path', '/'
':method', 'GET'
'user-agent', 'curl/8.12.1'
'accept', '*/*'

[2025-05-04 10:15:04.690][218445][debug][http] [source/common/http/conn_manager_impl.cc:1179] [Tags: "ConnectionId":"0","StreamId":"8444646063331171296"] request end stream timestamp recorded
[2025-05-04 10:15:04.690][218445][debug][connection] [./source/common/network/connection_impl.h:99] [Tags: "ConnectionId":"0"] current connecting state: false
```

**Comment by onemanbucket** [comment]
So I think the issue was that I was using static route config, which doesn't seem to support VHDS (empty implementation of  in`requestVirtualHostsUpdate` https://github.com/envoyproxy/envoy/blob/main/source/common/router/static_route_provider_impl.h#L48)

Switching to RDS makes it work. 

```
node:
  id: erik-test
  cluster: test-cluster

admin:
  address:
    socket_address: { address: 0.0.0.0, port_value: 9001 }

dynamic_resources:
  lds_config:
    ads: { }
  cds_config:
    ads: { }
  ads_config:
    api_type: DELTA_GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: xds_control_plane

static_resources:
  clusters:
    - name: xds_control_plane
      type: STATIC

<SNIP>         
        
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                  - name: envoy.filters.http.on_demand
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.on_demand.v3.OnDemand
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                rds:
                  route_config_name: virtual_route
                  config_source:
                    ads: {}
```
