### ISSUE TITLE
envoy possibly breaks grpc-web requests

### ISSUE THREAD

**Issue by dora-gt** [envoyproxy/envoy#39351]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*:
**envoy possibly breaks grpc-web requests**

*Description*:
Recently our gRPC server is experiencing `grpc: error unmarshalling request: string field contains invalid UTF-8` error. It is because the server receives broken data on a string field.

We have the following request structure:

```
message FooRequest {
  string field1 = 1;
  string field2 = 2;
  string field3 = 3;
  NullString field4 = 4;
}
```
*This is a pseudo structure because the real request is used for the production environment.*

We confirm that string `field2` contains **the whole gRPC request payload** from the beginning, which looks so weird. The request is completely broken, so the unmarshalling the request fails.

For example, let's say this is the correct request:

- string field1 = `Hello world!`
- string field2 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit.`
- string field3 = `She sells seashells by the seashore.`

field2 of the gRPC request is like:
```
Lorem ipsum dolor sit amet, consec(here starts gRPC request payload from the beggining)Hello world!
```

*Repro steps*:
We don't have the complete steps to reproduce this bug but it constantly occurs on our production environment although it is very rare.

Envoy: `envoyproxy/envoy:v1.26.6`
google.golang.org/grpc: `1.71.0`
grpc-web: `1.2.1` (client apparently uses HTTP/3)

*Config*:
>Include the config used to configure Envoy.

```
                    http_filters:
                      - name: envoy.filters.http.grpc_web
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
```
