### ISSUE TITLE
envoy google_grpc TLS seems not work

### ISSUE THREAD

**Issue by quanjielin** [envoyproxy/envoy#3939]
*Description*:
envoy google_grpc TLS seems not work

*Repro steps*:
server is built on gRPC/go
client is envoy built on gRPC/c++

Our scenario is envoy(client based on gRPC/C++) needs to send Google credentials(some GKE token) to server(based on gRPC/go) through UDS(unix domain socket).

Below is from envoy(client) side config 
```
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/var/run/sds/uds_path
                    channel_credentials:
                      ssl_credentials:
                        root_certs:
                          filename: /etc/istio/nodeagent-root-cert.pem
```

server side error
```
ransport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:30:37.250966Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:31:42.641122Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF
```

server side error is thrown from
https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http2_server.go#L264

Notes -
1. attached envoy log - 
[envoy_grpc.log](https://github.com/envoyproxy/envoy/files/2221477/envoy_grpc.log)

2. if I write a simple grpc client using go to setup channel cred(TLS), server side didn't see this error; looks like gRPC/go client takes care of clientPreface
https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http2_client.go#L274

**Comment by lizan** [comment]
@quanjielin can you attach your simple client 2.?

**Comment by quanjielin** [comment]
I built it locally;
client : https://github.com/istio/istio/blob/collab-gcp-identity/security/tools/sds/sds_cli.go
with code bring back from security/tools/sds/sds_cli.go in 
https://github.com/istio/istio/pull/6990/files

**Comment by htuch** [comment]
@quanjielin can you run with these env vars set and get a trace `GRPC_TRACE=ssl,http GRPC_VERBOSITY=debug`? I think this will tell us what happens at the wire level.

**Comment by quanjielin** [comment]
@htuch I shared with you and @lizan my test env so that you could debug; I will pull the logs tomorrow after finishing something else.

**Comment by htuch** [comment]
@quanjielin FWIW, we have an integration test in Envoy for ADS + Google gRPC + TLS, see https://github.com/envoyproxy/envoy/blob/master/test/integration/ads_integration_test.cc#L258. So, we know that at least the basics of this work. What we're trying to do here is understand why it's not working in this particular setup.

**Comment by quanjielin** [comment]
@htuch thanks for the info, there maybe some env/setup issue, also gRPC/c++ -> gRPC/go may introduce some complexity.
1. from the server error, seems ClientPreface is missing from the connection; does envoy/grpc c++ set this value ?
```
    // ClientPreface is the string that must be sent by new
    // connections from clients.
    ClientPreface = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
```
btw I tried config like below(set alpn_protocols) still hit same error
```
     tls_context:
        common_tls_context:
          tls_certificate_sds_secret_configs:
          - name: "spiffe://cluster.local/ns/default/sa/default"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/var/run/sds/uds_path
                    channel_credentials:
                      ssl_credentials:
                        root_certs:
                          filename: /etc/istio/nodeagent-root-cert.pem
                refresh_delay: 60s
          alpn_protocols:
          - h2
            http/1.1
```

2. I've set env variables in envoy container and attached logs; let me know if it's good enough

```
root@envoy-65675f8f54-bwknn:/# echo $GRPC_TRACE
ssl,http
root@envoy-65675f8f54-bwknn:/# export GRPC_VERBOSITY=debug
root@envoy-65675f8f54-bwknn:/# echo $GRPC_VERBOSITY
debug
```

[envoy_grpc_1.log](https://github.com/envoyproxy/envoy/files/2221778/envoy_grpc_1.log)
