### ISSUE TITLE
Remove path from URL using Envoy Proxy

### ISSUE THREAD

**Issue by welsonplay** [envoyproxy/envoy#3944]
I am using the envoy as Front Proxy. And my site responds as follows:
http://my_site.com/MyService.

I would like to remove MyService from the url of my Front Proxy so that I can access the site without having to com /MyService, but my site needs this path.

Is there any way to access the site http://my_site.com/ and the request for the upstream to be sent with / MyService.

This is the configuration file:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  prefix_rewrite: "/"
                  cluster: service1
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: service1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address:[Ip_My_Server]
        port_value: 80

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
