### ISSUE TITLE
rbac: `enforced_engine_result` is not avilable in the `envoy.filters.http.rbac` metadata

### ISSUE THREAD

**Issue by zhaohuabing** [envoyproxy/envoy#39479]
This seems from https://github.com/envoyproxy/envoy/pull/39465

Configuration:

```yaml
                envoy.filters.http.rbac:
                  '@type': type.googleapis.com/envoy.extensions.filters.http.rbac.v3.RBACPerRoute
                  rbac:
                    matcher:
                      onNoMatch:
                        action:
                          name: default
                          typedConfig:
                            '@type': type.googleapis.com/envoy.config.rbac.v3.Action
                            name: ALLOW
```

Envoy Gateway issue: https://github.com/envoyproxy/gateway/issues/6077
