### ISSUE TITLE
How to configure max_response_headers_kb for Istio Ingress Gateway (Envoy)

### ISSUE THREAD

**Issue by tejash-jl** [envoyproxy/envoy#39507]
*Title*: *Setting ENVOY_RELOADABLE_FEATURE_MAX_RESPONSE_HEADERS_SIZE_KB in Istio Ingress Gateway does not take effect*

*Description*:
We are running a setup with Istio Ingress Gateway only (no sidecars) and have services behind the gateway that can produce large response headers.

We tried to increase the response headers size limit in Envoy by adding the following environment variable inside the istio-proxy container of the istio-ingressgateway deployment:
```yaml
- name: ENVOY_RELOADABLE_FEATURE_MAX_RESPONSE_HEADERS_SIZE_KB
  value: "2500"
```
However, even after applying this and restarting the gateway, the issue still persists.
Our services still throw the following error only when running behind the Istio ingress gateway (no such issue when directly accessed or on local setups):

```bash
org.apache.coyote.http11.HeadersTooLargeException: An attempt was made to write more data to the response headers than there was room available in the buffer. Increase maxHttpHeaderSize on the connector or write less data into the response headers.
```
We verified that this only happens inside the Kubernetes cluster with Istio ingress gateway.

*Questions:*

- Is setting ENVOY_RELOADABLE_FEATURE_MAX_RESPONSE_HEADERS_SIZE_KB as an environment variable inside the istio-proxy container the correct and supported approach?
- If yes, what is the correct way to confirm that the feature flag has been applied and is active?
- Are there any additional Envoy configurations or listeners that need to be patched to honor the increased limit?

[optional *Relevant Links*:]
> https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-httpprotocoloptions

**Comment by ramaraochavali** [comment]
It is not an environment variable. You have to set [runtime Variable](https://github.com/istio/api/blob/master/mesh/v1alpha1/proxy.proto#L518) using proxyConfig

proxy.istio.io/config : '{runtimeValues: { "envoy.reloadable_features.max_response_headers_size_kb": "value"}}'

**Comment by tejash-jl** [comment]
@ramaraochavali,
I have updated the istio-ingressgateway deployment with the following configuration:
```yaml
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        kubectl.kubernetes.io/restartedAt: "2025-05-16T10:40:57Z"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        proxy.istio.io/config: |
          {
            "runtimeValues": {
              "envoy.reloadable_features.max_response_headers_size_kb": "1024"
            }
          }
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
```
However, I am still facing the same issue in my application.

I can now see that changes in the /runtime,

can you help me with how to resolve this issue?
