### ISSUE TITLE
HTTP Dynamic Forward Proxy filter doesn't honor dynamic_host filter state while SNI/UDP proxies do

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#39579]
*Title*: *HTTP Dynamic Forward Proxy filter doesn't honor dynamic_host filter state while SNI/UDP proxies do*

## Description

The HTTP Dynamic Forward Proxy filter doesn't honor the `envoy.upstream.dynamic_host` filter state value that's set in the stream info, while both the SNI Dynamic Forward Proxy and UDP Dynamic Forward Proxy filters properly check for and use this value.

This inconsistency means host overriding via filter state works for SNI/UDP proxies but not for HTTP proxies. IMO the behavior is a bit confusing when trying to use the same filter state mechanism across different proxy types.

In the SNI Dynamic Forward Proxy implementation, the filter explicitly checks for the filter state value first:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/network/sni_dynamic_forward_proxy/proxy_filter.cc#L36-L44

Similarly, the UDP Dynamic Forward Proxy filter also checks for the filter state value:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/udp/udp_proxy/session_filters/dynamic_forward_proxy/proxy_filter.cc#L44-L50

However, the HTTP Dynamic Forward Proxy filter does not check the filter state for the host value. Instead, it directly uses the HTTP Host header:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/http/dynamic_forward_proxy/proxy_filter.cc#L292-L295

Interestingly, the DynamicForwardProxy cluster's load balancer does check for the filter state, but this happens after the HTTP filter has already resolved the host:
https://github.com/envoyproxy/envoy/blob/main/source/extensions/clusters/dynamic_forward_proxy/cluster.cc#L361-L374

## Expected Behavior

I would expect the HTTP Dynamic Forward Proxy filter to check for and use the `envoy.upstream.dynamic_host` filter state value before falling back to the HTTP Host header, matching the behavior of the SNI and UDP proxy implementations.

### Example

I would expect the following to work and correctly resolve the DNS for `example.com` and then route to `example.com`. But with the current state of things, it spits out a **503** with no healthy upstream.

```yaml
admin:
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: main_listener
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 9200
    access_log:
      - name: envoy.access_loggers.file
        typed_config:
          '@type': >-
            type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          path: envoy-tcp.log
          log_format:
            json_format:
              duration: '%DURATION%'
              start_time: '%START_TIME%'
              response_flags: '%RESPONSE_FLAGS%'
              upstream_request_attempt_count: '%UPSTREAM_REQUEST_ATTEMPT_COUNT%'
              bytes_received: '%BYTES_RECEIVED%'
              downstream_wire_bytes_sent: '%DOWNSTREAM_WIRE_BYTES_SENT%'
              downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
              requested_server_name: '%REQUESTED_SERVER_NAME%'
              connection_termination_details: '%CONNECTION_TERMINATION_DETAILS%'
              upstream_wire_bytes_received: '%UPSTREAM_WIRE_BYTES_RECEIVED%'
              upstream_wire_bytes_sent: '%UPSTREAM_WIRE_BYTES_SENT%'
              log_type: TCP
              bytes_sent: '%BYTES_SENT%'
              downstream_wire_bytes_received: '%DOWNSTREAM_WIRE_BYTES_RECEIVED%'
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              matcher:
                on_no_match:
                  action:
                    name: allow-traffic
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.route.v3.Route
                      match:
                        prefix: /
                      route:
                        cluster: dfp
                matcher_tree:
                  input:
                    name: request-headers
                    typed_config:
                      "@type": type.googleapis.com/envoy.type.matcher.v3.HttpRequestHeaderMatchInput
                      header_name: :path
                  prefix_match_map:
                    map:
                      /no-match:
                        action:
                          name: deny-traffic
                          typed_config:
                            "@type": type.googleapis.com/envoy.config.route.v3.Route
                            match:
                              prefix: /
                            direct_response:
                              status: 404
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: envoy-http.log
              log_format:
                json_format:
                  duration: "%DURATION%"
                  method: "%REQ(:METHOD)%"
                  start_time: "%START_TIME%"
                  response_flags: "%RESPONSE_FLAGS%"
                  upstream_request_attempt_count: "%UPSTREAM_REQUEST_ATTEMPT_COUNT%"
                  path: "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                  bytes_received: "%BYTES_RECEIVED%"
                  downstream_transport_failure_reason: "%DOWNSTREAM_TRANSPORT_FAILURE_REASON%"
                  response_code: "%RESPONSE_CODE%"
                  downstream_wire_bytes_sent: "%DOWNSTREAM_WIRE_BYTES_SENT%"
                  listener_name: internal_api_endpoint_listener_untrusted_fake-pod
                  user_agent: "%REQ(USER-AGENT)%"
                  downstream_remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                  requested_server_name: "%REQUESTED_SERVER_NAME%"
                  connection_termination_details: "%CONNECTION_TERMINATION_DETAILS%"
                  forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                  upstream_wire_bytes_received: "%UPSTREAM_WIRE_BYTES_RECEIVED%"
                  upstream_wire_bytes_sent: "%UPSTREAM_WIRE_BYTES_SENT%"
                  log_type: HTTP
                  bytes_sent: "%BYTES_SENT%"
                  upstream_host: "%UPSTREAM_HOST%"
                  upstream_service_time: "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%"
                  protocol: "%PROTOCOL%"
                  authority: "%REQ(:AUTHORITY)%"
                  downstream_wire_bytes_received: "%DOWNSTREAM_WIRE_BYTES_RECEIVED%"
          http_filters:
          - name: envoy.filters.http.set_filter_state
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.set_filter_state.v3.Config
              on_request_headers:
              - object_key: "envoy.upstream.dynamic_host"
                format_string:
                  text_format_source:
                    inline_string: "example.com"
              - object_key: "envoy.upstream.dynamic_port"
                format_string:
                  text_format_source:
                    inline_string: "443"
          - name: envoy.filters.http.dynamic_forward_proxy
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
              dns_cache_config:
                name: dfp
                dns_lookup_family: V4_ONLY
                typed_dns_resolver_config:
                  name: envoy.network.dns_resolver.cares
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
                    resolvers:
                    - socket_address:
                        address: "8.8.8.8"
                        port_value: 53
                    dns_resolver_options:
                      use_tcp_for_dns_lookups: false
                      no_default_search_domain: false
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: dfp
    lb_policy: CLUSTER_PROVIDED
    cluster_type:
      name: envoy.clusters.dynamic_forward_proxy
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
        dns_cache_config:
          name: dfp
          dns_lookup_family: V4_ONLY
          typed_dns_resolver_config:
            name: envoy.network.dns_resolver.cares
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.network.dns_resolver.cares.v3.CaresDnsResolverConfig
              resolvers:
              - socket_address:
                  address: "8.8.8.8"
                  port_value: 53
              dns_resolver_options:
                use_tcp_for_dns_lookups: false
                no_default_search_domain: false
    transport_socket: 
      name: envoy.transport_sockets.tls 
      typed_config: 
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /opt/homebrew/etc/ca-certificates/cert.pem
    connect_timeout: 5.0s
```

## Possible Solution
We modify the HTTP Dynamic Forward Proxy filter's `decodeHeaders()` method to first check for the `envoy.upstream.dynamic_host` filter state value before using the HTTP Host header value.
