### ISSUE TITLE
Upstream Http Filter disabled by default and route level disable does not work

### ISSUE THREAD

**Issue by andy-fong** [envoyproxy/envoy#39587]
*Title*: *Upstream Http Filter disabled by default and route level disable does not work*

*Description*:
Basically trying to do the same thing described in https://github.com/envoyproxy/envoy/issues/20867 but putting the filter at the router's upstream_http_filters. While you can disable the filter by default but the per route setting does not re-enable it. Enabled by default and try to disable at route level also does not work.  

*Repro steps*:
Disable at route leve case:
See config file in the *Config* section.
```
curl -v localhost:8080/test -H "test: foobar"
```
http-echo returns:
```
  "headers": {
    "host": "localhost:8080",
    "user-agent": "curl/8.5.0",
    "accept": "*/*",
    "test": "foobar",
    "x-forwarded-proto": "http",
    "x-request-id": "47333334-0853-4b64-881c-1711562b8d21",
    "x-envoy-expected-rq-timeout-ms": "15000",
    "x-amz-content-sha256": "UNSIGNED-PAYLOAD"
  },
```
The `x-amz-content-sha256` indicated that the filter is not disabled 

Disable by default and enable with per route setting case:
Switch the `disabled` field to true in the upstream filter:
```
 curl -v localhost:8080/aws -H "test: foobar"
```
and http-echo returns:
```
  "headers": {
    "host": "localhost:8080",
    "user-agent": "curl/8.5.0",
    "accept": "*/*",
    "test": "foobar",
    "x-forwarded-proto": "http",
    "x-request-id": "31b46d41-7dad-4889-b933-287ad8d2bf9d",
    "x-envoy-expected-rq-timeout-ms": "15000"
  },
```
No `x-amz-*` headers any more. So, the filter is completely disabled and the per route setting does not enabled it.

I tried moving the filter to under `http_filters` and everything works as expected. 

*Config*:
This is the config with the filter enabled by default but disable at the "/" prefix match route. (switch the `disabled` at the upstream filter to true to reproduce the other scenario)
```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: httpbin_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/aws"
                route:
                  cluster: httpbin_cluster
                typed_per_filter_config:
                  my.aws_request_signing:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigningPerRoute
                    aws_request_signing:
                      service_name: bedrock
                      region: us-west-2
                      credential_provider:
                        inline_credential:
                          access_key_id: FAKE
                          secret_access_key: redacted
                          session_token: redacted
                    stat_prefix: bedrock
              - match:
                  prefix: "/"
                route:
                  cluster: httpbin_cluster
                typed_per_filter_config:
                  my.aws_request_signing:
                    "@type": type.googleapis.com/envoy.config.route.v3.FilterConfig
                    config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigningPerRoute
                      aws_request_signing:
                        service_name: dummy
                        region: dummy
                      stat_prefix: dummy
                    disabled: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              upstream_http_filters:
                - name: my.aws_request_signing
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.aws_request_signing.v3.AwsRequestSigning
                    service_name: bedrock
                    region: us-east-1
                    use_unsigned_payload: true
                  disabled: false
                - name: envoy.filters.http.upstream_codec
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.upstream_codec.v3.UpstreamCodec
  clusters:
  - name: httpbin_cluster
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: httpbin_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 80
```
