### ISSUE TITLE
Locality stats sticking around after localities are removed.

### ISSUE THREAD

**Issue by malattia** [envoyproxy/envoy#39590]
*Title*: *Locality stats sticking around after localities are removed.*

*Description*:

Essentially the title. We have a system that adds/remove localities to a small number of clusters. Each locality has a unique name and we noticed that eventually stats bloat to the point of breaking other dependent systems consuming stats from Envoy.

There are possibly ways to make our own system name localities consistently so that they don't change all the time, but bloating of stats is still a potential issue.

If this is indeed a bug, I suppose that a potential fix could be to do stats cleanup when reloading EDS. I noticed that localities are affected by this but it's also possible that other dynamic entities that appear in stats are affected.

*Repro steps*:
1. One route, one cluster with one endpoint in one locality called `zone1`:
```
❯ curl -s 'localhost:32991/clusters'|grep '::zone::'
test_cluster1::240.10.0.1:32200::zone::zone1

❯ curl -s 'localhost:32991/stats?format=prometheus&usedonly'|egrep 'zone._upstream_rq_completed'
# TYPE envoy_cluster_zone_0_zone1_upstream_rq_completed counter
envoy_cluster_zone_0_zone1_upstream_rq_completed{envoy_cluster_name="test_cluster1"} 1
```

Change the zone name and let Envoy reload, now we have only one zone called `zone2` but stats for both zone1 and zone2.
```
❮ curl -s 'localhost:32991/clusters'|grep '::zone::'                                            
test_cluster1::240.10.0.1:32200::zone::zone2

❮ curl -s 'localhost:32991/stats?format=prometheus&usedonly'|egrep 'zone._upstream_rq_completed'
# TYPE envoy_cluster_zone_0_zone1_upstream_rq_completed counter
envoy_cluster_zone_0_zone1_upstream_rq_completed{envoy_cluster_name="test_cluster1"} 1
# TYPE envoy_cluster_zone_0_zone2_upstream_rq_completed counter
envoy_cluster_zone_0_zone2_upstream_rq_completed{envoy_cluster_name="test_cluster1"} 3
```

*Config*:
```
❯ cat etc/envoy.yaml                  
static_resources:
  listeners:
  - name: proxy
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
          stat_prefix: example_http
          codec_type: HTTP1
          rds:
            route_config_name: example_routes
            config_source:
              path: /etc/envoy/rds.json
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"

dynamic_resources:
  cds_config:
    path: /etc/envoy/cds.json

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

```
❯ cat etc/envoy/rds.json 
{
    "resources": [{
        "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
        "name": "example_routes",
        "virtual_hosts": [{
            "name": "test-cluster1",
            "domains": ["*"],
            "routes": [
                {
                    "match": {
                        "prefix": "/"
                    },
                    "route": {
                        "cluster": "test_cluster1",
                        "timeout": "1s"
                    }
                }]
        }]
    }]
}
```
```
❯ cat etc/envoy/cds.json 
{
  "resources": [
    {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "test_cluster1",
      "type": "EDS",
      "eds_cluster_config": {
        "eds_config": {
          "path_config_source": {
            "path": "/etc/envoy/test_cluster1.eds.json"
          }
        }
      },
      "common_lb_config": {
      "healthy_panic_threshold": {
        "value": 35.0
      },
        "locality_weighted_lb_config": {}
      }
    }
  ]
}
```
```
❯ cat etc/envoy/test_cluster1.eds.json 
{
    "resources": [{
        "@type": "type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment",
        "cluster_name": "test_cluster1",
        "endpoints": [
            {
                "locality": {
                    "zone": "zone1"
                },
                "lb_endpoints": [{
                    "endpoint": {
                        "address": {
                            "socket_address": {
                                "address": "240.10.0.1",
                                "port_value": 32200

                            }
                        }
                    },
                    "load_balancing_weight": 100
                }]
            }]
    }]
}
```
