### ISSUE TITLE
Support ROLE command in redis proxy

### ISSUE THREAD

**Issue by tkukushkin** [envoyproxy/envoy#39630]
*Title*: Support ROLE command in redis proxy

*Description*:

Hi! We're trying to use envoy as proxy for redis.

<details>
  <summary>Our configuration</summary>

  ```yaml
  admin:
    access_log_path: /dev/null
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 19000

  static_resources:
    listeners:
    - name: redis
      address:
        socket_address: { address: 0.0.0.0, port_value: 6379 }
      filter_chains:
      - filters:
        - name: envoy.filters.network.redis_proxy
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
            stat_prefix: redis
            settings:
              op_timeout: 10s
            custom_commands: [ role ]
            prefix_routes:
              catch_all_route:
                cluster: rw
                read_command_policy:
                  cluster: ro

    clusters:
    - name: ro
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      health_checks:
      - timeout: 1s
        interval: 1s
        no_traffic_interval: 1s
        no_traffic_healthy_interval: 1s
        unhealthy_interval: 1s
        unhealthy_threshold: 2
        healthy_threshold: 1
        custom_health_check:
          name: envoy.health_checkers.redis
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.health_checkers.redis.v3.Redis
      load_assignment:
        cluster_name: ro
        endpoints:
        - priority: 0
          lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: host-1
                  port_value: 6379
        - priority: 1
          lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: host-2
                  port_value: 6379
        
    - name: rw
      type: STRICT_DNS
      lb_policy: ROUND_ROBIN
      common_lb_config:
        healthy_panic_threshold:
          value: 0
      health_checks:
      - timeout: 1s
        interval: 1s
        no_traffic_interval: 1s
        no_traffic_healthy_interval: 1s
        unhealthy_interval: 1s
        unhealthy_threshold: 2
        healthy_threshold: 1
        reuse_connection: false
        tcp_health_check:
          send:
            text: '0d0a524f4c450d0a'  # ROLE\r\n
          receive:
          - text: '2a33'  # *3 (only primary returns array with 3 elements)
      load_assignment:
        cluster_name: rw
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: host-1
                  port_value: 6379
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: host-2
                  port_value: 6379
  ```
</details>

This configuration splits read and write commands.
Write commands go to redis primary (thanks to custom `tcp_health_check`)
Read commands go to replicas. Priorities are based on locality of replicas.

And unfortunately some our clients execute `ROLE` command when creating new connection to check that they are connected to primary, but it leads to an error:
```
ERR unknown command 'ROLE', with args beginning with:
```

We can't remove it quickly as it would require to update library in hundreds of microservices.

We added `role` to `custom_commands` hoping it will be proxied to master, but it doesn't help, we just get another error:
```
(error) invalid request
```

I am not sure if it's intended, or it's just some edge case which wasn't thought out.

Thank you in advance!
