### ISSUE TITLE
ext_proc filter stalls when the external-processor service sits behind its own Envoy sidecar

### ISSUE THREAD

**Issue by billshen99** [envoyproxy/envoy#39659]
**If you are reporting *any* crash or *any* potential security issue, *do not*
open an issue in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged appropriately.**

*Title*: *One line description*
 ext_proc filter stalls when the external-processor service sits behind its own Envoy sidecar

*Description*:
What we’re doing
We run an External Processing (ext_proc) HTTP filter to sample traffic:

```
- name: external-processor
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
    failure_mode_allow: true          # should let the request through on any error
    observability_mode: true          # should make the call fire-and-forget / non-blocking
    processing_mode:
      request_header_mode: SEND
      response_header_mode: SEND
      request_body_mode: STREAMED
      response_body_mode: STREAMED
      request_trailer_mode: SKIP
      response_trailer_mode: SKIP
    grpc_service:
      envoy_grpc:
        cluster_name: egress_http2_external_server   # → external processor

```
The external processor  runs behind its own Envoy sidecar.

**What we expect**
With observability_mode: true + failure_mode_allow: true the filter should never block the data path; the original request should flow straight through while Envoy streams a copy of the headers/body to the _"egress_http2_external_server"_.

**What actually happens**
When the _"egress_http2_external_server"_ has its envoy sidecar, the requests hangs.  

As soon as we remove the sidecar from the _"egress_http2_external_server"_ , the hang disappears and the filter behaves as expected(non-blocking).

**Envoy versions tested: 1.30.5**

**Do you have idea why does this happen?**
