### ISSUE TITLE
Validate mode segfaults when using CEL formatter

### ISSUE THREAD

**Issue by kevintan250** [envoyproxy/envoy#39653]
*Title*: *Validate mode segfaults when using CEL formatter*

*Description*:
Running envoy in validation mode segfaults if there is a CEL expression in the Fluentd access log config. This appears to be introduced with this commit (https://github.com/envoyproxy/envoy/commit/59a14b1dcb532b23a5566173009e06d02892c1a9).

*Repro steps*:
Using -dev docker images for commit [f31c99d](https://hub.docker.com/layers/envoyproxy/envoy/dev-f31c99db74965c20b9636a0e44a95ae89271a345/images/sha256-0108c9050041058f50fa77e2aa53116831b349856562660eda9ff3b168ea47fe) and [cce9fa8](https://hub.docker.com/layers/envoyproxy/envoy/dev-cce9fa8460df3fc2a5fbf9e1cff9b723f62495cd/images/sha256-996dbe92409e5f2faa040229eba5f36cd139d3054f55795bc2c216db618213b6). These sandwich the commit that makes CEL the built-in formatter.

![Image](https://github.com/user-attachments/assets/f10c0308-9d19-43cd-9475-07228a2889b2)
![Image](https://github.com/user-attachments/assets/cccf73fa-a7e3-4c55-910b-ea7d5e85eb13)

Segfault when using post-commit image. The segfault shows up even when the typed config for the CEL formatter is removed to address warning about built-in formatter. If a different record is used without a CEL expression, the segfault goes away.

`docker run --rm -v "$PWD:/data" d84f4b5452ae --mode validate -c /data/envoy-cel.yaml --service-node "test" --service-cluster "test"`
> [2025-05-28 06:19:11.815][1][info][main] [source/server/server.cc:900] runtime: {}
[2025-05-28 06:19:11.815][1][info][config] [source/server/configuration_impl.cc:173] loading tracing configuration
[2025-05-28 06:19:11.815][1][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2025-05-28 06:19:11.815][1][info][config] [source/server/configuration_impl.cc:130] loading 2 cluster(s)
[2025-05-28 06:19:11.817][1][info][config] [source/server/configuration_impl.cc:140] loading 1 listener(s)
[2025-05-28 06:19:11.820][1][warning][config] [source/extensions/formatter/cel/config.cc:17] 'CEL' formatter is treated as a built-in formatter and does not require configuration.
[2025-05-28 06:19:11.821][1][critical][assert] [./source/common/singleton/threadsafe_singleton.h:115] assert failure: loader_. Details: ThreadLocalInjectableSingleton used prior to initialization
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:38] stacktrace for envoy bug
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #0 UNKNOWN [0x561c042e6587]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #1 UNKNOWN [0x561c04fd26fa]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #2 UNKNOWN [0x561c04fd38f6]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #3 UNKNOWN [0x561c04da1ab9]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #4 UNKNOWN [0x561c02bf49fa]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #5 UNKNOWN [0x561c04db2a22]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #6 UNKNOWN [0x561c04cbac52]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #7 UNKNOWN [0x561c04cb7205]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #8 UNKNOWN [0x561c04cb7395]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #9 UNKNOWN [0x561c04cb7319]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #10 UNKNOWN [0x561c04cbedbe]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #11 UNKNOWN [0x561c04c459a1]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #12 UNKNOWN [0x561c04c26c8b]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #13 UNKNOWN [0x561c04c55309]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #14 UNKNOWN [0x561c04c54d39]
[2025-05-28 06:19:11.821][1][error][envoy_bug] [./source/common/common/assert.h:45] #15 UNKNOWN [0x561c04c6e0ef]
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:129] Caught Aborted, suspect faulting address 0x6500000001
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:113] Backtrace (use tools/stack_decode.py to get line numbers):
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:114] Envoy version: cce9fa8460df3fc2a5fbf9e1cff9b723f62495cd/1.34.0-dev/Clean/RELEASE/BoringSSL
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:116] Address mapping: 561c02bca000-561c057e9000 /usr/local/bin/envoy
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:123] #0: [0x7f2fd073a520]
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:129] Caught Segmentation fault, suspect faulting address 0x0
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:113] Backtrace (use tools/stack_decode.py to get line numbers):
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:114] Envoy version: cce9fa8460df3fc2a5fbf9e1cff9b723f62495cd/1.34.0-dev/Clean/RELEASE/BoringSSL
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:116] Address mapping: 561c02bca000-561c057e9000 /usr/local/bin/envoy
[2025-05-28 06:19:11.822][1][critical][backtrace] [./source/server/backtrace.h:123] #0: [0x7f2fd073a520]

With stacktrace:
`tools/stack_decode.py bazel-bin/source/exe/envoy-static --mode validate -c envoy-cel.yaml --service-node "test" --service-cluster "test"

> [2025-05-28 23:51:35.178][3518][info][main] [source/server/server.cc:900] runtime: {}
[2025-05-28 23:51:35.180][3518][info][config] [source/server/configuration_impl.cc:173] loading tracing configuration
[2025-05-28 23:51:35.180][3518][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2025-05-28 23:51:35.180][3518][info][config] [source/server/configuration_impl.cc:130] loading 2 cluster(s)
[2025-05-28 23:51:35.204][3518][info][config] [source/server/configuration_impl.cc:140] loading 1 listener(s)
[2025-05-28 23:51:35.235][3518][warning][config] [source/extensions/formatter/cel/config.cc:15] 'CEL' formatter is treated as a built-in formatter and does not require configuration.
[2025-05-28 23:51:35.244][3518][critical][assert] [./source/common/singleton/threadsafe_singleton.h:115] assert failure: loader_. Details: ThreadLocalInjectableSingleton used prior to initialization
[2025-05-28 23:51:35.244][3518][error][envoy_bug] [./source/common/common/assert.h:38] stacktrace for envoy bug
[2025-05-28 23:51:35.341][3518][error][envoy_bug] [./source/common/common/assert.h:43] #0 Envoy::ThreadLocalInjectableSingleton<>::get() [0x64825528799e]
[2025-05-28 23:51:35.378][3518][error][envoy_bug] [./source/common/common/assert.h:43] #1 Envoy::Extensions::Formatter::CELFormatterCommandParser::parse() [0x648255287261]
[2025-05-28 23:51:35.414][3518][error][envoy_bug] [./source/common/common/assert.h:43] #2 Envoy::Formatter::SubstitutionFormatParser::parse() [0x64825761ee11]
[2025-05-28 23:51:35.447][3518][error][envoy_bug] [./source/common/common/assert.h:43] #3 Envoy::Formatter::JsonFormatterImpl::JsonFormatterImpl() [0x64825761f9d0]
[2025-05-28 23:51:35.481][3518][error][envoy_bug] [./source/common/common/assert.h:43] #4 std::make_unique<>() [0x6482570323fd]
[2025-05-28 23:51:35.515][3518][error][envoy_bug] [./source/common/common/assert.h:43] #5 Envoy::Formatter::SubstitutionFormatStringUtils::createJsonFormatter() [0x64825702e35e]
[2025-05-28 23:51:35.549][3518][error][envoy_bug] [./source/common/common/assert.h:43] #6 Envoy::Extensions::AccessLoggers::Fluentd::FluentdAccessLogFactory::createAccessLogInstance() [0x648250c293fc]
[2025-05-28 23:51:35.585][3518][error][envoy_bug] [./source/common/common/assert.h:43] #7 Envoy::AccessLog::AccessLogFactory::fromProto() [0x648257054fe3]
[2025-05-28 23:51:35.619][3518][error][envoy_bug] [./source/common/common/assert.h:43] #8 Envoy::Extensions::NetworkFilters::HttpConnectionManager::HttpConnectionManagerConfig::HttpConnectionManagerConfig() [0x648256e11a32]
[2025-05-28 23:51:35.653][3518][error][envoy_bug] [./source/common/common/assert.h:43] #9 std::construct_at<>() [0x648256e2d55e]
[2025-05-28 23:51:35.687][3518][error][envoy_bug] [./source/common/common/assert.h:43] #10 std::allocator_traits<>::construct<>() [0x648256e2d65a]
[2025-05-28 23:51:35.721][3518][error][envoy_bug] [./source/common/common/assert.h:43] #11 std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>() [0x648256e2bad0]
[2025-05-28 23:51:35.754][3518][error][envoy_bug] [./source/common/common/assert.h:43] #12 std::__shared_count<>::__shared_count<>() [0x648256e293b1]
[2025-05-28 23:51:35.789][3518][error][envoy_bug] [./source/common/common/assert.h:43] #13 std::__shared_ptr<>::__shared_ptr<>() [0x648256e270f4]
[2025-05-28 23:51:35.822][3518][error][envoy_bug] [./source/common/common/assert.h:43] #14 std::shared_ptr<>::shared_ptr<>() [0x648256e23168]
[2025-05-28 23:51:35.856][3518][error][envoy_bug] [./source/common/common/assert.h:43] #15 std::allocate_shared<>() [0x648256e1f59b]
[2025-05-28 23:51:35.856][3518][critical][backtrace] [./source/server/backtrace.h:129] Caught Aborted, suspect faulting address 0x3e800000dbe
[2025-05-28 23:51:35.856][3518][critical][backtrace] [./source/server/backtrace.h:113] Backtrace (use tools/stack_decode.py to get line numbers):
[2025-05-28 23:51:35.856][3518][critical][backtrace] [./source/server/backtrace.h:114] Envoy version: cce9fa8460df3fc2a5fbf9e1cff9b723f62495cd/1.34.0-dev/Modified/DEBUG/BoringSSL
[2025-05-28 23:51:35.856][3518][critical][backtrace] [./source/server/backtrace.h:116] Address mapping: 648250298000-64825e1b2000 /home/kevintan/.cache/bazel/_bazel_kevintan/33555eb895f6387837a81f49d8afb7a2/execroot/envoy/bazel-out/k8-dbg/bin/source/exe/envoy-static (used as address offset)

The same config file doesn't segfault when validating using the pre-commit image

` docker run --rm -v "$PWD:/data" 1c4710d95047 --mode validate -c /data/envoy-cel.yaml --service-node "test" --service-cluster "test"`
>[2025-05-28 06:19:22.172][1][info][main] [source/server/server.cc:900] runtime: {}
[2025-05-28 06:19:22.173][1][info][config] [source/server/configuration_impl.cc:173] loading tracing configuration
[2025-05-28 06:19:22.173][1][info][config] [source/server/configuration_impl.cc:124] loading 0 static secret(s)
[2025-05-28 06:19:22.173][1][info][config] [source/server/configuration_impl.cc:130] loading 2 cluster(s)
[2025-05-28 06:19:22.177][1][info][config] [source/server/configuration_impl.cc:140] loading 1 listener(s)
[2025-05-28 06:19:22.181][1][info][config] [source/server/configuration_impl.cc:156] loading stats configuration
configuration '/data/envoy-cel.yaml' OK

*Config*:
Config file with CEL expression in access logger used above (envoy-cel.yaml)
```
---
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 30443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          access_log:
            name: envoy.access_loggers.fluentd
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.fluentd.v3.FluentdAccessLogConfig
              cluster: fluentd_cluster
              tag: sample_tag
              stat_prefix: sample_statprefix
              record:
                sample: "%CEL(request.method)%"
              formatters:
              - name: envoy.formatter.cel
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.formatter.cel.v3.Cel
          route_config:
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: backend_cluster
  clusters:
  - name: backend_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: backend_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: backend_service
                port_value: 80
  - name: fluentd_cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: fluentd_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: fluentd_service
                port_value: 24224
```
