### ISSUE TITLE
Question - access logs for udp_listener.dns_filter

### ISSUE THREAD

**Issue by AntonKanug** [envoyproxy/envoy#39671]
Is there a way to get access logs for a UDP listener which is only used for dns_filter as below? 

```
static_resources:
  listeners:
  - name: udp_listener_for_dns_override_from_xds
    address:
      socket_address:
        protocol: UDP
        address: 127.0.0.1
        port_value: 10053
    listener_filters:
    - name: envoy.filters.udp_listener.dns_filter
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.udp.dns_filter.v3.DnsFilterConfig
        stat_prefix: dns_filter_prefix
        client_config:
          max_pending_lookups: 256
          dns_resolution_config:
            dns_resolver_options:
              use_tcp_for_dns_lookups: true
              no_default_search_domain: false
            resolvers:
            - socket_address:
                protocol: TCP
                address: 10.0.0.1
                port_value: 53
        server_config:
          inline_dns_table:
            virtual_domains:
            - name: hello.com
              endpoint:
                address_list:
                  address:
                  - 1.1.1.1
```

looking at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/observability/access_logging#arch-overview-access-logs I dont see support for the dns filter
