### ISSUE TITLE
ext_proc upstream timed out after functioning for some time

### ISSUE THREAD

**Issue by hoseinalirezaee** [envoyproxy/envoy#39699]
*Title*: *ext_proc upstream timed out after functioning for some time*

*Description*:
After upgrading from version 1.33.3 to 1.34.1, I've noticed a growing number of message_timeouts metric on routes where ext_proc is enabled. Importantly, these timeouts do not appear immediately following the upgrade—instead, they begin to surface after the system has been running for some time.

<details>

<summary>Click to expand</summary>

![Image](https://github.com/user-attachments/assets/763a915a-2ed4-4650-bb32-4a650908cdd0)

</details>

Setting the runtime guard `envoy.reloadable_features.http2_use_oghttp2` to `false` resolves the issue.

The upstream ext_proc is a GRPC service, and EnvoyGateway is used as the control plane.

*Repro steps*:
I am not sure, but we could reproduce the issue by using Envoy version 1.34.x. The ext_proc upstream should probably be a GRPC service, and the runtime guard `envoy.reloadable_features.http2_use_oghttp2` must be set to `true` (the default value in 1.34.x).

**Comment by paul-r-gall** [comment]
@birenroy for oghttp2.

**Comment by paul-r-gall** [comment]
are you able to reproduce with trace logging so that we can see what may be going on?

**Comment by yanjunxiang-google** [comment]
Envoy trace log will help for debugging. message_timeouts usually means the request sends to the external server is dropped somewhere.

**Comment by hoseinalirezaee** [comment]
I was able to reproduce the issue.

Before providing the explanation, I should mention that the external service is a service that decides whether to allow or deny based on request information (Client IP, headers, etc.). "Allow" means a response with a status of `continue`. "Deny" refers to a response in the form of an `immediate_response`. The content of this `immediate_response` is an HTML page approximately 10KB in size.

To reproduce, I defined the `ext proc` settings for the relevant route as follows (the following code is the output of `egctl`):

```
name: envoy.filters.http.ext_proc/envoyextensionpolicy/infrastructure/fake-log/extproc/0
typedConfig:
  '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
  failureModeAllow: true
  grpcService:
    envoyGrpc:
      authority: envoy-test-gateway-ext-proc.gateways
      clusterName: envoyextensionpolicy/infrastructure/fake-log/extproc/0
    timeout: 10s
  messageTimeout: 0.030s
  processingMode:
    requestHeaderMode: SEND
    requestTrailerMode: SKIP
    responseHeaderMode: SKIP
    responseTrailerMode: SKIP
  requestAttributes:
  - source.address
  - request.host
  - request.url_path
  - request.method
```

A key point here is the `message_timeout`, which is set to 30ms.

Requests were made to this route at a rate of 35 requests per second.

![Image](https://github.com/user-attachments/assets/42e11826-0e1d-4970-a1f5-90d4af2e86e9)

In the yellow chart (on the right side of the image), the value of `envoy.reloadable_features.http2_use_oghttp2` is `true`. Initially, all requests are allowed. However, as soon as requests start getting denied, the rate of timeout messages begins to increase. This continues to the point where all requests time out (35 req/s). The strange thing is that even after requests are allowed again, they still time out and don’t return to the initial state—until finally, reloading the configuration resets the timeout rate back to normal.

In the green chart (on the left side of the image), the value of `envoy.reloadable_features.http2_use_oghttp2` is `false`. As seen, its behavior differs from the yellow chart. The timeout rate after requests are denied is much lower than in the yellow chart. Moreover, after requests are allowed again, the timeout status returns to normal.

Cluster and Endpoint configurations are shown below:

<details>
<summary>Click to expand</summary>

```
cluster:
  '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
  circuitBreakers:
    thresholds:
    - maxRetries: 1024
  commonLbConfig:
    localityWeightedLbConfig: {}
  connectTimeout: 10s
  dnsLookupFamily: V4_PREFERRED
  edsClusterConfig:
    edsConfig:
      ads: {}
      resourceApiVersion: V3
    serviceName: envoyextensionpolicy/infrastructure/fake-log/extproc/0
  ignoreHealthOnHostRemoval: true
  lbPolicy: LEAST_REQUEST
  name: envoyextensionpolicy/infrastructure/fake-log/extproc/0
  perConnectionBufferLimitBytes: 32768
  type: EDS
  typedExtensionProtocolOptions:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      explicitHttpConfig:
        http2ProtocolOptions:
          initialConnectionWindowSize: 1048576
          initialStreamWindowSize: 65536
lastUpdated: "2025-06-03T12:06:49.854Z"
versionInfo: 850a6d816c6e375061ae9ee4fece0f779f64e29880c2ee1ca9186bcba7885c82
---
endpointConfig:
'@type': type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment
clusterName: envoyextensionpolicy/infrastructure/fake-log/extproc/0
endpoints:
- lbEndpoints:
  - endpoint:
      address:
        pipe:
          path: /tmp/waf/envoy.sock
      healthCheckConfig: {}
    healthStatus: HEALTHY
    loadBalancingWeight: 1
  loadBalancingWeight: 1
  locality:
    region: envoyextensionpolicy/infrastructure/fake-log/extproc/0/backend/0
policy:
  overprovisioningFactor: 140
```


</details>


Here are the links to captured trace logs:

[oghttp2-false](https://ha128.s3.ir-thr-at1.arvanstorage.ir/oghtt2-false.zip)

[oghttp2-true](https://ha128.s3.ir-thr-at1.arvanstorage.ir/oghttp2-true.zip)

Timezone of logs is UTC and timezone of graphs is Asia/Tehran.
