### ISSUE TITLE
Sharing alt_stat_name across clusters yields semi-arbitrary membership stats

### ISSUE THREAD

**Issue by marcusdarmstrong** [envoyproxy/envoy#39706]
*Description*:

In our application we have a variety of short-lived "canary" clusters that we route traffic to as a part of aggregate clusters. For observability purposes we use a shared alt_stat_name on each of these canary clusters and our noncanary to group them into a single unit on our dashboards to see all of our live traffic together. This works well for all stats except cluster membership, where we've discovered that the alt_stat_name membership behavior appears to select the most-recently-configured cluster and exclusively use its statistics on membership gauges for the alt_stat_name cluster as a whole. With xds dynamically defining our clusters as we shift traffic around, this leads to these membership gauges being largely unusable, as it's ambiguous which underlying cluster is being represented.

From my perspective, membership gauges would ideally sum across alt_stat_name clusters to describe the state of that group of clusters as a whole.

*Repro steps*:

Configuration as described below to demonstrate the behavior, the only difference between the two configurations is that in the first, cluster `b` has two members and in the second cluster `a` has two members.

*Admin and Stats Output*:

```
% curl -s http://localhost:9902/stats/prometheus | grep envoy_cluster_membership_total
# TYPE envoy_cluster_membership_total gauge
envoy_cluster_membership_total{envoy_cluster_name="c"} 2
% curl -s http://localhost:9903/stats/prometheus | grep envoy_cluster_membership_total
# TYPE envoy_cluster_membership_total gauge
envoy_cluster_membership_total{envoy_cluster_name="c"} 1
```

*Config*:

Configuration A:
```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  clusters:
    - name: a
      alt_stat_name: c
      type: STATIC
      load_assignment:
        cluster_name: a
        endpoints: 
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 123
    - name: b
      alt_stat_name: c
      type: STATIC
      load_assignment:
        cluster_name: b
        endpoints: 
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 124
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 125
```

Configuration B:
```
admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  clusters:
    - name: a
      alt_stat_name: c
      type: STATIC
      load_assignment:
        cluster_name: a
        endpoints: 
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 124
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 125
    - name: b
      alt_stat_name: c
      type: STATIC
      load_assignment:
        cluster_name: b
        endpoints: 
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 123
```

docker-compose config:
```
services:
  envoy-a:
    image: envoyproxy/envoy:v1.34.1
    ports:
      - 9902:9901
    volumes:
      - ./envoy-config.a.yml:/etc/envoy/envoy.yaml

  envoy-b:
    image: envoyproxy/envoy:v1.34.1
    ports:
      - 9903:9901
    volumes:
      - ./envoy-config.b.yml:/etc/envoy/envoy.yaml
```
