### ISSUE TITLE
session ticket with tls1.3 does not respect `session_timeout` duration.

### ISSUE THREAD

**Issue by bellatoris** [envoyproxy/envoy#39738]
*Title*: session ticket with tls1.3 does not respect `session_timeout` duration.

*Description*:

I have configured the session_timeout value to 86400 as shown below, but it consistently returns 172800. I have verified that this works correctly with TLS 1.2.

*config*

```yaml
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              session_timeout: 86400s
```

*tcpdump results*

```
  [-] TLSv1.3 Record Layer: Handshake Protocol: Multiple Handshake Messages
        Opaque Type: Application Data (23)
        Version: TLS 1.2 (0x0303)
        Length: 445
        Content Type: Handshake (22)
    [-] Handshake Protocol: New Session Ticket
          Handshake Type: New Session Ticket (4)
          Length: 210
      [-] TLS Session Ticket
            Session Ticket Lifetime Hint: 172800 seconds (2 days)
    [-] Handshake Protocol: New Session Ticket
          Handshake Type: New Session Ticket (4)
          Length: 210
      [-] TLS Session Ticket
            Session Ticket Lifetime Hint: 172800 seconds (2 days)
```

> This serves as a hint for the [TLS session ticket lifetime (for TLSv1.2)](https://tools.ietf.org/html/rfc5077#section-5.6). Only whole seconds are considered; fractional seconds are ignored.

While I understand that the documentation specifies this is for TLS 1.2, I would like to confirm whether the behavior with TLS 1.3—where this setting seems to have no effect—is intentional or possibly a bug.
