### ISSUE TITLE
Envoy reverse proxy (Proxy Front) + URL rewrite

### ISSUE THREAD

**Issue by welsonplay** [envoyproxy/envoy#3977]
Envoy is running on port 80, and I'm using it to reverse proxy (Front Proxy) URLs with path /foo to port 3200 this way:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  prefix_rewrite: "/"
                  cluster: service1
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: service1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address:[Ip_My_Server]
        port_value: 3200
```

This works fine, but I have an application on port 3200, for which I don't want the initial /foo to be sent to. That is - when I access http://localhost/foo/bar, I want only /bar to be the path as received by the app. 

In Nginx I need to do only this configuration:
```
location  /foo {
  rewrite /foo/(.*) /$1  break;
  proxy_pass         http://[Ip_My_Server]:3200;
  proxy_redirect     off;
  proxy_set_header   Host $host;
}
```
How can I make this same setting in Envoy?
