### ISSUE TITLE
Filter Chain selection using QUIC

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#39932]
*Title*: *Filter Chain selection using QUIC*

## Description

We’re exploring QUIC support and need a way to choose a filter chain based on the incoming Server Name Indication (SNI). In TCP mode, Envoy’s [TLS Inspector](https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector) can extract the SNI during the handshake and make it available to the filter chain matcher. I haven’t found an equivalent for QUIC.

Would it make sense to introduce a “QUIC Inspector” that parses the initial QUIC handshake, extracts the SNI, and exposes it to the filter chain matcher? 

I’m relatively new to QUIC, so pardon my ignorance if there’s a fundamental issue with this approach or if a better alternative already exists.

**Comment by kyessenov** [comment]
Doesn't QUIC mandate the use of encryption? TLS inspector is only needed if you have both plaintext and encrypted traffic on the same port.

**Comment by agrawroh** [comment]
> Doesn't QUIC mandate the use of encryption? TLS inspector is only needed if you have both plaintext and encrypted traffic on the same port.

Thanks, @kyessenov. My impression was that TLS Inspector also extracts the SNI and make it available to the filter chain matcher. Without the TLS Inspector, we won't have the SNI to match on. Is that not true?

**Comment by kyessenov** [comment]
Yes, correct, the filter chain matching happens after listener filters but before transport socket kicks in, while sometimes you do want to apply transport socket (decryption) before further matching, because in this case we do have certs for all possible SNI hosts. But we can get away with the inspection approach, with some extra cost to parse the TLS hello twice.

I'll defer to the actual quic expects.

@RyanTheOptimist

**Comment by RyanTheOptimist** [comment]
I thought that the QUIC code already set the requested server name here:

https://github.com/envoyproxy/envoy/blob/main/source/common/quic/envoy_quic_utils.cc#L345

I think this matches what the TlsInspector does.

https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L141

Is there more that needs to be done to expose this?

**Comment by agrawroh** [comment]
> I thought that the QUIC code already set the requested server name here:
> 
> https://github.com/envoyproxy/envoy/blob/main/source/common/quic/envoy_quic_utils.cc#L345
> 
> I think this matches what the TlsInspector does.
> 
> https://github.com/envoyproxy/envoy/blob/main/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L141
> 
> Is there more that needs to be done to expose this?

@RyanTheOptimist Thanks for the code pointers. Yes, you are absolutely right! I didn't realize that it happens already. I was able to verify it like this:
```
# Make requests using the following command(s):
# curl -vik --resolve google.com:10001:127.0.0.1 https://google.com:10001 --http3
# curl -vik --resolve envoyproxy.io:10001:127.0.0.1 https://envoyproxy.io:10001 --http3
#
# An example config which accepts HTTP/3 and forwards the requests upstream over TCP.
# This includes a TCP listener which advertises that HTTP/3 is available via the alt-svc header
admin:
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_udp
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10001
    udp_listener_config:
      quic_options: {}
      downstream_socket_config:
        prefer_gro: true
    filter_chain_matcher:
      matcher_list:
        matchers:
        - predicate:
            single_predicate:
              input:
                name: envoy.matching.inputs.server_name
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.matching.common_inputs.network.v3.ServerNameInput
              value_match:
                safe_regex:
                  google_re2: {}
                  regex: envoyproxy.io
          on_match:
            action:
              name: pick-allow-traffic-chain
              typed_config:
                "@type": type.googleapis.com/google.protobuf.StringValue
                value: allow-traffic
      on_no_match:
        action:
          name: pick-deny-traffic-chain
          typed_config:
            "@type": type.googleapis.com/google.protobuf.StringValue
            value: deny-traffic
    filter_chains:
    - name: allow-traffic
      transport_socket:
        name: envoy.transport_sockets.quic
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
          downstream_tls_context:
            require_client_certificate: false
            common_tls_context:
              alpn_protocols: "h3"
              tls_certificates:
              - certificate_chain:
                  filename: cert.pem
                private_key:
                  filename: key.pem
      filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: HTTP3
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite_literal: www.envoyproxy.io
                  cluster: service_envoyproxy_io
          http3_protocol_options:
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
  - name: service_envoyproxy_io
    connect_timeout: 30s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```
