### ISSUE TITLE
Another kind of canary mechanism

### ISSUE THREAD

**Issue by YvesZHI** [envoyproxy/envoy#39952]
If I'm right, current Envoy supports such a kind of Canary:
1. mark some endpoints as canary instances in the Envoy config;
2. if canary header in request is found, route to canary instances, otherwise, route to ANY of endpoints;
3. if canary instances are all unhealthy, route to ANY of healthy endpoints.

For me, I need such a kind of Canary:
1. mark some endpoints as canary instances in the Envoy config;
2. if canary header in request is found, route to canary instances, otherwise, route to any of NON-CANARY endpoints;
3. if canary instances are all unhealthy, route to ANY of healthy endpoints.

Can Envoy do such a kind of Canary or my design is not a proper Canary?

**Comment by wbpcode** [comment]
I believe subset lb could archieve your target.

**Comment by wbpcode** [comment]
https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/subsets

**Comment by YvesZHI** [comment]
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 22222
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: app
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: versioned-cluster
          http_filters:
          - name: envoy.filters.http.header_to_metadata
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.header_to_metadata.v3.Config
              request_rules:
              - header: x-version
                on_header_present:
                  metadata_namespace: envoy.lb
                  key: version
                  type: STRING
                on_header_missing:
                  metadata_namespace: envoy.lb
                  key: version
                  value: "prod"
                  type: STRING
                # remove: false
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
  - name: versioned-cluster
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    lb_subset_config:
      fallback_policy: DEFAULT_SUBSET
      default_subset:
        version: "prod"
      subset_selectors:
      - keys:
        - version
    health_checks:
      - timeout: 1s
        interval: 1s
        unhealthy_threshold: 3
        healthy_threshold: 2
        http_health_check:
          path: "/"
    load_assignment:
      cluster_name: versioned-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
          metadata:
            filter_metadata:
              envoy.lb:
                version: "prod"
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8081
          metadata:
            filter_metadata:
              envoy.lb:
                version: "1.0"
```
@wbpcode 
If I stop the server at `8081` and then send a request to my Envoy `curl -H 'x-version: 1.0' 127.0.0.1:22222`, I will always get the error: `upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111`. My question is if Envoy can route requests to the cluster with metadata `prod` in this case.

It doesn't seem that the subset mechanism support fallback policy on unhealthy case...
