### ISSUE TITLE
ExtProc ExtProcLoggingInfo is not available in access logs

### ISSUE THREAD

**Issue by agrawroh** [envoyproxy/envoy#39999]
*Title*: *ExtProc ExtProcLoggingInfo is not available in access logs*

## Description

It seems like the metadata/info exposed via `ExtProcLoggingInfo` in ExtProc is not available to the access logs. I get `null` when I try to access it.

It seems like we'll have to provide an override for `serializeAsProto()` and `serializeAsString()` for the formatter to be able to extract and serialize this object.

## Repro Steps

Run Envoy using the following config and verify the logs.

### Config

This is a simple config which could be used to test this out, 

```yaml
static_resources:
  listeners:
    - name: main_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                generate_request_id: true
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        json_format:
                          ext_proc_plain: "%FILTER_STATE(envoy.filters.http.ext_proc:PLAIN)%"
                          ext_proc_typed: "%FILTER_STATE(envoy.filters.http.ext_proc:TYPED)%"
                          ext_proc_field: "%FILTER_STATE(envoy.filters.http.ext_proc:FIELD:inbound_header_latency_us)%"
                http_filters:
                  - name: envoy.filters.http.ext_proc
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                      metadata_options:
                        receiving_namespaces:
                          untyped:
                          - envoy.filters.http.ext_proc
                      grpc_service:
                        envoy_grpc:
                            cluster_name: ext_proc_cluster
                        timeout: 10s
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      dns_cache_config:
                        name: dynamic_dns_cache
                        dns_lookup_family: V4_ONLY
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
  clusters:
    - name: dynamic_forward_proxy_cluster
      connect_timeout: 1s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          dns_cache_config:
            name: dynamic_dns_cache
            dns_lookup_family: V4_ONLY
    - name: ext_proc_cluster
      connect_timeout: 1s
      type: STATIC
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}  # Enables HTTP/2
      load_assignment:
        cluster_name: ext_proc_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    pipe:
                      path: /tmp/ext_proc_osd.sock
```

### Logs

This is what we see today:

```json
{"ext_proc_field":null,"ext_proc_plain":null,"ext_proc_typed":null}
```

I would expect to see something like this instead:

```json
{"ext_proc_field":"1191","ext_proc_plain":"ih:1191:14,bs:0,br:0","ext_proc_typed":{"bytes_received":0,"bytes_sent":0,"inbound_header_latency_us":1191,"inbound_header_status":14}}
```
