### ISSUE TITLE
Envoy v1.34.0+ Shows Increased Latency in Benchmarking

### ISSUE THREAD

**Issue by whutwhu** [envoyproxy/envoy#40070]
Has anyone noticed performance degradation in the latest Envoy versions **v1.34.0** and **v1.34.1**? We recently identified the performance regression in Envoy starting from version **v1.34.0**, based on our benchmarking results. Specifically, we observed an average latency increase of around 15%-25% compared to earlier versions. This issue persists in v1.34.x, while previous versions such as v1.33.x and v1.32.x do not exhibit this degradation.

For example, our benchmark comparing v1.34.0 to v1.33.3 clearly shows this performance drop:

- P50

<img width="1314" alt="Image" src="https://github.com/user-attachments/assets/0aa2d493-d969-42d3-b6d6-32a1d53c88a1" />

- P90

<img width="1307" alt="Image" src="https://github.com/user-attachments/assets/6aafc422-6373-4ef0-8dda-fe7d1e9051bc" />

Our benchmark setup and summary:

1. We used [fortio](https://github.com/fortio/fortio) as the traffic generator, varying QPS from 1k to 8k.
2. The test scenario evaluated the overhead of Envoy in a sidecar inbound setup: fortio -> envoy -> service.
3. No filters were enabled except for the basic http_connection_manager and router filter; Envoy simply forwarded requests to the service, and the service returned echoed responses.
4. The performance regression was consistently observed in both v1.34.0 and v1.34.1, while all versions prior to v1.34.0 performed as expected.
5. The latency increase is consistent with the CPU metrics shown below, which indicate higher CPU usage starting from v1.34.0:

<img width="1306" alt="Image" src="https://github.com/user-attachments/assets/ca1a50a4-a087-4e2d-9c6c-74aa6ea0352b" />

Does anyone have insights into what might have changed in v1.34.0? I'd appreciate any suggestions.

**Comment by wbpcode** [comment]
Hi, @whutwhu , thanks for the reporting. Could you provide a simple configuration file that could reproduce this result? Then we can do some profile based on the result. (Or if you are familar to the profiling, it would be more helpful to provide a profile file directly)

**Comment by whutwhu** [comment]
Hi @wbpcode, thanks for your reply! 

Our Envoy runs as a sidecar and listens on a TCP port. When it receives a request, it simply forwards it to the main app, which listens on the UDS. The listener and cluster configuration are shown below.

Regarding profiling — are you referring to using gperftools and pprof as shown in the [link](https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md)? I haven’t run this before, but I can follow the instructions. If you have any specific commands you'd like me to run, could you please share them?

 **Listener:**
 ```
"@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: listener_inbound_grpc
  address:
    socket_address: { address: "::", port_value: 19158, ipv4_compat: true }
  filter_chains:
    - filters:
        - name: envoy.filters.network.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
            stat_prefix: inbound_http
            codec_type: AUTO
            forward_client_cert_details: APPEND_FORWARD
            set_current_client_cert_details: {subject: true, uri: true, cert: true}
            route_config:
              name: inbound_route
              virtual_hosts:
                - name: inbound_service
                  domains: ["*"]

                  routes:
                    - match: { prefix: "/" }
                      route:
                        cluster: inbound_local_app_cluster_grpc
                        max_stream_duration: { grpc_timeout_header_max: 0s }
                        idle_timeout: 0s


            http_filters:

              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

     transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: ["h2,http/1.1"]
            tls_params:
              cipher_suites:
               - "[TLS_RSA_WITH_AES_128_CBC_SHA|TLS_RSA_WITH_AES_128_GCM_SHA256]"
               - ECDHE-ECDSA-AES128-GCM-SHA256
               - ECDHE-RSA-AES128-GCM-SHA256
               - ECDHE-ECDSA-AES256-GCM-SHA384
               - ECDHE-RSA-AES256-GCM-SHA384
            tls_certificate_sds_secret_configs:
              name: tls_sds
              sds_config:
                resource_api_version: V3
                path_config_source:
                  path: /export/content/app/envoy_sds.yaml
            validation_context_sds_secret_config:
              name: validation_context_sds
              sds_config:
                resource_api_version: V3
                path_config_source:
                  path: /export/content/app/envoy_sds_validation.yaml

```

Cluster:
```
"@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: inbound_local_app_cluster_grpc
  connect_timeout: 6s
  typed_extension_protocol_options:
    envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
      "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
      explicit_http_config:
        http2_protocol_options: {}
  type: STATIC
  lb_policy: ROUND_ROBIN
  load_assignment:
    cluster_name: inbound_local_app_cluster_grpc
    endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                pipe:
                  path: /export/content/app/inbound.sock
```

**Comment by wbpcode** [comment]
> Hi [@wbpcode](https://github.com/wbpcode), thanks for your reply!
> 
> Our Envoy runs as a sidecar and listens on a TCP port. When it receives a request, it simply forwards it to the main app, which listens on the UDS. The listener and cluster configuration are shown below.
> 
> Regarding profiling — are you referring to using gperftools and pprof as shown in the [link](https://github.com/envoyproxy/envoy/blob/main/bazel/PPROF.md)? I haven’t run this before, but I can follow the instructions. If you have any specific commands you'd like me to run, could you please share them?
> 
> **Listener:**
> 
> ```
> "@type": type.googleapis.com/envoy.config.listener.v3.Listener
>  name: listener_inbound_grpc
>  address:
>    socket_address: { address: "::", port_value: 19158, ipv4_compat: true }
>  filter_chains:
>    - filters:
>        - name: envoy.filters.network.http_connection_manager
>          typed_config:
>            "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
>            stat_prefix: inbound_http
>            codec_type: AUTO
>            forward_client_cert_details: APPEND_FORWARD
>            set_current_client_cert_details: {subject: true, uri: true, cert: true}
>            route_config:
>              name: inbound_route
>              virtual_hosts:
>                - name: inbound_service
>                  domains: ["*"]
> 
>                  routes:
>                    - match: { prefix: "/" }
>                      route:
>                        cluster: inbound_local_app_cluster_grpc
>                        max_stream_duration: { grpc_timeout_header_max: 0s }
>                        idle_timeout: 0s
> 
> 
>            http_filters:
> 
>              - name: envoy.filters.http.router
>                typed_config:
>                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
> 
>     transport_socket:
>        name: envoy.transport_sockets.tls
>        typed_config:
>          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
>          common_tls_context:
>            alpn_protocols: ["h2,http/1.1"]
>            tls_params:
>              cipher_suites:
>               - "[TLS_RSA_WITH_AES_128_CBC_SHA|TLS_RSA_WITH_AES_128_GCM_SHA256]"
>               - ECDHE-ECDSA-AES128-GCM-SHA256
>               - ECDHE-RSA-AES128-GCM-SHA256
>               - ECDHE-ECDSA-AES256-GCM-SHA384
>               - ECDHE-RSA-AES256-GCM-SHA384
>            tls_certificate_sds_secret_configs:
>              name: tls_sds
>              sds_config:
>                resource_api_version: V3
>                path_config_source:
>                  path: /export/content/app/envoy_sds.yaml
>            validation_context_sds_secret_config:
>              name: validation_context_sds
>              sds_config:
>                resource_api_version: V3
>                path_config_source:
>                  path: /export/content/app/envoy_sds_validation.yaml
> ```
> 
> Cluster:
> 
> ```
> "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
>   name: inbound_local_app_cluster_grpc
>   connect_timeout: 6s
>   typed_extension_protocol_options:
>     envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
>       "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
>       explicit_http_config:
>         http2_protocol_options: {}
>   type: STATIC
>   lb_policy: ROUND_ROBIN
>   load_assignment:
>     cluster_name: inbound_local_app_cluster_grpc
>     endpoints:
>       - lb_endpoints:
>           - endpoint:
>               address:
>                 pipe:
>                   path: /export/content/app/inbound.sock
> ```

If you want to observe the CPU overhead, then I think `perf` tools that provided by kernel would be better for now. (Now, the Envoy is compiled with tcmalloc rather than gperftools).

You can change the image of Envoy to a version with symbol (See https://github.com/envoyproxy/envoy/blob/main/ci/README.md), then run the `perf record -g -e cpu-cycles -p <envoy pid>`. Then, you start a launch a benchmark test, and after the test is over or a while, use ctrl + c to stop the recording and you will get a perf.data.

Repeat above steps with two different versions of Envoy, you should get two `perf.data` files. Then you can use the `pprof` tool to analyze these `perf.data`s.

**Comment by yanavlasov** [comment]
What HTTP protocol version was used for the test?

**Comment by whutwhu** [comment]
> What HTTP protocol version was used for the test?

Hi @yanavlasov! Our service uses gRPC, and we've only tested it with gRPC requests.

**Comment by yanavlasov** [comment]
In your test, can you set the `envoy.reloadable_features.http2_use_oghttp2` flag to `false` and see if it affects your measurement, please?

**Comment by whutwhu** [comment]
> In your test, can you set the `envoy.reloadable_features.http2_use_oghttp2` flag to `false` and see if it affects your measurement, please?

Thanks, @yanavlasov! I’m running the new benchmarks and will share the results with you.

**Comment by whutwhu** [comment]
Hi @yanavlasov, thanks so much for your help! We’ve confirmed that the issue is indeed caused by this flag. Setting it to `true` leads to worse performance.

Below is our benchmarking result for your reference. We used the same Envoy version (v1.34.0), ran benchmarks, and compared the results with the `envoy.reloadable_features.http2_use_oghttp2` flag set to both true and false. The outcome clearly reflects the performance degradation we observed when comparing versions after v1.34.0 to those before it.

1. P50

<img width="1291" height="467" alt="Image" src="https://github.com/user-attachments/assets/7f18a931-6b77-454e-8967-e85ee9aa2c31" />

2. P90

<img width="1288" height="477" alt="Image" src="https://github.com/user-attachments/assets/2d2f6a9f-061f-4fbb-8351-946a460c272e" />

3. CPU  

<img width="1284" height="479" alt="Image" src="https://github.com/user-attachments/assets/3b277206-b0cc-4f93-8ebe-9daa809ab614" />

**Comment by yanavlasov** [comment]
Adding @birenroy for any info on this issue.

**Comment by birenroy** [comment]
Could you please provide more details about the traffic generated by fortio? Is there any message body payload, or are you testing minimal request/response headers?

I'm not surprised to see a small regression in the worst case, but in real world scenarios I don't expect the difference to be significant.

**Comment by whutwhu** [comment]
> Could you please provide more details about the traffic generated by fortio? Is there any message body payload, or are you testing minimal request/response headers?
> 
> I'm not surprised to see a small regression in the worst case, but in real world scenarios I don't expect the difference to be significant.

Thanks for asking! In our benchmarking setup, we use `fortio` to vary the QPS from 1k to 8k, with a fixed payload size of 5k and a 4k header.
We made some modifications to `fortio` to enable it to invoke our gRPC method.
For each QPS level, we run a 3-minute warmup followed by a 20-minute test (`-t 20m -warm 3m`).

**Comment by yanavlasov** [comment]
How many request and response headers do you have?

The increase in latency looks to be about 50us on average. Is 50us important to you? Note that in most cases Envoy runs some business logic per request, and 50us would be a rounding error in the overall latency added by a proxy.

**Comment by whutwhu** [comment]
Hi @yanavlasov! We’re running the benchmarking test where each request includes a single header with a value size of 4KB. Envoy is deployed as a sidecar in our service mesh architecture to handle inter-service communication. In many cases, a single request may traverse dozens of services, each with its own Envoy sidecar. Because of this, we pay close attention to the overhead introduced by each additional Envoy hop.

In our recent benchmarking, we observed roughly a 20% performance degradation and a 15% increase in CPU usage with a single additional Envoy hop. This appears to correlate with this OSS [PR](https://github.com/envoyproxy/envoy/pull/38026), which seems be related to the switch to OgHTTP2.

We’d like to understand:

1. Is OgHTTP2 considered stable in Envoy at this point?
2. Have you received reports from other users about increased CPU usage or degraded performance after enabling OgHTTP2?
3. Would you recommend enabling or disabling OgHTTP2 in a production environment at this time?

Thanks for your help!

**Comment by yanavlasov** [comment]
oghttp2 is considered stable and will be supported going forward. nghttp2 is deprecated and will be removed at some point.
We did not receive any other reports about performance degradation.
You can switch back to nghttp2 for now while this issue is being resolved.

**Comment by jukie** [comment]
Should this be renamed to track oghttp2 performance?

**Comment by jukie** [comment]
I was able to reproduce this and am seeing ~8% increase in p50 and p90 latency when using oghttp2 vs nghttp2.

I'll update with some profiling data and an example git repo so anyone can reproduce it. @whutwhu could you share more info about your execution environment? Intel vs AMD vs ARM and anything else that would be useful for debugging further.

**Comment by jukie** [comment]
Performance looks to be worse with 1.35 and nghttp2 performs ~30% better in terms of rq throughput and ~12% better for latency. Would the maintainers consider changing the default back to nghttp2 until this can be improved? This is a substantial regression and making it the default doesn't seem right. Unfortunately performance has been continuously dropping over time as discussed in https://github.com/envoyproxy/envoy/issues/19103.

nghttp2:
![Image](https://github.com/user-attachments/assets/21378881-7ad3-4561-996c-0025cce29d23)

<details open>
  <summary>nghttp2 nighthawk output</summary>
  
  ```
benchmark_http_client.latency_2xx (1648387 samples)
  min: 0s 100ms 466us | mean: 0s 109ms 720us | max: 0s 171ms 040us | pstdev: 0s 004ms 868us

  Percentile  Count       Value          
  0.5         824456      0s 108ms 838us 
  0.75        1236620     0s 112ms 709us 
  0.8         1319004     0s 113ms 709us 
  0.9         1483768     0s 115ms 900us 
  0.95        1566013     0s 118ms 140us 
  0.990625    1632941     0s 124ms 227us 
  0.99902344  1646779     0s 134ms 897us 

Queueing and connection setup latency (1648959 samples)
  min: 0s 000ms 016us | mean: 0s 000ms 020us | max: 0s 015ms 086us | pstdev: 0s 000ms 025us

  Percentile  Count       Value          
  0.5         845952      0s 000ms 019us 
  0.75        1244948     0s 000ms 019us 
  0.8         1324543     0s 000ms 020us 
  0.9         1484776     0s 000ms 021us 
  0.95        1567223     0s 000ms 023us 
  0.990625    1633544     0s 000ms 029us 
  0.99902344  1647350     0s 000ms 053us 

Request start to response end (1648387 samples)
  min: 0s 100ms 466us | mean: 0s 109ms 720us | max: 0s 171ms 040us | pstdev: 0s 004ms 868us

  Percentile  Count       Value          
  0.5         824472      0s 108ms 838us 
  0.75        1236627     0s 112ms 709us 
  0.8         1319011     0s 113ms 709us 
  0.9         1483777     0s 115ms 900us 
  0.95        1566014     0s 118ms 140us 
  0.990625    1632941     0s 124ms 227us 
  0.99902344  1646779     0s 134ms 897us 

Response body size in bytes (1648387 samples)
  min: 12 | mean: 12 | max: 12 | pstdev: 0

Response header size in bytes (1648387 samples)
  min: 139 | mean: 139 | max: 139 | pstdev: 0

Blocking. Results are skewed when significant numbers are reported here. (77369 samples)
  min: 0s 000ms 112us | mean: 0s 031ms 014us | max: 0s 152ms 322us | pstdev: 0s 030ms 482us

  Percentile  Count       Value          
  0.5         38685       0s 019ms 954us 
  0.75        58027       0s 046ms 159us 
  0.8         61896       0s 054ms 779us 
  0.9         69635       0s 080ms 097us 
  0.95        73502       0s 098ms 869us 
  0.990625    76645       0s 117ms 358us 
  0.99902344  77294       0s 125ms 149us 

Initiation to completion (1648579 samples)
  min: 0s 000ms 010us | mean: 0s 110ms 224us | max: 0s 172ms 695us | pstdev: 0s 005ms 200us

  Percentile  Count       Value          
  0.5         824467      0s 109ms 326us 
  0.75        1236484     0s 113ms 364us 
  0.8         1319023     0s 114ms 458us 
  0.9         1483763     0s 116ms 703us 
  0.95        1566189     0s 119ms 029us 
  0.990625    1633129     0s 125ms 149us 
  0.99902344  1646970     0s 135ms 913us 

Counter                                 Value       Per second
benchmark.http_2xx                      1648387     5494.69
benchmark.pool_overflow                 192         0.64
cluster_manager.cluster_added           8           0.03
default.total_match_count               8           0.03
membership_change                       8           0.03
runtime.load_success                    1           0.00
runtime.override_dir_not_exists         1           0.00
ssl.ciphers.ECDHE-RSA-AES128-GCM-SHA256 8           0.03
ssl.curves.X25519                       8           0.03
ssl.handshake                           8           0.03
ssl.sigalgs.rsa_pss_rsae_sha256         8           0.03
ssl.versions.TLSv1.2                    8           0.03
upstream_cx_http2_total                 8           0.03
upstream_cx_rx_bytes_total              65997093    219992.83
upstream_cx_total                       8           0.03
upstream_cx_tx_bytes_total              21437243    71458.29
upstream_rq_pending_overflow            192         0.64
upstream_rq_pending_total               8           0.03
upstream_rq_total                       1648959     5496.59


  ```
</details>

oghttp2:
![Image](https://github.com/user-attachments/assets/ad87c948-abed-47dc-a6f4-0c6946a3abad)

<details open>
  <summary>oghttp2 nighthawk output</summary>
  
  ```
benchmark_http_client.latency_2xx (1254367 samples)
  min: 0s 100ms 630us | mean: 0s 122ms 098us | max: 0s 167ms 124us | pstdev: 0s 005ms 640us

  Percentile  Count       Value          
  0.5         627205      0s 123ms 662us 
  0.75        940855      0s 125ms 263us 
  0.8         1003946     0s 125ms 603us 
  0.9         1129155     0s 126ms 541us 
  0.95        1191656     0s 127ms 807us 
  0.990625    1242613     0s 132ms 751us 
  0.99902344  1253143     0s 147ms 447us 

Queueing and connection setup latency (1254883 samples)
  min: 0s 000ms 016us | mean: 0s 000ms 020us | max: 0s 021ms 024us | pstdev: 0s 000ms 049us

  Percentile  Count       Value          
  0.5         634509      0s 000ms 019us 
  0.75        947480      0s 000ms 019us 
  0.8         1006203     0s 000ms 019us 
  0.9         1130387     0s 000ms 021us 
  0.95        1192639     0s 000ms 023us 
  0.990625    1243146     0s 000ms 032us 
  0.99902344  1253658     0s 000ms 059us 

Request start to response end (1254367 samples)
  min: 0s 100ms 626us | mean: 0s 122ms 098us | max: 0s 167ms 124us | pstdev: 0s 005ms 640us

  Percentile  Count       Value          
  0.5         627219      0s 123ms 662us 
  0.75        940871      0s 125ms 263us 
  0.8         1003962     0s 125ms 603us 
  0.9         1129164     0s 126ms 541us 
  0.95        1191660     0s 127ms 807us 
  0.990625    1242613     0s 132ms 751us 
  0.99902344  1253143     0s 147ms 447us 

Response body size in bytes (1254367 samples)
  min: 12 | mean: 12 | max: 12 | pstdev: 0

Response header size in bytes (1254367 samples)
  min: 139 | mean: 139 | max: 139 | pstdev: 0

Blocking. Results are skewed when significant numbers are reported here. (39129 samples)
  min: 0s 000ms 179us | mean: 0s 061ms 325us | max: 0s 168ms 148us | pstdev: 0s 046ms 832us

  Percentile  Count       Value          
  0.5         19565       0s 050ms 100us 
  0.75        29347       0s 114ms 823us 
  0.8         31306       0s 123ms 994us 
  0.9         35221       0s 126ms 324us 
  0.95        37176       0s 127ms 275us 
  0.990625    38763       0s 129ms 527us 
  0.99902344  39091       0s 144ms 146us 

Initiation to completion (1254651 samples)
  min: 0s 000ms 010us | mean: 0s 122ms 812us | max: 0s 168ms 140us | pstdev: 0s 006ms 085us

  Percentile  Count       Value          
  0.5         627738      0s 124ms 506us 
  0.75        941181      0s 126ms 140us 
  0.8         1003885     0s 126ms 476us 
  0.9         1129515     0s 127ms 361us 
  0.95        1192029     0s 128ms 487us 
  0.990625    1242891     0s 133ms 484us 
  0.99902344  1253427     0s 148ms 455us 

Counter                                 Value       Per second
benchmark.http_2xx                      1254367     4181.22
benchmark.pool_overflow                 284         0.95
cluster_manager.cluster_added           8           0.03
default.total_match_count               8           0.03
membership_change                       8           0.03
runtime.load_success                    1           0.00
runtime.override_dir_not_exists         1           0.00
ssl.ciphers.ECDHE-RSA-AES128-GCM-SHA256 8           0.03
ssl.curves.X25519                       8           0.03
ssl.handshake                           8           0.03
ssl.sigalgs.rsa_pss_rsae_sha256         8           0.03
ssl.versions.TLSv1.2                    8           0.03
upstream_cx_http2_total                 8           0.03
upstream_cx_rx_bytes_total              45221595    150738.64
upstream_cx_total                       8           0.03
upstream_cx_tx_bytes_total              16314255    54380.85
upstream_rq_pending_overflow            284         0.95
upstream_rq_pending_total               8           0.03
upstream_rq_total                       1254883     4182.94
  ```
</details>


Build/runtime environment:
M4 Max macbook pro with `bazel build --define tcmalloc=gperftools //source/exe:envoy-static` on commit 564612e32eafc10a7a7fd490cdb5cc7149e5802b

Load generation:
```
nighthawk_client \
        --duration 300 \
        --connections 20 \
        --concurrency 8 \
        --rps 2000 \
        -p http2 \
        --request-header "host:example.com" \
        --output-format human \
        https://127.0.0.1:10000/
```

Upstream cluster: https://gist.github.com/jukie/c1a75703ee03e2e6afdcc27f61e16897

Envoy config:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: HTTP2
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536
            initial_connection_window_size: 1048576
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: backend_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /tmp/tls.crt
              private_key:
                filename: /tmp/tls.key
            alpn_protocols: ["h2", "http/1.1"]

  clusters:
  - name: backend_cluster
    type: STATIC
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options:
            max_concurrent_streams: 100
            initial_stream_window_size: 65536
            initial_connection_window_size: 1048576
    load_assignment:
      cluster_name: backend_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```

Then set oghttp2 to true/false accordingly:
```
layered_runtime:
  layers:
  - name: static_reloadable_features
    static_layer:
      envoy.reloadable_features.http2_use_oghttp2: true|false
```
