### ISSUE TITLE
envoy crashes when a cluster is updated with new subset selector

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#4072]
Steps for repro:

a) start with a simple cluster:

```
  ---
  name: cluster-name
  type: EDS
  eds_cluster_config:
    eds_config:
      path: '.../eds.conf'
  connect_timeout:
    seconds: 10
  lb_policy: LEAST_REQUEST
  lb_subset_config:
    fallback_policy: DEFAULT_SUBSET
    default_subset:
      stage: prod
    subset_selectors:
    - keys:
      - v
      - stage
    - keys:
      - stage
```

b) Update the cluster so that it includes a new subset selector, e.g.:

```
...
    - keys:
      - stage
      - foo
```

c) crash happens

I'll get a stack trace and/or a test case repro later today/tomorrow. 

cc: @zuercher
