### ISSUE TITLE
--service-node and --service-cluster are not used when sending DiscoveryRequest

### ISSUE THREAD

**Issue by skwasiborski** [envoyproxy/envoy#4085]
*Description*:
When envoy is run with --service-node and --service-cluster cli parameters the values are not respected when sending xDS DiscoveryRequests. If node element is present in the bootstrap file the values from bootstrap are sent, if node element is not present in bootstrap file node.id and node.cluster in DiscoveryRequest are empty.

Expected behavior is that value passed to --service-node is used as node.id in all DiscoveryRequests and --service-cluster is used as node.cluster.

*Repro steps*:
Given envoy is run with the following command
```envoy --service-cluster cluster0 --service-node _Node_0 -c envoy.yaml```
and node element is not present in envoy.yaml file, all xDS request are snet with following node definition:
```
Sending DiscoveryRequest for type.googleapis.com/envoy.api.v2.Cluster: node {
   build_version: "3f59fb5c0f6554f8b3f2e73ab4c1437a63d42668/1.7.0/Clean/RELEASE"
}
```

**Comment by mattklein123** [comment]
This sounds like a regression. It will need to be investigated.

**Comment by dio** [comment]
Tried quickly using the following .yaml config (with no `node` defined):

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

dynamic_resources:
  lds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster

  cds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
        envoy_grpc:
          cluster_name: xds_cluster

static_resources:
  clusters:
    - name: xds_cluster
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      hosts: [{ socket_address: { address: xds, port_value: 50051 } }]
```

And,

0. Running an xDS service
1. Running envoyproxy/envoy-alpine:v1.7.0 with:

```
CMD ["/usr/local/bin/envoy", "-c", "/etc/config.yaml", "-l", "trace", "--service-cluster", "cluster0", "--service-node", "node0"]
```

The captured trace-level log gave:

```
envoy_1  | [2018-08-12 02:54:23.254][6][trace][upstream] source/common/config/grpc_mux_impl.cc:80] Sending DiscoveryRequest for type.googleapis.com/envoy.api.v2.Cluster: node {
envoy_1  |   id: "node0"
envoy_1  |   cluster: "cluster0"
envoy_1  |   build_version: "3f59fb5c0f6554f8b3f2e73ab4c1437a63d42668/1.7.0/Clean/RELEASE"
envoy_1  | }
envoy_1  | type_url: "type.googleapis.com/envoy.api.v2.Cluster"
envoy_1  |
```

@skwasiborski do you think I missed something while reproducing you case? Thanks!

**Comment by skwasiborski** [comment]
@dio it seems like your repro should show the issue. I am using ADS not LDS/CDS maybe that is why you do not see the issue. I will verify tomorrow if switching to LDS/CDS changes anything in my setup.

**Comment by dio** [comment]
@skwasiborski thanks for the hint on setting the subscription to `ads`. I can reproduce the issue.

e.g. with the following config

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: xds_cluster

  lds_config: { ads: {} }
  cds_config: { ads: {} }

static_resources:
  clusters:
    - name: xds_cluster
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      hosts: [{ socket_address: { address: xds, port_value: 50051 } }]
```

Ran with:

```
--service-cluster cluster0 --service-node node0
```

Saw the following logged.

```
envoy_1  | [2018-08-12 23:37:24.339][6][trace][upstream] source/common/config/grpc_mux_impl.cc:80] Sending DiscoveryRequest for type.googleapis.com/envoy.api.v2.Cluster: node {
envoy_1  |   build_version: "3f59fb5c0f6554f8b3f2e73ab4c1437a63d42668/1.7.0/Clean/RELEASE"
envoy_1  | }
envoy_1  | type_url: "type.googleapis.com/envoy.api.v2.Cluster"
envoy_1  |
envoy_1  | [2018-08-12 23:37:24.339][6][trace][router] source/common/router/router.cc:872] [C0][S7075102453735512773] proxying 111 bytes
envoy_1  | [2018-08-12 23:37:24.339][6][trace][connection] source/common/network/connection_impl.cc:326] [C0] writing 120 bytes, end_stream false
```
