### ISSUE TITLE
Help migrating from v1 to v2 with Front Proxy setup and EDS

### ISSUE THREAD

**Issue by cdelguercio** [envoyproxy/envoy#4095]
I'm attempting to upgrade my envoy setup from v1 to v2 and I'm having a bit of trouble. My end goal is to have static clusters behind a front proxy with EDS set up.

My previous setup used the lyft/discovery reference SDS, and what I think I want is to drop in an EDS server based on the go-control-plane repo.

I've attempted to take the go-control-plane from stub to an actual EDS server here: https://gist.github.com/cdelguercio/63113ed22959bb249ebb816dd2f487e3 but I'm not sure if I've done everything I need to make it fully functional. It is able to talk to my front proxy fine (it outputs the cluster config from the front proxy), but my services aren't registering with it they way they did with the lyft/discovery server.

Here's the relevant part of my front proxy config:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
          - name: envoy.file_access_log
            filter:
              not_health_check_filter: {}
            config:
              path: "/tmp/envoy_access.log"
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend_services
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/api.service"
                  headers:
                  - name: content-type
                    value: "application/grpc"
                route:
                  cluster: service_grpc
                  timeout: 30s
                  retry_policy:
                    retry_on: 5xx
                    num_retries: 2
                    per_try_timeout: 15s
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: xds_cluster
    connect_timeout: 30s
    type: STRICT_DNS
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 18000
  - name: service_grpc
    connect_timeout: 30s
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      service_name: "my-service"
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
          refresh_delay: 15s
```

The the relevant part of my service config:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
          - name: envoy.file_access_log
            filter:
              not_health_check_filter: {}
            config:
              path: "/tmp/envoy_access.log"
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: content-type
                    value: "application/grpc"
                route:
                  cluster: local_service_grpc
                  timeout: 60s
                  retry_policy:
                    retry_on: 5xx
                    num_retries: 2
                    per_try_timeout: 15s
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: xds_cluster
    connect_timeout: 10s
    type: STRICT_DNS
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 18000
  - name: local_service_grpc
    connect_timeout: 60s
    type: EDS
    http2_protocol_options: {}
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8000
    eds_cluster_config:
      eds_config:
        api_config_source:
          api_type: GRPC
          grpc_services:
            envoy_grpc:
              cluster_name: xds_cluster
          refresh_delay: 15s
      service_name: "my-service"
```

Any help would be greatly appreciated.
