### ISSUE TITLE
Redirect traffic to same port as it was received / Listen on several ports

### ISSUE THREAD

**Issue by apsega** [envoyproxy/envoy#4301]
*Title*: *Redirect traffic to same port as it was received / Listen on several ports*

*Description*:
I couldn't find if Envoy Proxy actually supports the option to listen on all/range of ports and redirect traffic (L4) to the backends on the same port as the traffic has been received. If there's actually a capability can someone share a configuration?

HAProxy actually supports this kind of stuff i.e.:

```
frontend http
  bind *:80-30000
```

This redirects to same upstream port as traffic went in just by not declaring it:

```
backend http
  server backend xx.x.xx.xxx maxconn 10000 check inter 5000 fastinter 1000 fall 3 rise 1 weight 1
```

**Comment by lizan** [comment]
Sounds like iptables REDIRECT (or TPROXY, need more capability and configuration) with original dst cluster will achieve this? See https://github.com/envoyproxy/envoy/tree/master/configs/original-dst-cluster too.

**Comment by apsega** [comment]
I've tried the following config and it seems that Envoy is not receiving traffic on random port:

```
static_resources:
  listeners:
  - name: edgeproxy
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    listener_filters:
      name: envoy.listener.original_dst
    transparent: true
    filter_chains:
      - filters:
        - name: envoy.tcp_proxy
          config:
            stat_prefix: ingress_tcp
            cluster: upstreams
            access_log:
            - name: envoy.file_access_log
              config:
                path: "/dev/stdout"
  clusters:
  - name: upstreams
    connect_timeout: 5s
    type: original_dst
    lb_policy: original_dst_lb
    load_assignment:
      cluster_name: upstreams
      endpoints:
        lb_endpoints:
          endpoint:
            address:
              socket_address:
                address: some.internal.dns
                port_value: 80
```

The backend listens on port `27439` and when I'm trying to connect through Envoy on that port:

```
nc -v <some_dns> 27439
nc: connectx to <some_dns> port 27439 (tcp) failed: Connection refused
```
