### ISSUE TITLE
http2.tx_reset increments even when stream is not disconnected with stream_idle_timeout

### ISSUE THREAD

**Issue by ramaraochavali** [envoyproxy/envoy#4316]
We have long running http2 stream and the connection manager is configured like this
```
 - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_h2
          stream_idle_timeout: 0s
```
 Before `stream_idle_timeout` is configured, the local reset used to happen and `http2.tx_reset` stat used to be incremented.
After `stream_idle_timeout` is configuration, local reset stopped and  stream is now not disconnected. But still the `http2.tx_reset` is incremented. Is this a bug?
