### ISSUE TITLE
Incorrect TLS example in documentation

### ISSUE THREAD

**Issue by mshaverdo** [envoyproxy/envoy#4408]
*Title*: *Incorrect TLS example in documentation*

*Description*:
There is an invalid `tls_context` block In [https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/ssl#example-configuration]()

```
      tls_context:
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /usr/local/my-client-ca.crt
```

When trying to use this example with envoy 1.7.1, error "A single TLS certificate is required for server contexts" occurs. To fix it, `tls_certificates` section should be added:

```
      tls_context:
        common_tls_context:
          tls_certificates:
            certificate_chain: { "filename": "/cert.crt" }
            private_key: { "filename": "/cert.key" }
          validation_context:
            trusted_ca:
              filename: /ca.crt
```

Also, error message "A single TLS certificate is required for server contexts" isn't informative in this case
