### ISSUE TITLE
"No healthy upstream" seen sometimes for static localhost cluster.

### ISSUE THREAD

**Issue by ikatson** [envoyproxy/envoy#4414]
*Description*:
We have some "No healthy upstream" errors happening in production. They are rare and we can't reproduce them or figure out why they are happening.
The most concerning case is the one where the remote cluster is a "STATIC" type cluster with 127.0.0.1 host.

Here's the cluster definition we see UH flag with

```
      - circuit_breakers:
          thresholds:
          - max_connections: 8192
            max_pending_requests: 300
        common_lb_config:
          healthy_panic_threshold:
            value: 0.25
        connect_timeout: 0.1s
        dns_lookup_family: V4_ONLY
        health_checks:
        - healthy_threshold: 2
          http_health_check:
            path: /status
          interval: 5s
          no_traffic_interval: 5s
          timeout: 5s
          unhealthy_threshold: 3
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 8080
        lb_policy: LEAST_REQUEST
        name: local-appserver
        type: STATIC
```

Our expectation was that for at least static clusters we should never see UH flag, and that panic mode will route the request whatever happens.

This also happens for remote clusters which use STRICT_DNS discovery. For those I would understand if temporary DNS blips would cause this behavior somehow, although I suspect it's the same reason we see it for localhost cluster.

What can be causing this?

Version of envoy:
not sure. We are using the dockerhub envoy docker image 
envoyproxy/envoy-alpine@sha256:fee7f5cd71f82e01957921a27c8fbb370e4e0bbb5646d88603dd7ab62d630f5a
version: 2d744738c8ba57c189ac5444b3e48f45c442c8ee/1.7.0-dev/Clean/RELEASE
