### ISSUE TITLE
Generic string (and bytes) search and replace network filter

### ISSUE THREAD

**Issue by bmetzdorf** [envoyproxy/envoy#4462]
*Description*:
I'm proposing to create a generic string (and bytes) search and replace network filter, that can replace strings and bytes in the payload at the beginning of a downstream connection (readFilter) as well as when sending the response (writeFilter). Sometimes one needs to massage incoming and outgoing payloads just a little bit (e.g. legacy applications or missing control over client behavior).

Since matching arbitrary strings across different packets/buffers is hard, I'd limit this to a certain amount of data at the beginning of the payload, when the read/write filter chain is invoked. The filter would wait until a certain amount of data has been accumulated and then would try to search and replace. This amount of data could be specified as a string/bytes sequence (e.g. "\r\n\r\n" to catch all HTTP/1 headers) or as an amount of bytes. Should the payload never include the sequence or reach the amount of bytes, then we could continue down the filter chain after some configurable timeout.

Search and replace could be done via statically matched strings (or bytes in hex?) or via regular expressions.

Example:

```
filters:
  - name: search_replace
    config:
      read:
        search: "old"
        replace: "new"
        mode: string
        wait_for_bytes: 50
        timeout_in_ms: 2000
      write:
        search: "(.*)new(.*)"
        replace: "$1old$2"
        mode: regex
        wait_for_string: "\n"
        timeout_in_ms: 1000
```
(another `mode` could be `bytes`, with `search` and `replace` being hex values)

With this configuration a client could send the following payload:
```
blah blah super old proprietary protocol request blah blah
```
And the filter would modify this to
```
blah blah super new proprietary protocol request blah blah
```
before passing it on.

On the way back downstream: 
```
blah blah dynamic 123 super new proprietary protocol response unique value blah blah\n
```
would be turned into
```
blah blah dynamic 123 super old proprietary protocol response unique 567 value blah blah\n
```

(You get the picture...)

What do we think? Worthwhile to have this functionality? I'd volunteer to work on this.

**Comment by mattklein123** [comment]
This sounds reasonable to me and generally useful. I thought about it, and I can't think of another filter that this type of functionality would naturally fit in, so this seems like a reasonable place. I think we will want to think carefully about the filter config though to make it extensible enough for the future in which we might want to implement various other types of replacements. E.g., I could imagine someone even eventually wanting a JSON or gRPC field munging filter of some type. (In v1 clearly just basic byte munging is fine)

**Comment by bmetzdorf** [comment]
@mattklein123 What do you think about the idea of introducing a type of version into the filter config, so that we can iterate and adapt easier in the future?

Example:

```
filters:
  - name: search_replace
    config:
      v1:
        read:
          search: "old"
          replace: "new"
          mode: string
          wait_for_bytes: 50
          timeout_in_ms: 2000
        write:
          search: "(.*)new(.*)"
          replace: "$1old$2"
          mode: regex
          wait_for_string: "\n"
          timeout_in_ms: 1000
      v2:
        brand_new_stuff_invented_in_2019
```

The filter could then pick the newest configuration, or we could introduce an `active_config` field that specifies which version to use:


```
filters:
  - name: search_replace
    active_config: v1
    config:
      v1: {}
      v2: {}
```

I think it might be worthwhile to consider something along these lines, since it would really take the pain away from trying to catch all possible and unknown future use cases for the filter config today.
