### ISSUE TITLE
Changing endpoint priority causes Envoy to lose track of the endpoint

### ISSUE THREAD

**Issue by bplotnick** [envoyproxy/envoy#4473]
*Title*: *Changing endpoint priority causes Envoy to lose track of the endpoint*

*Description*:
When moving an endpoint to a new priority, Envoy loses track of that endpoint.

Example before and after eds config:

Before:
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: service1
  endpoints:
  - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_1_ip}}
              port_value: 80
      - endpoint:
          address:
            socket_address:
              address: {{service1_2_ip}}
              port_value: 80
```

After:
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: service1
  endpoints:
  - priority: 0
    lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_1_ip}}
              port_value: 80
  - priority: 1
    lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: {{service1_2_ip}}
              port_value: 80
```

Envoy will no longer know about `{{service1_2_ip}}`

*Repro steps*:
I've created a repro here: https://github.com/bplotnick/envoy_examples/tree/master/losing_endpoints

CC: @mpuncel and @snowp who dealt with something similar in #3930
