### ISSUE TITLE
crash when mirroring traffic to non-existent cluster

### ISSUE THREAD

**Issue by avereha** [envoyproxy/envoy#4504]
*Title*: *Envoy crash when trying to mirror traffic to non-existent cluster*

*Description*:

We tried to use the "request_mirror_policy" feature and noticed that we get a crash if the cluster that we try to mirror traffic to doesn't exist. The crash is happening on the first request that is using that route. This bug seems to manifest only if we load the route configuration via RDS. When we try to specify the route in configuration, validation fails and we can't reproduce the bug.

*Repro steps*:

The minimal configuration that I used to reproduce the bug is this:
```yaml
node:
  id: test.node
  cluster: test.cluster

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901

static_resources:
  clusters:
    - name: service_google
      connect_timeout: 0.25s
      type: "LOGICAL_DNS"
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      hosts:
        - socket_address:
            address: google.com
            port_value: 443
      tls_context: { sni: www.google.com }

  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            stat_prefix: default
            rds:
              route_config_name: default
              config_source:
                path: ./mirror-crash-route.yaml
            http_filters:
            - name: envoy.router
              config: {}
```
mirror-crash-route.yaml content:
```yaml
version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: default
    virtual_hosts:
      - name: virtual_host_0
        domains: ["*"]
        routes:
          - match:
              prefix: "/"
            route:
              host_rewrite: www.google.com
              cluster: service_google
              request_mirror_policy:
                cluster: invalid

```
Version:
```
./envoy-static  version: 5a3baabe12152dea0f423065fba85f9618b676a3/1.8.0-dev/Clean/DEBUG
```
To reproduce the crash I'm starting it like this:
```
 ./envoy-static -c mirror-crash.yaml --log-path crash.log
``` 
and sending a http request to http://localhost:10000.

*Config*:

I had to rename all the files to ".txt" so I could upload them.

[config_dump.txt](https://github.com/envoyproxy/envoy/files/2407819/config_dump.txt)
[mirror-crash.yaml.txt](https://github.com/envoyproxy/envoy/files/2407811/mirror-crash.yaml.txt)
[mirror-crash-route.yaml.txt](https://github.com/envoyproxy/envoy/files/2407812/mirror-crash-route.yaml.txt)

*Logs*:
[crash.log](https://github.com/envoyproxy/envoy/files/2407809/crash.log)
