### ISSUE TITLE
RBAC Filter Envoy Proxy Usage

### ISSUE THREAD

**Issue by gupash** [envoyproxy/envoy#4542]
**Help Wanted**

*Title*: *I want some sample example of RBAC network filter usage with complete envoy yml configuration*

*Description*:
>I want to implement something like this in a RBAC filter

Below is just a sudo config of what I want:
```
network_filters:
     - name: envoy.rbac
       config:  
             rules:
                 action: ALLOW
                 policies:
                     "service-access":
                         principals:
                            source_ip: 192.168.135.211/32
                         permissions:
                            - destination_ip: 0.0.0.0/32
                            - destination_port: 443
```

**Comment by mimiasd** [comment]
```
static_resources:
  listeners:
  - name: "ingress listener"
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9001
    filter_chains:
      filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"  
                route:
                  cluster: local_service
                per_filter_config:
                  envoy.filters.http.rbac:
                    rbac:
                      rules:
                        action: ALLOW
                        policies:
                          "per-route-rule":
                            permissions:
                            - any: true
                            principals:
                            - any: true
          http_filters:
          - name: envoy.filters.http.rbac 
            config: 
              rules: 
                action: ALLOW
                policies:
                  "general-rules":
                    permissions:
                    - any: true
                    principals:
                    - any: true
          - name: envoy.router
            config: {}
          access_log:
            name: envoy.file_access_log
            config: {path: /dev/stdout}

  clusters:
  - name: local_service
    connect_timeout: 0.250s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9000

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8080

```
@gupash can do like this.  RBAC is a great feature. @mattklein123
