### ISSUE TITLE
Envoy leaks cluster members when using  STRICT_DNS and ClusterLoadAssignment

### ISSUE THREAD

**Issue by devshorts** [envoyproxy/envoy#4548]
*Title*: Envoy leaks cluster members when using  STRICT_DNS and ClusterLoadAssignment

*Description*:
We are using envoy sha f1aee97b079ad4a0130583ef7cd656351dd70bd7 with a configuration that sets up DNS entries in our cluster load assignment registered via a CDS

```
"load_assignment": {
     "cluster_name": "cluster_name",
     "endpoints": [
      {
       "lb_endpoints": [
        {
         "endpoint": {
          "address": {
           "socket_address": {
            "address": "host1",
            "port_value": 10652
           }
          }
         }
        }
       ],
       "load_balancing_weight": 70
      },
      {
       "lb_endpoints": [
        {
         "endpoint": {
          "address": {
           "socket_address": {
            "address": "host2",
            "port_value": 10652
           }
          }
         }
        }
       ],
       "load_balancing_weight": 30
      }
     ]
    }
   },
```

When we had this envoy would resolve the DNS and continuously say in the debug logs that the hosts have changed, and so it would add new members to the cluster.  The only indication this was happening was in the cluster membership add/change stats and the cluster member list under 9901/clusters.  The config dump always showed the correct load assignment configuration. 

I should note that the host names in our cluster addresses were aliased in /etc/hosts and did not need to be resolved via pure DNS. I tried to replicate this scenario in a docker container using a public IP like from google.com but was unable to reproduce it, so not sure if this is related.

When members are configured with health checks we ended up in a situation with a health check DDOS as envoy kept adding new cluster members.  

We switched over to using STATIC ip addresses, with the exact same configuration, and the membership changes stopped and stabilized.

**Comment by dio** [comment]
Sure @mattklein123 I've been trying to look at the issue. Will do on the weekend if required since I'm travelling back today.

Paging @snowp too just in case you have spare cycles for this 🙂. Thanks!

**Comment by dio** [comment]
Hum, seems false positive. Will investigate more.

**Comment by dio** [comment]
There are at least to issues here:

1. The `updateDynamicHostList` is called per resolve async process, hence the `all_hosts_` is not updated properly by the `updated_hosts`.
2. The final_hosts can have duplicated hosts.

**Comment by snowp** [comment]
I think there is an issue in that the `all_hosts_` stuff was based around the idea that the entire cluster is updated at once. This holds true for EDS where the entire cluster EDS update comes at once, but not true for STRICT_DNS since it's callback based per resolve target.

I think we probably want to not use the `updated_hosts` mechanism for STRICT_EDS (since it's based around updating an entire priority) and instead keep track of what hosts were resolved per resolve target. With that, we could compute the diff for each resolve target after resolution and update `all_hosts_` based on that (allowing cross priority moves).

**Comment by devshorts** [comment]
@dio its tough for me to test out a new build unfortunately,  we use a custom fork here at stripe and we pull in the main line patches as necessary. Basically its a pain in the butt for me to fire off new builds :/ . If you do need a beta tester let me know and I can go through the process to do it, but just wanted to respond and let you know I wasn't ignoring your request

**Comment by tonya11en** [comment]
@dio I'm pretty we're hitting this issue here at Lyft and I can try to test it out.

**Comment by dio** [comment]
@tonya11en much appreciated! That will be really helpful. Thank you!

**Comment by tonya11en** [comment]
@dio I was in the process of building/testing the change, but I have to revert the change that introduces this bug for now. I can see if we can introduce the issue to a subset of our fleet, but if the change looks OK to merge, I think we should just go ahead and then I can just deploy it and monitor.

Let me know if that works for you.

**Comment by dio** [comment]
@tonya11en I think that’s fine. Out of curiosity, which commit do you think introducing this bug?

**Comment by tonya11en** [comment]
Sorry, I meant I'm reverting the configuration that allows this bug to manifest. It's hard to tell exactly which commit introduces this, but my first guess is that when `b32eabfc141760ec14622a4a2a2f0ab0a741cd6c` went out:
```
commit b32eabfc141760ec14622a4a2a2f0ab0a741cd6c
Author:     Dhi Aurrahman <dio@rockybars.com>
AuthorDate: Wed Jul 25 00:01:23 2018 +0700
Commit:     htuch <htuch@users.noreply.github.com>
CommitDate: Tue Jul 24 12:01:23 2018 -0500

    upstream: implement Cluster's load_assignment field (#3864)
    
    This patch implements load_assigment field in CDS' Cluster.
    This change specifically adds the implementation of the new load_assigment field
    for clusters with discovery-type: STATIC, STRICT_DNS and LOGICAL_DNS.
    
    While adding this load_assigment field implementation to Cluster,
    this patch also allows specifying optional (active) health check config per specified upstream host.
    
    Risk Level: medium
    Testing: unit tests
    Docs Changes:
    
    This unhides docs for endpoint health check config
    Release Notes: N/A
    
    Fixes #439
    
    Signed-off-by: Dhi Aurrahman <dio@rockybars.com>
```

it didn't check for duplicate entries in the envoy config introduced via something like:
```
    load_assignment:
      cluster_name: tony_example_name
      endpoints:
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: {address: localhost, port_value: 9201, protocol: TCP}
        priority: 0 # Lower number is higher priority.
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: {address: localhost, port_value: 9201, protocol: TCP}
        priority: 0 # Lower number is higher priority.
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: {address: localhost, port_value: 9201, protocol: TCP}
        priority: 0 # Lower number is higher priority.
      - lb_endpoints:
          - endpoint:
              address:
                socket_address: {address: localhost, port_value: 9202, protocol: TCP}
        priority: 1 # Lower number is higher priority.
```

But I didn't really do the necessary forensics. I'm still not sure whether the priority state manager should have been resilient to this or whether we should have caught this in the config... Either way, I think your change will fix this. Once it gets merged, we'll deploy it within a few days at Lyft and I can report back here if the problem persists.
