### ISSUE TITLE
Feature Request: Pass request url to gRPC rate limit service

### ISSUE THREAD

**Issue by TylerZale** [envoyproxy/envoy#4656]
Background
===

We would like to be able to do rate limiting logic based on the request url inside the custom gRPC service.

The Feature Request
===

Create a new route.RateLimit.Action [https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-ratelimit]

to pass the request url to the gRPC service.

**Comment by mattklein123** [comment]
@TylerZale can't you already send a header as a key? https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#route-ratelimit-action-requestheaders and then send the ":path" header?

**Comment by TylerZale** [comment]
Hi @mattklein123 , 

Thank you, you are right, that worked.

```
rate_limits:
  actions:
    - generic_key:
       descriptor_value: "api"
    - request_headers:
       header_name: ":path"
       descriptor_key: "path"
```


I'll make mention of that in the slack channel. You might want to add that to the documentation (or link to it if its there somewhere.)


TZ
