### ISSUE TITLE
Downstream metric vs. upstream mismatch during route addition

### ISSUE THREAD

**Issue by mhite** [envoyproxy/envoy#4673]
*Description*:

When adding a new route, upstream cluster metrics spike (for example, `envoy.cluster.upstream_rq_xx`) with a corresponding HTTP connection manager downstream drop.

The following graph from Datadog represents upstream responses from an impacted microservice API in our Kubernetes cluster. While we do expect some brief spikes as we roll envoy (we do not use a control plane to configure it currently, so no live config swap), the spike never subsides until I roll back the route addition change being introduced. In fact, it almost looks like metrics are double counted on upstream during the event.

<img width="1647" alt="screen shot 2018-10-10 at 9 27 46 am" src="https://user-images.githubusercontent.com/1464385/46753687-61de5200-cc75-11e8-9c7a-2f6595bd7dd2.png">

Here is the `envoy.http.downstream_rq_xx` metrics for our external HTTP connection manager (which corresponds to the aforementioned upstream graph).

<img width="1648" alt="screen shot 2018-10-10 at 9 37 40 am" src="https://user-images.githubusercontent.com/1464385/46753705-6b67ba00-cc75-11e8-99df-f0b10217e009.png">

The load balancer statistics for the Google Cloud Platform Global Load Balancer which sits in front of all this looks unaffected.

<img width="1650" alt="screen shot 2018-10-10 at 9 24 07 am" src="https://user-images.githubusercontent.com/1464385/46753720-74588b80-cc75-11e8-917c-55db7947a768.png">

This implies that traffic is not actually disrupted for our users (I think).

The following route is being introduced when the issue is triggered, although it appears to be any route addition that triggers the issue.

```
                          - match:
                              prefix: /userprofilephoto.UserProfilePhotoService/
                            route:
                              cluster: user-profile-photo/user-profile-photo
```

… with the following cluster definition:

```
         - name: user-profile-photo/user-profile-photo
           type: STRICT_DNS
           connect_timeout: 0.25s
           lb_policy: LEAST_REQUEST
           http2_protocol_options: {}
           hosts:
             - socket_address:
                 protocol: TCP
                 address: user-profile-photo.user-profile-photo
                 port_value: 8080
```

I am running 1.7.0 envoy. I have looked through the release notes for 1.7.1 and 1.8.0 for items that might be related but I’m coming up empty. (This doesn’t mean I’m not missing something, I’m just not terribly envoy savvy yet nor am I a C++ developer.) I have not tried upgrading to 1.8.0 yet. It's definitely on the table.

Is this a bug? Am I potentially doing something wrong? Here is a sanitized configuration I am working with:

```
---
# Source: envoy-front-proxy-helm/templates/ConfigMap.yaml
 
    stats_sinks:
      - name: envoy.dog_statsd
        config:
          address:
            socket_address:
              protocol: UDP
              address: <redacted>
              port_value: 8125
    stats_config:
      stats_tags:
        tag_name: envoy-deployment
        fixed_value: envoy-front-proxy
      use_all_default_tags: true
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      listeners:
        - name: public-internet-http-ingress
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8000
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  codec_type: AUTO
                  stat_prefix: external_http
                  idle_timeout:
                    seconds: 10
                  use_remote_address: true
                  xff_num_trusted_hops: 2
                  http_filters:
                    - name: envoy.health_check
                      config:
                        pass_through_mode: false
                        endpoint: /healthcheck
                    - name: envoy.gzip
                    - name: envoy.router
                  access_log:
                    name: envoy.file_access_log
                    filter:
                      not_health_check_filter: {}
                    config:
                      path: /dev/stdout
                      format: >+
                        [access.log][external][%START_TIME%] "%REQ(:METHOD)%
                        %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
                        %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED%
                        %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%
                        "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%"
                        "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
                        
                  route_config:
                    virtual_hosts:
                      - name: backend
                        domains: ["*"]
                        routes:
                          - match:
                              prefix: /REDACTED1
                            route:
                              cluster: REDACTED2/REDACTED3
                              prefix_rewrite: /
                          - match:
                              prefix: /REDACTED4/
                            route:
                              cluster: REDACTED5/REDACTED6
                              prefix_rewrite: /
                          - match:
                              prefix: /REDACTED7/
                            route:
                              cluster: REDACTED8/REDACTED9
                              prefix_rewrite: /
                          - match:
                              prefix: /REDACTED10/
                              case_sensitive: false
                            route:
                              cluster: REDACTED11/REDACTED12
                        virtual_clusters:
                          - name: REDACTED13-thumbnail-get
                            pattern: ^\/REDACTED14\/v\d+\/thumbnail\/(small|large)\/[a-zA-Z0-9-]+$
                            method: GET
                          - name: REDACTED15-get-all
                            pattern: ^\/REDACTED16(\/v\d+)?\/-\/-.*
                            method: GET
                          - name: REDACTED16-search
                            pattern: ^\/REDACTED17(\/v\d+)?\/-\/[^-].*
                            method: GET
                          - name: REDACTED18-get
                            pattern: ^\/REDACTED19(\/v\d+)?\/[a-zA-Z0-9-]{36}\/.*
                            method: GET
                          - name: REDACTED20-create
                            pattern: ^\/REDACTED21(\/v\d+)?\/[a-zA-Z0-9-]{36}$
                            method: POST
                          - name: REDACTED22-update
                            pattern: ^\/REDACTED23(\/v\d+)?\/[a-zA-Z0-9-]{36}$
                            method: PUT
                          - name: REDACTED24-delete
                            pattern: ^\/REDACTED25(\/v\d+)?\/[a-zA-Z0-9-]{36}$
                            method: DELETE
                          - name: REDACTED26-metadata-get
                            pattern: ^\/REDACTED27\/v\d+\/metadata\/[a-zA-Z0-9-]{36}$
                            method: GET
                          - name: REDACTED28-metadata-get-all
                            pattern: ^\/REDACTED29\/v\d+\/metadata\/-$
                            method: GET
                          - name: REDACTED30-content-get
                            pattern: ^\/REDACTED31\/v\d+\/content\/[a-zA-Z0-9-]{36}$
                            method: GET
                          - name: REDACTED32-utility-enable
                            pattern: ^\/REDACTED33(\/v\d+)?\/enabled$
                            method: GET
                          - name: REDACTED34-utility-enable-beta
                            pattern: ^\/REDACTED35(\/v\d+)?\/enabled\?beta=(true|false)$
                            method: GET
                          - name: REDACTED36-utility-health
                            pattern: ^\/REDACTED37\/health$
                            method: GET
                          - name: REDACTED38-utility-stat
                            pattern: ^\/REDACTED39\/v\d+\/stat\/[a-zA-Z0-9-]{36}\/\w+$
                            method: POST
                          - name: REDACTED40-utility-health
                            pattern: ^\/REDACTED41\/v\d+\/health$
                            method: GET
                          - name: REDACTED42-get-all
                            pattern: ^\/REDACTED43\/v\d+$
                            method: GET
                          - name: REDACTED44-get-single
                            pattern: ^\/REDACTED45\/v\d+\/[a-zA-Z0-9-]{36}$
                            method: GET
                          - name: REDACTED46-create-task
                            pattern: ^\/REDACTED47\/v\d+$
                            method: POST
                          - name: REDACTED48-update-single
                            pattern: ^\/REDACTED49\/v\d+\/[a-zA-Z0-9-]{36}$
                            method: PUT
                          - name: REDACTED50-delete-single
                            pattern: ^\/REDACTED51\/v\d+\/[a-zA-Z0-9-]{36}$
                            method: DELETE
                          - name: REDACTED52-bulk-update
                            pattern: ^\/REDACTED53\/v\d+\/bulk$
                            method: POST
        - name: internal-http-ingress
          address:
            socket_address:
              protocol: TCP
              address: 0.0.0.0
              port_value: 8002
          filter_chains:
            filters:
              - name: envoy.http_connection_manager
                config:
                  codec_type: AUTO
                  stat_prefix: internal_http
                  idle_timeout:
                    seconds: 60
                  use_remote_address: true
                  http_filters:
                    - name: envoy.health_check
                      config:
                        pass_through_mode: false
                        endpoint: /healthcheck
                    - name: envoy.router
                  access_log:
                    name: envoy.file_access_log
                    filter:
                      not_health_check_filter: {}
                    config:
                      path: /dev/stdout
                      format: >+
                        [access.log][internal][%START_TIME%] "%REQ(:METHOD)%
                        %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
                        %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED%
                        %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%
                        "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%"
                        "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
                        
                  route_config:
                    virtual_hosts:
                      - name: backend
                        domains: ["*"]
                        routes:
                          - match:
                              prefix: /REDACTED53
                            route:
                              cluster: REDACTED54/REDACTED55
                              prefix_rewrite: /
                          - match:
                              prefix: /userprofilephoto.UserProfilePhotoService/
                            route:
                              cluster: user-profile-photo/user-profile-photo
                          - match:
                              prefix: /REDACTED56/
                            route:
                              cluster: REDACTED57/REDACTED58
                          - match:
                              prefix: /REDACTED59/
                            route:
                              cluster: REDACTED60/REDACTED61
                          - match:
                              prefix: /REDACTED62/
                            route:
                              cluster: REDACTED63/REDACTED64
                          - match:
                              prefix: /REDACTED65/
                            route:
                              cluster: REDACTED66/REDACTED67
                          - match:
                              prefix: /REDACTED68
                            route:
                              cluster: REDACTED69/REDACTED70
                          - match:
                              prefix: /REDACTED71/
                            route:
                              cluster: REDACTED72/REDACTED73
                          - match:
                              prefix: /REDACTED74/
                            route:
                              cluster: REDACTED75/REDACTED76
                          - match:
                              prefix: /REDACTED77/
                            route:
                              cluster: REDACTED78/REDACTED79
                          - match:
                              prefix: /REDACTED80/
                            route:
                              cluster: REDACTED81/REDACTED82
                          - match:
                              prefix: /REDACTED83/
                            route:
                              cluster: REDACTED84
      clusters:
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 80
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8080
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8090
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8091
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 80
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 80
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 80
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8000
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 9757
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8001
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8888
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8200
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8440
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 9000
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 28100
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8081
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8421
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8082
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8081
        - name: REDACTED
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: REDACTED
                port_value: 8448
        - name: user-profile-photo/user-profile-photo
          type: STRICT_DNS
          connect_timeout: 0.25s
          lb_policy: LEAST_REQUEST
          http2_protocol_options: {}
          hosts:
            - socket_address:
                protocol: TCP
                address: user-profile-photo.user-profile-photo
                port_value: 8080
```

I am happy to provide the un-redacted configuration through a non-public channel for further investigation efforts.

All help appreciated. We're stuck.
