### ISSUE TITLE
Allow changing header matched on for virtual hosts

### ISSUE THREAD

**Issue by snowp** [envoyproxy/envoy#4690]
We'd like to be able to specify which header(s) should be consulted when determining what virtual host to route to. Currently this reads the Host header, which means that for clients that don't allow overriding the Host header on a per-call basis (e.g. gRPC) we end up having to maintain one client per Host header we want to use. Since we're not using TLS in this case the extra clients are unnecessary and just ends up complicating our Envoy client libraries. 

I'd love to have a `domain_header` option on the vhost that specifies a list of headers that are consulted, using the first non-empty. This would let me put `domain_header: [virtual-host, :authority]`, allowing me to use `virtual-host` to determine what virtual host to use while also being able to fall back to using Host for other clients (e.g curl).

Another option would be a `alternative_domain_header` that allows setting a single header that is consulted before the Host header. This would ensure Envoy is well behaved wrt to the Host header but also allow our use case of having a single client target multiple vhosts. 

A third option would be to simply introduce a `x-envoy-virtual-host` header that accomplishes all of this without any additional configuration.

**Comment by mattklein123** [comment]
Having the `domain_header` option which defaults to `:authority` makes sense to me. @envoyproxy/maintainers any thoughts?

**Comment by htuch** [comment]
@AndresGuedez has a design proposal that provides a superset of this capability. I think stay tuned for him to share the doc ("Scoped RDS").

**Comment by AndresGuedez** [comment]
@snowp PTAL at #4704, where I propose API enhancements that could support your use case. You would need to create a routing configuration scope per `virtual-host`, and clone the `RouteConfiguration` for each scope, changing the `Route`'s action as needed per `virtual-host`.

I recognize the increase in configuration complexity may not be worth it for this particular use case, and the proposed `domain_header` may still make sense, but if you have other requirements that could be satisfied by the introduction of scopes, my proposal may of interest.

**Comment by htuch** [comment]
I think we want economy of mechanism in the API, so if #4704 works for @snowp, we can close this out as dupe.

**Comment by snowp** [comment]
If I understand the proposal correctly, I would change my current setup of (1 RouteConfiguration with N vhosts) to (N RCs with one vhost), deciding which RC to use by defining an scoped key builder that inspects Host or `virtual-host` ? 

Sounds like it would work for us. We might even want to use the new API for perf reasons (we sometimes end up with a lot of vhosts) so I'm not concerned about the additional API complexity. I'll close this out

**Comment by AndresGuedez** [comment]
> If I understand the proposal correctly, I would change my current setup of (1 RouteConfiguration with N vhosts) to (N RCs with one vhost), deciding which RC to use by defining an scoped key builder that inspects Host or `virtual-host` ?

That's pretty close to what I'm envisioning, except that the ScopeKeyBuilder config would only need to deal with the 'virtual-host' header. E.g., with config defined as follows:

(This config doesn't actually map to valid Envoy YAML or JSON, but should be sufficient for this example)
RC1: { domains: [ www.service.com ], routes: [ { ..., cluster: clusterA } ] } 

Virtual-Host: service1
Host: www.service.com

**Comment by AndresGuedez** [comment]
> If I understand the proposal correctly, I would change my current setup of (1 RouteConfiguration with N vhosts) to (N RCs with one vhost), deciding which RC to use by defining an scoped key builder that inspects Host or virtual-host ?

That's pretty close to what I'm envisioning, except that the ScopeKeyBuilder config would only need to deal with the 'virtual-host' header. 

E.g., with config defined as follows:

(NOTE: this RouteConfiguration config doesn't actually map to valid Envoy YAML or JSON, but should be sufficient for this example)
```
RC1: { virtual_host: { name: vhost1, domains: [ www.service.com ], routes: [ { ..., cluster: clusterA } ] }
RC2: { virtual_host: { name: vhost1, domains: [ www.service.com ], routes: [ { ..., cluster: clusterB } ] }
```

(The following would actually be valid YAML)
```
scoped_route_config:
  name: scoped_routes                                                                                                                                  
  scope_key_builder:
   fragments:
      - header_element:
        name: Virtual-Host
                                                                                                                                  
  scopes:
   - route_configuration_name: RC1
     key:
        fragments:
          - string_key: service1
    - route_configuration_name: RC2
      key:
        fragments:
          - string_key: service2
```

Requests would be routed as follows:

```
Virtual-Host: service1
Host: www.service.com

-> routed to clusterA

Virtual-Host: service2
Host: www.service.com

-> routed to clusterB
```
