### ISSUE TITLE
Unable to get new style (websocket) upgrades work

### ISSUE THREAD

**Issue by containscafeine** [envoyproxy/envoy#4740]
*Description*:

I was trying to get websockets to work with the new style upgrade support as detailed at https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/websocket#new-style-upgrade-support

Well, the old style support works when I use `use_websocket` field, but the new style does not.

I am getting 403 return codes like such -
```console
$ wscat --connect localhost:10000/
error: Unexpected server response: 403
```

The right connection looks like -
```console
$ wscat --connect echo.websocket.org
connected (press CTRL+C to quit)
> Test
< Test
```

*Config for repro*:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          upgrade_configs:
          - upgrade_type: websocket
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite: echo.websocket.org, cluster: websocket_cluster }
          http_filters:
          - name: envoy.router
  clusters:
  - name: websocket_cluster
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 10s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: echo.websocket.org, port_value: 80 }}]
```

I am running this config in the latest envoy container image - `envoyproxy/envoy:latest`

**Comment by alyssawilk** [comment]
Any chance you can dump the headers wscat is sending?

**Comment by containscafeine** [comment]
Sure. FWIW here are the complete envoy debug logs - https://paste.fedoraproject.org/paste/kzlq8rlvqJvbEjzfWlMK8g

The headers that I got from the logs are -
```
':authority', 'localhost:10000'
':path', '/'
':method', 'GET'
'sec-websocket-version', '13'
'sec-websocket-key', 'Hw9E5mkN5YkVVdE9slR/vQ=='
'connection', 'Upgrade'
'upgrade', 'websocket'
'sec-websocket-extensions', 'permessage-deflate; client_max_window_bits'
```

**Comment by containscafeine** [comment]
Hey, thanks for the quick response @alyssawilk, really appreciate it :)

I am running with `envoyproxy/envoy:latest` container image, with the command - `docker run --name envoy --rm -p 10000:10000 -p 9901:9901 -v /tmp/test.yaml:/test.yaml envoyproxy/envoy:latest envoy -c test.yaml -l trace`, I _assume_ it points to HEAD.

Here are the logs with `-l trace` - https://paste.fedoraproject.org/paste/6np-~Eb6U6mckpVrBHCdug

**Comment by containscafeine** [comment]
Wait, it could be a bug. I just tried this with `envoyproxy/envoy:v1.8.0` image and it worked :thinking:

**Comment by containscafeine** [comment]
@mattklein123 not sure if this is a question anymore, it's a bug, no?

**Comment by alyssawilk** [comment]
Are you still able to replicate the failed behavior?

**Comment by containscafeine** [comment]
@alyssawilk yep, fails on `envoy:latest` but works on `envoy:v1.8.0`

**Comment by moderation** [comment]
nghttp2 1.34.0 contains a websocket fix that @alyssawilk worked on ([PR](https://github.com/nghttp2/nghttp2/pull/1231) and [issue](https://github.com/nghttp2/nghttp2/issues/1181)). Does this have bearing on this issue?

**Comment by alyssawilk** [comment]
I think that should be for H2 websocket support, which is still hidden in Envoy configs due to us not pulling nghttp2 latest.  I believe this problem is with HTTP/1.1 so probably not related

I'll see if I can repro with envoy:latest today

**Comment by alyssawilk** [comment]
Sadly, I still can't repro.  Can you determine if you can reproduce on envoy:latest with the telnet command I ran? 
When I run against docker latest I still get an upgrade response and I'm unsure if we're still somehow running something different or if there's some subtle difference in what wscat is doing and what I'm doing.

**Comment by alyssawilk** [comment]
Also bonus points if you're willing to remove your local copy of envoy:latest.  I usually just kill all docker state with

docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
rm -rf /tmp/envoy-docker-build/*

but that's probably overkill.  I'm wondering if somehow your docker:latest got pinned to a stale/bad version?

**Comment by containscafeine** [comment]
@alyssawilk sorry, missed the notifications. I just tried this today with the latest image and it works :+1: Thanks for the help! :)

**Comment by andrewwebber** [comment]
If anyone is still having issues upgrading, check the order of your http filters as they have been inverted.

Breaks
```yaml
- name: envoy.buffer
  config:
    max_request_bytes: 100000
    max_request_time: 36s
- name: envoy.router
```
Works
```yaml
- name: envoy.router
- name: envoy.buffer
  config:
    max_request_bytes: 100000
    max_request_time: 36s
```
