### ISSUE TITLE
https_redirect does not correctly handle presence of a port in the request Host header

### ISSUE THREAD

**Issue by georgi-d** [envoyproxy/envoy#4832]
When a route action is configured to do https_redirect and a request is send with a port specified in the Host header the port is preserved in the response leading to incorrect behavior.

*Repro steps*:
- Configure a route to do https_redirect
- send a request which includes Host header with port `:80` in it.

```
curl -v http://localhost:80/redirect_to_https   -H "Host: localhost:80"
> GET /redirect_to_https HTTP/1.1
> User-Agent: curl/7.19.7 
> Accept: */*
> Host: localnost:80
>
< HTTP/1.1 301 Moved Permanently
< location: https://localhost:80/redirect_to_https
< server: envoy
< content-length: 0
<
```

It can be seen that the original port 80 was pereserved in the Location header.

Envoy should at least recognize port 80 as the default HTTP port and change it to 443 or just remove it in the Location header.

*Config*:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/redirect_to_https"
                redirect:
                  https_redirect: true
          http_filters:
          - name: envoy.router
            config: {}
```
