### ISSUE TITLE
Add support for sending data in Zipkin v2 format

### ISSUE THREAD

**Issue by adriancole** [envoyproxy/envoy#4839]
*Title*:  Add support for sending data in Zipkin format

*Description*:
It would be really helpful to support sending data in zipkin v2 json for reasons of efficiency and reduced tech debt in trace data pipelines. This could go alongside the existing functionality. While proto3 is even more efficient, it could be optional as most don't use that.

---

Zipkin's data format has been historically criticized for its heft. Through community effort, last August 2017 we formalized a compact v2 json, accepted on all transports including http, kafka, rabbit, etc. Later, we introduced a proto3 encoding of the same, also accepted on all transports.

Between last August and now, this format has become the primary and preferred format, especially to those trying to work with the data.  For example, at a recent meeting we've found that envoy is a key piece of the network that still emits the v1 format, requiring "rosetta stone" style proxies.

This is fine in pure zipkin installs as the server reads all historical formats, but is limiting for those using different pipelines. A switch to v2 would also work with zipkin clones such as jaeger who also support that format.

[original spec for zipkin and envoy](https://docs.google.com/document/d/1q3F_RVf6Rozn69KbqhrKknOZP9_17WH1RK3wIc7AnuE/edit#)
[json v2 encoding](https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml)
[proto3 encoding](https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto)
[trace data pipeline meeting](https://cwiki.apache.org/confluence/display/ZIPKIN/2018-09-20+Filtering%2C+Aggregations+and+Proxies+at+Salesforce) 
[jaeger's v2 support](https://github.com/jaegertracing/jaeger/blob/7262bdc9e59933f15fb0802f0d3ba7fb642a8955/cmd/collector/app/zipkin/http_handler.go#L112)

**Comment by adriancole** [comment]
@zyfjeff wondering if you have some time to help with this. It would be really appreciated by the community, especially those who write their own proxies.

**Comment by adriancole** [comment]
sorry to nag you @zyfjeff but you've done the only major work on zipkin side recently. there are few people with c++ experience in the ecosystem.. would others be able to help you with something you need in order to clear time to help them? For example, I recently help with alibaba dubbo. I think others may be able to help you'all some how to make mutual benefit. I fear no one will work on this unless someone like you does.

**Comment by zyfjeff** [comment]
@adriancole 
Sorry, I have been doing Envoy's secondary development for the company recently. I will take some time this month to familiarize myself with the Zipkin v2 format. I am willing to help the community to complete this issue, but I can't guarantee that it will be completed soon.

@mattklein123  please assign to  me

**Comment by adriancole** [comment]
@zyfjeff thanks for even considering this.. starting is the first step in finishing (or so my span says)

**Comment by adriancole** [comment]
if any questions ask on https://gitter.im/openzipkin/zipkin I've alerted the team to watch for you!

**Comment by zyfjeff** [comment]
OK, I am happy to help the community.

**Comment by devinsba** [comment]
@zyfjeff If you can help get me started on where I would want to change I might be able to start the ball rolling on this. I've got a working dev environment from my small contribution about a year ago, so I only have to update that.

**Comment by zyfjeff** [comment]
@devinsba  Are you still continue to work? I recently ready to solve this problem

@adriancole 
If the v2 format is supported, how is the format of v1 handled? Or is it made configurable?

**Comment by foshantiger** [comment]
Any progress on this issue?

**Comment by shakuzen** [comment]
> If the v2 format is supported, how is the format of v1 handled? Or is it made configurable?

@zyfjeff if you are asking about Zipkin Server: v1 write endpoints are still available on the server, in addition to v2 read/write endpoints. If you mean tracers, they typically include a configuration option for the endpoint and encoding to send spans.

**Comment by adriancole** [comment]
@Dudi119 any chance you can help with this? everyone in the ecosystem including zipkin clones are affected by lack of v2 support and it seems the project maintainers are still not doing this on own

**Comment by adriancole** [comment]
ps the next version of zipkin (2.13) will also have a grpc endpoint with exact same proto3 message as http post /api/v2/spans

https://github.com/apache/incubator-zipkin-api/blob/master/zipkin.proto#L224

that said I think most clones likely will want the json endpoint (not that it is mutually exclusive)

**Comment by objectiser** [comment]
Another option may be https://github.com/envoyproxy/envoy/pull/5387 - as I believe there is a zipkin v2 exporter. Looks pretty close to being merged.

**Comment by devinsba** [comment]
If I were a maintainer of envoy, I would not merge that request due to the upcoming merger of census and OT, I would let that settle and then bring in the merged c++ client. But that is just my 2p

**Comment by Dudi119** [comment]
@adriancole sure, happy to help.

**Comment by cetanu** [comment]
We've found issues with the OpenCensus and OT tracers, as they do not add the B3 propagation headers to the request sent upstream. I think that supporting the Zipkin v2 format with the existing Zipkin tracer should not be that difficult?? If someone can point me at the files I would need to change, maybe I can make a PR for it.

**Comment by adriancole** [comment]
my guess is someone could pickup where these last stalled due to people's lives getting too busy. I know @basvanbeek was interested in this, too https://github.com/envoy-zipkin/envoy/pull/3

**Comment by dio** [comment]
Yeah. Sorry for this. @cetanu let me prepare some playground for it and let you know. I’ll sync with @basvanbeek as well.

**Comment by mattbailey** [comment]
So, this is effectively overcome if you use the opencensus driver, which will export via zipkin v2, like this:

```yaml
tracing:
  http:
    name: envoy.tracers.opencensus
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v2.OpenCensusConfig
      zipkin_exporter_enabled: true
      zipkin_url: http://127.0.0.1:19000/trace
      zipkin_service_name: myservice
      outgoing_trace_context: [ "TRACE_CONTEXT", "GRPC_TRACE_BIN" ]
```

My configuration is such that I also require adding an API key to the trace server, so I feed it through envoy as a listener:

```yaml
static_resources:
  listeners:
  - name: trace
    address:
      socket_address: { address: 0.0.0.0, port_value: 19000 }
    filter_chains:
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: zipkin_http
          route_config:
            name: local_route
            request_headers_to_add:
            - header: { key: "Api-Key", value: "MYAPIKEY" }
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { path: "/trace" }
                route: { auth_host_rewrite: true, cluster: "zipkin_outbound" }
          http_filters:
          - name: envoy.router
  clusters:
    - name: zipkin_inbound
      connect_timeout: 1s
      type: STATIC
      http_protocol_options: {}
      load_assignment:
        cluster_name: zipkin_inbound
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: 127.0.0.1
                  port_value: 19000
    - name: zipkin_outbound
      connect_timeout: 1s
      type: LOGICAL_DNS
      lb_policy: ROUND_ROBIN
      dns_lookup_family: V4_ONLY
      respect_dns_ttl: true
      http_protocol_options: {}
      tls_context: {}
      load_assignment:
        cluster_name: zipkin_outbound
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: ACTUAL_ZIPKIN_SERVER.com
                  port_value: 443
```

The added benefit here is that if this is acting as a sidecar, the actual upstream server can also use this exposed listener and not have to be concerned with the api key or other configuration.
