### ISSUE TITLE
unhealthy_interval doesn't work

### ISSUE THREAD

**Issue by misterwilliam** [envoyproxy/envoy#4902]
*Title*: *unhealthy_interval doesn't work*

*Description*:

For health check config:
```
       health_checks:
      - timeout: 60s
        interval: 60s
        unhealthy_interval: 0.1s
        unhealthy_threshold: 1
        healthy_threshold: 1
        tcp_health_check: {}
```

I expect a TCP connection attempt every 0.1 seconds for an unhealthy backend. It looks like it is happening every 1 minute.

*Repro steps*:

1.  I created a health check config like the following:
     ```
       health_checks:
      - timeout: 60s
        interval: 60s
        unhealthy_interval: 0.1s
        unhealthy_threshold: 1
        healthy_threshold: 1
        tcp_health_check: {}
     ```
     As a reverse proxy to port 8080
     ```
       filter_chains:
       - filters:
         - name: envoy.http_connection_manager
           config:
             stat_prefix: ingress_http
             codec_type: AUTO
             stream_idle_timeout: 3600s
             route_config:
               name: local_route
               virtual_hosts:
               - name: local_service
                 domains:
                   - "*"
                 routes:
                 - match:
                     prefix: "/"
                   route:
                     cluster: worker_endpoint
                     timeout: 300s
    clusters:
     - name: worker_endpoint
       connect_timeout: 1s
       type: STRICT_DNS
      lb_policy: ROUND_ROBIN
       hosts:
         socket_address:
           address: 127.0.0.1
           port_value: 8080
     ```
1.  Launch Envoy.
1.  Run tcpdump on 8080
     ```
     $ sudo tcpdump -i lo -nn -v port 8080
     ```
1.  Look at clusters/ verify worker_container is marked as unhealthy

What I expect to see is that tcpdump shows a TCP connection attempt every 0.1 seconds, but I don't see that. It looks more like every 1 minute.
