### ISSUE TITLE
CORS headers missing from response

### ISSUE THREAD

**Issue by arianmotamedi** [envoyproxy/envoy#4919]
I'm trying to add a CORS policy to my only virtual_host in the ingress listener:

```
"route_config": {
"virtual_hosts": [
  {
    "routes": [
      {
        "route": {
          "cluster": "my-service",
          "timeout": "60s"
        },
        "match": {
          "prefix": "/"
        }
      }
    ],
    "cors": {
      "allow_headers": "Authorization,Content-Type, correlationid",
      "allow_origin": [
        "my-domain.com"
      ],
      "allow_methods": "GET, POST, PUT, HEAD, OPTIONS"
    },
...
```

Based on [implementation details](https://github.com/envoyproxy/envoy/issues/300#issuecomment-296796675) for CORS, having this should allow me to do an OPTIONS request and get a 200 OK back with the corresponding CORS headers in the response. However, it looks like my OPTIONS request is bypassing this filter altogether and getting to my application (which then responds with a 405 error):

```
# curl -v https://my-service -X OPTIONS -H 'Origin: foo.com'
*   Trying 172.20.244.140...
* TCP_NODELAY set
* Connected to my-service (172.20.244.140) port 443 (#0)
> OPTIONS / HTTP/1.1
> Host: my-service
> User-Agent: curl/7.61.0
> Accept: */*
> Origin: foo.com
> 
< HTTP/1.1 405 Method Not Allowed
< content-type: application/json; charset=UTF-8
< date: Tue, 30 Oct 2018 20:30:41 GMT
< content-length: 32
< x-envoy-upstream-service-time: 3
< server: my-service
< 
* Connection #0 to host my-service left intact
{"message":"Method Not Allowed"}
```
In this case `my-service` is a K8s service listening on 443 and sending to Envoy's ingress listener, which has only one virtual_host defined with the CORS policy listed above. Any ideas as to what I might be missing here?

**Comment by mattklein123** [comment]
@codesuki @dschaller

**Comment by codesuki** [comment]
Did you add the CORS filter to the `http_filters` list?
Similar to this.
```
listeners:
  filter_chains:
    http_filters:
      - name: envoy.cors
```

**Comment by dschaller** [comment]
It appears you're missing the `Access-Control-Request-Method` header in your options request

**Comment by codesuki** [comment]
Good catch!

**Comment by arianmotamedi** [comment]
Unfortunately still not working even with the `Access-Control-Request-Method` in the request header. Here's my full listener config (converted to yaml for readability):


```
static_resources:
  listeners:
  - address:
      socket_address:
        address: '0.0.0.0'
        port_value: 12345
    name: ingress
    filter_chains:
      filters:
      - config:
          route_config:
            virtual_hosts:
            - routes:
              - route:
                  cluster: my-service
                  timeout: 60s
                match:
                  prefix: /
              require_tls: ALL
              name: local_service
              cors:
                allow_origin:
                - my-domain.com
                allow_methods: GET, POST, PUT, HEAD, OPTIONS
                allow_headers: Authorization,Content-Type,correlationid
              domains:
              - '*'
            name: local_route
          server_name: my-service
          stat_prefix: ingress_http
          http_filters:
          - name: envoy.cors
          - name: envoy.router
          codec_type: AUTO
        name: envoy.http_connection_manager
```
I'm referencing `envoy.cors` as part of `http_filters` in `envoy.http_connection_manager`. Does it need to be defined elsewhere?
