### ISSUE TITLE
Return grpc status on direct response

### ISSUE THREAD

**Issue by kindermoumoute** [envoyproxy/envoy#4989]
**Return grpc status on direct response**

*Description*:
Currently, if I want to return a direct response on grpc requests I'll do something like that:
```yaml
virtual_hosts:
  - name: plop
    domains: ["*"]
    routes:
      - match:
          prefix: "/"
          grpc: {}
        direct_response:
          status: 501
          body:
            inline_string: "grpc method not implemented"
```

However I can only attach an HTTP status to this direct response. By default grpc status will be `unknown`.

**Solution 1**: match grpc statuses with a [wide range of http status](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto#L163).

**Solution 2**: add a field `grpc_status` in the config:
```yaml
virtual_hosts:
  - name: plop
    domains: ["*"]
    routes:
      - match:
          prefix: "/"
          grpc: {}
        direct_response:
          grpc_status: 12
```
