### ISSUE TITLE
/clusters and /clusters?format=json don't match

### ISSUE THREAD

**Issue by yannlandry** [envoyproxy/envoy#5029]
*`/clusters` and `/clusters?format=json` don't match*

**Description:**
When querying the `/clusters` endpoint of my envoy instance I'm able to retrieve the `load_balancing_weight` value (named `weight`) that I specified in my endpoint configuration. However, when querying the same endpoint but requesting the JSON format I cannot retrieve the value. There are quite a few more metrics missing at the cluster-wide level; for example, outlier detection metrics, priority information and locality information.

**Repro steps:**
Try to query `/clusters` and you should find a `weight` value for every endpoint (default=1). Query `/clusters?format=json` and there's no weight value associated with any endpoint.

**Clusters output:**
`/clusters` default format for a random cluster/endpoint:
```
some_service2.main.cluster::outlier::success_rate_average::-1
some_service2.main.cluster::outlier::success_rate_ejection_threshold::-1
some_service2.main.cluster::default_priority::max_connections::1024
some_service2.main.cluster::default_priority::max_pending_requests::1024
some_service2.main.cluster::default_priority::max_requests::1024
some_service2.main.cluster::default_priority::max_retries::3
some_service2.main.cluster::high_priority::max_connections::1024
some_service2.main.cluster::high_priority::max_pending_requests::1024
some_service2.main.cluster::high_priority::max_requests::1024
some_service2.main.cluster::high_priority::max_retries::3
some_service2.main.cluster::added_via_api::true
some_service2.main.cluster::172.17.0.4:80::cx_active::0
some_service2.main.cluster::172.17.0.4:80::cx_connect_fail::0
some_service2.main.cluster::172.17.0.4:80::cx_total::0
some_service2.main.cluster::172.17.0.4:80::rq_active::0
some_service2.main.cluster::172.17.0.4:80::rq_error::0
some_service2.main.cluster::172.17.0.4:80::rq_success::0
some_service2.main.cluster::172.17.0.4:80::rq_timeout::0
some_service2.main.cluster::172.17.0.4:80::rq_total::0
some_service2.main.cluster::172.17.0.4:80::health_flags::healthy
some_service2.main.cluster::172.17.0.4:80::weight::1
some_service2.main.cluster::172.17.0.4:80::region::
some_service2.main.cluster::172.17.0.4:80::zone::
some_service2.main.cluster::172.17.0.4:80::sub_zone::
some_service2.main.cluster::172.17.0.4:80::canary::false
some_service2.main.cluster::172.17.0.4:80::success_rate::-1
```

`clusters?format=json` for the same endpoint:
```
{
    "name": "some_service2.main.cluster",
    "added_via_api": true,
    "host_statuses": [{
        "address": {
            "socket_address": {
                "address": "172.17.0.4",
                "port_value": 80
            }
        },
        "stats": [{
            "name": "cx_connect_fail"
        }, {
            "name": "cx_total"
        }, {
            "name": "rq_error"
        }, {
            "name": "rq_success"
        }, {
            "name": "rq_timeout"
        }, {
            "name": "rq_total"
        }, {
            "type": "GAUGE",
            "name": "cx_active"
        }, {
            "type": "GAUGE",
            "name": "rq_active"
        }],
        "health_status": {
            "eds_health_status": "HEALTHY"
        }
    }]
}
```

**Config:**
File `some_service2.main.yaml`:
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: some_service2.main.cluster
  endpoints:
  - priority: 0
    lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 172.17.0.4
            port_value: 80
      load_balancing_weight: 1
  - priority: 1
    lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 172.17.0.4
            port_value: 80
      load_balancing_weight: 1
  - priority: 2
    lb_endpoints:
    - endpoint:
        address:
          socket_address:
            address: 172.17.0.4
            port_value: 80
      load_balancing_weight: 1
  - priority: 3
    lb_endpoints:
```
