### ISSUE TITLE
overprovisioning_factor ignored

### ISSUE THREAD

**Issue by billybanfield** [envoyproxy/envoy#5089]
*Title*: *overprovisioning_factor ignored*

*Description*:
We seem to be observing the following behavior:
The control plane is sending an overprovisioning_factor for each cluster_load_assignment of 10000. This is being acknowledged by envoy and displayed in the debug logs. Additionally, we are setting priority, with one locality at priority 0, and all other localities at priority 1. Our expectation is that Envoy would route all traffic to the priority 0 locality until it had no healthy endpoints left. However, we are observing Envoy routing traffic to the other localities while there are still healthy endpoints in the priority 0 locality. 

*Repro steps*:
* Start an Envoy instance
* Start 10-20 dummy services.
* Start control-plane
* Divide the services into 3 localities and return cluster load assignments for each, marking two as priority 1, and one as priority 0, and configure the overprovisioning_factor to 10000.
* Mark 2 services from the priority 0 locality as unhealthy.
* Send traffic to the cluster through envoy. 

Attached are the relevant files/logs snippets/endpoint output.
[cluster_load_log.txt](https://github.com/envoyproxy/envoy/files/2597260/cluster_load_log.txt)
[clusters.txt](https://github.com/envoyproxy/envoy/files/2597261/clusters.txt)
[request_logs.txt](https://github.com/envoyproxy/envoy/files/2597263/request_logs.txt)
[server_info.txt](https://github.com/envoyproxy/envoy/files/2597264/server_info.txt)
[stats.txt](https://github.com/envoyproxy/envoy/files/2597266/stats.txt)
[envoy-config.txt](https://github.com/envoyproxy/envoy/files/2597280/envoy-config.txt)

**Comment by snowp** [comment]
Confirming this as a bug, using this config:

```
static_resources:
  clusters:
  - name: c
    connect_timeout: 1s
    load_assignment:
      cluster_name: c
      endpoints:
        locality: { zone: z }
        lb_endpoints:
        - endpoint:
            address:
              socket_address: { address: 127.0.0.1, port_value: 5005 }
      policy:
        overprovisioning_factor: 10000
```

and modifying the /clusters endpoint to read the over provisioning factor from the host_set that contains the host:

```
➜  envoy git:(master) ✗ curl localhost:9901/clusters -s|grep over
c::127.0.0.1:5005::overprovision_factor::140
```
