### ISSUE TITLE
Envoy reports https traces to jaeger 

### ISSUE THREAD

**Issue by clyang82** [envoyproxy/envoy#5190]
Hello Guys,

is it possible to report https request by envoy? if so, could you please point me an example or some sample configurations? Thanks.

**Comment by junr03** [comment]
related jaeger setup issues: https://github.com/envoyproxy/envoy/issues/4963 https://github.com/envoyproxy/envoy/issues/5163. You will be able to find additional info, and people involved in Jaeger tracing there.

**Comment by clyang82** [comment]
@junr03 Thanks for your response. I have a https enabled nginx service with envoy injected. When I curl this service, the output is 
```
curl -kv https://10.0.105.14
* Rebuilt URL to: https://10.0.105.14/
*   Trying 10.0.105.14...
* Connected to 10.0.105.14 (10.0.105.14) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 692 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: An unexpected TLS packet was received.
* Closing connection 0
curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.
```

I have enabled envoy debug mode, there is an error thrown:
`[2018-12-04 13:31:12.560][35][debug][http] external/envoy/source/common/http/conn_manager_impl.cc:233] [C1] dispatch error: http/1.1 protocol error: HPE_INVALID_METHOD`

I guess the problem is have not find the correct certificate and key. Does it help if I apply the configures for envoy? Thanks
```
tls_context:
    common_tls_context:
      tls_certificates:
      - certificate_chain: { filename: "example_com_cert.pem" }
        private_key: { filename: "example_com_key.pem" }
```
