### ISSUE TITLE
upstream circuit breakers with strict_dns

### ISSUE THREAD

**Issue by mangareader** [envoyproxy/envoy#5206]
*Title*: *upstream circuit breakers with strict_dns*

*Description*:
I use service discovery (strict_dns) and define max_connections, but it doesn't work correct.
When set max_connections=5, i expected each host in cluster (35 hosts) will have max conn 10, and have 350 concurrent request before have pending request.
But when run, connection each host (rq_active) is very low & pending request is very high. And when set max conn 1024, everything normally.

![Image of Yaktocat](https://i.imgur.com/gq8yQ5T.jpg)

*Envoy version: 1.8.0*

*config*:
```yaml
static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 80
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: web
                      timeout: 50s
              http_filters:
              - name: envoy.router
                config: {}
      clusters:
      - name: web
        connect_timeout: 2s
        type: strict_dns
        lb_policy: ROUND_ROBIN
        circuit_breakers:
          thresholds:
            - priority: DEFAULT
              max_connections: 10
              max_requests: 10
            - priority: HIGH
              max_connections: 10
              max_requests: 10
        health_checks:
        - timeout: 2s
          interval: 2s
          unhealthy_threshold: 3
          healthy_threshold: 3
          http_health_check:
            path: "/status"
        hosts:
        - socket_address:
            address: web
            port_value: 5100
```
