### ISSUE TITLE
Service_name of datadog sets cluster name to default value

### ISSUE THREAD

**Issue by nakabonne** [envoyproxy/envoy#5208]
*Title*: *service_name of datadog sets cluster name to default value*

*Description*:
#### proposal
Currently, service_name of [config.trace.v2.DatadogConfig](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/trace/v2/trace.proto#config-trace-v2-datadogconfig) is required.
However, I think that it's better to set cluster of [core.Node](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-node) to the default value and service_name of DatadogConfig should be optional.

#### Why we need a default

If the default value is not set for service_name, we have to prepare config file for all services.
I manage the configuration file by node type for multiple services (e.g. sidecar, gateway, front-proxy).
In the case of such a use case, I think that similar descriptions will be repeated. I think it's not very good.

```yaml
tracing:
  http:
    name: envoy.tracers.datadog
    config:
      collector_cluster: datadog
      service_name: app1 # need to be optional
```
