### ISSUE TITLE
Does envoy.ext_authz support cookies?

### ISSUE THREAD

**Issue by bbigras** [envoyproxy/envoy#5213]
**Issue Template**

*Title*: *Envoy doesn't seem to send the cookie after auth*

*Description*:
> I know I can use `allowed_authorization_headers` and `allowed_request_headers` to allow headers going to a service to auth with envoy.ext_authz but "set-cookie" doesn't seem to be passed back to the client after a successful login.

```yaml
          http_filters:
          - name: envoy.ext_authz
            config:
              http_service:
                  server_uri:
                    uri: hostname:8080
                    cluster: ext-authz
                    timeout: 0.25s
                  path_prefix: "/auth"
                  allowed_authorization_headers: ["www-authenticate", "set-cookie"]
                  allowed_request_headers: [ "authorization", "cookie" ]
```
