### ISSUE TITLE
Headers stripped out on redirect

### ISSUE THREAD

**Issue by Fadelis** [envoyproxy/envoy#5343]
*Title*: *Headers stripped out on redirect*

*Description*:
> When using route with redirect any custom headers inserted are not passed to end host. I've tried to research this, but did not find anything concrete. Maybe I'm missing come configuration or this behavior is intended.

This is my sample config to replicate the issue:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9090

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8080
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          redirect:
                            host_redirect: headers.jsontest.com
                http_filters:
                  - name: envoy.lua
                    config:
                      inline_code: |
                        function envoy_on_request(request_handle)
                          request_handle:headers():add("apikey", "my-key")
                        end
                  - name: envoy.router
```
