### ISSUE TITLE
Support for optional client SSL auth info use in FilterChainMatch

### ISSUE THREAD

**Issue by redbaron** [envoyproxy/envoy#5445]
*Title*: *Routing based on client SSL cert info*

*Description*:
Envoy misses feature where routing decision can be made on information stored in client's SSL cert and it's validity. 

*Relevant Links*
Nginx's `$ssl_client_verify` and `$ssl_client_*` params: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#var_ssl_client_verify

**Comment by PiotrSikora** [comment]
@redbaron which fields are you interested in, exactly?

You can somehow awkwardly make routing decisions based on the client certificate at the HTTP level by forwarding client certificate details and checking values in the `x-forwarded-client-cert` header, e.g. to forward requests only from clients with valid certificate matching `spiffe://your.org/*`, you could use config like this:
```
static_resources:
  listeners:
  - address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - tls_context:
        require_client_certificate: true
        common_tls_context:
          validation_context:
            trusted_ca: { filename: "/path/to/ca_cert.pem" }
          tls_certificates:
            - certificate_chain: { filename: "/path/to/server_cert.pem" }
              private_key: { filename: "/path/to/server_key.pem" }
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          forward_client_cert_details: SANITIZE_SET
          set_current_client_cert_details: { uri: true }
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  headers:
                  - name: "x-forwarded-client-cert"
                     regex_match: ".*;URI=spiffe://your.org/.+"
                route:
                  cluster: local_cluster
          http_filters:
          - name: envoy.router
```

As for matching at the filter chain level, as @ggreenway mentioned, filter chain selection happens very early on, and at that point we don't even know which TLS context to use or if TLS is going to be terminated at the proxy, so matching based on client certificates isn't possible with the current architecture... I'd be interested in hearing why you need this to be matched at the filter chain level, though. What's your exact use case?
