### ISSUE TITLE
Can't redirect to https on the same port

### ISSUE THREAD

**Issue by vovata** [envoyproxy/envoy#5514]
The action https_redirect works for redirecting http port 80 to https port 443, or http port X1 to https port X2, and no way to use same listener on same port for redirecting.

On defined listener to accept and route https request it is tried to add redirection from http schema to https on the same port. But the listener doesn't accept the requests on http when there is tls context defined. In the same time there is no way to define 2 listeners on same port, one for http with https_redirect action, and one for the secure request.

How it is possible to use https_redirect on same port in the same listener?
The goal is, if there is a url https://server:12345 which accepts secure requests, then if a request to http://server:12345 is sent, the proxy to redirect it to https://server:12345.

Thanks

**Comment by vovata** [comment]
I have secure listener, and it works on https url on specific port.
But I want if someone requested same url with same port, just to redirect the request to https.
Nothing special in my wish, just do not reject the request if the url and the port are correct, but sent as http.

**Comment by dnoe** [comment]
In that scenario you can't redirect, because the http:// URL to the port
that is expecting HTTPS will not be able to do the basic protocol
communication that is needed to do a redirect. This isn't a limitation of
Envoy, but of HTTP in general.

**Comment by lizan** [comment]
It is actually possible with Envoy with TLS inspector, you can setup two filter chains on same listener (same port), one with TLS and one with plaintext. And setup http connection manager in the plaintext one to redirect to HTTPS.

**Comment by vovata** [comment]
Thanks a lot Lizan, your solution works well.

**Comment by prateek33** [comment]
@vovata can you please share the config on how you achieved this? Thanks

**Comment by vovata** [comment]
@prateek33 check this sample:
`  - name: listener_x
    address:
      socket_address: { address: "::", ipv4_compat: true, port_value: 443 }
    listener_filters:
    - name: envoy.listener.tls_inspector
      config: {}
    filter_chains:
    - filter_chain_match:
        transport_protocol: raw_buffer
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_redirect
            virtual_hosts:
            - name: local_http
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                redirect: { https_redirect: true }
          http_filters:
          - name: envoy.router
            config: {}
    - filter_chain_match:
        transport_protocol: tls
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_path
              domains: ["*"]
              routes:
              - match: { path: "/" }
                redirect: { path_redirect: "/welcome.html"}
          http_filters:
          - name: envoy.router
            config: {}`

**Comment by vit-zikmund** [comment]
Hi everyone, here's the significant part for the above modified for envoy ~v1.30 (which requires explicit config types):
```yaml
listener_filters:
  name: envoy.filters.listener.tls_inspector
  typed_config:
    "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
filter_chains:
- filter_chain_match:
    transport_protocol: raw_buffer
  filters:
  - name: envoy.filters.network.http_connection_manager
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
      stat_prefix: ingress_http
      http_filters:
      - name: envoy.filters.http.router
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      route_config:
        name: local_redirect
        virtual_hosts:
        - name: local_http
          domains: ["*"]
          routes:
          - match: { prefix: "/" }
            redirect: { https_redirect: true }
```
