### ISSUE TITLE
Confusing 503 when connection is closed

### ISSUE THREAD

**Issue by rvansa** [envoyproxy/envoy#5594]
*Title*: *Confusing 503 when connection is closed*

*Description*:
When we send a request (over HTTP1.1) to envoy configured as HTTP proxy and subsequently close this connection from the client side (send FIN packet), the client receives response with status code 503, and message "upstream connect error or disconnect/reset before headers" before the FIN response. I find this rather confusing, since the termination has nothing to do with upstream.

(I think I also saw x-envoy-overloaded headers in such requests, together with the message above, but I can't find them in my last tcpdump).

Using envoy 1.10.0-dev built from sources.

*Config*:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: {{ proxy_port }}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: ""
                route:
                  cluster: backend
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: backend
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: {{ backend_host }}
        port_value: {{ backend_port }}
    circuit_breakers: # effectively disable circuit breaking
      thresholds:
        max_pending_requests: 100000
        max_requests: 100000
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: {{ proxy_admin_host }}
      port_value: {{ proxy_admin_port }}
```
