### ISSUE TITLE
Initialize with static config only when management server is not responding

### ISSUE THREAD

**Issue by MarcinFalkowski** [envoyproxy/envoy#5622]
*Title*: *Initialise Envoy with static config only, when management server is not responding*

*Description*:
In our envoy config we have static listeners, several static clusters and some dynamic resources fetched from management server (by RDS, CDS and EDS).

Our static config is sufficient to handle our "minimal" viable scenario, so we want to be able to initialise Envoy successfully, even if the management server is down.

One of the static listeners doesn't use dynamic resources at all (only static route config and static clusters). However, when the management server is not responding, even that listener doesn't work (returns empty reply for all requests) 

When the management server is down Envoy is stuck at `PRE_INITIALIZING` state and we have in application log:

```
[2019-01-16 16:38:02.009][000025][info][config] [source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2019-01-16 16:38:02.009][000025][info][config] [source/server/configuration_impl.cc:56] loading 2 cluster(s)
[2019-01-16 16:38:02.014][000025][info][config] [source/server/configuration_impl.cc:67] loading 2 listener(s)
[2019-01-16 16:38:02.017][000025][info][config] [source/server/configuration_impl.cc:92] loading tracing configuration
[2019-01-16 16:38:02.017][000025][info][config] [source/server/configuration_impl.cc:112] loading stats sink configuration
[2019-01-16 16:38:02.017][000025][info][main] [source/server/server.cc:463] starting main dispatch loop
[2019-01-16 16:38:02.019][000025][info][upstream] [source/common/upstream/cluster_manager_impl.cc:132] cm init: initializing cds
[2019-01-16 16:38:03.015][000025][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
[2019-01-16 16:38:04.101][000025][warning][upstream] [source/common/config/grpc_mux_impl.cc:268] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers
<the last line is repeated infinitely>
```

Is there any way to make management server optional, and successfully initialise Envoy when management server is not responding?

**Comment by mattklein123** [comment]
If the management server doesn't respond, assuming timeouts, etc., Envoy should not get stuck, and should actually complete initialization even if the target resources are not available. It's possible there is a bug here, so this would probably require more in-depth debugging.

**Comment by MarcinFalkowski** [comment]
@mattklein123 Thanks for your reply! 
I extracted minimal complete config where this problem can be observed. Maybe something is configured wrong? 

To reproduce the problem, run envoy with that config. Go to port 7000 (full_static_listener). It should proxy you to 127.0.0.1:8080 ("static_service" cluster - make sure something is listening here). 
But when the management server is down ("xds" cluster), that listener will not proxy you to "static_service".
In envoy admin you will see PRE_INITIALIZING state.

Tested with envoy v1.9.0 and the latest snapshot (docker dc7632d216b25e9acf039f0ef3fb77a281193123) with the same results.

@mattklein123 You said that this is not intended behaviour of Envoy, so I see two possibilities here:
* this is a real bug
* my config is flawed

 I will greatly appreciate if someone can confirm which case it is.

```yaml
node:
  id: "node-1"
  cluster: "nodes"
static_resources:
  listeners:
  - name: full_static_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 7000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: full_static_http
          route_config:
            name: full_static_routes
            virtual_hosts:
            - name: route
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: "static_service"
          http_filters:
          - name: envoy.router
  clusters:
  - name: static_service
    type: STATIC
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8080
    connect_timeout:
      seconds: 1
  - name: xds
    type: static
    hosts:
    - socket_address:
        address: 10.55.131.99
        #address: 127.2.3.4  # no one listen on this address
        port_value: 50000
    connect_timeout:
      seconds: 1
    http2_protocol_options: {}

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
      - envoy_grpc:
          cluster_name: xds
        timeout:
          seconds: 5

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 6000
```
