### ISSUE TITLE
Multiple external auth filters per route

### ISSUE THREAD

**Issue by carlosmayer** [envoyproxy/envoy#5769]
*Title*: *Multiple external auth filters per route*

*Description*:
I would like to have more than one external auth filter associated with a route. Additionally, I would like to be able to enable/disable them on independently on a per-route basis.

Example:
Let's say I have two authentication services: AuthA and AuthB, that should allow or block a specific request.

And I have three routes:
1. /unauthenticated
2. /authenticated
3. /strongly-authenticated

I would like to apply none of the auth servers to route 1, just AuthA to route 2 and both of them (AuthA and AuthB) to route 3.

Does that make sense in general? And is that possible to do?

I tried locally and I was able to define more than 1 external authentication service. In theory I could define AuthA and Auth and disable them using the per_route configuration. The problem is that the per_route seems to disable both of them (since it applies to envoy.ext_authz and both AuthA and AuthB would be envoy.ext_authz).

**Comment by mattklein123** [comment]
@gsagula

**Comment by gsagula** [comment]
Sorry, I totally missed this one. @carlosmayer How did you define more than one authorization service?   Did you stack multiple `ext-authz` filters? I've never tried that, not sure if it's possible.

**Comment by carlosmayer** [comment]
@gsagula Thanks for getting to it. 

Yes, exactly, I just stacked two of them and it seems to work. But the issue is that I would like to apply each filter independently to different routes and that does not seem to be possible. 

Do you see any way (or workaround) to achieve that?

**Comment by itroot** [comment]
@carlosmayer Did you succeed in this effort?

**Comment by yubofredwang** [comment]
@gsagula Hi is there a fix for this? we have two external_authz service, we want to disable one of them for specific routes. From this post seems that it is not achievable? Is there any workaround or plan to fix for this issue?

**Comment by jkendzorra** [comment]
@gsagula @mattklein123 is there a way of selectively disabling a particular instance of ext_authz in a filter when multiple configurations have been stacked? @carlosmayer did you successfully spend further time on this?

**Comment by cheimu** [comment]
Is this problem solved? I got the same situation here...

**Comment by aaddati** [comment]
Hi @carlosmayer!!! I need the same functionality. Could you found a workaround?

**Comment by prince-melvin** [comment]
Hi,

We can make use of the filter_enabled_metadata field present in ext_authz filter which will enable/disable based on the criteria.
It checks for only dynamic_metadata, right now i am using lua filter to set the metadata

```
function envoy_on_request(request_handle)
                  request_handle:logInfo("setting dynamic metadata")
                  request_handle:streamInfo():dynamicMetadata():set("xyz.abc", "filter1",true);
                end
```

```
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              stat_prefix: waf
              transport_api_version: V3
              http_service:
                server_uri:
                  uri:  ${AUTH1_ENDPOINT}
                  cluster: auth1-service
                  timeout:  0.250s
              filter_enabled_metadata:
                filter: xyz.abc
                path:
                - key: filter1
                value:
                  bool_match: true
          - name: envoy.filters.http.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              stat_prefix: waf
              transport_api_version: V3
              http_service:
                server_uri:
                  uri:  ${AUTH2_ENDPOINT}
                  cluster: auth2-service
                  timeout:  0.250s
              filter_enabled_metadata:
                filter: xyz.abc
                path:
                - key: filter2
                value:
                  bool_match: true
```
