### ISSUE TITLE
Envoy "Connection: close" causes 1s rq_time overhead

### ISSUE THREAD

**Issue by fkowal** [envoyproxy/envoy#5788]
Given the below configuration:

Request with __Connection: close__, causes envoy to delays the sending the tcp (FIN) / closing the socket by 1s.

Envoy sends the response data, rightaway (no delay visible in tcpdump / wireshark), the FIN / closing of the connection is the issue.
```bash
time fortio curl -loglevel=debug -keepalive=false localhost:8080/
```

Request without 'Connection: close', works as expected
```bash
time fortio curl -loglevel=debug localhost:8080/
```

```yaml
---
node:
  locality:
    zone: default-zone

static_resources:
  listeners:
  - name: default_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_proxy
          access_log:
            name: envoy.file_access_log
            config:
              path: "/dev/stdout"
              format: >
                [%START_TIME%] %PROTOCOL% %REQ(:METHOD)% %REQ(:authority)% %REQ(:PATH)% %RESPONSE_CODE% %RESPONSE_FLAGS%
                %BYTES_RECEIVED%b %BYTES_SENT%b %DURATION%ms "%DOWNSTREAM_REMOTE_ADDRESS%" -> "%UPSTREAM_HOST%"
          route_config:
            name: "ingress_routes"
            virtual_hosts:
              - name: "local_service"
                domains:
                  - "*"
                routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: "example"
          http_filters:
            - name: envoy.router
          http_protocol_options:
            allow_absolute_url: true

  clusters:
  - name: example
    type: STRICT_DNS
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9091
    connect_timeout:
      seconds: 1

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9091
```

This looks similar to #234, we've noticed unhealthy instances in varnish, when probes had .timeout < 1s.
