### ISSUE TITLE
No x-request-id on direct response

### ISSUE THREAD

**Issue by kindermoumoute** [envoyproxy/envoy#5828]
*No x-request-id on direct response*

*Description*:
When doing a curl on a directResponse route, I do not see the x-request-id header.

*Repro steps*:

Envoy config:

```yaml
# envoy.yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - direct_response:
                  body:
                    inline_string: '{"message":"direct response"}'
                  status: 400
                match:
                  prefix: "/"
                response_headers_to_add:
                - append: false
                  header:
                    key: content-type
                    value: application/json
          http_filters:
          - name: envoy.router
```

Run Envoy:

```bash
$ docker run --rm -v $(pwd)/envoy.yaml:/etc/envoy/envoy.yaml -p 80:80 envoyproxy/envoy:latest
```

See the bug:

```bash
$ curl -v http://localhost
* Rebuilt URL to: http://localhost/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< content-length: 35
< location: http://localhost/
< content-type: application/json
< date: Mon, 04 Feb 2019 16:41:47 GMT
< server: envoy
<
* Connection #0 to host localhost left intact
{"message":"direct response"}%
```

*What I expected to see*:
- `< x-request-id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
