### ISSUE TITLE
Connection manager removes headers after Route.request_headers_to_add

### ISSUE THREAD

**Issue by kindermoumoute** [envoyproxy/envoy#5858]
**Use case**: need to cleanup a custom header from the request before adding it (or not) in routes.

**Envoy**: 1.9.0

**Config**:

```yaml
#envoy.yaml
#...
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 80 }
      filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            config:
              stat_prefix: ingress_http
              codec_type: AUTO
              route_config:
                name: local_route
                request_headers_to_remove: # this happens second
                  - x-custom-header
                virtual_hosts:
                  - name: local_service
                    domains: ["*"]
                    routes:
                      - match:
                          prefix: "/"
                        request_headers_to_add: # this happens first
                          - append: false
                            header:
                              key: x-custom-header
                              value: plip
                        route:
                          cluster: xxx
              http_filters:
                - name: envoy.router
#...
```

**What I see**: `request_headers_to_remove`  in connection manager happens after `request_headers_to_add` in route config.

**What I expected to see**: `request_headers_to_remove`  in connection manager happens before `request_headers_to_add` in route config.
