### ISSUE TITLE
Redis rate limit example

### ISSUE THREAD

**Issue by poyaz** [envoyproxy/envoy#5930]
*Title*: *Redis reatelimit sample*

*Description*:
1) How to use rate limit in redis and tcp network?
2) and how use below configuration?
```
rate_limit:
   unit: second
   requests_per_unit: 500
```

3) What is the best replacement for "xxxx", "yyyy"?

Config:
```
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

static_resources:
  listeners:
    - name: redis_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 6000
      filter_chains:
        - filters:
            - name: envoy.redis_proxy
              config:
                stat_prefix: egress_redis
                cluster: redis_cluster
                settings:
                  op_timeout: 5s

            - name: envoy.ratelimit
              config:
                stat_prefix: rate_redis
                domain: rate_per_ip
                descriptors:
                  entries:
                  - key: xxxx
                    value: yyyy

  clusters:
    - name: redis_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: proxy-redis1
            port_value: 6379
```
