### ISSUE TITLE
TCP proxy route by domain name

### ISSUE THREAD

**Issue by poyaz** [envoyproxy/envoy#5939]
*Description*:
I have two different PostgreSQL instance and i want route by domain name in port 5432 like below:

* if use `pg1.example.com` (for X application) got to cluster `pg1_cluster`
* if use `pg2.example.com` (For Y application) got to cluster `pg2_cluster`

and i don't know how to use filter or any other options in **tcp_proxy**

*Config*:
```yml
static_resources:
  listeners:
    - name: postgres_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 5432
#      filter_chains:
#        - filters:
#            - name: envoy.tcp_proxy
#              config:
#                stat_prefix: pg1
#                cluster: pg1_cluster

  clusters:
    - name: pg1_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: pg1_server   # 172.17.0.10
            port_value: 5432

   - name: pg2_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: pg2_server   # 172.17.0.11
            port_value: 5432
```

**Comment by junr03** [comment]
This is not a feature of the TCP proxy, nor can it be done with the filter chain match as at L4 there is no  knowledge of domain name. 

However, if you use the [http connection manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/http_conn_man) you can create L7 aware routing rules like you describe.

**Comment by chopmann** [comment]
If you use TLS you might get away with using the SNI to do that:

https://www.envoyproxy.io/docs/envoy/latest/configuration/listener_filters/tls_inspector

https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto#envoy-api-msg-listener-filterchainmatch

**Comment by poyaz** [comment]
Sorry, some of the parts for me not understandable.

 It's possible to take a sample configuration (how use filter)?

**Comment by chopmann** [comment]
Maybe something like this can help

```yaml
---
static_resources:
  listeners:
    - name: postgres_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 5432
      listener_filters:
        - name: "envoy.listener.tls_inspector"
          config: {}
      filter_chains:
        - filter_chain_match:
            transport_protocol: tls
            server_names:
              - pg1.example.com
          filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: pg1_cluster_stats
              cluster: pg1_cluster
          tls_context:
            common_tls_context:
                tls_certificates:
                - certificate_chain: { filename: "...." }
                  private_key: { filename: "..." }
        - filter_chain_match:
            transport_protocol: tls
            server_names:
              - pg2.example.com
          filters:
          - name: envoy.tcp_proxy
            config:
              stat_prefix: pg1_cluster_stats
              cluster: pg2_cluster
          tls_context:
            common_tls_context:
                tls_certificates:
                - certificate_chain: { filename: "...." }
                  private_key: { filename: "..." }

  clusters:
    - name: pg1_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: pg1_server   # 172.17.0.10
            port_value: 5432
    - name: pg2_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: pg2_server   # 172.17.0.11
            port_value: 5432

```

**Comment by poyaz** [comment]
sorry, but i can't connect with psql, how to connect with client modules to proxy?

create tls file:
```bash
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /my-patch/pg1.example.com/tls.key -out /my-patch/pg1.example.com/tls.cert-subj "/CN=pg1.example.com"

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /my-patch/pg2.example.com/tls.key -out /my-patch/pg2.example.com/tls.cert-subj "/CN=pg2.example.com"
```

psql connection:
```
psql "host=pg1.example.com user=postgres dbname=postgres sslmode=prefer"
```

```yml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

static_resources:
  listeners:
    - name: postgres_listner
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 5432
      listener_filters:
        - name: envoy.listener.tls_inspector
          config: {}
      filter_chains:
        - filter_chain_match:
            transport_protocol: tls
            server_names:
              - pg1.pooya.partdp.ir
          filters:
            - name: envoy.tcp_proxy
              config:
                stat_prefix: pg1_cluster_stats
                cluster: pg1_cluster
          tls_context:
            common_tls_context:
              tls_certificates:
                - certificate_chain: { filename: "/my-patch/pg1.example.com/tls.cert" }
                  private_key: { filename: "/my-patch/pg1.example.com/tls.key" }

#        - filter_chain_match:
#            transport_protocol: tls
#            server_names:
#              - pg2.pooya.partdp.ir
#          filters:
#            - name: envoy.tcp_proxy
#              config:
#                stat_prefix: pg2_cluster_stats
#                cluster: pg2_cluster
#          tls_context:
#            common_tls_context:
#              tls_certificates:
#                - certificate_chain: { filename: "/my-patch/pg2.example.com/tls.cert" }
#                  private_key: { filename: "/my-patch/pg2.example.com/tls.key" }

  clusters:
    - name: pg1_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: proxy-pg1
            port_value: 5432

    - name: pg2_cluster
      connect_timeout: 1s
      type: strict_dns
      lb_policy: MAGLEV
      hosts:
        - socket_address:
            address: proxy-pg2
            port_value: 5432
```
