### ISSUE TITLE
possible to suppress the access log by route ?

### ISSUE THREAD

**Issue by steveinatorx** [envoyproxy/envoy#5969]
unclear to me if its possible to suppress access logging in the /healthcheck_envoy route below 

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
          - name: envoy.file_access_log
            config:
              path: "/dev/stdout" 
          upgrade_configs:
          - upgrade_type: websocket
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: proxy_route
            virtual_hosts:
            - name: prokeep_dev
              domains: ["*"]
              routes:
              - match: { prefix: "/healthcheck-envoy" }
                direct_response: 
                  status: 200 
              - match: { prefix: "/" } 
                route: { cluster: cloudfront }
          http_filters:
          - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/ssl/fullchain.pem"
              private_key:
                filename: "/etc/ssl/privkey.pem"
 
  clusters:
  - name: cloudfront
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 10s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: XXX.cloudfront.net, port_value: 80 }}]
```

**Comment by junr03** [comment]
You could use the [header filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto.html?highlight=response%20flag#envoy-api-msg-config-filter-accesslog-v2-headerfilter) and use the path header to filter out based on the path header.

**Comment by yongzhang** [comment]
> You could use the [header filter](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto.html?highlight=response%20flag#envoy-api-msg-config-filter-accesslog-v2-headerfilter) and use the path header to filter out based on the path header.

I have the same question, is the filter used to `filter` or `filter OUT` log lines?

**Comment by amankumarcs** [comment]
hi, @yongzhang  can you provide a bit more info on how you solved it?

**Comment by yongzhang** [comment]
> hi, @yongzhang can you provide a bit more info on how you solved it? I want to use accesslog.v3.AccessLog

Here's the example:

```
                          access_log:
                          - name: envoy.access_loggers.stdout
                            filter:
                              header_filter:
                                header:
                                  name: ":path"
                                  string_match:
                                    exact: "/healthcheck"
                                  invert_match: true
                            typed_config:
                              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
```

**Comment by yongzhang** [comment]
> @yongzhang i'm getting ERROR can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog: unknown field "filter" in envoy.extensions.access_loggers.stream.v3.StdoutAccessLog

Can you paste your full config here?

**Comment by yongzhang** [comment]
> I'm adding access log filter inside envoyfilter
> 
> `apiVersion: networking.istio.io/v1alpha3 kind: EnvoyFilter metadata: annotations: meta. helm.sh/release-name: envoyfilter meta.helm.sh/release-namespace: namespace creationTimestamp: "2023-08-12T05:24:24Z" generation: 12 labels: app.kubernetes.io/managed-by: Helm name: ext-authz namespace: istio-system resourceVersion: "26544328" uid: 2915c605-7684-40a4-8a32-df002db40d1c spec: configPatches:
> 
> * applyTo: HTTP_FILTER
>   match:
>   context: GATEWAY
>   listener:
>   filterChain:
>   filter:
>   name: envoy.http_connection_manager
>   subFilter:
>   name: envoy.router
>   patch:
>   operation: INSERT_BEFORE
>   value:
>   name: envoy.access_loggers.stdout
>   typed_config:
>   '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
>   filter:
>   header_filter:
>   header:
>   invert_match: true
>   name: :path
>   string_match:
>   exact: /bundle/bundle.tar.gz`

Sorry I can't read your config without code block 😃 
From your error msg, it seems like you're missing indentations somewhere.

**Comment by amankumarcs** [comment]
> > I'm adding access log filter inside envoyfilter
> > `apiVersion: networking.istio.io/v1alpha3 kind: EnvoyFilter metadata: annotations: meta. helm.sh/release-name: envoyfilter meta.helm.sh/release-namespace: namespace creationTimestamp: "2023-08-12T05:24:24Z" generation: 12 labels: app.kubernetes.io/managed-by: Helm name: ext-authz namespace: istio-system resourceVersion: "26544328" uid: 2915c605-7684-40a4-8a32-df002db40d1c spec: configPatches:
> > 
> > * applyTo: HTTP_FILTER
> >   match:
> >   context: GATEWAY
> >   listener:
> >   filterChain:
> >   filter:
> >   name: envoy.http_connection_manager
> >   subFilter:
> >   name: envoy.router
> >   patch:
> >   operation: INSERT_BEFORE
> >   value:
> >   name: envoy.access_loggers.stdout
> >   typed_config:
> >   '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
> >   filter:
> >   header_filter:
> >   header:
> >   invert_match: true
> >   name: :path
> >   string_match:
> >   exact: /bundle/bundle.tar.gz`
> 
> Sorry I can't read your config without code block smiley From your error msg, it seems like you're missing indentations somewhere.

please check above code block i have fixed thanks

**Comment by yongzhang** [comment]
> name: envoy.access_loggers.stdout
>         typed_config:
>           '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
>           filter:
>             header_filter:
>               header:
>                 invert_match: true
>                 name: :path
>                 string_match:
>                   exact: /bundle/bundle.tar.gz

ok so this issue should be obvious, `filter` is not a field of `typed_config`, you should change it like this:

```
        name: envoy.access_loggers.stdout
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
        filter:
          header_filter:
            header:
              invert_match: true
              name: :path
              string_match:
                exact: /bundle/bundle.tar.gz
```
