### ISSUE TITLE
Issues with RBAC + non http protocols

### ISSUE THREAD

**Issue by rshriram** [envoyproxy/envoy#6030]
It is possible to use the RBAC filter with non HTTP protocols for things like restricting the set of operations allowed on a database. For example, the following works with mysql:

```yaml
 - filters:
      - name: envoy.filters.network.mysql_proxy
        config:
          stat_prefix: mysql
      - name: envoy.filters.network.rbac
        config:
          stat_prefix: rbac
          rules:
            action: DENY
            policies:
              "product-viewer":
                permissions:
                - metadata:
                    filter: envoy.filters.network.mysql_proxy
                    path:
                    - key: table1.testdb
                    value:
                      list_match:
                        one_of:
                          string_match:
                            exact: update
                principals:
                - any: true
```

where queries like `update testdb.table1 set foo='random'` will be blocked..

But the following filter format (with the intent of allowing only select queries) will break even the basic mysql connectivity (client can't even establish a session)

```yaml
 - filters:
      - name: envoy.filters.network.mysql_proxy
        config:
          stat_prefix: mysql
      - name: envoy.filters.network.rbac
        config:
          stat_prefix: rbac
          rules:
            action: ALLOW
            policies:
              "product-viewer":
                permissions:
                - metadata:
                    filter: envoy.filters.network.mysql_proxy
                    path:
                    - key: table1.testdb
                    value:
                      list_match:
                        one_of:
                          string_match:
                            exact: select
                principals:
                - any: true
```

It breaks because protocol codecs like mysql/mongo/redis/kafka/zookeeper have a whole bunch of standard *protocol-chatter* like establishing sessions, etc.. before they get to the actual operations (create stuff/read stuff/update/delete/publish/etc.). While the set of operations are a handful, there is an arbitrary amount of protocol chatter involved.

A simple ALLOW rule, being a white list, cannot capture all forms of the protocol chatter. Yet, from a UX point of view, the end user specifies only the operations she wants to allow, while implicitly assuming that the protocol chatter is always allowed.

The right solution is to create some universally known constant for protocol chatter and tag all non-operation events across all codecs (mongo/mysql/redis for the moment, kafka/zookeeper to follow) as protocol-chatter.
When setting up RBAC filter for such codecs, we could create a universal fallthrough rule, like this:

```yaml
 - filters:
      - name: envoy.filters.network.mysql_proxy
        config:
          stat_prefix: mysql
      - name: envoy.filters.network.rbac
        config:
          stat_prefix: rbac
          rules:
            action: ALLOW
            policies:
              "product-viewer":
                permissions:
                - metadata:
                    filter: envoy.filters.network.mysql_proxy
                    path:
                    - key: table1.testdb
                    value:
                      list_match:
                        one_of:
                          string_match:
                            exact: select
                principals:
                - any: true
              "fallthrough":
                permissions:
                - metadata:
                    filter: envoy.filters.network.mysql_proxy
                    path:
                    - key: __protocolchatter__
                    value:
                        null_match: 
                principals:
                - any: true
```

the above config would allow normal login/session authentication/etc. commands to proceed while allowing only select operation on testdb.table1 .

cc @yangminzhu and co
