### ISSUE TITLE
tap: generic body matching

### ISSUE THREAD

**Issue by mattklein123** [envoyproxy/envoy#6107]
Add generic text body matchers that perform matches up to some buffer limit.

**Comment by cpakulski** [comment]
@mattklein123 Since there are no assumptions about the body's structure, I think that only matchers would be:
- contains _token_
- does not contain _token_
where the _token_ is string or regex.

Should the matching process kick in only when content-Type is text/plain, or leave it to a user to configure two matchers?

```
and_match:
  rules:
    - http_request_headers_match:
              headers:
               - name: content-type
                  exact_match: plain/text
    - generic_body_match:
             contains: envoy

```
