### ISSUE TITLE
envoy.grpc_http1_reverse_bridge http_filter config error

### ISSUE THREAD

**Issue by sp-manuel-jurado** [envoyproxy/envoy#6154]
**envoy.grpc_http1_reverse_bridge http_filter config error**

*Title*: *error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for name: 'envoy.grpc_http1_reverse_bridge'*

*Description*:
I'm trying to configure gRPC HTTP/1.1 reverse bridge http filter but I get the next error trying to run the docker container:

`error initializing configuration '/etc/envoy/envoy.yaml': Didn't find a registered implementation for name: 'envoy.grpc_http1_reverse_bridge'`.

I'm doing something wrong?
Thx in advance.

Context:

Envoy version:
```
envoy --version
envoy  version: 98e323460b081324c2b6436220e2f92fb7c87075/1.10.0-dev/Clean/RELEASE/BoringSSL
```
envoy.yaml config:

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite: nginx
                            cluster: nginx
                http_filters:
                  - name: envoy.grpc_http1_reverse_bridge
                    typed_config: {}
                  - name: envoy.router
                    typed_config: {}
  clusters:
    - name: nginx
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: nginx
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: nginx
                      port_value: 80

```

docker-compose file:

```
version: '3'

services:
  envoy_gateway:
    image: envoyproxy/envoy:latest
    depends_on:
      - nginx
    ports:
      - "9901:9901"
      - "10000:10000"
    volumes:
      - ./docker/envoy/envoy.yaml:/etc/envoy/envoy.yaml

...

```

*Relevant Links*:
>[Documentation info](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_http1_reverse_bridge_filter#grpc-http-1-1-reverse-bridge).

**Comment by mattklein123** [comment]
@snowp

**Comment by moderation** [comment]
@sp-manuel-jurado Having done a lot of testing for https://github.com/envoyproxy/envoy/pull/6025 I'm pretty sure you are trying to use `grpc_http1_reverse_bridge` filter on a build of Envoy that has not included that extension. It's likely the build of Envoy had the following line commented out - https://github.com/envoyproxy/envoy/blob/master/source/extensions/extensions_build_config.bzl#L34

When Envoy starts it will output what extensions it is built with. Here is the line that would include `grpc_http1_reverse_bridge` if Envoy was built with that extension

```
[2019-03-02 14:07:01.724][21017][info][main] [source/server/server.cc:215]   filters.network: envoy.filters.network.rbac,envoy.http_connection_manager,envoy.ratelimit,envoy.tcp_proxy
```

**Comment by snowp** [comment]
I think the issue is that the real name of the filter is `envoy.filters.http.grpc_http1_reverse_bridge`, the documentation in `docs/root/configuration/http_filters/grpc_http1_reverse_bridge_filter.rst` seems to be wrong. If someone wants to PR a doc fix that would be great, otherwise I'll get to it next week

**Comment by moderation** [comment]
@snowp is right - confirmed at https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/well_known_names.h#L30. But the naming is inconsistent as noted on line 11 https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/well_known_names.h#L11

**Comment by sp-manuel-jurado** [comment]
Hi @moderation and @snowp 

I tested envoy proxy changing the name of the filter by `envoy.filters.http.grpc_http1_reverse_bridge` using the latest docker image in docker hub (latest, 741df7aa13ddb15acbc77468579f0c6b58542839) and I can see that:

- filter `envoy.filters.http.grpc_http1_reverse_bridge` is registered ok
```
envoy_gateway_1  | [2019-03-03 20:19:04.633][1][info][main] [source/server/server.cc:209]   filters.http: envoy.buffer,envoy.cors,envoy.ext_authz,envoy.fault,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
```

- but a different error `FilterConfigValidationError.ContentType` is thrown Proto constraint validation failed:
```
envoy_gateway_1  | [2019-03-03 20:19:04.642][1][critical][main] [source/server/server.cc:87] error initializing configuration '/etc/envoy/envoy.yaml': Proto constraint validation failed (FilterConfigValidationError.ContentType: ["value length must be at least " '\x01' " bytes"]): 
envoy_gateway_1  | [2019-03-03 20:19:04.643][1][info][main] [source/server/server.cc:516] exiting
envoy_gateway_1  | Proto constraint validation failed (FilterConfigValidationError.ContentType: ["value length must be at least " '\x01' " bytes"]): 
```

**Comment by snowp** [comment]
@sp-manuel-jurado You need to specify a `content_type` value for the filter to know what content-type to expect from the upstream

**Comment by sp-manuel-jurado** [comment]
@snowp It works adding content_type
thx so much for the support

I attach the configuration used:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            host_rewrite: nginx
                            cluster: nginx
                http_filters:
                  - name: envoy.filters.http.grpc_http1_reverse_bridge
                    config:
                      content_type: application/x-proto
                      withhold_grpc_frames: true
                  - name: envoy.router
  clusters:
    - name: nginx
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: nginx
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: nginx
                      port_value: 80
```
