### ISSUE TITLE
Example of logging metadata set by a route?

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#6156]
In the envoy docs for [core.Metadata](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-metadata), it says:

> An example use of metadata is providing additional values to http_connection_manager in the envoy.http_connection_manager.access_log namespace.

I've tried to set metadata on a route with this namespace with the intention of it being logged by the parent listener, to no avail.

Here are the relevant snippets of my config:

RouteConfiguration:

```
version_info: '0'
resources:
  - '@type': type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: foobar-route-config
    virtual_hosts:
      - name: foobar-virtualhost
        domains:
          - 'foobar.com'
        routes:
        - match:
            prefix: /
          route:
            cluster: foobar-cluster
          metadata:
            filter_metadata:
              envoy.http_connection_manager.access_log:
                example: 'something'
```

Listener:

```
version_info: '0'
resources:
  - '@type': type.googleapis.com/envoy.api.v2.Listener
    name: foobar-listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
        protocol: TCP
    filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            stat_prefix: upstreams
            codec_type: AUTO
            idle_timeout: 300s
            use_remote_address: yes
            access_log:
              - name: envoy.file_access_log
                config:
                  path: /var/log/envoy/access.log
                  json_format:
                    my_metadata_value: "%DYNAMIC_METADATA(envoy.http_connection_manager.access_log:example)%"
              - name: envoy.router
            rds:
              route_config_name: foobar-route-config
              config_source:
                api_config_source:
                  api_type: REST
                  cluster_names: [controlplane]
                  refresh_delay: 5s
```

These are responses sent by an envoy control-plane.

Am I doing this wrong? The value is logged as `'-'`.

**Comment by dio** [comment]
I think the metadata that will be logged by the access logger is not that route entry metadata, but the [streamInfo.metadata()](https://github.com/envoyproxy/envoy/blob/8052ec65c49e8bb52b373b6c19a9e170672892ab/source/common/access_log/access_log_formatter.cc#L471). In order to set that (dynamic) metadata you have two options:

1. Dynamic Metadata can be set by filters using the StreamInfo API: [setDynamicMetadata](https://github.com/envoyproxy/envoy/blob/8052ec65c49e8bb52b373b6c19a9e170672892ab/include/envoy/stream_info/stream_info.h#L347). The data will be logged as a JSON string.
2. Header to metadata filter (https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/header_to_metadata_filter.html) which at the end uses the same [setDynamicMedatadata](https://github.com/envoyproxy/envoy/blob/8052ec65c49e8bb52b373b6c19a9e170672892ab/source/extensions/filters/http/header_to_metadata/header_to_metadata_filter.cc#L179).

**Comment by dio** [comment]
Oh, I almost forget that you can set it via Lua too https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/lua_filter.html?highlight=lua#set

**Comment by cetanu** [comment]
So I could then do something like this in my config...
```
http_filters:
  - name: envoy.filters.http.header_to_metadata
    config:
      request_rules:
        - header: x-my-metadata-key
          on_header_missing:  # It's always missing
            metadata_namespace: envoy.http_connection_manager.access_log
            key: hello
            value: world
            type: STRING
```

and then log it with:

```
access_log:
              - name: envoy.file_access_log
                config:
                  path: /var/log/envoy/access.log
                  json_format:
                    my_metadata_value: "%DYNAMIC_METADATA(envoy.http_connection_manager.access_log:hello)%"
```

Is that correct?
