### ISSUE TITLE
Admin endpoints not responding

### ISSUE THREAD

**Issue by confusedIamHowBoutU** [envoyproxy/envoy#6165]
**Issue Template**

*Title*: *Admin endpoint not responding*

*Description*:
>Just to start with I am new to envoy. From getting started example I am able to get envoy to proxy all outgoing calls. Now I am trying to get stats and metrics from envoy using the admin endpoint such as /stats.  

> When I "curl -v localhost:9901/stats" Get the following:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9901 (#0)
> GET /stats HTTP/1.1
> Host: localhost:9901
> User-Agent: curl/7.54.0
> Accept: */*
>
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

Also when I try to connect to via chrome on localhost:9901/stats same response come back. My guess admin server is not being  instantiated when starting docker. Not sure if this is the right approach.

*Config*:
>envoy.yaml
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  host_rewrite: {service_name}
                  cluster: {cluster_name}
          http_filters:
          - name: envoy.router
  clusters:
  - name: {cluster_name}
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    #dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: chat_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: {service_name}
                port_value: 443
    tls_context:
      sni: {service_name}
```

>Dockerfile
```
FROM envoyproxy/envoy:latest
RUN apt-get update
ADD envoy.yaml /etc/envoy/envoy.yaml
CMD /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
```
>Docker Cmd for running
```
docker run -d --name envoy -p 9901:9901 -p 10000:10000 envoy:v1
```
