### ISSUE TITLE
Can I do ratelimit based on sub of jwt token?

### ISSUE THREAD

**Issue by rashidfornajah** [envoyproxy/envoy#6189]
*Can I do ratelimit based on sub of jwt token?*

*Description*:
>I would like to do rate limit based on the sub of the jwt token. Every user with valid token will be allowed a maximmum number of limits per second/minute etc.

**Comment by qiwzhang** [comment]
It is not supported now.   Jwt_authn filter and rate-limiting filter are two independent filters, their data are not shared.

A valid JWT payload is written to dynamic Metata,  so rate limiting filter could potentially pick up that data and use it.

**Comment by rashidfornajah** [comment]
Thanks @qiwzhang . It is working now

making this change in rate limit filter passed the JWT token to rate limit service
 ```
   rate_limits:
                - stage: 0
                  actions:
                     - {request_headers:  { header_name: "Authorization", descriptor_key: "token"}}
```

Change in Rate limit service:
```
domain: apis
descriptors:
  - key: token
    rate_limit:
      unit: day
      requests_per_unit: 5
```
