### ISSUE TITLE
[warning] REST config update failed: fetch failure

### ISSUE THREAD

**Issue by TolikT** [envoyproxy/envoy#6197]
**REST config update failed: fetch failure**

*Warning messages*: *using the xds*

*Description*:
>I'm interested in some envoy behavior. I implemented python (flask+tornado) discovery service that is used as xds cluster in envoy configuration and fills following jinja templates with necessary data.

eds.j2
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: some_cluster
  endpoints:
  - lb_endpoints:
    {% for instance in instances %}
    - endpoint:
        address:
          socket_address:
            address: {{ instance.address }}
            port_value: {{ instance.port }}
    {% endfor %}
```

cds.j2
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: some_cluster
  connect_timeout: 1s
  lb_policy: MAGLEV
  type: EDS
  {% if tls %}
  tls_context:
      common_tls_context:
        validation_context:
          trusted_ca:
            filename: /app/data/trusted.pem
  {% endif %}
  eds_cluster_config:
    eds_config:
      api_config_source:
        api_type: REST
        refresh_delay: 10s
        cluster_names:
          - xds_cluster
{% for service in services %}
- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: {{ service.name }}
  type: STRICT_DNS
  connect_timeout: 0.25s
  lb_policy: MAGLEV
  hosts:
    - socket_address: { address: {{ service.name }}, port_value: {{ service.port }} }
{% endfor %}
```

rds.j2
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
  name: router
  virtual_hosts:
  - name: common
    domains: ["*"]
    routes:
    - match: { prefix: "/some-service/" }
      route:
        prefix_rewrite: "/some-prefix/"
        cluster: some_cluster
        auto_host_rewrite: true
        timeout: {{ request_timeout }}s
        hash_policy:
        - header:
            header_name: some-header
    {% for service in services %}
    - match: { prefix: "/{{ service.name }}/" }
      route:
        prefix_rewrite: "/"
        cluster: {{ service.name }}
        auto_host_rewrite: true
        timeout: {{ service.request_timeout }}s
        hash_policy:
        - header:
            header_name: some-header
    {% endfor %}
```

*Config*:

Envoy version is v1.9.0, pulled from docker hub

```
admin:
  access_log_path: /app/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8081 }
    
node:
  cluster: my_cluster
  id: my_cluster

dynamic_resources:
  cds_config:
    api_config_source:
      api_type: REST
      refresh_delay: 10s
      cluster_names: 
        - xds_cluster

static_resources:
  listeners:
  - name: listener1
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          config:
            codec_type: AUTO
            stat_prefix: ingress
            rds:
              route_config_name: router
              config_source:
                api_config_source:
                  api_type: REST
                  refresh_delay: 10s
                  cluster_names: [xds_cluster]
            http_filters:
            - name: envoy.router
  clusters:
  - name: xds_cluster
    connect_timeout: 1s
    type: STRICT_DNS
    dns_refresh_rate: 10s
    lb_policy: ROUND_ROBIN
    hosts:
    - socket_address:
        address: discovery-service
        port_value: 5000
```

*Logs*:
There are following log messages
```
[2019-03-06 19:00:52.505][000006][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/http_subscription_lib/common/config/http_subscription_impl.h:104] REST config update failed: fetch failure
```

And when debug level is set
```
[2019-03-06 20:10:02.133][000006][debug][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/http_subscription_lib/common/config/http_subscription_impl.h:69] Sending REST request for /v2/discovery:routes
--
  | [2019-03-06 20:10:02.133][000006][debug][router] [source/common/router/router.cc:270] [C0][S6400359821593019494] cluster 'xds_cluster' match for URL '/v2/discovery:routes'
  | [2019-03-06 20:10:02.133][000006][debug][router] [source/common/router/router.cc:328] [C0][S6400359821593019494] router decoding headers:
  | ':method', 'POST'
  | ':path', '/v2/discovery:routes'
  | ':authority', 'xds_cluster'
  | ':scheme', 'http'
  | 'content-type', 'application/json'
  | 'content-length', '183'
  | 'x-envoy-internal', 'true'
  | 'x-forwarded-for', 'xxx'
  | 'x-envoy-expected-rq-timeout-ms', '1000'
  |  
  | [2019-03-06 20:10:02.133][000006][debug][pool] [source/common/http/http1/conn_pool.cc:91] [C2562] using existing connection
  | [2019-03-06 20:10:02.133][000006][debug][router] [source/common/router/router.cc:1023] [C0][S6400359821593019494] pool ready
  | [2019-03-06 20:10:02.154][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1237] starting async DNS resolution for xxx
  | [2019-03-06 20:10:02.154][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.155][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.155][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.155][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.156][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.157][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.157][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1244] async DNS resolution complete for xxx
  | [2019-03-06 20:10:02.954][000006][debug][main] [source/server/server.cc:143] flushing stats
  | [2019-03-06 20:10:02.969][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1237] starting async DNS resolution for xxx
  | [2019-03-06 20:10:02.970][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.970][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.970][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.971][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.971][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.971][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.972][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.972][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.972][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.973][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:02.973][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1244] async DNS resolution complete for xxx
  | [2019-03-06 20:10:03.095][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1237] starting async DNS resolution for xxx
  | [2019-03-06 20:10:03.095][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.095][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.096][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.096][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.097][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.097][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.097][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.098][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.098][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.098][000006][debug][upstream] [source/common/network/dns_impl.cc:158] Setting DNS resolution timer for 5000 milliseconds
  | [2019-03-06 20:10:03.098][000006][debug][upstream] [source/common/upstream/upstream_impl.cc:1244] async DNS resolution complete for xxx
  | [2019-03-06 20:10:03.133][000006][debug][router] [source/common/router/router.cc:462] [C0][S6400359821593019494] upstream timeout
  | [2019-03-06 20:10:03.133][000006][debug][router] [source/common/router/router.cc:968] [C0][S6400359821593019494] resetting pool request
  | [2019-03-06 20:10:03.133][000006][debug][client] [source/common/http/codec_client.cc:105] [C2562] request reset
  | [2019-03-06 20:10:03.133][000006][debug][connection] [source/common/network/connection_impl.cc:101] [C2562] closing data_to_write=0 type=1
  | [2019-03-06 20:10:03.133][000006][debug][connection] [source/common/network/connection_impl.cc:183] [C2562] closing socket: 1
  | [2019-03-06 20:10:03.133][000006][debug][client] [source/common/http/codec_client.cc:82] [C2562] disconnect. resetting 0 pending requests
  | [2019-03-06 20:10:03.133][000006][debug][pool] [source/common/http/http1/conn_pool.cc:121] [C2562] client disconnected
  | [2019-03-06 20:10:03.133][000006][debug][http] [source/common/http/async_client_impl.cc:93] async http request response headers (end_stream=false):
  | ':status', '504'
  | 'content-length', '24'
  | 'content-type', 'text/plain'
  |  
  | [2019-03-06 20:10:03.133][000006][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/http_subscription_lib/common/config/http_subscription_impl.h:104] REST config update failed: fetch failure
```

*Note*:
From the prometheus metrics I see that there are success updates exist and also when something is changed, configuration is applied almost immediately.

*Questions*:
1. The version is constant and equal to '0'. It does not lead to failure, but should somehow be changed?
2. What should the xds service return when there is no configuration update?
3. Why there are such messages in logs? I saw such warnings in other issues, but nobody cares. I really do not understand why there is 504 status code returned and what request for, but xds service itself logs only successful responses, no any errors there.
