### ISSUE TITLE
Latest "incremental CDS" feature breaks existing GRPC non-ADS Control Planes

### ISSUE THREAD

**Issue by MarcinFalkowski** [envoyproxy/envoy#6237]
*Title*: Latest "incremental CDS" feature (#6191 ) breaks existing Control Planes

*Description*:
Incremental CDS changed GRPC method from `envoy.api.v2.ClusterDiscoveryService.StreamClusters` to `envoy.api.v2.ClusterDiscoveryService.DeltaClusters` (https://github.com/envoyproxy/envoy/pull/6191/files#diff-1dbe6018649b440b0e51b4f1567d19e0R37). 

From what we se, it breaks our GRPC control plane based on `java-control-plane`. Problem exists in non-ADS mode. Server doesn't recognise new method. 

Envoy logs:
```
gRPC config stream closed: 12, Method not found: envoy.api.v2.ClusterDiscoveryService/DeltaClusters
```

Server logs:
```
17:31:06.370 [grpc-worker-event-loop-thread-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x21d4c2c4, L:/127.0.0.1:50000 - R:/127.0.0.1:58883] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status: 12, grpc-message: Method not found: envoy.api.v2.ClusterDiscoveryService/DeltaClusters] streamDependency=0 weight=16 exclusive=false padding=0 endStream=true
```

config source configuration:
```yaml
dynamic_resources:
  cds_config:
    api_config_source:
      api_type: GRPC
      grpc_services:
      - envoy_grpc:
          cluster_name: envoy-control-xds
        timeout: 1s
```
