### ISSUE TITLE
The 'x-envoy-upstream-service-time' header is not populated for (web socket) upgrade requests

### ISSUE THREAD

**Issue by roekatz** [envoyproxy/envoy#6266]
*Description*:
For web socket upgrade requests, Envoy doesn't set the upstream response time.
I guess that's a bug rather than the intended behaviour.
We use this header, and need it also for web sockets upgrade requests.
After a short look in the code - seems like this field isn't calculated since `end_stream=true` is not passed at the completion of an upgrade request.

*Repro steps*:
Using the following configuration, we get the `x-envoy-upstream-service-time` header on a regular curl:
```
curl --include --no-buffer http://localhost:10000/

HTTP/1.1 404 Not Found
content-type: text/html
content-length: 61
x-envoy-upstream-service-time: 698
date: Tue, 12 Mar 2019 15:48:47 GMT
server: envoy

<html><head></head><body><h1>404 Not Found</h1></body></html>
```

But on Upgrade request, there's no  `x-envoy-upstream-service-time`:
```
curl --include --no-buffer \
     --header "Connection: Upgrade" \
     --header "Upgrade: websocket" \
     --header "Host: localhost:10000" \
     --header "Origin: http://localhost:10000" \
     --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
     --header "Sec-WebSocket-Version: 13" \
     http://localhost:10000/

HTTP/1.1 101 Switching Protocols
access-control-allow-credentials: true
access-control-allow-headers: content-type,authorization,x-websocket-extensions,x-websocket-version,x-websocket-protocol
access-control-allow-origin: http://localhost:10000
connection: Upgrade
date: Tue, 12 Mar 2019 15:28:22 GMT
sec-websocket-accept: qGEgH3En71di5rrssAZTmtRTyFk=
server: envoy
upgrade: websocket
content-length: 0
```
> 

*Config*:
```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { host_rewrite: echo.websocket.org, cluster: service_echo }
          http_filters:
          - name: envoy.router
          upgrade_configs:
          - upgrade_type: websocket
            enabled: true
  clusters:
  - name: service_echo
    connect_timeout: 0.5s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: echo.websocket.org, port_value: 80 }}]
```
