### ISSUE TITLE
Question: Front Proxy example load balancing (Docker aliases)

### ISSUE THREAD

**Issue by Diggzinc** [envoyproxy/envoy#6321]
*Title*: **Front Proxy example load balancing (Docker aliases)**

*Description*:
The example provided by the Envoy repository for the Front Proxy [[link](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy)] demonstrates a `service1` and `service2` that scale horizontally through the usage of `docker-compose scale`.

On **Step 5: Test Envoy’s load balancing capabilities** in the documentation it is mentioned that when scaling the service the envoy clustering capabilities are being demonstrated. Isn't this statement incorrect?

From my understanding, what is happening in this example is the following:
- scaling either `service1`  or `service2` creates new containers (including the **_replica of the side-car proxy_** since they live on the same container)
- The actual resolution of the instance to pick is done by docker when resolving the alias for the services that is specified on the docker compose (see snippets below).

**docker-compose.yml** (ln. 28) [[link](https://github.com/envoyproxy/envoy/blob/8593e6af3953e6a0ca73be8eaebcb2ea0181abc0/examples/front-proxy/docker-compose.yml#L28)]
```
networks:
    envoymesh:
        aliases:
            - service1
```

**front-envoy.yml** (ln. 45) [[link](https://github.com/envoyproxy/envoy/blob/dc23262af443276500c740dd92067a5d22d06e68/examples/front-proxy/front-envoy.yaml#L45)]
```
endpoints:
    - lb_endpoints:
        - endpoint:
            address:
                socket_address:
                    address: service1
                    port_value: 80
```

From what I understand this is not the correct example to demonstrate the envoy capabilities regarding loadbalancing. 
Shouldn't the example be, having **_one side-car proxy per service_** and then have the endpoints of the instances registered on the side-car proxy instead of having one side-car proxy per instance that happens to be resolved by docker through the aliases?

Given all of this, can someone confirm if my rational is correct? I've only delved with Envoy since yesterday so there might be something that I've misunderstood.

Best Regards,
Diogo Pinho

*Relevant Links*:
Front Proxy example documentation - [link](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy)
Front Proxy example code - [link](https://github.com/envoyproxy/envoy/tree/master/examples/front-proxy)
