### ISSUE TITLE
Reload configuration without quit process

### ISSUE THREAD

**Issue by odg0318** [envoyproxy/envoy#6353]
*Title*: *Reloading configuration without quit envoy process*

*Description*:
> I try to replace `nginx` with `envoy` as front proxy. How can I reload configuration without fully restarting envoy process? I read some documentations about hot restart, which seems like working to fork a new process and replace old process with new one. I cannot find a way to reload configuration like `nginx -s reload` in below links.
> Is there a way to reload configuration like nginx without extra starter?

*Relevant Links*
> http://nginx.org/en/docs/beginners_guide.html#control
> http://nginx.org/en/docs/control.html

**Comment by mattklein123** [comment]
Envoy does not work in quite the same way. It uses a dynamic configuration system called xDS. One of the xDS options is to watch configuration files on disk and reload them. 

See https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/v2_overview and https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#core-configsource

**Comment by odg0318** [comment]
@mattklein123 I already read the documentation you refered. As I undertand, I can reload(actually service discovery) ti configure target hosts as upstream not total configuration.
Please let me know something wrong I am saying

**Comment by aclowkey** [comment]
What would be the easiest way to reload configuration similar to what  "nginx -s reload" does? 
I read about hot restart but it didn't find any usage guide..

**Comment by dio** [comment]
@aclowkey do you think file based xDS config will help? e.g. https://medium.com/grensesnittet/file-based-dynamic-configuration-of-routes-in-envoy-proxy-6234dae968d2

Or you want to reload the bootstrap config as well?

**Comment by aclowkey** [comment]
I need to reload the clusters and route_config parts.
Looks like both can be configured as dynamic resources.
Thank you @dio

**Comment by aclowkey** [comment]
@dio It's actually not enough.
I want to have dynamic clusters, i.e. add services dynamically each with their own cluster.
The docs say that the cluster proto is for one upstream cluster, this means I need to generate dynamic list for the `cluster` resources. So either I'm missing something or it's not possible.

I generated the following template for my services
```
resources:
- "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
  name: local_route
  virtual_hosts:
  - name: "lb"
    domains: "*.service.consul"
    routes:
    # Local services
    {{ with node }}
    {{- range .Services -}}
    - match:
        prefix: "/"
        headers:
        - name: ":authority"
          prefix_match: "{{ .Service }}"
        - name: "x-envoy-internal"
          invert_match: true
      route:
        cluster: "{{ .Service }}-local"
    {{- end }}
    {{ end }}
    # External services
    {{ range services -}}
    - match:
        prefix: "/"
        headers:
        - name: ":authority"
          prefix_match: "{{ .Name }}"
      route:
        cluster: "{{ .Name }}-lb"
    {{ end }}
```
Combined with the EDC configuration:
```
  clusters:
  - name: internal
    connect_timeout: 025s
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      service_name: localservices
      eds_config:
        path: /etc/envoy/eds.yaml
```
When I route by {{ .Service}}.service.consul it doesn't find the cluster, because it's named internal
Any tips?
