### ISSUE TITLE
Cannot bind a list to map for field 'typed_per_filter_config'

### ISSUE THREAD

**Issue by rnd4222** [envoyproxy/envoy#6381]
I'm trying to write custom envoy control plane and I need per-route config for **ExtAuthz** filter.
However, when sending **Map("envoy.ext_authz" -> ExtAuthzPerRoute)** in **typed_per_filter_config** field of a **Route**, I'm getting an error in envoy logs:

> [2019-03-26 18:31:18.949][030564][warning][config] [bazel-out/k8-fastbuild/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener rin-listener: Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].routes[0]): invalid value Cannot bind a list to map for field 'typed_per_filter_config'. for type Map): {"http_filters":[{"name":"envoy.router"}],"route_config":{"response_headers_to_add":[],"name":"","virtual_hosts":[{"rate_limits":[],"response_headers_to_remove":[],"routes":[{"response_headers_to_remove":[],"route":{"upgrade_configs":[],"request_headers_to_add":[],"cluster":"cop","hash_policy":[],"response_headers_to_add":[],"prefix_rewrite":"","rate_limits":[],"response_headers_to_remove":[]},"request_headers_to_remove":[],"per_filter_config":[],"request_headers_to_add":[],"typed_per_filter_config":[{"value":{"type_url":"type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthzPerRoute"},"key":"envoy.ext_authz"}],"response_headers_to_add":[],"match":{"headers":[{"name":":method","exact_match":"PATCH"}],"query_parameters":[],"regex":"/api/v1/a/([^/]+)/b/([^/]+)/c/([^/]+)([/]?)"}}],"request_headers_to_remove":[],"request_headers_to_add":[],"virtual_clusters":[],"domains":["*"],"response_headers_to_add":[],"name":"rin"}],"response_headers_to_remove":[],"request_headers_to_remove":[],"request_headers_to_add":[],"internal_only_headers":[]},"via":"","stat_prefix":"rin-router-stats","upgrade_configs":[],"access_log":[],"server_name":""}

Any suggestions?.
I'm also tried setting **per_filter_config** - no luck.

**Comment by rnd4222** [comment]
And I'm getting another error when trying to set **http_connection_error.HttpFilter.typed_config**:

> Unable to parse JSON as proto (INVALID_ARGUMENT:(http_filters[1].typed_config): invalid value Missing @type for any field in envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager for type Any)

So how do I set **Any** or **Struct** typed fields?

**Comment by mattklein123** [comment]
cc @htuch @lizan @moderation

**Comment by lizan** [comment]
@rnd4222 can you post your config or a part of it?

**Comment by rnd4222** [comment]
@lizan I can post it tomorrow, but it's pretty standard bootstrap config which uses LDS/CDS via gRPC ADS.

**Comment by rnd4222** [comment]
@lizan here is the config:

```
node:
  id: node-id-1
  cluster: dc1
dynamic_resources:
  cds_config: { ads: {} }
  lds_config: { ads: {} }
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: ads_cluster
static_resources:
  clusters:
  - name: ads_cluster
    connect_timeout: { seconds: 5 }
    type: STATIC
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 10003
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 12346 }
```
