### ISSUE TITLE
circuit breaking support grpc?

### ISSUE THREAD

**Issue by yiqinguo** [envoyproxy/envoy#6427]
*Title*: 

circuit breaker does not take effect on grpc.

*Description*:
Does the envoy circuit breaker support GRPC? I test the circuit breaker does not take effect on grpc.

*Config*:
This is my envoy config.
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                  grpc: {}
                route:
                  cluster: service_grpc
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_grpc
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    max_requests_per_connection: 1
    outlier_detection:
      interval: "5s"
      base_ejection_time: "180s"
      enforcing_consecutive_5xx: 1
      consecutive_gateway_failure: 1
      enforcing_consecutive_gateway_failure: 100
    circuit_breakers:
      thresholds:
        - max_connections: 1
          max_pending_requests: 1
          max_requests: 1
          max_retries: 1
    hosts:
      - socket_address:
          address: 192.168.1.4
          port_value: 8081
```
