### ISSUE TITLE
Size limit on gRPC-JSON transcoder with google.api.HttpBody as output?

### ISSUE THREAD

**Issue by npuichigo** [envoyproxy/envoy#6441]
Hi, I have been using gRPC-JSON transcoder with google.api.HttpBody to send media resources like mp3 and so on. 

Everything is okay until the body size of HttpBody grows to more than 1MB, and the response header has Internal Server Error in Grpc-Message field.

Here is my configuration:
```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route:
                  cluster: texttospeech_service
                  max_grpc_timeout: 0s
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_json_transcoder
            config:
              proto_descriptor: "/data/texttospeech_service_definition.pb"
              services: ["tts_system.serving.TextToSpeech"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: texttospeech_service
    connect_timeout: 1.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    hosts: [{ socket_address: { address: tts-server, port_value: 9090 }}]
    upstream_connection_options:
      tcp_keepalive:
        keepalive_time: 300
        keepalive_interval: 30
        keepalive_probes: 10
```

 So is there any option to configure the size limit of the transcoded message?
