### ISSUE TITLE
Help with gRPC HTTP / 1.1 reverse bridge: grpc-message mapping.

### ISSUE THREAD

**Issue by sp-manuel-jurado** [envoyproxy/envoy#6471]
**Help with gRPC HTTP / 1.1 reverse bridge.**

*Title*: *Help with gRPC HTTP / 1.1 reverse bridge: grpc-message mapping.*

*Description*:
I'm using the gRPC HTTP / 1.1 reverse bridge and I have the next doubt:

In case of error, (besides the **grpc-status** "auto" map) is there any way to map an error message to the trailer **grpc-message** when my upstream does not understand any gRPC semantics? 

I would like to avoid passing errors in the body and use the standard way.

Many thanks in advance and excuse my ignorance.

*Config*:
This is the config I'm using it and working correctly:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: backend
                  virtual_hosts:
                    - name: backend
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { host_rewrite: nginx, cluster: backend, timeout: 59.99s }
                http_filters:
                  - name: envoy.filters.http.grpc_http1_reverse_bridge
                    config:
                      content_type: application/grpc+proto
                      withhold_grpc_frames: true
                  - name: envoy.router
                    typed_config: {}
  clusters:
  - name: backend
    connect_timeout: 59.99s
    type: logical_dns
    dns_lookup_family: v4_only
    lb_policy: round_robin
    load_assignment:
      cluster_name: backend
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: nginx
                    port_value: 80
```
