### ISSUE TITLE
Change content-type in ext_authz response

### ISSUE THREAD

**Issue by pablo-aledo** [envoyproxy/envoy#6508]
*Title*: *ext_authz changes content-type to text/plain*

*Description*:

I am using envoy as a front-proxy for a set of services in k8s. My
configuration is as follows:

```
- filters:
  - name: envoy.http_connection_manager
    config:
      codec_type: auto
      stat_prefix: ingress_http
      route_config:
        name: local_route
        virtual_hosts:
        - name: local_service
          domains: ["*"]
          routes:
          - match: { prefix: "/" }
            route:
              cluster: monitoring_ui
      http_filters:
      - name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: oauth2-proxy
              cluster: ext-authz
              timeout: 0.25s
            path_prefix: "/oauth2/start"
            allowed_request_headers:
              - Authorization
      - name: envoy.router
...
clusters:
- name: monitoring_ui
  connect_timeout: 0.25s
  type: logical_dns
  hosts:
  - socket_address:
      address: monitoring-ui
      port_value: 80
- name: ext-authz
  connect_timeout: 0.25s
  type: logical_dns
  hosts:
  - socket_address:
      address: oauth2-proxy
      port_value: 80
```

I have an oauth-2-proxy and a dex server instances in the same cluster.

When I make a request without the correct authorization, I would expect envoy
to redirect me to the oauth provider authorization webpage. This is correctly
managed, but the content-type of the response is changed to text/plain, even
when the oauth2-proxy is answering with text/html:

```
curl -v http://192.168.197.242:30878
* About to connect() to 192.168.197.242 port 30878 (#0)
*   Trying 192.168.197.242...
* Connected to 192.168.197.242 (192.168.197.242) port 30878 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.197.242:30878
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< content-length: 2484
< content-type: text/plain
< date: Mon, 08 Apr 2019 11:24:20 GMT
< server: envoy
<

<!DOCTYPE html>
<html lang="en" charset="utf-8">
<head>
        <title>Sign In</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <style>
        body {
... /rest of the authorization page/
```

Because of the fact that content-type is now changed to text/plain, the browser
does not render the webpage and the authorization cannot continue. I am
wondering why the content-type is changed. If this is not a configuration
error, I would like to know if content-type can be changed. I've tried with

```
    route:
      cluster: monitoring_ui
      response_headers_to_add:
        - header:
            key: "Content-Type"
            value: "text/html; charset=utf-8"
```

But without success.

Thanks a lot.

**Comment by snowp** [comment]
@gsagula Mind taking a look at this?

**Comment by enbohm** [comment]
Are you using 1.9.0? Adding allowed_authorization_headers might do the trick, see below
```
- name: envoy.ext_authz
        config:
          http_service:
            server_uri:
              uri: oauth2-proxy
              cluster: ext-authz
              timeout: 0.25s
            path_prefix: "/oauth2/start"
            allowed_request_headers:
              - Authorization
            allowed_authorization_headers: ["content-type"]
```

https://www.envoyproxy.io/docs/envoy/v1.9.0/api-v2/config/filter/http/ext_authz/v2alpha/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2alpha-httpservice
