### ISSUE TITLE
response_headers_to_add field is no longer works on envoyproxy/envoy-alpine:latest image

### ISSUE THREAD

**Issue by herpiko** [envoyproxy/envoy#6527]
*Title*: *response_headers_to_add field is no longer works on envoyproxy/envoy-alpine:latest image*

*Description*:

My existing envoy.yml is no longer valid on the latest envoy image. It seems that `response_headers_to_add` field makes envoy restarting in loop.

*Repro steps*:

This happened with the latest envoy image.

```
$ docker image inspect envoyproxy/envoy-alpine:latest
[
    {
        "Id": "sha256:0246380e4b703fd1f99605a8c31b288c088c078b80ee2de1d987ad819b06e1ec",
        "RepoTags": [
            "envoyproxy/envoy-alpine:latest"
        ],
        "RepoDigests": [
            "envoyproxy/envoy-alpine@sha256:930f6e7a1cde805d455683c9e54d452b5a6acc035ec77f86a7d499d6c92785a0"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-04-05T18:46:51.052058565Z",
        "Container": "b27cba3a12984561a7f7fa1f4040996050e4550acd39bffd9715c3366aa275b1",
        "ContainerConfig": {
            "Hostname": "b27cba3a1298",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"envoy\" \"-c\" \"/etc/envoy/envoy.yaml\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:418e59c4b029ae9fc7f374e72150dae9cb276a97baeee852aee52db99e8cd039",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "envoy",
                "-c",
                "/etc/envoy/envoy.yaml"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:418e59c4b029ae9fc7f374e72150dae9cb276a97baeee852aee52db99e8cd039",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 28655248,
        "VirtualSize": 28655248,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/8d35c70eb566b0530d6a412c1d60c4a91bf32a77e5d7ffda8a7fbf8053892d1b/diff:/var/lib/docker/overlay2/705e5c923258f78e5b37cffa055ae34e92b97865954f88c4cbce8a12198c4247/diff:/var/lib/docker/overlay2/cefc90abca91d6bf495576a91cbc125ae64bfc9d27cab40ae5d2ceb7c94097a8/diff:/var/lib/docker/overlay2/3560ae16ddf868be42c6de479cfb13e7c437f8e6a84890bb23fd5f8fb05ff37e/diff:/var/lib/docker/overlay2/dd5edc8fde19cc2b6ada30250b88734d0e9fa88bd06bbcb18595fb265f097ebf/diff",
                "MergedDir": "/var/lib/docker/overlay2/31864d5272aad277e801407e659f3c50cd7fd7df260c530ff6c982e8290f46cd/merged",
                "UpperDir": "/var/lib/docker/overlay2/31864d5272aad277e801407e659f3c50cd7fd7df260c530ff6c982e8290f46cd/diff",
                "WorkDir": "/var/lib/docker/overlay2/31864d5272aad277e801407e659f3c50cd7fd7df260c530ff6c982e8290f46cd/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:503e53e365f34399c4d58d8f4e23c161106cfbce4400e3d0a0357967bad69390",
                "sha256:2ff9e9430eaf6884551c1dc0118d4e57f3fb76df9d379cb73c78f4925926b044",
                "sha256:f7c5bc0d2684585635e197635b097d2b70afb81e71c258365a0da760d7ec55a8",
                "sha256:cebcca04242eeeafde6a130321fa8fe258aabe2ccf8e25160412808d32e22c4c",
                "sha256:e7c452847afd0d77c0d562de51938c28ce9bd78312f06dfa09d4843d0ab1e6de",
                "sha256:57a1877dbb83155b621c77939003782c36501e3388ca0ac58378a20779c3d77e"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

```

But it still works without any error if I rolled back the image to `envoyproxy/envoy-alpine:36f39c746eb7d03b762099b206403935b11972d8`

```
$ docker image inspect envoyproxy/envoy-alpine:36f39c746eb7d03b762099b206403935b11972d8
[
    {
        "Id": "sha256:c5a7056a3a1e5e710a46d7f7d4e07e7151fd13e14be45a1fab35c464e3da532f",
        "RepoTags": [
            "envoyproxy/envoy-alpine:36f39c746eb7d03b762099b206403935b11972d8"
        ],
        "RepoDigests": [
            "envoyproxy/envoy-alpine@sha256:82dabcdcef0c2f093915dd6fafe727306fdaeaf28c335dbe602dfddab345a682"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2019-03-20T16:55:21.509720414Z",
        "Container": "0a2a180ad65ea94c4f96100f231708d750bf3ae77229035bd6bac0f99582d00c",
        "ContainerConfig": {
            "Hostname": "0a2a180ad65e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"envoy\" \"-c\" \"/etc/envoy/envoy.yaml\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:772c41cb894309a69bb555860b9b48148234ae531cd0511b8fea445885c2e448",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "10000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8"
            ],
            "Cmd": [
                "envoy",
                "-c",
                "/etc/envoy/envoy.yaml"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:772c41cb894309a69bb555860b9b48148234ae531cd0511b8fea445885c2e448",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/docker-entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 28655184,
        "VirtualSize": 28655184,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/49ceb468adb4580c52aa5fa8af8ced1b8e9ea28c50fa258a213f6b347cacfad2/diff:/var/lib/docker/overlay2/9b2ce4a9142f92c49599f0b092fa1f3daacd70112713fd618e4bb9ec44f571de/diff:/var/lib/docker/overlay2/47c6ed9ee86e8137df7c5bec51f099e7b4c4cf1adf255f1a0a7d0a0e98ab8cf2/diff:/var/lib/docker/overlay2/3560ae16ddf868be42c6de479cfb13e7c437f8e6a84890bb23fd5f8fb05ff37e/diff:/var/lib/docker/overlay2/dd5edc8fde19cc2b6ada30250b88734d0e9fa88bd06bbcb18595fb265f097ebf/diff",
                "MergedDir": "/var/lib/docker/overlay2/aa4ff979d66357be3d54165c37d6598e1f7535c980c48ffeb11d5455119860b3/merged",
                "UpperDir": "/var/lib/docker/overlay2/aa4ff979d66357be3d54165c37d6598e1f7535c980c48ffeb11d5455119860b3/diff",
                "WorkDir": "/var/lib/docker/overlay2/aa4ff979d66357be3d54165c37d6598e1f7535c980c48ffeb11d5455119860b3/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:503e53e365f34399c4d58d8f4e23c161106cfbce4400e3d0a0357967bad69390",
                "sha256:2ff9e9430eaf6884551c1dc0118d4e57f3fb76df9d379cb73c78f4925926b044",
                "sha256:62fdd70c1925aae52acdecf263b9299ae54198a339c90959f9780b609ae7eeb7",
                "sha256:71a109633ff6aa9f626f7389c442172e0ae95393d499529bdd30f51c28e6a55b",
                "sha256:1a58dc68ff37518a91d27ecdefda628107f59dd1f5bd53dbc67f4b71e42b4f00",
                "sha256:a1547a50088ca10121b72eca41418e9c20f64d63c3c2ec87389b6708539f9ef6"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

```

*Config*:

Bellow is part of  `envoy.yaml` that contains `response_headers_to_add`
```
            virtual_hosts:
            - name: xx_service
              domains: ["censored_domain"]
              routes:
              - match: { prefix: "/" }
                route: 
                  cluster: xx_frontend
                  timeout: 360s
                  response_headers_to_add:
                    - header:
                        key: "x-frame-options"
                        value: "sameorigin"
                    - header:
                        key: "cache-control"
                        value: "must-revalidate"
                    - header:
                        key: "x-xss-protection"
                        value: "1; mode=block"
                    - header:
                        key: "x-content-type-options"
                        value: "nosniff"
                    - header:
                        key: "Strict-Transport-Security"
                        value: "max-age=63072000; includeSubdomains"
                    - header:
                        key: "Content-Security-Policy"
                        value: "style-src 'self' 'unsafe-inline'; script-src-elem 'self' 'unsafe-eval' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdnjs.cloudflare.com; object-src 'self' data:; img-src 'self' data: https://x.censored.domain; connect-src 'self' data: https://fr.webrtc.censored.domain; default-src 'self' data: https://fr.webrtc.censored.domain https://cdnjs.cloudflare.com https://x.censored.domain"
                    - header:
                        key: "Public-Key-Pins"
                        value: "pin-sha256=\"censoredstring=\"; max-age=5184000; includeSubDomains"
                    - header:
                        key: "X-Permitted-Cross-Domain-Policy"
                        value: "none"
                      append: true
```

*Logs*:

```
[2019-04-09 18:49:24.705][1][debug][grpc] [source/common/grpc/google_async_client_impl.cc:33] Joined completionThread
[2019-04-09 18:49:24.706][1][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:829] shutting down thread local cluster manager
[2019-04-09 18:49:24.706][1][info][main] [source/server/server.cc:522] exiting
[2019-04-09 18:49:24.706][1][debug][init] [source/common/init/watcher_impl.cc:27] ListenerImpl destroyed
[2019-04-09 18:49:24.706][1][debug][init] [source/common/init/watcher_impl.cc:27] init manager Listener http_listener destroyed
[2019-04-09 18:49:24.706][1][debug][init] [source/common/init/watcher_impl.cc:27] init manager Server destroyed
Unable to parse JSON as proto (INVALID_ARGUMENT:(route_config.virtual_hosts[0].routes[2].route) response_headers_to_add: Cannot find field.): {"codec_type":"AUTO","http_filters":[{"name":"envoy.gzip","config":{"compression_level":"BEST","memory_level":9}},{"name":"envoy.router"}],"stat_prefix":"ingress_http","upgrade_configs":[{"upgrade_type":"websocket"}],"route_config":{"name":"registration_route","virtual_hosts":[{"domains":["censored.domain"],"name":"xx_service","routes":[{"route":{"cluster":"xx_backend"},"match":{"prefix":"/api"}},{"route":{"cluster":"xx_backend"},"match":{"prefix":"/ws"}},{"route":{"cluster":"xx_frontend","timeout":"360s","response_headers_to_add":[{"header":{"key":"x-frame-options","value":"sameorigin"}},{"header":{"key":"cache-control","value":"must-revalidate"}},{"header":{"key":"x-xss-protection","value":"1; mode=block"}},{"header":{"key":"x-content-type-options","value":"nosniff"}},{"header":{"key":"Strict-Transport-Security","value":"max-age=63072000; includeSubdomains"}},{"header":{"key":"Content-Security-Policy","value":"style-src 'self' 'unsafe-inline'; script-src-elem 'self' 'unsafe-eval' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdnjs.cloudflare.com; object-src 'self' data:; img-src 'self' data: https://x.censored.domain; connect-src 'self' data: https://fr.webrtc.censored.domain; default-src 'self' data: https://fr.webrtc.censored.domain https://cdnjs.cloudflare.com https://x.censored.domain"}},{"header":{"key":"Public-Key-Pins","value":"pin-sha256=\"censoredstring=\"; max-age=5184000; includeSubDomains"}},{"header":{"key":"X-Permitted-Cross-Domain-Policy","value":"none"},"append":true}]},"match":{"prefix":"/"}}]}]}}
```
