### ISSUE TITLE
Envoy redirects requests regardless X-Forwarded-Proto scheme when configured with require_tls: ALL

### ISSUE THREAD

**Issue by gsagula** [envoyproxy/envoy#6559]
*Use case*:
`Envoy` is running with an external `LB terminating TLS` in front of it. I want `Envoy` to redirect the requests based on `X-Forwarded-Proto` (XFP) value. For example, only requests that contain `X-Forwarded-Proto: http`, should be redirected to a new HTTPs location, and requests that contain `X-Forwarded-Proto: https` should pass through.

*Description:*
When setting `require_tls: ALL` to the virtual host, it seems that the requests get redirected regardless of the XFP header. In very early Envoy versions, a request would get redirected based on XFP when a virtual host was configured with `require_ssl: all` if `use_remote_address: false`.

*Configuration:*
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
 
    filter_chains:
      use_proxy_proto: False
      filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          idle_timeout: 0.840s
          stat_prefix: egress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: echo-service
              require_tls: ALL
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: echo-service

          - name: envoy.router
            config: {}

  clusters:  
  - name: echo-service
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    connect_timeout: 10s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: echo-service, port_value: 80 }}]

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 61893
```

Is this an issue? If not, any idea of how to support the use case described above?
