### ISSUE TITLE
How to redirect all traffic from www to non-www

### ISSUE THREAD

**Issue by joseluisq** [envoyproxy/envoy#6573]
**Title**: How to redirect all traffic from www to non-www

**Description**:
I would like to redirect all traffic from `www.domain.com` to `domain.com`:

- http://www.domain.com →https://domain.com (done)
- http://www.domain.com/page.html → https://domain.com/page.html
- https://www.domain.com → https://domain.com
- https://www.domain.com/page.html → https://domain.com/page.html

**Config**:

```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address: { protocol: TCP, address: 0.0.0.0, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_http
    address:
      socket_address: { protocol: TCP, address: 0.0.0.0, port_value: 80 }
    listener_filters:
    - name: "envoy.listener.tls_inspector"
      typed_config: {}
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:

            virtual_hosts:

            # this only redirect: http://www.domain.com to https://www.domain.com
            - name: www_backend
              domains:
              - "www.*"
              routes:
              - match: { prefix: "/" }
                redirect: { path_redirect: "/", https_redirect: true }

            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/" }
                redirect: { path_redirect: "/", https_redirect: true }

          http_filters:
          - name: envoy.router
            config: {}

  - name: listener_https
    address:
      socket_address: { protocol: TCP, address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route

            virtual_hosts:
            - name: domain_com_backend
              domains:
              - "domain.com"
              routes:
              - match: { prefix: "/" }
                route: { cluster: domain_com }

          http_filters:
          - name: envoy.router
            typed_config: {}
      tls_context:
        common_tls_context:
          alpn_protocols: [ "h2,http/1.1" ]
          tls_certificates:
          - certificate_chain: { filename: "/etc/envoy/certs/domain_com.cert" }
            private_key: { filename: "/etc/envoy/certs/domain_com.key" }

  clusters:
  - name: domain_com
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    load_assignment:
      cluster_name: domain_com
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: domain_com
                port_value: 80
```

Thanks!

**Comment by htuch** [comment]
@joseluisq I think if you drop the `path_redirect` field it should work as you intend.

**Comment by joseluisq** [comment]
@htuch I solved it droping `www_backend` (`listener_http`) then in `listener_https` I have created a new entry in `virtual_hosts` putting _**manually**_ the domain name (with www), finally redirecting via `host_redirect`:

```yaml
static_resources:
  listeners:
  - name: listener_http
    # ...

            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match: { prefix: "/" }
                redirect: { https_redirect: true }

  - name: listener_https
    # ...

            virtual_hosts:
            - name: www_backend
              domains:
              - "www.domain.com"
              routes:
              - match: { prefix: "/" }
                redirect: { host_redirect: "domain.com", https_redirect: true }

           virtual_hosts:
            - name: domain_com_backend
              domains:
              - "domain.com"
              routes:
              - match: { prefix: "/" }
                route: { cluster: domain_com }
```

**Comment by joseluisq** [comment]
But the questions is how can I do using a wildcard? Actually this below doesn't work.

```yaml
            virtual_hosts:
            - name: www_backend
              domains:
              - "www.*"
              routes:
              - match: { prefix: "/" }
                redirect: { https_redirect: true }

                # Something like this maybe?:
                redirect: { host_redirect: "*", https_redirect: true }
```
