### ISSUE TITLE
Invalid Redis config when using prefix_routes?

### ISSUE THREAD

**Issue by jshlbrd** [envoyproxy/envoy#6664]
**Issue Template**

*Title*: *Invalid Redis config when using prefix_route?*

*Description*:
I'm having difficulty getting prefix_routes to work. Based on the docs, the Redis example configuration seems to be out of date. Specifically, here: https://github.com/envoyproxy/envoy/blob/master/examples/redis/envoy.yaml#L14

```
          cluster: redis_cluster
```

The documentation says this about "cluster":
```
Attention

This field is deprecated. Use a catch-all cluster instead.
```

However, when I change the example to match the new docs (shown here) ...

```
          prefix_routes:
            catch_all_cluster: redis_cluster
```

... I receive this error:

```
[2019-04-20 15:48:31.951][1][critical][main] [source/server/server.cc:90] error initializing configuration '/etc/envoy/envoy.yaml': Unable to parse JSON as proto (INVALID_ARGUMENT:prefix_routes: Cannot find field.): {"admin":{"address":{"socket_address":{"port_value":8001,"address":"0.0.0.0"}},"access_log_path":"/dev/null"},"static_resources":{"clusters":[{"load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":6379,"address":"widget_1"}}}}]}],"cluster_name":"redis_cluster"},"lb_policy":"MAGLEV","type":"strict_dns","name":"redis_cluster","connect_timeout":"1s"}],"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"settings":{"op_timeout":"5s"},"prefix_routes":{"catch_all_cluster":"redis_cluster"},"@type":"type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy","stat_prefix":"egress_redis"},"name":"envoy.redis_proxy"}]}],"name":"redis_listener","address":{"socket_address":{"port_value":1999,"address":"0.0.0.0"}}}]}}

Unable to parse JSON as proto (INVALID_ARGUMENT:prefix_routes: Cannot find field.): {"admin":{"address":{"socket_address":{"port_value":8001,"address":"0.0.0.0"}},"access_log_path":"/dev/null"},"static_resources":{"clusters":[{"load_assignment":{"endpoints":[{"lb_endpoints":[{"endpoint":{"address":{"socket_address":{"port_value":6379,"address":"widget_1"}}}}]}],"cluster_name":"redis_cluster"},"lb_policy":"MAGLEV","type":"strict_dns","name":"redis_cluster","connect_timeout":"1s"}],"listeners":[{"filter_chains":[{"filters":[{"typed_config":{"settings":{"op_timeout":"5s"},"prefix_routes":{"catch_all_cluster":"redis_cluster"},"@type":"type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy","stat_prefix":"egress_redis"},"name":"envoy.redis_proxy"}]}],"name":"redis_listener","address":{"socket_address":{"port_value":1999,"address":"0.0.0.0"}}}]}}
```

I also tried mimicking the Redis proxy integration test settings and that failed too: https://github.com/envoyproxy/envoy/blob/dc3467adacb8f2b0393583857e709c06d76a2441/test/extensions/filters/network/redis_proxy/redis_proxy_integration_test.cc#L142-L153

*Config*:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 1999
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          prefix_routes:
            catch_all_cluster: redis_cluster
          settings:
            op_timeout: 5s

  clusters:
  - name: redis_cluster
    connect_timeout: 1s
    type: strict_dns # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: widget_1
                port_value: 6379

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
