### ISSUE TITLE
Envoy (re)uses connection after receiving FIN from upstream

### ISSUE THREAD

**Issue by lvgilmore** [envoyproxy/envoy#6815]
*Description*:
With Envoy serving as HTTP/1.1 proxy, sometimes Envoy tries to reuse a connection even after receiving FIN from upstream. In production I saw this issue even with couple of seconds from FIN to next request, and Envoy never returned FIN ACK (just FIN from upstream to envoy, then PUSH with new HTTP request from Envoy to upstream). Then Envoy returns 503 UC even though upstream is up and operational.

Steps to reproduce shows a slightly modified version of this issue, as to encourage Envoy to reuse a connection I set circuit breakers to low max_connections and max_requests. Instead of returning UO, Envoy try to reuse a connection that received FIN and so we get 503 UC.

*Repro steps*:
Upstream is a simple web server that sleeps 2s, then returns simple json, running as simple docker container in same network as Envoy. Envoy is running as container as well, using version
8c8b068c51492710a2c7697a296592841499e8e7/1.11.0-dev/Clean/RELEASE/BoringSSL
client just cURL running ~ concurenlty 7 times.
We can see the error:
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/9298707/57228355-4a552500-701c-11e9-8d19-c8c120fcece8.png">
In logs it looks like
```
[2019-05-05T08:44:21.926Z] "GET /6 HTTP/1.1" 503 UO 0 81 1 - "-" "curl/7.54.0" "bd5c20e6-10a4-4654-81fb-c2ed46d175fe" "localhost:9080" "-"
[2019-05-05T08:44:21.909Z] "GET /shit HTTP/1.1" 200 - 0 16 2007 2004 "-" "curl/7.54.0" "1bbcaca7-8b33-43fb-9cf2-ef26841b5321" "localhost:9080" "172.22.0.3:8080"
[2019-05-05T08:44:21.915Z] "GET /3 HTTP/1.1" 200 - 0 16 2004 2004 "-" "curl/7.54.0" "7d19bc5f-a267-43c3-b3c0-6a042b24a9f5" "localhost:9080" "172.22.0.3:8080"
[2019-05-05T08:44:21.917Z] "GET /1 HTTP/1.1" 503 UC 0 95 2003 - "-" "curl/7.54.0" "23764aa2-2f3e-4ea0-bfed-dd0bb9b977b3" "localhost:9080" "172.22.0.3:8080"
[2019-05-05T08:44:21.920Z] "GET /2 HTTP/1.1" 200 - 0 16 2005 2004 "-" "curl/7.54.0" "10a76e91-cdf0-4560-892c-4b64c8462202" "localhost:9080" "172.22.0.3:8080"
[2019-05-05T08:44:21.925Z] "GET /5 HTTP/1.1" 200 - 0 16 4010 4008 "-" "curl/7.54.0" "214df7d2-da2b-4f71-ad4e-f4c02c30d7d8" "localhost:9080" "172.22.0.3:8080"
[2019-05-05T08:44:21.926Z] "GET /4 HTTP/1.1" 200 - 0 16 6017 6017 "-" "curl/7.54.0" "a98e7bdd-6de7-4165-bea1-0f248cf55f9f" "localhost:9080" "172.22.0.3:8080"
```
of most interest is the 4th line, GET /1 HTTP/1.1" **503 UC** 

*Config*:
envoy config
```
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9000

node:
  cluster: mycluster
  id: test-id

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 9080 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          access_log:
            config: {path: /dev/stdout}
            name: envoy.file_access_log
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: upstream }
          http_filters:
          - name: envoy.router

  clusters:
  - name: upstream
    type: STRICT_DNS
    connect_timeout: 0.25s
    hosts: [{ socket_address: { address: 'upstream' , port_value: 8080 }}]
    circuit_breakers:
      thresholds:
      - {max_connections: 2, max_pending_requests: 3, max_requests: 4,
        max_retries: 0, priority: default}
```

*Logs*:
[trace.log](https://github.com/envoyproxy/envoy/files/3148140/trace.log)

**Comment by alyssawilk** [comment]
I'm a bit confused at this trace.  I'm reading "Upstream sends Envoy an GET" and "Envoy sends the upstream 1 200/OK".    Do you have the names inverted in your trace?

Assuming so, I believe there's always going to be a race condition (helped by but not entirely fixed by #2871) where Envoy may reuse the connection before processing the FIN.  In your case it looks like you're sending HTTP/1.0 responses where the connection should not by default be reused.  You could file a feature request for better upstream HTTP/1.0 handling, or you could configure retries to handle the race.

**Comment by winguse** [comment]
I observed this issue in our production recently.

![image](https://user-images.githubusercontent.com/1443504/76720224-2784b880-6777-11ea-8a44-1ae6bf2ea95f.png)

We are using an older version, `v1.9.0`, and the backend is a node.js service.

As you can see the packages, the node.js send a FIN and envoy already ack the FIN but still sending a new HTTP request to upstream and the node.js send with RST and terminate the request.

The downstream of envoy will see `upstream connect error or disconnect/reset before headers` (HTTP 503).

Our cluster config is simple:

```yaml
name: local_cluster
connect_timeout: 15s
type: STATIC
lb_policy: ROUND_ROBIN
hosts:
- socket_address:
    address: 127.0.0.1
    port_value: 15225
health_checks:
- timeout: 5s
  interval: 10s
  healthy_threshold: 1
  unhealthy_threshold: 2
  reuse_connection: true
  http_health_check:
    path: /api/health
```

I believe this is a race condition.

**Comment by winguse** [comment]
we walk around this by adding:

```yaml
common_http_protocol_options:
  # node.js is going to close the connection when idle 5s,
  # we set it to 4s to let envoy close the conn early
  idle_timeout: 4s 
```

But i believe this should be permanently fixed in Envoy
