### ISSUE TITLE
gRPC transcoding: No 'Content-Type' on Request

### ISSUE THREAD

**Issue by sgammon** [envoyproxy/envoy#6846]
*Title*: gRPC transcoding: No `Content-Type` on Request

*Description*:
There should be a way to default to JSON output from gRPC -> JSON transcoding. Perhaps there is one, but I built against `v1.11.0` and I don't see a way to do it in the docs.

When submitting a request against a URL bound via `goog.api.http`, and there is no existing `Content-Type` value on the request, or `Accept` value on the request, that indicates or contains `application/grpc`, then the server should default to JSON (potentially behind a configuration flag).

*Relevant Links*:
Release notes [in progress for `v1.11.0`](https://www.envoyproxy.io/docs/envoy/latest/intro/version_history#pending) indicate that [auto mapping](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/transcoder/v2/transcoder.proto#envoy-api-field-config-filter-http-transcoder-v2-grpcjsontranscoder-auto-mapping) was added recently, which follows `goog.api.http` annotations for gRPC/JSON transcoding.

*Repro steps*:
1) build Envoy release executable from `master`
2) launch Envoy configured with gRPC JSON transcoding, and with `auto_mapping` set to `true` and `match_incoming_request_route` set to `true`

3) visit a mapped gRPC endpoint in a browser - instead of a `404` (pre-`v1.10.0`), receive the following response:

(simulated via `curl`):
```
curl 'https://endpoint:port/some-endpoint' -H 'authority: endpoint:port' -H 'cache-control: max-age=0' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; ...)' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -v
```

response from Envoy:
```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 415 
< content-type: text/plain; encoding=utf-8
< grpc-status: 13
< grpc-message: Content-Type is missing from the request
< x-envoy-upstream-service-time: 10
< date: Tue, 07 May 2019 21:39:07 GMT
< server: envoy
```

4) Okay, you say to yourself. i'll play this game with you envoy. let's specify a `Content-Type`, although, that might cause a CORS preflight when used via XHR in the browser (which may not set a `Content-Type` on the request, but rather, an `Accept`, to indicate types).

so you specify a `Content-Type` via `curl`, to `application/json`, since that's what we want:
```
curl 'https://endpoint:port/some-endpoint' -H 'authority: endpoint:port' -H 'cache-control: max-age=0' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; ...)' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -v -H 'content-type: application/json'
```

response from Envoy:
```
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 415 
< content-type: text/plain; encoding=utf-8
< grpc-status: 13
< grpc-message: Content-Type 'application/json' is not supported
< x-envoy-upstream-service-time: 9
< date: Tue, 07 May 2019 21:40:36 GMT
< server: envoy
```

Anybody have an idea what that **grpc-message: Content-Type 'application/json' is not supported** is about, and/or how to ask Envoy to default to enabling gRPC > JSON transcoding?

Happy to post Envoy Collect and admin/stats output if needed.

*Config*:
```yaml
static_resources:
  listeners:
    - name: rpc_listener_tls
      address:
        socket_address: { address: 0.0.0.0, port_value: <port> }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/dev/stdout"
                stat_prefix: ingress_https
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains:
                        - "*"
                      require_tls: ALL
                      routes:
                        - match: { prefix: "/" }
                          route:
                            cluster: rpc
                            max_grpc_timeout: 2s
                      cors:
                        allow_origin:
                          - "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: <lots-of-headers>
                        max_age: "86400"
                        expose_headers: grpc-status,grpc-message
                        filter_enabled:
                          default_value:
                            numerator: 100
                            denominator: HUNDRED
                          runtime_key: cors.tls.enabled
                http_filters:
                  - name: envoy.grpc_web
                    typed_config: {}
                  - name: envoy.grpc_http1_bridge
                    typed_config: {}
                  - name: envoy.grpc_json_transcoder
                    config:
                      proto_descriptor: "/services.pb"
                      services:
                        - "some.service.defined.Here"
                      auto_mapping: true
                      match_incoming_request_route: true
                      print_options:
                        add_whitespace: false
                        always_print_primitive_fields: false
                        always_print_enums_as_ints: false
                        preserve_proto_field_names: false
                  - name: envoy.cors
                    typed_config: {}
                  - name: envoy.router
                    typed_config: {}
```

*Logs*:
Happy to post if needed but they're regular `HTTP 415` errors, like so:
```
GET /some/bound/uri HTTP/2" 415 - 0 48 9 9 "-" "Mozilla/5.0 (Macintosh; ...)" "trace-id-here" "endpoint:port" "cluster-ip:cluster-port"
```
