### ISSUE TITLE
Selectively check TLS client cert based on domain or route

### ISSUE THREAD

**Issue by markschmid** [envoyproxy/envoy#6963]
Description

In a "web context", we would like to check the TLS client certificate for some requests, but for other requests to the same envoyproxy, no client certificate is needed. The distinction could be based on domain or path (routing) level. We've tried different ways to achieve that goal, but have not succeeded so far.

Things we've considered:
- As far as we understand from the docs, a listener address has to be unique (e.g. 0.0.0.0:443 in our case), which means we have to solve the problem from within the same listener(?)
- Seems like the `tls_context` definition is for the whole filter chain, so it's unclear how to make a distinction between requests that need checking the client cert and others that do not
- according to https://github.com/envoyproxy/envoy/issues/5920 it seems that you cannot have multiple `envoy.http_connection_manager` filters "in a row" where any of them can match

Is it possible and how? Help greatly appreciated.

**Comment by markschmid** [comment]
Simplified config:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    #listener_filters:
    #- name: "envoy.listener.tls_inspector"
    #  config: {}
    filter_chains:
      filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          forward_client_cert_details: ALWAYS_FORWARD_ONLY
          route_config:
            name: local_route
            virtual_hosts:
            - name: x
              domains: ["domain.com"]
              routes:
              - match:
                  prefix: "/api"
                route:
                  cluster: api
          http_filters:
          - name: envoy.router
      tls_context:
        #require_client_certificate: true
        common_tls_context:
          tls_certificates:
            certificate_chain: { "filename": "/etc/envoy/certs/cert_bundle.crt" }
            private_key: { "filename": "/etc/envoy/certs/priv.key" }
          validation_context:
            verify_certificate_spki: "<value>"
  clusters:
  - name: api
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
      - socket_address: { address: api, port_value: 3333 }
  - name: web
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    hosts:
      - socket_address: { address: web, port_value: 3334 }
```

How to extend this config with a route or a domain for the cluster `web` where requests must not be checked for client certificate?
