### ISSUE TITLE
Cannot set up global rate limit service locally

### ISSUE THREAD

**Issue by Richardo92** [envoyproxy/envoy#6974]
**Issue Template**

*Title*: *fail to connect envoy proxy with global rate limit service*

*Description*:
I have set up a simple mesh network based on envoy locally.
Below is the mesh file:
```
version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

networks:
  envoymesh: {}

```
I am using the latest envoy docker image: `FROM envoyproxy/envoy-dev:latest`

When I `curl localhost:8000/service/1`, request will first go to the front-envoy, and then gets redirected to service1. Below is the yaml file for the front-envoy:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/var/log/access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
                - "*"
              routes:
                - match:
                    prefix: "/service/1"
                  route:
                    cluster: service1
              rate_limits:
                - stage: 0
                  actions:
                  - generic_key:
                      descriptor_value: "default"
          http_filters:
          - name: envoy.rate_limit
            config:
              domain: apis
              stage: 0
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: rate_limit_cluster
                  timeout: 0.25s

          - name: envoy.router
            typed_config: {}
  clusters:
  - name: local_service
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: local_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080

  - name: service1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: service1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: service1
                port_value: 80

  - name: rate_limit_cluster
    type: STATIC
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8081 }}]
    http2_protocol_options: {}

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001

```

When I do curl, I can see the response from service1:
```
$ curl localhost:8000/service/1
Hello from behind Envoy (service 1)! hostname: 545bf3621ff3 resolvedhostname: 172.25.0.4
```
(I don't plan to share the yaml file of service1 here because I feel it is not useful to debug the issue)

I want to connect front-envoy with the global rate-limit service, as you can see in my yaml file.
I have set up the global rate limit service by:
- Go to https://github.com/lyft/ratelimit and clone the repo
- Finish the setup section
- docker-compose up

The rate limit server is working because I can see its config:
```
C02SQ230H03M:ratelimit zhidongliu$ curl localhost:6070/rlconfig
apis.generic_key_default: unit=MINUTE requests_per_unit=1
```

But when I call front-envoy, the rate limit never works. I can always keep sending request to my service and get the response. But request never get rate limited. I don't know why.
```
// logs from envoy
service1_1     | 127.0.0.1 - - [16/May/2019 22:26:48] "GET /service/1 HTTP/1.1" 200 -
service1_1     | 127.0.0.1 - - [16/May/2019 22:26:50] "GET /service/1 HTTP/1.1" 200 -
service1_1     | 127.0.0.1 - - [16/May/2019 22:26:51] "GET /service/1 HTTP/1.1" 200 -
service1_1     | 127.0.0.1 - - [16/May/2019 22:26:51] "GET /service/1 HTTP/1.1" 200 -
service1_1     | 127.0.0.1 - - [16/May/2019 22:27:00] "GET /service/1 HTTP/1.1" 200 -
```

I have seen some examples online about setting up rate limit in envoy. But seems we cannot use rate_limit_service at the same level with admin section anymore. So I move it under envoy.rate_limit http filter. 

I feel the request never gets redirected to the global rate limit service by envoy. Because I cannot find any hit logs in rate limit service.
```
C02SQ230H03M:ratelimit zhidongliu$ curl localhost:6070/stats
// logs from rate limit service
cmdline: ["/usr/local/bin/ratelimit"]
memstats: {"Alloc":1038992,"TotalAlloc":154639832,"Sys":9246968,"Lookups":206,"Mallocs":4593662,"Frees":4580862,"HeapAlloc":1038992,"HeapSys":5373952,"HeapIdle":3235840,"HeapInuse":2138112,"HeapReleased":3235840,"HeapObjects":12800,"StackInuse":917504,"StackSys":917504,"MSpanInuse":40280,"MSpanSys":65536,"MCacheInuse":6944,"MCacheSys":16384,"BuckHashSys":1455550,"GCSys":405504,"OtherSys":1012538,"NextGC":4194304,"LastGC":1558045534505899237,"PauseTotalNs":729405326,"PauseNs":[5861718,383475,694958,870430,.......
```

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.
https://github.com/envoyproxy/envoy/issues/6615
https://github.com/envoyproxy/envoy/issues/3388

Please help me take a look at it. I think it may be a real issue. I have been stuck on it for 2 weeks. Thanks in advance!

**Comment by Richardo92** [comment]
@junr03 @htuch FYI

**Comment by Richardo92** [comment]
I tried to downgrade my envoy version to be `envoyproxy/envoy:v1.9.0`
and followed the configure in this issue: https://github.com/envoyproxy/envoy/issues/3388
Now I can move rate_limit_service out but rate limit still doesn't work.

```
// docker-compose.yaml
version: "3.7"
services:

  front-envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
```

```
// front-envoy.yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 8001 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 80 }
    filter_chains:
    - filters:

      - name: envoy.http_connection_manager
        config:
          use_remote_address: true 
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/var/log/access.log"
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              rate_limits:
                - stage: 0
                  actions:
                    - generic_key:
                        descriptor_value: "default"
              routes:
                - match: { prefix: "/" }
                  route:
                       host_rewrite: www.google.com
                       cluster: service_google

          http_filters:
          - name: envoy.rate_limit
            config:
                stage: 0
                domain: apis
          - name: envoy.router

  clusters:
  - name: rate_limit_cluster
    type: STATIC
    connect_timeout: 0.25s
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 8081 }}]
    http2_protocol_options: {}

  - name: service_google
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }


rate_limit_service:
    grpc_service:
        envoy_grpc:
            cluster_name: rate_limit_cluster
        timeout: 0.25s

```

```
// docker-compose.yaml in rate limit
version: "3"
services:

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - ratelimit-network

  # minimal container that builds the ratelimit service binary and exits.
  ratelimit-build:
    image: golang:1.10-alpine
    working_dir: /go/src/github.com/lyft/ratelimit
    command: go build -o /usr/local/bin/ratelimit /go/src/github.com/lyft/ratelimit/src/service_cmd/main.go
    volumes:
      - .:/go/src/github.com/lyft/ratelimit
      - binary:/usr/local/bin/

  ratelimit:
    image: alpine:3.6
    command: /usr/local/bin/ratelimit
    ports:
      - 8080:8080
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
      - ratelimit-build
    networks:
      - ratelimit-network
    volumes:
      - binary:/usr/local/bin/
      - ./examples:/data
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit

networks:
  ratelimit-network:

volumes:
  binary:

```

```
---
// rate limit configure
domain: apis
descriptors:
  - key: generic_key
    value: default
    rate_limit:
      unit: minute
      requests_per_unit: 1
```


Please help me. Or I have to call police.... @junr03 @htuch CC
