### ISSUE TITLE
why the transcoding_filter could not find service in the proto descriptor

### ISSUE THREAD

**Issue by developersPHP** [envoyproxy/envoy#6999]
## the envoy config like this:
```
                always_print_primitive_fields: true
                                                                                                      32,17         31%
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: main-listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 51051 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/", grpc: {} }
                route: { cluster: grpc-backend-services, timeout: { seconds: 60 } }
          http_filters:
          - name: envoy.grpc_json_transcoder
            config:
              proto_descriptor: "/data/reservation_service_definition.pb"
              services: ["reservations.ReservationService"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
          - name: envoy.router

  clusters:
  - name: grpc-backend-services
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
```
### when i use docker to run envoy like this
```
docker run -it --rm --name envoy --network="host" -v "reservation_service_definition.pb:/data/reservation_service_definition.pb:ro" -v "/vagrant_data/envoyconf/envoy.yaml:/etc/envoy/envoy.yaml:ro" envoyproxy/envoy
```
i will be error and the error info is "[2019-05-18 10:37:41.192][1][critical][main] [source/server/server.cc:90] error initializing configuration '/etc/envoy/envoy.yaml': transcoding_filter: Could not find 'reservations.ReservationService' in the proto descriptor
[2019-05-18 10:37:41.194][1][info][main] [source/server/server.cc:522] exiting
transcoding_filter: Could not find 'reservations.ReservationService' in the proto descriptor
failed to resize tty, using default size"

### i generate a descriptor file like this 
"protoc -I. -I/Users/liufuhong/TTProject-study/tt-smdb/envoymesher/proto/third_party/googleapis --include_imports --include_source_info --descriptor_set_out=./reservation_service_definition.pb --go_out=plugins=grpc:. ./reservation_service.proto"

### my proto file like this 
```
syntax = "proto3";

package reservations;

import "google/api/annotations.proto";

service ReservationService {
    rpc CreateReservation(CreateReservationRequest) returns (Reservation) {
        option (google.api.http) = {
            post: "/v1/reservations"
            body: "reservation"
         };
    }
    rpc GetReservation(GetReservationRequest) returns (Reservation) {
        option (google.api.http) = {
            get: "/v1/reservations/{id}"
        };
    }
}

message Reservation {
    string id = 1;
    string title = 2;
    string venue = 3;
    string room = 4;
    string timestamp = 5;
    repeated Person attendees = 6;
}

message Person {
    string ssn = 1;
    string firstName = 2;
    string lastName = 3;
}

message CreateReservationRequest {
    Reservation reservation = 1;
}

message CreateReservationResponse {
    Reservation reservation = 1;
}

```
