### ISSUE TITLE
Envoy does not seem to respect SDS load balancing weights with HTTP2 (GRPC)

### ISSUE THREAD

**Issue by owais** [envoyproxy/envoy#7004]
*Title*: *Load balancing weights not working as expected with GRPC (HTTP2)*

*Description*:
I'm deploying Envoy as an edge proxy to load balance GRPC traffic but am not able to get it to load balance correctly between a set of GRPC endpoints.  It looks like the connections are causing session affinity between the clients and the servers and Envoy is not able re-balance properly once the connections are established.

As a workaround and to test Envoy's behavior, I implemented a simple EDS service that returns a set of GRPC endpoints to Envoy. To simulate an extreme case, the service returns five endpoints. 
- The first endpoint has load balancing weight set to `128` while the rest have it set to `1`. 
- Envoy picks this up and as expected starts sending all requests to the first endpoint.
- After a few minutes, I reverse the order of the endpoints in the EDS service so that the last service is assigned a weight of 128 and the first one is set to `1` along with the others.
- Envoy picks up the new config just fine but struggles to re-balance the load. 
- After waiting for a few seconds to a couple of minutes, the new endpoint starts receiving some traffic while the old one continues to receive majority of the traffic. The balance changes from 100:0 to approximately 80:20 while as the expected change was supposed to be 0:100.
- If Envoy is restarted, it correctly balances the traffic as expected.
- If clients (service sending data to Envoy) are restarted, Envoy again is able to re-balance immediately.
- Clients can only see Envoy's IP and cannot connect to any of the servers directly.
- This is end to end GRPC, not GRPC web or some other bridge.
- *Note*: The test was performed with connection pooling disabled by setting `max_requests_per_connection` to `1` which isn't too reasonable to do in production. Without this, Envoy takes much much longer to respond to the endpoint weight change and the end result is even worse.

I know this is an unrealistic simulation but I wanted to understand Envoy's LB behavior better to be able to load balance a real GRPC workload better. In the real workload, the endpoint with the most traffic often receives 10-20x more traffic than the one with the least traffic. 

I was hoping using an SDS that dynamically returned LB weights based on performance/traffic metrics exposed by the upstream service would solve the issue for us but looks like the weights don't have as much of an effect as I was expecting with long-lived connections.

*Config:*
```
    node:
      id: id_1
      cluster: test_cluster
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8000
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              codec_type: auto
              stat_prefix: ingress_http
              access_log:
              - name: envoy.file_access_log
                config:
                  path: "/dev/stdout"
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: ""
                    route:
                      cluster: grpc_cluster
              http_filters:
              - name: envoy.router
                typed_config: {}
      clusters:
      - name: grpc_cluster
        connect_timeout: 0.25s
        type: EDS
        lb_policy: ROUND_ROBIN
        # lb_policy: LEAST_REQUEST
        http2_protocol_options: {}
        max_requests_per_connection: 1
        eds_cluster_config:
          eds_config:
            api_config_source:
              api_type: REST
              cluster_names: [xds_cluster]
              refresh_delay: 1s

      - name: xds_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        upstream_connection_options:
          tcp_keepalive: {}
        load_assignment:
          cluster_name: 0.0.0.0
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: eds-service-address
                    port_value: 3000
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
```

*Initial cluster info*
```
xds_cluster::default_priority::max_connections::1024
xds_cluster::default_priority::max_pending_requests::1024
xds_cluster::default_priority::max_requests::1024
xds_cluster::default_priority::max_retries::3
xds_cluster::high_priority::max_connections::1024
xds_cluster::high_priority::max_pending_requests::1024
xds_cluster::high_priority::max_requests::1024
xds_cluster::high_priority::max_retries::3
xds_cluster::added_via_api::false
xds_cluster::100.67.222.139:3000::cx_active::1
xds_cluster::100.67.222.139:3000::cx_connect_fail::0
xds_cluster::100.67.222.139:3000::cx_total::1
xds_cluster::100.67.222.139:3000::rq_active::0
xds_cluster::100.67.222.139:3000::rq_error::0
xds_cluster::100.67.222.139:3000::rq_success::44
xds_cluster::100.67.222.139:3000::rq_timeout::0
xds_cluster::100.67.222.139:3000::rq_total::44
xds_cluster::100.67.222.139:3000::health_flags::healthy
xds_cluster::100.67.222.139:3000::weight::1
xds_cluster::100.67.222.139:3000::region::
xds_cluster::100.67.222.139:3000::zone::
xds_cluster::100.67.222.139:3000::sub_zone::
xds_cluster::100.67.222.139:3000::canary::false
xds_cluster::100.67.222.139:3000::success_rate::-1
grpc_cluster::default_priority::max_connections::1024
grpc_cluster::default_priority::max_pending_requests::1024
grpc_cluster::default_priority::max_requests::1024
grpc_cluster::default_priority::max_retries::3
grpc_cluster::high_priority::max_connections::1024
grpc_cluster::high_priority::max_pending_requests::1024
grpc_cluster::high_priority::max_requests::1024
grpc_cluster::high_priority::max_retries::3
grpc_cluster::added_via_api::false

======  receives all the traffic as weight is set to 128 ======
grpc_cluster::100.103.223.47:9000::cx_active::13
grpc_cluster::100.103.223.47:9000::cx_connect_fail::0
grpc_cluster::100.103.223.47:9000::cx_total::89
grpc_cluster::100.103.223.47:9000::rq_active::8
grpc_cluster::100.103.223.47:9000::rq_error::151
grpc_cluster::100.103.223.47:9000::rq_success::0
grpc_cluster::100.103.223.47:9000::rq_timeout::0
grpc_cluster::100.103.223.47:9000::rq_total::159
grpc_cluster::100.103.223.47:9000::health_flags::healthy
grpc_cluster::100.103.223.47:9000::weight::128
grpc_cluster::100.103.223.47:9000::region::
grpc_cluster::100.103.223.47:9000::zone::
grpc_cluster::100.103.223.47:9000::sub_zone::
grpc_cluster::100.103.223.47:9000::canary::false
grpc_cluster::100.103.223.47:9000::success_rate::-1
====== ======

grpc_cluster::100.113.244.100:9000::cx_active::0
grpc_cluster::100.113.244.100:9000::cx_connect_fail::0
grpc_cluster::100.113.244.100:9000::cx_total::0
grpc_cluster::100.113.244.100:9000::rq_active::0
grpc_cluster::100.113.244.100:9000::rq_error::0
grpc_cluster::100.113.244.100:9000::rq_success::0
grpc_cluster::100.113.244.100:9000::rq_timeout::0
grpc_cluster::100.113.244.100:9000::rq_total::0
grpc_cluster::100.113.244.100:9000::health_flags::healthy
grpc_cluster::100.113.244.100:9000::weight::1
grpc_cluster::100.113.244.100:9000::region::
grpc_cluster::100.113.244.100:9000::zone::
grpc_cluster::100.113.244.100:9000::sub_zone::
grpc_cluster::100.113.244.100:9000::canary::false
grpc_cluster::100.113.244.100:9000::success_rate::-1
grpc_cluster::100.117.74.221:9000::cx_active::0
grpc_cluster::100.117.74.221:9000::cx_connect_fail::0
grpc_cluster::100.117.74.221:9000::cx_total::0
grpc_cluster::100.117.74.221:9000::rq_active::0
grpc_cluster::100.117.74.221:9000::rq_error::0
grpc_cluster::100.117.74.221:9000::rq_success::0
grpc_cluster::100.117.74.221:9000::rq_timeout::0
grpc_cluster::100.117.74.221:9000::rq_total::0
grpc_cluster::100.117.74.221:9000::health_flags::healthy
grpc_cluster::100.117.74.221:9000::weight::1
grpc_cluster::100.117.74.221:9000::region::
grpc_cluster::100.117.74.221:9000::zone::
grpc_cluster::100.117.74.221:9000::sub_zone::
grpc_cluster::100.117.74.221:9000::canary::false
grpc_cluster::100.117.74.221:9000::success_rate::-1
grpc_cluster::100.117.95.31:9000::cx_active::0
grpc_cluster::100.117.95.31:9000::cx_connect_fail::0
grpc_cluster::100.117.95.31:9000::cx_total::0
grpc_cluster::100.117.95.31:9000::rq_active::0
grpc_cluster::100.117.95.31:9000::rq_error::0
grpc_cluster::100.117.95.31:9000::rq_success::0
grpc_cluster::100.117.95.31:9000::rq_timeout::0
grpc_cluster::100.117.95.31:9000::rq_total::0
grpc_cluster::100.117.95.31:9000::health_flags::healthy
grpc_cluster::100.117.95.31:9000::weight::1
grpc_cluster::100.117.95.31:9000::region::
grpc_cluster::100.117.95.31:9000::zone::
grpc_cluster::100.117.95.31:9000::sub_zone::
grpc_cluster::100.117.95.31:9000::canary::false
grpc_cluster::100.117.95.31:9000::success_rate::-1
grpc_cluster::100.98.71.46:9000::cx_active::0
grpc_cluster::100.98.71.46:9000::cx_connect_fail::0
grpc_cluster::100.98.71.46:9000::cx_total::0
grpc_cluster::100.98.71.46:9000::rq_active::0
grpc_cluster::100.98.71.46:9000::rq_error::0
grpc_cluster::100.98.71.46:9000::rq_success::0
grpc_cluster::100.98.71.46:9000::rq_timeout::0
grpc_cluster::100.98.71.46:9000::rq_total::0
grpc_cluster::100.98.71.46:9000::health_flags::healthy
grpc_cluster::100.98.71.46:9000::weight::1
grpc_cluster::100.98.71.46:9000::region::
grpc_cluster::100.98.71.46:9000::zone::
grpc_cluster::100.98.71.46:9000::sub_zone::
grpc_cluster::100.98.71.46:9000::canary::false
grpc_cluster::100.98.71.46:9000::success_rate::-1
```

*Cluster Info after LB weight reversal in EDS*
```
xds_cluster::default_priority::max_connections::1024
xds_cluster::default_priority::max_pending_requests::1024
xds_cluster::default_priority::max_requests::1024
xds_cluster::default_priority::max_retries::3
xds_cluster::high_priority::max_connections::1024
xds_cluster::high_priority::max_pending_requests::1024
xds_cluster::high_priority::max_requests::1024
xds_cluster::high_priority::max_retries::3
xds_cluster::added_via_api::false
xds_cluster::100.67.222.139:3000::cx_active::1
xds_cluster::100.67.222.139:3000::cx_connect_fail::1
xds_cluster::100.67.222.139:3000::cx_total::3
xds_cluster::100.67.222.139:3000::rq_active::0
xds_cluster::100.67.222.139:3000::rq_error::1
xds_cluster::100.67.222.139:3000::rq_success::246
xds_cluster::100.67.222.139:3000::rq_timeout::0
xds_cluster::100.67.222.139:3000::rq_total::246
xds_cluster::100.67.222.139:3000::health_flags::healthy
xds_cluster::100.67.222.139:3000::weight::1
xds_cluster::100.67.222.139:3000::region::
xds_cluster::100.67.222.139:3000::zone::
xds_cluster::100.67.222.139:3000::sub_zone::
xds_cluster::100.67.222.139:3000::canary::false
xds_cluster::100.67.222.139:3000::success_rate::-1
grpc_cluster::default_priority::max_connections::1024
grpc_cluster::default_priority::max_pending_requests::1024
grpc_cluster::default_priority::max_requests::1024
grpc_cluster::default_priority::max_retries::3
grpc_cluster::high_priority::max_connections::1024
grpc_cluster::high_priority::max_pending_requests::1024
grpc_cluster::high_priority::max_requests::1024
grpc_cluster::high_priority::max_retries::3
grpc_cluster::added_via_api::false

====== Still has more connections open even though weight has changed to 1 ======
grpc_cluster::100.103.223.47:9000::cx_active::4
grpc_cluster::100.103.223.47:9000::cx_connect_fail::0
grpc_cluster::100.103.223.47:9000::cx_total::140
grpc_cluster::100.103.223.47:9000::rq_active::4
grpc_cluster::100.103.223.47:9000::rq_error::247
grpc_cluster::100.103.223.47:9000::rq_success::0
grpc_cluster::100.103.223.47:9000::rq_timeout::0
grpc_cluster::100.103.223.47:9000::rq_total::251
grpc_cluster::100.103.223.47:9000::health_flags::healthy
grpc_cluster::100.103.223.47:9000::weight::1
grpc_cluster::100.103.223.47:9000::region::
grpc_cluster::100.103.223.47:9000::zone::
grpc_cluster::100.103.223.47:9000::sub_zone::
grpc_cluster::100.103.223.47:9000::canary::false
grpc_cluster::100.103.223.47:9000::success_rate::-1
============

grpc_cluster::100.113.244.100:9000::cx_active::0
grpc_cluster::100.113.244.100:9000::cx_connect_fail::0
grpc_cluster::100.113.244.100:9000::cx_total::4
grpc_cluster::100.113.244.100:9000::rq_active::0
grpc_cluster::100.113.244.100:9000::rq_error::4
grpc_cluster::100.113.244.100:9000::rq_success::0
grpc_cluster::100.113.244.100:9000::rq_timeout::0
grpc_cluster::100.113.244.100:9000::rq_total::4
grpc_cluster::100.113.244.100:9000::health_flags::healthy
grpc_cluster::100.113.244.100:9000::weight::1
grpc_cluster::100.113.244.100:9000::region::
grpc_cluster::100.113.244.100:9000::zone::
grpc_cluster::100.113.244.100:9000::sub_zone::
grpc_cluster::100.113.244.100:9000::canary::false
grpc_cluster::100.113.244.100:9000::success_rate::-1
grpc_cluster::100.117.74.221:9000::cx_active::0
grpc_cluster::100.117.74.221:9000::cx_connect_fail::0
grpc_cluster::100.117.74.221:9000::cx_total::4
grpc_cluster::100.117.74.221:9000::rq_active::0
grpc_cluster::100.117.74.221:9000::rq_error::4
grpc_cluster::100.117.74.221:9000::rq_success::0
grpc_cluster::100.117.74.221:9000::rq_timeout::0
grpc_cluster::100.117.74.221:9000::rq_total::4
grpc_cluster::100.117.74.221:9000::health_flags::healthy
grpc_cluster::100.117.74.221:9000::weight::1
grpc_cluster::100.117.74.221:9000::region::
grpc_cluster::100.117.74.221:9000::zone::
grpc_cluster::100.117.74.221:9000::sub_zone::
grpc_cluster::100.117.74.221:9000::canary::false
grpc_cluster::100.117.74.221:9000::success_rate::-1
grpc_cluster::100.117.95.31:9000::cx_active::3
grpc_cluster::100.117.95.31:9000::cx_connect_fail::0
grpc_cluster::100.117.95.31:9000::cx_total::3
grpc_cluster::100.117.95.31:9000::rq_active::3
grpc_cluster::100.117.95.31:9000::rq_error::0
grpc_cluster::100.117.95.31:9000::rq_success::0
grpc_cluster::100.117.95.31:9000::rq_timeout::0
grpc_cluster::100.117.95.31:9000::rq_total::3
grpc_cluster::100.117.95.31:9000::health_flags::healthy
grpc_cluster::100.117.95.31:9000::weight::1
grpc_cluster::100.117.95.31:9000::region::
grpc_cluster::100.117.95.31:9000::zone::
grpc_cluster::100.117.95.31:9000::sub_zone::
grpc_cluster::100.117.95.31:9000::canary::false
grpc_cluster::100.117.95.31:9000::success_rate::-1

====== Has weight set to 128 but receives much less traffic  ======
grpc_cluster::100.98.71.46:9000::cx_active::1
grpc_cluster::100.98.71.46:9000::cx_connect_fail::0
grpc_cluster::100.98.71.46:9000::cx_total::4
grpc_cluster::100.98.71.46:9000::rq_active::1
grpc_cluster::100.98.71.46:9000::rq_error::7
grpc_cluster::100.98.71.46:9000::rq_success::0
grpc_cluster::100.98.71.46:9000::rq_timeout::0
grpc_cluster::100.98.71.46:9000::rq_total::8
grpc_cluster::100.98.71.46:9000::health_flags::healthy
grpc_cluster::100.98.71.46:9000::weight::128
grpc_cluster::100.98.71.46:9000::region::
grpc_cluster::100.98.71.46:9000::zone::
grpc_cluster::100.98.71.46:9000::sub_zone::
grpc_cluster::100.98.71.46:9000::canary::false
grpc_cluster::100.98.71.46:9000::success_rate::-1
=========
```

![2019-05-20_04-32](https://user-images.githubusercontent.com/46186/57989535-8b881300-7ab9-11e9-9e39-18a0e2129571.png)

The graph shows almost no change when connection pooling is not disabled.
