### ISSUE TITLE
TLS and SNI for TCP proxy connections

### ISSUE THREAD

**Issue by chintan-mishra** [envoyproxy/envoy#7066]
### Description
> While connecting via protocols other than HTTP(say MQTT), the method for TLS termination/origination and SNI are not well documented. This is helpful when we have to manage a TCP proxy. Allowing us to use domain/server name instead of IPs all the while ensuring our connection cannot be snooped.

<details>
<summary>Here is the config with which we can connect with upstream TCP proxy using IP, port</summary>

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 127.0.0.1
      port_value: 9901
static_resources:
  listeners:
  ##- name: listener_other
  - name: listener_mqtt
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 1883
    # listener_filters:
    # - name: "envoy.listener.tls_inspector"
      # config: {}
    filter_chains:
    # - filter_chain_match: 
        # server_names: ["dev.8hoot.com"]
        # transport_protocol: tls
        # application_protocols: []
      # tls_context:
        # common_tls_context:
          # tls_certificates:
          # - certificate_chain:
              # filename: "./docker_volume_path/cert.pem"
            # private_key:
              # filename: "./docker_volume_path/privkey.pem"
      filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: vernemq
          cluster: service_mqtt

  clusters:
  ##- name: service_other
  - name: service_mqtt
    connect_timeout: 0.25s
    type: STATIC
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_mqtt
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 172.17.0.10
                port_value: 1883
```
</details>

### Other relevant details

- The above configuration allows connecting with the upstream TCP connection using IP. Connecting with MQTT server behind Envoy's TCP proxy looks like this
    ```shell
    $ export HOST='1.1.1.1' # any IP
    $ mosquitto_pub -h ${HOST} -p 1883 -t topic -m payload -q 2 -d
    ```
- With the help SNI we will be able to connect with the TCP proxy using domain names instead. It would look like this
    ```shell
    $ export HOST='test.mosquitto.org' # any domain/server name
    $ mosquitto_pub -h ${HOST} -p 1883 -t topic -m payload -q 2 -d
    ```
- Further TLS temination/origination will allow securing TCP proxy connection between client and Envoy.

- Comments with single `#` are what I tried for implementing TLS and SNI.

**Comment by chintan-mishra** [comment]
Evidently, SNI works when it has been set in the nameserver settings and **no changes are required in Envoy's config**. However, TLS for TCP is still bugging me. I will update this if I make further discoveries.

**Comment by alochym01** [comment]
> Evidently, SNI works when it has been set in the nameserver settings and **no changes are required in Envoy's config**. However, TLS for TCP is still bugging me. I will update this if I make further discoveries.

any news information?? i had same issue

**Comment by chintan-mishra** [comment]
I made no discoveries. Still facing the same issue.

**Comment by alochym01** [comment]
@chintan-mishra i got working and i use 

```
[root@localhost envoy]# envoy --version

envoy  version: 845923714078e5a3528e85d4b58f2cc95850a1c6/1.8.0-dev/Distribution/RELEASE
```
running envoy check configured file
```
[root@localhost envoy]# envoy -c envoy-apiqueue-mqtt.yaml --mode validate
[2019-08-03 13:17:51.011][5539][info][config] source/server/configuration_impl.cc:50] loading 0 static secret(s)
[2019-08-03 13:17:51.013][5539][info][upstream] source/common/upstream/cluster_manager_impl.cc:133] cm init: all clusters initialized
[2019-08-03 13:17:51.013][5539][info][config] source/server/configuration_impl.cc:60] loading 2 listener(s)
[2019-08-03 13:17:51.110][5539][warning][config] source/server/listener_manager_impl.cc:257] adding listener 'x.x.x.x:8883': filter chain match rules require TLS Inspector listener filter, but it isn't configured, trying to inject it (this might fail if Envoy is compiled without it)
[2019-08-03 13:17:51.110][5539][info][config] source/server/configuration_impl.cc:94] loading tracing configuration
[2019-08-03 13:17:51.110][5539][info][config] source/server/configuration_impl.cc:116] loading stats sink configuration
configuration 'envoy-apiqueue-mqtt.yaml' OK

```

my envoy config
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: your_public_ip
        port_value: 8883
      listener_filters:
      - name: "envoy.listener.tls_inspector"
        config: {}
    filter_chains:
    - filter_chain_match:
        server_names: ["yourdomain"]
        transport_protocol: tls
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: mqtt_server
          cluster: mqtt_server
      tls_context:
        common_tls_context:
          tls_certificates:
            certificate_chain: {filename: "/etc/ssl/certs/certificate.cert"}
            private_key: {filename: "/etc/ssl/private/private.key"}
  clusters:
  - name: mqtt_server
    connect_timeout: 0.25s
    type: STATIC
    lb_policy: round_robin
    load_assignment:
      cluster_name: mqtt_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: x.x.x.x
                port_value: 1883
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000
```
my mqtt config
```
user mosquitto

pid_file /var/run/mosquitto/mosquitto.pid

#bind_address localhost

autosave_interval 3600
autosave_on_changes false
persistence true
persistence_file mosquitto.db
persistence_location /mnt/ssd/mosquitto/

#connection_messages false
allow_anonymous false
clientid_prefixes xxx-

listener 1883 your_ip_address

listener 9001
protocol websockets

auth_plugin /etc/mosquitto/libs/auth-plug.so
auth_opt_backends http
auth_opt_acl_cacheseconds 0
auth_opt_auth_cacheseconds 0
auth_opt_acl_cachejitter 0
auth_opt_auth_cachejitter 0

#HTTP
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 8002
auth_opt_http_getuser_uri /queue/auth
auth_opt_http_superuser_uri /queue/superuser
auth_opt_http_aclcheck_uri /queue/acl
auth_opt_http_with_tls false
```

hope it helps
