### ISSUE TITLE
thrift-request blocked when restart client

### ISSUE THREAD

**Issue by pyrl247** [envoyproxy/envoy#7085]
I used thrift server as envoy upstream and thrift client as envoy downstream.
here is my yaml:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      protocol: TCP
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.thrift_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.thrift_proxy.v2alpha1.ThriftProxy
          transport: UNFRAMED
          protocol: BINARY
          stat_prefix: ingress_proxy
          route_config:
            name: local_route
            routes:
            - match:
                method_name: ping
              route:
                cluster: service_thrift
          thrift_filters:
            name: envoy.filters.thrift.router

  clusters:
  - name: service_thrift
    connect_timeout: 0.25s
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_thrift
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.4.44.88
                port_value: 9999
```
When I stop the client , the connection between server and envoy will not release.Is that correct?
And when I start the client again ,it block the thrift request.
