### ISSUE TITLE
Multiple RDS resources

### ISSUE THREAD

**Issue by fttyX** [envoyproxy/envoy#7107]
Is it possible to have multiple RDS resources?

I tried to feed envoy with 2 RDS resources (with different names) and got: "REST config update rejected: Unexpected RDS resource length: 2" error.

Checked source code and found this:
https://github.com/envoyproxy/envoy/blob/73c46c9aba2c032f8fccb32e1b2c0c7a1df25a8d/source/common/router/rds_impl.cc#L163

>   if (num_resources != 1) {
>     throw EnvoyException(fmt::format("Unexpected RDS resource length: {}", num_resources));
>     // (would be a return false here)
>   }
>   return true;

Any reason for that?

In my configuration I need to have different set of routes for http and https listeners. Maybe there's some other way to get that and i'm going the wrong way?

Thanks.

**Comment by htuch** [comment]
@fttyX what do you mean by multiple RDS resources here? Each listener can only take a single RDS subscription.

**Comment by fttyX** [comment]
@htuch is it possible to subscribe each listener to different RDS resource? To have different routes/domains for http and https listeners, for example.

**Comment by htuch** [comment]
Yes, but as it works today, I think each listener will open up its own independent RDS request for REST. You should reply back to Envoy with the requested resources in your management server.

**Comment by fttyX** [comment]
Thanks!

**Comment by htuch** [comment]
@calegari-adriano this seems unrelated, maybe a new issue? I don't see a priori how the choice of codec would affect RDS loading, they are independent in implementation.

**Comment by calegari-adriano** [comment]
Yes, new issue.

Not only code, but HTTP3 (UDP) listener in specific, with HTTP2 (TCP) there is no issue.
```yaml
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http-udp
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 443
      protocol: UDP
  ```

**Comment by calegari-adriano** [comment]
Yes, that it is a new issue, I think. It is better to create a new one.

In that issue, I used the: https://www.getenvoy.io/
getenvoy standard:1.18.2/linux-glibc

I think: I did a wrong configuration or envoy has a issue or the getenvoy envoy build has a issue.

Not codec only, but HTTP3 (UDP) listener in specific, with HTTP2 (TCP) there is no issue.

In the example below, the http-udp listener only works when the dummy-for-http-udp exists.

```yaml
version_info: "3"
resources:
- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: http-udp
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 443
      protocol: UDP
  reuse_port: true
  udp_listener_config:
    quic_options: {}
    downstream_socket_config:
      prefer_gro: true
  filter_chains:
  - filter_chain_match:
      transport_protocol: quic  
      server_names:
        - www.example.com
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
        downstream_tls_context:
          common_tls_context:
            alpn_protocols: h3
            tls_params: 
              tls_minimum_protocol_version: TLSv1_3
            tls_certificates:          
              certificate_chain:
                filename: /envoy-tls/fullchain.crt
              private_key:
                filename: /envoy-tls/tls.key 
    filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager        
        codec_type: HTTP3           

        http3_protocol_options: {}  

        rds:
          route_config_name: main
          config_source:
            resource_api_version: V3
            path: /envoy-config/rds.yaml
        http_filters:
        - name: envoy.filters.http.router        

- "@type": type.googleapis.com/envoy.config.listener.v3.Listener
  name: dummy-for-http-udp
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 444 
  filter_chains:  
  - filter_chain_match:
      server_names:
        - www.example.com
    transport_socket:
      name: envoy.transport_sockets.quic
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.transport_sockets.quic.v3.QuicDownstreamTransport
        downstream_tls_context:
          common_tls_context:
            alpn_protocols: h2
            tls_params: 
              tls_minimum_protocol_version: TLSv1_2
            tls_certificates:          
              certificate_chain:
                filename: /envoy-tls/fullchain.crt
              private_key:
                filename: /envoy-tls/tls.key 
    filters:
    - name: envoy.filters.network.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager        
        codec_type: HTTP2

        rds: # same rds confing of the http-udp (hack)
          route_config_name: main
          config_source:
            resource_api_version: V3
            path: /envoy-config/rds.yaml 
        http_filters:
        - name: envoy.filters.http.router
```
