### ISSUE TITLE
Opportunistic encryption for downstream envoy

### ISSUE THREAD

**Issue by crazyxy** [envoyproxy/envoy#7135]
I was wondering if would there be interest in adding opportunistic encryption to envoy?

**Description**:
When downstream envoy tries to connect to upstream hosts, the downstream envoy is able to select the connection to be encrypted (TLS) or not (plain text) according to existence the `tls_context`. If one of the load balance endpoints doesn't support TLS connection, it will return 503 when picking that endpoint. For example:

Downstream envoy:
```yaml
clusters:
  - name: proxy
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: proxy
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address: 
                address: proxy
                port_value: 80
        - endpoint:
            address:
              socket_address:
                address: proxy
                port_value: 443
    tls_context: {}
```

One of the endpoint doesn't support TLS connection:
```yaml
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
      ...
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
      ...
      tls_context:
        common_tls_context:
          tls_certificates:
          - certificate_chain:
              filename: /etc/cert.pem
            private_key:
              filename: /etc/key.pem
          validation_context: {}
```

50% of the requests will fail with 503 due to the connection to `proxy:80` cannot be established. 

Applying opportunistic encryption could resolve this problem. Downstream envoy can try to establish TLS connection first, if it fails, it will fall back to use plain text connection.

**Details**
The opportunistic encryption is only available when `tls_context` is provided in upstream tls context. (*If upstream tls context is not provided, the client will use plain text connection directly*). When `tls_context` is provided, downstream envoy can config the mode to be either `Permissive` or `Strict`. Under `Permissive` mode, the downstream envoy will try TLS connection first and fall back to plain text connection if the first trial fails. Under `Strict` mode, the downstream envoy will try TLS connection only.

cc @louiscryan @duderino
