### ISSUE TITLE
unhealthy_threshold not respected with active health check

### ISSUE THREAD

**Issue by mirek-stripe** [envoyproxy/envoy#7171]
*Description*:

We have an envoy cluster with an active HTTP health check and `unhealthy_threshold = 3`. We noticed that when the healthcheck endpoint returns 404, the host is _immediately_ marked unhealthy, ignoring `unhealthy_threshold`. This can be easily reproduced with any status code other than 200.

The docs for `unhealthy_threshold` say: 
> The number of unhealthy health checks required before a host is marked unhealthy. Note that for http health checking if a host responds with 503 this threshold is ignored and the host is considered unhealthy immediately."

This implies that 404 from an active health check should not cause immediate health change. But that is not the case - the implementation in [health_checker_base_impl.cc](https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/health_checker_base_impl.cc#L311) suggests that `unhealthy_threshold` is only considered for `HealthCheckFailureType::NETWORK` (ie status code does not matter).

What is the indented behavior? Is there currently a way to configure `unhealthy_threshold` for active HTTP health check? (similar to haproxy's `fall`?)

*Repro steps*:

Run a simple service that fails every 5th health check call, like
```
from flask import Flask, request
app = Flask(__name__)
hc = 0

@app.route('/healthcheck')
def healthcheck():
  global hc
  hc += 1
  result = [200, 200, 200, 200, 400][hc % 5]
  return "Health check returning status {}\n".format(result), result

if __name__ == "__main__":
  app.run(host='0.0.0.0', port=8080, debug=True, threaded=True)
```

Use the envoy config below and observe that health changes immediately after the first 400.

*Config*:

```
static_resources:
  clusters:
    - name: test-service
      lb_policy: round_robin
      type: strict_dns
      connect_timeout: 1s
      hosts:
        - socket_address:
            port_value: 8080
            address: 127.0.0.1
      health_checks:
        - interval: 5s
          timeout: 5s
          no_traffic_interval: 5s
          unhealthy_threshold: 3
          healthy_threshold: 3
          http_health_check:
            path: /healthcheck
          event_log_path: /envoy_health_event.log
          always_log_health_check_failures: true
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

```

*Logs*:

Health checks calls: 
```
127.0.0.1 - - [04/Jun/2019 23:27:40] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:27:45] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:27:50] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:27:55] "GET /healthcheck HTTP/1.1" 400 -
127.0.0.1 - - [04/Jun/2019 23:28:00] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:28:05] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:28:10] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:28:15] "GET /healthcheck HTTP/1.1" 200 -
127.0.0.1 - - [04/Jun/2019 23:28:20] "GET /healthcheck HTTP/1.1" 400 -
```
Health events log: 
```
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","add_healthy_event":{"first_check":false},"timestamp":"2019-06-04T23:27:50.313Z"}
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","eject_unhealthy_event":{"failure_type":"ACTIVE"},"timestamp":"2019-06-04T23:27:55.317Z"}
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","health_check_failure_event":{"failure_type":"ACTIVE","first_check":false},"timestamp":"2019-06-04T23:27:55.317Z"}
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","add_healthy_event":{"first_check":false},"timestamp":"2019-06-04T23:28:10.296Z"}
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","eject_unhealthy_event":{"failure_type":"ACTIVE"},"timestamp":"2019-06-04T23:28:20.304Z"}
{"health_checker_type":"HTTP","host":{"socket_address":{"protocol":"TCP","address":"127.0.0.1","resolver_name":"","ipv4_compat":false,"port_value":8080}},"cluster_name":"test-service","health_check_failure_event":{"failure_type":"ACTIVE","first_check":false},"timestamp":"2019-06-04T23:28:20.304Z"}
```
At `23:27:55`, healthcheck call fails and the host is immediately removed. At `23:28:10`, third consecutive healthcheck call succeeds and the host is put back as expected.
