### ISSUE TITLE
Is it possible to use an NFS mounted file as dynamic configuration?

### ISSUE THREAD

**Issue by deoxyszc** [envoyproxy/envoy#7319]
I'm using evoy v1.10.0
![image](https://user-images.githubusercontent.com/45086445/59741884-db1b5380-929e-11e9-90bf-c3549492c4b5.png)

I wrote an xds configuration file below:
```
node: {cluster: systemF-envoy, id: systemF-envoy}
tracing:
  http:
    name: envoy.zipkin
    config: {collector_endpoint: /api/v1/spans, collector_cluster: zipkin}
dynamic_resources:
  cds_config: {path: /envoy/config/cds.yaml}
  lds_config: {path: /envoy/config/lds.yaml}
admin:
  address:
    socket_address: {address: 0.0.0.0, port_value: 9901}
  access_log_path: /envoy/admin_access.log
static_resources:
  clusters:
  - name: zipkin
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: zipkin
        port_value: 9411
```
The path `/envoy/` is a mounted NFS path.

When I modify the `.yaml` files on the NFS client, which envoy is running on, envoy will reload the configuration correctly; but if the files are modified on the NFS server, envoy couldn't reload the configuration.

I checked for the code, envoy is using `kevent` to get filesystem events. After googled several websites, it seemed that the `kevent` could not get events in mounted NFS.

My questions are, is it possible to use an NFS mounted file as dynamic configuration? If so, how to do that? Thanks a lot!~
