### ISSUE TITLE
Question: Filter chain not matching on expected criteria

### ISSUE THREAD

**Issue by bcelenza** [envoyproxy/envoy#7341]
**Bug Template**

*Title*:  Expected filter chain match is not made

*Description*:

Consider the following listener configuration:

```
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 15001
      filter_chains:
      - filter_chain_match:
          destination_port: 443
          server_names:
          - "*.foo.com"
        filters:
        - name: envoy.tcp_proxy
          config:
            stat_prefix: egress
            cluster: foo
      - filter_chain_match:
          prefix_ranges:
          - address_prefix: 0.0.0.0
            prefix_len: 0
        filters:
        - name: envoy.tcp_proxy
          config:
            stat_prefix: egress
            cluster: bar
      listener_filters:
      - name: envoy.listener.original_dst
      - name: envoy.listener.tls_inspector
```

The clusters in this example are both simple original destination clusters (and could conceivably be the same cluster).

If I send an HTTP request to `https://somewhere.foo.com:443`, the request succeeds as expected. However if I send an HTTP request to `https://bar.com:443`, Envoy rejects the request with:

> [source/server/connection_handler_impl.cc:231] closing connection: no matching filter chain found

The [filter chain match documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener/listener.proto) states:

> In order for a filter chain to be selected, ALL of its criteria must be fulfilled by the incoming connection, properties of which are set by the networking stack and/or listener filters.

My understanding is the second example request should match on the filter chain match for all destination addresses (0.0.0.0/0), but this does not occur, and Envoy claims no match is made. However, if I remove the first filter chain match (443 for *.foo.com), the match is made and the request processed as expected.

I have verified this behavior in Envoy 1.9.0 and 1.9.1.

Is this expected behavior for Envoy?
