### ISSUE TITLE
Enabling ext_authz and setting max_request_body enables buffering globally, even where exluded

### ISSUE THREAD

**Issue by virtru-tdewitt** [envoyproxy/envoy#7404]
*Title*: Enabling ext_authz and setting `max_request_body` enables buffering globally, even where exluded

*Description*:
Using `max_request_bytes` with the `envoy.ext_authz` filter enables buffering.  Even where the filter is explicitly disabled, buffering is enabled and `max_request_body` appears to be respected.

*Relevant Links*:

This seems like it could be related:
* https://github.com/envoyproxy/envoy/issues/5513

*Repro steps*:
PUTs to the `/encrypted_storate` route (see config below) with payloads exceeding `max_request_body` response with "413 (Payload Too Large)".  

*Config*:
Calls to the `/encrypted_storage` route have `max_request_body` applied.
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          redirect:
                            https_redirect: true
                http_filters:
                  - name: envoy.router
                    config: {}
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/dev/stdout"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/accounts/"
                          route:
                            cluster: accounts
                            prefix_rewrite: "/"

                        - match:
                            prefix: "/encrypted-storage/"
                          route:
                            cluster: encrypted-storage
                            prefix_rewrite: "/"
                            host_rewrite: REDACTED
                          per_filter_config:
                            envoy.ext_authz:
                              disabled: true
                        - match:
                            prefix: "/encrypted-storage/"
                          route:
                            cluster: encrypted-storage
                            prefix_rewrite: "/"
                            host_rewrite: REDACTED
...[snip]...
                http_filters:
                  - name: envoy.ext_authz
                    config:
                      http_service:
                        server_uri:
                          uri: REDACTED:443
                          cluster: auth
                          timeout: 5s
                        authorization_request:
                          allowed_headers:
                            patterns:
                            - exact: Content-Type
                            - exact: auth
                            - prefix: x-envoy
                            - prefix: x-virtru
                            - prefix: :method
                            - prefix: :path
                        path_prefix: /validate
                        authorization_response:
                          allowed_upstream_headers:
                            patterns:
                            - exact: X-Virtru-User
                            - prefix: x-success
                      with_request_body:
                        max_request_bytes: 100000
                        allow_partial_message: false
                      status_on_error:
                        code: 503
                  - name: envoy.health_check
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.health_check.v2.HealthCheck
                      pass_through_mode: false
                      headers:
                        - exact_match: /haproxy_status
                          name: :path
                  - name: envoy.router
                    typed_config: {}
          tls_context:
            common_tls_context:
              tls_params:
                tls_minimum_protocol_version: TLSv1_2
              tls_certificates:
                - certificate_chain:
                    filename: /etc/envoy/ssl/ca-intermediary.pem
                  private_key:
                    filename: /etc/envoy/ssl/private.pem

clusters:

    - name: accounts
      connect_timeout: 30s
      type: strict_dns
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      dns_refresh_rate: 60s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: accounts
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                     address: REDACTED
                     port_value: 443
      tls_context:
        sni: REDACTED

    - name: encrypted-storage
      connect_timeout: 30s
      type: strict_dns
      # Comment out the following line to test on v6 networks
      dns_lookup_family: V4_ONLY
      dns_refresh_rate: 60s
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: encrypted-storage
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                     address: REDACTED
                     port_value: 443
      tls_context:
        sni: REDACTED
        common_tls_context:
          validation_context:
            trusted_ca:
              filename: /etc/ssl/certs/ca-certificates.crt
```
