### ISSUE TITLE
Authz and route config when using RDS

### ISSUE THREAD

**Issue by andye2004** [envoyproxy/envoy#7421]
Not sure if this is a question or a feature request or just a whinge really. Basically I'm looking at using RDS at the moment and realised I have an issue with extauthz.

In my current static setup I have something like this:-

```yaml
static_resources:
  listeners:
    - name: "listener"
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: httpmgr
                http_filters:
                  - name: envoy.ext_authz
                    config:
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext-authz
                  - name: envoy.router
                route_config:
                  name: web_routes
                  virtual_hosts:
                    - name: all_domains
                      domains: ["*"]
                      routes:
                        - match: { prefix: /service1 }
                          route: { cluster: service1 }
                        - match: { prefix: /service2 }
                          route: { cluster: service2 }
                          # No extauthz for this one
                          per_filter_config:
                            envoy.ext_authz:
                              disabled: true
```
If I want to use extauthz and differentiate behaviour based on routes my RDS now needs to know that an extauthz filter is in play.

What I really want to do is replace the above config with something like:-

```yaml
static_resources:
  listeners:
    - name: "listener"
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: httpmgr
                http_filters:
                  - name: envoy.ext_authz
                    config:
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext-authz
                  - name: envoy.router
                rds:
                  route_config_name: web_port
                  config_source:
                    path: /path/to/xds/rds/rds.yaml
```
and have an rds.yaml file as follows:-
```yaml
version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: wf_admin_port
    virtual_hosts:
      - name: wf_admin_port_domains
        domains: ["*"]
        routes:
          - match: { prefix: "/service1" }
            route: { cluster: service1 }
          - match: { prefix: "/service2" }
            route: { cluster: service2 }
```
To me this is much better but now both of my routes will have the extauthz filter applied to them because the per filter config is no longer there. Although this is file based RDS the same scenario will exist with a grpc based service.

So, in order to ensure the `/service2` route doesn't have the extauthz filter applied I need to have the following:-
```yaml
version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: wf_admin_port
    virtual_hosts:
      - name: wf_admin_port_domains
        domains: ["*"]
        routes:
          - match: { prefix: "/service1" }
            route: { cluster: service1 }
          - match: { prefix: "/service2" }
            route: { cluster: service2 }
            per_filter_config:
              envoy.ext_authz:
              disabled: true
```
But this now means I have configuration inside the rds file that, I believe, really doesn't belong in there and is remote from the remaining extauthz configuration.

Is there something I'm missing here or this an oversight in the design of the extauthz plugin that requires the configuration to be broken up in this way?

I'm looking at the config for this vs the config for the JWT filter where the rules section allows per route config but keeps it with the other JWT configuration.

EDITED: Provide a bit more clarity on what was being described / questioned.
