### ISSUE TITLE
Need help configuring Envoy as both a proxy and a reverse proxy

### ISSUE THREAD

**Issue by huang195** [envoyproxy/envoy#7462]
I have 2 machines, A and B. I've configured all of A's traffic to be routed to B. On B, I have Envoy running, which I'd like to use to proxy A's traffic to the outside world. Additionally, A runs a service, for which I'd like to have B to act as a reverse proxy.

I can configure Envoy to either act as a proxy or a reverse proxy, but I'm having problem configuring it acting as both at the same time. I was trying to look for examples by looking at Istio, but Istio uses xDS, and I'd like to use a static configuration, if possible.

To configure Envoy as a proxy, I use this static configuration:

```
static_resources:
  listeners:
  - name: virtual
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          stat_prefix: passthrough
          cluster: PassthroughCluster
    use_original_dst: true
  clusters:
  - name: PassthroughCluster
    type: ORIGINAL_DST
    connect_timeout: 10s
    lb_policy: ORIGINAL_DST_LB
    circuit_breakers:
      thresholds:
      - max_connections: 102400
        max_retries: 1024
```

Since I was also doing `iptables -t nat -A PREROUTING ... -j REDIRECT` similar to Istio, this worked great to have Envoy proxying tcp connection for A.

For the reverse proxy configuration, I used:

```
static_resources:
  listeners:
  - name: fortio
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          generate_request_id: false
          route_config:
            name: fortio_routes
            virtual_hosts:
            - name: fortio_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: fortio_backend
          http_filters:
          - name: envoy.router
            config:
              dynamic_stats: false
  clusters:
  - name: fortio_backend
    connect_timeout: 0.25s
    hosts:
    - socket_address:
        address: 10.100.1.1
        port_value: 8080
```

This by itself also worked great, as I was able to reach the backend service running on A via Envoy running on B. 

However, the problem is how do I combine these configurations so Envoy can do both proxying and reverse proxying at the same time? I couldn't wrap my head around how Istio does this by only having Envoy listening to 1 port (15001). Thanks!
