### ISSUE TITLE
Customize response code on upstream reset

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [envoyproxy/envoy#7537]
Hello,

we would like to customize the response code of upstream reset. Right now, we see that 503 is hardcoded in [Filter::onUpstreamReset](https://github.com/envoyproxy/envoy/blob/ecd03a4eed07e1cfea9e9844e519b7fffada437a/source/common/router/router.cc#L864)

## Motivation
**Status code**
Without Envoy, when app A was communicating with B and was not available, the A's client received connection refused. With Envoy in place, the A will receive 503 status code. We would like to differentiate this behaviour with different status code, for example 504 or 502, so our developers that this is not a problem with B itself throwing 503, but with a connection to B.

If you think that makes sense, we are ready to contribute it, but need a guidance where to put a parameters for this.

**Comment by mattklein123** [comment]
I think this is a dup of https://github.com/envoyproxy/envoy/issues/1178. Can we track there?

**Comment by jakubdyszkiewicz** [comment]
Ok, the response body part is definitely duplicate. I used search, but I guess I typed wrong keywords.

But I think the hardcoded status code is a different problem. What do you think?

**Comment by mattklein123** [comment]
Sure fair enough. Can you update the title/text to clarify that you are looking for response code customization?

**Comment by lukidzi** [comment]
You can assigne this issue  to me. Could you suggest where should I add configuration for custom code and response message?

**Comment by mattklein123** [comment]
I would take a look at the router filter configuration most likely. If we want to do this in a more general sense we could like at HTTP connection manager (HCM) level configuration for send local reply?

**Comment by lukidzi** [comment]
Ok. So I thought about structure of config and I came up with something like this:
```
http_connection_manager_config
  ...
  "http_filters": [],
  "send_local_reply_config":
      - "match" : 
            "status" : 503,
            "reason" : "remote reset"
        "rewrite" : 
            "status" : 504
  
```
I am a bit worried how to distinguish between `remote reset` and other errors at sendLocalReply(or should I check it in router.cc ?- not generic) method because we receive code and body(I can look for reason in body or maybe pass reason to sendLocalReply?).
I am not sure if it is good approach but it might be easier to extend this config for task with custom message and json format.

**Comment by mattklein123** [comment]
@lukidzi that is roughly the type of config that I have been considering also. I think we can do other things in that config such as JSON vs. text, etc.

**Comment by mattklein123** [comment]
See also https://github.com/envoyproxy/envoy/issues/6166 which is related and I would like to handle in the same config.

**Comment by euroelessar** [comment]
> I am a bit worried how to distinguish between remote reset and other errors at sendLocalReply

Can we use `StreamInfo::hasResponseFlag` method for it? (assuming the enum is somehow represented in protobuf), e.g. smth like:
```yaml
"send_local_reply_config":
- "match": 
  "status": [503],
  "response_flags":
    "all":
    - "UPSTREAM_REMOTE_RESET"
  "rewrite": 
    "status": 504
```

On a side note, we can accommodate #1178 and #6166 by using custom rewrite rules:
```yaml
- "match":
    "status": [500, 502, 503]
  "rewrite":
    "body":
      "inline_string": "internal error (you definitely did not crash our servers)"
# or
- "match":
    "prefix": "/api"
  "rewrite":
    "json_body": # this field may be required to be dynamic, similar to access log json support
      "error": "%BODY%"
```
