### ISSUE TITLE
Front proxy routing to external server returns 503

### ISSUE THREAD

**Issue by sekaninat** [envoyproxy/envoy#7632]
*Title*: *Envoy proxy routing to external server returns 503*

*Description*:
Hi, I have a envoy front proxy which I would like to use for routing to external services, which are not running in envoy, but I am getting 503 Service unavailable from my proxy. As I managed to get this running in demo setup with envoy containers (something like in [docs](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy)) it leads me to a question... Am I doing something wrong or is it not possible to do this altogether? Have routing to non-envoy instances? I managed to do this with redirect, but that's not the behavior I need. 

I am getting bit frustrated so any help is appreciated. If it turns out it is just my mistake I will gladly add my configuration to see where is the problem.

**Comment by crazyxy** [comment]
@sekaninat Can you add your configuration? AFAIK, Envoy supports routing to non-envoy instances.

**Comment by sekaninat** [comment]
I'd expect I shouldn't use a cluster for the external servers then, but the [route](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction) requires it.
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backends
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/external1/"
                route:
                  cluster: external1
                  prefix_rewrite: "/"
              - match:
                  prefix: "/external2/"
                route:
                  cluster: external2
          http_filters:
          - name: envoy.router
            typed_config: {}
          access_log:
            - name: envoy.file_access_log
              config:
                path: "/dev/stdout"
            - name: envoy.file_access_log
              config:
                path: "/tmp/access.log"
  clusters:
  - name: external1
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: external1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 1.2.3.4
                port_value: 80
  - name: external2
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: external2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 5.6.7.8
                port_value: 80
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

**Comment by crazyxy** [comment]
@sekaninat sorry for late response. Does the external service support h2 connection? I can reproduce your issue when I try to connect to a upstream cluster which doesn't support h2 connection. You can remove the `http2_protocol_options: {}` to create http1 connection to upstream.

Here is my configuration:
<details>

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: /1
                route:
                  prefix_rewrite: /
                  cluster: h2server
              - match:
                  prefix: /2
                route:
                  prefix_rewrite: /
                  cluster: h1server1
              - match:
                  prefix: /3
                route:
                  prefix_rewrite: /
                  cluster: h1server2
          http_filters:
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: h2server
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: h2server
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 139.162.123.134    # nghttp2.org
                port_value: 80
  - name: h1server1
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: h1server1
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 52.73.47.183    # httpbin.org
                port_value: 80
  - name: h1server2
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: h1server2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 52.73.47.183    # httpbin.org
                port_value: 80
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

</details>

`curl localhost:8000/1` and `curl localhost:8000/1` will return correctly but `curl localhost:8000/2` will return 503 because `htttpbin.org` doesn't support h2 connection.

@mattklein123 is this expected behavior or do we need to retry to connect the upstream using http1?
