### ISSUE TITLE
What is the automatic retry behavior？

### ISSUE THREAD

**Issue by yangjinjie** [envoyproxy/envoy#7649]
*Title*: *What is the automatic retry behavior?*

*Description*:
Using static configuration, when one of the nodes is down, what is envoy's retry behavior? Will it send requests to the downtime node or reject the downtime node and send requests to other nodes for retry?

**Comment by mattklein123** [comment]
Envoy does no retries by default.

**Comment by yangjinjie** [comment]
My configuration is like this. When one of the nodes is down, what is envoy's retry behavior? Will it send requests to the downtime node or reject the downtime node and send requests to other nodes for retry?

```yaml
...
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              retry_policy: { retry_on: "connect-failure,refused-stream,unavailable,cancelled,resource-exhausted,retriable-status-codes,5xx", num_retries: 3 }
              routes:
                - match: { regex: "/basic.*" }
                  route: { cluster: basic-rpc }
                - match: { regex: "/perm.*" }
                  route: { cluster: perm-rpc }
...

  - name: basic-rpc
    connect_timeout: 0.5s
    type: STATIC
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [
    { socket_address: {address: 172.16.13.110, port_value: 4000 }},
    { socket_address: {address: 172.16.13.120, port_value: 4000 }}
    ]
  - name: perm-rpc
    connect_timeout: 0.5s
    type: STATIC
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [
    { socket_address: {address: 172.16.13.110, port_value: 5000 }},
    { socket_address: {address: 172.16.13.120, port_value: 5000 }}
    ]
...
```
