### ISSUE TITLE
specify a grace period to allow an request with expired jwt when using jwt auth filter

### ISSUE THREAD

**Issue by kyanamgoutham** [envoyproxy/envoy#7693]
When using jwt auth filter we should be able to specify a grace period to allow an request with expired jwt for the specified amount of time?

Or may be provide a way to forward the requests with expired JWT to a different upstream.

**Comment by qiwzhang** [comment]
This should be marked as feature proposal. 
Could you state your usages of allowing a grace period for requests with expired JWT or forwarding  requests with expired JWT to a different backend?

**Comment by Gurpartap** [comment]
> Could you state your usages of allowing a grace period for requests with expired JWT or forwarding requests with expired JWT to a different backend?

Handling a "Refresh Token" request (with expired bearer jwt access token) would be one use-case.

```
> POST /refreshToken
> Authorization: Bearer accessTokenA
> X-Refresh-Token: refreshTokenB
```

```yaml
rules:
  - match:
      prefix: "/refreshToken"
      headers:
        - name: "Authorization"
          prefix_match: "Bearer "
    requires:
      provider_name: jwt_provider_0
      allow_expired: true # 👈
```
