### ISSUE TITLE
Client Envoy Can't Access ALNP protocol value from SslSocket::protocol()

### ISSUE THREAD

**Issue by incfly** [envoyproxy/envoy#7785]
*Title*: *Client Envoy Can't Access ALNP protocol value*

*Description*:
- Envoy Server configure listener with http1.1 ALPN and TLS enabled, DirectResponse. Two filter chains, one matching the alpn == http1.1, one is default filter chain, returns response "hello world, selected from alpn http1.1."
- Envoy Client configures Cluster with http1.1 ALPN and TLS enabled, cluster requests sends to server Envoy.
- Sending request from curl -> Client Envoy -> Server Envoy, returns "hello world alpn 1.1"
- However ALPN "http1.1" can't be fetched via SslSocket::protocol(), returns empty, callstack is from [`Http1::createClientConnection`](https://github.com/envoyproxy/envoy/blob/master/source/common/http/http1/conn_pool.cc#L344), with `data.connection_.protocol->nextProtocol()`.

Note, these two parts are using different SSL methods.

1. FilterChainMatch uses [`boringssl::SSL_early_callback_ctx_extension_get`](https://github.com/envoyproxy/envoy/blob/25c672c0d6e18f948fd11bef643866025b199f55/source/extensions/filters/listener/tls_inspector/tls_inspector.cc#L43)
1. SslSocket::protocol invokes [`borgingssl::SSL_get0_alpn_selected`](https://github.com/envoyproxy/envoy/blob/master/source/extensions/transport_sockets/tls/ssl_socket.cc#L395)

Question

1. Is this an intended behavior? A.K.A the ALPN configured on client/server Envoy is only used for FilterChainMatch but not able to accessed from SslSocket::protocol? In another words, the ALPN is detected in server, but not actually selected and thus we see empty values in client Envoy?
1. If yes, any suggestion, how we should make it available for client Envoy/cluster?
1. If no, Is it a misconfiguration issue?

Reproduce steps (The modified Envoy to print out the `connection_->nextProtocol`) in the right place is not included below)

```bash
bazel-bin/source/exe/envoy-static -c ../httpx-server.yaml --base-id 2
bazel-bin/source/exe/envoy-static -c ../httpx-client.yaml --base-id 1
# see request is responded with "hello world, alpn 1.1 selected."
curl localhost:8000
```

Client Envoy
```yaml
---
node:
  id: 'a2'
  cluster: 'd2'
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filter_chain_match:
        # empty
      filters:
      - config:
          codec_type: auto
          http_filters:
          - config: {}
            name: envoy.router
          route_config:
            name: local_route
            virtual_hosts:
            - domains:
              - "*"
              name: service
              routes:
              - match:
                  prefix: "/"
                route: { cluster: open_cluster }
                #direct_response:
                  #status: 200
                  #body:
                    #inline_string: "hello world, inline response."
          stat_prefix: httpxtest
        name: envoy.http_connection_manager
  clusters:
  - connect_timeout: 0.25s
    tls_context:
      common_tls_context:
        alpn_protocols:
        - http/1.1
        tls_certificates:
          - certificate_chain: { filename: "./test/config/integration/certs/clientcert.pem" }
            private_key: { filename: "./test/config/integration/certs/clientkey.pem" }
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 9000
    lb_policy: round_robin
    name: open_cluster
    type: strict_dns
```

Server Envoy
```yaml
---
node:
  id: 'abc'
  cluster: 'def'
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9001
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9000
    filter_chains:
    - filter_chain_match:
        application_protocols:
        - "http/1.1"
      tls_context:
        common_tls_context:
          alpn_protocols:
          - http/1.1
          tls_certificates:
            - certificate_chain: { filename: "./test/config/integration/certs/servercert.pem" }
              private_key: { filename: "./test/config/integration/certs/serverkey.pem" }
      filters:
      - config:
          codec_type: auto
          http_filters:
          - config: {}
            name: envoy.router
          route_config:
            name: local_route
            virtual_hosts:
            - domains:
              - "*"
              name: service
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "hello world, from httpx-server-envoy-with-http1.1 alpn match."
          stat_prefix: httpxtest
        name: envoy.http_connection_manager
    - filter_chain_match:
        # empty
      tls_context:
        common_tls_context:
          alpn_protocols:
          - http/1.1
          tls_certificates:
            - certificate_chain: { filename: "./test/config/integration/certs/servercert.pem" }
              private_key: { filename: "./test/config/integration/certs/serverkey.pem" }
      filters:
      - config:
          codec_type: auto
          http_filters:
          - config: {}
            name: envoy.router
          route_config:
            name: local_route
            virtual_hosts:
            - domains:
              - "*"
              name: service
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "hello world, from httpx-server-envoy."
          stat_prefix: httpxtest
        name: envoy.http_connection_manager
```
