### ISSUE TITLE
Envoy CORS filter doesn't work. Returns 404 to Preflight OPTIONS request.

### ISSUE THREAD

**Issue by vaibhav-gupta-grab** [envoyproxy/envoy#7833]
Envoy CORS filter not working

I have a similar issue. Can you please tell me what is wrong with it?

Envoy Config:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: main-listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 51051 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              cors:
                allow_origin: ["*"]
                allow_methods: "GET, PUT, DELETE, POST, PATCH, OPTIONS"
                allow_headers: "authorization, keep-alive, user-agent, cache-control, content-type, content-transfer-encoding, x-accept-content-transfer-encoding, x-accept-response-streaming, x-user-agent, x-grpc-web, referer"
                expose_headers: "grpc-status, grpc-message, x-envoy-upstream-service-time"
              routes:
              - match: { prefix: "/", grpc: {} }
                route: { cluster: grpc-backend-services, timeout: { seconds: 60 } }
          http_filters:
          - name: envoy.cors
          - name: envoy.grpc_web
          - name: envoy.grpc_json_transcoder
            config:
              proto_descriptor: "/data/campaignmgmt.pb"
              services: ["CampaignMgmt"]
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
          - name: envoy.router

  clusters:
  - name: grpc-backend-services
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: host.docker.internal
        port_value: 6565
```

curl request:
```
curl -v 'https://localhost:51051/method' -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: content-type' -H 'Origin: http://localhost:8181'
```

The Envoy Debug-level log says that 

>no cluster match for URL '/method'
>Sending local reply with details route_not_found

**Comment by mattklein123** [comment]
cc @dschaller

**Comment by dschaller** [comment]
I can dig into this and take a look but my initial thought is that this doesn't sound like a CORS issue. The filter shouldn't be modifying the returned status code. It either adds headers to the response or passes it through without the addition.

**Comment by vaibhav-gupta-grab** [comment]
It seems to me from the specs mentioned in issue 300, that for OPTIONS request that doesn't match any route, return status 200 and appropriate CORS headers should be set on the Response by CORS filter and should be returned. From my error it seems that the CORS filter isn't doing that, rather the request is going to the router filter and it can't find a matching route. Why is the CORS filter not sending back the response with 200 and CORS headers set?
 
https://github.com/envoyproxy/envoy/issues/300

**Comment by vaibhav-gupta-grab** [comment]
As @lizan mentions here https://github.com/envoyproxy/envoy/issues/6608#issuecomment-484272498, it is okay if there is no route matching the preflight request. Filter should still return appropriate response.

**Comment by dschaller** [comment]
Actually, not sure where this 404 is coming from. Looking at the [filter](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/cors/cors_filter.cc#L68) it appears that the status is explicitly set to 200 and at the end of a preflight request we [stop filter iteration](https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/cors/cors_filter.cc#L91). To me it looks like the filter is correctly handling this logic but it's possible I'm missing something.

**Comment by lizan** [comment]
@dschaller because the route matches gRPC request only, where preflight request doesn't match that route.

@vaibhav-gupta-grab I believe if you remove `grpc: {}` from the route match line, it would work.

**Comment by vaibhav-gupta-grab** [comment]
envoy.cors is the first filter mentioned (before the grpc_transcoder). In that case, envoy.cors should receive the request and return it before the transcoder and route filters are called. Isn't that how it works?

**Comment by lizan** [comment]
@vaibhav-gupta-grab yes, but the preflight request doesn't match what you specified in route match, so for cors filter there is no cors policy specified.

**Comment by vaibhav-gupta-grab** [comment]
Awesome. The solution works. Thanks for the help!

**Comment by dschaller** [comment]
Thanks @lizan!

**Comment by logrusorgru** [comment]
> @dschaller because the route matches gRPC request only, where preflight request doesn't match that route.
> 
> @vaibhav-gupta-grab I believe if you remove `grpc: {}` from the route match line, it would work.

It doesn't work for few grpc clusters
```
              - match: { prefix: "/service1.Service1", grpc: {} }
                route: { cluster: auth, timeout: 60s }
              - match: { prefix: "/service2.Service2", grpc: {} }
                route: { cluster: notifier, timeout: 60s }
              - match: { prefix: "/service3.Service3", grpc: {} }
                route: { cluster: mailer, timeout: 60s }
```
An OPTIONS request with `Content-Type: application/grpc` returns 200 OK. But any other -- 404.

**Comment by cfife-btig** [comment]
We were having a similar issue as you @logrusorgru but it turned out to have more to do with our cluster's routing configuration then with Envoy. It turned out we were blocking non `application/grpc` requests from ever coming to our envoy proxy. But a preflight request is a `text/plain` and OPTIONS request. 

In our case, we adjusted our ingress configuration to route non- `application/grpc` requests to go to the envoy yaml (such that envoy would handle the preflight request).

**Comment by logrusorgru** [comment]
@cfife-btig , hello, can you please provide an example? I'm using special service routed by `/` that handles some CORS requests to cover the Envoy cavity with multiple services.

**Comment by yongzhang** [comment]
same issue, couldn't find a solution.

**Comment by n0v1** [comment]
@yongzhang, a route like this should work I think:
```yaml
- match:
    prefix: "/"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  direct_response:
    status: 204
```

**Comment by mostafafarzaneh** [comment]
@n0v1 

I used 
```
- match:
    prefix: "/"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  route:
    cluster: "some-cluster-name"
```

The preflight request succeeded but I get this:

`origin has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by mostafafarzaneh** [comment]
Hey @n0v1 

I used the route you mentioned:

```
- match:
    prefix: "/"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  route:
    cluster: "some-cluster-name"
```

The preflight request succeeded, but the actual request failed. I get this error:
`origin has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

But if I use this route, everything works fine.
```
- match:
    prefix: "/"
  route:
    cluster: "some-cluster-name"
```

Do you have any idea?
