### ISSUE TITLE
Can't seem to get ClientSSLAuth working in edge scenario using rest api

### ISSUE THREAD

**Issue by ericbrumfield** [envoyproxy/envoy#7858]
I'm having a lot of trouble getting an edge proxy scenario to work.  I could be off track in what I'm trying to do but our use case is that I need to run 1 instances of envoy as an edge proxy that forwards back to a few http applications.  I've been able to get TLS working end to end and we are now looking to limit to "1 car on the highway" by using client certificate authentication.  We'd like for this to be enforced ingress at envoy proxy, no client cert, then no way forward to apps behind the proxy.

I've stripped things back as much as I can and am using a self-signed cert for the client cert auth.  I have stood up a rest api following docs here: https://www.envoyproxy.io/docs/envoy/latest/configuration/network_filters/client_ssl_auth_filter and this returns back certificate/principals successfully when I check  envoy admin stats, total_principals is populated and I see update_success counts increase as it polls for auth.clientssl

As I'm testing and hunting through docs, I feel lost in this configuration yaml and feel like I'm missing something small at this point.  While testing/troubleshooting, I receive nothing but auth_digest_no_match in the admin stats when I enable ClientSSLAuth in the config and a lot of handshake error 2 in the console.

Below is my current envoy config:

```
static_resources:
  listeners:
  - address:
      # Tells Envoy to listen on 0.0.0.0:15000
      socket_address:
        address: 0.0.0.0
        port_value: 15000
    filter_chains:
    - filters:
      #the hook where we'll check/enforce vault issued client certs in this edge proxy
      - name: envoy.client_ssl_auth
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.client_ssl_auth.v2.ClientSSLAuth
          auth_api_cluster: "Envoy_mTLS_Auth"
          stat_prefix: "envoy-mtls-auth"
          refresh_delay: 5s
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: Tenable
          http_filters:
          - name: envoy.router
            typed_config: {}
      tls_context:
        require_client_certificate: true
        validation_context:
            trusted_ca:
              filename: "/etc/envoy/ebrumfield.tenable.cert.pem"
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/etc/envoy/webapp-wildcard.crt"
              private_key:
                filename: "/etc/envoy/webapp-wildcard.key"
                password: "changeit"
  clusters:
  - name: Envoy_mTLS_Auth
    connect_timeout: 15s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: Envoy_mTLS_Auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: envoy-mtls-auth.foo.com
                port_value: 443
    tls_context: {}
  - name: Tenable
    connect_timeout: 15s
    type: static
    lb_policy: round_robin
    load_assignment:
      cluster_name: Tenable
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                # address: 172.32.2.114
                address: 172.32.3.110
                port_value: 443
    tls_context:
      require_client_certificate: true
      common_tls_context:
       tls_certificates:
          - certificate_chain:
              filename: "/etc/envoy/webapp-wildcard.crt"
            private_key:
              filename: "/etc/envoy/webapp-wildcard.key"
              password: "changeit"
admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15001
```

I appreciate any help or guidance here on what to check or maybe try!
