### ISSUE TITLE
envoy 1.11 use websocket 503 UR

### ISSUE THREAD

**Issue by zhiqli** [envoyproxy/envoy#7894]
hi, Now I use envoy 1.7 as a websocket proxy is ok，my config is
```
 "filters": [
        {
          "type": "read",
          "name": "http_connection_manager",
          "config": {
            "codec_type": "auto",
            "stat_prefix": "ssl_ingress_http",
            "use_remote_address": true,
            "http2_settings": {"max_concurrent_streams": 1024000},
            "idle_timeout_s": 300,
            "route_config":
            {
                "virtual_hosts":
                [
                    {
                        "name" : "backend",
                        "domains" : ["*"],
                        "routes" : [
                            {
				"prefix" : "/", "use_websocket": true, "cluster": "backend"
				  ]
    			        }]
    		        }]
                    }
                ]
            },
            "filters": [
		{
		  "type": "both",
		  "name": "health_check",
		  "config": {
		    "pass_through_mode": false,
		    "endpoint": "/healthcheck"
		   }
		},
              {
                "type": "decoder",
                "name": "router",
                "config": {}
              }
            ],
            "access_log" :
            [
                {"path" : "/dev/stdout"}
            ]
	  }
        }
      ]
```
Now I want to upgrade to version 1.11，my config is
```
filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          http_filters:
          - name: envoy.health_check
            config: {pass_through_mode: true, endpoint: /healthcheck}
          - name: envoy.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match: {prefix: "/"}
                route:
                  cluster:backend
          codec_type: auto
          upgrade_configs:
          - upgrade_type: websocket
          access_log:
            name: envoy.file_access_log
            config: {path: /dev/stdout}
          stat_prefix: ingress_http
          use_remote_address: true
          idle_timeout: 10s
```
**The request always returns 503 UR, the upstream server is the same。may I know what is the reason？**
