### ISSUE TITLE
Question. RBAC on jwt token

### ISSUE THREAD

**Issue by weilip1803** [envoyproxy/envoy#7913]
It is known that istio employs RBAC through ServiceRole and ServiceRoleBindings. Can the RBAC filter do something similar to that? Will love an example

**Comment by yuval-k** [comment]
for simplicity we don't use additional CRDs.
See an example here: https://gloo.solo.io/gloo_routing/virtual_services/authentication/jwt/access_control/

**Comment by cstrahan** [comment]
Yes, this is something that we needed. Here's an example:

```
http_filters:
  - name: envoy.filters.http.jwt_authn
    config:
      providers:
        default_provider:
          payload_in_metadata: "payload"
          issuer: https://example.com
          local_jwks:
            # JWKS goes here (truncated for readability)
            inline_string: |
              { "keys": [ … ] }
      rules:
        - match:
            prefix: "/"
          requires:
            provider_name: "default_provider"

  - name: envoy.filters.http.rbac
    config:
      rules:
        action: ALLOW
        policies:
          "any":
            principals:
              - any: true
            permissions:
              - not_rule:
                  header: { name: ":path", regex_match: "/admin(/.*)?" }
          "admin":
            principals:
              - metadata:
                  filter: envoy.filters.http.jwt_authn
                  path:
                    - key: payload
                    - key: role
                  value:
                    string_match:
                      exact: admin
            permissions:
              - any: true

  - name: envoy.router
    config: {}
```

These are the docs you'll want to review:

* https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/rbac_filter
* https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/jwt_authn_filter
* https://www.envoyproxy.io/docs/envoy/latest/configuration/well_known_dynamic_metadata

This comment describes how `payload_in_metadata` works: https://github.com/envoyproxy/envoy/blob/cb15cc3d2010aff77d6e022ddf6d723fa8becbc0/api/envoy/config/filter/http/jwt_authn/v2alpha/config.proto#L170-L186

FWIW, this is the PR that introduced the metadata for the jwt_authn filter: https://github.com/envoyproxy/envoy/pull/4707

Lemme know if you have any trouble.
