### ISSUE TITLE
ext_authz  headers_to_add not interpret variables %DOWNSTREAM....%

### ISSUE THREAD

**Issue by sam80180** [envoyproxy/envoy#7946]
I wanna add custom headers to my ext_authz service, but envoy does not interpret variables. 
I only got non-interpreted string like %DOWNSTREAM.....%

envoy version: (docker image)envoyproxy/envoy:v1.11.1
config:
```
  - name: envoy.ext_authz
    config:
      http_service:
          server_uri:
            uri: http://x.x.x.x:yy
            cluster: ext_authz_nodes
            timeout: 15s
          path_prefix: "/envoy-ext-authz"
          authorization_request:
            allowed_headers:
              patterns:
              - regex: ".*"
            headers_to_add:
            - key: "x-downstream-address"
              value: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
```
