### ISSUE TITLE
mac: unable to open file '/dev/stdout': Permission denied

### ISSUE THREAD

**Issue by lizan** [envoyproxy/envoy#7997]
*Description*:
In macOS only, when stdout is redirected, envoy is unable to open log file /dev/stdout and reject config.

*Repro steps*:
with following config:
```
static_resources:

admin:
  access_log_path: "/dev/stdout"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 15001
```

and run `envoy -c envoy.yaml > foo.log`.
