### ISSUE TITLE
How to configure multiple domain name certificates.

### ISSUE THREAD

**Issue by tonyboxes** [envoyproxy/envoy#8064]
*Description*:
> I configured multiple domain certificates to get this error log.

*Config*:
```
tls_context:
  common_tls_context:
    alpn_protocols: "h2"
    tls_certificates:
        - certificate_chain: { filename: "/etc/certs/domain1.com.crt" }
             private_key: { filename: "/etc/certs/domain1.com.key" }
        - certificate_chain: { filename: "/etc/certs/domain2.com.crt" }
	    private_key: { filename: "/etc/certs/domain2.com.key" }
```

*Logs*:
>[critical][main] [source/server/server.cc:93] error initializing configuration 'envoy.yaml': Failed to load certificate chain from /etc/certs/domain1.com.crt, at most one certificate of a given type may be specified
>[info][main] [source/server/server.cc:560] exiting Failed to load certificate chain from /etc/certs/domain2.com.crt, at most one certificate of a given type may be specified
