### ISSUE TITLE
[Dubbo] How to use head match in dubbo_proxy.v2alpha1.RouteMatch

### ISSUE THREAD

**Issue by zx3821ren** [envoyproxy/envoy#8102]
In dubbo proxy RouteMatch defination,it looks like **heads** can be used to route to different clusters.
eg.
```yaml
name: local_route
interface: org.apache.dubbo.demo.DemoService
routes:
  - match:
      method:
        name:
          exact: "add"
      headers:
      - name: custom
        exact_match: "123"
      - name: custom1
        exact_match: "123"
        invert_match: true
    route:
        cluster: user_service_dubbo_server
```
 
but what is the head exact meaning? In dubbo protocol defination,there is no head can be set by users. Is the head set in meatdata? If so, in which part of variable data part, Attachments?
