### ISSUE TITLE
Support for multiple cluster_names in api_config_source definition

### ISSUE THREAD

**Issue by tinder-mattheworlove** [envoyproxy/envoy#8134]
According to API config source documentation for REST EDS clusters:
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/config_source.proto#envoy-api-msg-core-apiconfigsource 

**cluster_names**
```
Cluster names should be used only with REST_LEGACY/REST. If > 1 cluster is defined, clusters will be cycled through if any kind of failure occurs.
```

However, if more than one cluster_name is defined the following error gets thrown:
https://github.com/envoyproxy/envoy/blob/master/source/common/config/utility.cc#L118
```
envoy::api::v2::core::ConfigSource must have a singleton cluster name specified
```

Ideally this functionality would work as intended and allow multiple clusters to be defined and cycled through in case of failure or unavailability. Something like this should work as intended:
```
      - name: svc
        connect_timeout: 5s
        type: EDS
        lb_policy: least_request
        eds_cluster_config:
          service_name: svc
          eds_config:
            api_config_source:
              api_type: REST
              cluster_names:
              - eds-1
              - eds-2
              refresh_delay: 30s
```
