### ISSUE TITLE
Cannot use EDS cluster type for control plane, because ADS only rely on primary clusters

### ISSUE THREAD

**Issue by lukidzi** [envoyproxy/envoy#8168]
*Title*: *Cannot use EDS cluster type for control plane, because ADS only rely on primary clusters.*

*Description*:
Currently we are using load balancer address and port to connect to Control-plane, but we observe some problems caused by this setup. We want to switch from STATIC to EDS cluster type for control-plane cluster definition. In code I can see that EDS type cluster is loaded after ADS configuration because EDS cluster may potentially need ADS. 
I have configuration like this:
```
 clusters:
  - name: control-plane
    type: EDS
    eds_cluster_config:
      eds_config:
        path: '/tmp/envoy/eds.yaml'

dynamic_resources:
  lds_config:
    ads: {}
  cds_config:
    ads: {}
  ads_config:
    api_type: GRPC
    grpc_services:
      envoy_grpc:
        cluster_name: control-plane
```

Is it possible to add some (flag/type) which allows to define EDS cluster which will be loaded before ADS setup phase?
