### ISSUE TITLE
CDS with strict/logical_dns

### ISSUE THREAD

**Issue by krm1312** [envoyproxy/envoy#8182]
I would like to have CDS (currently file based) contain clusters of type strict_dns.  It appears the solution in https://github.com/envoyproxy/envoy/issues/5186 no longer works of inlining in the CDS cluster definition.

If this is no longer supported, is it still a valid feature request?  There is at least one issue related to this in the go-control-plane project, but, I suspect it should be here (https://github.com/envoyproxy/go-control-plane/issues/87#issuecomment-400739949).

Specifically:

```
dynamic_resources:
  cds_config:
    path: "conf/cds.yaml"

```

cds.yaml

```
resources:
- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: cl_acme-service-any-compute-cluster
  connect_timeout: 0.5s
  http2_protocol_options: {}
  lb_policy: least_request
  type: strict_dns
    dns_lookup_family: v4_only
    dns_resolvers:
      socket_address:
        address: 172.22.0.100
        port_value: 8600
    load_assignment:
      cluster_name: cl_acme-service-any-compute-cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: acme-service.service.consul
                port_value: 4435

- "@type": type.googleapis.com/envoy.api.v2.Cluster
  name: cl_acme-service-c001
  connect_timeout: 0.5s
  http2_protocol_options: {}
  # Sticky
  lb_policy: ring_hash
  type: strict_dns
    dns_lookup_family: v4_only
    dns_resolvers:
      socket_address:
        address: 172.22.0.100
        port_value: 8600
    load_assignment:
      cluster_name: cl_acme-service-c001
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: c001.acme-service.service.consul
                port_value: 4435
                
# c002...etc.
```

Basically, in our app the first request would goes to the 'any' compute cluster.  After that,  the rest of the "interaction" is handled by a specific cluster (say c001 above).  The client sends this in a cluster_header.

These auto-register with consul - so, the idea was that all that was needed in envoy to add a new compute cluster was to drop an additional cluster in cds.yaml with its (consul) DNS.

All the clusters are just ignored, so, it is possible I'm missing something obvious.  Trace logs show file reloading but, it appears everything is silently ignored.

```

[2019-09-09 18:03:12.876][1][debug][file] [external/envoy/source/common/filesystem/inotify/watcher_impl.cc:75] notification: fd: 1 mask: 80 file: cds.yaml~
[2019-09-09 18:03:12.877][1][debug][file] [external/envoy/source/common/filesystem/inotify/watcher_impl.cc:75] notification: fd: 1 mask: 2 file: cds.yaml
[2019-09-09 18:03:12.880][1][debug][file] [external/envoy/source/common/filesystem/inotify/watcher_impl.cc:75] notification: fd: 1 mask: 2 file: .cds.yaml.swp
```

Nothing relevant before or after those entries.

```
[root@d73e06c31888 conf]# envoy --version

envoy  version: e349fb6139e4b7a59a9a359be0ea45dd61e589c5/1.11.1/clean-getenvoy-930d4a5/RELEASE/BoringSSL
```
