### ISSUE TITLE
how to make stat_prefix per domain when envoy as reverse proxy

### ISSUE THREAD

**Issue by alochym01** [envoyproxy/envoy#8245]
envoy as reverse proxy for 2 domains: abc.com, xyz.com
there is only 1 `stat_prefix: ingress_http`
how to assign:
- `stat_prefix: ingress_http_abc` for abc.com
- `stat_prefix: ingress_http_xyz` for xyz.com

envoy.yaml config
```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 192.168.56.101
          port_value: 80
      filter_chains:
      - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                route_config:
                  name: local_route1
                  virtual_hosts:
                    - name: backend1
                      domains:
                        - "xyz.com"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service2
                    - name: backend
                      domains:
                        - "abc.com"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service1
                http_filters:
                  - name: envoy.router
                    typed_config: {}
  clusters:
    - name: service1
      connect_timeout: 0.25s
      lb_policy: round_robin
      load_assignment:
        cluster_name: service1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: service2
      connect_timeout: 0.25s
      lb_policy: round_robin
      load_assignment:
        cluster_name: service2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8081
```

**Comment by alochym01** [comment]
Any suggestions

**Comment by zuercher** [comment]
I don't think this is currently possible. HTTP stats are emitted per-cluster and per-listener but neither of those maps directly to domains. I believe this is intentional so that the number of metrics produced by Envoy is bounded.

**Comment by mattklein123** [comment]
One thing you could do is use "virtual clusters." This is not a perfect solution but might work for you.

**Comment by alochym01** [comment]
@mattklein123 are you mention https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/route_matching

1. The HTTP request’s host or :authority header is matched to a virtual host.
2. Each route entry in the virtual host is checked, in order. If there is a match, the route is used and no further route checks are made.
3. Independently, each virtual cluster in the virtual host is checked, in order. If there is a match, the virtual cluster is used and no further virtual cluster checks are made.
 
i should virtual cluster for routing and not using option 1 and option 2???

could you please me an example of envoy configuration for virtual cluster

thank you

**Comment by alochym01** [comment]
i try to config virtual_cluster and it works but not with 100% satisfied

hope it helps for someone

the envoy.yaml config
```yaml
static_resources:
  listeners:
    - address:
        socket_address:
          address: 192.168.56.101
          port_value: 80
      filter_chains:
      - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: ingress_http
                route_config:
                  name: local_route1
                  virtual_hosts:
                    - name: backend1
                      domains:
                        - "cba.com"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service2
                      virtual_clusters:
                        - name: "cba.com"
                          pattern: "/"
                    - name: backend
                      domains:
                        - "abc.com"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service1
                      virtual_clusters:
                        - name: "abc.com"
                          pattern: "/"
                http_filters:
                  - name: envoy.router
                    typed_config: {}
  clusters:
    - name: service1
      connect_timeout: 0.25s
      lb_policy: round_robin
      load_assignment:
        cluster_name: service1
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: service2
      connect_timeout: 0.25s
      lb_policy: round_robin
      load_assignment:
        cluster_name: service2
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8081
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
