### ISSUE TITLE
direct_response precedence over CORS pre-flight response

### ISSUE THREAD

**Issue by llchan** [envoyproxy/envoy#8262]
When using `direct_response`, it _seems_ to take effect with higher precedence than the `envoy.cors` filter, even if `envoy.cors` is first in the `http_filters` list.

My http config is essentially:
```
http_filters:
- name: envoy.cors
- name: envoy.filters.http.jwt_authn
  config: { ... }
- name: envoy.router
route_config:
  virtual_hosts:
  - cors: { ... }
    ...
    routes:
    - match: { path: "/ping" }
      direct_response: { status: 200 }
```

If I change `direct_response` to a `route` to a dummy cluster, a pre-flight OPTIONS request returns the right cors response, but with `direct_response` the response is the 200 even for the pre-flight request.  It's possible to use a header method match to manually construct a different response for OPTIONS vs other requests to that route, but ideally there would be a way to configure a route action to be a direct response that acts on the request after cors (and other filters) have done their work.

The use case here is e.g. a `/ping` endpoint that goes through the filter stack and sends a direct response.

**Comment by mattklein123** [comment]
cc @dschaller ^

**Comment by zuercher** [comment]
This happens because the CORS filter checks for a route and route entry:

```
  if (decoder_callbacks_->route() == nullptr ||
      decoder_callbacks_->route()->routeEntry() == nullptr) {
    return Http::FilterHeadersStatus::Continue;
  }
```

In this case, the routeEntry returns nullptr, but `decoder_callbacks_->route()->directResponseEntry()` wouldn't.

**Comment by dschaller** [comment]
Sorry I missed this tag in my inbox.

@zuercher is right on the spot here. Ideally we should be checking for any route type. This should be a quick fix. @mattklein123 can you assign this one to me?

**Comment by dschaller** [comment]
Just an update on this request. It turns out that simply checking for the presence of a direct response is not sufficient as the CORS configuration is read in from either the route or it's virtual host. However, direct response objects do not have a way of accessing the virtual host they are registered on (https://github.com/envoyproxy/envoy/blob/master/include/envoy/router/router.h#L57-L96).

The good news is that we should move this filter out of the route proto object anyways and use `per_filter_config`. By doing this we can utilize the `resolveMostSpecificPerFilterConfig` function which will check the routeEntry, route, and virtual host for a CORS configuration which should solve this problem.

I'm currently working on the project mentioned above and hope to have something posted for review in the next couple of days.

I'm working on this migration at the moment.

**Comment by bokan** [comment]
Any updates on this?

**Comment by eugenk** [comment]
I don't like to ping thread, but it seems appropriate here:

> Any updates on this?

**Comment by n0v1** [comment]
Because of this issue, workarounds are needed to get CORS filter working together with gRPC-JSON transcoder.

Instead of
```yaml
- match:
    safe_regex:
      regex: ".*"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  direct_response:
    status: 204
```
We need to use either
```yaml
- match:
    safe_regex:
      regex: ".*"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  route:
    cluster: "cluster-grpc-upstream"
```
which is misleading because the cluster won't actually handle OPTIONS requests

or
```yaml
- match:
    safe_regex:
      regex: ".*"
    headers:
    - name: ":method"
      string_match:
        exact: "OPTIONS"
  direct_response:
    status: 204
  response_headers_to_add:
  - append_action: ADD_IF_ABSENT
    header:
      key: "access-control-allow-origin"
      value: "%REQ(ORIGIN?:AUTHORITY)%"
  - append_action: ADD_IF_ABSENT
    header:
      key: "access-control-allow-methods"
      value: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
  - append_action: ADD_IF_ABSENT
    header:
      key: "access-control-allow-headers"
      value: "*, Authorization"
  - append_action: ADD_IF_ABSENT
    header:
      key: "access-control-allow-credentials"
      value: "true"
  - append_action: ADD_IF_ABSENT
    header:
      key: "access-control-max-age"
      value: "86400"
```
which defeats  the purpose of already having a CORS filter configured.

See https://github.com/envoyproxy/envoy/issues/17031#issuecomment-1923585622.

@dschaller wrote that the CORS filter should be changed to use `per_filter_config` first. I think this was already done already as [documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/cors/v3/cors.proto) states 
> Please note that it must be configured in the RouteConfiguration as typed_per_filter_config [...]

So what is left to be done here?
