### ISSUE TITLE
Large timings when using envoy and libjaegertracing_plugin.so  for tracing

### ISSUE THREAD

**Issue by TheSpbra1n** [envoyproxy/envoy#8307]
*Large timings when using envoy and libjaegertracing_plugin.so  for tracing*

*Description*:
Hi. We use envoy with over 10000 rps in one cluster.  Typically, the query time is kept at:
- full request time(serviceA -> envoy -> serviceB): 0.2-0.5 seconds
- connection establishment time (envoy -> serviceB): 0.48-0.49 milliseconds

After adding libjaegertracing_plugin.so ( www.envoyproxy.io/docs/envoy/latest/start/sandboxes/jaeger_native_tracing.html ) timings increase to:
- full request time(serviceA -> envoy -> serviceB): 0.5-2 seconds
- connection establishment time (envoy -> serviceB): 20-150 milliseconds

( a little better with the latest libjaegertracing_plugin.so, connection establishment time at 2 and more milliseconds )

Without libjaegertracing_plugin.so, or with built in zipkin`s tracing, or with libjaegertracing_plugin.so and with less rps - timings are normal.

*Repro steps*:
Add to envoy.yml:
```
static_resources:
  listeners:
...
          tracing:
            operation_name: egress
...
tracing:
  http:
    name: envoy.dynamic.ot
    typed_config:
      "@type": type.googleapis.com/envoy.config.trace.v2.DynamicOtConfig
      library: /tmp/libjaegertracing_plugin.linux_amd64-v0.4.2.so
      config:
        service_name: jaeger
        sampler:
          type: const
          param: 1
        reporter:
          localAgentHostPort: 127.0.0.1:6831
        headers:
          jaegerDebugHeader: jaeger-debug-id
          jaegerBaggageHeader: jaeger-baggage
          traceBaggageHeaderPrefix: uberctx-
          baggage_restrictions:
          denyBaggageOnInitializationFailure: false
          hostPort: ""
```
