### ISSUE TITLE
ext_authz: Pass full downstream certificate to the external service

### ISSUE THREAD

**Issue by sel-vcc** [envoyproxy/envoy#8326]
*Title*: ext_authz: Pass full downstream certificate to the external service

*Description*:
This is a feature request.

Today the ext_authz filter sends the principle of the downstream X.509 certificate in the [Peer AttributeContext](
https://www.envoyproxy.io/docs/envoy/v1.11.1/api-v2/service/auth/v2/attribute_context.proto#service-auth-v2-attributecontext-peer).

In our authorization system we require validation of additional parts of the X.509 certificate, such as the serial number.

We propose to send the full downstream client X.509 certificate as a label in the source Peer AttributeContext.

**Comment by sel-vcc** [comment]
I have uploaded #8327 to aid in explanation of the change that we propose.

**Comment by xxx0624** [comment]
Hi @sel-vcc , definitely this is an amazing feature! I have one quick question regarding to passing the peer certificate to the ext auth service. Not sure if you know this.

I found that only if the `validation_context` is configured in the yaml can we access the peer certificate in the ext auth service.
Is this expected?
BTW my yaml config file is as followed:
```yaml
static_resources:
  listeners:
  - name: listener_0
    address: {socket_address: {address: ::, port_value: 443}}
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          route_config:
            virtual_hosts:
            - name: default
              domains: ["*"]
              routes:
              - match: {prefix: "/"}
                route:
                  cluster: some_service
     http_filters:
        name: envoy.filters.http.ext_authz
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          grpc_service:
            envoy_grpc:
              cluster_name: ext-authz
          with_request_body:
            max_request_bytes: 1024
            allow_partial_message: true
            pack_as_bytes: true
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain: {filename: "certs/servercert1.pem"}
              private_key: {filename: "certs/serverkey1.pem"}
            validation_context: // enabled here!!!!!!!
              match_subject_alt_names:
  		contains: ""
  clusters:
  - name: some_service
    type: STATIC
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: some_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 1234
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context:
          tls_certificates:
          - certificate_chain: {"filename": "certs/servercert2.pem"}
            private_key: {"filename": "certs/serverkey2.pem"}
  - name: ext-authz
     ...
```
