### ISSUE TITLE
[Help wanted] 308 Permanent Redirect example

### ISSUE THREAD

**Issue by mmorejon** [envoyproxy/envoy#8393]
308 Permanent Redirect example

_Description:_
I'm trying to set up Envoy to redirect the traffic to a specific location based in a header location parameter (308 Permanent Redirect)

_Question_
Do you have an example of this configuration?

**Comment by derekargueta** [comment]
this example redirects everything to www.google.com
```
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8000
      filter_chains:
      - filters:
        - name: envoy.http_connection_manager
          typed_config:
            "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
            stat_prefix: ingress_http
            codec_type: AUTO
            route_config:
              name: local_route
              virtual_hosts:
              - name: local_service
                domains: ["*"]
                routes:
                - match:
                    prefix: "/"
                  redirect:
                    host_redirect: www.google.com
                    response_code: PERMANENT_REDIRECT
            http_filters:
            - name: envoy.router
```

curl output:
```
➜  ~ curl -svo /dev/null localhost:8000/foobar 2>&1 | grep "< "
< HTTP/1.1 308 Permanent Redirect
< location: http://www.google.com/foobar
< date: Fri, 04 Oct 2019 19:51:14 GMT
< server: envoy
< content-length: 0
<
➜  ~
```
