### ISSUE TITLE
Utilizing IP Tagging as an Edge proxy

### ISSUE THREAD

**Issue by cetanu** [envoyproxy/envoy#8412]
I've come across a small issue that I'm unsure how to solve:

When running envoy as an edge proxy, it's advised by the docs to set [`use_remote_address`](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-use-remote-address) to `true` in the listener config.

This setting seems to prevent envoy from adding the `X-Envoy-Ip-Tags` header *unless* the IP is a private address from rfc1918.

An example configuration that you may use to trigger such behavior:

```
static_resources:
  listeners:
    - name: test
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8888
          protocol: TCP
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: test
                use_remote_address: true
                http_filters:
                  - name: envoy.ip_tagging
                    config:
                      ip_tags: 
                        - ip_tag_name: AWS-EC2-US-EAST-1
                          ip_list:
                            - address_prefix: 52.23.63.224
                              prefix_len: 27
                  - name: envoy.router
                route_config:
                  name: static-response
                  virtual_hosts:
                    - name: catchall
                      domains:
                        - '*'
                      routes:
                        - match:
                            prefix: /
                          direct_response:
                            status: 200
                            body:
                              inline_string: |
                                Hello world!
```

This may be somewhat hard to test unless you can make a request to an envoy proxy running the above config from a public IP address. Maybe if you have a EC2 box in AWS us-east-1 you can test with it? 😅 

Am I perhaps doing something wrong here, or is this a known limitation of the IP Tagging HTTP Filter?
Should I propose a change to the filter?
