### ISSUE TITLE
allow reversing the order of the evaluateHeaders() calls

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#8450]
Currently, adding or removing request/response headers is hard-coded to the following order [0]:

* route specific
* vhost specific
* connection manager level

This means that you can't set global configs (e.g.: vhost or conn manager level) and then unset them at the route specific level.

Would it be acceptable to have a  config option -- say `reverse_header_evaluation_order` -- to support the reverse order (from least to most specific: conn manager -> vhost -> route)?

Or would this break anything else?

cc: @mattklein123 

[0] https://github.com/envoyproxy/envoy/blob/master/source/common/router/config_impl.cc#L386

**Comment by sc0ttbeardsley** [comment]
O.o This would make my life easier

**Comment by mattklein123** [comment]
cc @htuch for API thoughts. I can't see any harm in this, but I wonder if the we should just allow the order to be defined as a repeated enum or something so it's fully flexible? I'm not sure if the extra flexibility would be actually useful or not. Thoughts?

**Comment by rgs1** [comment]
I'll send in a PR for just reversing, since I can't think of use-cases for arbitrary ordering (unless @htuch  can come up with one)...

**Comment by rgs1** [comment]
@mattklein123 @htuch perhaps something like #8466? (sorting out the v2 -> v3alpha out of sync stuff)

**Comment by htuch** [comment]
The other option would be to set an explicit priority on each header manipulation. Can you give some concrete examples of manipulations that you think would be using this for? I'm trying to wrap my head around the set/unset/override logic, so seeing something concrete would be helpful.

**Comment by rgs1** [comment]
@htuch this test case is what we want: https://github.com/envoyproxy/envoy/pull/8466/commits/fa89efd9b0f9c5e371834a1e15e2e7bce6824a29

Basically:

* set `cache-control: private` at the global connection manager level
* unset it for a few routes

**Comment by rgs1** [comment]
Inlining what we want/need:

```
name: foo
virtual_hosts:
  - name: www2
    domains: ["www.lyft.com"]
    reverse_header_evaluation_order: true
    routes:
      - match:
          prefix: "/cacheable"
        route:
          cluster: www2
        response_headers_to_remove: ["cache-control"]
      - match:
          prefix: "/"
        route:
          cluster: "www2"
response_headers_to_add:
  - header:
      key: cache-control
      value: private
```
