### ISSUE TITLE
Question: Can we log the egress errors for the http tracer

### ISSUE THREAD

**Issue by jyotimahapatra** [envoyproxy/envoy#8451]
Question:
We use lightstepproxy as a http tracer and the configs look like this
```
tracing:
  http:
    config: {access_token_file: <redacted>, collector_cluster: lightstep_saas}
    name: envoy.lightstep
```
We are experiencing SR in our lightstepproxy clusters and we were investigating if its possible to configure the egress logs going to lightstep and investigate the probems.
The [proto](https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/trace/v2/trace.proto#L59) doesn't have a setting to add a log file.
Is there any way to log the egress errors to lightstep tracer?
