### ISSUE TITLE
access_log json_format DYNAMIC_METADATA values are escaped

### ISSUE THREAD

**Issue by jstewmon** [envoyproxy/envoy#8593]
When using `json_format` for `access_log`, `DYNAMIC_METADATA` values, which are already JSON, are escaped, resulting in double-escaped JSON values.

Since dynamic metadata values are already well-formed JSON, I think they should not be escaped when using `json_format` access logs.

*Repro steps*:
A basic `envoy.yaml` that logs a dynamic metadata field:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            name: envoy.file_access_log
            typed_config:
              '@type': type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
              path: /dev/stdout
              json_format:
                version: '%DYNAMIC_METADATA(envoy.lb:version)%'
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: ok
          http_filters:
          - name: envoy.filters.http.header_to_metadata
            config:
              request_rules:
                - header: x-version
                  on_header_present:
                    metadata_namespace: envoy.lb
                    key: version
                    type: STRING
          - name: envoy.router
            typed_config: {}
```

Run the config through docker:

```sh
docker run --rm -v $(pwd)/envoy.yaml:/etc/envoy/envoy.yaml -p 8000:80 -it envoyproxy/envoy-alpine:v1.11.1
```

Sends requests with and without `x-version` header:

```sh
curl localhost:8000
curl localhost:8000 -H'x-version: 123'
```

Observed log messages:
```json
{"version":"-"}
{"version":"\"123\""}
```
