### ISSUE TITLE
Redis through envoy gets high response time with redis-benchmark

### ISSUE THREAD

**Issue by mosespx** [envoyproxy/envoy#8644]
Hi, 
I’m deploying envoy redis in our environment and I’ve found out that it’s increasing the RTT of the 95 percentile requests to redis in about 7~ms, I have run `redis-benchmark` tool in both configurations, and through envoy the higher percents getting a much higher response time. results attached.
this is the configuration file:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 50051
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service_grpc
          http_filters:
          - name: envoy.router
            config: {}
  - name: redis_nrt_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 0.03s
            enable_redirection: true
            enable_hashtagging: true
          prefix_routes:
            catch_all_route:
              cluster: redis_nrt_cluster
  - name: redis_vol_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6380
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 0.03s
            enable_redirection: true
            enable_hashtagging: true
          prefix_routes:
            catch_all_route:
              cluster: redis_vol_cluster
  clusters:
  - name: local_service_grpc
    connect_timeout: 0.250s
    type: logical_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    health_checks:
    - timeout: 1s
      interval: 3s
      interval_jitter: 1s
      unhealthy_threshold: 3
      healthy_threshold: 3
      tcp_health_check:
        send:
        receive: []
    hosts:
    - socket_address:
        address: router-us-east4-b-prod.ocddx.com
        port_value: 50051
  - name: redis_vol_cluster
    connect_timeout: 1s
    type: strict_dns # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis-us-east4-b-prd.ocddx.com
                port_value: 6379
  - name: redis_nrt_cluster
    connect_timeout: 1s
    type: strict_dns # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: redis-nrt-us-east4-b-prd.ocddx.com
                port_value: 6379
admin:
  access_log_path: "/var/log/envoy_admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
```

redis-benchmark running from container to the envoy sidecar:
```
redis-benchmark -h collector_envoy -t set,get
====== SET ======
  100000 requests completed in 7.06 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

4.92% <= 1 milliseconds
59.69% <= 2 milliseconds
73.69% <= 3 milliseconds
82.54% <= 4 milliseconds
88.11% <= 5 milliseconds
91.77% <= 6 milliseconds
94.26% <= 7 milliseconds
95.89% <= 8 milliseconds
97.18% <= 9 milliseconds
98.01% <= 10 milliseconds
98.58% <= 11 milliseconds
98.97% <= 12 milliseconds
99.22% <= 13 milliseconds
99.43% <= 14 milliseconds
99.58% <= 15 milliseconds
99.73% <= 16 milliseconds
99.78% <= 17 milliseconds
99.81% <= 18 milliseconds
99.88% <= 19 milliseconds
99.90% <= 20 milliseconds
99.90% <= 21 milliseconds
99.93% <= 22 milliseconds
99.97% <= 23 milliseconds
99.98% <= 24 milliseconds
99.98% <= 28 milliseconds
100.00% <= 29 milliseconds
14164.31 requests per second

====== GET ======
  100000 requests completed in 7.66 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

4.18% <= 1 milliseconds
55.05% <= 2 milliseconds
71.89% <= 3 milliseconds
81.03% <= 4 milliseconds
87.10% <= 5 milliseconds
90.96% <= 6 milliseconds
93.66% <= 7 milliseconds
95.49% <= 8 milliseconds
96.44% <= 9 milliseconds
97.22% <= 10 milliseconds
97.75% <= 11 milliseconds
98.34% <= 12 milliseconds
98.83% <= 13 milliseconds
99.15% <= 14 milliseconds
99.34% <= 15 milliseconds
99.49% <= 16 milliseconds
99.59% <= 17 milliseconds
99.69% <= 18 milliseconds
99.72% <= 19 milliseconds
99.81% <= 20 milliseconds
99.87% <= 21 milliseconds
99.89% <= 22 milliseconds
99.91% <= 23 milliseconds
99.92% <= 24 milliseconds
99.93% <= 25 milliseconds
99.96% <= 26 milliseconds
99.97% <= 27 milliseconds
99.97% <= 28 milliseconds
99.98% <= 29 milliseconds
99.98% <= 34 milliseconds
99.98% <= 35 milliseconds
99.99% <= 36 milliseconds
100.00% <= 37 milliseconds
13063.36 requests per second
```

redis-benchmark running from container to a single redis host (part of a  masters cluster):
```
bash-4.4# redis-benchmark -h 10.240.15.147 -t set,get
====== SET ======
  100000 requests completed in 4.95 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

11.96% <= 1 milliseconds
94.58% <= 2 milliseconds
96.80% <= 3 milliseconds
98.02% <= 4 milliseconds
98.75% <= 5 milliseconds
99.27% <= 6 milliseconds
99.58% <= 7 milliseconds
99.75% <= 8 milliseconds
99.89% <= 9 milliseconds
99.96% <= 10 milliseconds
99.97% <= 11 milliseconds
99.97% <= 12 milliseconds
99.99% <= 13 milliseconds
100.00% <= 13 milliseconds
20197.94 requests per second

====== GET ======
  100000 requests completed in 5.07 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1

15.41% <= 1 milliseconds
90.76% <= 2 milliseconds
95.60% <= 3 milliseconds
97.79% <= 4 milliseconds
98.70% <= 5 milliseconds
99.23% <= 6 milliseconds
99.60% <= 7 milliseconds
99.76% <= 8 milliseconds
99.82% <= 9 milliseconds
99.83% <= 11 milliseconds
99.87% <= 12 milliseconds
99.89% <= 13 milliseconds
99.91% <= 14 milliseconds
99.97% <= 15 milliseconds
99.99% <= 16 milliseconds
100.00% <= 16 milliseconds
19704.43 requests per second
```
As you can see there's a huge different between the response times, I've been trying to change some configuration for example: type to `logical_dns` instead of `strict_dns`, remove the `lb_type` and add `max_buffer_size_before_flush` and `buffer_flush_timeout` and even change the dns to point to only one member of the redis cluster, the same host I checked in the second test, to ensure the reliability of the `redis-benchmark` test. 

I'd be glad if someone who using redis with envoy will do the same test I did and share the results, and if someone has any recommendations to solve this response time issue

**Comment by mosespx** [comment]
@zuercher please add a BUG label, seems like its happening also in other environments

**Comment by HenryYYang** [comment]
Are you introducing a network hop in the envoy case in your test?

Here's the result for my test against a local docker container:
> root@8362fe3593b4:/# redis-benchmark -h redis-server -p 7001 -t get,set
> 
> ====== SET ======
>   100000 requests completed in 3.07 seconds
>   50 parallel clients
>   3 bytes payload
>   keep alive: 1
> 
> 84.07% <= 1 milliseconds
> 99.09% <= 2 milliseconds
> 99.84% <= 3 milliseconds
> 99.93% <= 4 milliseconds
> 99.94% <= 5 milliseconds
> 99.96% <= 6 milliseconds
> 99.96% <= 9 milliseconds
> 99.96% <= 10 milliseconds
> 99.97% <= 11 milliseconds
> 99.99% <= 26 milliseconds
> 100.00% <= 27 milliseconds
> 100.00% <= 27 milliseconds
> 32626.43 requests per second
> 
> ====== GET ======
>   100000 requests completed in 3.04 seconds
>   50 parallel clients
>   3 bytes payload
>   keep alive: 1
> 
> 85.27% <= 1 milliseconds
> 98.79% <= 2 milliseconds
> 99.85% <= 3 milliseconds
> 99.97% <= 4 milliseconds
> 99.97% <= 9 milliseconds
> 99.99% <= 10 milliseconds
> 100.00% <= 11 milliseconds
> 32894.74 requests per second
> 
> 
> root@8362fe3593b4:/# redis-benchmark -p 6381 -t get,set
> ====== SET ======
>   100000 requests completed in 3.78 seconds
>   50 parallel clients
>   3 bytes payload
>   keep alive: 1
> 
> 0.00% <= -32 milliseconds
> 0.01% <= -30 milliseconds
> 0.02% <= -29 milliseconds
> 0.03% <= -28 milliseconds
> 0.03% <= -26 milliseconds
> 0.04% <= 0 milliseconds
> 24.19% <= 1 milliseconds
> 89.52% <= 2 milliseconds
> 99.04% <= 3 milliseconds
> 99.78% <= 4 milliseconds
> 99.82% <= 5 milliseconds
> 99.84% <= 6 milliseconds
> 99.85% <= 7 milliseconds
> 99.87% <= 8 milliseconds
> 99.89% <= 10 milliseconds
> 99.94% <= 11 milliseconds
> 99.96% <= 12 milliseconds
> 99.97% <= 13 milliseconds
> 99.98% <= 14 milliseconds
> 99.98% <= 15 milliseconds
> 99.98% <= 16 milliseconds
> 99.99% <= 19 milliseconds
> 100.00% <= 20 milliseconds
> 26462.03 requests per second
> 
> ====== GET ======
>   100000 requests completed in 3.05 seconds
>   50 parallel clients
>   3 bytes payload
>   keep alive: 1
> 
> 28.07% <= 1 milliseconds
> 96.50% <= 2 milliseconds
> 99.51% <= 3 milliseconds
> 99.80% <= 4 milliseconds
> 99.95% <= 5 milliseconds
> 100.00% <= 6 milliseconds
> 100.00% <= 6 milliseconds
> 32797.64 requests per second

Here's the relevant section of envoy.yaml:
```
static_resources:
  listeners:
    - name: listener_1
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 6381
      filter_chains:
        filters:
          name: envoy.redis_proxy
          config:
            stat_prefix: redis_stats
            prefix_routes:
              catch_all_route:
                cluster: cluster_1
            settings:
              op_timeout: 5s
  clusters:
    - name: cluster_1
      connect_timeout: 0.25s
      lb_policy: RING_HASH
      hosts:
      - socket_address:
          address: redis-server
          port_value: 7001
      type: STRICT_DNS
```
