### ISSUE TITLE
Overload Manager using injected resource doesn't work in production

### ISSUE THREAD

**Issue by madhu-shankar** [envoyproxy/envoy#8690]
*Title*: *Overload Manager using injected resource doesn't work in production*

*Description*:
>We are tying to enable overload manger in Envoy 1.8.0, based on CPU and Memory usage. For this, we tried using the injected_resource. Form the stats, we see that Envoy is able to read the injected_resource file. But when the threshold is reached, requests are not getting rejected with 503. The injected_resource documentation says that it is intended for integration tests, does it mean we can't use it in production or is it not enabled in the version we are using(1.8.0)? Below are the envoy configuration and stats emitted by envoy, please let me know if there is anything wrong in the configuration or if my understanding is incorrect.

*Configuration*:
```
overload_manager:
  refresh_interval:
    seconds: 0
    nanos: 250000000
  resource_monitors:
    - name: "envoy.resource_monitors.injected_resource"
      config:
        filename: "/tmp/envoy_cpu_usage"
  actions:
    - name: "envoy.overload_actions.stop_accepting_requests"
      triggers:
        - name: "envoy.resource_monitors.injected_resource"
          threshold:
            value: 0.65
```

*Metrics*:
envoy.overload.envoy.resource_monitors.injected_resource.pressure = 75, for testing, we are emitting this number(0.75) temporarily.
envoy.overload.envoy.overload_actions.stop_accepting_requests.active = 1, 50% of the times and 0 otherwise.

>Extra documentation required to understand the issue.
1. [Overload Manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager)
2. [Injected Resource](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/resource_monitor/injected_resource/v2alpha/injected_resource.proto)
