### ISSUE TITLE
FilterChainMatch: allow matching rule to require multiple ALPN values.

### ISSUE THREAD

**Issue by PiotrSikora** [envoyproxy/envoy#8709]
Currently, FilterChainMatch allows matching against any of the presented ALPN values using `application_protocols` field, which can be repeated multiple times in order to provide OR semantics, i.e.
```
# HTTP traffic
- filter_chain_match:
  - application_protocols: ["h2", "http/1.1"] 
  filters: ...
# non-HTTP traffic
- filter_chain_match:
  filters: ...
```

However, we're (ab)using `istio` ALPN value to differentiate between service mesh and legacy traffic, and we'd like to also differentiate between HTTP and non-HTTP traffic in the same listener, so we need to add the ability to match values using AND semantics, e.g.
```
filter_chains:
# service mesh HTTP traffic
- filter_chain_match:
  - application_protocols: ("istio" AND "h2") OR ("istio" AND "http/1.1")
  filters: ...
# service mesh non-HTTP traffic
- filter_chain_match:
  - application_protocols: "istio"
  filters: ...
# legacy HTTP traffic
- filter_chain_match:
  - application_protocols: ["h2", "http/1.1"] 
  filters: ...
# legacy non-HTTP traffic
- filter_chain_match:
  filters: ...
```

There are a few ways this can be expressed at the API level:

a) create a top-level OR array of an AND arrays, e.g.
```
- filter_chain_match:
  - application_protocols:
    - ["istio", "h2"]
    - ["istio", "http/1.1"]
  filters: ...
```
b) provide AND/OR semantics inline, which could be done without modifying existing proto, e.g. using `+` operator:
```
- filter_chain_match:
  - application_protocols: ["istio+h2", "istio+http/1.1"]
  filters: ...
```

Any thoughts, @envoyproxy/api-shepherds?

cc @yxue @lambdai @rshriram
