### ISSUE TITLE
Lua filter after route resolution

### ISSUE THREAD

**Issue by sekaninat** [envoyproxy/envoy#8719]
**Lua filter after route resolution**

*Description*:
I am dealing with pretty much the same as in https://github.com/envoyproxy/envoy/issues/4274.

I need to change the prefixes before forwarding them to backends. My idea was to change the :path header in a lua filter. However it seems like the route matching happens again after the lua script because when I change it I end up with 404 from my proxy.

I am honestly confused with this. The lua filter apparently takes metadata from the correct route, but then the route is matched again... 

This is trimmed down version of what I have:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backends
              domains:
              - "*"
              routes:
              - match:
                  safe_regex:
                    google_re2: {}
                    regex: "^/a/b/[a-zA-Z0-9._-]+$"
                route:
                  cluster: cluster1
                metadata:
                  filter_metadata:
                    envoy.lua:
                      prefix: /prefix/
          http_filters:
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                    prefix = "/"
                    if request_handle:metadata():get("prefix") then
                      prefix = request_handle:metadata():get("prefix")
                    end
                  path = request_handle:headers():get(":path"):gsub("^/a/b/", prefix)
                  request_handle:headers():replace(":path", path)
                end
                function envoy_on_response(request_handle)
                end
```
Thanks for any help.
