### ISSUE TITLE
Cluster healthcheck uses wrong interval due to metric filtering

### ISSUE THREAD

**Issue by ivanpondal** [envoyproxy/envoy#8771]
Given an **Envoy v1.11.1** node with [cluster](https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats) metrics excluded via `StatsMatcher` and cluster health checking enabled, when sending traffic to the cluster healthcheck is always run with `no_traffic_interval` 60s default interval.

The cause is the same as with https://github.com/envoyproxy/envoy/issues/8630, metrics are being used for application functionality.

In this case [upstream_cx_total](https://github.com/envoyproxy/envoy/blob/v1.11.1/source/common/upstream/health_checker_base_impl.cc#L86) is the metric on which the dependency exists. Therefore the workaround is to whitelist it:

```
stats_config:
 stats_matcher:
  inclusion_list:
    patterns:
    - suffix: upstream_cx_total
```
