### ISSUE TITLE
Possible Lua filter memory leak when using body in envoy_on_response()

### ISSUE THREAD

**Issue by vblvl19** [envoyproxy/envoy#8773]
*Title*: *Possible Lua filter memory leak when using body in envoy_on_response()*

*Description*:
When accessing the response body inside the envoy_on_response() Lua function, either with body() or bodyChunks(), the memory does not seem to be freed after Envoy finishes responding to the downstream.

*Envoy Version*: v1.11.1

*Repro steps*:
1. Use the standard implementation of the envoy.lua filter with the following code:
```lua
function envoy_on_request(handle)
  local metadata = handle:streamInfo():dynamicMetadata()
  local headers = handle:headers()
  local rid = headers:get("x-request-id")
  if rid ~= nil then metadata:set("envoy.lua", "x-original-request-id") end
end

function envoy_on_response(handle)
  local cluster = "logging_server"
  local headers = {
    [":method"] = "POST",
    [":path"] = "/logging/response",
    [":authority"] = cluster,
  }
  local metadata = handle:streamInfo():dynamicMetadata():get("envoy.lua")
  for key, value in pairs(metadata) do
    if key == "x-original-request-id" then headers[":path"] = "/logging/response/for/" .. value end
    headers["x-int-meta-" .. key] = value
  end
  if (handle:metadata():get("buffer_response") == "buffered") then
    local res = handle:body()
    local body = res:getBytes(0, res:length())
    handle:httpCall(cluster, headers, body, 0)  -- Point A
  else
    local t = {}
    for chunk in handle:bodyChunks() do
      local body = chunk:getBytes(0, chunk:length())
      table.insert(t, body)
    end
    handle:httpCall(cluster, headers, table.concat(t, ""), 0)  -- Point B
  end
end
```
2. Configure the listener `per_connection_buffer_limit_bytes` to about 10 MiB.
3. Run the alpine docker image of Envoy acting as a reverse proxy for a server that responds to GET requests with large payloads (120kiB to ~2MiB), and run `docker stats` to observe the memory usage. On my machine, Envoy usually starts with ~8MiB.
4. Run a load testing framework (I used gatling) that exercises the endpoints that return the larger payloads. I ran a test from one machine that throttled to 100 RPS.
5. Observe Envoy's memory usage shoot up to ~1 GiB, which does not go down even an hour after the test is run.

*Notes*:
- I've ensured that the payload server has enough capacity to handle the requests; Envoy's access log shows 200 status codes and no 503/504 errors are logged.
- The memory usage does not change when *Point A* or *Point B* are commented out.
- Separately, *Point B* will abruptly terminate its connection to the `logging_server` cluster if it is unable to upload the request in time. I will get exceptions from the logging server to the tune of "the client has disconnected while sending a request".

*Config*:
```yaml
# lds.yaml
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.Listener
  name: vip_listener
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8080
  per_connection_buffer_limit_bytes: 10000000
  filter_chains:
  - filters:
    - name: envoy.http_connection_manager
      typed_config:
        "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
        stat_prefix: vip_http
        codec_type: auto
        rds:
          route_config_name: vip_routes
          config_source:
            path: /envoy/conf/rds.yaml
        http_filters:
          - name: envoy.health_check
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.health_check.v2.HealthCheck
              pass_through_mode: false
              headers:
                - name: ":path"
                  exact_match: "/healthcheck"
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              inline_code: |
                -- << INSERT LUA CODE HERE >>
          - name: envoy.router
            config: {}
        access_log:
          - name: envoy.file_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
              format: '[%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION% %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%
                "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%" "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
                '
              path: /dev/stdout
```

```yaml
# rds.yaml
version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.api.v2.RouteConfiguration
    name: vip_routes
    virtual_hosts:
      - name: incoming
        domains:
          - "*"
        routes:
          - match:
              prefix: /log/buffer/
            route:
              prefix_rewrite: /
              cluster: test
              request_mirror_policy:
                cluster: logging_server
            metadata:
              filter_metadata:
                envoy.lua:
                  buffer_response: buffered
          - match:
              prefix: /log/
            route:
              prefix_rewrite: /
              cluster: test
              request_mirror_policy:
                cluster: logging_server
          - match:
              prefix: /
            route:
              cluster: test
```

```yaml
# cds.yaml
version_info: "0"
resources:
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: test
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: test
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: app
                    port_value: 8080
    drain_connections_on_host_removal: true
    circuit_breakers:
      thresholds:
        - max_connections: 10000
          max_pending_requests: 10000
          max_requests: 10000
          max_retries: 0
          priority: DEFAULT
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: logging_server
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: logging_server
      endpoints:
        - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: logger
                    port_value: 5000
    drain_connections_on_host_removal: true
    circuit_breakers:
      thresholds:
        - max_connections: 10000
          max_pending_requests: 10000
          max_requests: 10000
          max_retries: 0
          priority: DEFAULT
```

```yaml
# envoy.yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
dynamic_resources:
  cds_config:
    path: '/envoy/conf/cds.yaml'
  lds_config:
    path: '/envoy/conf/lds.yaml'
```
