### ISSUE TITLE
Inotify events being dropped for EDS files.

### ISSUE THREAD

**Issue by shidel-dev** [envoyproxy/envoy#8787]
*Missing inotify notifications*

*Description*:

I am trying to use envoy as a front proxy for 3 grpc services. I have static configuration for everthing, except for EDS. For EDS I am attempting to use [consul-template](https://github.com/hashicorp/consul-template) to render yaml files. They are rendered into a tmp directory and then are moved into the location configured for the corresponding cluster (`mv eds-tmp/<service-name>/conf.yaml eds/<service-name>/conf.yaml`).

This works well, and I can see debug logs for file notifications when a new instance is registered. However for reasons unknown to me, envoy will stop responding to newly rendered files being moved into these directories. Nothing is logged when this happens.

Some relevant logs from before this happens
```
[ 039ab0b837fd ] 10-24 21:10:47 ERROR - [2019-10-25 04:10:47.758][39][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:50] added watch for directory: '/envoy/eds/results' file: 'conf.yaml' fd: 1
[ 039ab0b837fd ] 10-24 21:10:47 ERROR - [2019-10-25 04:10:47.758][39][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:50] added watch for directory: '/envoy/eds/scanning' file: 'conf.yaml' fd: 1
[ 039ab0b837fd ] 10-24 21:10:47 ERROR - [2019-10-25 04:10:47.759][39][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:50] added watch for directory: '/envoy/eds/printing' file: 'conf.yaml' fd: 1
[ 039ab0b837fd ] 10-24 21:10:47 ERROR - [2019-10-25 04:10:47.760][39][debug][file] [source/common/filesystem/inotify/watcher_impl.cc:50] added watch for directory: '/envoy/lds' file: 'conf.yaml' fd: 1
[ 039ab0b837fd ] 10-24 21:10:47 ERROR - [2019-10-25 04:10:47.760][39][debug][init] [source/common/init/manager_impl.cc:20] added target LDS to init manager Server
[ 039ab0b837fd ] 10-25 03:47:17 ERROR - [2019-10-25 10:47:17.040][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 1 removed 0
[ 039ab0b837fd ] 10-25 03:47:17 ERROR - [2019-10-25 10:47:17.040][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 1 removed 0
[ 039ab0b837fd ] 10-25 03:47:17 ERROR - [2019-10-25 10:47:17.040][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 1 removed 0
[ 039ab0b837fd ] 10-25 03:49:36 ERROR - [2019-10-25 10:49:36.023][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 1 removed 0
[ 039ab0b837fd ] 10-25 03:49:36 ERROR - [2019-10-25 10:49:36.023][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 1 removed 0
[ 039ab0b837fd ] 10-25 03:49:36 ERROR - [2019-10-25 10:49:36.023][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 1 removed 0
[ 039ab0b837fd ] 10-25 03:56:58 ERROR - [2019-10-25 10:56:58.640][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 1 removed 0
[ 039ab0b837fd ] 10-25 03:56:58 ERROR - [2019-10-25 10:56:58.640][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 1 removed 0
[ 039ab0b837fd ] 10-25 03:56:58 ERROR - [2019-10-25 10:56:58.640][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 1 removed 0
[ 039ab0b837fd ] 10-25 21:00:33 ERROR - [2019-10-26 04:00:33.319][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 0 removed 1
[ 039ab0b837fd ] 10-25 21:00:33 ERROR - [2019-10-26 04:00:33.319][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 0 removed 1
[ 039ab0b837fd ] 10-25 21:00:33 ERROR - [2019-10-26 04:00:33.321][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster results added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:19 ERROR - [2019-10-26 04:01:19.741][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:19 ERROR - [2019-10-26 04:01:19.741][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:19 ERROR - [2019-10-26 04:01:19.741][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster scanning added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:28 ERROR - [2019-10-26 04:01:28.604][39][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:28 ERROR - [2019-10-26 04:01:28.604][45][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 0 removed 1
[ 039ab0b837fd ] 10-25 21:01:28 ERROR - [2019-10-26 04:01:28.604][47][debug][upstream] [source/common/upstream/cluster_manager_impl.cc:999] membership update for TLS cluster printing added 0 removed 1
```

Configuration:

```
node:
  id: front-proxy
  cluster: front-proxy
dynamic_resources:
  lds_config:
    path: /envoy/lds/conf.yaml
static_resources:
  clusters:
  - name: results
    connect_timeout: 2s
    http2_protocol_options: { }
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        path: /envoy/eds/results/conf.yaml
  - name: scanning 
    connect_timeout: 2s
    http2_protocol_options: { }
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        path: /envoy/eds/scanning/conf.yaml
  - name: printing 
    connect_timeout: 2s
    http2_protocol_options: { }
    lb_policy: ROUND_ROBIN
    type: EDS
    eds_cluster_config:
      eds_config:
        path: /envoy/eds/printing/conf.yaml
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8002
```

one of the EDS templates
```
version_info: "0"
resources:
- "@type": type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: "results"
  endpoints:
  - lb_endpoints:{{ range service "results" }}
    - endpoint:
        address:
          socket_address:
            address: {{.Address}}
            port_value: {{.Port}}
{{end}}
```

One potential factor is that this seems to happen when envoy starts and there are no instances of the services (staging environment where things scale to 0 at night). EDS files are still rendered with no endpoints under `lb_endpoints`. When the service does come online the EDS file gets rerendered, but envoy does not load the new endpoints (No endpoints show up in /clusters).
