### ISSUE TITLE
max_requests_per_connection=1 causes gRPC connections reset

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#8817]
*Title*: max_requests_per_connection=1 reset gRPC connections

*Description*:
We have a simple upstream which is a simple helloworld gRPC server.
We set up a simple envoy proxy in front of the server with the config (see attached). One thing special is max_requests_per_connection=1

When we use a simple client that starts N go routines, each go routines sends M sequential requests, however, the many requests fail due to connection reset 

"code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"

If "max_requests_per_connection=1" is removed, it works fine.

*Repro steps*:
Source:
https://github.com/bakins/cloud-run-grpc-concurrency-test

1. start envoy with the attached config

2. start the server:
go run ./server/

3. start the client:
go run ./client/ --iterations 5 --workers 5  --url http://127.0.0.1:9090
2019/10/30 21:17:52 could not greet: 2 1 rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination 
... 

*Config*:

```
static_resources:
  listeners:
  - name: listener_0
    address:
     socket_address:
        address: 127.0.0.1
        port_value: 9090
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          generate_request_id: false
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: upstream
          http_filters:
          - name: envoy.router
            config:
              suppress_envoy_headers: true
  clusters:
  - name: upstream
    connect_timeout: 5s
    max_requests_per_connection: 1
    protocol_selection: USE_DOWNSTREAM_PROTOCOL
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    hosts:
      - socket_address:
          address: 127.0.0.1
          port_value: 8080

```
