### ISSUE TITLE
Unable to filter HTTP requests before HCM

### ISSUE THREAD

**Issue by Quexint** [envoyproxy/envoy#8853]
### Description

We have multiple domains on port 80 and want to customize every domain's HCM setting. For example, separating the access_logs for every domain (`${domain}.${status_code}.log`), enabling different http_filters and enabling websocket support.

When all domains go through TLS protocol, using `server_names` in `FilterChainMatch` can achieve this goal. But `server_names` is based on TLS SNI, and it does not support HTTP requests.

Currently, I can separate HTTP requests to different clusters in routing (virtual_hosts layer), but all domains share the same HCM setting. Is there any solution for separating HCM setting?

Thanks in advising.

### Relative Configs

<details>

<summary> Multiple HTTPS Domains </summary>

```
---
static_resources:
  listeners:
  - "@type": type.googleapis.com/envoy.api.v2.Listener
    name: listener_443
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 443
    listener_filters:
    - name: envoy.listener.tls_inspector
      typed_config: {}
    filter_chains:
    - filter_chain_match:
        server_names:
        - test1:443
        - test1
      tls_context:
        common_tls_context:
          tls_certificates:
          - certificate_chain:
              filename: "/self-signed/test1.crt"
            private_key:
              filename: "/self-signed/test1.key"
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          generate_request_id: true
          tracing:
            operation_name: egress
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service1
              require_ssl: all
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_www_google_com_443
                  host_rewrite: www.google.com
                metadata:
                  filter_metadata:
                    envoy.filters.http.modsecurity: {}
          http_filters:
          - name: envoy.router
    - filter_chain_match:
        server_names:
        - test2:443
        - test2
      tls_context:
        common_tls_context:
          tls_certificates:
          - certificate_chain:
              filename: "/self-signed/test2.crt"
            private_key:
              filename: "/self-signed/test2.key"
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          generate_request_id: true
          tracing:
            operation_name: egress
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service1
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_www_yahoo_com_443
                  host_rewrite: www.yahoo.com
          http_filters:
          - name: envoy.router
  clusters:
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: service_www_google_com_443
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_www_google_com_443
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
    tls_context:
      sni: www.google.com
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: service_www_yahoo_com_443
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_www_yahoo_com_443
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.yahoo.com
                port_value: 443
    tls_context:
      sni: www.yahoo.com
```

</details>

<details>

<summary> Multiple HTTP Domains </summary>

```
---
static_resources:
  listeners:
  - "@type": type.googleapis.com/envoy.api.v2.Listener
    name: listener_80
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          generate_request_id: true
          tracing:
            operation_name: egress
          route_config:
            virtual_hosts:
            - name: ingress_test5
              domains:
              - test5:80
              - test5
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_www_google_com_443
                  host_rewrite: www.google.com
            - name: ingress_test6
              domains:
              - test6:80
              - test6
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: service_www_yahoo_com_443
                  host_rewrite: www.yahoo.com
          http_filters:
          - name: envoy.router
  clusters:
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: service_www_google_com_443
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_www_google_com_443
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.google.com
                port_value: 443
    tls_context:
      sni: www.google.com
  - "@type": type.googleapis.com/envoy.api.v2.Cluster
    name: service_www_yahoo_com_443
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_www_yahoo_com_443
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.yahoo.com
                port_value: 443
    tls_context:
      sni: www.yahoo.com
```

</details>

### Relative Issues

- Issue #3615: `server_names` is from TLS SNI
- Issue #5920: Multiple http filters don't work
