### ISSUE TITLE
lb_subset_config: global fallback_policy is not enforced for selectors if there is another more specific selector

### ISSUE THREAD

**Issue by MarcinFalkowski** [envoyproxy/envoy#8874]
Given following subset config:

```
lb_subset_config:
  fallback_policy: ANY_ENDPOINT
  subset_selectors:
  - keys: ["canary"]
  - keys: ["tag", "canary"]
    fallback_policy: ANY_ENDPOINT
```

For route metadata ["canary": "not existing value"] there should be a fallback to ANY_ENDPOINT, as defined in global fallback policy. But instead, `no healthy upstream` is returned.

It happens, because in `SubsetLoadBalancer::selectors_` tree, the node for "canary" is created as an intermediate node to ["canary", "tag"], which has its own fallback_policy defined. Thus `tryFindSelectorFallbackParams` returns not empty optional with fallback policy NOT_DEFINED for ["canary"] metadata. Then `chooseHostForSelectorFallbackPolicy` is executed instead of falling back to global fallback policy.

I am already preparing fix for this as part of implementation for #8767 . I created this issue only for reference if anybody else will search for this bug.
