### ISSUE TITLE
Upstream connect error or disconnect/reset before headers

### ISSUE THREAD

**Issue by PabloDeCortes** [envoyproxy/envoy#8937]
Hi, I'm simply trying to configure envoy as reverse proxy, but when I'm trying to proxy to my docker container, I see error `upstream connect error or disconnect/reset before headers. reset reason: connection failure`. Could you, please, point me, where I misconfigured envoy.

*docker-compose.yml:*
```
version: "3.7"
services:
  envoy:
    depends_on: 
      - nginx
    networks:
      - proxynet
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
    ports:
      - "8081:8081"
      - "80:80"
    container_name: envoy
    image: envoyproxy/envoy-alpine
  nginx:
    networks:
      proxynet:
        aliases:
          - nginx
    ports:
      - "7000:80"
    container_name: nginx
    image: nginx
networks:
  proxynet:
```
*envoy.yml:*
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 80
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: backend
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/nginx"
                          route:
                            cluster: nginx
                http_filters:
                  - name: envoy.router
  clusters:
    - name: nginx
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: nginx
            port_value: 7000
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8081
```
