### ISSUE TITLE
Multiple Rate limit configurations based on request attributes

### ISSUE THREAD

**Issue by ankit-joinwal** [envoyproxy/envoy#8967]
Hi i am using Envoy along with Ratelimit (https://github.com/lyft/ratelimit)

The setup is working fine. It is able to rate limit on simple scenario (using generic_key descriptor)

I now want to rate limit with following scenario

- If request contains header called "referrer-app" and destination cluster is "ServiceA", restrict to 100 RPM
- Else if request does not contain a header called "referrer-app" but destination cluster is "ServiceA", restrict to 50 RPM

Want to know if this scenario is possible with Envoy configuration?

Currently I tried following configuration but it doesnt work:

Here is my envoy.yaml
```

            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: serviceA
              rate_limits:
                - stage: 0
                  actions:
                    - destination_cluster: {}
                - stage: 0
                  actions:
                    - destination_cluster: {}
                    - {request_headers: {header_name: "referrer-app",descriptor_key: "referrer-app"}}
```

And here is my rate limit configuration
```
  - key: destination_cluster
    value: serviceA
    rate_limit:
      unit: minute
      requests_per_unit: 50
    descriptors:
      - key: referrer-app
        value: clientA
        rate_limit:
          unit: minute
          requests_per_unit: 100
```

The problem with above configuration is that it sends both the descriptors in request everytime. What I want is kind of an If-else for the descriptors.

**Comment by htuch** [comment]
@junr03 can you take a look at this?

**Comment by junr03** [comment]
For clarity, you only need the second set of actions to accomplish what you are describing, so:

```
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: serviceA
              rate_limits:
                - stage: 0
                  actions:
                    - destination_cluster: {}
                    - {request_headers: {header_name: "referrer-app",descriptor_key: "referrer-app"}}
```

is enough.

The request headers action should only send a descriptor when the request has a header with the key `header_name`. What do your request headers look like for the requests that should not be sending both descriptors?

How have you verified that envoy always sends both descriptors?

**Comment by ankit-joinwal** [comment]
Hi ,
Thanks for your response.

> What do your request headers look like for the requests that should not be sending both descriptors?
When the request headers contain "referrer-app" header, then the following descriptor should be generated (pseudocode)
("destination_cluster", "serviceA")
("referrer-app", "clientA")

However, with the configuration I posted in my initial question, the below descriptor is also sent to rate limit because the rate limit being matched is for the below descriptor
("destination_cluster", "serviceA")

> How have you verified that envoy always sends both descriptors?
Logs from rate limit show that it is matching both the keys : destination_cluster_serviceA and referrer-app_clientA

Logs from rate limit:
``` 
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="starting get limit lookup"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="looking up key: destination_cluster_serviceA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="found rate limit: destination_cluster_serviceA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="iterating to next level"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="starting get limit lookup"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="looking up key: destination_cluster_serviceA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="found rate limit: destination_cluster_serviceA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="request depth does not match config depth, there are more entries in the request's descriptor"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="iterating to next level"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="looking up key: referrer-app_clientA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="found rate limit: referrer-app_clientA"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="starting cache lookup"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="looking up cache key: apis_destination_cluster_serviceA_1573456860"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="looking up cache key: apis_destination_cluster_serviceA_referrer-app_clientA_1573456860"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="cache key: apis_destination_cluster_serviceA_1573456860 current: 4"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="cache key: apis_destination_cluster_serviceA_referrer-app_clientA_1573456860 current: 4"
ratelimit_1        | time="2019-11-11T07:21:38Z" level=debug msg="returning normal response"
```

The problem with using just one action as mentioned by you is that if an action doesn’t append a descriptor entry, no descriptor is generated for the configuration.

So, for the requests that do not contain the "referrer-app" but have destination_cluster = "ServiceA", then it would not generate the descriptor at all. So i am not able to rate limit based on only destination_cluster.

I would like to clarify my use case again:

- If request contains header called "referrer-app" and destination cluster is "ServiceA", restrict to 100 RPM

- Else if request does not contain a header called "referrer-app" but destination cluster is "ServiceA", restrict to 50 RPM

**Comment by ankit-joinwal** [comment]
Any help on this please

**Comment by junr03** [comment]
I see what you mean now. Thank you for the additional information. In order to use the behavior you suggest I would recommend using the following configuration

```
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                   prefix: "/service"
                   headers: 
                     - name: "referrer-app"
                       present_match: true (I believe you mention just the presence of the header, but note that there are other matchers you can use if the value of the header is important)
                 route:
                   cluster: serviceA
                 rate_limits:
                   - stage: 0
                       actions:
                         - destination_cluster: {}
                        - {request_headers: {header_name: "referrer-app",descriptor_key: "referrer-app"}}
              - match:
                   prefix: "/service"
                 route:
                   cluster: serviceA
                 rate_limits:
                   - stage: 0
                       actions:
                         - destination_cluster: {}
```

This way your request is matched by header, and the ratelimit actions can differ between them. Does that make sense?


P.S: It is unfortunate that the presence of descriptors in the ratelimit filter is all or nothing, but it is done that way because ordering matters.

**Comment by ankit-joinwal** [comment]
Hi,
Thanks for your reply.

I tried to use the configuration provided by you.
However, Envoy does not start with above configuration.

Here is my complete configuration
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 9010
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/service"
                route:
                  cluster: serviceA
              rate_limits:
                - stage: 0
                  actions:
                    - destination_cluster: {}
              - match:
                  prefix: "/service"
                  headers:
                     - name: "referrer-app"
                       present_match: true
                route:
                  cluster: serviceA
              rate_limits:
                - stage: 0
                  actions:
                    - destination_cluster: {}
                    - {request_headers: {header_name: "referrer-app",descriptor_key: "referrer-app"}}
          http_filters:
          - name: envoy.rate_limit
            config:
              domain: apis
              stage: 0
              timeout: 5s
              rate_limit_service:
                 grpc_service:
                    envoy_grpc:
                       cluster_name: rate_limit_cluster
          - name: envoy.router
  clusters:
  - name: serviceA
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: serviceA
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9080
  - name: rate_limit_cluster
    connect_timeout: 5s
    type: strict_dns
    lb_policy: round_robin
    http2_protocol_options: {}
    load_assignment:
      cluster_name: rate_limit_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: ratelimit
                port_value: 8081

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9081

```

Error while starting:
`[2019-11-18 10:54:53.817][8][critical][main] [source/server/server.cc:96] error initializing configuration '/config/envoy.yaml': yaml-cpp: error at line 29, column 15: end of map not found
`

I think that configuring rate_limits per matcher is not the supported configuration.
There is no rate_limits configuration mentioned in docs within matcher.
Ref - https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-msg-route-route 
And, https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto.html#envoy-api-msg-route-routematch

Until now i have only configure rate_limits at the virtual_hosts level.

Please correct me if i am not using the correct configuration as mentioned in your answer.
