### ISSUE TITLE
Add a port white list in sniffer-ish listener filter

### ISSUE THREAD

**Issue by lambdai** [envoyproxy/envoy#9032]
*Description*:
A per listener time out doesn't work well in iptables-redirect-to listener.
For example:
For server-first -packet protocol filter chain: a immediate timeout is preferred
For TLS expected filter chain: it is expected to be infinity timeout

I propose adding a L4 address based timeout in sniffer listener filter (tls_inspector)
```
Timeouts: 
- matcher:
   port: 3306 #mysql server first protocol 
  timeout: 0.0000001s
- matcher: {} 
  timeout: 100000000s
```
Alternative solution:
  list of port for infinity timeout, and a list of port for immediate timeout
