### ISSUE TITLE
Simple Ratelimit doesnt work with envoy frontproxy

### ISSUE THREAD

**Issue by nagireddygatla** [envoyproxy/envoy#9084]
Simple Ratelimit doesnt work with envoy frontproxy

envoy front proxy config:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          use_remote_address: true
          stat_prefix: ingress_http
          access_log:
            - name: envoy.file_access_log
              config:
                path: /dev/stdout
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  # Send request to an endpoint in the Google cluster
                  cluster: google
                  host_rewrite: www.google.com
                rate_limits:
                  - actions:
                      - remote_address: {}
          http_filters:
          - name: envoy.rate_limit
            config:
              domain: rate_per_ip
              rate_limit_service:
                grpc_service:
                  envoy_grpc:
                    cluster_name: rate_limit_cluster
                  timeout: 0.25s
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: google
    connect_timeout: 1s
    type: logical_dns 
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    load_assignment:
    hosts: [{ socket_address: { address: google.com, port_value: 443 }}]
    tls_context: { sni: www.google.com }

  - name: rate_limit_cluster
    type: STATIC 
    connect_timeout: 1s
    lb_policy: ROUND_ROBIN
    http2_protocol_options: {}
    hosts: [{ socket_address: { address: 127.0.0.1 , port_value: 8081 }}]
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

ratelimit config:
```
domain: rate_per_ip
descriptors:
  - key: database
    value: users
    rate_limit:
      unit: minute
      requests_per_unit: 5
  - key: remote_address
    rate_limit:
      unit: minute
      requests_per_unit: 5
```

I can see both ratelimit and envoy working, and can access them, but envoy doesnt hit ratelimit service at all. Please help me.
