### ISSUE TITLE
Issue integration Envoy tracing with Spring Sleuth 

### ISSUE THREAD

**Issue by christine-gong** [envoyproxy/envoy#9105]
**Have problem integrating Envoy tracing with Spring Sleuth** 

*Description*:
We are using Envoy with Jaeger and zipkin tracer. 
e.g.
```
tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: jaeger
          collector_endpoint: "/api/v1/spans"
```
Looks like that egress traffic's spanid always get rewritten to something like 1,2,3,4. It is ok when manually forwarding headers inside the service by preserving the ingress spanid.

But when propagating tracing headers with Spring Sleuth and zipkin tracer, looks like sleuth always creates new spanid for the egress traffic as well. 

So in the jaeger ui, there is warning saying `invalid parent span IDs=xxxxxxxxx; skipping clock skew adjustment` makes
 ```
a -> b -> c -> d 
``` 
becoming 
```
a -> b
c -> d
```
My questions are:
1. How to integrate with systems that has its own tracer defined? 
2. Why envoy/jaeger always rewrites the egress spanid & parentspanid?

Thanks !!!
