### ISSUE TITLE
ext_authz CheckRequest not including request body on HTTP2 requests with with_request_body enabled

### ISSUE THREAD

**Issue by brectanus-sigsci** [envoyproxy/envoy#9111]
*Description*:

I have ext_authz configured with `with_request_body` and the body is passed over in the CheckRequest call for HTTP/1.1 requests, but not when the request is HTTP/2. This seems to be the case with the following envoy containers (e.g., since this feature was introduced):

* envoyproxy/envoy:latest
* envoyproxy/envoy:v1.11.0
* envoyproxy/envoy:v1.10.0

*Repro steps*:

CheckRequest with HTTP/1.1 (curl -d test -http11 https://test.example.com:8800):
```yaml
attributes:
  source:
    address:
      socket_address:
        address: "192.168.65.3"
        port_value: 55522
  destination:
    address:
      socket_address:
        address: "10.1.3.214"
        port_value: 8800
    principal: "CN=*.example.com,OU=PositiveSSL Wildcard,OU=Domain Control Validated"
  request:
    http:
      id: "144129472221377462"
      method: "POST"
      headers:
        - key: ":authority"
          value: "test.example.com:8800"
        - key: ":method"
          value: "POST"
        - key: ":path"
          value: "/"
        - key: "accept"
          value: "*/*"
        - key: "content-length"
          value: "4"
        - key: "content-type"
          value: "application/x-www-form-urlencoded"
        - key: "user-agent"
          value: "curl/7.64.1"
        - key: "x-forwarded-proto"
          value: "https"
        - key: "x-request-id"
          value: "033f7b53-df7d-4bcf-88b0-fc55e64d331a"
      path: "/"
      host: "test.example.com:8800"
      size: 4
      protocol: "HTTP/1.1"
      body: "test"
```

CheckRequest with HTTP/2 (curl -d test --http2-prior-knowledge https://test.example.com:8800/):
```yaml
attributes:
  source:
    address:
      socket_address:
        address: "192.168.65.3"
        port_value: 43370
  destination:
    address:
      socket_address:
        address: "10.1.3.214"
        port_value: 8800
    principal: "CN=*.example.com,OU=PositiveSSL Wildcard,OU=Domain Control Validated"
  request:
    http:
      id: "10625449567139415222"
      method: "POST"
      headers:
        - key: ":authority"
          value: "test.example.com:8800"
        - key: ":method"
          value: "POST"
        - key: ":path"
          value: "/"
        - key: ":scheme"
          value: "https"
        - key: "accept"
          value: "*/*"
        - key: "content-length"
          value: "4"
        - key: "content-type"
          value: "application/x-www-form-urlencoded"
        - key: "user-agent"
          value: "curl/7.64.1"
        - key: "x-forwarded-proto"
          value: "https"
        - key: "x-request-id"
          value: "f99842a4-85fe-48d6-b363-d7693422490d"
      path: "/"
      host: "test.example.com:8800"
      scheme: "https"
      size: 4
      protocol: "HTTP/2"
```

Diff of HTTP/1.1 -> HTTP/2:
```diff
# curl -d test -http11 https://test.example.com:8800
# curl -d test --http2-prior-knowledge https://test.example.com:8800/
--- checkRequest_http11.yaml	2019-11-22 11:30:50.000000000 -0500
+++ checkRequest_http2.yaml	2019-11-22 11:28:12.000000000 -0500
@@ -3,7 +3,7 @@
     address:
       socket_address:
         address: "192.168.65.3"
-        port_value: 55522
+        port_value: 43370
   destination:
     address:
       socket_address:
@@ -12,7 +12,7 @@
     principal: "CN=*.example.com,OU=PositiveSSL Wildcard,OU=Domain Control Validated"
   request:
     http:
-      id: "144129472221377462"
+      id: "10625449567139415222"
       method: "POST"
       headers:
         - key: ":authority"
@@ -21,6 +21,8 @@
           value: "POST"
         - key: ":path"
           value: "/"
+        - key: ":scheme"
+          value: "https"
         - key: "accept"
           value: "*/*"
         - key: "content-length"
@@ -32,9 +34,9 @@
         - key: "x-forwarded-proto"
           value: "https"
         - key: "x-request-id"
-          value: "033f7b53-df7d-4bcf-88b0-fc55e64d331a"
+          value: "f99842a4-85fe-48d6-b363-d7693422490d"
       path: "/"
       host: "test.example.com:8800"
-      size: 4
-      protocol: "HTTP/1.1"
-      body: "test"
+      scheme: "https"
+      size: 4
+      protocol: "HTTP/2"
```

*Config*:

Simple Config I am using:
```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8800
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: test-app
          access_log:
          http_filters:
          - name: envoy.ext_authz
            config:
              grpc_service:
                envoy_grpc:
                  cluster_name: test-agent-grpc
                timeout: 0.2s
              failure_mode_allow: true
              with_request_body:
                max_request_bytes: 8192
                allow_partial_message: true
          - name: envoy.router
            config: {}
      tls_context:
        common_tls_context:
          tls_certificates:
            - certificate_chain:
                filename: "/local/example.com.crt.pem"
              private_key:
                filename: "/local/example.com.key.pem"
  clusters:
  - name: test-app
    connect_timeout: 0.2s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: test-app
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8080
  - name: test-agent-grpc
    connect_timeout: 0.25s
    type: strict_dns
    http2_protocol_options: {}
    load_assignment:
      cluster_name: test-agent-grpc
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 9999
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
 
*Logs*:

The ext_authz filter seems to be buffering in either HTTP/1.1 or HTTP/2 cases as I see this in the logs:

```
[2019-11-22 17:08:58.734][31][debug][http] [source/common/http/conn_manager_impl.cc:246] [C0] new stream
[2019-11-22 17:08:58.735][31][debug][http] [source/common/http/conn_manager_impl.cc:600] [C0][S4397996624313074540] request headers complete (end_stream=false):
':method', 'POST'
':path', '/'
':scheme', 'https'
':authority', 'test.example.com:8800'
'user-agent', 'curl/7.64.1'
'accept', '*/*'
'content-length', '4'
'content-type', 'application/x-www-form-urlencoded'

[2019-11-22 17:08:58.735][31][debug][filter] [source/extensions/filters/http/ext_authz/ext_authz.cc:87] [C0][S4397996624313074540] ext_authz filter is buffering the request
[2019-11-22 17:08:58.735][31][trace][http] [source/common/http/conn_manager_impl.cc:857] [C0][S4397996624313074540] decode headers called: filter=0x244fc20 status=1
[2019-11-22 17:08:58.735][31][debug][http] [source/common/http/conn_manager_impl.cc:1092] [C0][S4397996624313074540] request end stream
[2019-11-22 17:08:58.735][31][debug][filter] [source/extensions/filters/http/ext_authz/ext_authz.cc:105] [C0][S4397996624313074540] ext_authz filter finished buffering the request since stream is ended
[2019-11-22 17:08:58.735][31][trace][filter] [source/extensions/filters/http/ext_authz/ext_authz.cc:72] [C0][S4397996624313074540] ext_authz filter calling authorization server
[2019-11-22 17:08:58.736][31][trace][http] [source/common/http/conn_manager_impl.cc:982] [C0][S4397996624313074540] decode data called: filter=0x244fc20 status=2
[2019-11-22 17:08:58.739][31][debug][http] [source/common/http/async_client_impl.cc:91] async http request response headers (end_stream=false):
':status', '200'
'content-type', 'application/grpc'
'x-envoy-upstream-service-time', '2'

[2019-11-22 17:08:58.739][31][trace][http] [source/common/http/async_client_impl.cc:99] async http request response data (length=66 end_stream=false)
[2019-11-22 17:08:58.739][31][debug][http] [source/common/http/async_client_impl.cc:106] async http request response trailers:
'grpc-status', '0'
'grpc-message', ''
```

cc @gsagula (continuing a slack chat on this)
