### ISSUE TITLE
Chunked transfer-encoding cause envoy leak memory?

### ISSUE THREAD

**Issue by wlhee** [envoyproxy/envoy#9123]
*Title*: *Chunked transfer-encoding cause envoy leak memory?*

*Description*:
Envoy memory usage keeps growing when upstream is a fast chunked response writer but the downstream is a slow reader. However, the memory usage keeps growing instead of being freed after upstream and downstream are disconnected.

*Repro steps*:
1. start envoy with the simple config

2. start an upstream: 
https://gist.github.com/wlhee/ad457e47301f1f4f534258cbaed2459e

3. start a slow downstream client:
https://gist.github.com/wlhee/77ee97862c376a43b2a091d90e123789

client --url "http://localhost:9090/chunked?size_bytes=1&&infinite=true&&interval=0ms"

4. 'ps' shows envoy process memory usage keeps growing even after both upstream and downstream are disconnected

*Config*:
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: {
      address: 127.0.0.1,
      port_value: 9901
    }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: {
        address: 127.0.0.1,
        port_value: 9090
      }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
                - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: worker_endpoint
                  timeout: 300s
          http_filters:
          - name: envoy.router

  clusters:
  - name: worker_endpoint
    connect_timeout: 5s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    hosts:
      socket_address:
        address: 127.0.0.1
        port_value: 8080
```
