### ISSUE TITLE
How to get real client IP in Envoy?

### ISSUE THREAD

**Issue by metalLeveller** [envoyproxy/envoy#9127]
I need to get the real client IP address from the request and as I understand, I can get it with the help of [XFF](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#envoy-api-field-config-filter-network-http-connection-manager-v2-httpconnectionmanager-use-remote-address)

According to [this documentation](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-for), I need to enable use_remote_address (as it is set to false by the default).

This is an example of a config. I ran tests with different values for skip_xff_append and xff_num_trusted_hops variables. The result is the same - I get the IP address of Envoy node at the x-forwarded-for header.

Configs works for [36f39c746eb7d03b762099b206403935b11972d8](https://hub.docker.com/layers/envoyproxy/envoy/36f39c746eb7d03b762099b206403935b11972d8/images/sha256-23052e099eb4795f8c2f3c330370fa8b9159e66362d6159337de4da885b6334d) version.
```
admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: ingress_http
                stream_idle_timeout: 0s
                use_remote_address: true
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/api/" }
                          route:
                            prefix_rewrite: "/"
                            cluster: api_gateway
                            max_grpc_timeout: 0s
                            retry_policy:
                              retry_on: 5xx
                              num_retries: 5
                              per_try_timeout: 1s
                      cors:
                        allow_origin: ["*"]
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,authorization
                        max_age: "1728000"
                        expose_headers: grpc-status,grpc-message
                        enabled: true
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.cors
                  - name: envoy.router
  clusters:
    - name: api_gateway
      connect_timeout: 0.25s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts: [{ socket_address: { address: "api_gateway", port_value: 6565 }}]
```
