### ISSUE TITLE
Envoy [TLS/HTTPS] to Envoy [TLS/HTTPS] Failing

### ISSUE THREAD

**Issue by yks0000** [envoyproxy/envoy#9128]
*Title*: ***Envoy to Envoy HTTPS Connection is failing***

*Description*:

We have two Envoy, both running on TLS/HTTPS (say envoy1 and envoy2). Envoy2 connects to actual service which also expose HTTP2. When I make call to envoy2, I get response over https and h2. However when I make call to Envoy1, I get 503 upstream error.

`Envoy1 (Edge/FrontEnd) [listener: 0.0.0.0:443] -> Envoy2 (Service FrontEnd) [listener: 0.0.0.0:8443] -> Service Envoy1 [listener: 0.0.0.0:7000]`

**Response:**

From Envoy2:

```
# curl -i https://localhost:8443/health/local -k;echo
HTTP/2 200
date: Mon, 25 Nov 2019 16:00:59 GMT
content-type: text/plain
x-envoy-upstream-service-time: 0
server: envoy
Health Check Ok
```

From Envoy1:

```
# curl -i https://localhost/health/local -k;echo
HTTP/2 503 
content-length: 95
content-type: text/plain
date: Mon, 25 Nov 2019 16:13:25 GMT
server: envoy
upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

Envoy1 Config:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager 
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: ingress_http
          access_log:
            name: envoy.file_access_log
            config:
              path: /dev/stdout
              format: "- %UPSTREAM_HOST% - [%START_TIME(%d/%m/%YT%H:%M:%S%z %s)%] method=%REQ(:METHOD)% host=%REQ(:AUTHORITY)% txId=%RESP(INTUIT_TID)% request=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% alpn=%PROTOCOL% response_flag=%RESPONSE_FLAGS% ssl_protocol=%DOWNSTREAM_TLS_VERSION% ssl_cipher=%DOWNSTREAM_TLS_CIPHER% status=%RESPONSE_CODE% response_size=%BYTES_SENT% upstream_time_ms=%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% envoy_request_id=%REQ(X-REQUEST-ID)% user-agent=%REQ(USER-AGENT)% xFor=%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT% total_time_ms=%DURATION% gw_time_ms=%RESPONSE_DURATION%\n"
          route_config:
            name: search_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:   
              - match:
                  prefix: "/"
                route:
                  cluster: envoy2
          http_filters:
          - name: envoy.router
            typed_config: {}
      transport_socket:
         name: envoy.transport_sockets.tls
         typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            alpn_protocols: "h2"
            tls_certificates:
                certificate_chain:
                    filename: "/etc/example.crt"
                private_key:
                    filename: "/etc/example.key"
  clusters:
  - name: envoy2
    connect_timeout: 1s
    type: logical_dns 
    dns_lookup_family: V4_ONLY
    lb_policy: round_robin
    load_assignment:
      cluster_name: envoy2
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8443
admin:
  access_log_path: /dev/stdout
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

Envoy1 access log:

```
- 127.0.0.1:8443 - [25/11/2019T16:13:25+0000 1574698405] method=GET host=localhost:443 txId=- request=/health/local alpn=HTTP/2 response_flag=UC ssl_protocol=TLSv1.2 ssl_cipher=ECDHE-RSA-AES128-GCM-SHA256 status=503 response_size=95 upstream_time_ms=- envoy_request_id=f61762bf-8866-475a-ba7a-da5edda2ebe4 user-agent=curl/7.61.1 xFor=127.0.0.1 total_time_ms=1 gw_time_ms=-
```

I am sure, there is something missing in `cluster` config, but what exactly not sure. 

Apart from above, I have another question if Envoy can make H2 call to upstream which is on non ssl [Upstream support h2].
