### ISSUE TITLE
Reverse Proxy - from Nginx to envoyproxy

### ISSUE THREAD

**Issue by Guigouu** [envoyproxy/envoy#9170]
*Description*:
I am using currently some Nginx reverse proxy with mod "proxy_pass" to forward http listener to https remote public site, I would like to know what is the equivalent with envoyproxy? 

I tried many of examples, some of them give me 404, 400 or no healthy upstream...no one worked.

for example:
`static_resources:
  listeners:
  - name: fortio
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          generate_request_id: false
          route_config:
            name: emote_site_route
            virtual_hosts:
            - name: remote_site_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: remote_site
          http_filters:
          - name: envoy.router
            config:
              dynamic_stats: false
  clusters:
  - name: remote_site
    connect_timeout: 0.25s
    hosts:
    - socket_address:
        address: public_site
        port_value: 443`

To resume the process: HTTP Client request -> HTTP listener Reverse Envoy Proxy -> Remote site HTTPS. Do you have any solution, thank you.

**Comment by Guigouu** [comment]
```
admin:
   access_log_path: /tmp/admin_access.log
   address:
     socket_address: { address: 0.0.0.0, port_value: 9901 }
 static_resources:
   listeners:
   - address:
       socket_address:
         address: 0.0.0.0
         port_value: ${ENVOYPROXY_PORT_LISTENER}
     filter_chains:
     - filters:
       - name: envoy.http_connection_manager
         config:
           access_log:
             name: envoy.file_access_log
             config:
               path: /var/log/envoy.log
           stat_prefix: ingress_http
           route_config:
             name: local_route
             virtual_hosts:
             - name: backend
               domains: ["*"]
               routes:
               - match:
                   #prefix: /
                   prefix: ${API_PREFIX}
                 route:
                   cluster: upstream
                   prefix_rewrite: /
                   auto_host_rewrite: true
           http_filters:
           - name: envoy.router
   clusters:
   - name: upstream
     connect_timeout: 1s
     type: strict_dns
     lb_policy: round_robin
     # http2_protocol_options: {} ## UNCOMMENT ME FOR TROUBLE
     respect_dns_ttl: true
     tls_context:
       sni: ${API_HOST}
     load_assignment:
       cluster_name: upstream
       endpoints:
       - lb_endpoints:
         - endpoint:
             address:
               socket_address:
                 address: ${API_HOST}
                 port_value: ${API_PORT}
                 protocol: TCP
 
```

This example works for me.
