### ISSUE TITLE
Fault filter: allows the user to configure the header and body returned by 'FaultAbort'

### ISSUE THREAD

**Issue by wbpcode** [envoyproxy/envoy#9178]
Fault filter can only customize response code of abort. However, in actual use, we sometimes need to customize the header and body returned by abort.
Now I want to be able to extend this plugin, but it's unclear if anyone in the community is already doing related work.

**Comment by dio** [comment]
> we sometimes need to customize the header and body returned by the abort. `FaultFilter::abortWithHTTPStatus()`

For my own education, could you expand more why we need this? (if it is really useful, probably will be a good addition in our docs on how people can potentially leverage the usage of this fault filter).

@wbpcode I think you can propose the config for it.

**Comment by wbpcode** [comment]
@dio We use fault filter to limit the number of requests based on a percentage. Here is a example config snippet:
```
abort:
  http_status: 403
  headers:
  - key: why
    value: "no why"
  - key: "xxx"
    value: "yyy"
  body:
    inline_string: "There is some error. Please retry."
  percentage:
    numerator: 50
    denominator: HUNDRED
```
In the above configuration, only 50% of the traffic will be processed by the backend. But for the other 50% of requests that were "aborted", we still hope to provide some more friendly information. For example, a prompt string, or a fixed HTML page, not just an error code. We currently implement this feature on our own branch and think it is very useful.

In addition, since abort provides the ability to customize the response code, it should be reasonable to provide the ability to customize the header and body. Users can choose to use it or not.
