### ISSUE TITLE
redis_proxy: NOAUTH Authentication required while auth ok return

### ISSUE THREAD

**Issue by denghuancong** [envoyproxy/envoy#9179]
*Title*:  (error) NOAUTH Authentication required while auth ok return 

*Description*:
> login the envoy proxy, auth return ok but when type set cmd ,it return error

*Config*:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 33336
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
            enable_redirection: "true"
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
          downstream_auth_password:
            inline_string: "123456"
  clusters:
  - name: redis_cluster
    connect_timeout: 1s
    type: strict_dns # static
    lb_policy: MAGLEV
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: dhc-cc-test.cc-test.svc.cluster.local
                port_value: 6379

admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 33337
```

*Logs*:
```
[root@10-25-83-4 envoy]# redis-cli -h 10.25.152.90 -p 33310 -c -a 123456
10.25.152.90:33310> auth 123
(error) ERR invalid password
10.25.152.90:33310> auth 123456
OK
10.25.152.90:33310> set aaa 123
(error) NOAUTH Authentication required.
10.25.152.90:33310>
```

*admin cmd output *:
```
redis_cluster::default_priority::max_connections::1024
redis_cluster::default_priority::max_pending_requests::1024
redis_cluster::default_priority::max_requests::1024
redis_cluster::default_priority::max_retries::3
redis_cluster::high_priority::max_connections::1024
redis_cluster::high_priority::max_pending_requests::1024
redis_cluster::high_priority::max_requests::1024
redis_cluster::high_priority::max_retries::3
redis_cluster::added_via_api::false
redis_cluster::10.25.232.175:6379::cx_active::0
redis_cluster::10.25.232.175:6379::cx_connect_fail::0
redis_cluster::10.25.232.175:6379::cx_total::0
redis_cluster::10.25.232.175:6379::rq_active::0
redis_cluster::10.25.232.175:6379::rq_error::0
redis_cluster::10.25.232.175:6379::rq_success::0
redis_cluster::10.25.232.175:6379::rq_timeout::0
redis_cluster::10.25.232.175:6379::rq_total::0
redis_cluster::10.25.232.175:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.232.175:6379::health_flags::healthy
redis_cluster::10.25.232.175:6379::weight::1
redis_cluster::10.25.232.175:6379::region::
redis_cluster::10.25.232.175:6379::zone::
redis_cluster::10.25.232.175:6379::sub_zone::
redis_cluster::10.25.232.175:6379::canary::false
redis_cluster::10.25.232.175:6379::priority::0
redis_cluster::10.25.232.175:6379::success_rate::-1
redis_cluster::10.25.232.175:6379::local_origin_success_rate::-1
redis_cluster::10.25.35.221:6379::cx_active::0
redis_cluster::10.25.35.221:6379::cx_connect_fail::0
redis_cluster::10.25.35.221:6379::cx_total::0
redis_cluster::10.25.35.221:6379::rq_active::0
redis_cluster::10.25.35.221:6379::rq_error::0
redis_cluster::10.25.35.221:6379::rq_success::0
redis_cluster::10.25.35.221:6379::rq_timeout::0
redis_cluster::10.25.35.221:6379::rq_total::0
redis_cluster::10.25.35.221:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.35.221:6379::health_flags::healthy
redis_cluster::10.25.35.221:6379::weight::1
redis_cluster::10.25.35.221:6379::region::
redis_cluster::10.25.35.221:6379::zone::
redis_cluster::10.25.35.221:6379::sub_zone::
redis_cluster::10.25.35.221:6379::canary::false
redis_cluster::10.25.35.221:6379::priority::0
redis_cluster::10.25.35.221:6379::success_rate::-1
redis_cluster::10.25.35.221:6379::local_origin_success_rate::-1
redis_cluster::10.25.230.16:6379::cx_active::0
redis_cluster::10.25.230.16:6379::cx_connect_fail::0
redis_cluster::10.25.230.16:6379::cx_total::0
redis_cluster::10.25.230.16:6379::rq_active::0
redis_cluster::10.25.230.16:6379::rq_error::0
redis_cluster::10.25.230.16:6379::rq_success::0
redis_cluster::10.25.230.16:6379::rq_timeout::0
redis_cluster::10.25.230.16:6379::rq_total::0
redis_cluster::10.25.230.16:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.230.16:6379::health_flags::healthy
redis_cluster::10.25.230.16:6379::weight::1
redis_cluster::10.25.230.16:6379::region::
redis_cluster::10.25.230.16:6379::zone::
redis_cluster::10.25.230.16:6379::sub_zone::
redis_cluster::10.25.230.16:6379::canary::false
redis_cluster::10.25.230.16:6379::priority::0
redis_cluster::10.25.230.16:6379::success_rate::-1
redis_cluster::10.25.230.16:6379::local_origin_success_rate::-1
redis_cluster::10.25.94.85:6379::cx_active::0
redis_cluster::10.25.94.85:6379::cx_connect_fail::0
redis_cluster::10.25.94.85:6379::cx_total::0
redis_cluster::10.25.94.85:6379::rq_active::0
redis_cluster::10.25.94.85:6379::rq_error::0
redis_cluster::10.25.94.85:6379::rq_success::0
redis_cluster::10.25.94.85:6379::rq_timeout::0
redis_cluster::10.25.94.85:6379::rq_total::0
redis_cluster::10.25.94.85:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.94.85:6379::health_flags::healthy
redis_cluster::10.25.94.85:6379::weight::1
redis_cluster::10.25.94.85:6379::region::
redis_cluster::10.25.94.85:6379::zone::
redis_cluster::10.25.94.85:6379::sub_zone::
redis_cluster::10.25.94.85:6379::canary::false
redis_cluster::10.25.94.85:6379::priority::0
redis_cluster::10.25.94.85:6379::success_rate::-1
redis_cluster::10.25.94.85:6379::local_origin_success_rate::-1
redis_cluster::10.25.230.247:6379::cx_active::1
redis_cluster::10.25.230.247:6379::cx_connect_fail::0
redis_cluster::10.25.230.247:6379::cx_total::1
redis_cluster::10.25.230.247:6379::rq_active::0
redis_cluster::10.25.230.247:6379::rq_error::0
redis_cluster::10.25.230.247:6379::rq_success::0
redis_cluster::10.25.230.247:6379::rq_timeout::0
redis_cluster::10.25.230.247:6379::rq_total::1
redis_cluster::10.25.230.247:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.230.247:6379::health_flags::healthy
redis_cluster::10.25.230.247:6379::weight::1
redis_cluster::10.25.230.247:6379::region::
redis_cluster::10.25.230.247:6379::zone::
redis_cluster::10.25.230.247:6379::sub_zone::
redis_cluster::10.25.230.247:6379::canary::false
redis_cluster::10.25.230.247:6379::priority::0
redis_cluster::10.25.230.247:6379::success_rate::-1
redis_cluster::10.25.230.247:6379::local_origin_success_rate::-1
redis_cluster::10.25.34.121:6379::cx_active::0
redis_cluster::10.25.34.121:6379::cx_connect_fail::0
redis_cluster::10.25.34.121:6379::cx_total::0
redis_cluster::10.25.34.121:6379::rq_active::0
redis_cluster::10.25.34.121:6379::rq_error::0
redis_cluster::10.25.34.121:6379::rq_success::0
redis_cluster::10.25.34.121:6379::rq_timeout::0
redis_cluster::10.25.34.121:6379::rq_total::0
redis_cluster::10.25.34.121:6379::hostname::dhc-cc-test.cc-test.svc.cluster.local
redis_cluster::10.25.34.121:6379::health_flags::healthy
redis_cluster::10.25.34.121:6379::weight::1
redis_cluster::10.25.34.121:6379::region::
redis_cluster::10.25.34.121:6379::zone::
redis_cluster::10.25.34.121:6379::sub_zone::
redis_cluster::10.25.34.121:6379::canary::false
redis_cluster::10.25.34.121:6379::priority::0
redis_cluster::10.25.34.121:6379::success_rate::-1
redis_cluster::10.25.34.121:6379::local_origin_success_rate::-1
```
