### ISSUE TITLE
Question: Can we configure ALPN on PATH based?

### ISSUE THREAD

**Issue by yks0000** [envoyproxy/envoy#9180]
**Issue Template**

*Title*: *Can we configure Envoy Upstream ALPN on PATH based*

*Description*:
I have Envoy behind AWS NLB (Network Load Balancer) with TCP Listener. NLB can have Health Check communicate to EC2 only on HTTP1.1 _[Use of TCP Health Check is not really recommended]_. As I we want to restrict codec_type to http2 only, Is it possible to setup http1.1 only for /health route so that NLB Health Check can connect to it on same listener port (443) and all other path follow strict h2.

/health goes to Upstream 

Current Used Config:

```yaml
static_resources:
    listeners:
        address:
            socket_address:
                address: 0.0.0.0
                port_value: 443
        filter_chains:
            filters:
            -   name: envoy.http_connection_manager
                typed_config:
                    '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                    codec_type: auto
                    use_remote_address: true
                    stat_prefix: gateway_ingress_http
                    access_log:
                        name: envoy.file_access_log
                        config:
                            path: /var/log/envoy/access.log
                            format: "[%START_TIME(%d/%m/%YT%H:%M:%S%z %s)%] method=%REQ(:METHOD)%\
                                \ authority=%REQ(:AUTHORITY)% txId=%RESP(TNX_ID)%\
                                \ request=%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% alpn=%PROTOCOL%\
                                \ response_flag=%RESPONSE_FLAGS% ssl_protocol=%DOWNSTREAM_TLS_VERSION%\
                                \ ssl_cipher=%DOWNSTREAM_TLS_CIPHER% status=%RESPONSE_CODE%\
                                \ request_size=%BYTES_RECEIVED% response_size=%BYTES_SENT%\
                                \ envoy_request_id=%REQ(X-REQUEST-ID)% user-agent=%REQ(USER-AGENT)%\
                                \ xFor=%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT% x-envoy-upstream-service-time=%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%\
                                \ total_time_ms=%DURATION% upstream_cluster=%UPSTREAM_CLUSTER%\
                                \ upstream=%UPSTREAM_HOST%\n"
                    route_config:
                        name: gateway_portless
                        virtual_hosts:
                        -   name: gateway_portless
                            domains:
                            -   '*'
                            routes:
                            -   match:
                                    prefix: /
                                route:
                                    cluster: gateway_portless
                    http_filters:
                    -   name: envoy.gzip
                        typed_config: {}
                    -   name: envoy.grpc_web
                        typed_config: {}
                    -   name: envoy.grpc_http1_bridge
                        typed_config: {}
                    -   name: envoy.router
                        typed_config: {}
            transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                    '@type': type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
                    common_tls_context:
                        tls_params:
                            tls_maximum_protocol_version: TLSv1_3
                            tls_minimum_protocol_version: TLSv1_2
                        alpn_protocols: h2
                        tls_certificates:
                        -   certificate_chain:
                                filename: /etc/envoy/ssl/sw10.crt
                            private_key:
                                filename: /etc/envoy/ssl/sw10.key
    clusters:
    -   name: gateway_portless
        http2_protocol_options: {}
        connect_timeout: 1s
        type: static
        dns_lookup_family: V4_ONLY
        lb_policy: round_robin
        load_assignment:
            cluster_name: gateway_portless
            endpoints:
            -   lb_endpoints:
                -   endpoint:
                        address:
                            socket_address:
                                address: 127.0.0.1
                                port_value: 7000
admin:
    access_log_path: /var/log/envoy/admin.log
    address:
        socket_address:
            address: 127.0.0.1
            port_value: 6000
```

or, if there is any alternate implementation done, please suggest?
