### ISSUE TITLE
Multitagging for Prometheus metrics with regex doesn't work as documented

### ISSUE THREAD

**Issue by truealex81** [envoyproxy/envoy#9238]
**Title: Multitagging for Prometheus metrics with regex doesn't work as documented**

**Description**:
I'm trying to tag some metrics for Prometheus.
My clusters are configured like this one with names containing "@" delimiter
```
      - name: gateway@echo
        connect_timeout: 1s
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: LEAST_REQUEST
        hosts:
          socket_address: 
            address: gateway.echo.svc.cluster.local
            port_value: 8080
```
So, I have stat strings like this one:
`cluster.gateway@echo.assignment_stale: 0`
And now I want to catch 2 tags: `backend=gateway` and `namesp=echo` with following config:
```
    stats_config:
      stats_tags: 
      - tag_name: "backend"
        regex: '^cluster\.(.+)@.+$'
      - tag_name: "namesp"
        regex: '^cluster\.(@(.+?)\.).*$'
```
According to the documentation example 2 (https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/metrics/v2/stats.proto#config-metrics-v2-tagspecifier) first regex should remove matching part `gateway` from metric name producing the following series
`cluster.@echo.assignment_stale: 0`
Second regex should then match `echo` and remove `@echo.` part producing 
`cluster.assignment_stale: 0`

But as a result for Prometheus stats I have only first regex match:
`envoy_cluster__echo_assignment_stale{envoy_cluster_name="gateway@echo",backend="gateway"} 0`
_Note that after "cluster" we have two underscore signs._

**Workaround:**
If we're assuming that the first regex doesn't remove parts from the metric names then it works.
The following config...
```
    stats_config:
      stats_tags: 
      - tag_name: "backend"
        regex: '^cluster\.(.+)@.+$'
      - tag_name: "namesp"
        regex: '^cluster\..+@((.+?)\.).+$'
```
...produces following series:
`envoy_cluster_assignment_stale{envoy_cluster_name="gateway@echo",backend="gateway",namesp="echo"} 0`
Note that even if we didn't remove "@" by regex it disappeared.
