### ISSUE TITLE
Return x-b3-trace id in response

### ISSUE THREAD

**Issue by bluetechy** [envoyproxy/envoy#9243]
*Description*:

Since Zipkin's Lens UI allows one to search on the trace id, it would be helpful if there was a flag in envoy's `typed_config` to include in the response header the `x-b3-traceid`, such as `return_trace_id: true` (similar to the `generate_request_id: true` flag).

For example:

```
tracing:
    http:
        name: envoy.zipkin
        typed_config:
            "@type": type.googleapis.com/envoy.config.trace.v2.ZipkinConfig
            return_trace_id: true
            collector_cluster: zipkin-svc
            collector_endpoint: "/api/v1/spans"
```

Or alternatively in the `tracing` object:

```
                    - name: envoy.http_connection_manager
                      typed_config:
                          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                          generate_request_id: true
                          tracing:
                              operation_name: egress
                              return_trace_id: true
```

so that it could be used to search here:

![Screen Shot 2019-12-05 at 1 52 03 PM](https://user-images.githubusercontent.com/6248629/70273035-8abd8280-1766-11ea-914f-fc58bb33a8df.png)

*Relevant Links*:

* https://github.com/openzipkin/b3-propagation/issues/4

**Comment by dio** [comment]
@bluetechy I'm wondering if `response_headers_to_add` is sufficient for this case:

e.g.

Tried adding it in: `examples/zipkin-tracing/front-envoy-zipkin.yaml`.

```diff
             name: local_route
             virtual_hosts:
             - name: backend
+              response_headers_to_add:
+                - header:
+                    key: x-b3-traceid
+                    value: "%REQ(x-b3-traceid)%"
               domains:
               - "*"
               routes:
```
```
$ # in examples/zipkin-tracing
$ docker-compose up -d
$ curl -I localhost:8000/trace/2
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 89
server: envoy
date: Thu, 05 Dec 2019 21:35:54 GMT
x-envoy-upstream-service-time: 14
x-b3-traceid: e3ca48e615bbc5ee
```

**Comment by bluetechy** [comment]
@dio Yes, I would think that would work nicely.  Is `value: "%REQ(x-b3-traceid)%"` currently supported as I just tried it locally and my pod crashed?  If it is, I will double-check my yaml then to figure out if I got a yaml error or not.

**Comment by dio** [comment]
@bluetechy mind to share your envoy version?

**Comment by bluetechy** [comment]
@dio Yes, sorry....I should have included my version in my last question to you.  Here you go:

![Screen Shot 2019-12-05 at 3 58 38 PM](https://user-images.githubusercontent.com/6248629/70281462-4e931d80-1778-11ea-85d0-385e52eefe66.png)

**Comment by bluetechy** [comment]
@dio Just came across this issue (https://github.com/envoyproxy/envoy/issues/8683) which looks to discuss this same syntax.

**Comment by bluetechy** [comment]
@dio Looks to be a new feature in version 1.13.0 (see https://www.envoyproxy.io/docs/envoy/latest/intro/version_history).

![Screen Shot 2019-12-05 at 4 16 31 PM](https://user-images.githubusercontent.com/6248629/70282301-a6328880-177a-11ea-9ef6-58dab3fa8119.png)

**Comment by dio** [comment]
Yeap. You can use `envoyproxy/envoy-dev:latest` if you are OK with that. 😉

**Comment by dio** [comment]
Since it seems it is answered, I'm closing this.

**Comment by bluetechy** [comment]
@dio I can confirm it does work with using `envoyproxy/envoy-dev:latest` so thank you for the excellent help.  It would be nice that once this is released that the example above that you provided is added to `examples/zipkin-tracing/front-envoy-zipkin.yaml`.  These would be the headers I think are most important:

```
                                    response_headers_to_add:
                                        - header:
                                              key: "x-b3-traceid"
                                              value: "%REQ(x-b3-traceid)%"
                                        - header:
                                              key: "x-request-id"
                                              value: "%REQ(x-request-id)%"
```
