### ISSUE TITLE
Enhance envoy listener TLS to support multiple trust domain

### ISSUE THREAD

**Issue by rbkumar88** [envoyproxy/envoy#9284]
*Title*: *Enhance envoy listener TLS to support multiple trust domain*

*Description*:
Currently the envoy TLS listener configuration only supports mTLS communication only from one trust domain. Would be nice to enhance that to support multiple trust domains so that authN mechanisms like SPIFFE can be leveraged.

**Comment by evan2645** [comment]
I've been getting a lot of questions about this lately. To solve it with a single listener, it is necessary to choose the correct bundle based on the domain of the certificate that's being validated. There are some examples of how to do this in other projects (CA pinning), but I haven't found support for it in Envoy.

I've put a bit of thought into what it could look like. One option is to extend certificate validation context to include a new configurable. It could be SPIFFE-specific, or there may be a way to generalize it further. For instance, we could provide a map of bundles keyed by trust domain name:
```
   tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename": "/cert.crt" }
          private_key: { "filename": "/cert.key" }
        validation_context:
          spiffe_ca:
            "example.org": { “filename”: “example-org.crt” }
            "example.net": { “filename”: “example-net.crt” }
```
When `spiffe_ca` is set, certificates will be validated using the bundle for the relevant trust domain. If the relevant trust domain is not present in the map, then the certificate is not trusted. SPIFFE certificates can only have one URI SAN set.

Alternatively, a more generalized approach could be taken that matches in the same way that `verify_subject_alt_name` matches (related: https://github.com/envoyproxy/envoy/issues/7813). For instance:
```
        validation_context:
          pinned_ca:
            "spiffe://example.org/*": { “filename”: “example-org.crt” }
            "spiffe://example.net/*": { “filename”: “example-net.crt” }
```
One issue with this approach is that there may be more than one name present in the certificate.
