### ISSUE TITLE
What is the correct name of a tls transport socket

### ISSUE THREAD

**Issue by davecheney** [envoyproxy/envoy#9319]
According to the deprecation [documentation](https://www.envoyproxy.io/docs/envoy/v1.12.0/api-v2/api/v2/listener/listener.proto#envoy-api-field-listener-listenerfilter-name), the name of the transport socket should be `tls`

> To setup TLS, set a transport socket with name tls and DownstreamTlsContext in the typed_config. 

However, documentation on the [SNI faq page](https://www.envoyproxy.io/docs/envoy/v1.12.0/faq/configuration/sni#faq-how-to-setup-sni) suggests that the correct name is `envoy.transport_sockets.tls`.
```
- filter_chain_match:
    server_names: "api.example.com"
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
      common_tls_context:
        tls_certificates:
        - certificate_chain: { filename: "api_example_com_cert.pem" }
          private_key: { filename: "api_example_com_key.pem" }
```

Which is correct?
