### ISSUE TITLE
API Request: Add HttpFilter.instance_name

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy#9358]
HttpFilter.name is used to instantiate a specific type of filter by http_connection_manager
In that sense `HttpFilter.name` is the `className` parameter.
In filters like WASM and lua, a filter with the same `name` is deployed multiple times.
This makes it difficult to identify a specific filter instance without resorting to peeking inside `HttpFilter.typed_config`. 

Add 
```proto
message HttpFilter {
  // The name of the filter to instantiate. The name must match a
  // :ref:`supported filter <config_http_filters>`.
  string name = 1 [(validate.rules).string = {min_bytes: 1}];

  string instance_name = 5;

  // ...
}
```

Using `instance_name`, the filter can be identified in a meaningful way.
In the following example, without `instance_name=wasm.stats` both filters have the same name `envoy.filters.http.wasm`.

```yaml
filters:
- name: envoy.http_connection_manager
   typed_config:
    '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
    forward_client_cert_details: APPEND_FORWARD
    generate_request_id: true
    http_filters:
    - instance_name: wasm.stats
      name: envoy.filters.http.wasm
      config:
        config:
          root_id: stats_inbound
          vm_config:
            code:
              inline_string: envoy.wasm.stats
            runtime: envoy.wasm.runtime.null
            vm_id: stats_inbound
    - instance_name: wasm.metadata_exchange
      name: envoy.filters.http.wasm
      config:
        config:
          vm_config:
            code:
              inline_string: envoy.wasm.metadata_exchange
            runtime: envoy.wasm.runtime.null
```

Here

**Comment by mandarjog** [comment]
@kyessenov @rshriram

**Comment by mattklein123** [comment]
My initial sniff test is that this is not generally useful, and I don't see why it's that bad to peak inside the typed_config, but happy to be swayed if there is a convincing argument.

**Comment by kyessenov** [comment]
I think this would be useful for Filter Config discovery service. Having a common field across all filter configs helps in discovery and monitoring IMHO. I don't think it's possible to express that Any in the typed config must have a specific field, so pulling it up one level to filter config seems reasonable:

```yaml
# static config
name: envoy.http.wasm
config_name: wasm1
typed_config: {}
# dynamic config
name: envoy.http.wasm
config_name: wasm1
config_source:
  ads: {}
```
