### ISSUE TITLE
Provide support for certificate rotation for xDS connection in Envoy container images

### ISSUE THREAD

**Issue by tsaarni** [envoyproxy/envoy#9359]
**Problem description**:

The official docker container is used by e.g. Contour ingress controller.

While Contour is able to replace certificates for user plane by using SDS, it is not currently possible to rotate control plane certificates (xDS gRPC interface) without traffic interruption.

**Proposal for a new feature**:

Include a new binary in official Envoy container images at https://hub.docker.com/r/envoyproxy/.  This new binary can be used by deployments to

1) acting as pid 1 in the container and forking & execing `envoy`
2) triggering Envoy's hot restart procedure when certificate or key files are updated

inotify can be used to watch the file updates, which works with e.g. Kubernetes secret volume mounts.

**Implementation alternatives**:

With your guidance, I'd be interested in implementing the above feature and submitting PR.

The default entrypoint can still remain like it is currently.  The new binary could be "opt-in" for deployments that require xDS with TLS and hot-reload.

One implementation alternative would be to extend [hot-restarter.py](https://github.com/envoyproxy/envoy/tree/master/restarter) with inotify, but alternatively new version could be implemented with C++ in order to avoid bringing Python as dependency into all Envoy images.

**Comment by mattklein123** [comment]
@htuch @lizan any thoughts on ^? I understand why this is being requested, but I also wonder if there should be some built-in way for Envoy to rotate control plane certs?

**Comment by tsaarni** [comment]
I was also thinking a bit about built-in way. It can be more elegant - no need to have parent process monitoring childs, no need to run two Envoys during draining period.

Control plane connection is established rarely, so at simplest Envoy could maybe reload certificates unconditionally before connecting, in order to catch updates automatically without watching the files. But since Envoy gRPC client seems to share the TLS related code with data plane, maybe it is not feasible to have this simple approach without impacting performance of data plane?

Furthermore, I saw that Istio uses external way (pilot-agent uses hot restart for control plane certificate reload).

**Comment by htuch** [comment]
Is the root of the issue that the bootstrap has some certs that are necessary before we even are able to do SDS? If so, why not do SDS with a filesystem subscription, you can update this with a move operation. Envoy picks up the inotify event.

**Comment by tsaarni** [comment]
Cool idea!  I tried SDS with filesystem subscription but there are couple of problems:

1. When Kubernetes updates the certificate files, the only inotify event which fires is for a hidden directory `..data`. There is no events for the individual updated certificate files since Kubernetes has set up them as symbolic links that do not change. Since `..data` does not match with any of the file watches, `WatcherImpl::onInotifyEvent()` will just ignore the event and changes will go unnoticed.
2. How can I do SDS subscribe for certificate and key files? I could only configure watches the DiscoveryRequests with Secrets which point to certificate files, but not the certificate files themselves

Here is my cluster for the control plane using SDS config:

```yaml
static_resources:
  clusters:
  - name: control_plane
    type: LOGICAL_DNS
    connect_timeout: 1s
    load_assignment:
      cluster_name: control_plane
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: controlplane
                port_value: 8080
    http2_protocol_options: {}
    transport_socket:
      name: "envoy.transport_sockets.tls"
      typed_config:
        "@type": "type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext"
        common_tls_context:
          tls_certificate_sds_secret_configs:
            sds_config:
              path: /etc/envoy/tls-certificate.yaml
          validation_context_sds_secret_config:
            sds_config:
              path: /etc/envoy/validation-context.yaml
```
and here are the DiscoveryRequest files:

/etc/envoy/tls-certificate.yaml:
```yaml
resources:
  - "@type": "type.googleapis.com/envoy.api.v2.auth.Secret"
    tls_certificate:
      certificate_chain:
        filename: /etc/envoy/envoy.pem
      private_key:
        filename: /etc/envoy/envoy-key.pem
```
/etc/envoy/validation-context.yaml:
```yaml
resources:
  - "@type": "type.googleapis.com/envoy.api.v2.auth.Secret"
    validation_context:
      trusted_ca:
        filename: /etc/envoy/control-plane-root.pem
```

To overcome problem 2,  I could use `inline_string` instead of `filename` to inline the certificates and key into the DiscoveryRequest files.  But I think user should only configure pem files so then I should run some software to actively monitor updates and convert from pem files to DiscoveryRequest. 

Any ideas / recommendations more than welcome!
