### ISSUE TITLE
503 Connection pool errors

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#9386]
*Description*:

Hi, we've been running load tests through Envoy which is running as a sidecar to our nodejs server. 
Most of the requests are good, except in all of our tests there is a point where Envoy seems to temporarily drop its connections to the upstream (the nodejs server). 

From the stats I see "upstream_rq_pending_failure_eject" is the culprit of these failures which is described as "Total requests that were failed due to a connection pool connection failure" 

What does this exactly mean, and what can we do to avoid these errors? 

*Admin and Stats Output*:

As this is not our development environment, I do not have direct access to the Envoy stats, and I can only view them through Grafana.

*Config*:

```
  clusters:
  - name: xxxxxxxxx
    connect_timeout: 1s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: xxxxxxxxxxx
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost.ssl
                port_value: 8443
    tls_context:
      common_tls_context:
        validation_context:
          trusted_ca: { filename: "xxxxxxxxxxx" }
```

*Logs*:
Sample access log: 

> [2019-12-17T16:33:31.362Z] "GET /xxxxx/ HTTP/1.1" 503 UF 0 91 0 - "xx.xxx.xxx.xxx" "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)" "c60e035b-157b-98d5-a11d-3610acd7effc" "xxxxxx.com" "127.0.0.1:8443"
