### ISSUE TITLE
JSON transcoding. When I send wrong url parameter name, the response returns 404

### ISSUE THREAD

**Issue by DenisGlot** [envoyproxy/envoy#9395]
And no other data provided. So the rest users have no idea why the request failed.
I tried to specify `query_parameters` as an empty array. Didn't work out

Is should return 400.  
It'd be great to have a json body with errors describing the situation with mapping.
It also could transcode what request have to grpc, since all fields in protobuf are optional. And the server will give a comprehensive response.

envoy config

```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address: { address: 0.0.0.0, port_value: 51051 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                codec_type: auto
                stat_prefix: grpc_json
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/", grpc: {}, query_parameters: [] }
                          route:
                            cluster: local_cluster
                            timeout: { seconds: 60 }
                      cors:
                        allow_origin:
                          - "*"
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,authorization,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                        max_age: "1728000"
                        expose_headers: grpc-status,grpc-message
                http_filters:
                  - name: envoy.grpc_json_transcoder
                    config:
                      proto_descriptor: "/path/to/descriptor.pb"
                      services: ["pile.of.services.MyService"]
                      print_options:
                        add_whitespace: true
                        always_print_primitive_fields: true
                        always_print_enums_as_ints: false
                        preserve_proto_field_names: false
                  - name: envoy.cors
                  - name: envoy.router
  clusters:
    - name: local_cluster
      connect_timeout: 2s
      type: logical_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      hosts: [{ socket_address: { address: "my.host", port_value:8080 }}]
```
