### ISSUE TITLE
Feature: Queue manager for circuit breaker queue

### ISSUE THREAD

**Issue by lcabancla** [envoyproxy/envoy#9606]
Currently, circuit breakers enqueue pending requests. A queue manager can be added to manage this queue. For example, algorithms like Adaptive LIFO with CoDel (see links below) have been shown to work well in large systems. 

A possible configuration is below.

```
circuit_breakers:
      thresholds:
        - max_connections: 10
          max_pending_requests: 20
          max_requests: 10
          max_retries: 10
     queue_manager: adaptive_lifo_with_codel
         config:
            queue_size_threshold: 10
            low_timeout: 100
            high_timeout: 500
```       

Links:
[Adaptive LIFO with Codel ACM talk (video)](https://queue.acm.org/detail.cfm?id=2839461)
[Summary of talk](https://blog.acolyer.org/2015/11/19/fail-at-scale-controlling-queue-delay/)
