### ISSUE TITLE
listener TCP backlog queue length isn't equal to Linux defined net.core.somaxconn

### ISSUE THREAD

**Issue by Lookyan** [envoyproxy/envoy#9659]
I'm experiencing problems with establishing connections to envoy at a high rate of requests. The first assumption is that we run out of TCP backlog queue for the listener. The default value for net.core.somaxconn is 128. We changed it using sysctl for container to 32428. But when envoy starts and binds to listen 15001 port for incoming connections we can see that this queue is at the previous value 128:
```
ss -ntpl
State      Recv-Q Send-Q               Local Address:Port                              Peer Address:Port
LISTEN     0      128                              *:7313                                         *:*
LISTEN     0      128                              *:15001                                        *:*
LISTEN     0      128                              *:9156                                         *:*
LISTEN     0      32428                           :::14956                                       :::*
LISTEN     0      32428                           :::14957                                       :::*
```

7313, 15001, 9156 are envoy ports. 14956, 14957 are golang service ports, which have the desired value.

Listener is defined statically:
```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 15001
    filter_chains:
    - filters:
      - name: envoy.tcp_proxy
        config:
          cluster: "BlackHoleCluster"
          stat_prefix: "BlackHoleCluster"
    use_original_dst: true
```

Version of envoy:
```
curl 127.0.0.1:9156/server_info
{
 "version": "7a12f379e47a9f7cf7211c727fe8fc70b6a0a9ab/1.11.2/Clean/RELEASE/BoringSSL",
 "state": "LIVE",
 "command_line_options": {
  "base_id": "0",
  "concurrency": 30,
  "config_path": "/envoy/envoy.yaml",
  "config_yaml": "",
  "allow_unknown_fields": false,
  "admin_address_path": "",
  "local_address_ip_version": "v4",
  "log_level": "info",
  "component_log_level": "",
  "log_format": "[%Y-%m-%d %T.%e][%t][%l][%n] %v",
  "log_path": "",
  "hot_restart_version": false,
  "service_cluster": "cluster",
  "service_node": "service-name",
  "service_zone": "",
  "mode": "Serve",
  "max_stats": "0",
  "max_obj_name_len": "0",
  "disable_hot_restart": false,
  "enable_mutex_tracing": false,
  "restart_epoch": 0,
  "cpuset_threads": false,
  "file_flush_interval": "10s",
  "drain_time": "600s",
  "parent_shutdown_time": "900s"
 },
 "uptime_current_epoch": "175950s",
 "uptime_all_epochs": "175950s"
}
```
