### ISSUE TITLE
Tutorial on TLS is not working on the website

### ISSUE THREAD

**Issue by Skarlso** [envoyproxy/envoy#9662]
Following the tutorial here: 
https://www.envoyproxy.io/learn/ssl

I've got this error:

```
front-envoy_1  | [2020-01-12 07:54:22.719][6][critical][main] [source/server/server.cc:94] error initializing configuration '/etc/front-envoy.yaml': Protobuf message (type envoy.config.bootstrap.v3alpha.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[1]) tls_context: Cannot find field.) has unknown fields
front-envoy_1  | [2020-01-12 07:54:22.719][6][info][main] [source/server/server.cc:595] exiting
front-envoy_1  | Protobuf message (type envoy.config.bootstrap.v3alpha.Bootstrap reason INVALID_ARGUMENT:(static_resources.listeners[0].filter_chains[1]) tls_context: Cannot find field.) has unknown fields
```

With this settings  on the envoy front-end:

```yaml
    - tls_context:
      common_tls_context:
        tls_certificates:
          - certificate_chain:
              filename: "/etc/listener.crt"
            private_key:
              filename: "/etc/listener.key"
```

**Comment by htuch** [comment]
@Skarlso what is the full bootstrap you are using? Looks like Envoy is viewing this as a v3 YAML, where `tls_context` is deprecated in favor of TLS transport extension configuration.

**Comment by htuch** [comment]
@caniszczyk @mattklein123 who is responsible for keeping https://www.envoyproxy.io/learn/ssl etc. up-to-date going forward given that Turbine Labs are no longer around?

**Comment by Skarlso** [comment]
Hi @htuch! Thank you for jumping in. It turns out that I didn't indent it correctly. :( It was under filter_chains instead of filters. I switched to the new form of doing this: 

```yaml
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.api.v2.auth.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: "/etc/example-com.crt"
              private_key:
                filename: "/etc/example-com.key"
```

Since it say tls_context is deprecated anyways. :)

But I'll keep an eye out for things. Also, thank you for your help and sorry, I didn't close this issue before hand. I think I can consider it resolved. :)
