### ISSUE TITLE
mirroring breaks when the destination cluster doesn't exist

### ISSUE THREAD

**Issue by rgs1** [envoyproxy/envoy#9698]
Consider the following route config:

```
    - match:
        prefix: "/foo"
      route:
        cluster: "does_not_exist"
        request_mirror_policy:
          cluster: "mirror_cluster_does_exist"
          runtime_fraction:
            runtime_key: "mirror_key"
            default_value:
              numerator: 100
              denominator: "HUNDRED"
```

where the `does_not_exist`destination cluster isn't present. Is the expectation
for mirroring to still work? It currently doesn't.

I guess one could argue that, if the destination cluster doesn't exist then the route
is effectively broken and thus mirroring is broken too.

If this the case, we can tight up the docs to make that clear. If we still want mirroring
to work, even when the destination cluster is missing, I'll send a PR to handle that.

Thoughts?

cc: @derekargueta
