### ISSUE TITLE
Upstream connections don't increase beyond a certain point

### ISSUE THREAD

**Issue by sunit-saavn** [envoyproxy/envoy#9789]
*Title*: *Redis Cluster - Upstream connections don't increase beyond a certain point*

*Description*:
I am trying to use envoy as a connection pooler for a redis cluster. To load test the setup I am using redis-benchmark to fire concurrent requests. The problem is even after setting up >5000 concurrent connections on redis-benchmark the number of upstream connections opened (as reported by /stats) by envoy is around 18-20. The requests take a lot of time to complete, average time is beyond 1s. If I decrease the concurrency of requests to 80 then the latencies are within 100ms. 

*Redis-Benchmark command* : 
`redis-benchmark  -n 100 -k 0 -t ping,set,get,hget,hgetall -c 8000 -l -h <host>` 
Sample output: 
```
====== PING_BULK ======
  100 requests completed in 6.25 seconds
  8000 parallel clients
  3 bytes payload
  keep alive: 0

1.00% <= 61 milliseconds
2.00% <= 6244 milliseconds
5.00% <= 6245 milliseconds
41.00% <= 6246 milliseconds
86.00% <= 6247 milliseconds
100.00% <= 6247 milliseconds
16.00 requests per second

====== SET ======
  100 requests completed in 6.25 seconds
  8000 parallel clients
  3 bytes payload
  keep alive: 0

1.00% <= 62 milliseconds
2.00% <= 6246 milliseconds
9.00% <= 6247 milliseconds
46.00% <= 6248 milliseconds
79.00% <= 6249 milliseconds
100.00% <= 6249 milliseconds
15.99 requests per second

====== GET ======
  100 requests completed in 6.25 seconds
  8000 parallel clients
  3 bytes payload
  keep alive: 0

1.00% <= 61 milliseconds
2.00% <= 6245 milliseconds
26.00% <= 6246 milliseconds
59.00% <= 6247 milliseconds
98.00% <= 6248 milliseconds
100.00% <= 6248 milliseconds
16.00 requests per second 
```

*Admin and Stats Output*:
listener.0.0.0.0_6379.downstream_cx_active: 5656
listener.0.0.0.0_6379.downstream_cx_destroy: 2516157
listener.0.0.0.0_6379.downstream_cx_total: 2521813
listener.0.0.0.0_6379.downstream_pre_cx_active: 0
listener.0.0.0.0_6379.downstream_pre_cx_timeout: 0

cluster.redis_cluster.upstream_cx_active: 18
cluster.redis_cluster.upstream_rq_timeout: 0
cluster.redis_cluster.upstream_rq_total: 14019

*Config*:
```
static_resources:
  listeners:
  - name: redis_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
    - filters:
      - name: envoy.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.redis_proxy.v2.RedisProxy
          stat_prefix: egress_redis
          settings:
            op_timeout: 5s
            enable_redirection: true
            read_policy: PREFER_REPLICA
          prefix_routes:
            catch_all_route:
              cluster: redis_cluster
  clusters:
  - name: redis_cluster
    connect_timeout: 1s
    #type: strict_dns # static
    lb_policy: ROUND_ROBIN
    circuit_breakers:
      thresholds:
        - priority : high
          max_connections: 1000
          max_connection_pools: 100
          max_pending_requests: 1000
          track_remaining: true
        - priority : default
          max_connections: 1000
          max_connection_pools: 100
          max_pending_requests: 1000
          track_remaining: true
    cluster_type:
      name: envoy.clusters.redis
      typed_config:
        "@type": type.googleapis.com/google.protobuf.Struct
        value:
          cluster_refresh_rate: 5s
          cluster_refresh_timeout: 0.5s
          redirect_refresh_interval: 10s
          redirect_refresh_threshold: 10
    load_assignment:
      cluster_name: redis_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <host>
                port_value: 6379
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```
