### ISSUE TITLE
gRPC message conversion seems dependent on config cluster specification

### ISSUE THREAD

**Issue by catper** [envoyproxy/envoy#9796]
*Title: gRPC message isn't always converted*

I've created a simple gRPC greeting service and am running it on minikube together with an Envoy config based on the gRPC-JSON transcoder config reference (https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_json_transcoder_filter) anda am seeing some strange behaviour.

*Config*
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: listener1
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                stat_prefix: grpc_json
                codec_type: AUTO
                access_log:
                  - name: envoy.file_access_log
                    config:
                      path: "/var/log/access.log"
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/example.HelloService" }
                          route: { cluster: hello, timeout: { seconds: 60 } }
                http_filters:
                  - name: envoy.grpc_json_transcoder
                    config:
                      proto_descriptor: "/tmp/envoy/hello_service.pb"
                      convert_grpc_status: true
                      services: ["example.HelloService"]
                      print_options:
                        add_whitespace: true
                        always_print_primitive_fields: true
                        preserve_proto_field_names: true
                  - name: envoy.router

  clusters:
    - name: hello
      connect_timeout: 1.5s
      type: logical_dns
      lb_policy: round_robin
      dns_lookup_family: V4_ONLY
      http2_protocol_options: {}
      load_assignment:
        cluster_name: hello
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9090


```

With this setup, routing doesn't work correctly: the cluster address of 127.0.0.1 results in Envoy returning "connection failure" and the same thing happens with ip 0.0.0.0. Using host.docker.internal and gateway.docker.internal in turn returns a response of “no healthy upstream”. The good part is that the gRPC error is mapped as expected:

```
{
    "code": 14,
    "message": "upstream connect error or disconnect/reset before headers. reset reason: connection failure",
    "details": []
}
```
Playing around with connection timeout and keep alive options etc. doesn't make a difference.

The only way I can get the routing to work is by naming the service explicitly

```
load_assignment:
        cluster_name: hello
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: hello-service.default.svc.cluster.local
                      port_value: 9090

```
and while I have no issue with having to do this it is my impression that it should not be required. More importantly though, when I do name the service explicitly, conversion of the gRPC error message no longer works:

<img width="1029" alt="Screenshot 2020-01-23 at 13 38 21" src="https://user-images.githubusercontent.com/60221155/72985851-32f6db80-3de7-11ea-94dc-e55f7632a0e8.png">

I imagine that the error may very well lie with me and my config rather than with Envoy but I can’t seem to find a way around this and so am reporting it. If anyone can shed any light on why this is happening it would be greatly appreciated. Thanks!
