### ISSUE TITLE
Custom request_headers_to_add Authorization header being ignored

### ISSUE THREAD

**Issue by rsmck** [envoyproxy/envoy#9815]
When setting an Authorization header with `request_headers_to_add` to authenticate against the application behind the proxy this works as expected unless an Authorization header is passed by the user (e.g. in response to ext_authz) when it overwrites the header specified in `request_headers_to_add`

Example config below, I expect the value of the Authorization header to be sent to the backend on https://aptest.localdomain/ irrespective of what the uses authenticated to Envoy with;

```
static_resources:
  listeners:
  - name: http
    address:
      socket_address: { address: 0.0.0.0, port_value: 443 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          use_remote_address: true
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/app/" }
                request_headers_to_add:
                - header:
                   key: "Authorization"
                   value: "Basic cm9zcy1tY3142GxvcDoqY3J4OD3eNg=="
                route: { host_rewrite: "apptest.localdomain", cluster: appserver }
          http_filters:
          - name: envoy.ext_authz
            config:
              http_service:
                server_uri:
                  uri: 127.0.0.1:5757
                  cluster: ext-authz
                  timeout: 0.25s
          - name: envoy.router
      tls_context:
        common_tls_context:
          tls_certificates:
           - certificate_chain:
               filename: "/etc/envoy/tls.crt"
             private_key:
               filename: "/etc/envoy/tls.key"
  clusters:
  - name: ext-authz
    connect_timeout: 0.5s
    type: strict_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 5757
  - name: appserver
    connect_timeout: 2s
    type: STATIC
    lb_policy: ROUND_ROBIN
    hosts: [{ socket_address: { address: 10.0.21.3, port_value: 443 }}]
    tls_context:
      common_tls_context:
        tls_certificates:
          certificate_chain: { "filename": "/etc/envoy/tls.crt" }
          private_key: { "filename": "/etc/envoy/tls.key" }
        validation_context:
          trusted_ca:
            filename: /etc/ssl/certs/ca-certificates.crt
```
