### ISSUE TITLE
Example for overriding use of deprecated features?

### ISSUE THREAD

**Issue by jaegchoi** [envoyproxy/envoy#9823]
This section here describes the use of the runtime configuration to enable the use of deprecated features:

 https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features
> In the second phase the field will be tagged as disallowed_by_default and use of that configuration field will cause the config to be rejected by default. This disallowed mode can be overridden in runtime configuration by setting envoy.deprecated_features:full_fieldname or envoy.deprecated_features:full_enum_value to true. For example, for a deprecated field Foo.Bar.Eep set envoy.deprecated_features:Foo.bar.Eep to true

Can anyone provide an example of this? Specifically I'd like to be able to use the Zipkin tracing config with HTTP_JSON_V1 for a little while until we can update our Jaeger collector configuration. 

```
tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: jaeger
      collector_endpoint: @COLLECTOR_ENDPOINT@
      collector_endpoint_version: HTTP_JSON_V1
```

I know that the link above has examples for configuring the Runtime with layers but I don't understand where envoy.deprecated_features:full_fieldname would fit in

**Comment by mattklein123** [comment]
@htuch can you potentially weave this into the version upgrade FAQ that you are building? cc @alyssawilk also in case she prefers to do this after you build the structure. I agree this is something we have to better document.

**Comment by jaegchoi** [comment]
@alyssawilk Do you know what the configuration might look like when it's just one enum value that is deprecated?
I've tried this along with other variations involving the actual enum (HTTP_JSON_V1) but none seem to work: 

```
layered_runtime:
  layers:
  - name: static_layer
    static_layer:
      envoy.deprecated_features:envoy.config.trace.v3.ZipkinConfig.hidden_envoy_deprecated_collector_endpoint_version: true
```

The error I'm getting is this: 

>       Proto constraint validation failed (Using the default now-deprecated value HTTP_JSON_V1 for enum 'envoy.config.trace.v2.ZipkinConfig.collector_endpoint_version' from file trace.proto. This enum value will be removed from Envoy soon so a non-default value must now be explicitly set. Please see https://www.envoyproxy.io/docs/envoy/latest/intro/deprecated for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.)
