### ISSUE TITLE
gzip filter and per_connection_buffer_limit_bytes not supported in envoy version 1.12.2

### ISSUE THREAD

**Issue by Vinutha-Garimella** [envoyproxy/envoy#9847]
*Title*: *gzip filter and per_connection_buffer_limit_bytes*

*Description*:
I installed envoy version 1.12.2 and validated my envoy.yaml file, I keep getting these errors while validating envoy.yaml file.
Error: Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[1]) gzip: Cannot find field.) has unknown fields

**Bug Template**

*Title*: *Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT*

*Description*:
Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[1]) gzip: Cannot find field.) has unknown fields
Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[1]) per_connection_buffer_limit_bytes: Cannot find field.) has unknown fields
envoy validation should have been successful, the same syntax works in 1.11.1
*Repro steps*:
> add gzip filter and per_connection_buffer_limit_bytes fields in route configuration of envoy

*Admin and Stats Output*:
envoy -c envoy.yaml -l debug
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:249] initializing epoch 0 (hot restart version=disabled)
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:251] statically linked extensions:
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:253]   access_loggers: envoy.file_access_log,envoy.http_grpc_access_log,envoy.tcp_grpc_access_log
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:256]   filters.http: envoy.buffer,envoy.cors,envoy.csrf,envoy.ext_authz,envoy.fault,envoy.filters.http.adaptive_concurrency,envoy.filters.http.dynamic_forward_proxy,envoy.filters.http.grpc_http1_reverse_bridge,envoy.filters.http.grpc_stats,envoy.filters.http.header_to_metadata,envoy.filters.http.jwt_authn,envoy.filters.http.original_src,envoy.filters.http.rbac,envoy.filters.http.tap,envoy.grpc_http1_bridge,envoy.grpc_json_transcoder,envoy.grpc_web,envoy.gzip,envoy.health_check,envoy.http_dynamo_filter,envoy.ip_tagging,envoy.lua,envoy.rate_limit,envoy.router,envoy.squash
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:259]   filters.listener: envoy.listener.http_inspector,envoy.listener.original_dst,envoy.listener.original_src,envoy.listener.proxy_protocol,envoy.listener.tls_inspector
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:262]   filters.network: envoy.client_ssl_auth,envoy.echo,envoy.ext_authz,envoy.filters.network.dubbo_proxy,envoy.filters.network.mysql_proxy,envoy.filters.network.rbac,envoy.filters.network.sni_cluster,envoy.filters.network.thrift_proxy,envoy.filters.network.zookeeper_proxy,envoy.http_connection_manager,envoy.mongo_proxy,envoy.ratelimit,envoy.redis_proxy,envoy.tcp_proxy
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:264]   stat_sinks: envoy.dog_statsd,envoy.metrics_service,envoy.stat_sinks.hystrix,envoy.statsd
[2020-01-28 11:09:07.343][190523][info][main] [external/envoy/source/server/server.cc:266]   tracers: envoy.dynamic.ot,envoy.lightstep,envoy.tracers.datadog,envoy.tracers.opencensus,envoy.tracers.xray,envoy.zipkin
[2020-01-28 11:09:07.344][190523][info][main] [external/envoy/source/server/server.cc:269]   transport_sockets.downstream: envoy.transport_sockets.alts,envoy.transport_sockets.raw_buffer,envoy.transport_sockets.tap,envoy.transport_sockets.tls,raw_buffer,tls
[2020-01-28 11:09:07.344][190523][info][main] [external/envoy/source/server/server.cc:272]   transport_sockets.upstream: envoy.transport_sockets.alts,envoy.transport_sockets.raw_buffer,envoy.transport_sockets.tap,envoy.transport_sockets.tls,raw_buffer,tls
[2020-01-28 11:09:07.344][190523][info][main] [external/envoy/source/server/server.cc:278] buffer implementation: new
[2020-01-28 11:09:07.369][190523][critical][main] [external/envoy/source/server/server.cc:95] error initializing configuration 'envoy.yaml': Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[1]) per_connection_buffer_limit_bytes: Cannot find field.) has unknown fields
[2020-01-28 11:09:07.369][190523][info][main] [external/envoy/source/server/server.cc:594] exiting
[2020-01-28 11:09:07.369][190523][debug][init] [external/envoy/source/common/init/watcher_impl.cc:27] init manager Server destroyed
Protobuf message (type envoy.config.bootstrap.v2.Bootstrap reason INVALID_ARGUMENT:(route_config.virtual_hosts[1]) per_connection_buffer_limit_bytes: Cannot find field.) has unknown fields

*Config*:
`node:
  id: id_1
  cluster: test
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: http_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9090
    listener_filters:
    filter_chains:
    - filter_chain_match:
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          upgrade_configs:
          - upgrade_type: websocket
          stat_prefix: ingress_http
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: app-auth
              domains:
              - localhost:8080
              routes:
              - match:
                  prefix: /
                route:
                  cluster: app-auth
              cors:
                allow_origin:
                - '*'
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: '1728000'
                expose_headers: custom-header-1,grpc-status,grpc-message
                filter_enabled:
                  default_value:
                    numerator: 1
                    denominator: HUNDRED
                  runtime_key: 100%
              gzip:
                filter_enabled:
              per_connection_buffer_limit_bytes: 1024  
          http_filters:
          - name: envoy.cors
          - name: envoy.grpc_web
          - name: envoy.gzip
          - name: envoy.router
  clusters:
  - name: app-auth
    connect_timeout: 15.00s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: app-auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: keycloak-test
                port_value: 8080`

**Comment by yanavlasov** [comment]
@Vinutha-Garimella thanks for posting the issue. Could you post the config .yaml file you use, please? It is hard to figure out the formatting and indentation from the original post. You can place between use the 
` ```YAML `
`<Your config content> `
` ``` `
to make it formatted correctly.

From what I see though it looks like a syntax error your config. The [VirtualHost](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-virtualhost) message does not have the `per_connection_buffer_limit_bytes` field. It has `per_request_buffer_limit_bytes`
It is hard to read but are specifying `gzip` under `VirtualHost` as well? if so it is an error as well.

**Comment by Vinutha-Garimella** [comment]
@yanavlasov  here is my envoy.yaml file, I have configured `gzip and per_connection_buffer_limit_bytes` under the indentation of cors
```YAML
#  This allows the Envoy node to be identified, potentially allowing for unique configurations to be applied.
node:
  id: id_1
  cluster: testing
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
  - name: http_listener
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9090
    listener_filters:
    filter_chains:
    - filter_chain_match:
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          upgrade_configs:
          - upgrade_type: websocket
          stat_prefix: ingress_http
          use_remote_address: true
          route_config:
            name: local_route
            virtual_hosts:
            - name: app-auth
              domains:
              - localhost:8080
              routes:
              - match:
                  prefix: /
                route:
                  cluster: app-auth
              cors:
                allow_origin:
                - '*'
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: '1728000'
                expose_headers: custom-header-1,grpc-status,grpc-message
                filter_enabled:
                  default_value:
                    numerator: 1
                    denominator: HUNDRED
                  runtime_key: 100%
            - name: jwt-tester
              domains:
              - localhost:9090
              routes:
              - match:
                  prefix: /
                route:
                  cluster: ui-integration
              cors:
                allow_origin:
                - '*'
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                max_age: '1728000'
                expose_headers: custom-header-1,grpc-status,grpc-message
                filter_enabled:
                  default_value:
                    numerator: 0
                    denominator: HUNDRED
              gzip:
                filter_enabled:
              per_connection_buffer_limit_bytes: 1024  
          http_filters:
          - name: envoy.cors
          - name: envoy.grpc_web
          - name: envoy.gzip
          - name: envoy.router
  clusters:
  - name: app-auth
    connect_timeout: 15.00s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: app-auth
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: keycloak-test
                port_value: 8080
  - name: ui-integration
    connect_timeout: 0.25s
    type: STATIC
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: ui-integration
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 8000

```

**Comment by Vinutha-Garimella** [comment]
@yanavlasov  I understood the error for `per_connection_buffer_limit_bytes: 1024 ` I'll change this configuration, you said that `gzip.filter_enabled` should not be under virtual hosts can you please let me know where to add this filed.

**Comment by yanavlasov** [comment]
You provide filter configuration in the `http_filters` section, like this:
```YAML
          http_filters:
          - name: envoy.cors
          - name: envoy.grpc_web
          - name: envoy.gzip
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.gzip.v2.Gzip
              memory_level: 3
              window_bits: 10
              compression_level: best
              compression_strategy: rle
              content_length: 100
              content_type:
                - text/html
                - application/json
              disable_on_etag_header: true              
          - name: envoy.router
```
See [gzip config options](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/gzip/v2/gzip.proto)
