### ISSUE TITLE
GRPC-JSON transcoder is ignoring ext_authz filter

### ISSUE THREAD

**Issue by ShanePadellaro** [envoyproxy/envoy#9869]
We have successfully configured the GRPC-JSON transcoder filter and transcoding seems to be working. But for some reason transcoded calls (JSON to grpc) is skipping the Ext authz filter.

In short:

GRPC call's hit the external auth service, but Json calls do not and are routed directly to the service.

This is the test config we are using:

```yaml
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }         #1

static_resources:
  listeners:
  - name: main-listener
    address:
      socket_address: { address: 0.0.0.0, port_value: 51051 }      #2
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: grpc_json
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/billing" , grpc: {}}  # 3a grpc:{} means that requests are only forwarded if they are found in the grpc service definition, returning 404 for others
                route: { cluster: billsby-billing, timeout: { seconds: 60 } }   #3b
              - match: { prefix: "/test" , grpc: {}}  # 3a grpc:{} means that requests are only forwarded if they are found in the grpc service definition, returning 404 for others
                route: { cluster: billsby-webhooks, timeout: { seconds: 60 } }
              - match: { prefix: "/api/" }  # 3a grpc:{} means that requests are only forwarded if they are found in the grpc service definition, returning 404 for others
                route: {prefix_rewrite: "/",cluster: google, timeout: { seconds: 60 } }   #3b
          http_filters:
          - name: envoy.grpc_json_transcoder
            # configuration docs: https://github.com/envoyproxy/envoy/blob/master/api/envoy/config/filter/http/transcoder/v2/transcoder.proto
            config:
              proto_descriptor: "/etc/envoy/proto.pb"             #4
              services: ["billing.private.customer.CustomerService"]                        #5
              print_options:
                add_whitespace: true
                always_print_primitive_fields: true
                always_print_enums_as_ints: false
                preserve_proto_field_names: false
              convert_grpc_status: true                                     #6
          - name: envoy.ext_authz
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.ext_authz.v2.ExtAuthz
              http_service:
                server_uri:
                  uri: localhost
                  cluster: ext-authz
                  timeout: 2.0s
                path_prefix: /public
                authorization_request:
                  allowed_headers: 
                    patterns: 
                    - exact: authorization
                    - exact: apikey
                authorization_response:
                  allowed_upstream_headers: 
                    patterns: 
                    - exact: authorization
                    - exact: apikey
          - name: envoy.router

  clusters:
  - name: billsby-billing                  #7
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: billsby-billing                       #8
        port_value: 50051
  - name: billsby-webhooks                  #7
    connect_timeout: 1.25s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: billsby-webhooks                       #8
        port_value: 50051
  - name: google                  #7
    connect_timeout: 10s
    type: logical_dns
    lb_policy: round_robin
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    hosts:
    - socket_address:
        address: billsby-api                       #8
        port_value: 80
  - name: ext-authz
    connect_timeout: 0.25s
    type: logical_dns
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: ambassador-auth
        port_value: 8080
```
