### ISSUE TITLE
Too many Host headers caused via lua headers():add(":a","value")

### ISSUE THREAD

**Issue by jusmaki** [envoyproxy/envoy#9937]
*Description*:

The lua filters makes it possible to add headers which are available
only for access logs by adding ':' character to them. However if this
kind of "hidden" header starts with ":a" it is used as ":authority"
and this causes multiple "host" headers to appear with HTTP/1.X
requests. This in turns causes error with at least golang based http server:
"HTTP/1.1 400 Bad Request: too many Host headers".

With the envoy virtual hosts routes config it is not possible to
modify the ":" prefixed headers but it's nicely possible via lua api.

The use of ":" started headers via lua api may be an unplanned feature
but it makes it possible to have these hidden/log-only headers like
the Nginx supports via variables. These variables/hidden headers are
very convenient especially when using external authorizers or other
external subrequests where one needs to log the subrequest result
headers as part of access logs but not pass all of them to the
upstream.

*Proposed fix*:

Envoy should copy only the ":authority" header as HTTP/1.X "host" header and not all of the ":a*" headers.

*Proposed new feature*:

Add documented support for using hidden/access-log only headers.

*Repro steps*:
- Use the configuration below
- Have upstream server ready (written in go), or some other server but verify headers with tcpdump.
- make a request to the envoy
- notice that the server returns 400 error (you can verify the issue by using tcpdump to capture the traffic).

*Config*:

```
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8081
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          codec_type: auto
          stat_prefix: proxy_http
          http_protocol_options:
            accept_http_10: true
          #Disabled delayed close for the http/1.0 (and all other...)
          delayed_close_timeout: 0.0s
          access_log:
          - name: envoy.file_access_log
            typed_config:
              "@type": type.googleapis.com/envoy.config.accesslog.v2.FileAccessLog
              path: /var/log/envoy/envoy-access.log
              format: "[%START_TIME%] \
                       host=\"%REQ(:AUTHORITY)%\" \
                       m=\"%REQ(:METHOD)%\" \
                       st=\"%RESPONSE_CODE%\" \
                       ahidden=\"%REQ(:AHIDDEN)%\" \
                       bhidden=\"%REQ(:BHIDDEN)%\" \
                       \"\n"
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  path: /envoy-status
                direct_response:
                  status: 200
                  body:
                    inline_string: OK
              - match:
                  prefix: /
                route:
                  cluster: upstream
          http_filters:
          - name: envoy.lua
            typed_config:
              "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
              #################################################################
              inline_code: |
                function envoy_on_request(handle)
                     -- testing request header modifications,
                     -- adding a "hidden" log only header starting with ":a" will be used
                     -- as ":authority" causing "HTTP/1.1 400 Bad Request: too many Host headers" error
                     -- Example headers caused by this example:
                     --     host: localhost:8081
                     --     host: a-value
                     handle:headers():replace(":ahidden", "a-value")
                     handle:headers():replace(":bhidden", "b-value")
                end 
              ##########################################################
          - name: envoy.router
            typed_config: {}
  clusters:
  - name: upstream
    connect_timeout: 0.25s
    type: strict_dns
    lb_policy: round_robin
    load_assignment:
      cluster_name: upstream
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: upstream
                port_value: 9090
### LISTENER FOR ADMIN API
admin:
  access_log_path: "/var/log/envoy/envoy-admin.log"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 8001

```
