### ISSUE TITLE
Feature request: Consistent hashing on value other than address

### ISSUE THREAD

**Issue by mattrobenolt** [envoyproxy/envoy#9968]
Given a config similar to this:

```yaml
static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: thing
          route_config:
            name: local
            virtual_hosts:
            - name: service
              domains:
              - "*"
              routes:
              - match:
                  prefix: /
                route:
                  cluster: peers
                  hash_policy:
                    header:
                      header_name: some-header
          http_filters:
          - name: envoy.router
  clusters:
  - name: peers
    type: STRICT_DNS
    dns_lookup_family: V4_ONLY
    dns_refresh_rate: 5s
    lb_policy: MAGLEV
    connect_timeout: 0.5s
    load_assignment:
      cluster_name: peers
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: foo.default.svc.cluster.local
                port_value: 8080
```

It's impossible to actually achieve consistent hashing around the `peers` cluster with the defined `hash_policy` as instances come and go. This specific example is using pointing at a StatefulSet in Kubernetes.

What that means, is we have a DNS record of `foo.default.svc.cluster.local` which is a CNAME for `foo-{0..N}.foo.default.svc.cluster.local`.

In Kubernetes, a StatefulSet is guaranteed to have the same hostnames, but they'll obviously get different IP addresses for each Pod.

Routing and hashing within the `cluster` is determined by the ultimate address of the server (the ip:port) pairs.

Even if we didn't use DNS for discovery, and we introduce a hardcoded list of `endpoint` records that point the individual hostnames, hashing is still broken as soon as the IP changes.

I'm not sure exactly how we can work around this in envoy infrastructure, but ideally, there'd be some option to choose how to determine the hash. In my case, ideally I'd use the hostname, not the IP:port. Alternately, adding a `name` field to each endpoint would be useful if you spell out exactly what the hosts are. This obviously breaks the ability to do service discovery.

Through every measure I can find, there's no way to accomplish consistent hashing while leveraging any form of service discovery, unfortunately.

Am I missing something, or does the feature request make sense?
