### ISSUE TITLE
config.filter.http.ext_authz.v2.AuthorizationRequest headers_to_add not doing interpolation

### ISSUE THREAD

**Issue by mikebryant** [envoyproxy/envoy#9980]
**Bug Template**

*Title*: *headers_to_add not doing interpolation*

*Description*:
I'm trying to use ext_authz with oauth2-proxy under istio. 

[these docs](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/ext_authz/v2/ext_authz.proto#envoy-api-msg-config-filter-http-ext-authz-v2-authorizationrequest) point to [this doc](https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/base.proto#envoy-api-msg-core-headervalue) which states `The same format specifier as used for HTTP access logging applies here, however unknown header values are replaced with the empty string instead of -.`

However, what gets sent is:
```
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][trace][filter] [external/envoy/source/extensions/filters/http/ext_authz/ext_authz.cc:80] [C1704][S12786298896255907122] ext_authz filter calling authorization server
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][debug][router] [external/envoy/source/common/router/router.cc:434] [C0][S17990863836512223039] cluster 'outbound|80||oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local' match for URL '/qfqf'
[Envoy (Epoch 0)] [2020-02-09 02:19:18.510][39][debug][router] [external/envoy/source/common/router/router.cc:549] [C0][S17990863836512223039] router decoding headers:
':authority', 'kubernetes-dashboard.home.mikebryant.me.uk'
':method', 'GET'
':path', '/qfqf'
':scheme', 'https'
'content-length', '0'
'x-auth-request-redirect', '%REQ(:SCHEME)://%REQ(:AUTHORITY)%/%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
'x-envoy-internal', 'true'
'x-forwarded-for', '10.244.128.46'
'x-envoy-expected-rq-timeout-ms', '5000'
```

Note the header sent to the authorization service hasn't been interpolated / formatted

*Repro steps*:
Use this config - the important part is to try and use format strings in the headers
```
        name: "envoy.ext_authz"
        config:
          failure_mode_allow: false
          http_service:
            authorization_request:
              allowed_headers:
                patterns:
                - exact: Authorization
                - exact: Cookie
              headers_to_add:
              - key: X-Auth-Request-Redirect
                value: "%REQ(:SCHEME)://%REQ(:AUTHORITY)%/%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
            server_uri:
              cluster: outbound|80||oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local
              uri: http://oauth2-proxy-oauth2-proxy.oauth2-proxy.svc.cluster.local
              timeout: 5.000s
```

>**Note**: The [Envoy_collect tool](https://github.com/envoyproxy/envoy/blob/master/tools/envoy_collect/README.md)
gathers a tarball with debug logs, config and the following admin
endpoints: /stats, /clusters and /server_info. Please note if there are
privacy concerns, sanitize the data prior to sharing the tarball/pasting.

*Admin and Stats Output*:
>Include the admin output for the following endpoints: /stats,
/clusters, /routes, /server_info. For more information, refer to the
[admin endpoint documentation.](https://www.envoyproxy.io/docs/envoy/latest/operations/admin)

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Config*:
>Include the config used to configure Envoy.

*Logs*:
>Include the access logs and the Envoy logs.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.
